# Two-sample inference

```{r 05-two-sample-inference-1, eval=F}
library(tidyverse)
```

```{r 05-two-sample-inference-2, child="packages.Rmd"}
```


```{r 05-two-sample-inference-3, child="devices-r_qq.Rmd"}
```

```{r 05-two-sample-inference-4, child="parking_qq.Rmd"}
```

```{r 05-two-sample-inference-5, child="bellpepper_qq.Rmd"}
```

```{r 05-two-sample-inference-6, child="mousebully_qq.Rmd"}
```

```{r 05-two-sample-inference-7, child="kids-diet_qq.Rmd"}
```

```{r 05-two-sample-inference-8, child="handspan_qq.Rmd"}
```

```{r 05-two-sample-inference-9, child="ozvus_qq.Rmd"}
```

My solutions follow:

```{r 05-two-sample-inference-10, child="devices-r.Rmd"}
```

```{r 05-two-sample-inference-11, child="parking.Rmd"}
```

```{r 05-two-sample-inference-12, child="bellpepper.Rmd"}
```

```{r 05-two-sample-inference-13, child="mousebully.Rmd"}
```

```{r 05-two-sample-inference-14, child="kids-diet.Rmd"}
```

```{r 05-two-sample-inference-15, child="handspan.Rmd"}
```

```{r 05-two-sample-inference-16, child="ozvus.Rmd"}
```

