# Matched pairs t and sign test

```{r 08-matched-pairs-sign-1, eval=F}
library(tidyverse)
library(smmr)
```

```{r 08-matched-pairs-sign-2, child="packages.Rmd"}
```


```{r 08-matched-pairs-sign-3, child="bodyfat_qq.Rmd"}
```

```{r 08-matched-pairs-sign-4, child="baseball-softball-r_qq.Rmd"}
```

```{r 08-matched-pairs-sign-5, child="throw_qq.Rmd"}
```


```{r 08-matched-pairs-sign-6, child="salaryinc_qq.Rmd"}
```

```{r 08-matched-pairs-sign-7, child="bodyfat-sign_qq.Rmd"}
```

```{r 08-matched-pairs-sign-8, child="blood_pressure_paired_qq.Rmd"}
```

```{r 08-matched-pairs-sign-9, child="french_qq.Rmd"}
```

My solutions follow:


```{r 08-matched-pairs-sign-10, child="bodyfat.Rmd"}
```

```{r 08-matched-pairs-sign-11, child="baseball-softball-r.Rmd"}
```

```{r 08-matched-pairs-sign-12, child="throw.Rmd"}
```


```{r 08-matched-pairs-sign-13, child="salaryinc.Rmd"}
```

```{r 08-matched-pairs-sign-14, child="bodyfat-sign.Rmd"}
```

```{r 08-matched-pairs-sign-15, child="blood_pressure_paired.Rmd"}
```

```{r 08-matched-pairs-sign-16, child="french.Rmd"}
```

