# Analysis of variance

```{r 10-analysis-of-variance-1, eval=F}
library(tidyverse)
```

```{r 10-analysis-of-variance-2, child="packages.Rmd"}
```


```{r 10-analysis-of-variance-3, child="movies-r_qq.Rmd"}
```

```{r 10-analysis-of-variance-4, child="deer_qq.Rmd"}
```

```{r 10-analysis-of-variance-5, child="movies2_qq.Rmd"}
```

```{r 10-analysis-of-variance-6, child="carbon_qq.Rmd"}
```

```{r 10-analysis-of-variance-7, child="caffeine_qq.Rmd"}
```

```{r 10-analysis-of-variance-8, child="reggae_qq.Rmd"}
```

```{r 10-analysis-of-variance-9, child="gss_tv_qq.Rmd"}
```

```{r 10-analysis-of-variance-10, child="writers_qq.Rmd"}
```

```{r 10-analysis-of-variance-11, child="relig_qq.Rmd"}
```

My solutions follow:

```{r 10-analysis-of-variance-12, child="movies-r.Rmd"}
```

```{r 10-analysis-of-variance-13, child="deer.Rmd"}
```

```{r 10-analysis-of-variance-14, child="movies2.Rmd"}
```

```{r 10-analysis-of-variance-15, child="carbon.Rmd"}
```

```{r 10-analysis-of-variance-16, child="caffeine.Rmd"}
```

```{r 10-analysis-of-variance-17, child="reggae.Rmd"}
```

```{r 10-analysis-of-variance-18, child="gss_tv.Rmd"}
```

```{r 10-analysis-of-variance-19, child="writers.Rmd"}
```

```{r 10-analysis-of-variance-20, child="relig.Rmd"}
```

