# Tidying data

```{r 11-tidying-data-1, eval=F}
library(tidyverse)
```

```{r 11-tidying-data-2, child="packages.Rmd"}
```


```{r 11-tidying-data-3, child="throw-spaghetti_qq.Rmd"}
```

```{r 11-tidying-data-4, child="ethanol_qq.Rmd"}
```

```{r 11-tidying-data-5, child="tomatoes_qq.Rmd"}
```

```{r 11-tidying-data-6,child="migraine_qq.Rmd"}
```

```{r 11-tidying-data-7,child="plants_qq.Rmd"}
```

```{r 11-tidying-data-8,child="crickets_qq.Rmd"}
```



```{r 11-tidying-data-9, child="billboard_qq.Rmd"}
```

```{r 11-tidying-data-10, child="bikes_qq.Rmd"}
```

```{r 11-tidying-data-11, child="heat-r_qq.Rmd"}
```

```{r 11-tidying-data-12, child="isoflavones_qq.Rmd"}
```

```{r 11-tidying-data-13, child="jocko_qq.Rmd"}
```


```{r 11-tidying-data-14, child="util_temp_qq.Rmd"}
```

```{r 11-tidying-data-15, child="blood_pressure_tidy_qq.Rmd"}
```


My solutions follow:

```{r 11-tidying-data-16, child="throw-spaghetti.Rmd"}
```

```{r 11-tidying-data-17, child="ethanol.Rmd"}
```

```{r 11-tidying-data-18, child="tomatoes.Rmd"}
```

```{r 11-tidying-data-19,child="migraine.Rmd"}
```

```{r 11-tidying-data-20,child="plants.Rmd"}
```

```{r 11-tidying-data-21,child="crickets.Rmd"}
```



```{r 11-tidying-data-22, child="billboard.Rmd"}
```

```{r 11-tidying-data-23, child="bikes.Rmd"}
```

```{r 11-tidying-data-24, child="heat-r.Rmd"}
```

```{r 11-tidying-data-25, child="isoflavones.Rmd"}
```

```{r 11-tidying-data-26, child="jocko.Rmd"}
```

```{r 11-tidying-data-27, child="util_temp.Rmd"}
```

```{r 11-tidying-data-28, child="blood_pressure_tidy.Rmd"}
```

