# Regression

```{r 12-multiple-regression-1, eval=F}
library(tidyverse)
```

```{r 12-multiple-regression-2, child="packages.Rmd"}
```

These problems are about simple regression (just one $x$-variable):



```{r 12-multiple-regression-3,child="calirain.Rmd"}
```

```{r 12-multiple-regression-4,child="ftccigar.Rmd"}
```


```{r 12-multiple-regression-5, child="youngboys.Rmd"}
```



```{r 12-multiple-regression-6, child="fbfriends.Rmd"}
```

```{r 12-multiple-regression-7, child="carp.Rmd"}
```



```{r 12-multiple-regression-8, child="socwork.Rmd"}
```

```{r 12-multiple-regression-9, child="pinetrees.Rmd"}
```

```{r 12-multiple-regression-10, child="tortoise.Rmd"}
```

```{r 12-multiple-regression-11, child="crickets-b.Rmd"}
```

```{r 12-multiple-regression-12, child="coasters.Rmd"}
```

```{r 12-multiple-regression-13, child="diabetic.Rmd"}
```

```{r 12-multiple-regression-14, child="pizza.Rmd"}
```

```{r 12-multiple-regression-15, child="fire_damage.Rmd"}
```

These problems are about multiple regression (more than one $x$-variable):


```{r 12-multiple-regression-16, child="hospital.Rmd"}
```

```{r 12-multiple-regression-17, child="chemical.Rmd"}
```

```{r 12-multiple-regression-18, child="mathsal.Rmd"}
```

```{r 12-multiple-regression-19, child="gpa.Rmd"}
```

