# Simple regression

```{r 12-simple-regression-1, eval=F}
library(tidyverse)
```

```{r 12-simple-regression-2, child="packages.Rmd"}
```


```{r 12-simple-regression-3,child="calirain_qq.Rmd"}
```

```{r 12-simple-regression-4,child="ftccigar_qq.Rmd"}
```


```{r 12-simple-regression-5, child="youngboys_qq.Rmd"}
```



```{r 12-simple-regression-6, child="fbfriends_qq.Rmd"}
```

```{r 12-simple-regression-7, child="carp_qq.Rmd"}
```



```{r 12-simple-regression-8, child="socwork_qq.Rmd"}
```

```{r 12-simple-regression-9, child="pinetrees_qq.Rmd"}
```

```{r 12-simple-regression-10, child="tortoise_qq.Rmd"}
```


```{r 12-simple-regression-11, child="coasters_qq.Rmd"}
```

```{r 12-simple-regression-12, child="diabetic_qq.Rmd"}
```

```{r 12-simple-regression-13, child="pizza_qq.Rmd"}
```

```{r 12-simple-regression-14, child="fire_damage_qq.Rmd"}
```


```{r 12-simple-regression-15, child="braking_qq.Rmd"}
```

```{r 12-simple-regression-16, child="heightfoot_qq.Rmd"}
```


My solutions follow:

```{r 12-simple-regression-17,child="calirain.Rmd"}
```

```{r 12-simple-regression-18,child="ftccigar.Rmd"}
```


```{r 12-simple-regression-19, child="youngboys.Rmd"}
```



```{r 12-simple-regression-20, child="fbfriends.Rmd"}
```

```{r 12-simple-regression-21, child="carp.Rmd"}
```



```{r 12-simple-regression-22, child="socwork.Rmd"}
```

```{r 12-simple-regression-23, child="pinetrees.Rmd"}
```

```{r 12-simple-regression-24, child="tortoise.Rmd"}
```


```{r 12-simple-regression-25, child="coasters.Rmd"}
```

```{r 12-simple-regression-26, child="diabetic.Rmd"}
```

```{r 12-simple-regression-27, child="pizza.Rmd"}
```

```{r 12-simple-regression-28, child="fire_damage.Rmd"}
```

```{r 12-simple-regression-29, child="braking.Rmd"}
```

```{r 12-simple-regression-30, child="heightfoot.Rmd"}
```

