# Logistic regression

```{r 15-logistic-regression-1, eval=F}
library(tidyverse)
```

```{r 15-logistic-regression-2, child="packages.Rmd"}
```


```{r 15-logistic-regression-3, wolfspider,child="wolfspider_qq.Rmd"}
```

```{r 15-logistic-regression-4, aphids, child="aphids_qq.Rmd"}
```

```{r 15-logistic-regression-5, doseresponse, child="doseresponse_qq.Rmd"}
```

```{r 15-logistic-regression-6, parasite, child="parasite_qq.Rmd"}
```

```{r 15-logistic-regression-7, ethics, child="ethics_qq.Rmd"}
```

```{r 15-logistic-regression-8, heart,  child="heart_qq.Rmd"}
```

```{r 15-logistic-regression-9, breastfeed, child="breastfeed_qq.Rmd"}
```

```{r 15-logistic-regression-10, donner, child="donner_qq.Rmd"}
```

```{r 15-logistic-regression-11, apache, child="apache_qq.Rmd"}
```

```{r 15-logistic-regression-12, ha2, child="ha2_qq.Rmd"}
```

My solutions follow:

```{r 15-logistic-regression-13, wolfspider,child="wolfspider.Rmd"}
```

```{r 15-logistic-regression-14, aphids, child="aphids.Rmd"}
```

```{r 15-logistic-regression-15, doseresponse, child="doseresponse.Rmd"}
```

```{r 15-logistic-regression-16, parasite, child="parasite.Rmd"}
```

```{r 15-logistic-regression-17, ethics, child="ethics.Rmd"}
```

```{r 15-logistic-regression-18, heart,  child="heart.Rmd"}
```

```{r 15-logistic-regression-19, breastfeed, child="breastfeed.Rmd"}
```

```{r 15-logistic-regression-20, donner, child="donner.Rmd"}
```

```{r 15-logistic-regression-21, apache, child="apache.Rmd"}
```

```{r 15-logistic-regression-22, ha2, child="ha2.Rmd"}
```

