project:
  type: book

book:
  title: "Problems and Solutions in Applied Statistics (2nd ed)"
  author: "Ken Butler"
  date: "2023-05-23"
  chapters:
    - index.qmd
    - getting_used.qmd
    - reading-in.Rmd
    - making-graphs.Rmd
    - data-summaries.Rmd
    - working-with-dataframes.Rmd
    - one-sample-inference.Rmd
    - two-sample-inference.Rmd
    - power.Rmd
    - sign.Rmd
    - mood-median.Rmd
    - matched-pairs-sign.Rmd
    - normal-quantile.Rmd
    - analysis-of-variance.Rmd
    - reports.Rmd
    - coding.Rmd
    - dandruff.Rmd
    - tidying-data.Rmd
    - simple-regression.Rmd
    - multiple-regression.Rmd
    - regression-categorical.Rmd
    - dates-and-times.Rmd
    - functions.Rmd
    - vector-matrix.Rmd
    - bootstrap.Rmd
    - stan.Rmd
    - logistic-regression.Rmd
    - ordinal-response.Rmd
    - nominal-response.Rmd
    - survival-analysis.Rmd
    - anova-revisited.Rmd
    - ancova.Rmd
    - manova.Rmd
    - repeated-measures.Rmd
    - discriminant-analysis.Rmd
    - cluster.Rmd
    - kmeans-cluster.Rmd
    - maps.Rmd
    - mds.Rmd
    - pc.Rmd
    - fa.Rmd
    - loglin.Rmd
format:
  html:
    theme: cosmo
    df-print: paged
  pdf:
    documentclass: scrreprt



