## Learning algebra

 At a high  school in New Jersey, teachers were interested in what might help students to learn algebra. One idea was laptops as a learning aid, to see whether having access to one helped with algebra scores. (This was some time ago.) The 20 students in one class were given laptops to use in school and at home, while the 27 students in another class were not given laptops. For all of these students, the final exam score in algebra was recorded. The data are in [http://ritsokiguess.site/datafiles/algebra.txt](http://ritsokiguess.site/datafiles/algebra.txt), with two columns, one indicating whether the student received a laptop or not, and the other giving their score on the algebra final exam.



(a) Read in and display (some of) the data. Do you have (i) the correct number of observations, and (ii) the correct *type* of columns? Explain briefly.



(b) Make a suitable graph of these data.



(c) Comment briefly on your graph, thinking about what the teachers would like to know.



(d) Work out the median and  inter-quartile range for the students who did and who did not have laptops, and compare with the boxplot. (In R, the inter-quartile range is `IQR` in uppercase.)



