## Tidy blood pressure

 Going to the dentist is scary for a lot of people. One way in which this might show up is that people might have higher blood pressure on average before their dentist's appointment than an hour after the appointment is done. Ten randomly-chosen individuals have their (systolic^[A blood pressure is usually given as two numbers, like "120 over 80". The first number, which is the one shown in our data, is called the systolic blood pressure. It is the pressure in the arteries when the heart is pumping. The second is called the diastolic blood pressure, and it is the pressure in the arteries when the heart is resting.])  blood pressure measured while they are in a dentist's waiting room, and then again one hour after their appointment is finished.

You might have seen a tidy version of this data set before.

The data as I originally received it is in [http://ritsokiguess.site/datafiles/blood_pressure2.csv](http://ritsokiguess.site/datafiles/blood_pressure2.csv).



(a) Read in and display the data as originally received.



(b) Describe briefly how the data you read in is not tidy, bearing in mind how the data were collected and how they would be analysed.



(c) Produce a tidy dataframe from the one you read in from the file. (How many rows should you have?)



(d) What kind of test might you run on these data? Explain briefly.



(e) Draw a suitable graph of these data.





