## The dentist and blood pressure

 Going to the dentist is scary for a lot of people. One way in which this might show up is that people might have higher blood pressure on average before their dentist's appointment than an hour after the appointment is done. Ten randomly-chosen individuals have their (systolic) blood pressure measured while they are in a dentist's waiting room, and then again one hour after their appointment is finished.

The data are in [http://ritsokiguess.site/datafiles/blood_pressure1.csv](http://ritsokiguess.site/datafiles/blood_pressure1.csv).


(a) Read in and display the data.



(b) What kind of experimental design is this? How do you know? Explain briefly.



(c) Run a suitable $t$-test on these data. What do you conclude, in the context of the data?



(d) Run a suitable sign test on these data. What do you conclude, in the context of the data?



(e) Draw a suitable normal quantile plot of these data, one that will enable you to decide between the tests you ran in the previous two parts.



(f) Discuss briefly which of your two tests is the more appropriate one to run.






