##  Air conditioning failures


 Back in 1963, there was a report on failures in
air-conditioning equipment in
\href{https://en.wikipedia.org/wiki/Boeing_720}{Boeing 720}
aircraft. For one aircraft, the air-conditioning equipment failed 12
times, and the number of hours it ran before failing each time was
recorded. The data are in
[link](https://raw.githubusercontent.com/nxskok/pasias/master/air_conditioning.csv). Boeing
was interested in the mean failure time, because the company wanted to
plan for engineers to fix the failures (and thus needed to estimate a
failure *rate*).

There is randomization here. Your answers will differ slightly from
mine, unless you throw in this before you start (or at least before
you generate your first random numbers).

```{r }
set.seed(457299)
```

 



(a) Read in the data, and observe that you have the correct number
of rows. (Note that the failure times are in ascending order).


(b) What do you notice about the *shape* of the distribution of failure times? Explain briefly.


(c) Obtain the means of 1000 bootstrap samples (that is, samples from the data with replacement). Save them.


(d) Make a normal quantile plot of your bootstrap distribution. What do you see? Explain briefly.


(e) Obtain the 95\% bootstrap percentile confidence interval for the mean.


(f) Obtain the 95\% bootstrap-$t$ confidence interval for
the mean, and compare your two intervals.


(g) Obtain the BCa 95\% confidence interval for the mean.


(h) Compare the BCa confidence interval with the other ones. Which one would you recommend? Explain briefly.




