
## Making it stop

 If you are driving, and you hit the brakes, how far do you travel before coming to a complete stop? 
Presumably this depends on how fast you are going. 
Knowing this relationship is important in setting speed limits on roads. For example, on a very bendy road, the speed limit needs to be low, because you cannot see very far ahead, and there could be something just
out of sight that you need to stop for. 

Data were collected for a typical car and driver, as shown in \url{http://ritsokiguess.site/datafiles/stopping.csv}. These are American data, so the speeds are miles per hour and the stopping distances are in feet.



(a) Read in and display (probably all of) the data.



(b) Make a suitable plot of the data.



(c) Describe any trend you see in your graph.



(d) Fit a linear regression predicting stopping distance from speed. (You might have some misgivings about doing this, but do it anyway.)



(e) Plot the residuals against the fitted values for this regression.



(f) What do you learn from the residual plot? Does that surprise you? Explain briefly. 



(g) What is the actual relationship between stopping distance and speed, according to the physics? See if you can find out. Cite any books or websites that you use: that is, include a link to a website, or give enough information about a book that the grader could find it.



(h) Fit the relationship that your research indicated (in the previous part) and display the results. Comment briefly on the R-squared value.





(i) Somebody says to you "if you have a regression with a high R-squared, like 95%, there is no need to look for a better model." How do you respond to this? Explain briefly.







