## One-sample cholesterol

 The data set at
\url{http://ritsokiguess.site/datafiles/cholest.csv} contains cholesterol
measurements for heart attack patients (at several different times) as
well as for a group of control patients. We will focus on the control
patients in this question. 


(a) Read in and display (some of) the data.



(b) Make a suitable plot of the cholesterol levels of the
control patients, and comment briefly on the shape of the
distribution. 



(c) It is recommended that people in good health, such as the
Control patients here, keep their cholesterol level below 200. Is
there evidence that the mean cholesterol level of the population of
people of which the Control patients are a sample is less than 200? Show that you understand the process,
and state your conclusion in the context of the data.



(d) What values could the population mean cholesterol level take? You
might need to get some more output to determine this.



(e) Explain briefly why you would be reasonably happy to trust
the $t$ procedures in this question. (There are two points you need
to make.)




