## Coefficient of Variation

 The coefficient of variation of a vector `x` is defined as the standard deviation of `x` divided by the mean of `x`. 



(a) Write a function called `cv` that calculates the coefficient of variation of its input and returns the result. You should use base R's functions that reliably compute the pieces that you need.



(b) Use your function to find the coefficient of variation of the set of integers 1 through 5.




(c) Define a vector as follows:

```{r cv-qq-1}
v <- c(-2.8, -1.8, -0.8, 1.2, 4.2)
```

What is its coefficient of variation, according to your function? Does this make sense? Why did this happen? Explain briefly.



(d) Most people only calculate a coefficient of variation if there are no negative numbers. Rewrite your function so that it gives an error if there are any negative numbers in the input, and test it with the vector `v` above. Hint: you might need to add `error=TRUE` to your chunk header to allow your document to preview/knit (inside the curly brackets at the top of the chunk, after a comma).





