## Dolphins

 Dolphins and other large marine mammals are at the top of the marine food chain, and so if there is any heavy metal pollution in the sea, it will find its way into the dolphins. The study we look at is of the concentration of mercury. This is expected to be different in males and females because the mercury in a female is transferred to her offspring during gestation and nursing. In this study, there were 28 males and 17 females of various ages. There are three columns in the data file:

- `mercury`, the concentration in the liver, in micrograms per gram
- `age` in years
- `sex` of the dolphin, male or female.

The data are in [http://ritsokiguess.site/datafiles/dolphins.csv](http://ritsokiguess.site/datafiles/dolphins.csv) as a CSV file. This question appears to have a lot of parts, but most of them ought not to take you too long.



(a) Read in and display (some of) the data.



(b) Display only the two columns `mercury` and `sex`.



(c) Display all the columns whose names have exactly three characters, without naming any columns.



(d) Display only the mercury levels for the females. 



(e) What is the mean mercury concentration for all the dolphins whose age is less than 15?



(f) What is the mean mercury concentration for all  the dolphins whose age is greater than 25?



(g) Make a suitable graph of these data (all three columns).



(h) Explain briefly how your graph and your calculations of mean mercury concentration are telling a similar story.





