## xxx title here

 Some students in a Statistics class were asked how many
minutes they typically exercised in a week. The data are shown in
\url{http://ritsokiguess.site/datafiles/exercise.txt}. 

Some of the
students identified as male and some as female. Our concern is how the males
and females compare in terms of the amount of exercise they do.


(a) Take a look at the data file. (Click on the link, or paste the copied link into your web browser.) How is it laid out?



(b) Read in and display (some of) the data. (This means to
display enough of what you read in to convince others that you read
in the right kind of thing.)



(c) Make a suitable plot of this data frame. 



(d) Does there appear to be any substantial difference in the
average amount of time that males and females spend exercising?
Explain briefly. ("average" could be mean or median. Which is it
here?)



(e) How do you know that both distributions, for males as well
as females, are skewed to the right? Explain (very) briefly.



(f) For data like this, why does it make practical sense that
the distributions are skewed to the right?






