## Comparing eyesight

 Do people see on average better with their left eye or their right eye, or is there no difference? To find out, 15 subjects were shown a sequence of images, some to their left eye and some to their right (with a blindfold on the other eye). The subjects were asked to identify some objects in each image, and were given an overall score for each eye, based on their ability to identify objects with each eye. (A higher score is better.) Data in \url{http://ritsokiguess.site/datafiles/eyesight.csv}.



(a) Read in and display (some of) the data.



(b) Explain briefly why looking at differences (say right minus left) makes sense for these data, and calculate and save a dataframe with the differences added to it.



(c) Make a suitable normal quantile plot, and describe what it tells you.



(d) Obtain a bootstrap distribution of the sample *median*.




(e) Make a histogram of your bootstrap distribution of the median. Use a lot of bins, such as the default 30, for this. What do you notice about the distribution? Why did it come out this way?



(f) Find a 95% percentile interval for the population median.^[I was also going to have you do a bootstrap-t interval, but I'm not completely convinced I got that right when I was explaining it to you before.]



(g) Find the BCA 95% confidence interval for the population median difference.



(h) What do your intervals tell us about any possible difference between left eye and right eye in terms of ability to identify objects in images? Do the intervals agree or disagree about this?




