## French teachers

 Twenty high-school French teachers attended a summer institute to improve their French skills. At the beginning of their session, each teacher took a listening test (to test their understanding of spoken French). After 4 weeks of immersion in French, each teacher took a similar listening test again. (The actual French spoken in the two tests was different, so simply taking the first test should not improve the score in the second one; the tests were otherwise similar.) The maximum score on each test was 36, and a higher score is better. The data are [here](http://ritsokiguess.site/datafiles/frenchtest.txt). (Right-click on the link, select "copy link address", and then paste that URL into R Studio.) The data values are separated by *tabs*.

The data file has three columns:

- an identification for each teacher
- the teacher's score in the first test
- the teacher's score in the second test



(a) Read in and display (some of) the data.



(b) Explain briefly why this is a matched-pairs study. 



(c) Run a suitable matched-pairs $t$-test to see whether the teachers' scores have on average *improved* over the four weeks.



(d) What do you conclude from your test, in the context of the data?



(e) How much is the teachers' listening skill improving, on average? Give a suitable interval to support your answer.



(f) Make a suitable plot to assess any assumptions for this test.



(g) Do you trust the result of your matched-pairs $t$-test? Explain briefly. 



(h) Run a suitable sign test, and obtain a suitable (95%) confidence interval. Comment briefly on your results.



(i) Comment briefly on the comparison between your inferences for the mean and the median. 





