
## Watching TV and education

 The General Social Survey is a large survey of a large number of people. One of the questions on the survey is "how many hours of TV do you watch in a typical day?" Another is "what is your highest level of education attained", on this scale:

- **HSorLess**: completed no more than high h school
- **College**: completed some form of college, either a community college (like Centennial) or a four-year university (like UTSC)
- **Graduate**: completed a graduate degree such as an MSc.

Do people with more education tend to watch more TV? We will be exploring this. The data are in [http://ritsokiguess.site/datafiles/gss_tv.csv](http://ritsokiguess.site/datafiles/gss_tv.csv).



(a) Read in and display (some of) the data.



(b) For each level of education, obtain the number of observations, the mean and the median of the number of hours of TV watched.



(c) What does your answer to the previous part tell you about the shapes of the distributions of the numbers of hours of TV watched? Explain briefly. 



(d) Obtain a suitable graph of your data frame.



(e) Does your plot indicate that your guess about the distribution shape was correct? Explain briefly.



(f) Run a suitable test to compare the average number of hours of TV watched for people with each amount of education. ("Average" could be mean or median, whichever you think is appropriate.)



(g) What do you conclude from your test, in the context of the data?



(h) Why might you now want to run some kind of follow-up test? Run the appropriate thing and explain briefly what you conclude from it, in the context of the data.








