# Handspans of males and females

 Take your right hand, and stretch the fingers out as far as
you can. The distance between the tip of your thumb and the tip of
your little (pinky) finger is your handspan. The students in a
Statistics class at Penn State measured their handspans and also
whether they identified as male or female. The data are at
\url{http://ritsokiguess.site/datafiles/handspan.txt}, with handspans
measured in inches.  Thinking of these as a random sample of all
possible students, is it true that males have a larger mean handspan
than females? This is what we will explore.


(a) Read in and display (some of) the data.



(b) Make a suitable graph of the two columns.



(c) Run a suitable two-sample $t$-test to address the question
of interest. What do you conclude, in the context of the data?



(d) Obtain a 90\% confidence interval for the difference
in mean handspan between males and females. Do you need to run
any more code? Explain briefly.



(e) Explain briefly why you might have some concerns about the
validity of the $t$-tests you ran in this question. Or, if you don't have any concerns, explain briefly why that is.





