## Handspans revisited

 Take your right hand, and stretch the fingers out as far as
you can. The distance between the tip of your thumb and the tip of
your little (pinky) finger is your handspan. The students in a
Statistics class at Penn State measured their handspans and also
whether they identified as male or female.  The data are at [http://ritsokiguess.site/datafiles/handspan.txt](http://ritsokiguess.site/datafiles/handspan.txt),
with handspans
measured in inches. We want to
see whether male students have a larger mean handspan than female students.


(a) Read in and display (some of) the data.



(b) Make a suitable (facetted) normal quantile plot of the data. (Bear in
mind what is supposed to have a normal distribution.)



(c) Discuss briefly whether you might prefer to use Mood's median
test to compare the handspans of the male and female students,
compared to a two-sample $t$-test.



(d) Run Mood's median test. What do you conclude from the test, in the context of the data?







