## Predicting height from foot length

 Is it possible to estimate the height of a person from the length of their foot? To find out, 33 (male) students had their height and foot length measured. The data are in 
[http://ritsokiguess.site/datafiles/heightfoot.csv](http://ritsokiguess.site/datafiles/heightfoot.csv).



(a) Read in and display (some of) the data. (If you are having trouble, make sure you have *exactly* the right URL. The correct URL has no spaces or other strange characters in it.)



(b) Make a suitable plot of the two variables in the data frame.



(c) Are there any observations not on the trend of the other points? What is unusual about those observations? 



(d) Fit a regression predicting height from foot length, *including* any observations that you identified in the previous part. For that regression, plot the residuals against the fitted values and make a normal quantile plot of the residuals.




(e) Earlier, you identified one or more observations that were off the trend. How does this point or points show up on each of the plots you drew in the previous part?



(f) Any data points that concerned you earlier were actually errors.
Create and save a new data frame that does not contain any of those data points. 



(g) Run a regression predicting height from foot length for your data set without errors. Obtain a plot of the residuals against fitted values and a normal quantile plot of the residuals for this regression.




(h) Do you see any problems on the plots you drew in the previous part? Explain briefly. 



(i) Find a way to plot the data and *both* regression lines on the same plot, in such a way that you can see which regression line is which. If you get help from anything outside the course materials, cite your source(s).



(j) Discuss briefly how removing the observation(s) that were errors has changed where the regression line goes, and whether that is what you expected.




