## Jocko's Garage

 Insurance adjusters are concerned that Jocko's Garage is giving estimates for repairing car damage that are too high. To see whether this is indeed the case, ten cars that had been in collisions were taken to both Jocko's Garage and another garage, and the two estimates for repair were recorded. The data as recorded are [here](http://ritsokiguess.site/datafiles/jocko.txt).



(a) Take a look at the data file (eg. by using your web browser). How are the data laid out? Do there appear to be column headers?



(b) Read in and display the data file, bearing in mind what you just concluded about it. What names did the columns acquire?



(c) Make this data set tidy. That is, you need to end up with columns containing the repair cost estimates at each of the two garages and also identifying the cars, with each observation on one row. Describe your thought process. (It needs to be possible for the reader to follow your description and understand why it works.)
Save your tidy dataframe.



(d) Make a suitable graph to assess the comparison of interest, and say briefly what your graph tells you.



(e) Carry  out a test to make an appropriate comparison of the mean estimates. What do you conclude, in the context of the data?






