## Fish and mercury

Eating fish is generally healthy, but sometimes the fish is contaminated with mercury. What might affect the amount of mercury in a fish? Large-mouth bass were studied in Florida lakes to examine factors that might affect the amount of mercury contamination. 38 lakes were used for the study. Water samples were taken from each lake and analyzed. Also, samples of fish were caught in each lake and the mercury concentration in their muscle tissue was measured. The resulting data are in [http://ritsokiguess.site/datafiles/mercury.txt](http://ritsokiguess.site/datafiles/mercury.txt), separated by single spaces. The variables measured were as follows:

-   standardized mercury level (parts per million in 3-year-old fish)
-   alkalinity of water (milligrams per litre)
-   calcium level of water (milligrams per litre)
-   pH of water (standard scale; see eg. [this](https://www.usgs.gov/special-topic/water-science-school/science/ph-and-water?qt-science_center_objects=0#qt-science_center_objects))



(a) Read in and display (some of) the data.



(b) Plot the mercury levels against each of the explanatory variables.



(c) Describe any trends (or lack thereof) that you see on your graphs.



(d) Concerned by some of what you see on your plots, you consult with a fisheries scientist, who says that using the logs of `alkalinity` and `calcium` are often used in modelling this kind of data. Add columns containing the logs of these two variables to your dataframe, and run a regression predicting `mercury` from `ph` and the two new variables. Display the output from your regression.



(e) What might you learn from running Box-Cox here? Explain briefly, then run it (on the same variables as your regression above) and describe what the results tell you.



(f) Using the results of the Box-Cox procedure and your previous work in the question, what seems to be the most appropriate regression now? Fit it, and display the results. 



(g) Obtain all the standard residual plots (the ones we have seen in this course) for this model. Describe any problems you see.



