## The anchoring effect: Australia vs US

 Two groups of students (in a class at a American university) were asked what they thought the population of Canada was. (The correct answer at the time was just over 30 million.)
Some of the students, before having to answer this, were told that the population of the United States was about 270 million. The other students in the class were told that the population of Australia was
about 18 million. The data are in \url{http://ritsokiguess.site/datafiles/anchoring.csv}. The first column contains the country whose population the student was told, and the second contains the student's guess at the population of Canada.

You might wonder how being told the population of an unrelated country would have any impact on a student's guess at the population of Canada. Psychology says it does: it's called the *anchoring effect*, and the idea is that the number mentioned first acts as an "anchor": a person's guess will be closer to the anchor than it would have been otherwise. In this case, that would mean that the guesses for the students given the
US as an anchor will be higher than for the students given Australia as an anchor. We are interested in seeing whether there is evidence for that here.




(a) Read in and display (some of)  the data.



(b) Draw a suitable graph of these data.



(c) Explain briefly why a Welch $t$-test would be better than a pooled $t$-test in this case.



(d) Run a suitable Welch $t$-test and display the output.



(e) What do you conclude from your test, in the context of the data?






