## Power and $\alpha$ in a skewed population

 A population of a large number of values `v` is at [http://ritsokiguess.site/datafiles/pop.csv](http://ritsokiguess.site/datafiles/pop.csv), in a CSV file. 



(a) Read in the population and display some of the values.




(b) Obtain a suitable plot of your population. What do you notice?



(c) If you take a sample of 10 observations from this population and run a $t$-test, how likely are you to (correctly) reject the null hypothesis $H_0: \mu = 4$, against the alternative $H_a: \mu > 4$? Investigate by simulation.





(d) Try again with a sample size of 50 (leaving everything else the same). Explain briefly why the results so far are as you'd expect.



(e) Again by simulation, estimate the probability that the null hypothesis $H_0: \mu=5$ will be rejected when a sample of size 10 is taken from this population, in favour of the alternative $H_a: \mu > 5$. Explain briefly why the answer is not what you would have expected, and why that happened here. (Hint: what is the population mean?)






