## Six ounces of protein

 A company produces prepackaged  diet meals. These meals are advertised as containing "6 ounces of protein per package". A consumer organization is concerned that this is not accurate. The organization takes a random sample of 20 of these meals, and measures the protein content of each one. The data are in [http://ritsokiguess.site/datafiles/protein.txt](http://ritsokiguess.site/datafiles/protein.txt)
as one column. 



(a) Read in and display (some of) the data.



(b) Make a suitable graph of your data.



(c) Why might a sign test be better than a $t$-test for assessing the average amount of protein per package? Explain briefly. ("Average" here means any measure of centre.)



(d) Run a suitable sign test for these data. What do you conclude?



(e) In your sign test, how could you have deduced that the P-value was going to be small even without looking at any of the P-values themselves? Explain briefly.



(f) Obtain a 90% confidence interval for the population median protein content. What does this tell you about the reason for the rejection or non-rejection of the null hypothesis above?




