## Pulse rates and marching

 Forty students, some male and some female, measured their resting pulse rates. Then they marched in place for one minute and measured their pulse rate again. 
Our aim is to use regression to predict the pulse rate after the marching from the pulse rate before, and to see whether that is different for males and females. The data set is in [http://ritsokiguess.site/datafiles/pulsemarch.csv](http://ritsokiguess.site/datafiles/pulsemarch.csv). 



(a) Read in and display (some of) the data.



(b) Make a suitable graph using all three variables, adding appropriate regression line(s) to the plot.



(c) Explain briefly but carefully how any effects of pulse rate before on pulse rate after, and also of sex on pulse rate after, show up on your plot. (If either explanatory variable has no effect, explain how you know.)



(d) Run a regression predicting pulse rate after from the other two variables. Display the output.



(e) Looking at your graph, does the significance (or lack of) of each of your two explanatory variables surprise you? Explain briefly.



(f) What does the numerical value of the Estimate for `Sex` in your regression output mean, in the context of this data set? Explain briefly.











