## The Cross-City Line

When I went to university (in Birmingham, England, a long time ago), I was very excited because I would be travelling to campus by train. My journey was on the Cross-City Line, a metro-type service with lots of stops short distances apart, but run in those days by diesel trains (the electrification came later). 

```{r echo=FALSE}
my_url <- "http://ritsokiguess.site/datafiles/cross-city.csv"
```


A list of the stations on the line is in `r my_url`. There is one column in the data file, called `station`. We are going to draw a map of these.

(a) Read in and display (some of) the station names.


(b) In preparation for geocoding, create a second column in the dataframe that consists of the station names with "station UK" on the end. (This is to improve the chances of the geocoder finding the actual railway station.)


(c) Look up the longitudes and latitudes of all the stations, organizing your dataframe so that they are visible.


(d) Make a Leaflet map of the stations. Use circle markers or the "pin" markers as you prefer.



(e) Zoom in to see whether the geocoding did indeed find each of the stations. Comment briefly on what you find.


