## Unprecendented rainfall

 In 1997, a company in Davis, California, had problems with
odour in its wastewater facility. According to a company official, the
problems were caused by "unprecedented weather conditions" and "because
rainfall was at 170 to 180 percent of its normal level, the water in
the holding ponds took longer to exit for irrigation, giving it more
time to develop an odour."

Annual rainfall data for the Davis area is [here](http://ritsokiguess.site/datafiles/rainfall.txt).
Note that clicking on the link will display the file, and *right*-clicking on the link will give you some options, one of which is Copy Link Address, which you can then paste into your R Notebook.

The rainfall is
measured in inches.





(a) Read in and display (some of) the data.



(b) Summarize the data frame.



(c) Make a suitable plot of the rainfall values. (We are not,
for the time being, concerned about the years.)



(d) How would you describe the shape of the distribution of
rainfall values?



(e) In the quote at the beginning of the question, where do you
think the assertion that the 1997 rainfall was "at 170 to 180
percent of its normal level" came from? Explain briefly.



(f) Do you think the official's calculation was reasonable? 
Explain briefly. (Note that this is not the same as asking whether
the official's calculation was \emph{correct}. This is an important
distinction for you to make.)



(g) Do you think that the official was right to use the word
"unprecedented" to describe the 1997 rainfall? Justify your answer
briefly. 





