## Heights and foot lengths again

 Earlier, we investigated some data on predicting the height of a person from the length of their foot. The data were in \url{http://ritsokiguess.site/datafiles/heightfoot.csv}.



(a) Read in and display (some of) the data.



(b) In your regression course, you learned (or will learn) the matrix formulation of the least squares estimates of intercept and slope. This produces a vector $\hat\beta$ containing estimates of both the intercept and the slope, from the formula

$$ \hat\beta = (X^T X)^{-1} X^T y, $$

where:

- $X$ is a matrix containing a column of 1s followed by all the columns of explanatory variables
- $X^T$ denotes the (matrix) transpose of $X$
- $M^{-1}$ denotes the inverse of the matrix $M$
- $y$ denotes the column of response variable values.

Use the formula above to obtain the least squares estimates of intercepts and slope for this regression, using R's vector-matrix algebra. Hint: you are advised to do the calculation in steps, or else it will be very hard to read, and hard for the grader to check that it is correct.



(c) Verify that your calculation is correct by running the regression.




