## Reggae music

 Reggae is a music genre that originated in Jamaica in the late 1960s. One of the most famous reggae bands was Bob Marley and the Wailers. 
In a survey, 729 students were asked to rate reggae music on a scale from 1, "don't like it at all" to 6, "like it a lot". 
We will treat the ratings as quantitative.
Each student was also asked to classify their home town as one of "big city", "suburban", "small town", "rural". Does a student's opinion of reggae depend on the kind of home town they come from? The data are in [http://ritsokiguess.site/datafiles/reggae.csv](http://ritsokiguess.site/datafiles/reggae.csv). 



(a) Read in and display (some of) the data.



(b) How many students are from each different size of town?



(c) Make a suitable graph of the two variables in this data frame. 



(d) Discuss briefly why you might prefer to run Mood's median test to compare ratings among home towns.



(e) Suppose that somebody wanted to run Welch ANOVA on these data. What would be a reasonable argument to support that?



(f) Run Mood's median test and display the output.



(g) Explain briefly why running pairwise median tests is a good idea, run them, and display the results.



(h) Summarize, as concisely as possible, how the home towns differ in terms of their students' ratings of reggae music.
















