---
title: "regstan"
output: html_notebook
---

## packages

```{r}
library(tidyverse)
library(rstan)
```

## read the data

```{r}
vocabulary=read_delim("vocab.txt", " ")
vocabulary
```

## scatterplot

```{r haeberlingin}
ggplot(vocabulary, aes(x=age, y=vocab))+ geom_point()
```

ordinary regression

```{r}
vocab.1=lm(vocab~age, data=vocabulary)
summary(vocab.1)
cbind(vocabulary$age, predict(vocab.1, interval="p") )
```

compile

```{r}
reg_code=stan_model("reg.stan")
```

save

```{r}
saveRDS(reg_code, "reg_code.rds")
```
  
construct data

```{r}
reg_data = list(
  n = 10,
  x = vocabulary$age,
  y = vocabulary$vocab,
  prior_int_mean = -500,
  prior_int_sd = 125,
  prior_slope_mean = 500,
  prior_slope_sd = 100,
  prior_sigma_mean = 200
)
reg.1 = sampling(reg_code, reg_data)
reg.1
```

```{r}
reg_samples=rstan::extract(reg.1)
cbind(a=reg_samples$a, b=reg_samples$b, sigma=reg_samples$sigma) %>%
    as_tibble() -> sims
sims
```

```{r cunz}
sims %>% 
    mutate(sim_vocab=rnorm(nrow(sims), a+b*5, sigma)) -> sims2
ggplot(sims2, aes(x=sim_vocab)) + geom_histogram(bins=20)
```

```{r}
with(sims2, quantile(sim_vocab, c(0.025, 0.975)))
```

```{r}
vocabulary.1=lm(vocab~age, data=vocabulary)
new=tibble(age=5)
predict(vocabulary.1, new, interval="p")
```

a bit wider