## xxx title here

 Many students at a certain university were asked about the importance of religion in their lives (categorized as "not", "fairly", or "very" important), and also about the number of 
hours they spent studying per week. (This was part of a much larger survey.) We want to see whether there is any kind of relationship between these two variables. The data are in [here](http://ritsokiguess.site/datafiles/student_relig.csv). 



(a) Read in and display (some of) the data.



(b) Obtain the number of observations and the mean and standard deviation of study hours for each level of importance.



(c) Comment briefly on how the groups compare in terms of study hours.



(d) Make a suitable graph of this data set.



(e) The statistician in this study decided that the data were sufficiently normal in shape given the (very large) sample sizes, but was concerned about unequal spreads among the three groups. 
Given this,
run a suitable analysis and display the output. (This includes a suitable follow-up test, if warranted.)



(f) What do you conclude from your analysis of the previous part, in the context of the data?






