## Changes in salary



 A company is growing and would like to attract more
employees. The company would like to advertise that salaries there are
increasing. To do this, the company randomly samples 20 employees that
have been working there since January 2016, and for each of these
employees, records their salary in January 2016 and January 2017. The
data, with salaries in thousands of dollars, are in
[link](http://ritsokiguess.site/datafiles/salaryinc.txt). 



(a) Read the data into R and demonstrate that you have two
salaries for each of 20 employees.


(b) To compare the salaries, explain briefly why a
matched-pairs test would be better than a two-sample test.


(c) Make a suitable graph to assess the assumptions for a
matched-pairs $t$-test. What does your graph tell you?


(d) Carry out a suitable matched-pairs $t$-test on these data. (If you
thought in the previous part that this was the wrong thing to do, do
it anyway for the purposes of this assignment.) What do you conclude?


(e) The company would like to estimate  \emph{how
much} salaries are increasing, on average. Obtain some output that
will enable the company to assess this, and tell the CEO which piece
of the output they should look at.



