
## Going to sleep

 A student keeps track of what time they go to bed and what time they get up in the morning. They also have an app on their phone that measures the number of hours they were asleep during that time. The data for one week are in \url{http://ritsokiguess.site/datafiles/sleeping.csv}, in the 24-hour clock.




(a) Read in and display the data. What type of things are each of your columns? 



(b) Work out the fractional number of hours that the student was in bed each of these nights. (They may not have been asleep this whole time.) Your result needs to be a *number* since we will be doing some calculations with it shortly.



(c) The student is concerned with something they call "sleep efficiency". This is the percentage of time in bed spent sleeping. Work out the student's sleep efficiency for the seven nights in this dataframe. Which night was the student's sleep efficiency greatest?



(d) Display the time spent in bed each night as a number of hours, minutes and seconds.



(e) Make a graph of what time the student went to bed each night. Bear in mind that you only need the times, not the dates, and that you want a graph that is informative, showing appropriately the distribution of times the student went to bed.





