##  Urine and obesity: what makes a difference?


 A study was made of the characteristics of urine of young
men. The men were classified into four groups based on their degree of
obesity. (The groups are labelled `a, b, c, d`.) Four variables
were measured, `x` (which you can ignore), pigment creatinine,
chloride and chlorine. The data are in
[link](http://ritsokiguess.site/datafiles/urine.csv) as a
`.csv` file. There are 45 men altogether.

Yes, you may have seen this one before. What you found was something like this:

```{r }
my_url <- "http://ritsokiguess.site/datafiles/urine.csv"
urine <- read_csv(my_url)
response <- with(urine, cbind(creatinine, chlorine, chloride))
urine.1 <- manova(response ~ obesity, data = urine)
summary(urine.1)
```

 

Our aim is to understand why this result was significant.



(a) Read in the data again (copy the code from above) and
obtain a discriminant analysis.
 

(b) How many linear discriminants were you expecting? Explain briefly.
 

(c) Why do you think we should pay attention to the first two
linear discriminants but not the third? Explain briefly.
 

(d) Plot the first two linear discriminant scores (against each
other), with each obesity group being a different colour.
 

(e) <a name="part:plot">*</a> Looking at your plot, discuss how (if at all) the
discriminants separate the obesity groups. (Where does each
obesity group fall on the plot?)
 

(f) <a name="part:table">*</a> Obtain a table showing observed and predicted obesity
groups. Comment on the accuracy of the predictions.
 

(g) Do your conclusions from (<a href="#part:plot">here</a>) and
(<a href="#part:table">here</a>) appear to be consistent?
 



