## Tidying electricity consumption

 How does the consumption of electricity depend on  temperature?  To find out, a short-term study was carried out by a utility company based in a certain area. For a period of two years, the average monthly temperature was recorded (in degrees Fahrenheit), the mean daily demand for electricity per household (in kilowatt hours), and the cost per kilowatt  hour of electricity for that year (8 cents for the first year and 10 cents for the second, which it will be easiest to treat as categorical). 

The data were laid out in an odd way, as shown in \url{http://ritsokiguess.site/datafiles/utils.txt}, in aligned columns: the twelve months of temperature were laid out on *two* lines for the first year, then the twelve months of consumption for the first year on the next two lines, and then four more lines for the second year laid out the same way. Thus the temperature of 31 in the first line goes with the consumption of 55 in the *third* line, and the last measurements for that year are the 78 at the end of the second line (temperature) and 73 at the end of the fourth line (consumption).  Lines 5 through 8 of the data file are the same thing for the second year (when electricity was more expensive). 

The data seem to have been laid out in order of temperature, rather than in order of months, which I would have thought would make more sense. But this is what we have.



(a) Read in and display the data file, bearing in mind that it has *no column names*.



(b) Arrange these data tidily, so that there is a column of price (per kilowatt hour), a column of temperatures, and a column of consumptions. Describe your process, including why you got list-columns (if you did) and what you did about them (if necessary).



(c) Make a suitable graph of temperature, consumption and price in your tidy dataframe. Add smooth trends if appropriate. If you were unable to get the data tidy, use my tidy version [here](http://ritsokiguess.site/datafiles/utils_tidy.csv). (If you need the other file, right-click on "here" and Copy Link Address.)



(d) What patterns or trends do you see on your graph? Do they make practical sense? There are two things I would like you to comment on.





