## Death of poets

 Some people believe that poets, especially female poets, die younger than other types of writer. [William Butler Yeats](https://en.wikipedia.org/wiki/W._B._Yeats) `r tufte::margin_note("An Irish, that is to say, Gaelic, poet (see below), but a male one.")` wrote:

> She is the Gaelic `r tufte::margin_note("Gaelic is a language of Scotland and Ireland, and the culture of the people who speak it.")` muse, for she gives inspiration to those she persecutes. The Gaelic poets die young, for she is restless, and will not let them remain long on earth.

A literature student wanted to investigate this, and so collected a sample of 123 female writers (of three different types), and noted the age at death of each writer. 

The data are in [http://ritsokiguess.site/datafiles/writers.csv](http://ritsokiguess.site/datafiles/writers.csv).



(a) Read in and display (some of) the data.



(b) Make a suitable plot of the ages and types of writing.



(c) Obtain a summary table showing, for each type of writing, the number of writers of that type, along with the mean, median and standard deviation of their ages at death.



(d) Run a complete analysis, starting with an ordinary (not Welch) analysis of variance, that ends with a conclusion in the context of the data and an assessment of assumptions.




