<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">

<head>

<meta charset="utf-8">
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<meta name="generator" content="pandoc" />
<meta name="viewport" content="width=device-width, initial-scale=1">
<meta property="og:title" content="Problems and Solutions in Applied Statistics" />
<meta property="og:type" content="book" />
<meta property="og:url" content="<a href="http://ritsokiguess.site/pasias" class="uri">http://ritsokiguess.site/pasias</a>" />

<meta property="og:description" content="A set of problems and solutions, in R, on various parts of applied statistics" />
<meta name="github-repo" content="nxskok/pasias" />

<meta name="author" content="Ken Butler" />

<meta name="date" content="2018-10-09" />

<script type="text/x-mathjax-config">
MathJax.Hub.Config({
  TeX: { equationNumbers: { autoNumber: "AMS" } }
});
</script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.2/MathJax.js?config=TeX-AMS_CHTML-full" type="text/javascript"></script>

<meta name="description" content="A set of problems and solutions, in R, on various parts of applied statistics">

<title>Problems and Solutions in Applied Statistics</title>

<link href="libs/tufte-css-2015.12.29/tufte-fonts.css" rel="stylesheet" />
<link href="libs/tufte-css-2015.12.29/tufte-background.css" rel="stylesheet" />
<link href="libs/tufte-css-2015.12.29/tufte-italics.css" rel="stylesheet" />
<link href="libs/tufte-css-2015.12.29/tufte.css" rel="stylesheet" />


<style type="text/css">code{white-space: pre;}</style>
<style type="text/css">
a.sourceLine { display: inline-block; line-height: 1.25; }
a.sourceLine { pointer-events: none; color: inherit; text-decoration: inherit; }
a.sourceLine:empty { height: 1.2em; position: absolute; }
.sourceCode { overflow: visible; }
code.sourceCode { white-space: pre; position: relative; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
code.sourceCode { white-space: pre-wrap; }
a.sourceLine { text-indent: -1em; padding-left: 1em; }
}
pre.numberSource a.sourceLine
  { position: relative; }
pre.numberSource a.sourceLine:empty
  { position: absolute; }
pre.numberSource a.sourceLine::before
  { content: attr(data-line-number);
    position: absolute; left: -5em; text-align: right; vertical-align: baseline;
    border: none; pointer-events: all;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {  }
@media screen {
a.sourceLine::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>


<link rel="stylesheet" href="toc.css" type="text/css" />

</head>

<body>



<div class="row">
<div class="col-sm-12">
<div id="TOC">
<ul>
<li><a href="index.html#introduction"><span class="toc-section-number">1</span> Introduction</a></li>
<li class="has-sub"><a href="2-getting-used-to-r-and-r-studio.html#getting-used-to-r-and-r-studio"><span class="toc-section-number">2</span> Getting used to R and R Studio</a><ul>
<li><a href="2-1-getting-an-r-studio-cloud-account.html#getting-an-r-studio-cloud-account"><span class="toc-section-number">2.1</span> Getting an R Studio Cloud account</a></li>
<li><a href="2-2-getting-started.html#getting-started"><span class="toc-section-number">2.2</span> Getting started</a></li>
<li><a href="2-3-reading-data-from-a-file.html#reading-data-from-a-file"><span class="toc-section-number">2.3</span> Reading data from a file</a></li>
</ul></li>
<li class="has-sub"><a href="3-reading-in-data-and-drawing-some-graphs.html#reading-in-data-and-drawing-some-graphs"><span class="toc-section-number">3</span> Reading in data and drawing some graphs</a><ul>
<li><a href="3-1-orange-juice.html#orange-juice"><span class="toc-section-number">3.1</span> Orange juice</a></li>
<li><a href="3-2-making-soap.html#making-soap"><span class="toc-section-number">3.2</span> Making soap</a></li>
<li><a href="3-3-handling-shipments.html#handling-shipments"><span class="toc-section-number">3.3</span> Handling shipments</a></li>
</ul></li>
<li class="has-sub"><a href="4-data-exploration.html#data-exploration"><span class="toc-section-number">4</span> Data exploration</a><ul>
<li><a href="4-1-north-carolina-births.html#north-carolina-births"><span class="toc-section-number">4.1</span> North Carolina births</a></li>
<li><a href="4-2-more-about-the-nc-births.html#more-about-the-nc-births"><span class="toc-section-number">4.2</span> More about the NC births</a></li>
<li><a href="4-3-nenana-alaska.html#nenana-alaska"><span class="toc-section-number">4.3</span> Nenana, Alaska</a></li>
<li><a href="4-4-computerized-accounting.html#computerized-accounting"><span class="toc-section-number">4.4</span> Computerized accounting</a></li>
</ul></li>
<li class="has-sub"><a href="5-one-sample-inference.html#one-sample-inference"><span class="toc-section-number">5</span> One-sample inference</a><ul>
<li><a href="5-1-hunter-gatherers-in-australia.html#hunter-gatherers-in-australia"><span class="toc-section-number">5.1</span> Hunter-gatherers in Australia</a></li>
<li><a href="5-2-length-of-gestation-in-north-carolina.html#length-of-gestation-in-north-carolina"><span class="toc-section-number">5.2</span> Length of gestation in North Carolina</a></li>
<li><a href="5-3-inferring-ice-break-up-in-nenana.html#inferring-ice-break-up-in-nenana"><span class="toc-section-number">5.3</span> Inferring ice break-up in Nenana</a></li>
</ul></li>
<li class="has-sub"><a href="6-two-sample-inference.html#two-sample-inference"><span class="toc-section-number">6</span> Two-sample inference</a><ul>
<li><a href="6-1-children-and-electronic-devices.html#children-and-electronic-devices"><span class="toc-section-number">6.1</span> Children and electronic devices</a></li>
<li><a href="6-2-parking-close-to-the-curb.html#parking-close-to-the-curb"><span class="toc-section-number">6.2</span> Parking close to the curb</a></li>
</ul></li>
<li class="has-sub"><a href="7-power-and-sample-size.html#power-and-sample-size"><span class="toc-section-number">7</span> Power and sample size</a><ul>
<li><a href="7-1-simulating-power.html#simulating-power"><span class="toc-section-number">7.1</span> Simulating power</a></li>
<li><a href="7-2-calculating-power-and-sample-size-for-estimating-mean.html#calculating-power-and-sample-size-for-estimating-mean"><span class="toc-section-number">7.2</span> Calculating power and sample size for estimating mean</a></li>
<li><a href="7-3-simulating-power-for-proportions.html#simulating-power-for-proportions"><span class="toc-section-number">7.3</span> Simulating power for proportions</a></li>
</ul></li>
<li><a href="8-the-sign-test-and-moods-median-test.html#the-sign-test-and-moods-median-test"><span class="toc-section-number">8</span> The sign test and Mood’s median test</a></li>
<li><a href="9-matched-pairs-t-and-sign-test.html#matched-pairs-t-and-sign-test"><span class="toc-section-number">9</span> Matched pairs t and sign test</a></li>
<li><a href="10-normal-quantile-plots.html#normal-quantile-plots"><span class="toc-section-number">10</span> Normal quantile plots</a></li>
</ul>
</div>
</div>
</div>
<div class="row">
<div class="col-sm-12">
<div id="nenana-alaska" class="section level2">
<h2><span class="header-section-number">4.3</span> Nenana, Alaska</h2>
<p>Nenana, Alaska, is about 50 miles west of Fairbanks.
Every spring, there is a contest in Nenana. A wooden tripod is
placed on the frozen river, and people try to guess the exact minute
when the ice melts enough for the tripod to fall through the ice. The
contest started in 1917 as an amusement for railway workers, and has
taken place every year since. Now, hundreds of thousands of people
enter their guesses on the Internet and the prize for the winner can
be as much as $300,000.</p>
<p>Because so much money is at stake, and because the exact same tripod
is placed at the exact same spot on the ice every year, the data are
consistent and accurate. The data are in
<a href="http://www.utsc.utoronto.ca/~butler/c32/nenana.txt" class="uri">http://www.utsc.utoronto.ca/~butler/c32/nenana.txt</a>.</p>
<ol style="list-style-type: lower-alpha">
<li>Read the data into R. Note that the values are
separated by <em>tabs</em> rather than spaces, so you’ll need an
appropriate <code>read\_</code> to read it in.</li>
</ol>
<p>Solution</p>
<p>These are “tab-separated values”, so <code>read\_tsv</code> is the
thing, as for the Australian athletes:</p>
<div class="sourceCode" id="cb95"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb95-1" data-line-number="1">myurl=<span class="st">&quot;http://www.utsc.utoronto.ca/~butler/c32/nenana.txt&quot;</span></a>
<a class="sourceLine" id="cb95-2" data-line-number="2">nenana=<span class="kw">read_tsv</span>(myurl)</a></code></pre></div>
<pre><code>## Parsed with column specification:
## cols(
##   Year = col_integer(),
##   JulianDate = col_double(),
##   `Date&amp;Time` = col_character()
## )</code></pre>
<p>Use whatever name you like for the data frame. One that is different
from any of the column headers is smart; then it is clear whether you
mean the whole data frame or one of its columns. <code>ice</code> or
<code>melt</code> or anything like that would also be good.</p>
<p>I haven’t asked you to display or check the data (that’s coming up),
but if you look at it and find that it didn’t work, you’ll know to
come back and try this part again. R usually gets it right or gives
you an error.</p>
<p>If you look at the data, they do appear to be separated by spaces, but
the text version of the date and time <em>also</em> have spaces in them,
so things might go astray if you try and read the values in without
recognizing that the actual separator is a tab:</p>
<div class="sourceCode" id="cb97"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb97-1" data-line-number="1">x=<span class="kw">read_delim</span>(myurl,<span class="st">&quot; &quot;</span>)</a></code></pre></div>
<pre><code>## Parsed with column specification:
## cols(
##   `Year  JulianDate  Date&amp;Time` = col_character()
## )</code></pre>
<pre><code>## Warning in rbind(names(probs), probs_f): number of columns of result is not
## a multiple of vector length (arg 1)</code></pre>
<pre><code>## Warning: 87 parsing failures.
## row # A tibble: 5 x 5 col     row col   expected  actual    file                                     expected   &lt;int&gt; &lt;chr&gt; &lt;chr&gt;     &lt;chr&gt;     &lt;chr&gt;                                    actual 1     1 &lt;NA&gt;  1 columns 5 columns &#39;http://www.utsc.utoronto.ca/~butler/c3… file 2     2 &lt;NA&gt;  1 columns 5 columns &#39;http://www.utsc.utoronto.ca/~butler/c3… row 3     3 &lt;NA&gt;  1 columns 5 columns &#39;http://www.utsc.utoronto.ca/~butler/c3… col 4     4 &lt;NA&gt;  1 columns 5 columns &#39;http://www.utsc.utoronto.ca/~butler/c3… expected 5     5 &lt;NA&gt;  1 columns 5 columns &#39;http://www.utsc.utoronto.ca/~butler/c3…
## ... ................. ... .......................................................................... ........ .......................................................................... ...... .......................................................................... .... .......................................................................... ... .......................................................................... ... .......................................................................... ........ ..........................................................................
## See problems(...) for more details.</code></pre>
<p>Ouch! A hint as to what went wrong comes from looking at the read-in
data frame:</p>
<div class="sourceCode" id="cb101"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb101-1" data-line-number="1">x</a></code></pre></div>
<pre><code>## # A tibble: 87 x 1
##    `Year\tJulianDate\tDate&amp;Time`
##    &lt;chr&gt;                        
##  1 &quot;1917\t120.4795\tApril&quot;      
##  2 &quot;1918\t131.3983\tMay&quot;        
##  3 &quot;1919\t123.6066\tMay&quot;        
##  4 &quot;1920\t132.4490\tMay&quot;        
##  5 &quot;1921\t131.2795\tMay&quot;        
##  6 &quot;1922\t132.5559\tMay&quot;        
##  7 &quot;1923\t129.0837\tMay&quot;        
##  8 &quot;1924\t132.6323\tMay&quot;        
##  9 &quot;1925\t127.7726\tMay&quot;        
## 10 &quot;1926\t116.6691\tApril&quot;      
## # ... with 77 more rows</code></pre>
<p>Those “= symbols mean ``tab character”, which is our hint that
the values were separated by tabs rather than spaces.</p>
<p>More detail (if you can bear to see it) is here:</p>
<div class="sourceCode" id="cb103"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb103-1" data-line-number="1"><span class="kw">problems</span>(x)</a></code></pre></div>
<pre><code>## # A tibble: 87 x 5
##      row col   expected  actual   file                                    
##    &lt;int&gt; &lt;chr&gt; &lt;chr&gt;     &lt;chr&gt;    &lt;chr&gt;                                   
##  1     1 &lt;NA&gt;  1 columns 5 colum… &#39;http://www.utsc.utoronto.ca/~butler/c3…
##  2     2 &lt;NA&gt;  1 columns 5 colum… &#39;http://www.utsc.utoronto.ca/~butler/c3…
##  3     3 &lt;NA&gt;  1 columns 5 colum… &#39;http://www.utsc.utoronto.ca/~butler/c3…
##  4     4 &lt;NA&gt;  1 columns 5 colum… &#39;http://www.utsc.utoronto.ca/~butler/c3…
##  5     5 &lt;NA&gt;  1 columns 5 colum… &#39;http://www.utsc.utoronto.ca/~butler/c3…
##  6     6 &lt;NA&gt;  1 columns 5 colum… &#39;http://www.utsc.utoronto.ca/~butler/c3…
##  7     7 &lt;NA&gt;  1 columns 5 colum… &#39;http://www.utsc.utoronto.ca/~butler/c3…
##  8     8 &lt;NA&gt;  1 columns 5 colum… &#39;http://www.utsc.utoronto.ca/~butler/c3…
##  9     9 &lt;NA&gt;  1 columns 5 colum… &#39;http://www.utsc.utoronto.ca/~butler/c3…
## 10    10 &lt;NA&gt;  1 columns 5 colum… &#39;http://www.utsc.utoronto.ca/~butler/c3…
## # ... with 77 more rows</code></pre>
<p>The first line of the data file (with the variable names in it) had no
spaces, only tabs, so <code>read\_delim</code> thinks there is <em>one</em>
column with a very long name, but in the actual data, there are
<em>five</em> space-separated columns. The text date-times are of the
form “April 30 at 11:30 AM”, which, if you think it’s all separated
by spaces, is actually 5 things: April, 30, at and so on. These are
the only things that are separated by spaces, so, from that point of
view, there are five columns.</p>
<ol start="2" style="list-style-type: lower-alpha">
<li>Find a way of displaying how many rows and columns your
data frame has, and some of the values. Describe the first and last
of the variables that
you appear to have.</li>
</ol>
<p>Solution</p>
<p>The easiest is just to display the tibble:</p>
<div class="sourceCode" id="cb105"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb105-1" data-line-number="1">nenana</a></code></pre></div>
<pre><code>## # A tibble: 87 x 3
##     Year JulianDate `Date&amp;Time`         
##    &lt;int&gt;      &lt;dbl&gt; &lt;chr&gt;               
##  1  1917       120. April 30 at 11:30 AM
##  2  1918       131. May 11 at 9:33 AM   
##  3  1919       124. May 3 at 2:33 PM    
##  4  1920       132. May 11 at 10:46 AM  
##  5  1921       131. May 11 at 6:42 AM   
##  6  1922       133. May 12 at 1:20 PM   
##  7  1923       129. May 9 at 2:00 AM    
##  8  1924       133. May 11 at 3:10 PM   
##  9  1925       128. May 7 at 6:32 PM    
## 10  1926       117. April 26 at 4:03 PM 
## # ... with 77 more rows</code></pre>
<p>Alternatively, you can take a <code>glimpse</code> of it:</p>
<div class="sourceCode" id="cb107"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb107-1" data-line-number="1"><span class="kw">glimpse</span>(nenana)</a></code></pre></div>
<pre><code>## Observations: 87
## Variables: 3
## $ Year        &lt;int&gt; 1917, 1918, 1919, 1920, 1921, 1922, 1923, 1924, 19...
## $ JulianDate  &lt;dbl&gt; 120.4795, 131.3983, 123.6066, 132.4490, 131.2795, ...
## $ `Date&amp;Time` &lt;chr&gt; &quot;April 30 at 11:30 AM&quot;, &quot;May 11 at 9:33 AM&quot;, &quot;May ...</code></pre>
<p>There are 87 years, and 3 columns (variables).
The first column is year, and the last
column is the date and time that the tripod fell into the river,
written as a piece of text. I explain the second column in a moment.</p>
<ol start="3" style="list-style-type: lower-alpha">
<li>Dates and times are awkward to handle with software. (We
see more ways later in the course.) The column <code>JulianDate</code>
expresses the time that the tripod fell through the ice as a
fractional number of days since December 31. This enables the time
(as a fraction of the way through the day) to be recorded as well,
the whole thing being an ordinary number.
Make a histogram of the Julian dates. Comment briefly on its shape.</li>
</ol>
<p>Solution</p>
<p>With a <code>ggplot</code> histogram, we need a number of bins
first. I can do Sturges’ rule in my head: the next power of 2 up
from 87 (our <span class="math inline">\(n\)</span>) is 128, which is <span class="math inline">\(2^7\)</span>, so the base 2 log of
87 rounds up to 7. That plus one is 8, so we need 8 bins. For
you, any not-insane number of bins will do, or any not-insane
bin width, if you want to go that way:</p>
<div class="sourceCode" id="cb109"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb109-1" data-line-number="1"><span class="kw">ggplot</span>(nenana,<span class="kw">aes</span>(<span class="dt">x=</span>JulianDate))<span class="op">+</span><span class="kw">geom_histogram</span>(<span class="dt">bins=</span><span class="dv">8</span>)</a></code></pre></div>
<p><img src="03-data-summaries_files/figure-html/unnamed-chunk-31-1.png" width="672"  /></p>
<p>Note that you need to type <code>JulianDate</code> exactly as it
appears, capital letters and all. R is case-sensitive.</p>
<p>This histogram looks more or less symmetric (and, indeed, normal). I
really don’t think you can justify an answer other than “symmetric”
here. (Or “approximately normal”: that’s good too.) If your
histogram is different, say so. I think that “hole” in the middle is
not especially important.</p>
<p>We haven’t done normal quantile plots yet, but looking ahead:</p>
<div class="sourceCode" id="cb110"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb110-1" data-line-number="1"><span class="kw">ggplot</span>(nenana, <span class="kw">aes</span>(<span class="dt">sample=</span>JulianDate))<span class="op">+</span><span class="kw">stat_qq</span>()<span class="op">+</span><span class="kw">stat_qq_line</span>()</a></code></pre></div>
<p><img src="03-data-summaries_files/figure-html/unnamed-chunk-32-1.png" width="672"  /></p>
<p>That hugs the line pretty well, so I would call it close to
normally-distributed. It bulges away from the line because there are
more values just below 120 than you would expect for a
normal. This corresponds to the histogram bar centred just below 120
being taller than you would have expected.</p>
<p>Extra: looking <em>way</em> ahead (to almost the end of the R stuff),
this is how you handle the dates and times:</p>
<div class="sourceCode" id="cb111"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb111-1" data-line-number="1"><span class="kw">library</span>(lubridate)</a></code></pre></div>
<pre><code>## 
## Attaching package: &#39;lubridate&#39;</code></pre>
<pre><code>## The following object is masked from &#39;package:base&#39;:
## 
##     date</code></pre>
<div class="sourceCode" id="cb114"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb114-1" data-line-number="1">nenana <span class="op">%&gt;%</span><span class="st"> </span></a>
<a class="sourceLine" id="cb114-2" data-line-number="2"><span class="kw">mutate</span>(<span class="dt">longdt=</span><span class="kw">str_c</span>(Year,<span class="st">&quot; &quot;</span>,<span class="st">`</span><span class="dt">Date&amp;Time</span><span class="st">`</span>)) <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb114-3" data-line-number="3"><span class="kw">mutate</span>(<span class="dt">datetime=</span><span class="kw">ymd_hm</span>(longdt,<span class="dt">tz=</span><span class="st">&quot;America/Anchorage&quot;</span>))</a></code></pre></div>
<pre><code>## # A tibble: 87 x 5
##     Year JulianDate `Date&amp;Time`       longdt           datetime           
##    &lt;int&gt;      &lt;dbl&gt; &lt;chr&gt;             &lt;chr&gt;            &lt;dttm&gt;             
##  1  1917       120. April 30 at 11:3… 1917 April 30 a… 1917-04-30 11:30:00
##  2  1918       131. May 11 at 9:33 AM 1918 May 11 at … 1918-05-11 09:33:00
##  3  1919       124. May 3 at 2:33 PM  1919 May 3 at 2… 1919-05-03 14:33:00
##  4  1920       132. May 11 at 10:46 … 1920 May 11 at … 1920-05-11 10:46:00
##  5  1921       131. May 11 at 6:42 AM 1921 May 11 at … 1921-05-11 06:42:00
##  6  1922       133. May 12 at 1:20 PM 1922 May 12 at … 1922-05-12 13:20:00
##  7  1923       129. May 9 at 2:00 AM  1923 May 9 at 2… 1923-05-09 02:00:00
##  8  1924       133. May 11 at 3:10 PM 1924 May 11 at … 1924-05-11 15:10:00
##  9  1925       128. May 7 at 6:32 PM  1925 May 7 at 6… 1925-05-07 18:32:00
## 10  1926       117. April 26 at 4:03… 1926 April 26 a… 1926-04-26 16:03:00
## # ... with 77 more rows</code></pre>
<p>I am not doing any further analysis with these, so just displaying them is good.</p>
<p>I have to do a preliminary step to get the date-times <em>with</em> their year in one place. <code>str_c- glues pieces of text together: in this case, the year, a space, and then the rest of the</code>Date&amp;Time-. I stored this in <code>longdt-. The second</code>mutate- is the business end of it: <code>ymd_hm- takes a piece of text containing a year, month (by name or number), day, hours, minutes *in that order*, and extracts those things from it, storing the whole thing as an R date-time. Note that the AM/PM was handled properly. The benefit of doing that is we can extract anything from the dates, such as the month or day of week, or take differences between the dates. Or even check that the Julian dates were calculated correctly (the</code>lubridate- function is called ``yday- for “day of year”):</p>
<div class="sourceCode" id="cb116"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb116-1" data-line-number="1">nenana <span class="op">%&gt;%</span><span class="st"> </span></a>
<a class="sourceLine" id="cb116-2" data-line-number="2"><span class="kw">mutate</span>(<span class="dt">longdt=</span><span class="kw">str_c</span>(Year,<span class="st">&quot; &quot;</span>,<span class="st">`</span><span class="dt">Date&amp;Time</span><span class="st">`</span>)) <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb116-3" data-line-number="3"><span class="kw">mutate</span>(<span class="dt">datetime=</span><span class="kw">ymd_hm</span>(longdt,<span class="dt">tz=</span><span class="st">&quot;America/Anchorage&quot;</span>)) <span class="op">%&gt;%</span><span class="st"> </span></a>
<a class="sourceLine" id="cb116-4" data-line-number="4"><span class="kw">mutate</span>(<span class="dt">jd=</span><span class="kw">yday</span>(datetime)) -&gt;</a>
<a class="sourceLine" id="cb116-5" data-line-number="5">nenana2</a>
<a class="sourceLine" id="cb116-6" data-line-number="6">nenana2 <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">select</span>(JulianDate,jd,datetime)</a></code></pre></div>
<pre><code>## # A tibble: 87 x 3
##    JulianDate    jd datetime           
##         &lt;dbl&gt; &lt;dbl&gt; &lt;dttm&gt;             
##  1       120.   120 1917-04-30 11:30:00
##  2       131.   131 1918-05-11 09:33:00
##  3       124.   123 1919-05-03 14:33:00
##  4       132.   132 1920-05-11 10:46:00
##  5       131.   131 1921-05-11 06:42:00
##  6       133.   132 1922-05-12 13:20:00
##  7       129.   129 1923-05-09 02:00:00
##  8       133.   132 1924-05-11 15:10:00
##  9       128.   127 1925-05-07 18:32:00
## 10       117.   116 1926-04-26 16:03:00
## # ... with 77 more rows</code></pre>
<p>Hmm, some of those are off by one. What do the off-by-one ones have in common? Let’s look at more of them. ``round- rounds off to the nearest integer (since these are actually decimal numbers):</p>
<div class="sourceCode" id="cb118"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb118-1" data-line-number="1">nenana2 <span class="op">%&gt;%</span><span class="st"> </span></a>
<a class="sourceLine" id="cb118-2" data-line-number="2"><span class="kw">filter</span>(<span class="kw">round</span>(JulianDate) <span class="op">!=</span><span class="st"> </span><span class="kw">round</span>(jd)) <span class="op">%&gt;%</span><span class="st"> </span></a>
<a class="sourceLine" id="cb118-3" data-line-number="3"><span class="kw">select</span>(JulianDate,jd,datetime)</a></code></pre></div>
<pre><code>## # A tibble: 61 x 3
##    JulianDate    jd datetime           
##         &lt;dbl&gt; &lt;dbl&gt; &lt;dttm&gt;             
##  1       124.   123 1919-05-03 14:33:00
##  2       133.   132 1922-05-12 13:20:00
##  3       133.   132 1924-05-11 15:10:00
##  4       128.   127 1925-05-07 18:32:00
##  5       117.   116 1926-04-26 16:03:00
##  6       128.   127 1928-05-06 16:25:00
##  7       126.   125 1929-05-05 15:41:00
##  8       129.   128 1930-05-08 19:03:00
##  9       129.   128 1933-05-08 19:30:00
## 10       121.   120 1934-04-30 14:07:00
## # ... with 51 more rows</code></pre>
<p>The ones shown here are all <em>after noon</em>, and the Julian date in
the data file appears as one more than the one calculated by
<code>lubridate-. What has actually happened is a quirk of how tibbles are displayed: they show 3 significant digits, *rounded*. The Julian dates given by</code>yday- are the whole-number part, so the
ones in the data value are that plus more than 0.5, which will round
<em>up</em>. The first line of code below displays 6 significant digits
rather than only three:</p>
<div class="sourceCode" id="cb120"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb120-1" data-line-number="1"><span class="kw">options</span>(<span class="dt">pillar.sigfig=</span><span class="dv">6</span>)</a>
<a class="sourceLine" id="cb120-2" data-line-number="2">nenana2 <span class="op">%&gt;%</span><span class="st"> </span></a>
<a class="sourceLine" id="cb120-3" data-line-number="3"><span class="kw">filter</span>(<span class="kw">round</span>(JulianDate) <span class="op">!=</span><span class="st"> </span><span class="kw">round</span>(jd)) <span class="op">%&gt;%</span><span class="st"> </span></a>
<a class="sourceLine" id="cb120-4" data-line-number="4"><span class="kw">select</span>(JulianDate,jd,datetime)</a></code></pre></div>
<pre><code>## # A tibble: 61 x 3
##    JulianDate    jd datetime           
##         &lt;dbl&gt; &lt;dbl&gt; &lt;dttm&gt;             
##  1    123.607   123 1919-05-03 14:33:00
##  2    132.556   132 1922-05-12 13:20:00
##  3    132.632   132 1924-05-11 15:10:00
##  4    127.773   127 1925-05-07 18:32:00
##  5    116.669   116 1926-04-26 16:03:00
##  6    127.684   127 1928-05-06 16:25:00
##  7    125.654   125 1929-05-05 15:41:00
##  8    128.794   128 1930-05-08 19:03:00
##  9    128.813   128 1933-05-08 19:30:00
## 10    120.588   120 1934-04-30 14:07:00
## # ... with 51 more rows</code></pre>
<p>Displaying more decimals shows that I was right: <code>jd- is (to this accuracy) a whole number, but</code>JulianDate- is a decimal with fractional part greater than 0.50.</p>
<p>Now I have to turn the extra signficant digits off:</p>
<div class="sourceCode" id="cb122"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb122-1" data-line-number="1"><span class="kw">options</span>(<span class="dt">pillar.sigfig=</span><span class="dv">3</span>)</a></code></pre></div>
<ol start="4" style="list-style-type: lower-alpha">
<li>Plot <code>JulianDate</code> against <code>Year</code> on a
scatterplot. What recent trends, if any, do you see? Comment briefly.</li>
</ol>
<p>Solution</p>
<p>``geom_point+:</p>
<div class="sourceCode" id="cb123"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb123-1" data-line-number="1"><span class="kw">ggplot</span>(nenana,<span class="kw">aes</span>(<span class="dt">x=</span>Year,<span class="dt">y=</span>JulianDate))<span class="op">+</span><span class="kw">geom_point</span>()</a></code></pre></div>
<p><img src="03-data-summaries_files/figure-html/unnamed-chunk-38-1.png" width="672"  />
This is actually a small-but-real downward trend, especially since
about 1960,
but the large amount
of variability makes it hard to see, so I’m good with either ``no
trend’’ or “weak downward trend”
or anything roughly like that. There is definitely not much trend
before 1960, but most of the really early break-ups (less than about
118) have been since about 1990.</p>
<p>You can even add to the <code>ggplot</code>, by putting a smooth trend on it:</p>
<div class="sourceCode" id="cb124"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb124-1" data-line-number="1"><span class="kw">ggplot</span>(nenana,<span class="kw">aes</span>(<span class="dt">x=</span>Year,<span class="dt">y=</span>JulianDate))<span class="op">+</span><span class="kw">geom_point</span>()<span class="op">+</span><span class="kw">geom_smooth</span>()</a></code></pre></div>
<pre><code>## `geom_smooth()` using method = &#39;loess&#39; and formula &#39;y ~ x&#39;</code></pre>
<p><img src="03-data-summaries_files/figure-html/unnamed-chunk-39-1.png" width="672"  /></p>
<p>This is R’s version of a trend that is not constrained
to be linear (so that it “lets the data speak for itself”).</p>
<p>Now there is something obvious to see: after about 1960, there is a clear
downward trend: the ice is breaking up earlier on average every
year. Even though there is a lot of variability, the overall trend,
viewed this way, is clear.</p>
<p>What does this mean, in practice? This notion of the ice melting
earlier than it used to is consistent all over the Arctic, and is one
more indication of climate change. Precisely, it is an indication that
climate change is happening, but we would have to delve further to
make any statements about the <em>cause</em> of that climate change.</p>
</div>
<p style="text-align: center;">
<a href="4-2-more-about-the-nc-births.html"><button class="btn btn-default">Previous</button></a>
<a href="4-4-computerized-accounting.html"><button class="btn btn-default">Next</button></a>
</p>
</div>
</div>



</body>
</html>
