<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">

<head>

<meta charset="utf-8">
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<meta name="generator" content="pandoc" />
<meta name="viewport" content="width=device-width, initial-scale=1">
<meta property="og:title" content="Problems and Solutions in Applied Statistics" />
<meta property="og:type" content="book" />
<meta property="og:url" content="<a href="http://ritsokiguess.site/pasias" class="uri">http://ritsokiguess.site/pasias</a>" />

<meta property="og:description" content="A set of problems and solutions, in R, on various parts of applied statistics" />
<meta name="github-repo" content="nxskok/pasias" />

<meta name="author" content="Ken Butler" />

<meta name="date" content="2018-10-09" />

<script type="text/x-mathjax-config">
MathJax.Hub.Config({
  TeX: { equationNumbers: { autoNumber: "AMS" } }
});
</script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.2/MathJax.js?config=TeX-AMS_CHTML-full" type="text/javascript"></script>

<meta name="description" content="A set of problems and solutions, in R, on various parts of applied statistics">

<title>Problems and Solutions in Applied Statistics</title>

<link href="libs/tufte-css-2015.12.29/tufte-fonts.css" rel="stylesheet" />
<link href="libs/tufte-css-2015.12.29/tufte-background.css" rel="stylesheet" />
<link href="libs/tufte-css-2015.12.29/tufte-italics.css" rel="stylesheet" />
<link href="libs/tufte-css-2015.12.29/tufte.css" rel="stylesheet" />


<style type="text/css">code{white-space: pre;}</style>
<style type="text/css">
a.sourceLine { display: inline-block; line-height: 1.25; }
a.sourceLine { pointer-events: none; color: inherit; text-decoration: inherit; }
a.sourceLine:empty { height: 1.2em; position: absolute; }
.sourceCode { overflow: visible; }
code.sourceCode { white-space: pre; position: relative; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
code.sourceCode { white-space: pre-wrap; }
a.sourceLine { text-indent: -1em; padding-left: 1em; }
}
pre.numberSource a.sourceLine
  { position: relative; }
pre.numberSource a.sourceLine:empty
  { position: absolute; }
pre.numberSource a.sourceLine::before
  { content: attr(data-line-number);
    position: absolute; left: -5em; text-align: right; vertical-align: baseline;
    border: none; pointer-events: all;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {  }
@media screen {
a.sourceLine::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>


<link rel="stylesheet" href="toc.css" type="text/css" />

</head>

<body>



<div class="row">
<div class="col-sm-12">
<div id="TOC">
<ul>
<li><a href="index.html#introduction"><span class="toc-section-number">1</span> Introduction</a></li>
<li class="has-sub"><a href="2-getting-used-to-r-and-r-studio.html#getting-used-to-r-and-r-studio"><span class="toc-section-number">2</span> Getting used to R and R Studio</a><ul>
<li><a href="2-1-getting-an-r-studio-cloud-account.html#getting-an-r-studio-cloud-account"><span class="toc-section-number">2.1</span> Getting an R Studio Cloud account</a></li>
<li><a href="2-2-getting-started.html#getting-started"><span class="toc-section-number">2.2</span> Getting started</a></li>
<li><a href="2-3-reading-data-from-a-file.html#reading-data-from-a-file"><span class="toc-section-number">2.3</span> Reading data from a file</a></li>
</ul></li>
<li class="has-sub"><a href="3-reading-in-data-and-drawing-some-graphs.html#reading-in-data-and-drawing-some-graphs"><span class="toc-section-number">3</span> Reading in data and drawing some graphs</a><ul>
<li><a href="3-1-orange-juice.html#orange-juice"><span class="toc-section-number">3.1</span> Orange juice</a></li>
<li><a href="3-2-making-soap.html#making-soap"><span class="toc-section-number">3.2</span> Making soap</a></li>
<li><a href="3-3-handling-shipments.html#handling-shipments"><span class="toc-section-number">3.3</span> Handling shipments</a></li>
</ul></li>
<li class="has-sub"><a href="4-data-exploration.html#data-exploration"><span class="toc-section-number">4</span> Data exploration</a><ul>
<li><a href="4-1-north-carolina-births.html#north-carolina-births"><span class="toc-section-number">4.1</span> North Carolina births</a></li>
<li><a href="4-2-more-about-the-nc-births.html#more-about-the-nc-births"><span class="toc-section-number">4.2</span> More about the NC births</a></li>
<li><a href="4-3-nenana-alaska.html#nenana-alaska"><span class="toc-section-number">4.3</span> Nenana, Alaska</a></li>
<li><a href="4-4-computerized-accounting.html#computerized-accounting"><span class="toc-section-number">4.4</span> Computerized accounting</a></li>
</ul></li>
<li class="has-sub"><a href="5-one-sample-inference.html#one-sample-inference"><span class="toc-section-number">5</span> One-sample inference</a><ul>
<li><a href="5-1-hunter-gatherers-in-australia.html#hunter-gatherers-in-australia"><span class="toc-section-number">5.1</span> Hunter-gatherers in Australia</a></li>
<li><a href="5-2-length-of-gestation-in-north-carolina.html#length-of-gestation-in-north-carolina"><span class="toc-section-number">5.2</span> Length of gestation in North Carolina</a></li>
<li><a href="5-3-inferring-ice-break-up-in-nenana.html#inferring-ice-break-up-in-nenana"><span class="toc-section-number">5.3</span> Inferring ice break-up in Nenana</a></li>
</ul></li>
<li class="has-sub"><a href="6-two-sample-inference.html#two-sample-inference"><span class="toc-section-number">6</span> Two-sample inference</a><ul>
<li><a href="6-1-children-and-electronic-devices.html#children-and-electronic-devices"><span class="toc-section-number">6.1</span> Children and electronic devices</a></li>
<li><a href="6-2-parking-close-to-the-curb.html#parking-close-to-the-curb"><span class="toc-section-number">6.2</span> Parking close to the curb</a></li>
</ul></li>
<li class="has-sub"><a href="7-power-and-sample-size.html#power-and-sample-size"><span class="toc-section-number">7</span> Power and sample size</a><ul>
<li><a href="7-1-simulating-power.html#simulating-power"><span class="toc-section-number">7.1</span> Simulating power</a></li>
<li><a href="7-2-calculating-power-and-sample-size-for-estimating-mean.html#calculating-power-and-sample-size-for-estimating-mean"><span class="toc-section-number">7.2</span> Calculating power and sample size for estimating mean</a></li>
<li><a href="7-3-simulating-power-for-proportions.html#simulating-power-for-proportions"><span class="toc-section-number">7.3</span> Simulating power for proportions</a></li>
</ul></li>
<li><a href="8-the-sign-test-and-moods-median-test.html#the-sign-test-and-moods-median-test"><span class="toc-section-number">8</span> The sign test and Mood’s median test</a></li>
<li><a href="9-matched-pairs-t-and-sign-test.html#matched-pairs-t-and-sign-test"><span class="toc-section-number">9</span> Matched pairs t and sign test</a></li>
<li><a href="10-normal-quantile-plots.html#normal-quantile-plots"><span class="toc-section-number">10</span> Normal quantile plots</a></li>
</ul>
</div>
</div>
</div>
<div class="row">
<div class="col-sm-12">
<div id="computerized-accounting" class="section level2">
<h2><span class="header-section-number">4.4</span> Computerized accounting</h2>
<p>Beginning accounting students need to
learn to learn to audit in a computerized environment. A sample of
beginning accounting students took each of two tests: the Computer
Attitude Scale (CAS) and the Computer Anxiety Rating Scale (CARS). A
higher score in each indicates greater anxiety around computers. The test scores are scaled to be between 0 and 5. Also
noted was each student’s gender. The data are in
<a href="http://www.utsc.utoronto.ca/~butler/c32/compatt.txt" class="uri">http://www.utsc.utoronto.ca/~butler/c32/compatt.txt</a>. The data values are separated by spaces.</p>
<ol style="list-style-type: lower-alpha">
<li>Read the data into R. Do you have what you expected? Explain briefly.</li>
</ol>
<p>Solution</p>
<p>Read in and display the data. This, I think, is the easiest way.</p>
<div class="sourceCode" id="cb126"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb126-1" data-line-number="1">url=<span class="st">&quot;http://www.utsc.utoronto.ca/~butler/c32/compatt.txt&quot;</span></a>
<a class="sourceLine" id="cb126-2" data-line-number="2">anxiety=<span class="kw">read_delim</span>(url,<span class="st">&quot; &quot;</span>)</a></code></pre></div>
<pre><code>## Parsed with column specification:
## cols(
##   gender = col_character(),
##   CAS = col_double(),
##   CARS = col_double()
## )</code></pre>
<div class="sourceCode" id="cb128"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb128-1" data-line-number="1">anxiety</a></code></pre></div>
<pre><code>## # A tibble: 35 x 3
##    gender   CAS  CARS
##    &lt;chr&gt;  &lt;dbl&gt; &lt;dbl&gt;
##  1 female  2.85  2.9 
##  2 male    2.6   2.32
##  3 female  2.2   1   
##  4 male    2.65  2.58
##  5 male    2.6   2.58
##  6 male    3.2   3.05
##  7 male    3.65  3.74
##  8 female  2.55  1.9 
##  9 male    3.15  3.32
## 10 male    2.8   2.74
## # ... with 25 more rows</code></pre>
<p>There is a total of 35 students with a CAS score, a CARS score and a
gender recorded for each. This is in line with what I was
expecting. (You can also note that the genders appear to be a mixture
of males and females.)</p>
<ol start="2" style="list-style-type: lower-alpha">
<li>How many males and females were there in the sample?</li>
</ol>
<p>Solution</p>
<p>Most easily <code>count</code>:</p>
<div class="sourceCode" id="cb130"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb130-1" data-line-number="1">anxiety <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">count</span>(gender)</a></code></pre></div>
<pre><code>## # A tibble: 2 x 2
##   gender     n
##   &lt;chr&gt;  &lt;int&gt;
## 1 female    15
## 2 male      20</code></pre>
<p>This also works (and is therefore good):</p>
<div class="sourceCode" id="cb132"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb132-1" data-line-number="1">anxiety <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">group_by</span>(gender) <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">summarize</span>(<span class="dt">count=</span><span class="kw">n</span>())</a></code></pre></div>
<pre><code>## # A tibble: 2 x 2
##   gender count
##   &lt;chr&gt;  &lt;int&gt;
## 1 female    15
## 2 male      20</code></pre>
<p>I want you to use R to do the counting (that is, don’t just list out
the whole data set with <code>print(n=Inf)</code> and count the males and
females yourself). This is because you might have thousands of data
values and you need to learn how to get R (or, later, SAS) to count them for
you.</p>
<p>15 females and 20 males, <em>which you should say</em>. I made a point
of <em>not</em> saying that it is enough to get the output with the
answers on it, so you need to tell me what the answer is.</p>
<ol start="3" style="list-style-type: lower-alpha">
<li>Do the CAS scores tend to be higher for females or for males? Draw a suitable graph to help you decide, and come to a conclusion.</li>
</ol>
<p>Solution</p>
<p>Gender is categorical and CAS score is quantitative, so a boxplot would appear to be the thing:</p>
<div class="sourceCode" id="cb134"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb134-1" data-line-number="1"><span class="kw">ggplot</span>(anxiety,<span class="kw">aes</span>(<span class="dt">x=</span>gender,<span class="dt">y=</span>CAS))<span class="op">+</span><span class="kw">geom_boxplot</span>()</a></code></pre></div>
<p><img src="03-data-summaries_files/figure-html/unnamed-chunk-43-1.png" width="672"  /></p>
<p>The median for males is slightly higher, so male accountants are more anxious around computers than female accountants are.</p>
<p>If you wish, side-by-side (or, better, above-and-below) histograms
would also work:</p>
<div class="sourceCode" id="cb135"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb135-1" data-line-number="1"><span class="kw">ggplot</span>(anxiety,<span class="kw">aes</span>(<span class="dt">x=</span>CAS))<span class="op">+</span><span class="kw">geom_histogram</span>(<span class="dt">bins=</span><span class="dv">6</span>)<span class="op">+</span></a>
<a class="sourceLine" id="cb135-2" data-line-number="2"><span class="kw">facet_wrap</span>(<span class="op">~</span>gender,<span class="dt">ncol=</span><span class="dv">1</span>)</a></code></pre></div>
<p><img src="03-data-summaries_files/figure-html/unnamed-chunk-44-1.png" width="672"  /></p>
<p>If you go this way, you have to make a call about where the centres of the histograms are. I guess the male one is slightly further to the right, but it’s not so easy to tell. (Make a call.)</p>
<ol start="4" style="list-style-type: lower-alpha">
<li>Find the median CAS scores for each gender. Does this support what you saw on your plot? Explain briefly.</li>
</ol>
<p>Solution</p>
<p>Group-by and summarize:</p>
<div class="sourceCode" id="cb136"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb136-1" data-line-number="1">anxiety <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">group_by</span>(gender) <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">summarize</span>(<span class="dt">med=</span><span class="kw">median</span>(CAS))</a></code></pre></div>
<pre><code>## # A tibble: 2 x 2
##   gender   med
##   &lt;chr&gt;  &lt;dbl&gt;
## 1 female  2.55
## 2 male    2.85</code></pre>
<p>The median is a bit higher for males, which is what I got on my
boxplot (and is apparently the same thing as is on the histograms, but
it’s harder to be sure there).</p>
<ol start="5" style="list-style-type: lower-alpha">
<li>Find the mean and standard deviation of both CAS and CARS scores (for all the students combined, ie. not separated by gender) <em>without</em> naming those columns explicitly.</li>
</ol>
<p>Solution</p>
<p>Without naming them explicitly means using some other way to pick them out of the data frame, either <code>summarize\_if</code> or <code>summarize\_at</code>. To do it the first way, ask what these two columns have in common: they are the only two numeric (quantitative) columns:</p>
<div class="sourceCode" id="cb138"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb138-1" data-line-number="1">anxiety <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">summarize_if</span>(is.numeric,<span class="kw">funs</span>(mean,sd))</a></code></pre></div>
<pre><code>## # A tibble: 1 x 4
##   CAS_mean CARS_mean CAS_sd CARS_sd
##      &lt;dbl&gt;     &lt;dbl&gt;  &lt;dbl&gt;   &lt;dbl&gt;
## 1     2.82      2.77  0.484   0.671</code></pre>
<p>Or the second way, asking yourself what the <em>names</em> of those columns have in common: they start with C and the gender column doesn’t:</p>
<div class="sourceCode" id="cb140"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb140-1" data-line-number="1">anxiety <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">summarize_at</span>(<span class="kw">vars</span>(<span class="kw">starts_with</span>(<span class="st">&quot;C&quot;</span>)),<span class="kw">funs</span>(mean,sd))</a></code></pre></div>
<pre><code>## # A tibble: 1 x 4
##   CAS_mean CARS_mean CAS_sd CARS_sd
##      &lt;dbl&gt;     &lt;dbl&gt;  &lt;dbl&gt;   &lt;dbl&gt;
## 1     2.82      2.77  0.484   0.671</code></pre>
<p>Either of these is good, or anything equivalent (like noting that the two anxiety scales both <code>ends\_with</code> S):</p>
<div class="sourceCode" id="cb142"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb142-1" data-line-number="1">anxiety <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">summarize_at</span>(<span class="kw">vars</span>(<span class="kw">ends_with</span>(<span class="st">&quot;S&quot;</span>)),<span class="kw">funs</span>(mean,sd))</a></code></pre></div>
<pre><code>## # A tibble: 1 x 4
##   CAS_mean CARS_mean CAS_sd CARS_sd
##      &lt;dbl&gt;     &lt;dbl&gt;  &lt;dbl&gt;   &lt;dbl&gt;
## 1     2.82      2.77  0.484   0.671</code></pre>
<p>Because I didn’t say otherwise, you should tell me what the means and SDs are, rounding off suitably: the CAS scores have mean 2.82 and SD 0.48, and the CARS scores have mean 2.77 and SD 0.67.</p>
<p>Yet another way to do it is to select the columns you want first (which
you can do by number so as not to name them), and then find the mean
and SD of all of them. This uses two tools that we haven’t seen yet:</p>
<div class="sourceCode" id="cb144"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb144-1" data-line-number="1">anxiety <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">select</span>(<span class="dv">2</span><span class="op">:</span><span class="dv">3</span>) <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">summarize_all</span>(<span class="kw">funs</span>(mean,sd))</a></code></pre></div>
<pre><code>## # A tibble: 1 x 4
##   CAS_mean CARS_mean CAS_sd CARS_sd
##      &lt;dbl&gt;     &lt;dbl&gt;  &lt;dbl&gt;   &lt;dbl&gt;
## 1     2.82      2.77  0.484   0.671</code></pre>
<p>This doesn’t work:</p>
<div class="sourceCode" id="cb146"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb146-1" data-line-number="1"><span class="kw">summary</span>(anxiety)</a></code></pre></div>
<pre><code>##     gender               CAS             CARS      
##  Length:35          Min.   :1.800   Min.   :1.000  
##  Class :character   1st Qu.:2.575   1st Qu.:2.445  
##  Mode  :character   Median :2.800   Median :2.790  
##                     Mean   :2.816   Mean   :2.771  
##                     3rd Qu.:3.150   3rd Qu.:3.290  
##                     Max.   :3.750   Max.   :4.000</code></pre>
<p>because, although it gets the means, it does not get the standard
deviations. (I added the SD to the original question to make you find
a way other than this.)</p>
<p>In summary, find a way to get those answers without naming those
columns in your code, and I’m good.</p>
<p>In case you were wondering about how to do this separately by gender, well, put the <code>group\_by</code> in like you did before:</p>
<div class="sourceCode" id="cb148"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb148-1" data-line-number="1">anxiety <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">group_by</span>(gender) <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb148-2" data-line-number="2"><span class="kw">summarize_if</span>(is.numeric,<span class="kw">funs</span>(mean,sd))</a></code></pre></div>
<pre><code>## # A tibble: 2 x 5
##   gender CAS_mean CARS_mean CAS_sd CARS_sd
##   &lt;chr&gt;     &lt;dbl&gt;     &lt;dbl&gt;  &lt;dbl&gt;   &lt;dbl&gt;
## 1 female     2.64      2.51  0.554   0.773
## 2 male       2.94      2.96  0.390   0.525</code></pre>
<p>or</p>
<div class="sourceCode" id="cb150"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb150-1" data-line-number="1">anxiety <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">group_by</span>(gender) <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb150-2" data-line-number="2"><span class="kw">summarize_at</span>(<span class="kw">vars</span>(<span class="kw">starts_with</span>(<span class="st">&quot;C&quot;</span>)),<span class="kw">funs</span>(mean,sd))</a></code></pre></div>
<pre><code>## # A tibble: 2 x 5
##   gender CAS_mean CARS_mean CAS_sd CARS_sd
##   &lt;chr&gt;     &lt;dbl&gt;     &lt;dbl&gt;  &lt;dbl&gt;   &lt;dbl&gt;
## 1 female     2.64      2.51  0.554   0.773
## 2 male       2.94      2.96  0.390   0.525</code></pre>
<p>The male means are slightly higher on both tests, but the male
standard deviations are a little smaller.
You might be wondering whether the test scores are related. They are both quantitative, so the obvious way to find out is a scatterplot:</p>
<div class="sourceCode" id="cb152"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb152-1" data-line-number="1"><span class="kw">ggplot</span>(anxiety,<span class="kw">aes</span>(<span class="dt">x=</span>CAS,<span class="dt">y=</span>CARS))<span class="op">+</span><span class="kw">geom_point</span>()</a></code></pre></div>
<p><img src="03-data-summaries_files/figure-html/unnamed-chunk-53-1.png" width="672"  /></p>
<p>The two variables can be on either axis, since there is no obvious
response or explanatory variable. A higher score on one scale goes
with a higher score on the other, suggesting that the two scales are
measuring the same thing.</p>
<p>This plot mixes up the males and females, so you might like to distinguish them, which goes like this:</p>
<div class="sourceCode" id="cb153"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb153-1" data-line-number="1"><span class="kw">ggplot</span>(anxiety,<span class="kw">aes</span>(<span class="dt">x=</span>CAS,<span class="dt">y=</span>CARS,<span class="dt">colour=</span>gender))<span class="op">+</span><span class="kw">geom_point</span>()</a></code></pre></div>
<p><img src="03-data-summaries_files/figure-html/unnamed-chunk-54-1.png" width="672"  /></p>
<p>There is a slight (but only slight) tendency for the males to be up
and to the right, and for the females to be down and to the left. This
is about what you would expect, given that the male means are slightly
bigger on both scores, but the difference in means is not that big
compared to the SD.</p>

</div>
<!-- </div> -->
<p style="text-align: center;">
<a href="4-3-nenana-alaska.html"><button class="btn btn-default">Previous</button></a>
<a href="5-one-sample-inference.html"><button class="btn btn-default">Next</button></a>
</p>
</div>
</div>



</body>
</html>
