<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">

<head>

<meta charset="utf-8">
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<meta name="generator" content="pandoc" />
<meta name="viewport" content="width=device-width, initial-scale=1">
<meta property="og:title" content="Problems and Solutions in Applied Statistics" />
<meta property="og:type" content="book" />
<meta property="og:url" content="<a href="http://ritsokiguess.site/pasias" class="uri">http://ritsokiguess.site/pasias</a>" />

<meta property="og:description" content="A set of problems and solutions, in R, on various parts of applied statistics" />
<meta name="github-repo" content="nxskok/pasias" />

<meta name="author" content="Ken Butler" />

<meta name="date" content="2019-01-07" />

<script type="text/x-mathjax-config">
MathJax.Hub.Config({
  TeX: { equationNumbers: { autoNumber: "AMS" } }
});
</script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.2/MathJax.js?config=TeX-AMS_CHTML-full" type="text/javascript"></script>

<meta name="description" content="A set of problems and solutions, in R, on various parts of applied statistics">

<title>Problems and Solutions in Applied Statistics</title>

<link href="libs/tufte-css-2015.12.29/tufte-fonts.css" rel="stylesheet" />
<link href="libs/tufte-css-2015.12.29/tufte-background.css" rel="stylesheet" />
<link href="libs/tufte-css-2015.12.29/tufte-italics.css" rel="stylesheet" />
<link href="libs/tufte-css-2015.12.29/tufte.css" rel="stylesheet" />


<style type="text/css">code{white-space: pre;}</style>
<style type="text/css">
a.sourceLine { display: inline-block; line-height: 1.25; }
a.sourceLine { pointer-events: none; color: inherit; text-decoration: inherit; }
a.sourceLine:empty { height: 1.2em; position: absolute; }
.sourceCode { overflow: visible; }
code.sourceCode { white-space: pre; position: relative; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
code.sourceCode { white-space: pre-wrap; }
a.sourceLine { text-indent: -1em; padding-left: 1em; }
}
pre.numberSource a.sourceLine
  { position: relative; }
pre.numberSource a.sourceLine:empty
  { position: absolute; }
pre.numberSource a.sourceLine::before
  { content: attr(data-line-number);
    position: absolute; left: -5em; text-align: right; vertical-align: baseline;
    border: none; pointer-events: all;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {  }
@media screen {
a.sourceLine::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>


<link rel="stylesheet" href="toc.css" type="text/css" />

</head>

<body>



<div class="row">
<div class="col-sm-12">
<div id="TOC">
<ul>
<li><a href="index.html#introduction"><span class="toc-section-number">1</span> Introduction</a></li>
<li><a href="packages-used-somewhere-in-this-book.html#packages-used-somewhere-in-this-book"><span class="toc-section-number">2</span> Packages used somewhere in this book</a></li>
<li class="has-sub"><a href="bayesian-statistics-with-rstan.html#bayesian-statistics-with-rstan"><span class="toc-section-number">3</span> Bayesian Statistics with <code>rstan</code></a><ul>
<li><a href="bayesian-statistics-with-rstan.html#estimating-proportion-in-favour-from-a-survey"><span class="toc-section-number">3.1</span> Estimating proportion in favour from a survey</a></li>
<li><a href="bayesian-statistics-with-rstan.html#bayesian-regression"><span class="toc-section-number">3.2</span> Bayesian regression</a></li>
</ul></li>
<li class="has-sub"><a href="getting-used-to-r-and-r-studio.html#getting-used-to-r-and-r-studio"><span class="toc-section-number">4</span> Getting used to R and R Studio</a><ul>
<li><a href="getting-used-to-r-and-r-studio.html#getting-an-r-studio-cloud-account"><span class="toc-section-number">4.1</span> Getting an R Studio Cloud account</a></li>
<li><a href="getting-used-to-r-and-r-studio.html#getting-started"><span class="toc-section-number">4.2</span> Getting started</a></li>
<li><a href="getting-used-to-r-and-r-studio.html#reading-data-from-a-file"><span class="toc-section-number">4.3</span> Reading data from a file</a></li>
<li><a href="getting-used-to-r-and-r-studio.html#reading-files-different-ways"><span class="toc-section-number">4.4</span> Reading files different ways</a></li>
</ul></li>
<li class="has-sub"><a href="reading-in-data-and-drawing-some-graphs.html#reading-in-data-and-drawing-some-graphs"><span class="toc-section-number">5</span> Reading in data and drawing some graphs</a><ul>
<li><a href="reading-in-data-and-drawing-some-graphs.html#orange-juice"><span class="toc-section-number">5.1</span> Orange juice</a></li>
<li><a href="reading-in-data-and-drawing-some-graphs.html#making-soap"><span class="toc-section-number">5.2</span> Making soap</a></li>
<li><a href="reading-in-data-and-drawing-some-graphs.html#handling-shipments"><span class="toc-section-number">5.3</span> Handling shipments</a></li>
</ul></li>
<li class="has-sub"><a href="data-exploration.html#data-exploration"><span class="toc-section-number">6</span> Data exploration</a><ul>
<li><a href="data-exploration.html#north-carolina-births"><span class="toc-section-number">6.1</span> North Carolina births</a></li>
<li><a href="data-exploration.html#more-about-the-nc-births"><span class="toc-section-number">6.2</span> More about the NC births</a></li>
<li><a href="data-exploration.html#nenana-alaska"><span class="toc-section-number">6.3</span> Nenana, Alaska</a></li>
<li><a href="data-exploration.html#computerized-accounting"><span class="toc-section-number">6.4</span> Computerized accounting</a></li>
<li><a href="data-exploration.html#test-scores-in-two-classes"><span class="toc-section-number">6.5</span> Test scores in two classes</a></li>
</ul></li>
<li class="has-sub"><a href="one-sample-inference.html#one-sample-inference"><span class="toc-section-number">7</span> One-sample inference</a><ul>
<li><a href="one-sample-inference.html#hunter-gatherers-in-australia"><span class="toc-section-number">7.1</span> Hunter-gatherers in Australia</a></li>
<li><a href="one-sample-inference.html#buses-to-boulder"><span class="toc-section-number">7.2</span> Buses to Boulder</a></li>
<li><a href="one-sample-inference.html#length-of-gestation-in-north-carolina"><span class="toc-section-number">7.3</span> Length of gestation in North Carolina</a></li>
<li><a href="one-sample-inference.html#inferring-ice-break-up-in-nenana"><span class="toc-section-number">7.4</span> Inferring ice break-up in Nenana</a></li>
</ul></li>
<li class="has-sub"><a href="two-sample-inference.html#two-sample-inference"><span class="toc-section-number">8</span> Two-sample inference</a><ul>
<li><a href="two-sample-inference.html#children-and-electronic-devices"><span class="toc-section-number">8.1</span> Children and electronic devices</a></li>
<li><a href="two-sample-inference.html#parking-close-to-the-curb"><span class="toc-section-number">8.2</span> Parking close to the curb</a></li>
<li><a href="two-sample-inference.html#bell-peppers-and-too-much-water"><span class="toc-section-number">8.3</span> Bell peppers and too much water</a></li>
<li><a href="two-sample-inference.html#exercise-and-anxiety-and-bullying-mice"><span class="toc-section-number">8.4</span> Exercise and anxiety and bullying mice</a></li>
<li><a href="two-sample-inference.html#diet-and-growth-in-boys"><span class="toc-section-number">8.5</span> Diet and growth in boys</a></li>
</ul></li>
<li class="has-sub"><a href="power-and-sample-size.html#power-and-sample-size"><span class="toc-section-number">9</span> Power and sample size</a><ul>
<li><a href="power-and-sample-size.html#simulating-power"><span class="toc-section-number">9.1</span> Simulating power</a></li>
<li><a href="power-and-sample-size.html#calculating-power-and-sample-size-for-estimating-mean"><span class="toc-section-number">9.2</span> Calculating power and sample size for estimating mean</a></li>
<li><a href="power-and-sample-size.html#simulating-power-for-proportions"><span class="toc-section-number">9.3</span> Simulating power for proportions</a></li>
</ul></li>
<li class="has-sub"><a href="the-sign-test-and-moods-median-test.html#the-sign-test-and-moods-median-test"><span class="toc-section-number">10</span> The sign test and Mood’s median test</a><ul>
<li><a href="the-sign-test-and-moods-median-test.html#running-a-maze"><span class="toc-section-number">10.1</span> Running a maze</a></li>
<li><a href="the-sign-test-and-moods-median-test.html#chocolate-chips"><span class="toc-section-number">10.2</span> Chocolate chips</a></li>
<li><a href="the-sign-test-and-moods-median-test.html#the-power-of-the-sign-test"><span class="toc-section-number">10.3</span> The power of the sign test</a></li>
<li><a href="the-sign-test-and-moods-median-test.html#sugar-in-breakfast-cereals"><span class="toc-section-number">10.4</span> Sugar in breakfast cereals</a></li>
<li><a href="the-sign-test-and-moods-median-test.html#fear-of-math"><span class="toc-section-number">10.5</span> Fear of math</a></li>
<li><a href="the-sign-test-and-moods-median-test.html#medical-instructions"><span class="toc-section-number">10.6</span> Medical instructions</a></li>
</ul></li>
<li class="has-sub"><a href="matched-pairs-t-and-sign-test.html#matched-pairs-t-and-sign-test"><span class="toc-section-number">11</span> Matched pairs t and sign test</a><ul>
<li><a href="matched-pairs-t-and-sign-test.html#measuring-body-fat"><span class="toc-section-number">11.1</span> Measuring body fat</a></li>
<li><a href="matched-pairs-t-and-sign-test.html#throwing-baseballs-and-softballs"><span class="toc-section-number">11.2</span> Throwing baseballs and softballs</a></li>
<li><a href="matched-pairs-t-and-sign-test.html#throwing-baseballs-and-softballs-again"><span class="toc-section-number">11.3</span> Throwing baseballs and softballs, again</a></li>
<li><a href="matched-pairs-t-and-sign-test.html#changes-in-salary"><span class="toc-section-number">11.4</span> Changes in salary</a></li>
<li><a href="matched-pairs-t-and-sign-test.html#body-fat-revisited"><span class="toc-section-number">11.5</span> Body fat revisited</a></li>
</ul></li>
<li class="has-sub"><a href="normal-quantile-plots.html#normal-quantile-plots"><span class="toc-section-number">12</span> Normal quantile plots</a><ul>
<li><a href="normal-quantile-plots.html#lengths-of-heliconia-flowers"><span class="toc-section-number">12.1</span> Lengths of heliconia flowers</a></li>
<li><a href="normal-quantile-plots.html#ferritin-and-normality"><span class="toc-section-number">12.2</span> Ferritin and normality</a></li>
</ul></li>
<li class="has-sub"><a href="analysis-of-variance.html#analysis-of-variance"><span class="toc-section-number">13</span> Analysis of variance</a><ul>
<li><a href="analysis-of-variance.html#movie-ratings-and-lengths"><span class="toc-section-number">13.1</span> Movie ratings and lengths</a></li>
<li><a href="analysis-of-variance.html#deer-and-how-much-they-eat"><span class="toc-section-number">13.2</span> Deer and how much they eat</a></li>
<li><a href="analysis-of-variance.html#movie-ratings-again"><span class="toc-section-number">13.3</span> Movie ratings again</a></li>
<li><a href="analysis-of-variance.html#atomic-weight-of-carbon"><span class="toc-section-number">13.4</span> Atomic weight of carbon</a></li>
<li><a href="analysis-of-variance.html#can-caffeine-improve-your-performance-on-a-test"><span class="toc-section-number">13.5</span> Can caffeine improve your performance on a test?</a></li>
</ul></li>
<li class="has-sub"><a href="tidying-and-selecting-data.html#tidying-and-selecting-data"><span class="toc-section-number">14</span> Tidying and selecting data</a><ul>
<li><a href="tidying-and-selecting-data.html#tidying-the-jays-data"><span class="toc-section-number">14.1</span> Tidying the Jays data</a></li>
<li><a href="tidying-and-selecting-data.html#baseball-and-softball-spaghetti"><span class="toc-section-number">14.2</span> Baseball and softball spaghetti</a></li>
<li><a href="tidying-and-selecting-data.html#ethanol-and-sleep-time-in-rats"><span class="toc-section-number">14.3</span> Ethanol and sleep time in rats</a></li>
<li><a href="tidying-and-selecting-data.html#growth-of-tomatoes"><span class="toc-section-number">14.4</span> Growth of tomatoes</a></li>
<li><a href="tidying-and-selecting-data.html#pain-relief-in-migraine-headaches-again"><span class="toc-section-number">14.5</span> Pain relief in migraine headaches (again)</a></li>
<li><a href="tidying-and-selecting-data.html#location-species-and-disease-in-plants"><span class="toc-section-number">14.6</span> Location, species and disease in plants</a></li>
<li><a href="tidying-and-selecting-data.html#mating-songs-in-crickets"><span class="toc-section-number">14.7</span> Mating songs in crickets</a></li>
<li><a href="tidying-and-selecting-data.html#cars"><span class="toc-section-number">14.8</span> Cars</a></li>
<li><a href="tidying-and-selecting-data.html#number-1-songs"><span class="toc-section-number">14.9</span> Number 1 songs</a></li>
<li><a href="tidying-and-selecting-data.html#bikes-on-college"><span class="toc-section-number">14.10</span> Bikes on College</a></li>
<li><a href="tidying-and-selecting-data.html#feeling-the-heat"><span class="toc-section-number">14.11</span> Feeling the heat</a></li>
</ul></li>
<li class="has-sub"><a href="regression.html#regression"><span class="toc-section-number">15</span> Regression</a><ul>
<li><a href="regression.html#rainfall-in-california"><span class="toc-section-number">15.1</span> Rainfall in California</a></li>
<li><a href="regression.html#carbon-monoxide-in-cigarettes"><span class="toc-section-number">15.2</span> Carbon monoxide in cigarettes</a></li>
<li><a href="regression.html#maximal-oxygen-uptake-in-young-boys"><span class="toc-section-number">15.3</span> Maximal oxygen uptake in young boys</a></li>
<li><a href="regression.html#facebook-friends-and-grey-matter"><span class="toc-section-number">15.4</span> Facebook friends and grey matter</a></li>
<li><a href="regression.html#endogenous-nitrogen-excretion-in-carp"><span class="toc-section-number">15.5</span> Endogenous nitrogen excretion in carp</a></li>
<li><a href="regression.html#sparrowhawks"><span class="toc-section-number">15.6</span> Sparrowhawks</a></li>
<li><a href="regression.html#salaries-of-social-workers"><span class="toc-section-number">15.7</span> Salaries of social workers</a></li>
<li><a href="regression.html#predicting-volume-of-wood-in-pine-trees"><span class="toc-section-number">15.8</span> Predicting volume of wood in pine trees</a></li>
<li><a href="regression.html#tortoise-shells-and-eggs"><span class="toc-section-number">15.9</span> Tortoise shells and eggs</a></li>
<li><a href="regression.html#crickets-revisited"><span class="toc-section-number">15.10</span> Crickets revisited</a></li>
<li><a href="regression.html#roller-coasters"><span class="toc-section-number">15.11</span> Roller coasters</a></li>
<li><a href="regression.html#running-and-blood-sugar"><span class="toc-section-number">15.12</span> Running and blood sugar</a></li>
<li><a href="regression.html#calories-and-fat-in-pizza"><span class="toc-section-number">15.13</span> Calories and fat in pizza</a></li>
<li><a href="regression.html#where-should-the-fire-stations-be"><span class="toc-section-number">15.14</span> Where should the fire stations be?</a></li>
<li><a href="regression.html#being-satisfied-with-hospital"><span class="toc-section-number">15.15</span> Being satisfied with hospital</a></li>
<li><a href="regression.html#handling-shipments-of-chemicals"><span class="toc-section-number">15.16</span> Handling shipments of chemicals</a></li>
<li><a href="regression.html#salaries-of-mathematicians"><span class="toc-section-number">15.17</span> Salaries of mathematicians</a></li>
<li><a href="regression.html#predicting-gpa-of-computer-science-students"><span class="toc-section-number">15.18</span> Predicting GPA of computer science students</a></li>
</ul></li>
<li class="has-sub"><a href="dates-and-times.html#dates-and-times"><span class="toc-section-number">16</span> Dates and times</a><ul>
<li><a href="dates-and-times.html#dealing-with-dates-in-the-worcester-heart-attack-study"><span class="toc-section-number">16.1</span> Dealing with dates in the Worcester Heart Attack study</a></li>
<li><a href="dates-and-times.html#growth-of-mizuna-lettuce-seeds"><span class="toc-section-number">16.2</span> Growth of Mizuna lettuce seeds</a></li>
<li><a href="dates-and-times.html#types-of-childbirth"><span class="toc-section-number">16.3</span> Types of childbirth</a></li>
<li><a href="dates-and-times.html#wolves-and-caribou"><span class="toc-section-number">16.4</span> Wolves and caribou</a></li>
</ul></li>
<li class="has-sub"><a href="functions.html#functions"><span class="toc-section-number">17</span> Functions</a><ul>
<li><a href="functions.html#making-some-r-functions"><span class="toc-section-number">17.1</span> Making some R functions</a></li>
<li><a href="functions.html#the-collatz-sequence"><span class="toc-section-number">17.2</span> The Collatz sequence</a></li>
</ul></li>
<li class="has-sub"><a href="the-bootstrap.html#the-bootstrap"><span class="toc-section-number">18</span> The Bootstrap</a><ul>
<li><a href="the-bootstrap.html#air-conditioning-failures"><span class="toc-section-number">18.1</span> Air conditioning failures</a></li>
<li><a href="the-bootstrap.html#air-conditioning-failures-bootstrapping-the-median"><span class="toc-section-number">18.2</span> Air conditioning failures: bootstrapping the median</a></li>
</ul></li>
<li class="has-sub"><a href="logistic-regression.html#logistic-regression"><span class="toc-section-number">19</span> Logistic regression</a><ul>
<li><a href="logistic-regression.html#finding-wolf-spiders-on-the-beach"><span class="toc-section-number">19.1</span> Finding wolf spiders on the beach</a></li>
<li><a href="logistic-regression.html#killing-aphids"><span class="toc-section-number">19.2</span> Killing aphids</a></li>
<li><a href="logistic-regression.html#the-effects-of-substance-a"><span class="toc-section-number">19.3</span> The effects of Substance A</a></li>
<li><a href="logistic-regression.html#what-makes-an-animal-get-infected"><span class="toc-section-number">19.4</span> What makes an animal get infected?</a></li>
<li><a href="logistic-regression.html#the-brain-of-a-cat"><span class="toc-section-number">19.5</span> The brain of a cat</a></li>
<li><a href="logistic-regression.html#how-not-to-get-heart-disease"><span class="toc-section-number">19.6</span> How not to get heart disease</a></li>
<li><a href="logistic-regression.html#successful-breastfeeding"><span class="toc-section-number">19.7</span> Successful breastfeeding</a></li>
<li><a href="logistic-regression.html#making-it-over-the-mountains"><span class="toc-section-number">19.8</span> Making it over the mountains</a></li>
<li><a href="logistic-regression.html#who-needs-the-most-intensive-care"><span class="toc-section-number">19.9</span> Who needs the most intensive care?</a></li>
<li><a href="logistic-regression.html#go-away-and-dont-come-back"><span class="toc-section-number">19.10</span> Go away and don’t come back!</a></li>
</ul></li>
<li class="has-sub"><a href="logistic-regression-with-ordinal-or-nominal-response.html#logistic-regression-with-ordinal-or-nominal-response"><span class="toc-section-number">20</span> Logistic regression with ordinal or nominal response</a><ul>
<li><a href="logistic-regression-with-ordinal-or-nominal-response.html#do-you-like-your-mobile-phone"><span class="toc-section-number">20.1</span> Do you like your mobile phone?</a></li>
<li><a href="logistic-regression-with-ordinal-or-nominal-response.html#attitudes-towards-abortion"><span class="toc-section-number">20.2</span> Attitudes towards abortion</a></li>
<li><a href="logistic-regression-with-ordinal-or-nominal-response.html#finding-non-missing-values"><span class="toc-section-number">20.3</span> Finding non-missing values</a></li>
<li><a href="logistic-regression-with-ordinal-or-nominal-response.html#european-social-survey-and-voting"><span class="toc-section-number">20.4</span> European Social Survey and voting</a></li>
<li><a href="logistic-regression-with-ordinal-or-nominal-response.html#alligator-food"><span class="toc-section-number">20.5</span> Alligator food</a></li>
<li><a href="logistic-regression-with-ordinal-or-nominal-response.html#how-do-you-like-your-steak-the-data"><span class="toc-section-number">20.6</span> How do you like your steak – the data</a></li>
<li><a href="logistic-regression-with-ordinal-or-nominal-response.html#crimes-in-san-francisco-the-data"><span class="toc-section-number">20.7</span> Crimes in San Francisco – the data</a></li>
<li><a href="logistic-regression-with-ordinal-or-nominal-response.html#how-do-you-like-your-steak"><span class="toc-section-number">20.8</span> How do you like your steak?</a></li>
<li><a href="logistic-regression-with-ordinal-or-nominal-response.html#crimes-in-san-francisco"><span class="toc-section-number">20.9</span> Crimes in San Francisco</a></li>
<li><a href="logistic-regression-with-ordinal-or-nominal-response.html#high-school-and-beyond"><span class="toc-section-number">20.10</span> High School and Beyond</a></li>
<li><a href="logistic-regression-with-ordinal-or-nominal-response.html#what-sports-do-these-athletes-play"><span class="toc-section-number">20.11</span> What sports do these athletes play?</a></li>
</ul></li>
<li class="has-sub"><a href="survival-analysis.html#survival-analysis"><span class="toc-section-number">21</span> Survival analysis</a><ul>
<li><a href="survival-analysis.html#the-worcester-survey"><span class="toc-section-number">21.1</span> The Worcester survey</a></li>
<li><a href="survival-analysis.html#drug-treatment-programs"><span class="toc-section-number">21.2</span> Drug treatment programs</a></li>
<li><a href="survival-analysis.html#multiple-myeloma"><span class="toc-section-number">21.3</span> Multiple myeloma</a></li>
<li><a href="survival-analysis.html#ovarian-cancer"><span class="toc-section-number">21.4</span> Ovarian cancer</a></li>
</ul></li>
<li class="has-sub"><a href="analysis-of-variance-revisited.html#analysis-of-variance-revisited"><span class="toc-section-number">22</span> Analysis of variance revisited</a><ul>
<li><a href="analysis-of-variance-revisited.html#acid-rain"><span class="toc-section-number">22.1</span> Acid rain</a></li>
<li><a href="analysis-of-variance-revisited.html#treating-hay-fever"><span class="toc-section-number">22.2</span> Treating hay fever</a></li>
<li><a href="analysis-of-variance-revisited.html#focused-comparisons-of-the-effect-of-caffeine"><span class="toc-section-number">22.3</span> Focused comparisons of the effect of caffeine</a></li>
<li><a href="analysis-of-variance-revisited.html#who-studies-the-most-outside-class"><span class="toc-section-number">22.4</span> Who studies the most outside class?</a></li>
<li><a href="analysis-of-variance-revisited.html#mental-context"><span class="toc-section-number">22.5</span> Mental context</a></li>
<li><a href="analysis-of-variance-revisited.html#trying-on-shirts"><span class="toc-section-number">22.6</span> Trying on shirts</a></li>
<li><a href="analysis-of-variance-revisited.html#productivity-and-research-and-development"><span class="toc-section-number">22.7</span> Productivity and research-and-development</a></li>
<li><a href="analysis-of-variance-revisited.html#treating-leprosy"><span class="toc-section-number">22.8</span> Treating leprosy</a></li>
</ul></li>
<li class="has-sub"><a href="multivariate-analysis-of-variance.html#multivariate-analysis-of-variance"><span class="toc-section-number">23</span> Multivariate analysis of variance</a><ul>
<li><a href="multivariate-analysis-of-variance.html#fabricated-data"><span class="toc-section-number">23.1</span> Fabricated data</a></li>
<li><a href="multivariate-analysis-of-variance.html#do-characteristics-of-urine-depend-on-obesity"><span class="toc-section-number">23.2</span> Do characteristics of urine depend on obesity?</a></li>
<li><a href="multivariate-analysis-of-variance.html#how-do-height-and-weight-depend-on-sport-played-by-elite-athletes"><span class="toc-section-number">23.3</span> How do height and weight depend on sport played by elite athletes?</a></li>
</ul></li>
<li class="has-sub"><a href="repeated-measures.html#repeated-measures"><span class="toc-section-number">24</span> Repeated measures</a><ul>
<li><a href="repeated-measures.html#effect-of-drug-on-rat-weight"><span class="toc-section-number">24.1</span> Effect of drug on rat weight</a></li>
<li><a href="repeated-measures.html#social-interaction-among-old-people"><span class="toc-section-number">24.2</span> Social interaction among old people</a></li>
<li><a href="repeated-measures.html#investigating-motor-activity-in-rats"><span class="toc-section-number">24.3</span> Investigating motor activity in rats</a></li>
<li><a href="repeated-measures.html#repeated-measures-with-no-background"><span class="toc-section-number">24.4</span> Repeated measures with no background</a></li>
</ul></li>
<li class="has-sub"><a href="discriminant-analysis.html#discriminant-analysis"><span class="toc-section-number">25</span> Discriminant analysis</a><ul>
<li><a href="discriminant-analysis.html#telling-whether-a-banknote-is-real-or-counterfeit"><span class="toc-section-number">25.1</span> Telling whether a banknote is real or counterfeit</a></li>
<li><a href="discriminant-analysis.html#urine-and-obesity-what-makes-a-difference"><span class="toc-section-number">25.2</span> Urine and obesity: what makes a difference?</a></li>
<li><a href="discriminant-analysis.html#understanding-a-manova"><span class="toc-section-number">25.3</span> Understanding a MANOVA</a></li>
<li><a href="discriminant-analysis.html#what-distinguishes-people-who-do-different-jobs"><span class="toc-section-number">25.4</span> What distinguishes people who do different jobs?</a></li>
<li><a href="discriminant-analysis.html#observing-children-with-adhd"><span class="toc-section-number">25.5</span> Observing children with ADHD</a></li>
<li><a href="discriminant-analysis.html#growing-corn"><span class="toc-section-number">25.6</span> Growing corn</a></li>
<li><a href="discriminant-analysis.html#understanding-athletes-height-weight-sport-and-gender"><span class="toc-section-number">25.7</span> Understanding athletes’ height, weight, sport and gender</a></li>
</ul></li>
<li class="has-sub"><a href="cluster-analysis.html#cluster-analysis"><span class="toc-section-number">26</span> Cluster analysis</a><ul>
<li><a href="cluster-analysis.html#sites-on-the-sea-bed"><span class="toc-section-number">26.1</span> Sites on the sea bed</a></li>
<li><a href="cluster-analysis.html#dissimilarities-between-fruits"><span class="toc-section-number">26.2</span> Dissimilarities between fruits</a></li>
<li><a href="cluster-analysis.html#similarity-of-species"><span class="toc-section-number">26.3</span> Similarity of species</a></li>
<li><a href="cluster-analysis.html#rating-beer"><span class="toc-section-number">26.4</span> Rating beer</a></li>
<li><a href="cluster-analysis.html#clustering-the-swiss-bills"><span class="toc-section-number">26.5</span> Clustering the Swiss bills</a></li>
<li><a href="cluster-analysis.html#grouping-similar-cars"><span class="toc-section-number">26.6</span> Grouping similar cars</a></li>
<li><a href="cluster-analysis.html#running-jumping-and-throwing"><span class="toc-section-number">26.7</span> Running, jumping, and throwing</a></li>
<li><a href="cluster-analysis.html#bridges-in-pittsburgh"><span class="toc-section-number">26.8</span> Bridges in Pittsburgh</a></li>
<li><a href="cluster-analysis.html#clustering-the-australian-athletes"><span class="toc-section-number">26.9</span> Clustering the Australian athletes</a></li>
</ul></li>
<li class="has-sub"><a href="multidimensional-scaling.html#multidimensional-scaling"><span class="toc-section-number">27</span> Multidimensional Scaling</a><ul>
<li><a href="multidimensional-scaling.html#making-a-map-of-wisconsin"><span class="toc-section-number">27.1</span> Making a map of Wisconsin</a></li>
<li><a href="multidimensional-scaling.html#things-that-feel-similar-to-each-other"><span class="toc-section-number">27.2</span> Things that feel similar to each other</a></li>
<li><a href="multidimensional-scaling.html#confusing-letters"><span class="toc-section-number">27.3</span> Confusing letters</a></li>
<li><a href="multidimensional-scaling.html#more-beer-please"><span class="toc-section-number">27.4</span> More beer please</a></li>
<li><a href="multidimensional-scaling.html#feeling-similar-again"><span class="toc-section-number">27.5</span> Feeling similar, again</a></li>
</ul></li>
<li class="has-sub"><a href="principal-components-and-factor-analysis.html#principal-components-and-factor-analysis"><span class="toc-section-number">28</span> Principal Components and Factor Analysis</a><ul>
<li><a href="principal-components-and-factor-analysis.html#the-weather-somewhere"><span class="toc-section-number">28.1</span> The weather, somewhere</a></li>
<li><a href="principal-components-and-factor-analysis.html#air-pollution"><span class="toc-section-number">28.2</span> Air pollution</a></li>
<li><a href="principal-components-and-factor-analysis.html#a-correlation-matrix"><span class="toc-section-number">28.3</span> A correlation matrix</a></li>
<li><a href="principal-components-and-factor-analysis.html#the-interpersonal-circumplex"><span class="toc-section-number">28.4</span> The Interpersonal Circumplex</a></li>
</ul></li>
<li class="has-sub"><a href="frequency-table-analysis.html#frequency-table-analysis"><span class="toc-section-number">29</span> Frequency table analysis</a><ul>
<li><a href="frequency-table-analysis.html#college-plans"><span class="toc-section-number">29.1</span> College plans</a></li>
<li><a href="frequency-table-analysis.html#predicting-voting"><span class="toc-section-number">29.2</span> Predicting voting</a></li>
</ul></li>
</ul>
</div>
</div>
</div>
<div class="row">
<div class="col-sm-12">
<div id="analysis-of-variance" class="section level1">
<h1><span class="header-section-number">Chapter 13</span> Analysis of variance</h1>
<div class="sourceCode" id="cb934"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb934-1" data-line-number="1"><span class="kw">library</span>(tidyverse)</a></code></pre></div>
<pre><code>## Warning: package &#39;ggplot2&#39; was built under R version 3.5.3</code></pre>
<pre><code>## Warning: package &#39;tibble&#39; was built under R version 3.5.3</code></pre>
<pre><code>## Warning: package &#39;tidyr&#39; was built under R version 3.5.3</code></pre>
<pre><code>## Warning: package &#39;readr&#39; was built under R version 3.5.2</code></pre>
<pre><code>## Warning: package &#39;purrr&#39; was built under R version 3.5.3</code></pre>
<pre><code>## Warning: package &#39;dplyr&#39; was built under R version 3.5.2</code></pre>
<pre><code>## Warning: package &#39;stringr&#39; was built under R version 3.5.2</code></pre>
<pre><code>## Warning: package &#39;forcats&#39; was built under R version 3.5.1</code></pre>
<pre><code>## Warning: package &#39;survminer&#39; was built under R version 3.5.1</code></pre>
<pre><code>## Warning: package &#39;ggpubr&#39; was built under R version 3.5.1</code></pre>
<pre><code>## Warning: package &#39;magrittr&#39; was built under R version 3.5.1</code></pre>
<pre><code>## Warning: package &#39;car&#39; was built under R version 3.5.1</code></pre>
<pre><code>## Warning: package &#39;carData&#39; was built under R version 3.5.1</code></pre>
<pre><code>## Warning: package &#39;ggbiplot&#39; was built under R version 3.5.1</code></pre>
<pre><code>## Warning: package &#39;plyr&#39; was built under R version 3.5.1</code></pre>
<pre><code>## Warning: package &#39;scales&#39; was built under R version 3.5.1</code></pre>
<pre><code>## Warning: package &#39;ggrepel&#39; was built under R version 3.5.1</code></pre>
<pre><code>## Warning: package &#39;broom&#39; was built under R version 3.5.2</code></pre>
<pre><code>## Warning: package &#39;rstan&#39; was built under R version 3.5.3</code></pre>
<pre><code>## Warning: package &#39;StanHeaders&#39; was built under R version 3.5.1</code></pre>
<div id="movie-ratings-and-lengths" class="section level2">
<h2><span class="header-section-number">13.1</span> Movie ratings and lengths</h2>
<p>Before a movie is shown in theatres, it
receives a “rating” that says what kind of material it
contains. <a href="https://en.wikipedia.org/wiki/Motion_Picture_Association_of_America_film_rating_system">link</a>
explains the categories, from G (suitable for children) to R (anyone
under 17 must be accompanied by parent/guardian). In 2011, two
students collected data on the length (in minutes) and the rating
category, for 15 movies of each rating category, randomly chosen from
all the movies released that year. The data are at
<a href="http://www.utsc.utoronto.ca/~butler/c32/movie-lengths.csv">link</a>.</p>
<ol style="list-style-type: lower-alpha">
<li>Read the data into R, and display (some of) what you read in.</li>
</ol>
<p>Solution</p>
<p><code>read_csv</code>:</p>
<div class="sourceCode" id="cb955"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb955-1" data-line-number="1">my_url &lt;-<span class="st"> &quot;http://www.utsc.utoronto.ca/~butler/c32/movie-lengths.csv&quot;</span></a>
<a class="sourceLine" id="cb955-2" data-line-number="2">movies &lt;-<span class="st"> </span><span class="kw">read_csv</span>(my_url)</a></code></pre></div>
<pre><code>## Parsed with column specification:
## cols(
##   length = col_double(),
##   rating = col_character()
## )</code></pre>
<div class="sourceCode" id="cb957"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb957-1" data-line-number="1">movies</a></code></pre></div>
<pre><code>## # A tibble: 60 x 2
##    length rating
##     &lt;dbl&gt; &lt;chr&gt; 
##  1     25 G     
##  2     75 G     
##  3     88 G     
##  4     63 G     
##  5     76 G     
##  6     97 G     
##  7     68 G     
##  8     82 G     
##  9     98 G     
## 10     74 G     
## # … with 50 more rows</code></pre>
<p>Something that looks like a length in minutes, and a rating.</p>
<ol start="2" style="list-style-type: lower-alpha">
<li>Count how many movies there are of each rating.</li>
</ol>
<p>Solution</p>
<div class="sourceCode" id="cb959"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb959-1" data-line-number="1">movies <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">count</span>(rating)</a></code></pre></div>
<pre><code>## # A tibble: 4 x 2
##   rating     n
##   &lt;chr&gt;  &lt;int&gt;
## 1 G         15
## 2 PG        15
## 3 PG-13     15
## 4 R         15</code></pre>
<p>Fifteen of each rating. (It’s common to have the same number of
observations in each group, but not necessary for a one-way ANOVA.)</p>
<ol start="3" style="list-style-type: lower-alpha">
<li>Carry out an ANOVA and a Tukey
analysis (if warranted).</li>
</ol>
<p>Solution</p>
<p>ANOVA first:</p>
<div class="sourceCode" id="cb961"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb961-1" data-line-number="1">length<span class="fl">.1</span> &lt;-<span class="st"> </span><span class="kw">aov</span>(length <span class="op">~</span><span class="st"> </span>rating, <span class="dt">data =</span> movies)</a>
<a class="sourceLine" id="cb961-2" data-line-number="2"><span class="kw">summary</span>(length<span class="fl">.1</span>)</a></code></pre></div>
<pre><code>##             Df Sum Sq Mean Sq F value   Pr(&gt;F)    
## rating       3  14624    4875   11.72 4.59e-06 ***
## Residuals   56  23295     416                     
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<p>This P-value is 0.00000459, which is way less than 0.05.</p>
<p>Having rejected the null (which said “all means equal”), we now need to
do Tukey, thus:</p>
<div class="sourceCode" id="cb963"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb963-1" data-line-number="1"><span class="kw">TukeyHSD</span>(length<span class="fl">.1</span>)</a></code></pre></div>
<pre><code>##   Tukey multiple comparisons of means
##     95% family-wise confidence level
## 
## Fit: aov(formula = length ~ rating, data = movies)
## 
## $rating
##                diff        lwr       upr     p adj
## PG-G      26.333333   6.613562 46.053104 0.0044541
## PG-13-G   42.800000  23.080229 62.519771 0.0000023
## R-G       30.600000  10.880229 50.319771 0.0007379
## PG-13-PG  16.466667  -3.253104 36.186438 0.1327466
## R-PG       4.266667 -15.453104 23.986438 0.9397550
## R-PG-13  -12.200000 -31.919771  7.519771 0.3660019</code></pre>
<p>Cast your eye down the <code>p adj</code> column and look for the ones
that are significant, here the first three. These are all comparisons
with the G (“general”) movies, which are shorter on average than the
others (which are not significantly different from each other).</p>
<p>If you like, you can make a table of means to verify that:</p>
<div class="sourceCode" id="cb965"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb965-1" data-line-number="1">movies <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb965-2" data-line-number="2"><span class="st">  </span><span class="kw">group_by</span>(rating) <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb965-3" data-line-number="3"><span class="st">  </span><span class="kw">summarize</span>(<span class="dt">mean =</span> <span class="kw">mean</span>(length))</a></code></pre></div>
<pre><code>## # A tibble: 4 x 2
##   rating  mean
##   &lt;chr&gt;  &lt;dbl&gt;
## 1 G       80.6
## 2 PG     107. 
## 3 PG-13  123. 
## 4 R      111.</code></pre>
<p>When we do this problem in SAS, you’ll see the Tukey get handled a
different way, one that you might find more appealing.</p>
<ol start="4" style="list-style-type: lower-alpha">
<li>Make a graph to assess whether this ANOVA is
trustworthy. Discuss your graph and its implications briefly.</li>
</ol>
<p>Solution</p>
<p>The obvious graph is a boxplot:</p>
<div class="sourceCode" id="cb967"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb967-1" data-line-number="1"><span class="kw">ggplot</span>(movies, <span class="kw">aes</span>(<span class="dt">x =</span> rating, <span class="dt">y =</span> length)) <span class="op">+</span><span class="st"> </span><span class="kw">geom_boxplot</span>()</a></code></pre></div>
<p><img src="10-analysis-of-variance_files/figure-html/unnamed-chunk-9-1.png" width="672"  /></p>
<p>For ANOVA, we are looking for approximately normal distributions
within each group and approximately equal spreads. Without the
outliers, I would be more or less happy with that, but the G movies
have a low outlier that would pull the mean down and the PG and PG-13
movies have outliers that would pull the mean up. So a comparison of
means might make the differences look more significant than they
should. Having said that, you could also say that the ANOVA is
<em>very</em> significant, so even considering the effect of the
outliers, the differences between G and the others are still likely to
be significant.</p>
<p>Extra: the way to go if you don’t trust the ANOVA is (as for the
two-sample <span class="math inline">\(t\)</span>) the Mood’s median test. This applies to any number of
groups, and works in the same way as before:</p>
<div class="sourceCode" id="cb968"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb968-1" data-line-number="1"><span class="kw">library</span>(smmr)</a>
<a class="sourceLine" id="cb968-2" data-line-number="2"><span class="kw">median_test</span>(movies, length, rating)</a></code></pre></div>
<pre><code>## $table
##        above
## group   above below
##   G         2    13
##   PG        7     7
##   PG-13    12     3
##   R         8     6
## 
## $test
##        what        value
## 1 statistic 13.752380952
## 2        df  3.000000000
## 3   P-value  0.003262334</code></pre>
<p>Still significant, though not quite as small a P-value as before
(which echoes our thoughts about what the outliers might do to the
means). If you look at the table above the test results, you see that
the G movies are mostly shorter than the overall median, but now the
PG-13 movies are mostly <em>longer</em>. So the picture is a little
different.</p>
<p>Mood’s median test does not naturally come with something like Tukey.
What you can do is to do all the pairwise Mood’s median tests, between
each pair of groups, and then adjust to allow for your having done
several tests at once. I thought this was generally useful enough that
I put it into <code>smmr</code> under the name <code>pairwise_median_test</code>:</p>
<div class="sourceCode" id="cb970"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb970-1" data-line-number="1"><span class="kw">pairwise_median_test</span>(movies, length, rating)</a></code></pre></div>
<pre><code>## # A tibble: 6 x 4
##   g1    g2      p_value adj_p_value
##   &lt;chr&gt; &lt;chr&gt;     &lt;dbl&gt;       &lt;dbl&gt;
## 1 G     PG    0.00799      0.0479  
## 2 G     PG-13 0.0000590    0.000354
## 3 G     R     0.0106       0.0635  
## 4 PG    PG-13 0.0106       0.0635  
## 5 PG    R     0.715        1       
## 6 PG-13 R     0.273        1</code></pre>
<p>You can ignore those (adjusted) P-values rather stupidly bigger than
1. These are not significant.</p>
<p>There are two significant differences in median length: between G
movies and the two flavours of PG movies. The G movies are
significantly shorter (as you can tell from the boxplot), but the
difference between G and R movies is no longer significant (a change
from the regular ANOVA).</p>
<p>You may be puzzled by something in the boxplot: how is it that the G
movies are significantly shorter than the PG movies, but not
significantly shorter than the R movies, ? In Tukey, if the
difference in means is bigger, the P-value is
smaller.
<label for="tufte-mn-40" class="margin-toggle">⊕</label><input type="checkbox" id="tufte-mn-40" class="margin-toggle"><span class="marginnote">Actually, this doesn’t always work if the sample sizes in each group are different. If you’re comparing two small groups, it takes a <em>very large</em> difference in means to get a small P-value. But in this case the sample sizes are all the same.</span>
The resolution to this puzzle, such as it is, is that Mood’s median
test is not directly comparing the medians of the groups (despite its
name); it’s counting values above and below a <em>joint</em> median,
which might be a different story.</p>
</div>
<div id="deer-and-how-much-they-eat" class="section level2">
<h2><span class="header-section-number">13.2</span> Deer and how much they eat</h2>
<p>Do adult deer eat different amounts of food at different
times of the year? The data in
<a href="http://www.utsc.utoronto.ca/~butler/c32/deer.txt">link</a> are the weights
of food (in kilograms) consumed by randomly selected adult deer
observed at different times of the year (in February, May, August and
November). We will assume that these were different deer observed in
the different months. (If the same animals had been observed at
different times, we would have been in the domain of
“repeated measures”, which would require a different analysis,
beyond the scope
of this course.)</p>
<ol style="list-style-type: lower-alpha">
<li>Read the data into R, and calculate numbers of observations
and the median amounts of food
eaten each month.</li>
</ol>
<p>Solution</p>
<p>The usual stuff for data values separated by spaces:</p>
<div class="sourceCode" id="cb972"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb972-1" data-line-number="1">myurl &lt;-<span class="st"> &quot;http://www.utsc.utoronto.ca/~butler/c32/deer.txt&quot;</span></a>
<a class="sourceLine" id="cb972-2" data-line-number="2">deer &lt;-<span class="st"> </span><span class="kw">read_delim</span>(myurl, <span class="st">&quot; &quot;</span>)</a></code></pre></div>
<pre><code>## Parsed with column specification:
## cols(
##   month = col_character(),
##   food = col_double()
## )</code></pre>
<p>and then, recalling that <code>n()</code> is the handy way of getting the
number of observations in each group:</p>
<div class="sourceCode" id="cb974"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb974-1" data-line-number="1">deer <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb974-2" data-line-number="2"><span class="st">  </span><span class="kw">group_by</span>(month) <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb974-3" data-line-number="3"><span class="st">  </span><span class="kw">summarize</span>(<span class="dt">n =</span> <span class="kw">n</span>(), <span class="dt">med =</span> <span class="kw">median</span>(food))</a></code></pre></div>
<pre><code>## # A tibble: 4 x 3
##   month     n   med
##   &lt;chr&gt; &lt;int&gt; &lt;dbl&gt;
## 1 Aug       6  4.7 
## 2 Feb       5  4.8 
## 3 May       6  4.35
## 4 Nov       5  5.2</code></pre>
<p>When you want the number of observations <em>plus</em> some other
summaries, as here, the group-by and summarize idea is the way, using
<code>n()</code> to get the number of observations in each
group. <code>count</code> counts the number of observations per group when
you <em>only</em> have grouping variables.</p>
<p>The medians differ a bit, but it’s hard to judge without a sense of
spread, which the boxplots (next) provide. November is a bit higher
and May a bit lower.</p>
<ol start="2" style="list-style-type: lower-alpha">
<li>Make side-by-side boxplots of the amount of food eaten each
month. Comment briefly on what you see.</li>
</ol>
<p>Solution</p>
<div class="sourceCode" id="cb976"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb976-1" data-line-number="1"><span class="kw">ggplot</span>(deer, <span class="kw">aes</span>(<span class="dt">x =</span> month, <span class="dt">y =</span> food)) <span class="op">+</span><span class="st"> </span><span class="kw">geom_boxplot</span>()</a></code></pre></div>
<p><img src="10-analysis-of-variance_files/figure-html/unnamed-chunk-14-1.png" width="672"  /></p>
<p>This offers the suggestion that maybe November will be significantly
higher than the rest and May significantly lower, or at least they
will be significantly different from each other.</p>
<p>This is perhaps getting ahead of the game: we should be thinking about
spread and shape. Bear in mind that there are only 5 or 6 observations
in each group, so you won’t be able to say much about normality. In
any case, we are going to be doing a Mood’s median test, so any lack
of normality doesn’t matter (eg. perhaps that 4.4 observation in
August). Given the small sample sizes, I actually think the spreads
are quite similar.</p>
<p>Another way of looking at the data, especially with these small sample
sizes, is a “dot plot”: instead of making a boxplot for each month,
we plot the actual points for each month as if we were making a
scatterplot:</p>
<div class="sourceCode" id="cb977"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb977-1" data-line-number="1"><span class="kw">ggplot</span>(deer, <span class="kw">aes</span>(<span class="dt">x =</span> month, <span class="dt">y =</span> food)) <span class="op">+</span><span class="st"> </span><span class="kw">geom_point</span>()</a></code></pre></div>
<p><img src="10-analysis-of-variance_files/figure-html/unnamed-chunk-15-1.png" width="672"  /></p>
<p>Wait a minute. There were five deer in February and six in
August. Where did they go?</p>
<p>The problem is <em>overplotting</em>: more than one of the deer plotted
in the same place on the plot, because the amounts of food eaten were
only given to one decimal place and there were some duplicated values.
One way to solve this is to randomly
move the points around so that no two of them plot in the same
place. This is called <em>jittering</em>, and is done like this:</p>
<div class="sourceCode" id="cb978"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb978-1" data-line-number="1"><span class="kw">ggplot</span>(deer, <span class="kw">aes</span>(<span class="dt">x =</span> month, <span class="dt">y =</span> food)) <span class="op">+</span><span class="st"> </span><span class="kw">geom_jitter</span>(<span class="dt">width =</span> <span class="dv">0</span>, <span class="dt">height =</span> <span class="fl">0.05</span>)</a></code></pre></div>
<p><img src="10-analysis-of-variance_files/figure-html/unnamed-chunk-16-1.png" width="672"  /></p>
<p>Now you see all the deer, and you can see that two pairs of points in
August and one pair of points in February are close enough on the
jittered plot that they would have been the same to one decimal place.</p>
<p>I wanted to
keep the points above the months they belong to, so I only allowed vertical
jitter (that’s the <code>width</code> and <code>height</code> in the
<code>geom_jitter</code>; the width is zero so there is no horizontal
jittering).
If you like, you can colour the
months; it’s up to you whether you think that’s making the plot easier
to read, or is overkill (see my point on the facetted plots on the
2017 midterm).</p>
<p>This way you see the whole distribution for each month. Normally it’s
nicer to see the summary made by the boxplots, but here there are not
very many points. The value of 4.4 in August does look quite a bit
lower than the rest, but the other months look believably normal given
the small sample sizes. I don’t know about equal spreads (November
looks more spread out), but normality looks believable. Maybe this is
the kind of situation in which Welch’s ANOVA is a good idea. (If you
believe that the normality-with-unequal-spreads is a reasonable
assumption to make, then the Welch ANOVA will be more powerful than
the Mood’s median test, and so should be preferred.)</p>
<ol start="3" style="list-style-type: lower-alpha">
<li>Run a Mood’s median test as in lecture (ie. not using
<code>smmr</code>). What do you conclude, in the context of the data?</li>
</ol>
<p>Solution</p>
<p>To give you some practice with the mechanics, first find the
overall median:</p>
<div class="sourceCode" id="cb979"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb979-1" data-line-number="1">deer <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">summarize</span>(<span class="dt">med =</span> <span class="kw">median</span>(food))</a></code></pre></div>
<pre><code>## # A tibble: 1 x 1
##     med
##   &lt;dbl&gt;
## 1   4.7</code></pre>
<p>or</p>
<div class="sourceCode" id="cb981"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb981-1" data-line-number="1"><span class="kw">median</span>(deer<span class="op">$</span>food)</a></code></pre></div>
<pre><code>## [1] 4.7</code></pre>
<p>I like the first way because it’s the same idea as we did before, just
not differentiating by month. I think there are some observations
exactly equal to the median, which will mess things up later:</p>
<div class="sourceCode" id="cb983"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb983-1" data-line-number="1">deer <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">filter</span>(food <span class="op">==</span><span class="st"> </span><span class="fl">4.7</span>)</a></code></pre></div>
<pre><code>## # A tibble: 4 x 2
##   month  food
##   &lt;chr&gt; &lt;dbl&gt;
## 1 Feb     4.7
## 2 Feb     4.7
## 3 Aug     4.7
## 4 Aug     4.7</code></pre>
<p>There are, two in February and two in August.</p>
<p>Next, make (and save) a table of the observations within each month
that are above and below this median:</p>
<div class="sourceCode" id="cb985"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb985-1" data-line-number="1">tab1 &lt;-<span class="st"> </span><span class="kw">with</span>(deer, <span class="kw">table</span>(month, food <span class="op">&lt;</span><span class="st"> </span><span class="fl">4.7</span>))</a>
<a class="sourceLine" id="cb985-2" data-line-number="2">tab1</a></code></pre></div>
<pre><code>##      
## month FALSE TRUE
##   Aug     4    2
##   Feb     5    0
##   May     0    6
##   Nov     5    0</code></pre>
<p>or</p>
<div class="sourceCode" id="cb987"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb987-1" data-line-number="1">tab2 &lt;-<span class="st"> </span><span class="kw">with</span>(deer, <span class="kw">table</span>(month, food <span class="op">&gt;</span><span class="st"> </span><span class="fl">4.7</span>))</a>
<a class="sourceLine" id="cb987-2" data-line-number="2">tab2</a></code></pre></div>
<pre><code>##      
## month FALSE TRUE
##   Aug     4    2
##   Feb     2    3
##   May     6    0
##   Nov     0    5</code></pre>
<p>Either of these is good, but note that they are different. Two of the
February observations (the ones that were exactly 4.7) have
“switched sides”,
and (look carefully) two of the August ones also. Hence the
test results will be different, and <code>smmr</code> (later) will give
different results again:</p>
<div class="sourceCode" id="cb989"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb989-1" data-line-number="1"><span class="kw">chisq.test</span>(tab1, <span class="dt">correct =</span> F)</a></code></pre></div>
<pre><code>## Warning in chisq.test(tab1, correct = F): Chi-squared approximation may be
## incorrect</code></pre>
<pre><code>## 
##  Pearson&#39;s Chi-squared test
## 
## data:  tab1
## X-squared = 16.238, df = 3, p-value = 0.001013</code></pre>
<div class="sourceCode" id="cb992"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb992-1" data-line-number="1"><span class="kw">chisq.test</span>(tab2, <span class="dt">correct =</span> F)</a></code></pre></div>
<pre><code>## Warning in chisq.test(tab2, correct = F): Chi-squared approximation may be
## incorrect</code></pre>
<pre><code>## 
##  Pearson&#39;s Chi-squared test
## 
## data:  tab2
## X-squared = 11.782, df = 3, p-value = 0.008168</code></pre>
<p>The warnings are because of the small frequencies. If you’ve done
these by hand before (which you will have if you took PSYC08), you’ll
remember that thing about “expected frequencies less than 5”. This
is that. It means “don’t take those P-values <em>too</em> seriously.”</p>
<p>The P-values are different, but they are both clearly significant, so the
median amounts of food eaten in the different months are not all the
same. (This is the same “there are differences” that you get from an
ANOVA, which you would follow up with Tukey.) Despite the injunction
not to take the P-values too seriously, I think these are small enough
that they could be off by a bit without affecting the conclusion.</p>
<p>The first table came out with a smaller P-value because it looked more
extreme: all of the February measurements were taken as higher than
the overall median (since we were counting “strictly less” and
“the rest”). In the second table, the February measurements look more
evenly split, so the overall P-value is not quite so small.</p>
<p>You can make a guess as to what <code>smmr</code> will come out with
(next), since it throws away any data values exactly equal to the median.</p>
<ol start="4" style="list-style-type: lower-alpha">
<li>Run a Mood’s median test using <code>smmr</code>, and compare the
results with the previous part.</li>
</ol>
<p>Solution</p>
<p>Off we go:</p>
<div class="sourceCode" id="cb995"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb995-1" data-line-number="1"><span class="kw">library</span>(smmr)</a>
<a class="sourceLine" id="cb995-2" data-line-number="2"><span class="kw">median_test</span>(deer, food, month)</a></code></pre></div>
<pre><code>## $table
##      above
## group above below
##   Aug     2     2
##   Feb     3     0
##   May     0     6
##   Nov     5     0
## 
## $test
##        what        value
## 1 statistic 13.950000000
## 2        df  3.000000000
## 3   P-value  0.002974007</code></pre>
<p>The P-value came out in between the other two, but the conclusion is
the same all three ways: the months are not all the same in terms of
median food eaten. The researchers can then go ahead and try to figure
out <em>why</em> the animals eat different amounts in the different months.</p>
<p>You might be wondering how you could get rid of the equal-to-median
values in the build-it-yourself way. This is <code>filter</code> from
<code>dplyr</code>, which you use first:</p>
<div class="sourceCode" id="cb997"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb997-1" data-line-number="1">deer2 &lt;-<span class="st"> </span>deer <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">filter</span>(food <span class="op">!=</span><span class="st"> </span><span class="fl">4.7</span>)</a>
<a class="sourceLine" id="cb997-2" data-line-number="2">tab3 &lt;-<span class="st"> </span><span class="kw">with</span>(deer2, <span class="kw">table</span>(month, food <span class="op">&lt;</span><span class="st"> </span><span class="fl">4.7</span>))</a>
<a class="sourceLine" id="cb997-3" data-line-number="3">tab3</a></code></pre></div>
<pre><code>##      
## month FALSE TRUE
##   Aug     2    2
##   Feb     3    0
##   May     0    6
##   Nov     5    0</code></pre>
<div class="sourceCode" id="cb999"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb999-1" data-line-number="1"><span class="kw">chisq.test</span>(tab3)</a></code></pre></div>
<pre><code>## Warning in chisq.test(tab3): Chi-squared approximation may be incorrect</code></pre>
<pre><code>## 
##  Pearson&#39;s Chi-squared test
## 
## data:  tab3
## X-squared = 13.95, df = 3, p-value = 0.002974</code></pre>
<p>which is exactly what <code>smmr</code> does, so the answer is
identical.
<label for="tufte-mn-41" class="margin-toggle">⊕</label><input type="checkbox" id="tufte-mn-41" class="margin-toggle"><span class="marginnote">The computer scientists among you will note that I should not use equals or not-equals to compare a decimal floating-point number, since decimal numbers are not represented exactly in the computer. R, however, is ahead of us here, since when you try to do food not equal to 4.7, it tests whether food is more than a small distance away from 4.7, which is the right way to do it. In R, therefore, code like my <em>food != 4.7</em> does exactly what I want, but in something like C, it <em>does not</em>, and you have to be more careful: <em>abs(food-4.7)&gt;1e-8</em>, or something like that. The small number <em>1e-8</em> is typically equal to <strong>machine epsilon</strong>, the smallest number on a computer that is distinguishable from zero.</span>
How would an ANOVA come out here? My guess is, very similarly:</p>
<div class="sourceCode" id="cb1002"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb1002-1" data-line-number="1">deer<span class="fl">.1</span> &lt;-<span class="st"> </span><span class="kw">aov</span>(food <span class="op">~</span><span class="st"> </span>month, <span class="dt">data =</span> deer)</a>
<a class="sourceLine" id="cb1002-2" data-line-number="2"><span class="kw">summary</span>(deer<span class="fl">.1</span>)</a></code></pre></div>
<pre><code>##             Df Sum Sq Mean Sq F value   Pr(&gt;F)    
## month        3 2.3065  0.7688   22.08 2.94e-06 ***
## Residuals   18 0.6267  0.0348                     
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<div class="sourceCode" id="cb1004"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb1004-1" data-line-number="1"><span class="kw">TukeyHSD</span>(deer<span class="fl">.1</span>)</a></code></pre></div>
<pre><code>##   Tukey multiple comparisons of means
##     95% family-wise confidence level
## 
## Fit: aov(formula = food ~ month, data = deer)
## 
## $month
##               diff         lwr        upr     p adj
## Feb-Aug  0.1533333 -0.16599282  0.4726595 0.5405724
## May-Aug -0.3333333 -0.63779887 -0.0288678 0.0290758
## Nov-Aug  0.5733333  0.25400718  0.8926595 0.0004209
## May-Feb -0.4866667 -0.80599282 -0.1673405 0.0021859
## Nov-Feb  0.4200000  0.08647471  0.7535253 0.0109631
## Nov-May  0.9066667  0.58734052  1.2259928 0.0000013</code></pre>
<p>The conclusion is the same, but the P-value on the <span class="math inline">\(F\)</span>-test is much
smaller. I think this is because the <span class="math inline">\(F\)</span>-test uses the actual values,
rather than just whether they are bigger or smaller than 4.7. The
Tukey says that all the months are different in terms of (now) mean,
except for February and August, which were those two very similar ones
on the boxplot.</p>
<ol start="5" style="list-style-type: lower-alpha">
<li>How is it that Mood’s median test does not completely answer the
question you really want to answer? How might you get an answer to the
question you <em>really</em> want answered? Explain briefly, and obtain
the answer you <em>really</em> want, discussing your results briefly.</li>
</ol>
<p>Solution</p>
<p>That’s rather a lot, so let’s take those things one at a
time.
<label for="tufte-mn-42" class="margin-toggle">⊕</label><input type="checkbox" id="tufte-mn-42" class="margin-toggle"><span class="marginnote">Most of these parts are old from assignment questions that I actually asked a previous class to do, but not this part. I added it later.</span></p>
<p>Mood’s median test is really like the <span class="math inline">\(F\)</span>-test in ANOVA: it’s testing
the null hypothesis
that the groups (months) all have the same median (of food eaten),
against the alternative that the null is not true. We rejected this
null, but we don’t know which months differ significantly from
which. To resolve this in ANOVA, we do Tukey (or Games-Howell if we
did the Welch ANOVA). The corresponding thing here is to do all the
possible two-group Mood tests on all the pairs of groups, and, after
adjusting for doing (here) six tests at once, look at the adjusted
P-values to see how the months differ in terms of food eaten.</p>
<p>This is accomplished in <code>smmr</code> via <code>pairwise_median_test</code>,
thus:</p>
<div class="sourceCode" id="cb1006"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb1006-1" data-line-number="1"><span class="kw">pairwise_median_test</span>(deer, food, month)</a></code></pre></div>
<pre><code>## # A tibble: 6 x 4
##   g1    g2    p_value adj_p_value
##   &lt;chr&gt; &lt;chr&gt;   &lt;dbl&gt;       &lt;dbl&gt;
## 1 Aug   Feb   0.147       0.884  
## 2 Aug   May   0.0209      0.126  
## 3 Aug   Nov   0.00270     0.0162 
## 4 Feb   May   0.00157     0.00939
## 5 Feb   Nov   0.0578      0.347  
## 6 May   Nov   0.00157     0.00939</code></pre>
<p>This compares each month with each other month. Looking at the last
column, there are only three significant differences: August-November,
February-May and May-November. Going back to the table of medians we
made in (a), November is significantly higher (in terms of median food
eaten) than August and May (but not February), and February is
significantly higher than May. The other differences are not big
enough to be significant.</p>
<p>Extra: Pairwise median tests done this way are not likely to be very
sensitive (that is, powerful), for a couple of reasons: (i) the usual
one that the median tests don’t use the data very efficiently, and
(ii) the way I go from the unadjusted to the adjusted P-values is via
Bonferroni (here, multiply the P-values by 6), which is known to be
safe but conservative. This is why the Tukey produced more significant
differences among the months than the pairwise median tests did.</p>
</div>
<div id="movie-ratings-again" class="section level2">
<h2><span class="header-section-number">13.3</span> Movie ratings again</h2>
<p>This question again uses the movie rating data at
<a href="http://www.utsc.utoronto.ca/~butler/c32/movie-lengths.csv">link</a>.</p>
<ol style="list-style-type: lower-alpha">
<li>Read the data into R and obtain the number of movies of
each rating and the <em>median</em> length of movies of each rating.</li>
</ol>
<p>Solution</p>
<p>Reading in is as in the other question using these data (just copy
your code, or mine). No credit for that, since you’ve done it before.</p>
<div class="sourceCode" id="cb1008"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb1008-1" data-line-number="1">my_url &lt;-<span class="st"> &quot;http://www.utsc.utoronto.ca/~butler/c32/movie-lengths.csv&quot;</span></a>
<a class="sourceLine" id="cb1008-2" data-line-number="2">movies &lt;-<span class="st"> </span><span class="kw">read_csv</span>(my_url)</a></code></pre></div>
<pre><code>## Parsed with column specification:
## cols(
##   length = col_double(),
##   rating = col_character()
## )</code></pre>
<div class="sourceCode" id="cb1010"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb1010-1" data-line-number="1">movies</a></code></pre></div>
<pre><code>## # A tibble: 60 x 2
##    length rating
##     &lt;dbl&gt; &lt;chr&gt; 
##  1     25 G     
##  2     75 G     
##  3     88 G     
##  4     63 G     
##  5     76 G     
##  6     97 G     
##  7     68 G     
##  8     82 G     
##  9     98 G     
## 10     74 G     
## # … with 50 more rows</code></pre>
<p>Now, the actual for-credit part, which is a <code>group_by</code> and
<code>summarize</code>:</p>
<div class="sourceCode" id="cb1012"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb1012-1" data-line-number="1">movies <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb1012-2" data-line-number="2"><span class="st">  </span><span class="kw">group_by</span>(rating) <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb1012-3" data-line-number="3"><span class="st">  </span><span class="kw">summarize</span>(<span class="dt">count =</span> <span class="kw">n</span>(), <span class="dt">med =</span> <span class="kw">median</span>(length))</a></code></pre></div>
<pre><code>## # A tibble: 4 x 3
##   rating count   med
##   &lt;chr&gt;  &lt;int&gt; &lt;dbl&gt;
## 1 G         15    82
## 2 PG        15   100
## 3 PG-13     15   117
## 4 R         15   103</code></pre>
<p>The G movies have a smaller median than the others, but also the PG-13
movies seem to be longer on average (not what we found before).</p>
<ol start="2" style="list-style-type: lower-alpha">
<li>Obtain a suitable graph that assesses the assumptions for
ANOVA. Why do you think it is not reasonable to run ANOVA here? Explain
briefly.</li>
</ol>
<p>Solution</p>
<p>The graph would seem to be a boxplot, side by side for each group:</p>
<div class="sourceCode" id="cb1014"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb1014-1" data-line-number="1"><span class="kw">ggplot</span>(movies, <span class="kw">aes</span>(<span class="dt">x =</span> rating, <span class="dt">y =</span> length)) <span class="op">+</span><span class="st"> </span><span class="kw">geom_boxplot</span>()</a></code></pre></div>
<p><img src="10-analysis-of-variance_files/figure-html/unnamed-chunk-29-1.png" width="672"  /></p>
<p>We are looking for approximate normal distributions with approximately
equal spreads, which I don’t think we have: there are outliers, at the
low end for G movies, and at the high end for PG and PG-13
movies. Also, you might observe that the distribution of lengths for R
movies is skewed to the right. (Noting either the outliers or skewness
as a reason for not believing normality is enough, since all we need
is <em>one</em> way that normality fails.)</p>
<p>I think the spreads (as measured by the interquartile ranges) are
acceptably similar, but since we have rejected normality, it is a bit
late for that.</p>
<p>So I think it is far from reasonable to run an ANOVA here. In my
opinion 15 observations in each group is not enough to gain much from
the Central Limit Theorem either.</p>
<p>Extra: since part of the assumption for ANOVA is (approximate)
normality, it would also be entirely reasonable to make normal
quantile plots, one for each movie type, facetted. Remember the
process: you pretend that you are making a normal quantile plot for
all the data together, regardless of group, and then at the last
minute, you throw in a <code>facet_wrap</code>. I’ve written the code out
on three lines, so that you can see the pieces: the “what to plot”,
then the normal quantile plot part, then the facetting:</p>
<div class="sourceCode" id="cb1015"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb1015-1" data-line-number="1"><span class="kw">ggplot</span>(movies, <span class="kw">aes</span>(<span class="dt">sample =</span> length)) <span class="op">+</span></a>
<a class="sourceLine" id="cb1015-2" data-line-number="2"><span class="st">  </span><span class="kw">stat_qq</span>() <span class="op">+</span><span class="st"> </span><span class="kw">stat_qq_line</span>() <span class="op">+</span></a>
<a class="sourceLine" id="cb1015-3" data-line-number="3"><span class="st">  </span><span class="kw">facet_wrap</span>(<span class="op">~</span>rating)</a></code></pre></div>
<p><img src="10-analysis-of-variance_files/figure-html/unnamed-chunk-30-1.png" width="672"  /></p>
<p>Since there are four movie ratings, <code>facet_wrap</code> has arranged
them into a <span class="math inline">\(2\times 2\)</span> grid, which satisfyingly means that each
normal quantile plot is more or less square and thus easy to
interpret.</p>
<p>The principal problem unveiled by these plots is outliers. It looks as
if the G movies have one low outlier, the PG movies have two high
outliers, the PG-13 movies have one or maybe three high outliers
(depending on how you count them), and the R movies have none. Another
way to look at the last two is you could call them curved, with too
much bunching up at the bottom and (on PG-13) too much spread-out-ness
at the top, indicating right-skewed distributions. The distribution
of lengths of the R-rated movies is too bunched up at the bottom, but
as you would expect for a normal at the top. The R movies show the
right-skewedness in an odd way: usually this skewness shows up by
having too many high values, but this time it’s having too <em>few</em>
<em>low</em> values.</p>
<p>The assumption for ANOVA is that all four of these are at least
approximately normal (with the same spread). We found problems with
the normality on at least three of them, so we definitely have doubts
about trusting ANOVA here.</p>
<p>I could have used <code>scales=free</code> here to get a separate <span class="math inline">\(y\)</span>-axis
for each plot, but since the <span class="math inline">\(y\)</span>-axis is movie length each time, and
all four groups would be expected to have at least roughly similar
movie lengths, I left it as it was. (The other advantage of leaving
the scales the same is that you can compare spread by comparing the
slopes of the lines on these graphs; since the lines connect the
observed and theoretical quartiles, a steeper slope means a larger
IQR. Here, the R line is steepest and the PG line is flattest. Compare
this with the spreads of the boxplots.)</p>
<p>Extra extra: if you want, you can compare the normal quantile plots
with the boxplots to see whether you get the same conclusion from
both. For the G movies, the low outlier shows up both ways, and the
rest of the distribution is at least more or less normal. For the PG
movies, I’d say the distribution is basically normal except for the
highest two values (on both plots). For the PG-13 movies, only the
highest value shows up as an outlier, but the next two apparent
outliers on the normal quantile plot are at the upper end of the long
upper whisker, so the boxplot is saying “right-skewed with one upper outlier” rather than “three upper outliers”. The distribution of
the R movies is skewed right, with the bunching at the bottom showing
up as the very small lower whisker.</p>
<p>The boxplots and the normal quantile plots are basically telling the
same story in each case, but they are doing it in a slightly different
way.</p>
<ol start="3" style="list-style-type: lower-alpha">
<li>Run a Mood’s median test (use <code>smmr</code> if you
like). What do you conclude, in the context of the data?</li>
</ol>
<p>Solution</p>
<p>The smart way is to use <code>smmr</code>, since it is much easier:</p>
<div class="sourceCode" id="cb1016"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb1016-1" data-line-number="1"><span class="kw">library</span>(smmr)</a>
<a class="sourceLine" id="cb1016-2" data-line-number="2"><span class="kw">median_test</span>(movies, length, rating)</a></code></pre></div>
<pre><code>## $table
##        above
## group   above below
##   G         2    13
##   PG        7     7
##   PG-13    12     3
##   R         8     6
## 
## $test
##        what        value
## 1 statistic 13.752380952
## 2        df  3.000000000
## 3   P-value  0.003262334</code></pre>
<p>The movies do not all have the same median length, or at least one of
the rating types has movies of different median length from the
others. Or something equivalent to that. It’s the same conclusion as
for ANOVA, only with medians instead of means.</p>
<p>You can speculate about why the test came out significant.
My guess is that the G movies are shorter than
average, and that the PG-13 movies are longer than average. (We had
the first conclusion before, but not the second. This is where medians
are different from means.)</p>
<p>The easiest way to see which movie types really differ in length from
which is to do all the pairwise median tests, which is in
<code>smmr</code> thus:</p>
<div class="sourceCode" id="cb1018"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb1018-1" data-line-number="1"><span class="kw">pairwise_median_test</span>(movies, length, rating)</a></code></pre></div>
<pre><code>## # A tibble: 6 x 4
##   g1    g2      p_value adj_p_value
##   &lt;chr&gt; &lt;chr&gt;     &lt;dbl&gt;       &lt;dbl&gt;
## 1 G     PG    0.00799      0.0479  
## 2 G     PG-13 0.0000590    0.000354
## 3 G     R     0.0106       0.0635  
## 4 PG    PG-13 0.0106       0.0635  
## 5 PG    R     0.715        1       
## 6 PG-13 R     0.273        1</code></pre>
<p>The inputs for this are the same ones in the same order as for
<code>median_test</code>. (A design decision on my part, since otherwise
<em>I</em> would never have been able to remember how to run these!)
Only the first two of these are significant (look in the last
column). We can remind ourselves of the sample medians:</p>
<div class="sourceCode" id="cb1020"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb1020-1" data-line-number="1">movies <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb1020-2" data-line-number="2"><span class="st">  </span><span class="kw">group_by</span>(rating) <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb1020-3" data-line-number="3"><span class="st">  </span><span class="kw">summarize</span>(<span class="dt">count =</span> <span class="kw">n</span>(), <span class="dt">med =</span> <span class="kw">median</span>(length))</a></code></pre></div>
<pre><code>## # A tibble: 4 x 3
##   rating count   med
##   &lt;chr&gt;  &lt;int&gt; &lt;dbl&gt;
## 1 G         15    82
## 2 PG        15   100
## 3 PG-13     15   117
## 4 R         15   103</code></pre>
<p>The G movies are significantly shorter than the PG and PG-13 movies,
but not quite significantly different from the R movies. This is a
little odd, since the difference in sample medians between G and PG,
significant, is <em>less</em> than for G and R (not significant).
There are several Extras here, which you can skip if you don’t care
about the background. First, we can do the median test by hand:
This has about four steps: (i) find the median of all the data, (ii) make a
table tabulating the number of values above and below the overall
median for each group, (iii) test the table for association, (iv)
draw a conclusion.
Thus (i):</p>
<div class="sourceCode" id="cb1022"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb1022-1" data-line-number="1"><span class="kw">median</span>(movies<span class="op">$</span>length)</a></code></pre></div>
<pre><code>## [1] 100</code></pre>
<p>or</p>
<div class="sourceCode" id="cb1024"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb1024-1" data-line-number="1">movies <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">summarize</span>(<span class="dt">med =</span> <span class="kw">median</span>(length))</a></code></pre></div>
<pre><code>## # A tibble: 1 x 1
##     med
##   &lt;dbl&gt;
## 1   100</code></pre>
<p>or store it in a variable,
and then (ii):</p>
<div class="sourceCode" id="cb1026"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb1026-1" data-line-number="1">tab1 &lt;-<span class="st"> </span><span class="kw">with</span>(movies, <span class="kw">table</span>(length <span class="op">&lt;</span><span class="st"> </span><span class="dv">100</span>, rating))</a>
<a class="sourceLine" id="cb1026-2" data-line-number="2">tab1</a></code></pre></div>
<pre><code>##        rating
##          G PG PG-13  R
##   FALSE  2  8    12  9
##   TRUE  13  7     3  6</code></pre>
<p>or</p>
<div class="sourceCode" id="cb1028"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb1028-1" data-line-number="1">tab2 &lt;-<span class="st"> </span><span class="kw">with</span>(movies, <span class="kw">table</span>(length <span class="op">&gt;</span><span class="st"> </span><span class="dv">100</span>, rating))</a>
<a class="sourceLine" id="cb1028-2" data-line-number="2">tab2</a></code></pre></div>
<pre><code>##        rating
##          G PG PG-13  R
##   FALSE 13  8     3  7
##   TRUE   2  7    12  8</code></pre>
<p>These differ because there are evidently some movies of length exactly
100 minutes, and it matters whether you count <span class="math inline">\(&lt;\)</span> and <span class="math inline">\(\ge\)</span> (as in
<code>tab1</code>) or <span class="math inline">\(&gt;\)</span> and <span class="math inline">\(le\)</span> (<code>tab2</code>). Either is good.</p>
<p>Was I right about movies of length exactly 100 minutes?</p>
<div class="sourceCode" id="cb1030"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb1030-1" data-line-number="1">movies <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">filter</span>(length <span class="op">==</span><span class="st"> </span><span class="dv">100</span>)</a></code></pre></div>
<pre><code>## # A tibble: 2 x 2
##   length rating
##    &lt;dbl&gt; &lt;chr&gt; 
## 1    100 PG    
## 2    100 R</code></pre>
<p>One PG and one R. It makes a difference to the R movies, but if you
look carefully, it makes a difference to the PG movies as well,
because the False and True switch roles between <code>tab1</code> and
<code>tab2</code> (compare the G movies, for instance).
You
need to store your table in a variable because it has to get passed on
to <code>chisq.test</code> below, (iii):</p>
<div class="sourceCode" id="cb1032"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb1032-1" data-line-number="1"><span class="kw">chisq.test</span>(tab1, <span class="dt">correct =</span> F)</a></code></pre></div>
<pre><code>## 
##  Pearson&#39;s Chi-squared test
## 
## data:  tab1
## X-squared = 14.082, df = 3, p-value = 0.002795</code></pre>
<p>or</p>
<div class="sourceCode" id="cb1034"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb1034-1" data-line-number="1"><span class="kw">chisq.test</span>(tab2, <span class="dt">correct =</span> F)</a></code></pre></div>
<pre><code>## 
##  Pearson&#39;s Chi-squared test
## 
## data:  tab2
## X-squared = 13.548, df = 3, p-value = 0.003589</code></pre>
<p>Either is correct, or, actually, without the <code>correct=F</code>.
<label for="tufte-mn-43" class="margin-toggle">⊕</label><input type="checkbox" id="tufte-mn-43" class="margin-toggle"><span class="marginnote">see discussion elsewhere about Yates’ Correction and fixed margins.</span></p>
<p>The conclusion (iv) is the same either way: the null of no association
is clearly rejected (with a P-value of 0.0028 or 0.0036 as
appropriate), and therefore whether a movie is longer or shorter than
median length depends on what rating it has: that is, the median
lengths do differ among the ratings. The same conclusion, in other
words, as the <span class="math inline">\(F\)</span>-test gave, though with not quite such a small
P-value.</p>
<p>Second, you might be curious about how
we might do something like Tukey having found some significant
differences (that is, what’s lurking in the background of
<code>pairwise_median_test</code>).</p>
<p>Let’s first suppose we are comparing G and PG movies. We need
to pull out just those, and then compare them using
<code>smmr</code>. Because the first input to <code>median_test</code> is a
data frame, it fits neatly into a pipe (with the data frame omitted):</p>
<div class="sourceCode" id="cb1036"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb1036-1" data-line-number="1">movies <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb1036-2" data-line-number="2"><span class="st">  </span><span class="kw">filter</span>(rating <span class="op">==</span><span class="st"> &quot;G&quot;</span> <span class="op">|</span><span class="st"> </span>rating <span class="op">==</span><span class="st"> &quot;PG&quot;</span>) <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb1036-3" data-line-number="3"><span class="st">  </span><span class="kw">median_test</span>(length, rating)</a></code></pre></div>
<pre><code>## $table
##      above
## group above below
##    G      4    11
##    PG    10     3
## 
## $test
##        what       value
## 1 statistic 7.035897436
## 2        df 1.000000000
## 3   P-value 0.007989183</code></pre>
<p>We’re going to be doing this about six times — <span class="math inline">\({4 \choose 2}=6\)</span> choices
of two rating groups to compare out of the four — so we should have a
function to do it. I think the input to the function should be a data
frame that has a column called <code>rating</code>, and two names of
ratings to compare:</p>
<div class="sourceCode" id="cb1038"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb1038-1" data-line-number="1">comp2 &lt;-<span class="st"> </span><span class="cf">function</span>(rat_<span class="dv">1</span>, rat_<span class="dv">2</span>, d) {</a>
<a class="sourceLine" id="cb1038-2" data-line-number="2">  d <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb1038-3" data-line-number="3"><span class="st">    </span><span class="kw">filter</span>(rating <span class="op">==</span><span class="st"> </span>rat_<span class="dv">1</span> <span class="op">|</span><span class="st"> </span>rating <span class="op">==</span><span class="st"> </span>rat_<span class="dv">2</span>) <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb1038-4" data-line-number="4"><span class="st">    </span><span class="kw">median_test</span>(length, rating)</a>
<a class="sourceLine" id="cb1038-5" data-line-number="5">}</a></code></pre></div>
<p>The way I wrote this function is that you have to specify the movie
ratings in quotes. It is <em>possible</em> to write it in such a way
that you input them without quotes, <code>tidyverse</code> style, but that
gets into “non-standard evaluation” and <code>enquo()</code> and
<code>!!</code>, which (i) I have to look up every time I want to do it,
and (ii) I am feeling that the effort involved in explaining it to you
is going to exceed the benefit you will gain from it. I mastered it enough
to make it work in <code>smmr</code> (note that you specify column names
without quotes there). There are tutorials on this kind of thing if
you’re interested.</p>
<p>Anyway, testing:</p>
<div class="sourceCode" id="cb1039"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb1039-1" data-line-number="1"><span class="kw">comp2</span>(<span class="st">&quot;G&quot;</span>, <span class="st">&quot;PG&quot;</span>, movies)</a></code></pre></div>
<pre><code>## $table
##      above
## group above below
##    G      4    11
##    PG    10     3
## 
## $test
##        what       value
## 1 statistic 7.035897436
## 2        df 1.000000000
## 3   P-value 0.007989183</code></pre>
<p>That works, but I really only want to pick out the P-value, which is
in the list item <code>test</code> in the column <code>value</code>, the third
entry. So let’s rewrite the function to return just that:</p>
<div class="sourceCode" id="cb1041"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb1041-1" data-line-number="1">comp2 &lt;-<span class="st"> </span><span class="cf">function</span>(rat_<span class="dv">1</span>, rat_<span class="dv">2</span>, d) {</a>
<a class="sourceLine" id="cb1041-2" data-line-number="2">  d <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb1041-3" data-line-number="3"><span class="st">    </span><span class="kw">filter</span>(rating <span class="op">==</span><span class="st"> </span>rat_<span class="dv">1</span> <span class="op">|</span><span class="st"> </span>rating <span class="op">==</span><span class="st"> </span>rat_<span class="dv">2</span>) <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb1041-4" data-line-number="4"><span class="st">    </span><span class="kw">median_test</span>(length, rating) <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb1041-5" data-line-number="5"><span class="st">    </span><span class="kw">pluck</span>(<span class="st">&quot;test&quot;</span>, <span class="st">&quot;value&quot;</span>, <span class="dv">3</span>)</a>
<a class="sourceLine" id="cb1041-6" data-line-number="6">}</a>
<a class="sourceLine" id="cb1041-7" data-line-number="7"><span class="kw">comp2</span>(<span class="st">&quot;G&quot;</span>, <span class="st">&quot;PG&quot;</span>, movies)</a></code></pre></div>
<pre><code>## [1] 0.007989183</code></pre>
<p>Gosh.</p>
<p>What <code>median_test</code> returns is an R <code>list</code> that has two
things in it, one called <code>table</code> and one called
<code>test</code>. The thing called <code>test</code> is a data frame with a
column called <code>value</code> that contains the P-values. The third of
these is the two-sided P-value that we want.</p>
<p>You might not have seen <code>pluck</code> before. This is a way of
getting things out of complicated data structures. This one takes the
output from <code>median_test</code> and from it grabs the piece called
<code>test</code>. This is a data frame. Next, we want the column called
<code>value</code>, and from that we want the third row. These are
specified one after the other to <code>pluck</code> and it pulls out the
right thing.</p>
<p>So now our function returns just the P-value.</p>
<p>I have to say that it took me several goes and some playing around in
R Studio to sort this one out. Once I thought I understood
<code>pluck</code>, I wondered why my function was not returning a
value. And then I realized that I was saving the value inside the
function and not returning it. Ooops. The nice thing about
<code>pluck</code> is that I can put it on the end of the pipeline and and
it will pull out (and return) whatever I want it to.</p>
<p>Let’s grab a hold of the different rating groups we have:</p>
<div class="sourceCode" id="cb1043"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb1043-1" data-line-number="1">the_ratings &lt;-<span class="st"> </span><span class="kw">unique</span>(movies<span class="op">$</span>rating)</a>
<a class="sourceLine" id="cb1043-2" data-line-number="2">the_ratings</a></code></pre></div>
<pre><code>## [1] &quot;G&quot;     &quot;PG-13&quot; &quot;PG&quot;    &quot;R&quot;</code></pre>
<p>The Pythonisti among you will know how to finish this off: do a
loop-inside-a-loop over the rating groups, and get the P-value for
each pair. You can do that in R, if you must. It’s not pretty at all,
but it works:</p>
<div class="sourceCode" id="cb1045"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb1045-1" data-line-number="1">ii &lt;-<span class="st"> </span><span class="kw">character</span>(<span class="dv">0</span>)</a>
<a class="sourceLine" id="cb1045-2" data-line-number="2">jj &lt;-<span class="st"> </span><span class="kw">character</span>(<span class="dv">0</span>)</a>
<a class="sourceLine" id="cb1045-3" data-line-number="3">pp &lt;-<span class="st"> </span><span class="kw">numeric</span>(<span class="dv">0</span>)</a>
<a class="sourceLine" id="cb1045-4" data-line-number="4"><span class="cf">for</span> (i <span class="cf">in</span> the_ratings) {</a>
<a class="sourceLine" id="cb1045-5" data-line-number="5">  <span class="cf">for</span> (j <span class="cf">in</span> the_ratings) {</a>
<a class="sourceLine" id="cb1045-6" data-line-number="6">    pval &lt;-<span class="st"> </span><span class="kw">comp2</span>(i, j, movies)</a>
<a class="sourceLine" id="cb1045-7" data-line-number="7">    ii &lt;-<span class="st"> </span><span class="kw">c</span>(ii, i)</a>
<a class="sourceLine" id="cb1045-8" data-line-number="8">    jj &lt;-<span class="st"> </span><span class="kw">c</span>(jj, j)</a>
<a class="sourceLine" id="cb1045-9" data-line-number="9">    pp &lt;-<span class="st"> </span><span class="kw">c</span>(pp, pval)</a>
<a class="sourceLine" id="cb1045-10" data-line-number="10">  }</a>
<a class="sourceLine" id="cb1045-11" data-line-number="11">}</a>
<a class="sourceLine" id="cb1045-12" data-line-number="12"><span class="kw">tibble</span>(ii, jj, pp)</a></code></pre></div>
<pre><code>## # A tibble: 16 x 3
##    ii    jj           pp
##    &lt;chr&gt; &lt;chr&gt;     &lt;dbl&gt;
##  1 G     G     1        
##  2 G     PG-13 0.0000590
##  3 G     PG    0.00799  
##  4 G     R     0.0106   
##  5 PG-13 G     0.0000590
##  6 PG-13 PG-13 1        
##  7 PG-13 PG    0.0106   
##  8 PG-13 R     0.273    
##  9 PG    G     0.00799  
## 10 PG    PG-13 0.0106   
## 11 PG    PG    1        
## 12 PG    R     0.715    
## 13 R     G     0.0106   
## 14 R     PG-13 0.273    
## 15 R     PG    0.715    
## 16 R     R     1</code></pre>
<p>This is a lot of fiddling about, since you have to initialize three
vectors, and then update them every time through the loop. It’s hard
to read, because the actual business part of the loop is the
calculation of the P-value, and that’s almost hidden by all the
book-keeping. (It’s also slow and inefficient, though the slowness
doesn’t matter too much here since it’s not a very big problem.)</p>
<p>Let’s try another way:</p>
<div class="sourceCode" id="cb1047"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb1047-1" data-line-number="1"><span class="kw">crossing</span>(<span class="dt">first =</span> the_ratings, <span class="dt">second =</span> the_ratings)</a></code></pre></div>
<pre><code>## # A tibble: 16 x 2
##    first second
##    &lt;chr&gt; &lt;chr&gt; 
##  1 G     G     
##  2 G     PG    
##  3 G     PG-13 
##  4 G     R     
##  5 PG    G     
##  6 PG    PG    
##  7 PG    PG-13 
##  8 PG    R     
##  9 PG-13 G     
## 10 PG-13 PG    
## 11 PG-13 PG-13 
## 12 PG-13 R     
## 13 R     G     
## 14 R     PG    
## 15 R     PG-13 
## 16 R     R</code></pre>
<p>This does “all possible combinations” of one rating with another. We
don’t actually need all of that; we just need the ones where the first
one is (alphabetically) strictly less than the second one. This is
because we’re never comparing a rating with itself, and each pair of
ratings appears twice, once in alphabetical order, and once the other
way around. The ones we need are these:</p>
<div class="sourceCode" id="cb1049"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb1049-1" data-line-number="1"><span class="kw">crossing</span>(<span class="dt">first =</span> the_ratings, <span class="dt">second =</span> the_ratings) <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb1049-2" data-line-number="2"><span class="st">  </span><span class="kw">filter</span>(first <span class="op">&lt;</span><span class="st"> </span>second)</a></code></pre></div>
<pre><code>## # A tibble: 6 x 2
##   first second
##   &lt;chr&gt; &lt;chr&gt; 
## 1 G     PG    
## 2 G     PG-13 
## 3 G     R     
## 4 PG    PG-13 
## 5 PG    R     
## 6 PG-13 R</code></pre>
<p>A technique thing to note: instead of asking
“how do I pick out the distinct pairs of ratings?”,
I use two simpler tools: first I make
all the combinations of pairs of ratings, and then out of those, pick
the ones that are alphabetically in ascending order, which we know how
to do.</p>
<p>Now we want to call our function <code>comp2</code> for each of the things
in <code>first</code> <em>and</em> each of the things in <code>second</code>,
and make a new column called <code>pval</code> that contains exactly
that. This (coming fresh from page 332 of the R book, this being the
first time I’ve ever used it)
<label for="tufte-mn-44" class="margin-toggle">⊕</label><input type="checkbox" id="tufte-mn-44" class="margin-toggle"><span class="marginnote">This was a year ago when I first wrote this.} is exactly what the texttt{map2</span> family of functions
does. In our case, <code>comp2</code> returns a decimal number, a
<code>dbl</code>, so <code>map2_dbl</code> does it. Thus:</p>
<div class="sourceCode" id="cb1051"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb1051-1" data-line-number="1"><span class="kw">crossing</span>(<span class="dt">first =</span> the_ratings, <span class="dt">second =</span> the_ratings) <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb1051-2" data-line-number="2"><span class="st">  </span><span class="kw">filter</span>(first <span class="op">&lt;</span><span class="st"> </span>second) <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb1051-3" data-line-number="3"><span class="st">  </span><span class="kw">mutate</span>(<span class="dt">pval =</span> <span class="kw">map2_dbl</span>(first, second, <span class="op">~</span><span class="st"> </span><span class="kw">comp2</span>(.x, .y, movies)))</a></code></pre></div>
<pre><code>## # A tibble: 6 x 3
##   first second      pval
##   &lt;chr&gt; &lt;chr&gt;      &lt;dbl&gt;
## 1 G     PG     0.00799  
## 2 G     PG-13  0.0000590
## 3 G     R      0.0106   
## 4 PG    PG-13  0.0106   
## 5 PG    R      0.715    
## 6 PG-13 R      0.273</code></pre>
<p>The logic of <code>map2_dbl</code> is
“for each of the things in <code>first</code>, and each of the things in <code>second</code>, taken in parallel, call the function <code>comp2</code> with those two inputs in that order, always with data frame <code>movies</code>”.
The <code>.x</code>
and <code>.y</code> play the role of the <code>.</code> that we usually have
inside a map, but now we’re “mapping” over two things rather than
just one, so that they cannot both be called <code>.</code>.</p>
<p>One more thing: we’re doing 6 tests at once here, so we’re giving
ourselves 6 chances to reject a null (all medians equal) that might
have been true. So the true probability of a type I error is no longer
0.05 but something bigger.</p>
<p>The easiest way around that is to do a so-called Bonferroni
adjustment: instead of rejecting if the P-value is less than 0.05, we
only reject if it is less than <span class="math inline">\(0.05/6\)</span>, since we are doing 6
tests. This is a fiddly calculation to do by hand, but it’s easy to
build in another <code>mutate</code>, thus:
<label for="tufte-mn-45" class="margin-toggle">⊕</label><input type="checkbox" id="tufte-mn-45" class="margin-toggle"><span class="marginnote">In the pairwise median test in <em>smmr</em>, I did this backwards: rather than changing the alpha that you compare each P-value with from 0.05 to 0.05/6, I flip it around so that you adjust the P-values by <em>multiplying</em> them by 6, and then comparing the adjusted P-values with the usual 0.05. It comes to the same place in the end, except that this way you can get adjusted P-values that are greater than 1, which makes no sense. You read those as being definitely not significant.</span></p>
<div class="sourceCode" id="cb1053"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb1053-1" data-line-number="1"><span class="kw">crossing</span>(<span class="dt">first =</span> the_ratings, <span class="dt">second =</span> the_ratings) <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb1053-2" data-line-number="2"><span class="st">  </span><span class="kw">filter</span>(first <span class="op">&lt;</span><span class="st"> </span>second) <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb1053-3" data-line-number="3"><span class="st">  </span><span class="kw">mutate</span>(<span class="dt">pval =</span> <span class="kw">map2_dbl</span>(first, second, <span class="op">~</span><span class="st"> </span><span class="kw">comp2</span>(.x, .y, movies))) <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb1053-4" data-line-number="4"><span class="st">  </span><span class="kw">mutate</span>(<span class="dt">reject =</span> pval <span class="op">&lt;</span><span class="st"> </span><span class="fl">0.05</span> <span class="op">/</span><span class="st"> </span><span class="dv">6</span>)</a></code></pre></div>
<pre><code>## # A tibble: 6 x 4
##   first second      pval reject
##   &lt;chr&gt; &lt;chr&gt;      &lt;dbl&gt; &lt;lgl&gt; 
## 1 G     PG     0.00799   TRUE  
## 2 G     PG-13  0.0000590 TRUE  
## 3 G     R      0.0106    FALSE 
## 4 PG    PG-13  0.0106    FALSE 
## 5 PG    R      0.715     FALSE 
## 6 PG-13 R      0.273     FALSE</code></pre>
<p>And not a loop in sight.</p>
<p>This is how I coded it in <code>pairwise_median_test</code>. If you want to
check it, it’s on Github:
<a href="https://raw.githubusercontent.com/nxskok/smmr/master/R/pairwise_median_test.R">link</a>.
The function <code>median_test_pair</code> is the same as <code>comp2</code>
above.</p>
<p>So the only significant differences are now G compared to PG and
PG-13. There is not a significant difference in median movie length
between G and R, though it is a close call. We thought the PG-13
movies might have a significantly different median from other rating
groups beyond G, but they turn out not to have. (The third and fourth
comparisons would have been significant had we not made the Bonferroni
adjustment to compensate for doing six tests at once; with that
adjustment, we only reject if the P-value is less than
<span class="math inline">\(0.05/6=0.0083\)</span>, and so 0.0106 is not quite small enough to reject
with.)</p>
<p>Listing the rating groups sorted by median would give you an idea of
how far different the medians have to be to be significantly different:</p>
<div class="sourceCode" id="cb1055"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb1055-1" data-line-number="1">medians &lt;-<span class="st"> </span>movies <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb1055-2" data-line-number="2"><span class="st">  </span><span class="kw">group_by</span>(rating) <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb1055-3" data-line-number="3"><span class="st">  </span><span class="kw">summarize</span>(<span class="dt">med =</span> <span class="kw">median</span>(length)) <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb1055-4" data-line-number="4"><span class="st">  </span><span class="kw">arrange</span>(<span class="kw">desc</span>(med))</a>
<a class="sourceLine" id="cb1055-5" data-line-number="5">medians</a></code></pre></div>
<pre><code>## # A tibble: 4 x 2
##   rating   med
##   &lt;chr&gt;  &lt;dbl&gt;
## 1 PG-13    117
## 2 R        103
## 3 PG       100
## 4 G         82</code></pre>
<p>Something rather interesting has happened: even though the comparison of
G and PG (18 apart) is significant, the comparison of G and R (21
apart) is not significant. This seems very odd, but it happens because
the Mood median test is not actually literally comparing the sample
medians, but only assessing the splits of values above and below the
median of the combined sample. A subtlety, rather than an error, I’d say.</p>
<p>Here’s something extremely flashy to finish with:</p>
<div class="sourceCode" id="cb1057"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb1057-1" data-line-number="1"><span class="kw">crossing</span>(<span class="dt">first =</span> the_ratings, <span class="dt">second =</span> the_ratings) <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb1057-2" data-line-number="2"><span class="st">  </span><span class="kw">filter</span>(first <span class="op">&lt;</span><span class="st"> </span>second) <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb1057-3" data-line-number="3"><span class="st">  </span><span class="kw">mutate</span>(<span class="dt">pval =</span> <span class="kw">map2_dbl</span>(first, second, <span class="op">~</span><span class="st"> </span><span class="kw">comp2</span>(.x, .y, movies))) <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb1057-4" data-line-number="4"><span class="st">  </span><span class="kw">mutate</span>(<span class="dt">reject =</span> pval <span class="op">&lt;</span><span class="st"> </span><span class="fl">0.05</span> <span class="op">/</span><span class="st"> </span><span class="dv">6</span>) <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb1057-5" data-line-number="5"><span class="st">  </span><span class="kw">left_join</span>(medians, <span class="dt">by =</span> <span class="kw">c</span>(<span class="st">&quot;first&quot;</span> =<span class="st"> &quot;rating&quot;</span>)) <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb1057-6" data-line-number="6"><span class="st">  </span><span class="kw">left_join</span>(medians, <span class="dt">by =</span> <span class="kw">c</span>(<span class="st">&quot;second&quot;</span> =<span class="st"> &quot;rating&quot;</span>))</a></code></pre></div>
<pre><code>## # A tibble: 6 x 6
##   first second      pval reject med.x med.y
##   &lt;chr&gt; &lt;chr&gt;      &lt;dbl&gt; &lt;lgl&gt;  &lt;dbl&gt; &lt;dbl&gt;
## 1 G     PG     0.00799   TRUE      82   100
## 2 G     PG-13  0.0000590 TRUE      82   117
## 3 G     R      0.0106    FALSE     82   103
## 4 PG    PG-13  0.0106    FALSE    100   117
## 5 PG    R      0.715     FALSE    100   103
## 6 PG-13 R      0.273     FALSE    117   103</code></pre>
<p>The additional two lines look up the medians of the rating groups in
<code>first</code>, then <code>second</code>, so that you can see the actual
medians of the groups being compared each time. You see that medians
different by 30 are definitely different, ones differing by 15 or less
are definitely not different, and ones differing by about 20 could go
either way.</p>
<p>I think that’s <em>quite</em> enough of that.</p>
</div>
<div id="atomic-weight-of-carbon" class="section level2">
<h2><span class="header-section-number">13.4</span> Atomic weight of carbon</h2>
<p>The atomic weight of the chemical element
carbon is 12. Two methods of measuring the atomic weight of samples of
carbon were compared. The results are shown in
<a href="http://www.utsc.utoronto.ca/~butler/c32/carbon.txt">link</a>. The methods
are labelled 1 and 2. The first task is to find out whether the two
methods have different “typical” measures (mean or median, as
appropriate) of the atomic weight of carbon.</p>
<p>For this question, compose a report in R Markdown. (R Markdown is
what you use in an R Notebook, but you can also have a separate R
Markdown document from which you can produce HTML, Word etc. output.)
See part (a) for how to get this started.</p>
<p>Your report should
read like an actual report, not just the answers to some questions
that I set you. To help with that, write some text that links the
parts of the report together smoothly, so that it reads as a coherent
whole. The grader had 3 discretionary marks to award for the overall
quality of your writing. The scale for this was:</p>
<ul>
<li><p>3 points: excellent writing. The report flows smoothly, is easy
to read, and contains everything it should (and nothing it
shouldn’t).</p></li>
<li><p>2 points: satisfactory writing. Not the easiest to read, but
says what it should, and it looks at least somewhat like a report
rather than a string of answers to questions.</p></li>
<li><p>1 point: writing that is hard to read or to understand. If you
get this (or 0), you should consider what you need to do to improve
when you write your project.</p></li>
<li><p>0 points: you answered the questions, but you did almost nothing
to make it read like a report.</p></li>
</ul>
<ol style="list-style-type: lower-alpha">
<li>Create a new R Markdown document. To do this, in R Studio, select File,
New File, R Markdown. Type the report title and your name in the
boxes, and leave the output on the default HTML. Click OK.</li>
</ol>
<p>Solution</p>
<p>You’ll
see the title and your name in a section at the top of the document,
and below that you’ll see a template document, as you would for an R
Notebook. The difference is that where you are used to seeing
Preview, it now says “knit”, but this has the same effect of
producing the formatted version of your report.</p>
<ol start="2" style="list-style-type: lower-alpha">
<li>Write an introduction that explains the purpose of this
study and the data collected in your own words.</li>
</ol>
<p>Solution</p>
Something like this:

<p>Before that, start a new section like this:
<code>## Introduction</code>.
Also, get used to expressing your understanding in your words,
not mine. (Using my words, in this course, is likely to be
worth very little.)</p>
<ol start="3" style="list-style-type: lower-alpha">
<li>Begin an appropriately-titled new section in your report,
read the data into R and display the results.</li>
</ol>
<p>Solution</p>
<p>Values separated by spaces:</p>
<div class="sourceCode" id="cb1059"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb1059-1" data-line-number="1">my_url &lt;-<span class="st"> &quot;http://www.utsc.utoronto.ca/~butler/c32/carbon.txt&quot;</span></a>
<a class="sourceLine" id="cb1059-2" data-line-number="2">carbon &lt;-<span class="st"> </span><span class="kw">read_delim</span>(my_url, <span class="st">&quot; &quot;</span>)</a></code></pre></div>
<pre><code>## Parsed with column specification:
## cols(
##   method = col_double(),
##   weight = col_double()
## )</code></pre>
<div class="sourceCode" id="cb1061"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb1061-1" data-line-number="1">carbon</a></code></pre></div>
<pre><code>## # A tibble: 15 x 2
##    method weight
##     &lt;dbl&gt;  &lt;dbl&gt;
##  1      1   12.0
##  2      1   12.0
##  3      1   12.0
##  4      1   12.0
##  5      1   12.0
##  6      1   12.0
##  7      1   12.0
##  8      1   12.0
##  9      1   12.0
## 10      1   12.0
## 11      2   12.0
## 12      2   12.0
## 13      2   12.0
## 14      2   12.0
## 15      2   12.0</code></pre>
<p>I would expect you to include, without being told to include it, some
text in your report indicating that you have sensible data: two
methods labelled 1 and 2 as promised, and a bunch
<label for="tufte-mn-46" class="margin-toggle">⊕</label><input type="checkbox" id="tufte-mn-46" class="margin-toggle"><span class="marginnote">It’s probably better in a report to use language a bit more formal than <em>a bunch</em>. Something like <em>a number</em> would be better.</span>
of atomic
weights close to the nominal figure of 12.</p>
<ol start="4" style="list-style-type: lower-alpha">
<li>Make an appropriate plot to compare the measurements
obtained by the two methods. You might need to do something about
the two methods being given as numbers even though they are really
only identifiers. (If you do, your report ought to say what you did
and why.)</li>
</ol>
<p>Solution</p>
<p>The appropriate plot, with a categorical method and quantitative
weight, is something like a boxplot. If you’re not careful,
<code>method</code> will get treated as a quantitative variable,
which you don’t want; the easiest way around that, for a boxplot
at least, is to turn it into a factor like this:</p>
<div class="sourceCode" id="cb1063"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb1063-1" data-line-number="1"><span class="kw">ggplot</span>(carbon, <span class="kw">aes</span>(<span class="dt">x =</span> <span class="kw">factor</span>(method), <span class="dt">y =</span> weight)) <span class="op">+</span><span class="st"> </span><span class="kw">geom_boxplot</span>()</a></code></pre></div>
<p><img src="10-analysis-of-variance_files/figure-html/unnamed-chunk-54-1.png" width="672"  /></p>
<p>If you insist, you could do a faceted histogram (above and below, for preference):</p>
<div class="sourceCode" id="cb1064"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb1064-1" data-line-number="1"><span class="kw">ggplot</span>(carbon, <span class="kw">aes</span>(<span class="dt">x =</span> weight)) <span class="op">+</span><span class="st"> </span><span class="kw">geom_histogram</span>(<span class="dt">bins =</span> <span class="dv">5</span>) <span class="op">+</span></a>
<a class="sourceLine" id="cb1064-2" data-line-number="2"><span class="st">  </span><span class="kw">facet_wrap</span>(<span class="op">~</span>method, <span class="dt">ncol =</span> <span class="dv">1</span>)</a></code></pre></div>
<p><img src="10-analysis-of-variance_files/figure-html/unnamed-chunk-55-1.png" width="672"  /></p>
<p>There are really not enough data values for a histogram to be of much
help, so I don’t like this as much.</p>
<p>If you are thinking ahead (we are going to be doing a <span class="math inline">\(t\)</span>-test), then
you’ll realize that normality is the kind of thing we’re looking for,
in which case normal quantile plots would be the thing. However, we
might have to be rather forgiving for method 2 since there are only 5
observations:</p>
<div class="sourceCode" id="cb1065"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb1065-1" data-line-number="1"><span class="kw">ggplot</span>(carbon, <span class="kw">aes</span>(<span class="dt">sample =</span> weight)) <span class="op">+</span></a>
<a class="sourceLine" id="cb1065-2" data-line-number="2"><span class="st">  </span><span class="kw">stat_qq</span>() <span class="op">+</span><span class="st"> </span><span class="kw">stat_qq_line</span>() <span class="op">+</span></a>
<a class="sourceLine" id="cb1065-3" data-line-number="3"><span class="st">  </span><span class="kw">facet_wrap</span>(<span class="op">~</span>method)</a></code></pre></div>
<p><img src="10-analysis-of-variance_files/figure-html/unnamed-chunk-56-1.png" width="672"  /></p>
<p>I don’t mind these coming out side by side, though I would rather have
them squarer.</p>
<p>I would say, boxplots are the best, normal quantile plots are also
acceptable, but expect to lose something for histograms because they
offer only a rather crude comparison in this case.</p>
<ol start="5" style="list-style-type: lower-alpha">
<li>Comment briefly on what you see in your plot.</li>
</ol>
<p>Solution</p>
<p>In boxplots, if that’s what you drew, there are several things
that deserve comment: the medians, the spreads and the
shapes. The median for method 1 is a little bit lower than for
method 2 (the means are probably more different, given the
shapes of the boxes). The spread for method 2 is a lot
bigger. (Looking forward, that suggests a Welch-Satterthwaite
rather than a pooled test.) As for shape, the method 2
measurements seem more or less symmetric (the whiskers are equal
anyway, even if the position of the median in the box isn’t),
but the method 1 measurements have a low outlier.
The histograms are hard to compare. Try to say something about
centre and spread and shape. I think the method 2 histogram has
a slightly higher centre and definitely bigger spread. On my
histogram for method 1, the distribution looks skewed left.
If you did normal quantile plots, say something sensible about
normality for each of the two methods. For method 1, I would say
the low value is an outlier and the rest of the values look
pretty straight. Up to you whether you think there is a curve on
the plot (which would indicate skewness, but then that highest
value is too high: it would be bunched up with the other values
below 12.01 if there were really skewness).
For method 2, it’s really hard to say anything since there are
only five values. Given where the line goes, there isn’t much
you can say to doubt normality. Perhaps the best you can say
here is that in a sample of size 5, it’s difficult to assess
normality at all.</p>
<ol start="6" style="list-style-type: lower-alpha">
<li>Carry out the most appropriate <span class="math inline">\(t\)</span>-test. (You might like to
begin another new section in your report here.)</li>
</ol>
<p>Solution</p>
<p>This would be the Welch-Satterthwaite version of the two-sample
<span class="math inline">\(t\)</span>-test, since the two groups do appear to have different spreads:</p>
<div class="sourceCode" id="cb1066"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb1066-1" data-line-number="1"><span class="kw">t.test</span>(weight <span class="op">~</span><span class="st"> </span>method, <span class="dt">data =</span> carbon)</a></code></pre></div>
<pre><code>## 
##  Welch Two Sample t-test
## 
## data:  weight by method
## t = -1.817, df = 5.4808, p-value = 0.1238
## alternative hypothesis: true difference in means is not equal to 0
## 95 percent confidence interval:
##  -0.027777288  0.004417288
## sample estimates:
## mean in group 1 mean in group 2 
##        12.00260        12.01428</code></pre>
<p>Imagining that this is a report that would go to your boss, you ought
to defend your choice of the Welch-Satterthwaite test (as I did
above), and not just do the default <span class="math inline">\(t\)</span>-test without comment.</p>
<p>If, in your discussion above, you thought the spreads were equal
enough, then you should do the pooled <span class="math inline">\(t\)</span>-test here, which goes like this:</p>
<div class="sourceCode" id="cb1068"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb1068-1" data-line-number="1"><span class="kw">t.test</span>(weight <span class="op">~</span><span class="st"> </span>method, <span class="dt">data =</span> carbon, <span class="dt">var.equal =</span> T)</a></code></pre></div>
<pre><code>## 
##  Two Sample t-test
## 
## data:  weight by method
## t = -2.1616, df = 13, p-value = 0.04989
## alternative hypothesis: true difference in means is not equal to 0
## 95 percent confidence interval:
##  -2.335341e-02 -6.588810e-06
## sample estimates:
## mean in group 1 mean in group 2 
##        12.00260        12.01428</code></pre>
<p>The point here is that you should do the right test based on your
conclusion. Being consistent is the most important thing. (In this
case, note that the P-values are very different. We’ll get to that
shortly.)</p>
<p>If we were doing this in SAS, as we see later, we’d get a test at the
bottom of the output that compares the two variances. I feel that it’s
just as good to eyeball the spreads and make a call about whether they
are “reasonably close”. Or even, to always do the
Welch-Satterthwaite test on the basis that it is pretty good even if
the two populations have the same variance. (If this last point of
view is one that you share, you ought to say something about that when
you do your <span class="math inline">\(t\)</span>-test.)</p>
<p>Extra: I guess this is a good place to say something about tests for comparing
variances, given that you might be pondering that. There are
several that I can think of, that R can do, of which I mention two.</p>
<p>The first is the <span class="math inline">\(F\)</span>-test for variances that you might have learned in
B57 (that is the basis for the ANOVA <span class="math inline">\(F\)</span>-test):</p>
<div class="sourceCode" id="cb1070"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb1070-1" data-line-number="1"><span class="kw">var.test</span>(weight <span class="op">~</span><span class="st"> </span>method, <span class="dt">data =</span> carbon)</a></code></pre></div>
<pre><code>## 
##  F test to compare two variances
## 
## data:  weight by method
## F = 0.35768, num df = 9, denom df = 4, p-value = 0.1845
## alternative hypothesis: true ratio of variances is not equal to 1
## 95 percent confidence interval:
##  0.04016811 1.68758230
## sample estimates:
## ratio of variances 
##          0.3576842</code></pre>
<p>This, unfortunately, is rather dependent on the data in the two groups
being approximately normal. Since we are talking variances rather than
means, there is no Central Limit Theorem to rescue us for large
samples (quite aside from the fact that these samples are <em>not</em>
large). Since the ANOVA <span class="math inline">\(F\)</span>-test is based on the same theory, this is
why normality is also more important in ANOVA than it is in a <span class="math inline">\(t\)</span>-test.</p>
<p>The second is Levene’s test. This doesn’t depend on normality (at
least, not nearly so much), so I like it better in general:</p>
<div class="sourceCode" id="cb1072"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb1072-1" data-line-number="1"><span class="kw">library</span>(car)</a>
<a class="sourceLine" id="cb1072-2" data-line-number="2"><span class="kw">leveneTest</span>(weight <span class="op">~</span><span class="st"> </span><span class="kw">factor</span>(method), <span class="dt">data =</span> carbon)</a></code></pre></div>
<pre><code>## Levene&#39;s Test for Homogeneity of Variance (center = median)
##       Df F value Pr(&gt;F)
## group  1  0.9887 0.3382
##       13</code></pre>
<p>Levene’s test takes a different approach: first the absolute
differences from the group medians are calculated, and then an ANOVA
is run on the absolute differences. If, say, one of the groups has a
larger spread than the other(s), its absolute differences from the
median will tend to be bigger.
<label for="tufte-mn-47" class="margin-toggle">⊕</label><input type="checkbox" id="tufte-mn-47" class="margin-toggle"><span class="marginnote">The use of absolute differences, and the median, downplays the influence of outliers. The assumption here is that the absolute differences from the medians are approximately normal, which seems a less big assumption than assuming the actual data are approximately normal.</span>
As for what we conclude here, well, neither of the variance tests show
any significance at all, so from that point of view there is no
evidence against using the pooled <span class="math inline">\(t\)</span>-test. Having said that, the
samples are small, and so it would be difficult to <em>prove</em> that
the two methods have different variance, even if they actually
did.
<label for="tufte-mn-48" class="margin-toggle">⊕</label><input type="checkbox" id="tufte-mn-48" class="margin-toggle"><span class="marginnote">This is coming back to the <em>power</em> of something like Levene’s test; the power of any test is not going to be very big if the sample sizes are small.</span></p>
<p>Things are never as clear-cut as you would like. In the end, it all
comes down to making a call and defending it.</p>
<ol start="7" style="list-style-type: lower-alpha">
<li>Do the most appropriate test you know that does not assume
normally-distributed data.</li>
</ol>
<p>Solution</p>
<p>That would be Mood’s median test. Since I didn’t say anything
about building it yourself, feel free to use <code>smmr</code>:</p>
<div class="sourceCode" id="cb1074"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb1074-1" data-line-number="1"><span class="kw">library</span>(smmr)</a>
<a class="sourceLine" id="cb1074-2" data-line-number="2"><span class="kw">median_test</span>(carbon, weight, method)</a></code></pre></div>
<pre><code>## $table
##      above
## group above below
##     1     3     6
##     2     4     1
## 
## $test
##        what      value
## 1 statistic 2.80000000
## 2        df 1.00000000
## 3   P-value 0.09426431</code></pre>
<p>As an aside, if you have run into a non-parametric test such as
Mann-Whitney or Kruskal-Wallis that applies in this situation, be
careful about using it here, because they have additional assumptions
that you may not want to trust. Mann-Whitney started life as a test for
“equal distributions”.
<label for="tufte-mn-49" class="margin-toggle">⊕</label><input type="checkbox" id="tufte-mn-49" class="margin-toggle"><span class="marginnote">The test goes back to the 1940s.</span> This
means that the null is equal location <em>and</em> equal spread, and if
you reject the null, one of those has failed. But here, we suspect that
equal spread will fail, so that the Mann-Whitney test may end up
rejecting <em>whether or not</em> the medians are different, so it won’t
answer the question you want an answer to. Mood’s median test doesn’t
have that problem; all it’s saying if the null is true is that the
medians are equal; the spreads could be anything at all.</p>
<p>The same kind of issues apply to the signed-rank test vs. the sign
test. In the case of the signed-rank test, the extra assumption is of
a symmetric distribution — to my mind, if you don’t believe
normality, you probably don’t have much confidence in symmetry
either. That’s why I like the sign test and Mood’s median test: in the
situation where you don’t want to be dealing with assumptions, these
tests don’t make you worry about that.</p>
<p>Another comment that you don’t need to make is based on the
not-quite-significance of the Mood test. The P-value is less than 0.10
but not less than 0.05, so it doesn’t quite reach significance by the
usual standard. But if you look up at the table, the frequencies seem
rather unbalanced: 6 out of the remaining 9 weights in group 1 are
below the overall median, but 4 out of 5 weights in group 2 are
above. This seems as if it ought to be significant, but bear in mind
that the sample sizes are small, and thus Mood’s median test needs
<em>very</em> unbalanced frequencies, which we don’t quite have here.</p>
<ol start="8" style="list-style-type: lower-alpha">
<li>Discuss the results of your tests and what they say about
the two methods for measuring the atomic weight of carbon. If it
seems appropriate, put the discussion into a section called
Conclusions.</li>
</ol>
<p>Solution</p>
<p>Begin by pulling out the P-values for your preferred test(s) and
say what they mean. The P-value for the Welch-Satterthwaite
<span class="math inline">\(t\)</span>-test is 0.1238, which indicates no difference in mean atomic
weights between the two methods. The Mood median test gives a
similarly non-significant 0.0943, indicating no difference in
the <em>median</em> weights. If you think both tests are
plausible, then give both P-values and do a compare-and-contrast
with them; if you think that one of the tests is clearly
preferable, then say so (and why) and focus on that test’s
results.
If you thought the pooled test was the right one, then you’ll
have a bit more discussion to do, since its P-value is 0.0499,
and at <span class="math inline">\(\alpha=0.05\)</span> this test disagrees with the others. If you
are comparing this test with the Mood test, you ought to make
some kind of reasoned recommendation about which test to
believe.
As ever, be consistent in your reasoning.
This dataset, where I found it, was actually being used to
illustrate a case where the pooled and the Welch-Satterthwaite
tests disagreed. The authors of the original paper that used
this dataset (a 1987 paper by Rayner and Best,
; the data come from 1924!) point out that the
pooled <span class="math inline">\(t\)</span>-test can be especially misleading when the smaller
sample is also the one with the larger variance. This is what
happened here.
In the Rayner and Best paper, the Mood (or the Mann-Whitney) test was
not being considered, but I think it’s good practice to draw a
picture and make a call about which test is appropriate.
I loaded package <code>car</code> above; I’d better be tidy and
unload it before I go on:</p>
<div class="sourceCode" id="cb1076"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb1076-1" data-line-number="1"><span class="kw">detach</span>(package<span class="op">:</span>car, <span class="dt">unload =</span> T)</a></code></pre></div>
</div>
<div id="can-caffeine-improve-your-performance-on-a-test" class="section level2">
<h2><span class="header-section-number">13.5</span> Can caffeine improve your performance on a test?</h2>
<p>Does caffeine help students do better on a certain test? To
find out, 36 students were randomly allocated to three groups (12 in
each group). Each student received a fixed number of cups of coffee
while they were studying, but the students didn’t know whether they
were receiving all full-strength coffee (“high”), all decaf coffee
(“low”) or a 50-50 mixture of the two (“moderate”). For each
subject, their group was recorded as well as their score on the
test. The data are in
<a href="http://www.utsc.utoronto.ca/~butler/d29/caffeine.csv">link</a>, as a
<code>.csv</code> file.</p>
<ol style="list-style-type: lower-alpha">
<li>Read in and examine the data. How are the values laid out?</li>
</ol>
<p>Solution</p>
<p><code>read_csv</code> because it’s a <code>.csv</code> file:</p>
<div class="sourceCode" id="cb1077"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb1077-1" data-line-number="1">my_url &lt;-<span class="st"> &quot;http://www.utsc.utoronto.ca/~butler/d29/caffeine.csv&quot;</span></a>
<a class="sourceLine" id="cb1077-2" data-line-number="2">caffeine.untidy &lt;-<span class="st"> </span><span class="kw">read_csv</span>(my_url)</a></code></pre></div>
<pre><code>## Parsed with column specification:
## cols(
##   Sub = col_double(),
##   High = col_double(),
##   Moderate = col_double(),
##   None = col_double()
## )</code></pre>
<div class="sourceCode" id="cb1079"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb1079-1" data-line-number="1">caffeine.untidy</a></code></pre></div>
<pre><code>## # A tibble: 12 x 4
##      Sub  High Moderate  None
##    &lt;dbl&gt; &lt;dbl&gt;    &lt;dbl&gt; &lt;dbl&gt;
##  1     1    72       68    68
##  2     2    65       80    74
##  3     3    68       64    59
##  4     4    83       65    61
##  5     5    79       69    65
##  6     6    92       79    72
##  7     7    69       80    80
##  8     8    74       63    58
##  9     9    78       69    65
## 10    10    83       70    60
## 11    11    88       83    78
## 12    12    71       75    75</code></pre>
<p>The first column is the number of the subject (actually within each
group, since each student only tried one amount of caffeine). Then
follow the test scores for the students in each group, one group per column.</p>
<p>I gave the data frame a kind of dumb name, since (looking ahead) I
could see that I would need a less-dumb name for the tidied-up data,
and it seemed sensible to keep <code>caffeine</code> for that.</p>
<ol start="2" style="list-style-type: lower-alpha">
<li>Explain briefly how the data are not “tidy”.</li>
</ol>
<p>Solution</p>
<p>The last three columns are all scores on the test: that is, they
all measure the same thing, so they should all be in the same column.
Or, there should be a column of scores, and a separate column
naming the groups. Or, there were 36 observations in the data, so
there should be 36 rows. You always have a variety of ways to
answer these, any of which will do.</p>
<ol start="3" style="list-style-type: lower-alpha">
<li>Use a suitable tool from the <code>tidyverse</code> to create one
column of test scores and and one column of group labels. Call your
column of group labels <code>amount</code>. Is it a <code>factor</code>?</li>
</ol>
<p>Solution</p>
<p>We are combining several columns into one, so this is <code>gather</code>:</p>
<div class="sourceCode" id="cb1081"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb1081-1" data-line-number="1">caffeine &lt;-<span class="st"> </span>caffeine.untidy <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb1081-2" data-line-number="2"><span class="st">  </span><span class="kw">gather</span>(amount, score, <span class="kw">c</span>(High<span class="op">:</span>None))</a></code></pre></div>
<p>I didn’t ask you to list the resulting data frame, but it is smart to
at least look for yourself, to make sure <code>gather</code> has done
what you expected.</p>
<div class="sourceCode" id="cb1082"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb1082-1" data-line-number="1">caffeine</a></code></pre></div>
<pre><code>## # A tibble: 36 x 3
##      Sub amount score
##    &lt;dbl&gt; &lt;chr&gt;  &lt;dbl&gt;
##  1     1 High      72
##  2     2 High      65
##  3     3 High      68
##  4     4 High      83
##  5     5 High      79
##  6     6 High      92
##  7     7 High      69
##  8     8 High      74
##  9     9 High      78
## 10    10 High      83
## # … with 26 more rows</code></pre>
<p>A column of amounts of caffeine, and a column of test scores. This is
what we expected. There should be 12 each of the <code>amount</code>s,
which you can check if you like:</p>
<div class="sourceCode" id="cb1084"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb1084-1" data-line-number="1">caffeine <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">count</span>(amount)</a></code></pre></div>
<pre><code>## # A tibble: 3 x 2
##   amount       n
##   &lt;chr&gt;    &lt;int&gt;
## 1 High        12
## 2 Moderate    12
## 3 None        12</code></pre>
<p>Indeed.</p>
<p>Note that <code>amount</code> is text, not a factor. Does this matter? We’ll see.</p>
<p>This is entirely the kind of situation where you need <code>gather</code>,
so get used to seeing where it will be useful.</p>
<ol start="4" style="list-style-type: lower-alpha">
<li>Obtain side-by-side boxplots of test scores by amount of caffeine.</li>
</ol>
<p>Solution</p>
<div class="sourceCode" id="cb1086"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb1086-1" data-line-number="1"><span class="kw">ggplot</span>(caffeine, <span class="kw">aes</span>(<span class="dt">x =</span> amount, <span class="dt">y =</span> score)) <span class="op">+</span><span class="st"> </span><span class="kw">geom_boxplot</span>()</a></code></pre></div>
<p><img src="10-analysis-of-variance_files/figure-html/unnamed-chunk-67-1.png" width="672"  /></p>
<ol start="5" style="list-style-type: lower-alpha">
<li>Does caffeine amount seem to have an effect? If so, what
kind of effect?</li>
</ol>
<p>Solution</p>
<p>On average, exam scores seem to be higher when the amount of
caffeine is higher (with
the effect being particularly pronounced for High caffeine).
If you want to, you can also say the the effect of caffeine seems
to be small, relative to the amount of variability there is (there
is a lot). The point is that you say <em>something</em> supported by
the boxplot.</p>
<ol start="6" style="list-style-type: lower-alpha">
<li>Run a suitable analysis of variance to determine whether
the mean test score is equal or unequal for the three groups. What
do you conclude?</li>
</ol>
<p>Solution</p>
<p>Something like this:</p>
<div class="sourceCode" id="cb1087"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb1087-1" data-line-number="1">caff<span class="fl">.1</span> &lt;-<span class="st"> </span><span class="kw">aov</span>(score <span class="op">~</span><span class="st"> </span>amount, <span class="dt">data =</span> caffeine)</a>
<a class="sourceLine" id="cb1087-2" data-line-number="2"><span class="kw">summary</span>(caff<span class="fl">.1</span>)</a></code></pre></div>
<pre><code>##             Df Sum Sq Mean Sq F value Pr(&gt;F)  
## amount       2  477.7  238.86   3.986 0.0281 *
## Residuals   33 1977.5   59.92                 
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<p>The P-value on the <span class="math inline">\(F\)</span>-test is less than 0.05, so we reject the null
hypothesis (which says that all the groups have equal means) in favour
of the alternative: the group means are not all the same (one or more
of them is different from the others).</p>
<p>Notice that the boxplot and the <code>aov</code> are quite happy for
<code>amount</code> to be text rather than a factor (they actually do want
a factor, but if the input is text, they’ll create one).</p>
<ol start="7" style="list-style-type: lower-alpha">
<li>Why is it a good idea to run Tukey’s method here?</li>
</ol>
<p>Solution</p>
<p>The analysis of variance <span class="math inline">\(F\)</span>-test is significant, so that the
groups are not all the same. Tukey’s method will tell us which
group(s) differ(s) from the others. There are three groups, so
there are differences to find that we don’t know about yet.</p>
<ol start="8" style="list-style-type: lower-alpha">
<li>Run Tukey’s method. What do you conclude?</li>
</ol>
<p>Solution</p>
<p>This kind of thing:</p>
<div class="sourceCode" id="cb1089"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb1089-1" data-line-number="1">caff<span class="fl">.3</span> &lt;-<span class="st"> </span><span class="kw">TukeyHSD</span>(caff<span class="fl">.1</span>)</a>
<a class="sourceLine" id="cb1089-2" data-line-number="2">caff<span class="fl">.3</span></a></code></pre></div>
<pre><code>##   Tukey multiple comparisons of means
##     95% family-wise confidence level
## 
## Fit: aov(formula = score ~ amount, data = caffeine)
## 
## $amount
##                    diff       lwr       upr     p adj
## Moderate-High -4.750000 -12.50468  3.004679 0.3025693
## None-High     -8.916667 -16.67135 -1.161987 0.0213422
## None-Moderate -4.166667 -11.92135  3.588013 0.3952176</code></pre>
<p>The high-caffeine group definitely has a higher mean test score than
the no-caffeine group. (The Moderate group is not significantly
different from either of the other groups.)
Both the
comparisons involving Moderate could go either way (the interval for
the difference in means includes zero). The None-High comparison,
however, is away from zero, so this is the significant one. As is
usual, we are pretty sure that the difference in means (this way
around) is negative, but we are not at all clear about how big it is,
because the confidence interval is rather long.
<label for="tufte-mn-50" class="margin-toggle">⊕</label><input type="checkbox" id="tufte-mn-50" class="margin-toggle"><span class="marginnote">We’d need a lot more students to make it narrower, but this is not surprising since students vary in a lot of other ways that were not measured here.</span></p>

</div>
</div>
<p style="text-align: center;">
<a href="normal-quantile-plots.html"><button class="btn btn-default">Previous</button></a>
<a href="tidying-and-selecting-data.html"><button class="btn btn-default">Next</button></a>
</p>
</div>
</div>



</body>
</html>
