<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>Chapter 30 Analysis of variance revisited | Problems and Solutions in Applied Statistics</title>
  <meta name="description" content="A set of problems and solutions, in R, on various parts of applied statistics" />
  <meta name="generator" content="bookdown 0.21 and GitBook 2.6.7" />

  <meta property="og:title" content="Chapter 30 Analysis of variance revisited | Problems and Solutions in Applied Statistics" />
  <meta property="og:type" content="book" />
  <meta property="og:url" content="http://ritsokiguess.site/pasias" />
  
  <meta property="og:description" content="A set of problems and solutions, in R, on various parts of applied statistics" />
  <meta name="github-repo" content="nxskok/pasias" />

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Chapter 30 Analysis of variance revisited | Problems and Solutions in Applied Statistics" />
  
  <meta name="twitter:description" content="A set of problems and solutions, in R, on various parts of applied statistics" />
  

<meta name="author" content="Ken Butler" />


<meta name="date" content="2021-06-04" />

  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="survival-analysis.html"/>
<link rel="next" href="analysis-of-covariance.html"/>
<script src="libs/jquery-2.2.3/jquery.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />











<style type="text/css">
a.sourceLine { display: inline-block; line-height: 1.25; }
a.sourceLine { pointer-events: none; color: inherit; text-decoration: inherit; }
a.sourceLine:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode { white-space: pre; position: relative; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
code.sourceCode { white-space: pre-wrap; }
a.sourceLine { text-indent: -1em; padding-left: 1em; }
}
pre.numberSource a.sourceLine
  { position: relative; left: -4em; }
pre.numberSource a.sourceLine::before
  { content: attr(title);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; pointer-events: all; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {  }
@media screen {
a.sourceLine::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">Problems and Solutions in Applied Statistics</a></li>

<li class="divider"></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i>Introduction</a><ul>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#packages-used-somewhere-in-this-book"><i class="fa fa-check"></i>Packages used somewhere in this book</a></li>
</ul></li>
<li class="chapter" data-level="1" data-path="getting-used-to-r-and-r-studio.html"><a href="getting-used-to-r-and-r-studio.html"><i class="fa fa-check"></i><b>1</b> Getting used to R and R Studio</a><ul>
<li class="chapter" data-level="1.1" data-path="getting-used-to-r-and-r-studio.html"><a href="getting-used-to-r-and-r-studio.html#running-r-studio-on-jupyterhub"><i class="fa fa-check"></i><b>1.1</b> Running R Studio on Jupyterhub</a></li>
<li class="chapter" data-level="1.2" data-path="getting-used-to-r-and-r-studio.html"><a href="getting-used-to-r-and-r-studio.html#getting-an-r-studio-cloud-account"><i class="fa fa-check"></i><b>1.2</b> Getting an R Studio Cloud account</a></li>
<li class="chapter" data-level="1.3" data-path="getting-used-to-r-and-r-studio.html"><a href="getting-used-to-r-and-r-studio.html#getting-started"><i class="fa fa-check"></i><b>1.3</b> Getting started</a></li>
<li class="chapter" data-level="1.4" data-path="getting-used-to-r-and-r-studio.html"><a href="getting-used-to-r-and-r-studio.html#reading-data-from-a-file"><i class="fa fa-check"></i><b>1.4</b> Reading data from a file</a></li>
<li class="chapter" data-level="1.5" data-path="getting-used-to-r-and-r-studio.html"><a href="getting-used-to-r-and-r-studio.html#reading-files-different-ways"><i class="fa fa-check"></i><b>1.5</b> Reading files different ways</a></li>
</ul></li>
<li class="chapter" data-level="2" data-path="reading-in-data.html"><a href="reading-in-data.html"><i class="fa fa-check"></i><b>2</b> Reading in data</a></li>
<li class="chapter" data-level="3" data-path="drawing-graphs.html"><a href="drawing-graphs.html"><i class="fa fa-check"></i><b>3</b> Drawing graphs</a></li>
<li class="chapter" data-level="4" data-path="data-exploration.html"><a href="data-exploration.html"><i class="fa fa-check"></i><b>4</b> Data exploration</a></li>
<li class="chapter" data-level="5" data-path="working-with-dataframes.html"><a href="working-with-dataframes.html"><i class="fa fa-check"></i><b>5</b> Working with dataframes</a></li>
<li class="chapter" data-level="6" data-path="one-sample-inference.html"><a href="one-sample-inference.html"><i class="fa fa-check"></i><b>6</b> One-sample inference</a></li>
<li class="chapter" data-level="7" data-path="two-sample-inference.html"><a href="two-sample-inference.html"><i class="fa fa-check"></i><b>7</b> Two-sample inference</a></li>
<li class="chapter" data-level="8" data-path="power-and-sample-size.html"><a href="power-and-sample-size.html"><i class="fa fa-check"></i><b>8</b> Power and sample size</a></li>
<li class="chapter" data-level="9" data-path="the-sign-test.html"><a href="the-sign-test.html"><i class="fa fa-check"></i><b>9</b> The sign test</a></li>
<li class="chapter" data-level="10" data-path="mood-median-test.html"><a href="mood-median-test.html"><i class="fa fa-check"></i><b>10</b> Mood median test</a></li>
<li class="chapter" data-level="11" data-path="matched-pairs-t-and-sign-test.html"><a href="matched-pairs-t-and-sign-test.html"><i class="fa fa-check"></i><b>11</b> Matched pairs t and sign test</a></li>
<li class="chapter" data-level="12" data-path="normal-quantile-plots.html"><a href="normal-quantile-plots.html"><i class="fa fa-check"></i><b>12</b> Normal quantile plots</a><ul>
<li class="chapter" data-level="12.1" data-path="normal-quantile-plots.html"><a href="normal-quantile-plots.html#lengths-of-heliconia-flowers"><i class="fa fa-check"></i><b>12.1</b> Lengths of heliconia flowers</a></li>
<li class="chapter" data-level="12.2" data-path="normal-quantile-plots.html"><a href="normal-quantile-plots.html#ferritin-and-normality"><i class="fa fa-check"></i><b>12.2</b> Ferritin and normality</a></li>
<li class="chapter" data-level="12.3" data-path="normal-quantile-plots.html"><a href="normal-quantile-plots.html#lengths-of-heliconia-flowers-1"><i class="fa fa-check"></i><b>12.3</b> Lengths of heliconia flowers</a></li>
<li class="chapter" data-level="12.4" data-path="normal-quantile-plots.html"><a href="normal-quantile-plots.html#ferritin-and-normality-1"><i class="fa fa-check"></i><b>12.4</b> Ferritin and normality</a></li>
</ul></li>
<li class="chapter" data-level="13" data-path="analysis-of-variance.html"><a href="analysis-of-variance.html"><i class="fa fa-check"></i><b>13</b> Analysis of variance</a></li>
<li class="chapter" data-level="14" data-path="writing-reports.html"><a href="writing-reports.html"><i class="fa fa-check"></i><b>14</b> Writing reports</a></li>
<li class="chapter" data-level="15" data-path="learning-to-code.html"><a href="learning-to-code.html"><i class="fa fa-check"></i><b>15</b> Learning to code</a><ul>
<li class="chapter" data-level="15.1" data-path="learning-to-code.html"><a href="learning-to-code.html#introduction-1"><i class="fa fa-check"></i><b>15.1</b> Introduction</a></li>
<li class="chapter" data-level="15.2" data-path="learning-to-code.html"><a href="learning-to-code.html#data-and-pre-processing"><i class="fa fa-check"></i><b>15.2</b> Data and pre-processing</a></li>
<li class="chapter" data-level="15.3" data-path="learning-to-code.html"><a href="learning-to-code.html#analysis"><i class="fa fa-check"></i><b>15.3</b> Analysis</a></li>
<li class="chapter" data-level="15.4" data-path="learning-to-code.html"><a href="learning-to-code.html#conclusions-see-note-9"><i class="fa fa-check"></i><b>15.4</b> Conclusions (see note 9)</a></li>
</ul></li>
<li class="chapter" data-level="16" data-path="treating-dandruff.html"><a href="treating-dandruff.html"><i class="fa fa-check"></i><b>16</b> Treating dandruff</a><ul>
<li class="chapter" data-level="16.1" data-path="treating-dandruff.html"><a href="treating-dandruff.html#introduction-2"><i class="fa fa-check"></i><b>16.1</b> Introduction</a></li>
<li class="chapter" data-level="16.2" data-path="treating-dandruff.html"><a href="treating-dandruff.html#exploratory-analysis"><i class="fa fa-check"></i><b>16.2</b> Exploratory analysis</a></li>
<li class="chapter" data-level="16.3" data-path="treating-dandruff.html"><a href="treating-dandruff.html#analysis-of-variance-1"><i class="fa fa-check"></i><b>16.3</b> Analysis of Variance</a></li>
<li class="chapter" data-level="16.4" data-path="treating-dandruff.html"><a href="treating-dandruff.html#assessment-of-assumptions"><i class="fa fa-check"></i><b>16.4</b> Assessment of Assumptions</a></li>
<li class="chapter" data-level="16.5" data-path="treating-dandruff.html"><a href="treating-dandruff.html#conclusions"><i class="fa fa-check"></i><b>16.5</b> Conclusions</a></li>
<li class="chapter" data-level="16.6" data-path="treating-dandruff.html"><a href="treating-dandruff.html#end"><i class="fa fa-check"></i><b>16.6</b> End</a></li>
</ul></li>
<li class="chapter" data-level="17" data-path="tidying-data.html"><a href="tidying-data.html"><i class="fa fa-check"></i><b>17</b> Tidying data</a></li>
<li class="chapter" data-level="18" data-path="simple-regression.html"><a href="simple-regression.html"><i class="fa fa-check"></i><b>18</b> Simple regression</a></li>
<li class="chapter" data-level="19" data-path="multiple-regression.html"><a href="multiple-regression.html"><i class="fa fa-check"></i><b>19</b> Multiple regression</a></li>
<li class="chapter" data-level="20" data-path="regression-with-categorical-variables.html"><a href="regression-with-categorical-variables.html"><i class="fa fa-check"></i><b>20</b> Regression with categorical variables</a><ul>
<li class="chapter" data-level="20.1" data-path="regression-with-categorical-variables.html"><a href="regression-with-categorical-variables.html#crickets-revisited"><i class="fa fa-check"></i><b>20.1</b> Crickets revisited</a></li>
<li class="chapter" data-level="20.2" data-path="regression-with-categorical-variables.html"><a href="regression-with-categorical-variables.html#pulse-rates-and-marching"><i class="fa fa-check"></i><b>20.2</b> Pulse rates and marching</a></li>
<li class="chapter" data-level="20.3" data-path="regression-with-categorical-variables.html"><a href="regression-with-categorical-variables.html#crickets-revisited-1"><i class="fa fa-check"></i><b>20.3</b> Crickets revisited</a></li>
<li class="chapter" data-level="20.4" data-path="regression-with-categorical-variables.html"><a href="regression-with-categorical-variables.html#pulse-rates-and-marching-1"><i class="fa fa-check"></i><b>20.4</b> Pulse rates and marching</a></li>
</ul></li>
<li class="chapter" data-level="21" data-path="dates-and-times.html"><a href="dates-and-times.html"><i class="fa fa-check"></i><b>21</b> Dates and times</a></li>
<li class="chapter" data-level="22" data-path="functions.html"><a href="functions.html"><i class="fa fa-check"></i><b>22</b> Functions</a></li>
<li class="chapter" data-level="23" data-path="vector-and-matrix-algebra.html"><a href="vector-and-matrix-algebra.html"><i class="fa fa-check"></i><b>23</b> Vector and matrix algebra</a><ul>
<li class="chapter" data-level="23.1" data-path="vector-and-matrix-algebra.html"><a href="vector-and-matrix-algebra.html#heights-and-foot-lengths-again"><i class="fa fa-check"></i><b>23.1</b> Heights and foot lengths again</a></li>
<li class="chapter" data-level="23.2" data-path="vector-and-matrix-algebra.html"><a href="vector-and-matrix-algebra.html#heights-and-foot-lengths-again-1"><i class="fa fa-check"></i><b>23.2</b> Heights and foot lengths again</a></li>
</ul></li>
<li class="chapter" data-level="24" data-path="the-bootstrap.html"><a href="the-bootstrap.html"><i class="fa fa-check"></i><b>24</b> The Bootstrap</a></li>
<li class="chapter" data-level="25" data-path="bayesian-statistics-with-stan.html"><a href="bayesian-statistics-with-stan.html"><i class="fa fa-check"></i><b>25</b> Bayesian Statistics with Stan</a></li>
<li class="chapter" data-level="26" data-path="logistic-regression.html"><a href="logistic-regression.html"><i class="fa fa-check"></i><b>26</b> Logistic regression</a></li>
<li class="chapter" data-level="27" data-path="logistic-regression-with-ordinal-response.html"><a href="logistic-regression-with-ordinal-response.html"><i class="fa fa-check"></i><b>27</b> Logistic regression with ordinal response</a></li>
<li class="chapter" data-level="28" data-path="logistic-regression-with-nominal-response.html"><a href="logistic-regression-with-nominal-response.html"><i class="fa fa-check"></i><b>28</b> Logistic regression with nominal response</a></li>
<li class="chapter" data-level="29" data-path="survival-analysis.html"><a href="survival-analysis.html"><i class="fa fa-check"></i><b>29</b> Survival analysis</a></li>
<li class="chapter" data-level="30" data-path="analysis-of-variance-revisited.html"><a href="analysis-of-variance-revisited.html"><i class="fa fa-check"></i><b>30</b> Analysis of variance revisited</a><ul>
<li class="chapter" data-level="30.1" data-path="analysis-of-variance-revisited.html"><a href="analysis-of-variance-revisited.html#acid-rain"><i class="fa fa-check"></i><b>30.1</b> Acid rain</a></li>
<li class="chapter" data-level="30.2" data-path="analysis-of-variance-revisited.html"><a href="analysis-of-variance-revisited.html#treating-hay-fever"><i class="fa fa-check"></i><b>30.2</b> Treating hay fever</a></li>
<li class="chapter" data-level="30.3" data-path="analysis-of-variance-revisited.html"><a href="analysis-of-variance-revisited.html#focused-comparisons-of-the-effect-of-caffeine"><i class="fa fa-check"></i><b>30.3</b> Focused comparisons of the effect of caffeine</a></li>
<li class="chapter" data-level="30.4" data-path="analysis-of-variance-revisited.html"><a href="analysis-of-variance-revisited.html#who-studies-the-most-outside-class"><i class="fa fa-check"></i><b>30.4</b> Who studies the most outside class?</a></li>
<li class="chapter" data-level="30.5" data-path="analysis-of-variance-revisited.html"><a href="analysis-of-variance-revisited.html#mental-context"><i class="fa fa-check"></i><b>30.5</b> Mental context</a></li>
<li class="chapter" data-level="30.6" data-path="analysis-of-variance-revisited.html"><a href="analysis-of-variance-revisited.html#trying-on-shirts"><i class="fa fa-check"></i><b>30.6</b> Trying on shirts</a></li>
<li class="chapter" data-level="30.7" data-path="analysis-of-variance-revisited.html"><a href="analysis-of-variance-revisited.html#acid-rain-1"><i class="fa fa-check"></i><b>30.7</b> Acid rain</a></li>
<li class="chapter" data-level="30.8" data-path="analysis-of-variance-revisited.html"><a href="analysis-of-variance-revisited.html#treating-hay-fever-1"><i class="fa fa-check"></i><b>30.8</b> Treating hay fever</a></li>
<li class="chapter" data-level="30.9" data-path="analysis-of-variance-revisited.html"><a href="analysis-of-variance-revisited.html#focused-comparisons-of-the-effect-of-caffeine-1"><i class="fa fa-check"></i><b>30.9</b> Focused comparisons of the effect of caffeine</a></li>
<li class="chapter" data-level="30.10" data-path="analysis-of-variance-revisited.html"><a href="analysis-of-variance-revisited.html#who-studies-the-most-outside-class-1"><i class="fa fa-check"></i><b>30.10</b> Who studies the most outside class?</a></li>
<li class="chapter" data-level="30.11" data-path="analysis-of-variance-revisited.html"><a href="analysis-of-variance-revisited.html#mental-context-1"><i class="fa fa-check"></i><b>30.11</b> Mental context</a></li>
<li class="chapter" data-level="30.12" data-path="analysis-of-variance-revisited.html"><a href="analysis-of-variance-revisited.html#trying-on-shirts-1"><i class="fa fa-check"></i><b>30.12</b> Trying on shirts</a></li>
</ul></li>
<li class="chapter" data-level="31" data-path="analysis-of-covariance.html"><a href="analysis-of-covariance.html"><i class="fa fa-check"></i><b>31</b> Analysis of covariance</a></li>
<li class="chapter" data-level="32" data-path="multivariate-analysis-of-variance.html"><a href="multivariate-analysis-of-variance.html"><i class="fa fa-check"></i><b>32</b> Multivariate analysis of variance</a></li>
<li class="chapter" data-level="33" data-path="repeated-measures.html"><a href="repeated-measures.html"><i class="fa fa-check"></i><b>33</b> Repeated measures</a></li>
<li class="chapter" data-level="34" data-path="discriminant-analysis.html"><a href="discriminant-analysis.html"><i class="fa fa-check"></i><b>34</b> Discriminant analysis</a></li>
<li class="chapter" data-level="35" data-path="hierarchical-cluster-analysis.html"><a href="hierarchical-cluster-analysis.html"><i class="fa fa-check"></i><b>35</b> Hierarchical cluster analysis</a></li>
<li class="chapter" data-level="36" data-path="k-means-cluster-analysis.html"><a href="k-means-cluster-analysis.html"><i class="fa fa-check"></i><b>36</b> K-means cluster analysis</a></li>
<li class="chapter" data-level="37" data-path="drawing-maps-with-leaflet.html"><a href="drawing-maps-with-leaflet.html"><i class="fa fa-check"></i><b>37</b> Drawing maps with Leaflet</a></li>
<li class="chapter" data-level="38" data-path="multidimensional-scaling.html"><a href="multidimensional-scaling.html"><i class="fa fa-check"></i><b>38</b> Multidimensional Scaling</a></li>
<li class="chapter" data-level="39" data-path="principal-components.html"><a href="principal-components.html"><i class="fa fa-check"></i><b>39</b> Principal Components</a><ul>
<li class="chapter" data-level="39.1" data-path="principal-components.html"><a href="principal-components.html#the-weather-somewhere"><i class="fa fa-check"></i><b>39.1</b> The weather, somewhere</a></li>
<li class="chapter" data-level="39.2" data-path="principal-components.html"><a href="principal-components.html#the-weather-somewhere-1"><i class="fa fa-check"></i><b>39.2</b> The weather, somewhere</a></li>
</ul></li>
<li class="chapter" data-level="40" data-path="factor-analysis.html"><a href="factor-analysis.html"><i class="fa fa-check"></i><b>40</b> Factor Analysis</a></li>
<li class="chapter" data-level="41" data-path="frequency-table-analysis.html"><a href="frequency-table-analysis.html"><i class="fa fa-check"></i><b>41</b> Frequency table analysis</a></li>
<li class="divider"></li>
<li><a href="https://github.com/rstudio/bookdown" target="blank">Published with bookdown</a></li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Problems and Solutions in Applied Statistics</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="analysis-of-variance-revisited" class="section level1">
<h1><span class="header-section-number">Chapter 30</span> Analysis of variance revisited</h1>
<p>Packages for this chapter:</p>
<div class="sourceCode" id="cb254"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb254-1" title="1"><span class="kw">library</span>(MASS)</a>
<a class="sourceLine" id="cb254-2" title="2"><span class="kw">library</span>(car)</a>
<a class="sourceLine" id="cb254-3" title="3"><span class="kw">library</span>(tidyverse)</a></code></pre></div>
<div id="acid-rain" class="section level2">
<h2><span class="header-section-number">30.1</span> Acid rain</h2>
<p>One of the first noticeable effects of climate change was
“acid rain”. This is formed by the water vapour in clouds combining
with nitrous oxide and sulfur dioxide, which come from coal and oil
production. How does the acidity of rain affect the acidity of the
soil on which it falls? (This will have an effect on the kind of
plants that can be grown in that soil.) Acidity is measured using the
pH scale, where a pH of 7 is chemically neutral, a number less than 7
is acidic, and a number greater than 7 is alkaline.</p>
<p>An experiment was conducted at the Florida Institute of Food and
Agricultural Sciences, to determine how acidity of rain affects soil
acidity. Experimental plots were irrigated with rainwater that was
prepared to have one of two different pH levels, 3.7 and 4.5. The
acidity of the soil was then measured at three different depths,
0–15, 15–30, and 30–46 centimetres. This was done on three
different dates, in April and June 1991. The data are in
<a href="http://ritsokiguess.site/datafiles/acidrain.csv">link</a>.</p>
<ol style="list-style-type: lower-alpha">
<li><p>Read in and display the data.</p></li>
<li><p>Draw a grouped boxplot to show how soil acidity depends on
the pH of the rain and the soil depth. (The first time you do this
you might not get the boxplot you want. How can you fix that?)</p></li>
<li><p>What does your grouped boxplot say about likely
interactions? Explain briefly.</p></li>
<li><p>Fit an ANOVA with interaction. What do you conclude from
it? You may want to create a column that is the factor version of
<code>rain_pH</code> first.</p></li>
</ol>
</div>
<div id="treating-hay-fever" class="section level2">
<h2><span class="header-section-number">30.2</span> Treating hay fever</h2>
<p>Hay fever is an allergic reaction to things like grasses or
pollen which can make it unpleasant to go outside when the weather is
at its best. A research lab is developing a new compound to relieve
severe cases of hay fever. There were two active ingredients, labelled
A and B, with each one having three levels, low, medium and
high. There were thus <span class="math inline">\(3\times 3=9\)</span> treatment combinations. 36
subjects were available, and these were randomly assigned to
combinations of levels of factor A and factor B, so that each
combination was tested on 4 people. The response variable was the
number of hours of relief from symptoms (so a higher value is
better). The data are in
<a href="http://ritsokiguess.site/datafiles/hayfever.txt">link</a>.</p>
<ol style="list-style-type: lower-alpha">
<li><p>Read the data and display its structure. Verify that you
have what you were expecting.</p></li>
<li><p>Calculate the mean hours of relief for each combination of
levels of the two active ingredients. Save your results in a data
frame and display that.</p></li>
<li><p>Make an interaction plot, showing how the mean pain relief depends on the combination of levels of A and B. It is probably easiest to use the data frame you obtained in the previous part.</p></li>
<li><p>What do you conclude from your interaction plot? Explain briefly.</p></li>
<li><p>Run an analysis of variance with interaction. What do you conclude?</p></li>
<li><p>Analyze the simple effects of B when A is
<code>medium</code>. (This means doing an appropriate <code>aov</code> and
an appropriate Tukey, if warranted.)</p></li>
<li><p>Analyze the simple effects of B when A is <code>high</code>.</p></li>
</ol>
</div>
<div id="focused-comparisons-of-the-effect-of-caffeine" class="section level2">
<h2><span class="header-section-number">30.3</span> Focused comparisons of the effect of caffeine</h2>
<p>Does caffeine help students do better on a certain test? To
find out, 36 students were randomly allocated to three groups (12 in
each group). Each student received a fixed number of cups of coffee
while they were studying, but the students didn’t know whether they
were receiving all full-strength coffee (“high”), all decaf coffee
(“low”) or a 50-50 mixture of the two (“moderate”). For each
subject, their group was recorded as well as their score on the
test. The data are in
<a href="http://ritsokiguess.site/datafiles/caffeine.csv">link</a>, as a
<code>.csv</code> file.</p>
<p>This time we look at
contrasts. Suppose I knew ahead of time
that I wanted to compare moderate caffeine with high, and any
caffeine with none. (In the latter case, we’re comparing
“no caffeine” against the average of the other two groups.)</p>
<p>In the previous go-through of the caffeine data, we
discovered that <code>amount</code> was actually text rather than a
factor, but we also discovered that it <em>didn’t matter</em>. Here it
does matter, so the first thing we have to do is to re-do the
<code>pivot_longer</code>, creating a factor version of <code>amount</code>.</p>
<ol style="list-style-type: lower-alpha">
<li><p>Read in the data again, from
<a href="http://ritsokiguess.site/datafiles/caffeine.csv">link</a>, and
display it. This is the untidy format, so name it appropriately:</p></li>
<li><p>Copy your <code>pivot_longer</code> from before, only this time add
<code>names_ptypes = list(amount=factor())</code> to the end of it. Take a look at the
results. What has changed from before?</p></li>
<li><p>Using the newly tidied caffeine data, run the ANOVA
<em>as a regression</em> (that is, using <code>lm</code>). Look at the
<code>summary</code> of the output. What do you see?</p></li>
<li><p>Obtain the different values of <code>amount</code>, in the order
that R has them.</p></li>
<li><p>Create a contrast that compares High with Moderate, ignoring
None. That is, create a vector whose length is the same as the
number of levels of <code>amount</code>, and which has a 1 to represent
High and a <span class="math inline">\(-1\)</span> to represent Moderate.</p></li>
<li><p>Create a contrast that compares “any caffeine” against
“none” by comparing None against the average of Moderate and High.</p></li>
<li><p>Verify that your two contrasts are orthogonal.</p></li>
<li><p>Arrange your contrasts as columns of a matrix (using
<code>cbind</code>), and say that you want to use these as contrasts for
<code>amount</code> (in data frame <code>caffeine</code> or whatever you
called it).</p></li>
<li><p>Fit the ANOVA as an <code>lm</code>, and look at the
<code>summary</code>. What do you conclude about your contrasts?</p></li>
<li><p>What happens if you try to use high caffeine vs. moderate
caffeine and moderate vs. none as your two contrasts?</p></li>
</ol>
</div>
<div id="who-studies-the-most-outside-class" class="section level2">
<h2><span class="header-section-number">30.4</span> Who studies the most outside class?</h2>
<p>A social scientist wanted to see how many hours students
studied outside of class. She took a random sample of 75 students
from three different majors: math, social science and English, and
recorded the number of weekly outside-class study hours for each
student. The data can be found at
<a href="http://ritsokiguess.site/datafiles/studyhours.txt">link</a>. The
social scientist had two research questions: whether math students study
more outside of class than the other students, and whether English and
social science students study different amounts of time outside class.</p>
<ol style="list-style-type: lower-alpha">
<li><p>Explain briefly why contrasts would be a better idea here
than ANOVA with Tukey.</p></li>
<li><p>Read in the data and make side-by-side boxplots of study
hours by major. What do the boxplots suggest about the comparisons
that the researcher wants to make?</p></li>
<li><p>Set up contrasts for each of the researcher’s research
questions, bearing in mind the levels of <code>major</code> and the
order in which they come. (For the <code>Math</code> contrast, you want
Math against the average of the other two.)</p></li>
<li><p>Verify that your two contrasts are orthogonal.</p></li>
<li><p>Create a matrix of contrasts (using <code>cbind</code>) and let
<code>lm</code> know that these are contrasts for <code>major</code>, in
data frame <code>studyhours</code> (or whatever you called it).</p></li>
<li><p>Fit the model using <code>lm</code>. What do you conclude about
your contrasts?</p></li>
<li><p>Are you surprised by the significance or non-significance you
found in the previous part? Explain briefly.</p></li>
</ol>
</div>
<div id="mental-context" class="section level2">
<h2><span class="header-section-number">30.5</span> Mental context</h2>
<p>It is believed that being in the same mental context for
learning and for testing leads to better test scores. An experiment
was carried out to test this. During the learning phase, subjects
learned a list of 80 words in a room painted orange and decorated with
posters, paintings and other paraphernalia.<a href="#fn36" class="footnote-ref" id="fnref36"><sup>36</sup></a> A memory test was given to all subjects
immediately after they had learned the words, to give the impression
that the experiment was over. (The results of this test were
discarded.) One day later, subjects were unexpectedly re-tested under
different experimental conditions and asked to write down all the
words of the original list that they could remember. The re-test took
place in five different conditions, which subjects were randomly
allocated to one of:</p>
<ul>
<li><p>Same context: in the original orange-painted room.</p></li>
<li><p>Different context: in a very different room, painted grey and
located in a different part of campus.</p></li>
<li><p>Imaginary context: in the grey room, but subjects are asked to
remember the orange room in which they took the original test. To
help them with this, the experimenter begins by asking them several
questions about the orange room and the objects in it.</p></li>
<li><p>Photographed context: in the grey room, but subjects are shown
photographs of the orange room.</p></li>
<li><p>Placebo context: in the grey room, with subjects first being
asked to recall their living room.</p></li>
</ul>
<p>In each case, the response variable was the number of words on the
original list successfully recalled by each subject.</p>
<p>50 subjects in total completed the experiment, 10 under each of the 5
conditions.</p>
<p>The researchers had four research hypotheses to test with the data:</p>
<ul>
<li><p>Groups where the context matches (is the same, or is simulated
by imagining or photograph) will perform better than groups with
different or placebo contexts.</p></li>
<li><p>The group with the same context will differ from the group with
imaginary or photographed contexts.</p></li>
<li><p>The imaginary-context group will differ from the
photographed-context group.</p></li>
<li><p>The different-context group will differ from the placebo-context group.</p></li>
</ul>
<p>The research hypotheses are (as is usual) written as
<em>alternative</em> hypotheses. We can rewrite them as null
hypotheses, with some extra wording to facilitate converting them
into contrasts, like this:</p>
<ul>
<li><p>The mean of the <code>same</code>, <code>imaginary</code> and
<code>photograph</code> groups (group means) is equal to the mean of the
<code>different</code> and <code>placebo</code> groups (group means).</p></li>
<li><p>The mean of the <code>imaginary</code> and <code>photograph</code>
groups is equal to the (mean of the) <code>same</code> group.</p></li>
<li><p>The <code>imaginary</code> and the <code>photograph</code> groups will
have the same mean.</p></li>
<li><p>The <code>different</code> and the <code>placebo</code> groups will
have the same mean.</p></li>
</ul>
<p>The data are in
<a href="http://ritsokiguess.site/datafiles/smith.txt">link</a> (the
original researcher’s name was Smith).</p>
<ol style="list-style-type: lower-alpha">
<li><p>Read in the data and verify that you have a column called
<code>context</code> that is text and a column called
<code>words</code> that is a (whole) number.</p></li>
<li><p>Turn <code>context</code> into a <code>factor</code>, within the
data frame. (We are going to be doing contrasts). Display how the
data frame now looks.</p></li>
<li><p>What are the names of the five contexts in the data set
(just display them),
and what order are they in?</p></li>
<li><p>Write each of the four research hypotheses (in the
null-hypothesis versions) as R vectors that can be used to make
contrasts. (This will mean getting the contexts in the right
order. If you get stuck, do the last two first, since they’re
easiest. The first one is actually the hardest.)</p></li>
<li><p>Pick two of your contrasts (doesn’t matter which two) and
demonstrate that they are orthogonal.</p></li>
<li><p>Collect your contrasts together into a matrix, and
tell <code>lm</code> that these are the contrasts for <code>context</code>.</p></li>
<li><p>Fit a model with <code>lm</code>, and display the results.</p></li>
<li><p>For each of the original research hypotheses, what do you
infer about them?</p></li>
</ol>
</div>
<div id="trying-on-shirts" class="section level2">
<h2><span class="header-section-number">30.6</span> Trying on shirts</h2>
<p>Does it make a difference if you see somebody else trying on
a shirt before you do, and if so, does it matter what kind of person
it is?</p>
<p>An experiment was carried out in a university bookstore, with
students who wanted to try on a shirt serving as (unsuspecting)
experimental subjects. When a student wanted to try on a shirt, the
sales associate told them that there was only one shirt left, and it
was being tried on by an “other customer”. This “other customer”
was actually a “confederate” of the experimenter (that means, they
were pretending to be a real customer but were actually part of the
experiment). The “other customer” was always female: either an
attractive well-dressed model, or an average-looking student wearing
jeans. The “other customer” would come out of the
dressing room and hand the shirt to the sales associate, who would
give it to the student who wanted to try it on. When the student had
tried on the shirt, they were asked to rate it on a 7-point scale (on
five different dimensions, and those five scores were then
averaged). Does a student’s evaluation depend on whether the student
was male or female, and whether the “other customer” was a model or
a student? There was also a control group, where the student was
handed the shirt directly by the sales associate, without the
“other customer” being involved at all.</p>
<p>There were thus five treatments:
male students who saw a model, male students who saw a student, female
students who saw a model, female students who saw a student, and the
control group. There were 25 students in each treatment group.</p>
<p>The data from this experiment can be found at
<a href="http://ritsokiguess.site/datafiles/shirts.csv">link</a>.</p>
<ol style="list-style-type: lower-alpha">
<li><p>Read in and display the data. How many observations do you
have, and is that what you should have?</p></li>
<li><p>Turn <code>treatment</code> into a <code>factor</code> in your data
frame. (You can use the same name as the text <code>treatment</code>
that you read in from the file.)</p></li>
<li><p>List the treatments in the order that they are in within
your <code>factor</code>. (There are lots of ways to do this; any one of
them except for <code>distinct</code> is good.)</p></li>
<li><p><a name="part:mean-eval">*</a>
Obtain a table of mean evaluation scores for each treatment group.</p></li>
<li><p>The experimenters wanted to compare four specific things in
their analysis:</p></li>
</ol>
<ul>
<li><p>evaluation scores between male students who saw a (female) model and
male students who saw a (female) student</p></li>
<li><p>evaluation scores between female students who saw a (female)
model and female students who saw a (female) student</p></li>
<li><p>evaluation scores for male and for female students (overall)</p></li>
<li><p>evaluation scores for the (average of the) four genuine
treatments and for the control group</p></li>
</ul>
<p>Create contrasts, with suitable names, using vectors with
appropriate values.</p>
<ol start="6" style="list-style-type: lower-alpha">
<li><p>Pick two of your contrasts (doesn’t matter which two) and
demonstrate that they are orthogonal.</p></li>
<li><p>Collect all your contrasts together into a matrix and
declare that they are contrasts for <code>treatment</code> within your
data frame (whatever you called it).</p></li>
<li><p>Predict evaluation score from
treatment <em>as a regression</em>, and display the results.</p></li>
<li><p>For each of your contrasts, assess whether or not it is
significant, and explain briefly what that means in the context of the
data. If a contrast is significant, use your answer to
part (<a href="#part:mean-eval">here</a>) to help in your interpretation.</p></li>
</ol>
<p>My solutions follow:</p>
</div>
<div id="acid-rain-1" class="section level2">
<h2><span class="header-section-number">30.7</span> Acid rain</h2>
<p>One of the first noticeable effects of climate change was
“acid rain”. This is formed by the water vapour in clouds combining
with nitrous oxide and sulfur dioxide, which come from coal and oil
production. How does the acidity of rain affect the acidity of the
soil on which it falls? (This will have an effect on the kind of
plants that can be grown in that soil.) Acidity is measured using the
pH scale, where a pH of 7 is chemically neutral, a number less than 7
is acidic, and a number greater than 7 is alkaline.</p>
<p>An experiment was conducted at the Florida Institute of Food and
Agricultural Sciences, to determine how acidity of rain affects soil
acidity. Experimental plots were irrigated with rainwater that was
prepared to have one of two different pH levels, 3.7 and 4.5. The
acidity of the soil was then measured at three different depths,
0–15, 15–30, and 30–46 centimetres. This was done on three
different dates, in April and June 1991. The data are in
<a href="http://ritsokiguess.site/datafiles/acidrain.csv">link</a>.</p>
<ol style="list-style-type: lower-alpha">
<li>Read in and display the data.</li>
</ol>
<p>Solution</p>
<p>This time, it’s a <code>.csv</code>:</p>
<div class="sourceCode" id="cb255"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb255-1" title="1">my_url &lt;-<span class="st"> &quot;http://ritsokiguess.site/datafiles/acidrain.csv&quot;</span></a>
<a class="sourceLine" id="cb255-2" title="2">acidrain &lt;-<span class="st"> </span><span class="kw">read_csv</span>(my_url)</a></code></pre></div>
<pre><code>## 
## ── Column specification ──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
## cols(
##   soil_depth = col_character(),
##   date = col_date(format = &quot;&quot;),
##   rain_pH = col_double(),
##   soil_acidity = col_double()
## )</code></pre>
<div class="sourceCode" id="cb257"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb257-1" title="1">acidrain</a></code></pre></div>
<pre><code>## # A tibble: 18 x 4
##    soil_depth date       rain_pH soil_acidity
##    &lt;chr&gt;      &lt;date&gt;       &lt;dbl&gt;        &lt;dbl&gt;
##  1 0-15       1991-04-03     3.7         5.33
##  2 0-15       1991-04-03     4.5         5.33
##  3 0-15       1991-06-16     3.7         5.47
##  4 0-15       1991-06-16     4.5         5.47
##  5 0-15       1991-06-30     3.7         5.2 
##  6 0-15       1991-06-30     4.5         5.13
##  7 15-30      1991-04-03     3.7         5.27
##  8 15-30      1991-04-03     4.5         5.03
##  9 15-30      1991-06-16     3.7         5.5 
## 10 15-30      1991-06-16     4.5         5.53
## 11 15-30      1991-06-30     3.7         5.33
## 12 15-30      1991-06-30     4.5         5.2 
## 13 30-46      1991-04-03     3.7         5.37
## 14 30-46      1991-04-03     4.5         5.4 
## 15 30-46      1991-06-16     3.7         5.8 
## 16 30-46      1991-06-16     4.5         5.6 
## 17 30-46      1991-06-30     3.7         5.33
## 18 30-46      1991-06-30     4.5         5.17</code></pre>
<p>There are 4 columns, soil depth, date, pH of the rain that was
applied (all explanatory) and soil acidity, the response. You’ll note
that we have one soil acidity value per combination of the other
things (it was a designed experiment).</p>
<p>We’re going to ignore the date for now, treating the observations on
different dates as replicates.</p>
<p><span class="math inline">\(\blacksquare\)</span></p>
<ol start="2" style="list-style-type: lower-alpha">
<li>Draw a grouped boxplot to show how soil acidity depends on
the pH of the rain and the soil depth. (The first time you do this
you might not get the boxplot you want. How can you fix that?)</li>
</ol>
<p>Solution</p>
<p>The problem is likely to be that either your <code>x</code> or your
<code>fill</code> for your boxplot is numerical (<code>rain_pH</code> is
<code>dbl</code>) rather than the categorical variable you need.
Try to use one of the explanatory variables as <code>x</code> and the other
one as <code>fill</code> (or <code>colour</code>):</p>
<div class="sourceCode" id="cb259"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb259-1" title="1"><span class="kw">ggplot</span>(acidrain, <span class="kw">aes</span>(<span class="dt">x =</span> rain_pH, <span class="dt">y =</span> soil_acidity, <span class="dt">fill =</span> soil_depth)) <span class="op">+</span></a>
<a class="sourceLine" id="cb259-2" title="2"><span class="st">  </span><span class="kw">geom_boxplot</span>()</a></code></pre></div>
<p><img src="pasias_files/figure-html/acidrain-2-1.png" width="672" /></p>
<p>That looks as if it worked, but it didn’t. See the boxplot below for
how it’s supposed to be. I need <code>x</code> for the boxplot needs to
be categorical. The easiest way to make it such is to wrap it in
<code>factor</code>:</p>
<div class="sourceCode" id="cb260"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb260-1" title="1"><span class="kw">ggplot</span>(acidrain, <span class="kw">aes</span>(<span class="dt">x =</span> <span class="kw">factor</span>(rain_pH), <span class="dt">y =</span> soil_acidity, <span class="dt">fill =</span> soil_depth)) <span class="op">+</span></a>
<a class="sourceLine" id="cb260-2" title="2"><span class="st">  </span><span class="kw">geom_boxplot</span>()</a></code></pre></div>
<p><img src="pasias_files/figure-html/acidrain-3-1.png" width="672" /></p>
<p>Even though <code>soil_depth</code> looks like numbers, the printout of
the data frame reveals that it is text, so that is OK.</p>
<p>If you prefer, exchange <code>x</code> and <code>fill</code>:</p>
<div class="sourceCode" id="cb261"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb261-1" title="1"><span class="kw">ggplot</span>(acidrain, <span class="kw">aes</span>(<span class="dt">fill =</span> <span class="kw">factor</span>(rain_pH), <span class="dt">y =</span> soil_acidity, <span class="dt">x =</span> soil_depth)) <span class="op">+</span></a>
<a class="sourceLine" id="cb261-2" title="2"><span class="st">  </span><span class="kw">geom_boxplot</span>()</a></code></pre></div>
<p><img src="pasias_files/figure-html/acidrain-4-1.png" width="672" /></p>
<p><span class="math inline">\(\blacksquare\)</span></p>
<ol start="3" style="list-style-type: lower-alpha">
<li>What does your grouped boxplot say about likely
interactions? Explain briefly.</li>
</ol>
<p>Solution</p>
<p>Think about the effect of one of your explanatory variables, for
each level of the other. For example, in the last plot, the effect
of the rain pH pm on the soil acidity is very small at the largest
and smallest depths, but at the middle soil depth 15–30, the
average (median) soil acidity is a lot less when the rain pH is
<em>higher</em> (which seems odd to me). The effect of rain pH being
different according to soil pH is what suggests an interaction
effect.
Another way of thinking about this is imagining what an
interaction plot would look like. This would be a trace going
through the middle (strictly, mean rather than median) of each set
of boxplots of one colour. In the last boxplot, the red trace
would go close to straight across, while the blue one would dip in
the middle. Not parallel, so suggesting an interaction.
Either approach is good.</p>
<p><span class="math inline">\(\blacksquare\)</span></p>
<ol start="4" style="list-style-type: lower-alpha">
<li>Fit an ANOVA with interaction. What do you conclude from
it? You may want to create a column that is the factor version of
<code>rain_pH</code> first.</li>
</ol>
<p>Solution</p>
<p>Following my own hint:</p>
<div class="sourceCode" id="cb262"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb262-1" title="1">acidrain &lt;-<span class="st"> </span>acidrain <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">mutate</span>(<span class="dt">frph =</span> <span class="kw">factor</span>(rain_pH))</a>
<a class="sourceLine" id="cb262-2" title="2">soil<span class="fl">.1</span> &lt;-<span class="st"> </span><span class="kw">aov</span>(soil_acidity <span class="op">~</span><span class="st"> </span>frph <span class="op">*</span><span class="st"> </span>soil_depth, <span class="dt">data =</span> acidrain)</a>
<a class="sourceLine" id="cb262-3" title="3"><span class="kw">summary</span>(soil<span class="fl">.1</span>)</a></code></pre></div>
<pre><code>##                 Df Sum Sq Mean Sq F value Pr(&gt;F)
## frph             1 0.0304 0.03042   0.759  0.401
## soil_depth       2 0.0671 0.03357   0.838  0.457
## frph:soil_depth  2 0.0078 0.00391   0.097  0.908
## Residuals       12 0.4810 0.04008</code></pre>
<p>The interaction is nowhere near significant, perhaps surprisingly. But
bear in mind that there are only 18 observations in total, so each box
on the boxplot is based on <em>three</em> observations only. So the
interaction would have to be a lot bigger to be significant.</p>
<p>The usual procedure after finding a non-significant
interaction is to take it out:</p>
<div class="sourceCode" id="cb264"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb264-1" title="1">soil<span class="fl">.2</span> &lt;-<span class="st"> </span><span class="kw">update</span>(soil<span class="fl">.1</span>, . <span class="op">~</span><span class="st"> </span>. <span class="op">-</span><span class="st"> </span>frph<span class="op">:</span>soil_depth)</a>
<a class="sourceLine" id="cb264-2" title="2"><span class="kw">summary</span>(soil<span class="fl">.2</span>)</a></code></pre></div>
<pre><code>##             Df Sum Sq Mean Sq F value Pr(&gt;F)
## frph         1 0.0304 0.03042   0.871  0.366
## soil_depth   2 0.0671 0.03357   0.962  0.406
## Residuals   14 0.4888 0.03492</code></pre>
<p>The P-values have come down a bit (the result of gaining two df for
error while the error SS only got a tiny bit bigger), but not nearly
enough to be significant.</p>
<p><span class="math inline">\(\blacksquare\)</span></p>
</div>
<div id="treating-hay-fever-1" class="section level2">
<h2><span class="header-section-number">30.8</span> Treating hay fever</h2>
<p>Hay fever is an allergic reaction to things like grasses or
pollen which can make it unpleasant to go outside when the weather is
at its best. A research lab is developing a new compound to relieve
severe cases of hay fever. There were two active ingredients, labelled
A and B, with each one having three levels, low, medium and
high. There were thus <span class="math inline">\(3\times 3=9\)</span> treatment combinations. 36
subjects were available, and these were randomly assigned to
combinations of levels of factor A and factor B, so that each
combination was tested on 4 people. The response variable was the
number of hours of relief from symptoms (so a higher value is
better). The data are in
<a href="http://ritsokiguess.site/datafiles/hayfever.txt">link</a>.</p>
<ol style="list-style-type: lower-alpha">
<li>Read the data and display its structure. Verify that you
have what you were expecting.</li>
</ol>
<p>Solution</p>
<p>Aligned columns separated by spaces, so <code>read_table</code>:</p>
<div class="sourceCode" id="cb266"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb266-1" title="1">my_url &lt;-<span class="st"> &quot;http://ritsokiguess.site/datafiles/hayfever.txt&quot;</span></a>
<a class="sourceLine" id="cb266-2" title="2">hayfever &lt;-<span class="st"> </span><span class="kw">read_table</span>(my_url)</a></code></pre></div>
<pre><code>## 
## ── Column specification ──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
## cols(
##   relief = col_double(),
##   a = col_character(),
##   b = col_character(),
##   replicate = col_double()
## )</code></pre>
<div class="sourceCode" id="cb268"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb268-1" title="1">hayfever</a></code></pre></div>
<pre><code>## # A tibble: 36 x 4
##    relief a     b      replicate
##     &lt;dbl&gt; &lt;chr&gt; &lt;chr&gt;      &lt;dbl&gt;
##  1    2.4 low   low            1
##  2    2.7 low   low            2
##  3    2.3 low   low            3
##  4    2.5 low   low            4
##  5    4.6 low   medium         1
##  6    4.2 low   medium         2
##  7    4.9 low   medium         3
##  8    4.7 low   medium         4
##  9    4.8 low   high           1
## 10    4.5 low   high           2
## # … with 26 more rows</code></pre>
<p>I have 36 observations (patients). There are two categorical columns
<code>a</code> and <code>b</code> corresponding to the two active ingredients,
and they each seem to have levels low, medium and high.<a href="#fn37" class="footnote-ref" id="fnref37"><sup>37</sup></a></p>
<p>The <code>replicate</code> column labels each observation <em>within</em>
its A-B combination, so that each treatment combination was indeed
replicated four times. We won’t be using this column in our analysis;
I think it’s a refugee from the original untidy format the data was in
before it came to you.</p>
<p><span class="math inline">\(\blacksquare\)</span></p>
<ol start="2" style="list-style-type: lower-alpha">
<li>Calculate the mean hours of relief for each combination of
levels of the two active ingredients. Save your results in a data
frame and display that.</li>
</ol>
<p>Solution</p>
<p>This is a group-by and summarize, but there are two active ingredients and they <em>both</em> have to go in the group-by:</p>
<div class="sourceCode" id="cb270"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb270-1" title="1">hayfever <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb270-2" title="2"><span class="st">  </span><span class="kw">group_by</span>(a, b) <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb270-3" title="3"><span class="st">  </span><span class="kw">summarize</span>(<span class="dt">m =</span> <span class="kw">mean</span>(relief)) -&gt;<span class="st"> </span>d</a></code></pre></div>
<pre><code>## `summarise()` has grouped output by &#39;a&#39;. You can override using the `.groups` argument.</code></pre>
<div class="sourceCode" id="cb272"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb272-1" title="1">d</a></code></pre></div>
<pre><code>## # A tibble: 9 x 3
## # Groups:   a [3]
##   a      b          m
##   &lt;chr&gt;  &lt;chr&gt;  &lt;dbl&gt;
## 1 high   high   13.2 
## 2 high   low     5.98
## 3 high   medium 10.3 
## 4 low    high    4.58
## 5 low    low     2.48
## 6 low    medium  4.6 
## 7 medium high    9.12
## 8 medium low     5.45
## 9 medium medium  8.93</code></pre>
<p>I’m using my usual name <code>d</code> for a temporary data frame. I could
have put brackets around my whole pipeline to display its result, but
I still need to save the data frame <code>d</code> to use in a moment.</p>
<p>These levels are in the wrong logical order, but they are in the right order in the original data frame, so we can use <code>fct_inorder</code> first, thus:</p>
<div class="sourceCode" id="cb274"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb274-1" title="1">hayfever <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb274-2" title="2"><span class="st">  </span><span class="kw">mutate</span>(<span class="dt">a =</span> <span class="kw">fct_inorder</span>(a), <span class="dt">b =</span> <span class="kw">fct_inorder</span>(b)) <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb274-3" title="3"><span class="st">  </span><span class="kw">group_by</span>(a, b) <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb274-4" title="4"><span class="st">  </span><span class="kw">summarize</span>(<span class="dt">m =</span> <span class="kw">mean</span>(relief)) -&gt;<span class="st"> </span>d2</a></code></pre></div>
<pre><code>## `summarise()` has grouped output by &#39;a&#39;. You can override using the `.groups` argument.</code></pre>
<div class="sourceCode" id="cb276"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb276-1" title="1">d2</a></code></pre></div>
<pre><code>## # A tibble: 9 x 3
## # Groups:   a [3]
##   a      b          m
##   &lt;fct&gt;  &lt;fct&gt;  &lt;dbl&gt;
## 1 low    low     2.48
## 2 low    medium  4.6 
## 3 low    high    4.58
## 4 medium low     5.45
## 5 medium medium  8.93
## 6 medium high    9.12
## 7 high   low     5.98
## 8 high   medium 10.3 
## 9 high   high   13.2</code></pre>
<p><span class="math inline">\(\blacksquare\)</span></p>
<ol start="3" style="list-style-type: lower-alpha">
<li>Make an interaction plot, showing how the mean pain relief depends on the combination of levels of A and B. It is probably easiest to use the data frame you obtained in the previous part.</li>
</ol>
<p>Solution</p>
<p>My column of mean relief values is called <code>m</code>. Use whatever
name you gave it. I’m going to use my proper-order data frame for
this:</p>
<div class="sourceCode" id="cb278"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb278-1" title="1"><span class="kw">ggplot</span>(d2, <span class="kw">aes</span>(<span class="dt">x =</span> a, <span class="dt">y =</span> m, <span class="dt">colour =</span> b, <span class="dt">group =</span> b)) <span class="op">+</span></a>
<a class="sourceLine" id="cb278-2" title="2"><span class="st">  </span><span class="kw">geom_point</span>() <span class="op">+</span><span class="st"> </span><span class="kw">geom_line</span>()</a></code></pre></div>
<p><img src="pasias_files/figure-html/zellerin-1.png" width="672" /></p>
<p>Or, you probably had this:</p>
<div class="sourceCode" id="cb279"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb279-1" title="1"><span class="kw">ggplot</span>(d, <span class="kw">aes</span>(<span class="dt">x =</span> a, <span class="dt">y =</span> m, <span class="dt">colour =</span> b, <span class="dt">group =</span> b)) <span class="op">+</span></a>
<a class="sourceLine" id="cb279-2" title="2"><span class="st">  </span><span class="kw">geom_point</span>() <span class="op">+</span><span class="st"> </span><span class="kw">geom_line</span>()</a></code></pre></div>
<p><img src="pasias_files/figure-html/bapplin-1.png" width="672" /></p>
<p>Since <code>a</code> and <code>b</code> both have three levels, you could just as well use them the other way around:</p>
<div class="sourceCode" id="cb280"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb280-1" title="1"><span class="kw">ggplot</span>(d2, <span class="kw">aes</span>(<span class="dt">x =</span> b, <span class="dt">y =</span> m, <span class="dt">colour =</span> a, <span class="dt">group =</span> a)) <span class="op">+</span></a>
<a class="sourceLine" id="cb280-2" title="2"><span class="st">  </span><span class="kw">geom_point</span>() <span class="op">+</span><span class="st"> </span><span class="kw">geom_line</span>()</a></code></pre></div>
<p><img src="pasias_files/figure-html/vonmengen-1.png" width="672" /></p>
<p>The plot looks different depending on how you draw it, but the
conclusion from it (below) will be the same.</p>
<p><span class="math inline">\(\blacksquare\)</span></p>
<ol start="4" style="list-style-type: lower-alpha">
<li>What do you conclude from your interaction plot? Explain briefly.</li>
</ol>
<p>Solution</p>
<p>The three lines are not particularly close to being parallel, so I
would expect to see an interaction between the two active
ingredients (that is, the number of hours of pain relief depends
on the combination of the two of them).</p>
<p>Extra: It is always a judgment call to decide whether the lines
are “approximately parallel” or not. It depends on how much
variability there is in the data, which the interaction plot
doesn’t show. Another idea is to add the data to the interaction
plot, colour-coded in the same way. I would do this by taking out
the <code>geom_point</code> for the means and add one instead for the
data, taken from the original data frame:</p>
<div class="sourceCode" id="cb281"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb281-1" title="1"><span class="kw">ggplot</span>(d2, <span class="kw">aes</span>(<span class="dt">x =</span> a, <span class="dt">y =</span> m, <span class="dt">colour =</span> b, <span class="dt">group =</span> b)) <span class="op">+</span></a>
<a class="sourceLine" id="cb281-2" title="2"><span class="st">  </span><span class="kw">geom_line</span>() <span class="op">+</span></a>
<a class="sourceLine" id="cb281-3" title="3"><span class="st">  </span><span class="kw">geom_point</span>(<span class="dt">data =</span> hayfever, <span class="kw">aes</span>(<span class="dt">y =</span> relief))</a></code></pre></div>
<p><img src="pasias_files/figure-html/swaub-1.png" width="672" /></p>
<p>Technique: for that last <code>geom_point</code>, put in anything that
changes: a new data frame, and a new <code>y</code> for the plot, but the
<code>x</code> and <code>colour</code> and <code>group</code> are the same as they
were before, so I don’t need to specify them.</p>
<p>The points are <em>very</em> close to the lines, so there is almost no
residual variability. This makes it more convincing that the
interaction is real and will be significant.</p>
<p><span class="math inline">\(\blacksquare\)</span></p>
<ol start="5" style="list-style-type: lower-alpha">
<li>Run an analysis of variance with interaction. What do you conclude?</li>
</ol>
<p>Solution</p>
<div class="sourceCode" id="cb282"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb282-1" title="1">hayfever<span class="fl">.1</span> &lt;-<span class="st"> </span><span class="kw">aov</span>(relief <span class="op">~</span><span class="st"> </span>a <span class="op">*</span><span class="st"> </span>b, <span class="dt">data =</span> hayfever)</a>
<a class="sourceLine" id="cb282-2" title="2"><span class="kw">summary</span>(hayfever<span class="fl">.1</span>)</a></code></pre></div>
<pre><code>##             Df Sum Sq Mean Sq F value Pr(&gt;F)    
## a            2 220.02  110.01  1827.9 &lt;2e-16 ***
## b            2 123.66   61.83  1027.3 &lt;2e-16 ***
## a:b          4  29.42    7.36   122.2 &lt;2e-16 ***
## Residuals   27   1.63    0.06                   
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<p>The interaction is (strongly) significant. The hours of relief depend on the combination of levels of the active ingredients A and B.</p>
<p>Don’t try to interpret the main effects of A and B from here. That’s what simple effects are for, coming up.</p>
<p><span class="math inline">\(\blacksquare\)</span></p>
<ol start="6" style="list-style-type: lower-alpha">
<li>Analyze the simple effects of B when A is
<code>medium</code>. (This means doing an appropriate <code>aov</code> and
an appropriate Tukey, if warranted.)</li>
</ol>
<p>Solution</p>
<p>First, we pull out only the data where A is <code>medium</code>, and then we do a one-way analysis of B on that data. This is the slick way, though you can certainly save the result of <code>filter</code> first:</p>
<div class="sourceCode" id="cb284"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb284-1" title="1">hayfever <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb284-2" title="2"><span class="st">  </span><span class="kw">filter</span>(a <span class="op">==</span><span class="st"> &quot;medium&quot;</span>) <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb284-3" title="3"><span class="st">  </span><span class="kw">aov</span>(relief <span class="op">~</span><span class="st"> </span>b, <span class="dt">data =</span> .) -&gt;<span class="st"> </span>simple_medium</a>
<a class="sourceLine" id="cb284-4" title="4"><span class="kw">summary</span>(simple_medium)</a></code></pre></div>
<pre><code>##             Df Sum Sq Mean Sq F value   Pr(&gt;F)    
## b            2  34.16  17.081   262.8 1.04e-08 ***
## Residuals    9   0.59   0.065                     
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<p>There is definitely some effect of ingredient B when A is medium. What
is it? Tukey will tell us:</p>
<div class="sourceCode" id="cb286"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb286-1" title="1"><span class="kw">TukeyHSD</span>(simple_medium)</a></code></pre></div>
<pre><code>##   Tukey multiple comparisons of means
##     95% family-wise confidence level
## 
## Fit: aov(formula = relief ~ b, data = .)
## 
## $b
##               diff       lwr       upr     p adj
## low-high    -3.675 -4.178336 -3.171664 0.0000000
## medium-high -0.200 -0.703336  0.303336 0.5323662
## medium-low   3.475  2.971664  3.978336 0.0000000</code></pre>
<p>There is no difference between medium and high (levels of B), but both of these are better in terms of relief than low is.</p>
<p><span class="math inline">\(\blacksquare\)</span></p>
<ol start="7" style="list-style-type: lower-alpha">
<li>Analyze the simple effects of B when A is <code>high</code>.</li>
</ol>
<p>Solution</p>
<p>Same idea: pull out only the data where A is <code>high</code>, do a one-way analysis of B, and do Tukey if needed:</p>
<div class="sourceCode" id="cb288"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb288-1" title="1">hayfever <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb288-2" title="2"><span class="st">  </span><span class="kw">filter</span>(a <span class="op">==</span><span class="st"> &quot;high&quot;</span>) <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb288-3" title="3"><span class="st">  </span><span class="kw">aov</span>(relief <span class="op">~</span><span class="st"> </span>b, <span class="dt">data =</span> .) -&gt;<span class="st"> </span>simple_high</a>
<a class="sourceLine" id="cb288-4" title="4"><span class="kw">summary</span>(simple_high)</a></code></pre></div>
<pre><code>##             Df Sum Sq Mean Sq F value   Pr(&gt;F)    
## b            2 107.02   53.51     796 7.49e-11 ***
## Residuals    9   0.61    0.07                     
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<div class="sourceCode" id="cb290"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb290-1" title="1"><span class="kw">TukeyHSD</span>(simple_high)</a></code></pre></div>
<pre><code>##   Tukey multiple comparisons of means
##     95% family-wise confidence level
## 
## Fit: aov(formula = relief ~ b, data = .)
## 
## $b
##               diff       lwr       upr p adj
## low-high    -7.275 -7.786868 -6.763132 0e+00
## medium-high -2.975 -3.486868 -2.463132 2e-07
## medium-low   4.300  3.788132  4.811868 0e+00</code></pre>
<p>When A is high, there is definitely an effect of B again, but this
time high (for B) is better than medium is better than low. (All the
P-values in Tukey are very small.)</p>
<p>You could guess this from the interaction plot as well (whichever one
you came up with): when A is high, it is better for B to be high as
well, but when A is medium or low, there is not much difference
between B being medium or high.</p>
<p>Extra: here, the effect of B is different, depending on what A is. This is
what a significant interaction <em>means</em>. If there were no
significant interaction, the effect of B would always be the same, no
matter what A was.</p>
<p><span class="math inline">\(\blacksquare\)</span></p>
</div>
<div id="focused-comparisons-of-the-effect-of-caffeine-1" class="section level2">
<h2><span class="header-section-number">30.9</span> Focused comparisons of the effect of caffeine</h2>
<p>Does caffeine help students do better on a certain test? To
find out, 36 students were randomly allocated to three groups (12 in
each group). Each student received a fixed number of cups of coffee
while they were studying, but the students didn’t know whether they
were receiving all full-strength coffee (“high”), all decaf coffee
(“low”) or a 50-50 mixture of the two (“moderate”). For each
subject, their group was recorded as well as their score on the
test. The data are in
<a href="http://ritsokiguess.site/datafiles/caffeine.csv">link</a>, as a
<code>.csv</code> file.</p>
<p>This time we look at
contrasts. Suppose I knew ahead of time
that I wanted to compare moderate caffeine with high, and any
caffeine with none. (In the latter case, we’re comparing
“no caffeine” against the average of the other two groups.)</p>
<p>In the previous go-through of the caffeine data, we
discovered that <code>amount</code> was actually text rather than a
factor, but we also discovered that it <em>didn’t matter</em>. Here it
does matter, so the first thing we have to do is to re-do the
<code>pivot_longer</code>, creating a factor version of <code>amount</code>.</p>
<ol style="list-style-type: lower-alpha">
<li>Read in the data again, from
<a href="http://ritsokiguess.site/datafiles/caffeine.csv">link</a>, and
display it. This is the untidy format, so name it appropriately:</li>
</ol>
<p>Solution</p>
<div class="sourceCode" id="cb292"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb292-1" title="1">my_url &lt;-<span class="st"> &quot;http://individual.utoronto.ca/kbutler/stad29/caffeine.csv&quot;</span></a>
<a class="sourceLine" id="cb292-2" title="2">caffeine.untidy &lt;-<span class="st"> </span><span class="kw">read_csv</span>(my_url)</a></code></pre></div>
<pre><code>## 
## ── Column specification ──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
## cols(
##   Sub = col_double(),
##   High = col_double(),
##   Moderate = col_double(),
##   None = col_double()
## )</code></pre>
<div class="sourceCode" id="cb294"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb294-1" title="1">caffeine.untidy</a></code></pre></div>
<pre><code>## # A tibble: 12 x 4
##      Sub  High Moderate  None
##    &lt;dbl&gt; &lt;dbl&gt;    &lt;dbl&gt; &lt;dbl&gt;
##  1     1    72       68    68
##  2     2    65       80    74
##  3     3    68       64    59
##  4     4    83       65    61
##  5     5    79       69    65
##  6     6    92       79    72
##  7     7    69       80    80
##  8     8    74       63    58
##  9     9    78       69    65
## 10    10    83       70    60
## 11    11    88       83    78
## 12    12    71       75    75</code></pre>
<p>One caffeine level per column, rather than a column of caffeine
levels, so untidy.</p>
<p><span class="math inline">\(\blacksquare\)</span></p>
<ol start="2" style="list-style-type: lower-alpha">
<li>Copy your <code>pivot_longer</code> from before, only this time add
<code>names_ptypes = list(amount=factor())</code> to the end of it. Take a look at the
results. What has changed from before?</li>
</ol>
<p>Solution</p>
<p>We’ll save into <code>caffeine</code> again:</p>
<div class="sourceCode" id="cb296"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb296-1" title="1">caffeine.untidy <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb296-2" title="2"><span class="st">  </span><span class="kw">pivot_longer</span>(<span class="op">-</span>Sub, <span class="dt">names_to=</span><span class="st">&quot;amount&quot;</span>, <span class="dt">values_to=</span><span class="st">&quot;score&quot;</span>, </a>
<a class="sourceLine" id="cb296-3" title="3">               <span class="dt">names_ptypes =</span> <span class="kw">list</span>(<span class="dt">amount=</span><span class="kw">factor</span>())) -&gt;<span class="st"> </span>caffeine</a>
<a class="sourceLine" id="cb296-4" title="4">caffeine</a></code></pre></div>
<pre><code>## # A tibble: 36 x 3
##      Sub amount   score
##    &lt;dbl&gt; &lt;fct&gt;    &lt;dbl&gt;
##  1     1 High        72
##  2     1 Moderate    68
##  3     1 None        68
##  4     2 High        65
##  5     2 Moderate    80
##  6     2 None        74
##  7     3 High        68
##  8     3 Moderate    64
##  9     3 None        59
## 10     4 High        83
## # … with 26 more rows</code></pre>
<p>The variable created for the “names” is now a
<code>factor</code>: it was text before. Maybe we should have made it a
factor before (it wouldn’t have done any harm), but we got away with
not doing so.</p>
<p><span class="math inline">\(\blacksquare\)</span></p>
<ol start="3" style="list-style-type: lower-alpha">
<li>Using the newly tidied caffeine data, run the ANOVA
<em>as a regression</em> (that is, using <code>lm</code>). Look at the
<code>summary</code> of the output. What do you see?</li>
</ol>
<p>Solution</p>
<p>Extra: I’m going to run the ANOVA the “old way” first, so that we can
compare results. You don’t need to do this:</p>
<div class="sourceCode" id="cb298"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb298-1" title="1">caffeine.old &lt;-<span class="st"> </span><span class="kw">aov</span>(score <span class="op">~</span><span class="st"> </span>amount, <span class="dt">data =</span> caffeine)</a>
<a class="sourceLine" id="cb298-2" title="2"><span class="kw">summary</span>(caffeine.old)</a></code></pre></div>
<pre><code>##             Df Sum Sq Mean Sq F value Pr(&gt;F)  
## amount       2  477.7  238.86   3.986 0.0281 *
## Residuals   33 1977.5   59.92                 
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<div class="sourceCode" id="cb300"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb300-1" title="1"><span class="kw">TukeyHSD</span>(caffeine.old)</a></code></pre></div>
<pre><code>##   Tukey multiple comparisons of means
##     95% family-wise confidence level
## 
## Fit: aov(formula = score ~ amount, data = caffeine)
## 
## $amount
##                    diff       lwr       upr     p adj
## Moderate-High -4.750000 -12.50468  3.004679 0.3025693
## None-High     -8.916667 -16.67135 -1.161987 0.0213422
## None-Moderate -4.166667 -11.92135  3.588013 0.3952176</code></pre>
<p>End of digression.</p>
<p>Now we’ll do it using <code>lm</code>, with contrasts later, and see how
things change:</p>
<div class="sourceCode" id="cb302"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb302-1" title="1">caffeine<span class="fl">.2</span> &lt;-<span class="st"> </span><span class="kw">lm</span>(score <span class="op">~</span><span class="st"> </span>amount, <span class="dt">data =</span> caffeine)</a>
<a class="sourceLine" id="cb302-2" title="2"><span class="kw">summary</span>(caffeine<span class="fl">.2</span>)</a></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = score ~ amount, data = caffeine)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -11.833  -6.958  -2.458   6.354  15.167 
## 
## Coefficients:
##                Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)      76.833      2.235  34.383  &lt; 2e-16 ***
## amountModerate   -4.750      3.160  -1.503  0.14234    
## amountNone       -8.917      3.160  -2.821  0.00803 ** 
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 7.741 on 33 degrees of freedom
## Multiple R-squared:  0.1946, Adjusted R-squared:  0.1458 
## F-statistic: 3.986 on 2 and 33 DF,  p-value: 0.02815</code></pre>
<p>Look at the slopes. They are <code>amount</code> followed by one of the
amounts of caffeine. R is using “high” as a baseline (that’s the
first level alphabetically), so the
<code>amountModerate</code> line is testing high vs. moderate: high is
<em>not</em> significantly higher, in terms of test scores, than
moderate. That’s one of the things I wanted to test. What about the
coefficient for <code>amountNone</code>? That’s none vs. <em>high</em>,
since high was the baseline. This is, as we saw from Tukey,
significant. But it is not what I said we wanted to test.</p>
<p>Extra: in case you’re curious, you can also get the regular analysis of
variance table as below. <code>anova</code> is multi-talented:</p>
<div class="sourceCode" id="cb304"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb304-1" title="1"><span class="kw">anova</span>(caffeine<span class="fl">.2</span>)</a></code></pre></div>
<pre><code>## Analysis of Variance Table
## 
## Response: score
##           Df  Sum Sq Mean Sq F value  Pr(&gt;F)  
## amount     2  477.72 238.861  3.9861 0.02815 *
## Residuals 33 1977.50  59.924                  
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<p>The problem is that you can’t naturally do Tukey this way, which is
often what you want to do next. That’s why we used <code>aov</code> before.</p>
<p>Since we have a regression model (albeit a peculiar one), we can test
whether we should remove <code>amount</code> (that is, whether it has any
impact on test scores) this way too:</p>
<div class="sourceCode" id="cb306"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb306-1" title="1"><span class="kw">drop1</span>(caffeine<span class="fl">.2</span>, <span class="dt">test =</span> <span class="st">&quot;F&quot;</span>)</a></code></pre></div>
<pre><code>## Single term deletions
## 
## Model:
## score ~ amount
##        Df Sum of Sq    RSS    AIC F value  Pr(&gt;F)  
## &lt;none&gt;              1977.5 150.22                  
## amount  2    477.72 2455.2 154.01  3.9861 0.02815 *
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<p>Same conclusion: there is some effect of caffeine level on test score.</p>
<p><span class="math inline">\(\blacksquare\)</span></p>
<ol start="4" style="list-style-type: lower-alpha">
<li>Obtain the different values of <code>amount</code>, in the order
that R has them.</li>
</ol>
<p>Solution</p>
<p>Count them, or find the distinct ones:</p>
<div class="sourceCode" id="cb308"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb308-1" title="1">caffeine <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">group_by</span>(amount) <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">summarize</span>(<span class="dt">count =</span> <span class="kw">n</span>())</a></code></pre></div>
<pre><code>## # A tibble: 3 x 2
##   amount   count
##   &lt;fct&gt;    &lt;int&gt;
## 1 High        12
## 2 Moderate    12
## 3 None        12</code></pre>
<p>or there is this shortcut to the above:</p>
<div class="sourceCode" id="cb310"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb310-1" title="1">caffeine <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">count</span>(amount)</a></code></pre></div>
<pre><code>## # A tibble: 3 x 2
##   amount       n
##   &lt;fct&gt;    &lt;int&gt;
## 1 High        12
## 2 Moderate    12
## 3 None        12</code></pre>
<p>Or</p>
<div class="sourceCode" id="cb312"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb312-1" title="1">caffeine <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">distinct</span>(amount)</a></code></pre></div>
<pre><code>## # A tibble: 3 x 1
##   amount  
##   &lt;fct&gt;   
## 1 High    
## 2 Moderate
## 3 None</code></pre>
<p>since we didn’t really need to know how many of each there were.</p>
<p>These would all have worked if <code>amount</code> had been text rather a
factor. If you have a genuine <code>factor</code>, you can also ask for
its <code>levels</code>:</p>
<div class="sourceCode" id="cb314"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb314-1" title="1"><span class="kw">with</span>(caffeine, <span class="kw">levels</span>(amount))</a></code></pre></div>
<pre><code>## [1] &quot;High&quot;     &quot;Moderate&quot; &quot;None&quot;</code></pre>
<p>or <code>summary</code> will count them up and list them:</p>
<div class="sourceCode" id="cb316"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb316-1" title="1">caffeine <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">select</span>(amount) <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">summary</span>()</a></code></pre></div>
<pre><code>##       amount  
##  High    :12  
##  Moderate:12  
##  None    :12</code></pre>
<p>This last won’t work if you have a categorical-variable-as-text. It
has to be a genuine factor for it to work.</p>
<p>The categories are High, Moderate and None in that order. For working
with contrasts, we need to have the thing we’re making contrasts for
(see below) as a <code>factor</code>, otherwise it won’t work.</p>
<p><span class="math inline">\(\blacksquare\)</span></p>
<ol start="5" style="list-style-type: lower-alpha">
<li>Create a contrast that compares High with Moderate, ignoring
None. That is, create a vector whose length is the same as the
number of levels of <code>amount</code>, and which has a 1 to represent
High and a <span class="math inline">\(-1\)</span> to represent Moderate.</li>
</ol>
<p>Solution</p>
<p>Put a 0 in for None:</p>
<div class="sourceCode" id="cb318"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb318-1" title="1">c.hm &lt;-<span class="st"> </span><span class="kw">c</span>(<span class="dv">1</span>, <span class="dv">-1</span>, <span class="dv">0</span>)</a></code></pre></div>
<p>Having the 1 and the <span class="math inline">\(-1\)</span> the other way around would also have been fine.</p>
<p><span class="math inline">\(\blacksquare\)</span></p>
<ol start="6" style="list-style-type: lower-alpha">
<li>Create a contrast that compares “any caffeine” against
“none” by comparing None against the average of Moderate and High.</li>
</ol>
<p>Solution</p>
<div class="sourceCode" id="cb319"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb319-1" title="1">c.any &lt;-<span class="st"> </span><span class="kw">c</span>(<span class="op">-</span><span class="fl">0.5</span>, <span class="fl">-0.5</span>, <span class="dv">1</span>)</a></code></pre></div>
<p>Note that both our contrasts have coefficients that add up to zero, as
they must:</p>
<div class="sourceCode" id="cb320"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb320-1" title="1"><span class="kw">sum</span>(c.hm)</a></code></pre></div>
<pre><code>## [1] 0</code></pre>
<div class="sourceCode" id="cb322"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb322-1" title="1"><span class="kw">sum</span>(c.any)</a></code></pre></div>
<pre><code>## [1] 0</code></pre>
<p><span class="math inline">\(\blacksquare\)</span></p>
<ol start="7" style="list-style-type: lower-alpha">
<li>Verify that your two contrasts are orthogonal.</li>
</ol>
<p>Solution</p>
<p>Multiply them together and check that what you get adds up to zero:</p>
<div class="sourceCode" id="cb324"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb324-1" title="1"><span class="kw">sum</span>(c.hm <span class="op">*</span><span class="st"> </span>c.any)</a></code></pre></div>
<pre><code>## [1] 0</code></pre>
<p>Zero, so orthogonal. You can check that writing <code>c.any</code> as
<code>c(-1,-1,2)</code> would also work (and still be orthogonal with
<code>c.hm</code>), and so would writing it as <code>c(1,1,-2)</code>.</p>
<p><span class="math inline">\(\blacksquare\)</span></p>
<ol start="8" style="list-style-type: lower-alpha">
<li>Arrange your contrasts as columns of a matrix (using
<code>cbind</code>), and say that you want to use these as contrasts for
<code>amount</code> (in data frame <code>caffeine</code> or whatever you
called it).</li>
</ol>
<p>Solution</p>
<div class="sourceCode" id="cb326"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb326-1" title="1">m &lt;-<span class="st"> </span><span class="kw">cbind</span>(c.hm, c.any)</a>
<a class="sourceLine" id="cb326-2" title="2"><span class="kw">contrasts</span>(caffeine<span class="op">$</span>amount) &lt;-<span class="st"> </span>m</a></code></pre></div>
<p><span class="math inline">\(\blacksquare\)</span></p>
<ol style="list-style-type: lower-roman">
<li>Fit the ANOVA as an <code>lm</code>, and look at the
<code>summary</code>. What do you conclude about your contrasts?</li>
</ol>
<p>Solution</p>
<div class="sourceCode" id="cb327"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb327-1" title="1">caff<span class="fl">.3</span> &lt;-<span class="st"> </span><span class="kw">lm</span>(score <span class="op">~</span><span class="st"> </span>amount, <span class="dt">data =</span> caffeine)</a>
<a class="sourceLine" id="cb327-2" title="2"><span class="kw">summary</span>(caff<span class="fl">.3</span>)</a></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = score ~ amount, data = caffeine)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -11.833  -6.958  -2.458   6.354  15.167 
## 
## Coefficients:
##             Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)   72.278      1.290  56.022   &lt;2e-16 ***
## amountc.hm     2.375      1.580   1.503   0.1423    
## amountc.any   -4.361      1.825  -2.390   0.0227 *  
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 7.741 on 33 degrees of freedom
## Multiple R-squared:  0.1946, Adjusted R-squared:  0.1458 
## F-statistic: 3.986 on 2 and 33 DF,  p-value: 0.02815</code></pre>
<p><code>c.hm</code> was the contrast between high and moderate
caffeine. This is not significant (P-value 0.142), which is the same
conclusion as Tukey, but the P-value here is quite a bit lower (and
thus closer to being significant). There’s a reason for that: here we
are focusing in on the two contrasts that we really wanted to test,
and ignoring the <span class="math inline">\(F\)</span>-test and the Tukey that tell us stuff that we
don’t care about. By focusing our comparison, we get a better
(smaller) P-value.</p>
<p><code>c.any</code> was none vs. average of any
caffeine. This one is significant, with a P-value of 0.023. So this
contrast tells us that having any caffeine is better than having none.</p>
<p><span class="math inline">\(\blacksquare\)</span></p>
<ol start="10" style="list-style-type: lower-alpha">
<li>What happens if you try to use high caffeine vs. moderate
caffeine and moderate vs. none as your two contrasts?</li>
</ol>
<p>Solution</p>
<div class="sourceCode" id="cb329"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb329-1" title="1">c.hm &lt;-<span class="st"> </span><span class="kw">c</span>(<span class="dv">1</span>, <span class="dv">-1</span>, <span class="dv">0</span>)</a>
<a class="sourceLine" id="cb329-2" title="2">c.mn &lt;-<span class="st"> </span><span class="kw">c</span>(<span class="dv">0</span>, <span class="dv">1</span>, <span class="dv">-1</span>)</a></code></pre></div>
<p>So far so good: the coefficients add up to zero and they reflect the
right comparisons. But now:</p>
<div class="sourceCode" id="cb330"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb330-1" title="1"><span class="kw">sum</span>(c.hm <span class="op">*</span><span class="st"> </span>c.mn)</a></code></pre></div>
<pre><code>## [1] -1</code></pre>
<p>This does <em>not</em> add up to zero, so these two contrasts are not
orthogonal, and we can’t do what we just did. R will give us an answer
if we try it, but it’ll be the <em>wrong</em> answer.<a href="#fn38" class="footnote-ref" id="fnref38"><sup>38</sup></a></p>
<p>The best
description I have seen of what to do here is by David Howell,<a href="#fn39" class="footnote-ref" id="fnref39"><sup>39</sup></a> at
<a href="https://www.uvm.edu/~dhowell/StatPages/More_Stuff/R/AnovaOneway.html">link</a>
(at the bottom).
Let
me try to follow his method.</p>
<p>First we need a vector that is all 1’s, which I have called
<code>c0</code> below. Since each of our contrasts <code>c.hm</code> and
<code>c.mn</code> have 3 things in them (3 groups), we need to add a
“dummy” 3rd contrast to give us a <span class="math inline">\(3\times 3\)</span> array of numbers:<a href="#fn40" class="footnote-ref" id="fnref40"><sup>40</sup></a></p>
<div class="sourceCode" id="cb332"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb332-1" title="1">c0 &lt;-<span class="st"> </span><span class="kw">rep</span>(<span class="dv">1</span>, <span class="dv">3</span>)</a>
<a class="sourceLine" id="cb332-2" title="2">m &lt;-<span class="st"> </span><span class="kw">cbind</span>(c0, c.hm, c.mn)</a>
<a class="sourceLine" id="cb332-3" title="3">m</a></code></pre></div>
<pre><code>##      c0 c.hm c.mn
## [1,]  1    1    0
## [2,]  1   -1    1
## [3,]  1    0   -1</code></pre>
<p>This is what Howell calls an “augmented” matrix of contrasts, since
it has our two contrasts as the second and third columns, plus
the extra dummy one. Next we invert this matrix of contrasts,
which we can do because it’s square. <code>t(m)</code> means
“take the matrix transpose of <code>m</code>”, if you’re trying to keep up at the
back, and <code>solve</code> finds a matrix inverse:</p>
<div class="sourceCode" id="cb334"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb334-1" title="1">minv &lt;-<span class="st"> </span><span class="kw">solve</span>(<span class="kw">t</span>(m))</a></code></pre></div>
<p>and then we remove the first column, which represents the contrast
that we didn’t want anyway (what Howell calls “deaugmenting”):<a href="#fn41" class="footnote-ref" id="fnref41"><sup>41</sup></a></p>
<div class="sourceCode" id="cb335"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb335-1" title="1">m.contr &lt;-<span class="st"> </span>minv[, <span class="dv">-1</span>]</a>
<a class="sourceLine" id="cb335-2" title="2">m.contr</a></code></pre></div>
<pre><code>##            c.hm       c.mn
## [1,]  0.6666667  0.3333333
## [2,] -0.3333333  0.3333333
## [3,] -0.3333333 -0.6666667</code></pre>
<div class="sourceCode" id="cb337"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb337-1" title="1"><span class="kw">contrasts</span>(caffeine<span class="op">$</span>amount) &lt;-<span class="st"> </span>m.contr</a></code></pre></div>
<p>The columns of <code>m.contr</code> are our new
contrasts. Note that they appear to be something else: high vs. the
average of moderate and none, and none vs. the average of moderate
and high. They are actually
<em>not</em> orthogonal, but if Howell is to be trusted,<a href="#fn42" class="footnote-ref" id="fnref42"><sup>42</sup></a> they can be
used to test what we want.
Now fit the model again:</p>
<div class="sourceCode" id="cb338"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb338-1" title="1">caff<span class="fl">.4</span> &lt;-<span class="st"> </span><span class="kw">lm</span>(score <span class="op">~</span><span class="st"> </span>amount, <span class="dt">data =</span> caffeine)</a>
<a class="sourceLine" id="cb338-2" title="2"><span class="kw">summary</span>(caff<span class="fl">.4</span>)</a></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = score ~ amount, data = caffeine)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -11.833  -6.958  -2.458   6.354  15.167 
## 
## Coefficients:
##             Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)   72.278      1.290  56.022   &lt;2e-16 ***
## amountc.hm     4.750      3.160   1.503    0.142    
## amountc.mn     4.167      3.160   1.318    0.196    
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 7.741 on 33 degrees of freedom
## Multiple R-squared:  0.1946, Adjusted R-squared:  0.1458 
## F-statistic: 3.986 on 2 and 33 DF,  p-value: 0.02815</code></pre>
<p>The rows <code>amountc.hm</code> and <code>amountc.mn</code> are the proper tests
for our contrasts <code>c.hm</code> and <code>c.mn</code>.
<code>c.hm</code> is not significant (P-value 0.14) and
<code>c.mn</code> is not significant either
(P-value 0.20). This is the same significance as from Tukey, but note
that the P-values for the non-significant tests are much lower than
the corresponding ones from Tukey, once again because we have focused
on just these comparisons, and not on any others. We decided ahead of
time to test just these, and gave ourselves the best chance of finding
significance that we could.</p>
<p><span class="math inline">\(\blacksquare\)</span></p>
</div>
<div id="who-studies-the-most-outside-class-1" class="section level2">
<h2><span class="header-section-number">30.10</span> Who studies the most outside class?</h2>
<p>A social scientist wanted to see how many hours students
studied outside of class. She took a random sample of 75 students
from three different majors: math, social science and English, and
recorded the number of weekly outside-class study hours for each
student. The data can be found at
<a href="http://ritsokiguess.site/datafiles/studyhours.txt">link</a>. The
social scientist had two research questions: whether math students study
more outside of class than the other students, and whether English and
social science students study different amounts of time outside class.</p>
<ol style="list-style-type: lower-alpha">
<li>Explain briefly why contrasts would be a better idea here
than ANOVA with Tukey.</li>
</ol>
<p>Solution</p>
<p>The researcher is not interested in all the comparisons between
the groups, but rather in two specific ones (as detailed in the
question). So we should focus our attention on those
comparisons. This is what contrasts are for.</p>
<p><span class="math inline">\(\blacksquare\)</span></p>
<ol start="2" style="list-style-type: lower-alpha">
<li>Read in the data and make side-by-side boxplots of study
hours by major. What do the boxplots suggest about the comparisons
that the researcher wants to make?</li>
</ol>
<p>Solution</p>
<p>Separated by one space. There appear to be some strange quotes
in there, but we’ll ignore those and see whether they cause any
trouble:</p>
<div class="sourceCode" id="cb340"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb340-1" title="1">my_url &lt;-<span class="st"> &quot;http://ritsokiguess.site/datafiles/studyhours.txt&quot;</span></a>
<a class="sourceLine" id="cb340-2" title="2">studyhours &lt;-<span class="st"> </span><span class="kw">read_delim</span>(my_url, <span class="st">&quot; &quot;</span>)</a></code></pre></div>
<pre><code>## 
## ── Column specification ──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
## cols(
##   id = col_double(),
##   major = col_character(),
##   hours = col_double()
## )</code></pre>
<div class="sourceCode" id="cb342"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb342-1" title="1">studyhours</a></code></pre></div>
<pre><code>## # A tibble: 75 x 3
##       id major hours
##    &lt;dbl&gt; &lt;chr&gt; &lt;dbl&gt;
##  1     1 math     15
##  2     2 math     20
##  3     3 math     14
##  4     4 math     15
##  5     5 math     14
##  6     6 math     10
##  7     7 math     12
##  8     8 math      9
##  9     9 math     10
## 10    10 math     11
## # … with 65 more rows</code></pre>
<p>So far so good. 75 students, in tidy format.</p>
<div class="sourceCode" id="cb344"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb344-1" title="1"><span class="kw">ggplot</span>(studyhours, <span class="kw">aes</span>(<span class="dt">x =</span> major, <span class="dt">y =</span> hours)) <span class="op">+</span><span class="st"> </span><span class="kw">geom_boxplot</span>()</a></code></pre></div>
<p><img src="pasias_files/figure-html/studyhours-2-1.png" width="672" /></p>
<p>This suggests that the math students study more than the others, but
the English and social science students study about the same amount.</p>
<p>I see some rather consistent right-skewness here (but no outliers). We
have 25 observations in each group, a decent amount of data, so I’m
not too worried, but a transformation could be a good idea, something
like square root, perhaps. The spreads are not that unequal, but it
<em>is</em> true that the Math students have both the largest median
<em>and</em> the largest spread, and the social science students are the
lowest on both.</p>
<p>Extra: Box-Cox also works on ANOVA-type data, since that is an <code>lm</code>
kind of model:</p>
<div class="sourceCode" id="cb345"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb345-1" title="1"><span class="kw">boxcox</span>(hours <span class="op">~</span><span class="st"> </span>major, <span class="dt">data =</span> studyhours)</a></code></pre></div>
<p><img src="pasias_files/figure-html/studyhours-3-1.png" width="672" /></p>
<p>This suggests that some kind of transformation would be a good idea
(no transformation, power 1, is not supported by the data). My guess
of 0.5 is not bad; that, or something a bit less like 0.25 (fourth
root) would be good. Even log is supportable. But we’ll proceed
without transformation in this question to give you some practice with
contrasts. Despite appearances, I do (sometimes) like to make things
not so complicated!</p>
<p><span class="math inline">\(\blacksquare\)</span></p>
<ol start="3" style="list-style-type: lower-alpha">
<li>Set up contrasts for each of the researcher’s research
questions, bearing in mind the levels of <code>major</code> and the
order in which they come. (For the <code>Math</code> contrast, you want
Math against the average of the other two.)</li>
</ol>
<p>Solution</p>
<p>We need to know what the categories of <code>major</code> are, so that
we can set up the contrasts correctly, so let’s start with that:</p>
<div class="sourceCode" id="cb346"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb346-1" title="1">studyhours <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">select</span>(major) <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">summary</span>()</a></code></pre></div>
<pre><code>##     major          
##  Length:75         
##  Class :character  
##  Mode  :character</code></pre>
<p>Oh. Yeah. We never turned <code>major</code> into a factor. We’d better do
that, and then try again:</p>
<div class="sourceCode" id="cb348"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb348-1" title="1">studyhours &lt;-<span class="st"> </span>studyhours <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">mutate</span>(<span class="dt">major =</span> <span class="kw">factor</span>(major))</a>
<a class="sourceLine" id="cb348-2" title="2">studyhours <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">select</span>(major) <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">summary</span>()</a></code></pre></div>
<pre><code>##      major   
##  english:25  
##  math   :25  
##  socsci :25</code></pre>
<p>In alphabetical order.</p>
<p>All right, contrasts. The English vs. social science one is easier,
so we’ll do that first. Just set it up with a 1 for one of them and a
<span class="math inline">\(-1\)</span> for the other and 0 for math, in the right order according to
what the levels are, viz:</p>
<div class="sourceCode" id="cb350"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb350-1" title="1">c.eng.socsci &lt;-<span class="st"> </span><span class="kw">c</span>(<span class="dv">1</span>, <span class="dv">0</span>, <span class="dv">-1</span>)</a></code></pre></div>
<p>Or <code>c(-1,0,1)</code> would be just as good.</p>
<p>The other one is a bit trickier, because you want math against the
average of the others, like
<span class="math display">\[\mbox{math}-(\mbox{English}+\mbox{socsci})/2.\]</span>
This translates into contrast-ese like this, making sure to get Math
in the middle where it belongs:<a href="#fn43" class="footnote-ref" id="fnref43"><sup>43</sup></a></p>
<div class="sourceCode" id="cb351"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb351-1" title="1">c.math.others &lt;-<span class="st"> </span><span class="kw">c</span>(<span class="op">-</span><span class="fl">0.5</span>, <span class="dv">1</span>, <span class="fl">-0.5</span>)</a></code></pre></div>
<p>The coefficients have to add up to zero, so I have to have two halves
to balance my one 1. Or I can use two <span class="math inline">\(-1\)</span>s and a 2.</p>
<p><span class="math inline">\(\blacksquare\)</span></p>
<ol start="4" style="list-style-type: lower-alpha">
<li>Verify that your two contrasts are orthogonal.</li>
</ol>
<p>Solution</p>
<p>Multiply them together (elementwise, which is how R does it)
and show that what you get adds up to zero:</p>
<div class="sourceCode" id="cb352"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb352-1" title="1"><span class="kw">sum</span>(c.eng.socsci <span class="op">*</span><span class="st"> </span>c.math.others)</a></code></pre></div>
<pre><code>## [1] 0</code></pre>
<p>Zero. Orthogonal.</p>
<p>So we are safely in “familiar” territory, not in the
here-be-dragons<a href="#fn44" class="footnote-ref" id="fnref44"><sup>44</sup></a> land of
non-orthogonal contrasts.</p>
<p><span class="math inline">\(\blacksquare\)</span></p>
<ol start="5" style="list-style-type: lower-alpha">
<li>Create a matrix of contrasts (using <code>cbind</code>) and let
<code>lm</code> know that these are contrasts for <code>major</code>, in
data frame <code>studyhours</code> (or whatever you called it).</li>
</ol>
<p>Solution</p>
<p>So, like the example in lecture (where the
<code>contrasts(model)</code> was admittedly rather confusing):</p>
<div class="sourceCode" id="cb354"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb354-1" title="1">m &lt;-<span class="st"> </span><span class="kw">cbind</span>(c.math.others, c.eng.socsci)</a>
<a class="sourceLine" id="cb354-2" title="2">m</a></code></pre></div>
<pre><code>##      c.math.others c.eng.socsci
## [1,]          -0.5            1
## [2,]           1.0            0
## [3,]          -0.5           -1</code></pre>
<div class="sourceCode" id="cb356"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb356-1" title="1"><span class="kw">contrasts</span>(studyhours<span class="op">$</span>major) &lt;-<span class="st"> </span>m</a></code></pre></div>
<p><span class="math inline">\(\blacksquare\)</span></p>
<ol start="6" style="list-style-type: lower-alpha">
<li>Fit the model using <code>lm</code>. What do you conclude about
your contrasts?</li>
</ol>
<p>Solution</p>
<p>Pretend the ANOVA is a regression (though you can fit ANOVAs
either way: we just used <code>aov</code> before because we were
going to follow up with Tukey):</p>
<div class="sourceCode" id="cb357"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb357-1" title="1">studyhours<span class="fl">.1</span> &lt;-<span class="st"> </span><span class="kw">lm</span>(hours <span class="op">~</span><span class="st"> </span>major, <span class="dt">data =</span> studyhours)</a>
<a class="sourceLine" id="cb357-2" title="2"><span class="kw">summary</span>(studyhours<span class="fl">.1</span>)</a></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = hours ~ major, data = studyhours)
## 
## Residuals:
##    Min     1Q Median     3Q    Max 
##  -6.44  -2.48  -0.48   2.52  10.56 
## 
## Coefficients:
##                    Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)          7.3200     0.3980  18.392  &lt; 2e-16 ***
## majorc.math.others   2.1200     0.5628   3.767 0.000335 ***
## majorc.eng.socsci    0.7800     0.4874   1.600 0.113936    
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 3.447 on 72 degrees of freedom
## Multiple R-squared:  0.1887, Adjusted R-squared:  0.1662 
## F-statistic: 8.374 on 2 and 72 DF,  p-value: 0.0005375</code></pre>
<p>There is a seriously significant difference between the math students
and the others. There is not, however, any kind of difference between
the mean study hours of the English and social science students.</p>
<p><span class="math inline">\(\blacksquare\)</span></p>
<ol start="7" style="list-style-type: lower-alpha">
<li>Are you surprised by the significance or non-significance you
found in the previous part? Explain briefly.</li>
</ol>
<p>Solution</p>
<p>Go back and compare with the boxplots. The math students
studied noticeably more than the others, so it is not
surprising that this difference came out significant. The
median study times for the English and social science students
were similar, so it is not at all surprising that this difference
failed to be significant.</p>
<p>When you set up contrasts, <em>these</em> are the tests you are
interested in, so there is no reason for following up with
Tukey or anything else. But you have to be able to say ahead of
time which contrasts you want to test. This is in
contrast<a href="#fn45" class="footnote-ref" id="fnref45"><sup>45</sup></a> to Tukey, where you don’t have to decide
which comparisons interest you until right at the end.</p>
<p>Another question you might have had is
“how many contrasts can I do”? To answer this, go back and look at the ANOVA table. If
you run an ANOVA using <code>lm</code>, you get the ANOVA table by
passing the fitted model object into <code>anova</code> rather than
<code>summary</code>:<a href="#fn46" class="footnote-ref" id="fnref46"><sup>46</sup></a></p>
<div class="sourceCode" id="cb359"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb359-1" title="1"><span class="kw">anova</span>(studyhours<span class="fl">.1</span>)</a></code></pre></div>
<pre><code>## Analysis of Variance Table
## 
## Response: hours
##           Df Sum Sq Mean Sq F value    Pr(&gt;F)    
## major      2 198.96   99.48  8.3737 0.0005375 ***
## Residuals 72 855.36   11.88                      
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<p>Two degrees of freedom for <code>major</code>, so we can do 2
contrasts. (The example in class had four models of chainsaw, so 3 df
for model, so 3 contrasts possible.) What if we don’t use all those
contrasts up? Try it and see:</p>
<div class="sourceCode" id="cb361"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb361-1" title="1">m &lt;-<span class="st"> </span><span class="kw">cbind</span>(c.math.others)</a>
<a class="sourceLine" id="cb361-2" title="2">m</a></code></pre></div>
<pre><code>##      c.math.others
## [1,]          -0.5
## [2,]           1.0
## [3,]          -0.5</code></pre>
<div class="sourceCode" id="cb363"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb363-1" title="1"><span class="kw">contrasts</span>(studyhours<span class="op">$</span>major) &lt;-<span class="st"> </span>m</a>
<a class="sourceLine" id="cb363-2" title="2">studyhours<span class="fl">.2</span> &lt;-<span class="st"> </span><span class="kw">lm</span>(hours <span class="op">~</span><span class="st"> </span>major, <span class="dt">data =</span> studyhours)</a>
<a class="sourceLine" id="cb363-3" title="3"><span class="kw">summary</span>(studyhours<span class="fl">.2</span>)</a></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = hours ~ major, data = studyhours)
## 
## Residuals:
##    Min     1Q Median     3Q    Max 
##  -6.44  -2.48  -0.48   2.52  10.56 
## 
## Coefficients:
##                    Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)          7.3200     0.3980  18.392  &lt; 2e-16 ***
## majorc.math.others   2.1200     0.5628   3.767 0.000335 ***
## major               -1.1031     0.6893  -1.600 0.113936    
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 3.447 on 72 degrees of freedom
## Multiple R-squared:  0.1887, Adjusted R-squared:  0.1662 
## F-statistic: 8.374 on 2 and 72 DF,  p-value: 0.0005375</code></pre>
<p>The two P-values are identical, but the second one is not now
identified with any contrast (so we just ignore it). If we were only
interested in how math students compared with the rest, we could test
it this way.</p>
<p>Or, we could relabel the students as “math” and “other” and just
do a two-sample <span class="math inline">\(t\)</span>-test. To do this, we need to delve into
<code>forcats</code> (which is a part of the <code>tidyverse</code>). It deals
with categorical variables which are genuine factors, which we haven’t
had much cause to do so far. But now we do. What we want to do is to
<em>recode</em> the levels of <code>major</code>, which is done by
<code>fct_recode</code>:</p>
<div class="sourceCode" id="cb365"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb365-1" title="1">studyhoursx &lt;-<span class="st"> </span>studyhours <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb365-2" title="2"><span class="st">  </span><span class="kw">mutate</span>(<span class="dt">mathrest =</span> <span class="kw">fct_recode</span>(major,</a>
<a class="sourceLine" id="cb365-3" title="3">    <span class="st">&quot;rest&quot;</span> =<span class="st"> &quot;english&quot;</span>,</a>
<a class="sourceLine" id="cb365-4" title="4">    <span class="st">&quot;rest&quot;</span> =<span class="st"> &quot;socsci&quot;</span></a>
<a class="sourceLine" id="cb365-5" title="5">  ))</a>
<a class="sourceLine" id="cb365-6" title="6">studyhoursx <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">count</span>(mathrest)</a></code></pre></div>
<pre><code>## # A tibble: 2 x 2
##   mathrest     n
##   &lt;fct&gt;    &lt;int&gt;
## 1 rest        50
## 2 math        25</code></pre>
<p>The way <code>fct_recode</code> works is that you first give a factor,
here <code>major</code>, then you define a list of new levels in terms of
the old ones. We want a student whose major is either English or
Social Science to end up in the new not-math group that we’ll call
<code>rest</code>, so we need two lines inside <code>fct_recode</code>, one
that says that the new <code>rest</code> group includes the old
<code>english</code> majors, and another that says that <code>rest</code> also
includes the old <code>socsci</code> majors. Any levels not mentioned
(here <code>math</code>) are left unchanged.</p>
<p>I did this wrong the first time: I got the things before and after the
<code>=</code> in <code>fct_recode</code> the wrong way around.</p>
<p>The last line is to check that the result makes sense. I previously
had 25 students in each major. Now I have 25 students for whom
<code>mathrest</code> is <code>math</code> (the math majors) and <span class="math inline">\(50=25+25\)</span>
students for whom <code>mathrest</code> is <code>rest</code> (everyone else).</p>
<p>Now, the <span class="math inline">\(t\)</span>-test.</p>
<div class="sourceCode" id="cb367"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb367-1" title="1"><span class="kw">t.test</span>(hours <span class="op">~</span><span class="st"> </span>mathrest, <span class="dt">data =</span> studyhoursx, <span class="dt">var.equal =</span> T)</a></code></pre></div>
<pre><code>## 
##  Two Sample t-test
## 
## data:  hours by mathrest
## t = -3.7269, df = 73, p-value = 0.0003796
## alternative hypothesis: true difference in means is not equal to 0
## 95 percent confidence interval:
##  -4.880528 -1.479472
## sample estimates:
## mean in group rest mean in group math 
##               6.26               9.44</code></pre>
<p>This is very close to, but not the same as, the test with the contrasts,
because we are not quite testing the same thing. Here, we are
comparing the mean of the math students to the mean of everyone else,
thrown together into one big bag, but with the contrasts, we are
comparing the mean of the math students with the <em>average of the
means</em> of the other two groups, treating them as different. (Not
clear? Well, it’s not that clear to me either.)</p>
<p>That business with the <code>var.equal=T</code>? This is doing a pooled
<span class="math inline">\(t\)</span>-test. I did that here because the ANOVA is assuming equal spreads
within the groups (which is what a pooled <span class="math inline">\(t\)</span>-test does) and I thought
I should do my best to be consistent. A pooled <span class="math inline">\(t\)</span>-test is really a
two-group one-way ANOVA, or at least it is if it is done two-sided.</p>
<p><span class="math inline">\(\blacksquare\)</span></p>
</div>
<div id="mental-context-1" class="section level2">
<h2><span class="header-section-number">30.11</span> Mental context</h2>
<p>It is believed that being in the same mental context for
learning and for testing leads to better test scores. An experiment
was carried out to test this. During the learning phase, subjects
learned a list of 80 words in a room painted orange and decorated with
posters, paintings and other paraphernalia.<a href="#fn47" class="footnote-ref" id="fnref47"><sup>47</sup></a> A memory test was given to all subjects
immediately after they had learned the words, to give the impression
that the experiment was over. (The results of this test were
discarded.) One day later, subjects were unexpectedly re-tested under
different experimental conditions and asked to write down all the
words of the original list that they could remember. The re-test took
place in five different conditions, which subjects were randomly
allocated to one of:</p>
<ul>
<li><p>Same context: in the original orange-painted room.</p></li>
<li><p>Different context: in a very different room, painted grey and
located in a different part of campus.</p></li>
<li><p>Imaginary context: in the grey room, but subjects are asked to
remember the orange room in which they took the original test. To
help them with this, the experimenter begins by asking them several
questions about the orange room and the objects in it.</p></li>
<li><p>Photographed context: in the grey room, but subjects are shown
photographs of the orange room.</p></li>
<li><p>Placebo context: in the grey room, with subjects first being
asked to recall their living room.</p></li>
</ul>
<p>In each case, the response variable was the number of words on the
original list successfully recalled by each subject.</p>
<p>50 subjects in total completed the experiment, 10 under each of the 5
conditions.</p>
<p>The researchers had four research hypotheses to test with the data:</p>
<ul>
<li><p>Groups where the context matches (is the same, or is simulated
by imagining or photograph) will perform better than groups with
different or placebo contexts.</p></li>
<li><p>The group with the same context will differ from the group with
imaginary or photographed contexts.</p></li>
<li><p>The imaginary-context group will differ from the
photographed-context group.</p></li>
<li><p>The different-context group will differ from the placebo-context group.</p></li>
</ul>
<p>The research hypotheses are (as is usual) written as
<em>alternative</em> hypotheses. We can rewrite them as null
hypotheses, with some extra wording to facilitate converting them
into contrasts, like this:</p>
<ul>
<li><p>The mean of the <code>same</code>, <code>imaginary</code> and
<code>photograph</code> groups (group means) is equal to the mean of the
<code>different</code> and <code>placebo</code> groups (group means).</p></li>
<li><p>The mean of the <code>imaginary</code> and <code>photograph</code>
groups is equal to the (mean of the) <code>same</code> group.</p></li>
<li><p>The <code>imaginary</code> and the <code>photograph</code> groups will
have the same mean.</p></li>
<li><p>The <code>different</code> and the <code>placebo</code> groups will
have the same mean.</p></li>
</ul>
<p>The data are in
<a href="http://ritsokiguess.site/datafiles/smith.txt">link</a> (the
original researcher’s name was Smith).</p>
<ol style="list-style-type: lower-alpha">
<li>Read in the data and verify that you have a column called
<code>context</code> that is text and a column called
<code>words</code> that is a (whole) number.</li>
</ol>
<p>Solution</p>
<p>The usual thing — read in the data appropriately and look at the
data frame you got:</p>
<div class="sourceCode" id="cb369"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb369-1" title="1">my_url &lt;-<span class="st"> &quot;http://ritsokiguess.site/datafiles/smith.txt&quot;</span></a>
<a class="sourceLine" id="cb369-2" title="2">smith &lt;-<span class="st"> </span><span class="kw">read_delim</span>(my_url, <span class="st">&quot; &quot;</span>)</a></code></pre></div>
<pre><code>## 
## ── Column specification ──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
## cols(
##   id = col_double(),
##   context = col_character(),
##   words = col_double()
## )</code></pre>
<div class="sourceCode" id="cb371"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb371-1" title="1">smith</a></code></pre></div>
<pre><code>## # A tibble: 50 x 3
##       id context words
##    &lt;dbl&gt; &lt;chr&gt;   &lt;dbl&gt;
##  1     1 same       25
##  2     2 same       26
##  3     3 same       17
##  4     4 same       15
##  5     5 same       14
##  6     6 same       17
##  7     7 same       14
##  8     8 same       20
##  9     9 same       11
## 10    10 same       21
## # … with 40 more rows</code></pre>
<p><code>dbl</code> actually means “decimal number”, but these look like whole numbers, so I think we are good.</p>
<p><span class="math inline">\(\blacksquare\)</span></p>
<ol start="2" style="list-style-type: lower-alpha">
<li>Turn <code>context</code> into a <code>factor</code>, within the
data frame. (We are going to be doing contrasts). Display how the
data frame now looks.</li>
</ol>
<p>Solution</p>
<p>Use <code>mutate</code> and assign everything back to what it was
before:</p>
<div class="sourceCode" id="cb373"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb373-1" title="1">smith &lt;-<span class="st"> </span>smith <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">mutate</span>(<span class="dt">context =</span> <span class="kw">factor</span>(context))</a>
<a class="sourceLine" id="cb373-2" title="2">smith</a></code></pre></div>
<pre><code>## # A tibble: 50 x 3
##       id context words
##    &lt;dbl&gt; &lt;fct&gt;   &lt;dbl&gt;
##  1     1 same       25
##  2     2 same       26
##  3     3 same       17
##  4     4 same       15
##  5     5 same       14
##  6     6 same       17
##  7     7 same       14
##  8     8 same       20
##  9     9 same       11
## 10    10 same       21
## # … with 40 more rows</code></pre>
<p>Note that <code>context</code> is now labelled as the factor that we made.</p>
<p><span class="math inline">\(\blacksquare\)</span></p>
<ol start="3" style="list-style-type: lower-alpha">
<li>What are the names of the five contexts in the data set
(just display them),
and what order are they in?</li>
</ol>
<p>Solution</p>
<p>You have lots of choices now, since <code>context</code> is a factor
(and can also be treated as text).
The most obvious factor-based way is this:</p>
<div class="sourceCode" id="cb375"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb375-1" title="1"><span class="kw">levels</span>(smith<span class="op">$</span>context)</a></code></pre></div>
<pre><code>## [1] &quot;different&quot;  &quot;imaginary&quot;  &quot;photograph&quot; &quot;placebo&quot;    &quot;same&quot;</code></pre>
<p>or use <code>summary</code>:</p>
<div class="sourceCode" id="cb377"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb377-1" title="1">smith <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">select</span>(context) <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">summary</span>()</a></code></pre></div>
<pre><code>##        context  
##  different :10  
##  imaginary :10  
##  photograph:10  
##  placebo   :10  
##  same      :10</code></pre>
<p>Or treat <code>context</code> as text, such as this way:</p>
<div class="sourceCode" id="cb379"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb379-1" title="1">smith <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">count</span>(context)</a></code></pre></div>
<pre><code>## # A tibble: 5 x 2
##   context        n
##   &lt;fct&gt;      &lt;int&gt;
## 1 different     10
## 2 imaginary     10
## 3 photograph    10
## 4 placebo       10
## 5 same          10</code></pre>
<p>These all display the contexts in alphabetical order.</p>
<p>Or display the distinct values:</p>
<div class="sourceCode" id="cb381"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb381-1" title="1">smith <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">distinct</span>(context)</a></code></pre></div>
<pre><code>## # A tibble: 5 x 1
##   context   
##   &lt;fct&gt;     
## 1 same      
## 2 different 
## 3 imaginary 
## 4 photograph
## 5 placebo</code></pre>
<p>or, without using the <code>tidyverse</code>,</p>
<div class="sourceCode" id="cb383"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb383-1" title="1"><span class="kw">unique</span>(smith<span class="op">$</span>context)</a></code></pre></div>
<pre><code>## [1] same       different  imaginary  photograph placebo   
## Levels: different imaginary photograph placebo same</code></pre>
<p>These two <em>don’t</em> display things in alphabetical order, because
they display things as they appear in the file. This is not the order
we want, though the second way <em>does</em> display the <code>Levels</code>
in the right order.</p>
<p><span class="math inline">\(\blacksquare\)</span></p>
<ol start="4" style="list-style-type: lower-alpha">
<li>Write each of the four research hypotheses (in the
null-hypothesis versions) as R vectors that can be used to make
contrasts. (This will mean getting the contexts in the right
order. If you get stuck, do the last two first, since they’re
easiest. The first one is actually the hardest.)</li>
</ol>
<p>Solution</p>
<p>All right, let’s go from the bottom:</p>
<ul>
<li>Different and placebo have same means. These are 1st and 4th.</li>
</ul>
<div class="sourceCode" id="cb385"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb385-1" title="1">c4 &lt;-<span class="st"> </span><span class="kw">c</span>(<span class="dv">1</span>, <span class="dv">0</span>, <span class="dv">0</span>, <span class="dv">-1</span>, <span class="dv">0</span>)</a></code></pre></div>
<ul>
<li>Imaginary and photograph have same means. 2nd and 3rd:</li>
</ul>
<div class="sourceCode" id="cb386"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb386-1" title="1">c3 &lt;-<span class="st"> </span><span class="kw">c</span>(<span class="dv">0</span>, <span class="dv">1</span>, <span class="dv">-1</span>, <span class="dv">0</span>, <span class="dv">0</span>)</a></code></pre></div>
<ul>
<li>Imaginary and photograph together same as <code>same</code>. This
time we have two means being compared with one, so we need to give
the two means half weight. 2nd and 3rd against 5th:</li>
</ul>
<div class="sourceCode" id="cb387"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb387-1" title="1">c2 &lt;-<span class="st"> </span><span class="kw">c</span>(<span class="dv">0</span>, <span class="dv">1</span> <span class="op">/</span><span class="st"> </span><span class="dv">2</span>, <span class="dv">1</span> <span class="op">/</span><span class="st"> </span><span class="dv">2</span>, <span class="dv">0</span>, <span class="dv">-1</span>)</a></code></pre></div>
<ul>
<li>(Same and imaginary and photograph) vs. (different or placebo):
2nd, 3rd and 5th with weight <span class="math inline">\(1/3\)</span> (three of them) against 1st and
4th with weight <span class="math inline">\(1/2\)</span> (2 of them):</li>
</ul>
<div class="sourceCode" id="cb388"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb388-1" title="1">c1 &lt;-<span class="st"> </span><span class="kw">c</span>(<span class="op">-</span><span class="dv">1</span> <span class="op">/</span><span class="st"> </span><span class="dv">2</span>, <span class="dv">1</span> <span class="op">/</span><span class="st"> </span><span class="dv">3</span>, <span class="dv">1</span> <span class="op">/</span><span class="st"> </span><span class="dv">3</span>, <span class="dv">-1</span> <span class="op">/</span><span class="st"> </span><span class="dv">2</span>, <span class="dv">1</span> <span class="op">/</span><span class="st"> </span><span class="dv">3</span>)</a></code></pre></div>
<p>Variations: you can switch the sign on everything within a
contrast (since it doesn’t matter which is plus and which is
minus). You can also multiply through by anything to get rid of
the fractions, for example these:</p>
<div class="sourceCode" id="cb389"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb389-1" title="1">c2 &lt;-<span class="st"> </span><span class="kw">c</span>(<span class="dv">0</span>, <span class="dv">1</span>, <span class="dv">1</span>, <span class="dv">0</span>, <span class="dv">-2</span>)</a>
<a class="sourceLine" id="cb389-2" title="2">c1 &lt;-<span class="st"> </span><span class="kw">c</span>(<span class="op">-</span><span class="dv">3</span>, <span class="dv">2</span>, <span class="dv">2</span>, <span class="dv">-3</span>, <span class="dv">2</span>)</a></code></pre></div>
<p>All that matters is that the coefficients add up to zero, and that they are the right size and sign relative to each other.</p>
<p><span class="math inline">\(\blacksquare\)</span></p>
<ol start="5" style="list-style-type: lower-alpha">
<li>Pick two of your contrasts (doesn’t matter which two) and
demonstrate that they are orthogonal.</li>
</ol>
<p>Solution</p>
<p>Multiply your chosen contrasts together elementwise, and show
that the results add to zero, eg. by showing the whole thing:</p>
<div class="sourceCode" id="cb390"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb390-1" title="1">c1 <span class="op">*</span><span class="st"> </span>c2</a></code></pre></div>
<pre><code>## [1]  0.0000000  0.1666667  0.1666667  0.0000000 -0.3333333</code></pre>
<p>which adds to zero because it is <span class="math inline">\(2/6\)</span> minus <span class="math inline">\(1/3\)</span>,
or by explicitly summing the elementwise product:</p>
<div class="sourceCode" id="cb392"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb392-1" title="1"><span class="kw">sum</span>(c1 <span class="op">*</span><span class="st"> </span>c3)</a></code></pre></div>
<pre><code>## [1] 0</code></pre>
<p>Any pair is good.</p>
<p><span class="math inline">\(\blacksquare\)</span></p>
<ol start="6" style="list-style-type: lower-alpha">
<li>Collect your contrasts together into a matrix, and
tell <code>lm</code> that these are the contrasts for <code>context</code>.</li>
</ol>
<p>Solution</p>
<p>This:</p>
<div class="sourceCode" id="cb394"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb394-1" title="1">m &lt;-<span class="st"> </span><span class="kw">cbind</span>(c1, c2, c3, c4)</a>
<a class="sourceLine" id="cb394-2" title="2"><span class="kw">contrasts</span>(smith<span class="op">$</span>context) &lt;-<span class="st"> </span>m</a></code></pre></div>
<p>Slipping off into another aside, you might have been wondering whether
there was a way to test
<em>all</em> the contrasts for orthogonality at once. There is, and it
depends on the rules for matrix multiplication. We want to test all
the <em>columns</em> of <code>m</code> for orthogonality, but matrix
multiplication works by combining a <em>row</em> with a column. No
matter, <em>transposing</em> a matrix interchanges rows and columns, so
that in math, we want to look at the matrix <span class="math inline">\(M^T M\)</span>. In R,
<code>%*%</code> means “matrix multiply.”<a href="#fn48" class="footnote-ref" id="fnref48"><sup>48</sup></a> Thus,</p>
<div class="sourceCode" id="cb395"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb395-1" title="1"><span class="kw">t</span>(m) <span class="op">%*%</span><span class="st"> </span>m</a></code></pre></div>
<pre><code>##           c1  c2 c3 c4
## c1 0.8333333 0.0  0  0
## c2 0.0000000 1.5  0  0
## c3 0.0000000 0.0  2  0
## c4 0.0000000 0.0  0  2</code></pre>
<p>This matrix-multiplies the transpose of <code>m</code> by <code>m</code>
itself. There are numbers down the top-left to bottom-right diagonal,
but don’t worry about these, since a contrast doesn’t have to be
orthogonal with itself. The thing to note is that
<em>all the other elements</em> of this matrix are
<em>zero</em>: that means that each of
the four contrasts is orthogonal to each of the other three.</p>
<p><span class="math inline">\(\blacksquare\)</span></p>
<ol start="7" style="list-style-type: lower-alpha">
<li>Fit a model with <code>lm</code>, and display the results.</li>
</ol>
<p>Solution</p>
<p>We’re past the hard part:</p>
<div class="sourceCode" id="cb397"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb397-1" title="1">smith<span class="fl">.1</span> &lt;-<span class="st"> </span><span class="kw">lm</span>(words <span class="op">~</span><span class="st"> </span>context, <span class="dt">data =</span> smith)</a>
<a class="sourceLine" id="cb397-2" title="2"><span class="kw">summary</span>(smith<span class="fl">.1</span>)</a></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = words ~ context, data = smith)
## 
## Residuals:
##    Min     1Q Median     3Q    Max 
##   -9.0   -4.0   -1.5    4.6   11.6 
## 
## Coefficients:
##             Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)  14.8000     0.8129  18.207  &lt; 2e-16 ***
## contextc1     8.6000     1.9912   4.319 8.52e-05 ***
## contextc2    -0.3333     1.4841  -0.225    0.823    
## contextc3    -0.1000     1.2853  -0.078    0.938    
## contextc4     0.5000     1.2853   0.389    0.699    
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 5.748 on 45 degrees of freedom
## Multiple R-squared:  0.2954, Adjusted R-squared:  0.2327 
## F-statistic: 4.715 on 4 and 45 DF,  p-value: 0.002902</code></pre>
<p><span class="math inline">\(\blacksquare\)</span></p>
<ol start="8" style="list-style-type: lower-alpha">
<li>For each of the original research hypotheses, what do you
infer about them?</li>
</ol>
<p>Solution</p>
<p>Even though I generated the contrasts backwards, I maintained
the numbering so that they refer to the original numbered
hypotheses. You might have named them something more mnemonic;
that works too, and is quite possibly better.
Anyway:</p>
<ul>
<li><p>Matching context better than non-matching context:
strongly significant (P-value 0.000085). (Strictly, this is a
two-sided test, but the way I constructed the contrast, this
should be significantly <em>positive</em> if the research
hypothesis is true, and it is.)</p></li>
<li><p>Same context <em>not</em> different from
imaginary/photographed context (P-value 0.823)</p></li>
<li><p>Imaginary context <em>not</em> different from photographed context (P-value 0.938).</p></li>
<li><p>Different context <em>not</em> different from placebo
context (P-value 0.699).</p></li>
</ul>
<p>I wanted you to match up the research hypotheses with the
P-values, as above, and state a conclusion about each one. If
you do that, I am happy.</p>
<p>Taking this back to the original research, I think the
first hypothesis was the most immediately important of the four:
we were able to show that having (or faking up) the original
room helped with recall. After that, it didn’t matter how it was
done: being in the original room was not different from
imagining the original room (by thinking about it or seeing a
photo of it). Failing to recall the original room was equally
bad, whether the subjects were in a different room and not asked
to think about the original orange room, or whether they were
literally asked to think about another room entirely.</p>
<p>Contrasts enabled us to tackle this problem and gain a very clear
conclusion: recalling the original orange room is helpful, but
it doesn’t matter how you do it.</p>
<p>How big of a difference does thinking about the orange room
make? You can use the 2 SE thing to get a 95% confidence interval:
the difference in the (mean of the) recall-orange-room means and
the (mean of the) don’t-recall means is between about 4.6 and
12.6 words (out of 80). I leave it for you to decide whether
that is practically important as well as being statistically significant.</p>
<p><span class="math inline">\(\blacksquare\)</span></p>
</div>
<div id="trying-on-shirts-1" class="section level2">
<h2><span class="header-section-number">30.12</span> Trying on shirts</h2>
<p>Does it make a difference if you see somebody else trying on
a shirt before you do, and if so, does it matter what kind of person
it is?</p>
<p>An experiment was carried out in a university bookstore, with
students who wanted to try on a shirt serving as (unsuspecting)
experimental subjects. When a student wanted to try on a shirt, the
sales associate told them that there was only one shirt left, and it
was being tried on by an “other customer”. This “other customer”
was actually a “confederate” of the experimenter (that means, they
were pretending to be a real customer but were actually part of the
experiment). The “other customer” was always female: either an
attractive well-dressed model, or an average-looking student wearing
jeans. The “other customer” would come out of the
dressing room and hand the shirt to the sales associate, who would
give it to the student who wanted to try it on. When the student had
tried on the shirt, they were asked to rate it on a 7-point scale (on
five different dimensions, and those five scores were then
averaged). Does a student’s evaluation depend on whether the student
was male or female, and whether the “other customer” was a model or
a student? There was also a control group, where the student was
handed the shirt directly by the sales associate, without the
“other customer” being involved at all.</p>
<p>There were thus five treatments:
male students who saw a model, male students who saw a student, female
students who saw a model, female students who saw a student, and the
control group. There were 25 students in each treatment group.</p>
<p>The data from this experiment can be found at
<a href="http://ritsokiguess.site/datafiles/shirts.csv">link</a>.</p>
<ol style="list-style-type: lower-alpha">
<li>Read in and display the data. How many observations do you
have, and is that what you should have?</li>
</ol>
<p>Solution</p>
<p><code>read_csv</code>:</p>
<div class="sourceCode" id="cb399"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb399-1" title="1">my_url &lt;-<span class="st"> &quot;http://ritsokiguess.site/datafiles/shirts.csv&quot;</span></a>
<a class="sourceLine" id="cb399-2" title="2">shirts &lt;-<span class="st"> </span><span class="kw">read_csv</span>(my_url)</a></code></pre></div>
<pre><code>## 
## ── Column specification ──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
## cols(
##   treatment = col_character(),
##   score = col_double()
## )</code></pre>
<div class="sourceCode" id="cb401"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb401-1" title="1">shirts</a></code></pre></div>
<pre><code>## # A tibble: 125 x 2
##    treatment         score
##    &lt;chr&gt;             &lt;dbl&gt;
##  1 male_seeing_model   6.8
##  2 male_seeing_model   4.7
##  3 male_seeing_model   5.1
##  4 male_seeing_model   4.7
##  5 male_seeing_model   5.5
##  6 male_seeing_model   6  
##  7 male_seeing_model   4.4
##  8 male_seeing_model   6  
##  9 male_seeing_model   5.3
## 10 male_seeing_model   6.3
## # … with 115 more rows</code></pre>
<p>There were 5 treatment groups with 25 students in each, so there
should be, and are, <span class="math inline">\(5 \times 25=125\)</span> observations.</p>
<p><span class="math inline">\(\blacksquare\)</span></p>
<ol start="2" style="list-style-type: lower-alpha">
<li>Turn <code>treatment</code> into a <code>factor</code> in your data
frame. (You can use the same name as the text <code>treatment</code>
that you read in from the file.)</li>
</ol>
<p>Solution</p>
<p>Thus:</p>
<div class="sourceCode" id="cb403"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb403-1" title="1">shirts &lt;-<span class="st"> </span>shirts <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">mutate</span>(<span class="dt">treatment =</span> <span class="kw">factor</span>(treatment))</a></code></pre></div>
<p>and for checking:</p>
<div class="sourceCode" id="cb404"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb404-1" title="1">shirts</a></code></pre></div>
<pre><code>## # A tibble: 125 x 2
##    treatment         score
##    &lt;fct&gt;             &lt;dbl&gt;
##  1 male_seeing_model   6.8
##  2 male_seeing_model   4.7
##  3 male_seeing_model   5.1
##  4 male_seeing_model   4.7
##  5 male_seeing_model   5.5
##  6 male_seeing_model   6  
##  7 male_seeing_model   4.4
##  8 male_seeing_model   6  
##  9 male_seeing_model   5.3
## 10 male_seeing_model   6.3
## # … with 115 more rows</code></pre>
<p>see that <code>treatment</code> is now definitely a factor rather than a
categorical variable represented as a piece of text.</p>
<p><span class="math inline">\(\blacksquare\)</span></p>
<ol start="3" style="list-style-type: lower-alpha">
<li>List the treatments in the order that they are in within
your <code>factor</code>. (There are lots of ways to do this; any one of
them except for <code>distinct</code> is good.)</li>
</ol>
<p>Solution</p>
<p>This is the most direct:</p>
<div class="sourceCode" id="cb406"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb406-1" title="1"><span class="kw">levels</span>(shirts<span class="op">$</span>treatment)</a></code></pre></div>
<pre><code>## [1] &quot;control&quot;               &quot;female_seeing_model&quot;   &quot;female_seeing_student&quot; &quot;male_seeing_model&quot;     &quot;male_seeing_student&quot;</code></pre>
<p>or you can do one of the <code>tidyverse</code>-style ways, such as</p>
<div class="sourceCode" id="cb408"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb408-1" title="1">shirts <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">count</span>(treatment)</a></code></pre></div>
<pre><code>## # A tibble: 5 x 2
##   treatment                 n
##   &lt;fct&gt;                 &lt;int&gt;
## 1 control                  25
## 2 female_seeing_model      25
## 3 female_seeing_student    25
## 4 male_seeing_model        25
## 5 male_seeing_student      25</code></pre>
<p>or</p>
<div class="sourceCode" id="cb410"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb410-1" title="1">shirts <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">distinct</span>(treatment)</a></code></pre></div>
<pre><code>## # A tibble: 5 x 1
##   treatment            
##   &lt;fct&gt;                
## 1 male_seeing_model    
## 2 male_seeing_student  
## 3 female_seeing_model  
## 4 female_seeing_student
## 5 control</code></pre>
<p>except that <code>distinct</code> shows you the values in the order that
they appear in the data file, which is <em>not</em> the order that they
appear in the factor. So that’s why I asked you not to do it that way.</p>
<p>Alphabetical order, is the moral of the story.</p>
<p>Extra: you can make them appear in the order they appear in the data,
if you want to (and if you know what you are doing):</p>
<div class="sourceCode" id="cb412"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb412-1" title="1">shirts <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">mutate</span>(<span class="dt">trt2 =</span> <span class="kw">fct_inorder</span>(treatment)) -&gt;<span class="st"> </span>d</a>
<a class="sourceLine" id="cb412-2" title="2"><span class="kw">levels</span>(d<span class="op">$</span>trt2)</a></code></pre></div>
<pre><code>## [1] &quot;male_seeing_model&quot;     &quot;male_seeing_student&quot;   &quot;female_seeing_model&quot;   &quot;female_seeing_student&quot; &quot;control&quot;</code></pre>
<p><code>fct_inorder</code> <em>creates</em> a factor whose levels are in the
order that they appeared in the data. If this is what you want, you
can go ahead and do this, and use this order when you create your
contrasts. It will work, and it will be good even though your
contrasts will look different from mine.</p>
<p><span class="math inline">\(\blacksquare\)</span></p>
<ol start="4" style="list-style-type: lower-alpha">
<li><a name="part:mean-eval">*</a>
Obtain a table of mean evaluation scores for each treatment group.</li>
</ol>
<p>Solution</p>
<p>We will use this later when assessing the significance of the
contrasts. It’s the usual group-by and summarize:</p>
<div class="sourceCode" id="cb414"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb414-1" title="1">shirts <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb414-2" title="2"><span class="st">  </span><span class="kw">group_by</span>(treatment) <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb414-3" title="3"><span class="st">  </span><span class="kw">summarize</span>(<span class="dt">m =</span> <span class="kw">mean</span>(score))</a></code></pre></div>
<pre><code>## # A tibble: 5 x 2
##   treatment                 m
##   &lt;fct&gt;                 &lt;dbl&gt;
## 1 control                4.03
## 2 female_seeing_model    4.07
## 3 female_seeing_student  3.36
## 4 male_seeing_model      5.42
## 5 male_seeing_student    3.25</code></pre>
<p>Extra: how does this come out if you have your factor levels in a
non-alphabetical order?</p>
<div class="sourceCode" id="cb416"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb416-1" title="1">d <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">group_by</span>(trt2) <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">summarize</span>(<span class="dt">m =</span> <span class="kw">mean</span>(score))</a></code></pre></div>
<pre><code>## # A tibble: 5 x 2
##   trt2                      m
##   &lt;fct&gt;                 &lt;dbl&gt;
## 1 male_seeing_model      5.42
## 2 male_seeing_student    3.25
## 3 female_seeing_model    4.07
## 4 female_seeing_student  3.36
## 5 control                4.03</code></pre>
<p>Ah, it respects the order of the levels of the factor: that is to say,
the treatment groups appear here in the order that they were in the
data, because the factor <code>trt2</code> was created to make that
happen.</p>
<p><code>forcats</code> has other tools to re-order the levels of a factor,
lump factor levels together to make a category “other”, and so
on. These also work if you start with a categorical variable as text:
it <em>creates</em> a factor with those properties.</p>
<p><span class="math inline">\(\blacksquare\)</span></p>
<ol start="5" style="list-style-type: lower-alpha">
<li>The experimenters wanted to compare four specific things in
their analysis:</li>
</ol>
<ul>
<li><p>evaluation scores between male students who saw a (female) model and
male students who saw a (female) student</p></li>
<li><p>evaluation scores between female students who saw a (female)
model and female students who saw a (female) student</p></li>
<li><p>evaluation scores for male and for female students (overall)</p></li>
<li><p>evaluation scores for the (average of the) four genuine
treatments and for the control group</p></li>
</ul>
<p>Create contrasts, with suitable names, using vectors with
appropriate values.</p>
<p>Solution</p>
<p>These, in that order, are comparisons of treatments 4 and 5:</p>
<div class="sourceCode" id="cb418"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb418-1" title="1">c_mms &lt;-<span class="st"> </span><span class="kw">c</span>(<span class="dv">0</span>, <span class="dv">0</span>, <span class="dv">0</span>, <span class="dv">1</span>, <span class="dv">-1</span>)</a></code></pre></div>
<p>treatments 2 and 3:</p>
<div class="sourceCode" id="cb419"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb419-1" title="1">c_fms &lt;-<span class="st"> </span><span class="kw">c</span>(<span class="dv">0</span>, <span class="dv">1</span>, <span class="dv">-1</span>, <span class="dv">0</span>, <span class="dv">0</span>)</a></code></pre></div>
<p>(in these two the 1 and <span class="math inline">\(-1\)</span> can also be the other way around)</p>
<p>the average of 2 and 3 vs. the average of 4 and 5:</p>
<div class="sourceCode" id="cb420"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb420-1" title="1">c_mf &lt;-<span class="st"> </span><span class="kw">c</span>(<span class="dv">0</span>, <span class="fl">0.5</span>, <span class="fl">0.5</span>, <span class="fl">-0.5</span>, <span class="fl">-0.5</span>)</a></code></pre></div>
<p>or you can use 1 and <span class="math inline">\(-1\)</span> instead of the 0.5s, or you can switch the
signs around. I like the 0.5 values to remind me it’s an average of
two means.</p>
<p>Finally</p>
<div class="sourceCode" id="cb421"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb421-1" title="1">c_tc &lt;-<span class="st"> </span><span class="kw">c</span>(<span class="dv">1</span>, <span class="fl">-0.25</span>, <span class="fl">-0.25</span>, <span class="fl">-0.25</span>, <span class="fl">-0.25</span>)</a></code></pre></div>
<p>or multiply through by 4 to get rid of the fractions, or have the
negative sign on the first one and positive signs on the others.</p>
<p>I tried to give the contrasts mnemonic but short names, so that I
would remember which was which.</p>
<p><span class="math inline">\(\blacksquare\)</span></p>
<ol start="6" style="list-style-type: lower-alpha">
<li>Pick two of your contrasts (doesn’t matter which two) and
demonstrate that they are orthogonal.</li>
</ol>
<p>Solution</p>
<p>Multiply them together (elementwise, which is what <code>*</code>
does) and add them up, showing that you get zero, for example:</p>
<div class="sourceCode" id="cb422"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb422-1" title="1"><span class="kw">sum</span>(c_mf <span class="op">*</span><span class="st"> </span>c_tc)</a></code></pre></div>
<pre><code>## [1] 0</code></pre>
<p>Check (mops brow).</p>
<p><span class="math inline">\(\blacksquare\)</span></p>
<ol start="7" style="list-style-type: lower-alpha">
<li>Collect all your contrasts together into a matrix and
declare that they are contrasts for <code>treatment</code> within your
data frame (whatever you called it).</li>
</ol>
<p>Solution</p>
<p>I called my data frame <code>shirts</code>, so I need to do this:</p>
<div class="sourceCode" id="cb424"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb424-1" title="1">m &lt;-<span class="st"> </span><span class="kw">cbind</span>(c_mms, c_fms, c_mf, c_tc)</a>
<a class="sourceLine" id="cb424-2" title="2"><span class="kw">contrasts</span>(shirts<span class="op">$</span>treatment) &lt;-<span class="st"> </span>m</a></code></pre></div>
<p>There’s no output here; we’ll see in a moment whether it worked.</p>
<p>Extra: once you’ve created the matrix <code>m</code>, it gives you a
second way to test the contrasts for orthogonality, all at once:</p>
<div class="sourceCode" id="cb425"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb425-1" title="1"><span class="kw">t</span>(m) <span class="op">%*%</span><span class="st"> </span>m</a></code></pre></div>
<pre><code>##       c_mms c_fms c_mf c_tc
## c_mms     2     0    0 0.00
## c_fms     0     2    0 0.00
## c_mf      0     0    1 0.00
## c_tc      0     0    0 1.25</code></pre>
<p>This matrix-multiplies the transpose of <code>m</code> by <code>m</code>, so
it’s testing each column of <code>m</code> to see whether it’s orthogonal
to each other column. The columns don’t have to be orthogonal to
themselves, hence the non-zeros down the diagonal, but all the
off-diagonal entries are zero. Hence each contrast is orthogonal to
each other contrast.</p>
<p>Or even:</p>
<div class="sourceCode" id="cb427"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb427-1" title="1">z &lt;-<span class="st"> </span><span class="kw">t</span>(m) <span class="op">%*%</span><span class="st"> </span>m</a>
<a class="sourceLine" id="cb427-2" title="2"><span class="kw">all</span>(z[<span class="kw">row</span>(z) <span class="op">!=</span><span class="st"> </span><span class="kw">col</span>(z)] <span class="op">==</span><span class="st"> </span><span class="dv">0</span>)</a></code></pre></div>
<pre><code>## [1] TRUE</code></pre>
<p>That says (a little breathlessly) that it is true that all the
elements of <span class="math inline">\(M^TM\)</span> that are off the diagonal are zero.<a href="#fn49" class="footnote-ref" id="fnref49"><sup>49</sup></a></p>
<p><span class="math inline">\(\blacksquare\)</span></p>
<ol start="8" style="list-style-type: lower-alpha">
<li>Predict evaluation score from
treatment <em>as a regression</em>, and display the results.</li>
</ol>
<p>Solution</p>
<p>Once you have everything set up, it’s just a matter of going
through the process:</p>
<div class="sourceCode" id="cb429"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb429-1" title="1">score<span class="fl">.1</span> &lt;-<span class="st"> </span><span class="kw">lm</span>(score <span class="op">~</span><span class="st"> </span>treatment, <span class="dt">data =</span> shirts)</a>
<a class="sourceLine" id="cb429-2" title="2"><span class="kw">summary</span>(score<span class="fl">.1</span>)</a></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = score ~ treatment, data = shirts)
## 
## Residuals:
##    Min     1Q Median     3Q    Max 
## -3.860 -0.760  0.032  0.840  3.640 
## 
## Coefficients:
##                Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)      4.0256     0.1231  32.705  &lt; 2e-16 ***
## treatmentc_mms   1.0820     0.1946   5.560 1.66e-07 ***
## treatmentc_fms   0.3540     0.1946   1.819   0.0714 .  
## treatmentc_mf   -0.6200     0.2752  -2.253   0.0261 *  
## treatmentc_tc    0.0064     0.2462   0.026   0.9793    
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 1.376 on 120 degrees of freedom
## Multiple R-squared:  0.2467, Adjusted R-squared:  0.2216 
## F-statistic: 9.823 on 4 and 120 DF,  p-value: 6.576e-07</code></pre>
<p>Note how the contrasts have appeared as “slopes” in our
regression. (If this didn’t happen for you, go back and check what you
did. Probably something gave you an error before, in that case.)</p>
<p>Your slopes can differ in terms of sign and possibly value from mine,
but the <span class="math inline">\(t\)</span>-statistics and P-values should be the same as mine.</p>
<p><span class="math inline">\(\blacksquare\)</span></p>
<ol style="list-style-type: lower-roman">
<li>For each of your contrasts, assess whether or not it is
significant, and explain briefly what that means in the context of the
data. If a contrast is significant, use your answer to
part (<a href="#part:mean-eval">here</a>) to help in your interpretation.</li>
</ol>
<p>Solution</p>
<p>I’ll take my four contrasts as they appear in the output from <code>lm</code>:</p>
<ul>
<li><p>Comparing the male students who saw the model with those
who saw the student: this is strongly significant, and the
table of means shows that the males who saw the model rated
the shirt significantly <em>higher</em> than those who saw the
“average-looking” female student.</p></li>
<li><p>Comparing the female students who saw the model with
those who saw the student: this difference is not quite
significant, so we conclude that it didn’t matter who the
female students saw coming out of the dressing room.</p></li>
<li><p>There is a significant difference between the average
evaluation score that males gave to the shirt and that
females did. The table of means reveals that the male
average was higher, mostly because males <em>really</em> liked
the shirt when they thought the model had been wearing it!</p></li>
<li><p>There is no significant difference overall between
treatment and control groups in terms of average
score. (This is mostly because the treatment groups differ
among themselves, with the scores for students who saw the
model being higher and those for students who saw the female
student being lower than for the control group.)</p></li>
</ul>
<p>It is enough, on the non-significant ones, to say what it is
that the contrast is testing, and then to note that it is not
significant. On the significant ones, I want you to say what
is higher than what.
You can also get these conclusions from the <code>lm</code>
output, but it requires a bit more care:</p>
<ul>
<li><p>I set up <code>c_mms</code> with the score for the students
who had seen the model as plus and those who saw the student
as minus. My slope here is positive, so the score for
male students who saw the model is higher.</p></li>
<li><p>My slope for <code>c_fms</code> is also positive, and I set
this one up the same way with model as positive and student
as negative, so the female students rated the shirt higher
(but not significantly higher) when they saw the model.</p></li>
<li><p>My <code>c_mf</code> slope is significantly negative. I set
up this contrast with females as plus and males as minus, so
this means males gave a significantly <em>higher</em> score on
average (for reasons discussed above).</p></li>
<li><p>The last slope is very close to 0, consistent with there
being no difference (on average) between treatment and control.</p></li>
</ul>
<p>Perhaps the story to get from this analysis is that male
students are <em>such</em> suckers!</p>
<p><span class="math inline">\(\blacksquare\)</span></p>

</div>
</div>
<div class="footnotes">
<hr />
<ol start="36">
<li id="fn36"><p>This is a fancy word for <em>stuff</em>.<a href="analysis-of-variance-revisited.html#fnref36" class="footnote-back">↩</a></p></li>
<li id="fn37"><p>It’s important to be clear about the distinction between a categorical variable, that lives in a data frame column, and its levels, the values that appear in the column. This is especially important if you’re trying to decide whether a data frame is tidy, since typically an untidy data frame will have factor levels as column names rather than the factor itself, and you need to be able to tell the difference.<a href="analysis-of-variance-revisited.html#fnref37" class="footnote-back">↩</a></p></li>
<li id="fn38"><p>SAS, for example, has a way of making non-orthogonal contrasts orthogonal in a way that the user doesn’t have to worry about, but in R, you are closer to the ground, so to speak, and you have to make it happen yourself.<a href="analysis-of-variance-revisited.html#fnref38" class="footnote-back">↩</a></p></li>
<li id="fn39"><p>Howell is the author of a famous text on Statistics in Psychology.<a href="analysis-of-variance-revisited.html#fnref39" class="footnote-back">↩</a></p></li>
<li id="fn40"><p>Which we are going to invert, as a matrix. But I get ahead of myself.<a href="analysis-of-variance-revisited.html#fnref40" class="footnote-back">↩</a></p></li>
<li id="fn41"><p>We are working with R matrices here rather than data frames, so we access elements, rows and columns using the square bracket notation: inside the square brackets, we put first the numbers of the rows we want, then a comma, then the numbers of the columns. There are two special pieces of notation, both of which I use here: leaving the row or column slot blank means all the rows or all the columns, and using a negative row or column number means all the rows or columns except the one(s) named. Thus my notation here is all the rows, and all the columns except for the first one. You can access data frames this way too, but the Tidyverse makes it much easier.<a href="analysis-of-variance-revisited.html#fnref41" class="footnote-back">↩</a></p></li>
<li id="fn42"><p>I think Howell is famous enough to be
trusted.<a href="analysis-of-variance-revisited.html#fnref42" class="footnote-back">↩</a></p></li>
<li id="fn43"><p>As I failed to do the first time.<a href="analysis-of-variance-revisited.html#fnref43" class="footnote-back">↩</a></p></li>
<li id="fn44"><p>On ancient maps, people didn’t know what was in certain parts of the world, because no-one had ever explored them, so they wrote on the map “here be dragons”.<a href="analysis-of-variance-revisited.html#fnref44" class="footnote-back">↩</a></p></li>
<li id="fn45"><p>In contrast. Get it? No? Well, never mind then.<a href="analysis-of-variance-revisited.html#fnref45" class="footnote-back">↩</a></p></li>
<li id="fn46"><p><code>anova</code> is one of R’s multi-purpose tools; what it does depends on what you feed it.<a href="analysis-of-variance-revisited.html#fnref46" class="footnote-back">↩</a></p></li>
<li id="fn47"><p>This is a fancy word for <em>stuff</em>.<a href="analysis-of-variance-revisited.html#fnref47" class="footnote-back">↩</a></p></li>
<li id="fn48"><p>In R, percents around something mean that it is a special version of that something. Hence the notation for matrix-multiply and the pipe symbol. A regular * when used for multiplying matrices in R will multiply them element by element.<a href="analysis-of-variance-revisited.html#fnref48" class="footnote-back">↩</a></p></li>
<li id="fn49"><p>The thing inside the square brackets says only to look at the elements of <span class="math inline">\(M^TM\)</span> whose row number and whose column number are different; it is perhaps easier to reason that elements of a matrix whose row number and column number are the <em>same</em> are <em>on</em> the diagonal, for example the element in row 2, column 2.<a href="analysis-of-variance-revisited.html#fnref49" class="footnote-back">↩</a></p></li>
</ol>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="survival-analysis.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="analysis-of-covariance.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/lunr.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": null,
"text": null
},
"history": {
"link": null,
"text": null
},
"view": {
"link": null,
"text": null
},
"download": ["pasias.pdf"],
"toc": {
"collapse": "subsection"
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
