<!DOCTYPE html>
<html >

<head>

  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <title>Problems and Solutions in Applied Statistics</title>
  <meta name="description" content="A set of problems and solutions, in R, on various parts of applied statistics">
  <meta name="generator" content="bookdown 0.7 and GitBook 2.6.7">

  <meta property="og:title" content="Problems and Solutions in Applied Statistics" />
  <meta property="og:type" content="book" />
  <meta property="og:url" content="<a href="http://ritsokiguess.site/pasias" class="uri">http://ritsokiguess.site/pasias</a>" />
  
  <meta property="og:description" content="A set of problems and solutions, in R, on various parts of applied statistics" />
  <meta name="github-repo" content="nxskok/pasias" />

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Problems and Solutions in Applied Statistics" />
  
  <meta name="twitter:description" content="A set of problems and solutions, in R, on various parts of applied statistics" />
  

<meta name="author" content="Ken Butler">


<meta name="date" content="2018-10-09">

  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="apple-mobile-web-app-capable" content="yes">
  <meta name="apple-mobile-web-app-status-bar-style" content="black">
  
  
<link rel="prev" href="reading-in-data-and-drawing-some-graphs.html">
<link rel="next" href="one-sample-inference.html">
<script src="libs/jquery-2.2.3/jquery.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />









<style type="text/css">
a.sourceLine { display: inline-block; line-height: 1.25; }
a.sourceLine { pointer-events: none; color: inherit; text-decoration: inherit; }
a.sourceLine:empty { height: 1.2em; position: absolute; }
.sourceCode { overflow: visible; }
code.sourceCode { white-space: pre; position: relative; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
code.sourceCode { white-space: pre-wrap; }
a.sourceLine { text-indent: -1em; padding-left: 1em; }
}
pre.numberSource a.sourceLine
  { position: relative; }
pre.numberSource a.sourceLine:empty
  { position: absolute; }
pre.numberSource a.sourceLine::before
  { content: attr(data-line-number);
    position: absolute; left: -5em; text-align: right; vertical-align: baseline;
    border: none; pointer-events: all;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {  }
@media screen {
a.sourceLine::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">Problems and Solutions in Applied Statistics</a></li>

<li class="divider"></li>
<li class="chapter" data-level="1" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i><b>1</b> Introduction</a></li>
<li class="chapter" data-level="2" data-path="getting-used-to-r-and-r-studio.html"><a href="getting-used-to-r-and-r-studio.html"><i class="fa fa-check"></i><b>2</b> Getting used to R and R Studio</a><ul>
<li class="chapter" data-level="2.1" data-path="getting-used-to-r-and-r-studio.html"><a href="getting-used-to-r-and-r-studio.html#attaching-packages-tidyverse-1.2.1"><i class="fa fa-check"></i><b>2.1</b> ── Attaching packages ─────────────────────────────────────────────────────────────────────────────────────── tidyverse 1.2.1 ──</a></li>
<li class="chapter" data-level="2.2" data-path="getting-used-to-r-and-r-studio.html"><a href="getting-used-to-r-and-r-studio.html#ggplot2-3.0.0-purrr-0.2.5"><i class="fa fa-check"></i><b>2.2</b> ✔ ggplot2 3.0.0 ✔ purrr 0.2.5</a></li>
<li class="chapter" data-level="2.3" data-path="getting-used-to-r-and-r-studio.html"><a href="getting-used-to-r-and-r-studio.html#tibble-1.4.2-dplyr-0.7.6"><i class="fa fa-check"></i><b>2.3</b> ✔ tibble 1.4.2 ✔ dplyr 0.7.6</a></li>
<li class="chapter" data-level="2.4" data-path="getting-used-to-r-and-r-studio.html"><a href="getting-used-to-r-and-r-studio.html#tidyr-0.8.1-stringr-1.3.1"><i class="fa fa-check"></i><b>2.4</b> ✔ tidyr 0.8.1 ✔ stringr 1.3.1</a></li>
<li class="chapter" data-level="2.5" data-path="getting-used-to-r-and-r-studio.html"><a href="getting-used-to-r-and-r-studio.html#readr-1.1.1-forcats-0.3.0"><i class="fa fa-check"></i><b>2.5</b> ✔ readr 1.1.1 ✔ forcats 0.3.0</a></li>
<li class="chapter" data-level="2.6" data-path="getting-used-to-r-and-r-studio.html"><a href="getting-used-to-r-and-r-studio.html#conflicts-tidyverse_conflicts"><i class="fa fa-check"></i><b>2.6</b> ── Conflicts ────────────────────────────────────────────────────────────────────────────────────────── tidyverse_conflicts() ──</a></li>
<li class="chapter" data-level="2.7" data-path="getting-used-to-r-and-r-studio.html"><a href="getting-used-to-r-and-r-studio.html#dplyrfilter-masks-statsfilter"><i class="fa fa-check"></i><b>2.7</b> ✖ dplyr::filter() masks stats::filter()</a></li>
<li class="chapter" data-level="2.8" data-path="getting-used-to-r-and-r-studio.html"><a href="getting-used-to-r-and-r-studio.html#dplyrlag-masks-statslag"><i class="fa fa-check"></i><b>2.8</b> ✖ dplyr::lag() masks stats::lag()</a></li>
<li class="chapter" data-level="2.9" data-path="getting-used-to-r-and-r-studio.html"><a href="getting-used-to-r-and-r-studio.html#getting-an-r-studio-cloud-account"><i class="fa fa-check"></i><b>2.9</b> Getting an R Studio Cloud account</a></li>
<li class="chapter" data-level="2.10" data-path="getting-used-to-r-and-r-studio.html"><a href="getting-used-to-r-and-r-studio.html#getting-started"><i class="fa fa-check"></i><b>2.10</b> Getting started</a></li>
<li class="chapter" data-level="2.11" data-path="getting-used-to-r-and-r-studio.html"><a href="getting-used-to-r-and-r-studio.html#a-tibble-32-x-11"><i class="fa fa-check"></i><b>2.11</b> # A tibble: 32 x 11</a></li>
<li class="chapter" data-level="2.12" data-path="getting-used-to-r-and-r-studio.html"><a href="getting-used-to-r-and-r-studio.html#mpg-cyl-disp-hp-drat-wt-qsec-vs-am-gear-carb"><i class="fa fa-check"></i><b>2.12</b> mpg cyl disp hp drat wt qsec vs am gear carb</a></li>
<li class="chapter" data-level="2.13" data-path="getting-used-to-r-and-r-studio.html"><a href="getting-used-to-r-and-r-studio.html#section"><i class="fa fa-check"></i><b>2.13</b> * <dbl> <dbl> <dbl> <dbl> <dbl> <dbl> <dbl> <dbl> <dbl> <dbl> <dbl></a></li>
<li class="chapter" data-level="2.14" data-path="getting-used-to-r-and-r-studio.html"><a href="getting-used-to-r-and-r-studio.html#section-1"><i class="fa fa-check"></i><b>2.14</b> 1 21 6 160 110 3.9 2.62 16.5 0 1 4 4</a></li>
<li class="chapter" data-level="2.15" data-path="getting-used-to-r-and-r-studio.html"><a href="getting-used-to-r-and-r-studio.html#section-2"><i class="fa fa-check"></i><b>2.15</b> 2 21 6 160 110 3.9 2.88 17.0 0 1 4 4</a></li>
<li class="chapter" data-level="2.16" data-path="getting-used-to-r-and-r-studio.html"><a href="getting-used-to-r-and-r-studio.html#section-3"><i class="fa fa-check"></i><b>2.16</b> 3 22.8 4 108 93 3.85 2.32 18.6 1 1 4 1</a></li>
<li class="chapter" data-level="2.17" data-path="getting-used-to-r-and-r-studio.html"><a href="getting-used-to-r-and-r-studio.html#section-4"><i class="fa fa-check"></i><b>2.17</b> 4 21.4 6 258 110 3.08 3.22 19.4 1 0 3 1</a></li>
<li class="chapter" data-level="2.18" data-path="getting-used-to-r-and-r-studio.html"><a href="getting-used-to-r-and-r-studio.html#section-5"><i class="fa fa-check"></i><b>2.18</b> 5 18.7 8 360 175 3.15 3.44 17.0 0 0 3 2</a></li>
<li class="chapter" data-level="2.19" data-path="getting-used-to-r-and-r-studio.html"><a href="getting-used-to-r-and-r-studio.html#section-6"><i class="fa fa-check"></i><b>2.19</b> 6 18.1 6 225 105 2.76 3.46 20.2 1 0 3 1</a></li>
<li class="chapter" data-level="2.20" data-path="getting-used-to-r-and-r-studio.html"><a href="getting-used-to-r-and-r-studio.html#section-7"><i class="fa fa-check"></i><b>2.20</b> 7 14.3 8 360 245 3.21 3.57 15.8 0 0 3 4</a></li>
<li class="chapter" data-level="2.21" data-path="getting-used-to-r-and-r-studio.html"><a href="getting-used-to-r-and-r-studio.html#section-8"><i class="fa fa-check"></i><b>2.21</b> 8 24.4 4 147. 62 3.69 3.19 20 1 0 4 2</a></li>
<li class="chapter" data-level="2.22" data-path="getting-used-to-r-and-r-studio.html"><a href="getting-used-to-r-and-r-studio.html#section-9"><i class="fa fa-check"></i><b>2.22</b> 9 22.8 4 141. 95 3.92 3.15 22.9 1 0 4 2</a></li>
<li class="chapter" data-level="2.23" data-path="getting-used-to-r-and-r-studio.html"><a href="getting-used-to-r-and-r-studio.html#section-10"><i class="fa fa-check"></i><b>2.23</b> 10 19.2 6 168. 123 3.92 3.44 18.3 1 0 4 4</a></li>
<li class="chapter" data-level="2.24" data-path="getting-used-to-r-and-r-studio.html"><a href="getting-used-to-r-and-r-studio.html#with-22-more-rows"><i class="fa fa-check"></i><b>2.24</b> # … with 22 more rows</a></li>
<li class="chapter" data-level="2.25" data-path="getting-used-to-r-and-r-studio.html"><a href="getting-used-to-r-and-r-studio.html#mpg-cyl-disp-hp"><i class="fa fa-check"></i><b>2.25</b> mpg cyl disp hp</a></li>
<li class="chapter" data-level="2.26" data-path="getting-used-to-r-and-r-studio.html"><a href="getting-used-to-r-and-r-studio.html#min.-10.40-min.-4.000-min.-71.1-min.-52.0"><i class="fa fa-check"></i><b>2.26</b> Min. :10.40 Min. :4.000 Min. : 71.1 Min. : 52.0</a></li>
<li class="chapter" data-level="2.27" data-path="getting-used-to-r-and-r-studio.html"><a href="getting-used-to-r-and-r-studio.html#st-qu.15.43-1st-qu.4.000-1st-qu.120.8-1st-qu.-96.5"><i class="fa fa-check"></i><b>2.27</b> 1st Qu.:15.43 1st Qu.:4.000 1st Qu.:120.8 1st Qu.: 96.5</a></li>
<li class="chapter" data-level="2.28" data-path="getting-used-to-r-and-r-studio.html"><a href="getting-used-to-r-and-r-studio.html#median-19.20-median-6.000-median-196.3-median-123.0"><i class="fa fa-check"></i><b>2.28</b> Median :19.20 Median :6.000 Median :196.3 Median :123.0</a></li>
<li class="chapter" data-level="2.29" data-path="getting-used-to-r-and-r-studio.html"><a href="getting-used-to-r-and-r-studio.html#mean-20.09-mean-6.188-mean-230.7-mean-146.7"><i class="fa fa-check"></i><b>2.29</b> Mean :20.09 Mean :6.188 Mean :230.7 Mean :146.7</a></li>
<li class="chapter" data-level="2.30" data-path="getting-used-to-r-and-r-studio.html"><a href="getting-used-to-r-and-r-studio.html#rd-qu.22.80-3rd-qu.8.000-3rd-qu.326.0-3rd-qu.180.0"><i class="fa fa-check"></i><b>2.30</b> 3rd Qu.:22.80 3rd Qu.:8.000 3rd Qu.:326.0 3rd Qu.:180.0</a></li>
<li class="chapter" data-level="2.31" data-path="getting-used-to-r-and-r-studio.html"><a href="getting-used-to-r-and-r-studio.html#max.-33.90-max.-8.000-max.-472.0-max.-335.0"><i class="fa fa-check"></i><b>2.31</b> Max. :33.90 Max. :8.000 Max. :472.0 Max. :335.0</a></li>
<li class="chapter" data-level="2.32" data-path="getting-used-to-r-and-r-studio.html"><a href="getting-used-to-r-and-r-studio.html#drat-wt-qsec-vs"><i class="fa fa-check"></i><b>2.32</b> drat wt qsec vs</a></li>
<li class="chapter" data-level="2.33" data-path="getting-used-to-r-and-r-studio.html"><a href="getting-used-to-r-and-r-studio.html#min.-2.760-min.-1.513-min.-14.50-min.-0.0000"><i class="fa fa-check"></i><b>2.33</b> Min. :2.760 Min. :1.513 Min. :14.50 Min. :0.0000</a></li>
<li class="chapter" data-level="2.34" data-path="getting-used-to-r-and-r-studio.html"><a href="getting-used-to-r-and-r-studio.html#st-qu.3.080-1st-qu.2.581-1st-qu.16.89-1st-qu.0.0000"><i class="fa fa-check"></i><b>2.34</b> 1st Qu.:3.080 1st Qu.:2.581 1st Qu.:16.89 1st Qu.:0.0000</a></li>
<li class="chapter" data-level="2.35" data-path="getting-used-to-r-and-r-studio.html"><a href="getting-used-to-r-and-r-studio.html#median-3.695-median-3.325-median-17.71-median-0.0000"><i class="fa fa-check"></i><b>2.35</b> Median :3.695 Median :3.325 Median :17.71 Median :0.0000</a></li>
<li class="chapter" data-level="2.36" data-path="getting-used-to-r-and-r-studio.html"><a href="getting-used-to-r-and-r-studio.html#mean-3.597-mean-3.217-mean-17.85-mean-0.4375"><i class="fa fa-check"></i><b>2.36</b> Mean :3.597 Mean :3.217 Mean :17.85 Mean :0.4375</a></li>
<li class="chapter" data-level="2.37" data-path="getting-used-to-r-and-r-studio.html"><a href="getting-used-to-r-and-r-studio.html#rd-qu.3.920-3rd-qu.3.610-3rd-qu.18.90-3rd-qu.1.0000"><i class="fa fa-check"></i><b>2.37</b> 3rd Qu.:3.920 3rd Qu.:3.610 3rd Qu.:18.90 3rd Qu.:1.0000</a></li>
<li class="chapter" data-level="2.38" data-path="getting-used-to-r-and-r-studio.html"><a href="getting-used-to-r-and-r-studio.html#max.-4.930-max.-5.424-max.-22.90-max.-1.0000"><i class="fa fa-check"></i><b>2.38</b> Max. :4.930 Max. :5.424 Max. :22.90 Max. :1.0000</a></li>
<li class="chapter" data-level="2.39" data-path="getting-used-to-r-and-r-studio.html"><a href="getting-used-to-r-and-r-studio.html#am-gear-carb"><i class="fa fa-check"></i><b>2.39</b> am gear carb</a></li>
<li class="chapter" data-level="2.40" data-path="getting-used-to-r-and-r-studio.html"><a href="getting-used-to-r-and-r-studio.html#min.-0.0000-min.-3.000-min.-1.000"><i class="fa fa-check"></i><b>2.40</b> Min. :0.0000 Min. :3.000 Min. :1.000</a></li>
<li class="chapter" data-level="2.41" data-path="getting-used-to-r-and-r-studio.html"><a href="getting-used-to-r-and-r-studio.html#st-qu.0.0000-1st-qu.3.000-1st-qu.2.000"><i class="fa fa-check"></i><b>2.41</b> 1st Qu.:0.0000 1st Qu.:3.000 1st Qu.:2.000</a></li>
<li class="chapter" data-level="2.42" data-path="getting-used-to-r-and-r-studio.html"><a href="getting-used-to-r-and-r-studio.html#median-0.0000-median-4.000-median-2.000"><i class="fa fa-check"></i><b>2.42</b> Median :0.0000 Median :4.000 Median :2.000</a></li>
<li class="chapter" data-level="2.43" data-path="getting-used-to-r-and-r-studio.html"><a href="getting-used-to-r-and-r-studio.html#mean-0.4062-mean-3.688-mean-2.812"><i class="fa fa-check"></i><b>2.43</b> Mean :0.4062 Mean :3.688 Mean :2.812</a></li>
<li class="chapter" data-level="2.44" data-path="getting-used-to-r-and-r-studio.html"><a href="getting-used-to-r-and-r-studio.html#rd-qu.1.0000-3rd-qu.4.000-3rd-qu.4.000"><i class="fa fa-check"></i><b>2.44</b> 3rd Qu.:1.0000 3rd Qu.:4.000 3rd Qu.:4.000</a></li>
<li class="chapter" data-level="2.45" data-path="getting-used-to-r-and-r-studio.html"><a href="getting-used-to-r-and-r-studio.html#max.-1.0000-max.-5.000-max.-8.000"><i class="fa fa-check"></i><b>2.45</b> Max. :1.0000 Max. :5.000 Max. :8.000</a></li>
<li class="chapter" data-level="2.46" data-path="getting-used-to-r-and-r-studio.html"><a href="getting-used-to-r-and-r-studio.html#reading-data-from-a-file"><i class="fa fa-check"></i><b>2.46</b> Reading data from a file</a></li>
<li class="chapter" data-level="2.47" data-path="getting-used-to-r-and-r-studio.html"><a href="getting-used-to-r-and-r-studio.html#parsed-with-column-specification"><i class="fa fa-check"></i><b>2.47</b> Parsed with column specification:</a></li>
<li class="chapter" data-level="2.48" data-path="getting-used-to-r-and-r-studio.html"><a href="getting-used-to-r-and-r-studio.html#cols"><i class="fa fa-check"></i><b>2.48</b> cols(</a></li>
<li class="chapter" data-level="2.49" data-path="getting-used-to-r-and-r-studio.html"><a href="getting-used-to-r-and-r-studio.html#group-col_character"><i class="fa fa-check"></i><b>2.49</b> group = col_character(),</a></li>
<li class="chapter" data-level="2.50" data-path="getting-used-to-r-and-r-studio.html"><a href="getting-used-to-r-and-r-studio.html#density-col_integer"><i class="fa fa-check"></i><b>2.50</b> density = col_integer()</a></li>
<li class="chapter" data-level="2.51" data-path="getting-used-to-r-and-r-studio.html"><a href="getting-used-to-r-and-r-studio.html#section-11"><i class="fa fa-check"></i><b>2.51</b> )</a></li>
<li class="chapter" data-level="2.52" data-path="getting-used-to-r-and-r-studio.html"><a href="getting-used-to-r-and-r-studio.html#a-tibble-30-x-2"><i class="fa fa-check"></i><b>2.52</b> # A tibble: 30 x 2</a></li>
<li class="chapter" data-level="2.53" data-path="getting-used-to-r-and-r-studio.html"><a href="getting-used-to-r-and-r-studio.html#group-density"><i class="fa fa-check"></i><b>2.53</b> group density</a></li>
<li class="chapter" data-level="2.54" data-path="getting-used-to-r-and-r-studio.html"><a href="getting-used-to-r-and-r-studio.html#section-12"><i class="fa fa-check"></i><b>2.54</b> <chr> <int></a></li>
<li class="chapter" data-level="2.55" data-path="getting-used-to-r-and-r-studio.html"><a href="getting-used-to-r-and-r-studio.html#control-611"><i class="fa fa-check"></i><b>2.55</b> 1 Control 611</a></li>
<li class="chapter" data-level="2.56" data-path="getting-used-to-r-and-r-studio.html"><a href="getting-used-to-r-and-r-studio.html#control-621"><i class="fa fa-check"></i><b>2.56</b> 2 Control 621</a></li>
<li class="chapter" data-level="2.57" data-path="getting-used-to-r-and-r-studio.html"><a href="getting-used-to-r-and-r-studio.html#control-614"><i class="fa fa-check"></i><b>2.57</b> 3 Control 614</a></li>
<li class="chapter" data-level="2.58" data-path="getting-used-to-r-and-r-studio.html"><a href="getting-used-to-r-and-r-studio.html#control-593"><i class="fa fa-check"></i><b>2.58</b> 4 Control 593</a></li>
<li class="chapter" data-level="2.59" data-path="getting-used-to-r-and-r-studio.html"><a href="getting-used-to-r-and-r-studio.html#control-593-1"><i class="fa fa-check"></i><b>2.59</b> 5 Control 593</a></li>
<li class="chapter" data-level="2.60" data-path="getting-used-to-r-and-r-studio.html"><a href="getting-used-to-r-and-r-studio.html#control-653"><i class="fa fa-check"></i><b>2.60</b> 6 Control 653</a></li>
<li class="chapter" data-level="2.61" data-path="getting-used-to-r-and-r-studio.html"><a href="getting-used-to-r-and-r-studio.html#control-600"><i class="fa fa-check"></i><b>2.61</b> 7 Control 600</a></li>
<li class="chapter" data-level="2.62" data-path="getting-used-to-r-and-r-studio.html"><a href="getting-used-to-r-and-r-studio.html#control-554"><i class="fa fa-check"></i><b>2.62</b> 8 Control 554</a></li>
<li class="chapter" data-level="2.63" data-path="getting-used-to-r-and-r-studio.html"><a href="getting-used-to-r-and-r-studio.html#control-603"><i class="fa fa-check"></i><b>2.63</b> 9 Control 603</a></li>
<li class="chapter" data-level="2.64" data-path="getting-used-to-r-and-r-studio.html"><a href="getting-used-to-r-and-r-studio.html#control-569"><i class="fa fa-check"></i><b>2.64</b> 10 Control 569</a></li>
<li class="chapter" data-level="2.65" data-path="getting-used-to-r-and-r-studio.html"><a href="getting-used-to-r-and-r-studio.html#with-20-more-rows"><i class="fa fa-check"></i><b>2.65</b> # … with 20 more rows</a></li>
<li class="chapter" data-level="2.66" data-path="getting-used-to-r-and-r-studio.html"><a href="getting-used-to-r-and-r-studio.html#a-tibble-3-x-2"><i class="fa fa-check"></i><b>2.66</b> # A tibble: 3 x 2</a></li>
<li class="chapter" data-level="2.67" data-path="getting-used-to-r-and-r-studio.html"><a href="getting-used-to-r-and-r-studio.html#group-m"><i class="fa fa-check"></i><b>2.67</b> group m</a></li>
<li class="chapter" data-level="2.68" data-path="getting-used-to-r-and-r-studio.html"><a href="getting-used-to-r-and-r-studio.html#section-13"><i class="fa fa-check"></i><b>2.68</b> <chr> <dbl></a></li>
<li class="chapter" data-level="2.69" data-path="getting-used-to-r-and-r-studio.html"><a href="getting-used-to-r-and-r-studio.html#control-601."><i class="fa fa-check"></i><b>2.69</b> 1 Control 601.</a></li>
<li class="chapter" data-level="2.70" data-path="getting-used-to-r-and-r-studio.html"><a href="getting-used-to-r-and-r-studio.html#highjump-639."><i class="fa fa-check"></i><b>2.70</b> 2 Highjump 639.</a></li>
<li class="chapter" data-level="2.71" data-path="getting-used-to-r-and-r-studio.html"><a href="getting-used-to-r-and-r-studio.html#lowjump-612."><i class="fa fa-check"></i><b>2.71</b> 3 Lowjump 612.</a></li>
</ul></li>
<li class="chapter" data-level="3" data-path="reading-in-data-and-drawing-some-graphs.html"><a href="reading-in-data-and-drawing-some-graphs.html"><i class="fa fa-check"></i><b>3</b> Reading in data and drawing some graphs</a><ul>
<li class="chapter" data-level="3.1" data-path="reading-in-data-and-drawing-some-graphs.html"><a href="reading-in-data-and-drawing-some-graphs.html#orange-juice"><i class="fa fa-check"></i><b>3.1</b> Orange juice</a></li>
<li class="chapter" data-level="3.2" data-path="reading-in-data-and-drawing-some-graphs.html"><a href="reading-in-data-and-drawing-some-graphs.html#attaching-packages-tidyverse-1.2.1-1"><i class="fa fa-check"></i><b>3.2</b> ── Attaching packages ─────────────────────────────────────────────────────────────────────────────────────── tidyverse 1.2.1 ──</a></li>
<li class="chapter" data-level="3.3" data-path="reading-in-data-and-drawing-some-graphs.html"><a href="reading-in-data-and-drawing-some-graphs.html#ggplot2-3.0.0-purrr-0.2.5-1"><i class="fa fa-check"></i><b>3.3</b> ✔ ggplot2 3.0.0 ✔ purrr 0.2.5</a></li>
<li class="chapter" data-level="3.4" data-path="reading-in-data-and-drawing-some-graphs.html"><a href="reading-in-data-and-drawing-some-graphs.html#tibble-1.4.2-dplyr-0.7.6-1"><i class="fa fa-check"></i><b>3.4</b> ✔ tibble 1.4.2 ✔ dplyr 0.7.6</a></li>
<li class="chapter" data-level="3.5" data-path="reading-in-data-and-drawing-some-graphs.html"><a href="reading-in-data-and-drawing-some-graphs.html#tidyr-0.8.1-stringr-1.3.1-1"><i class="fa fa-check"></i><b>3.5</b> ✔ tidyr 0.8.1 ✔ stringr 1.3.1</a></li>
<li class="chapter" data-level="3.6" data-path="reading-in-data-and-drawing-some-graphs.html"><a href="reading-in-data-and-drawing-some-graphs.html#readr-1.1.1-forcats-0.3.0-1"><i class="fa fa-check"></i><b>3.6</b> ✔ readr 1.1.1 ✔ forcats 0.3.0</a></li>
<li class="chapter" data-level="3.7" data-path="reading-in-data-and-drawing-some-graphs.html"><a href="reading-in-data-and-drawing-some-graphs.html#conflicts-tidyverse_conflicts-1"><i class="fa fa-check"></i><b>3.7</b> ── Conflicts ────────────────────────────────────────────────────────────────────────────────────────── tidyverse_conflicts() ──</a></li>
<li class="chapter" data-level="3.8" data-path="reading-in-data-and-drawing-some-graphs.html"><a href="reading-in-data-and-drawing-some-graphs.html#dplyrfilter-masks-statsfilter-1"><i class="fa fa-check"></i><b>3.8</b> ✖ dplyr::filter() masks stats::filter()</a></li>
<li class="chapter" data-level="3.9" data-path="reading-in-data-and-drawing-some-graphs.html"><a href="reading-in-data-and-drawing-some-graphs.html#dplyrlag-masks-statslag-1"><i class="fa fa-check"></i><b>3.9</b> ✖ dplyr::lag() masks stats::lag()</a></li>
<li class="chapter" data-level="3.10" data-path="reading-in-data-and-drawing-some-graphs.html"><a href="reading-in-data-and-drawing-some-graphs.html#parsed-with-column-specification-1"><i class="fa fa-check"></i><b>3.10</b> Parsed with column specification:</a></li>
<li class="chapter" data-level="3.11" data-path="reading-in-data-and-drawing-some-graphs.html"><a href="reading-in-data-and-drawing-some-graphs.html#cols-1"><i class="fa fa-check"></i><b>3.11</b> cols(</a></li>
<li class="chapter" data-level="3.12" data-path="reading-in-data-and-drawing-some-graphs.html"><a href="reading-in-data-and-drawing-some-graphs.html#run-col_integer"><i class="fa fa-check"></i><b>3.12</b> run = col_integer(),</a></li>
<li class="chapter" data-level="3.13" data-path="reading-in-data-and-drawing-some-graphs.html"><a href="reading-in-data-and-drawing-some-graphs.html#sweetness-col_double"><i class="fa fa-check"></i><b>3.13</b> sweetness = col_double(),</a></li>
<li class="chapter" data-level="3.14" data-path="reading-in-data-and-drawing-some-graphs.html"><a href="reading-in-data-and-drawing-some-graphs.html#pectin-col_integer"><i class="fa fa-check"></i><b>3.14</b> pectin = col_integer()</a></li>
<li class="chapter" data-level="3.15" data-path="reading-in-data-and-drawing-some-graphs.html"><a href="reading-in-data-and-drawing-some-graphs.html#section-14"><i class="fa fa-check"></i><b>3.15</b> )</a></li>
<li class="chapter" data-level="3.16" data-path="reading-in-data-and-drawing-some-graphs.html"><a href="reading-in-data-and-drawing-some-graphs.html#a-tibble-24-x-3"><i class="fa fa-check"></i><b>3.16</b> # A tibble: 24 x 3</a></li>
<li class="chapter" data-level="3.17" data-path="reading-in-data-and-drawing-some-graphs.html"><a href="reading-in-data-and-drawing-some-graphs.html#run-sweetness-pectin"><i class="fa fa-check"></i><b>3.17</b> run sweetness pectin</a></li>
<li class="chapter" data-level="3.18" data-path="reading-in-data-and-drawing-some-graphs.html"><a href="reading-in-data-and-drawing-some-graphs.html#section-15"><i class="fa fa-check"></i><b>3.18</b> <int> <dbl> <int></a></li>
<li class="chapter" data-level="3.19" data-path="reading-in-data-and-drawing-some-graphs.html"><a href="reading-in-data-and-drawing-some-graphs.html#section-16"><i class="fa fa-check"></i><b>3.19</b> 1 1 5.2 220</a></li>
<li class="chapter" data-level="3.20" data-path="reading-in-data-and-drawing-some-graphs.html"><a href="reading-in-data-and-drawing-some-graphs.html#section-17"><i class="fa fa-check"></i><b>3.20</b> 2 2 5.5 227</a></li>
<li class="chapter" data-level="3.21" data-path="reading-in-data-and-drawing-some-graphs.html"><a href="reading-in-data-and-drawing-some-graphs.html#section-18"><i class="fa fa-check"></i><b>3.21</b> 3 3 6 259</a></li>
<li class="chapter" data-level="3.22" data-path="reading-in-data-and-drawing-some-graphs.html"><a href="reading-in-data-and-drawing-some-graphs.html#section-19"><i class="fa fa-check"></i><b>3.22</b> 4 4 5.9 210</a></li>
<li class="chapter" data-level="3.23" data-path="reading-in-data-and-drawing-some-graphs.html"><a href="reading-in-data-and-drawing-some-graphs.html#section-20"><i class="fa fa-check"></i><b>3.23</b> 5 5 5.8 224</a></li>
<li class="chapter" data-level="3.24" data-path="reading-in-data-and-drawing-some-graphs.html"><a href="reading-in-data-and-drawing-some-graphs.html#section-21"><i class="fa fa-check"></i><b>3.24</b> 6 6 6 215</a></li>
<li class="chapter" data-level="3.25" data-path="reading-in-data-and-drawing-some-graphs.html"><a href="reading-in-data-and-drawing-some-graphs.html#section-22"><i class="fa fa-check"></i><b>3.25</b> 7 7 5.8 231</a></li>
<li class="chapter" data-level="3.26" data-path="reading-in-data-and-drawing-some-graphs.html"><a href="reading-in-data-and-drawing-some-graphs.html#section-23"><i class="fa fa-check"></i><b>3.26</b> 8 8 5.6 268</a></li>
<li class="chapter" data-level="3.27" data-path="reading-in-data-and-drawing-some-graphs.html"><a href="reading-in-data-and-drawing-some-graphs.html#section-24"><i class="fa fa-check"></i><b>3.27</b> 9 9 5.6 239</a></li>
<li class="chapter" data-level="3.28" data-path="reading-in-data-and-drawing-some-graphs.html"><a href="reading-in-data-and-drawing-some-graphs.html#section-25"><i class="fa fa-check"></i><b>3.28</b> 10 10 5.9 212</a></li>
<li class="chapter" data-level="3.29" data-path="reading-in-data-and-drawing-some-graphs.html"><a href="reading-in-data-and-drawing-some-graphs.html#with-14-more-rows"><i class="fa fa-check"></i><b>3.29</b> # … with 14 more rows</a></li>
<li class="chapter" data-level="3.30" data-path="reading-in-data-and-drawing-some-graphs.html"><a href="reading-in-data-and-drawing-some-graphs.html#parsed-with-column-specification-2"><i class="fa fa-check"></i><b>3.30</b> Parsed with column specification:</a></li>
<li class="chapter" data-level="3.31" data-path="reading-in-data-and-drawing-some-graphs.html"><a href="reading-in-data-and-drawing-some-graphs.html#cols-2"><i class="fa fa-check"></i><b>3.31</b> cols(</a></li>
<li class="chapter" data-level="3.32" data-path="reading-in-data-and-drawing-some-graphs.html"><a href="reading-in-data-and-drawing-some-graphs.html#x-col_integer"><i class="fa fa-check"></i><b>3.32</b> x = col_integer(),</a></li>
<li class="chapter" data-level="3.33" data-path="reading-in-data-and-drawing-some-graphs.html"><a href="reading-in-data-and-drawing-some-graphs.html#y-col_integer"><i class="fa fa-check"></i><b>3.33</b> y = col_integer()</a></li>
<li class="chapter" data-level="3.34" data-path="reading-in-data-and-drawing-some-graphs.html"><a href="reading-in-data-and-drawing-some-graphs.html#section-26"><i class="fa fa-check"></i><b>3.34</b> )</a></li>
<li class="chapter" data-level="3.35" data-path="reading-in-data-and-drawing-some-graphs.html"><a href="reading-in-data-and-drawing-some-graphs.html#a-tibble-3-x-2-1"><i class="fa fa-check"></i><b>3.35</b> # A tibble: 3 x 2</a></li>
<li class="chapter" data-level="3.36" data-path="reading-in-data-and-drawing-some-graphs.html"><a href="reading-in-data-and-drawing-some-graphs.html#x-y"><i class="fa fa-check"></i><b>3.36</b> x y</a></li>
<li class="chapter" data-level="3.37" data-path="reading-in-data-and-drawing-some-graphs.html"><a href="reading-in-data-and-drawing-some-graphs.html#section-27"><i class="fa fa-check"></i><b>3.37</b> <int> <int></a></li>
<li class="chapter" data-level="3.38" data-path="reading-in-data-and-drawing-some-graphs.html"><a href="reading-in-data-and-drawing-some-graphs.html#section-28"><i class="fa fa-check"></i><b>3.38</b> 1 1 2</a></li>
<li class="chapter" data-level="3.39" data-path="reading-in-data-and-drawing-some-graphs.html"><a href="reading-in-data-and-drawing-some-graphs.html#section-29"><i class="fa fa-check"></i><b>3.39</b> 2 3 4</a></li>
<li class="chapter" data-level="3.40" data-path="reading-in-data-and-drawing-some-graphs.html"><a href="reading-in-data-and-drawing-some-graphs.html#section-30"><i class="fa fa-check"></i><b>3.40</b> 3 5 6</a></li>
<li class="chapter" data-level="3.41" data-path="reading-in-data-and-drawing-some-graphs.html"><a href="reading-in-data-and-drawing-some-graphs.html#geom_smooth-using-method-loess-and-formula-y-x"><i class="fa fa-check"></i><b>3.41</b> <code>geom_smooth()</code> using method = ‘loess’ and formula ‘y ~ x’</a></li>
<li class="chapter" data-level="3.42" data-path="reading-in-data-and-drawing-some-graphs.html"><a href="reading-in-data-and-drawing-some-graphs.html#making-soap"><i class="fa fa-check"></i><b>3.42</b> Making soap</a></li>
<li class="chapter" data-level="3.43" data-path="reading-in-data-and-drawing-some-graphs.html"><a href="reading-in-data-and-drawing-some-graphs.html#parsed-with-column-specification-3"><i class="fa fa-check"></i><b>3.43</b> Parsed with column specification:</a></li>
<li class="chapter" data-level="3.44" data-path="reading-in-data-and-drawing-some-graphs.html"><a href="reading-in-data-and-drawing-some-graphs.html#cols-3"><i class="fa fa-check"></i><b>3.44</b> cols(</a></li>
<li class="chapter" data-level="3.45" data-path="reading-in-data-and-drawing-some-graphs.html"><a href="reading-in-data-and-drawing-some-graphs.html#case-col_integer"><i class="fa fa-check"></i><b>3.45</b> case = col_integer(),</a></li>
<li class="chapter" data-level="3.46" data-path="reading-in-data-and-drawing-some-graphs.html"><a href="reading-in-data-and-drawing-some-graphs.html#scrap-col_integer"><i class="fa fa-check"></i><b>3.46</b> scrap = col_integer(),</a></li>
<li class="chapter" data-level="3.47" data-path="reading-in-data-and-drawing-some-graphs.html"><a href="reading-in-data-and-drawing-some-graphs.html#speed-col_integer"><i class="fa fa-check"></i><b>3.47</b> speed = col_integer(),</a></li>
<li class="chapter" data-level="3.48" data-path="reading-in-data-and-drawing-some-graphs.html"><a href="reading-in-data-and-drawing-some-graphs.html#line-col_character"><i class="fa fa-check"></i><b>3.48</b> line = col_character()</a></li>
<li class="chapter" data-level="3.49" data-path="reading-in-data-and-drawing-some-graphs.html"><a href="reading-in-data-and-drawing-some-graphs.html#section-31"><i class="fa fa-check"></i><b>3.49</b> )</a></li>
<li class="chapter" data-level="3.50" data-path="reading-in-data-and-drawing-some-graphs.html"><a href="reading-in-data-and-drawing-some-graphs.html#a-tibble-27-x-4"><i class="fa fa-check"></i><b>3.50</b> # A tibble: 27 x 4</a></li>
<li class="chapter" data-level="3.51" data-path="reading-in-data-and-drawing-some-graphs.html"><a href="reading-in-data-and-drawing-some-graphs.html#case-scrap-speed-line"><i class="fa fa-check"></i><b>3.51</b> case scrap speed line</a></li>
<li class="chapter" data-level="3.52" data-path="reading-in-data-and-drawing-some-graphs.html"><a href="reading-in-data-and-drawing-some-graphs.html#section-32"><i class="fa fa-check"></i><b>3.52</b> <int> <int> <int> <chr></a></li>
<li class="chapter" data-level="3.53" data-path="reading-in-data-and-drawing-some-graphs.html"><a href="reading-in-data-and-drawing-some-graphs.html#a"><i class="fa fa-check"></i><b>3.53</b> 1 1 218 100 a</a></li>
<li class="chapter" data-level="3.54" data-path="reading-in-data-and-drawing-some-graphs.html"><a href="reading-in-data-and-drawing-some-graphs.html#a-1"><i class="fa fa-check"></i><b>3.54</b> 2 2 248 125 a</a></li>
<li class="chapter" data-level="3.55" data-path="reading-in-data-and-drawing-some-graphs.html"><a href="reading-in-data-and-drawing-some-graphs.html#a-2"><i class="fa fa-check"></i><b>3.55</b> 3 3 360 220 a</a></li>
<li class="chapter" data-level="3.56" data-path="reading-in-data-and-drawing-some-graphs.html"><a href="reading-in-data-and-drawing-some-graphs.html#a-3"><i class="fa fa-check"></i><b>3.56</b> 4 4 351 205 a</a></li>
<li class="chapter" data-level="3.57" data-path="reading-in-data-and-drawing-some-graphs.html"><a href="reading-in-data-and-drawing-some-graphs.html#a-4"><i class="fa fa-check"></i><b>3.57</b> 5 5 470 300 a</a></li>
<li class="chapter" data-level="3.58" data-path="reading-in-data-and-drawing-some-graphs.html"><a href="reading-in-data-and-drawing-some-graphs.html#a-5"><i class="fa fa-check"></i><b>3.58</b> 6 6 394 255 a</a></li>
<li class="chapter" data-level="3.59" data-path="reading-in-data-and-drawing-some-graphs.html"><a href="reading-in-data-and-drawing-some-graphs.html#a-6"><i class="fa fa-check"></i><b>3.59</b> 7 7 332 225 a</a></li>
<li class="chapter" data-level="3.60" data-path="reading-in-data-and-drawing-some-graphs.html"><a href="reading-in-data-and-drawing-some-graphs.html#a-7"><i class="fa fa-check"></i><b>3.60</b> 8 8 321 175 a</a></li>
<li class="chapter" data-level="3.61" data-path="reading-in-data-and-drawing-some-graphs.html"><a href="reading-in-data-and-drawing-some-graphs.html#a-8"><i class="fa fa-check"></i><b>3.61</b> 9 9 410 270 a</a></li>
<li class="chapter" data-level="3.62" data-path="reading-in-data-and-drawing-some-graphs.html"><a href="reading-in-data-and-drawing-some-graphs.html#a-9"><i class="fa fa-check"></i><b>3.62</b> 10 10 260 170 a</a></li>
<li class="chapter" data-level="3.63" data-path="reading-in-data-and-drawing-some-graphs.html"><a href="reading-in-data-and-drawing-some-graphs.html#with-17-more-rows"><i class="fa fa-check"></i><b>3.63</b> # … with 17 more rows</a></li>
<li class="chapter" data-level="3.64" data-path="reading-in-data-and-drawing-some-graphs.html"><a href="reading-in-data-and-drawing-some-graphs.html#section-33"><i class="fa fa-check"></i><b>3.64</b> </a></li>
<li class="chapter" data-level="3.65" data-path="reading-in-data-and-drawing-some-graphs.html"><a href="reading-in-data-and-drawing-some-graphs.html#welch-two-sample-t-test"><i class="fa fa-check"></i><b>3.65</b> Welch Two Sample t-test</a></li>
<li class="chapter" data-level="3.66" data-path="reading-in-data-and-drawing-some-graphs.html"><a href="reading-in-data-and-drawing-some-graphs.html#section-34"><i class="fa fa-check"></i><b>3.66</b> </a></li>
<li class="chapter" data-level="3.67" data-path="reading-in-data-and-drawing-some-graphs.html"><a href="reading-in-data-and-drawing-some-graphs.html#data-scrap-by-line"><i class="fa fa-check"></i><b>3.67</b> data: scrap by line</a></li>
<li class="chapter" data-level="3.68" data-path="reading-in-data-and-drawing-some-graphs.html"><a href="reading-in-data-and-drawing-some-graphs.html#t-1.2493-df-21.087-p-value-0.2253"><i class="fa fa-check"></i><b>3.68</b> t = 1.2493, df = 21.087, p-value = 0.2253</a></li>
<li class="chapter" data-level="3.69" data-path="reading-in-data-and-drawing-some-graphs.html"><a href="reading-in-data-and-drawing-some-graphs.html#alternative-hypothesis-true-difference-in-means-is-not-equal-to-0"><i class="fa fa-check"></i><b>3.69</b> alternative hypothesis: true difference in means is not equal to 0</a></li>
<li class="chapter" data-level="3.70" data-path="reading-in-data-and-drawing-some-graphs.html"><a href="reading-in-data-and-drawing-some-graphs.html#percent-confidence-interval"><i class="fa fa-check"></i><b>3.70</b> 95 percent confidence interval:</a></li>
<li class="chapter" data-level="3.71" data-path="reading-in-data-and-drawing-some-graphs.html"><a href="reading-in-data-and-drawing-some-graphs.html#section-35"><i class="fa fa-check"></i><b>3.71</b> -26.97888 108.21222</a></li>
<li class="chapter" data-level="3.72" data-path="reading-in-data-and-drawing-some-graphs.html"><a href="reading-in-data-and-drawing-some-graphs.html#sample-estimates"><i class="fa fa-check"></i><b>3.72</b> sample estimates:</a></li>
<li class="chapter" data-level="3.73" data-path="reading-in-data-and-drawing-some-graphs.html"><a href="reading-in-data-and-drawing-some-graphs.html#mean-in-group-a-mean-in-group-b"><i class="fa fa-check"></i><b>3.73</b> mean in group a mean in group b</a></li>
<li class="chapter" data-level="3.74" data-path="reading-in-data-and-drawing-some-graphs.html"><a href="reading-in-data-and-drawing-some-graphs.html#section-36"><i class="fa fa-check"></i><b>3.74</b> 333.5333 292.9167</a></li>
<li class="chapter" data-level="3.75" data-path="reading-in-data-and-drawing-some-graphs.html"><a href="reading-in-data-and-drawing-some-graphs.html#section-37"><i class="fa fa-check"></i><b>3.75</b> </a></li>
<li class="chapter" data-level="3.76" data-path="reading-in-data-and-drawing-some-graphs.html"><a href="reading-in-data-and-drawing-some-graphs.html#call"><i class="fa fa-check"></i><b>3.76</b> Call:</a></li>
<li class="chapter" data-level="3.77" data-path="reading-in-data-and-drawing-some-graphs.html"><a href="reading-in-data-and-drawing-some-graphs.html#lmformula-scrap-speed-line-data-soap"><i class="fa fa-check"></i><b>3.77</b> lm(formula = scrap ~ speed + line, data = soap)</a></li>
<li class="chapter" data-level="3.78" data-path="reading-in-data-and-drawing-some-graphs.html"><a href="reading-in-data-and-drawing-some-graphs.html#section-38"><i class="fa fa-check"></i><b>3.78</b> </a></li>
<li class="chapter" data-level="3.79" data-path="reading-in-data-and-drawing-some-graphs.html"><a href="reading-in-data-and-drawing-some-graphs.html#residuals"><i class="fa fa-check"></i><b>3.79</b> Residuals:</a></li>
<li class="chapter" data-level="3.80" data-path="reading-in-data-and-drawing-some-graphs.html"><a href="reading-in-data-and-drawing-some-graphs.html#min-1q-median-3q-max"><i class="fa fa-check"></i><b>3.80</b> Min 1Q Median 3Q Max</a></li>
<li class="chapter" data-level="3.81" data-path="reading-in-data-and-drawing-some-graphs.html"><a href="reading-in-data-and-drawing-some-graphs.html#section-39"><i class="fa fa-check"></i><b>3.81</b> -39.557 -14.161 -0.121 17.518 33.953</a></li>
<li class="chapter" data-level="3.82" data-path="reading-in-data-and-drawing-some-graphs.html"><a href="reading-in-data-and-drawing-some-graphs.html#section-40"><i class="fa fa-check"></i><b>3.82</b> </a></li>
<li class="chapter" data-level="3.83" data-path="reading-in-data-and-drawing-some-graphs.html"><a href="reading-in-data-and-drawing-some-graphs.html#coefficients"><i class="fa fa-check"></i><b>3.83</b> Coefficients:</a></li>
<li class="chapter" data-level="3.84" data-path="reading-in-data-and-drawing-some-graphs.html"><a href="reading-in-data-and-drawing-some-graphs.html#estimate-std.-error-t-value-prt"><i class="fa fa-check"></i><b>3.84</b> Estimate Std. Error t value Pr(&gt;|t|)</a></li>
<li><a href="reading-in-data-and-drawing-some-graphs.html#intercept-80.41099-14.54379-5.529-1.10e-05-speed-1.23074-0.06555-18.775-7.48e-16"><span class="toc-section-number">3.85</span> (Intercept) 80.41099 14.54379 5.529 1.10e-05 <strong><em>
## speed 1.23074 0.06555 18.775 7.48e-16 </em></strong></a></li>
<li><a href="reading-in-data-and-drawing-some-graphs.html#lineb--53.12920-8.21003--6.471-1.08e-06-signif.-codes-0-0.001-0.01-0.05-.-0.1-1-residual-standard-error-21.13-on-24-degrees-of-freedom-multiple-r-squared-0.9402-adjusted-r-squared-0.9352-f-statistic-188.6-on-2-and-24-df-p-value-2.104e-15-handling-shipments-parsed-with-column-specification-cols-warehouse-col_character-size-col_integer-cost-col_double-a-tibble-10-x-3-warehouse-size-cost-1-a-225-12.0-2-b-350-14.1-3-a-150-8.93-4-a-200-11.0-5-a-175-10.0-6-a-180-10.1-7-b-325-13.8-8-b-290-13.3-9-b-400-15-10-a-125-7.97"><span class="toc-section-number">3.86</span> lineb -53.12920 8.21003 -6.471 1.08e-06 ***
## —
## Signif. codes: 0 ‘<em><strong>’ 0.001 ’</strong>’ 0.01 ’</em>’ 0.05 ‘.’ 0.1 ‘’ 1
##
## Residual standard error: 21.13 on 24 degrees of freedom
## Multiple R-squared: 0.9402, Adjusted R-squared: 0.9352
## F-statistic: 188.6 on 2 and 24 DF, p-value: 2.104e-15
## Handling shipments
## Parsed with column specification:
## cols(
## warehouse = col_character(),
## size = col_integer(),
## cost = col_double()
## )
## # A tibble: 10 x 3
## warehouse size cost
## <chr> <int> <dbl>
## 1 A 225 12.0
## 2 B 350 14.1
## 3 A 150 8.93
## 4 A 200 11.0
## 5 A 175 10.0
## 6 A 180 10.1
## 7 B 325 13.8
## 8 B 290 13.3
## 9 B 400 15<br />
## 10 A 125 7.97</a></li>
</ul></li>
<li class="chapter" data-level="4" data-path="data-exploration.html"><a href="data-exploration.html"><i class="fa fa-check"></i><b>4</b> Data exploration</a><ul>
<li class="chapter" data-level="4.1" data-path="data-exploration.html"><a href="data-exploration.html#north-carolina-births"><i class="fa fa-check"></i><b>4.1</b> North Carolina births</a></li>
<li class="chapter" data-level="4.2" data-path="data-exploration.html"><a href="data-exploration.html#more-about-the-nc-births"><i class="fa fa-check"></i><b>4.2</b> More about the NC births</a></li>
<li class="chapter" data-level="4.3" data-path="data-exploration.html"><a href="data-exploration.html#nenana-alaska"><i class="fa fa-check"></i><b>4.3</b> Nenana, Alaska</a></li>
<li class="chapter" data-level="4.4" data-path="data-exploration.html"><a href="data-exploration.html#computerized-accounting"><i class="fa fa-check"></i><b>4.4</b> Computerized accounting</a></li>
<li class="chapter" data-level="4.5" data-path="data-exploration.html"><a href="data-exploration.html#hunter-gatherers-in-australia"><i class="fa fa-check"></i><b>4.5</b> Hunter-gatherers in Australia</a></li>
</ul></li>
<li class="chapter" data-level="5" data-path="one-sample-inference.html"><a href="one-sample-inference.html"><i class="fa fa-check"></i><b>5</b> One-sample inference</a><ul>
<li class="chapter" data-level="5.1" data-path="one-sample-inference.html"><a href="one-sample-inference.html#attaching-packages-tidyverse-1.2.1-2"><i class="fa fa-check"></i><b>5.1</b> ── Attaching packages ─────────────────────────────────────────────────────────────────────────────────────── tidyverse 1.2.1 ──</a></li>
<li class="chapter" data-level="5.2" data-path="one-sample-inference.html"><a href="one-sample-inference.html#ggplot2-3.0.0-purrr-0.2.5-2"><i class="fa fa-check"></i><b>5.2</b> ✔ ggplot2 3.0.0 ✔ purrr 0.2.5</a></li>
<li class="chapter" data-level="5.3" data-path="one-sample-inference.html"><a href="one-sample-inference.html#tibble-1.4.2-dplyr-0.7.6-2"><i class="fa fa-check"></i><b>5.3</b> ✔ tibble 1.4.2 ✔ dplyr 0.7.6</a></li>
<li class="chapter" data-level="5.4" data-path="one-sample-inference.html"><a href="one-sample-inference.html#tidyr-0.8.1-stringr-1.3.1-2"><i class="fa fa-check"></i><b>5.4</b> ✔ tidyr 0.8.1 ✔ stringr 1.3.1</a></li>
<li class="chapter" data-level="5.5" data-path="one-sample-inference.html"><a href="one-sample-inference.html#readr-1.1.1-forcats-0.3.0-2"><i class="fa fa-check"></i><b>5.5</b> ✔ readr 1.1.1 ✔ forcats 0.3.0</a></li>
<li class="chapter" data-level="5.6" data-path="one-sample-inference.html"><a href="one-sample-inference.html#conflicts-tidyverse_conflicts-2"><i class="fa fa-check"></i><b>5.6</b> ── Conflicts ────────────────────────────────────────────────────────────────────────────────────────── tidyverse_conflicts() ──</a></li>
<li class="chapter" data-level="5.7" data-path="one-sample-inference.html"><a href="one-sample-inference.html#dplyrfilter-masks-statsfilter-2"><i class="fa fa-check"></i><b>5.7</b> ✖ dplyr::filter() masks stats::filter()</a></li>
<li class="chapter" data-level="5.8" data-path="one-sample-inference.html"><a href="one-sample-inference.html#dplyrlag-masks-statslag-2"><i class="fa fa-check"></i><b>5.8</b> ✖ dplyr::lag() masks stats::lag()</a></li>
<li class="chapter" data-level="5.9" data-path="one-sample-inference.html"><a href="one-sample-inference.html#length-of-gestation-in-north-carolina"><i class="fa fa-check"></i><b>5.9</b> Length of gestation in North Carolina</a></li>
<li class="chapter" data-level="5.10" data-path="one-sample-inference.html"><a href="one-sample-inference.html#parsed-with-column-specification-4"><i class="fa fa-check"></i><b>5.10</b> Parsed with column specification:</a></li>
<li class="chapter" data-level="5.11" data-path="one-sample-inference.html"><a href="one-sample-inference.html#cols-4"><i class="fa fa-check"></i><b>5.11</b> cols(</a></li>
<li class="chapter" data-level="5.12" data-path="one-sample-inference.html"><a href="one-sample-inference.html#father-age-col_integer"><i class="fa fa-check"></i><b>5.12</b> <code>Father Age</code> = col_integer(),</a></li>
<li class="chapter" data-level="5.13" data-path="one-sample-inference.html"><a href="one-sample-inference.html#mother-age-col_integer"><i class="fa fa-check"></i><b>5.13</b> <code>Mother Age</code> = col_integer(),</a></li>
<li class="chapter" data-level="5.14" data-path="one-sample-inference.html"><a href="one-sample-inference.html#weeks-gestation-col_integer"><i class="fa fa-check"></i><b>5.14</b> <code>Weeks Gestation</code> = col_integer(),</a></li>
<li class="chapter" data-level="5.15" data-path="one-sample-inference.html"><a href="one-sample-inference.html#pre-natal-visits-col_integer"><i class="fa fa-check"></i><b>5.15</b> <code>Pre-natal Visits</code> = col_integer(),</a></li>
<li class="chapter" data-level="5.16" data-path="one-sample-inference.html"><a href="one-sample-inference.html#marital-status-col_integer"><i class="fa fa-check"></i><b>5.16</b> <code>Marital Status</code> = col_integer(),</a></li>
<li class="chapter" data-level="5.17" data-path="one-sample-inference.html"><a href="one-sample-inference.html#mother-weight-gained-col_integer"><i class="fa fa-check"></i><b>5.17</b> <code>Mother Weight Gained</code> = col_integer(),</a></li>
<li class="chapter" data-level="5.18" data-path="one-sample-inference.html"><a href="one-sample-inference.html#low-birthweight-col_integer"><i class="fa fa-check"></i><b>5.18</b> <code>Low Birthweight?</code> = col_integer(),</a></li>
<li class="chapter" data-level="5.19" data-path="one-sample-inference.html"><a href="one-sample-inference.html#weight-pounds-col_double"><i class="fa fa-check"></i><b>5.19</b> <code>Weight (pounds)</code> = col_double(),</a></li>
<li class="chapter" data-level="5.20" data-path="one-sample-inference.html"><a href="one-sample-inference.html#premie-col_integer"><i class="fa fa-check"></i><b>5.20</b> <code>Premie?</code> = col_integer(),</a></li>
<li class="chapter" data-level="5.21" data-path="one-sample-inference.html"><a href="one-sample-inference.html#few-visits-col_integer"><i class="fa fa-check"></i><b>5.21</b> <code>Few Visits?</code> = col_integer()</a></li>
<li class="chapter" data-level="5.22" data-path="one-sample-inference.html"><a href="one-sample-inference.html#section-41"><i class="fa fa-check"></i><b>5.22</b> )</a></li>
<li class="chapter" data-level="5.23" data-path="one-sample-inference.html"><a href="one-sample-inference.html#section-42"><i class="fa fa-check"></i><b>5.23</b> </a></li>
<li class="chapter" data-level="5.24" data-path="one-sample-inference.html"><a href="one-sample-inference.html#one-sample-t-test"><i class="fa fa-check"></i><b>5.24</b> One Sample t-test</a></li>
<li class="chapter" data-level="5.25" data-path="one-sample-inference.html"><a href="one-sample-inference.html#section-43"><i class="fa fa-check"></i><b>5.25</b> </a></li>
<li class="chapter" data-level="5.26" data-path="one-sample-inference.html"><a href="one-sample-inference.html#data-bwweight-pounds-t-104.94-df-499-p-value-2.2e-16-alternative-hypothesis-true-mean-is-not-equal-to-0-95-percent-confidence-interval-6.936407-7.201093-sample-estimates-mean-of-x-7.06875-one-sample-t-test-data-weight-pounds-t-104.94-df-499-p-value-2.2e-16-alternative-hypothesis-true-mean-is-not-equal-to-0-95-percent-confidence-interval-6.936407-7.201093-sample-estimates-mean-of-x-7.06875-one-sample-t-test-data-bwweight-pounds"><i class="fa fa-check"></i><b>5.26</b> data: bw<span class="math inline">\(`Weight (pounds)` ## t = 104.94, df = 499, p-value &lt; 2.2e-16 ## alternative hypothesis: true mean is not equal to 0 ## 95 percent confidence interval: ## 6.936407 7.201093 ## sample estimates: ## mean of x ## 7.06875 ## ## One Sample t-test ## ## data: Weight (pounds) ## t = 104.94, df = 499, p-value &lt; 2.2e-16 ## alternative hypothesis: true mean is not equal to 0 ## 95 percent confidence interval: ## 6.936407 7.201093 ## sample estimates: ## mean of x ## 7.06875 ## ## One Sample t-test ## ## data: bw\)</span><code>Weight (pounds)</code></a></li>
<li class="chapter" data-level="5.27" data-path="one-sample-inference.html"><a href="one-sample-inference.html#t--3.4331-df-499-p-value-0.0003232"><i class="fa fa-check"></i><b>5.27</b> t = -3.4331, df = 499, p-value = 0.0003232</a></li>
<li class="chapter" data-level="5.28" data-path="one-sample-inference.html"><a href="one-sample-inference.html#alternative-hypothesis-true-mean-is-less-than-7.3"><i class="fa fa-check"></i><b>5.28</b> alternative hypothesis: true mean is less than 7.3</a></li>
<li class="chapter" data-level="5.29" data-path="one-sample-inference.html"><a href="one-sample-inference.html#percent-confidence-interval-1"><i class="fa fa-check"></i><b>5.29</b> 95 percent confidence interval:</a></li>
<li class="chapter" data-level="5.30" data-path="one-sample-inference.html"><a href="one-sample-inference.html#inf-7.179752"><i class="fa fa-check"></i><b>5.30</b> -Inf 7.179752</a></li>
<li class="chapter" data-level="5.31" data-path="one-sample-inference.html"><a href="one-sample-inference.html#sample-estimates-1"><i class="fa fa-check"></i><b>5.31</b> sample estimates:</a></li>
<li class="chapter" data-level="5.32" data-path="one-sample-inference.html"><a href="one-sample-inference.html#mean-of-x"><i class="fa fa-check"></i><b>5.32</b> mean of x</a></li>
<li class="chapter" data-level="5.33" data-path="one-sample-inference.html"><a href="one-sample-inference.html#section-44"><i class="fa fa-check"></i><b>5.33</b> 7.06875</a></li>
<li class="chapter" data-level="5.34" data-path="one-sample-inference.html"><a href="one-sample-inference.html#inferring-ice-break-up-in-nenana"><i class="fa fa-check"></i><b>5.34</b> Inferring ice break-up in Nenana</a></li>
<li class="chapter" data-level="5.35" data-path="one-sample-inference.html"><a href="one-sample-inference.html#parsed-with-column-specification-5"><i class="fa fa-check"></i><b>5.35</b> Parsed with column specification:</a></li>
<li class="chapter" data-level="5.36" data-path="one-sample-inference.html"><a href="one-sample-inference.html#cols-5"><i class="fa fa-check"></i><b>5.36</b> cols(</a></li>
<li class="chapter" data-level="5.37" data-path="one-sample-inference.html"><a href="one-sample-inference.html#year-col_integer"><i class="fa fa-check"></i><b>5.37</b> Year = col_integer(),</a></li>
<li class="chapter" data-level="5.38" data-path="one-sample-inference.html"><a href="one-sample-inference.html#juliandate-col_double"><i class="fa fa-check"></i><b>5.38</b> JulianDate = col_double(),</a></li>
<li class="chapter" data-level="5.39" data-path="one-sample-inference.html"><a href="one-sample-inference.html#datetime-col_character"><i class="fa fa-check"></i><b>5.39</b> <code>Date&amp;Time</code> = col_character()</a></li>
<li class="chapter" data-level="5.40" data-path="one-sample-inference.html"><a href="one-sample-inference.html#section-45"><i class="fa fa-check"></i><b>5.40</b> )</a></li>
<li class="chapter" data-level="5.41" data-path="one-sample-inference.html"><a href="one-sample-inference.html#section-46"><i class="fa fa-check"></i><b>5.41</b> </a></li>
<li class="chapter" data-level="5.42" data-path="one-sample-inference.html"><a href="one-sample-inference.html#one-sample-t-test-1"><i class="fa fa-check"></i><b>5.42</b> One Sample t-test</a></li>
<li class="chapter" data-level="5.43" data-path="one-sample-inference.html"><a href="one-sample-inference.html#section-47"><i class="fa fa-check"></i><b>5.43</b> </a></li>
<li class="chapter" data-level="5.44" data-path="one-sample-inference.html"><a href="one-sample-inference.html#data-juliandate"><i class="fa fa-check"></i><b>5.44</b> data: JulianDate</a></li>
<li class="chapter" data-level="5.45" data-path="one-sample-inference.html"><a href="one-sample-inference.html#t-197.41-df-86-p-value-2.2e-16"><i class="fa fa-check"></i><b>5.45</b> t = 197.41, df = 86, p-value &lt; 2.2e-16</a></li>
<li class="chapter" data-level="5.46" data-path="one-sample-inference.html"><a href="one-sample-inference.html#alternative-hypothesis-true-mean-is-not-equal-to-0"><i class="fa fa-check"></i><b>5.46</b> alternative hypothesis: true mean is not equal to 0</a></li>
<li class="chapter" data-level="5.47" data-path="one-sample-inference.html"><a href="one-sample-inference.html#percent-confidence-interval-2"><i class="fa fa-check"></i><b>5.47</b> 90 percent confidence interval:</a></li>
<li class="chapter" data-level="5.48" data-path="one-sample-inference.html"><a href="one-sample-inference.html#section-48"><i class="fa fa-check"></i><b>5.48</b> 124.4869 126.6018</a></li>
<li class="chapter" data-level="5.49" data-path="one-sample-inference.html"><a href="one-sample-inference.html#sample-estimates-2"><i class="fa fa-check"></i><b>5.49</b> sample estimates:</a></li>
<li class="chapter" data-level="5.50" data-path="one-sample-inference.html"><a href="one-sample-inference.html#mean-of-x-1"><i class="fa fa-check"></i><b>5.50</b> mean of x</a></li>
<li class="chapter" data-level="5.51" data-path="one-sample-inference.html"><a href="one-sample-inference.html#section-49"><i class="fa fa-check"></i><b>5.51</b> 125.5443</a></li>
<li class="chapter" data-level="5.52" data-path="one-sample-inference.html"><a href="one-sample-inference.html#section-50"><i class="fa fa-check"></i><b>5.52</b> </a></li>
<li class="chapter" data-level="5.53" data-path="one-sample-inference.html"><a href="one-sample-inference.html#one-sample-t-test-2"><i class="fa fa-check"></i><b>5.53</b> One Sample t-test</a></li>
<li class="chapter" data-level="5.54" data-path="one-sample-inference.html"><a href="one-sample-inference.html#section-51"><i class="fa fa-check"></i><b>5.54</b> </a></li>
<li class="chapter" data-level="5.55" data-path="one-sample-inference.html"><a href="one-sample-inference.html#data-juliandate-1"><i class="fa fa-check"></i><b>5.55</b> data: JulianDate</a></li>
<li class="chapter" data-level="5.56" data-path="one-sample-inference.html"><a href="one-sample-inference.html#t--7.0063-df-86-p-value-2.575e-10"><i class="fa fa-check"></i><b>5.56</b> t = -7.0063, df = 86, p-value = 2.575e-10</a></li>
<li class="chapter" data-level="5.57" data-path="one-sample-inference.html"><a href="one-sample-inference.html#alternative-hypothesis-true-mean-is-less-than-130"><i class="fa fa-check"></i><b>5.57</b> alternative hypothesis: true mean is less than 130</a></li>
<li class="chapter" data-level="5.58" data-path="one-sample-inference.html"><a href="one-sample-inference.html#percent-confidence-interval-3"><i class="fa fa-check"></i><b>5.58</b> 95 percent confidence interval:</a></li>
<li class="chapter" data-level="5.59" data-path="one-sample-inference.html"><a href="one-sample-inference.html#inf-126.6018"><i class="fa fa-check"></i><b>5.59</b> -Inf 126.6018</a></li>
<li class="chapter" data-level="5.60" data-path="one-sample-inference.html"><a href="one-sample-inference.html#sample-estimates-3"><i class="fa fa-check"></i><b>5.60</b> sample estimates:</a></li>
<li class="chapter" data-level="5.61" data-path="one-sample-inference.html"><a href="one-sample-inference.html#mean-of-x-2"><i class="fa fa-check"></i><b>5.61</b> mean of x</a></li>
<li class="chapter" data-level="5.62" data-path="one-sample-inference.html"><a href="one-sample-inference.html#section-52"><i class="fa fa-check"></i><b>5.62</b> 125.5443</a></li>
<li class="chapter" data-level="5.63" data-path="one-sample-inference.html"><a href="one-sample-inference.html#geom_smooth-using-method-loess-and-formula-y-x-1"><i class="fa fa-check"></i><b>5.63</b> <code>geom_smooth()</code> using method = ‘loess’ and formula ‘y ~ x’</a></li>
</ul></li>
<li class="divider"></li>
<li><a href="https://github.com/rstudio/bookdown" target="blank">Published with bookdown</a></li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Problems and Solutions in Applied Statistics</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="data-exploration" class="section level1">
<h1><span class="header-section-number">Chapter 4</span> Data exploration</h1>
<div class="sourceCode" id="cb1"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb1-1" data-line-number="1"><span class="kw">library</span>(tidyverse)</a></code></pre></div>
<pre><code>## ── Attaching packages ─────────────────────────────────────────────────────────────────────────────────────── tidyverse 1.2.1 ──</code></pre>
<pre><code>## ✔ ggplot2 3.0.0     ✔ purrr   0.2.5
## ✔ tibble  1.4.2     ✔ dplyr   0.7.6
## ✔ tidyr   0.8.1     ✔ stringr 1.3.1
## ✔ readr   1.1.1     ✔ forcats 0.3.0</code></pre>
<pre><code>## ── Conflicts ────────────────────────────────────────────────────────────────────────────────────────── tidyverse_conflicts() ──
## ✖ dplyr::filter() masks stats::filter()
## ✖ dplyr::lag()    masks stats::lag()</code></pre>
<div id="north-carolina-births" class="section level2">
<h2><span class="header-section-number">4.1</span> North Carolina births</h2>
<p>The data in file
<a href="http://www.utsc.utoronto.ca/~butler/c32/ncbirths.csv" class="uri">http://www.utsc.utoronto.ca/~butler/c32/ncbirths.csv</a> are about
500 randomly chosen births of babies in North Carolina. There is a lot
of information: not just the weight at birth of the baby, but whether
the baby was born prematurely, the ages of the parents, whether the
parents are married, how long (in weeks) the pregnancy lasted (this is
called the “gestation”) and so on.</p>
<ol style="list-style-type: lower-alpha">
<li>Read in the data from the file into R, bearing in mind what
type of file it is.</li>
</ol>
<p>Solution</p>
<p>This is a <code>.csv</code> file (it came from a spreadsheet), so it
needs reading in accordingly. Work directly from the URL (rather
than downloading the file, unless you are working offline):</p>
<div class="sourceCode" id="cb5"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb5-1" data-line-number="1">myurl=<span class="st">&quot;http://www.utsc.utoronto.ca/~butler/c32/ncbirths.csv&quot;</span></a>
<a class="sourceLine" id="cb5-2" data-line-number="2">bw=<span class="kw">read_csv</span>(myurl)</a></code></pre></div>
<pre><code>## Parsed with column specification:
## cols(
##   `Father Age` = col_integer(),
##   `Mother Age` = col_integer(),
##   `Weeks Gestation` = col_integer(),
##   `Pre-natal Visits` = col_integer(),
##   `Marital Status` = col_integer(),
##   `Mother Weight Gained` = col_integer(),
##   `Low Birthweight?` = col_integer(),
##   `Weight (pounds)` = col_double(),
##   `Premie?` = col_integer(),
##   `Few Visits?` = col_integer()
## )</code></pre>
<p>This shows you which variables the data set has (some of the names got
a bit mangled), and it shows you that they are all integers except for
the birth weight (a decimal number).</p>
<p>The easiest way to find out how many rows and columns there are is
simply to list the data frame:</p>
<div class="sourceCode" id="cb7"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb7-1" data-line-number="1">bw</a></code></pre></div>
<pre><code>## # A tibble: 500 x 10
##    `Father Age` `Mother Age` `Weeks Gestatio… `Pre-natal Visi…
##           &lt;int&gt;        &lt;int&gt;            &lt;int&gt;            &lt;int&gt;
##  1           27           26               38               14
##  2           35           33               40               11
##  3           34           22               37               10
##  4           NA           16               38                9
##  5           35           33               39               12
##  6           32           24               36               12
##  7           33           33               38               15
##  8           38           35               38               16
##  9           28           29               40                5
## 10           NA           19               34               10
## # ... with 490 more rows, and 6 more variables: `Marital Status` &lt;int&gt;,
## #   `Mother Weight Gained` &lt;int&gt;, `Low Birthweight?` &lt;int&gt;, `Weight
## #   (pounds)` &lt;dbl&gt;, `Premie?` &lt;int&gt;, `Few Visits?` &lt;int&gt;</code></pre>
<p>or you can take a “glimpse” of it:</p>
<div class="sourceCode" id="cb9"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb9-1" data-line-number="1"><span class="kw">glimpse</span>(bw)</a></code></pre></div>
<pre><code>## Observations: 500
## Variables: 10
## $ `Father Age`           &lt;int&gt; 27, 35, 34, NA, 35, 32, 33, 38, 28, NA,...
## $ `Mother Age`           &lt;int&gt; 26, 33, 22, 16, 33, 24, 33, 35, 29, 19,...
## $ `Weeks Gestation`      &lt;int&gt; 38, 40, 37, 38, 39, 36, 38, 38, 40, 34,...
## $ `Pre-natal Visits`     &lt;int&gt; 14, 11, 10, 9, 12, 12, 15, 16, 5, 10, 1...
## $ `Marital Status`       &lt;int&gt; 1, 1, 2, 2, 1, 1, 2, 1, 1, 2, 1, 1, 2, ...
## $ `Mother Weight Gained` &lt;int&gt; 32, 23, 50, NA, 15, 12, 60, 2, 20, NA, ...
## $ `Low Birthweight?`     &lt;int&gt; 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, ...
## $ `Weight (pounds)`      &lt;dbl&gt; 6.8750, 6.8125, 7.2500, 8.8125, 8.8125,...
## $ `Premie?`              &lt;int&gt; 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, ...
## $ `Few Visits?`          &lt;int&gt; 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, ...</code></pre>
<p>Either of these displays show that there are 500 rows (observations,
here births) and 10 columns (variables), and they both show what the
variables are called. So they’re both good as an answer to the
question.</p>
<p>What you’ll notice is that the variables have <em>spaces</em> in their
names, which will require special handling later. These outputs show
you what to do about those spaces in variable names: surround the
variable name with “backticks”. (On my keyboard, that’s on the key
to the left of number 1, where the squiggle is, that looks like a
backwards apostrophe. Probably next to <code>Esc</code>, depending on the
layout of your keyboard.)</p>
<p>Although almost all of the variables are stored as integers, the ones
that have a question mark in their name are actually “logical”, true
or false, with 1 denoting true and 0 false. We could convert them
later if we want to. (A question mark is not a traditional character
to put in a variable name, so we have to surround these variables with
backticks too.)</p>
<ol start="2" style="list-style-type: lower-alpha">
<li>From your output, verify that you have the
right number of observations and that you have several
variables. Which of your variables correspond to birthweight,
prematureness and length of pregnancy? (You might have to make guesses
based on the names of the variables.)</li>
</ol>
<p>Solution</p>
<p>I do indeed have 500 observations on 10 variables (“several”). (If
you don’t have several variables, check to see that you didn’t use
<code>read_delim</code> or something by mistake.) After the
“500 observations of 10 variables” line(s) in each case, you see all the
variables by name, with what type of values they have, and the first few of the
values.</p>
<p>The variable <code>Weight (pounds)</code> is the birthweight (in pounds),
<code>Premie?</code> is 1 for a premature baby and 0 for a full-term baby,
and <code>Weeks Gestation</code> is the number of weeks the pregnancy
lasted. Don’t forget to put backticks around each of those when
you use them
later.</p>
<ol start="3" style="list-style-type: lower-alpha">
<li>The theory behind the <span class="math inline">\(t\)</span>-test (which we do later) says that the
distribution of birth weights should be (approximately) normally
distributed. Obtain a histogram of the birth weights. Does it look
approximately normal? Comment briefly. (You’ll have to pick a number
of bins for your histogram first. I don’t mind very much what you
pick, as long as it’s not obviously too many or too few bins.)</li>
</ol>
<p>Solution</p>
<p>You’ll have seen that I often start with 10 bins, or maybe not quite
that many if I don’t have much data, and this is a decent general
principle. That would give</p>
<div class="sourceCode" id="cb11"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb11-1" data-line-number="1"><span class="kw">ggplot</span>(bw,<span class="kw">aes</span>(<span class="dt">x=</span><span class="st">`</span><span class="dt">Weight (pounds)</span><span class="st">`</span>))<span class="op">+</span><span class="kw">geom_histogram</span>(<span class="dt">bins=</span><span class="dv">10</span>)</a></code></pre></div>
<p><img src="03-data-summaries_files/figure-html/unnamed-chunk-10-1.png" width="672" /></p>
<p>which is perfectly acceptable. You can try something a bit more or a
bit less, and see how you like it in comparison. What you are looking
for is a nice clear picture of <em>shape</em>. If you have too few bins,
you’ll lose the shape:</p>
<div class="sourceCode" id="cb12"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb12-1" data-line-number="1"><span class="kw">ggplot</span>(bw,<span class="kw">aes</span>(<span class="dt">x=</span><span class="st">`</span><span class="dt">Weight (pounds)</span><span class="st">`</span>))<span class="op">+</span><span class="kw">geom_histogram</span>(<span class="dt">bins=</span><span class="dv">4</span>)</a></code></pre></div>
<p><img src="03-data-summaries_files/figure-html/unnamed-chunk-11-1.png" width="672" /></p>
<p>(is that leftmost bin an indication of skewness or some observations
that happen to be smallish?)</p>
<p>And if you have too many, the shape will be there, but
it will be hard to make out in all the noise, with frequencies going
up and down:</p>
<div class="sourceCode" id="cb13"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb13-1" data-line-number="1"><span class="kw">ggplot</span>(bw,<span class="kw">aes</span>(<span class="dt">x=</span><span class="st">`</span><span class="dt">Weight (pounds)</span><span class="st">`</span>))<span class="op">+</span><span class="kw">geom_histogram</span>(<span class="dt">bins=</span><span class="dv">30</span>)</a></code></pre></div>
<p><img src="03-data-summaries_files/figure-html/unnamed-chunk-12-1.png" width="672" /></p>
<p>I generally am fairly relaxed about the number of bins you use, as
long as it’s not clearly too few or too many. You might have done
exercises in the past that illustrate that the choice of number of
bins (or the class intervals where you move from one bin to the next,
which is another issue that I won’t explore here) can make an
appreciable difference to how a histogram looks.
Extra: I had some thoughts about this issue that I put in a blog
post, that you might like to read:
<a href="http://ritsokiguess.site/docs/2017/06/08/histograms-and-bins/" class="uri">http://ritsokiguess.site/docs/2017/06/08/histograms-and-bins/</a>. The
nice thing about Sturges’ rule, mentioned there, is that you can
almost get a number of bins for your histogram in your head (as long
as you know the powers of 2, that is). What you do is to start with
your sample size, here <span class="math inline">\(n=500\)</span>. You find the next power of 2 above
that, which is here <span class="math inline">\(512=2^9\)</span>. You then take that power and add 1,
to get 10 bins. If you don’t like that, you can get R to calculate
it for you:</p>
<div class="sourceCode" id="cb14"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb14-1" data-line-number="1"><span class="kw">nclass.Sturges</span>(bw<span class="op">$</span><span class="st">`</span><span class="dt">Weight (pounds)</span><span class="st">`</span>)</a></code></pre></div>
<pre><code>## [1] 10</code></pre>
<p>The place where Sturges’ rule comes from is an assumption of normal
data (actually a binomial approximation to the normal, backwards
though that sounds). If you have less than 30 observations, you’ll get
fewer than 6 bins, which won’t do much of a job of showing the
shape. Rob Hyndman wrote a
 about
Sturges’ rule in which he asserts that it is just plain wrong (if you
have taken B57, this note is very readable).</p>
<p>So what to use instead? Well, judgment is still better than something
automatic, but if you want a place to start from, something with a
better foundation than Sturges is the Freedman-Diaconis rule. This, in
its original formulation, gives a bin width rather than a number of bins:</p>
<p><span class="math display">\[ 
w=2(IQR)n^{-1/3}
\]</span></p>
<p>The nice thing about this is that it uses the interquartile range, so
it won’t be distorted by outliers. <code>geom_histogram</code> can take a
bin width, so we can use it as follows:</p>
<div class="sourceCode" id="cb16"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb16-1" data-line-number="1">w=<span class="dv">2</span><span class="op">*</span><span class="kw">IQR</span>(bw<span class="op">$</span><span class="st">`</span><span class="dt">Weight (pounds)</span><span class="st">`</span>)<span class="op">*</span><span class="dv">500</span><span class="op">^</span>(<span class="op">-</span><span class="dv">1</span><span class="op">/</span><span class="dv">3</span>)</a>
<a class="sourceLine" id="cb16-2" data-line-number="2">w</a></code></pre></div>
<pre><code>## [1] 0.4094743</code></pre>
<div class="sourceCode" id="cb18"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb18-1" data-line-number="1"><span class="kw">ggplot</span>(bw,<span class="kw">aes</span>(<span class="dt">x=</span><span class="st">`</span><span class="dt">Weight (pounds)</span><span class="st">`</span>))<span class="op">+</span><span class="kw">geom_histogram</span>(<span class="dt">binwidth=</span>w)</a></code></pre></div>
<p><img src="03-data-summaries_files/figure-html/unnamed-chunk-14-1.png" width="672" /></p>
<p>R also has</p>
<div class="sourceCode" id="cb19"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb19-1" data-line-number="1">nc=<span class="kw">nclass.FD</span>(bw<span class="op">$</span><span class="st">`</span><span class="dt">Weight (pounds)</span><span class="st">`</span>)</a>
<a class="sourceLine" id="cb19-2" data-line-number="2">nc</a></code></pre></div>
<pre><code>## [1] 26</code></pre>
<p>which turns the Freedman-Diaconis rule into a number of bins rather
than a binwidth; using that gives the same histogram as we got with <code>binwidth</code>.</p>
<p>In my opinion, Freedman-Diaconis tends to give too many bins (here
there are 26 rather than the 10 of Sturges). But I put it out there
for you to make your own call.</p>
<p>Another way to go is a “density plot”. This is a smoothed-out version of a histogram that is not obviously frequencies in bins, but which does have a theoretical basis. It goes something like this:</p>
<div class="sourceCode" id="cb21"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb21-1" data-line-number="1"><span class="kw">ggplot</span>(bw, <span class="kw">aes</span>(<span class="dt">x=</span><span class="st">`</span><span class="dt">Weight (pounds)</span><span class="st">`</span>))<span class="op">+</span><span class="kw">geom_density</span>()</a></code></pre></div>
<p><img src="03-data-summaries_files/figure-html/unnamed-chunk-16-1.png" width="672" /></p>
<p><code>geom_density</code> has an optional parameter that controls how smooth
or wiggly the picture is, but the default is usually good.</p>
<p>Alright, before we got distracted, we were assessing normality. What
about that?</p>
<p>It is mostly normal-looking, but I am suspicious about those
<em>very</em> low birth weights, the ones below about 4 pounds. There
are a few too many of those, as I see it.</p>
<p>If you think this is approximately normal, you need to make some
comment along the lines of ``the shape is approximately symmetric with
no outliers’’. I think my first answer is better, but this answer is
worth something, since it is a not completely unreasonable
interpretation of the histogram.</p>
<p>I have been making the distinction between a histogram (for one
quantitative variable) and side-by-side boxplots (for one quantitative
variable divided into groups by one categorical variable). When you
learned the boxplot, you probably learned it in the context of one
quantitative variable. You can draw a boxplot for that, too, but the
<code>ggplot</code> boxplot has an <code>x</code> as well as a
<code>y</code>. What you do to make a single boxplot is to set the
<code>x</code> equal 1, which produces a weird <span class="math inline">\(x\)</span>-axis (that you ignore):</p>
<div class="sourceCode" id="cb22"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb22-1" data-line-number="1"><span class="kw">ggplot</span>(bw,<span class="kw">aes</span>(<span class="dt">x=</span><span class="dv">1</span>,<span class="dt">y=</span><span class="st">`</span><span class="dt">Weight (pounds)</span><span class="st">`</span>))<span class="op">+</span><span class="kw">geom_boxplot</span>()</a></code></pre></div>
<p><img src="03-data-summaries_files/figure-html/unnamed-chunk-17-1.png" width="672" /></p>
<p>The high weight is actually an outlier, but look at all those outliers
at the bottom!</p>
<p><em>I</em> think the reason for those extra very low values is that they
are the premature births (that can result in <em>very</em> small
babies). Which leads to the additional question coming up.</p>
</div>
<div id="more-about-the-nc-births" class="section level2">
<h2><span class="header-section-number">4.2</span> More about the NC births</h2>
<p>This is an exploration of
some extra issues around the North Carolina births data set.</p>
<ol style="list-style-type: lower-alpha">
<li>How short does a pregnancy have to be, for the birth to be
classified as “premature”? Deduce this from the data, by drawing a
suitable graph or otherwise.</li>
</ol>
<p>Solution</p>
<p>To figure it out from the data, we can
see how <code>Weeks Gestation</code> depends
on <code>Premie?</code>. Some possibilities are boxplots or a
scatterplot. Either of the first two graphs would get full credit (for
the graphing part: you still have to do the explanation) if this
were being marked:</p>
<div class="sourceCode" id="cb23"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb23-1" data-line-number="1"><span class="kw">ggplot</span>(bw,<span class="kw">aes</span>(<span class="dt">x=</span><span class="kw">factor</span>(<span class="st">`</span><span class="dt">Premie?</span><span class="st">`</span>),<span class="dt">y=</span><span class="st">`</span><span class="dt">Weeks Gestation</span><span class="st">`</span>))<span class="op">+</span><span class="kw">geom_boxplot</span>()</a></code></pre></div>
<pre><code>## Warning: Removed 1 rows containing non-finite values (stat_boxplot).</code></pre>
<p><img src="03-data-summaries_files/figure-html/unnamed-chunk-18-1.png" width="672" /></p>
<p>The warning is because the prematurity of one of the babies is not known.
Or</p>
<div class="sourceCode" id="cb25"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb25-1" data-line-number="1"><span class="kw">ggplot</span>(bw,<span class="kw">aes</span>(<span class="dt">x=</span><span class="st">`</span><span class="dt">Premie?</span><span class="st">`</span>,<span class="dt">y=</span><span class="st">`</span><span class="dt">Weeks Gestation</span><span class="st">`</span>))<span class="op">+</span><span class="kw">geom_point</span>()</a></code></pre></div>
<pre><code>## Warning: Removed 1 rows containing missing values (geom_point).</code></pre>
<p><img src="03-data-summaries_files/figure-html/unnamed-chunk-19-1.png" width="672" /></p>
<p>The same warning again, for the same reason.</p>
<p>Notice how the graphs are similar in syntax, because the
what-to-plot is the same (apart from the <code>factor</code> thing) and we
just make a small change in
how-to-plot-it. In the boxplot, the thing on the <span class="math inline">\(x\)</span>-scale needs to be
categorical, and <code>Premie?</code> is actually a number, so we’d better
make it into a <code>factor</code>, which is R’s version of a categorical
variable.
<code>Premie.</code> is actually a categorical variable (“premature” or
“not premature”)
masquerading as a quantitative one (1 or 0). It is an “indicator variable”, if
you’re familiar with that term.</p>
<p>It looks as if the breakpoint is 37 weeks: a pregnancy at least that
long is considered normal, but a shorter one ends with a premature
birth. Both plots show the same thing: the `<code>Premie?</code>=1` births
all go with short pregnancies, shorter than 37 weeks. This is
completely clear cut.</p>
<p>Another way to attack this is to use <code>summarize</code>, finding the
max and min:</p>
<div class="sourceCode" id="cb27"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb27-1" data-line-number="1">bw <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">summarize</span>( <span class="dt">n=</span><span class="kw">n</span>(),</a>
<a class="sourceLine" id="cb27-2" data-line-number="2"><span class="dt">min=</span><span class="kw">min</span>(<span class="st">`</span><span class="dt">Weeks Gestation</span><span class="st">`</span>),</a>
<a class="sourceLine" id="cb27-3" data-line-number="3"><span class="dt">max=</span><span class="kw">max</span>(<span class="st">`</span><span class="dt">Weeks Gestation</span><span class="st">`</span>))</a></code></pre></div>
<pre><code>## # A tibble: 1 x 3
##       n   min   max
##   &lt;int&gt; &lt;dbl&gt; &lt;dbl&gt;
## 1   500    NA    NA</code></pre>
<p>only this is for <em>all</em> the babies, premature or not. So we want it by prematurity,
which means a <code>group_by</code> first:</p>
<div class="sourceCode" id="cb29"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb29-1" data-line-number="1">bw <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">group_by</span>(<span class="st">`</span><span class="dt">Premie?</span><span class="st">`</span>) <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb29-2" data-line-number="2"><span class="kw">summarize</span>( <span class="dt">n=</span><span class="kw">n</span>(),</a>
<a class="sourceLine" id="cb29-3" data-line-number="3"><span class="dt">min=</span><span class="kw">min</span>(<span class="st">`</span><span class="dt">Weeks Gestation</span><span class="st">`</span>),</a>
<a class="sourceLine" id="cb29-4" data-line-number="4"><span class="dt">max=</span><span class="kw">max</span>(<span class="st">`</span><span class="dt">Weeks Gestation</span><span class="st">`</span>))</a></code></pre></div>
<pre><code>## # A tibble: 3 x 4
##   `Premie?`     n   min   max
##       &lt;int&gt; &lt;int&gt; &lt;dbl&gt; &lt;dbl&gt;
## 1         0   424    37    45
## 2         1    75    20    36
## 3        NA     1    NA    NA</code></pre>
<p><code>group_by</code> with a number works, even though using the number
in <code>Premie?</code> in a boxplot didn’t. <code>group_by</code> just uses
the distinct values, whether they are numbers, text or factor levels.</p>
<p>Any of these graphs or summaries will help you answer the question, in
the same way. The ultimate issue here is ``something that will get the
job done’’: it doesn’t matter so much what.</p>
<p>In R, <code>NA</code> means “missing”. When you try to compute something
containing a missing value, the answer is usually missing (since you
don’t know what the missing value is). That’s why the first
<code>summarize</code> gave us missing values: there was one missing weeks
of gestation in with all the ones for which we had values, so the max
and min had to be missing as well. In the second <code>summarize</code>,
the one by whether a baby was born prematurely or not, we learn a bit
more about that missing <code>Premie?</code>: evidently its weeks of
gestation was missing as well, since the min and max of that were
missing.</p>
<p>Here’s that baby. I’m doing a bit of fiddling to show all the columns
(as rows, since there’s only one actual row). Don’t worry about the
second line of code below; we will investigate that later.</p>
<div class="sourceCode" id="cb31"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb31-1" data-line-number="1">bw <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">filter</span>(<span class="kw">is.na</span>(<span class="st">`</span><span class="dt">Premie?</span><span class="st">`</span>)) <span class="op">%&gt;%</span><span class="st"> </span></a>
<a class="sourceLine" id="cb31-2" data-line-number="2"><span class="kw">gather</span>(name,value,<span class="kw">everything</span>())</a></code></pre></div>
<pre><code>## # A tibble: 10 x 2
##    name                 value
##    &lt;chr&gt;                &lt;dbl&gt;
##  1 Father Age           33   
##  2 Mother Age           32   
##  3 Weeks Gestation      NA   
##  4 Pre-natal Visits      9   
##  5 Marital Status        1   
##  6 Mother Weight Gained 25   
##  7 Low Birthweight?      0   
##  8 Weight (pounds)       7.19
##  9 Premie?              NA   
## 10 Few Visits?           0</code></pre>
<p>The <em>only</em> thing that was missing was its weeks of gestation, but
that prevented anyone from figuring out whether it was premature or
not.</p>
<ol start="2" style="list-style-type: lower-alpha">
<li>Explore the relationship between birth weight and
length of pregancy (“gestation”) using a suitable graph. What do you
see?</li>
</ol>
<p>Solution</p>
<p>This needs
to be a scatterplot because these are both quantitative variables:</p>
<div class="sourceCode" id="cb33"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb33-1" data-line-number="1"><span class="kw">ggplot</span>(bw,<span class="kw">aes</span>(<span class="dt">x=</span><span class="st">`</span><span class="dt">Weeks Gestation</span><span class="st">`</span>,<span class="dt">y=</span><span class="st">`</span><span class="dt">Weight (pounds)</span><span class="st">`</span>))<span class="op">+</span><span class="kw">geom_point</span>()</a></code></pre></div>
<pre><code>## Warning: Removed 1 rows containing missing values (geom_point).</code></pre>
<p><img src="03-data-summaries_files/figure-html/unnamed-chunk-23-1.png" width="672" /></p>
<p>You see a rather clear upward trend. Those very underweight babies
came from very short pregnancies, but the vast majority of pregnancies
were of more or less normal length (40 weeks is normal) and resulted
in babies of more or less normal birth weight.</p>
<p>I want to illustrate something else: how about <em>colouring</em> the
births that were premature? Piece of cake with <code>ggplot</code>:</p>
<div class="sourceCode" id="cb35"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb35-1" data-line-number="1"><span class="kw">ggplot</span>(bw,<span class="kw">aes</span>(<span class="dt">x=</span><span class="st">`</span><span class="dt">Weeks Gestation</span><span class="st">`</span>,<span class="dt">y=</span><span class="st">`</span><span class="dt">Weight (pounds)</span><span class="st">`</span>,</a>
<a class="sourceLine" id="cb35-2" data-line-number="2"><span class="dt">colour=</span><span class="st">`</span><span class="dt">Premie?</span><span class="st">`</span>))<span class="op">+</span><span class="kw">geom_point</span>()</a></code></pre></div>
<pre><code>## Warning: Removed 1 rows containing missing values (geom_point).</code></pre>
<p><img src="03-data-summaries_files/figure-html/unnamed-chunk-24-1.png" width="672" /></p>
<p>That was rather silly because <code>ggplot</code> treated prematureness as a <em>continuous</em> variable, and plotted the values on a dark blue-light blue scale. This is the same issue as on the boxplot above, and has the same solution:</p>
<div class="sourceCode" id="cb37"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb37-1" data-line-number="1"><span class="kw">ggplot</span>(bw,<span class="kw">aes</span>(<span class="dt">x=</span><span class="st">`</span><span class="dt">Weeks Gestation</span><span class="st">`</span>,<span class="dt">y=</span><span class="st">`</span><span class="dt">Weight (pounds)</span><span class="st">`</span>,</a>
<a class="sourceLine" id="cb37-2" data-line-number="2"><span class="dt">colour=</span><span class="kw">factor</span>(<span class="st">`</span><span class="dt">Premie?</span><span class="st">`</span>)))<span class="op">+</span><span class="kw">geom_point</span>()</a></code></pre></div>
<pre><code>## Warning: Removed 1 rows containing missing values (geom_point).</code></pre>
<p><img src="03-data-summaries_files/figure-html/unnamed-chunk-25-1.png" width="672" /></p>
<p>Better.</p>
<p>With the normal-length pregnancies (red), there seems to be no
relationship between length of pregnancy and birth weight, just a
random variation. But with the premature births, a shorter pregnancy
typically goes with a <em>lower</em> birth weight. This would be why the
birth weights for the premature births were more variable.</p>
<ol start="3" style="list-style-type: lower-alpha">
<li>Do a web search to find the standard (North American)
definition of a premature birth. Does that correspond to what you saw
in the data? Cite the website you used, for example by saying
“according to <code>URL</code>, ldots”, with <code>URL</code> replaced by
the address of the website you found.</li>
</ol>
<p>Solution</p>
<p>The website <a href="http://www.mayoclinic.org/diseases-conditions/premature-birth/basics/definition/con-20020050" class="uri">http://www.mayoclinic.org/diseases-conditions/premature-birth/basics/definition/con-20020050</a>
says that ``a premature birth is one that occurs before the start of
the 37th week of pregnancy’’, which is exactly what we found. (Note
that I am citing the webpage on which I found this, and I even made it
into a link so that you can check it.) The Mayo Clinic is a famous
hospital system with locations in several US states, so I think we can
trust what its website says.</p>
</div>
<div id="nenana-alaska" class="section level2">
<h2><span class="header-section-number">4.3</span> Nenana, Alaska</h2>
<p>Nenana, Alaska, is about 50 miles west of Fairbanks.
Every spring, there is a contest in Nenana. A wooden tripod is
placed on the frozen river, and people try to guess the exact minute
when the ice melts enough for the tripod to fall through the ice. The
contest started in 1917 as an amusement for railway workers, and has
taken place every year since. Now, hundreds of thousands of people
enter their guesses on the Internet and the prize for the winner can
be as much as $300,000.</p>
<p>Because so much money is at stake, and because the exact same tripod
is placed at the exact same spot on the ice every year, the data are
consistent and accurate. The data are in
<a href="http://www.utsc.utoronto.ca/~butler/c32/nenana.txt" class="uri">http://www.utsc.utoronto.ca/~butler/c32/nenana.txt</a>.</p>
<ol style="list-style-type: lower-alpha">
<li>Read the data into R. Note that the values are
separated by <em>tabs</em> rather than spaces, so you’ll need an
appropriate <code>read\_</code> to read it in.</li>
</ol>
<p>Solution</p>
<p>These are “tab-separated values”, so <code>read\_tsv</code> is the
thing, as for the Australian athletes:</p>
<div class="sourceCode" id="cb39"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb39-1" data-line-number="1">myurl=<span class="st">&quot;http://www.utsc.utoronto.ca/~butler/c32/nenana.txt&quot;</span></a>
<a class="sourceLine" id="cb39-2" data-line-number="2">nenana=<span class="kw">read_tsv</span>(myurl)</a></code></pre></div>
<pre><code>## Parsed with column specification:
## cols(
##   Year = col_integer(),
##   JulianDate = col_double(),
##   `Date&amp;Time` = col_character()
## )</code></pre>
<p>Use whatever name you like for the data frame. One that is different
from any of the column headers is smart; then it is clear whether you
mean the whole data frame or one of its columns. <code>ice</code> or
<code>melt</code> or anything like that would also be good.</p>
<p>I haven’t asked you to display or check the data (that’s coming up),
but if you look at it and find that it didn’t work, you’ll know to
come back and try this part again. R usually gets it right or gives
you an error.</p>
<p>If you look at the data, they do appear to be separated by spaces, but
the text version of the date and time <em>also</em> have spaces in them,
so things might go astray if you try and read the values in without
recognizing that the actual separator is a tab:</p>
<div class="sourceCode" id="cb41"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb41-1" data-line-number="1">x=<span class="kw">read_delim</span>(myurl,<span class="st">&quot; &quot;</span>)</a></code></pre></div>
<pre><code>## Parsed with column specification:
## cols(
##   `Year  JulianDate  Date&amp;Time` = col_character()
## )</code></pre>
<pre><code>## Warning in rbind(names(probs), probs_f): number of columns of result is not
## a multiple of vector length (arg 1)</code></pre>
<pre><code>## Warning: 87 parsing failures.
## row # A tibble: 5 x 5 col     row col   expected  actual    file                                     expected   &lt;int&gt; &lt;chr&gt; &lt;chr&gt;     &lt;chr&gt;     &lt;chr&gt;                                    actual 1     1 &lt;NA&gt;  1 columns 5 columns &#39;http://www.utsc.utoronto.ca/~butler/c3… file 2     2 &lt;NA&gt;  1 columns 5 columns &#39;http://www.utsc.utoronto.ca/~butler/c3… row 3     3 &lt;NA&gt;  1 columns 5 columns &#39;http://www.utsc.utoronto.ca/~butler/c3… col 4     4 &lt;NA&gt;  1 columns 5 columns &#39;http://www.utsc.utoronto.ca/~butler/c3… expected 5     5 &lt;NA&gt;  1 columns 5 columns &#39;http://www.utsc.utoronto.ca/~butler/c3…
## ... ................. ... .......................................................................... ........ .......................................................................... ...... .......................................................................... .... .......................................................................... ... .......................................................................... ... .......................................................................... ........ ..........................................................................
## See problems(...) for more details.</code></pre>
<p>Ouch! A hint as to what went wrong comes from looking at the read-in
data frame:</p>
<div class="sourceCode" id="cb45"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb45-1" data-line-number="1">x</a></code></pre></div>
<pre><code>## # A tibble: 87 x 1
##    `Year\tJulianDate\tDate&amp;Time`
##    &lt;chr&gt;                        
##  1 &quot;1917\t120.4795\tApril&quot;      
##  2 &quot;1918\t131.3983\tMay&quot;        
##  3 &quot;1919\t123.6066\tMay&quot;        
##  4 &quot;1920\t132.4490\tMay&quot;        
##  5 &quot;1921\t131.2795\tMay&quot;        
##  6 &quot;1922\t132.5559\tMay&quot;        
##  7 &quot;1923\t129.0837\tMay&quot;        
##  8 &quot;1924\t132.6323\tMay&quot;        
##  9 &quot;1925\t127.7726\tMay&quot;        
## 10 &quot;1926\t116.6691\tApril&quot;      
## # ... with 77 more rows</code></pre>
<p>Those “= symbols mean ``tab character”, which is our hint that
the values were separated by tabs rather than spaces.</p>
<p>More detail (if you can bear to see it) is here:</p>
<div class="sourceCode" id="cb47"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb47-1" data-line-number="1"><span class="kw">problems</span>(x)</a></code></pre></div>
<pre><code>## # A tibble: 87 x 5
##      row col   expected  actual   file                                    
##    &lt;int&gt; &lt;chr&gt; &lt;chr&gt;     &lt;chr&gt;    &lt;chr&gt;                                   
##  1     1 &lt;NA&gt;  1 columns 5 colum… &#39;http://www.utsc.utoronto.ca/~butler/c3…
##  2     2 &lt;NA&gt;  1 columns 5 colum… &#39;http://www.utsc.utoronto.ca/~butler/c3…
##  3     3 &lt;NA&gt;  1 columns 5 colum… &#39;http://www.utsc.utoronto.ca/~butler/c3…
##  4     4 &lt;NA&gt;  1 columns 5 colum… &#39;http://www.utsc.utoronto.ca/~butler/c3…
##  5     5 &lt;NA&gt;  1 columns 5 colum… &#39;http://www.utsc.utoronto.ca/~butler/c3…
##  6     6 &lt;NA&gt;  1 columns 5 colum… &#39;http://www.utsc.utoronto.ca/~butler/c3…
##  7     7 &lt;NA&gt;  1 columns 5 colum… &#39;http://www.utsc.utoronto.ca/~butler/c3…
##  8     8 &lt;NA&gt;  1 columns 5 colum… &#39;http://www.utsc.utoronto.ca/~butler/c3…
##  9     9 &lt;NA&gt;  1 columns 5 colum… &#39;http://www.utsc.utoronto.ca/~butler/c3…
## 10    10 &lt;NA&gt;  1 columns 5 colum… &#39;http://www.utsc.utoronto.ca/~butler/c3…
## # ... with 77 more rows</code></pre>
<p>The first line of the data file (with the variable names in it) had no
spaces, only tabs, so <code>read\_delim</code> thinks there is <em>one</em>
column with a very long name, but in the actual data, there are
<em>five</em> space-separated columns. The text date-times are of the
form “April 30 at 11:30 AM”, which, if you think it’s all separated
by spaces, is actually 5 things: April, 30, at and so on. These are
the only things that are separated by spaces, so, from that point of
view, there are five columns.</p>
<ol start="2" style="list-style-type: lower-alpha">
<li>Find a way of displaying how many rows and columns your
data frame has, and some of the values. Describe the first and last
of the variables that
you appear to have.</li>
</ol>
<p>Solution</p>
<p>The easiest is just to display the tibble:</p>
<div class="sourceCode" id="cb49"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb49-1" data-line-number="1">nenana</a></code></pre></div>
<pre><code>## # A tibble: 87 x 3
##     Year JulianDate `Date&amp;Time`         
##    &lt;int&gt;      &lt;dbl&gt; &lt;chr&gt;               
##  1  1917       120. April 30 at 11:30 AM
##  2  1918       131. May 11 at 9:33 AM   
##  3  1919       124. May 3 at 2:33 PM    
##  4  1920       132. May 11 at 10:46 AM  
##  5  1921       131. May 11 at 6:42 AM   
##  6  1922       133. May 12 at 1:20 PM   
##  7  1923       129. May 9 at 2:00 AM    
##  8  1924       133. May 11 at 3:10 PM   
##  9  1925       128. May 7 at 6:32 PM    
## 10  1926       117. April 26 at 4:03 PM 
## # ... with 77 more rows</code></pre>
<p>Alternatively, you can take a <code>glimpse</code> of it:</p>
<div class="sourceCode" id="cb51"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb51-1" data-line-number="1"><span class="kw">glimpse</span>(nenana)</a></code></pre></div>
<pre><code>## Observations: 87
## Variables: 3
## $ Year        &lt;int&gt; 1917, 1918, 1919, 1920, 1921, 1922, 1923, 1924, 19...
## $ JulianDate  &lt;dbl&gt; 120.4795, 131.3983, 123.6066, 132.4490, 131.2795, ...
## $ `Date&amp;Time` &lt;chr&gt; &quot;April 30 at 11:30 AM&quot;, &quot;May 11 at 9:33 AM&quot;, &quot;May ...</code></pre>
<p>There are 87 years, and 3 columns (variables).
The first column is year, and the last
column is the date and time that the tripod fell into the river,
written as a piece of text. I explain the second column in a moment.</p>
<ol start="3" style="list-style-type: lower-alpha">
<li>Dates and times are awkward to handle with software. (We
see more ways later in the course.) The column <code>JulianDate</code>
expresses the time that the tripod fell through the ice as a
fractional number of days since December 31. This enables the time
(as a fraction of the way through the day) to be recorded as well,
the whole thing being an ordinary number.
Make a histogram of the Julian dates. Comment briefly on its shape.</li>
</ol>
<p>Solution</p>
<p>With a <code>ggplot</code> histogram, we need a number of bins
first. I can do Sturges’ rule in my head: the next power of 2 up
from 87 (our <span class="math inline">\(n\)</span>) is 128, which is <span class="math inline">\(2^7\)</span>, so the base 2 log of
87 rounds up to 7. That plus one is 8, so we need 8 bins. For
you, any not-insane number of bins will do, or any not-insane
bin width, if you want to go that way:</p>
<div class="sourceCode" id="cb53"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb53-1" data-line-number="1"><span class="kw">ggplot</span>(nenana,<span class="kw">aes</span>(<span class="dt">x=</span>JulianDate))<span class="op">+</span><span class="kw">geom_histogram</span>(<span class="dt">bins=</span><span class="dv">8</span>)</a></code></pre></div>
<p><img src="03-data-summaries_files/figure-html/unnamed-chunk-32-1.png" width="672" /></p>
<p>Note that you need to type <code>JulianDate</code> exactly as it
appears, capital letters and all. R is case-sensitive.</p>
<p>This histogram looks more or less symmetric (and, indeed, normal). I
really don’t think you can justify an answer other than “symmetric”
here. (Or “approximately normal”: that’s good too.) If your
histogram is different, say so. I think that “hole” in the middle is
not especially important.</p>
<p>We haven’t done normal quantile plots yet, but looking ahead:</p>
<div class="sourceCode" id="cb54"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb54-1" data-line-number="1"><span class="kw">ggplot</span>(nenana, <span class="kw">aes</span>(<span class="dt">sample=</span>JulianDate))<span class="op">+</span><span class="kw">stat_qq</span>()<span class="op">+</span><span class="kw">stat_qq_line</span>()</a></code></pre></div>
<p><img src="03-data-summaries_files/figure-html/unnamed-chunk-33-1.png" width="672" /></p>
<p>That hugs the line pretty well, so I would call it close to
normally-distributed. It bulges away from the line because there are
more values just below 120 than you would expect for a
normal. This corresponds to the histogram bar centred just below 120
being taller than you would have expected.</p>
<p>Extra: looking <em>way</em> ahead (to almost the end of the R stuff),
this is how you handle the dates and times:</p>
<div class="sourceCode" id="cb55"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb55-1" data-line-number="1"><span class="kw">library</span>(lubridate)</a></code></pre></div>
<pre><code>## 
## Attaching package: &#39;lubridate&#39;</code></pre>
<pre><code>## The following object is masked from &#39;package:base&#39;:
## 
##     date</code></pre>
<div class="sourceCode" id="cb58"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb58-1" data-line-number="1">nenana <span class="op">%&gt;%</span><span class="st"> </span></a>
<a class="sourceLine" id="cb58-2" data-line-number="2"><span class="kw">mutate</span>(<span class="dt">longdt=</span><span class="kw">str_c</span>(Year,<span class="st">&quot; &quot;</span>,<span class="st">`</span><span class="dt">Date&amp;Time</span><span class="st">`</span>)) <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb58-3" data-line-number="3"><span class="kw">mutate</span>(<span class="dt">datetime=</span><span class="kw">ymd_hm</span>(longdt,<span class="dt">tz=</span><span class="st">&quot;America/Anchorage&quot;</span>))</a></code></pre></div>
<pre><code>## # A tibble: 87 x 5
##     Year JulianDate `Date&amp;Time`       longdt           datetime           
##    &lt;int&gt;      &lt;dbl&gt; &lt;chr&gt;             &lt;chr&gt;            &lt;dttm&gt;             
##  1  1917       120. April 30 at 11:3… 1917 April 30 a… 1917-04-30 11:30:00
##  2  1918       131. May 11 at 9:33 AM 1918 May 11 at … 1918-05-11 09:33:00
##  3  1919       124. May 3 at 2:33 PM  1919 May 3 at 2… 1919-05-03 14:33:00
##  4  1920       132. May 11 at 10:46 … 1920 May 11 at … 1920-05-11 10:46:00
##  5  1921       131. May 11 at 6:42 AM 1921 May 11 at … 1921-05-11 06:42:00
##  6  1922       133. May 12 at 1:20 PM 1922 May 12 at … 1922-05-12 13:20:00
##  7  1923       129. May 9 at 2:00 AM  1923 May 9 at 2… 1923-05-09 02:00:00
##  8  1924       133. May 11 at 3:10 PM 1924 May 11 at … 1924-05-11 15:10:00
##  9  1925       128. May 7 at 6:32 PM  1925 May 7 at 6… 1925-05-07 18:32:00
## 10  1926       117. April 26 at 4:03… 1926 April 26 a… 1926-04-26 16:03:00
## # ... with 77 more rows</code></pre>
<p>I am not doing any further analysis with these, so just displaying them is good.</p>
<p>I have to do a preliminary step to get the date-times <em>with</em> their year in one place. <code>str_c- glues pieces of text together: in this case, the year, a space, and then the rest of the</code>Date&amp;Time-. I stored this in <code>longdt-. The second</code>mutate- is the business end of it: <code>ymd_hm- takes a piece of text containing a year, month (by name or number), day, hours, minutes *in that order*, and extracts those things from it, storing the whole thing as an R date-time. Note that the AM/PM was handled properly. The benefit of doing that is we can extract anything from the dates, such as the month or day of week, or take differences between the dates. Or even check that the Julian dates were calculated correctly (the</code>lubridate- function is called ``yday- for “day of year”):</p>
<div class="sourceCode" id="cb60"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb60-1" data-line-number="1">nenana <span class="op">%&gt;%</span><span class="st"> </span></a>
<a class="sourceLine" id="cb60-2" data-line-number="2"><span class="kw">mutate</span>(<span class="dt">longdt=</span><span class="kw">str_c</span>(Year,<span class="st">&quot; &quot;</span>,<span class="st">`</span><span class="dt">Date&amp;Time</span><span class="st">`</span>)) <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb60-3" data-line-number="3"><span class="kw">mutate</span>(<span class="dt">datetime=</span><span class="kw">ymd_hm</span>(longdt,<span class="dt">tz=</span><span class="st">&quot;America/Anchorage&quot;</span>)) <span class="op">%&gt;%</span><span class="st"> </span></a>
<a class="sourceLine" id="cb60-4" data-line-number="4"><span class="kw">mutate</span>(<span class="dt">jd=</span><span class="kw">yday</span>(datetime)) -&gt;</a>
<a class="sourceLine" id="cb60-5" data-line-number="5">nenana2</a>
<a class="sourceLine" id="cb60-6" data-line-number="6">nenana2 <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">select</span>(JulianDate,jd,datetime)</a></code></pre></div>
<pre><code>## # A tibble: 87 x 3
##    JulianDate    jd datetime           
##         &lt;dbl&gt; &lt;dbl&gt; &lt;dttm&gt;             
##  1       120.   120 1917-04-30 11:30:00
##  2       131.   131 1918-05-11 09:33:00
##  3       124.   123 1919-05-03 14:33:00
##  4       132.   132 1920-05-11 10:46:00
##  5       131.   131 1921-05-11 06:42:00
##  6       133.   132 1922-05-12 13:20:00
##  7       129.   129 1923-05-09 02:00:00
##  8       133.   132 1924-05-11 15:10:00
##  9       128.   127 1925-05-07 18:32:00
## 10       117.   116 1926-04-26 16:03:00
## # ... with 77 more rows</code></pre>
<p>Hmm, some of those are off by one. What do the off-by-one ones have in common? Let’s look at more of them. ``round- rounds off to the nearest integer (since these are actually decimal numbers):</p>
<div class="sourceCode" id="cb62"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb62-1" data-line-number="1">nenana2 <span class="op">%&gt;%</span><span class="st"> </span></a>
<a class="sourceLine" id="cb62-2" data-line-number="2"><span class="kw">filter</span>(<span class="kw">round</span>(JulianDate) <span class="op">!=</span><span class="st"> </span><span class="kw">round</span>(jd)) <span class="op">%&gt;%</span><span class="st"> </span></a>
<a class="sourceLine" id="cb62-3" data-line-number="3"><span class="kw">select</span>(JulianDate,jd,datetime)</a></code></pre></div>
<pre><code>## # A tibble: 61 x 3
##    JulianDate    jd datetime           
##         &lt;dbl&gt; &lt;dbl&gt; &lt;dttm&gt;             
##  1       124.   123 1919-05-03 14:33:00
##  2       133.   132 1922-05-12 13:20:00
##  3       133.   132 1924-05-11 15:10:00
##  4       128.   127 1925-05-07 18:32:00
##  5       117.   116 1926-04-26 16:03:00
##  6       128.   127 1928-05-06 16:25:00
##  7       126.   125 1929-05-05 15:41:00
##  8       129.   128 1930-05-08 19:03:00
##  9       129.   128 1933-05-08 19:30:00
## 10       121.   120 1934-04-30 14:07:00
## # ... with 51 more rows</code></pre>
<p>The ones shown here are all <em>after noon</em>, and the Julian date in
the data file appears as one more than the one calculated by
<code>lubridate-. What has actually happened is a quirk of how tibbles are displayed: they show 3 significant digits, *rounded*. The Julian dates given by</code>yday- are the whole-number part, so the
ones in the data value are that plus more than 0.5, which will round
<em>up</em>. The first line of code below displays 6 significant digits
rather than only three:</p>
<div class="sourceCode" id="cb64"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb64-1" data-line-number="1"><span class="kw">options</span>(<span class="dt">pillar.sigfig=</span><span class="dv">6</span>)</a>
<a class="sourceLine" id="cb64-2" data-line-number="2">nenana2 <span class="op">%&gt;%</span><span class="st"> </span></a>
<a class="sourceLine" id="cb64-3" data-line-number="3"><span class="kw">filter</span>(<span class="kw">round</span>(JulianDate) <span class="op">!=</span><span class="st"> </span><span class="kw">round</span>(jd)) <span class="op">%&gt;%</span><span class="st"> </span></a>
<a class="sourceLine" id="cb64-4" data-line-number="4"><span class="kw">select</span>(JulianDate,jd,datetime)</a></code></pre></div>
<pre><code>## # A tibble: 61 x 3
##    JulianDate    jd datetime           
##         &lt;dbl&gt; &lt;dbl&gt; &lt;dttm&gt;             
##  1    123.607   123 1919-05-03 14:33:00
##  2    132.556   132 1922-05-12 13:20:00
##  3    132.632   132 1924-05-11 15:10:00
##  4    127.773   127 1925-05-07 18:32:00
##  5    116.669   116 1926-04-26 16:03:00
##  6    127.684   127 1928-05-06 16:25:00
##  7    125.654   125 1929-05-05 15:41:00
##  8    128.794   128 1930-05-08 19:03:00
##  9    128.813   128 1933-05-08 19:30:00
## 10    120.588   120 1934-04-30 14:07:00
## # ... with 51 more rows</code></pre>
<p>Displaying more decimals shows that I was right: <code>jd- is (to this accuracy) a whole number, but</code>JulianDate- is a decimal with fractional part greater than 0.50.</p>
<p>Now I have to turn the extra signficant digits off:</p>
<div class="sourceCode" id="cb66"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb66-1" data-line-number="1"><span class="kw">options</span>(<span class="dt">pillar.sigfig=</span><span class="dv">3</span>)</a></code></pre></div>
<ol start="4" style="list-style-type: lower-alpha">
<li>Plot <code>JulianDate</code> against <code>Year</code> on a
scatterplot. What recent trends, if any, do you see? Comment briefly.</li>
</ol>
<p>Solution</p>
<p>``geom_point+:</p>
<div class="sourceCode" id="cb67"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb67-1" data-line-number="1"><span class="kw">ggplot</span>(nenana,<span class="kw">aes</span>(<span class="dt">x=</span>Year,<span class="dt">y=</span>JulianDate))<span class="op">+</span><span class="kw">geom_point</span>()</a></code></pre></div>
<p><img src="03-data-summaries_files/figure-html/unnamed-chunk-39-1.png" width="672" />
This is actually a small-but-real downward trend, especially since
about 1960,
but the large amount
of variability makes it hard to see, so I’m good with either ``no
trend’’ or “weak downward trend”
or anything roughly like that. There is definitely not much trend
before 1960, but most of the really early break-ups (less than about
118) have been since about 1990.</p>
<p>You can even add to the <code>ggplot</code>, by putting a smooth trend on it:</p>
<div class="sourceCode" id="cb68"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb68-1" data-line-number="1"><span class="kw">ggplot</span>(nenana,<span class="kw">aes</span>(<span class="dt">x=</span>Year,<span class="dt">y=</span>JulianDate))<span class="op">+</span><span class="kw">geom_point</span>()<span class="op">+</span><span class="kw">geom_smooth</span>()</a></code></pre></div>
<pre><code>## `geom_smooth()` using method = &#39;loess&#39; and formula &#39;y ~ x&#39;</code></pre>
<p><img src="03-data-summaries_files/figure-html/unnamed-chunk-40-1.png" width="672" /></p>
<p>This is R’s version of a trend that is not constrained
to be linear (so that it “lets the data speak for itself”).</p>
<p>Now there is something obvious to see: after about 1960, there is a clear
downward trend: the ice is breaking up earlier on average every
year. Even though there is a lot of variability, the overall trend,
viewed this way, is clear.</p>
<p>What does this mean, in practice? This notion of the ice melting
earlier than it used to is consistent all over the Arctic, and is one
more indication of climate change. Precisely, it is an indication that
climate change is happening, but we would have to delve further to
make any statements about the <em>cause</em> of that climate change.</p>
</div>
<div id="computerized-accounting" class="section level2">
<h2><span class="header-section-number">4.4</span> Computerized accounting</h2>
<p>Beginning accounting students need to
learn to learn to audit in a computerized environment. A sample of
beginning accounting students took each of two tests: the Computer
Attitude Scale (CAS) and the Computer Anxiety Rating Scale (CARS). A
higher score in each indicates greater anxiety around computers. The test scores are scaled to be between 0 and 5. Also
noted was each student’s gender. The data are in
<a href="http://www.utsc.utoronto.ca/~butler/c32/compatt.txt" class="uri">http://www.utsc.utoronto.ca/~butler/c32/compatt.txt</a>. The data values are separated by spaces.</p>
<ol style="list-style-type: lower-alpha">
<li>Read the data into R. Do you have what you expected? Explain briefly.</li>
</ol>
<p>Solution</p>
<p>Read in and display the data. This, I think, is the easiest way.</p>
<div class="sourceCode" id="cb70"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb70-1" data-line-number="1">url=<span class="st">&quot;http://www.utsc.utoronto.ca/~butler/c32/compatt.txt&quot;</span></a>
<a class="sourceLine" id="cb70-2" data-line-number="2">anxiety=<span class="kw">read_delim</span>(url,<span class="st">&quot; &quot;</span>)</a></code></pre></div>
<pre><code>## Parsed with column specification:
## cols(
##   gender = col_character(),
##   CAS = col_double(),
##   CARS = col_double()
## )</code></pre>
<div class="sourceCode" id="cb72"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb72-1" data-line-number="1">anxiety</a></code></pre></div>
<pre><code>## # A tibble: 35 x 3
##    gender   CAS  CARS
##    &lt;chr&gt;  &lt;dbl&gt; &lt;dbl&gt;
##  1 female  2.85  2.9 
##  2 male    2.6   2.32
##  3 female  2.2   1   
##  4 male    2.65  2.58
##  5 male    2.6   2.58
##  6 male    3.2   3.05
##  7 male    3.65  3.74
##  8 female  2.55  1.9 
##  9 male    3.15  3.32
## 10 male    2.8   2.74
## # ... with 25 more rows</code></pre>
<p>There is a total of 35 students with a CAS score, a CARS score and a
gender recorded for each. This is in line with what I was
expecting. (You can also note that the genders appear to be a mixture
of males and females.)</p>
<ol start="2" style="list-style-type: lower-alpha">
<li>How many males and females were there in the sample?</li>
</ol>
<p>Solution</p>
<p>Most easily <code>count</code>:</p>
<div class="sourceCode" id="cb74"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb74-1" data-line-number="1">anxiety <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">count</span>(gender)</a></code></pre></div>
<pre><code>## # A tibble: 2 x 2
##   gender     n
##   &lt;chr&gt;  &lt;int&gt;
## 1 female    15
## 2 male      20</code></pre>
<p>This also works (and is therefore good):</p>
<div class="sourceCode" id="cb76"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb76-1" data-line-number="1">anxiety <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">group_by</span>(gender) <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">summarize</span>(<span class="dt">count=</span><span class="kw">n</span>())</a></code></pre></div>
<pre><code>## # A tibble: 2 x 2
##   gender count
##   &lt;chr&gt;  &lt;int&gt;
## 1 female    15
## 2 male      20</code></pre>
<p>I want you to use R to do the counting (that is, don’t just list out
the whole data set with <code>print(n=Inf)</code> and count the males and
females yourself). This is because you might have thousands of data
values and you need to learn how to get R (or, later, SAS) to count them for
you.</p>
<p>15 females and 20 males, <em>which you should say</em>. I made a point
of <em>not</em> saying that it is enough to get the output with the
answers on it, so you need to tell me what the answer is.</p>
<ol start="3" style="list-style-type: lower-alpha">
<li>Do the CAS scores tend to be higher for females or for males? Draw a suitable graph to help you decide, and come to a conclusion.</li>
</ol>
<p>Solution</p>
<p>Gender is categorical and CAS score is quantitative, so a boxplot would appear to be the thing:</p>
<div class="sourceCode" id="cb78"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb78-1" data-line-number="1"><span class="kw">ggplot</span>(anxiety,<span class="kw">aes</span>(<span class="dt">x=</span>gender,<span class="dt">y=</span>CAS))<span class="op">+</span><span class="kw">geom_boxplot</span>()</a></code></pre></div>
<p><img src="03-data-summaries_files/figure-html/unnamed-chunk-44-1.png" width="672" /></p>
<p>The median for males is slightly higher, so male accountants are more anxious around computers than female accountants are.</p>
<p>If you wish, side-by-side (or, better, above-and-below) histograms
would also work:</p>
<div class="sourceCode" id="cb79"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb79-1" data-line-number="1"><span class="kw">ggplot</span>(anxiety,<span class="kw">aes</span>(<span class="dt">x=</span>CAS))<span class="op">+</span><span class="kw">geom_histogram</span>(<span class="dt">bins=</span><span class="dv">6</span>)<span class="op">+</span></a>
<a class="sourceLine" id="cb79-2" data-line-number="2"><span class="kw">facet_wrap</span>(<span class="op">~</span>gender,<span class="dt">ncol=</span><span class="dv">1</span>)</a></code></pre></div>
<p><img src="03-data-summaries_files/figure-html/unnamed-chunk-45-1.png" width="672" /></p>
<p>If you go this way, you have to make a call about where the centres of the histograms are. I guess the male one is slightly further to the right, but it’s not so easy to tell. (Make a call.)</p>
<ol start="4" style="list-style-type: lower-alpha">
<li>Find the median CAS scores for each gender. Does this support what you saw on your plot? Explain briefly.</li>
</ol>
<p>Solution</p>
<p>Group-by and summarize:</p>
<div class="sourceCode" id="cb80"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb80-1" data-line-number="1">anxiety <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">group_by</span>(gender) <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">summarize</span>(<span class="dt">med=</span><span class="kw">median</span>(CAS))</a></code></pre></div>
<pre><code>## # A tibble: 2 x 2
##   gender   med
##   &lt;chr&gt;  &lt;dbl&gt;
## 1 female  2.55
## 2 male    2.85</code></pre>
<p>The median is a bit higher for males, which is what I got on my
boxplot (and is apparently the same thing as is on the histograms, but
it’s harder to be sure there).</p>
<ol start="5" style="list-style-type: lower-alpha">
<li>Find the mean and standard deviation of both CAS and CARS scores (for all the students combined, ie. not separated by gender) <em>without</em> naming those columns explicitly.</li>
</ol>
<p>Solution</p>
<p>Without naming them explicitly means using some other way to pick them out of the data frame, either <code>summarize\_if</code> or <code>summarize\_at</code>. To do it the first way, ask what these two columns have in common: they are the only two numeric (quantitative) columns:</p>
<div class="sourceCode" id="cb82"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb82-1" data-line-number="1">anxiety <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">summarize_if</span>(is.numeric,<span class="kw">funs</span>(mean,sd))</a></code></pre></div>
<pre><code>## # A tibble: 1 x 4
##   CAS_mean CARS_mean CAS_sd CARS_sd
##      &lt;dbl&gt;     &lt;dbl&gt;  &lt;dbl&gt;   &lt;dbl&gt;
## 1     2.82      2.77  0.484   0.671</code></pre>
<p>Or the second way, asking yourself what the <em>names</em> of those columns have in common: they start with C and the gender column doesn’t:</p>
<div class="sourceCode" id="cb84"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb84-1" data-line-number="1">anxiety <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">summarize_at</span>(<span class="kw">vars</span>(<span class="kw">starts_with</span>(<span class="st">&quot;C&quot;</span>)),<span class="kw">funs</span>(mean,sd))</a></code></pre></div>
<pre><code>## # A tibble: 1 x 4
##   CAS_mean CARS_mean CAS_sd CARS_sd
##      &lt;dbl&gt;     &lt;dbl&gt;  &lt;dbl&gt;   &lt;dbl&gt;
## 1     2.82      2.77  0.484   0.671</code></pre>
<p>Either of these is good, or anything equivalent (like noting that the two anxiety scales both <code>ends\_with</code> S):</p>
<div class="sourceCode" id="cb86"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb86-1" data-line-number="1">anxiety <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">summarize_at</span>(<span class="kw">vars</span>(<span class="kw">ends_with</span>(<span class="st">&quot;S&quot;</span>)),<span class="kw">funs</span>(mean,sd))</a></code></pre></div>
<pre><code>## # A tibble: 1 x 4
##   CAS_mean CARS_mean CAS_sd CARS_sd
##      &lt;dbl&gt;     &lt;dbl&gt;  &lt;dbl&gt;   &lt;dbl&gt;
## 1     2.82      2.77  0.484   0.671</code></pre>
<p>Because I didn’t say otherwise, you should tell me what the means and SDs are, rounding off suitably: the CAS scores have mean 2.82 and SD 0.48, and the CARS scores have mean 2.77 and SD 0.67.</p>
<p>Yet another way to do it is to select the columns you want first (which
you can do by number so as not to name them), and then find the mean
and SD of all of them. This uses two tools that we haven’t seen yet:</p>
<div class="sourceCode" id="cb88"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb88-1" data-line-number="1">anxiety <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">select</span>(<span class="dv">2</span><span class="op">:</span><span class="dv">3</span>) <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">summarize_all</span>(<span class="kw">funs</span>(mean,sd))</a></code></pre></div>
<pre><code>## # A tibble: 1 x 4
##   CAS_mean CARS_mean CAS_sd CARS_sd
##      &lt;dbl&gt;     &lt;dbl&gt;  &lt;dbl&gt;   &lt;dbl&gt;
## 1     2.82      2.77  0.484   0.671</code></pre>
<p>This doesn’t work:</p>
<div class="sourceCode" id="cb90"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb90-1" data-line-number="1"><span class="kw">summary</span>(anxiety)</a></code></pre></div>
<pre><code>##     gender               CAS             CARS      
##  Length:35          Min.   :1.800   Min.   :1.000  
##  Class :character   1st Qu.:2.575   1st Qu.:2.445  
##  Mode  :character   Median :2.800   Median :2.790  
##                     Mean   :2.816   Mean   :2.771  
##                     3rd Qu.:3.150   3rd Qu.:3.290  
##                     Max.   :3.750   Max.   :4.000</code></pre>
<p>because, although it gets the means, it does not get the standard
deviations. (I added the SD to the original question to make you find
a way other than this.)</p>
<p>In summary, find a way to get those answers without naming those
columns in your code, and I’m good.</p>
<p>In case you were wondering about how to do this separately by gender, well, put the <code>group\_by</code> in like you did before:</p>
<div class="sourceCode" id="cb92"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb92-1" data-line-number="1">anxiety <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">group_by</span>(gender) <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb92-2" data-line-number="2"><span class="kw">summarize_if</span>(is.numeric,<span class="kw">funs</span>(mean,sd))</a></code></pre></div>
<pre><code>## # A tibble: 2 x 5
##   gender CAS_mean CARS_mean CAS_sd CARS_sd
##   &lt;chr&gt;     &lt;dbl&gt;     &lt;dbl&gt;  &lt;dbl&gt;   &lt;dbl&gt;
## 1 female     2.64      2.51  0.554   0.773
## 2 male       2.94      2.96  0.390   0.525</code></pre>
<p>or</p>
<div class="sourceCode" id="cb94"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb94-1" data-line-number="1">anxiety <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">group_by</span>(gender) <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb94-2" data-line-number="2"><span class="kw">summarize_at</span>(<span class="kw">vars</span>(<span class="kw">starts_with</span>(<span class="st">&quot;C&quot;</span>)),<span class="kw">funs</span>(mean,sd))</a></code></pre></div>
<pre><code>## # A tibble: 2 x 5
##   gender CAS_mean CARS_mean CAS_sd CARS_sd
##   &lt;chr&gt;     &lt;dbl&gt;     &lt;dbl&gt;  &lt;dbl&gt;   &lt;dbl&gt;
## 1 female     2.64      2.51  0.554   0.773
## 2 male       2.94      2.96  0.390   0.525</code></pre>
<p>The male means are slightly higher on both tests, but the male
standard deviations are a little smaller.
You might be wondering whether the test scores are related. They are both quantitative, so the obvious way to find out is a scatterplot:</p>
<div class="sourceCode" id="cb96"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb96-1" data-line-number="1"><span class="kw">ggplot</span>(anxiety,<span class="kw">aes</span>(<span class="dt">x=</span>CAS,<span class="dt">y=</span>CARS))<span class="op">+</span><span class="kw">geom_point</span>()</a></code></pre></div>
<p><img src="03-data-summaries_files/figure-html/unnamed-chunk-54-1.png" width="672" /></p>
<p>The two variables can be on either axis, since there is no obvious
response or explanatory variable. A higher score on one scale goes
with a higher score on the other, suggesting that the two scales are
measuring the same thing.</p>
<p>This plot mixes up the males and females, so you might like to distinguish them, which goes like this:</p>
<div class="sourceCode" id="cb97"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb97-1" data-line-number="1"><span class="kw">ggplot</span>(anxiety,<span class="kw">aes</span>(<span class="dt">x=</span>CAS,<span class="dt">y=</span>CARS,<span class="dt">colour=</span>gender))<span class="op">+</span><span class="kw">geom_point</span>()</a></code></pre></div>
<p><img src="03-data-summaries_files/figure-html/unnamed-chunk-55-1.png" width="672" /></p>
<p>There is a slight (but only slight) tendency for the males to be up
and to the right, and for the females to be down and to the left. This
is about what you would expect, given that the male means are slightly
bigger on both scores, but the difference in means is not that big
compared to the SD.</p>
</div>
<div id="hunter-gatherers-in-australia" class="section level2">
<h2><span class="header-section-number">4.5</span> Hunter-gatherers in Australia</h2>
<p>A hunter-gatherer society is one where people get their food
by hunting, fishing or foraging rather than by agriculture or by
raising animals. Such societies tend to move from place to place.
Anthropologists have studied hunter-gatherer societies in forest
ecosystems across the world. The average population density of these
societies is 7.38 people per 100 km<span class="math inline">\(^2\)</span>. Hunter-gatherer societies on
different continents might have different population densities,
possibly because of large-scale ecological constraints (such as
resource availability), or because of other factors, possibly social
and/or historic, determining population density.</p>
<p>Some hunter-gatherer societies in Australia were studied, and the
population density per 100 km<span class="math inline">\(^2\)</span> recorded for each. The data are in
<a href="http://www.utsc.utoronto.ca/~butler/c32/hg.txt" class="uri">http://www.utsc.utoronto.ca/~butler/c32/hg.txt</a>.</p>
<ol style="list-style-type: lower-alpha">
<li>Read the data into R. Do you have the correct variables?
How many hunter-gatherer societies in Australia were studied?
Explain briefly.</li>
</ol>
<p>Solution</p>
<p>The data values are separated by (single) spaces, so <code>read\_delim</code>
is the thing:</p>
<div class="sourceCode" id="cb98"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb98-1" data-line-number="1">url=<span class="st">&quot;http://www.utsc.utoronto.ca/~butler/c32/hg.txt&quot;</span></a>
<a class="sourceLine" id="cb98-2" data-line-number="2">societies=<span class="kw">read_delim</span>(url,<span class="st">&quot; &quot;</span>)</a></code></pre></div>
<pre><code>## Parsed with column specification:
## cols(
##   name = col_character(),
##   density = col_double()
## )</code></pre>
<p>I like to put the URL in a variable first, because if I don’t, the
<code>read\_delim</code> line can be rather long. But if you want to do it
in one step, that’s fine, as long as it’s clear that you are doing the
right thing.</p>
<p>Let’s look at the data frame:</p>
<div class="sourceCode" id="cb100"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb100-1" data-line-number="1">societies</a></code></pre></div>
<pre><code>## # A tibble: 13 x 2
##    name       density
##    &lt;chr&gt;        &lt;dbl&gt;
##  1 jeidji       17   
##  2 kuku         50   
##  3 mamu         45   
##  4 ngatjan      59.8 
##  5 undanbi      21.7 
##  6 jinibarra    16   
##  7 ualaria       9   
##  8 barkindji    15.4 
##  9 wongaibon     5.12
## 10 jaralde      40   
## 11 tjapwurong   35   
## 12 tasmanians   13.4 
## 13 badjalang    13.4</code></pre>
<p>I have the name of each society and its population density, as
promised (so that is correct). There were 13 societies that were
studied. For me, they were all displayed. For you, you’ll probably see only the first ten, and you’ll have to click Next to see the last three.</p>
<ol start="2" style="list-style-type: lower-alpha">
<li>The question of interest is whether these Australian
hunter-gatherer societies are like the rest of the world in terms of mean
population density. State suitable null and alternative
hypotheses. <em>Define any symbols you use</em>: that is, if you use a
symbol, you also have to say what it means.</li>
</ol>
<p>Solution</p>
<p>The mean for the world as a whole (“average”, as stated earlier)
is 7.38. Let <span class="math inline">\(\mu\)</span> denote the population mean for Australia (of
which these societies are a sample). Then our hypotheses are:
<span class="math display">\[ H_0: \mu=7.38\]</span>
and
<span class="math display">\[ H_a: \mu \ne 7.38.\]</span>
There is no reason for a one-sided alternative here, since all we
are interested in is whether Australia is different from the rest
of the world.
<em>Expect to lose a point</em> if you use the symbol <span class="math inline">\(\mu\)</span> without
saying what it means.</p>
<ol start="3" style="list-style-type: lower-alpha">
<li>Test your hypotheses using a suitable test. What do you
conclude, in the context of the data?</li>
</ol>
<p>Solution</p>
<p>A <span class="math inline">\(t\)</span>-test, since we are testing a mean:</p>
<div class="sourceCode" id="cb102"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb102-1" data-line-number="1"><span class="kw">t.test</span>(societies<span class="op">$</span>density,<span class="dt">mu=</span><span class="fl">7.38</span>)</a></code></pre></div>
<pre><code>## 
##  One Sample t-test
## 
## data:  societies$density
## t = 3.8627, df = 12, p-value = 0.002257
## alternative hypothesis: true mean is not equal to 7.38
## 95 percent confidence interval:
##  15.59244 36.84449
## sample estimates:
## mean of x 
##  26.21846</code></pre>
<p>The P-value is 0.0023, less than the usual <span class="math inline">\(\alpha\)</span> of 0.05, so we
<em>reject</em> the null hypothesis and conclude that the mean
population density is not equal to 7.38. That is to say, Australia is
different from the rest of the world in this sense.</p>
<p>As you know, “reject the null hypothesis” is only part of the
answer, so gets only part of the marks.</p>
<ol start="4" style="list-style-type: lower-alpha">
<li>Do you have any doubts about the validity of your test?
Explain briefly, using a suitable graph to support your
explanation.</li>
</ol>
<p>Solution</p>
<p>The assumption behind the <span class="math inline">\(t\)</span>-test is that the data are
approximately normal. We can assess that in several ways, but the
simplest (which is perfectly acceptable at this point) is a
histogram. You’ll need to pick a suitable number of bins. This one
comes from Sturges’ rule:</p>
<div class="sourceCode" id="cb104"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb104-1" data-line-number="1"><span class="kw">ggplot</span>(societies,<span class="kw">aes</span>(<span class="dt">x=</span>density))<span class="op">+</span><span class="kw">geom_histogram</span>(<span class="dt">bins=</span><span class="dv">5</span>)</a></code></pre></div>
<p><img src="03-data-summaries_files/figure-html/unnamed-chunk-59-1.png" width="672" />
Your conclusion might depend on how many bins you chose for your
histogram. Here’s 8 bins (which is really too many with only 13
observations, but it actually shows the shape well):</p>
<div class="sourceCode" id="cb105"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb105-1" data-line-number="1"><span class="kw">ggplot</span>(societies,<span class="kw">aes</span>(<span class="dt">x=</span>density))<span class="op">+</span><span class="kw">geom_histogram</span>(<span class="dt">bins=</span><span class="dv">8</span>)</a></code></pre></div>
<p><img src="03-data-summaries_files/figure-html/unnamed-chunk-60-1.png" width="672" /></p>
<p>or you can get a number of bins from one of the built-in functions,
such as:</p>
<div class="sourceCode" id="cb106"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb106-1" data-line-number="1">mybins=<span class="kw">nclass.FD</span>(societies<span class="op">$</span>density)</a>
<a class="sourceLine" id="cb106-2" data-line-number="2">mybins</a></code></pre></div>
<pre><code>## [1] 3</code></pre>
<p>This one is small. The interquartile range is large and <span class="math inline">\(n\)</span> is small,
so the binwidth will be large and therefore the number of bins will be
small.</p>
<p>Other choices: a one-group boxplot:</p>
<div class="sourceCode" id="cb108"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb108-1" data-line-number="1"><span class="kw">ggplot</span>(societies,<span class="kw">aes</span>(<span class="dt">x=</span><span class="dv">1</span>,<span class="dt">y=</span>density))<span class="op">+</span><span class="kw">geom_boxplot</span>()</a></code></pre></div>
<p><img src="03-data-summaries_files/figure-html/unnamed-chunk-62-1.png" width="672" /></p>
<p>This isn’t the best for assessing normality as such, but it will tell
you about lack of symmetry and outliers, which are the most important
threats to the <span class="math inline">\(t\)</span>-test, so it’s fine here. Or, a normal quantile plot:</p>
<div class="sourceCode" id="cb109"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb109-1" data-line-number="1"><span class="kw">ggplot</span>(societies,<span class="kw">aes</span>(<span class="dt">sample=</span>density))<span class="op">+</span></a>
<a class="sourceLine" id="cb109-2" data-line-number="2"><span class="kw">stat_qq</span>()<span class="op">+</span><span class="kw">stat_qq_line</span>()</a></code></pre></div>
<p><img src="03-data-summaries_files/figure-html/unnamed-chunk-63-1.png" width="672" /></p>
<p>This is actually the best way to assess normality, but I’m not
expecting you to use this plot here, because we may not have gotten to
it in class yet. (If you have read ahead and successfully use the
plot, it’s fine.)</p>
<p>After you have drawn your chosen plot (you need <em>one</em> plot), you
need to say something about normality and thus whether you have any
doubts about the validity of your <span class="math inline">\(t\)</span>-test. This will depend on the
graph you drew: if you think your graph is symmetric and outlier-free,
you should have no doubts about your <span class="math inline">\(t\)</span>-test; if you think it has
something wrong with it, you should say what it is and express your
doubts. My guess is that you will think this distribution is skewed to
the right. Most of my plots are saying that.</p>
<p>On the website where I got these data, they were using the data as
an example for another test, precisely <em>because</em> they thought the
distribution was right-skewed. Later on, we’ll learn about the sign
test for the median, which I think is actually a better test here.</p>
<p>4 distribution of hunter-gatherer population densities (N = 86)
across all forest ecosystems worldwide is skewed to the right and is
non-normal. The median is therefore the most reliable measure of
central tendency. As such, the median population density (per 100 km)
of forest hunter-gatherers is ηo = 7.38. An interesting question that
we may want to ask is whether this value is an accurate estimate of
the population density of forest hunter-gatherers on specific
continents; the results might answer the question of whether
hunter-gatherer population densities are determined primarily by
large-scale ecological constraints (such as resource availability), or
whether there seem to be other factors, possibly social and/or
historic, determining population density. For this example we will
look at the hunter-gatherer groups of the northern Australian forests
(n = 13). Let ηo be the median population density of all forest
hunter-gatherer groups (N = 86), where ηo = 7.38, and let η be the
median population density for Australian forest hunter-gatherer groups
(n = 13). Formally, we wish to test the hypothesis at the a = 0.05
(95%) level:</p>

</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="reading-in-data-and-drawing-some-graphs.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="one-sample-inference.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/lunr.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"google": false,
"linkedin": false,
"weibo": false,
"instapper": false,
"vk": false,
"all": ["facebook", "google", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": null,
"text": null
},
"download": null,
"toc": {
"collapse": "subsection"
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://cdn.bootcss.com/mathjax/2.7.1/MathJax.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:" && /^https?:/.test(src))
      src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
