<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>Chapter 19 Dates and times | Problems and Solutions in Applied Statistics</title>
  <meta name="description" content="A set of problems and solutions, in R, on various parts of applied statistics" />
  <meta name="generator" content="bookdown 0.21 and GitBook 2.6.7" />

  <meta property="og:title" content="Chapter 19 Dates and times | Problems and Solutions in Applied Statistics" />
  <meta property="og:type" content="book" />
  <meta property="og:url" content="http://ritsokiguess.site/pasias" />
  
  <meta property="og:description" content="A set of problems and solutions, in R, on various parts of applied statistics" />
  <meta name="github-repo" content="nxskok/pasias" />

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Chapter 19 Dates and times | Problems and Solutions in Applied Statistics" />
  
  <meta name="twitter:description" content="A set of problems and solutions, in R, on various parts of applied statistics" />
  

<meta name="author" content="Ken Butler" />


<meta name="date" content="2021-04-26" />

  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="regression-with-categorical-variables.html"/>
<link rel="next" href="functions.html"/>
<script src="libs/header-attrs-2.7/header-attrs.js"></script>
<script src="libs/jquery-2.2.3/jquery.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />









<script src="libs/accessible-code-block-0.0.1/empty-anchor.js"></script>


<style type="text/css">
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">Problems and Solutions in Applied Statistics</a></li>

<li class="divider"></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i>Introduction</a>
<ul>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#packages-used-somewhere-in-this-book"><i class="fa fa-check"></i>Packages used somewhere in this book</a></li>
</ul></li>
<li class="chapter" data-level="1" data-path="getting-used-to-r-and-r-studio.html"><a href="getting-used-to-r-and-r-studio.html"><i class="fa fa-check"></i><b>1</b> Getting used to R and R Studio</a></li>
<li class="chapter" data-level="2" data-path="reading-in-data.html"><a href="reading-in-data.html"><i class="fa fa-check"></i><b>2</b> Reading in data</a></li>
<li class="chapter" data-level="3" data-path="drawing-graphs.html"><a href="drawing-graphs.html"><i class="fa fa-check"></i><b>3</b> Drawing graphs</a></li>
<li class="chapter" data-level="4" data-path="data-exploration.html"><a href="data-exploration.html"><i class="fa fa-check"></i><b>4</b> Data exploration</a></li>
<li class="chapter" data-level="5" data-path="working-with-dataframes.html"><a href="working-with-dataframes.html"><i class="fa fa-check"></i><b>5</b> Working with dataframes</a></li>
<li class="chapter" data-level="6" data-path="one-sample-inference.html"><a href="one-sample-inference.html"><i class="fa fa-check"></i><b>6</b> One-sample inference</a></li>
<li class="chapter" data-level="7" data-path="two-sample-inference.html"><a href="two-sample-inference.html"><i class="fa fa-check"></i><b>7</b> Two-sample inference</a></li>
<li class="chapter" data-level="8" data-path="power-and-sample-size.html"><a href="power-and-sample-size.html"><i class="fa fa-check"></i><b>8</b> Power and sample size</a></li>
<li class="chapter" data-level="9" data-path="the-sign-test.html"><a href="the-sign-test.html"><i class="fa fa-check"></i><b>9</b> The sign test</a></li>
<li class="chapter" data-level="10" data-path="mood-median-test.html"><a href="mood-median-test.html"><i class="fa fa-check"></i><b>10</b> Mood median test</a></li>
<li class="chapter" data-level="11" data-path="matched-pairs-t-and-sign-test.html"><a href="matched-pairs-t-and-sign-test.html"><i class="fa fa-check"></i><b>11</b> Matched pairs t and sign test</a></li>
<li class="chapter" data-level="12" data-path="normal-quantile-plots.html"><a href="normal-quantile-plots.html"><i class="fa fa-check"></i><b>12</b> Normal quantile plots</a>
<ul>
<li class="chapter" data-level="12.1" data-path="normal-quantile-plots.html"><a href="normal-quantile-plots.html#lengths-of-heliconia-flowers"><i class="fa fa-check"></i><b>12.1</b> Lengths of heliconia flowers</a></li>
<li class="chapter" data-level="12.2" data-path="normal-quantile-plots.html"><a href="normal-quantile-plots.html#ferritin-and-normality"><i class="fa fa-check"></i><b>12.2</b> Ferritin and normality</a></li>
<li class="chapter" data-level="12.3" data-path="normal-quantile-plots.html"><a href="normal-quantile-plots.html#lengths-of-heliconia-flowers-1"><i class="fa fa-check"></i><b>12.3</b> Lengths of heliconia flowers</a></li>
<li class="chapter" data-level="12.4" data-path="normal-quantile-plots.html"><a href="normal-quantile-plots.html#ferritin-and-normality-1"><i class="fa fa-check"></i><b>12.4</b> Ferritin and normality</a></li>
</ul></li>
<li class="chapter" data-level="13" data-path="analysis-of-variance.html"><a href="analysis-of-variance.html"><i class="fa fa-check"></i><b>13</b> Analysis of variance</a></li>
<li class="chapter" data-level="14" data-path="writing-reports.html"><a href="writing-reports.html"><i class="fa fa-check"></i><b>14</b> Writing reports</a></li>
<li class="chapter" data-level="15" data-path="tidying-data.html"><a href="tidying-data.html"><i class="fa fa-check"></i><b>15</b> Tidying data</a></li>
<li class="chapter" data-level="16" data-path="simple-regression.html"><a href="simple-regression.html"><i class="fa fa-check"></i><b>16</b> Simple regression</a></li>
<li class="chapter" data-level="17" data-path="multiple-regression.html"><a href="multiple-regression.html"><i class="fa fa-check"></i><b>17</b> Multiple regression</a></li>
<li class="chapter" data-level="18" data-path="regression-with-categorical-variables.html"><a href="regression-with-categorical-variables.html"><i class="fa fa-check"></i><b>18</b> Regression with categorical variables</a>
<ul>
<li class="chapter" data-level="18.1" data-path="regression-with-categorical-variables.html"><a href="regression-with-categorical-variables.html#crickets-revisited"><i class="fa fa-check"></i><b>18.1</b> Crickets revisited</a></li>
<li class="chapter" data-level="18.2" data-path="regression-with-categorical-variables.html"><a href="regression-with-categorical-variables.html#pulse-rates-and-marching"><i class="fa fa-check"></i><b>18.2</b> Pulse rates and marching</a></li>
<li class="chapter" data-level="18.3" data-path="regression-with-categorical-variables.html"><a href="regression-with-categorical-variables.html#crickets-revisited-1"><i class="fa fa-check"></i><b>18.3</b> Crickets revisited</a></li>
<li class="chapter" data-level="18.4" data-path="regression-with-categorical-variables.html"><a href="regression-with-categorical-variables.html#pulse-rates-and-marching-1"><i class="fa fa-check"></i><b>18.4</b> Pulse rates and marching</a></li>
</ul></li>
<li class="chapter" data-level="19" data-path="dates-and-times.html"><a href="dates-and-times.html"><i class="fa fa-check"></i><b>19</b> Dates and times</a>
<ul>
<li class="chapter" data-level="19.1" data-path="dates-and-times.html"><a href="dates-and-times.html#growth-of-mizuna-lettuce-seeds"><i class="fa fa-check"></i><b>19.1</b> Growth of Mizuna lettuce seeds</a></li>
<li class="chapter" data-level="19.2" data-path="dates-and-times.html"><a href="dates-and-times.html#types-of-childbirth"><i class="fa fa-check"></i><b>19.2</b> Types of childbirth</a></li>
<li class="chapter" data-level="19.3" data-path="dates-and-times.html"><a href="dates-and-times.html#wolves-and-caribou"><i class="fa fa-check"></i><b>19.3</b> Wolves and caribou</a></li>
<li class="chapter" data-level="19.4" data-path="dates-and-times.html"><a href="dates-and-times.html#dealing-with-dates-in-the-worcester-heart-attack-study"><i class="fa fa-check"></i><b>19.4</b> Dealing with dates in the Worcester Heart Attack study</a></li>
<li class="chapter" data-level="19.5" data-path="dates-and-times.html"><a href="dates-and-times.html#going-to-sleep"><i class="fa fa-check"></i><b>19.5</b> Going to sleep</a></li>
<li class="chapter" data-level="19.6" data-path="dates-and-times.html"><a href="dates-and-times.html#growth-of-mizuna-lettuce-seeds-1"><i class="fa fa-check"></i><b>19.6</b> Growth of Mizuna lettuce seeds</a></li>
<li class="chapter" data-level="19.7" data-path="dates-and-times.html"><a href="dates-and-times.html#types-of-childbirth-1"><i class="fa fa-check"></i><b>19.7</b> Types of childbirth</a></li>
<li class="chapter" data-level="19.8" data-path="dates-and-times.html"><a href="dates-and-times.html#wolves-and-caribou-1"><i class="fa fa-check"></i><b>19.8</b> Wolves and caribou</a></li>
<li class="chapter" data-level="19.9" data-path="dates-and-times.html"><a href="dates-and-times.html#dealing-with-dates-in-the-worcester-heart-attack-study-1"><i class="fa fa-check"></i><b>19.9</b> Dealing with dates in the Worcester Heart Attack study</a></li>
<li class="chapter" data-level="19.10" data-path="dates-and-times.html"><a href="dates-and-times.html#going-to-sleep-1"><i class="fa fa-check"></i><b>19.10</b> Going to sleep</a></li>
</ul></li>
<li class="chapter" data-level="20" data-path="functions.html"><a href="functions.html"><i class="fa fa-check"></i><b>20</b> Functions</a></li>
<li class="chapter" data-level="21" data-path="vector-and-matrix-algebra.html"><a href="vector-and-matrix-algebra.html"><i class="fa fa-check"></i><b>21</b> Vector and matrix algebra</a>
<ul>
<li class="chapter" data-level="21.1" data-path="vector-and-matrix-algebra.html"><a href="vector-and-matrix-algebra.html#heights-and-foot-lengths-again"><i class="fa fa-check"></i><b>21.1</b> Heights and foot lengths again</a></li>
<li class="chapter" data-level="21.2" data-path="vector-and-matrix-algebra.html"><a href="vector-and-matrix-algebra.html#heights-and-foot-lengths-again-1"><i class="fa fa-check"></i><b>21.2</b> Heights and foot lengths again</a></li>
</ul></li>
<li class="chapter" data-level="22" data-path="the-bootstrap.html"><a href="the-bootstrap.html"><i class="fa fa-check"></i><b>22</b> The Bootstrap</a></li>
<li class="chapter" data-level="23" data-path="bayesian-statistics-with-stan.html"><a href="bayesian-statistics-with-stan.html"><i class="fa fa-check"></i><b>23</b> Bayesian Statistics with Stan</a></li>
<li class="chapter" data-level="24" data-path="logistic-regression.html"><a href="logistic-regression.html"><i class="fa fa-check"></i><b>24</b> Logistic regression</a></li>
<li class="chapter" data-level="25" data-path="logistic-regression-with-ordinal-response.html"><a href="logistic-regression-with-ordinal-response.html"><i class="fa fa-check"></i><b>25</b> Logistic regression with ordinal response</a></li>
<li class="chapter" data-level="26" data-path="logistic-regression-with-nominal-response.html"><a href="logistic-regression-with-nominal-response.html"><i class="fa fa-check"></i><b>26</b> Logistic regression with nominal response</a></li>
<li class="chapter" data-level="27" data-path="survival-analysis.html"><a href="survival-analysis.html"><i class="fa fa-check"></i><b>27</b> Survival analysis</a></li>
<li class="chapter" data-level="28" data-path="analysis-of-variance-revisited.html"><a href="analysis-of-variance-revisited.html"><i class="fa fa-check"></i><b>28</b> Analysis of variance revisited</a></li>
<li class="chapter" data-level="29" data-path="analysis-of-covariance.html"><a href="analysis-of-covariance.html"><i class="fa fa-check"></i><b>29</b> Analysis of covariance</a></li>
<li class="chapter" data-level="30" data-path="multivariate-analysis-of-variance.html"><a href="multivariate-analysis-of-variance.html"><i class="fa fa-check"></i><b>30</b> Multivariate analysis of variance</a></li>
<li class="chapter" data-level="31" data-path="repeated-measures.html"><a href="repeated-measures.html"><i class="fa fa-check"></i><b>31</b> Repeated measures</a></li>
<li class="chapter" data-level="32" data-path="discriminant-analysis.html"><a href="discriminant-analysis.html"><i class="fa fa-check"></i><b>32</b> Discriminant analysis</a></li>
<li class="chapter" data-level="33" data-path="hierarchical-cluster-analysis.html"><a href="hierarchical-cluster-analysis.html"><i class="fa fa-check"></i><b>33</b> Hierarchical cluster analysis</a></li>
<li class="chapter" data-level="34" data-path="k-means-cluster-analysis.html"><a href="k-means-cluster-analysis.html"><i class="fa fa-check"></i><b>34</b> K-means cluster analysis</a></li>
<li class="chapter" data-level="35" data-path="drawing-maps-with-leaflet.html"><a href="drawing-maps-with-leaflet.html"><i class="fa fa-check"></i><b>35</b> Drawing maps with Leaflet</a></li>
<li class="chapter" data-level="36" data-path="multidimensional-scaling.html"><a href="multidimensional-scaling.html"><i class="fa fa-check"></i><b>36</b> Multidimensional Scaling</a></li>
<li class="chapter" data-level="37" data-path="principal-components.html"><a href="principal-components.html"><i class="fa fa-check"></i><b>37</b> Principal Components</a>
<ul>
<li class="chapter" data-level="37.1" data-path="principal-components.html"><a href="principal-components.html#the-weather-somewhere"><i class="fa fa-check"></i><b>37.1</b> The weather, somewhere</a></li>
<li class="chapter" data-level="37.2" data-path="principal-components.html"><a href="principal-components.html#the-weather-somewhere-1"><i class="fa fa-check"></i><b>37.2</b> The weather, somewhere</a></li>
</ul></li>
<li class="chapter" data-level="38" data-path="factor-analysis.html"><a href="factor-analysis.html"><i class="fa fa-check"></i><b>38</b> Factor Analysis</a></li>
<li class="chapter" data-level="39" data-path="frequency-table-analysis.html"><a href="frequency-table-analysis.html"><i class="fa fa-check"></i><b>39</b> Frequency table analysis</a></li>
<li class="divider"></li>
<li><a href="https://github.com/rstudio/bookdown" target="blank">Published with bookdown</a></li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Problems and Solutions in Applied Statistics</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="dates-and-times" class="section level1" number="19">
<h1><span class="header-section-number">Chapter 19</span> Dates and times</h1>
<p>The usual to begin with:</p>
<div class="sourceCode" id="cb73"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb73-1"><a href="dates-and-times.html#cb73-1"></a><span class="kw">library</span>(tidyverse)</span></code></pre></div>
<div id="growth-of-mizuna-lettuce-seeds" class="section level2" number="19.1">
<h2><span class="header-section-number">19.1</span> Growth of Mizuna lettuce seeds</h2>
<p>In 2010, a group of students planted some Mizuna lettuce
seeds, and recorded how they grew. The data were saved in an Excel
spreadsheet, which is at
<a href="http://ritsokiguess.site/datafiles/mizuna.xlsx">link</a>. The columns
are: the date, the height (in cm) of (I presume) the tallest plant,
the amount of water added since the previous date (ml), the
temperature in the container where the seedlings were growing, and any
additional notes that the students made (edited for length by me). The
top line of the data file is variable names.</p>
<ol style="list-style-type: lower-alpha">
<li><p>Read the
spreadsheet data.</p></li>
<li><p>Make a plot of <code>height</code> against your
dates, with the points joined by lines.</p></li>
<li><p>Label each point on the plot with the
amount of water added up to that point.</p></li>
</ol>
</div>
<div id="types-of-childbirth" class="section level2" number="19.2">
<h2><span class="header-section-number">19.2</span> Types of childbirth</h2>
<p>Childbirths can be of two types: a
“vaginal” birth in which the child is born through the mother’s
vagina in the normal fashion, and a “cesarean section” where a
surgeon cuts through the wall of the mother’s abdomen, and the baby
is delivered through the incision. Cesarean births are used when
there are difficulties in pregnancy or during childbirth that would
make a vaginal birth too risky.
A hospital kept track of the number of vaginal and Cesarean births
for the twelve months of 2012. Of interest is whether the Cesarean
rate (the ratio of Cesarean births to all births) was increasing,
decreasing or remaining stable over that time.
The data may be found at
<a href="http://ritsokiguess.site/datafiles/birthtypes.txt">link</a>. The
columns are the names of the months (in 2012), the number of cesarean
births and the number of vaginal births. (The data are not real, but
are typical of the kind of thing you would observe.)</p>
<ol style="list-style-type: lower-alpha">
<li><p>Read the data into R and display your data frame.</p></li>
<li><p>Create a column of actual dates and also a column of
cesarean rates, as defined above. Store your new data frame in a
variable and display it. For the dates, assume that each date is of
the 1st of the month that it belongs to.</p></li>
<li><p>Plot the cesarean rate against time, with a smooth
trend. Do you see an upward trend, a downward trend, no trend, or
something else?</p></li>
<li><p>Try to summarize the trend you just found with a
correlation. What goes wrong? How can you fix it?</p></li>
</ol>
</div>
<div id="wolves-and-caribou" class="section level2" number="19.3">
<h2><span class="header-section-number">19.3</span> Wolves and caribou</h2>
<p>In Denali National Park, Alaska, the size of the wolf
population depends on the size of the caribou population (since
wolves hunt and kill caribou). This is a large national park, so
caribou are found in very large herds, so big, in fact, that the
well-being of the entire herd is not threatened by wolf
attacks.<a href="#fn15" class="footnote-ref" id="fnref15"><sup>15</sup></a>
Can the size of the caribou population
be used to predict the size of the wolf population?
The data can be found at
<a href="http://ritsokiguess.site/datafiles/caribou.txt">link</a>. The
columns
are: the date of the survey,<a href="#fn16" class="footnote-ref" id="fnref16"><sup>16</sup></a>
the name of the park employee in charge of the survey, the caribou population (in hundreds) and the wolf population (actual count).<a href="#fn17" class="footnote-ref" id="fnref17"><sup>17</sup></a></p>
<ol style="list-style-type: lower-alpha">
<li><p>Take a look at the data file. How would you describe its
format? Read it into R, and check that you got something sensible.</p></li>
<li><p>Create a new data frame where the column labelled
<code>date</code> is now a genuine R <code>Date</code>, using something
from <code>lubridate</code>.</p></li>
<li><p>Create new columns containing the days of
the week and the month names for the dates.</p></li>
<li><p>Enough playing around with dates. Make a scatterplot of
caribou population (explanatory) against wolf population
(response). Do you see any relationship?</p></li>
<li><p>On your plot from the previous part, label each point with
the year it belongs to. You can do this in two steps: first make a
new column containing just the years, and then use it as labels
for the points on the plot.</p></li>
<li><p>Make a plot of caribou population against time (this is done
the obvious way). What seems to be happening to the caribou
population over time?</p></li>
<li><p>The caribou and wolf populations over time are
really “time series”.
See if you can make a plot of <em>both</em> the
caribou and wolf populations against time. You can make two
<span class="math inline">\(y\)</span>-axes, one for caribou and one for wolf; this will probably
require some research on your part to figure out.</p></li>
</ol>
</div>
<div id="dealing-with-dates-in-the-worcester-heart-attack-study" class="section level2" number="19.4">
<h2><span class="header-section-number">19.4</span> Dealing with dates in the Worcester Heart Attack study</h2>
<p>The Worcester Heart Attack Study is an ongoing study of
heart attacks in the Worcester, MA area. The main purpose of the study
is to investigate changes over time in incidence and death rates, and also
the use of different treatment approaches. We will be mainly using
this data set to investigate data handling and dealing with dates. The
data can be found at
<a href="http://ritsokiguess.site/datafiles/whas500.txt">link</a>.</p>
<ol style="list-style-type: lower-alpha">
<li><p>Read the data into R. The reading-in part is
straightforward, but check what type of thing each column is. Is
that what it should be?</p></li>
<li><p>The date columns should be R dates. They are not
year-month-day, so converting them via <code>as.Date</code> (which is
what <code>read_delim</code> tries to do) will not work. Load the
<code>lubridate</code> package, and create new columns in your data
frame that are properly dates. Save your data frame, and list it to
demonstrate that it worked.</p></li>
<li><p>Create three new variables <code>diff1, diff2, diff3</code> that
are the numbers of days between each of your dates, and save the
data frame in which they have been created. Verify that at
least some of them are the same as <code>los</code> and <code>lenfol</code>.</p></li>
<li><p>Construct side-by-side boxplots of the length of followup by
each followup status. You’ll need to make sure
that the followup status, as it gets fed into <code>ggplot</code>, is a
<code>factor</code>, or, at least, not the number that it is now.</p></li>
</ol>
</div>
<div id="going-to-sleep" class="section level2" number="19.5">
<h2><span class="header-section-number">19.5</span> Going to sleep</h2>
<p>A student keeps track of what time they go to bed and what time they get up in the morning. They also have an app on their phone that measures the number of hours they were asleep during that time. The data for one week are in <a href="http://ritsokiguess.site/datafiles/sleeping.csv">http://ritsokiguess.site/datafiles/sleeping.csv</a>, in the 24-hour clock.</p>
<ol style="list-style-type: lower-alpha">
<li><p>Read in and display the data. What type of things are each of your columns?</p></li>
<li><p>Work out the fractional number of hours that the student was in bed each of these nights. (They may not have been asleep this whole time.) Your result needs to be a <em>number</em> since we will be doing some calculations with it shortly.</p></li>
<li><p>The student is concerned with something they call “sleep efficiency”. This is the percentage of time in bed spent sleeping. Work out the student’s sleep efficiency for the seven nights in this dataframe. Which night was the student’s sleep efficiency greatest?</p></li>
<li><p>Display the time spent in bed each night as a number of hours, minutes and seconds.</p></li>
<li><p>Make a graph of what time the student went to bed each night. Bear in mind that you only need the times, not the dates, and that you want a graph that is informative, showing appropriately the distribution of times the student went to bed.</p></li>
</ol>
<p>My solutions follow:</p>
</div>
<div id="growth-of-mizuna-lettuce-seeds-1" class="section level2" number="19.6">
<h2><span class="header-section-number">19.6</span> Growth of Mizuna lettuce seeds</h2>
<p>In 2010, a group of students planted some Mizuna lettuce
seeds, and recorded how they grew. The data were saved in an Excel
spreadsheet, which is at
<a href="http://ritsokiguess.site/datafiles/mizuna.xlsx">link</a>. The columns
are: the date, the height (in cm) of (I presume) the tallest plant,
the amount of water added since the previous date (ml), the
temperature in the container where the seedlings were growing, and any
additional notes that the students made (edited for length by me). The
top line of the data file is variable names.</p>
<ol style="list-style-type: lower-alpha">
<li>Read the
spreadsheet data.</li>
</ol>
<p>Solution</p>
<p>This is <code>read_excel</code> from package <code>readxl</code>. I’m
not sure what will happen to the dates yet. Note that this needs
a “local” copy of the spreadsheet (that is, you have to
download it and save it on your computer, then upload it to
<code>rstudio.cloud</code>), possibly using <code>file.choose</code> to
help R find it. I put my copy in the same project folder as I was
working in, so I just need the file name:</p>
<div class="sourceCode" id="cb74"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb74-1"><a href="dates-and-times.html#cb74-1"></a><span class="kw">library</span>(readxl)</span>
<span id="cb74-2"><a href="dates-and-times.html#cb74-2"></a>mizuna &lt;-<span class="st"> </span><span class="kw">read_excel</span>(<span class="st">&quot;mizuna.xlsx&quot;</span>)</span>
<span id="cb74-3"><a href="dates-and-times.html#cb74-3"></a>mizuna</span></code></pre></div>
<p>The dates <em>did</em> get read properly. <code>dttm</code> is
“date-time”, so I guess it’s allowing for the possibility that my
dates had times attached as well. Unlike with SAS (as we see later),
the years came out right.</p>
<p><span class="math inline">\(\blacksquare\)</span></p>
<ol start="2" style="list-style-type: lower-alpha">
<li>Make a plot of <code>height</code> against your
dates, with the points joined by lines.</li>
</ol>
<p>Solution</p>
<div class="sourceCode" id="cb75"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb75-1"><a href="dates-and-times.html#cb75-1"></a><span class="kw">ggplot</span>(mizuna, <span class="kw">aes</span>(<span class="dt">x =</span> date, <span class="dt">y =</span> height)) <span class="op">+</span><span class="st"> </span><span class="kw">geom_point</span>() <span class="op">+</span><span class="st"> </span><span class="kw">geom_line</span>()</span></code></pre></div>
<p><img src="pasias_files/figure-html/unnamed-chunk-65-1.png" width="672" /></p>
<p><span class="math inline">\(\blacksquare\)</span></p>
<ol start="3" style="list-style-type: lower-alpha">
<li>Label each point on the plot with the
amount of water added up to that point.</li>
</ol>
<p>Solution</p>
<p>This is <code>water</code> again. The way to do this is to load
<code>ggrepel</code>, then add <code>geom_text_repel</code> to the
plot, by adding <code>label=water</code> to the <em>original</em>
<code>aes</code>:</p>
<div class="sourceCode" id="cb76"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb76-1"><a href="dates-and-times.html#cb76-1"></a><span class="kw">library</span>(ggrepel)</span>
<span id="cb76-2"><a href="dates-and-times.html#cb76-2"></a><span class="kw">ggplot</span>(mizuna, <span class="kw">aes</span>(<span class="dt">x =</span> date, <span class="dt">y =</span> height, <span class="dt">label =</span> water)) <span class="op">+</span></span>
<span id="cb76-3"><a href="dates-and-times.html#cb76-3"></a><span class="st">  </span><span class="kw">geom_point</span>() <span class="op">+</span><span class="st"> </span><span class="kw">geom_line</span>() <span class="op">+</span><span class="st"> </span><span class="kw">geom_text_repel</span>(<span class="dt">colour =</span> <span class="st">&quot;red&quot;</span>)</span></code></pre></div>
<p><img src="pasias_files/figure-html/unnamed-chunk-66-1.png" width="672" /></p>
<p>I made the text red, so that you can see it more easily. It “repels”
away from the points, but not from the lines joining them. Which makes
me wonder whether this would work better (I explain <code>alpha</code> afterwards):</p>
<div class="sourceCode" id="cb77"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb77-1"><a href="dates-and-times.html#cb77-1"></a><span class="kw">library</span>(ggrepel)</span>
<span id="cb77-2"><a href="dates-and-times.html#cb77-2"></a><span class="kw">ggplot</span>(mizuna, <span class="kw">aes</span>(<span class="dt">x =</span> date, <span class="dt">y =</span> height, <span class="dt">label =</span> water)) <span class="op">+</span></span>
<span id="cb77-3"><a href="dates-and-times.html#cb77-3"></a><span class="st">  </span><span class="kw">geom_point</span>() <span class="op">+</span><span class="st"> </span><span class="kw">geom_line</span>() <span class="op">+</span><span class="st"> </span><span class="kw">geom_label_repel</span>(<span class="dt">colour =</span> <span class="st">&quot;red&quot;</span>, <span class="dt">alpha =</span> <span class="fl">0.7</span>)</span></code></pre></div>
<p><img src="pasias_files/figure-html/unnamed-chunk-67-1.png" width="672" /></p>
<p>The difference between <code>text</code> and <code>label</code> is that
<code>text</code> just uses the text of the variable to mark the point,
while <code>label</code> puts that text in a box.</p>
<p>I think it works better. You can see where the line goes (under the boxes with
the labels in them), but you can see the labels clearly.</p>
<p>What that <code>alpha</code> does is to make the thing it’s attached to
(the labels) partly <em>transparent</em>. If you leave it out (try it),
the black line disappears completely under the label boxes and you
can’t see where it goes at all. The value you give for <code>alpha</code>
says how transparent the thing is, from 1 (not transparent at all)
down to 0 (invisible). I first tried 0.3, and you could hardly see the
boxes; then I tried 0.7 so that the boxes were a bit more
prominent but the lines underneath were still slightly visible, and I
decided that this is what I liked. I think making the labels a
different colour was a good idea, since that helps to distinguish the
number on the label from the line underneath.</p>
<p>You can apply <code>alpha</code> to pretty much any <code>ggplot</code> thing
that might be on top of something else, to make it possible to see
what’s underneath it. The commonest use for it is if you have a
scatterplot with a lot of points; normally, you only see some of the
points, because the plot is then a sea of black. But if you make the
points partly transparent, you can see more of what’s nearby that
would otherwise have been hidden.</p>
<p>At some point, I also have to show
you folks <code>jitter</code>, which plots in slightly different places
points that would otherwise overprint each other exactly, and you
wouldn’t know how many of them there were, like the outliers on the
boxplots of German children near the new airport.</p>
<p><span class="math inline">\(\blacksquare\)</span></p>
</div>
<div id="types-of-childbirth-1" class="section level2" number="19.7">
<h2><span class="header-section-number">19.7</span> Types of childbirth</h2>
<p>Childbirths can be of two types: a
“vaginal” birth in which the child is born through the mother’s
vagina in the normal fashion, and a “cesarean section” where a
surgeon cuts through the wall of the mother’s abdomen, and the baby
is delivered through the incision. Cesarean births are used when
there are difficulties in pregnancy or during childbirth that would
make a vaginal birth too risky.
A hospital kept track of the number of vaginal and Cesarean births
for the twelve months of 2012. Of interest is whether the Cesarean
rate (the ratio of Cesarean births to all births) was increasing,
decreasing or remaining stable over that time.
The data may be found at
<a href="http://ritsokiguess.site/datafiles/birthtypes.txt">link</a>. The
columns are the names of the months (in 2012), the number of cesarean
births and the number of vaginal births. (The data are not real, but
are typical of the kind of thing you would observe.)</p>
<ol style="list-style-type: lower-alpha">
<li>Read the data into R and display your data frame.</li>
</ol>
<p>Solution</p>
<p>This is a space-delimited text file, which means:</p>
<div class="sourceCode" id="cb78"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb78-1"><a href="dates-and-times.html#cb78-1"></a>my_url &lt;-<span class="st"> &quot;http://ritsokiguess.site/datafiles/birthtypes.txt&quot;</span></span>
<span id="cb78-2"><a href="dates-and-times.html#cb78-2"></a>births &lt;-<span class="st"> </span><span class="kw">read_delim</span>(my_url, <span class="st">&quot; &quot;</span>)</span></code></pre></div>
<pre><code>## 
## ── Column specification ─────────────────────────────────────────────────
## cols(
##   month = col_character(),
##   cesarean = col_double(),
##   vaginal = col_double()
## )</code></pre>
<div class="sourceCode" id="cb80"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb80-1"><a href="dates-and-times.html#cb80-1"></a>births</span></code></pre></div>
<p>Some text and two numbers for each month. Check.</p>
<p><span class="math inline">\(\blacksquare\)</span></p>
<ol start="2" style="list-style-type: lower-alpha">
<li>Create a column of actual dates and also a column of
cesarean rates, as defined above. Store your new data frame in a
variable and display it. For the dates, assume that each date is of
the 1st of the month that it belongs to.</li>
</ol>
<p>Solution</p>
<p>The easiest way is to use <code>str_c</code> or <code>paste</code> to
create a text date with year, month and day in some order, and
then to use the appropriate function from <code>lubridate</code> to
turn that into an actual <code>date</code>. If you use
<code>str_c</code>, you (probably) need the <code>sep</code> thing to
make sure the values get a space between them; <code>paste</code>
does this automatically. (The next question is whether
<code>ymd</code> or whatever can cope without spaces, but I’m not
exploring that.)
The cesarean rate is <code>cesarean</code> divided by
<code>cesarean</code> plus <code>vaginal</code>:</p>
<div class="sourceCode" id="cb81"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb81-1"><a href="dates-and-times.html#cb81-1"></a><span class="kw">library</span>(lubridate)</span>
<span id="cb81-2"><a href="dates-and-times.html#cb81-2"></a>b2 &lt;-<span class="st"> </span>births <span class="op">%&gt;%</span></span>
<span id="cb81-3"><a href="dates-and-times.html#cb81-3"></a><span class="st">  </span><span class="kw">mutate</span>(<span class="dt">datestr =</span> <span class="kw">str_c</span>(<span class="st">&quot;2012&quot;</span>, month, <span class="st">&quot;1&quot;</span>, <span class="dt">sep =</span> <span class="st">&quot; &quot;</span>)) <span class="op">%&gt;%</span></span>
<span id="cb81-4"><a href="dates-and-times.html#cb81-4"></a><span class="st">  </span><span class="kw">mutate</span>(<span class="dt">thedate =</span> <span class="kw">ymd</span>(datestr)) <span class="op">%&gt;%</span></span>
<span id="cb81-5"><a href="dates-and-times.html#cb81-5"></a><span class="st">  </span><span class="kw">mutate</span>(<span class="dt">cesarean_rate =</span> cesarean <span class="op">/</span><span class="st"> </span>(cesarean <span class="op">+</span><span class="st"> </span>vaginal))</span>
<span id="cb81-6"><a href="dates-and-times.html#cb81-6"></a>b2</span></code></pre></div>
<p>If you don’t like that, create columns that contain 2012 and 1 all
the way down. If you set a column name equal to a single value, that
single value gets repeated the right number of times:<a href="#fn18" class="footnote-ref" id="fnref18"><sup>18</sup></a></p>
<div class="sourceCode" id="cb82"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb82-1"><a href="dates-and-times.html#cb82-1"></a>births <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">mutate</span>(<span class="dt">year =</span> <span class="dv">2012</span>, <span class="dt">day =</span> <span class="dv">1</span>)</span></code></pre></div>
<p>and then use <code>unite</code> as in class. The distinction is that
<code>unite</code> <em>only</em> works on columns. It also “swallows up”
the columns that it is made out of; in this case, the original year,
month and day disappear:</p>
<div class="sourceCode" id="cb83"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb83-1"><a href="dates-and-times.html#cb83-1"></a>b3 &lt;-<span class="st"> </span>births <span class="op">%&gt;%</span></span>
<span id="cb83-2"><a href="dates-and-times.html#cb83-2"></a><span class="st">  </span><span class="kw">mutate</span>(<span class="dt">year =</span> <span class="dv">2012</span>, <span class="dt">day =</span> <span class="dv">1</span>) <span class="op">%&gt;%</span></span>
<span id="cb83-3"><a href="dates-and-times.html#cb83-3"></a><span class="st">  </span><span class="kw">unite</span>(datestr, year, month, day) <span class="op">%&gt;%</span></span>
<span id="cb83-4"><a href="dates-and-times.html#cb83-4"></a><span class="st">  </span><span class="kw">mutate</span>(<span class="dt">thedate =</span> <span class="kw">ymd</span>(datestr)) <span class="op">%&gt;%</span></span>
<span id="cb83-5"><a href="dates-and-times.html#cb83-5"></a><span class="st">  </span><span class="kw">mutate</span>(<span class="dt">cesarean_rate =</span> cesarean <span class="op">/</span><span class="st"> </span>(cesarean <span class="op">+</span><span class="st"> </span>vaginal))</span>
<span id="cb83-6"><a href="dates-and-times.html#cb83-6"></a>b3</span></code></pre></div>
<p>I don’t mind which order you glue your year, month and day together,
as long as you construct the dates with the consistent
<code>lubridate</code> function.</p>
<p><span class="math inline">\(\blacksquare\)</span></p>
<ol start="3" style="list-style-type: lower-alpha">
<li>Plot the cesarean rate against time, with a smooth
trend. Do you see an upward trend, a downward trend, no trend, or
something else?</li>
</ol>
<p>Solution</p>
<p>This is a scatterplot with time on the <span class="math inline">\(x\)</span> axis:</p>
<div class="sourceCode" id="cb84"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb84-1"><a href="dates-and-times.html#cb84-1"></a><span class="kw">ggplot</span>(b2, <span class="kw">aes</span>(<span class="dt">x =</span> thedate, <span class="dt">y =</span> cesarean_rate)) <span class="op">+</span><span class="st"> </span><span class="kw">geom_point</span>() <span class="op">+</span><span class="st"> </span><span class="kw">geom_smooth</span>()</span></code></pre></div>
<pre><code>## `geom_smooth()` using method = &#39;loess&#39; and formula &#39;y ~ x&#39;</code></pre>
<p><img src="pasias_files/figure-html/unnamed-chunk-72-1.png" width="672" /></p>
<p>I like this better than joining the points by lines, since we already
have a trend on the plot, but you can do that in some contrasting way:</p>
<div class="sourceCode" id="cb86"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb86-1"><a href="dates-and-times.html#cb86-1"></a><span class="kw">ggplot</span>(b2, <span class="kw">aes</span>(<span class="dt">x =</span> thedate, <span class="dt">y =</span> cesarean_rate)) <span class="op">+</span><span class="st"> </span><span class="kw">geom_point</span>() <span class="op">+</span></span>
<span id="cb86-2"><a href="dates-and-times.html#cb86-2"></a><span class="st">  </span><span class="kw">geom_line</span>(<span class="dt">linetype =</span> <span class="st">&quot;dashed&quot;</span>) <span class="op">+</span><span class="st"> </span><span class="kw">geom_smooth</span>()</span></code></pre></div>
<pre><code>## `geom_smooth()` using method = &#39;loess&#39; and formula &#39;y ~ x&#39;</code></pre>
<p><img src="pasias_files/figure-html/unnamed-chunk-73-1.png" width="672" /></p>
<p>I see a downward trend. (“A downward trend with a wiggle” if you
like.) There is a certain unevenness
in the trend of the actual data, but the overall picture appears to be
downhill.</p>
<p><span class="math inline">\(\blacksquare\)</span></p>
<ol start="4" style="list-style-type: lower-alpha">
<li>Try to summarize the trend you just found with a
correlation. What goes wrong? How can you fix it?</li>
</ol>
<p>Solution</p>
<p>Something like this is the obvious guess:</p>
<div class="sourceCode" id="cb88"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb88-1"><a href="dates-and-times.html#cb88-1"></a><span class="kw">with</span>(b2, <span class="kw">cor</span>(thedate, cesarean_rate))</span></code></pre></div>
<pre><code>## Error in cor(thedate, cesarean_rate): &#39;x&#39; must be numeric</code></pre>
<p>This fails because <code>thedate</code> is not of itself a number. But
lurking in the background is how the date is actually
<em>represented</em>: as a number of days since Jan 1, 1970. Thus,
passing it through <code>as.numeric</code> might turn it into that:</p>
<div class="sourceCode" id="cb90"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb90-1"><a href="dates-and-times.html#cb90-1"></a>b2 <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">mutate</span>(<span class="dt">numeric_date =</span> <span class="kw">as.numeric</span>(thedate)) -&gt;<span class="st"> </span>b5</span>
<span id="cb90-2"><a href="dates-and-times.html#cb90-2"></a>b5</span></code></pre></div>
<p>A little mental calculation suggests that these dates in 2012 are a
bit over 40 years, that is <span class="math inline">\(40 \times 365 \simeq 14000\)</span> days, since
the “zero” date of Jan 1, 1970, and so it turns out. This suggests
that we can calculate a correlation with the numeric dates:</p>
<div class="sourceCode" id="cb91"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb91-1"><a href="dates-and-times.html#cb91-1"></a><span class="kw">with</span>(b5, <span class="kw">cor</span>(numeric_date, cesarean_rate))</span></code></pre></div>
<pre><code>## [1] -0.7091219</code></pre>
<p>and we can make a test of the null hypothesis that the correlation is
zero (against a two-sided alternative) thus:</p>
<div class="sourceCode" id="cb93"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb93-1"><a href="dates-and-times.html#cb93-1"></a><span class="kw">with</span>(b5, <span class="kw">cor.test</span>(numeric_date, cesarean_rate))</span></code></pre></div>
<pre><code>## 
##  Pearson&#39;s product-moment correlation
## 
## data:  numeric_date and cesarean_rate
## t = -3.1804, df = 10, p-value = 0.009813
## alternative hypothesis: true correlation is not equal to 0
## 95 percent confidence interval:
##  -0.9119078 -0.2280145
## sample estimates:
##        cor 
## -0.7091219</code></pre>
<p>That downward trend is more than just chance, with a P-value just
under 0.01. Having said that, though, if you look at the confidence
interval for the correlation, it includes almost all the negative
values it could be, so that with only 12 observations we really know
very little about the correlation other than that it appears to be
negative.</p>
<p>Extra:
In practice, you would typically have a much longer time series
of measurements than this, such as monthly measurements for
several years. In looking at only one year, like we did here,
we could get trapped by seasonal effects: for example, cesarean
rates might always go down through the year and then jump up
again in January. Looking at several years would enable us to
disentangle seasonal effects that happen every year from
long-term trends. (As an example of this, think of Toronto
snowfall: there is almost always snow in the winter and there
is never snow in the summer, a seasonal effect, but in
assessing climate change, you want to think about long-term
trends in snowfall, after allowing for which month you’re
looking at.)</p>
<p><span class="math inline">\(\blacksquare\)</span></p>
</div>
<div id="wolves-and-caribou-1" class="section level2" number="19.8">
<h2><span class="header-section-number">19.8</span> Wolves and caribou</h2>
<p>In Denali National Park, Alaska, the size of the wolf
population depends on the size of the caribou population (since
wolves hunt and kill caribou). This is a large national park, so
caribou are found in very large herds, so big, in fact, that the
well-being of the entire herd is not threatened by wolf
attacks.<a href="#fn19" class="footnote-ref" id="fnref19"><sup>19</sup></a>
Can the size of the caribou population
be used to predict the size of the wolf population?
The data can be found at
<a href="http://ritsokiguess.site/datafiles/caribou.txt">link</a>. The
columns
are: the date of the survey,<a href="#fn20" class="footnote-ref" id="fnref20"><sup>20</sup></a>
the name of the park employee in charge of the survey, the caribou population (in hundreds) and the wolf population (actual count).<a href="#fn21" class="footnote-ref" id="fnref21"><sup>21</sup></a></p>
<ol style="list-style-type: lower-alpha">
<li>Take a look at the data file. How would you describe its
format? Read it into R, and check that you got something sensible.</li>
</ol>
<p>Solution</p>
<p>This looks at first sight as if it’s separated by spaces, but
most of the data values are separated by <em>more than one</em>
space. If you look further, you’ll see that the values are
<em>lined up in columns</em>, with the variable names aligned at
the top. This is exactly the kind of thing that
<code>read_table</code> will read. We start with the usual
<code>library(tidyverse)</code>:</p>
<div class="sourceCode" id="cb95"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb95-1"><a href="dates-and-times.html#cb95-1"></a><span class="kw">library</span>(tidyverse)</span>
<span id="cb95-2"><a href="dates-and-times.html#cb95-2"></a>my_url &lt;-<span class="st"> &quot;http://ritsokiguess.site/datafiles/caribou.txt&quot;</span></span>
<span id="cb95-3"><a href="dates-and-times.html#cb95-3"></a>denali &lt;-<span class="st"> </span><span class="kw">read_table</span>(my_url)</span></code></pre></div>
<pre><code>## 
## ── Column specification ─────────────────────────────────────────────────
## cols(
##   date = col_character(),
##   name = col_character(),
##   caribou = col_double(),
##   wolf = col_double()
## )</code></pre>
<div class="sourceCode" id="cb97"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb97-1"><a href="dates-and-times.html#cb97-1"></a>denali</span></code></pre></div>
<p>That worked: four columns with the right names, and the counts of
caribou and wolf are numbers. There are only seven years of surveys;
in real-life data you would have more. But the point here is working
with dates.</p>
<p>The only (small) weirdness is that the
dates are text rather than having been converted into dates. This is
because they are not year-month-day, which is the only format that
gets automatically converted into dates when read in. (You could use
<code>mdy</code> from <code>lubridate</code> to make them dates.)</p>
<p>Extra: you might have wondered how the names survived, even though
they have spaces in them, sometimes more than one. Here’s how the file looks:</p>
<pre><code>
date       name             caribou wolf
09/01/1995 David S.         30       66
09/24/1996 Youngjin K.      34       79
10/03/1997 Srinivasan M.    27       70
09/15/1998 Lee Anne J.      25       60
09/08/1999 Stephanie T.     17       48
09/03/2000 Angus Mc D.      23       55
10/06/2001 David S.         20       60
</code></pre>
<p>What <code>read_table</code> looks for is columns that contain spaces
<em>all the way down</em>, and separates the values there. For example,
between the year of<code>date</code> and the first name in <code>name</code>
there is a space all the way down. After the names and before the
caribou counts there are several spaces, and there is one space
between the words <code>caribou</code> and <code>wolf</code> in the header
line that goes all the way down. Thus four columns, <code>date</code>,
<code>name</code>, <code>caribou</code> and <code>wolf</code>. This means that the
spaces within the names don’t cause any problems at all, since the
spaces aren’t in the same place in <em>every</em> line.<a href="#fn22" class="footnote-ref" id="fnref22"><sup>22</sup></a></p>
<p><span class="math inline">\(\blacksquare\)</span></p>
<ol start="2" style="list-style-type: lower-alpha">
<li>Create a new data frame where the column labelled
<code>date</code> is now a genuine R <code>Date</code>, using something
from <code>lubridate</code>.</li>
</ol>
<p>Solution</p>
<p>What you do is to look at the format of the dates as they are
now. They appear to be month-day-year, American
style.<a href="#fn23" class="footnote-ref" id="fnref23"><sup>23</sup></a><br />
Thus the function needed is <code>mdy</code>. It doesn’t matter
whether the months are names or numbers:</p>
<div class="sourceCode" id="cb99"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb99-1"><a href="dates-and-times.html#cb99-1"></a>denali <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">mutate</span>(<span class="dt">date =</span> <span class="kw">mdy</span>(date)) -&gt;<span class="st"> </span>denali</span>
<span id="cb99-2"><a href="dates-and-times.html#cb99-2"></a>denali</span></code></pre></div>
<p>I lived on the edge and overwrote both my column and the whole data
frame.<a href="#fn24" class="footnote-ref" id="fnref24"><sup>24</sup></a></p>
<p>The dates are displayed in ISO format, year-month-day. You see at the
top of the column that they now really <em>are</em> dates, not just
pieces of text that look like dates.</p>
<p><span class="math inline">\(\blacksquare\)</span></p>
<ol start="3" style="list-style-type: lower-alpha">
<li>Create new columns containing the days of
the week and the month names for the dates.</li>
</ol>
<p>Solution</p>
<p>This involves digging in the <code>lubridate</code> help to find out how to extract things from a date. It turns out that <code>wday</code> extracts the day of the week from a date, by default as a number, and <code>month</code> gets the month, also by default as a number:</p>
<div class="sourceCode" id="cb100"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb100-1"><a href="dates-and-times.html#cb100-1"></a>denali <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">mutate</span>(<span class="dt">mon =</span> <span class="kw">month</span>(date), <span class="dt">wd =</span> <span class="kw">wday</span>(date))</span></code></pre></div>
<p>This is not what we wanted, though; we wanted the names of the months
and of the days. To fix that, add <code>label=T</code> to both functions:</p>
<div class="sourceCode" id="cb101"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb101-1"><a href="dates-and-times.html#cb101-1"></a>denali <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">mutate</span>(<span class="dt">mon =</span> <span class="kw">month</span>(date, <span class="dt">label =</span> T), <span class="dt">wd =</span> <span class="kw">wday</span>(date, <span class="dt">label =</span> T))</span></code></pre></div>
<p>and that cracks it.</p>
<p>No need to save this data frame anywhere, since we’re not using any of
this later.</p>
<p>Extra: the <code>ord</code> means “ordered factor”, which makes sense
since these are categorical variables with a natural order. This means
that you could do something like counting the number of surveys in
each month like this:</p>
<div class="sourceCode" id="cb102"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb102-1"><a href="dates-and-times.html#cb102-1"></a>denali <span class="op">%&gt;%</span></span>
<span id="cb102-2"><a href="dates-and-times.html#cb102-2"></a><span class="st">  </span><span class="kw">mutate</span>(<span class="dt">mon =</span> <span class="kw">month</span>(date, <span class="dt">label =</span> T), <span class="dt">wd =</span> <span class="kw">wday</span>(date, <span class="dt">label =</span> T)) <span class="op">%&gt;%</span></span>
<span id="cb102-3"><a href="dates-and-times.html#cb102-3"></a><span class="st">  </span><span class="kw">count</span>(mon)</span></code></pre></div>
<p><span class="math inline">\(\blacksquare\)</span></p>
<ol start="4" style="list-style-type: lower-alpha">
<li>Enough playing around with dates. Make a scatterplot of
caribou population (explanatory) against wolf population
(response). Do you see any relationship?</li>
</ol>
<p>Solution</p>
<p>Nothing terribly surprising here:</p>
<div class="sourceCode" id="cb103"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb103-1"><a href="dates-and-times.html#cb103-1"></a><span class="kw">ggplot</span>(denali, <span class="kw">aes</span>(<span class="dt">x =</span> caribou, <span class="dt">y =</span> wolf)) <span class="op">+</span><span class="st"> </span><span class="kw">geom_point</span>()</span></code></pre></div>
<p><img src="pasias_files/figure-html/unnamed-chunk-83-1.png" width="672" /></p>
<p>If you like, add a smooth trend to it:<a href="#fn25" class="footnote-ref" id="fnref25"><sup>25</sup></a></p>
<div class="sourceCode" id="cb104"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb104-1"><a href="dates-and-times.html#cb104-1"></a><span class="kw">ggplot</span>(denali, <span class="kw">aes</span>(<span class="dt">x =</span> caribou, <span class="dt">y =</span> wolf)) <span class="op">+</span><span class="st"> </span><span class="kw">geom_point</span>() <span class="op">+</span><span class="st"> </span><span class="kw">geom_smooth</span>(<span class="dt">se =</span> F)</span></code></pre></div>
<pre><code>## `geom_smooth()` using method = &#39;loess&#39; and formula &#39;y ~ x&#39;</code></pre>
<p><img src="pasias_files/figure-html/unnamed-chunk-84-1.png" width="672" /></p>
<p>This is an upward trend: when one population is large, the other one
is large too. This is typical for predator-prey relationships: when
there is more to eat (more caribou) the wolf population goes up, and
when less, it goes down.</p>
<p><span class="math inline">\(\blacksquare\)</span></p>
<ol start="5" style="list-style-type: lower-alpha">
<li>On your plot from the previous part, label each point with
the year it belongs to. You can do this in two steps: first make a
new column containing just the years, and then use it as labels
for the points on the plot.</li>
</ol>
<p>Solution</p>
<p>I’m going to use <code>geom_text_repel</code> for the labels from package
<code>ggrepel</code>. The year values are gotten using the
<code>lubridate</code> function <code>year</code>:</p>
<div class="sourceCode" id="cb106"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb106-1"><a href="dates-and-times.html#cb106-1"></a>denali <span class="op">%&gt;%</span></span>
<span id="cb106-2"><a href="dates-and-times.html#cb106-2"></a><span class="st">  </span><span class="kw">mutate</span>(<span class="dt">year =</span> <span class="kw">year</span>(date)) <span class="op">%&gt;%</span></span>
<span id="cb106-3"><a href="dates-and-times.html#cb106-3"></a><span class="st">  </span><span class="kw">ggplot</span>(<span class="kw">aes</span>(<span class="dt">x =</span> caribou, <span class="dt">y =</span> wolf, <span class="dt">label =</span> year)) <span class="op">+</span><span class="st"> </span><span class="kw">geom_point</span>() <span class="op">+</span><span class="st"> </span><span class="kw">geom_text_repel</span>()</span></code></pre></div>
<p><img src="pasias_files/figure-html/unnamed-chunk-85-1.png" width="672" /></p>
<p>I thought about joining up the points in year order. This is actually
<em>not</em> <code>geom_line</code> as you would have guessed, since what that
does is to join points in the order of the variable on the
<span class="math inline">\(x\)</span>-axis.<a href="#fn26" class="footnote-ref" id="fnref26"><sup>26</sup></a>
To join points in the order that they are in the data (what we want
here, because the points are in time order in the data), use instead
<code>geom_path</code>:</p>
<div class="sourceCode" id="cb107"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb107-1"><a href="dates-and-times.html#cb107-1"></a>denali <span class="op">%&gt;%</span></span>
<span id="cb107-2"><a href="dates-and-times.html#cb107-2"></a><span class="st">  </span><span class="kw">mutate</span>(<span class="dt">year =</span> <span class="kw">year</span>(date)) <span class="op">%&gt;%</span></span>
<span id="cb107-3"><a href="dates-and-times.html#cb107-3"></a><span class="st">  </span><span class="kw">ggplot</span>(<span class="kw">aes</span>(<span class="dt">x =</span> caribou, <span class="dt">y =</span> wolf, <span class="dt">label =</span> year)) <span class="op">+</span><span class="st"> </span><span class="kw">geom_point</span>() <span class="op">+</span></span>
<span id="cb107-4"><a href="dates-and-times.html#cb107-4"></a><span class="st">  </span><span class="kw">geom_text_repel</span>() <span class="op">+</span><span class="st"> </span><span class="kw">geom_path</span>()</span></code></pre></div>
<p><img src="pasias_files/figure-html/unnamed-chunk-86-1.png" width="672" /></p>
<p>In 1996, both populations were large, and both showed a steady decline
until 1999. In 2000 and 2001, both populations seemed to be on the way
up again, and you can imagine that in a couple of years, things would
go back to about where they were in 1995.</p>
<p><span class="math inline">\(\blacksquare\)</span></p>
<ol start="6" style="list-style-type: lower-alpha">
<li>Make a plot of caribou population against time (this is done
the obvious way). What seems to be happening to the caribou
population over time?</li>
</ol>
<p>Solution</p>
<p>Make a scatterplot, with the survey date as explanatory
variable, and caribou population as response (since time always
goes on the <span class="math inline">\(x\)</span>-axis):</p>
<div class="sourceCode" id="cb108"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb108-1"><a href="dates-and-times.html#cb108-1"></a><span class="kw">ggplot</span>(denali, <span class="kw">aes</span>(<span class="dt">x =</span> date, <span class="dt">y =</span> caribou)) <span class="op">+</span><span class="st"> </span><span class="kw">geom_point</span>() <span class="op">+</span><span class="st"> </span><span class="kw">geom_line</span>()</span></code></pre></div>
<p><img src="pasias_files/figure-html/unnamed-chunk-87-1.png" width="672" /></p>
<p>I used an ordinary <code>geom_line</code> this time, to connect neighbouring
years, as is often done with a time series. The overall trend is
downward, though the 1999 value might be a low from which the
population is recovering.</p>
<p><span class="math inline">\(\blacksquare\)</span></p>
<ol start="7" style="list-style-type: lower-alpha">
<li>The caribou and wolf populations over time are
really “time series”.
See if you can make a plot of <em>both</em> the
caribou and wolf populations against time. You can make two
<span class="math inline">\(y\)</span>-axes, one for caribou and one for wolf; this will probably
require some research on your part to figure out.</li>
</ol>
<p>Solution</p>
<p>The obvious starting point is to note that both the
<code>caribou</code> and <code>wolf</code> columns are animal
populations, just of different animals. One way of plotting both
populations is to <code>pivot_longer</code> them up into one longer column, and
then plot them against time, with the two animals distinguished
by colour:</p>
<div class="sourceCode" id="cb109"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb109-1"><a href="dates-and-times.html#cb109-1"></a>denali <span class="op">%&gt;%</span></span>
<span id="cb109-2"><a href="dates-and-times.html#cb109-2"></a><span class="st">  </span><span class="kw">pivot_longer</span>(caribou<span class="op">:</span>wolf, <span class="dt">names_to=</span><span class="st">&quot;animal&quot;</span>, <span class="dt">values_to=</span><span class="st">&quot;population&quot;</span>) <span class="op">%&gt;%</span></span>
<span id="cb109-3"><a href="dates-and-times.html#cb109-3"></a><span class="st">  </span><span class="kw">ggplot</span>(<span class="kw">aes</span>(<span class="dt">x =</span> date, <span class="dt">y =</span> population, <span class="dt">colour =</span> animal)) <span class="op">+</span></span>
<span id="cb109-4"><a href="dates-and-times.html#cb109-4"></a><span class="st">  </span><span class="kw">geom_point</span>() <span class="op">+</span><span class="st"> </span><span class="kw">geom_line</span>()</span></code></pre></div>
<p><img src="pasias_files/figure-html/unnamed-chunk-88-1.png" width="672" /></p>
<p>This is not quite the story, though, because the caribou and wolf
populations are on different scales. The caribou population is
numbered in hundreds, while the wolf population is an actual count.</p>
<p>The surveys are late in the year, so the one that is nearly in 1996 is
actually the 1995 survey.</p>
<p>What would be nice would be to have a secondary <span class="math inline">\(y\)</span>-axis, so that
there were two <span class="math inline">\(y\)</span>-scales, one for each animal. This is very easy to
manipulate, though (you can change either scale and get a very
different-looking graph), so we ought to be careful.</p>
<p>All right, so let’s put the caribou on the left:</p>
<div class="sourceCode" id="cb110"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb110-1"><a href="dates-and-times.html#cb110-1"></a><span class="kw">ggplot</span>(denali, <span class="kw">aes</span>(<span class="dt">x =</span> date, <span class="dt">y =</span> caribou)) <span class="op">+</span><span class="st"> </span><span class="kw">geom_line</span>()</span></code></pre></div>
<p><img src="pasias_files/figure-html/unnamed-chunk-89-1.png" width="672" /></p>
<p>Or we can add a <code>colour</code> aesthetic to distinguish the caribou
from the wolf populations, that we’re going to add in a moment. This looks rather odd at first:</p>
<div class="sourceCode" id="cb111"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb111-1"><a href="dates-and-times.html#cb111-1"></a><span class="kw">ggplot</span>(denali, <span class="kw">aes</span>(<span class="dt">x =</span> date, <span class="dt">y =</span> caribou, <span class="dt">colour =</span> <span class="st">&quot;caribou&quot;</span>)) <span class="op">+</span><span class="st"> </span><span class="kw">geom_line</span>()</span></code></pre></div>
<p><img src="pasias_files/figure-html/unnamed-chunk-90-1.png" width="672" /></p>
<p>Now we think about adding the wolf numbers. This is done by adding a
second <code>geom_line</code>, overriding the <code>y</code> and the
<code>colour</code> to specify that this is wolf now:</p>
<div class="sourceCode" id="cb112"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb112-1"><a href="dates-and-times.html#cb112-1"></a><span class="kw">ggplot</span>(denali, <span class="kw">aes</span>(<span class="dt">x =</span> date, <span class="dt">y =</span> caribou, <span class="dt">colour =</span> <span class="st">&quot;caribou&quot;</span>)) <span class="op">+</span></span>
<span id="cb112-2"><a href="dates-and-times.html#cb112-2"></a><span class="st">  </span><span class="kw">geom_line</span>() <span class="op">+</span></span>
<span id="cb112-3"><a href="dates-and-times.html#cb112-3"></a><span class="st">  </span><span class="kw">geom_line</span>(<span class="kw">aes</span>(<span class="dt">y =</span> wolf, <span class="dt">colour =</span> <span class="st">&quot;wolf&quot;</span>))</span></code></pre></div>
<p><img src="pasias_files/figure-html/unnamed-chunk-91-1.png" width="672" /></p>
<p>What has happened is that we get lines of different colour for each
animal, with a legend. So far so good. The problem is that the wolf
numbers are about 2.5 times bigger than the caribou
numbers,<a href="#fn27" class="footnote-ref" id="fnref27"><sup>27</sup></a>
so that
we don’t get a good sense of how they go up and down together. If we
divided the wolf numbers by 2.5, we would see this better:</p>
<div class="sourceCode" id="cb113"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb113-1"><a href="dates-and-times.html#cb113-1"></a><span class="kw">ggplot</span>(denali, <span class="kw">aes</span>(<span class="dt">x =</span> date, <span class="dt">y =</span> caribou, <span class="dt">colour =</span> <span class="st">&quot;caribou&quot;</span>)) <span class="op">+</span></span>
<span id="cb113-2"><a href="dates-and-times.html#cb113-2"></a><span class="st">  </span><span class="kw">geom_line</span>() <span class="op">+</span></span>
<span id="cb113-3"><a href="dates-and-times.html#cb113-3"></a><span class="st">  </span><span class="kw">geom_line</span>(<span class="kw">aes</span>(<span class="dt">y =</span> wolf <span class="op">/</span><span class="st"> </span><span class="fl">2.5</span>, <span class="dt">colour =</span> <span class="st">&quot;wolf&quot;</span>))</span></code></pre></div>
<p><img src="pasias_files/figure-html/unnamed-chunk-92-1.png" width="672" /></p>
<p>Now we get to the secondary <span class="math inline">\(y\)</span>-axis. We want to label this
<code>wolf</code> and have it reflect that we actually made the graph by
dividing the wolf values by 2.5:</p>
<div class="sourceCode" id="cb114"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb114-1"><a href="dates-and-times.html#cb114-1"></a><span class="kw">ggplot</span>(denali, <span class="kw">aes</span>(<span class="dt">x =</span> date, <span class="dt">y =</span> caribou, <span class="dt">colour =</span> <span class="st">&quot;caribou&quot;</span>)) <span class="op">+</span></span>
<span id="cb114-2"><a href="dates-and-times.html#cb114-2"></a><span class="st">  </span><span class="kw">geom_line</span>() <span class="op">+</span></span>
<span id="cb114-3"><a href="dates-and-times.html#cb114-3"></a><span class="st">  </span><span class="kw">geom_line</span>(<span class="kw">aes</span>(<span class="dt">y =</span> wolf <span class="op">/</span><span class="st"> </span><span class="fl">2.5</span>, <span class="dt">colour =</span> <span class="st">&quot;wolf&quot;</span>)) <span class="op">+</span></span>
<span id="cb114-4"><a href="dates-and-times.html#cb114-4"></a><span class="st">  </span><span class="kw">scale_y_continuous</span>(<span class="dt">sec.axis =</span> <span class="kw">sec_axis</span>(<span class="op">~</span><span class="st"> </span>. <span class="op">*</span><span class="st"> </span><span class="fl">2.5</span>, <span class="dt">name =</span> <span class="st">&quot;wolf&quot;</span>))</span></code></pre></div>
<p><img src="pasias_files/figure-html/unnamed-chunk-93-1.png" width="672" /></p>
<p>Woo, and, very possibly, hoo. I got most of these ideas from
<a href="https://rpubs.com/MarkusLoew/226759">link</a>.</p>
<p>Now we see how the populations vary over time, and also that they vary
together.</p>
<p>This is about the only double-<span class="math inline">\(y\)</span>-axis setup that I like, with scales
chosen so that both the series vary about the same amount. By
“discreetly” changing the wolf scale, you could make it look as if
one population was much bigger than the other, or varied much more
than the other. Lies and statistics.</p>
<p>In my opinion, too many people just plot series against time, possibly
with a second <span class="math inline">\(y\)</span>-axis.<a href="#fn28" class="footnote-ref" id="fnref28"><sup>28</sup></a>
Variables that vary together, like the wolf
and caribou populations here, ought to be plotted  on a scatterplot, possibly with the time points labelled.</p>
<p>The ambitious among you may like to compare the graphs here with
other predator-prey relationships. If you are of a mathematical bent,
you might look into the Lotka-Volterra equations, which is a system of
two differential equations describing how changes in one population
cause changes in the other population.</p>
<p><span class="math inline">\(\blacksquare\)</span></p>
</div>
<div id="dealing-with-dates-in-the-worcester-heart-attack-study-1" class="section level2" number="19.9">
<h2><span class="header-section-number">19.9</span> Dealing with dates in the Worcester Heart Attack study</h2>
<p>The Worcester Heart Attack Study is an ongoing study of
heart attacks in the Worcester, MA area. The main purpose of the study
is to investigate changes over time in incidence and death rates, and also
the use of different treatment approaches. We will be mainly using
this data set to investigate data handling and dealing with dates. The
data can be found at
<a href="http://ritsokiguess.site/datafiles/whas500.txt">link</a>.</p>
<ol style="list-style-type: lower-alpha">
<li>Read the data into R. The reading-in part is
straightforward, but check what type of thing each column is. Is
that what it should be?</li>
</ol>
<p>Solution</p>
<p>This is <code>read_delim</code>:</p>
<div class="sourceCode" id="cb115"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb115-1"><a href="dates-and-times.html#cb115-1"></a>my_url &lt;-<span class="st"> &quot;http://ritsokiguess.site/datafiles/whas500.txt&quot;</span></span>
<span id="cb115-2"><a href="dates-and-times.html#cb115-2"></a>whas &lt;-<span class="st"> </span><span class="kw">read_delim</span>(my_url, <span class="st">&quot; &quot;</span>)</span></code></pre></div>
<pre><code>## 
## ── Column specification ─────────────────────────────────────────────────
## cols(
##   .default = col_double(),
##   admitdate = col_character(),
##   disdate = col_character(),
##   fdate = col_character()
## )
## ℹ Use `spec()` for the full column specifications.</code></pre>
<div class="sourceCode" id="cb117"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb117-1"><a href="dates-and-times.html#cb117-1"></a>whas</span></code></pre></div>
<p>To see what type everything is, note that when you display a
<code>tibble</code>, the type of all the columns on the screen is
displayed at the top. Click the little right-arrow to see more columns
and to check their type.</p>
<p>All the numbers are properly integer (<code>int</code>) or decimal
(<code>dbl</code>) numbers, but the date columns are <code>chr</code> or
text. This means that they haven’t been read as <code>Date</code>s
(because they were not in year-month-day order). This is (as we will
see) unlike SAS, which determined that they were dates, and even used
the first 20 rows of the file to determine what format of dates they
were.</p>
<p><span class="math inline">\(\blacksquare\)</span></p>
<ol start="2" style="list-style-type: lower-alpha">
<li>The date columns should be R dates. They are not
year-month-day, so converting them via <code>as.Date</code> (which is
what <code>read_delim</code> tries to do) will not work. Load the
<code>lubridate</code> package, and create new columns in your data
frame that are properly dates. Save your data frame, and list it to
demonstrate that it worked.</li>
</ol>
<p>Solution</p>
<p>Load <code>lubridate</code> first:</p>
<div class="sourceCode" id="cb118"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb118-1"><a href="dates-and-times.html#cb118-1"></a><span class="kw">library</span>(lubridate)</span></code></pre></div>
<p>These dates are day-month-year, so we need <code>dmy</code> from
<code>lubridate</code>:</p>
<div class="sourceCode" id="cb119"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb119-1"><a href="dates-and-times.html#cb119-1"></a>whas <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">mutate</span>(</span>
<span id="cb119-2"><a href="dates-and-times.html#cb119-2"></a>  <span class="dt">admit =</span> <span class="kw">dmy</span>(admitdate),</span>
<span id="cb119-3"><a href="dates-and-times.html#cb119-3"></a>  <span class="dt">dis =</span> <span class="kw">dmy</span>(disdate),</span>
<span id="cb119-4"><a href="dates-and-times.html#cb119-4"></a>  <span class="dt">f =</span> <span class="kw">dmy</span>(fdate)</span>
<span id="cb119-5"><a href="dates-and-times.html#cb119-5"></a>) -&gt;<span class="st"> </span>whas2</span>
<span id="cb119-6"><a href="dates-and-times.html#cb119-6"></a><span class="kw">glimpse</span>(whas2)</span></code></pre></div>
<pre><code>## Rows: 500
## Columns: 25
## $ id        &lt;dbl&gt; 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16…
## $ age       &lt;dbl&gt; 83, 49, 70, 70, 70, 70, 57, 55, 88, 54, 48, 75, 48, 5…
## $ gender    &lt;dbl&gt; 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1,…
## $ hr        &lt;dbl&gt; 89, 84, 83, 65, 63, 76, 73, 91, 63, 104, 95, 154, 85,…
## $ sysbp     &lt;dbl&gt; 152, 120, 147, 123, 135, 83, 191, 147, 209, 166, 160,…
## $ diasbp    &lt;dbl&gt; 78, 60, 88, 76, 85, 54, 116, 95, 100, 106, 110, 123, …
## $ bmi       &lt;dbl&gt; 25.54051, 24.02398, 22.14290, 26.63187, 24.41255, 23.…
## $ cvd       &lt;dbl&gt; 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 1, 0,…
## $ afb       &lt;dbl&gt; 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0,…
## $ sho       &lt;dbl&gt; 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,…
## $ chf       &lt;dbl&gt; 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1,…
## $ av3       &lt;dbl&gt; 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,…
## $ miord     &lt;dbl&gt; 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0,…
## $ mitype    &lt;dbl&gt; 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1,…
## $ year      &lt;dbl&gt; 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,…
## $ admitdate &lt;chr&gt; &quot;13-01-1997&quot;, &quot;19-01-1997&quot;, &quot;01-01-1997&quot;, &quot;17-02-1997…
## $ disdate   &lt;chr&gt; &quot;18-01-1997&quot;, &quot;24-01-1997&quot;, &quot;06-01-1997&quot;, &quot;27-02-1997…
## $ fdate     &lt;chr&gt; &quot;31-12-2002&quot;, &quot;31-12-2002&quot;, &quot;31-12-2002&quot;, &quot;11-12-1997…
## $ los       &lt;dbl&gt; 5, 5, 5, 10, 6, 1, 5, 4, 4, 5, 5, 10, 7, 21, 4, 1, 13…
## $ dstat     &lt;dbl&gt; 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,…
## $ lenfol    &lt;dbl&gt; 2178, 2172, 2190, 297, 2131, 1, 2122, 1496, 920, 2175…
## $ fstat     &lt;dbl&gt; 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1,…
## $ admit     &lt;date&gt; 1997-01-13, 1997-01-19, 1997-01-01, 1997-02-17, 1997…
## $ dis       &lt;date&gt; 1997-01-18, 1997-01-24, 1997-01-06, 1997-02-27, 1997…
## $ f         &lt;date&gt; 2002-12-31, 2002-12-31, 2002-12-31, 1997-12-11, 2002…</code></pre>
<p>There are a lot of columns, so I used <code>glimpse</code>. The three new
variables we created are at the end of the list. They are correctly
<code>Date</code>s, and they have the right values, the ones we can see at
least.</p>
<p>The indentation is up to you. I think it’s nice to make the
creations of the three new variables line up. You can also make the
opening and closing brackets on the long <code>mutate</code> aligned, or
you can do as I have done here and put two closing brackets on the
end. The rationale for this is that each of the variable definition
lines in the <code>mutate</code> ends either with a comma or an extra
closing bracket, the latter being on the last line. Your choice here is
a matter of taste or (in your working life) the coding norms of the
team you’re working with.</p>
<p>Extra: you may have been offended by the repetition above. It so happens that
these columns’ names all end in <code>date</code> and they are the only
ones that do, so we can use a “select helper” to select only them,
and then submit all of them to a <code>mutate</code> via <code>across</code>,
which goes like this:</p>
<div class="sourceCode" id="cb121"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb121-1"><a href="dates-and-times.html#cb121-1"></a>whas <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">mutate</span>(<span class="kw">across</span>(<span class="kw">ends_with</span>(<span class="st">&quot;date&quot;</span>), <span class="op">~</span><span class="kw">dmy</span>(.))) <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">glimpse</span>()</span></code></pre></div>
<pre><code>## Rows: 500
## Columns: 22
## $ id        &lt;dbl&gt; 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16…
## $ age       &lt;dbl&gt; 83, 49, 70, 70, 70, 70, 57, 55, 88, 54, 48, 75, 48, 5…
## $ gender    &lt;dbl&gt; 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1,…
## $ hr        &lt;dbl&gt; 89, 84, 83, 65, 63, 76, 73, 91, 63, 104, 95, 154, 85,…
## $ sysbp     &lt;dbl&gt; 152, 120, 147, 123, 135, 83, 191, 147, 209, 166, 160,…
## $ diasbp    &lt;dbl&gt; 78, 60, 88, 76, 85, 54, 116, 95, 100, 106, 110, 123, …
## $ bmi       &lt;dbl&gt; 25.54051, 24.02398, 22.14290, 26.63187, 24.41255, 23.…
## $ cvd       &lt;dbl&gt; 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 1, 0,…
## $ afb       &lt;dbl&gt; 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0,…
## $ sho       &lt;dbl&gt; 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,…
## $ chf       &lt;dbl&gt; 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1,…
## $ av3       &lt;dbl&gt; 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,…
## $ miord     &lt;dbl&gt; 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0,…
## $ mitype    &lt;dbl&gt; 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1,…
## $ year      &lt;dbl&gt; 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,…
## $ admitdate &lt;date&gt; 1997-01-13, 1997-01-19, 1997-01-01, 1997-02-17, 1997…
## $ disdate   &lt;date&gt; 1997-01-18, 1997-01-24, 1997-01-06, 1997-02-27, 1997…
## $ fdate     &lt;date&gt; 2002-12-31, 2002-12-31, 2002-12-31, 1997-12-11, 2002…
## $ los       &lt;dbl&gt; 5, 5, 5, 10, 6, 1, 5, 4, 4, 5, 5, 10, 7, 21, 4, 1, 13…
## $ dstat     &lt;dbl&gt; 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,…
## $ lenfol    &lt;dbl&gt; 2178, 2172, 2190, 297, 2131, 1, 2122, 1496, 920, 2175…
## $ fstat     &lt;dbl&gt; 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1,…</code></pre>
<p>One line, as you see, not three. The English-language version of this reads “for each of the columns whose
name ends with <code>date</code>, work out <code>dmy</code> of it”, that is to say, convert it into a date.
We can use any of the
select-helpers in this, including listing the column numbers or
names; in this case our date variables all ended with
<code>date</code>.</p>
<p>This overwrites the original date columns (you can see that they are now <code>date</code>s), but you can give them new names thus. This is inside the <code>across</code> inside the <code>mutate</code>, so it needs two close-brackets after (the probable reason for the error if you get one):</p>
<div class="sourceCode" id="cb123"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb123-1"><a href="dates-and-times.html#cb123-1"></a>whas <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">mutate</span>(<span class="kw">across</span>(<span class="kw">ends_with</span>(<span class="st">&quot;date&quot;</span>), <span class="op">~</span><span class="kw">dmy</span>(.), <span class="dt">.names =</span> <span class="st">&quot;{.col}_d&quot;</span>)) <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">glimpse</span>()</span></code></pre></div>
<pre><code>## Rows: 500
## Columns: 25
## $ id          &lt;dbl&gt; 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, …
## $ age         &lt;dbl&gt; 83, 49, 70, 70, 70, 70, 57, 55, 88, 54, 48, 75, 48,…
## $ gender      &lt;dbl&gt; 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, …
## $ hr          &lt;dbl&gt; 89, 84, 83, 65, 63, 76, 73, 91, 63, 104, 95, 154, 8…
## $ sysbp       &lt;dbl&gt; 152, 120, 147, 123, 135, 83, 191, 147, 209, 166, 16…
## $ diasbp      &lt;dbl&gt; 78, 60, 88, 76, 85, 54, 116, 95, 100, 106, 110, 123…
## $ bmi         &lt;dbl&gt; 25.54051, 24.02398, 22.14290, 26.63187, 24.41255, 2…
## $ cvd         &lt;dbl&gt; 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 1, …
## $ afb         &lt;dbl&gt; 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, …
## $ sho         &lt;dbl&gt; 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, …
## $ chf         &lt;dbl&gt; 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, …
## $ av3         &lt;dbl&gt; 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, …
## $ miord       &lt;dbl&gt; 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, …
## $ mitype      &lt;dbl&gt; 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, …
## $ year        &lt;dbl&gt; 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, …
## $ admitdate   &lt;chr&gt; &quot;13-01-1997&quot;, &quot;19-01-1997&quot;, &quot;01-01-1997&quot;, &quot;17-02-19…
## $ disdate     &lt;chr&gt; &quot;18-01-1997&quot;, &quot;24-01-1997&quot;, &quot;06-01-1997&quot;, &quot;27-02-19…
## $ fdate       &lt;chr&gt; &quot;31-12-2002&quot;, &quot;31-12-2002&quot;, &quot;31-12-2002&quot;, &quot;11-12-19…
## $ los         &lt;dbl&gt; 5, 5, 5, 10, 6, 1, 5, 4, 4, 5, 5, 10, 7, 21, 4, 1, …
## $ dstat       &lt;dbl&gt; 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, …
## $ lenfol      &lt;dbl&gt; 2178, 2172, 2190, 297, 2131, 1, 2122, 1496, 920, 21…
## $ fstat       &lt;dbl&gt; 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, …
## $ admitdate_d &lt;date&gt; 1997-01-13, 1997-01-19, 1997-01-01, 1997-02-17, 19…
## $ disdate_d   &lt;date&gt; 1997-01-18, 1997-01-24, 1997-01-06, 1997-02-27, 19…
## $ fdate_d     &lt;date&gt; 2002-12-31, 2002-12-31, 2002-12-31, 1997-12-11, 20…</code></pre>
<p>The three columns on the end are the new actual-dates we created. To give them new names, use <code>.names</code> inside <code>across</code>, and in <em>that</em> is a recipe that says how to make the new names. <code>{.col}</code> means the name the column had before, and the <code>_d</code> after that means to add that to the old name to make the new one.</p>
<p><span class="math inline">\(\blacksquare\)</span></p>
<ol start="3" style="list-style-type: lower-alpha">
<li>Create three new variables <code>diff1, diff2, diff3</code> that
are the numbers of days between each of your dates, and save the
data frame in which they have been created. Verify that at
least some of them are the same as <code>los</code> and <code>lenfol</code>.</li>
</ol>
<p>Solution</p>
<p>I don’t know
what R’s internal storage is for dates (it might be seconds or
milliseconds or anything, not necessarily days),
so subtracting them requires care; you have to divide by the
length of a day (in whatever units), thus:</p>
<div class="sourceCode" id="cb125"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb125-1"><a href="dates-and-times.html#cb125-1"></a>whas3 &lt;-<span class="st"> </span>whas2 <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">mutate</span>(</span>
<span id="cb125-2"><a href="dates-and-times.html#cb125-2"></a>  <span class="dt">diff1 =</span> (dis <span class="op">-</span><span class="st"> </span>admit) <span class="op">/</span><span class="st"> </span><span class="kw">ddays</span>(<span class="dv">1</span>),</span>
<span id="cb125-3"><a href="dates-and-times.html#cb125-3"></a>  <span class="dt">diff2 =</span> (f <span class="op">-</span><span class="st"> </span>admit) <span class="op">/</span><span class="st"> </span><span class="kw">ddays</span>(<span class="dv">1</span>),</span>
<span id="cb125-4"><a href="dates-and-times.html#cb125-4"></a>  <span class="dt">diff3 =</span> (f <span class="op">-</span><span class="st"> </span>dis) <span class="op">/</span><span class="st"> </span><span class="kw">ddays</span>(<span class="dv">1</span>)</span>
<span id="cb125-5"><a href="dates-and-times.html#cb125-5"></a>)</span>
<span id="cb125-6"><a href="dates-and-times.html#cb125-6"></a><span class="kw">glimpse</span>(whas3)</span></code></pre></div>
<pre><code>## Rows: 500
## Columns: 28
## $ id        &lt;dbl&gt; 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16…
## $ age       &lt;dbl&gt; 83, 49, 70, 70, 70, 70, 57, 55, 88, 54, 48, 75, 48, 5…
## $ gender    &lt;dbl&gt; 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1,…
## $ hr        &lt;dbl&gt; 89, 84, 83, 65, 63, 76, 73, 91, 63, 104, 95, 154, 85,…
## $ sysbp     &lt;dbl&gt; 152, 120, 147, 123, 135, 83, 191, 147, 209, 166, 160,…
## $ diasbp    &lt;dbl&gt; 78, 60, 88, 76, 85, 54, 116, 95, 100, 106, 110, 123, …
## $ bmi       &lt;dbl&gt; 25.54051, 24.02398, 22.14290, 26.63187, 24.41255, 23.…
## $ cvd       &lt;dbl&gt; 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 1, 0,…
## $ afb       &lt;dbl&gt; 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0,…
## $ sho       &lt;dbl&gt; 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,…
## $ chf       &lt;dbl&gt; 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1,…
## $ av3       &lt;dbl&gt; 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,…
## $ miord     &lt;dbl&gt; 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0,…
## $ mitype    &lt;dbl&gt; 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1,…
## $ year      &lt;dbl&gt; 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,…
## $ admitdate &lt;chr&gt; &quot;13-01-1997&quot;, &quot;19-01-1997&quot;, &quot;01-01-1997&quot;, &quot;17-02-1997…
## $ disdate   &lt;chr&gt; &quot;18-01-1997&quot;, &quot;24-01-1997&quot;, &quot;06-01-1997&quot;, &quot;27-02-1997…
## $ fdate     &lt;chr&gt; &quot;31-12-2002&quot;, &quot;31-12-2002&quot;, &quot;31-12-2002&quot;, &quot;11-12-1997…
## $ los       &lt;dbl&gt; 5, 5, 5, 10, 6, 1, 5, 4, 4, 5, 5, 10, 7, 21, 4, 1, 13…
## $ dstat     &lt;dbl&gt; 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,…
## $ lenfol    &lt;dbl&gt; 2178, 2172, 2190, 297, 2131, 1, 2122, 1496, 920, 2175…
## $ fstat     &lt;dbl&gt; 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1,…
## $ admit     &lt;date&gt; 1997-01-13, 1997-01-19, 1997-01-01, 1997-02-17, 1997…
## $ dis       &lt;date&gt; 1997-01-18, 1997-01-24, 1997-01-06, 1997-02-27, 1997…
## $ f         &lt;date&gt; 2002-12-31, 2002-12-31, 2002-12-31, 1997-12-11, 2002…
## $ diff1     &lt;dbl&gt; 5, 5, 5, 10, 6, 1, 5, 4, 4, 5, 5, 10, 7, 21, 4, 1, 13…
## $ diff2     &lt;dbl&gt; 2178, 2172, 2190, 297, 2131, 1, 2122, 1496, 920, 2175…
## $ diff3     &lt;dbl&gt; 2173, 2167, 2185, 287, 2125, 0, 2117, 1492, 916, 2170…</code></pre>
<p>The extra <code>d</code> on the front of <code>ddays</code> indicates that
these are what is known to <code>lubridate</code> as “durations”: a
period of time 1 day long that could be any day (as opposed to
“June 1, 1970” which is 1 day long, but tied to a particular day).</p>
<p><code>los</code> should be the number of days in hospital, what I
calculated as <code>diff1</code>, and <code>lenfol</code> should be the time
from being admitted to last followup, which is my <code>diff2</code>. My
output from <code>glimpse</code> confirms that.</p>
<p>Extra: of course, checking that the first few values match is a nice
confirmation, but is not actually a <em>proof</em>. For that, we should
compare all 500 values, and it would be best to do it in such a way
that R is comparing all 500 values for us, since it would be a lot
more reliable than the human eye. R has a function <code>all.equal</code>
which does exactly that. By way of warmup:</p>
<div class="sourceCode" id="cb127"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb127-1"><a href="dates-and-times.html#cb127-1"></a>x &lt;-<span class="st"> </span><span class="dv">1</span><span class="op">:</span><span class="dv">4</span></span>
<span id="cb127-2"><a href="dates-and-times.html#cb127-2"></a>y &lt;-<span class="st"> </span><span class="dv">1</span><span class="op">:</span><span class="dv">4</span></span>
<span id="cb127-3"><a href="dates-and-times.html#cb127-3"></a>z &lt;-<span class="st"> </span><span class="kw">c</span>(<span class="dv">1</span>, <span class="dv">2</span>, <span class="dv">3</span>, <span class="dv">5</span>)</span>
<span id="cb127-4"><a href="dates-and-times.html#cb127-4"></a><span class="kw">all.equal</span>(x, y)</span></code></pre></div>
<pre><code>## [1] TRUE</code></pre>
<div class="sourceCode" id="cb129"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb129-1"><a href="dates-and-times.html#cb129-1"></a><span class="kw">all.equal</span>(x, z)</span></code></pre></div>
<pre><code>## [1] &quot;Mean relative difference: 0.25&quot;</code></pre>
<p>I thought the second one was just going to say <code>FALSE</code>, but it
gave us a message instead, saying how close <code>x</code> and <code>z</code>
were on average, so that we could decide whether they were close
enough to call equal, or, as in this case, not.</p>
<p>Anyway:</p>
<div class="sourceCode" id="cb131"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb131-1"><a href="dates-and-times.html#cb131-1"></a><span class="kw">with</span>(whas3, <span class="kw">all.equal</span>(lenfol, diff2))</span></code></pre></div>
<pre><code>## [1] TRUE</code></pre>
<div class="sourceCode" id="cb133"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb133-1"><a href="dates-and-times.html#cb133-1"></a><span class="kw">with</span>(whas3, <span class="kw">all.equal</span>(los, diff1))</span></code></pre></div>
<pre><code>## [1] TRUE</code></pre>
<p>so they really are all equal, all 500 of them.<a href="#fn29" class="footnote-ref" id="fnref29"><sup>29</sup></a></p>
<p><span class="math inline">\(\blacksquare\)</span></p>
<ol start="4" style="list-style-type: lower-alpha">
<li>Construct side-by-side boxplots of the length of followup by
each followup status. You’ll need to make sure
that the followup status, as it gets fed into <code>ggplot</code>, is a
<code>factor</code>, or, at least, not the number that it is now.</li>
</ol>
<p>Solution</p>
<p>The easiest way to make a factor is to wrap <code>fstat</code>, which
is a numeric 0 or 1, in <code>factor()</code>:</p>
<div class="sourceCode" id="cb135"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb135-1"><a href="dates-and-times.html#cb135-1"></a><span class="kw">ggplot</span>(whas3, <span class="kw">aes</span>(<span class="dt">x =</span> <span class="kw">factor</span>(fstat), <span class="dt">y =</span> lenfol)) <span class="op">+</span><span class="st"> </span><span class="kw">geom_boxplot</span>()</span></code></pre></div>
<p><img src="pasias_files/figure-html/unnamed-chunk-102-1.png" width="672" /></p>
<p>Or create a factor version of <code>fstat</code> first:</p>
<div class="sourceCode" id="cb136"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb136-1"><a href="dates-and-times.html#cb136-1"></a>whas3 <span class="op">%&gt;%</span></span>
<span id="cb136-2"><a href="dates-and-times.html#cb136-2"></a><span class="st">  </span><span class="kw">mutate</span>(<span class="dt">ffstat =</span> <span class="kw">factor</span>(fstat)) <span class="op">%&gt;%</span></span>
<span id="cb136-3"><a href="dates-and-times.html#cb136-3"></a><span class="st">  </span><span class="kw">ggplot</span>(<span class="kw">aes</span>(<span class="dt">x =</span> ffstat, <span class="dt">y =</span> lenfol)) <span class="op">+</span><span class="st"> </span><span class="kw">geom_boxplot</span>()</span></code></pre></div>
<p><img src="pasias_files/figure-html/unnamed-chunk-103-1.png" width="672" /></p>
<p>I think the second way looks better, because you
get a cleaner <span class="math inline">\(x\)</span>-axis on your plot. But if you’re doing this for
exploration, rather than as something that’s going to appear in a
report for your boss, the first way is fine.</p>
<p><code>ggplot</code> also treats text stuff as categorical where needed, so
this also works:</p>
<div class="sourceCode" id="cb137"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb137-1"><a href="dates-and-times.html#cb137-1"></a>whas3 <span class="op">%&gt;%</span></span>
<span id="cb137-2"><a href="dates-and-times.html#cb137-2"></a><span class="st">  </span><span class="kw">mutate</span>(<span class="dt">cfstat =</span> <span class="kw">as.character</span>(fstat)) <span class="op">%&gt;%</span></span>
<span id="cb137-3"><a href="dates-and-times.html#cb137-3"></a><span class="st">  </span><span class="kw">ggplot</span>(<span class="kw">aes</span>(<span class="dt">x =</span> cfstat, <span class="dt">y =</span> lenfol)) <span class="op">+</span><span class="st"> </span><span class="kw">geom_boxplot</span>()</span></code></pre></div>
<p><img src="pasias_files/figure-html/unnamed-chunk-104-1.png" width="672" /></p>
<p>Extra: this is an example of what’s called “survival data”: the purpose of the study was to see what affected how long a person survived after a heart attack. Each patient was followed up for the number of days in <code>lenfol</code>, but followup could have stopped for two (or more) reasons: the patient died (indicated by <code>fstat</code> being 1), or something else happened to them (<code>fstat</code> is 0), such as moving away from where the study was conducted, getting another disease, the funding for this study running out, or simply losing touch with the people doing the study. Such a patient is called “lost to followup” or “censored”, and all we know about their survival is that they were still alive when last seen, but we don’t know how long they lived after that.</p>
<p>For example:</p>
<div class="sourceCode" id="cb138"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb138-1"><a href="dates-and-times.html#cb138-1"></a>whas <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">select</span>(id, lenfol, fstat)</span></code></pre></div>
<p>The patient with id 4 died after 297 days, but patients 1 through 3 lived for over 2000 days and were still alive when last seen. My guess for patients 1 through 3 is that the study ended and they were still alive:</p>
<div class="sourceCode" id="cb139"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb139-1"><a href="dates-and-times.html#cb139-1"></a>whas <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">summarize</span>(<span class="dt">maxfol =</span> <span class="kw">max</span>(lenfol)<span class="op">/</span><span class="fl">365.25</span>)</span></code></pre></div>
<p>The longest time anyone was followed up was six and a half years. Studies like this are funded for some number of years (say 10), and people can join after the beginning. (If they happen to join near the end, they won’t get followed up for very long.)</p>
<p>We’re not going to analyze these data, but if we were, we would want to take advantage of the information in the patient who lived for “at least 2178 days”. Looking only at the patients who we knew to have died would be wasteful and might introduce a bias; for example, if we were comparing several treatments, and one of the treatments was so good that almost everybody on it was still alive at the end, we would want to have a strong inference that this treatment was the best.</p>
<p>With that in mind, let’s redraw our boxplot with better labels for the followup status:</p>
<div class="sourceCode" id="cb140"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb140-1"><a href="dates-and-times.html#cb140-1"></a>whas3 <span class="op">%&gt;%</span><span class="st"> </span></span>
<span id="cb140-2"><a href="dates-and-times.html#cb140-2"></a><span class="st">  </span><span class="kw">mutate</span>(<span class="dt">followup_status =</span> <span class="kw">ifelse</span>(fstat <span class="op">==</span><span class="st"> </span><span class="dv">1</span>, <span class="st">&quot;died&quot;</span>, <span class="st">&quot;censored&quot;</span>)) <span class="op">%&gt;%</span><span class="st"> </span></span>
<span id="cb140-3"><a href="dates-and-times.html#cb140-3"></a><span class="st">  </span><span class="kw">ggplot</span>(<span class="kw">aes</span>(<span class="dt">x =</span> followup_status, <span class="dt">y =</span> lenfol)) <span class="op">+</span><span class="st"> </span><span class="kw">geom_boxplot</span>()</span></code></pre></div>
<p><img src="pasias_files/figure-html/unnamed-chunk-107-1.png" width="672" /></p>
<p>Now we have a clearer sense of what is going on. Out of the patients who died, some of them survived a long time, but most of them died fairly quickly. Out of the patients who were censored, the times they were observed were all over the place, which suggests that (at least for the ones still in the study at the end) they joined the study at all kinds of different times.</p>
<p>Another graph that is possible here is a facetted histogram:</p>
<div class="sourceCode" id="cb141"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb141-1"><a href="dates-and-times.html#cb141-1"></a>whas3 <span class="op">%&gt;%</span><span class="st"> </span></span>
<span id="cb141-2"><a href="dates-and-times.html#cb141-2"></a><span class="st">  </span><span class="kw">mutate</span>(<span class="dt">followup_status =</span> <span class="kw">ifelse</span>(fstat <span class="op">==</span><span class="st"> </span><span class="dv">1</span>, <span class="st">&quot;died&quot;</span>, <span class="st">&quot;censored&quot;</span>)) <span class="op">%&gt;%</span><span class="st"> </span></span>
<span id="cb141-3"><a href="dates-and-times.html#cb141-3"></a><span class="st">  </span><span class="kw">ggplot</span>(<span class="kw">aes</span>(<span class="dt">x =</span> lenfol)) <span class="op">+</span><span class="st"> </span><span class="kw">geom_histogram</span>(<span class="dt">bins =</span> <span class="dv">10</span>) <span class="op">+</span></span>
<span id="cb141-4"><a href="dates-and-times.html#cb141-4"></a><span class="st">  </span><span class="kw">facet_wrap</span>(<span class="op">~</span>followup_status)</span></code></pre></div>
<p><img src="pasias_files/figure-html/unnamed-chunk-108-1.png" width="672" /></p>
<p>The right-skewed distribution of times to death is what we saw from the boxplot, but what is that periodic thing on the left? Let’s convert the days to years and draw again:</p>
<div class="sourceCode" id="cb142"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb142-1"><a href="dates-and-times.html#cb142-1"></a>whas3 <span class="op">%&gt;%</span><span class="st"> </span></span>
<span id="cb142-2"><a href="dates-and-times.html#cb142-2"></a><span class="st">  </span><span class="kw">mutate</span>(<span class="dt">followup_status =</span> <span class="kw">ifelse</span>(fstat <span class="op">==</span><span class="st"> </span><span class="dv">1</span>, <span class="st">&quot;died&quot;</span>, <span class="st">&quot;censored&quot;</span>)) <span class="op">%&gt;%</span><span class="st"> </span></span>
<span id="cb142-3"><a href="dates-and-times.html#cb142-3"></a><span class="st">  </span><span class="kw">mutate</span>(<span class="dt">followup_years =</span> lenfol<span class="op">/</span><span class="fl">365.25</span>) <span class="op">%&gt;%</span><span class="st"> </span></span>
<span id="cb142-4"><a href="dates-and-times.html#cb142-4"></a><span class="st">  </span><span class="kw">ggplot</span>(<span class="kw">aes</span>(<span class="dt">x =</span> followup_years)) <span class="op">+</span><span class="st"> </span><span class="kw">geom_histogram</span>(<span class="dt">bins =</span> <span class="dv">20</span>) <span class="op">+</span></span>
<span id="cb142-5"><a href="dates-and-times.html#cb142-5"></a><span class="st">  </span><span class="kw">facet_wrap</span>(<span class="op">~</span>followup_status)</span></code></pre></div>
<p><img src="pasias_files/figure-html/unnamed-chunk-109-1.png" width="672" /></p>
<p>That’s odd. On the left, it looks as if there were bursts of patients admitted to the study at around 1.5, 3.5, and 5.5 years from the end. (These are, remember, all people who survived and mostly people who survived to the end.) Not what I would have expected – I would have expected a steady stream of patients, the heart attack victims as they happened to come in.</p>
<p><span class="math inline">\(\blacksquare\)</span></p>
</div>
<div id="going-to-sleep-1" class="section level2" number="19.10">
<h2><span class="header-section-number">19.10</span> Going to sleep</h2>
<p>A student keeps track of what time they go to bed and what time they get up in the morning. They also have an app on their phone that measures the number of hours they were asleep during that time. The data for one week are in <a href="http://ritsokiguess.site/datafiles/sleeping.csv">http://ritsokiguess.site/datafiles/sleeping.csv</a>, in the 24-hour clock.</p>
<ol style="list-style-type: lower-alpha">
<li>Read in and display the data. What type of things are each of your columns?</li>
</ol>
<p>Solution</p>
<p>The usual, to start:</p>
<div class="sourceCode" id="cb143"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb143-1"><a href="dates-and-times.html#cb143-1"></a>my_url &lt;-<span class="st"> &quot;http://ritsokiguess.site/datafiles/sleeping.csv&quot;</span></span>
<span id="cb143-2"><a href="dates-and-times.html#cb143-2"></a>sleep &lt;-<span class="st"> </span><span class="kw">read_csv</span>(my_url)</span></code></pre></div>
<pre><code>## 
## ── Column specification ─────────────────────────────────────────────────
## cols(
##   bed.time = col_datetime(format = &quot;&quot;),
##   rise.time = col_datetime(format = &quot;&quot;),
##   sleep.time = col_double()
## )</code></pre>
<div class="sourceCode" id="cb145"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb145-1"><a href="dates-and-times.html#cb145-1"></a>sleep</span></code></pre></div>
<p>On mine, the sleep time is an ordinary decimal number, but the two times are something called <code>dttm</code>, which I can guess means date-time. In your notebook, you might see
<code>S3:POSIXct</code>, and you probably don’t know what that is (although you can guess).<a href="#fn30" class="footnote-ref" id="fnref30"><sup>30</sup></a></p>
<p>If you search for this, you’ll find some links to the help files, but a bit further down is <a href="https://rstudio-pubs-static.s3.amazonaws.com/28038_1bcb9aa80ca84f27ace07d612872861a.html">this</a>, which says it in a few words: “These objects store the number of seconds (for <code>POSIXct</code>) … since January 1st 1970 at midnight.”<a href="#fn31" class="footnote-ref" id="fnref31"><sup>31</sup></a></p>
<p>Make the claim that the first two columns are genuine date-times, and if they are labelled <code>S3:POSIXct</code> for you, say how you know. That is to say, they may look like pieces of text laid out as date-times, but they are <em>actual</em> date-times stored internally as seconds since Jan 1 1970 and displayed nicely. Thus we <em>do not</em> need to use <code>ymd_hms</code> or anything similar to deal with them.</p>
<p><span class="math inline">\(\blacksquare\)</span></p>
<ol start="2" style="list-style-type: lower-alpha">
<li>Work out the fractional number of hours that the student was in bed each of these nights. (They may not have been asleep this whole time.) Your result needs to be a <em>number</em> since we will be doing some calculations with it shortly.</li>
</ol>
<p>Solution</p>
<p>Since these are genuine date-times, you can take the difference, but the unit is not predictable. Internally, these are stored as a number of <em>seconds</em>, but it displays a “nice” unit:</p>
<div class="sourceCode" id="cb146"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb146-1"><a href="dates-and-times.html#cb146-1"></a>sleep <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">mutate</span>(<span class="dt">in_bed =</span> rise.time <span class="op">-</span><span class="st"> </span>bed.time)</span></code></pre></div>
<p>In this case, we did get a number of hours, but in the next part, we are going to do a calculation like this:</p>
<div class="sourceCode" id="cb147"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb147-1"><a href="dates-and-times.html#cb147-1"></a>sleep <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">mutate</span>(<span class="dt">in_bed =</span> rise.time <span class="op">-</span><span class="st"> </span>bed.time) <span class="op">%&gt;%</span><span class="st"> </span></span>
<span id="cb147-2"><a href="dates-and-times.html#cb147-2"></a><span class="kw">mutate</span>(<span class="dt">ratio =</span> sleep.time <span class="op">/</span><span class="st"> </span>in_bed)</span></code></pre></div>
<pre><code>## Error: Problem with `mutate()` input `ratio`.
## x second argument of / cannot be a &quot;difftime&quot; object
## ℹ Input `ratio` is `sleep.time/in_bed`.</code></pre>
<p>and this doesn’t work because you can’t divide a number by a time. (What would its units be?) So we have to turn <code>in_bed</code> into a number, and to do that we can divide by the number of seconds in an hour:</p>
<div class="sourceCode" id="cb149"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb149-1"><a href="dates-and-times.html#cb149-1"></a>sleep <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">mutate</span>(<span class="dt">in_bed =</span> (rise.time <span class="op">-</span><span class="st"> </span>bed.time) <span class="op">/</span><span class="st"> </span><span class="kw">dhours</span>(<span class="dv">1</span>))</span></code></pre></div>
<p>This is now correctly a (decimal) number.</p>
<p><span class="math inline">\(\blacksquare\)</span></p>
<ol start="3" style="list-style-type: lower-alpha">
<li>The student is concerned with something they call “sleep efficiency”. This is the percentage of time in bed spent sleeping. Work out the student’s sleep efficiency for the seven nights in this dataframe. Which night was the student’s sleep efficiency greatest?</li>
</ol>
<p>Solution</p>
<p>Divide the sleep time by the in-bed time and multiply by 100. To answer the last part of the question, you might think of sorting these in descending order as well:</p>
<div class="sourceCode" id="cb150"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb150-1"><a href="dates-and-times.html#cb150-1"></a>sleep <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">mutate</span>(<span class="dt">in_bed =</span> (rise.time <span class="op">-</span><span class="st"> </span>bed.time) <span class="op">/</span><span class="st"> </span><span class="kw">dhours</span>(<span class="dv">1</span>)) <span class="op">%&gt;%</span><span class="st"> </span></span>
<span id="cb150-2"><a href="dates-and-times.html#cb150-2"></a><span class="kw">mutate</span>(<span class="dt">efficiency =</span> sleep.time <span class="op">/</span><span class="st"> </span>in_bed <span class="op">*</span><span class="st"> </span><span class="dv">100</span>) <span class="op">%&gt;%</span><span class="st"> </span></span>
<span id="cb150-3"><a href="dates-and-times.html#cb150-3"></a><span class="kw">arrange</span>(<span class="kw">desc</span>(efficiency))</span></code></pre></div>
<p>The night of September 8. This was the night the student went to bed the latest, but they were asleep almost all the time they were in bed.</p>
<p><span class="math inline">\(\blacksquare\)</span></p>
<ol start="4" style="list-style-type: lower-alpha">
<li>Display the time spent in bed each night as a number of hours, minutes and seconds.</li>
</ol>
<p>Solution</p>
<p>The idea here is to display the time between going to bed and getting up as an interval, using <code>%--%</code>, and then turn that into a period:</p>
<div class="sourceCode" id="cb151"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb151-1"><a href="dates-and-times.html#cb151-1"></a>sleep <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">mutate</span>(<span class="dt">in_bed_hms =</span> <span class="kw">as.period</span>(bed.time <span class="op">%--%</span><span class="st"> </span>rise.time))</span></code></pre></div>
<p><span class="math inline">\(\blacksquare\)</span></p>
<ol start="5" style="list-style-type: lower-alpha">
<li>Make a graph of what time the student went to bed each night. Bear in mind that you only need the times, not the dates, and that you want a graph that is informative, showing appropriately the distribution of times the student went to bed.</li>
</ol>
<p>Solution</p>
<p>If you just pull out the times, some of them will be at the end of the day and some will be at the beginning. Extracting the hours, minutes and seconds is one way:<a href="#fn32" class="footnote-ref" id="fnref32"><sup>32</sup></a></p>
<div class="sourceCode" id="cb152"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb152-1"><a href="dates-and-times.html#cb152-1"></a>sleep <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">mutate</span>(<span class="dt">h =</span> <span class="kw">hour</span>(bed.time), <span class="dt">m =</span> <span class="kw">minute</span>(bed.time), <span class="dt">s =</span> <span class="kw">second</span>(bed.time))</span></code></pre></div>
<p>You could convert these into fractional hours to make a histogram of:</p>
<div class="sourceCode" id="cb153"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb153-1"><a href="dates-and-times.html#cb153-1"></a>sleep <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">mutate</span>(<span class="dt">h =</span> <span class="kw">hour</span>(bed.time), <span class="dt">m =</span> <span class="kw">minute</span>(bed.time), <span class="dt">s =</span> <span class="kw">second</span>(bed.time)) <span class="op">%&gt;%</span><span class="st"> </span></span>
<span id="cb153-2"><a href="dates-and-times.html#cb153-2"></a><span class="kw">mutate</span>(<span class="dt">bed_time_hours =</span> h <span class="op">+</span><span class="st"> </span>m <span class="op">/</span><span class="st"> </span><span class="dv">60</span> <span class="op">+</span><span class="st"> </span>s <span class="op">/</span><span class="st"> </span>(<span class="dv">60</span><span class="op">*</span><span class="dv">60</span>))</span></code></pre></div>
<p>but if you make a histogram of these, this is what you get:</p>
<div class="sourceCode" id="cb154"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb154-1"><a href="dates-and-times.html#cb154-1"></a>sleep <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">mutate</span>(<span class="dt">h =</span> <span class="kw">hour</span>(bed.time), <span class="dt">m =</span> <span class="kw">minute</span>(bed.time), <span class="dt">s =</span> <span class="kw">second</span>(bed.time)) <span class="op">%&gt;%</span><span class="st"> </span></span>
<span id="cb154-2"><a href="dates-and-times.html#cb154-2"></a><span class="kw">mutate</span>(<span class="dt">bed_time_hours =</span> h <span class="op">+</span><span class="st"> </span>m <span class="op">/</span><span class="st"> </span><span class="dv">60</span> <span class="op">+</span><span class="st"> </span>s <span class="op">/</span><span class="st"> </span>(<span class="dv">60</span><span class="op">*</span><span class="dv">60</span>)) <span class="op">%&gt;%</span><span class="st"> </span></span>
<span id="cb154-3"><a href="dates-and-times.html#cb154-3"></a><span class="kw">ggplot</span>(<span class="kw">aes</span>(<span class="dt">x =</span> bed_time_hours)) <span class="op">+</span><span class="st"> </span><span class="kw">geom_histogram</span>(<span class="dt">bins =</span> <span class="dv">5</span>)</span></code></pre></div>
<p><img src="pasias_files/figure-html/unnamed-chunk-118-1.png" width="672" /></p>
<p>but this makes no sense because the bedtimes after midnight are on the end of the previous day, not the beginning of the next one!</p>
<p>With that in mind, let’s move the bedtimes that are, say, before 3:00am to the end of the previous day by adding 24 to them before we make the graph:</p>
<div class="sourceCode" id="cb155"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb155-1"><a href="dates-and-times.html#cb155-1"></a>sleep <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">mutate</span>(<span class="dt">h =</span> <span class="kw">hour</span>(bed.time), <span class="dt">m =</span> <span class="kw">minute</span>(bed.time), <span class="dt">s =</span> <span class="kw">second</span>(bed.time)) <span class="op">%&gt;%</span><span class="st"> </span></span>
<span id="cb155-2"><a href="dates-and-times.html#cb155-2"></a><span class="kw">mutate</span>(<span class="dt">bed_time_hours =</span> h <span class="op">+</span><span class="st"> </span>m <span class="op">/</span><span class="st"> </span><span class="dv">60</span> <span class="op">+</span><span class="st"> </span>s <span class="op">/</span><span class="st"> </span>(<span class="dv">60</span><span class="op">*</span><span class="dv">60</span>)) <span class="op">%&gt;%</span><span class="st"> </span></span>
<span id="cb155-3"><a href="dates-and-times.html#cb155-3"></a><span class="kw">mutate</span>(<span class="dt">bed_time_hours =</span> <span class="kw">ifelse</span>(bed_time_hours <span class="op">&lt;</span><span class="st"> </span><span class="dv">3</span>, bed_time_hours <span class="op">+</span><span class="st"> </span><span class="dv">24</span>, bed_time_hours)) <span class="op">%&gt;%</span><span class="st"> </span></span>
<span id="cb155-4"><a href="dates-and-times.html#cb155-4"></a><span class="kw">ggplot</span>(<span class="kw">aes</span>(<span class="dt">x =</span> bed_time_hours)) <span class="op">+</span><span class="st"> </span><span class="kw">geom_histogram</span>(<span class="dt">bins =</span> <span class="dv">5</span>)</span></code></pre></div>
<p><img src="pasias_files/figure-html/unnamed-chunk-119-1.png" width="672" /></p>
<p>This gives a sense of where the bedtimes are. If you’re used to reading the 24-hour clock, you’ll know that 23 is 11:00pm, and you’ll have a sense that some of the bedtimes were 11 or a bit earlier and some were around midnight. (I like the 24-hour clock.) There are only 7 observations, so the graph you get won’t look very nice as a histogram, but at least this one says something about when the student went to bed, in a way that puts times just after midnight next to times just before. You should give some thought about the number of bins; with only 7 observations, even 5 bins is pushing it, but this looked nicer to me than 4 bins.</p>
<p>If you’re more used to the 12-hour clock, you’ll want to convert the times to something between 10 and 12. You can do this with an <code>ifelse</code> as above, subtracting 12 from the ones before midnight and adding 12 to the ones after. Or you can recognize this as modulo arithmetic (the clock is a classic case: what is 10:00pm plus 3 hours?) A little thought will reveal that subtracting (or adding) 12 hours and taking the result modulo 24 would do it: the pre-midnight bedtimes will get turned into a number like 10 or 11, and the post-midnight ones to 12 and a bit. R has a modulo operator, which is <code>%%</code> (cite your source: mine was <a href="https://stat.ethz.ch/R-manual/R-patched/library/base/html/Arithmetic.html">this</a>):</p>
<div class="sourceCode" id="cb156"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb156-1"><a href="dates-and-times.html#cb156-1"></a>sleep <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">mutate</span>(<span class="dt">h =</span> <span class="kw">hour</span>(bed.time), <span class="dt">m =</span> <span class="kw">minute</span>(bed.time), <span class="dt">s =</span> <span class="kw">second</span>(bed.time)) <span class="op">%&gt;%</span><span class="st"> </span></span>
<span id="cb156-2"><a href="dates-and-times.html#cb156-2"></a><span class="kw">mutate</span>(<span class="dt">bed_time_hours =</span> h <span class="op">+</span><span class="st"> </span>m <span class="op">/</span><span class="st"> </span><span class="dv">60</span> <span class="op">+</span><span class="st"> </span>s <span class="op">/</span><span class="st"> </span>(<span class="dv">60</span><span class="op">*</span><span class="dv">60</span>)) <span class="op">%&gt;%</span><span class="st"> </span></span>
<span id="cb156-3"><a href="dates-and-times.html#cb156-3"></a><span class="kw">mutate</span>(<span class="dt">bed_time_hours =</span> (bed_time_hours <span class="op">-</span><span class="st"> </span><span class="dv">12</span>) <span class="op">%%</span><span class="st"> </span><span class="dv">24</span>) <span class="op">%&gt;%</span><span class="st"> </span></span>
<span id="cb156-4"><a href="dates-and-times.html#cb156-4"></a><span class="kw">ggplot</span>(<span class="kw">aes</span>(<span class="dt">x =</span> bed_time_hours)) <span class="op">+</span><span class="st"> </span><span class="kw">geom_histogram</span>(<span class="dt">bins =</span> <span class="dv">5</span>)</span></code></pre></div>
<p><img src="pasias_files/figure-html/unnamed-chunk-120-1.png" width="672" /></p>
<p>and you might find the <span class="math inline">\(x\)</span>-scale of that easier to cope with. (The bins have come out differently, for some reason.)</p>
<p>I think the best graph uses the fact that date-times plot nicely, so if we keep them as date-times, the <span class="math inline">\(x\)</span>-scale will look nice. The problem is that they are times on <em>different</em> days. What if we faked it up so that they were all on the <em>same</em> day (or, at least, consecutive days, to account for the ones after midnight)?</p>
<p>Let’s look at our dataframe again:</p>
<div class="sourceCode" id="cb157"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb157-1"><a href="dates-and-times.html#cb157-1"></a>sleep</span></code></pre></div>
<p>The <code>rise.time</code> values are all a.m., and on consecutive days, so if we subtract consecutive numbers of days from the <code>bed.time</code>s, we’ll put them all on appropriate days too:</p>
<div class="sourceCode" id="cb158"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb158-1"><a href="dates-and-times.html#cb158-1"></a>sleep <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">mutate</span>(<span class="dt">time_of_bed =</span> bed.time <span class="op">-</span><span class="st"> </span><span class="kw">ddays</span>(<span class="dv">0</span><span class="op">:</span><span class="dv">6</span>))</span></code></pre></div>
<p>These are all around the midnight at the end of September 1, so some of them are in the early hours of September 2. Now, if we make a histogram of <em>those</em>:</p>
<div class="sourceCode" id="cb159"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb159-1"><a href="dates-and-times.html#cb159-1"></a>sleep <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">mutate</span>(<span class="dt">time_of_bed =</span> bed.time <span class="op">-</span><span class="st"> </span><span class="kw">ddays</span>(<span class="dv">0</span><span class="op">:</span><span class="dv">6</span>)) <span class="op">%&gt;%</span><span class="st"> </span></span>
<span id="cb159-2"><a href="dates-and-times.html#cb159-2"></a><span class="kw">ggplot</span>(<span class="kw">aes</span>(<span class="dt">x =</span> time_of_bed)) <span class="op">+</span><span class="st"> </span><span class="kw">geom_histogram</span>(<span class="dt">bins =</span> <span class="dv">5</span>)</span></code></pre></div>
<p><img src="pasias_files/figure-html/unnamed-chunk-123-1.png" width="672" />
Now the <span class="math inline">\(x\)</span>-axis formatting looks like a time, and spills seamlessly into the next day. (There was no real range of dates, so the formatting is of the times only.)</p>
<p>One more embellishment, idea from <a href="https://www.r-bloggers.com/2018/06/customizing-time-and-date-scales-in-ggplot2/">here</a>:</p>
<div class="sourceCode" id="cb160"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb160-1"><a href="dates-and-times.html#cb160-1"></a>sleep <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">mutate</span>(<span class="dt">time_of_bed =</span> bed.time <span class="op">-</span><span class="st"> </span><span class="kw">ddays</span>(<span class="dv">0</span><span class="op">:</span><span class="dv">6</span>)) <span class="op">%&gt;%</span><span class="st"> </span></span>
<span id="cb160-2"><a href="dates-and-times.html#cb160-2"></a><span class="kw">ggplot</span>(<span class="kw">aes</span>(<span class="dt">x =</span> time_of_bed)) <span class="op">+</span><span class="st"> </span><span class="kw">geom_histogram</span>(<span class="dt">bins =</span> <span class="dv">5</span>) <span class="op">+</span></span>
<span id="cb160-3"><a href="dates-and-times.html#cb160-3"></a><span class="kw">scale_x_datetime</span>(<span class="dt">date_labels =</span> <span class="st">&quot;%l:%M %p&quot;</span>)</span></code></pre></div>
<p><img src="pasias_files/figure-html/unnamed-chunk-124-1.png" width="672" /></p>
<p>The <code>scale_x</code> and <code>scale_y</code> functions customize the <span class="math inline">\(x\)</span> and <span class="math inline">\(y\)</span> axes respectively. Inside <code>date_labels</code> go some codes that say what time units you want to display: in this case, the 12-hour hours, the minutes, and whether the time is AM or PM. The codes come from a function called <code>strftime</code>, and a full list is <a href="https://man7.org/linux/man-pages/man3/strftime.3.html">here</a>. Alternatively, you can look up the help for R’s function of the same name with <code>?strftime</code>.<a href="#fn33" class="footnote-ref" id="fnref33"><sup>33</sup></a></p>
<p><span class="math inline">\(\blacksquare\)</span></p>

</div>
</div>
<div class="footnotes">
<hr />
<ol start="15">
<li id="fn15"><p>In fact, it is believed that wolves help keep caribou herds strong by preventing over-population: that is, the weakest caribou are the ones taken by wolves.<a href="dates-and-times.html#fnref15" class="footnote-back">↩︎</a></p></li>
<li id="fn16"><p>The survey is always taken in the fall, but the date varies.<a href="dates-and-times.html#fnref16" class="footnote-back">↩︎</a></p></li>
<li id="fn17"><p>Counting animals in a region, especially rare, hard-to-find animals, is a whole science in itself. Our data are probably themselves estimates (with some uncertainty).<a href="dates-and-times.html#fnref17" class="footnote-back">↩︎</a></p></li>
<li id="fn18"><p>This is an example of R’s so-called “recycling rules”.<a href="dates-and-times.html#fnref18" class="footnote-back">↩︎</a></p></li>
<li id="fn19"><p>In fact, it is believed that wolves help keep caribou herds strong by preventing over-population: that is, the weakest caribou are the ones taken by wolves.<a href="dates-and-times.html#fnref19" class="footnote-back">↩︎</a></p></li>
<li id="fn20"><p>The survey is always taken in the fall, but the date varies.<a href="dates-and-times.html#fnref20" class="footnote-back">↩︎</a></p></li>
<li id="fn21"><p>Counting animals in a region, especially rare, hard-to-find animals, is a whole science in itself. Our data are probably themselves estimates (with some uncertainty).<a href="dates-and-times.html#fnref21" class="footnote-back">↩︎</a></p></li>
<li id="fn22"><p>The only way this would fail is if <em>every</em> first name had the same number of letters in it; then the space between first name and initial of last name <em>would</em> be in the same place in every line.<a href="dates-and-times.html#fnref22" class="footnote-back">↩︎</a></p></li>
<li id="fn23"><p>Not a surprise since Denali National Park is in Alaska.<a href="dates-and-times.html#fnref23" class="footnote-back">↩︎</a></p></li>
<li id="fn24"><p>It’s actually not <em>really</em> living on the edge, because if it doesn’t work, you go back and read the data in from the file again.<a href="dates-and-times.html#fnref24" class="footnote-back">↩︎</a></p></li>
<li id="fn25"><p>This wiggles more than I would like, with such a small number of observations. Try putting something like <code>span=2</code> in the smooth to make it less wiggly.<a href="dates-and-times.html#fnref25" class="footnote-back">↩︎</a></p></li>
<li id="fn26"><p>I have to say that I didn’t know that until just now.<a href="dates-and-times.html#fnref26" class="footnote-back">↩︎</a></p></li>
<li id="fn27"><p>Which means, if you stop to think about it, that there are <em>actually</em> about 40 times more caribou than wolves.<a href="dates-and-times.html#fnref27" class="footnote-back">↩︎</a></p></li>
<li id="fn28"><p>And all too often with Excel (spit).<a href="dates-and-times.html#fnref28" class="footnote-back">↩︎</a></p></li>
<li id="fn29"><p>The computer scientists among you will note that I shouldn’t have done this, because <code>diff1</code> through <code>diff3</code> are double-precision decimal numbers, so I should have tested their equality with <code>lenfol</code> and <code>los</code> by working out the absolute differences and testing whether they were all <em>small</em>. On consulting the help for <code>all.equal</code>, though, I find that it <em>does</em> work properly, because it actually tests whether the things being compared differ by less than a quantity <code>tolerance</code> which defaults to 0.000000015, and if they do it calls them equal. This is all tied in with the difference between integers and decimal numbers as they are represented on a computer: exactly and approximately, respectively. A double-precision number has about 16 significant digits of accuracy; equal things won’t have all 16 digits equal, most likely, but they would be expected to have at least 8 of those digits the same. CSCA08 stuff, I imagine. This is where you can casually toss around terms like “machine epsilon”. Oh! I just realized something. You know how very very small P-values are shown in R as <em>&lt;2.2e-16</em>? <em>That’s</em> the machine epsilon. Anything smaller than that is indistinguishable from zero, and you can’t have a P-value be <em>exactly</em> zero. The default <code>tolerance</code> I mentioned above is the square root of this, which is normally used for such things.<a href="dates-and-times.html#fnref29" class="footnote-back">↩︎</a></p></li>
<li id="fn30"><p>Which one you see will depend on which type of output you are looking at. In your notebook you will probably see the POSIXCT thing, but in your HTML or PDF output it will probably say ``dttm’’.<a href="dates-and-times.html#fnref30" class="footnote-back">↩︎</a></p></li>
<li id="fn31"><p>The piece in quotes comes word-for-word from the source: it is exactly what the author said. Except that the author also talks about dates, which don’t concern us here, so I removed that bit and replaced it with the three dots, called an “ellipsis”, to show that the author said some extra stuff that I didn’t quote. I checked that what remained does actually still capture what the author said. Extra-in-note: an ellipsis is not to be confused with the conic section called an ellipse, and these three dots are not to be confused with the three dots in an R function, where they mean
“anything else that was passed in to the function”. Both uses of the three dots capture the idea of
“something was missed out”.<a href="dates-and-times.html#fnref31" class="footnote-back">↩︎</a></p></li>
<li id="fn32"><p>Make sure you use “hour” and not “hours” as I did the first time. That computes the total number of hours between the zero date of Jan 1, 1970 and the time given, and so is way too large to be an answer here!<a href="dates-and-times.html#fnref32" class="footnote-back">↩︎</a></p></li>
<li id="fn33"><p>Confusingly, uppercase I and lowercase l not only look the same, but they also both display the 12-hour hour. The former adds a zero to the front if the hour is a single digit, and the latter does not. All the hours here have two digits, though, so it comes out the same whichever you use.<a href="dates-and-times.html#fnref33" class="footnote-back">↩︎</a></p></li>
</ol>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="regression-with-categorical-variables.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="functions.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/lunr.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": null,
"text": null
},
"history": {
"link": null,
"text": null
},
"view": {
"link": null,
"text": null
},
"download": ["pasias.pdf"],
"toc": {
"collapse": "subsection"
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
