<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>Chapter 3 Drawing graphs | Problems and Solutions in Applied Statistics</title>
  <meta name="description" content="A set of problems and solutions, in R, on various parts of applied statistics" />
  <meta name="generator" content="bookdown 0.21 and GitBook 2.6.7" />

  <meta property="og:title" content="Chapter 3 Drawing graphs | Problems and Solutions in Applied Statistics" />
  <meta property="og:type" content="book" />
  <meta property="og:url" content="http://ritsokiguess.site/pasias" />
  
  <meta property="og:description" content="A set of problems and solutions, in R, on various parts of applied statistics" />
  <meta name="github-repo" content="nxskok/pasias" />

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Chapter 3 Drawing graphs | Problems and Solutions in Applied Statistics" />
  
  <meta name="twitter:description" content="A set of problems and solutions, in R, on various parts of applied statistics" />
  

<meta name="author" content="Ken Butler" />


<meta name="date" content="2021-05-17" />

  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="reading-in-data.html"/>
<link rel="next" href="data-exploration.html"/>
<script src="libs/jquery-2.2.3/jquery.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />











<style type="text/css">
a.sourceLine { display: inline-block; line-height: 1.25; }
a.sourceLine { pointer-events: none; color: inherit; text-decoration: inherit; }
a.sourceLine:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode { white-space: pre; position: relative; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
code.sourceCode { white-space: pre-wrap; }
a.sourceLine { text-indent: -1em; padding-left: 1em; }
}
pre.numberSource a.sourceLine
  { position: relative; left: -4em; }
pre.numberSource a.sourceLine::before
  { content: attr(title);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; pointer-events: all; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {  }
@media screen {
a.sourceLine::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">Problems and Solutions in Applied Statistics</a></li>

<li class="divider"></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i>Introduction</a><ul>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#packages-used-somewhere-in-this-book"><i class="fa fa-check"></i>Packages used somewhere in this book</a></li>
</ul></li>
<li class="chapter" data-level="1" data-path="getting-used-to-r-and-r-studio.html"><a href="getting-used-to-r-and-r-studio.html"><i class="fa fa-check"></i><b>1</b> Getting used to R and R Studio</a></li>
<li class="chapter" data-level="2" data-path="reading-in-data.html"><a href="reading-in-data.html"><i class="fa fa-check"></i><b>2</b> Reading in data</a></li>
<li class="chapter" data-level="3" data-path="drawing-graphs.html"><a href="drawing-graphs.html"><i class="fa fa-check"></i><b>3</b> Drawing graphs</a><ul>
<li class="chapter" data-level="3.1" data-path="drawing-graphs.html"><a href="drawing-graphs.html#orange-juice"><i class="fa fa-check"></i><b>3.1</b> Orange juice</a></li>
<li class="chapter" data-level="3.2" data-path="drawing-graphs.html"><a href="drawing-graphs.html#making-soap"><i class="fa fa-check"></i><b>3.2</b> Making soap</a></li>
<li class="chapter" data-level="3.3" data-path="drawing-graphs.html"><a href="drawing-graphs.html#handling-shipments"><i class="fa fa-check"></i><b>3.3</b> Handling shipments</a></li>
<li class="chapter" data-level="3.4" data-path="drawing-graphs.html"><a href="drawing-graphs.html#rainfall-in-davis-california"><i class="fa fa-check"></i><b>3.4</b> Rainfall in Davis, California</a></li>
<li class="chapter" data-level="3.5" data-path="drawing-graphs.html"><a href="drawing-graphs.html#students-and-exercise"><i class="fa fa-check"></i><b>3.5</b> Students and exercise</a></li>
<li class="chapter" data-level="3.6" data-path="drawing-graphs.html"><a href="drawing-graphs.html#orange-juice-1"><i class="fa fa-check"></i><b>3.6</b> Orange juice</a></li>
<li class="chapter" data-level="3.7" data-path="drawing-graphs.html"><a href="drawing-graphs.html#making-soap-1"><i class="fa fa-check"></i><b>3.7</b> Making soap</a></li>
<li class="chapter" data-level="3.8" data-path="drawing-graphs.html"><a href="drawing-graphs.html#handling-shipments-1"><i class="fa fa-check"></i><b>3.8</b> Handling shipments</a></li>
<li class="chapter" data-level="3.9" data-path="drawing-graphs.html"><a href="drawing-graphs.html#rainfall-in-davis-california-1"><i class="fa fa-check"></i><b>3.9</b> Rainfall in Davis, California</a></li>
<li class="chapter" data-level="3.10" data-path="drawing-graphs.html"><a href="drawing-graphs.html#students-and-exercise-1"><i class="fa fa-check"></i><b>3.10</b> Students and exercise</a></li>
</ul></li>
<li class="chapter" data-level="4" data-path="data-exploration.html"><a href="data-exploration.html"><i class="fa fa-check"></i><b>4</b> Data exploration</a></li>
<li class="chapter" data-level="5" data-path="working-with-dataframes.html"><a href="working-with-dataframes.html"><i class="fa fa-check"></i><b>5</b> Working with dataframes</a></li>
<li class="chapter" data-level="6" data-path="one-sample-inference.html"><a href="one-sample-inference.html"><i class="fa fa-check"></i><b>6</b> One-sample inference</a></li>
<li class="chapter" data-level="7" data-path="two-sample-inference.html"><a href="two-sample-inference.html"><i class="fa fa-check"></i><b>7</b> Two-sample inference</a></li>
<li class="chapter" data-level="8" data-path="power-and-sample-size.html"><a href="power-and-sample-size.html"><i class="fa fa-check"></i><b>8</b> Power and sample size</a></li>
<li class="chapter" data-level="9" data-path="the-sign-test.html"><a href="the-sign-test.html"><i class="fa fa-check"></i><b>9</b> The sign test</a></li>
<li class="chapter" data-level="10" data-path="mood-median-test.html"><a href="mood-median-test.html"><i class="fa fa-check"></i><b>10</b> Mood median test</a></li>
<li class="chapter" data-level="11" data-path="matched-pairs-t-and-sign-test.html"><a href="matched-pairs-t-and-sign-test.html"><i class="fa fa-check"></i><b>11</b> Matched pairs t and sign test</a></li>
<li class="chapter" data-level="12" data-path="normal-quantile-plots.html"><a href="normal-quantile-plots.html"><i class="fa fa-check"></i><b>12</b> Normal quantile plots</a><ul>
<li class="chapter" data-level="12.1" data-path="normal-quantile-plots.html"><a href="normal-quantile-plots.html#lengths-of-heliconia-flowers"><i class="fa fa-check"></i><b>12.1</b> Lengths of heliconia flowers</a></li>
<li class="chapter" data-level="12.2" data-path="normal-quantile-plots.html"><a href="normal-quantile-plots.html#ferritin-and-normality"><i class="fa fa-check"></i><b>12.2</b> Ferritin and normality</a></li>
<li class="chapter" data-level="12.3" data-path="normal-quantile-plots.html"><a href="normal-quantile-plots.html#lengths-of-heliconia-flowers-1"><i class="fa fa-check"></i><b>12.3</b> Lengths of heliconia flowers</a></li>
<li class="chapter" data-level="12.4" data-path="normal-quantile-plots.html"><a href="normal-quantile-plots.html#ferritin-and-normality-1"><i class="fa fa-check"></i><b>12.4</b> Ferritin and normality</a></li>
</ul></li>
<li class="chapter" data-level="13" data-path="analysis-of-variance.html"><a href="analysis-of-variance.html"><i class="fa fa-check"></i><b>13</b> Analysis of variance</a></li>
<li class="chapter" data-level="14" data-path="writing-reports.html"><a href="writing-reports.html"><i class="fa fa-check"></i><b>14</b> Writing reports</a></li>
<li class="chapter" data-level="15" data-path="learning-to-code.html"><a href="learning-to-code.html"><i class="fa fa-check"></i><b>15</b> Learning to code</a><ul>
<li class="chapter" data-level="15.1" data-path="learning-to-code.html"><a href="learning-to-code.html#introduction-1"><i class="fa fa-check"></i><b>15.1</b> Introduction</a></li>
<li class="chapter" data-level="15.2" data-path="learning-to-code.html"><a href="learning-to-code.html#data-and-pre-processing"><i class="fa fa-check"></i><b>15.2</b> Data and pre-processing</a></li>
<li class="chapter" data-level="15.3" data-path="learning-to-code.html"><a href="learning-to-code.html#analysis"><i class="fa fa-check"></i><b>15.3</b> Analysis</a></li>
<li class="chapter" data-level="15.4" data-path="learning-to-code.html"><a href="learning-to-code.html#conclusions-see-note-9"><i class="fa fa-check"></i><b>15.4</b> Conclusions (see note 9)</a></li>
</ul></li>
<li class="chapter" data-level="16" data-path="a-comparison-of-four-shampoos-in-treating-dandruff.html"><a href="a-comparison-of-four-shampoos-in-treating-dandruff.html"><i class="fa fa-check"></i><b>16</b> A comparison of four shampoos in treating dandruff</a><ul>
<li class="chapter" data-level="16.1" data-path="a-comparison-of-four-shampoos-in-treating-dandruff.html"><a href="a-comparison-of-four-shampoos-in-treating-dandruff.html#introduction-2"><i class="fa fa-check"></i><b>16.1</b> Introduction</a></li>
<li class="chapter" data-level="16.2" data-path="a-comparison-of-four-shampoos-in-treating-dandruff.html"><a href="a-comparison-of-four-shampoos-in-treating-dandruff.html#exploratory-analysis"><i class="fa fa-check"></i><b>16.2</b> Exploratory analysis</a></li>
<li class="chapter" data-level="16.3" data-path="a-comparison-of-four-shampoos-in-treating-dandruff.html"><a href="a-comparison-of-four-shampoos-in-treating-dandruff.html#analysis-of-variance-1"><i class="fa fa-check"></i><b>16.3</b> Analysis of Variance</a></li>
<li class="chapter" data-level="16.4" data-path="a-comparison-of-four-shampoos-in-treating-dandruff.html"><a href="a-comparison-of-four-shampoos-in-treating-dandruff.html#assessment-of-assumptions"><i class="fa fa-check"></i><b>16.4</b> Assessment of Assumptions</a></li>
<li class="chapter" data-level="16.5" data-path="a-comparison-of-four-shampoos-in-treating-dandruff.html"><a href="a-comparison-of-four-shampoos-in-treating-dandruff.html#conclusions"><i class="fa fa-check"></i><b>16.5</b> Conclusions</a></li>
<li class="chapter" data-level="16.6" data-path="a-comparison-of-four-shampoos-in-treating-dandruff.html"><a href="a-comparison-of-four-shampoos-in-treating-dandruff.html#end"><i class="fa fa-check"></i><b>16.6</b> End</a></li>
</ul></li>
<li class="chapter" data-level="17" data-path="tidying-data.html"><a href="tidying-data.html"><i class="fa fa-check"></i><b>17</b> Tidying data</a></li>
<li class="chapter" data-level="18" data-path="simple-regression.html"><a href="simple-regression.html"><i class="fa fa-check"></i><b>18</b> Simple regression</a></li>
<li class="chapter" data-level="19" data-path="multiple-regression.html"><a href="multiple-regression.html"><i class="fa fa-check"></i><b>19</b> Multiple regression</a></li>
<li class="chapter" data-level="20" data-path="regression-with-categorical-variables.html"><a href="regression-with-categorical-variables.html"><i class="fa fa-check"></i><b>20</b> Regression with categorical variables</a><ul>
<li class="chapter" data-level="20.1" data-path="regression-with-categorical-variables.html"><a href="regression-with-categorical-variables.html#crickets-revisited"><i class="fa fa-check"></i><b>20.1</b> Crickets revisited</a></li>
<li class="chapter" data-level="20.2" data-path="regression-with-categorical-variables.html"><a href="regression-with-categorical-variables.html#pulse-rates-and-marching"><i class="fa fa-check"></i><b>20.2</b> Pulse rates and marching</a></li>
<li class="chapter" data-level="20.3" data-path="regression-with-categorical-variables.html"><a href="regression-with-categorical-variables.html#crickets-revisited-1"><i class="fa fa-check"></i><b>20.3</b> Crickets revisited</a></li>
<li class="chapter" data-level="20.4" data-path="regression-with-categorical-variables.html"><a href="regression-with-categorical-variables.html#pulse-rates-and-marching-1"><i class="fa fa-check"></i><b>20.4</b> Pulse rates and marching</a></li>
</ul></li>
<li class="chapter" data-level="21" data-path="dates-and-times.html"><a href="dates-and-times.html"><i class="fa fa-check"></i><b>21</b> Dates and times</a></li>
<li class="chapter" data-level="22" data-path="functions.html"><a href="functions.html"><i class="fa fa-check"></i><b>22</b> Functions</a></li>
<li class="chapter" data-level="23" data-path="vector-and-matrix-algebra.html"><a href="vector-and-matrix-algebra.html"><i class="fa fa-check"></i><b>23</b> Vector and matrix algebra</a><ul>
<li class="chapter" data-level="23.1" data-path="vector-and-matrix-algebra.html"><a href="vector-and-matrix-algebra.html#heights-and-foot-lengths-again"><i class="fa fa-check"></i><b>23.1</b> Heights and foot lengths again</a></li>
<li class="chapter" data-level="23.2" data-path="vector-and-matrix-algebra.html"><a href="vector-and-matrix-algebra.html#heights-and-foot-lengths-again-1"><i class="fa fa-check"></i><b>23.2</b> Heights and foot lengths again</a></li>
</ul></li>
<li class="chapter" data-level="24" data-path="the-bootstrap.html"><a href="the-bootstrap.html"><i class="fa fa-check"></i><b>24</b> The Bootstrap</a></li>
<li class="chapter" data-level="25" data-path="bayesian-statistics-with-stan.html"><a href="bayesian-statistics-with-stan.html"><i class="fa fa-check"></i><b>25</b> Bayesian Statistics with Stan</a></li>
<li class="chapter" data-level="26" data-path="logistic-regression.html"><a href="logistic-regression.html"><i class="fa fa-check"></i><b>26</b> Logistic regression</a></li>
<li class="chapter" data-level="27" data-path="logistic-regression-with-ordinal-response.html"><a href="logistic-regression-with-ordinal-response.html"><i class="fa fa-check"></i><b>27</b> Logistic regression with ordinal response</a></li>
<li class="chapter" data-level="28" data-path="logistic-regression-with-nominal-response.html"><a href="logistic-regression-with-nominal-response.html"><i class="fa fa-check"></i><b>28</b> Logistic regression with nominal response</a></li>
<li class="chapter" data-level="29" data-path="survival-analysis.html"><a href="survival-analysis.html"><i class="fa fa-check"></i><b>29</b> Survival analysis</a></li>
<li class="chapter" data-level="30" data-path="analysis-of-variance-revisited.html"><a href="analysis-of-variance-revisited.html"><i class="fa fa-check"></i><b>30</b> Analysis of variance revisited</a></li>
<li class="chapter" data-level="31" data-path="analysis-of-covariance.html"><a href="analysis-of-covariance.html"><i class="fa fa-check"></i><b>31</b> Analysis of covariance</a></li>
<li class="chapter" data-level="32" data-path="multivariate-analysis-of-variance.html"><a href="multivariate-analysis-of-variance.html"><i class="fa fa-check"></i><b>32</b> Multivariate analysis of variance</a></li>
<li class="chapter" data-level="33" data-path="repeated-measures.html"><a href="repeated-measures.html"><i class="fa fa-check"></i><b>33</b> Repeated measures</a></li>
<li class="chapter" data-level="34" data-path="discriminant-analysis.html"><a href="discriminant-analysis.html"><i class="fa fa-check"></i><b>34</b> Discriminant analysis</a></li>
<li class="chapter" data-level="35" data-path="hierarchical-cluster-analysis.html"><a href="hierarchical-cluster-analysis.html"><i class="fa fa-check"></i><b>35</b> Hierarchical cluster analysis</a></li>
<li class="chapter" data-level="36" data-path="k-means-cluster-analysis.html"><a href="k-means-cluster-analysis.html"><i class="fa fa-check"></i><b>36</b> K-means cluster analysis</a></li>
<li class="chapter" data-level="37" data-path="drawing-maps-with-leaflet.html"><a href="drawing-maps-with-leaflet.html"><i class="fa fa-check"></i><b>37</b> Drawing maps with Leaflet</a></li>
<li class="chapter" data-level="38" data-path="multidimensional-scaling.html"><a href="multidimensional-scaling.html"><i class="fa fa-check"></i><b>38</b> Multidimensional Scaling</a></li>
<li class="chapter" data-level="39" data-path="principal-components.html"><a href="principal-components.html"><i class="fa fa-check"></i><b>39</b> Principal Components</a><ul>
<li class="chapter" data-level="39.1" data-path="principal-components.html"><a href="principal-components.html#the-weather-somewhere"><i class="fa fa-check"></i><b>39.1</b> The weather, somewhere</a></li>
<li class="chapter" data-level="39.2" data-path="principal-components.html"><a href="principal-components.html#the-weather-somewhere-1"><i class="fa fa-check"></i><b>39.2</b> The weather, somewhere</a></li>
</ul></li>
<li class="chapter" data-level="40" data-path="factor-analysis.html"><a href="factor-analysis.html"><i class="fa fa-check"></i><b>40</b> Factor Analysis</a></li>
<li class="chapter" data-level="41" data-path="frequency-table-analysis.html"><a href="frequency-table-analysis.html"><i class="fa fa-check"></i><b>41</b> Frequency table analysis</a></li>
<li class="divider"></li>
<li><a href="https://github.com/rstudio/bookdown" target="blank">Published with bookdown</a></li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Problems and Solutions in Applied Statistics</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="drawing-graphs" class="section level1">
<h1><span class="header-section-number">Chapter 3</span> Drawing graphs</h1>
<div class="sourceCode" id="cb1"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb1-1" title="1"><span class="kw">library</span>(tidyverse)</a></code></pre></div>
<div id="orange-juice" class="section level2">
<h2><span class="header-section-number">3.1</span> Orange juice</h2>
<p>We will read in the orange juice data again,
in <a href="http://ritsokiguess.site/datafiles/ojuice.txt">link</a>, and make a suitable graph.</p>
<ol style="list-style-type: lower-alpha">
<li><p>The data values are separated by a space. Use the appropriate
Tidyverse function to read the data directly from the course website
into a “tibble”.</p></li>
<li><p>The juice manufacturer was interested in whether there was a
relationship between sweetness and pectin. To assess this, draw a
scatterplot. Does it look as if there is any kind of a
relationship? (I think <code>sweetness</code> is the outcome variable
and <code>pectin</code> is explanatory, so draw your scatterplot
appropriately.)</p></li>
</ol>
</div>
<div id="making-soap" class="section level2">
<h2><span class="header-section-number">3.2</span> Making soap</h2>
<p>Previously, we learned about a company that operates two production lines in a factory for
making soap bars. The production lines were
labelled A and B. A production line that moves faster may produce more
soap, but may possibly also produce more “scrap” (that is, bits of
soap that
can no longer be made into soap bars and will have to be thrown away).</p>
<p>The data are in <a href="http://ritsokiguess.site/datafiles/soap.txt">link</a>.</p>
<ol style="list-style-type: lower-alpha">
<li><p>Read the data into R again.</p></li>
<li><p>Obtain a histogram of the <code>scrap</code> values, using 10
bins for your histogram.</p></li>
<li><p>Comment briefly on the shape of the histogram. Is it approximately
symmetric, skewed to the left, skewed to the right or something else? (By “comment briefly” I mean “say in a few words why you gave the answer you did.”)</p></li>
<li><p>Make side-by-side boxplots of scrap values for each
production line.</p></li>
<li><p>Do you think your boxplot says that there are differences in the
amount of scrap produced by the two production lines, or not?
Explain briefly.</p></li>
<li><p>We started out with the suspicion that if the line was run
faster, there would be more scrap. We haven’t assessed this
yet. Draw a scatter plot with <code>scrap</code> on the <span class="math inline">\(y\)</span> axis and
<code>speed</code> on the <span class="math inline">\(x\)</span> axis.</p></li>
<li><p>What do you think is the most important conclusion from
your plot of the previous part? Describe your conclusion in the
context of the data.</p></li>
</ol>
</div>
<div id="handling-shipments" class="section level2">
<h2><span class="header-section-number">3.3</span> Handling shipments</h2>
<p>We learned earlier about a company called Global Electronics that
imports shipments of a certain large part used as a
component in several of its products. The size of the shipment varies
each time. Each shipment is sent to one of two warehouses (labelled A
and B) for handling. The data in
<a href="http://ritsokiguess.site/datafiles/global.csv">link</a> show the
<code>size</code> of each shipment (in thousands of parts) and the direct
<code>cost</code> of handling it, in thousands of dollars. Also shown is
the <code>warehouse</code> (A or B) that handled each shipment.</p>
<ol style="list-style-type: lower-alpha">
<li><p>Read the data into R and display your data frame.</p></li>
<li><p>Make a scatterplot of the cost of handling each shipment as it
depends on the shipment’s size.</p></li>
<li><p>What kind of relationship do you see on the scatterplot? Do
you think a straight line would describe it appropriately? Explain briefly.</p></li>
<li><p>When a shipment comes in, the cost of handling it is not
known. A decision is made about which warehouse to send it to, and
then, after it is handled, the cost is recorded. What do you think
determines which warehouse an incoming shipment goes to? Provide a
graph to support your answer.</p></li>
</ol>
</div>
<div id="rainfall-in-davis-california" class="section level2">
<h2><span class="header-section-number">3.4</span> Rainfall in Davis, California</h2>
<p>One way to assess climate change is to look at weather
records over a number of years and to identify any changes.</p>
<p>Annual rainfall data for the Davis, California is in
<a href="http://ritsokiguess.site/datafiles/rainfall.txt">here</a>.
(Right-click on the URL and select Copy Link Address, then paste into your R Notebook.)
The rainfall is
measured in inches.</p>
<ol style="list-style-type: lower-alpha">
<li><p>Read in and display (some of) the data. Briefly justify why you coded it as you did.</p></li>
<li><p>Make a suitable plot of the rainfall values and years. Explain briefly why you drew the plot you did.</p></li>
<li><p>Add a regression line to your plot. Is there any convincing
indication of a trend, upward or downward, in annual rainfall for
Davis, California? Discuss briefly.</p></li>
</ol>
</div>
<div id="students-and-exercise" class="section level2">
<h2><span class="header-section-number">3.5</span> Students and exercise</h2>
<p>Some students in a Statistics class were asked how many
minutes they typically exercised in a week. The data are shown in
.</p>
<p>Some of the
students identified as male and some as female. Our concern is how the males
and females compare in terms of the amount of exercise they do.</p>
<ol style="list-style-type: lower-alpha">
<li><p>Take a look at the data file. (Click on the link, or paste the copied link into your web browser.) How is it laid out?</p></li>
<li><p>Read in and display (some of) the data. (This means to
display enough of what you read in to convince others that you read
in the right kind of thing.)</p></li>
<li><p>Make a suitable plot of this data frame.</p></li>
<li><p>Does there appear to be any substantial difference in the
average amount of time that males and females spend exercising?
Explain briefly. (“average” could be mean or median. Which is it
here?)</p></li>
<li><p>How do you know that both distributions, for males as well
as females, are skewed to the right? Explain (very) briefly.</p></li>
<li><p>For data like this, why does it make practical sense that
the distributions are skewed to the right?</p></li>
</ol>
<p>My solutions follow:</p>
</div>
<div id="orange-juice-1" class="section level2">
<h2><span class="header-section-number">3.6</span> Orange juice</h2>
<p>We will read in the orange juice data again,
in <a href="http://ritsokiguess.site/datafiles/ojuice.txt">link</a>, and make a suitable graph.</p>
<ol style="list-style-type: lower-alpha">
<li>The data values are separated by a space. Use the appropriate
Tidyverse function to read the data directly from the course website
into a “tibble”.</li>
</ol>
<p>Solution</p>
<p>As before,</p>
<div class="sourceCode" id="cb2"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb2-1" title="1">url &lt;-<span class="st"> &quot;http://ritsokiguess.site/datafiles/ojuice.txt&quot;</span></a>
<a class="sourceLine" id="cb2-2" title="2">juice &lt;-<span class="st"> </span><span class="kw">read_delim</span>(url, <span class="st">&quot; &quot;</span>)</a></code></pre></div>
<pre><code>## 
## ── Column specification ──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
## cols(
##   run = col_double(),
##   sweetness = col_double(),
##   pectin = col_double()
## )</code></pre>
<div class="sourceCode" id="cb4"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb4-1" title="1">juice</a></code></pre></div>
<pre><code>## # A tibble: 24 x 3
##      run sweetness pectin
##    &lt;dbl&gt;     &lt;dbl&gt;  &lt;dbl&gt;
##  1     1       5.2    220
##  2     2       5.5    227
##  3     3       6      259
##  4     4       5.9    210
##  5     5       5.8    224
##  6     6       6      215
##  7     7       5.8    231
##  8     8       5.6    268
##  9     9       5.6    239
## 10    10       5.9    212
## # … with 14 more rows</code></pre>
<p>24 runs, as we had before.</p>
<p><span class="math inline">\(\blacksquare\)</span></p>
<ol start="2" style="list-style-type: lower-alpha">
<li>The juice manufacturer was interested in whether there was a
relationship between sweetness and pectin. To assess this, draw a
scatterplot. Does it look as if there is any kind of a
relationship? (I think <code>sweetness</code> is the outcome variable
and <code>pectin</code> is explanatory, so draw your scatterplot
appropriately.)</li>
</ol>
<p>Solution</p>
<p>This requires a <code>ggplot</code> plot. You can go back and look
at the lecture notes to figure out how to make a scatterplot:
the “what to plot” is the <span class="math inline">\(x\)</span>-axis and <span class="math inline">\(y\)</span>-axis variables,
with the response on the <span class="math inline">\(y\)</span>-axis (starting with a data frame
to get the variables from), and the “how to plot” is
<code>geom_point</code> to plot the points:</p>
<div class="sourceCode" id="cb6"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb6-1" title="1"><span class="kw">ggplot</span>(juice, <span class="kw">aes</span>(<span class="dt">x =</span> pectin, <span class="dt">y =</span> sweetness)) <span class="op">+</span><span class="st"> </span><span class="kw">geom_point</span>()</a></code></pre></div>
<p><img src="pasias_files/figure-html/unnamed-chunk-33-1.png" width="672" /></p>
<p>It looks to me as if there is a negative relationship: as pectin goes
up, sweetness tends to go <em>down</em>. The trend appears to go top
left to bottom right.</p>
<p>Extra: having said that, I’m wondering how much of the
apparent trend is caused by those two observations bottom right with
pectin over 350. If you take those away, the trend seems to me to be a
lot less convincing. You could add a smooth trend to the plot, thus:</p>
<div class="sourceCode" id="cb7"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb7-1" title="1"><span class="kw">ggplot</span>(juice, <span class="kw">aes</span>(<span class="dt">x =</span> pectin, <span class="dt">y =</span> sweetness)) <span class="op">+</span><span class="st"> </span><span class="kw">geom_point</span>() <span class="op">+</span><span class="st"> </span><span class="kw">geom_smooth</span>()</a></code></pre></div>
<pre><code>## `geom_smooth()` using method = &#39;loess&#39; and formula &#39;y ~ x&#39;</code></pre>
<p><img src="pasias_files/figure-html/unnamed-chunk-34-1.png" width="672" /></p>
<p>The smooth trend is kind of downhill, but not very convincing.</p>
<p><span class="math inline">\(\blacksquare\)</span></p>
</div>
<div id="making-soap-1" class="section level2">
<h2><span class="header-section-number">3.7</span> Making soap</h2>
<p>Previously, we learned about a company that operates two production lines in a factory for
making soap bars. The production lines were
labelled A and B. A production line that moves faster may produce more
soap, but may possibly also produce more “scrap” (that is, bits of
soap that
can no longer be made into soap bars and will have to be thrown away).</p>
<p>The data are in <a href="http://ritsokiguess.site/datafiles/soap.txt">link</a>.</p>
<ol style="list-style-type: lower-alpha">
<li>Read the data into R again.</li>
</ol>
<p>Solution</p>
<p>Read directly from the URL, most easily:</p>
<div class="sourceCode" id="cb9"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb9-1" title="1">url &lt;-<span class="st"> &quot;http://ritsokiguess.site/datafiles/soap.txt&quot;</span></a>
<a class="sourceLine" id="cb9-2" title="2">soap &lt;-<span class="st"> </span><span class="kw">read_delim</span>(url, <span class="st">&quot; &quot;</span>)</a></code></pre></div>
<pre><code>## 
## ── Column specification ──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
## cols(
##   case = col_double(),
##   scrap = col_double(),
##   speed = col_double(),
##   line = col_character()
## )</code></pre>
<div class="sourceCode" id="cb11"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb11-1" title="1">soap</a></code></pre></div>
<pre><code>## # A tibble: 27 x 4
##     case scrap speed line 
##    &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;chr&gt;
##  1     1   218   100 a    
##  2     2   248   125 a    
##  3     3   360   220 a    
##  4     4   351   205 a    
##  5     5   470   300 a    
##  6     6   394   255 a    
##  7     7   332   225 a    
##  8     8   321   175 a    
##  9     9   410   270 a    
## 10    10   260   170 a    
## # … with 17 more rows</code></pre>
<p>27 rows. <code>line</code>, which is either <code>a</code> or <code>b</code>, was
correctly deduced to be text.</p>
<p><span class="math inline">\(\blacksquare\)</span></p>
<ol start="2" style="list-style-type: lower-alpha">
<li>Obtain a histogram of the <code>scrap</code> values, using 10
bins for your histogram.</li>
</ol>
<p>Solution</p>
<div class="sourceCode" id="cb13"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb13-1" title="1"><span class="kw">ggplot</span>(soap, <span class="kw">aes</span>(<span class="dt">x =</span> scrap)) <span class="op">+</span><span class="st"> </span><span class="kw">geom_histogram</span>(<span class="dt">bins =</span> <span class="dv">10</span>)</a></code></pre></div>
<p><img src="pasias_files/figure-html/unnamed-chunk-36-1.png" width="672" /></p>
<p><span class="math inline">\(\blacksquare\)</span></p>
<ol start="3" style="list-style-type: lower-alpha">
<li>Comment briefly on the shape of the histogram. Is it approximately
symmetric, skewed to the left, skewed to the right or something else? (By “comment briefly” I mean “say in a few words why you gave the answer you did.”)</li>
</ol>
<p>Solution</p>
<p>I would call this “bimodal”. There are two peaks to the
histogram, one around 250 and one around 370, with a very small
frequency in between (the bar around 300).
Apart from the bimodality, there is no particular evidence for a
long tail on either end, so I don’t think you could otherwise
call it anything other than symmetric.
Having said that (this is going beyond the question), the way a
histogram looks can depend on the bins you choose to draw it
with. This is 8 bins rather than 10:</p>
<div class="sourceCode" id="cb14"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb14-1" title="1"><span class="kw">ggplot</span>(soap, <span class="kw">aes</span>(<span class="dt">x =</span> scrap)) <span class="op">+</span><span class="st"> </span><span class="kw">geom_histogram</span>(<span class="dt">bins =</span> <span class="dv">8</span>)</a></code></pre></div>
<p><img src="pasias_files/figure-html/unnamed-chunk-37-1.png" width="672" /></p>
<p>The middle low-frequency bin has gone, and this one just looks
symmetric, with a kind of “flat top”.</p>
<p><span class="math inline">\(\blacksquare\)</span></p>
<ol start="4" style="list-style-type: lower-alpha">
<li>Make side-by-side boxplots of scrap values for each
production line.</li>
</ol>
<p>Solution</p>
<div class="sourceCode" id="cb15"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb15-1" title="1"><span class="kw">ggplot</span>(soap, <span class="kw">aes</span>(<span class="dt">x =</span> line, <span class="dt">y =</span> scrap)) <span class="op">+</span><span class="st"> </span><span class="kw">geom_boxplot</span>()</a></code></pre></div>
<p><img src="pasias_files/figure-html/unnamed-chunk-38-1.png" width="672" /></p>
<p>One categorical, one quantitative variable, so boxplots make sense.</p>
<p><span class="math inline">\(\blacksquare\)</span></p>
<ol start="5" style="list-style-type: lower-alpha">
<li>Do you think your boxplot says that there are differences in the
amount of scrap produced by the two production lines, or not?
Explain briefly.</li>
</ol>
<p>Solution</p>
<p>I would say that there <em>is</em> a difference between the two
production lines, with line A producing an average (median) of
about 330 and line B producing a median of about 275. But you
could also make the case that, although the medians are rather
different, there is a lot of variability and hence a lot of
overlap between the two boxplots, and therefore that there is
not a “substantial” difference.
I would say that either of those answers are good . This is going to be a
common theme in this course: I am going to ask you to make a
decision and support it, where the reasons you provide are often
more
important than the decision you make.</p>
<p>Extra: you might be wondering whether the medians, or means, since
there is no serious skewness here and definitely no outliers,
are “significantly different”. This is inference, which we
will come to later, but a preview looks like this:</p>
<div class="sourceCode" id="cb16"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb16-1" title="1"><span class="kw">t.test</span>(scrap <span class="op">~</span><span class="st"> </span>line, <span class="dt">data =</span> soap)</a></code></pre></div>
<pre><code>## 
##  Welch Two Sample t-test
## 
## data:  scrap by line
## t = 1.2493, df = 21.087, p-value = 0.2253
## alternative hypothesis: true difference in means is not equal to 0
## 95 percent confidence interval:
##  -26.97888 108.21222
## sample estimates:
## mean in group a mean in group b 
##        333.5333        292.9167</code></pre>
<p>They are not: the P-value of 0.22 is not anywhere near as small as
0.05, so we can’t reject the null hypothesis that the two lines have
equal mean amount of scrap.</p>
<p>Rusty on this stuff? Don’t worry; we’re going to come back to it later
in the course.</p>
<p>I was also wondering about something else: that bimodal
histogram. Could that be explained by the scrap values being two
different production lines being mixed together? One way to understand
that is to have two separate histograms, one for each line, side by
side, which is what facetting does. There is an extra wrinkle here
that I explain afterwards:</p>
<div class="sourceCode" id="cb18"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb18-1" title="1"><span class="kw">ggplot</span>(soap, <span class="kw">aes</span>(<span class="dt">x =</span> scrap)) <span class="op">+</span><span class="st"> </span><span class="kw">geom_histogram</span>(<span class="dt">bins =</span> <span class="dv">10</span>) <span class="op">+</span><span class="st"> </span><span class="kw">facet_grid</span>(line <span class="op">~</span><span class="st"> </span>.)</a></code></pre></div>
<p><img src="pasias_files/figure-html/unnamed-chunk-40-1.png" width="672" /></p>
<p>I could have used <code>facet_wrap</code>, but that would have put the
histograms side by side, and I wanted them one above the other (for
ease of comparison, since they’ll be on the same
scale). <code>facet_grid</code> is like <code>facet_wrap</code>, but offers
you more control over where the facets go: you can arrange them above
and below by a variable, or left and right by a variable. Whatever is
facetting the plots up and down (on the <span class="math inline">\(y\)</span> axis) goes before the
squiggle, and whatever facets them left and right goes after. If there
is nothing separating the facets in one direction, here horizontally,
the variable is replaced by a dot.</p>
<p>In some ways, <code>facet_grid</code> is also <em>less</em> flexible,
because the facets have to be arranged up/down or left/right by a
variable. That worked here, but if you think back to the Australian
athletes, where there were ten different sports, it was
<code>facet_wrap</code> that did the right thing, arranging the sports
along rows <em>and</em> columns to produce a pleasing display.</p>
<p>All right, that bimodality. I was expecting that the scrap values from
one line would be centred about one value and the scrap values from
the other line would be centred about a different value, with a gap in
between. But that’s not what happened at all: the line B values are
all over the place, while it’s the line A values that are actually
bimodal all by themselves. I’m not sure whether that really means
anything, since the data sets are pretty small, but it’s kind of
interesting.</p>
<p><span class="math inline">\(\blacksquare\)</span></p>
<ol start="6" style="list-style-type: lower-alpha">
<li>We started out with the suspicion that if the line was run
faster, there would be more scrap. We haven’t assessed this
yet. Draw a scatter plot with <code>scrap</code> on the <span class="math inline">\(y\)</span> axis and
<code>speed</code> on the <span class="math inline">\(x\)</span> axis.</li>
</ol>
<p>Solution</p>
<p>Same mechanism as before:</p>
<div class="sourceCode" id="cb19"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb19-1" title="1"><span class="kw">ggplot</span>(soap, <span class="kw">aes</span>(<span class="dt">x =</span> speed, <span class="dt">y =</span> scrap)) <span class="op">+</span><span class="st"> </span><span class="kw">geom_point</span>()</a></code></pre></div>
<p><img src="pasias_files/figure-html/unnamed-chunk-41-1.png" width="672" /></p>
<p><span class="math inline">\(\blacksquare\)</span></p>
<ol start="7" style="list-style-type: lower-alpha">
<li>What do you think is the most important conclusion from
your plot of the previous part? Describe your conclusion in the
context of the data.</li>
</ol>
<p>Solution</p>
<p>There seems to be a pretty evident upward trend, apparently
linear, which means that if the speed of the production line is
higher, the amount of scrap produced is also higher.
My last sentence was meant to remind you that
“there is an upward trend” is <em>not a complete answer</em>:
we are concerned
with what that upward trend tells us about the data.
This, in other words, confirms the suspicion expressed in the
question, which was therefore a rather large clue: more speed
tends to go with more scrap.
That was as far as I wanted you to go: there seems to be an
association with speed, and there might be an association with
<code>line</code> that turned out not to be statistically significant.
What we haven’t done is to assess the relationship between speed
and scrap for <em>each</em> production line. To do that, we want
to plot the scrap-speed points distinguished for each production
line. <code>ggplot</code> makes that easy: you add a
<code>colour</code><a href="#fn1" class="footnote-ref" id="fnref1"><sup>1</sup></a> to say what you want to
distinguish by colour. This is two quantitative variables and one
categorical variable, if you want to think of it that way:</p>
<div class="sourceCode" id="cb20"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb20-1" title="1"><span class="kw">ggplot</span>(soap, <span class="kw">aes</span>(<span class="dt">x =</span> speed, <span class="dt">y =</span> scrap, <span class="dt">colour =</span> line)) <span class="op">+</span><span class="st"> </span><span class="kw">geom_point</span>()</a></code></pre></div>
<p><img src="pasias_files/figure-html/unnamed-chunk-42-1.png" width="672" /></p>
<p>Notice that we get a legend, automatically.</p>
<p>What is interesting about this one is the red dots are mostly at the
top (for any given speed), and the blue dots are mostly at the
bottom. That seems to mean that <em>when we account for speed</em>,
there is a difference between lines.</p>
<p>I want to show you one more embellishment, which is to put the
regression lines on the plot for each group separately. This is where
<code>ggplot</code> is so nice, since I just have to add one thing:</p>
<div class="sourceCode" id="cb21"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb21-1" title="1"><span class="kw">ggplot</span>(soap, <span class="kw">aes</span>(<span class="dt">x =</span> speed, <span class="dt">y =</span> scrap, <span class="dt">colour =</span> line)) <span class="op">+</span></a>
<a class="sourceLine" id="cb21-2" title="2"><span class="st">  </span><span class="kw">geom_point</span>() <span class="op">+</span><span class="st"> </span><span class="kw">geom_smooth</span>(<span class="dt">method =</span> <span class="st">&quot;lm&quot;</span>, <span class="dt">se =</span> F)</a></code></pre></div>
<pre><code>## `geom_smooth()` using formula &#39;y ~ x&#39;</code></pre>
<p><img src="pasias_files/figure-html/unnamed-chunk-43-1.png" width="672" /></p>
<p>The points and lines have come out in different colours, without our
having to think too hard.</p>
<p>Both lines show an upward trend, with about the same slope, which
means that regardless of line, increasing the speed goes with
increasing the scrap by the same amount. The fact that the red line is
above the blue one, however, suggests that production line A produces
more scrap at the same speed than production line B.</p>
<p>From a management point of view, there is an interesting dynamic at
work: if you run the production line faster, you’ll produce more bars
of soap, but you’ll produce more scrap as well. The crucial thing for
the people in the supervisor’s office is how much raw material is used
per bar of soap, and if you make the soap bars faster, you might use
more raw material, which will eat into your profits (from one angle),
but you will also have more bars of soap to sell.</p>
<p>Here’s another way to see the same thing. I’m <em>definitely</em> not
expecting you to follow the code, but you can admire the result!</p>
<div class="sourceCode" id="cb23"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb23-1" title="1">soap2 &lt;-<span class="st"> </span>soap <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">select</span>(<span class="op">-</span>line)</a>
<a class="sourceLine" id="cb23-2" title="2"><span class="kw">ggplot</span>(soap, <span class="kw">aes</span>(<span class="dt">x =</span> speed, <span class="dt">y =</span> scrap)) <span class="op">+</span></a>
<a class="sourceLine" id="cb23-3" title="3"><span class="st">  </span><span class="kw">geom_point</span>(<span class="dt">data =</span> soap2, <span class="dt">colour =</span> <span class="st">&quot;grey&quot;</span>) <span class="op">+</span></a>
<a class="sourceLine" id="cb23-4" title="4"><span class="st">  </span><span class="kw">geom_point</span>(<span class="kw">aes</span>(<span class="dt">colour =</span> line)) <span class="op">+</span><span class="st"> </span><span class="kw">facet_wrap</span>(<span class="op">~</span>line)</a></code></pre></div>
<p><img src="pasias_files/figure-html/unnamed-chunk-44-1.png" width="672" />
$</p>
<p>The idea is that we plot all the points in grey (to
“put them in the background”)
and then in each plot we plot the points again,
<em>coloured, for the group we are looking at</em>: line A in the left,
line B on the right. This is another way of seeing that line A has
more scrap than line B, given the speed at which the line was being
run. (I discovered this technique only yesterday. I think the code is
remarkably concise for what it does.)</p>
<p>The logic of the code is:</p>
<ul>
<li><p>create a new data frame that contains everything in
<code>soap</code> except for <code>line</code></p></li>
<li><p>make a scatter plot of all the points in this new data frame,
coloured grey</p></li>
<li><p>plot the points again (from the original data frame), coloured by
which production line they’re from</p></li>
<li><p>produce a separate scatterplot for each production line.</p></li>
</ul>
<p>The trick about creating the new data frame was to enable plotting of
all points regardless of group on each subplot (“facet” in
<code>ggplot</code> terminology), as well as the ones that come from that
production line.</p>
<p>I don’t expect you to be able to follow all the details of the code
below, either,
but I would like you to try and get the logic. What we do is a
regression predicting <code>scrap</code> from <em>two</em> things:
<code>speed</code> and production <code>line</code>. The results we get are these:</p>
<div class="sourceCode" id="cb24"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb24-1" title="1">scrap<span class="fl">.1</span> &lt;-<span class="st"> </span><span class="kw">lm</span>(scrap <span class="op">~</span><span class="st"> </span>speed <span class="op">+</span><span class="st"> </span>line, <span class="dt">data =</span> soap)</a>
<a class="sourceLine" id="cb24-2" title="2"><span class="kw">summary</span>(scrap<span class="fl">.1</span>)</a></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = scrap ~ speed + line, data = soap)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -39.557 -14.161  -0.121  17.518  33.953 
## 
## Coefficients:
##              Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)  80.41099   14.54379   5.529 1.10e-05 ***
## speed         1.23074    0.06555  18.775 7.48e-16 ***
## lineb       -53.12920    8.21003  -6.471 1.08e-06 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 21.13 on 24 degrees of freedom
## Multiple R-squared:  0.9402, Adjusted R-squared:  0.9352 
## F-statistic: 188.6 on 2 and 24 DF,  p-value: 2.104e-15</code></pre>
<p>The P-values for <code>speed</code> and <code>line</code> are the second and
third things in the last column, <span class="math inline">\(7 \times 10^{-16}\)</span> and <span class="math inline">\(1 \times 10^{-6}\)</span>
respectively. These are both very strongly significant, in contrast to
the two-sample <span class="math inline">\(t\)</span>-test where <code>line</code> was not significant.</p>
<p>So does production line make a difference or not?</p>
<p>The plot says that it does, and the meaning of model <code>scrap.1</code>
just above is that
, and
.
(In the two-sample <span class="math inline">\(t\)</span>-test above we didn’t
account for speed at all, since the various speeds were all mixed up.)</p>
<p>There is a moral to this story, which I would like you to get even if
you don’t get any of the statistics: if a variable makes a
difference, it should be in your model and on your
graph,<a href="#fn2" class="footnote-ref" id="fnref2"><sup>2</sup></a>
because it enables you to get better (more precise) conclusions about your
other variables. Here, there really is a difference between the
production lines, but the <span class="math inline">\(t\)</span>-test was too much of a blunt instrument
to unearth it (because <code>speed</code> made a difference as well).</p>
<p><span class="math inline">\(\blacksquare\)</span></p>
</div>
<div id="handling-shipments-1" class="section level2">
<h2><span class="header-section-number">3.8</span> Handling shipments</h2>
<p>We learned earlier about a company called Global Electronics that
imports shipments of a certain large part used as a
component in several of its products. The size of the shipment varies
each time. Each shipment is sent to one of two warehouses (labelled A
and B) for handling. The data in
<a href="http://ritsokiguess.site/datafiles/global.csv">link</a> show the
<code>size</code> of each shipment (in thousands of parts) and the direct
<code>cost</code> of handling it, in thousands of dollars. Also shown is
the <code>warehouse</code> (A or B) that handled each shipment.</p>
<ol style="list-style-type: lower-alpha">
<li>Read the data into R and display your data frame.</li>
</ol>
<p>Solution</p>
<p>A <code>.csv</code>:</p>
<div class="sourceCode" id="cb26"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb26-1" title="1">url &lt;-<span class="st"> &quot;http://ritsokiguess.site/datafiles/global.csv&quot;</span></a>
<a class="sourceLine" id="cb26-2" title="2">shipments &lt;-<span class="st"> </span><span class="kw">read_csv</span>(url)</a></code></pre></div>
<pre><code>## 
## ── Column specification ──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
## cols(
##   warehouse = col_character(),
##   size = col_double(),
##   cost = col_double()
## )</code></pre>
<div class="sourceCode" id="cb28"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb28-1" title="1">shipments</a></code></pre></div>
<pre><code>## # A tibble: 10 x 3
##    warehouse  size  cost
##    &lt;chr&gt;     &lt;dbl&gt; &lt;dbl&gt;
##  1 A           225 12.0 
##  2 B           350 14.1 
##  3 A           150  8.93
##  4 A           200 11.0 
##  5 A           175 10.0 
##  6 A           180 10.1 
##  7 B           325 13.8 
##  8 B           290 13.3 
##  9 B           400 15   
## 10 A           125  7.97</code></pre>
<p><span class="math inline">\(\blacksquare\)</span></p>
<ol start="2" style="list-style-type: lower-alpha">
<li>Make a scatterplot of the cost of handling each shipment as it
depends on the shipment’s size.</li>
</ol>
<p>Solution</p>
<p>The wording of the question says that cost is the response and so
belongs on the <span class="math inline">\(y\)</span>-axis. To make the plot, <code>ggplot</code> with an
<code>x=</code> and a <code>y=</code> in the <code>aes</code> (the “what to plot”
part), and a <code>geom_point()</code> after (the “how to plot it”):</p>
<div class="sourceCode" id="cb30"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb30-1" title="1"><span class="kw">ggplot</span>(shipments, <span class="kw">aes</span>(<span class="dt">x =</span> size, <span class="dt">y =</span> cost)) <span class="op">+</span><span class="st"> </span><span class="kw">geom_point</span>()</a></code></pre></div>
<p><img src="pasias_files/figure-html/unnamed-chunk-47-1.png" width="672" /></p>
<p>As a matter of coding, there are usually <em>two</em> brackets to close
after the <code>aes</code>, the one that begins the <code>ggplot</code> and
the one that begins the <code>aes</code>.</p>
<p><span class="math inline">\(\blacksquare\)</span></p>
<ol start="3" style="list-style-type: lower-alpha">
<li>What kind of relationship do you see on the scatterplot? Do
you think a straight line would describe it appropriately? Explain briefly.</li>
</ol>
<p>Solution</p>
<p>I see an upward trend: a shipment with larger <code>size</code> costs
more to handle.
If you look carefully at the scatterplot, you see that the cost of
handling a small shipment goes up fairly steeply with its size,
but the cost of handling a large shipment, while it still
increases with <code>size</code>, does not increase so fast. Thus
having one straight line to describe the whole relationship would
not work so well.
The relationship is actually two different
straight lines joined end-to-end, which we will explore later, but
if you think the relationship is curved, I’ll accept that. The
point is to get at the idea that the rate of increase is not
constant.</p>
<p><span class="math inline">\(\blacksquare\)</span></p>
<ol start="4" style="list-style-type: lower-alpha">
<li>When a shipment comes in, the cost of handling it is not
known. A decision is made about which warehouse to send it to, and
then, after it is handled, the cost is recorded. What do you think
determines which warehouse an incoming shipment goes to? Provide a
graph to support your answer.</li>
</ol>
<p>Solution</p>
<p>The veiled hint in the question is that the decision must depend
on <code>size</code>, since it cannot depend on <code>cost</code>. So we
have one quantitative variable <code>size</code> and one categorical
variable <code>warehouse</code>, which suggests drawing boxplots:</p>
<div class="sourceCode" id="cb31"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb31-1" title="1"><span class="kw">ggplot</span>(shipments, <span class="kw">aes</span>(<span class="dt">x =</span> warehouse, <span class="dt">y =</span> size)) <span class="op">+</span><span class="st"> </span><span class="kw">geom_boxplot</span>()</a></code></pre></div>
<p><img src="pasias_files/figure-html/unnamed-chunk-48-1.png" width="672" /></p>
<p>Well, there’s the answer right there. When the shipment has small
<code>size</code>, it goes to warehouse A, and when it’s large, it goes to
Warehouse B. We know this because <em>all</em> the shipments smaller
than about 250 (thousand parts) went to A and <em>all</em> the shipments
larger than that went to B. (If you want to provide a number to
delineate “small” and “large”, anything between the largest A,
about 225, and the smallest B, about 290, will do.)</p>
<p>Another way to think about this is to add something to the scatterplot
you drew before. The obvious thing is to make the two warehouses
different colours:</p>
<div class="sourceCode" id="cb32"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb32-1" title="1"><span class="kw">ggplot</span>(shipments, <span class="kw">aes</span>(<span class="dt">x =</span> size, <span class="dt">y =</span> cost, <span class="dt">colour =</span> warehouse)) <span class="op">+</span></a>
<a class="sourceLine" id="cb32-2" title="2"><span class="st">  </span><span class="kw">geom_point</span>()</a></code></pre></div>
<p><img src="pasias_files/figure-html/unnamed-chunk-49-1.png" width="672" /></p>
<p>As a point of technique, you can split lines of code to make them fit
on your screen. You can do this as long as , so that R knows more is to
come. Ending a line with a pipe symbol, or, as here, with one of the
pluses in the middle of a <code>ggplot</code>, will work. If you put the
plus on the start of the next line, you’ll get a blank plot, because R
thinks you’re done plotting. Try it and see.</p>
<p>Anyway, this plot tells exactly the same story: the small shipments
(in size or cost) go to Warehouse A and the large ones to Warehouse
B. But we don’t know cost when the decision is made about which
warehouse to send a shipment to, so the decision must be based on
<code>size</code>.</p>
<p>In the place where I got these data, it said “larger shipments are sent to Warehouse B, since this warehouse has specialized equipment that provides greater economies of scale for larger shipments”.
That
is to say, very large shipments are more expensive to handle, but not
as expensive as you might think.<a href="#fn3" class="footnote-ref" id="fnref3"><sup>3</sup></a>
That makes sense with our scatterplot, because the
<em>slope</em> for larger shipments is less than for smaller shipments.</p>
<p>When we get to regression later, we’ll see what happens if we fit a
straight line to data like these, and how to tell whether we really
ought to be able to do better with a different form of
relationship. There is also a trick to fit what is called a
“piecewise linear regression”, which has one slope for small
shipment sizes, a different (smaller) slope for large ones, and joins
up in the middle. But that’s well beyond our scope now.</p>
<p><span class="math inline">\(\blacksquare\)</span></p>
</div>
<div id="rainfall-in-davis-california-1" class="section level2">
<h2><span class="header-section-number">3.9</span> Rainfall in Davis, California</h2>
<p>One way to assess climate change is to look at weather
records over a number of years and to identify any changes.</p>
<p>Annual rainfall data for the Davis, California is in
<a href="http://ritsokiguess.site/datafiles/rainfall.txt">here</a>.
(Right-click on the URL and select Copy Link Address, then paste into your R Notebook.)
The rainfall is
measured in inches.</p>
<ol style="list-style-type: lower-alpha">
<li>Read in and display (some of) the data. Briefly justify why you coded it as you did.</li>
</ol>
<p>Solution</p>
<p>Look at the data file, and see that the values are separated by a
single space, so  will do it. (This is the brief justification.) You <em>need to have some words</em> in this part explaining your choice of <code>read_delim</code> (or <code>read_table</code>: see below).</p>
<p>Read straight from
the URL rather than copying and pasting the data or doing anything like that:<a href="#fn4" class="footnote-ref" id="fnref4"><sup>4</sup></a></p>
<div class="sourceCode" id="cb33"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb33-1" title="1">my_url &lt;-<span class="st"> &quot;http://ritsokiguess.site/datafiles/rainfall.txt&quot;</span></a>
<a class="sourceLine" id="cb33-2" title="2">rain &lt;-<span class="st"> </span><span class="kw">read_delim</span>(my_url, <span class="st">&quot; &quot;</span>)</a></code></pre></div>
<pre><code>## 
## ── Column specification ──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
## cols(
##   Year = col_double(),
##   Rainfall = col_double()
## )</code></pre>
<div class="sourceCode" id="cb35"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb35-1" title="1">rain</a></code></pre></div>
<pre><code>## # A tibble: 47 x 2
##     Year Rainfall
##    &lt;dbl&gt;    &lt;dbl&gt;
##  1  1951     20.7
##  2  1952     16.7
##  3  1953     13.5
##  4  1954     14.1
##  5  1955     25.4
##  6  1956     12.0
##  7  1957     28.7
##  8  1958     11.0
##  9  1959     12.6
## 10  1960     12.8
## # … with 37 more rows</code></pre>
<p>Note for later that the  and the  have
Capital Letters. You can call the data frame whatever you like, but I
think something descriptive is better than eg. .</p>
<p>Extra 1: <code>read_delim</code> works because there is exactly one space between the year and the
rainfall amount. But the year is always four digits, so the columns
line up, and there is a space all the way down between the year and
the rainfall. That is to say, another possibility for your “brief justification” is that the columns are lined up all the way down.
That means that this will also work:</p>
<div class="sourceCode" id="cb37"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb37-1" title="1">my_url &lt;-<span class="st"> &quot;http://ritsokiguess.site/datafiles/rainfall.txt&quot;</span></a>
<a class="sourceLine" id="cb37-2" title="2">rain &lt;-<span class="st"> </span><span class="kw">read_table</span>(my_url)</a></code></pre></div>
<pre><code>## 
## ── Column specification ──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
## cols(
##   Year = col_double(),
##   Rainfall = col_double()
## )</code></pre>
<div class="sourceCode" id="cb39"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb39-1" title="1">rain</a></code></pre></div>
<pre><code>## # A tibble: 47 x 2
##     Year Rainfall
##    &lt;dbl&gt;    &lt;dbl&gt;
##  1  1951     20.7
##  2  1952     16.7
##  3  1953     13.5
##  4  1954     14.1
##  5  1955     25.4
##  6  1956     12.0
##  7  1957     28.7
##  8  1958     11.0
##  9  1959     12.6
## 10  1960     12.8
## # … with 37 more rows</code></pre>
<p>This is therefore also good.</p>
<p>It also looks as if it could be tab-separated values, since the rainfall
column always starts in the same place, but if you try it, you’ll find
that it doesn’t work:</p>
<div class="sourceCode" id="cb41"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb41-1" title="1">my_url &lt;-<span class="st"> &quot;http://ritsokiguess.site/datafiles/rainfall.txt&quot;</span></a>
<a class="sourceLine" id="cb41-2" title="2">rain_nogood &lt;-<span class="st"> </span><span class="kw">read_tsv</span>(my_url)</a></code></pre></div>
<pre><code>## 
## ── Column specification ──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
## cols(
##   `Year Rainfall` = col_character()
## )</code></pre>
<div class="sourceCode" id="cb43"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb43-1" title="1">rain_nogood</a></code></pre></div>
<pre><code>## # A tibble: 47 x 1
##    `Year Rainfall`
##    &lt;chr&gt;          
##  1 1951 20.66     
##  2 1952 16.72     
##  3 1953 13.51     
##  4 1954 14.1      
##  5 1955 25.37     
##  6 1956 12.05     
##  7 1957 28.74     
##  8 1958 10.98     
##  9 1959 12.55     
## 10 1960 12.75     
## # … with 37 more rows</code></pre>
<p>This looks as if it worked, but it didn’t, because there is only
 column, of years and rainfalls smooshed together as text,
and if you try to do anything else with them later it won’t work.<a href="#fn5" class="footnote-ref" id="fnref5"><sup>5</sup></a></p>
<p>Hence those values that might have been tabs actually were
not. There’s no way to be sure about this; you have to try something
and see what works.<a href="#fn6" class="footnote-ref" id="fnref6"><sup>6</sup></a></p>
<p>Extra 2: <code>read.table</code> with a dot will work, but it is in this course <em>wrong</em>. As I stated in the course outline, I expect you to do things <em>as they are done in this course</em>. Strictly speaking, if you use <code>read.table</code>, which you did not learn from me, and you say nothing about where you got it from, you are guilty of plagiarism, which is an academic offence. I will probably not be that strict, but you should certainly expect to lose credit for doing things differently from how they are done in this course. The idea is that you need to demonstrate that you have learned something <em>here</em>.</p>
<p><span class="math inline">\(\blacksquare\)</span></p>
<ol start="2" style="list-style-type: lower-alpha">
<li>Make a suitable plot of the rainfall values and years. Explain briefly why you drew the plot you did.</li>
</ol>
<p>Solution</p>
<p>This is two quantitative variables, so a scatterplot makes
sense. (That’s the brief explanation.) To decide which variable goes on which axis, think of
rainfall as a response to the explanatory variable year, or note
that time goes by tradition on the horizontal axis:</p>
<div class="sourceCode" id="cb45"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb45-1" title="1"><span class="kw">ggplot</span>(rain, <span class="kw">aes</span>(<span class="dt">x=</span>Year, <span class="dt">y=</span>Rainfall)) <span class="op">+</span><span class="st"> </span><span class="kw">geom_point</span>()</a></code></pre></div>
<p><img src="pasias_files/figure-html/unnamed-chunk-53-1.png" width="672" /></p>
<p>This is a time trend, so it would also be reasonable to join the points with lines:</p>
<div class="sourceCode" id="cb46"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb46-1" title="1"><span class="kw">ggplot</span>(rain, <span class="kw">aes</span>(<span class="dt">x=</span>Year, <span class="dt">y=</span>Rainfall)) <span class="op">+</span><span class="st"> </span><span class="kw">geom_point</span>() <span class="op">+</span><span class="st"> </span><span class="kw">geom_line</span>()</a></code></pre></div>
<p><img src="pasias_files/figure-html/unnamed-chunk-54-1.png" width="672" /></p>
<p>and because any trend looks irregular, you could also justify putting a smooth trend through the points:</p>
<div class="sourceCode" id="cb47"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb47-1" title="1"><span class="kw">ggplot</span>(rain, <span class="kw">aes</span>(<span class="dt">x=</span>Year, <span class="dt">y=</span>Rainfall)) <span class="op">+</span><span class="st"> </span><span class="kw">geom_point</span>() <span class="op">+</span><span class="st"> </span><span class="kw">geom_smooth</span>()</a></code></pre></div>
<pre><code>## `geom_smooth()` using method = &#39;loess&#39; and formula &#39;y ~ x&#39;</code></pre>
<p><img src="pasias_files/figure-html/unnamed-chunk-55-1.png" width="672" /></p>
<p>This one is rather interesting (as an aside): there is a more noticeable upward trend at the end, after about 1985. If you study environmental science, you may have seen that a lot of time plots of climate data show a bigger change after about 1990, and this is one of those.</p>
<p>If you treat the year as categorical, and try to draw a boxplot, it won’t work out so well:</p>
<div class="sourceCode" id="cb49"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb49-1" title="1"><span class="kw">ggplot</span>(rain, <span class="kw">aes</span>(<span class="dt">x=</span>Year, <span class="dt">y=</span>Rainfall)) <span class="op">+</span><span class="st"> </span><span class="kw">geom_boxplot</span>()</a></code></pre></div>
<pre><code>## Warning: Continuous x aesthetic -- did you forget aes(group=...)?</code></pre>
<p><img src="pasias_files/figure-html/unnamed-chunk-56-1.png" width="672" /></p>
<p>This is actually a boxplot of rainfall in all the years together; it ignored year because it couldn’t figure out what you wanted to do with it. The warning message is indicating that you might have forgotten something that defines groups; the <code>x</code> is quantitative here. So you have to clarify what you meant. For example, you might have meant to treat the years as categorical, which you could do like this:</p>
<div class="sourceCode" id="cb51"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb51-1" title="1"><span class="kw">ggplot</span>(rain, <span class="kw">aes</span>(<span class="dt">x=</span><span class="kw">factor</span>(Year), <span class="dt">y=</span>Rainfall)) <span class="op">+</span><span class="st"> </span><span class="kw">geom_boxplot</span>()</a></code></pre></div>
<p><img src="pasias_files/figure-html/unnamed-chunk-57-1.png" width="672" /></p>
<p>Aside from the fact that you have too many years to see them all, you only have <em>one</em> observation per year (that year’s annual rainfall), so you don’t get an actual box. To get boxes, you need to organize groups where you have multiple observations, for example decades:</p>
<div class="sourceCode" id="cb52"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb52-1" title="1">rain <span class="op">%&gt;%</span><span class="st"> </span></a>
<a class="sourceLine" id="cb52-2" title="2"><span class="st">  </span><span class="kw">mutate</span>(<span class="dt">decade_number =</span> Year <span class="op">%/%</span><span class="st"> </span><span class="dv">10</span>) <span class="op">%&gt;%</span><span class="st"> </span></a>
<a class="sourceLine" id="cb52-3" title="3"><span class="st">  </span><span class="kw">mutate</span>(<span class="dt">decade =</span> <span class="kw">str_c</span>(decade_number, <span class="st">&quot;0s&quot;</span>)) <span class="op">%&gt;%</span><span class="st"> </span></a>
<a class="sourceLine" id="cb52-4" title="4"><span class="st">  </span><span class="kw">ggplot</span>(<span class="kw">aes</span>(<span class="dt">x =</span> decade, <span class="dt">y =</span> Rainfall)) <span class="op">+</span><span class="st"> </span><span class="kw">geom_boxplot</span>()</a></code></pre></div>
<p><img src="pasias_files/figure-html/unnamed-chunk-58-1.png" width="672" /></p>
<p>You see that there seems to have been an upward jump in rainfall in the 1990s (the last decade in the data).</p>
<p>About the code: `%/%’ does “integer division” (throws away the fractional part if there is one), so the calculation turns eg. 1954 into 195. I wanted to have the graph display something you could understand, so I constructed some text out of the decade number by gluing a 0 and a letter s onto the end.</p>
<p>Another kind of situation where this approach does work is if you have something like monthly rainfall over a number of years, and then you have multiple values for January over all the years that you have data for.</p>
<p><span class="math inline">\(\blacksquare\)</span></p>
<ol start="3" style="list-style-type: lower-alpha">
<li>Add a regression line to your plot. Is there any convincing
indication of a trend, upward or downward, in annual rainfall for
Davis, California? Discuss briefly.</li>
</ol>
<p>Solution</p>
<p>Thus:</p>
<div class="sourceCode" id="cb53"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb53-1" title="1"><span class="kw">ggplot</span>(rain, <span class="kw">aes</span>(<span class="dt">x=</span>Year, <span class="dt">y=</span>Rainfall)) <span class="op">+</span><span class="st"> </span><span class="kw">geom_point</span>() <span class="op">+</span><span class="st"> </span></a>
<a class="sourceLine" id="cb53-2" title="2"><span class="kw">geom_smooth</span>(<span class="dt">method=</span><span class="st">&quot;lm&quot;</span>)</a></code></pre></div>
<pre><code>## `geom_smooth()` using formula &#39;y ~ x&#39;</code></pre>
<p><img src="pasias_files/figure-html/unnamed-chunk-59-1.png" width="672" /></p>
<p>The regression line goes uphill, but this is not convincing evidence
of an overall upward trend for several reasons (pick one):</p>

<p>Further evidence comes from a regression (which we haven’t looked at
yet):</p>
<div class="sourceCode" id="cb55"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb55-1" title="1">r<span class="fl">.1</span> &lt;-<span class="st"> </span><span class="kw">lm</span>(Rainfall<span class="op">~</span>Year, <span class="dt">data=</span>rain)</a>
<a class="sourceLine" id="cb55-2" title="2"><span class="kw">summary</span>(r<span class="fl">.1</span>)</a></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = Rainfall ~ Year, data = rain)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -12.670  -5.252  -1.905   7.088  17.804 
## 
## Coefficients:
##               Estimate Std. Error t value Pr(&gt;|t|)
## (Intercept) -208.57325  158.42281  -1.317    0.195
## Year           0.11513    0.08025   1.435    0.158
## 
## Residual standard error: 7.463 on 45 degrees of freedom
## Multiple R-squared:  0.04373,    Adjusted R-squared:  0.02248 
## F-statistic: 2.058 on 1 and 45 DF,  p-value: 0.1583</code></pre>
<p>The slope is indeed positive, but it is not significantly different
from zero. Also, the R-squared is <em>very</em> small, 4.4%. Thus the apparent upward trend is no more than chance.</p>
<p>Extra: looking at the plot from earlier with the smooth trend suggests that there may not have been any real increase since 1950, but if you look only since about 1985 it may be different. There is a statistical question mark over that, though, because we started looking at 1985 only because there seemed to be an upward trend starting from about there.</p>
<p><span class="math inline">\(\blacksquare\)</span></p>
</div>
<div id="students-and-exercise-1" class="section level2">
<h2><span class="header-section-number">3.10</span> Students and exercise</h2>
<p>Some students in a Statistics class were asked how many
minutes they typically exercised in a week. The data are shown in
.</p>
<p>Some of the
students identified as male and some as female. Our concern is how the males
and females compare in terms of the amount of exercise they do.</p>
<ol style="list-style-type: lower-alpha">
<li>Take a look at the data file. (Click on the link, or paste the copied link into your web browser.) How is it laid out?</li>
</ol>
<p>Solution</p>
<p>Aligned in columns. Or, separated by spaces, but a variable number
of them. (The latter is a hint that  will not
work, and the former is a hint about what  work.)</p>
<p><span class="math inline">\(\blacksquare\)</span></p>
<ol start="2" style="list-style-type: lower-alpha">
<li>Read in and display (some of) the data. (This means to
display enough of what you read in to convince others that you read
in the right kind of thing.)</li>
</ol>
<p>Solution</p>
<p>“Aligned in columns” is the best way of saying it so that you
know to use . Hence:</p>
<div class="sourceCode" id="cb57"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb57-1" title="1">my_url &lt;-<span class="st"> &quot;http://ritsokiguess.site/datafiles/exercise.txt&quot;</span></a>
<a class="sourceLine" id="cb57-2" title="2">exercise &lt;-<span class="st"> </span><span class="kw">read_table</span>(my_url)</a></code></pre></div>
<pre><code>## 
## ── Column specification ──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
## cols(
##   gender = col_character(),
##   minutes = col_double()
## )</code></pre>
<div class="sourceCode" id="cb59"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb59-1" title="1">exercise</a></code></pre></div>
<pre><code>## # A tibble: 29 x 2
##    gender minutes
##    &lt;chr&gt;    &lt;dbl&gt;
##  1 female      60
##  2 female     240
##  3 female       0
##  4 female     360
##  5 female     450
##  6 female     200
##  7 female     100
##  8 female      70
##  9 female     240
## 10 female       0
## # … with 19 more rows</code></pre>
<p>Just entering the data frame name displays the first ten rows, which
is usually enough to convince anyone that you have the right thing.</p>
<p>Call the data frame what you like, as long as it describes what’s in
the data frame in some way.</p>
<p><span class="math inline">\(\blacksquare\)</span></p>
<ol start="3" style="list-style-type: lower-alpha">
<li>Make a suitable plot of this data frame.</li>
</ol>
<p>Solution</p>
<p>Two variables, one quantitative and one categorical, means that a
boxplot is the thing:</p>
<div class="sourceCode" id="cb61"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb61-1" title="1"><span class="kw">ggplot</span>(exercise, <span class="kw">aes</span>(<span class="dt">x=</span>gender, <span class="dt">y=</span>minutes)) <span class="op">+</span><span class="st"> </span><span class="kw">geom_boxplot</span>()</a></code></pre></div>
<p><img src="pasias_files/figure-html/unnamed-chunk-62-1.png" width="672" /></p>
<p><span class="math inline">\(\blacksquare\)</span></p>
<ol start="4" style="list-style-type: lower-alpha">
<li>Does there appear to be any substantial difference in the
average amount of time that males and females spend exercising?
Explain briefly. (“average” could be mean or median. Which is it
here?)</li>
</ol>
<p>Solution</p>
<p>A boxplot shows the median. So we learn here that the median time
spent exercising per week is very slightly higher for
females. However, there is a lot of variability (the height of the
boxes), and so the difference between the medians is very
small. Hence, there is definitely  substantial difference
between males and females.</p>
<p>Less insightfully, the difference in median between males and females is
very small (but that doesn’t rule out the possibility that the
spread is very small also).</p>
<p><span class="math inline">\(\blacksquare\)</span></p>
<ol start="5" style="list-style-type: lower-alpha">
<li>How do you know that both distributions, for males as well
as females, are skewed to the right? Explain (very) briefly.</li>
</ol>
<p>Solution</p>
<p>The upper whiskers, at the top of the box, are longer than the
lower ones (at the bottom).</p>
<p><span class="math inline">\(\blacksquare\)</span></p>
<ol start="6" style="list-style-type: lower-alpha">
<li>For data like this, why does it make practical sense that
the distributions are skewed to the right?</li>
</ol>
<p>Solution</p>
<p>Nobody can exercise less than 0 minutes per week, but there is no
upper limit: a student in the class can exercise as much as they
want. This means that there could be unusually high values, but
not unusually low values.</p>
<p>Extra: Distributions that have a limit on one side are often skewed to the other side.
This one has a limit on the left, so it is skewed to the <em>right</em>. This is most likely to be true if
there are observations close to the limit, such as the people in this data set that don’t exercise at all (and there are some of those).</p>
<p><span class="math inline">\(\blacksquare\)</span></p>

</div>
</div>
<div class="footnotes">
<hr />
<ol start="1">
<li id="fn1"><p>If you are concerned about the spelling: the guy who wrote ggplot is from New Zealand, where they spell <em>colour</em> the same way we do. However, if you want to use <em>color</em>, that works too.<a href="drawing-graphs.html#fnref1" class="footnote-back">↩</a></p></li>
<li id="fn2"><p>Meaning that the model should contain all three variables, <code>speed</code>, <code>scrap</code> and <code>line</code>.<a href="drawing-graphs.html#fnref2" class="footnote-back">↩</a></p></li>
<li id="fn3"><p>This is the same idea that it costs more to ride the GO bus from UTSC to York U than it does to ride from UTSC to Scarborough Town, but if you work out how much it costs per kilometre, the longer journey costs less per km. As of when I’m writing this, $5.30 for the 7.2 km to Scarborough Town and $6.75 for the 38 km to York. That’s quite an economy of scale, isn’t it?<a href="drawing-graphs.html#fnref3" class="footnote-back">↩</a></p></li>
<li id="fn4"><p>Reading from the URL is reproducible in that somebody else doing what you did will get exactly what results you did. Copying and pasting data is not in general reproducible because somebody else might do it differently from you, such as missing a line of data. Copying and pasting a URL, especially by right-clicking and Copy Link Address, has much less to go wrong. Physically selecting the URL text by selecting all the letters in the URL can go wrong, especially if the printed URL goes over two lines on the page.<a href="drawing-graphs.html#fnref4" class="footnote-back">↩</a></p></li>
<li id="fn5"><p>It is actually possible to disentangle data like this and then work with it (we will see how later in the course), but the best way to do it is to make it easiest for yourself and anyone reading your code, and read the data file in a way that is appropriate for the layout you have in the file.<a href="drawing-graphs.html#fnref5" class="footnote-back">↩</a></p></li>
<li id="fn6"><p>An indication, though: if you have more than one
space, and the things in the later columns are <em>left</em>-justified,
that could be tab-separated; if the things in the later columns are
<em>right</em>-justified, so that they finish in the same place but
don’t start in the same place, that is probably aligned columns.<a href="drawing-graphs.html#fnref6" class="footnote-back">↩</a></p></li>
</ol>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="reading-in-data.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="data-exploration.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/lunr.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": null,
"text": null
},
"history": {
"link": null,
"text": null
},
"view": {
"link": null,
"text": null
},
"download": ["pasias.pdf"],
"toc": {
"collapse": "subsection"
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
