<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>Chapter 41 Frequency table analysis | Problems and Solutions in Applied Statistics</title>
  <meta name="description" content="A set of problems and solutions, in R, on various parts of applied statistics" />
  <meta name="generator" content="bookdown 0.21 and GitBook 2.6.7" />

  <meta property="og:title" content="Chapter 41 Frequency table analysis | Problems and Solutions in Applied Statistics" />
  <meta property="og:type" content="book" />
  <meta property="og:url" content="http://ritsokiguess.site/pasias" />
  
  <meta property="og:description" content="A set of problems and solutions, in R, on various parts of applied statistics" />
  <meta name="github-repo" content="nxskok/pasias" />

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Chapter 41 Frequency table analysis | Problems and Solutions in Applied Statistics" />
  
  <meta name="twitter:description" content="A set of problems and solutions, in R, on various parts of applied statistics" />
  

<meta name="author" content="Ken Butler" />


<meta name="date" content="2021-06-04" />

  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="factor-analysis.html"/>

<script src="libs/jquery-2.2.3/jquery.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />











<style type="text/css">
a.sourceLine { display: inline-block; line-height: 1.25; }
a.sourceLine { pointer-events: none; color: inherit; text-decoration: inherit; }
a.sourceLine:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode { white-space: pre; position: relative; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
code.sourceCode { white-space: pre-wrap; }
a.sourceLine { text-indent: -1em; padding-left: 1em; }
}
pre.numberSource a.sourceLine
  { position: relative; left: -4em; }
pre.numberSource a.sourceLine::before
  { content: attr(title);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; pointer-events: all; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {  }
@media screen {
a.sourceLine::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">Problems and Solutions in Applied Statistics</a></li>

<li class="divider"></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i>Introduction</a><ul>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#packages-used-somewhere-in-this-book"><i class="fa fa-check"></i>Packages used somewhere in this book</a></li>
</ul></li>
<li class="chapter" data-level="1" data-path="getting-used-to-r-and-r-studio.html"><a href="getting-used-to-r-and-r-studio.html"><i class="fa fa-check"></i><b>1</b> Getting used to R and R Studio</a><ul>
<li class="chapter" data-level="1.1" data-path="getting-used-to-r-and-r-studio.html"><a href="getting-used-to-r-and-r-studio.html#running-r-studio-on-jupyterhub"><i class="fa fa-check"></i><b>1.1</b> Running R Studio on Jupyterhub</a></li>
<li class="chapter" data-level="1.2" data-path="getting-used-to-r-and-r-studio.html"><a href="getting-used-to-r-and-r-studio.html#getting-an-r-studio-cloud-account"><i class="fa fa-check"></i><b>1.2</b> Getting an R Studio Cloud account</a></li>
<li class="chapter" data-level="1.3" data-path="getting-used-to-r-and-r-studio.html"><a href="getting-used-to-r-and-r-studio.html#getting-started"><i class="fa fa-check"></i><b>1.3</b> Getting started</a></li>
<li class="chapter" data-level="1.4" data-path="getting-used-to-r-and-r-studio.html"><a href="getting-used-to-r-and-r-studio.html#reading-data-from-a-file"><i class="fa fa-check"></i><b>1.4</b> Reading data from a file</a></li>
<li class="chapter" data-level="1.5" data-path="getting-used-to-r-and-r-studio.html"><a href="getting-used-to-r-and-r-studio.html#reading-files-different-ways"><i class="fa fa-check"></i><b>1.5</b> Reading files different ways</a></li>
</ul></li>
<li class="chapter" data-level="2" data-path="reading-in-data.html"><a href="reading-in-data.html"><i class="fa fa-check"></i><b>2</b> Reading in data</a></li>
<li class="chapter" data-level="3" data-path="drawing-graphs.html"><a href="drawing-graphs.html"><i class="fa fa-check"></i><b>3</b> Drawing graphs</a></li>
<li class="chapter" data-level="4" data-path="data-exploration.html"><a href="data-exploration.html"><i class="fa fa-check"></i><b>4</b> Data exploration</a></li>
<li class="chapter" data-level="5" data-path="working-with-dataframes.html"><a href="working-with-dataframes.html"><i class="fa fa-check"></i><b>5</b> Working with dataframes</a></li>
<li class="chapter" data-level="6" data-path="one-sample-inference.html"><a href="one-sample-inference.html"><i class="fa fa-check"></i><b>6</b> One-sample inference</a></li>
<li class="chapter" data-level="7" data-path="two-sample-inference.html"><a href="two-sample-inference.html"><i class="fa fa-check"></i><b>7</b> Two-sample inference</a></li>
<li class="chapter" data-level="8" data-path="power-and-sample-size.html"><a href="power-and-sample-size.html"><i class="fa fa-check"></i><b>8</b> Power and sample size</a></li>
<li class="chapter" data-level="9" data-path="the-sign-test.html"><a href="the-sign-test.html"><i class="fa fa-check"></i><b>9</b> The sign test</a></li>
<li class="chapter" data-level="10" data-path="mood-median-test.html"><a href="mood-median-test.html"><i class="fa fa-check"></i><b>10</b> Mood median test</a></li>
<li class="chapter" data-level="11" data-path="matched-pairs-t-and-sign-test.html"><a href="matched-pairs-t-and-sign-test.html"><i class="fa fa-check"></i><b>11</b> Matched pairs t and sign test</a></li>
<li class="chapter" data-level="12" data-path="normal-quantile-plots.html"><a href="normal-quantile-plots.html"><i class="fa fa-check"></i><b>12</b> Normal quantile plots</a><ul>
<li class="chapter" data-level="12.1" data-path="normal-quantile-plots.html"><a href="normal-quantile-plots.html#lengths-of-heliconia-flowers"><i class="fa fa-check"></i><b>12.1</b> Lengths of heliconia flowers</a></li>
<li class="chapter" data-level="12.2" data-path="normal-quantile-plots.html"><a href="normal-quantile-plots.html#ferritin-and-normality"><i class="fa fa-check"></i><b>12.2</b> Ferritin and normality</a></li>
<li class="chapter" data-level="12.3" data-path="normal-quantile-plots.html"><a href="normal-quantile-plots.html#lengths-of-heliconia-flowers-1"><i class="fa fa-check"></i><b>12.3</b> Lengths of heliconia flowers</a></li>
<li class="chapter" data-level="12.4" data-path="normal-quantile-plots.html"><a href="normal-quantile-plots.html#ferritin-and-normality-1"><i class="fa fa-check"></i><b>12.4</b> Ferritin and normality</a></li>
</ul></li>
<li class="chapter" data-level="13" data-path="analysis-of-variance.html"><a href="analysis-of-variance.html"><i class="fa fa-check"></i><b>13</b> Analysis of variance</a></li>
<li class="chapter" data-level="14" data-path="writing-reports.html"><a href="writing-reports.html"><i class="fa fa-check"></i><b>14</b> Writing reports</a></li>
<li class="chapter" data-level="15" data-path="learning-to-code.html"><a href="learning-to-code.html"><i class="fa fa-check"></i><b>15</b> Learning to code</a><ul>
<li class="chapter" data-level="15.1" data-path="learning-to-code.html"><a href="learning-to-code.html#introduction-1"><i class="fa fa-check"></i><b>15.1</b> Introduction</a></li>
<li class="chapter" data-level="15.2" data-path="learning-to-code.html"><a href="learning-to-code.html#data-and-pre-processing"><i class="fa fa-check"></i><b>15.2</b> Data and pre-processing</a></li>
<li class="chapter" data-level="15.3" data-path="learning-to-code.html"><a href="learning-to-code.html#analysis"><i class="fa fa-check"></i><b>15.3</b> Analysis</a></li>
<li class="chapter" data-level="15.4" data-path="learning-to-code.html"><a href="learning-to-code.html#conclusions-see-note-9"><i class="fa fa-check"></i><b>15.4</b> Conclusions (see note 9)</a></li>
</ul></li>
<li class="chapter" data-level="16" data-path="treating-dandruff.html"><a href="treating-dandruff.html"><i class="fa fa-check"></i><b>16</b> Treating dandruff</a><ul>
<li class="chapter" data-level="16.1" data-path="treating-dandruff.html"><a href="treating-dandruff.html#introduction-2"><i class="fa fa-check"></i><b>16.1</b> Introduction</a></li>
<li class="chapter" data-level="16.2" data-path="treating-dandruff.html"><a href="treating-dandruff.html#exploratory-analysis"><i class="fa fa-check"></i><b>16.2</b> Exploratory analysis</a></li>
<li class="chapter" data-level="16.3" data-path="treating-dandruff.html"><a href="treating-dandruff.html#analysis-of-variance-1"><i class="fa fa-check"></i><b>16.3</b> Analysis of Variance</a></li>
<li class="chapter" data-level="16.4" data-path="treating-dandruff.html"><a href="treating-dandruff.html#assessment-of-assumptions"><i class="fa fa-check"></i><b>16.4</b> Assessment of Assumptions</a></li>
<li class="chapter" data-level="16.5" data-path="treating-dandruff.html"><a href="treating-dandruff.html#conclusions"><i class="fa fa-check"></i><b>16.5</b> Conclusions</a></li>
<li class="chapter" data-level="16.6" data-path="treating-dandruff.html"><a href="treating-dandruff.html#end"><i class="fa fa-check"></i><b>16.6</b> End</a></li>
</ul></li>
<li class="chapter" data-level="17" data-path="tidying-data.html"><a href="tidying-data.html"><i class="fa fa-check"></i><b>17</b> Tidying data</a></li>
<li class="chapter" data-level="18" data-path="simple-regression.html"><a href="simple-regression.html"><i class="fa fa-check"></i><b>18</b> Simple regression</a></li>
<li class="chapter" data-level="19" data-path="multiple-regression.html"><a href="multiple-regression.html"><i class="fa fa-check"></i><b>19</b> Multiple regression</a></li>
<li class="chapter" data-level="20" data-path="regression-with-categorical-variables.html"><a href="regression-with-categorical-variables.html"><i class="fa fa-check"></i><b>20</b> Regression with categorical variables</a><ul>
<li class="chapter" data-level="20.1" data-path="regression-with-categorical-variables.html"><a href="regression-with-categorical-variables.html#crickets-revisited"><i class="fa fa-check"></i><b>20.1</b> Crickets revisited</a></li>
<li class="chapter" data-level="20.2" data-path="regression-with-categorical-variables.html"><a href="regression-with-categorical-variables.html#pulse-rates-and-marching"><i class="fa fa-check"></i><b>20.2</b> Pulse rates and marching</a></li>
<li class="chapter" data-level="20.3" data-path="regression-with-categorical-variables.html"><a href="regression-with-categorical-variables.html#crickets-revisited-1"><i class="fa fa-check"></i><b>20.3</b> Crickets revisited</a></li>
<li class="chapter" data-level="20.4" data-path="regression-with-categorical-variables.html"><a href="regression-with-categorical-variables.html#pulse-rates-and-marching-1"><i class="fa fa-check"></i><b>20.4</b> Pulse rates and marching</a></li>
</ul></li>
<li class="chapter" data-level="21" data-path="dates-and-times.html"><a href="dates-and-times.html"><i class="fa fa-check"></i><b>21</b> Dates and times</a></li>
<li class="chapter" data-level="22" data-path="functions.html"><a href="functions.html"><i class="fa fa-check"></i><b>22</b> Functions</a></li>
<li class="chapter" data-level="23" data-path="vector-and-matrix-algebra.html"><a href="vector-and-matrix-algebra.html"><i class="fa fa-check"></i><b>23</b> Vector and matrix algebra</a><ul>
<li class="chapter" data-level="23.1" data-path="vector-and-matrix-algebra.html"><a href="vector-and-matrix-algebra.html#heights-and-foot-lengths-again"><i class="fa fa-check"></i><b>23.1</b> Heights and foot lengths again</a></li>
<li class="chapter" data-level="23.2" data-path="vector-and-matrix-algebra.html"><a href="vector-and-matrix-algebra.html#heights-and-foot-lengths-again-1"><i class="fa fa-check"></i><b>23.2</b> Heights and foot lengths again</a></li>
</ul></li>
<li class="chapter" data-level="24" data-path="the-bootstrap.html"><a href="the-bootstrap.html"><i class="fa fa-check"></i><b>24</b> The Bootstrap</a></li>
<li class="chapter" data-level="25" data-path="bayesian-statistics-with-stan.html"><a href="bayesian-statistics-with-stan.html"><i class="fa fa-check"></i><b>25</b> Bayesian Statistics with Stan</a></li>
<li class="chapter" data-level="26" data-path="logistic-regression.html"><a href="logistic-regression.html"><i class="fa fa-check"></i><b>26</b> Logistic regression</a></li>
<li class="chapter" data-level="27" data-path="logistic-regression-with-ordinal-response.html"><a href="logistic-regression-with-ordinal-response.html"><i class="fa fa-check"></i><b>27</b> Logistic regression with ordinal response</a></li>
<li class="chapter" data-level="28" data-path="logistic-regression-with-nominal-response.html"><a href="logistic-regression-with-nominal-response.html"><i class="fa fa-check"></i><b>28</b> Logistic regression with nominal response</a></li>
<li class="chapter" data-level="29" data-path="survival-analysis.html"><a href="survival-analysis.html"><i class="fa fa-check"></i><b>29</b> Survival analysis</a></li>
<li class="chapter" data-level="30" data-path="analysis-of-variance-revisited.html"><a href="analysis-of-variance-revisited.html"><i class="fa fa-check"></i><b>30</b> Analysis of variance revisited</a></li>
<li class="chapter" data-level="31" data-path="analysis-of-covariance.html"><a href="analysis-of-covariance.html"><i class="fa fa-check"></i><b>31</b> Analysis of covariance</a></li>
<li class="chapter" data-level="32" data-path="multivariate-analysis-of-variance.html"><a href="multivariate-analysis-of-variance.html"><i class="fa fa-check"></i><b>32</b> Multivariate analysis of variance</a></li>
<li class="chapter" data-level="33" data-path="repeated-measures.html"><a href="repeated-measures.html"><i class="fa fa-check"></i><b>33</b> Repeated measures</a></li>
<li class="chapter" data-level="34" data-path="discriminant-analysis.html"><a href="discriminant-analysis.html"><i class="fa fa-check"></i><b>34</b> Discriminant analysis</a></li>
<li class="chapter" data-level="35" data-path="hierarchical-cluster-analysis.html"><a href="hierarchical-cluster-analysis.html"><i class="fa fa-check"></i><b>35</b> Hierarchical cluster analysis</a></li>
<li class="chapter" data-level="36" data-path="k-means-cluster-analysis.html"><a href="k-means-cluster-analysis.html"><i class="fa fa-check"></i><b>36</b> K-means cluster analysis</a></li>
<li class="chapter" data-level="37" data-path="drawing-maps-with-leaflet.html"><a href="drawing-maps-with-leaflet.html"><i class="fa fa-check"></i><b>37</b> Drawing maps with Leaflet</a></li>
<li class="chapter" data-level="38" data-path="multidimensional-scaling.html"><a href="multidimensional-scaling.html"><i class="fa fa-check"></i><b>38</b> Multidimensional Scaling</a></li>
<li class="chapter" data-level="39" data-path="principal-components.html"><a href="principal-components.html"><i class="fa fa-check"></i><b>39</b> Principal Components</a><ul>
<li class="chapter" data-level="39.1" data-path="principal-components.html"><a href="principal-components.html#the-weather-somewhere"><i class="fa fa-check"></i><b>39.1</b> The weather, somewhere</a></li>
<li class="chapter" data-level="39.2" data-path="principal-components.html"><a href="principal-components.html#the-weather-somewhere-1"><i class="fa fa-check"></i><b>39.2</b> The weather, somewhere</a></li>
</ul></li>
<li class="chapter" data-level="40" data-path="factor-analysis.html"><a href="factor-analysis.html"><i class="fa fa-check"></i><b>40</b> Factor Analysis</a></li>
<li class="chapter" data-level="41" data-path="frequency-table-analysis.html"><a href="frequency-table-analysis.html"><i class="fa fa-check"></i><b>41</b> Frequency table analysis</a><ul>
<li class="chapter" data-level="41.1" data-path="frequency-table-analysis.html"><a href="frequency-table-analysis.html#college-plans"><i class="fa fa-check"></i><b>41.1</b> College plans</a></li>
<li class="chapter" data-level="41.2" data-path="frequency-table-analysis.html"><a href="frequency-table-analysis.html#predicting-voting"><i class="fa fa-check"></i><b>41.2</b> Predicting voting</a></li>
<li class="chapter" data-level="41.3" data-path="frequency-table-analysis.html"><a href="frequency-table-analysis.html#brand-m-laundry-detergent"><i class="fa fa-check"></i><b>41.3</b> Brand M laundry detergent</a></li>
<li class="chapter" data-level="41.4" data-path="frequency-table-analysis.html"><a href="frequency-table-analysis.html#college-plans-1"><i class="fa fa-check"></i><b>41.4</b> College plans</a></li>
<li class="chapter" data-level="41.5" data-path="frequency-table-analysis.html"><a href="frequency-table-analysis.html#predicting-voting-1"><i class="fa fa-check"></i><b>41.5</b> Predicting voting</a></li>
<li class="chapter" data-level="41.6" data-path="frequency-table-analysis.html"><a href="frequency-table-analysis.html#brand-m-laundry-detergent-1"><i class="fa fa-check"></i><b>41.6</b> Brand M laundry detergent</a></li>
</ul></li>
<li class="divider"></li>
<li><a href="https://github.com/rstudio/bookdown" target="blank">Published with bookdown</a></li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Problems and Solutions in Applied Statistics</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="frequency-table-analysis" class="section level1">
<h1><span class="header-section-number">Chapter 41</span> Frequency table analysis</h1>
<p>Packages for this chapter:</p>
<div class="sourceCode" id="cb287"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb287-1" title="1"><span class="kw">library</span>(tidyverse)</a></code></pre></div>
<div id="college-plans" class="section level2">
<h2><span class="header-section-number">41.1</span> College plans</h2>
<p>5199 male high school seniors in Wisconsin<a href="#fn38" class="footnote-ref" id="fnref38"><sup>38</sup></a> were classified by
socio-economic status (low, lower-middle, upper-middle, high), by
the degree that their parents encouraged them in their education (low
or high),
and whether or not they had plans to go to college (yes or no). How,
if at all, are these categorical variables related? The data can be
found at
<a href="http://ritsokiguess.site/datafiles/college-plans.txt">link</a>.</p>
<ol style="list-style-type: lower-alpha">
<li><p>Read in the data and check that you have a column for each
variable and a column of frequencies.</p></li>
<li><p>Fit a log-linear model containing all possible
interactions. You don’t need to examine it yet.</p></li>
<li><p>Find out which terms (interactions) could be removed. Do you
think removing any of them is a good idea?</p></li>
<li><p>Remove anything you can, and fit again. Hint: <code>update</code>.</p></li>
<li><p>Continue to examine what can be removed, and if reasonable,
remove it, until you need to stop. Which terms are left in your final model?</p></li>
<li><p>Make two-way tables of any remaining two-way interactions, and
describe any relationships that you see.</p></li>
</ol>
</div>
<div id="predicting-voting" class="section level2">
<h2><span class="header-section-number">41.2</span> Predicting voting</h2>
<p>1257 British voters were classified according
to their social class, age (categorized), sex and the political party
they voted for (Labour or Conservative). Which, if any, of these
factors influences the party that someone votes for? The data are in
<a href="http://ritsokiguess.site/datafiles/voting.txt">link</a>, one voter
per line.</p>
<ol style="list-style-type: lower-alpha">
<li><p>Read in the data and display (some of) the data frame.</p></li>
<li><p>There is no frequency column here, because each row of the
data frame only represents one voter. Count up the frequencies for
each combo of the categorical variables, and save it (this is the
data frame that we will use for the analysis).
Display the first few rows of the result. Do you now
have something that you need?</p></li>
<li><p>Fit a log-linear model with the appropriate interaction (as a
starting point).</p></li>
<li><p>Refine your model by taking out suitable non-significant
terms, in multiple steps. What model do you finish with?</p></li>
<li><p>If we think of the party someone votes for as the final
outcome (that depends on all the other things), what does our final
model say that someone’s vote depends on?</p></li>
<li><p>Obtain sub-tables that explain how <code>vote</code> depends on
any of the things it’s related to.</p></li>
</ol>
</div>
<div id="brand-m-laundry-detergent" class="section level2">
<h2><span class="header-section-number">41.3</span> Brand M laundry detergent</h2>
<p>A survey was carried out comparing respondents’ preferences of a laundry detergent M compared to a mystery brand X. For each respondent, the researchers recorded the temperature of the laundry load (low or high), whether or not they previously used brand M (yes or no), and the softness of the water used for the laundry load(hard, medium or soft). The aim of the survey was to find out what was associated with the respondents preferring brand M. The data are in <a href="http://ritsokiguess.site/datafiles/brand_m.csv" class="uri">http://ritsokiguess.site/datafiles/brand_m.csv</a>.</p>
<ol style="list-style-type: lower-alpha">
<li><p>Read in and display (some of) the data. Explain briefly how the data is laid out appropriately to fit a log-linear model.</p></li>
<li><p>Using backward elimination, build a suitable log-linear model for the associations between the variables. (Do <em>not</em> use <code>step</code>; do the elimination yourself).</p></li>
<li><p>What is associated with the brand a respondent prefers? By obtaining suitable frequency tables, describe the nature of these associations.</p></li>
</ol>
<p>My solutions follow:</p>
</div>
<div id="college-plans-1" class="section level2">
<h2><span class="header-section-number">41.4</span> College plans</h2>
<p>5199 male high school seniors in Wisconsin<a href="#fn39" class="footnote-ref" id="fnref39"><sup>39</sup></a> were classified by
socio-economic status (low, lower-middle, upper-middle, high), by
the degree that their parents encouraged them in their education (low
or high),
and whether or not they had plans to go to college (yes or no). How,
if at all, are these categorical variables related? The data can be
found at
<a href="http://ritsokiguess.site/datafiles/college-plans.txt">link</a>.</p>
<ol style="list-style-type: lower-alpha">
<li>Read in the data and check that you have a column for each
variable and a column of frequencies.</li>
</ol>
<p>Solution</p>
<p>Delimited by one space:</p>
<div class="sourceCode" id="cb288"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb288-1" title="1">my_url &lt;-<span class="st"> &quot;http://ritsokiguess.site/datafiles/college-plans.txt&quot;</span></a>
<a class="sourceLine" id="cb288-2" title="2">wisc &lt;-<span class="st"> </span><span class="kw">read_delim</span>(my_url, <span class="st">&quot; &quot;</span>)</a></code></pre></div>
<pre><code>## 
## ── Column specification ────────────────────────────────────────────────────────
## cols(
##   social.stratum = col_character(),
##   encouragement = col_character(),
##   college.plans = col_character(),
##   frequency = col_double()
## )</code></pre>
<div class="sourceCode" id="cb290"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb290-1" title="1">wisc</a></code></pre></div>
<pre><code>## # A tibble: 16 x 4
##    social.stratum encouragement college.plans frequency
##    &lt;chr&gt;          &lt;chr&gt;         &lt;chr&gt;             &lt;dbl&gt;
##  1 lower          low           no                  749
##  2 lower          low           yes                  35
##  3 lower          high          no                  233
##  4 lower          high          yes                 133
##  5 lowermiddle    low           no                  627
##  6 lowermiddle    low           yes                  38
##  7 lowermiddle    high          no                  330
##  8 lowermiddle    low           no                  303
##  9 uppermiddle    low           no                  627
## 10 uppermiddle    low           yes                  38
## 11 uppermiddle    high          no                  374
## 12 uppermiddle    high          yes                 467
## 13 higher         low           no                  153
## 14 higher         low           yes                  26
## 15 higher         high          no                  266
## 16 higher         high          yes                 800</code></pre>
<p>As promised. We only have 16 observations, because we have all
possible combinations of categorical variable combinations, 4 social
strata, times 2 levels of encouragement, times 2 levels of college
plans.</p>
<p>Each line of the data file summarizes a number of students, not just
one. For example, the first line says that 749 students were in the
lower social stratum, received low encouragement and have no college
plans. If we sum up the frequencies, we should get 5199 because there
were that many students altogether:</p>
<div class="sourceCode" id="cb292"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb292-1" title="1">wisc <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">summarize</span>(<span class="dt">tot =</span> <span class="kw">sum</span>(frequency))</a></code></pre></div>
<pre><code>## # A tibble: 1 x 1
##     tot
##   &lt;dbl&gt;
## 1  5199</code></pre>
<p><span class="math inline">\(\blacksquare\)</span></p>
<ol start="2" style="list-style-type: lower-alpha">
<li>Fit a log-linear model containing all possible
interactions. You don’t need to examine it yet.</li>
</ol>
<p>Solution</p>
<div class="sourceCode" id="cb294"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb294-1" title="1">wisc<span class="fl">.1</span> &lt;-<span class="st"> </span><span class="kw">glm</span>(frequency <span class="op">~</span><span class="st"> </span>social.stratum <span class="op">*</span><span class="st"> </span>encouragement <span class="op">*</span><span class="st"> </span>college.plans,</a>
<a class="sourceLine" id="cb294-2" title="2">  <span class="dt">data =</span> wisc, <span class="dt">family =</span> <span class="st">&quot;poisson&quot;</span></a>
<a class="sourceLine" id="cb294-3" title="3">)</a></code></pre></div>
<p><span class="math inline">\(\blacksquare\)</span></p>
<ol start="3" style="list-style-type: lower-alpha">
<li>Find out which terms (interactions) could be removed. Do you
think removing any of them is a good idea?</li>
</ol>
<p>Solution</p>
<p>This is <code>drop1</code>. If you forget the <code>test=</code>, you won’t
get any P-values:</p>
<div class="sourceCode" id="cb295"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb295-1" title="1"><span class="kw">drop1</span>(wisc<span class="fl">.1</span>, <span class="dt">test =</span> <span class="st">&quot;Chisq&quot;</span>)</a></code></pre></div>
<pre><code>## Single term deletions
## 
## Model:
## frequency ~ social.stratum * encouragement * college.plans
##                                            Df Deviance    AIC   LRT Pr(&gt;Chi)
## &lt;none&gt;                                          115.28 259.52               
## social.stratum:encouragement:college.plans  2   118.98 259.22 3.697   0.1575</code></pre>
<p>This P-value is not small, so the three-way interaction can be removed.</p>
<p><span class="math inline">\(\blacksquare\)</span></p>
<ol start="4" style="list-style-type: lower-alpha">
<li>Remove anything you can, and fit again. Hint: <code>update</code>.</li>
</ol>
<p>Solution</p>
<p>In this kind of modelling, it’s easier to describe what changes
should be made to get from one model to another, rather than
writing out the whole thing from scratch again.
Anyway, the three-way interaction can come out:</p>
<div class="sourceCode" id="cb297"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb297-1" title="1">wisc<span class="fl">.2</span> &lt;-<span class="st"> </span><span class="kw">update</span>(wisc<span class="fl">.1</span>, . <span class="op">~</span><span class="st"> </span>. <span class="op">-</span><span class="st"> </span>social.stratum<span class="op">:</span>encouragement<span class="op">:</span>college.plans)</a></code></pre></div>
<p><span class="math inline">\(\blacksquare\)</span></p>
<ol start="5" style="list-style-type: lower-alpha">
<li>Continue to examine what can be removed, and if reasonable,
remove it, until you need to stop. Which terms are left in your final model?</li>
</ol>
<p>Solution</p>
<p>Start with <code>drop1</code>:</p>
<div class="sourceCode" id="cb298"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb298-1" title="1"><span class="kw">drop1</span>(wisc<span class="fl">.2</span>, <span class="dt">test =</span> <span class="st">&quot;Chisq&quot;</span>)</a></code></pre></div>
<pre><code>## Single term deletions
## 
## Model:
## frequency ~ social.stratum + encouragement + college.plans + 
##     social.stratum:encouragement + social.stratum:college.plans + 
##     encouragement:college.plans
##                              Df Deviance     AIC    LRT  Pr(&gt;Chi)    
## &lt;none&gt;                            118.98  259.22                     
## social.stratum:encouragement  3   379.18  513.42 260.20 &lt; 2.2e-16 ***
## social.stratum:college.plans  3   331.86  466.10 212.88 &lt; 2.2e-16 ***
## encouragement:college.plans   1  1024.69 1162.94 905.72 &lt; 2.2e-16 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<p>These are all strongly significant, so they have to stay. There is
nothing else we can remove. All the two-way interactions have to stay
in the model.</p>
<p><span class="math inline">\(\blacksquare\)</span></p>
<ol start="6" style="list-style-type: lower-alpha">
<li>Make two-way tables of any remaining two-way interactions, and
describe any relationships that you see.</li>
</ol>
<p>Solution</p>
<p>We have three two-way tables to make.</p>
<p>My first one is social stratum by parental encouragement. Neither of
these is really a response, but I thought that social stratum would
influence parental encouragement rather than the other way around, hence:</p>
<div class="sourceCode" id="cb300"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb300-1" title="1"><span class="kw">xtabs</span>(frequency <span class="op">~</span><span class="st"> </span>social.stratum <span class="op">+</span><span class="st"> </span>encouragement, <span class="dt">data =</span> wisc) <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb300-2" title="2"><span class="st">  </span><span class="kw">prop.table</span>(<span class="dt">margin =</span> <span class="dv">1</span>)</a></code></pre></div>
<pre><code>##               encouragement
## social.stratum      high       low
##    higher      0.8562249 0.1437751
##    lower       0.3182609 0.6817391
##    lowermiddle 0.2542373 0.7457627
##    uppermiddle 0.5584329 0.4415671</code></pre>
<p>This says that there tends to be more parental encouragement, the
higher the social stratum.
Next, this:</p>
<div class="sourceCode" id="cb302"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb302-1" title="1"><span class="kw">xtabs</span>(frequency <span class="op">~</span><span class="st"> </span>social.stratum <span class="op">+</span><span class="st"> </span>college.plans, <span class="dt">data =</span> wisc) <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb302-2" title="2"><span class="st">  </span><span class="kw">prop.table</span>(<span class="dt">margin =</span> <span class="dv">1</span>)</a></code></pre></div>
<pre><code>##               college.plans
## social.stratum         no        yes
##    higher      0.33654618 0.66345382
##    lower       0.85391304 0.14608696
##    lowermiddle 0.97072419 0.02927581
##    uppermiddle 0.66467463 0.33532537</code></pre>
<p>In this one (and the next), <code>college.plans</code> is the response, in
columns, so we want to have the <em>rows</em> adding up to 1.</p>
<p>The higher the social stratum, the more likely is a male
high school senior to have plans to go to college. (The social stratum
is not in order, so you’ll have to jump from the second row to the
third to the fourth to the first to assess this. Lower and lower
middle are not in order, but the others are.)</p>
<p>Finally, this:</p>
<div class="sourceCode" id="cb304"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb304-1" title="1"><span class="kw">xtabs</span>(frequency <span class="op">~</span><span class="st"> </span>encouragement <span class="op">+</span><span class="st"> </span>college.plans, <span class="dt">data =</span> wisc) <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb304-2" title="2"><span class="st">  </span><span class="kw">prop.table</span>(<span class="dt">margin =</span> <span class="dv">1</span>)</a></code></pre></div>
<pre><code>##              college.plans
## encouragement        no       yes
##          high 0.4621590 0.5378410
##          low  0.9472265 0.0527735</code></pre>
<p>And here you see an <em>enormous</em> effect of parental encouragement
on college plans: if it is low, the high-school senior is very
unlikely to be considering college.</p>
<p>Nothing, in all honesty, that is very surprising here. But the two-way
interactions are easier to interpret than a three-way one would have
been.</p>
<p>Here, we think of college plans as being a response, and this
analysis has shown that whether or not a student has plans to go to
college depends separately on the socio-economic status and the level
of parental encouragement (rather than on the combination of both, as
would have been the case had the three-way interaction been
significant).</p>
<p><span class="math inline">\(\blacksquare\)</span></p>
</div>
<div id="predicting-voting-1" class="section level2">
<h2><span class="header-section-number">41.5</span> Predicting voting</h2>
<p>1257 British voters were classified according
to their social class, age (categorized), sex and the political party
they voted for (Labour or Conservative). Which, if any, of these
factors influences the party that someone votes for? The data are in
<a href="http://ritsokiguess.site/datafiles/voting.txt">link</a>, one voter
per line.</p>
<ol style="list-style-type: lower-alpha">
<li>Read in the data and display (some of) the data frame.</li>
</ol>
<p>Solution</p>
<p>Space-delimited:</p>
<div class="sourceCode" id="cb306"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb306-1" title="1">my_url &lt;-<span class="st"> &quot;http://ritsokiguess.site/datafiles/voting.txt&quot;</span></a>
<a class="sourceLine" id="cb306-2" title="2">vote0 &lt;-<span class="st"> </span><span class="kw">read_delim</span>(my_url, <span class="st">&quot; &quot;</span>)</a></code></pre></div>
<pre><code>## 
## ── Column specification ────────────────────────────────────────────────────────
## cols(
##   id = col_double(),
##   class = col_character(),
##   age = col_character(),
##   sex = col_character(),
##   vote = col_character()
## )</code></pre>
<div class="sourceCode" id="cb308"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb308-1" title="1">vote0</a></code></pre></div>
<pre><code>## # A tibble: 1,257 x 5
##       id class        age   sex    vote        
##    &lt;dbl&gt; &lt;chr&gt;        &lt;chr&gt; &lt;chr&gt;  &lt;chr&gt;       
##  1     1 upper middle &gt;75   male   conservative
##  2     2 upper middle &gt;75   male   conservative
##  3     3 upper middle &gt;75   male   conservative
##  4     4 upper middle &gt;75   male   conservative
##  5     5 upper middle &gt;75   female conservative
##  6     6 upper middle &gt;75   female conservative
##  7     7 upper middle &gt;75   female conservative
##  8     8 upper middle &gt;75   female conservative
##  9     9 upper middle &gt;75   female conservative
## 10    10 upper middle &gt;75   female conservative
## # … with 1,247 more rows</code></pre>
<p>I gave it a “disposable” name, since we make the “real” data set
shortly.</p>
<p><span class="math inline">\(\blacksquare\)</span></p>
<ol start="2" style="list-style-type: lower-alpha">
<li>There is no frequency column here, because each row of the
data frame only represents one voter. Count up the frequencies for
each combo of the categorical variables, and save it (this is the
data frame that we will use for the analysis).
Display the first few rows of the result. Do you now
have something that you need?</li>
</ol>
<p>Solution</p>
<p>I changed my mind about how to do this from last year. Using
<code>count</code> is alarmingly more direct than the method I had before:</p>
<div class="sourceCode" id="cb310"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb310-1" title="1">votes &lt;-<span class="st"> </span>vote0 <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">count</span>(class, age, sex, vote)</a>
<a class="sourceLine" id="cb310-2" title="2">votes</a></code></pre></div>
<pre><code>## # A tibble: 58 x 5
##    class        age   sex    vote             n
##    &lt;chr&gt;        &lt;chr&gt; &lt;chr&gt;  &lt;chr&gt;        &lt;int&gt;
##  1 lower middle &lt;26   female conservative    13
##  2 lower middle &lt;26   female labour           7
##  3 lower middle &lt;26   male   conservative     9
##  4 lower middle &lt;26   male   labour           9
##  5 lower middle &gt;75   female conservative     9
##  6 lower middle &gt;75   female labour           2
##  7 lower middle &gt;75   male   conservative     8
##  8 lower middle &gt;75   male   labour           4
##  9 lower middle 26-40 female conservative    17
## 10 lower middle 26-40 female labour          13
## # … with 48 more rows</code></pre>
<p>Exactly the right thing now: note the new column <code>n</code> with
frequencies in it. (Without a column of frequencies we can’t fit a
log-linear model.) There are now only 58 combinations of the four
categorical variables, as opposed to 1247 rows in the original data
set (with, inevitably, a lot of repeats).</p>
<p><span class="math inline">\(\blacksquare\)</span></p>
<ol start="3" style="list-style-type: lower-alpha">
<li>Fit a log-linear model with the appropriate interaction (as a
starting point).</li>
</ol>
<p>Solution</p>
<div class="sourceCode" id="cb312"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb312-1" title="1">vote<span class="fl">.1</span> &lt;-<span class="st"> </span><span class="kw">glm</span>(n <span class="op">~</span><span class="st"> </span>class <span class="op">*</span><span class="st"> </span>age <span class="op">*</span><span class="st"> </span>sex <span class="op">*</span><span class="st"> </span>vote, <span class="dt">data =</span> votes, <span class="dt">family =</span> <span class="st">&quot;poisson&quot;</span>)</a></code></pre></div>
<p><span class="math inline">\(\blacksquare\)</span></p>
<ol start="4" style="list-style-type: lower-alpha">
<li>Refine your model by taking out suitable non-significant
terms, in multiple steps. What model do you finish with?</li>
</ol>
<p>Solution</p>
<p>Alternating <code>drop1</code> and <code>update</code> until everything
remaining is significant:</p>
<div class="sourceCode" id="cb313"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb313-1" title="1"><span class="kw">drop1</span>(vote<span class="fl">.1</span>, <span class="dt">test =</span> <span class="st">&quot;Chisq&quot;</span>)</a></code></pre></div>
<pre><code>## Single term deletions
## 
## Model:
## n ~ class * age * sex * vote
##                    Df Deviance    AIC   LRT Pr(&gt;Chi)
## &lt;none&gt;                   0.000 381.49               
## class:age:sex:vote  7    8.086 375.58 8.086   0.3251</code></pre>
<p>Not anywhere near significant, so out it comes:</p>
<div class="sourceCode" id="cb315"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb315-1" title="1">vote<span class="fl">.2</span> &lt;-<span class="st"> </span><span class="kw">update</span>(vote<span class="fl">.1</span>, . <span class="op">~</span><span class="st"> </span>. <span class="op">-</span><span class="st"> </span>class<span class="op">:</span>age<span class="op">:</span>sex<span class="op">:</span>vote)</a>
<a class="sourceLine" id="cb315-2" title="2"><span class="kw">drop1</span>(vote<span class="fl">.2</span>, <span class="dt">test =</span> <span class="st">&quot;Chisq&quot;</span>)</a></code></pre></div>
<pre><code>## Single term deletions
## 
## Model:
## n ~ class + age + sex + vote + class:age + class:sex + age:sex + 
##     class:vote + age:vote + sex:vote + class:age:sex + class:age:vote + 
##     class:sex:vote + age:sex:vote
##                Df Deviance    AIC     LRT Pr(&gt;Chi)  
## &lt;none&gt;               8.086 375.58                   
## class:age:sex   8   11.244 362.74  3.1583  0.92404  
## class:age:vote  7   21.962 375.46 13.8759  0.05343 .
## class:sex:vote  2   10.142 373.64  2.0564  0.35765  
## age:sex:vote    4   14.239 373.73  6.1528  0.18802  
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<p>Take out the first one, since it has the highest P-value:</p>
<div class="sourceCode" id="cb317"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb317-1" title="1">vote<span class="fl">.3</span> &lt;-<span class="st"> </span><span class="kw">update</span>(vote<span class="fl">.2</span>, . <span class="op">~</span><span class="st"> </span>. <span class="op">-</span><span class="st"> </span>class<span class="op">:</span>age<span class="op">:</span>sex)</a>
<a class="sourceLine" id="cb317-2" title="2"><span class="kw">drop1</span>(vote<span class="fl">.3</span>, <span class="dt">test =</span> <span class="st">&quot;Chisq&quot;</span>)</a></code></pre></div>
<pre><code>## Single term deletions
## 
## Model:
## n ~ class + age + sex + vote + class:age + class:sex + age:sex + 
##     class:vote + age:vote + sex:vote + class:age:vote + class:sex:vote + 
##     age:sex:vote
##                Df Deviance    AIC     LRT Pr(&gt;Chi)  
## &lt;none&gt;              11.244 362.74                   
## class:age:vote  7   25.171 362.66 13.9262  0.05251 .
## class:sex:vote  2   12.794 360.29  1.5498  0.46074  
## age:sex:vote    4   19.248 362.74  8.0041  0.09143 .
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<p><code>class:sex:vote</code>:</p>
<div class="sourceCode" id="cb319"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb319-1" title="1">vote<span class="fl">.4</span> &lt;-<span class="st"> </span><span class="kw">update</span>(vote<span class="fl">.3</span>, . <span class="op">~</span><span class="st"> </span>. <span class="op">-</span><span class="st"> </span>class<span class="op">:</span>sex<span class="op">:</span>vote)</a>
<a class="sourceLine" id="cb319-2" title="2"><span class="kw">drop1</span>(vote<span class="fl">.4</span>, <span class="dt">test =</span> <span class="st">&quot;Chisq&quot;</span>)</a></code></pre></div>
<pre><code>## Single term deletions
## 
## Model:
## n ~ class + age + sex + vote + class:age + class:sex + age:sex + 
##     class:vote + age:vote + sex:vote + class:age:vote + age:sex:vote
##                Df Deviance    AIC     LRT Pr(&gt;Chi)  
## &lt;none&gt;              12.794 360.29                   
## class:sex       2   13.477 356.97  0.6830  0.71070  
## class:age:vote  7   26.698 360.19 13.9036  0.05292 .
## age:sex:vote    4   21.211 360.71  8.4172  0.07744 .
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<p><code>class:sex</code>:</p>
<div class="sourceCode" id="cb321"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb321-1" title="1">vote<span class="fl">.5</span> &lt;-<span class="st"> </span><span class="kw">update</span>(vote<span class="fl">.4</span>, . <span class="op">~</span><span class="st"> </span>. <span class="op">-</span><span class="st"> </span>class<span class="op">:</span>sex)</a>
<a class="sourceLine" id="cb321-2" title="2"><span class="kw">drop1</span>(vote<span class="fl">.5</span>, <span class="dt">test =</span> <span class="st">&quot;Chisq&quot;</span>)</a></code></pre></div>
<pre><code>## Single term deletions
## 
## Model:
## n ~ class + age + sex + vote + class:age + age:sex + class:vote + 
##     age:vote + sex:vote + class:age:vote + age:sex:vote
##                Df Deviance    AIC     LRT Pr(&gt;Chi)  
## &lt;none&gt;              13.477 356.97                   
## class:age:vote  7   27.633 357.13 14.1555  0.04848 *
## age:sex:vote    4   22.081 357.57  8.6037  0.07181 .
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<p>I don’t like having three-way interactions, so I’m going to yank
<code>age:sex:vote</code> now, even though its P-value is smallish:</p>
<div class="sourceCode" id="cb323"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb323-1" title="1">vote<span class="fl">.6</span> &lt;-<span class="st"> </span><span class="kw">update</span>(vote<span class="fl">.5</span>, . <span class="op">~</span><span class="st"> </span>. <span class="op">-</span><span class="st"> </span>age<span class="op">:</span>sex<span class="op">:</span>vote)</a>
<a class="sourceLine" id="cb323-2" title="2"><span class="kw">drop1</span>(vote<span class="fl">.6</span>, <span class="dt">test =</span> <span class="st">&quot;Chisq&quot;</span>)</a></code></pre></div>
<pre><code>## Single term deletions
## 
## Model:
## n ~ class + age + sex + vote + class:age + age:sex + class:vote + 
##     age:vote + sex:vote + class:age:vote
##                Df Deviance    AIC     LRT  Pr(&gt;Chi)    
## &lt;none&gt;              22.081 357.57                      
## age:sex         4   22.918 350.41  0.8372 0.9333914    
## sex:vote        1   33.018 366.51 10.9376 0.0009423 ***
## class:age:vote  7   36.236 357.73 14.1555 0.0484843 *  
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<p>The age-sex interaction can go, but we must be near the end now:</p>
<div class="sourceCode" id="cb325"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb325-1" title="1">vote<span class="fl">.7</span> &lt;-<span class="st"> </span><span class="kw">update</span>(vote<span class="fl">.6</span>, . <span class="op">~</span><span class="st"> </span>. <span class="op">-</span><span class="st"> </span>age<span class="op">:</span>sex)</a>
<a class="sourceLine" id="cb325-2" title="2"><span class="kw">drop1</span>(vote<span class="fl">.7</span>, <span class="dt">test =</span> <span class="st">&quot;Chisq&quot;</span>)</a></code></pre></div>
<pre><code>## Single term deletions
## 
## Model:
## n ~ class + age + sex + vote + class:age + class:vote + age:vote + 
##     sex:vote + class:age:vote
##                Df Deviance    AIC    LRT  Pr(&gt;Chi)    
## &lt;none&gt;              22.918 350.41                     
## sex:vote        1   33.808 359.30 10.890 0.0009667 ***
## class:age:vote  7   37.073 350.57 14.155 0.0484843 *  
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<p>And that’s it. The age and sex main effects are not included in the
list of droppable things because
both variables are part of higher-order interactions that are still in
the model.</p>
<p>If you want to, you can look at the <code>summary</code> of your final model:</p>
<div class="sourceCode" id="cb327"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb327-1" title="1"><span class="kw">summary</span>(vote<span class="fl">.7</span>)</a></code></pre></div>
<pre><code>## 
## Call:
## glm(formula = n ~ class + age + sex + vote + class:age + class:vote + 
##     age:vote + sex:vote + class:age:vote, family = &quot;poisson&quot;, 
##     data = votes)
## 
## Deviance Residuals: 
##      Min        1Q    Median        3Q       Max  
## -1.82417  -0.39708  -0.00015   0.41445   1.41435  
## 
## Coefficients: (1 not defined because of singularities)
##                                       Estimate Std. Error z value Pr(&gt;|z|)    
## (Intercept)                            2.50737    0.21613  11.601  &lt; 2e-16 ***
## classupper middle                     -0.45199    0.34188  -1.322 0.186151    
## classworking                           0.37469    0.27696   1.353 0.176088    
## age&gt;75                                -0.25783    0.32292  -0.798 0.424622    
## age26-40                               0.34294    0.27877   1.230 0.218619    
## age41-50                               0.93431    0.25162   3.713 0.000205 ***
## age51-75                               0.89794    0.25293   3.550 0.000385 ***
## sexmale                               -0.23242    0.08016  -2.900 0.003737 ** 
## votelabour                            -0.50081    0.33324  -1.503 0.132882    
## classupper middle:age&gt;75               0.25783    0.49713   0.519 0.604013    
## classworking:age&gt;75                    0.01097    0.41896   0.026 0.979113    
## classupper middle:age26-40             0.82466    0.41396   1.992 0.046358 *  
## classworking:age26-40                  0.41083    0.35167   1.168 0.242713    
## classupper middle:age41-50             0.37788    0.39239   0.963 0.335542    
## classworking:age41-50                 -0.28917    0.33310  -0.868 0.385327    
## classupper middle:age51-75             0.43329    0.39277   1.103 0.269954    
## classworking:age51-75                  0.10223    0.32668   0.313 0.754325    
## classupper middle:votelabour          -0.12338    0.53898  -0.229 0.818936    
## classworking:votelabour                1.05741    0.39259   2.693 0.007073 ** 
## age&gt;75:votelabour                     -0.72300    0.57745  -1.252 0.210547    
## age26-40:votelabour                    0.21667    0.41944   0.517 0.605452    
## age41-50:votelabour                   -0.93431    0.43395  -2.153 0.031315 *  
## age51-75:votelabour                   -0.62601    0.41724  -1.500 0.133526    
## sexmale:votelabour                     0.37323    0.11334   3.293 0.000992 ***
## classupper middle:age&gt;75:votelabour         NA         NA      NA       NA    
## classworking:age&gt;75:votelabour        -0.29039    0.68720  -0.423 0.672607    
## classupper middle:age26-40:votelabour -0.53698    0.65445  -0.821 0.411931    
## classworking:age26-40:votelabour      -0.28479    0.49429  -0.576 0.564516    
## classupper middle:age41-50:votelabour -0.01015    0.68338  -0.015 0.988147    
## classworking:age41-50:votelabour       1.06121    0.50772   2.090 0.036603 *  
## classupper middle:age51-75:votelabour -0.06924    0.65903  -0.105 0.916328    
## classworking:age51-75:votelabour       0.16608    0.49036   0.339 0.734853    
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## (Dispersion parameter for poisson family taken to be 1)
## 
##     Null deviance: 797.594  on 57  degrees of freedom
## Residual deviance:  22.918  on 27  degrees of freedom
## AIC: 350.41
## 
## Number of Fisher Scoring iterations: 4</code></pre>
<p>These tend to be rather unwieldy, and we’ll see a better way of
understanding the results below, but you can look for the very
significant results, bearing in mind that the first category is the
baseline, for example, more of the males in the survey voted Labour
(than Conservative).</p>
<p><span class="math inline">\(\blacksquare\)</span></p>
<ol start="5" style="list-style-type: lower-alpha">
<li>If we think of the party someone votes for as the final
outcome (that depends on all the other things), what does our final
model say that someone’s vote depends on?</li>
</ol>
<p>Solution</p>
<p>Find out which of the surviving terms are interactions with
<code>vote</code>. Here, there are two things, that <code>vote</code>
depends on separately:</p>
<ul>
<li><p><code>sex</code></p></li>
<li><p>The <code>age</code>-<code>class</code> interaction.</p></li>
</ul>
<p><span class="math inline">\(\blacksquare\)</span></p>
<ol start="6" style="list-style-type: lower-alpha">
<li>Obtain sub-tables that explain how <code>vote</code> depends on
any of the things it’s related to.</li>
</ol>
<p>Solution</p>
<p>This is <code>xtabs</code> again. The 3-way interaction is a bit
tricky, so we’ll do the simple one first:</p>
<div class="sourceCode" id="cb329"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb329-1" title="1"><span class="kw">xtabs</span>(n <span class="op">~</span><span class="st"> </span>vote <span class="op">+</span><span class="st"> </span>sex, <span class="dt">data =</span> votes) <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb329-2" title="2"><span class="st">  </span><span class="kw">prop.table</span>(<span class="dt">margin =</span> <span class="dv">2</span>)</a></code></pre></div>
<pre><code>##               sex
## vote              female      male
##   conservative 0.5474339 0.4543974
##   labour       0.4525661 0.5456026</code></pre>
<p>The female voters slightly preferred to vote Conservative and the male
voters slightly preferred to vote Labour. This is a small effect, but
I guess the large number of voters made it big enough to be significant.</p>
<p>I took it this way around because <code>vote</code> is the outcome, and
therefore I want to address things
like “if a voter is female, how likely are they to vote Labour”,
rather than conditioning the other
way around (which would
be “if a voter voted Labour, how likely are they to be female”,
which doesn’t make nearly so much sense).</p>
<p>Then the tricky one:</p>
<div class="sourceCode" id="cb331"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb331-1" title="1">xt &lt;-<span class="st"> </span><span class="kw">xtabs</span>(n <span class="op">~</span><span class="st"> </span>vote <span class="op">+</span><span class="st"> </span>age <span class="op">+</span><span class="st"> </span>class, <span class="dt">data =</span> votes)</a>
<a class="sourceLine" id="cb331-2" title="2">xt</a></code></pre></div>
<pre><code>## , , class = lower middle
## 
##               age
## vote           &lt;26 &gt;75 26-40 41-50 51-75
##   conservative  22  17    31    56    54
##   labour        16   6    28    16    21
## 
## , , class = upper middle
## 
##               age
## vote           &lt;26 &gt;75 26-40 41-50 51-75
##   conservative  14  14    45    52    53
##   labour         9   0    21    13    17
## 
## , , class = working
## 
##               age
## vote           &lt;26 &gt;75 26-40 41-50 51-75
##   conservative  32  25    68    61    87
##   labour        67  19   133   145   115</code></pre>
<p>Doing it this way has produced different subtables for each
<code>class</code>. This is actually OK, because we can
say “if a voter was of lower middle class” and then talk about the relationship
between age and vote, as if we were looking at a simple effect:</p>
<ul>
<li><p>If a voter was of lower-middle-class, they strongly favour voting
Conservative in all age groups except for <code>&lt;26</code> and 26–40.</p></li>
<li><p>If a voter was of upper-middle-class, they even more strongly favour
voting Conservative in all age groups except for “under 26” and
maybe 26–40.</p></li>
<li><p>If a voter was of Working class, they strongly favour voting
Labour, except in the
“over 75” age group (and maybe 51–75 as well).</p></li>
</ul>
<p>If the anomalous age group(s) had been the same one every time, there
would no longer have been an interaction between age and class in
their effect on <code>vote</code>. But the anomalous age groups were
different for each class (“different pattern”), and that explains
why there was a <code>vote:age:class</code> interaction: " the way someone votes depends on the <em>combination</em> of age and social class".</p>
<p>For <code>prop.table</code> in three dimensions, as we have here, we have to be a little
more careful about what to make add up to 1. For example, to make the
social classes each add up to 1, which is the third dimension:</p>
<div class="sourceCode" id="cb333"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb333-1" title="1"><span class="kw">prop.table</span>(xt, <span class="dv">3</span>)</a></code></pre></div>
<pre><code>## , , class = lower middle
## 
##               age
## vote                  &lt;26        &gt;75      26-40      41-50      51-75
##   conservative 0.08239700 0.06367041 0.11610487 0.20973783 0.20224719
##   labour       0.05992509 0.02247191 0.10486891 0.05992509 0.07865169
## 
## , , class = upper middle
## 
##               age
## vote                  &lt;26        &gt;75      26-40      41-50      51-75
##   conservative 0.05882353 0.05882353 0.18907563 0.21848739 0.22268908
##   labour       0.03781513 0.00000000 0.08823529 0.05462185 0.07142857
## 
## , , class = working
## 
##               age
## vote                  &lt;26        &gt;75      26-40      41-50      51-75
##   conservative 0.04255319 0.03324468 0.09042553 0.08111702 0.11569149
##   labour       0.08909574 0.02526596 0.17686170 0.19281915 0.15292553</code></pre>
<p>What happened here is that each of the three subtables adds up to 1,
so that we have a “joint distribution” in each table. We can put
<em>two</em> variables into <code>prop.table</code>, and see what happens then:</p>
<div class="sourceCode" id="cb335"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb335-1" title="1"><span class="kw">prop.table</span>(xt, <span class="kw">c</span>(<span class="dv">2</span>, <span class="dv">3</span>))</a></code></pre></div>
<pre><code>## , , class = lower middle
## 
##               age
## vote                 &lt;26       &gt;75     26-40     41-50     51-75
##   conservative 0.5789474 0.7391304 0.5254237 0.7777778 0.7200000
##   labour       0.4210526 0.2608696 0.4745763 0.2222222 0.2800000
## 
## , , class = upper middle
## 
##               age
## vote                 &lt;26       &gt;75     26-40     41-50     51-75
##   conservative 0.6086957 1.0000000 0.6818182 0.8000000 0.7571429
##   labour       0.3913043 0.0000000 0.3181818 0.2000000 0.2428571
## 
## , , class = working
## 
##               age
## vote                 &lt;26       &gt;75     26-40     41-50     51-75
##   conservative 0.3232323 0.5681818 0.3383085 0.2961165 0.4306931
##   labour       0.6767677 0.4318182 0.6616915 0.7038835 0.5693069</code></pre>
<p>This is making each <code>class</code>-<code>age</code> combination add up to
1, so that we can clearly see what fraction of voters voted for each
party in each case.<a href="#fn40" class="footnote-ref" id="fnref40"><sup>40</sup></a>
In the first two subtables, the two youngest
subgroups are clearly different from the others, with a smaller
proportion of people voting Conservative rather than Labour than for
the older subgroups. If that same pattern persisted for the third
subtable, with the two youngest age groups being different from the
three older ones, then we would have an age by vote interaction rather
than the age by class by vote interaction that we actually have. So
the third <code>class</code> group should be different. It is: it seems
that the first <em>three</em> age groups are different from the other
two, with ages 41–50 being more inclined to vote Labour, like the
younger groups. That’s where the interaction came from.</p>
<p>The Labour Party in the UK is like the NDP here, in that it has strong
ties with “working people”, trades unions in particular. The
Conservatives are like the Conservatives here (indeed, the nickname
“Tories” comes from the UK; the Conservatives there were officially
known as the Tories many years ago). Many people are lifelong voters
for their party, and would never think of voting for the “other side”,
in the same way that many Americans vote either Democrat or
Republican without thinking about it too much. Our parliamentary
system comes from the UK system (vote for a candidate in a riding, the
leader of the party with the most elected candidates becomes Prime
Minister), and a “landslide” victory often comes from persuading
enough of the voters open to persuasion to switch sides. In the UK, as
here, the parties’ share of the popular vote doesn’t change all that
much from election to election, even though the number of seats in
Parliament might change quite a lot.</p>
<p><span class="math inline">\(\blacksquare\)</span></p>
</div>
<div id="brand-m-laundry-detergent-1" class="section level2">
<h2><span class="header-section-number">41.6</span> Brand M laundry detergent</h2>
<p>A survey was carried out comparing respondents’ preferences of a laundry detergent M compared to a mystery brand X. For each respondent, the researchers recorded the temperature of the laundry load (low or high), whether or not they previously used brand M (yes or no), and the softness of the water used for the laundry load(hard, medium or soft). The aim of the survey was to find out what was associated with the respondents preferring brand M. The data are in <a href="http://ritsokiguess.site/datafiles/brand_m.csv" class="uri">http://ritsokiguess.site/datafiles/brand_m.csv</a>.</p>
<ol style="list-style-type: lower-alpha">
<li>Read in and display (some of) the data. Explain briefly how the data is laid out appropriately to fit a log-linear model.</li>
</ol>
<p>Solution</p>
<p>The reading-in is entirely familiar:</p>
<div class="sourceCode" id="cb337"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb337-1" title="1">my_url &lt;-<span class="st"> &quot;http://ritsokiguess.site/datafiles/brand_m.csv&quot;</span></a>
<a class="sourceLine" id="cb337-2" title="2">prefs &lt;-<span class="st"> </span><span class="kw">read_csv</span>(my_url)</a></code></pre></div>
<pre><code>## 
## ── Column specification ────────────────────────────────────────────────────────
## cols(
##   softness = col_character(),
##   m_user = col_character(),
##   temperature = col_character(),
##   prefer = col_character(),
##   frequency = col_double()
## )</code></pre>
<div class="sourceCode" id="cb339"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb339-1" title="1">prefs</a></code></pre></div>
<pre><code>## # A tibble: 24 x 5
##    softness m_user temperature prefer frequency
##    &lt;chr&gt;    &lt;chr&gt;  &lt;chr&gt;       &lt;chr&gt;      &lt;dbl&gt;
##  1 hard     no     low         x             68
##  2 hard     no     low         m             42
##  3 hard     no     high        x             42
##  4 hard     no     high        m             30
##  5 hard     yes    low         x             37
##  6 hard     yes    low         m             52
##  7 hard     yes    high        x             24
##  8 hard     yes    high        m             43
##  9 medium   no     low         x             66
## 10 medium   no     low         m             50
## # … with 14 more rows</code></pre>
<p>This is good because we have each “observation” (frequency, here) in one row, or, said differently, we have a column of frequencies and each of the factors in a column of its own. (See the Extra for the kind of layout we might have had to deal with.)</p>
<p>Extra: as you might expect, this is very much <em>not</em> how the data came to me. It was originally in a textbook, laid out like this:</p>
<p><img src="brand_m.jpg" title="Original layout of data (in a textbook)" /></p>
<p>This is a common layout for frequency data, because it saves a lot of space. Multiple header rows are hard to deal with, though, so I combined the three column variables into one with a layout like this (aligned in columns):</p>
<p>softness no_low_x no_low_m no_high_x no_high_m yes_low_x yes_low_m yes_high_x yes_high_m
hard 68 42 42 30 37 52 24 43
medium 66 50 33 23 47 55 23 47
soft 63 53 29 27 57 49 19 29</p>
<p>Let’s read this in and then think about what to do with it:</p>
<div class="sourceCode" id="cb341"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb341-1" title="1">prefs0 &lt;-<span class="st"> </span><span class="kw">read_table</span>(<span class="st">&quot;brand_m.txt&quot;</span>)</a></code></pre></div>
<pre><code>## 
## ── Column specification ────────────────────────────────────────────────────────
## cols(
##   softness = col_character(),
##   no_low_x = col_double(),
##   no_low_m = col_double(),
##   no_high_x = col_double(),
##   no_high_m = col_double(),
##   yes_low_x = col_double(),
##   yes_low_m = col_double(),
##   yes_high_x = col_double(),
##   yes_high_m = col_double()
## )</code></pre>
<div class="sourceCode" id="cb343"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb343-1" title="1">prefs0</a></code></pre></div>
<pre><code>## # A tibble: 3 x 9
##   softness no_low_x no_low_m no_high_x no_high_m yes_low_x yes_low_m yes_high_x yes_high_m
##   &lt;chr&gt;       &lt;dbl&gt;    &lt;dbl&gt;     &lt;dbl&gt;     &lt;dbl&gt;     &lt;dbl&gt;     &lt;dbl&gt;      &lt;dbl&gt;      &lt;dbl&gt;
## 1 hard           68       42        42        30        37        52         24         43
## 2 medium         66       50        33        23        47        55         23         47
## 3 soft           63       53        29        27        57        49         19         29</code></pre>
<p>We want to get all those frequencies into one column, which suggest some kind of <code>pivot_longer.</code>There are two ways to go about this. One is to try a regular <code>pivot_longer</code>and see what happens. I had to think for a moment about what to call the column that ended up as <code>combo</code>:</p>
<div class="sourceCode" id="cb345"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb345-1" title="1">prefs0 <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">pivot_longer</span>(<span class="op">-</span>softness, <span class="dt">names_to =</span> <span class="st">&quot;combo&quot;</span>, <span class="dt">values_to =</span> <span class="st">&quot;frequency&quot;</span>)</a></code></pre></div>
<pre><code>## # A tibble: 24 x 3
##    softness combo      frequency
##    &lt;chr&gt;    &lt;chr&gt;          &lt;dbl&gt;
##  1 hard     no_low_x          68
##  2 hard     no_low_m          42
##  3 hard     no_high_x         42
##  4 hard     no_high_m         30
##  5 hard     yes_low_x         37
##  6 hard     yes_low_m         52
##  7 hard     yes_high_x        24
##  8 hard     yes_high_m        43
##  9 medium   no_low_x          66
## 10 medium   no_low_m          50
## # … with 14 more rows</code></pre>
<p>This is the right kind of shape, but those things in the column <code>combo</code> are three variables all smooshed together: respectively, previous user (of brand M), temperature, preference (you can tell by the values, which are all different). These can be split up with <code>separate</code>, thus:</p>
<div class="sourceCode" id="cb347"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb347-1" title="1">prefs0 <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">pivot_longer</span>(<span class="op">-</span>softness, <span class="dt">names_to =</span> <span class="st">&quot;combo&quot;</span>, <span class="dt">values_to =</span> <span class="st">&quot;frequency&quot;</span>) <span class="op">%&gt;%</span><span class="st"> </span></a>
<a class="sourceLine" id="cb347-2" title="2"><span class="kw">separate</span>(combo, <span class="dt">into =</span> <span class="kw">c</span>(<span class="st">&quot;prev_user&quot;</span>, <span class="st">&quot;temperature&quot;</span>, <span class="st">&quot;preference&quot;</span>), <span class="dt">sep =</span> <span class="st">&quot;_&quot;</span>)</a></code></pre></div>
<pre><code>## # A tibble: 24 x 5
##    softness prev_user temperature preference frequency
##    &lt;chr&gt;    &lt;chr&gt;     &lt;chr&gt;       &lt;chr&gt;          &lt;dbl&gt;
##  1 hard     no        low         x                 68
##  2 hard     no        low         m                 42
##  3 hard     no        high        x                 42
##  4 hard     no        high        m                 30
##  5 hard     yes       low         x                 37
##  6 hard     yes       low         m                 52
##  7 hard     yes       high        x                 24
##  8 hard     yes       high        m                 43
##  9 medium   no        low         x                 66
## 10 medium   no        low         m                 50
## # … with 14 more rows</code></pre>
<p>That works, but the combination of <code>pivot_longer</code> and <code>separate</code> is a common one, and so there is an “advanced” version of <code>pivot_longer</code> that does it all at once. The idea is that you enter three columns into <code>names_to</code> and then use <code>names_sep</code> to say what they’re separated by:</p>
<div class="sourceCode" id="cb349"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb349-1" title="1">prefs0 <span class="op">%&gt;%</span><span class="st"> </span></a>
<a class="sourceLine" id="cb349-2" title="2"><span class="kw">pivot_longer</span>(<span class="op">-</span>softness, </a>
<a class="sourceLine" id="cb349-3" title="3"><span class="dt">names_to =</span> <span class="kw">c</span>(<span class="st">&quot;m_user&quot;</span>, <span class="st">&quot;temperature&quot;</span>, <span class="st">&quot;prefer&quot;</span>),</a>
<a class="sourceLine" id="cb349-4" title="4"><span class="dt">names_sep =</span> <span class="st">&quot;_&quot;</span>, <span class="dt">values_to =</span> <span class="st">&quot;frequency&quot;</span>) </a></code></pre></div>
<pre><code>## # A tibble: 24 x 5
##    softness m_user temperature prefer frequency
##    &lt;chr&gt;    &lt;chr&gt;  &lt;chr&gt;       &lt;chr&gt;      &lt;dbl&gt;
##  1 hard     no     low         x             68
##  2 hard     no     low         m             42
##  3 hard     no     high        x             42
##  4 hard     no     high        m             30
##  5 hard     yes    low         x             37
##  6 hard     yes    low         m             52
##  7 hard     yes    high        x             24
##  8 hard     yes    high        m             43
##  9 medium   no     low         x             66
## 10 medium   no     low         m             50
## # … with 14 more rows</code></pre>
<p>This data frame is what I saved for you.</p>
<p><span class="math inline">\(\blacksquare\)</span></p>
<ol start="2" style="list-style-type: lower-alpha">
<li>Using backward elimination, build a suitable log-linear model for the associations between the variables. (Do <em>not</em> use <code>step</code>; do the elimination yourself).</li>
</ol>
<p>Solution</p>
<p>The first step is to fit a model containing all the interactions between the factors, using <code>frequency</code> as the response, and then to use <code>drop1</code> with <code>test="Chisq"</code> to see what can come out. Don’t forget the <code>family = "poisson"</code>, since that’s what drives the modelling. I tnink it’s easiest to number these models, since there might be a lot of them:</p>
<div class="sourceCode" id="cb351"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb351-1" title="1">prefs<span class="fl">.1</span> &lt;-<span class="st"> </span><span class="kw">glm</span>(frequency<span class="op">~</span>softness<span class="op">*</span>m_user<span class="op">*</span>temperature<span class="op">*</span>prefer, <span class="dt">family =</span> <span class="st">&quot;poisson&quot;</span>, <span class="dt">data=</span>prefs)</a>
<a class="sourceLine" id="cb351-2" title="2"><span class="kw">drop1</span>(prefs<span class="fl">.1</span>, <span class="dt">test =</span> <span class="st">&quot;Chisq&quot;</span>)</a></code></pre></div>
<pre><code>## Single term deletions
## 
## Model:
## frequency ~ softness * m_user * temperature * prefer
##                                    Df Deviance    AIC     LRT Pr(&gt;Chi)
## &lt;none&gt;                                 0.00000 180.41                 
## softness:m_user:temperature:prefer  2  0.73732 177.15 0.73732   0.6917</code></pre>
<p>To our relief, the four-way interaction is not significant and can be removed. (I was <em>not</em> looking forward to the prospect of interpreting that!)</p>
<p>Now write an <code>update</code> line that removes that four-way interaction from your model, as shown below, and copy-paste your <code>drop1</code> line from above, changing the number of your model to the one coming out of <code>update</code>. Copy-paste the complicated interaction from the <code>drop1</code> output:</p>
<div class="sourceCode" id="cb353"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb353-1" title="1">prefs<span class="fl">.2</span> &lt;-<span class="st"> </span><span class="kw">update</span>(prefs<span class="fl">.1</span>, .<span class="op">~</span>.<span class="op">-</span>softness<span class="op">:</span>m_user<span class="op">:</span>temperature<span class="op">:</span>prefer)</a>
<a class="sourceLine" id="cb353-2" title="2"><span class="kw">drop1</span>(prefs<span class="fl">.2</span>, <span class="dt">test =</span> <span class="st">&quot;Chisq&quot;</span>)</a></code></pre></div>
<pre><code>## Single term deletions
## 
## Model:
## frequency ~ softness + m_user + temperature + prefer + softness:m_user + 
##     softness:temperature + m_user:temperature + softness:prefer + 
##     m_user:prefer + temperature:prefer + softness:m_user:temperature + 
##     softness:m_user:prefer + softness:temperature:prefer + m_user:temperature:prefer
##                             Df Deviance    AIC    LRT Pr(&gt;Chi)
## &lt;none&gt;                           0.7373 177.15                
## softness:m_user:temperature  2   2.1146 174.53 1.3773   0.5022
## softness:m_user:prefer       2   5.3086 177.72 4.5713   0.1017
## softness:temperature:prefer  2   0.8991 173.31 0.1618   0.9223
## m_user:temperature:prefer    1   2.9594 177.37 2.2220   0.1361</code></pre>
<p>There are now four three-way interactions that could be removed. You might suspect that they are all going to go eventually, but as in regression, we take them one at a time, starting with the one that has the highest P-value (just in case, for example, the P-value of the second one goes under 0.05 when we remove the others). The easiest way to do the coding is a vigorous amount of copying and pasting. Copy-paste your last code chunk:</p>
<div class="sourceCode" id="cb355"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb355-1" title="1">prefs<span class="fl">.2</span> &lt;-<span class="st"> </span><span class="kw">update</span>(prefs<span class="fl">.1</span>, .<span class="op">~</span>.<span class="op">-</span>softness<span class="op">:</span>m_user<span class="op">:</span>temperature<span class="op">:</span>prefer)</a>
<a class="sourceLine" id="cb355-2" title="2"><span class="kw">drop1</span>(prefs<span class="fl">.2</span>, <span class="dt">test =</span> <span class="st">&quot;Chisq&quot;</span>)</a></code></pre></div>
<p>Change the interaction in the <code>update</code> to the one you want to remove (from the <code>drop1</code> table), which is <code>softness:temperature:prefer</code> (you can copy-paste that too), and then increase all three of the model numbers by 1:</p>
<div class="sourceCode" id="cb356"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb356-1" title="1">prefs<span class="fl">.3</span> &lt;-<span class="st"> </span><span class="kw">update</span>(prefs<span class="fl">.2</span>, .<span class="op">~</span>.<span class="op">-</span>softness<span class="op">:</span>temperature<span class="op">:</span>prefer)</a>
<a class="sourceLine" id="cb356-2" title="2"><span class="kw">drop1</span>(prefs<span class="fl">.3</span>, <span class="dt">test =</span> <span class="st">&quot;Chisq&quot;</span>)</a></code></pre></div>
<pre><code>## Single term deletions
## 
## Model:
## frequency ~ softness + m_user + temperature + prefer + softness:m_user + 
##     softness:temperature + m_user:temperature + softness:prefer + 
##     m_user:prefer + temperature:prefer + softness:m_user:temperature + 
##     softness:m_user:prefer + m_user:temperature:prefer
##                             Df Deviance    AIC    LRT Pr(&gt;Chi)
## &lt;none&gt;                           0.8991 173.31                
## softness:m_user:temperature  2   2.2506 170.67 1.3514   0.5088
## softness:m_user:prefer       2   5.4952 173.91 4.5961   0.1005
## m_user:temperature:prefer    1   3.1148 173.53 2.2157   0.1366</code></pre>
<p>Then, as they say, rinse and repeat. This one takes a while, but each step is just like the others.</p>
<p>drop <code>softness:m_user:temperature</code></p>
<div class="sourceCode" id="cb358"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb358-1" title="1">prefs<span class="fl">.4</span> &lt;-<span class="st"> </span><span class="kw">update</span>(prefs<span class="fl">.3</span>, .<span class="op">~</span>.<span class="op">-</span>softness<span class="op">:</span>m_user<span class="op">:</span>temperature)</a>
<a class="sourceLine" id="cb358-2" title="2"><span class="kw">drop1</span>(prefs<span class="fl">.4</span>, <span class="dt">test =</span> <span class="st">&quot;Chisq&quot;</span>)</a></code></pre></div>
<pre><code>## Single term deletions
## 
## Model:
## frequency ~ softness + m_user + temperature + prefer + softness:m_user + 
##     softness:temperature + m_user:temperature + softness:prefer + 
##     m_user:prefer + temperature:prefer + softness:m_user:prefer + 
##     m_user:temperature:prefer
##                           Df Deviance    AIC    LRT Pr(&gt;Chi)  
## &lt;none&gt;                         2.2506 170.67                  
## softness:temperature       2   7.8155 172.23 5.5649  0.06189 .
## softness:m_user:prefer     2   7.0585 171.47 4.8080  0.09036 .
## m_user:temperature:prefer  1   4.5184 170.93 2.2678  0.13209  
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<p>drop <code>m_user:temperature:prefer</code></p>
<div class="sourceCode" id="cb360"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb360-1" title="1">prefs<span class="fl">.5</span> &lt;-<span class="st"> </span><span class="kw">update</span>(prefs<span class="fl">.4</span>, .<span class="op">~</span>.<span class="op">-</span>m_user<span class="op">:</span>temperature<span class="op">:</span>prefer)</a>
<a class="sourceLine" id="cb360-2" title="2"><span class="kw">drop1</span>(prefs<span class="fl">.5</span>, <span class="dt">test =</span> <span class="st">&quot;Chisq&quot;</span>)</a></code></pre></div>
<pre><code>## Single term deletions
## 
## Model:
## frequency ~ softness + m_user + temperature + prefer + softness:m_user + 
##     softness:temperature + m_user:temperature + softness:prefer + 
##     m_user:prefer + temperature:prefer + softness:m_user:prefer
##                        Df Deviance    AIC    LRT Pr(&gt;Chi)  
## &lt;none&gt;                      4.5184 170.93                  
## softness:temperature    2  10.6035 173.02 6.0851  0.04771 *
## m_user:temperature      1   5.2477 169.66 0.7293  0.39311  
## temperature:prefer      1   8.2467 172.66 3.7283  0.05350 .
## softness:m_user:prefer  2   9.8462 172.26 5.3278  0.06967 .
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<p>drop <code>m_user:temperature</code></p>
<div class="sourceCode" id="cb362"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb362-1" title="1">prefs<span class="fl">.6</span> &lt;-<span class="st"> </span><span class="kw">update</span>(prefs<span class="fl">.5</span>, .<span class="op">~</span>.<span class="op">-</span>m_user<span class="op">:</span>temperature)</a>
<a class="sourceLine" id="cb362-2" title="2"><span class="kw">drop1</span>(prefs<span class="fl">.6</span>, <span class="dt">test =</span> <span class="st">&quot;Chisq&quot;</span>)</a></code></pre></div>
<pre><code>## Single term deletions
## 
## Model:
## frequency ~ softness + m_user + temperature + prefer + softness:m_user + 
##     softness:temperature + softness:prefer + m_user:prefer + 
##     temperature:prefer + softness:m_user:prefer
##                        Df Deviance    AIC    LRT Pr(&gt;Chi)  
## &lt;none&gt;                      5.2477 169.66                  
## softness:temperature    2  11.2951 171.71 6.0474  0.04862 *
## temperature:prefer      1   9.5576 171.97 4.3099  0.03789 *
## softness:m_user:prefer  2  10.5860 171.00 5.3383  0.06931 .
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<p>drop <code>softness:m_user:prefer</code></p>
<div class="sourceCode" id="cb364"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb364-1" title="1">prefs<span class="fl">.7</span> &lt;-<span class="st"> </span><span class="kw">update</span>(prefs<span class="fl">.6</span>, .<span class="op">~</span>.<span class="op">-</span>softness<span class="op">:</span>m_user<span class="op">:</span>prefer)</a>
<a class="sourceLine" id="cb364-2" title="2"><span class="kw">drop1</span>(prefs<span class="fl">.7</span>, <span class="dt">test =</span> <span class="st">&quot;Chisq&quot;</span>)</a></code></pre></div>
<pre><code>## Single term deletions
## 
## Model:
## frequency ~ softness + m_user + temperature + prefer + softness:m_user + 
##     softness:temperature + softness:prefer + m_user:prefer + 
##     temperature:prefer
##                      Df Deviance    AIC     LRT  Pr(&gt;Chi)    
## &lt;none&gt;                    10.586 171.00                      
## softness:m_user       2   11.543 167.96  0.9569   0.61974    
## softness:temperature  2   16.633 173.05  6.0474   0.04862 *  
## softness:prefer       2   10.798 167.21  0.2120   0.89942    
## m_user:prefer         1   31.049 189.46 20.4633 6.079e-06 ***
## temperature:prefer    1   14.896 173.31  4.3099   0.03789 *  
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<p>More two-ways.</p>
<p>drop <code>softness:prefer</code></p>
<div class="sourceCode" id="cb366"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb366-1" title="1">prefs<span class="fl">.8</span> &lt;-<span class="st"> </span><span class="kw">update</span>(prefs<span class="fl">.7</span>, .<span class="op">~</span>.<span class="op">-</span>softness<span class="op">:</span>prefer)</a>
<a class="sourceLine" id="cb366-2" title="2"><span class="kw">drop1</span>(prefs<span class="fl">.8</span>, <span class="dt">test =</span> <span class="st">&quot;Chisq&quot;</span>)</a></code></pre></div>
<pre><code>## Single term deletions
## 
## Model:
## frequency ~ softness + m_user + temperature + prefer + softness:m_user + 
##     softness:temperature + m_user:prefer + temperature:prefer
##                      Df Deviance    AIC     LRT  Pr(&gt;Chi)    
## &lt;none&gt;                    10.798 167.21                      
## softness:m_user       2   11.886 164.30  1.0885   0.58027    
## softness:temperature  2   16.910 169.33  6.1125   0.04706 *  
## m_user:prefer         1   31.393 185.81 20.5949 5.675e-06 ***
## temperature:prefer    1   15.173 169.59  4.3750   0.03647 *  
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<p>One more?</p>
<p>drop <code>softness:m_user</code></p>
<div class="sourceCode" id="cb368"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb368-1" title="1">prefs<span class="fl">.9</span> &lt;-<span class="st"> </span><span class="kw">update</span>(prefs<span class="fl">.8</span>, .<span class="op">~</span>.<span class="op">-</span>softness<span class="op">:</span>m_user)</a>
<a class="sourceLine" id="cb368-2" title="2"><span class="kw">drop1</span>(prefs<span class="fl">.9</span>, <span class="dt">test =</span> <span class="st">&quot;Chisq&quot;</span>)</a></code></pre></div>
<pre><code>## Single term deletions
## 
## Model:
## frequency ~ softness + m_user + temperature + prefer + softness:temperature + 
##     m_user:prefer + temperature:prefer
##                      Df Deviance    AIC     LRT  Pr(&gt;Chi)    
## &lt;none&gt;                    11.886 164.30                      
## softness:temperature  2   17.986 166.40  6.0991   0.04738 *  
## m_user:prefer         1   32.468 182.88 20.5815 5.715e-06 ***
## temperature:prefer    1   16.248 166.66  4.3616   0.03676 *  
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<p>And finally we are done! There are three two-way interactions left, which shouldn’t be too hard to interpret. That’s in the next part.</p>
<p><span class="math inline">\(\blacksquare\)</span></p>
<ol start="3" style="list-style-type: lower-alpha">
<li>What is associated with the brand a respondent prefers? By obtaining suitable frequency tables, describe the nature of these associations.</li>
</ol>
<p>Solution</p>
<p>To see what is associated with brand preference, look for significant associations with <code>prefer</code>. There are two of them, one with <code>m_user</code>, and, separately, one with temperature. This means that a respondent’s brand preference depends on whether or not they previously used brand M, and also on what temperature the laundry was washed at.</p>
<p>To investigate these, use <code>xtabs</code> to get a frequency table (easiest), and if necessary use <code>prop.table</code> to get row or column proportions as appropriate. The first thing in the model formula in <code>xtabs</code> is the frequency column; the first thing after the squiggle is rows and the second thing is columns. (If there happened to be a third thing, it would be “layers” in the table.) You might find that the table of frequencies is enough to interpret what is going on, but if not, use <code>prop.table</code> to get a table of proportions. I talk about that in a moment.</p>
<div class="sourceCode" id="cb370"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb370-1" title="1">xt &lt;-<span class="st"> </span><span class="kw">xtabs</span>(frequency <span class="op">~</span><span class="st"> </span>m_user <span class="op">+</span><span class="st"> </span>prefer, <span class="dt">data =</span> prefs)</a>
<a class="sourceLine" id="cb370-2" title="2">xt</a></code></pre></div>
<pre><code>##       prefer
## m_user   m   x
##    no  225 301
##    yes 275 207</code></pre>
<p><code>prefer</code> is the response (outcome), which I put in the columns, so I look along the rows to see what is going on. Out of the people who were previous users of Brand M (second row), slightly more of them preferred Brand M; out of the people who were not Brand M users (first row), somewhat more of them preferred Brand X.</p>
<p>This was not hard to see, because the opposite frequencies were bigger each time. But you might find it easier to compute percentages and compare those. In my table, the response was rows, so the right percentages to compute are <em>row</em> ones. That is done like this. 1 is rows, 2 is columns:</p>
<div class="sourceCode" id="cb372"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb372-1" title="1"><span class="kw">prop.table</span>(xt, <span class="dt">margin =</span> <span class="dv">1</span>)</a></code></pre></div>
<pre><code>##       prefer
## m_user         m         x
##    no  0.4277567 0.5722433
##    yes 0.5705394 0.4294606</code></pre>
<p>Out of the people who were previous Brand M users, 57% preferred Brand M; out of the people who were not previous Brand M users, only 43% of them preferred Brand M.</p>
<p>Advertisers use terms like “brand familiarity” to capture ideas like this: more people prefer Brand M in the survey if they have used it before. Not altogether surprising.</p>
<p>On to the effects of temperature on preference:</p>
<div class="sourceCode" id="cb374"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb374-1" title="1">xt &lt;-<span class="st"> </span><span class="kw">xtabs</span>(frequency <span class="op">~</span><span class="st"> </span>temperature <span class="op">+</span><span class="st"> </span>prefer, <span class="dt">data =</span> prefs)</a>
<a class="sourceLine" id="cb374-2" title="2">xt</a></code></pre></div>
<pre><code>##            prefer
## temperature   m   x
##        high 199 170
##        low  301 338</code></pre>
<div class="sourceCode" id="cb376"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb376-1" title="1"><span class="kw">prop.table</span>(xt, <span class="dt">margin =</span> <span class="dv">1</span>)</a></code></pre></div>
<pre><code>##            prefer
## temperature         m         x
##        high 0.5392954 0.4607046
##        low  0.4710485 0.5289515</code></pre>
<p>Out of the people who used a high-temperature wash, 54% of them preferred brand M, but out of the people who used a low-temperature wash, only 47% of them preferred brand M.</p>
<p>I’m making it seem like this is a big difference, and of course it’s a very small one, but the size of the survey makes even this tiny difference significant.</p>
<p>Those are really the two effects of interest, since they are the ones associated with brand preference. But there was one more association that was significant: between temperature and softness. The softness in this case was of the water used to do the laundry (and not, for example, the softness of the clothes after they come out of the dryer). That goes like this:</p>
<div class="sourceCode" id="cb378"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb378-1" title="1">xt &lt;-<span class="st"> </span><span class="kw">xtabs</span>(frequency <span class="op">~</span><span class="st"> </span>temperature <span class="op">+</span><span class="st"> </span>softness, <span class="dt">data =</span> prefs)</a>
<a class="sourceLine" id="cb378-2" title="2">xt</a></code></pre></div>
<pre><code>##            softness
## temperature hard medium soft
##        high  139    126  104
##        low   199    218  222</code></pre>
<div class="sourceCode" id="cb380"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb380-1" title="1"><span class="kw">prop.table</span>(xt, <span class="dt">margin =</span> <span class="dv">2</span>)</a></code></pre></div>
<pre><code>##            softness
## temperature      hard    medium      soft
##        high 0.4112426 0.3662791 0.3190184
##        low  0.5887574 0.6337209 0.6809816</code></pre>
<p>I decided to condition on the softness of the water, since that cannot be controlled by the person doing the laundry (the water just <em>is</em> hard or soft, depending on where you live and where your water comes from).</p>
<p>In each case, a majority of the washes were done at low temperature, but the softer the water, the bigger that majority was. Once again, the effect is not all that big, because the association was only just significant.</p>
<p><span class="math inline">\(\blacksquare\)</span></p>

</div>
</div>













































<div class="footnotes">
<hr />
<ol start="38">
<li id="fn38"><p>I don’t know why Wisconsin again, but that’s what it is.<a href="frequency-table-analysis.html#fnref38" class="footnote-back">↩</a></p></li>
<li id="fn39"><p>I don’t know why Wisconsin again, but that’s what it is.<a href="frequency-table-analysis.html#fnref39" class="footnote-back">↩</a></p></li>
<li id="fn40"><p>The reason I thought of doing this is that these two are all the variables except response.<a href="frequency-table-analysis.html#fnref40" class="footnote-back">↩</a></p></li>
</ol>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="factor-analysis.html" class="navigation navigation-prev navigation-unique" aria-label="Previous page"><i class="fa fa-angle-left"></i></a>

    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/lunr.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": null,
"text": null
},
"history": {
"link": null,
"text": null
},
"view": {
"link": null,
"text": null
},
"download": ["pasias.pdf"],
"toc": {
"collapse": "subsection"
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
