<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>Chapter 27 Logistic regression with ordinal response | Problems and Solutions in Applied Statistics</title>
  <meta name="description" content="A set of problems and solutions, in R, on various parts of applied statistics" />
  <meta name="generator" content="bookdown 0.21 and GitBook 2.6.7" />

  <meta property="og:title" content="Chapter 27 Logistic regression with ordinal response | Problems and Solutions in Applied Statistics" />
  <meta property="og:type" content="book" />
  <meta property="og:url" content="http://ritsokiguess.site/pasias" />
  
  <meta property="og:description" content="A set of problems and solutions, in R, on various parts of applied statistics" />
  <meta name="github-repo" content="nxskok/pasias" />

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Chapter 27 Logistic regression with ordinal response | Problems and Solutions in Applied Statistics" />
  
  <meta name="twitter:description" content="A set of problems and solutions, in R, on various parts of applied statistics" />
  

<meta name="author" content="Ken Butler" />


<meta name="date" content="2021-05-17" />

  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="logistic-regression.html"/>
<link rel="next" href="logistic-regression-with-nominal-response.html"/>
<script src="libs/jquery-2.2.3/jquery.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />











<style type="text/css">
a.sourceLine { display: inline-block; line-height: 1.25; }
a.sourceLine { pointer-events: none; color: inherit; text-decoration: inherit; }
a.sourceLine:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode { white-space: pre; position: relative; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
code.sourceCode { white-space: pre-wrap; }
a.sourceLine { text-indent: -1em; padding-left: 1em; }
}
pre.numberSource a.sourceLine
  { position: relative; left: -4em; }
pre.numberSource a.sourceLine::before
  { content: attr(title);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; pointer-events: all; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {  }
@media screen {
a.sourceLine::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">Problems and Solutions in Applied Statistics</a></li>

<li class="divider"></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i>Introduction</a><ul>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#packages-used-somewhere-in-this-book"><i class="fa fa-check"></i>Packages used somewhere in this book</a></li>
</ul></li>
<li class="chapter" data-level="1" data-path="getting-used-to-r-and-r-studio.html"><a href="getting-used-to-r-and-r-studio.html"><i class="fa fa-check"></i><b>1</b> Getting used to R and R Studio</a></li>
<li class="chapter" data-level="2" data-path="reading-in-data.html"><a href="reading-in-data.html"><i class="fa fa-check"></i><b>2</b> Reading in data</a></li>
<li class="chapter" data-level="3" data-path="drawing-graphs.html"><a href="drawing-graphs.html"><i class="fa fa-check"></i><b>3</b> Drawing graphs</a></li>
<li class="chapter" data-level="4" data-path="data-exploration.html"><a href="data-exploration.html"><i class="fa fa-check"></i><b>4</b> Data exploration</a></li>
<li class="chapter" data-level="5" data-path="working-with-dataframes.html"><a href="working-with-dataframes.html"><i class="fa fa-check"></i><b>5</b> Working with dataframes</a></li>
<li class="chapter" data-level="6" data-path="one-sample-inference.html"><a href="one-sample-inference.html"><i class="fa fa-check"></i><b>6</b> One-sample inference</a></li>
<li class="chapter" data-level="7" data-path="two-sample-inference.html"><a href="two-sample-inference.html"><i class="fa fa-check"></i><b>7</b> Two-sample inference</a></li>
<li class="chapter" data-level="8" data-path="power-and-sample-size.html"><a href="power-and-sample-size.html"><i class="fa fa-check"></i><b>8</b> Power and sample size</a></li>
<li class="chapter" data-level="9" data-path="the-sign-test.html"><a href="the-sign-test.html"><i class="fa fa-check"></i><b>9</b> The sign test</a></li>
<li class="chapter" data-level="10" data-path="mood-median-test.html"><a href="mood-median-test.html"><i class="fa fa-check"></i><b>10</b> Mood median test</a></li>
<li class="chapter" data-level="11" data-path="matched-pairs-t-and-sign-test.html"><a href="matched-pairs-t-and-sign-test.html"><i class="fa fa-check"></i><b>11</b> Matched pairs t and sign test</a></li>
<li class="chapter" data-level="12" data-path="normal-quantile-plots.html"><a href="normal-quantile-plots.html"><i class="fa fa-check"></i><b>12</b> Normal quantile plots</a><ul>
<li class="chapter" data-level="12.1" data-path="normal-quantile-plots.html"><a href="normal-quantile-plots.html#lengths-of-heliconia-flowers"><i class="fa fa-check"></i><b>12.1</b> Lengths of heliconia flowers</a></li>
<li class="chapter" data-level="12.2" data-path="normal-quantile-plots.html"><a href="normal-quantile-plots.html#ferritin-and-normality"><i class="fa fa-check"></i><b>12.2</b> Ferritin and normality</a></li>
<li class="chapter" data-level="12.3" data-path="normal-quantile-plots.html"><a href="normal-quantile-plots.html#lengths-of-heliconia-flowers-1"><i class="fa fa-check"></i><b>12.3</b> Lengths of heliconia flowers</a></li>
<li class="chapter" data-level="12.4" data-path="normal-quantile-plots.html"><a href="normal-quantile-plots.html#ferritin-and-normality-1"><i class="fa fa-check"></i><b>12.4</b> Ferritin and normality</a></li>
</ul></li>
<li class="chapter" data-level="13" data-path="analysis-of-variance.html"><a href="analysis-of-variance.html"><i class="fa fa-check"></i><b>13</b> Analysis of variance</a></li>
<li class="chapter" data-level="14" data-path="writing-reports.html"><a href="writing-reports.html"><i class="fa fa-check"></i><b>14</b> Writing reports</a></li>
<li class="chapter" data-level="15" data-path="learning-to-code.html"><a href="learning-to-code.html"><i class="fa fa-check"></i><b>15</b> Learning to code</a><ul>
<li class="chapter" data-level="15.1" data-path="learning-to-code.html"><a href="learning-to-code.html#introduction-1"><i class="fa fa-check"></i><b>15.1</b> Introduction</a></li>
<li class="chapter" data-level="15.2" data-path="learning-to-code.html"><a href="learning-to-code.html#data-and-pre-processing"><i class="fa fa-check"></i><b>15.2</b> Data and pre-processing</a></li>
<li class="chapter" data-level="15.3" data-path="learning-to-code.html"><a href="learning-to-code.html#analysis"><i class="fa fa-check"></i><b>15.3</b> Analysis</a></li>
<li class="chapter" data-level="15.4" data-path="learning-to-code.html"><a href="learning-to-code.html#conclusions-see-note-9"><i class="fa fa-check"></i><b>15.4</b> Conclusions (see note 9)</a></li>
</ul></li>
<li class="chapter" data-level="16" data-path="a-comparison-of-four-shampoos-in-treating-dandruff.html"><a href="a-comparison-of-four-shampoos-in-treating-dandruff.html"><i class="fa fa-check"></i><b>16</b> A comparison of four shampoos in treating dandruff</a><ul>
<li class="chapter" data-level="16.1" data-path="a-comparison-of-four-shampoos-in-treating-dandruff.html"><a href="a-comparison-of-four-shampoos-in-treating-dandruff.html#introduction-2"><i class="fa fa-check"></i><b>16.1</b> Introduction</a></li>
<li class="chapter" data-level="16.2" data-path="a-comparison-of-four-shampoos-in-treating-dandruff.html"><a href="a-comparison-of-four-shampoos-in-treating-dandruff.html#exploratory-analysis"><i class="fa fa-check"></i><b>16.2</b> Exploratory analysis</a></li>
<li class="chapter" data-level="16.3" data-path="a-comparison-of-four-shampoos-in-treating-dandruff.html"><a href="a-comparison-of-four-shampoos-in-treating-dandruff.html#analysis-of-variance-1"><i class="fa fa-check"></i><b>16.3</b> Analysis of Variance</a></li>
<li class="chapter" data-level="16.4" data-path="a-comparison-of-four-shampoos-in-treating-dandruff.html"><a href="a-comparison-of-four-shampoos-in-treating-dandruff.html#assessment-of-assumptions"><i class="fa fa-check"></i><b>16.4</b> Assessment of Assumptions</a></li>
<li class="chapter" data-level="16.5" data-path="a-comparison-of-four-shampoos-in-treating-dandruff.html"><a href="a-comparison-of-four-shampoos-in-treating-dandruff.html#conclusions"><i class="fa fa-check"></i><b>16.5</b> Conclusions</a></li>
<li class="chapter" data-level="16.6" data-path="a-comparison-of-four-shampoos-in-treating-dandruff.html"><a href="a-comparison-of-four-shampoos-in-treating-dandruff.html#end"><i class="fa fa-check"></i><b>16.6</b> End</a></li>
</ul></li>
<li class="chapter" data-level="17" data-path="tidying-data.html"><a href="tidying-data.html"><i class="fa fa-check"></i><b>17</b> Tidying data</a></li>
<li class="chapter" data-level="18" data-path="simple-regression.html"><a href="simple-regression.html"><i class="fa fa-check"></i><b>18</b> Simple regression</a></li>
<li class="chapter" data-level="19" data-path="multiple-regression.html"><a href="multiple-regression.html"><i class="fa fa-check"></i><b>19</b> Multiple regression</a></li>
<li class="chapter" data-level="20" data-path="regression-with-categorical-variables.html"><a href="regression-with-categorical-variables.html"><i class="fa fa-check"></i><b>20</b> Regression with categorical variables</a><ul>
<li class="chapter" data-level="20.1" data-path="regression-with-categorical-variables.html"><a href="regression-with-categorical-variables.html#crickets-revisited"><i class="fa fa-check"></i><b>20.1</b> Crickets revisited</a></li>
<li class="chapter" data-level="20.2" data-path="regression-with-categorical-variables.html"><a href="regression-with-categorical-variables.html#pulse-rates-and-marching"><i class="fa fa-check"></i><b>20.2</b> Pulse rates and marching</a></li>
<li class="chapter" data-level="20.3" data-path="regression-with-categorical-variables.html"><a href="regression-with-categorical-variables.html#crickets-revisited-1"><i class="fa fa-check"></i><b>20.3</b> Crickets revisited</a></li>
<li class="chapter" data-level="20.4" data-path="regression-with-categorical-variables.html"><a href="regression-with-categorical-variables.html#pulse-rates-and-marching-1"><i class="fa fa-check"></i><b>20.4</b> Pulse rates and marching</a></li>
</ul></li>
<li class="chapter" data-level="21" data-path="dates-and-times.html"><a href="dates-and-times.html"><i class="fa fa-check"></i><b>21</b> Dates and times</a></li>
<li class="chapter" data-level="22" data-path="functions.html"><a href="functions.html"><i class="fa fa-check"></i><b>22</b> Functions</a></li>
<li class="chapter" data-level="23" data-path="vector-and-matrix-algebra.html"><a href="vector-and-matrix-algebra.html"><i class="fa fa-check"></i><b>23</b> Vector and matrix algebra</a><ul>
<li class="chapter" data-level="23.1" data-path="vector-and-matrix-algebra.html"><a href="vector-and-matrix-algebra.html#heights-and-foot-lengths-again"><i class="fa fa-check"></i><b>23.1</b> Heights and foot lengths again</a></li>
<li class="chapter" data-level="23.2" data-path="vector-and-matrix-algebra.html"><a href="vector-and-matrix-algebra.html#heights-and-foot-lengths-again-1"><i class="fa fa-check"></i><b>23.2</b> Heights and foot lengths again</a></li>
</ul></li>
<li class="chapter" data-level="24" data-path="the-bootstrap.html"><a href="the-bootstrap.html"><i class="fa fa-check"></i><b>24</b> The Bootstrap</a></li>
<li class="chapter" data-level="25" data-path="bayesian-statistics-with-stan.html"><a href="bayesian-statistics-with-stan.html"><i class="fa fa-check"></i><b>25</b> Bayesian Statistics with Stan</a></li>
<li class="chapter" data-level="26" data-path="logistic-regression.html"><a href="logistic-regression.html"><i class="fa fa-check"></i><b>26</b> Logistic regression</a></li>
<li class="chapter" data-level="27" data-path="logistic-regression-with-ordinal-response.html"><a href="logistic-regression-with-ordinal-response.html"><i class="fa fa-check"></i><b>27</b> Logistic regression with ordinal response</a><ul>
<li class="chapter" data-level="27.1" data-path="logistic-regression-with-ordinal-response.html"><a href="logistic-regression-with-ordinal-response.html#do-you-like-your-mobile-phone"><i class="fa fa-check"></i><b>27.1</b> Do you like your mobile phone?</a></li>
<li class="chapter" data-level="27.2" data-path="logistic-regression-with-ordinal-response.html"><a href="logistic-regression-with-ordinal-response.html#finding-non-missing-values"><i class="fa fa-check"></i><b>27.2</b> Finding non-missing values</a></li>
<li class="chapter" data-level="27.3" data-path="logistic-regression-with-ordinal-response.html"><a href="logistic-regression-with-ordinal-response.html#high-school-and-beyond"><i class="fa fa-check"></i><b>27.3</b> High School and Beyond</a></li>
<li class="chapter" data-level="27.4" data-path="logistic-regression-with-ordinal-response.html"><a href="logistic-regression-with-ordinal-response.html#how-do-you-like-your-steak"><i class="fa fa-check"></i><b>27.4</b> How do you like your steak?</a></li>
<li class="chapter" data-level="27.5" data-path="logistic-regression-with-ordinal-response.html"><a href="logistic-regression-with-ordinal-response.html#how-do-you-like-your-steak-the-data"><i class="fa fa-check"></i><b>27.5</b> How do you like your steak – the data</a></li>
<li class="chapter" data-level="27.6" data-path="logistic-regression-with-ordinal-response.html"><a href="logistic-regression-with-ordinal-response.html#do-you-like-your-mobile-phone-1"><i class="fa fa-check"></i><b>27.6</b> Do you like your mobile phone?</a></li>
<li class="chapter" data-level="27.7" data-path="logistic-regression-with-ordinal-response.html"><a href="logistic-regression-with-ordinal-response.html#finding-non-missing-values-1"><i class="fa fa-check"></i><b>27.7</b> Finding non-missing values</a></li>
<li class="chapter" data-level="27.8" data-path="logistic-regression-with-ordinal-response.html"><a href="logistic-regression-with-ordinal-response.html#high-school-and-beyond-1"><i class="fa fa-check"></i><b>27.8</b> High School and Beyond</a></li>
<li class="chapter" data-level="27.9" data-path="logistic-regression-with-ordinal-response.html"><a href="logistic-regression-with-ordinal-response.html#how-do-you-like-your-steak-1"><i class="fa fa-check"></i><b>27.9</b> How do you like your steak?</a></li>
<li class="chapter" data-level="27.10" data-path="logistic-regression-with-ordinal-response.html"><a href="logistic-regression-with-ordinal-response.html#how-do-you-like-your-steak-the-data-1"><i class="fa fa-check"></i><b>27.10</b> How do you like your steak – the data</a></li>
</ul></li>
<li class="chapter" data-level="28" data-path="logistic-regression-with-nominal-response.html"><a href="logistic-regression-with-nominal-response.html"><i class="fa fa-check"></i><b>28</b> Logistic regression with nominal response</a></li>
<li class="chapter" data-level="29" data-path="survival-analysis.html"><a href="survival-analysis.html"><i class="fa fa-check"></i><b>29</b> Survival analysis</a></li>
<li class="chapter" data-level="30" data-path="analysis-of-variance-revisited.html"><a href="analysis-of-variance-revisited.html"><i class="fa fa-check"></i><b>30</b> Analysis of variance revisited</a></li>
<li class="chapter" data-level="31" data-path="analysis-of-covariance.html"><a href="analysis-of-covariance.html"><i class="fa fa-check"></i><b>31</b> Analysis of covariance</a></li>
<li class="chapter" data-level="32" data-path="multivariate-analysis-of-variance.html"><a href="multivariate-analysis-of-variance.html"><i class="fa fa-check"></i><b>32</b> Multivariate analysis of variance</a></li>
<li class="chapter" data-level="33" data-path="repeated-measures.html"><a href="repeated-measures.html"><i class="fa fa-check"></i><b>33</b> Repeated measures</a></li>
<li class="chapter" data-level="34" data-path="discriminant-analysis.html"><a href="discriminant-analysis.html"><i class="fa fa-check"></i><b>34</b> Discriminant analysis</a></li>
<li class="chapter" data-level="35" data-path="hierarchical-cluster-analysis.html"><a href="hierarchical-cluster-analysis.html"><i class="fa fa-check"></i><b>35</b> Hierarchical cluster analysis</a></li>
<li class="chapter" data-level="36" data-path="k-means-cluster-analysis.html"><a href="k-means-cluster-analysis.html"><i class="fa fa-check"></i><b>36</b> K-means cluster analysis</a></li>
<li class="chapter" data-level="37" data-path="drawing-maps-with-leaflet.html"><a href="drawing-maps-with-leaflet.html"><i class="fa fa-check"></i><b>37</b> Drawing maps with Leaflet</a></li>
<li class="chapter" data-level="38" data-path="multidimensional-scaling.html"><a href="multidimensional-scaling.html"><i class="fa fa-check"></i><b>38</b> Multidimensional Scaling</a></li>
<li class="chapter" data-level="39" data-path="principal-components.html"><a href="principal-components.html"><i class="fa fa-check"></i><b>39</b> Principal Components</a><ul>
<li class="chapter" data-level="39.1" data-path="principal-components.html"><a href="principal-components.html#the-weather-somewhere"><i class="fa fa-check"></i><b>39.1</b> The weather, somewhere</a></li>
<li class="chapter" data-level="39.2" data-path="principal-components.html"><a href="principal-components.html#the-weather-somewhere-1"><i class="fa fa-check"></i><b>39.2</b> The weather, somewhere</a></li>
</ul></li>
<li class="chapter" data-level="40" data-path="factor-analysis.html"><a href="factor-analysis.html"><i class="fa fa-check"></i><b>40</b> Factor Analysis</a></li>
<li class="chapter" data-level="41" data-path="frequency-table-analysis.html"><a href="frequency-table-analysis.html"><i class="fa fa-check"></i><b>41</b> Frequency table analysis</a></li>
<li class="divider"></li>
<li><a href="https://github.com/rstudio/bookdown" target="blank">Published with bookdown</a></li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Problems and Solutions in Applied Statistics</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="logistic-regression-with-ordinal-response" class="section level1">
<h1><span class="header-section-number">Chapter 27</span> Logistic regression with ordinal response</h1>
<div class="sourceCode" id="cb212"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb212-1" title="1"><span class="kw">library</span>(MASS)</a>
<a class="sourceLine" id="cb212-2" title="2"><span class="kw">library</span>(tidyverse)</a></code></pre></div>
<div id="do-you-like-your-mobile-phone" class="section level2">
<h2><span class="header-section-number">27.1</span> Do you like your mobile phone?</h2>
<p>A phone company commissioned a survey of their customers’
satisfaction with their mobile devices. The responses to the survey
were on a so-called Likert scale of “very unsatisfied”,
“unsatisfied”, “satisfied”, “very satisfied”. Also recorded were
each customer’s gender and age group (under 18, 18–24, 25–30, 31 or
older). (A survey of this kind does not ask its respondents for their
exact age, only which age group they fall in.) The data, as
frequencies of people falling into each category combination, are in <a href="http://ritsokiguess.site/datafiles/mobile.txt">link</a>.</p>
<ol style="list-style-type: lower-alpha">
<li><p><a name="part:gather"><em></a> Read in the data and take a look at the format. Use a tool
that you know about to arrange the frequencies in </em>one* column,
with other columns labelling the response categories that the
frequencies belong to. Save the new data frame. (Take a look at it
if you like.)</p></li>
<li><p>We are going to fit ordered logistic models below. To
do that, we need our response variable to be a factor with its levels
in the right order. By looking at the data frame
you just created, determine what kind
of thing your intended response variable currently is.</p></li>
<li><p>If your intended response variable is not a factor, create a factor in your data frame with levels in the right order. Hint: look at the order your levels are <em>in the data</em>.</p></li>
<li><p><a name="part:thefit">*</a>
Fit ordered logistic models to predict satisfaction from (i) gender
and age group, (ii) gender only, (iii) age group only. (You don’t
need to examine the models.) Don’t forget a suitable
<code>weights</code>!</p></li>
<li><p>Use <code>drop1</code> on your model containing both explanatory
variables to determine whether you can remove either of them. Use
<code>test="Chisq"</code> to obtain P-values.</p></li>
<li><p>Use <code>anova</code> to decide whether we are justified in
removing <code>gender</code> from a model containing both <code>gender</code>
and <code>age.group</code>. Compare your P-value with the one from <code>drop1</code>.</p></li>
<li><p>Use <code>anova</code> to see whether we are justified in removing
<code>age.group</code> from a model containing both <code>gender</code> and
<code>age.group</code>. Compare your P-value with the one from
<code>drop1</code> above.</p></li>
<li><p>Which of the models you have fit so far is the most
appropriate one? Explain briefly.</p></li>
<li><p>Obtain predicted probabilities of a
customer falling in the various satisfaction categories, as it
depends on gender and age group. To do that, you need to feed
<code>predict</code> three things: the fitted model that contains both
age group and gender, the data frame that you read in from the file
back in part (<a href="#part:gather">here</a>) (which contains all the combinations of age group
and gender), and an appropriate <code>type</code>.</p></li>
<li><p><a name="part:unload">*</a>
Describe any patterns you see in the predictions, bearing in mind the
significance or not of the explanatory variables.</p></li>
</ol>
</div>
<div id="finding-non-missing-values" class="section level2">
<h2><span class="header-section-number">27.2</span> Finding non-missing values</h2>
<p><a name="part:prepare-next">*</a> This is to prepare you for something in the next
question. It’s meant to be easy.</p>
<p>In R, the code <code>NA</code> stands for “missing value” or
“value not known”. In R, <code>NA</code> should not have quotes around
it. (It is a special code, not a piece of text.)</p>
<ol style="list-style-type: lower-alpha">
<li><p>Create a vector <code>v</code> that contains some numbers and some
missing values, using <code>c()</code>. Put those values into a
one-column data frame.</p></li>
<li><p>Obtain a new column containing <code>is.na(v)</code>. When is this true and when is this false?</p></li>
<li><p>The symbol <code>!</code> means “not” in R (and other
programming languages). What does <code>!is.na(v)</code> do? Create a
new column containing that.</p></li>
<li><p>Use <code>filter</code> to display just the
rows of your data frame that have a non-missing value of <code>v</code>.</p></li>
</ol>
</div>
<div id="high-school-and-beyond" class="section level2">
<h2><span class="header-section-number">27.3</span> High School and Beyond</h2>
<p>A survey called High School and Beyond was given to a large
number of American high school seniors (grade 12) by the National
Center of Education Statistics. The data set at
<a href="http://ritsokiguess.site/datafiles/hsb.csv">link</a> is a random
sample of 200 of those students.</p>
<p>The variables collected are:</p>
<ul>
<li><p><code>gender</code>: student’s gender, female or male.</p></li>
<li><p><code>race</code>: the student’s race (African-American,
Asian,<a href="#fn36" class="footnote-ref" id="fnref36"><sup>36</sup></a> Hispanic, White).</p></li>
<li><p><code>ses</code>: Socio-economic status of student’s family (low,
middle, or high)</p></li>
<li><p><code>schtyp</code>: School type, public or private.</p></li>
<li><p><code>prog</code>: Student’s program, general, academic, or
vocational.</p></li>
<li><p><code>read</code>: Score on standardized reading test.</p></li>
<li><p><code>write</code>: Score on standardized writing test.</p></li>
<li><p><code>math</code>: Score on standardized math test.</p></li>
<li><p><code>science</code>: Score on standardized science test.</p></li>
<li><p><code>socst</code>: Score on standardized social studies test.</p></li>
</ul>
<p>Our aim is to see how socio-economic status is related to the other
variables.</p>
<ol style="list-style-type: lower-alpha">
<li><p>Read in and display (some of) the data.</p></li>
<li><p>Explain briefly why an ordinal logistic regression is
appropriate for our aims.</p></li>
<li><p>Fit an ordinal logistic regression predicting
socio-economic status from the scores on the five standardized
tests. (You don’t need to display the results.) You will probably
go wrong the first time. What kind of thing does your response
variable have to be?</p></li>
<li><p>Remove any non-significant explanatory variables one at a
time. Use <code>drop1</code> to decide which one to remove next.</p></li>
<li><p>The quartiles of the <code>science</code> test score are 44
and 58. The quartiles of the <code>socst</code> test score are 46 and 61. Make
a data frame that has all combinations of those quartiles. If your best
regression had any other explanatory variables in it, also put the
<em>medians</em> of those variables into this data frame.</p></li>
<li><p>Use the data frame you created in the previous part, together
with your best model, to obtain predicted probabilities of being in
each <code>ses</code> category.</p></li>
<li><p>What is the effect of an increased science score on the
likelihood of a student being in the different socioeconomic groups,
all else equal? Explain briefly. In your explanation, state clearly
how you are using your answer to the previous part.</p></li>
</ol>
</div>
<div id="how-do-you-like-your-steak" class="section level2">
<h2><span class="header-section-number">27.4</span> How do you like your steak?</h2>
<p>When you order a steak in a restaurant, the server will ask
you how you would like it cooked, or to be precise, <em>how much</em>
you would like it cooked: rare (hardly cooked at all), through medium
rare, medium, medium well to well (which means “well done”, so that
the meat has only a little red to it). Could you guess how a person
likes their steak cooked, from some other information about them? The
website <a href="fivethirtyeight.com">link</a> commissioned a survey where they
asked a number of people how they preferred their steak, along with as
many other things as they could think of to ask. (Many of the
variables below are related to risk-taking, which was something the
people designing the survey thought might have something to do with
liking steak rare.) The variables of interest are all factors or true/false:</p>
<ul>
<li><p><code>respondent_ID</code>: a ten-digit number identifying each
person who responded to the survey.</p></li>
<li><p><code>lottery_a</code>: true if the respondent preferred lottery A
with a small chance to win a lot of money, to lottery B, with a
larger chance to win less money.</p></li>
<li><p><code>smoke</code>: true if the respondent is currently a smoker</p></li>
<li><p><code>alcohol</code>: true if the respondent at least occasionally
drinks alcohol.</p></li>
<li><p><code>gamble</code>: true if the respondent likes to gamble (eg.
betting on horse racing or playing the lottery)</p></li>
<li><p><code>skydiving</code>: true if the respondent has ever been
skydiving.</p></li>
<li><p><code>speed</code>: true if the respondent likes to drive fast</p></li>
<li><p><code>cheated</code>: true if the respondent has ever cheated on a
spouse or girlfriend/boyfriend</p></li>
<li><p><code>steak</code>: true if the respondent likes to eat steak</p></li>
<li><p><code>steak_prep</code> (response): how the respondent likes their
steak cooked (factor, as described above, with 5 levels).</p></li>
<li><p><code>female</code>: true if the respondent is female</p></li>
<li><p><code>age</code>: age group, from 18–29 to 60+.</p></li>
<li><p><code>hhold_income</code>: household income group, from $0–24,999
to $150,000+.</p></li>
<li><p><code>educ</code>: highest level of education attained, from
“less than high school” up to “graduate degree”</p></li>
<li><p><code>region</code>: region (of the US)
that the respondent lives in (five values).</p></li>
</ul>
<p>The data are in
<a href="http://ritsokiguess.site/datafiles/steak1.csv">link</a>. This is the
cleaned-up data from a previous question, with the missing values removed.</p>
<ol style="list-style-type: lower-alpha">
<li><p>Read in the data and display the first few lines.</p></li>
<li><p>We are going to predict <code>steak_prep</code> from some of
the other variables. Why is the model-fitting function <code>polr</code>
from package <code>MASS</code> the best choice for these data
(alternatives being <code>glm</code> and <code>multinom</code> from package
<code>nnet</code>)?</p></li>
<li><p>What are the levels of <code>steak_prep</code>,
<em>in the order that R thinks they are in?</em> If they are not in a sensible
order, create an ordered factor where the levels are in a sensible order.</p></li>
<li><p>Fit a model predicting preferred steak preparation in an
ordinal logistic regression from <code>educ</code>, <code>female</code> and
<code>lottery_a</code>. This ought to be easy from your previous work,
but you have to be careful about one thing. No need to print out the
results.</p></li>
<li><p>Run <code>drop1</code> on your fitted model, with
<code>test="Chisq"</code>. Which explanatory variable should be removed
first, if any? Bear in mind that the variable with the
<em>smallest</em> AIC should come out first, in case your table
doesn’t get printed in order.</p></li>
<li><p>Remove the variable that should come out first, using
<code>update</code>. (If all the variables should stay, you can skip
this part.)</p></li>
<li><p>Using the best model that you have so far, predict the
probabilities of preferring each different steak preparation (method
of cooking) for each combination of the variables that
remain. (Some of the variables are TRUE and FALSE rather than
factors. Bear this in mind.)
Describe the effects of each variable on the predicted
probabilities, if any. Note that there is exactly one person in the
study whose educational level is “less than high school”.</p></li>
<li><p>Is it reasonable to remove <em>all</em> the remaining
explanatory variables from your best model so far? Fit a model with no explanatory variables,
and do a test. (In R, if the right side of the squiggle is a
<code>1</code>, that means “just an intercept”. Or you can remove
whatever remains using <code>update</code>.) What do you conclude?
Explain briefly.</p></li>
<li><p>In the article for which these data were collected,
<a href="https://fivethirtyeight.com/datalab/how-americans-like-their-steak/">link</a>,
does the author obtain consistent conclusions with yours? Explain
briefly. (It’s not a very long article, so it won’t take you long to
skim through, and the author’s point is pretty clear.)</p></li>
</ol>
</div>
<div id="how-do-you-like-your-steak-the-data" class="section level2">
<h2><span class="header-section-number">27.5</span> How do you like your steak – the data</h2>
<p><a name="q:steak-data"><em></a>
This question takes you through the data preparation for one
of the other questions. You don’t have to do </em>this*
question, but you may find it interesting or useful.</p>
<p>When you order a steak in a restaurant, the server will ask
you how you would like it cooked, or to be precise, <em>how much</em>
you would like it cooked: rare (hardly cooked at all), through medium
rare, medium, medium well to well (which means “well done”, so that
the meat has only a little red to it). Could you guess how a person
likes their steak cooked, from some other information about them? The
website <a href="fivethirtyeight.com">link</a> commissioned a survey where they
asked a number of people how they preferred their steak, along with as
many other things as they could think of to ask. (Many of the
variables below are related to risk-taking, which was something the
people designing the survey thought might have something to do with
liking steak rare.) The variables of interest are all factors or true/false:</p>
<ul>
<li><p><code>respondent_ID</code>: a ten-digit number identifying each
person who responded to the survey.</p></li>
<li><p><code>lottery_a</code>: true if the respondent preferred lottery A
with a small chance to win a lot of money, to lottery B, with a
larger chance to win less money.</p></li>
<li><p><code>smoke</code>: true if the respondent is currently a smoker</p></li>
<li><p><code>alcohol</code>: true if the respondent at least occasionally
drinks alcohol.</p></li>
<li><p><code>gamble</code>: true if the respondent likes to gamble (eg.
betting on horse racing or playing the lottery)</p></li>
<li><p><code>skydiving</code>: true if the respondent has ever been
skydiving.</p></li>
<li><p><code>speed</code>: true if the respondent likes to drive fast</p></li>
<li><p><code>cheated</code>: true if the respondent has ever cheated on a
spouse or girlfriend/boyfriend</p></li>
<li><p><code>steak</code>: true if the respondent likes to eat steak</p></li>
<li><p><code>steak_prep</code> (response): how the respondent likes their
steak cooked (factor, as described above, with 5 levels).</p></li>
<li><p><code>female</code>: true if the respondent is female</p></li>
<li><p><code>age</code>: age group, from 18–29 to 60+.</p></li>
<li><p><code>hhold_income</code>: household income group, from $0–24,999
to $150,000+.</p></li>
<li><p><code>educ</code>: highest level of education attained, from
“less than high school”
up to “graduate degree”</p></li>
<li><p><code>region</code>: region (of the US)
that the respondent lives in (five values).</p></li>
</ul>
<p>The data are in
<a href="https://raw.githubusercontent.com/nxskok/datafiles/master/steak.csv">link</a>.</p>
<ol style="list-style-type: lower-alpha">
<li><p>Read in the data and display the first few lines.</p></li>
<li><p>What do you immediately notice about your data frame? Run <code>summary</code> on the entire data frame. Would you say you have a lot of missing values, or only a few?</p></li>
<li><p>What does the function <code>drop_na</code> do when applied to a data frame with missing values? To find out, pass the data frame into <code>drop_na()</code>, then into <code>summary</code> again. What has happened?</p></li>
<li><p>Write the data into a <code>.csv</code> file, with a name like
<code>steak1.csv</code>. Open this file in a spreadsheet and (quickly)
verify that you have the right columns and no missing values.</p></li>
</ol>
<p>My solutions follow:</p>
</div>
<div id="do-you-like-your-mobile-phone-1" class="section level2">
<h2><span class="header-section-number">27.6</span> Do you like your mobile phone?</h2>
<p>A phone company commissioned a survey of their customers’
satisfaction with their mobile devices. The responses to the survey
were on a so-called Likert scale of “very unsatisfied”,
“unsatisfied”, “satisfied”, “very satisfied”. Also recorded were
each customer’s gender and age group (under 18, 18–24, 25–30, 31 or
older). (A survey of this kind does not ask its respondents for their
exact age, only which age group they fall in.) The data, as
frequencies of people falling into each category combination, are in <a href="http://ritsokiguess.site/datafiles/mobile.txt">link</a>.</p>
<ol style="list-style-type: lower-alpha">
<li><a name="part:gather"><em></a> Read in the data and take a look at the format. Use a tool
that you know about to arrange the frequencies in </em>one* column,
with other columns labelling the response categories that the
frequencies belong to. Save the new data frame. (Take a look at it
if you like.)</li>
</ol>
<p>Solution</p>
<div class="sourceCode" id="cb213"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb213-1" title="1">my_url &lt;-<span class="st"> &quot;http://ritsokiguess.site/datafiles/mobile.txt&quot;</span></a>
<a class="sourceLine" id="cb213-2" title="2">mobile &lt;-<span class="st"> </span><span class="kw">read_delim</span>(my_url, <span class="st">&quot; &quot;</span>)</a></code></pre></div>
<pre><code>## 
## ── Column specification ──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
## cols(
##   gender = col_character(),
##   age.group = col_character(),
##   very.unsat = col_double(),
##   unsat = col_double(),
##   sat = col_double(),
##   very.sat = col_double()
## )</code></pre>
<div class="sourceCode" id="cb215"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb215-1" title="1">mobile</a></code></pre></div>
<pre><code>## # A tibble: 8 x 6
##   gender age.group very.unsat unsat   sat very.sat
##   &lt;chr&gt;  &lt;chr&gt;          &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt;    &lt;dbl&gt;
## 1 male   0-17               3     9    18       24
## 2 male   18-24              6    13    16       28
## 3 male   25-30              9    13    17       20
## 4 male   31+                5     7    16       16
## 5 female 0-17               4     8    11       25
## 6 female 18-24              8    14    20       18
## 7 female 25-30             10    15    16       12
## 8 female 31+                5    14    12        8</code></pre>
<p>With multiple columns that are all frequencies, this is a job for
<code>pivot_longer</code>:</p>
<div class="sourceCode" id="cb217"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb217-1" title="1">mobile <span class="op">%&gt;%</span><span class="st"> </span></a>
<a class="sourceLine" id="cb217-2" title="2"><span class="st">  </span><span class="kw">pivot_longer</span>(very.unsat<span class="op">:</span>very.sat, </a>
<a class="sourceLine" id="cb217-3" title="3">               <span class="dt">names_to=</span><span class="st">&quot;satisfied&quot;</span>, </a>
<a class="sourceLine" id="cb217-4" title="4">               <span class="dt">values_to=</span><span class="st">&quot;frequency&quot;</span>) -&gt;<span class="st"> </span>mobile.long</a>
<a class="sourceLine" id="cb217-5" title="5">mobile.long</a></code></pre></div>
<pre><code>## # A tibble: 32 x 4
##    gender age.group satisfied  frequency
##    &lt;chr&gt;  &lt;chr&gt;     &lt;chr&gt;          &lt;dbl&gt;
##  1 male   0-17      very.unsat         3
##  2 male   0-17      unsat              9
##  3 male   0-17      sat               18
##  4 male   0-17      very.sat          24
##  5 male   18-24     very.unsat         6
##  6 male   18-24     unsat             13
##  7 male   18-24     sat               16
##  8 male   18-24     very.sat          28
##  9 male   25-30     very.unsat         9
## 10 male   25-30     unsat             13
## # … with 22 more rows</code></pre>
<p>Yep, all good. See how <code>mobile.long</code> contains what it should?
(For those keeping track, the original data frame had 8 rows and 4
columns to collect up, and the new one has <span class="math inline">\(8\times 4=32\)</span> rows.)</p>
<p><span class="math inline">\(\blacksquare\)</span></p>
<ol start="2" style="list-style-type: lower-alpha">
<li>We are going to fit ordered logistic models below. To
do that, we need our response variable to be a factor with its levels
in the right order. By looking at the data frame
you just created, determine what kind
of thing your intended response variable currently is.</li>
</ol>
<p>Solution</p>
<p>I looked at <code>mobile.long</code> in the previous part, but if you
didn’t, look at it here:</p>
<div class="sourceCode" id="cb219"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb219-1" title="1">mobile.long</a></code></pre></div>
<pre><code>## # A tibble: 32 x 4
##    gender age.group satisfied  frequency
##    &lt;chr&gt;  &lt;chr&gt;     &lt;chr&gt;          &lt;dbl&gt;
##  1 male   0-17      very.unsat         3
##  2 male   0-17      unsat              9
##  3 male   0-17      sat               18
##  4 male   0-17      very.sat          24
##  5 male   18-24     very.unsat         6
##  6 male   18-24     unsat             13
##  7 male   18-24     sat               16
##  8 male   18-24     very.sat          28
##  9 male   25-30     very.unsat         9
## 10 male   25-30     unsat             13
## # … with 22 more rows</code></pre>
<p>My intended response variable is what I called <code>satisfied</code>.
This is <code>chr</code> or “text”, not the <code>factor</code> that I
want.</p>
<p><span class="math inline">\(\blacksquare\)</span></p>
<ol start="3" style="list-style-type: lower-alpha">
<li>If your intended response variable is not a factor, create a factor in your data frame with levels in the right order. Hint: look at the order your levels are <em>in the data</em>.</li>
</ol>
<p>Solution</p>
<p>My intended response <code>satisfied</code> is text, not a factor, so
I need to do this part.
The hint is to look at the column <code>satisfied</code> in
<code>mobile.long</code> and note that the satisfaction categories
appear in the data <em>in the order that we want</em>. This is good
news, because we can use <code>fct_inorder</code> like this:</p>
<div class="sourceCode" id="cb221"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb221-1" title="1">mobile.long <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb221-2" title="2"><span class="st">  </span><span class="kw">mutate</span>(<span class="dt">satis =</span> <span class="kw">fct_inorder</span>(satisfied)) -&gt;<span class="st"> </span>mobile.long</a></code></pre></div>
<p>If you check, by looking at the data frame, <code>satis</code> is
a <code>factor</code>, and you can also do this to verify that its levels
are in the right order:</p>
<div class="sourceCode" id="cb222"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb222-1" title="1"><span class="kw">with</span>(mobile.long, <span class="kw">levels</span>(satis))</a></code></pre></div>
<pre><code>## [1] &quot;very.unsat&quot; &quot;unsat&quot;      &quot;sat&quot;        &quot;very.sat&quot;</code></pre>
<p>Success.</p>
<p>Extra: so now you are asking, what if the levels are in the <em>wrong</em> order in the data? Well, below is what you used to have to do, and it will work for this as well.
I’ll first find what levels of satisfaction I have. This
can be done by counting them, or by finding the distinct ones:</p>
<div class="sourceCode" id="cb224"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb224-1" title="1">mobile.long <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">count</span>(satisfied)</a></code></pre></div>
<pre><code>## # A tibble: 4 x 2
##   satisfied      n
##   &lt;chr&gt;      &lt;int&gt;
## 1 sat            8
## 2 unsat          8
## 3 very.sat       8
## 4 very.unsat     8</code></pre>
<p>or</p>
<div class="sourceCode" id="cb226"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb226-1" title="1">mobile.long <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">distinct</span>(satisfied)</a></code></pre></div>
<pre><code>## # A tibble: 4 x 1
##   satisfied 
##   &lt;chr&gt;     
## 1 very.unsat
## 2 unsat     
## 3 sat       
## 4 very.sat</code></pre>
<p>If you count them, they come out in alphabetical order. If you ask for
the distinct ones, they come out in the order they were in
<code>mobile.long</code>, which is the order the <em>columns</em> of those
names were in <code>mobile</code>, which is the order we want.</p>
<p>To actually grab those satisfaction levels as a vector (that we will
need in a minute), use <code>pluck</code> to pull the column out of the
data frame as a vector:</p>
<div class="sourceCode" id="cb228"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb228-1" title="1">v1 &lt;-<span class="st"> </span>mobile.long <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb228-2" title="2"><span class="st">  </span><span class="kw">distinct</span>(satisfied) <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb228-3" title="3"><span class="st">  </span><span class="kw">pluck</span>(<span class="st">&quot;satisfied&quot;</span>)</a>
<a class="sourceLine" id="cb228-4" title="4">v1</a></code></pre></div>
<pre><code>## [1] &quot;very.unsat&quot; &quot;unsat&quot;      &quot;sat&quot;        &quot;very.sat&quot;</code></pre>
<p>which is in the correct order, or</p>
<div class="sourceCode" id="cb230"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb230-1" title="1">v2 &lt;-<span class="st"> </span>mobile.long <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb230-2" title="2"><span class="st">  </span><span class="kw">count</span>(satisfied) <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb230-3" title="3"><span class="st">  </span><span class="kw">pluck</span>(<span class="st">&quot;satisfied&quot;</span>)</a>
<a class="sourceLine" id="cb230-4" title="4">v2</a></code></pre></div>
<pre><code>## [1] &quot;sat&quot;        &quot;unsat&quot;      &quot;very.sat&quot;   &quot;very.unsat&quot;</code></pre>
<p>which is in alphabetical order. The problem with the second one is
that we know the correct order, but there isn’t a good way to code
that, so we have to rearrange it ourselves. The correct order from
<code>v2</code> is 4, 2, 1, 3, so:</p>
<div class="sourceCode" id="cb232"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb232-1" title="1">v3 &lt;-<span class="st"> </span><span class="kw">c</span>(v2[<span class="dv">4</span>], v2[<span class="dv">2</span>], v2[<span class="dv">1</span>], v2[<span class="dv">3</span>])</a>
<a class="sourceLine" id="cb232-2" title="2">v3</a></code></pre></div>
<pre><code>## [1] &quot;very.unsat&quot; &quot;unsat&quot;      &quot;sat&quot;        &quot;very.sat&quot;</code></pre>
<div class="sourceCode" id="cb234"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb234-1" title="1">v4 &lt;-<span class="st"> </span>v2[<span class="kw">c</span>(<span class="dv">4</span>, <span class="dv">2</span>, <span class="dv">1</span>, <span class="dv">3</span>)]</a>
<a class="sourceLine" id="cb234-2" title="2">v4</a></code></pre></div>
<pre><code>## [1] &quot;very.unsat&quot; &quot;unsat&quot;      &quot;sat&quot;        &quot;very.sat&quot;</code></pre>
<p>Either of these will work. The first one is more typing, but is
perhaps more obvious. There is a third way, which is to keep things as
a data frame until the end, and use <code>slice</code> to pick out the
rows in the right order:</p>
<div class="sourceCode" id="cb236"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb236-1" title="1">v5 &lt;-<span class="st"> </span>mobile.long <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb236-2" title="2"><span class="st">  </span><span class="kw">count</span>(satisfied) <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb236-3" title="3"><span class="st">  </span><span class="kw">slice</span>(<span class="kw">c</span>(<span class="dv">4</span>, <span class="dv">2</span>, <span class="dv">1</span>, <span class="dv">3</span>)) <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb236-4" title="4"><span class="st">  </span><span class="kw">pluck</span>(<span class="st">&quot;satisfied&quot;</span>)</a>
<a class="sourceLine" id="cb236-5" title="5">v5</a></code></pre></div>
<pre><code>## [1] &quot;very.unsat&quot; &quot;unsat&quot;      &quot;sat&quot;        &quot;very.sat&quot;</code></pre>
<p>If you don’t see how that works, run it yourself, one line at a time.</p>
<p>The other way of doing this is to physically type them into a vector,
but this carries the usual warnings of requiring you to be very
careful and that it won’t be reproducible (eg. if you do another
survey with different response categories).</p>
<p>So now create the proper response
variable thus, using your vector of categories:</p>
<div class="sourceCode" id="cb238"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb238-1" title="1">mobile.long <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb238-2" title="2"><span class="st">  </span><span class="kw">mutate</span>(<span class="dt">satis =</span> <span class="kw">ordered</span>(satisfied, v1)) -&gt;<span class="st"> </span>mobile.long2</a>
<a class="sourceLine" id="cb238-3" title="3">mobile.long2</a></code></pre></div>
<pre><code>## # A tibble: 32 x 5
##    gender age.group satisfied  frequency satis     
##    &lt;chr&gt;  &lt;chr&gt;     &lt;chr&gt;          &lt;dbl&gt; &lt;ord&gt;     
##  1 male   0-17      very.unsat         3 very.unsat
##  2 male   0-17      unsat              9 unsat     
##  3 male   0-17      sat               18 sat       
##  4 male   0-17      very.sat          24 very.sat  
##  5 male   18-24     very.unsat         6 very.unsat
##  6 male   18-24     unsat             13 unsat     
##  7 male   18-24     sat               16 sat       
##  8 male   18-24     very.sat          28 very.sat  
##  9 male   25-30     very.unsat         9 very.unsat
## 10 male   25-30     unsat             13 unsat     
## # … with 22 more rows</code></pre>
<p><code>satis</code> has the same values as <code>satisfied</code>, but its
label <code>ord</code> means that it is an ordered factor, as we want.</p>
<p><span class="math inline">\(\blacksquare\)</span></p>
<ol start="4" style="list-style-type: lower-alpha">
<li><a name="part:thefit">*</a>
Fit ordered logistic models to predict satisfaction from (i) gender
and age group, (ii) gender only, (iii) age group only. (You don’t
need to examine the models.) Don’t forget a suitable
<code>weights</code>!</li>
</ol>
<p>Solution</p>
<p>(i):</p>
<div class="sourceCode" id="cb240"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb240-1" title="1"><span class="kw">library</span>(MASS)</a>
<a class="sourceLine" id="cb240-2" title="2">mobile<span class="fl">.1</span> &lt;-<span class="st"> </span><span class="kw">polr</span>(satis <span class="op">~</span><span class="st"> </span>gender <span class="op">+</span><span class="st"> </span>age.group, <span class="dt">weights =</span> frequency, <span class="dt">data =</span> mobile.long)</a></code></pre></div>
<p>For (ii) and (iii), <code>update</code> is the thing (it works for any
kind of model):</p>
<div class="sourceCode" id="cb241"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb241-1" title="1">mobile<span class="fl">.2</span> &lt;-<span class="st"> </span><span class="kw">update</span>(mobile<span class="fl">.1</span>, . <span class="op">~</span><span class="st"> </span>. <span class="op">-</span><span class="st"> </span>age.group)</a>
<a class="sourceLine" id="cb241-2" title="2">mobile<span class="fl">.3</span> &lt;-<span class="st"> </span><span class="kw">update</span>(mobile<span class="fl">.1</span>, . <span class="op">~</span><span class="st"> </span>. <span class="op">-</span><span class="st"> </span>gender)</a></code></pre></div>
<p>We’re not going to look at these, because the output from
<code>summary</code> is not very illuminating. What we do next is to try
to figure out which (if either) of the explanatory variables
<code>age.group</code> and <code>gender</code> we need.</p>
<p><span class="math inline">\(\blacksquare\)</span></p>
<ol start="5" style="list-style-type: lower-alpha">
<li>Use <code>drop1</code> on your model containing both explanatory
variables to determine whether you can remove either of them. Use
<code>test="Chisq"</code> to obtain P-values.</li>
</ol>
<p>Solution</p>
<p><code>drop1</code> takes a fitted model, and tests each term in
it in turn, and says which (if any) should be removed. Here’s how it goes:</p>
<div class="sourceCode" id="cb242"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb242-1" title="1"><span class="kw">drop1</span>(mobile<span class="fl">.1</span>, <span class="dt">test =</span> <span class="st">&quot;Chisq&quot;</span>)</a></code></pre></div>
<pre><code>## Single term deletions
## 
## Model:
## satis ~ gender + age.group
##           Df    AIC     LRT Pr(&gt;Chi)   
## &lt;none&gt;       1101.8                    
## gender     1 1104.2  4.4089 0.035751 * 
## age.group  3 1109.0 13.1641 0.004295 **
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<p>The possibilities are to remove <code>gender</code>, to remove
<code>age.group</code> or to remove nothing.
The best one is “remove nothing”, because it’s the one on the output with the smallest
AIC. Both P-values are small, so it would be a mistake to remove
either of the explanatory variables.</p>
<p><span class="math inline">\(\blacksquare\)</span></p>
<ol start="6" style="list-style-type: lower-alpha">
<li>Use <code>anova</code> to decide whether we are justified in
removing <code>gender</code> from a model containing both <code>gender</code>
and <code>age.group</code>. Compare your P-value with the one from <code>drop1</code>.</li>
</ol>
<p>Solution</p>
<p>This is a comparison of the model with both variables
(<code>mobile.1</code>) and the model with <code>gender</code> removed
(<code>mobile.3</code>). Use <code>anova</code> for this, smaller
(fewer-<span class="math inline">\(x\)</span>) model first:</p>
<div class="sourceCode" id="cb244"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb244-1" title="1"><span class="kw">anova</span>(mobile<span class="fl">.3</span>, mobile<span class="fl">.1</span>)</a></code></pre></div>
<pre><code>## Likelihood ratio tests of ordinal regression models
## 
## Response: satis
##                Model Resid. df Resid. Dev   Test    Df LR stat.    Pr(Chi)
## 1          age.group       414   1092.213                                 
## 2 gender + age.group       413   1087.804 1 vs 2     1  4.40892 0.03575146</code></pre>
<p>The P-value is (just) less than 0.05, so the models are significantly
different. That means that the model with both variables in fits
significantly better than the model with only <code>age.group</code>, and
therefore that taking <code>gender</code> out is a mistake.</p>
<p>The P-value is identical to the one from <code>drop1</code> (because they
are both doing the same test).</p>
<p><span class="math inline">\(\blacksquare\)</span></p>
<ol start="7" style="list-style-type: lower-alpha">
<li>Use <code>anova</code> to see whether we are justified in removing
<code>age.group</code> from a model containing both <code>gender</code> and
<code>age.group</code>. Compare your P-value with the one from
<code>drop1</code> above.</li>
</ol>
<p>Solution</p>
<p>Exactly the same idea as the last part. In my case, I’m comparing
models <code>mobile.2</code> and <code>mobile.1</code>:</p>
<div class="sourceCode" id="cb246"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb246-1" title="1"><span class="kw">anova</span>(mobile<span class="fl">.2</span>, mobile<span class="fl">.1</span>)</a></code></pre></div>
<pre><code>## Likelihood ratio tests of ordinal regression models
## 
## Response: satis
##                Model Resid. df Resid. Dev   Test    Df LR stat.     Pr(Chi)
## 1             gender       416   1100.968                                  
## 2 gender + age.group       413   1087.804 1 vs 2     3 13.16411 0.004294811</code></pre>
<p>This one is definitely significant, so I need to keep
<code>age.group</code> for sure. Again, the P-value is the same as the one
in <code>drop1</code>.</p>
<p><span class="math inline">\(\blacksquare\)</span></p>
<ol start="8" style="list-style-type: lower-alpha">
<li>Which of the models you have fit so far is the most
appropriate one? Explain briefly.</li>
</ol>
<p>Solution</p>
<p>I can’t drop either of my variables, so I have to keep them both:
<code>mobile.1</code>, with both <code>age.group</code> and <code>gender</code>.</p>
<p><span class="math inline">\(\blacksquare\)</span></p>
<ol style="list-style-type: lower-roman">
<li>Obtain predicted probabilities of a
customer falling in the various satisfaction categories, as it
depends on gender and age group. To do that, you need to feed
<code>predict</code> three things: the fitted model that contains both
age group and gender, the data frame that you read in from the file
back in part (<a href="#part:gather">here</a>) (which contains all the combinations of age group
and gender), and an appropriate <code>type</code>.</li>
</ol>
<p>Solution</p>
<p>My model containing both <span class="math inline">\(x\)</span>s was <code>mobile.1</code>, the data frame
read in from the file was called <code>mobile</code>, and I need
<code>type="p"</code> to get probabilities:</p>
<div class="sourceCode" id="cb248"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb248-1" title="1">probs &lt;-<span class="st"> </span><span class="kw">predict</span>(mobile<span class="fl">.1</span>, mobile, <span class="dt">type =</span> <span class="st">&quot;p&quot;</span>)</a>
<a class="sourceLine" id="cb248-2" title="2">mobile <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb248-3" title="3"><span class="st">  </span><span class="kw">select</span>(gender, age.group) <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb248-4" title="4"><span class="st">  </span><span class="kw">cbind</span>(probs)</a></code></pre></div>
<pre><code>##   gender age.group very.unsat     unsat       sat  very.sat
## 1   male      0-17 0.06070852 0.1420302 0.2752896 0.5219716
## 2   male     18-24 0.09212869 0.1932086 0.3044732 0.4101894
## 3   male     25-30 0.13341018 0.2438110 0.3084506 0.3143283
## 4   male       31+ 0.11667551 0.2252966 0.3097920 0.3482359
## 5 female      0-17 0.08590744 0.1840411 0.3011751 0.4288763
## 6 female     18-24 0.12858414 0.2387296 0.3091489 0.3235374
## 7 female     25-30 0.18290971 0.2853880 0.2920053 0.2396970
## 8 female       31+ 0.16112036 0.2692996 0.3008711 0.2687089</code></pre>
<p>This worked for me, but this might happen to you, with the same commands as above:</p>
<pre><code>## Error in MASS::select(., gender, age.group): unused arguments (gender, age.group)</code></pre>
<p>Oh, this didn’t work. Why not? There don’t seem to be any errors.</p>
<p>This is the kind of thing that can bother you for <em>days</em>. The
resolution (that it took me a long time to discover) is that you might
have the <code>tidyverse</code> <em>and also</em> <code>MASS</code> loaded, in
the wrong order, and <code>MASS</code> also has a <code>select</code> (that
takes different inputs and does something different). If you look back
at part (<a href="#part:thefit">here</a>), you might have seen a message there when you
loaded <code>MASS</code> that <code>select</code> was “masked”. When you
have two packages that both contain a function with the same name, the
one that you can see (and that will get used) is the one that was
loaded <em>last</em>, which is the <code>MASS</code> select (not the one we
actually wanted, which is the <code>tidyverse</code> select). There are a
couple of ways around this. One is to un-load the package we no longer
need (when we no longer need it). The mechanism for this is shown at
the end of part (<a href="#part:unload">here</a>). The other is to say explicitly
which package you want your function to come from, so that there is no
doubt. The <code>tidyverse</code> is actually a collection of
packages. The best way to find out which one our <code>select</code> comes
from is to go to the Console window in R Studio and ask for the help
for <code>select</code>. With both <code>tidyverse</code> and <code>MASS</code>
loaded, the help window offers you a choice of both <code>select</code>s;
the one we want is “select/rename variables by name”, and the actual
package it comes from is <code>dplyr</code>.</p>
<p>There is a third choice, which is the one I prefer now: install and load the package <code>conflicted</code>. When you run your code and it calls for something like <code>select</code> that is in two packages that you have loaded, it gives an error, like this:</p>
<pre><code>Error: [conflicted] `select` found in 2 packages.
Either pick the one you want with `::` 
* MASS::select
* dplyr::select
Or declare a preference with `conflict_prefer()`
* conflict_prefer(&quot;select&quot;, &quot;MASS&quot;)
* conflict_prefer(&quot;select&quot;, &quot;dplyr&quot;)</code></pre>
<p>Fixing this costs you a bit of time upfront, but once you have fixed it, you know that the right thing is being run. What I do is to copy-paste one of those <code>conflict_prefer</code> lines, in this case the second one, and put it <em>before</em> the <code>select</code> that now causes the error. Right after the <code>library(conflicted)</code> is a good place. When you use <code>conflicted</code>, you will probably have to run several times to fix up all the conflicts, which will be a bit frustrating, and you will end up with several <code>conflict_prefer</code> lines, but once you have them there, you won’t have to worry about the right function being called because you have explicitly said which one you want.</p>
<p>This is a non-standard use of <code>cbind</code> because I wanted to grab
only the gender and age group columns from <code>mobile</code> first, and
then <code>cbind</code> <em>that</em> to the predicted probabilities. The
missing first input to <code>cbind</code> is
“whatever came out of the previous step”,
that is, the first two columns of <code>mobile</code>.</p>
<p>I only included the first two columns of <code>mobile</code> in the
<code>cbind</code>, because the rest of the columns of <code>mobile</code>
were frequencies, which I don’t need to see. (Having said that, it
would be interesting to make a <em>plot</em> using the observed
proportions and predicted probabilities, but I didn’t ask you for that.)</p>
<p>This is an unusual <code>predict</code>, because we didn’t have to make a
data frame (with my usual name <code>new</code>) containing all the
combinations of things to predict for. We were lucky enough to have
those already in the original data frame <code>mobile</code>.</p>
<p>The usual way to do this is something like the trick that we did for
getting the different satisfaction levels:</p>
<div class="sourceCode" id="cb252"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb252-1" title="1">genders &lt;-<span class="st"> </span>mobile.long <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">distinct</span>(gender) <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">pluck</span>(<span class="st">&quot;gender&quot;</span>)</a>
<a class="sourceLine" id="cb252-2" title="2">age.groups &lt;-<span class="st"> </span>mobile.long <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb252-3" title="3"><span class="st">  </span><span class="kw">distinct</span>(age.group) <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb252-4" title="4"><span class="st">  </span><span class="kw">pluck</span>(<span class="st">&quot;age.group&quot;</span>)</a></code></pre></div>
<p>This is getting perilously close to deserving a function written to do
it (strictly speaking, we should, since this is three times we’ve
used this idea now).</p>
<p>Then <code>crossing</code> to get the combinations, and then
<code>predict</code>:</p>
<div class="sourceCode" id="cb253"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb253-1" title="1">new &lt;-<span class="st"> </span><span class="kw">crossing</span>(<span class="dt">gender =</span> genders, <span class="dt">age.group =</span> age.groups)</a>
<a class="sourceLine" id="cb253-2" title="2">new</a></code></pre></div>
<pre><code>## # A tibble: 8 x 2
##   gender age.group
##   &lt;chr&gt;  &lt;chr&gt;    
## 1 female 0-17     
## 2 female 18-24    
## 3 female 25-30    
## 4 female 31+      
## 5 male   0-17     
## 6 male   18-24    
## 7 male   25-30    
## 8 male   31+</code></pre>
<div class="sourceCode" id="cb255"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb255-1" title="1">pp &lt;-<span class="st"> </span><span class="kw">predict</span>(mobile<span class="fl">.1</span>, new, <span class="dt">type =</span> <span class="st">&quot;p&quot;</span>)</a>
<a class="sourceLine" id="cb255-2" title="2"><span class="kw">cbind</span>(new, pp)</a></code></pre></div>
<pre><code>##   gender age.group very.unsat     unsat       sat  very.sat
## 1 female      0-17 0.08590744 0.1840411 0.3011751 0.4288763
## 2 female     18-24 0.12858414 0.2387296 0.3091489 0.3235374
## 3 female     25-30 0.18290971 0.2853880 0.2920053 0.2396970
## 4 female       31+ 0.16112036 0.2692996 0.3008711 0.2687089
## 5   male      0-17 0.06070852 0.1420302 0.2752896 0.5219716
## 6   male     18-24 0.09212869 0.1932086 0.3044732 0.4101894
## 7   male     25-30 0.13341018 0.2438110 0.3084506 0.3143283
## 8   male       31+ 0.11667551 0.2252966 0.3097920 0.3482359</code></pre>
<p>This method is fine if you want to do this
question this way; the way I suggested first ought to be easier, but
the nice thing about this is its mindlessness: you always do it about
the same way.</p>
<p><span class="math inline">\(\blacksquare\)</span></p>
<ol start="10" style="list-style-type: lower-alpha">
<li><a name="part:unload">*</a>
Describe any patterns you see in the predictions, bearing in mind the
significance or not of the explanatory variables.</li>
</ol>
<p>Solution</p>
<p>I had both explanatory variables being significant, so I would
expect to see both an age-group effect <em>and</em> a gender effect.
For both males and females, there seems to be a decrease in
satisfaction as the customers get older, at least until age 30 or
so. I can see this because the predicted prob. of “very satisfied”
decreases, and the predicted prob.
of “very unsatisfied” increases. The 31+ age group are very
similar to the 25–30 group for both males and females. So that’s
the age group effect.
What about a gender effect? Well, for all the age groups, the males
are more likely to be very satisfied than the females of the
corresponding age group, and also less likely to to be very
unsatisfied. So the gender effect is that males are more satisfied
than females overall. (Or, the males are less discerning. Take your pick.)
When we did the tests above, age group was very definitely
significant, and gender less so (P-value around 0.03). This
suggests that the effect of age group ought to be large, and the
effect of gender not so large. This is about what we observed: the
age group effect was pretty clear, and the gender effect was
noticeable but small: the females were less satisfied than the
males, but there wasn’t all that much difference.</p>
<p><span class="math inline">\(\blacksquare\)</span></p>
</div>
<div id="finding-non-missing-values-1" class="section level2">
<h2><span class="header-section-number">27.7</span> Finding non-missing values</h2>
<p><a name="part:prepare-next">*</a> This is to prepare you for something in the next
question. It’s meant to be easy.</p>
<p>In R, the code <code>NA</code> stands for “missing value” or
“value not known”. In R, <code>NA</code> should not have quotes around
it. (It is a special code, not a piece of text.)</p>
<ol style="list-style-type: lower-alpha">
<li>Create a vector <code>v</code> that contains some numbers and some
missing values, using <code>c()</code>. Put those values into a
one-column data frame.</li>
</ol>
<p>Solution</p>
<p>Like this. The arrangement of numbers and missing values doesn’t
matter, as long as you have some of each:</p>
<div class="sourceCode" id="cb257"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb257-1" title="1">v &lt;-<span class="st"> </span><span class="kw">c</span>(<span class="dv">1</span>, <span class="dv">2</span>, <span class="ot">NA</span>, <span class="dv">4</span>, <span class="dv">5</span>, <span class="dv">6</span>, <span class="dv">9</span>, <span class="ot">NA</span>, <span class="dv">11</span>)</a>
<a class="sourceLine" id="cb257-2" title="2">mydata &lt;-<span class="st"> </span><span class="kw">tibble</span>(v)</a>
<a class="sourceLine" id="cb257-3" title="3">mydata</a></code></pre></div>
<pre><code>## # A tibble: 9 x 1
##       v
##   &lt;dbl&gt;
## 1     1
## 2     2
## 3    NA
## 4     4
## 5     5
## 6     6
## 7     9
## 8    NA
## 9    11</code></pre>
<p>This has one column called <code>v</code>.</p>
<p><span class="math inline">\(\blacksquare\)</span></p>
<ol start="2" style="list-style-type: lower-alpha">
<li>Obtain a new column containing <code>is.na(v)</code>. When is this true and when is this false?</li>
</ol>
<p>Solution</p>
<div class="sourceCode" id="cb259"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb259-1" title="1">mydata &lt;-<span class="st"> </span>mydata <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">mutate</span>(<span class="dt">isna =</span> <span class="kw">is.na</span>(v))</a>
<a class="sourceLine" id="cb259-2" title="2">mydata</a></code></pre></div>
<pre><code>## # A tibble: 9 x 2
##       v isna 
##   &lt;dbl&gt; &lt;lgl&gt;
## 1     1 FALSE
## 2     2 FALSE
## 3    NA TRUE 
## 4     4 FALSE
## 5     5 FALSE
## 6     6 FALSE
## 7     9 FALSE
## 8    NA TRUE 
## 9    11 FALSE</code></pre>
<p>This is <code>TRUE</code> if the corresponding element of <code>v</code> is
missing (in my case, the third value and the second-last one), and
<code>FALSE</code> otherwise (when there is an actual value there).</p>
<p><span class="math inline">\(\blacksquare\)</span></p>
<ol start="3" style="list-style-type: lower-alpha">
<li>The symbol <code>!</code> means “not” in R (and other
programming languages). What does <code>!is.na(v)</code> do? Create a
new column containing that.</li>
</ol>
<p>Solution</p>
<p>Try it and see. Give it whatever name you like. My name reflects
that I know what it’s going to do:</p>
<div class="sourceCode" id="cb261"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb261-1" title="1">mydata &lt;-<span class="st"> </span>mydata <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">mutate</span>(<span class="dt">notisna =</span> <span class="op">!</span><span class="kw">is.na</span>(v))</a>
<a class="sourceLine" id="cb261-2" title="2">mydata</a></code></pre></div>
<pre><code>## # A tibble: 9 x 3
##       v isna  notisna
##   &lt;dbl&gt; &lt;lgl&gt; &lt;lgl&gt;  
## 1     1 FALSE TRUE   
## 2     2 FALSE TRUE   
## 3    NA TRUE  FALSE  
## 4     4 FALSE TRUE   
## 5     5 FALSE TRUE   
## 6     6 FALSE TRUE   
## 7     9 FALSE TRUE   
## 8    NA TRUE  FALSE  
## 9    11 FALSE TRUE</code></pre>
<p>This is the logical opposite of <code>is.na</code>: it’s true if there is
a value, and false if it’s missing.</p>
<p><span class="math inline">\(\blacksquare\)</span></p>
<ol start="4" style="list-style-type: lower-alpha">
<li>Use <code>filter</code> to display just the
rows of your data frame that have a non-missing value of <code>v</code>.</li>
</ol>
<p>Solution</p>
<p><code>filter</code> takes a column to say which rows to pick, in
which case the column should contain something that either <em>is</em>
<code>TRUE</code> or <code>FALSE</code>, or something that can be
interpreted that way:</p>
<div class="sourceCode" id="cb263"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb263-1" title="1">mydata <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">filter</span>(notisna)</a></code></pre></div>
<pre><code>## # A tibble: 7 x 3
##       v isna  notisna
##   &lt;dbl&gt; &lt;lgl&gt; &lt;lgl&gt;  
## 1     1 FALSE TRUE   
## 2     2 FALSE TRUE   
## 3     4 FALSE TRUE   
## 4     5 FALSE TRUE   
## 5     6 FALSE TRUE   
## 6     9 FALSE TRUE   
## 7    11 FALSE TRUE</code></pre>
<p>or you can provide <code>filter</code> something that can be calculated
from what’s in the data frame, and also returns something that is
either true or false:</p>
<div class="sourceCode" id="cb265"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb265-1" title="1">mydata <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">filter</span>(<span class="op">!</span><span class="kw">is.na</span>(v))</a></code></pre></div>
<pre><code>## # A tibble: 7 x 3
##       v isna  notisna
##   &lt;dbl&gt; &lt;lgl&gt; &lt;lgl&gt;  
## 1     1 FALSE TRUE   
## 2     2 FALSE TRUE   
## 3     4 FALSE TRUE   
## 4     5 FALSE TRUE   
## 5     6 FALSE TRUE   
## 6     9 FALSE TRUE   
## 7    11 FALSE TRUE</code></pre>
<p>In either case, I only have non-missing values of <code>v</code>.</p>
<p><span class="math inline">\(\blacksquare\)</span></p>
</div>
<div id="high-school-and-beyond-1" class="section level2">
<h2><span class="header-section-number">27.8</span> High School and Beyond</h2>
<p>A survey called High School and Beyond was given to a large
number of American high school seniors (grade 12) by the National
Center of Education Statistics. The data set at
<a href="http://ritsokiguess.site/datafiles/hsb.csv">link</a> is a random
sample of 200 of those students.</p>
<p>The variables collected are:</p>
<ul>
<li><p><code>gender</code>: student’s gender, female or male.</p></li>
<li><p><code>race</code>: the student’s race (African-American,
Asian,<a href="#fn37" class="footnote-ref" id="fnref37"><sup>37</sup></a> Hispanic, White).</p></li>
<li><p><code>ses</code>: Socio-economic status of student’s family (low,
middle, or high)</p></li>
<li><p><code>schtyp</code>: School type, public or private.</p></li>
<li><p><code>prog</code>: Student’s program, general, academic, or
vocational.</p></li>
<li><p><code>read</code>: Score on standardized reading test.</p></li>
<li><p><code>write</code>: Score on standardized writing test.</p></li>
<li><p><code>math</code>: Score on standardized math test.</p></li>
<li><p><code>science</code>: Score on standardized science test.</p></li>
<li><p><code>socst</code>: Score on standardized social studies test.</p></li>
</ul>
<p>Our aim is to see how socio-economic status is related to the other
variables.</p>
<ol style="list-style-type: lower-alpha">
<li>Read in and display (some of) the data.</li>
</ol>
<p>Solution</p>
<p>This is a <code>.csv</code> file (I tried to make it easy for you):</p>
<div class="sourceCode" id="cb267"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb267-1" title="1">my_url &lt;-<span class="st"> &quot;http://ritsokiguess.site/datafiles/hsb.csv&quot;</span></a>
<a class="sourceLine" id="cb267-2" title="2">hsb &lt;-<span class="st"> </span><span class="kw">read_csv</span>(my_url)</a></code></pre></div>
<pre><code>## 
## ── Column specification ──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
## cols(
##   id = col_double(),
##   race = col_character(),
##   ses = col_character(),
##   schtyp = col_character(),
##   prog = col_character(),
##   read = col_double(),
##   write = col_double(),
##   math = col_double(),
##   science = col_double(),
##   socst = col_double(),
##   gender = col_character()
## )</code></pre>
<div class="sourceCode" id="cb269"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb269-1" title="1">hsb</a></code></pre></div>
<pre><code>## # A tibble: 200 x 11
##       id race       ses   schtyp prog      read write  math science socst gender
##    &lt;dbl&gt; &lt;chr&gt;      &lt;chr&gt; &lt;chr&gt;  &lt;chr&gt;    &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt;   &lt;dbl&gt; &lt;dbl&gt; &lt;chr&gt; 
##  1    70 white      low   public general     57    52    41      47    57 male  
##  2   121 white      midd… public vocatio…    68    59    53      63    61 female
##  3    86 white      high  public general     44    33    54      58    31 male  
##  4   141 white      high  public vocatio…    63    44    47      53    56 male  
##  5   172 white      midd… public academic    47    52    57      53    61 male  
##  6   113 white      midd… public academic    44    52    51      63    61 male  
##  7    50 african-a… midd… public general     50    59    42      53    61 male  
##  8    11 hispanic   midd… public academic    34    46    45      39    36 male  
##  9    84 white      midd… public general     63    57    54      58    51 male  
## 10    48 african-a… midd… public academic    57    55    52      50    51 male  
## # … with 190 more rows</code></pre>
<p><span class="math inline">\(\blacksquare\)</span></p>
<ol start="2" style="list-style-type: lower-alpha">
<li>Explain briefly why an ordinal logistic regression is
appropriate for our aims.</li>
</ol>
<p>Solution</p>
<p>The response variable <code>ses</code> is categorical, with
categories that come in order (low less than middle less than
high).</p>
<p><span class="math inline">\(\blacksquare\)</span></p>
<ol start="3" style="list-style-type: lower-alpha">
<li>Fit an ordinal logistic regression predicting
socio-economic status from the scores on the five standardized
tests. (You don’t need to display the results.) You will probably
go wrong the first time. What kind of thing does your response
variable have to be?</li>
</ol>
<p>Solution</p>
<p>It has to be an <code>ordered</code> factor, which you can create in
the data frame (or outside, if you prefer):</p>
<div class="sourceCode" id="cb271"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb271-1" title="1">hsb &lt;-<span class="st"> </span>hsb <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">mutate</span>(<span class="dt">ses =</span> <span class="kw">ordered</span>(ses, <span class="kw">c</span>(<span class="st">&quot;low&quot;</span>, <span class="st">&quot;middle&quot;</span>, <span class="st">&quot;high&quot;</span>)))</a>
<a class="sourceLine" id="cb271-2" title="2">hsb</a></code></pre></div>
<pre><code>## # A tibble: 200 x 11
##       id race       ses   schtyp prog      read write  math science socst gender
##    &lt;dbl&gt; &lt;chr&gt;      &lt;ord&gt; &lt;chr&gt;  &lt;chr&gt;    &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt;   &lt;dbl&gt; &lt;dbl&gt; &lt;chr&gt; 
##  1    70 white      low   public general     57    52    41      47    57 male  
##  2   121 white      midd… public vocatio…    68    59    53      63    61 female
##  3    86 white      high  public general     44    33    54      58    31 male  
##  4   141 white      high  public vocatio…    63    44    47      53    56 male  
##  5   172 white      midd… public academic    47    52    57      53    61 male  
##  6   113 white      midd… public academic    44    52    51      63    61 male  
##  7    50 african-a… midd… public general     50    59    42      53    61 male  
##  8    11 hispanic   midd… public academic    34    46    45      39    36 male  
##  9    84 white      midd… public general     63    57    54      58    51 male  
## 10    48 african-a… midd… public academic    57    55    52      50    51 male  
## # … with 190 more rows</code></pre>
<p><code>ses</code> is now <code>ord</code>. Good. Now fit the model:</p>
<div class="sourceCode" id="cb273"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb273-1" title="1">ses<span class="fl">.1</span> &lt;-<span class="st"> </span><span class="kw">polr</span>(ses <span class="op">~</span><span class="st"> </span>read <span class="op">+</span><span class="st"> </span>write <span class="op">+</span><span class="st"> </span>math <span class="op">+</span><span class="st"> </span>science <span class="op">+</span><span class="st"> </span>socst, <span class="dt">data =</span> hsb)</a></code></pre></div>
<p>No errors is good.</p>
<p><span class="math inline">\(\blacksquare\)</span></p>
<ol start="4" style="list-style-type: lower-alpha">
<li>Remove any non-significant explanatory variables one at a
time. Use <code>drop1</code> to decide which one to remove next.</li>
</ol>
<p>Solution</p>
<div class="sourceCode" id="cb274"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb274-1" title="1"><span class="kw">drop1</span>(ses<span class="fl">.1</span>, <span class="dt">test =</span> <span class="st">&quot;Chisq&quot;</span>)</a></code></pre></div>
<pre><code>## Single term deletions
## 
## Model:
## ses ~ read + write + math + science + socst
##         Df    AIC    LRT Pr(&gt;Chi)   
## &lt;none&gt;     404.63                   
## read     1 403.09 0.4620 0.496684   
## write    1 403.81 1.1859 0.276167   
## math     1 403.19 0.5618 0.453517   
## science  1 404.89 2.2630 0.132499   
## socst    1 410.08 7.4484 0.006349 **
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<p>I would have expected the AIC column to come out in order, but it
doesn’t. Never mind. Scan for the largest P-value, which belongs to
<code>read</code>. (This also has the lowest AIC.) So, remove <code>read</code>:</p>
<div class="sourceCode" id="cb276"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb276-1" title="1">ses<span class="fl">.2</span> &lt;-<span class="st"> </span><span class="kw">update</span>(ses<span class="fl">.1</span>, . <span class="op">~</span><span class="st"> </span>. <span class="op">-</span><span class="st"> </span>read)</a>
<a class="sourceLine" id="cb276-2" title="2"><span class="kw">drop1</span>(ses<span class="fl">.2</span>, <span class="dt">test =</span> <span class="st">&quot;Chisq&quot;</span>)</a></code></pre></div>
<pre><code>## Single term deletions
## 
## Model:
## ses ~ write + math + science + socst
##         Df    AIC    LRT Pr(&gt;Chi)   
## &lt;none&gt;     403.09                   
## write    1 402.10 1.0124 0.314325   
## math     1 402.04 0.9541 0.328689   
## science  1 404.29 3.1968 0.073782 . 
## socst    1 410.58 9.4856 0.002071 **
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<p>Note how the P-value for <code>science</code> has come down a long way.</p>
<p>A close call, but <code>math</code> goes next. The <code>update</code>
doesn’t take long to type:</p>
<div class="sourceCode" id="cb278"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb278-1" title="1">ses<span class="fl">.3</span> &lt;-<span class="st"> </span><span class="kw">update</span>(ses<span class="fl">.2</span>, . <span class="op">~</span><span class="st"> </span>. <span class="op">-</span><span class="st"> </span>math)</a>
<a class="sourceLine" id="cb278-2" title="2"><span class="kw">drop1</span>(ses<span class="fl">.3</span>, <span class="dt">test =</span> <span class="st">&quot;Chisq&quot;</span>)</a></code></pre></div>
<pre><code>## Single term deletions
## 
## Model:
## ses ~ write + science + socst
##         Df    AIC     LRT  Pr(&gt;Chi)    
## &lt;none&gt;     402.04                      
## write    1 400.60  0.5587 0.4547813    
## science  1 405.41  5.3680 0.0205095 *  
## socst    1 411.07 11.0235 0.0008997 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<p><code>science</code> has become significant now (probably because it was
strongly correlated with at least one of the variables we removed (at
my guess, <code>math</code>). That is, we didn’t need both
<code>science</code> and <code>math</code>, but we <em>do</em> need <em>one</em> of
them.</p>
<p>I think we can guess what will happen now: <code>write</code> comes out,
and the other two variables will stay, so that’ll be where we stop:</p>
<div class="sourceCode" id="cb280"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb280-1" title="1">ses<span class="fl">.4</span> &lt;-<span class="st"> </span><span class="kw">update</span>(ses<span class="fl">.3</span>, . <span class="op">~</span><span class="st"> </span>. <span class="op">-</span><span class="st"> </span>write)</a>
<a class="sourceLine" id="cb280-2" title="2"><span class="kw">drop1</span>(ses<span class="fl">.4</span>, <span class="dt">test =</span> <span class="st">&quot;Chisq&quot;</span>)</a></code></pre></div>
<pre><code>## Single term deletions
## 
## Model:
## ses ~ science + socst
##         Df    AIC     LRT  Pr(&gt;Chi)    
## &lt;none&gt;     400.60                      
## science  1 403.45  4.8511 0.0276291 *  
## socst    1 409.74 11.1412 0.0008443 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<p>Indeed so. We need just the science and social studies test scores to
predict socio-economic status.</p>
<p>Using AIC to decide on which variable to remove next will give the
same answer here, but I would like to see the <code>test=</code> part in
your <code>drop1</code> to give P-values (expect to lose something, but
not too much, if that’s not there).</p>
<p>Extras: I talked about correlation among the explanatory variables
earlier, which I can explore:</p>
<div class="sourceCode" id="cb282"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb282-1" title="1">hsb <span class="op">%&gt;%</span><span class="st"> </span>dplyr<span class="op">::</span><span class="kw">select</span>(read<span class="op">:</span>socst) <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">cor</span>()</a></code></pre></div>
<pre><code>##              read     write      math   science     socst
## read    1.0000000 0.5967765 0.6622801 0.6301579 0.6214843
## write   0.5967765 1.0000000 0.6174493 0.5704416 0.6047932
## math    0.6622801 0.6174493 1.0000000 0.6307332 0.5444803
## science 0.6301579 0.5704416 0.6307332 1.0000000 0.4651060
## socst   0.6214843 0.6047932 0.5444803 0.4651060 1.0000000</code></pre>
<p>The first time I did this, I forgot that I had <code>MASS</code> loaded
(for the <code>polr</code>), and so, to get the right <code>select</code>, I
needed to say which one I wanted.</p>
<p>Anyway, the correlations are all moderately high. There’s nothing that
stands out as being much higher than the others. The lowest two are
between social studies and math, and social studies and science. That
would be part of the reason that social studies needs to stay. The
highest correlation is between math and reading, which surprises me
(they seem to be different skills).</p>
<p>So there was not as much insight there as I expected.</p>
<p>The other thing is that you can use <code>step</code> for the
variable-elimination task as well:</p>
<div class="sourceCode" id="cb284"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb284-1" title="1">ses<span class="fl">.5</span> &lt;-<span class="st"> </span><span class="kw">step</span>(ses<span class="fl">.1</span>, <span class="dt">direction =</span> <span class="st">&quot;backward&quot;</span>, <span class="dt">test =</span> <span class="st">&quot;Chisq&quot;</span>)</a></code></pre></div>
<pre><code>## Start:  AIC=404.63
## ses ~ read + write + math + science + socst
## 
##           Df    AIC    LRT Pr(&gt;Chi)   
## - read     1 403.09 0.4620 0.496684   
## - math     1 403.19 0.5618 0.453517   
## - write    1 403.81 1.1859 0.276167   
## &lt;none&gt;       404.63                   
## - science  1 404.89 2.2630 0.132499   
## - socst    1 410.08 7.4484 0.006349 **
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Step:  AIC=403.09
## ses ~ write + math + science + socst
## 
##           Df    AIC    LRT Pr(&gt;Chi)   
## - math     1 402.04 0.9541 0.328689   
## - write    1 402.10 1.0124 0.314325   
## &lt;none&gt;       403.09                   
## - science  1 404.29 3.1968 0.073782 . 
## - socst    1 410.58 9.4856 0.002071 **
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Step:  AIC=402.04
## ses ~ write + science + socst
## 
##           Df    AIC     LRT  Pr(&gt;Chi)    
## - write    1 400.60  0.5587 0.4547813    
## &lt;none&gt;       402.04                      
## - science  1 405.41  5.3680 0.0205095 *  
## - socst    1 411.07 11.0235 0.0008997 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Step:  AIC=400.6
## ses ~ science + socst
## 
##           Df    AIC     LRT  Pr(&gt;Chi)    
## &lt;none&gt;       400.60                      
## - science  1 403.45  4.8511 0.0276291 *  
## - socst    1 409.74 11.1412 0.0008443 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<p>I would accept you doing it this way, again <em>as long as you have
the <code>test=</code> there as well</em>.</p>
<p><span class="math inline">\(\blacksquare\)</span></p>
<ol start="5" style="list-style-type: lower-alpha">
<li>The quartiles of the <code>science</code> test score are 44
and 58. The quartiles of the <code>socst</code> test score are 46 and 61. Make
a data frame that has all combinations of those quartiles. If your best
regression had any other explanatory variables in it, also put the
<em>medians</em> of those variables into this data frame.</li>
</ol>
<p>Solution</p>
<p>Thus, most obviously:</p>
<div class="sourceCode" id="cb286"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb286-1" title="1">sciences &lt;-<span class="st"> </span><span class="kw">c</span>(<span class="dv">44</span>, <span class="dv">58</span>)</a>
<a class="sourceLine" id="cb286-2" title="2">socsts &lt;-<span class="st"> </span><span class="kw">c</span>(<span class="dv">46</span>, <span class="dv">61</span>)</a>
<a class="sourceLine" id="cb286-3" title="3">new &lt;-<span class="st"> </span><span class="kw">crossing</span>(<span class="dt">science =</span> sciences, <span class="dt">socst =</span> socsts)</a>
<a class="sourceLine" id="cb286-4" title="4">new</a></code></pre></div>
<pre><code>## # A tibble: 4 x 2
##   science socst
##     &lt;dbl&gt; &lt;dbl&gt;
## 1      44    46
## 2      44    61
## 3      58    46
## 4      58    61</code></pre>
<p>Since there are only two variables left, this new data frame has only
<span class="math inline">\(2^2=4\)</span> rows.</p>
<p>There is a veiled hint here that these are the two variables that
should have remained in your regression. If that was not what you got,
find the median of any other variables you had, and put that into your
<code>new</code>. For example, if you still had <code>math</code>, you’d do
this:<a href="#fn38" class="footnote-ref" id="fnref38"><sup>38</sup></a></p>
<div class="sourceCode" id="cb288"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb288-1" title="1">hsb <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">summarize</span>(<span class="dt">m =</span> <span class="kw">median</span>(math))</a></code></pre></div>
<pre><code>## # A tibble: 1 x 1
##       m
##   &lt;dbl&gt;
## 1    52</code></pre>
<div class="sourceCode" id="cb290"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb290-1" title="1">maths &lt;-<span class="st"> </span><span class="dv">52</span></a>
<a class="sourceLine" id="cb290-2" title="2">new2 &lt;-<span class="st"> </span><span class="kw">crossing</span>(<span class="dt">science =</span> sciences, <span class="dt">socst =</span> socsts, <span class="dt">math =</span> maths)</a>
<a class="sourceLine" id="cb290-3" title="3">new2</a></code></pre></div>
<pre><code>## # A tibble: 4 x 3
##   science socst  math
##     &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt;
## 1      44    46    52
## 2      44    61    52
## 3      58    46    52
## 4      58    61    52</code></pre>
<p><span class="math inline">\(\blacksquare\)</span></p>
<ol start="6" style="list-style-type: lower-alpha">
<li>Use the data frame you created in the previous part, together
with your best model, to obtain predicted probabilities of being in
each <code>ses</code> category.</li>
</ol>
<p>Solution</p>
<p>This is <code>predict</code>, and we’ve done the setup. My best model
was called <code>ses.4</code>:</p>
<div class="sourceCode" id="cb292"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb292-1" title="1">p &lt;-<span class="st"> </span><span class="kw">predict</span>(ses<span class="fl">.4</span>, new, <span class="dt">type =</span> <span class="st">&quot;probs&quot;</span>)</a>
<a class="sourceLine" id="cb292-2" title="2"><span class="kw">cbind</span>(new, p)</a></code></pre></div>
<pre><code>##   science socst       low    middle      high
## 1      44    46 0.3262510 0.5056113 0.1681377
## 2      44    61 0.1885566 0.5150763 0.2963671
## 3      58    46 0.2278105 0.5230783 0.2491112
## 4      58    61 0.1240155 0.4672338 0.4087507</code></pre>
<p>If you forgot which <code>type</code> to use, guess one that’s obviously
wrong, and it will tell you what your options are. That ought to be
enough to trigger your memory of the right thing.</p>
<p>If you get the <code>type</code> right, but the <code>predict</code> still
doesn’t work, check the construction of your <code>new</code> data frame
very carefully. That’s likely where your problem is.</p>
<p><span class="math inline">\(\blacksquare\)</span></p>
<ol start="7" style="list-style-type: lower-alpha">
<li>What is the effect of an increased science score on the
likelihood of a student being in the different socioeconomic groups,
all else equal? Explain briefly. In your explanation, state clearly
how you are using your answer to the previous part.</li>
</ol>
<p>Solution</p>
<p>Use your predictions; hold the <code>socst</code> score constant (that’s
the all else equal part). So compare the first and third rows (or,
if you like, the second and fourth rows) of your predictions and see
what happens as the science score goes from 44 to 58.
What I see is that the probability of being <code>low</code> goes
noticeably <em>down</em> as the science score increases, the
probability of <code>middle</code> stays about the same, and the
probability of <code>high</code> goes <code>up</code> (by about the same
amount as the probability of <code>low</code> went down).
In other words, an increased science score goes with an increased
chance of <code>high</code> (and a decreased chance of <code>low</code>).
If your best model doesn’t have <code>science</code> in it, then you
need to say something like “<code>science</code> has no effect on socio-economic status”,
consistent with what you concluded before: if
you took it out, it’s because you thought it had no effect.
Extra: the effect of an increased social studies score is almost
exactly the same as an increased science score (so I didn’t ask you
about that). From a social-science point of view, this makes
perfect sense: the higher the social-economic stratum a student
comes from, the better they are likely to do in school.
I’ve been phrasing this as “association”, because really the cause
and effect is the other way around: a student’s family socioeconomic
status is explanatory, and school performance is response. But this
was the nicest example I could find of an ordinal response data set.</p>
<p><span class="math inline">\(\blacksquare\)</span></p>
</div>
<div id="how-do-you-like-your-steak-1" class="section level2">
<h2><span class="header-section-number">27.9</span> How do you like your steak?</h2>
<p>When you order a steak in a restaurant, the server will ask
you how you would like it cooked, or to be precise, <em>how much</em>
you would like it cooked: rare (hardly cooked at all), through medium
rare, medium, medium well to well (which means “well done”, so that
the meat has only a little red to it). Could you guess how a person
likes their steak cooked, from some other information about them? The
website <a href="fivethirtyeight.com">link</a> commissioned a survey where they
asked a number of people how they preferred their steak, along with as
many other things as they could think of to ask. (Many of the
variables below are related to risk-taking, which was something the
people designing the survey thought might have something to do with
liking steak rare.) The variables of interest are all factors or true/false:</p>
<ul>
<li><p><code>respondent_ID</code>: a ten-digit number identifying each
person who responded to the survey.</p></li>
<li><p><code>lottery_a</code>: true if the respondent preferred lottery A
with a small chance to win a lot of money, to lottery B, with a
larger chance to win less money.</p></li>
<li><p><code>smoke</code>: true if the respondent is currently a smoker</p></li>
<li><p><code>alcohol</code>: true if the respondent at least occasionally
drinks alcohol.</p></li>
<li><p><code>gamble</code>: true if the respondent likes to gamble (eg.
betting on horse racing or playing the lottery)</p></li>
<li><p><code>skydiving</code>: true if the respondent has ever been
skydiving.</p></li>
<li><p><code>speed</code>: true if the respondent likes to drive fast</p></li>
<li><p><code>cheated</code>: true if the respondent has ever cheated on a
spouse or girlfriend/boyfriend</p></li>
<li><p><code>steak</code>: true if the respondent likes to eat steak</p></li>
<li><p><code>steak_prep</code> (response): how the respondent likes their
steak cooked (factor, as described above, with 5 levels).</p></li>
<li><p><code>female</code>: true if the respondent is female</p></li>
<li><p><code>age</code>: age group, from 18–29 to 60+.</p></li>
<li><p><code>hhold_income</code>: household income group, from $0–24,999
to $150,000+.</p></li>
<li><p><code>educ</code>: highest level of education attained, from
“less than high school” up to “graduate degree”</p></li>
<li><p><code>region</code>: region (of the US)
that the respondent lives in (five values).</p></li>
</ul>
<p>The data are in
<a href="http://ritsokiguess.site/datafiles/steak1.csv">link</a>. This is the
cleaned-up data from a previous question, with the missing values removed.</p>
<ol style="list-style-type: lower-alpha">
<li>Read in the data and display the first few lines.</li>
</ol>
<p>Solution</p>
<p>The usual:</p>
<div class="sourceCode" id="cb294"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb294-1" title="1">steak &lt;-<span class="st"> </span><span class="kw">read_csv</span>(<span class="st">&quot;steak1.csv&quot;</span>)</a></code></pre></div>
<pre><code>## 
## ── Column specification ──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
## cols(
##   respondent_id = col_double(),
##   lottery_a = col_logical(),
##   smoke = col_logical(),
##   alcohol = col_logical(),
##   gamble = col_logical(),
##   skydiving = col_logical(),
##   speed = col_logical(),
##   cheated = col_logical(),
##   steak = col_logical(),
##   steak_prep = col_character(),
##   female = col_logical(),
##   age = col_character(),
##   hhold_income = col_character(),
##   educ = col_character(),
##   region = col_character()
## )</code></pre>
<div class="sourceCode" id="cb296"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb296-1" title="1"><span class="kw">head</span>(steak)</a></code></pre></div>
<pre><code>## # A tibble: 6 x 15
##   respondent_id lottery_a smoke alcohol gamble skydiving speed cheated steak
##           &lt;dbl&gt; &lt;lgl&gt;     &lt;lgl&gt; &lt;lgl&gt;   &lt;lgl&gt;  &lt;lgl&gt;     &lt;lgl&gt; &lt;lgl&gt;   &lt;lgl&gt;
## 1    3234982343 TRUE      FALSE TRUE    FALSE  FALSE     FALSE FALSE   TRUE 
## 2    3234973379 TRUE      FALSE TRUE    TRUE   FALSE     TRUE  TRUE    TRUE 
## 3    3234972383 FALSE     TRUE  TRUE    TRUE   FALSE     TRUE  TRUE    TRUE 
## 4    3234958833 FALSE     FALSE TRUE    FALSE  FALSE     TRUE  TRUE    TRUE 
## 5    3234955240 TRUE      FALSE FALSE   FALSE  FALSE     TRUE  FALSE   TRUE 
## 6    3234955010 TRUE      FALSE TRUE    TRUE   TRUE      TRUE  FALSE   TRUE 
## # … with 6 more variables: steak_prep &lt;chr&gt;, female &lt;lgl&gt;, age &lt;chr&gt;,
## #   hhold_income &lt;chr&gt;, educ &lt;chr&gt;, region &lt;chr&gt;</code></pre>
<p>We should also (re-)load <code>MASS</code>, since we’ll be needing it:</p>
<div class="sourceCode" id="cb298"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb298-1" title="1"><span class="kw">library</span>(MASS)</a></code></pre></div>
<p><span class="math inline">\(\blacksquare\)</span></p>
<ol start="2" style="list-style-type: lower-alpha">
<li>We are going to predict <code>steak_prep</code> from some of
the other variables. Why is the model-fitting function <code>polr</code>
from package <code>MASS</code> the best choice for these data
(alternatives being <code>glm</code> and <code>multinom</code> from package
<code>nnet</code>)?</li>
</ol>
<p>Solution</p>
<p>It all depends on the kind of response variable. We have a
response variable with five ordered levels from Rare to
Well. There are more than two levels (it is more than a
“success” and “failure”), which rules out <code>glm</code>, and
the levels are ordered, which rules out <code>multinom</code>. As we
know, <code>polr</code> handles an ordered response, so it is the
right choice.</p>
<p><span class="math inline">\(\blacksquare\)</span></p>
<ol start="3" style="list-style-type: lower-alpha">
<li>What are the levels of <code>steak_prep</code>,
<em>in the order that R thinks they are in?</em> If they are not in a sensible
order, create an ordered factor where the levels are in a sensible order.</li>
</ol>
<p>Solution</p>
<p>This is the most direct way to find out:</p>
<div class="sourceCode" id="cb299"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb299-1" title="1">preps &lt;-<span class="st"> </span>steak <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">distinct</span>(steak_prep) <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">pull</span>(steak_prep)</a>
<a class="sourceLine" id="cb299-2" title="2">preps</a></code></pre></div>
<pre><code>## [1] &quot;Medium rare&quot; &quot;Rare&quot;        &quot;Medium&quot;      &quot;Medium Well&quot; &quot;Well&quot;</code></pre>
<p>This is almost the right order (<code>distinct</code> uses the order in
the data frame). We just need to switch the first two around, and then
we’ll be done:</p>
<div class="sourceCode" id="cb301"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb301-1" title="1">preps1 &lt;-<span class="st"> </span>preps[<span class="kw">c</span>(<span class="dv">2</span>, <span class="dv">1</span>, <span class="dv">3</span>, <span class="dv">4</span>, <span class="dv">5</span>)]</a>
<a class="sourceLine" id="cb301-2" title="2">preps1</a></code></pre></div>
<pre><code>## [1] &quot;Rare&quot;        &quot;Medium rare&quot; &quot;Medium&quot;      &quot;Medium Well&quot; &quot;Well&quot;</code></pre>
<p>If you used <code>count</code>, there’s a bit more work to do:</p>
<div class="sourceCode" id="cb303"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb303-1" title="1">preps2 &lt;-<span class="st"> </span>steak <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">count</span>(steak_prep) <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">pull</span>(steak_prep)</a>
<a class="sourceLine" id="cb303-2" title="2">preps2</a></code></pre></div>
<pre><code>## [1] &quot;Medium&quot;      &quot;Medium rare&quot; &quot;Medium Well&quot; &quot;Rare&quot;        &quot;Well&quot;</code></pre>
<p>because <code>count</code> puts them in alphabetical order, so:</p>
<div class="sourceCode" id="cb305"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb305-1" title="1">preps3 &lt;-<span class="st"> </span>preps2[<span class="kw">c</span>(<span class="dv">4</span>, <span class="dv">2</span>, <span class="dv">1</span>, <span class="dv">3</span>, <span class="dv">5</span>)]</a>
<a class="sourceLine" id="cb305-2" title="2">preps3</a></code></pre></div>
<pre><code>## [1] &quot;Rare&quot;        &quot;Medium rare&quot; &quot;Medium&quot;      &quot;Medium Well&quot; &quot;Well&quot;</code></pre>
<p>These use the idea in the
attitudes-to-abortion question: create a vector of the levels in the
<em>right</em> order, then create an ordered factor with
<code>ordered()</code>. If you like, you can type the levels in the right
order (I won’t penalize you for that here), but it’s really better to
get the levels without typing or copying-pasting, so that you don’t
make any silly errors copying them (which will mess everything up
later).</p>
<p>So now I create my ordered response:</p>
<div class="sourceCode" id="cb307"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb307-1" title="1">steak &lt;-<span class="st"> </span>steak <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">mutate</span>(<span class="dt">steak_prep_ord =</span> <span class="kw">ordered</span>(steak_prep, preps1))</a></code></pre></div>
<p>or using one of the other <code>preps</code> vectors containing the levels
in the correct order.
As far as <code>polr</code> is concerned,
it doesn’t matter whether I start at <code>Rare</code> and go “up”, or
start at <code>Well</code> and go “down”. So if you do it the other way
around, that’s fine. As long as you get the levels in a sensible
order, you’re good.</p>
<p><span class="math inline">\(\blacksquare\)</span></p>
<ol start="4" style="list-style-type: lower-alpha">
<li>Fit a model predicting preferred steak preparation in an
ordinal logistic regression from <code>educ</code>, <code>female</code> and
<code>lottery_a</code>. This ought to be easy from your previous work,
but you have to be careful about one thing. No need to print out the
results.</li>
</ol>
<p>Solution</p>
<p>The thing you have to be careful about is that you use the
<em>ordered</em> factor that you just created as the response:</p>
<div class="sourceCode" id="cb308"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb308-1" title="1">steak<span class="fl">.1</span> &lt;-<span class="st"> </span><span class="kw">polr</span>(steak_prep_ord <span class="op">~</span><span class="st"> </span>educ <span class="op">+</span><span class="st"> </span>female <span class="op">+</span><span class="st"> </span>lottery_a, <span class="dt">data =</span> steak)</a></code></pre></div>
<p><span class="math inline">\(\blacksquare\)</span></p>
<ol start="5" style="list-style-type: lower-alpha">
<li>Run <code>drop1</code> on your fitted model, with
<code>test="Chisq"</code>. Which explanatory variable should be removed
first, if any? Bear in mind that the variable with the
<em>smallest</em> AIC should come out first, in case your table
doesn’t get printed in order.</li>
</ol>
<p>Solution</p>
<p>This:</p>
<div class="sourceCode" id="cb309"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb309-1" title="1"><span class="kw">drop1</span>(steak<span class="fl">.1</span>, <span class="dt">test =</span> <span class="st">&quot;Chisq&quot;</span>)</a></code></pre></div>
<pre><code>## Single term deletions
## 
## Model:
## steak_prep_ord ~ educ + female + lottery_a
##           Df    AIC    LRT Pr(&gt;Chi)  
## &lt;none&gt;       910.69                  
## educ       4 912.10 9.4107  0.05162 .
## female     1 908.70 0.0108  0.91715  
## lottery_a  1 909.93 1.2425  0.26498  
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<p>My table is indeed out of order (which is why I warned you about it,
in case that happens to you as well). The smallest AIC goes with
<code>female</code>, which also has a very non-significant P-value, so
this one should come out first.</p>
<p><span class="math inline">\(\blacksquare\)</span></p>
<ol start="6" style="list-style-type: lower-alpha">
<li>Remove the variable that should come out first, using
<code>update</code>. (If all the variables should stay, you can skip
this part.)</li>
</ol>
<p>Solution</p>
<p>You could type or copy-paste the whole model again, but
<code>update</code> is quicker:</p>
<div class="sourceCode" id="cb311"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb311-1" title="1">steak<span class="fl">.2</span> &lt;-<span class="st"> </span><span class="kw">update</span>(steak<span class="fl">.1</span>, . <span class="op">~</span><span class="st"> </span>. <span class="op">-</span><span class="st"> </span>female)</a></code></pre></div>
<p>That’s all.</p>
<p>I wanted to get some support for my <code>drop1</code> above (since I was
a bit worried about those out-of-order rows). Now that we have fitted
a model with <code>female</code> and one without, we can compare them
using <code>anova</code>:</p>
<div class="sourceCode" id="cb312"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb312-1" title="1"><span class="kw">anova</span>(steak<span class="fl">.2</span>, steak<span class="fl">.1</span>, <span class="dt">test =</span> <span class="st">&quot;Chisq&quot;</span>)</a></code></pre></div>
<pre><code>## Likelihood ratio tests of ordinal regression models
## 
## Response: steak_prep_ord
##                       Model Resid. df Resid. Dev   Test    Df  LR stat.
## 1          educ + lottery_a       322   890.7028                       
## 2 educ + female + lottery_a       321   890.6920 1 vs 2     1 0.0108221
##     Pr(Chi)
## 1          
## 2 0.9171461</code></pre>
<p>Don’t get taken in by that “LR stat” on the end of the first row of
the output table; the P-value wrapped onto the second line, and is in
fact exactly the same as in the <code>drop1</code> output (it is doing
exactly the same test). As non-significant as you could wish for.</p>
<p>I was curious about whether either of the other <span class="math inline">\(x\)</span>’s could come out now:</p>
<div class="sourceCode" id="cb314"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb314-1" title="1"><span class="kw">drop1</span>(steak<span class="fl">.2</span>, <span class="dt">test =</span> <span class="st">&quot;Chisq&quot;</span>)</a></code></pre></div>
<pre><code>## Single term deletions
## 
## Model:
## steak_prep_ord ~ educ + lottery_a
##           Df    AIC    LRT Pr(&gt;Chi)  
## &lt;none&gt;       908.70                  
## educ       4 910.13 9.4299  0.05121 .
## lottery_a  1 907.96 1.2599  0.26167  
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<p><code>lottery_a</code> should come out, but <code>educ</code> is edging
towards significance.</p>
<p><span class="math inline">\(\blacksquare\)</span></p>
<ol start="7" style="list-style-type: lower-alpha">
<li>Using the best model that you have so far, predict the
probabilities of preferring each different steak preparation (method
of cooking) for each combination of the variables that
remain. (Some of the variables are TRUE and FALSE rather than
factors. Bear this in mind.)
Describe the effects of each variable on the predicted
probabilities, if any. Note that there is exactly one person in the
study whose educational level is “less than high school”.</li>
</ol>
<p>Solution</p>
<p>Again, I’m leaving it to you to follow all the steps. My variables
remaining are <code>educ</code> and <code>lottery_a</code>. The second of
these is a logical, TRUE and FALSE, so I just filled in the two values:</p>
<div class="sourceCode" id="cb316"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb316-1" title="1">educs &lt;-<span class="st"> </span>steak <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">distinct</span>(educ) <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">pull</span>(educ)</a>
<a class="sourceLine" id="cb316-2" title="2">lottery_as &lt;-<span class="st"> </span><span class="kw">c</span>(<span class="ot">FALSE</span>, <span class="ot">TRUE</span>)</a>
<a class="sourceLine" id="cb316-3" title="3"></a>
<a class="sourceLine" id="cb316-4" title="4">steak.new &lt;-<span class="st"> </span><span class="kw">crossing</span>(<span class="dt">educ =</span> educs, <span class="dt">lottery_a =</span> lottery_as)</a>
<a class="sourceLine" id="cb316-5" title="5">steak.new</a></code></pre></div>
<pre><code>## # A tibble: 10 x 2
##    educ                             lottery_a
##    &lt;chr&gt;                            &lt;lgl&gt;    
##  1 Bachelor degree                  FALSE    
##  2 Bachelor degree                  TRUE     
##  3 Graduate degree                  FALSE    
##  4 Graduate degree                  TRUE     
##  5 High school degree               FALSE    
##  6 High school degree               TRUE     
##  7 Less than high school degree     FALSE    
##  8 Less than high school degree     TRUE     
##  9 Some college or Associate degree FALSE    
## 10 Some college or Associate degree TRUE</code></pre>
<p>My best model so far is the one I called <code>steak.2</code>, without
<code>female</code>, so this. As before, if you forget what <code>type</code>
should be, put in <em>something</em>, and it will tell you what your
choices are:</p>
<div class="sourceCode" id="cb318"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb318-1" title="1">p &lt;-<span class="st"> </span><span class="kw">predict</span>(steak<span class="fl">.2</span>, steak.new, <span class="dt">type =</span> <span class="st">&quot;probs&quot;</span>)</a>
<a class="sourceLine" id="cb318-2" title="2"><span class="kw">cbind</span>(steak.new, p)</a></code></pre></div>
<pre><code>##                                educ lottery_a         Rare  Medium rare
## 1                   Bachelor degree     FALSE 5.191314e-02 3.832425e-01
## 2                   Bachelor degree      TRUE 4.181795e-02 3.386213e-01
## 3                   Graduate degree     FALSE 7.954891e-02 4.691799e-01
## 4                   Graduate degree      TRUE 6.444488e-02 4.277303e-01
## 5                High school degree     FALSE 5.280801e-02 3.867857e-01
## 6                High school degree      TRUE 4.254661e-02 3.421527e-01
## 7      Less than high school degree     FALSE 8.507263e-08 1.111878e-06
## 8      Less than high school degree      TRUE 6.780714e-08 8.862222e-07
## 9  Some college or Associate degree     FALSE 5.499694e-02 3.951981e-01
## 10 Some college or Associate degree      TRUE 4.433010e-02 3.505796e-01
##          Medium  Medium Well       Well
## 1  3.347391e-01 1.719854e-01 0.05811984
## 2  3.468434e-01 2.008621e-01 0.07185531
## 3  2.920587e-01 1.215881e-01 0.03762435
## 4  3.158550e-01 1.452132e-01 0.04675658
## 5  3.334805e-01 1.697854e-01 0.05714038
## 6  3.461457e-01 1.984932e-01 0.07066175
## 7  4.001373e-06 1.997966e-05 0.99997482
## 8  3.189298e-06 1.592489e-05 0.99997993
## 9  3.303218e-01 1.646121e-01 0.05487110
## 10 3.442957e-01 1.929005e-01 0.06789415</code></pre>
<p>I find this hard to read, so I’m going to round off those
predictions. Three or four decimals seems to be sensible:</p>
<div class="sourceCode" id="cb320"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb320-1" title="1"><span class="kw">cbind</span>(steak.new, <span class="kw">round</span>(p, <span class="dv">3</span>))</a></code></pre></div>
<pre><code>##                                educ lottery_a  Rare Medium rare Medium
## 1                   Bachelor degree     FALSE 0.052       0.383  0.335
## 2                   Bachelor degree      TRUE 0.042       0.339  0.347
## 3                   Graduate degree     FALSE 0.080       0.469  0.292
## 4                   Graduate degree      TRUE 0.064       0.428  0.316
## 5                High school degree     FALSE 0.053       0.387  0.333
## 6                High school degree      TRUE 0.043       0.342  0.346
## 7      Less than high school degree     FALSE 0.000       0.000  0.000
## 8      Less than high school degree      TRUE 0.000       0.000  0.000
## 9  Some college or Associate degree     FALSE 0.055       0.395  0.330
## 10 Some college or Associate degree      TRUE 0.044       0.351  0.344
##    Medium Well  Well
## 1        0.172 0.058
## 2        0.201 0.072
## 3        0.122 0.038
## 4        0.145 0.047
## 5        0.170 0.057
## 6        0.198 0.071
## 7        0.000 1.000
## 8        0.000 1.000
## 9        0.165 0.055
## 10       0.193 0.068</code></pre>
<p>Say something about the effect of changing educational level on the
predictions, and say something about the effect of favouring Lottery A
vs. not. I don’t much mind what: you can say that there is not much
effect (of either variable), or you can say something like “people with a graduate degree are slightly more likely to like their steak rare and less likely to like it well done” (for education level) and
“people who preferred Lottery A are slightly less likely to like their steak rare and slightly more likely to like it well done” (for
effect of Lottery A). You can see these by comparing the first five
rows to assess the effect of education (or the last five rows, if you
prefer), and you can compare eg. rows 1 and 6 to assess the effect of
Lottery A (compare two lines with the <em>same</em> educational level
but <em>different</em> preferences re Lottery A).</p>
<p>I would keep away from saying anything about education level
“less than high school”, since this entire level is represented by exactly
one person.</p>
<p><span class="math inline">\(\blacksquare\)</span></p>
<ol start="8" style="list-style-type: lower-alpha">
<li>Is it reasonable to remove <em>all</em> the remaining
explanatory variables from your best model so far? Fit a model with no explanatory variables,
and do a test. (In R, if the right side of the squiggle is a
<code>1</code>, that means “just an intercept”. Or you can remove
whatever remains using <code>update</code>.) What do you conclude?
Explain briefly.</li>
</ol>
<p>Solution</p>
<p>The fitting part is the challenge, since the testing part is
<code>anova</code> again. The direct fit is this:</p>
<div class="sourceCode" id="cb322"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb322-1" title="1">steak<span class="fl">.3</span> &lt;-<span class="st"> </span><span class="kw">polr</span>(steak_prep_ord <span class="op">~</span><span class="st"> </span><span class="dv">1</span>, <span class="dt">data =</span> steak)</a></code></pre></div>
<p>and the <code>update</code> version is this, about equally long, starting
from <code>steak.2</code> since that is the best model so far:</p>
<div class="sourceCode" id="cb323"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb323-1" title="1">steak<span class="fl">.3</span>a &lt;-<span class="st"> </span><span class="kw">update</span>(steak<span class="fl">.2</span>, . <span class="op">~</span><span class="st"> </span>. <span class="op">-</span><span class="st"> </span>educ <span class="op">-</span><span class="st"> </span>lottery_a)</a></code></pre></div>
<p>You can use whichever you like. Either way, the second part is
<code>anova</code>, and the two possible answers should be the same:</p>
<div class="sourceCode" id="cb324"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb324-1" title="1"><span class="kw">anova</span>(steak<span class="fl">.3</span>, steak<span class="fl">.2</span>, <span class="dt">test =</span> <span class="st">&quot;Chisq&quot;</span>)</a></code></pre></div>
<pre><code>## Likelihood ratio tests of ordinal regression models
## 
## Response: steak_prep_ord
##              Model Resid. df Resid. Dev   Test    Df LR stat.    Pr(Chi)
## 1                1       327   901.4467                                 
## 2 educ + lottery_a       322   890.7028 1 vs 2     5 10.74387 0.05670146</code></pre>
<p>or</p>
<div class="sourceCode" id="cb326"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb326-1" title="1"><span class="kw">anova</span>(steak<span class="fl">.3</span>a, steak<span class="fl">.2</span>, <span class="dt">test =</span> <span class="st">&quot;Chisq&quot;</span>)</a></code></pre></div>
<pre><code>## Likelihood ratio tests of ordinal regression models
## 
## Response: steak_prep_ord
##              Model Resid. df Resid. Dev   Test    Df LR stat.    Pr(Chi)
## 1                1       327   901.4467                                 
## 2 educ + lottery_a       322   890.7028 1 vs 2     5 10.74387 0.05670146</code></pre>
<p>At the 0.05 level, removing both of the remaining variables is fine:
that is, nothing (out of these variables) has any impact on the
probability that a diner will prefer their steak cooked a particular
way.</p>
<p>However, with data like this and a rather exploratory analysis, I
might think about using a larger <span class="math inline">\(\alpha\)</span> like 0.10, and at this
level, taking out both these two variables is a bad idea. You could
say that one or both of them is “potentially useful” or
“provocative” or something like that.</p>
<p>If you think that removing these two variables is questionable, you
might like to go back to that <code>drop1</code> output I had above:</p>
<div class="sourceCode" id="cb328"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb328-1" title="1"><span class="kw">drop1</span>(steak<span class="fl">.2</span>, <span class="dt">test =</span> <span class="st">&quot;Chisq&quot;</span>)</a></code></pre></div>
<pre><code>## Single term deletions
## 
## Model:
## steak_prep_ord ~ educ + lottery_a
##           Df    AIC    LRT Pr(&gt;Chi)  
## &lt;none&gt;       908.70                  
## educ       4 910.13 9.4299  0.05121 .
## lottery_a  1 907.96 1.2599  0.26167  
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<p>The smallest AIC goes with <code>lottery_a</code>, so that comes out (it
is nowhere near significant):</p>
<div class="sourceCode" id="cb330"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb330-1" title="1">steak<span class="fl">.4</span> &lt;-<span class="st"> </span><span class="kw">update</span>(steak<span class="fl">.2</span>, . <span class="op">~</span><span class="st"> </span>. <span class="op">-</span><span class="st"> </span>lottery_a)</a>
<a class="sourceLine" id="cb330-2" title="2"><span class="kw">drop1</span>(steak<span class="fl">.4</span>, <span class="dt">test =</span> <span class="st">&quot;Chisq&quot;</span>)</a></code></pre></div>
<pre><code>## Single term deletions
## 
## Model:
## steak_prep_ord ~ educ
##        Df    AIC   LRT Pr(&gt;Chi)  
## &lt;none&gt;    907.96                 
## educ    4 909.45 9.484  0.05008 .
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<p>and what you see is that educational level is right on the edge of
significance, so that may or may not have any impact. Make a call. But
if anything, it’s educational level that makes a difference.</p>
<p><span class="math inline">\(\blacksquare\)</span></p>
<ol style="list-style-type: lower-roman">
<li>In the article for which these data were collected,
<a href="https://fivethirtyeight.com/datalab/how-americans-like-their-steak/">link</a>,
does the author obtain consistent conclusions with yours? Explain
briefly. (It’s not a very long article, so it won’t take you long to
skim through, and the author’s point is pretty clear.)</li>
</ol>
<p>Solution</p>
<p>The article says that <em>nothing</em> has anything to do with steak
preference. Whether you agree or not depends on what you thought
above about dropping those last two variables. So say something
consistent with what you said in the previous part. Two points for
saying that the author said “nothing has any effect”, and one
point for how your findings square with that.
Now that you have worked through this great long question, this is
where I tell you that I simplified things a fair bit for you! There
were lots of other variables that might have had an impact on how
people like their steaks, and we didn’t even consider those. Why did
I choose what I did here? Well, I wanted to fit a regression predicting
steak preference from everything else, do a big backward
elimination, but:</p>
<div class="sourceCode" id="cb332"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb332-1" title="1">steak<span class="fl">.5</span> &lt;-<span class="st"> </span><span class="kw">polr</span>(steak_prep_ord <span class="op">~</span><span class="st"> </span>., <span class="dt">data =</span> steak)</a></code></pre></div>
<pre><code>## Warning: glm.fit: algorithm did not converge</code></pre>
<pre><code>## Error in polr(steak_prep_ord ~ ., data = steak): attempt to find suitable starting values failed</code></pre>
<p>The <code>.</code> in place of explanatory
variables means “all the other variables”, including the nonsensical
personal ID. That saved me having to type them all out.</p>
<p>Unfortunately, however, it didn’t work. The problem is a numerical
one. Regular regression has a well-defined procedure, where the computer follows
through the steps and gets to the answer, every time. Once you go
beyond regression, however, the answer is obtained by a step-by-step
method: the computer makes an initial guess, tries to improve it, then
tries to improve it again, until it can’t improve things any more, at
which point it calls it good. The problem here is that <code>polr</code>
cannot even get the initial guess! (It apparently is known to suck at
this, in problems as big and complicated as this one.)</p>
<p>I don’t normally recommend forward selection, but I wonder whether it
works here:</p>
<div class="sourceCode" id="cb335"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb335-1" title="1">steak<span class="fl">.5</span> &lt;-<span class="st"> </span><span class="kw">polr</span>(steak_prep_ord <span class="op">~</span><span class="st"> </span><span class="dv">1</span>, <span class="dt">data =</span> steak)</a>
<a class="sourceLine" id="cb335-2" title="2">steak<span class="fl">.6</span> &lt;-<span class="st"> </span><span class="kw">step</span>(steak<span class="fl">.5</span>,</a>
<a class="sourceLine" id="cb335-3" title="3">  <span class="dt">scope =</span> . <span class="op">~</span><span class="st"> </span>lottery_a <span class="op">+</span><span class="st"> </span>smoke <span class="op">+</span><span class="st"> </span>alcohol <span class="op">+</span><span class="st"> </span>gamble <span class="op">+</span><span class="st"> </span>skydiving <span class="op">+</span></a>
<a class="sourceLine" id="cb335-4" title="4"><span class="st">    </span>speed <span class="op">+</span><span class="st"> </span>cheated <span class="op">+</span><span class="st"> </span>female <span class="op">+</span><span class="st"> </span>age <span class="op">+</span><span class="st"> </span>hhold_income <span class="op">+</span><span class="st"> </span>educ <span class="op">+</span><span class="st"> </span>region,</a>
<a class="sourceLine" id="cb335-5" title="5">  <span class="dt">direction =</span> <span class="st">&quot;forward&quot;</span>, <span class="dt">test =</span> <span class="st">&quot;Chisq&quot;</span>, <span class="dt">trace =</span> <span class="dv">0</span></a>
<a class="sourceLine" id="cb335-6" title="6">)</a>
<a class="sourceLine" id="cb335-7" title="7"><span class="kw">drop1</span>(steak<span class="fl">.6</span>, <span class="dt">test =</span> <span class="st">&quot;Chisq&quot;</span>)</a></code></pre></div>
<pre><code>## Single term deletions
## 
## Model:
## steak_prep_ord ~ educ
##        Df    AIC   LRT Pr(&gt;Chi)  
## &lt;none&gt;    907.96                 
## educ    4 909.45 9.484  0.05008 .
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<p>It does, and it says the <em>only</em> thing to add out of all the
variables is education level. So, for you, I picked this along with a
couple of other plausible-sounding variables and had you start from there.</p>
<p>Forward selection starts from a model containing nothing and asks
“what can we add?”. This is a bit more complicated than backward
elimination, because now you have to say what the candidate things to
add <em>are</em>. That’s the purpose of that <code>scope</code> piece, and
there I had no alternative but to type the names of all the
variables. Backward elimination is easier, because the candidate
variables to remove are the ones in the model, and you don’t need a
<code>scope</code>. The <code>trace=0</code> says “don’t give me any output”
(you can change it to a different value if you want to see what that
does), and last, the <code>drop1</code> looks at what is actually
<em>in</em> the final model (with a view to asking what can be removed,
but we don’t care about <em>that</em> here).</p>
<p><span class="math inline">\(\blacksquare\)</span></p>
</div>
<div id="how-do-you-like-your-steak-the-data-1" class="section level2">
<h2><span class="header-section-number">27.10</span> How do you like your steak – the data</h2>
<p><a name="q:steak-data"><em></a>
This question takes you through the data preparation for one
of the other questions. You don’t have to do </em>this*
question, but you may find it interesting or useful.</p>
<p>When you order a steak in a restaurant, the server will ask
you how you would like it cooked, or to be precise, <em>how much</em>
you would like it cooked: rare (hardly cooked at all), through medium
rare, medium, medium well to well (which means “well done”, so that
the meat has only a little red to it). Could you guess how a person
likes their steak cooked, from some other information about them? The
website <a href="fivethirtyeight.com">link</a> commissioned a survey where they
asked a number of people how they preferred their steak, along with as
many other things as they could think of to ask. (Many of the
variables below are related to risk-taking, which was something the
people designing the survey thought might have something to do with
liking steak rare.) The variables of interest are all factors or true/false:</p>
<ul>
<li><p><code>respondent_ID</code>: a ten-digit number identifying each
person who responded to the survey.</p></li>
<li><p><code>lottery_a</code>: true if the respondent preferred lottery A
with a small chance to win a lot of money, to lottery B, with a
larger chance to win less money.</p></li>
<li><p><code>smoke</code>: true if the respondent is currently a smoker</p></li>
<li><p><code>alcohol</code>: true if the respondent at least occasionally
drinks alcohol.</p></li>
<li><p><code>gamble</code>: true if the respondent likes to gamble (eg.
betting on horse racing or playing the lottery)</p></li>
<li><p><code>skydiving</code>: true if the respondent has ever been
skydiving.</p></li>
<li><p><code>speed</code>: true if the respondent likes to drive fast</p></li>
<li><p><code>cheated</code>: true if the respondent has ever cheated on a
spouse or girlfriend/boyfriend</p></li>
<li><p><code>steak</code>: true if the respondent likes to eat steak</p></li>
<li><p><code>steak_prep</code> (response): how the respondent likes their
steak cooked (factor, as described above, with 5 levels).</p></li>
<li><p><code>female</code>: true if the respondent is female</p></li>
<li><p><code>age</code>: age group, from 18–29 to 60+.</p></li>
<li><p><code>hhold_income</code>: household income group, from $0–24,999
to $150,000+.</p></li>
<li><p><code>educ</code>: highest level of education attained, from
“less than high school”
up to “graduate degree”</p></li>
<li><p><code>region</code>: region (of the US)
that the respondent lives in (five values).</p></li>
</ul>
<p>The data are in
<a href="https://raw.githubusercontent.com/nxskok/datafiles/master/steak.csv">link</a>.</p>
<ol style="list-style-type: lower-alpha">
<li>Read in the data and display the first few lines.</li>
</ol>
<p>Solution</p>
<p>The usual:</p>
<div class="sourceCode" id="cb337"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb337-1" title="1">my_url &lt;-<span class="st"> &quot;https://raw.githubusercontent.com/nxskok/datafiles/master/steak.csv&quot;</span></a>
<a class="sourceLine" id="cb337-2" title="2">steak0 &lt;-<span class="st"> </span><span class="kw">read_csv</span>(my_url)</a></code></pre></div>
<pre><code>## 
## ── Column specification ──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
## cols(
##   respondent_id = col_double(),
##   lottery_a = col_logical(),
##   smoke = col_logical(),
##   alcohol = col_logical(),
##   gamble = col_logical(),
##   skydiving = col_logical(),
##   speed = col_logical(),
##   cheated = col_logical(),
##   steak = col_logical(),
##   steak_prep = col_character(),
##   female = col_logical(),
##   age = col_character(),
##   hhold_income = col_character(),
##   educ = col_character(),
##   region = col_character()
## )</code></pre>
<div class="sourceCode" id="cb339"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb339-1" title="1">steak0</a></code></pre></div>
<pre><code>## # A tibble: 550 x 15
##    respondent_id lottery_a smoke alcohol gamble skydiving speed cheated steak
##            &lt;dbl&gt; &lt;lgl&gt;     &lt;lgl&gt; &lt;lgl&gt;   &lt;lgl&gt;  &lt;lgl&gt;     &lt;lgl&gt; &lt;lgl&gt;   &lt;lgl&gt;
##  1    3237565956 FALSE     NA    NA      NA     NA        NA    NA      NA   
##  2    3234982343 TRUE      FALSE TRUE    FALSE  FALSE     FALSE FALSE   TRUE 
##  3    3234973379 TRUE      FALSE TRUE    TRUE   FALSE     TRUE  TRUE    TRUE 
##  4    3234972383 FALSE     TRUE  TRUE    TRUE   FALSE     TRUE  TRUE    TRUE 
##  5    3234958833 FALSE     FALSE TRUE    FALSE  FALSE     TRUE  TRUE    TRUE 
##  6    3234955240 TRUE      FALSE FALSE   FALSE  FALSE     TRUE  FALSE   TRUE 
##  7    3234955097 TRUE      FALSE TRUE    FALSE  FALSE     TRUE  TRUE    FALSE
##  8    3234955010 TRUE      FALSE TRUE    TRUE   TRUE      TRUE  FALSE   TRUE 
##  9    3234953052 TRUE      TRUE  TRUE    TRUE   FALSE     TRUE  FALSE   TRUE 
## 10    3234951249 FALSE     FALSE TRUE    TRUE   FALSE     FALSE FALSE   TRUE 
## # … with 540 more rows, and 6 more variables: steak_prep &lt;chr&gt;, female &lt;lgl&gt;,
## #   age &lt;chr&gt;, hhold_income &lt;chr&gt;, educ &lt;chr&gt;, region &lt;chr&gt;</code></pre>
<p>I’m using a temporary name for reasons that will become clear shortly.</p>
<p><span class="math inline">\(\blacksquare\)</span></p>
<ol start="2" style="list-style-type: lower-alpha">
<li>What do you immediately notice about your data frame? Run <code>summary</code> on the entire data frame. Would you say you have a lot of missing values, or only a few?</li>
</ol>
<p>Solution</p>
<p>I see missing values, starting in the very first row.
Running the data frame through <code>summary</code> gives this, either as <code>summary(steak0)</code> or this way:</p>
<div class="sourceCode" id="cb341"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb341-1" title="1">steak0 <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">summary</span>()</a></code></pre></div>
<pre><code>##  respondent_id       lottery_a         smoke          alcohol       
##  Min.   :3.235e+09   Mode :logical   Mode :logical   Mode :logical  
##  1st Qu.:3.235e+09   FALSE:279       FALSE:453       FALSE:125      
##  Median :3.235e+09   TRUE :267       TRUE :84        TRUE :416      
##  Mean   :3.235e+09   NA&#39;s :4         NA&#39;s :13        NA&#39;s :9        
##  3rd Qu.:3.235e+09                                                  
##  Max.   :3.238e+09                                                  
##    gamble        skydiving         speed          cheated       
##  Mode :logical   Mode :logical   Mode :logical   Mode :logical  
##  FALSE:280       FALSE:502       FALSE:59        FALSE:447      
##  TRUE :257       TRUE :36        TRUE :480       TRUE :92       
##  NA&#39;s :13        NA&#39;s :12        NA&#39;s :11        NA&#39;s :11       
##                                                                 
##                                                                 
##    steak          steak_prep          female            age           
##  Mode :logical   Length:550         Mode :logical   Length:550        
##  FALSE:109       Class :character   FALSE:246       Class :character  
##  TRUE :430       Mode  :character   TRUE :268       Mode  :character  
##  NA&#39;s :11                           NA&#39;s :36                          
##                                                                       
##                                                                       
##  hhold_income           educ              region         
##  Length:550         Length:550         Length:550        
##  Class :character   Class :character   Class :character  
##  Mode  :character   Mode  :character   Mode  :character  
##                                                          
##                                                          
## </code></pre>
<p>Make a call about whether you think that’s a lot of missing values or only a few. This might not be all of them, because missing text doesn’t show here (we see later how to make it show up).</p>
<p><span class="math inline">\(\blacksquare\)</span></p>
<ol start="3" style="list-style-type: lower-alpha">
<li>What does the function <code>drop_na</code> do when applied to a data frame with missing values? To find out, pass the data frame into <code>drop_na()</code>, then into <code>summary</code> again. What has happened?</li>
</ol>
<p>Solution</p>
<p>Let’s try it and see.</p>
<div class="sourceCode" id="cb343"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb343-1" title="1">steak0 <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">drop_na</span>() <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">summary</span>()</a></code></pre></div>
<pre><code>##  respondent_id       lottery_a         smoke          alcohol       
##  Min.   :3.235e+09   Mode :logical   Mode :logical   Mode :logical  
##  1st Qu.:3.235e+09   FALSE:171       FALSE:274       FALSE:65       
##  Median :3.235e+09   TRUE :160       TRUE :57        TRUE :266      
##  Mean   :3.235e+09                                                  
##  3rd Qu.:3.235e+09                                                  
##  Max.   :3.235e+09                                                  
##    gamble        skydiving         speed          cheated         steak        
##  Mode :logical   Mode :logical   Mode :logical   Mode :logical   Mode:logical  
##  FALSE:158       FALSE:308       FALSE:28        FALSE:274       TRUE:331      
##  TRUE :173       TRUE :23        TRUE :303       TRUE :57                      
##                                                                                
##                                                                                
##                                                                                
##   steak_prep          female            age            hhold_income      
##  Length:331         Mode :logical   Length:331         Length:331        
##  Class :character   FALSE:174       Class :character   Class :character  
##  Mode  :character   TRUE :157       Mode  :character   Mode  :character  
##                                                                          
##                                                                          
##                                                                          
##      educ              region         
##  Length:331         Length:331        
##  Class :character   Class :character  
##  Mode  :character   Mode  :character  
##                                       
##                                       
## </code></pre>
<p>The missing values, the ones we can see anyway, have all gone. Precisely, <code>drop_na</code>, as its
name suggests, drops all the rows that have missing values in them
anywhere. This is potentially wasteful, since a row might be missing
only one value, and we drop the entire rest of the row, throwing away
the good data as well. If you check, we started with 550 rows, and we
now have only 311 left. Ouch.</p>
<p>So now we’ll save this into our “good” data frame, which means doing it again (now that we know it works):</p>
<div class="sourceCode" id="cb345"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb345-1" title="1">steak0 <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">drop_na</span>() -&gt;<span class="st"> </span>steak</a></code></pre></div>
<p>Extra: another way to handle missing data is called “imputation”:
what you do is to <em>estimate</em> a value for any missing data, and
then use that later on as if it were the truth. One way of estimating
missing values is to do a regression (of appropriate kind: regular or
logistic) to predict a column with missing values from all the other
columns.</p>
<p>Extra extra: below we see how we used to have to do this, for your information.</p>
<p>First, we run <code>complete.cases</code> on the data frame:</p>
<div class="sourceCode" id="cb346"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb346-1" title="1"><span class="kw">complete.cases</span>(steak0)</a></code></pre></div>
<pre><code>##   [1] FALSE  TRUE  TRUE  TRUE  TRUE  TRUE FALSE  TRUE  TRUE  TRUE  TRUE  TRUE
##  [13]  TRUE  TRUE  TRUE  TRUE  TRUE FALSE  TRUE FALSE  TRUE  TRUE FALSE  TRUE
##  [25]  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE FALSE FALSE  TRUE FALSE FALSE
##  [37]  TRUE FALSE FALSE FALSE FALSE  TRUE FALSE  TRUE FALSE  TRUE  TRUE  TRUE
##  [49]  TRUE  TRUE FALSE FALSE  TRUE  TRUE FALSE  TRUE  TRUE  TRUE FALSE  TRUE
##  [61] FALSE  TRUE  TRUE FALSE  TRUE  TRUE FALSE FALSE FALSE  TRUE FALSE FALSE
##  [73] FALSE  TRUE  TRUE FALSE FALSE FALSE  TRUE FALSE FALSE  TRUE FALSE FALSE
##  [85] FALSE  TRUE  TRUE  TRUE FALSE FALSE  TRUE  TRUE  TRUE FALSE FALSE  TRUE
##  [97]  TRUE  TRUE FALSE  TRUE FALSE  TRUE FALSE  TRUE  TRUE  TRUE FALSE  TRUE
## [109] FALSE  TRUE  TRUE FALSE FALSE  TRUE FALSE  TRUE FALSE FALSE  TRUE  TRUE
## [121]  TRUE  TRUE  TRUE FALSE  TRUE  TRUE FALSE FALSE FALSE  TRUE  TRUE  TRUE
## [133] FALSE FALSE  TRUE FALSE FALSE FALSE  TRUE  TRUE  TRUE  TRUE FALSE  TRUE
## [145]  TRUE FALSE  TRUE  TRUE  TRUE FALSE  TRUE  TRUE  TRUE  TRUE FALSE  TRUE
## [157]  TRUE  TRUE  TRUE FALSE FALSE  TRUE  TRUE FALSE FALSE FALSE FALSE FALSE
## [169]  TRUE FALSE  TRUE FALSE  TRUE  TRUE FALSE FALSE  TRUE  TRUE  TRUE FALSE
## [181] FALSE  TRUE FALSE FALSE  TRUE FALSE  TRUE FALSE  TRUE  TRUE FALSE FALSE
## [193]  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE FALSE  TRUE FALSE FALSE FALSE  TRUE
## [205]  TRUE FALSE  TRUE FALSE FALSE FALSE FALSE FALSE  TRUE  TRUE  TRUE  TRUE
## [217] FALSE  TRUE  TRUE FALSE  TRUE  TRUE FALSE  TRUE  TRUE FALSE  TRUE  TRUE
## [229]  TRUE  TRUE  TRUE FALSE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE FALSE  TRUE
## [241]  TRUE  TRUE  TRUE  TRUE  TRUE FALSE FALSE  TRUE FALSE  TRUE FALSE  TRUE
## [253] FALSE  TRUE FALSE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE FALSE  TRUE  TRUE
## [265] FALSE  TRUE  TRUE  TRUE FALSE  TRUE  TRUE  TRUE FALSE  TRUE FALSE FALSE
## [277]  TRUE FALSE  TRUE FALSE FALSE FALSE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE
## [289]  TRUE FALSE FALSE FALSE FALSE  TRUE  TRUE  TRUE FALSE  TRUE FALSE  TRUE
## [301] FALSE  TRUE  TRUE  TRUE FALSE FALSE  TRUE  TRUE FALSE  TRUE  TRUE  TRUE
## [313]  TRUE FALSE  TRUE  TRUE  TRUE  TRUE FALSE  TRUE FALSE  TRUE FALSE  TRUE
## [325] FALSE FALSE  TRUE  TRUE FALSE  TRUE  TRUE FALSE  TRUE  TRUE FALSE  TRUE
## [337]  TRUE  TRUE  TRUE  TRUE  TRUE FALSE FALSE  TRUE FALSE FALSE  TRUE FALSE
## [349] FALSE  TRUE  TRUE  TRUE FALSE  TRUE  TRUE FALSE FALSE  TRUE  TRUE  TRUE
## [361] FALSE  TRUE FALSE  TRUE  TRUE FALSE FALSE  TRUE  TRUE  TRUE  TRUE FALSE
## [373] FALSE FALSE  TRUE FALSE FALSE  TRUE  TRUE  TRUE  TRUE FALSE FALSE  TRUE
## [385]  TRUE  TRUE  TRUE  TRUE  TRUE FALSE FALSE  TRUE FALSE FALSE  TRUE  TRUE
## [397]  TRUE  TRUE  TRUE  TRUE FALSE  TRUE  TRUE FALSE  TRUE  TRUE  TRUE FALSE
## [409]  TRUE  TRUE  TRUE  TRUE FALSE  TRUE FALSE  TRUE FALSE  TRUE FALSE FALSE
## [421]  TRUE FALSE FALSE  TRUE  TRUE  TRUE FALSE  TRUE FALSE FALSE  TRUE  TRUE
## [433]  TRUE FALSE FALSE  TRUE  TRUE FALSE  TRUE  TRUE FALSE FALSE  TRUE FALSE
## [445]  TRUE  TRUE  TRUE FALSE FALSE  TRUE  TRUE FALSE  TRUE  TRUE FALSE  TRUE
## [457]  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE FALSE  TRUE  TRUE  TRUE FALSE
## [469]  TRUE  TRUE FALSE  TRUE FALSE FALSE  TRUE  TRUE FALSE FALSE  TRUE  TRUE
## [481] FALSE FALSE  TRUE  TRUE  TRUE  TRUE  TRUE FALSE  TRUE FALSE  TRUE FALSE
## [493] FALSE  TRUE  TRUE  TRUE  TRUE  TRUE FALSE  TRUE FALSE FALSE  TRUE FALSE
## [505]  TRUE FALSE FALSE  TRUE FALSE  TRUE FALSE  TRUE FALSE  TRUE  TRUE FALSE
## [517]  TRUE  TRUE FALSE FALSE  TRUE  TRUE FALSE FALSE  TRUE  TRUE  TRUE FALSE
## [529] FALSE FALSE  TRUE FALSE FALSE  TRUE  TRUE FALSE FALSE  TRUE  TRUE FALSE
## [541] FALSE FALSE  TRUE  TRUE  TRUE  TRUE FALSE  TRUE FALSE FALSE</code></pre>
<p>You might be able to guess what this does, in the light of what we
just did, but if not, you can investigate. Let’s pick three rows where
<code>complete.cases</code> is
<code>TRUE</code> and three where it’s
<code>FALSE</code>, and see what happens.</p>
<p>I’ll pick rows 496, 497, and 498 for the TRUE rows, and 540, 541 and
542 for the FALSE ones. Let’s assemble these rows into a vector and
use <code>slice</code> to display the rows with these numbers:</p>
<div class="sourceCode" id="cb348"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb348-1" title="1">rows &lt;-<span class="st"> </span><span class="kw">c</span>(<span class="dv">496</span>, <span class="dv">497</span>, <span class="dv">498</span>, <span class="dv">540</span>, <span class="dv">541</span>, <span class="dv">542</span>)</a>
<a class="sourceLine" id="cb348-2" title="2">rows</a></code></pre></div>
<pre><code>## [1] 496 497 498 540 541 542</code></pre>
<p>Like this:</p>
<div class="sourceCode" id="cb350"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb350-1" title="1">steak0 <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">slice</span>(rows)</a></code></pre></div>
<pre><code>## # A tibble: 6 x 15
##   respondent_id lottery_a smoke alcohol gamble skydiving speed cheated steak
##           &lt;dbl&gt; &lt;lgl&gt;     &lt;lgl&gt; &lt;lgl&gt;   &lt;lgl&gt;  &lt;lgl&gt;     &lt;lgl&gt; &lt;lgl&gt;   &lt;lgl&gt;
## 1    3234776895 FALSE     FALSE FALSE   FALSE  FALSE     FALSE FALSE   TRUE 
## 2    3234776815 TRUE      TRUE  TRUE    FALSE  FALSE     TRUE  FALSE   TRUE 
## 3    3234776702 FALSE     FALSE FALSE   FALSE  FALSE     FALSE FALSE   TRUE 
## 4    3234763650 TRUE      FALSE FALSE   FALSE  FALSE     TRUE  FALSE   FALSE
## 5    3234763171 TRUE      FALSE TRUE    TRUE   FALSE     TRUE  FALSE   TRUE 
## 6    3234762715 FALSE     FALSE FALSE   FALSE  FALSE     TRUE  FALSE   FALSE
## # … with 6 more variables: steak_prep &lt;chr&gt;, female &lt;lgl&gt;, age &lt;chr&gt;,
## #   hhold_income &lt;chr&gt;, educ &lt;chr&gt;, region &lt;chr&gt;</code></pre>
<p>What’s the difference?
The rows where <code>complete.cases</code> is FALSE have one (or more)
missing values in them; where <code>complete.cases</code> is TRUE the
rows have no missing values. (Depending on the rows you choose,
you may not see the missing value(s), as I didn’t.)
Extra (within “extra extra”: I hope you are keeping track): this
is a bit tricky to investigate more thoroughly, because the text
variables might have missing values in them, and they won’t show
up unless we turn them into a factor first:</p>
<div class="sourceCode" id="cb352"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb352-1" title="1">steak0 <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb352-2" title="2"><span class="st">  </span><span class="kw">mutate</span>(<span class="kw">across</span>(<span class="kw">where</span>(is.character), <span class="op">~</span><span class="kw">factor</span>(.))) <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb352-3" title="3"><span class="st">  </span><span class="kw">summary</span>()</a></code></pre></div>
<pre><code>##  respondent_id       lottery_a         smoke          alcohol       
##  Min.   :3.235e+09   Mode :logical   Mode :logical   Mode :logical  
##  1st Qu.:3.235e+09   FALSE:279       FALSE:453       FALSE:125      
##  Median :3.235e+09   TRUE :267       TRUE :84        TRUE :416      
##  Mean   :3.235e+09   NA&#39;s :4         NA&#39;s :13        NA&#39;s :9        
##  3rd Qu.:3.235e+09                                                  
##  Max.   :3.238e+09                                                  
##                                                                     
##    gamble        skydiving         speed          cheated       
##  Mode :logical   Mode :logical   Mode :logical   Mode :logical  
##  FALSE:280       FALSE:502       FALSE:59        FALSE:447      
##  TRUE :257       TRUE :36        TRUE :480       TRUE :92       
##  NA&#39;s :13        NA&#39;s :12        NA&#39;s :11        NA&#39;s :11       
##                                                                 
##                                                                 
##                                                                 
##    steak               steak_prep    female           age     
##  Mode :logical   Medium     :132   Mode :logical   &gt;60  :131  
##  FALSE:109       Medium rare:166   FALSE:246       18-29:110  
##  TRUE :430       Medium Well: 75   TRUE :268       30-44:133  
##  NA&#39;s :11        Rare       : 23   NA&#39;s :36        45-60:140  
##                  Well       : 36                   NA&#39;s : 36  
##                  NA&#39;s       :118                              
##                                                               
##               hhold_income                               educ    
##  $0 - $24,999       : 51   Bachelor degree                 :174  
##  $100,000 - $149,999: 76   Graduate degree                 :133  
##  $150,000+          : 54   High school degree              : 39  
##  $25,000 - $49,999  : 77   Less than high school degree    :  2  
##  $50,000 - $99,999  :172   Some college or Associate degree:164  
##  NA&#39;s               :120   NA&#39;s                            : 38  
##                                                                  
##                 region   
##  Pacific           : 91  
##  South Atlantic    : 88  
##  East North Central: 86  
##  Middle Atlantic   : 72  
##  West North Central: 42  
##  (Other)           :133  
##  NA&#39;s              : 38</code></pre>
<p>There are missing values everywhere. What the <code>where</code>
does is to do something for each column where the first thing is true:
here, if the column is text, then replace it by the factor version of
itself. This makes for a better summary, one that shows how many
observations are in each category, and, more important for us, how
many are missing (a lot).</p>
<p>All right, so there are 15 columns, so let’s investigate missingness
in our rows by looking at the columns 1 through 8 and then 9 through
15, so they all fit on the screen. Recall that you can <code>select</code>
columns by number:</p>
<div class="sourceCode" id="cb354"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb354-1" title="1">steak0 <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">select</span>(<span class="dv">1</span><span class="op">:</span><span class="dv">8</span>) <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">slice</span>(rows)</a></code></pre></div>
<pre><code>## # A tibble: 6 x 8
##   respondent_id lottery_a smoke alcohol gamble skydiving speed cheated
##           &lt;dbl&gt; &lt;lgl&gt;     &lt;lgl&gt; &lt;lgl&gt;   &lt;lgl&gt;  &lt;lgl&gt;     &lt;lgl&gt; &lt;lgl&gt;  
## 1    3234776895 FALSE     FALSE FALSE   FALSE  FALSE     FALSE FALSE  
## 2    3234776815 TRUE      TRUE  TRUE    FALSE  FALSE     TRUE  FALSE  
## 3    3234776702 FALSE     FALSE FALSE   FALSE  FALSE     FALSE FALSE  
## 4    3234763650 TRUE      FALSE FALSE   FALSE  FALSE     TRUE  FALSE  
## 5    3234763171 TRUE      FALSE TRUE    TRUE   FALSE     TRUE  FALSE  
## 6    3234762715 FALSE     FALSE FALSE   FALSE  FALSE     TRUE  FALSE</code></pre>
<p>and</p>
<div class="sourceCode" id="cb356"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb356-1" title="1">steak0 <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">select</span>(<span class="dv">9</span><span class="op">:</span><span class="dv">15</span>) <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">slice</span>(rows)</a></code></pre></div>
<pre><code>## # A tibble: 6 x 7
##   steak steak_prep  female age   hhold_income     educ               region     
##   &lt;lgl&gt; &lt;chr&gt;       &lt;lgl&gt;  &lt;chr&gt; &lt;chr&gt;            &lt;chr&gt;              &lt;chr&gt;      
## 1 TRUE  Medium rare TRUE   45-60 $0 - $24,999     Some college or A… West South…
## 2 TRUE  Medium      TRUE   45-60 $150,000+        Bachelor degree    New England
## 3 TRUE  Medium rare TRUE   &gt;60   $50,000 - $99,9… Graduate degree    Mountain   
## 4 FALSE &lt;NA&gt;        FALSE  45-60 $100,000 - $149… Some college or A… South Atla…
## 5 TRUE  Medium      FALSE  &gt;60   &lt;NA&gt;             Graduate degree    Pacific    
## 6 FALSE &lt;NA&gt;        FALSE  18-29 $50,000 - $99,9… Some college or A… West North…</code></pre>
<p>In this case, the first three rows have no missing values anywhere,
and the last three rows have exactly one missing value. This
corresponds to what we would expect, with <code>complete.cases</code>
identifying rows that have any missing values.</p>
<p>What we now need to do is to obtain a data frame that contains only
the rows with non-missing values. This can be done by saving the
result of <code>complete.cases</code> in a variable first; <code>filter</code>
can take anything that produces a true or a false for each row, and
will return the rows for which the thing it was fed was true.</p>
<div class="sourceCode" id="cb358"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb358-1" title="1">cc &lt;-<span class="st"> </span><span class="kw">complete.cases</span>(steak0)</a>
<a class="sourceLine" id="cb358-2" title="2">steak0 <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">filter</span>(cc) -&gt;<span class="st"> </span>steak.complete</a></code></pre></div>
<p>A quick check that we got rid of the missing values:</p>
<div class="sourceCode" id="cb359"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb359-1" title="1">steak.complete</a></code></pre></div>
<pre><code>## # A tibble: 331 x 15
##    respondent_id lottery_a smoke alcohol gamble skydiving speed cheated steak
##            &lt;dbl&gt; &lt;lgl&gt;     &lt;lgl&gt; &lt;lgl&gt;   &lt;lgl&gt;  &lt;lgl&gt;     &lt;lgl&gt; &lt;lgl&gt;   &lt;lgl&gt;
##  1    3234982343 TRUE      FALSE TRUE    FALSE  FALSE     FALSE FALSE   TRUE 
##  2    3234973379 TRUE      FALSE TRUE    TRUE   FALSE     TRUE  TRUE    TRUE 
##  3    3234972383 FALSE     TRUE  TRUE    TRUE   FALSE     TRUE  TRUE    TRUE 
##  4    3234958833 FALSE     FALSE TRUE    FALSE  FALSE     TRUE  TRUE    TRUE 
##  5    3234955240 TRUE      FALSE FALSE   FALSE  FALSE     TRUE  FALSE   TRUE 
##  6    3234955010 TRUE      FALSE TRUE    TRUE   TRUE      TRUE  FALSE   TRUE 
##  7    3234953052 TRUE      TRUE  TRUE    TRUE   FALSE     TRUE  FALSE   TRUE 
##  8    3234951249 FALSE     FALSE TRUE    TRUE   FALSE     FALSE FALSE   TRUE 
##  9    3234948883 FALSE     FALSE TRUE    FALSE  FALSE     TRUE  FALSE   TRUE 
## 10    3234948197 TRUE      FALSE FALSE   TRUE   FALSE     TRUE  FALSE   TRUE 
## # … with 321 more rows, and 6 more variables: steak_prep &lt;chr&gt;, female &lt;lgl&gt;,
## #   age &lt;chr&gt;, hhold_income &lt;chr&gt;, educ &lt;chr&gt;, region &lt;chr&gt;</code></pre>
<p>There are no missing values <em>there</em>. Of course, this is not a
proof, and there might be some missing values further down, but at
least it suggests that we might be good.</p>
<p>For proof, this is the easiest way I know:</p>
<div class="sourceCode" id="cb361"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb361-1" title="1">steak.complete <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb361-2" title="2"><span class="st">  </span><span class="kw">mutate</span>(<span class="kw">across</span>(<span class="kw">where</span>(is.character), <span class="op">~</span><span class="kw">factor</span>(.))) <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb361-3" title="3"><span class="st">  </span><span class="kw">summary</span>()</a></code></pre></div>
<pre><code>##  respondent_id       lottery_a         smoke          alcohol       
##  Min.   :3.235e+09   Mode :logical   Mode :logical   Mode :logical  
##  1st Qu.:3.235e+09   FALSE:171       FALSE:274       FALSE:65       
##  Median :3.235e+09   TRUE :160       TRUE :57        TRUE :266      
##  Mean   :3.235e+09                                                  
##  3rd Qu.:3.235e+09                                                  
##  Max.   :3.235e+09                                                  
##                                                                     
##    gamble        skydiving         speed          cheated         steak        
##  Mode :logical   Mode :logical   Mode :logical   Mode :logical   Mode:logical  
##  FALSE:158       FALSE:308       FALSE:28        FALSE:274       TRUE:331      
##  TRUE :173       TRUE :23        TRUE :303       TRUE :57                      
##                                                                                
##                                                                                
##                                                                                
##                                                                                
##        steak_prep    female           age                  hhold_income
##  Medium     :109   Mode :logical   &gt;60  :82   $0 - $24,999       : 37  
##  Medium rare:128   FALSE:174       18-29:70   $100,000 - $149,999: 66  
##  Medium Well: 56   TRUE :157       30-44:93   $150,000+          : 39  
##  Rare       : 18                   45-60:86   $25,000 - $49,999  : 55  
##  Well       : 20                              $50,000 - $99,999  :134  
##                                                                        
##                                                                        
##                                educ                    region  
##  Bachelor degree                 :120   South Atlantic    :68  
##  Graduate degree                 : 86   Pacific           :57  
##  High school degree              : 20   East North Central:48  
##  Less than high school degree    :  1   Middle Atlantic   :46  
##  Some college or Associate degree:104   West North Central:29  
##                                         Mountain          :24  
##                                         (Other)           :59</code></pre>
<p>If there were any missing values, they would be listed on the end of
the counts of observations for each level, or on the bottom of the
five-number sumamries. But there aren’t. So here’s your proof.</p>
<p><span class="math inline">\(\blacksquare\)</span></p>
<ol start="4" style="list-style-type: lower-alpha">
<li>Write the data into a <code>.csv</code> file, with a name like
<code>steak1.csv</code>. Open this file in a spreadsheet and (quickly)
verify that you have the right columns and no missing values.</li>
</ol>
<p>Solution</p>
<p>This is <code>write_csv</code>, using my output from
<code>drop_na</code>:</p>
<div class="sourceCode" id="cb363"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb363-1" title="1"><span class="kw">write_csv</span>(steak, <span class="st">&quot;steak1.csv&quot;</span>)</a></code></pre></div>
<p>Open up Excel, or whatever you have, and take a look. You should have
all the right columns, and, scrolling down, no visible missing values.</p>
<p><span class="math inline">\(\blacksquare\)</span></p>

</div>
</div>
<div class="footnotes">
<hr />
<ol start="36">
<li id="fn36"><p>I’m always amused at how Americans put all Asians into one group.<a href="logistic-regression-with-ordinal-response.html#fnref36" class="footnote-back">↩</a></p></li>
<li id="fn37"><p>I’m always amused at how Americans put all Asians into one group.<a href="logistic-regression-with-ordinal-response.html#fnref37" class="footnote-back">↩</a></p></li>
<li id="fn38"><p>That is <em>maths</em> as the apparently-plural of <em>math</em>, not as the British name for mathematics.<a href="logistic-regression-with-ordinal-response.html#fnref38" class="footnote-back">↩</a></p></li>
</ol>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="logistic-regression.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="logistic-regression-with-nominal-response.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/lunr.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": null,
"text": null
},
"history": {
"link": null,
"text": null
},
"view": {
"link": null,
"text": null
},
"download": ["pasias.pdf"],
"toc": {
"collapse": "subsection"
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
