<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

<meta charset="utf-8" />
<meta name="generator" content="pandoc" />
<meta name="viewport" content="width=device-width, initial-scale=1" />
<meta property="og:title" content="Chapter 12 Matched pairs t and sign test | Problems and Solutions in Applied Statistics" />
<meta property="og:type" content="book" />
<meta property="og:url" content="http://ritsokiguess.site/pasias" />

<meta property="og:description" content="A set of problems and solutions, in R, on various parts of applied statistics" />
<meta name="github-repo" content="nxskok/pasias" />

<meta name="author" content="Ken Butler" />

<meta name="date" content="2021-04-26" />

<script type="text/x-mathjax-config">
MathJax.Hub.Config({
  TeX: { equationNumbers: { autoNumber: "AMS" } }
});
</script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js" type="text/javascript"></script>

<meta name="description" content="A set of problems and solutions, in R, on various parts of applied statistics">

<title>Chapter 12 Matched pairs t and sign test | Problems and Solutions in Applied Statistics</title>

<script src="libs/header-attrs-2.7/header-attrs.js"></script>
<link href="libs/tufte-css-2015.12.29/tufte-fonts.css" rel="stylesheet" />
<link href="libs/tufte-css-2015.12.29/tufte-background.css" rel="stylesheet" />
<link href="libs/tufte-css-2015.12.29/tufte-italics.css" rel="stylesheet" />
<link href="libs/tufte-css-2015.12.29/tufte.css" rel="stylesheet" />
<script src="libs/accessible-code-block-0.0.1/empty-anchor.js"></script>
<link href="libs/pagedtable-1.1/css/pagedtable.css" rel="stylesheet" />
<script src="libs/pagedtable-1.1/js/pagedtable.js"></script>
<script src="libs/htmlwidgets-1.5.3/htmlwidgets.js"></script>
<script src="libs/jquery-1.12.4/jquery.min.js"></script>
<link href="libs/leaflet-1.3.1/leaflet.css" rel="stylesheet" />
<script src="libs/leaflet-1.3.1/leaflet.js"></script>
<link href="libs/leafletfix-1.0.0/leafletfix.css" rel="stylesheet" />
<script src="libs/proj4-2.6.2/proj4.min.js"></script>
<script src="libs/Proj4Leaflet-1.0.1/proj4leaflet.js"></script>
<link href="libs/rstudio_leaflet-1.3.1/rstudio_leaflet.css" rel="stylesheet" />
<script src="libs/leaflet-binding-2.0.4.1/leaflet.js"></script>


<style type="text/css">code{white-space: pre;}</style>
<style type="text/css">
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>


<link rel="stylesheet" href="toc.css" type="text/css" />

</head>

<body>



<div class="row">
<div class="col-sm-12">
<div id="TOC">
<ul>
<li><a href="index.html#introduction"><span class="toc-section-number">1</span> Introduction</a>
<ul>
<li><a href="index.html#packages-used-somewhere-in-this-book"><span class="toc-section-number">1.1</span> Packages used somewhere in this book</a></li>
</ul></li>
<li><a href="getting-used-to-r-and-r-studio.html#getting-used-to-r-and-r-studio"><span class="toc-section-number">2</span> Getting used to R and R Studio</a>
<ul>
<li><a href="getting-used-to-r-and-r-studio.html#getting-an-r-studio-cloud-account"><span class="toc-section-number">2.1</span> Getting an R Studio Cloud account</a></li>
<li><a href="getting-used-to-r-and-r-studio.html#getting-started"><span class="toc-section-number">2.2</span> Getting started</a></li>
<li><a href="getting-used-to-r-and-r-studio.html#reading-data-from-a-file"><span class="toc-section-number">2.3</span> Reading data from a file</a></li>
<li><a href="getting-used-to-r-and-r-studio.html#reading-files-different-ways"><span class="toc-section-number">2.4</span> Reading files different ways</a></li>
<li><a href="getting-used-to-r-and-r-studio.html#getting-an-r-studio-cloud-account-1"><span class="toc-section-number">2.5</span> Getting an R Studio Cloud account</a></li>
<li><a href="getting-used-to-r-and-r-studio.html#getting-started-1"><span class="toc-section-number">2.6</span> Getting started</a></li>
<li><a href="getting-used-to-r-and-r-studio.html#reading-data-from-a-file-1"><span class="toc-section-number">2.7</span> Reading data from a file</a></li>
<li><a href="getting-used-to-r-and-r-studio.html#reading-files-different-ways-1"><span class="toc-section-number">2.8</span> Reading files different ways</a></li>
</ul></li>
<li><a href="reading-in-data.html#reading-in-data"><span class="toc-section-number">3</span> Reading in data</a>
<ul>
<li><a href="reading-in-data.html#orange-juice"><span class="toc-section-number">3.1</span> Orange juice</a></li>
<li><a href="reading-in-data.html#making-soap"><span class="toc-section-number">3.2</span> Making soap</a></li>
<li><a href="reading-in-data.html#handling-shipments"><span class="toc-section-number">3.3</span> Handling shipments</a></li>
<li><a href="reading-in-data.html#orange-juice-1"><span class="toc-section-number">3.4</span> Orange juice</a></li>
<li><a href="reading-in-data.html#making-soap-1"><span class="toc-section-number">3.5</span> Making soap</a></li>
<li><a href="reading-in-data.html#handling-shipments-1"><span class="toc-section-number">3.6</span> Handling shipments</a></li>
</ul></li>
<li><a href="drawing-graphs.html#drawing-graphs"><span class="toc-section-number">4</span> Drawing graphs</a>
<ul>
<li><a href="drawing-graphs.html#orange-juice-2"><span class="toc-section-number">4.1</span> Orange juice</a></li>
<li><a href="drawing-graphs.html#making-soap-2"><span class="toc-section-number">4.2</span> Making soap</a></li>
<li><a href="drawing-graphs.html#handling-shipments-2"><span class="toc-section-number">4.3</span> Handling shipments</a></li>
<li><a href="drawing-graphs.html#orange-juice-3"><span class="toc-section-number">4.4</span> Orange juice</a></li>
<li><a href="drawing-graphs.html#making-soap-3"><span class="toc-section-number">4.5</span> Making soap</a></li>
<li><a href="drawing-graphs.html#handling-shipments-3"><span class="toc-section-number">4.6</span> Handling shipments</a></li>
</ul></li>
<li><a href="data-exploration.html#data-exploration"><span class="toc-section-number">5</span> Data exploration</a>
<ul>
<li><a href="data-exploration.html#north-carolina-births"><span class="toc-section-number">5.1</span> North Carolina births</a></li>
<li><a href="data-exploration.html#more-about-the-nc-births"><span class="toc-section-number">5.2</span> More about the NC births</a></li>
<li><a href="data-exploration.html#nenana-alaska"><span class="toc-section-number">5.3</span> Nenana, Alaska</a></li>
<li><a href="data-exploration.html#computerized-accounting"><span class="toc-section-number">5.4</span> Computerized accounting</a></li>
<li><a href="data-exploration.html#test-scores-in-two-classes"><span class="toc-section-number">5.5</span> Test scores in two classes</a></li>
<li><a href="data-exploration.html#north-carolina-births-1"><span class="toc-section-number">5.6</span> North Carolina births</a></li>
<li><a href="data-exploration.html#more-about-the-nc-births-1"><span class="toc-section-number">5.7</span> More about the NC births</a></li>
<li><a href="data-exploration.html#nenana-alaska-1"><span class="toc-section-number">5.8</span> Nenana, Alaska</a></li>
<li><a href="data-exploration.html#computerized-accounting-1"><span class="toc-section-number">5.9</span> Computerized accounting</a></li>
<li><a href="data-exploration.html#test-scores-in-two-classes-1"><span class="toc-section-number">5.10</span> Test scores in two classes</a></li>
</ul></li>
<li><a href="working-with-dataframes.html#working-with-dataframes"><span class="toc-section-number">6</span> Working with dataframes</a>
<ul>
<li><a href="working-with-dataframes.html#tidying-the-jays-data"><span class="toc-section-number">6.1</span> Tidying the Jays data</a></li>
<li><a href="working-with-dataframes.html#cars"><span class="toc-section-number">6.2</span> Cars</a></li>
<li><a href="working-with-dataframes.html#tidying-the-jays-data-1"><span class="toc-section-number">6.3</span> Tidying the Jays data</a></li>
<li><a href="working-with-dataframes.html#cars-1"><span class="toc-section-number">6.4</span> Cars</a></li>
</ul></li>
<li><a href="one-sample-inference.html#one-sample-inference"><span class="toc-section-number">7</span> One-sample inference</a>
<ul>
<li><a href="one-sample-inference.html#hunter-gatherers-in-australia"><span class="toc-section-number">7.1</span> Hunter-gatherers in Australia</a></li>
<li><a href="one-sample-inference.html#buses-to-boulder"><span class="toc-section-number">7.2</span> Buses to Boulder</a></li>
<li><a href="one-sample-inference.html#length-of-gestation-in-north-carolina"><span class="toc-section-number">7.3</span> Length of gestation in North Carolina</a></li>
<li><a href="one-sample-inference.html#inferring-ice-break-up-in-nenana"><span class="toc-section-number">7.4</span> Inferring ice break-up in Nenana</a></li>
<li><a href="one-sample-inference.html#hunter-gatherers-in-australia-1"><span class="toc-section-number">7.5</span> Hunter-gatherers in Australia</a></li>
<li><a href="one-sample-inference.html#buses-to-boulder-1"><span class="toc-section-number">7.6</span> Buses to Boulder</a></li>
<li><a href="one-sample-inference.html#length-of-gestation-in-north-carolina-1"><span class="toc-section-number">7.7</span> Length of gestation in North Carolina</a></li>
<li><a href="one-sample-inference.html#inferring-ice-break-up-in-nenana-1"><span class="toc-section-number">7.8</span> Inferring ice break-up in Nenana</a></li>
</ul></li>
<li><a href="two-sample-inference.html#two-sample-inference"><span class="toc-section-number">8</span> Two-sample inference</a>
<ul>
<li><a href="two-sample-inference.html#children-and-electronic-devices"><span class="toc-section-number">8.1</span> Children and electronic devices</a></li>
<li><a href="two-sample-inference.html#parking-close-to-the-curb"><span class="toc-section-number">8.2</span> Parking close to the curb</a></li>
<li><a href="two-sample-inference.html#bell-peppers-and-too-much-water"><span class="toc-section-number">8.3</span> Bell peppers and too much water</a></li>
<li><a href="two-sample-inference.html#exercise-and-anxiety-and-bullying-mice"><span class="toc-section-number">8.4</span> Exercise and anxiety and bullying mice</a></li>
<li><a href="two-sample-inference.html#diet-and-growth-in-boys"><span class="toc-section-number">8.5</span> Diet and growth in boys</a></li>
<li><a href="two-sample-inference.html#children-and-electronic-devices-1"><span class="toc-section-number">8.6</span> Children and electronic devices</a></li>
<li><a href="two-sample-inference.html#parking-close-to-the-curb-1"><span class="toc-section-number">8.7</span> Parking close to the curb</a></li>
<li><a href="two-sample-inference.html#bell-peppers-and-too-much-water-1"><span class="toc-section-number">8.8</span> Bell peppers and too much water</a></li>
<li><a href="two-sample-inference.html#exercise-and-anxiety-and-bullying-mice-1"><span class="toc-section-number">8.9</span> Exercise and anxiety and bullying mice</a></li>
<li><a href="two-sample-inference.html#diet-and-growth-in-boys-1"><span class="toc-section-number">8.10</span> Diet and growth in boys</a></li>
</ul></li>
<li><a href="power-and-sample-size.html#power-and-sample-size"><span class="toc-section-number">9</span> Power and sample size</a>
<ul>
<li><a href="power-and-sample-size.html#simulating-power"><span class="toc-section-number">9.1</span> Simulating power</a></li>
<li><a href="power-and-sample-size.html#calculating-power-and-sample-size-for-estimating-mean"><span class="toc-section-number">9.2</span> Calculating power and sample size for estimating mean</a></li>
<li><a href="power-and-sample-size.html#simulating-power-for-proportions"><span class="toc-section-number">9.3</span> Simulating power for proportions</a></li>
<li><a href="power-and-sample-size.html#simulating-power-1"><span class="toc-section-number">9.4</span> Simulating power</a></li>
<li><a href="power-and-sample-size.html#calculating-power-and-sample-size-for-estimating-mean-1"><span class="toc-section-number">9.5</span> Calculating power and sample size for estimating mean</a></li>
<li><a href="power-and-sample-size.html#simulating-power-for-proportions-1"><span class="toc-section-number">9.6</span> Simulating power for proportions</a></li>
</ul></li>
<li><a href="the-sign-test.html#the-sign-test"><span class="toc-section-number">10</span> The sign test</a>
<ul>
<li><a href="the-sign-test.html#running-a-maze"><span class="toc-section-number">10.1</span> Running a maze</a></li>
<li><a href="the-sign-test.html#chocolate-chips"><span class="toc-section-number">10.2</span> Chocolate chips</a></li>
<li><a href="the-sign-test.html#the-power-of-the-sign-test"><span class="toc-section-number">10.3</span> The power of the sign test</a></li>
<li><a href="the-sign-test.html#running-a-maze-1"><span class="toc-section-number">10.4</span> Running a maze</a></li>
<li><a href="the-sign-test.html#chocolate-chips-1"><span class="toc-section-number">10.5</span> Chocolate chips</a></li>
<li><a href="the-sign-test.html#the-power-of-the-sign-test-1"><span class="toc-section-number">10.6</span> The power of the sign test</a></li>
</ul></li>
<li><a href="moods-median-test.html#moods-median-test"><span class="toc-section-number">11</span> Mood’s median test</a>
<ul>
<li><a href="moods-median-test.html#sugar-in-breakfast-cereals"><span class="toc-section-number">11.1</span> Sugar in breakfast cereals</a></li>
<li><a href="moods-median-test.html#fear-of-math"><span class="toc-section-number">11.2</span> Fear of math</a></li>
<li><a href="moods-median-test.html#medical-instructions"><span class="toc-section-number">11.3</span> Medical instructions</a></li>
<li><a href="moods-median-test.html#sugar-in-breakfast-cereals-1"><span class="toc-section-number">11.4</span> Sugar in breakfast cereals</a></li>
<li><a href="moods-median-test.html#fear-of-math-1"><span class="toc-section-number">11.5</span> Fear of math</a></li>
<li><a href="moods-median-test.html#medical-instructions-1"><span class="toc-section-number">11.6</span> Medical instructions</a></li>
</ul></li>
<li><a href="matched-pairs-t-and-sign-test.html#matched-pairs-t-and-sign-test"><span class="toc-section-number">12</span> Matched pairs t and sign test</a>
<ul>
<li><a href="matched-pairs-t-and-sign-test.html#measuring-body-fat"><span class="toc-section-number">12.1</span> Measuring body fat</a></li>
<li><a href="matched-pairs-t-and-sign-test.html#throwing-baseballs-and-softballs"><span class="toc-section-number">12.2</span> Throwing baseballs and softballs</a></li>
<li><a href="matched-pairs-t-and-sign-test.html#throwing-baseballs-and-softballs-again"><span class="toc-section-number">12.3</span> Throwing baseballs and softballs, again</a></li>
<li><a href="matched-pairs-t-and-sign-test.html#changes-in-salary"><span class="toc-section-number">12.4</span> Changes in salary</a></li>
<li><a href="matched-pairs-t-and-sign-test.html#body-fat-revisited"><span class="toc-section-number">12.5</span> Body fat revisited</a></li>
<li><a href="matched-pairs-t-and-sign-test.html#measuring-body-fat-1"><span class="toc-section-number">12.6</span> Measuring body fat</a></li>
<li><a href="matched-pairs-t-and-sign-test.html#throwing-baseballs-and-softballs-1"><span class="toc-section-number">12.7</span> Throwing baseballs and softballs</a></li>
<li><a href="matched-pairs-t-and-sign-test.html#throwing-baseballs-and-softballs-again-1"><span class="toc-section-number">12.8</span> Throwing baseballs and softballs, again</a></li>
<li><a href="matched-pairs-t-and-sign-test.html#changes-in-salary-1"><span class="toc-section-number">12.9</span> Changes in salary</a></li>
<li><a href="matched-pairs-t-and-sign-test.html#body-fat-revisited-1"><span class="toc-section-number">12.10</span> Body fat revisited</a></li>
</ul></li>
<li><a href="normal-quantile-plots.html#normal-quantile-plots"><span class="toc-section-number">13</span> Normal quantile plots</a>
<ul>
<li><a href="normal-quantile-plots.html#lengths-of-heliconia-flowers"><span class="toc-section-number">13.1</span> Lengths of heliconia flowers</a></li>
<li><a href="normal-quantile-plots.html#ferritin-and-normality"><span class="toc-section-number">13.2</span> Ferritin and normality</a></li>
<li><a href="normal-quantile-plots.html#lengths-of-heliconia-flowers-1"><span class="toc-section-number">13.3</span> Lengths of heliconia flowers</a></li>
<li><a href="normal-quantile-plots.html#ferritin-and-normality-1"><span class="toc-section-number">13.4</span> Ferritin and normality</a></li>
</ul></li>
<li><a href="analysis-of-variance.html#analysis-of-variance"><span class="toc-section-number">14</span> Analysis of variance</a>
<ul>
<li><a href="analysis-of-variance.html#movie-ratings-and-lengths"><span class="toc-section-number">14.1</span> Movie ratings and lengths</a></li>
<li><a href="analysis-of-variance.html#deer-and-how-much-they-eat"><span class="toc-section-number">14.2</span> Deer and how much they eat</a></li>
<li><a href="analysis-of-variance.html#movie-ratings-again"><span class="toc-section-number">14.3</span> Movie ratings again</a></li>
<li><a href="analysis-of-variance.html#atomic-weight-of-carbon"><span class="toc-section-number">14.4</span> Atomic weight of carbon</a></li>
<li><a href="analysis-of-variance.html#can-caffeine-improve-your-performance-on-a-test"><span class="toc-section-number">14.5</span> Can caffeine improve your performance on a test?</a></li>
<li><a href="analysis-of-variance.html#movie-ratings-and-lengths-1"><span class="toc-section-number">14.6</span> Movie ratings and lengths</a></li>
<li><a href="analysis-of-variance.html#deer-and-how-much-they-eat-1"><span class="toc-section-number">14.7</span> Deer and how much they eat</a></li>
<li><a href="analysis-of-variance.html#movie-ratings-again-1"><span class="toc-section-number">14.8</span> Movie ratings again</a></li>
<li><a href="analysis-of-variance.html#atomic-weight-of-carbon-1"><span class="toc-section-number">14.9</span> Atomic weight of carbon</a></li>
<li><a href="analysis-of-variance.html#can-caffeine-improve-your-performance-on-a-test-1"><span class="toc-section-number">14.10</span> Can caffeine improve your performance on a test?</a></li>
</ul></li>
<li><a href="writing-reports.html#writing-reports"><span class="toc-section-number">15</span> Writing reports</a>
<ul>
<li><a href="writing-reports.html#atomic-weight-of-carbon-2"><span class="toc-section-number">15.1</span> Atomic weight of carbon</a></li>
<li><a href="writing-reports.html#sparrowhawks"><span class="toc-section-number">15.2</span> Sparrowhawks</a></li>
<li><a href="writing-reports.html#atomic-weight-of-carbon-3"><span class="toc-section-number">15.3</span> Atomic weight of carbon</a></li>
<li><a href="writing-reports.html#sparrowhawks-1"><span class="toc-section-number">15.4</span> Sparrowhawks</a></li>
</ul></li>
<li><a href="tidying-data.html#tidying-data"><span class="toc-section-number">16</span> Tidying data</a>
<ul>
<li><a href="tidying-data.html#baseball-and-softball-spaghetti"><span class="toc-section-number">16.1</span> Baseball and softball spaghetti</a></li>
<li><a href="tidying-data.html#ethanol-and-sleep-time-in-rats"><span class="toc-section-number">16.2</span> Ethanol and sleep time in rats</a></li>
<li><a href="tidying-data.html#growth-of-tomatoes"><span class="toc-section-number">16.3</span> Growth of tomatoes</a></li>
<li><a href="tidying-data.html#pain-relief-in-migraine-headaches-again"><span class="toc-section-number">16.4</span> Pain relief in migraine headaches (again)</a></li>
<li><a href="tidying-data.html#location-species-and-disease-in-plants"><span class="toc-section-number">16.5</span> Location, species and disease in plants</a></li>
<li><a href="tidying-data.html#mating-songs-in-crickets"><span class="toc-section-number">16.6</span> Mating songs in crickets</a></li>
<li><a href="tidying-data.html#number-1-songs"><span class="toc-section-number">16.7</span> Number 1 songs</a></li>
<li><a href="tidying-data.html#bikes-on-college"><span class="toc-section-number">16.8</span> Bikes on College</a></li>
<li><a href="tidying-data.html#feeling-the-heat"><span class="toc-section-number">16.9</span> Feeling the heat</a></li>
<li><a href="tidying-data.html#baseball-and-softball-spaghetti-1"><span class="toc-section-number">16.10</span> Baseball and softball spaghetti</a></li>
<li><a href="tidying-data.html#ethanol-and-sleep-time-in-rats-1"><span class="toc-section-number">16.11</span> Ethanol and sleep time in rats</a></li>
<li><a href="tidying-data.html#growth-of-tomatoes-1"><span class="toc-section-number">16.12</span> Growth of tomatoes</a></li>
<li><a href="tidying-data.html#pain-relief-in-migraine-headaches-again-1"><span class="toc-section-number">16.13</span> Pain relief in migraine headaches (again)</a></li>
<li><a href="tidying-data.html#location-species-and-disease-in-plants-1"><span class="toc-section-number">16.14</span> Location, species and disease in plants</a></li>
<li><a href="tidying-data.html#mating-songs-in-crickets-1"><span class="toc-section-number">16.15</span> Mating songs in crickets</a></li>
<li><a href="tidying-data.html#number-1-songs-1"><span class="toc-section-number">16.16</span> Number 1 songs</a></li>
<li><a href="tidying-data.html#bikes-on-college-1"><span class="toc-section-number">16.17</span> Bikes on College</a></li>
<li><a href="tidying-data.html#feeling-the-heat-1"><span class="toc-section-number">16.18</span> Feeling the heat</a></li>
</ul></li>
<li><a href="simple-regression.html#simple-regression"><span class="toc-section-number">17</span> Simple regression</a>
<ul>
<li><a href="simple-regression.html#rainfall-in-california"><span class="toc-section-number">17.1</span> Rainfall in California</a></li>
<li><a href="simple-regression.html#carbon-monoxide-in-cigarettes"><span class="toc-section-number">17.2</span> Carbon monoxide in cigarettes</a></li>
<li><a href="simple-regression.html#maximal-oxygen-uptake-in-young-boys"><span class="toc-section-number">17.3</span> Maximal oxygen uptake in young boys</a></li>
<li><a href="simple-regression.html#facebook-friends-and-grey-matter"><span class="toc-section-number">17.4</span> Facebook friends and grey matter</a></li>
<li><a href="simple-regression.html#endogenous-nitrogen-excretion-in-carp"><span class="toc-section-number">17.5</span> Endogenous nitrogen excretion in carp</a></li>
<li><a href="simple-regression.html#salaries-of-social-workers"><span class="toc-section-number">17.6</span> Salaries of social workers</a></li>
<li><a href="simple-regression.html#predicting-volume-of-wood-in-pine-trees"><span class="toc-section-number">17.7</span> Predicting volume of wood in pine trees</a></li>
<li><a href="simple-regression.html#tortoise-shells-and-eggs"><span class="toc-section-number">17.8</span> Tortoise shells and eggs</a></li>
<li><a href="simple-regression.html#roller-coasters"><span class="toc-section-number">17.9</span> Roller coasters</a></li>
<li><a href="simple-regression.html#running-and-blood-sugar"><span class="toc-section-number">17.10</span> Running and blood sugar</a></li>
<li><a href="simple-regression.html#calories-and-fat-in-pizza"><span class="toc-section-number">17.11</span> Calories and fat in pizza</a></li>
<li><a href="simple-regression.html#where-should-the-fire-stations-be"><span class="toc-section-number">17.12</span> Where should the fire stations be?</a></li>
<li><a href="simple-regression.html#rainfall-in-california-1"><span class="toc-section-number">17.13</span> Rainfall in California</a></li>
<li><a href="simple-regression.html#carbon-monoxide-in-cigarettes-1"><span class="toc-section-number">17.14</span> Carbon monoxide in cigarettes</a></li>
<li><a href="simple-regression.html#maximal-oxygen-uptake-in-young-boys-1"><span class="toc-section-number">17.15</span> Maximal oxygen uptake in young boys</a></li>
<li><a href="simple-regression.html#facebook-friends-and-grey-matter-1"><span class="toc-section-number">17.16</span> Facebook friends and grey matter</a></li>
<li><a href="simple-regression.html#endogenous-nitrogen-excretion-in-carp-1"><span class="toc-section-number">17.17</span> Endogenous nitrogen excretion in carp</a></li>
<li><a href="simple-regression.html#salaries-of-social-workers-1"><span class="toc-section-number">17.18</span> Salaries of social workers</a></li>
<li><a href="simple-regression.html#predicting-volume-of-wood-in-pine-trees-1"><span class="toc-section-number">17.19</span> Predicting volume of wood in pine trees</a></li>
<li><a href="simple-regression.html#tortoise-shells-and-eggs-1"><span class="toc-section-number">17.20</span> Tortoise shells and eggs</a></li>
<li><a href="simple-regression.html#roller-coasters-1"><span class="toc-section-number">17.21</span> Roller coasters</a></li>
<li><a href="simple-regression.html#running-and-blood-sugar-1"><span class="toc-section-number">17.22</span> Running and blood sugar</a></li>
<li><a href="simple-regression.html#calories-and-fat-in-pizza-1"><span class="toc-section-number">17.23</span> Calories and fat in pizza</a></li>
<li><a href="simple-regression.html#where-should-the-fire-stations-be-1"><span class="toc-section-number">17.24</span> Where should the fire stations be?</a></li>
</ul></li>
<li><a href="multiple-regression.html#multiple-regression"><span class="toc-section-number">18</span> Multiple regression</a>
<ul>
<li><a href="multiple-regression.html#being-satisfied-with-hospital"><span class="toc-section-number">18.1</span> Being satisfied with hospital</a></li>
<li><a href="multiple-regression.html#handling-shipments-of-chemicals"><span class="toc-section-number">18.2</span> Handling shipments of chemicals</a></li>
<li><a href="multiple-regression.html#salaries-of-mathematicians"><span class="toc-section-number">18.3</span> Salaries of mathematicians</a></li>
<li><a href="multiple-regression.html#predicting-gpa-of-computer-science-students"><span class="toc-section-number">18.4</span> Predicting GPA of computer science students</a></li>
<li><a href="multiple-regression.html#being-satisfied-with-hospital-1"><span class="toc-section-number">18.5</span> Being satisfied with hospital</a></li>
<li><a href="multiple-regression.html#handling-shipments-of-chemicals-1"><span class="toc-section-number">18.6</span> Handling shipments of chemicals</a></li>
<li><a href="multiple-regression.html#salaries-of-mathematicians-1"><span class="toc-section-number">18.7</span> Salaries of mathematicians</a></li>
<li><a href="multiple-regression.html#predicting-gpa-of-computer-science-students-1"><span class="toc-section-number">18.8</span> Predicting GPA of computer science students</a></li>
</ul></li>
<li><a href="regression-with-categorical-variables.html#regression-with-categorical-variables"><span class="toc-section-number">19</span> Regression with categorical variables</a>
<ul>
<li><a href="regression-with-categorical-variables.html#crickets-revisited"><span class="toc-section-number">19.1</span> Crickets revisited</a></li>
<li><a href="regression-with-categorical-variables.html#crickets-revisited-1"><span class="toc-section-number">19.2</span> Crickets revisited</a></li>
</ul></li>
<li><a href="dates-and-times.html#dates-and-times"><span class="toc-section-number">20</span> Dates and times</a>
<ul>
<li><a href="dates-and-times.html#growth-of-mizuna-lettuce-seeds"><span class="toc-section-number">20.1</span> Growth of Mizuna lettuce seeds</a></li>
<li><a href="dates-and-times.html#types-of-childbirth"><span class="toc-section-number">20.2</span> Types of childbirth</a></li>
<li><a href="dates-and-times.html#wolves-and-caribou"><span class="toc-section-number">20.3</span> Wolves and caribou</a></li>
<li><a href="dates-and-times.html#dealing-with-dates-in-the-worcester-heart-attack-study"><span class="toc-section-number">20.4</span> Dealing with dates in the Worcester Heart Attack study</a></li>
<li><a href="dates-and-times.html#growth-of-mizuna-lettuce-seeds-1"><span class="toc-section-number">20.5</span> Growth of Mizuna lettuce seeds</a></li>
<li><a href="dates-and-times.html#types-of-childbirth-1"><span class="toc-section-number">20.6</span> Types of childbirth</a></li>
<li><a href="dates-and-times.html#wolves-and-caribou-1"><span class="toc-section-number">20.7</span> Wolves and caribou</a></li>
<li><a href="dates-and-times.html#dealing-with-dates-in-the-worcester-heart-attack-study-1"><span class="toc-section-number">20.8</span> Dealing with dates in the Worcester Heart Attack study</a></li>
</ul></li>
<li><a href="functions.html#functions"><span class="toc-section-number">21</span> Functions</a>
<ul>
<li><a href="functions.html#making-some-r-functions"><span class="toc-section-number">21.1</span> Making some R functions</a></li>
<li><a href="functions.html#the-collatz-sequence"><span class="toc-section-number">21.2</span> The Collatz sequence</a></li>
<li><a href="functions.html#making-some-r-functions-1"><span class="toc-section-number">21.3</span> Making some R functions</a></li>
<li><a href="functions.html#the-collatz-sequence-1"><span class="toc-section-number">21.4</span> The Collatz sequence</a></li>
</ul></li>
<li><a href="the-bootstrap.html#the-bootstrap"><span class="toc-section-number">22</span> The Bootstrap</a>
<ul>
<li><a href="the-bootstrap.html#air-conditioning-failures"><span class="toc-section-number">22.1</span> Air conditioning failures</a></li>
<li><a href="the-bootstrap.html#air-conditioning-failures-bootstrapping-the-median"><span class="toc-section-number">22.2</span> Air conditioning failures: bootstrapping the median</a></li>
<li><a href="the-bootstrap.html#air-conditioning-failures-1"><span class="toc-section-number">22.3</span> Air conditioning failures</a></li>
<li><a href="the-bootstrap.html#air-conditioning-failures-bootstrapping-the-median-1"><span class="toc-section-number">22.4</span> Air conditioning failures: bootstrapping the median</a></li>
</ul></li>
<li><a href="bayesian-statistics-with-stan.html#bayesian-statistics-with-stan"><span class="toc-section-number">23</span> Bayesian Statistics with Stan</a>
<ul>
<li><a href="bayesian-statistics-with-stan.html#estimating-proportion-in-favour-from-a-survey"><span class="toc-section-number">23.1</span> Estimating proportion in favour from a survey</a></li>
<li><a href="bayesian-statistics-with-stan.html#bayesian-regression"><span class="toc-section-number">23.2</span> Bayesian regression</a></li>
<li><a href="bayesian-statistics-with-stan.html#estimating-proportion-in-favour-from-a-survey-1"><span class="toc-section-number">23.3</span> Estimating proportion in favour from a survey</a></li>
<li><a href="bayesian-statistics-with-stan.html#bayesian-regression-1"><span class="toc-section-number">23.4</span> Bayesian regression</a></li>
</ul></li>
<li><a href="logistic-regression.html#logistic-regression"><span class="toc-section-number">24</span> Logistic regression</a>
<ul>
<li><a href="logistic-regression.html#finding-wolf-spiders-on-the-beach"><span class="toc-section-number">24.1</span> Finding wolf spiders on the beach</a></li>
<li><a href="logistic-regression.html#killing-aphids"><span class="toc-section-number">24.2</span> Killing aphids</a></li>
<li><a href="logistic-regression.html#the-effects-of-substance-a"><span class="toc-section-number">24.3</span> The effects of Substance A</a></li>
<li><a href="logistic-regression.html#what-makes-an-animal-get-infected"><span class="toc-section-number">24.4</span> What makes an animal get infected?</a></li>
<li><a href="logistic-regression.html#the-brain-of-a-cat"><span class="toc-section-number">24.5</span> The brain of a cat</a></li>
<li><a href="logistic-regression.html#how-not-to-get-heart-disease"><span class="toc-section-number">24.6</span> How not to get heart disease</a></li>
<li><a href="logistic-regression.html#successful-breastfeeding"><span class="toc-section-number">24.7</span> Successful breastfeeding</a></li>
<li><a href="logistic-regression.html#making-it-over-the-mountains"><span class="toc-section-number">24.8</span> Making it over the mountains</a></li>
<li><a href="logistic-regression.html#who-needs-the-most-intensive-care"><span class="toc-section-number">24.9</span> Who needs the most intensive care?</a></li>
<li><a href="logistic-regression.html#go-away-and-dont-come-back"><span class="toc-section-number">24.10</span> Go away and don’t come back!</a></li>
<li><a href="logistic-regression.html#finding-wolf-spiders-on-the-beach-1"><span class="toc-section-number">24.11</span> Finding wolf spiders on the beach</a></li>
<li><a href="logistic-regression.html#killing-aphids-1"><span class="toc-section-number">24.12</span> Killing aphids</a></li>
<li><a href="logistic-regression.html#the-effects-of-substance-a-1"><span class="toc-section-number">24.13</span> The effects of Substance A</a></li>
<li><a href="logistic-regression.html#what-makes-an-animal-get-infected-1"><span class="toc-section-number">24.14</span> What makes an animal get infected?</a></li>
<li><a href="logistic-regression.html#the-brain-of-a-cat-1"><span class="toc-section-number">24.15</span> The brain of a cat</a></li>
<li><a href="logistic-regression.html#how-not-to-get-heart-disease-1"><span class="toc-section-number">24.16</span> How not to get heart disease</a></li>
<li><a href="logistic-regression.html#successful-breastfeeding-1"><span class="toc-section-number">24.17</span> Successful breastfeeding</a></li>
<li><a href="logistic-regression.html#making-it-over-the-mountains-1"><span class="toc-section-number">24.18</span> Making it over the mountains</a></li>
<li><a href="logistic-regression.html#who-needs-the-most-intensive-care-1"><span class="toc-section-number">24.19</span> Who needs the most intensive care?</a></li>
<li><a href="logistic-regression.html#go-away-and-dont-come-back-1"><span class="toc-section-number">24.20</span> Go away and don’t come back!</a></li>
</ul></li>
<li><a href="logistic-regression-with-ordinal-response.html#logistic-regression-with-ordinal-response"><span class="toc-section-number">25</span> Logistic regression with ordinal response</a>
<ul>
<li><a href="logistic-regression-with-ordinal-response.html#do-you-like-your-mobile-phone"><span class="toc-section-number">25.1</span> Do you like your mobile phone?</a></li>
<li><a href="logistic-regression-with-ordinal-response.html#finding-non-missing-values"><span class="toc-section-number">25.2</span> Finding non-missing values</a></li>
<li><a href="logistic-regression-with-ordinal-response.html#high-school-and-beyond"><span class="toc-section-number">25.3</span> High School and Beyond</a></li>
<li><a href="logistic-regression-with-ordinal-response.html#how-do-you-like-your-steak"><span class="toc-section-number">25.4</span> How do you like your steak?</a></li>
<li><a href="logistic-regression-with-ordinal-response.html#how-do-you-like-your-steak-the-data"><span class="toc-section-number">25.5</span> How do you like your steak – the data</a></li>
<li><a href="logistic-regression-with-ordinal-response.html#do-you-like-your-mobile-phone-1"><span class="toc-section-number">25.6</span> Do you like your mobile phone?</a></li>
<li><a href="logistic-regression-with-ordinal-response.html#finding-non-missing-values-1"><span class="toc-section-number">25.7</span> Finding non-missing values</a></li>
<li><a href="logistic-regression-with-ordinal-response.html#high-school-and-beyond-1"><span class="toc-section-number">25.8</span> High School and Beyond</a></li>
<li><a href="logistic-regression-with-ordinal-response.html#how-do-you-like-your-steak-1"><span class="toc-section-number">25.9</span> How do you like your steak?</a></li>
<li><a href="logistic-regression-with-ordinal-response.html#how-do-you-like-your-steak-the-data-1"><span class="toc-section-number">25.10</span> How do you like your steak – the data</a></li>
</ul></li>
<li><a href="logistic-regression-with-nominal-response.html#logistic-regression-with-nominal-response"><span class="toc-section-number">26</span> Logistic regression with nominal response</a>
<ul>
<li><a href="logistic-regression-with-nominal-response.html#finding-non-missing-values-2"><span class="toc-section-number">26.1</span> Finding non-missing values</a></li>
<li><a href="logistic-regression-with-nominal-response.html#european-social-survey-and-voting"><span class="toc-section-number">26.2</span> European Social Survey and voting</a></li>
<li><a href="logistic-regression-with-nominal-response.html#alligator-food"><span class="toc-section-number">26.3</span> Alligator food</a></li>
<li><a href="logistic-regression-with-nominal-response.html#crimes-in-san-francisco"><span class="toc-section-number">26.4</span> Crimes in San Francisco</a></li>
<li><a href="logistic-regression-with-nominal-response.html#crimes-in-san-francisco-the-data"><span class="toc-section-number">26.5</span> Crimes in San Francisco – the data</a></li>
<li><a href="logistic-regression-with-nominal-response.html#what-sports-do-these-athletes-play"><span class="toc-section-number">26.6</span> What sports do these athletes play?</a></li>
<li><a href="logistic-regression-with-nominal-response.html#finding-non-missing-values-3"><span class="toc-section-number">26.7</span> Finding non-missing values</a></li>
<li><a href="logistic-regression-with-nominal-response.html#european-social-survey-and-voting-1"><span class="toc-section-number">26.8</span> European Social Survey and voting</a></li>
<li><a href="logistic-regression-with-nominal-response.html#alligator-food-1"><span class="toc-section-number">26.9</span> Alligator food</a></li>
<li><a href="logistic-regression-with-nominal-response.html#crimes-in-san-francisco-1"><span class="toc-section-number">26.10</span> Crimes in San Francisco</a></li>
<li><a href="logistic-regression-with-nominal-response.html#crimes-in-san-francisco-the-data-1"><span class="toc-section-number">26.11</span> Crimes in San Francisco – the data</a></li>
<li><a href="logistic-regression-with-nominal-response.html#what-sports-do-these-athletes-play-1"><span class="toc-section-number">26.12</span> What sports do these athletes play?</a></li>
</ul></li>
<li><a href="survival-analysis.html#survival-analysis"><span class="toc-section-number">27</span> Survival analysis</a>
<ul>
<li><a href="survival-analysis.html#the-worcester-survey"><span class="toc-section-number">27.1</span> The Worcester survey</a></li>
<li><a href="survival-analysis.html#drug-treatment-programs"><span class="toc-section-number">27.2</span> Drug treatment programs</a></li>
<li><a href="survival-analysis.html#multiple-myeloma"><span class="toc-section-number">27.3</span> Multiple myeloma</a></li>
<li><a href="survival-analysis.html#ovarian-cancer"><span class="toc-section-number">27.4</span> Ovarian cancer</a></li>
<li><a href="survival-analysis.html#the-worcester-survey-1"><span class="toc-section-number">27.5</span> The Worcester survey</a></li>
<li><a href="survival-analysis.html#drug-treatment-programs-1"><span class="toc-section-number">27.6</span> Drug treatment programs</a></li>
<li><a href="survival-analysis.html#multiple-myeloma-1"><span class="toc-section-number">27.7</span> Multiple myeloma</a></li>
<li><a href="survival-analysis.html#ovarian-cancer-1"><span class="toc-section-number">27.8</span> Ovarian cancer</a></li>
</ul></li>
<li><a href="analysis-of-variance-revisited.html#analysis-of-variance-revisited"><span class="toc-section-number">28</span> Analysis of variance revisited</a>
<ul>
<li><a href="analysis-of-variance-revisited.html#acid-rain"><span class="toc-section-number">28.1</span> Acid rain</a></li>
<li><a href="analysis-of-variance-revisited.html#treating-hay-fever"><span class="toc-section-number">28.2</span> Treating hay fever</a></li>
<li><a href="analysis-of-variance-revisited.html#focused-comparisons-of-the-effect-of-caffeine"><span class="toc-section-number">28.3</span> Focused comparisons of the effect of caffeine</a></li>
<li><a href="analysis-of-variance-revisited.html#who-studies-the-most-outside-class"><span class="toc-section-number">28.4</span> Who studies the most outside class?</a></li>
<li><a href="analysis-of-variance-revisited.html#mental-context"><span class="toc-section-number">28.5</span> Mental context</a></li>
<li><a href="analysis-of-variance-revisited.html#trying-on-shirts"><span class="toc-section-number">28.6</span> Trying on shirts</a></li>
<li><a href="analysis-of-variance-revisited.html#acid-rain-1"><span class="toc-section-number">28.7</span> Acid rain</a></li>
<li><a href="analysis-of-variance-revisited.html#treating-hay-fever-1"><span class="toc-section-number">28.8</span> Treating hay fever</a></li>
<li><a href="analysis-of-variance-revisited.html#focused-comparisons-of-the-effect-of-caffeine-1"><span class="toc-section-number">28.9</span> Focused comparisons of the effect of caffeine</a></li>
<li><a href="analysis-of-variance-revisited.html#who-studies-the-most-outside-class-1"><span class="toc-section-number">28.10</span> Who studies the most outside class?</a></li>
<li><a href="analysis-of-variance-revisited.html#mental-context-1"><span class="toc-section-number">28.11</span> Mental context</a></li>
<li><a href="analysis-of-variance-revisited.html#trying-on-shirts-1"><span class="toc-section-number">28.12</span> Trying on shirts</a></li>
</ul></li>
<li><a href="analysis-of-covariance.html#analysis-of-covariance"><span class="toc-section-number">29</span> Analysis of covariance</a>
<ul>
<li><a href="analysis-of-covariance.html#productivity-and-research-and-development"><span class="toc-section-number">29.1</span> Productivity and research-and-development</a></li>
<li><a href="analysis-of-covariance.html#treating-leprosy"><span class="toc-section-number">29.2</span> Treating leprosy</a></li>
<li><a href="analysis-of-covariance.html#productivity-and-research-and-development-1"><span class="toc-section-number">29.3</span> Productivity and research-and-development</a></li>
<li><a href="analysis-of-covariance.html#treating-leprosy-1"><span class="toc-section-number">29.4</span> Treating leprosy</a></li>
</ul></li>
<li><a href="multivariate-analysis-of-variance.html#multivariate-analysis-of-variance"><span class="toc-section-number">30</span> Multivariate analysis of variance</a>
<ul>
<li><a href="multivariate-analysis-of-variance.html#fabricated-data"><span class="toc-section-number">30.1</span> Fabricated data</a></li>
<li><a href="multivariate-analysis-of-variance.html#do-characteristics-of-urine-depend-on-obesity"><span class="toc-section-number">30.2</span> Do characteristics of urine depend on obesity?</a></li>
<li><a href="multivariate-analysis-of-variance.html#how-do-height-and-weight-depend-on-sport-played-by-elite-athletes"><span class="toc-section-number">30.3</span> How do height and weight depend on sport played by elite athletes?</a></li>
<li><a href="multivariate-analysis-of-variance.html#fabricated-data-1"><span class="toc-section-number">30.4</span> Fabricated data</a></li>
<li><a href="multivariate-analysis-of-variance.html#do-characteristics-of-urine-depend-on-obesity-1"><span class="toc-section-number">30.5</span> Do characteristics of urine depend on obesity?</a></li>
<li><a href="multivariate-analysis-of-variance.html#how-do-height-and-weight-depend-on-sport-played-by-elite-athletes-1"><span class="toc-section-number">30.6</span> How do height and weight depend on sport played by elite athletes?</a></li>
</ul></li>
<li><a href="repeated-measures.html#repeated-measures"><span class="toc-section-number">31</span> Repeated measures</a>
<ul>
<li><a href="repeated-measures.html#effect-of-drug-on-rat-weight"><span class="toc-section-number">31.1</span> Effect of drug on rat weight</a></li>
<li><a href="repeated-measures.html#social-interaction-among-old-people"><span class="toc-section-number">31.2</span> Social interaction among old people</a></li>
<li><a href="repeated-measures.html#childrens-stress-levels-and-airports"><span class="toc-section-number">31.3</span> Children’s stress levels and airports</a></li>
<li><a href="repeated-measures.html#body-fat-as-repeated-measures"><span class="toc-section-number">31.4</span> Body fat as repeated measures</a></li>
<li><a href="repeated-measures.html#investigating-motor-activity-in-rats"><span class="toc-section-number">31.5</span> Investigating motor activity in rats</a></li>
<li><a href="repeated-measures.html#repeated-measures-with-no-background"><span class="toc-section-number">31.6</span> Repeated measures with no background</a></li>
<li><a href="repeated-measures.html#effect-of-drug-on-rat-weight-1"><span class="toc-section-number">31.7</span> Effect of drug on rat weight</a></li>
<li><a href="repeated-measures.html#social-interaction-among-old-people-1"><span class="toc-section-number">31.8</span> Social interaction among old people</a></li>
<li><a href="repeated-measures.html#childrens-stress-levels-and-airports-1"><span class="toc-section-number">31.9</span> Children’s stress levels and airports</a></li>
<li><a href="repeated-measures.html#body-fat-as-repeated-measures-1"><span class="toc-section-number">31.10</span> Body fat as repeated measures</a></li>
<li><a href="repeated-measures.html#investigating-motor-activity-in-rats-1"><span class="toc-section-number">31.11</span> Investigating motor activity in rats</a></li>
<li><a href="repeated-measures.html#repeated-measures-with-no-background-1"><span class="toc-section-number">31.12</span> Repeated measures with no background</a></li>
</ul></li>
<li><a href="discriminant-analysis.html#discriminant-analysis"><span class="toc-section-number">32</span> Discriminant analysis</a>
<ul>
<li><a href="discriminant-analysis.html#telling-whether-a-banknote-is-real-or-counterfeit"><span class="toc-section-number">32.1</span> Telling whether a banknote is real or counterfeit</a></li>
<li><a href="discriminant-analysis.html#urine-and-obesity-what-makes-a-difference"><span class="toc-section-number">32.2</span> Urine and obesity: what makes a difference?</a></li>
<li><a href="discriminant-analysis.html#understanding-a-manova"><span class="toc-section-number">32.3</span> Understanding a MANOVA</a></li>
<li><a href="discriminant-analysis.html#what-distinguishes-people-who-do-different-jobs"><span class="toc-section-number">32.4</span> What distinguishes people who do different jobs?</a></li>
<li><a href="discriminant-analysis.html#observing-children-with-adhd"><span class="toc-section-number">32.5</span> Observing children with ADHD</a></li>
<li><a href="discriminant-analysis.html#growing-corn"><span class="toc-section-number">32.6</span> Growing corn</a></li>
<li><a href="discriminant-analysis.html#understanding-athletes-height-weight-sport-and-gender"><span class="toc-section-number">32.7</span> Understanding athletes’ height, weight, sport and gender</a></li>
<li><a href="discriminant-analysis.html#telling-whether-a-banknote-is-real-or-counterfeit-1"><span class="toc-section-number">32.8</span> Telling whether a banknote is real or counterfeit</a></li>
<li><a href="discriminant-analysis.html#urine-and-obesity-what-makes-a-difference-1"><span class="toc-section-number">32.9</span> Urine and obesity: what makes a difference?</a></li>
<li><a href="discriminant-analysis.html#understanding-a-manova-1"><span class="toc-section-number">32.10</span> Understanding a MANOVA</a></li>
<li><a href="discriminant-analysis.html#what-distinguishes-people-who-do-different-jobs-1"><span class="toc-section-number">32.11</span> What distinguishes people who do different jobs?</a></li>
<li><a href="discriminant-analysis.html#observing-children-with-adhd-1"><span class="toc-section-number">32.12</span> Observing children with ADHD</a></li>
<li><a href="discriminant-analysis.html#growing-corn-1"><span class="toc-section-number">32.13</span> Growing corn</a></li>
<li><a href="discriminant-analysis.html#understanding-athletes-height-weight-sport-and-gender-1"><span class="toc-section-number">32.14</span> Understanding athletes’ height, weight, sport and gender</a></li>
</ul></li>
<li><a href="hierarchical-cluster-analysis.html#hierarchical-cluster-analysis"><span class="toc-section-number">33</span> Hierarchical cluster analysis</a>
<ul>
<li><a href="hierarchical-cluster-analysis.html#sites-on-the-sea-bed"><span class="toc-section-number">33.1</span> Sites on the sea bed</a></li>
<li><a href="hierarchical-cluster-analysis.html#dissimilarities-between-fruits"><span class="toc-section-number">33.2</span> Dissimilarities between fruits</a></li>
<li><a href="hierarchical-cluster-analysis.html#similarity-of-species"><span class="toc-section-number">33.3</span> Similarity of species</a></li>
<li><a href="hierarchical-cluster-analysis.html#bridges-in-pittsburgh"><span class="toc-section-number">33.4</span> Bridges in Pittsburgh</a></li>
<li><a href="hierarchical-cluster-analysis.html#sites-on-the-sea-bed-1"><span class="toc-section-number">33.5</span> Sites on the sea bed</a></li>
<li><a href="hierarchical-cluster-analysis.html#dissimilarities-between-fruits-1"><span class="toc-section-number">33.6</span> Dissimilarities between fruits</a></li>
<li><a href="hierarchical-cluster-analysis.html#similarity-of-species-1"><span class="toc-section-number">33.7</span> Similarity of species</a></li>
<li><a href="hierarchical-cluster-analysis.html#bridges-in-pittsburgh-1"><span class="toc-section-number">33.8</span> Bridges in Pittsburgh</a></li>
</ul></li>
<li><a href="k-means-cluster-analysis.html#k-means-cluster-analysis"><span class="toc-section-number">34</span> K-means cluster analysis</a>
<ul>
<li><a href="k-means-cluster-analysis.html#clustering-the-australian-athletes"><span class="toc-section-number">34.1</span> Clustering the Australian athletes</a></li>
<li><a href="k-means-cluster-analysis.html#running-jumping-and-throwing"><span class="toc-section-number">34.2</span> Running, jumping, and throwing</a></li>
<li><a href="k-means-cluster-analysis.html#clustering-the-swiss-bills"><span class="toc-section-number">34.3</span> Clustering the Swiss bills</a></li>
<li><a href="k-means-cluster-analysis.html#grouping-similar-cars"><span class="toc-section-number">34.4</span> Grouping similar cars</a></li>
<li><a href="k-means-cluster-analysis.html#rating-beer"><span class="toc-section-number">34.5</span> Rating beer</a></li>
<li><a href="k-means-cluster-analysis.html#clustering-the-australian-athletes-1"><span class="toc-section-number">34.6</span> Clustering the Australian athletes</a></li>
<li><a href="k-means-cluster-analysis.html#running-jumping-and-throwing-1"><span class="toc-section-number">34.7</span> Running, jumping, and throwing</a></li>
<li><a href="k-means-cluster-analysis.html#clustering-the-swiss-bills-1"><span class="toc-section-number">34.8</span> Clustering the Swiss bills</a></li>
<li><a href="k-means-cluster-analysis.html#grouping-similar-cars-1"><span class="toc-section-number">34.9</span> Grouping similar cars</a></li>
<li><a href="k-means-cluster-analysis.html#rating-beer-1"><span class="toc-section-number">34.10</span> Rating beer</a></li>
</ul></li>
<li><a href="drawing-maps-with-leaflet.html#drawing-maps-with-leaflet"><span class="toc-section-number">35</span> Drawing maps with Leaflet</a>
<ul>
<li><a href="drawing-maps-with-leaflet.html#the-brain-of-a-cat-revisited"><span class="toc-section-number">35.1</span> The brain of a cat, revisited</a></li>
<li><a href="drawing-maps-with-leaflet.html#making-a-map-of-wisconsin"><span class="toc-section-number">35.2</span> Making a map of Wisconsin</a></li>
<li><a href="drawing-maps-with-leaflet.html#the-cross-city-line"><span class="toc-section-number">35.3</span> The Cross-City Line</a></li>
<li><a href="drawing-maps-with-leaflet.html#the-brain-of-a-cat-revisited-1"><span class="toc-section-number">35.4</span> The brain of a cat, revisited</a></li>
<li><a href="drawing-maps-with-leaflet.html#making-a-map-of-wisconsin-1"><span class="toc-section-number">35.5</span> Making a map of Wisconsin</a></li>
<li><a href="drawing-maps-with-leaflet.html#the-cross-city-line-1"><span class="toc-section-number">35.6</span> The Cross-City Line</a></li>
</ul></li>
<li><a href="multidimensional-scaling.html#multidimensional-scaling"><span class="toc-section-number">36</span> Multidimensional Scaling</a>
<ul>
<li><a href="multidimensional-scaling.html#making-a-map-of-wisconsin-2"><span class="toc-section-number">36.1</span> Making a map of Wisconsin</a></li>
<li><a href="multidimensional-scaling.html#things-that-feel-similar-to-each-other"><span class="toc-section-number">36.2</span> Things that feel similar to each other</a></li>
<li><a href="multidimensional-scaling.html#confusing-letters"><span class="toc-section-number">36.3</span> Confusing letters</a></li>
<li><a href="multidimensional-scaling.html#more-beer-please"><span class="toc-section-number">36.4</span> More beer please</a></li>
<li><a href="multidimensional-scaling.html#feeling-similar-again"><span class="toc-section-number">36.5</span> Feeling similar, again</a></li>
<li><a href="multidimensional-scaling.html#making-a-map-of-wisconsin-3"><span class="toc-section-number">36.6</span> Making a map of Wisconsin</a></li>
<li><a href="multidimensional-scaling.html#things-that-feel-similar-to-each-other-1"><span class="toc-section-number">36.7</span> Things that feel similar to each other</a></li>
<li><a href="multidimensional-scaling.html#confusing-letters-1"><span class="toc-section-number">36.8</span> Confusing letters</a></li>
<li><a href="multidimensional-scaling.html#more-beer-please-1"><span class="toc-section-number">36.9</span> More beer please</a></li>
<li><a href="multidimensional-scaling.html#feeling-similar-again-1"><span class="toc-section-number">36.10</span> Feeling similar, again</a></li>
</ul></li>
<li><a href="principal-components.html#principal-components"><span class="toc-section-number">37</span> Principal Components</a>
<ul>
<li><a href="principal-components.html#the-weather-somewhere"><span class="toc-section-number">37.1</span> The weather, somewhere</a></li>
<li><a href="principal-components.html#the-weather-somewhere-1"><span class="toc-section-number">37.2</span> The weather, somewhere</a></li>
</ul></li>
<li><a href="factor-analysis.html#factor-analysis"><span class="toc-section-number">38</span> Factor Analysis</a>
<ul>
<li><a href="factor-analysis.html#the-interpersonal-circumplex"><span class="toc-section-number">38.1</span> The Interpersonal Circumplex</a></li>
<li><a href="factor-analysis.html#a-correlation-matrix"><span class="toc-section-number">38.2</span> A correlation matrix</a></li>
<li><a href="factor-analysis.html#air-pollution"><span class="toc-section-number">38.3</span> Air pollution</a></li>
<li><a href="factor-analysis.html#the-interpersonal-circumplex-1"><span class="toc-section-number">38.4</span> The Interpersonal Circumplex</a></li>
<li><a href="factor-analysis.html#a-correlation-matrix-1"><span class="toc-section-number">38.5</span> A correlation matrix</a></li>
<li><a href="factor-analysis.html#air-pollution-1"><span class="toc-section-number">38.6</span> Air pollution</a></li>
</ul></li>
<li><a href="frequency-table-analysis.html#frequency-table-analysis"><span class="toc-section-number">39</span> Frequency table analysis</a>
<ul>
<li><a href="frequency-table-analysis.html#college-plans"><span class="toc-section-number">39.1</span> College plans</a></li>
<li><a href="frequency-table-analysis.html#predicting-voting"><span class="toc-section-number">39.2</span> Predicting voting</a></li>
<li><a href="frequency-table-analysis.html#college-plans-1"><span class="toc-section-number">39.3</span> College plans</a></li>
<li><a href="frequency-table-analysis.html#predicting-voting-1"><span class="toc-section-number">39.4</span> Predicting voting</a></li>
</ul></li>
</ul>
</div>
</div>
</div>
<div class="row">
<div class="col-sm-12">
<div id="matched-pairs-t-and-sign-test" class="section level1" number="12">
<h1><span class="header-section-number">Chapter 12</span> Matched pairs t and sign test</h1>
<div class="sourceCode" id="cb551"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb551-1"><a href="matched-pairs-t-and-sign-test.html#cb551-1"></a><span class="kw">library</span>(tidyverse)</span>
<span id="cb551-2"><a href="matched-pairs-t-and-sign-test.html#cb551-2"></a><span class="kw">library</span>(smmr)</span></code></pre></div>
<div id="measuring-body-fat" class="section level2" number="12.1">
<h2><span class="header-section-number">12.1</span> Measuring body fat</h2>
<p>Athletes are concerned with measuring their body fat
percentage. Two different methods are available: one using ultrasound,
and the other using X-ray technology. We are interested in whether
there is a difference in the mean body fat percentage as measured by
these two methods, and if so, how big that difference is. Data on 16
athletes are at
<a href="http://ritsokiguess.site/datafiles/bodyfat.txt">link</a>.</p>
<ol style="list-style-type: lower-alpha">
<li><p>Explain briefly why a matched pairs analysis is more
suitable for these data than a two-independent-samples analysis
(using a two-sample <span class="math inline">\(t\)</span>-test). You might find that looking at the
data (clicking on the link) helps you figure this out.</p></li>
<li><p>Read in the data and check that you have a sensible number of
rows and columns.</p></li>
<li><p>Carry out a suitable test to determine whether the means are
the same or different. (At this point, obtain the R output including a P-value.)</p></li>
<li><p>What do you conclude from the test?</p></li>
<li><p>Obtain a 95% confidence interval for the population mean
difference. How is the interval consistent with your test?</p></li>
<li><p>Calculate the differences, and make a normal quantile plot of
them. Is there any evidence that normality of differences fails?
Explain briefly.</p></li>
</ol>
</div>
<div id="throwing-baseballs-and-softballs" class="section level2" number="12.2">
<h2><span class="header-section-number">12.2</span> Throwing baseballs and softballs</h2>
<p>Can students throw a baseball farther than a softball? A
statistics class, containing 24 students, went out to a football field
to try to answer this question. Each student warmed up and then threw
each type of ball as far as they could. The order of ball types was
randomized: some students threw the baseball first, and some threw the
softball first. (A softball is bigger than a baseball, so we might
expect that a softball would be harder to throw a long way than a
baseball.) The data are in
<a href="http://ritsokiguess.site/datafiles/throw.txt">http://ritsokiguess.site/datafiles/throw.txt</a> in three
columns: the first is a number identifying the student, the second is
the distance thrown with the baseball (in yards) and the third is the
distance thrown with the softball (also in yards).</p>
<ol style="list-style-type: lower-alpha">
<li><p>Read the data into R. You’ll need to supply some names
to the columns.</p></li>
<li><p>Calculate a column of differences, baseball minus softball,
<em>in</em> the data frame.</p></li>
<li><p>Carry out a sign test in R, testing the null hypothesis
that the median difference is zero, against the alternative that
it is greater than zero. Obtain a P-value. Your option whether you use
<code>smmr</code> or not.</p></li>
</ol>
</div>
<div id="throwing-baseballs-and-softballs-again" class="section level2" number="12.3">
<h2><span class="header-section-number">12.3</span> Throwing baseballs and softballs, again</h2>
<p>Previously, you carried out a sign test to determine
whether students could throw a baseball farther than a softball. This
time, we will calculate a confidence interval for the median
difference baseball minus softball, using the results of sign tests.</p>
<ol style="list-style-type: lower-alpha">
<li><p>Read the data into R from
<a href="http://ritsokiguess.site/datafiles/throw.txt">link</a>, giving
appropriate names to the columns, and add a column of
differences.</p></li>
<li><p>Use <code>smmr</code> to find a 95% confidence interval for the
median difference.</p></li>
<li><p>What function in <code>smmr</code> will run a two-sided sign test
and return only the P-value? Check that it works by testing whether the
median difference for your data is zero or different from zero.</p></li>
<li><p>Based on your P-value, do you think 0 is inside the confidence
interval or not? Explain briefly.</p></li>
<li><p>Obtain a 95% confidence interval for the population
median difference, baseball minus softball, using a
trial-and-error procedure that determines whether a number of
possible medians are inside or outside the CI.</p></li>
</ol>
</div>
<div id="changes-in-salary" class="section level2" number="12.4">
<h2><span class="header-section-number">12.4</span> Changes in salary</h2>
<p>A company is growing and would like to attract more
employees. The company would like to advertise that salaries there are
increasing. To do this, the company randomly samples 20 employees that
have been working there since January 2016, and for each of these
employees, records their salary in January 2016 and January 2017. The
data, with salaries in thousands of dollars, are in
<a href="http://ritsokiguess.site/datafiles/salaryinc.txt">link</a>.</p>
<ol style="list-style-type: lower-alpha">
<li><p>Read the data into R and demonstrate that you have two
salaries for each of 20 employees.</p></li>
<li><p>To compare the salaries, explain briefly why a
matched-pairs test would be better than a two-sample test.</p></li>
<li><p>Make a suitable graph to assess the assumptions for a
matched-pairs <span class="math inline">\(t\)</span>-test. What does your graph tell you?</p></li>
<li><p>Carry out a suitable matched-pairs <span class="math inline">\(t\)</span>-test on these data. (If you
thought in the previous part that this was the wrong thing to do, do
it anyway for the purposes of this assignment.) What do you conclude?</p></li>
<li><p>The company would like to estimate  salaries are increasing, on average. Obtain some output that
will enable the company to assess this, and tell the CEO which piece
of the output they should look at.</p></li>
</ol>
</div>
<div id="body-fat-revisited" class="section level2" number="12.5">
<h2><span class="header-section-number">12.5</span> Body fat revisited</h2>
<p>Athletes are concerned with measuring their body fat
percentage. Two different methods are available: one using ultrasound,
and the other using X-ray technology. We are interested in whether
there is a difference in the mean body fat percentage as measured by
these two methods, and if so, how big that difference is. Data on 16
athletes are at
<a href="http://ritsokiguess.site/datafiles/bodyfat.txt">link</a>.</p>
<p>We saw this data set before.</p>
<ol style="list-style-type: lower-alpha">
<li><p>Read in the data again.</p></li>
<li><p>Calculate the differences, and make a normal quantile plot of
them. Is there any evidence that normality of differences fails?
Explain briefly.</p></li>
<li><p>Previously, we did a matched-pairs <span class="math inline">\(t\)</span>-test for these data. In
the light of your normal quantile plot, do you think that was a good
idea? Explain briefly.</p></li>
<li><p>Use the sign test appropriately to compare the two methods for
measuring body fat. (Use <code>smmr</code> if you wish.) What do you
conclude, as ever in the context of the data?</p></li>
</ol>
<p>My solutions follow:</p>
</div>
<div id="measuring-body-fat-1" class="section level2" number="12.6">
<h2><span class="header-section-number">12.6</span> Measuring body fat</h2>
<p>Athletes are concerned with measuring their body fat
percentage. Two different methods are available: one using ultrasound,
and the other using X-ray technology. We are interested in whether
there is a difference in the mean body fat percentage as measured by
these two methods, and if so, how big that difference is. Data on 16
athletes are at
<a href="http://ritsokiguess.site/datafiles/bodyfat.txt">link</a>.</p>
<ol style="list-style-type: lower-alpha">
<li>Explain briefly why a matched pairs analysis is more
suitable for these data than a two-independent-samples analysis
(using a two-sample <span class="math inline">\(t\)</span>-test). You might find that looking at the
data (clicking on the link) helps you figure this out.</li>
</ol>
<p>Solution</p>
<p>The data file looks like this:</p>
<pre><code>
athlete xray ultrasound
1 5.00 4.75
2 7 3.75
3 9.25 9
4 12 11.75
5 17.25 17
6 29.5 27.5
7 5.5 6.5
8 6 6.75
9 8 8.75
10 8.5 9.5
11 9.25 9.5
12 11 12
13 12 12.25
14 14 15.5
15 17 18
16 18 18.25
</code></pre>
<p>The data are two measurements for each of the 16 athletes: that
is, each athlete had their body fat percentage measured using
<em>both</em> of the two methods.
Extra: a two-sample <span class="math inline">\(t\)</span> approach would be reasonable if one set of 16
athletes had been measured by X-ray and <em>another different</em>
set of 16 athletes had been measured by ultrasound. (That is, if
there had been 32 athletes in total, with each one randomly
assigned to <em>one</em> of the measurement methods.) But that’s not
what happened. It is easy to measure one athlete’s body fat
percentage using both of the two methods, so a matched pairs
design is easy to implement (as well as being better). If you use
two independent samples (each athlete doing only one measurement
method), you introduce an extra source of variability: athletes
differ one from another in body fat, as well as differing possibly
by measurement method. If you use a matched-pairs design, you
remove the athlete-to-athlete differences, leaving only the
differences due to measurement method.</p>
<p><span class="math inline">\(\blacksquare\)</span></p>
<ol start="2" style="list-style-type: lower-alpha">
<li>Read in the data and check that you have a sensible number of
rows and columns.</li>
</ol>
<p>Solution</p>
<p>This kind of thing. Since you looked at the data (didn’t you?),
you’ll know that the values are separated by single spaces:</p>
<div class="sourceCode" id="cb553"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb553-1"><a href="matched-pairs-t-and-sign-test.html#cb553-1"></a>myurl &lt;-<span class="st"> &quot;http://ritsokiguess.site/datafiles/bodyfat.txt&quot;</span></span>
<span id="cb553-2"><a href="matched-pairs-t-and-sign-test.html#cb553-2"></a>bodyfat &lt;-<span class="st"> </span><span class="kw">read_delim</span>(myurl, <span class="st">&quot; &quot;</span>)</span></code></pre></div>
<pre><code>## 
## ── Column specification ───────────────────────────────────
## cols(
##   athlete = col_double(),
##   xray = col_double(),
##   ultrasound = col_double()
## )</code></pre>
<div class="sourceCode" id="cb555"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb555-1"><a href="matched-pairs-t-and-sign-test.html#cb555-1"></a>bodyfat</span></code></pre></div>
<div data-pagedtable="false">
<script data-pagedtable-source type="application/json">
{"columns":[{"label":["athlete"],"name":[1],"type":["dbl"],"align":["right"]},{"label":["xray"],"name":[2],"type":["dbl"],"align":["right"]},{"label":["ultrasound"],"name":[3],"type":["dbl"],"align":["right"]}],"data":[{"1":"1","2":"5.00","3":"4.75"},{"1":"2","2":"7.00","3":"3.75"},{"1":"3","2":"9.25","3":"9.00"},{"1":"4","2":"12.00","3":"11.75"},{"1":"5","2":"17.25","3":"17.00"},{"1":"6","2":"29.50","3":"27.50"},{"1":"7","2":"5.50","3":"6.50"},{"1":"8","2":"6.00","3":"6.75"},{"1":"9","2":"8.00","3":"8.75"},{"1":"10","2":"8.50","3":"9.50"},{"1":"11","2":"9.25","3":"9.50"},{"1":"12","2":"11.00","3":"12.00"},{"1":"13","2":"12.00","3":"12.25"},{"1":"14","2":"14.00","3":"15.50"},{"1":"15","2":"17.00","3":"18.00"},{"1":"16","2":"18.00","3":"18.25"}],"options":{"columns":{"min":{},"max":[10]},"rows":{"min":[10],"max":[10]},"pages":{}}}
  </script>
</div>
<p>16 rows (athletes) and 3 columns, one for each measurement
method and one labelling the athletes. All good.</p>
<p>Since 16 is not too much bigger than 10, I got the whole data frame
here. (At least, I think that’s the reason I got more than 10 rows.)
In an R Notebook, you’ll see the first ten rows as normal, with a
button to click to see the other six.</p>
<p><span class="math inline">\(\blacksquare\)</span></p>
<ol start="3" style="list-style-type: lower-alpha">
<li>Carry out a suitable test to determine whether the means are
the same or different. (At this point, obtain the R output including a P-value.)</li>
</ol>
<p>Solution</p>
<p>Feed the two columns into <code>t.test</code> along with
<code>paired=T</code>. This is a two-sided test, so we don’t have to
take any special steps for that. Note that we’re back to the
“old-fashioned” version of <code>t.test</code> that <em>does not</em>
allow <code>data=</code>, so we have to go the <code>with</code> way:</p>
<div class="sourceCode" id="cb556"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb556-1"><a href="matched-pairs-t-and-sign-test.html#cb556-1"></a><span class="kw">with</span>(bodyfat, <span class="kw">t.test</span>(xray, ultrasound, <span class="dt">paired =</span> T))</span></code></pre></div>
<pre><code>## 
##  Paired t-test
## 
## data:  xray and ultrasound
## t = -0.30801, df = 15, p-value = 0.7623
## alternative hypothesis: true difference in means is not equal to 0
## 95 percent confidence interval:
##  -0.7425068  0.5550068
## sample estimates:
## mean of the differences 
##                -0.09375</code></pre>
<p><span class="math inline">\(\blacksquare\)</span></p>
<ol start="4" style="list-style-type: lower-alpha">
<li>What do you conclude from the test?</li>
</ol>
<p>Solution</p>
<p>The P-value of 0.7623 is not at all small, so there is no way we can
reject the null hypothesis.
<label for="tufte-mn-44" class="margin-toggle">⊕</label><input type="checkbox" id="tufte-mn-44" class="margin-toggle"><span class="marginnote">My hat stays on my head.</span> There
is no evidence of a difference in means; we can act as if the two
methods produce the same mean body fat percentage.
That is to say, on this evidence we can use either method, whichever
one is cheaper or more convenient.</p>
<p><span class="math inline">\(\blacksquare\)</span></p>
<ol start="5" style="list-style-type: lower-alpha">
<li>Obtain a 95% confidence interval for the population mean
difference. How is the interval consistent with your test?</li>
</ol>
<p>Solution</p>
<p>You don’t even need to do any more coding: the test was two-sided,
so just pick the confidence interval off the output above: <span class="math inline">\(-0.74\)</span>
to 0.56.
The interval includes both positive and negative values (or, 0 is
inside the interval), so the difference could go either way. This is
entirely consistent with not being able to reject the null.</p>
<p><span class="math inline">\(\blacksquare\)</span></p>
<ol start="6" style="list-style-type: lower-alpha">
<li>Calculate the differences, and make a normal quantile plot of
them. Is there any evidence that normality of differences fails?
Explain briefly.</li>
</ol>
<p>Solution</p>
<p>The smoothest
<label for="tufte-mn-45" class="margin-toggle">⊕</label><input type="checkbox" id="tufte-mn-45" class="margin-toggle"><span class="marginnote">I learned yesterday that the Welsh word for <em>ironing</em> is <em>smwddio</em>, which seems weird until you say it out loud: it sounds like <em>smoothio</em>.</span>
way to do this is to
use a pipeline: use a <code>mutate</code> to create the column of
differences, and then pipe that into <code>ggplot</code>, omitting the
data frame that would normally go first (the input data frame here
is the new one with the differences in it, which doesn’t have a
name). I’ll make a normal quantile plot in a moment, but if you
haven’t seen that yet, the plot to make is a histogram:</p>
<div class="sourceCode" id="cb558"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb558-1"><a href="matched-pairs-t-and-sign-test.html#cb558-1"></a>bodyfat <span class="op">%&gt;%</span></span>
<span id="cb558-2"><a href="matched-pairs-t-and-sign-test.html#cb558-2"></a><span class="st">  </span><span class="kw">mutate</span>(<span class="dt">diff =</span> xray <span class="op">-</span><span class="st"> </span>ultrasound) <span class="op">%&gt;%</span></span>
<span id="cb558-3"><a href="matched-pairs-t-and-sign-test.html#cb558-3"></a><span class="st">  </span><span class="kw">ggplot</span>(<span class="kw">aes</span>(<span class="dt">x =</span> diff)) <span class="op">+</span><span class="st"> </span><span class="kw">geom_histogram</span>(<span class="dt">bins =</span> <span class="dv">6</span>)</span></code></pre></div>
<p><img src="pasias_files/figure-html/unnamed-chunk-513-1.png" width="672"  /></p>
<p>I don’t know whether you’d call that “approximately normal” or
not. We are in kind of a double-bind with this one: the sample size is
small, so normality matters, but with a small sample, the data might
not look very normal. It’s kind of skewed right, but most of the
evidence for the skewness is contained in those two observations with
difference 2 and above, which is pretty flimsy evidence for
anything. (In the normal quantile plot below, the suggestion is that
those two observations really are a bit too large. It’s easier to tell
there.)</p>
<p>Below, I’m repeating the calculation of the differences, which is
inefficient. If I’m going to draw two graphs of the differences, the
right way is to calculate the differences , then use that new data frame twice. But you’re probably only
going to draw either the histogram or the normal quantile plot, not
both, so you can use the appropriate one of my two bits of code. The
normal quantile plot:</p>
<div class="sourceCode" id="cb559"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb559-1"><a href="matched-pairs-t-and-sign-test.html#cb559-1"></a>bodyfat <span class="op">%&gt;%</span></span>
<span id="cb559-2"><a href="matched-pairs-t-and-sign-test.html#cb559-2"></a><span class="st">  </span><span class="kw">mutate</span>(<span class="dt">diff =</span> xray <span class="op">-</span><span class="st"> </span>ultrasound) <span class="op">%&gt;%</span></span>
<span id="cb559-3"><a href="matched-pairs-t-and-sign-test.html#cb559-3"></a><span class="st">  </span><span class="kw">ggplot</span>(<span class="kw">aes</span>(<span class="dt">sample =</span> diff)) <span class="op">+</span><span class="st"> </span><span class="kw">stat_qq</span>() <span class="op">+</span><span class="st"> </span><span class="kw">stat_qq_line</span>()</span></code></pre></div>
<p><img src="pasias_files/figure-html/unnamed-chunk-514-1.png" width="672"  /></p>
<p>This is showing a little evidence of skewness or outliers (depending
on your point of view: either is good). The lowest and highest values
are both too high, and the pattern of points on the plot is kind of
curved (which would be evidence of skewness). Or you could say that
the two highest values are too high, with the other values being more
or less in line (that would be evidence of outliers at the upper
end). I like outliers better than skewness, since those bottom-end
points are not far off the line. I would also accept
“no substantial problems”,
if you can make the case that those two highest points are
not too far off the line. With only 16 observations as we have here,
even truly normal data would stray off the line a bit.</p>
<p>As ever, your explanation is more important than your conclusion. Can
you justify what you think?</p>
<p>If you took your differences the other way around, as
<code>ultrasound</code> minus <code>xray</code>, your plot will also be the
other way around, with the “outliers” at the bottom. That’s good
too.</p>
<p>Where this is going (which I didn’t ask you) is whether or not we
trust the result of the matched pairs test. I would say that the test
is so far from being significant, and the failure of normality is not
gross, that it is hard to imagine <em>any</em> alternative test coming
up with a significant result. So I would be happy to trust this paired
<span class="math inline">\(t\)</span>-test.</p>
<p><span class="math inline">\(\blacksquare\)</span></p>
</div>
<div id="throwing-baseballs-and-softballs-1" class="section level2" number="12.7">
<h2><span class="header-section-number">12.7</span> Throwing baseballs and softballs</h2>
<p>Can students throw a baseball farther than a softball? A
statistics class, containing 24 students, went out to a football field
to try to answer this question. Each student warmed up and then threw
each type of ball as far as they could. The order of ball types was
randomized: some students threw the baseball first, and some threw the
softball first. (A softball is bigger than a baseball, so we might
expect that a softball would be harder to throw a long way than a
baseball.) The data are in
<a href="http://ritsokiguess.site/datafiles/throw.txt">http://ritsokiguess.site/datafiles/throw.txt</a> in three
columns: the first is a number identifying the student, the second is
the distance thrown with the baseball (in yards) and the third is the
distance thrown with the softball (also in yards).</p>
<ol style="list-style-type: lower-alpha">
<li>Read the data into R. You’ll need to supply some names
to the columns.</li>
</ol>
<p>Solution</p>
<p>This kind of thing:</p>
<div class="sourceCode" id="cb560"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb560-1"><a href="matched-pairs-t-and-sign-test.html#cb560-1"></a>myurl=<span class="st">&quot;http://ritsokiguess.site/datafiles/throw.txt&quot;</span></span>
<span id="cb560-2"><a href="matched-pairs-t-and-sign-test.html#cb560-2"></a>throws=<span class="kw">read_delim</span>(myurl,<span class="st">&quot; &quot;</span>,<span class="dt">col_names=</span><span class="kw">c</span>(<span class="st">&quot;student&quot;</span>,<span class="st">&quot;baseball&quot;</span>,<span class="st">&quot;softball&quot;</span>))</span></code></pre></div>
<pre><code>## 
## ── Column specification ───────────────────────────────────
## cols(
##   student = col_double(),
##   baseball = col_double(),
##   softball = col_double()
## )</code></pre>
<div class="sourceCode" id="cb562"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb562-1"><a href="matched-pairs-t-and-sign-test.html#cb562-1"></a>throws</span></code></pre></div>
<div data-pagedtable="false">
<script data-pagedtable-source type="application/json">
{"columns":[{"label":["student"],"name":[1],"type":["dbl"],"align":["right"]},{"label":["baseball"],"name":[2],"type":["dbl"],"align":["right"]},{"label":["softball"],"name":[3],"type":["dbl"],"align":["right"]}],"data":[{"1":"1","2":"65","3":"57"},{"1":"2","2":"90","3":"58"},{"1":"3","2":"75","3":"66"},{"1":"4","2":"73","3":"61"},{"1":"5","2":"79","3":"65"},{"1":"6","2":"68","3":"56"},{"1":"7","2":"58","3":"53"},{"1":"8","2":"41","3":"41"},{"1":"9","2":"56","3":"44"},{"1":"10","2":"70","3":"65"},{"1":"11","2":"64","3":"57"},{"1":"12","2":"62","3":"60"},{"1":"13","2":"73","3":"55"},{"1":"14","2":"50","3":"53"},{"1":"15","2":"63","3":"54"},{"1":"16","2":"48","3":"42"},{"1":"17","2":"34","3":"32"},{"1":"18","2":"49","3":"48"},{"1":"19","2":"48","3":"45"},{"1":"20","2":"68","3":"67"},{"1":"21","2":"30","3":"27"},{"1":"22","2":"26","3":"25"},{"1":"23","2":"28","3":"25"},{"1":"24","2":"26","3":"31"}],"options":{"columns":{"min":{},"max":[10]},"rows":{"min":[10],"max":[10]},"pages":{}}}
  </script>
</div>
<p>This is one of those times where we have to tell R what names to give
the columns. Or you can put <code>col_names=F</code> and leave the
columns called <code>X1, X2, X3</code> or whatever they end up as.</p>
<p><span class="math inline">\(\blacksquare\)</span></p>
<ol start="2" style="list-style-type: lower-alpha">
<li>Calculate a column of differences, baseball minus softball,
<em>in</em> the data frame.</li>
</ol>
<p>Solution</p>
<p>Add it to the data frame using <code>mutate</code>. Use the
right-arrow assignment to create what I called
<code>throws2</code> below, or put something like
<code>throws2 &lt;-</code> on the beginning of the line. Your choice.</p>
<div class="sourceCode" id="cb563"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb563-1"><a href="matched-pairs-t-and-sign-test.html#cb563-1"></a>throws <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">mutate</span>(<span class="dt">diff=</span>baseball<span class="op">-</span>softball) -&gt;</span>
<span id="cb563-2"><a href="matched-pairs-t-and-sign-test.html#cb563-2"></a><span class="st">  </span>throws2</span></code></pre></div>
<p><span class="math inline">\(\blacksquare\)</span></p>
<ol start="3" style="list-style-type: lower-alpha">
<li>Carry out a sign test in R, testing the null hypothesis
that the median difference is zero, against the alternative that
it is greater than zero. Obtain a P-value. Your option whether you use
<code>smmr</code> or not.</li>
</ol>
<p>Solution</p>
<p>I think using <code>smmr</code> is way easier, so I’ll do that
first. There is even a shortcut in that the null median defaults to
zero, which is exactly what we want here:</p>
<div class="sourceCode" id="cb564"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb564-1"><a href="matched-pairs-t-and-sign-test.html#cb564-1"></a><span class="kw">library</span>(smmr)</span>
<span id="cb564-2"><a href="matched-pairs-t-and-sign-test.html#cb564-2"></a><span class="kw">sign_test</span>(throws2,diff)</span></code></pre></div>
<pre><code>## $above_below
## below above 
##     2    21 
## 
## $p_values
##   alternative      p_value
## 1       lower 9.999971e-01
## 2       upper 3.302097e-05
## 3   two-sided 6.604195e-05</code></pre>
<p>We want, this time, the upper-tailed one-sided test, since we want to
prove that students can throw a baseball a <em>longer</em> distance
than a softball. Thus the P-value we want is 0.000033.</p>
<p>To build it yourself, you know the steps by now.
First step is to count how many differences are greater and less than zero:</p>
<div class="sourceCode" id="cb566"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb566-1"><a href="matched-pairs-t-and-sign-test.html#cb566-1"></a><span class="kw">table</span>(throws2<span class="op">$</span>diff<span class="op">&gt;</span><span class="dv">0</span>)</span></code></pre></div>
<pre><code>## 
## FALSE  TRUE 
##     3    21</code></pre>
<p>or</p>
<div class="sourceCode" id="cb568"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb568-1"><a href="matched-pairs-t-and-sign-test.html#cb568-1"></a><span class="kw">table</span>(throws2<span class="op">$</span>diff<span class="op">&lt;</span><span class="dv">0</span>)</span></code></pre></div>
<pre><code>## 
## FALSE  TRUE 
##    22     2</code></pre>
<p>or, since we have things in a data frame,</p>
<div class="sourceCode" id="cb570"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb570-1"><a href="matched-pairs-t-and-sign-test.html#cb570-1"></a>throws2 <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">count</span>(diff<span class="op">&gt;</span><span class="dv">0</span>)</span></code></pre></div>
<div data-pagedtable="false">
<script data-pagedtable-source type="application/json">
{"columns":[{"label":["diff > 0"],"name":[1],"type":["lgl"],"align":["right"]},{"label":["n"],"name":[2],"type":["int"],"align":["right"]}],"data":[{"1":"FALSE","2":"3"},{"1":"TRUE","2":"21"}],"options":{"columns":{"min":{},"max":[10]},"rows":{"min":[10],"max":[10]},"pages":{}}}
  </script>
</div>
<p>or count those less than zero. I’d take any of those.</p>
<p>Note that these are <em>not all the same</em>. One of the differences is
in fact exactly zero. The technically right thing to do with the zero
difference is to throw it away (leaving 23 differences with 2 negative
and 21 positive). I would take that, or 2 or 3 negative differences
out of 24 (depending on whether you count “greater than zero” or
“less than zero”). We hope that this won’t make a material
difference to the P-value; it’ll make some difference, but won’t (we
hope) change the conclusion about whether to reject.</p>
<p>Second step is to get a P-value for whichever one of those you got,
from the appropriate binomial distribution.</p>
<p>The P-value is the probability of getting 21 (or 22) positive
differences out of 24 (or 23) or more, since this is the end of the
distribution we should be at if the alternative hypothesis is correct.
Thus any of these will get you a defensible P-value:</p>
<div class="sourceCode" id="cb571"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb571-1"><a href="matched-pairs-t-and-sign-test.html#cb571-1"></a><span class="kw">sum</span>(<span class="kw">dbinom</span>(<span class="dv">21</span><span class="op">:</span><span class="dv">23</span>,<span class="dv">23</span>,<span class="fl">0.5</span>))</span></code></pre></div>
<pre><code>## [1] 3.302097e-05</code></pre>
<div class="sourceCode" id="cb573"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb573-1"><a href="matched-pairs-t-and-sign-test.html#cb573-1"></a><span class="kw">sum</span>(<span class="kw">dbinom</span>(<span class="dv">22</span><span class="op">:</span><span class="dv">24</span>,<span class="dv">24</span>,<span class="fl">0.5</span>))</span></code></pre></div>
<pre><code>## [1] 1.7941e-05</code></pre>
<div class="sourceCode" id="cb575"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb575-1"><a href="matched-pairs-t-and-sign-test.html#cb575-1"></a><span class="kw">sum</span>(<span class="kw">dbinom</span>(<span class="dv">21</span><span class="op">:</span><span class="dv">24</span>,<span class="dv">24</span>,<span class="fl">0.5</span>))</span></code></pre></div>
<pre><code>## [1] 0.0001385808</code></pre>
<div class="sourceCode" id="cb577"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb577-1"><a href="matched-pairs-t-and-sign-test.html#cb577-1"></a><span class="kw">sum</span>(<span class="kw">dbinom</span>(<span class="dv">0</span><span class="op">:</span><span class="dv">2</span>,<span class="dv">23</span>,<span class="fl">0.5</span>))</span></code></pre></div>
<pre><code>## [1] 3.302097e-05</code></pre>
<div class="sourceCode" id="cb579"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb579-1"><a href="matched-pairs-t-and-sign-test.html#cb579-1"></a><span class="kw">sum</span>(<span class="kw">dbinom</span>(<span class="dv">0</span><span class="op">:</span><span class="dv">2</span>,<span class="dv">24</span>,<span class="fl">0.5</span>))</span></code></pre></div>
<pre><code>## [1] 1.7941e-05</code></pre>
<div class="sourceCode" id="cb581"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb581-1"><a href="matched-pairs-t-and-sign-test.html#cb581-1"></a><span class="kw">sum</span>(<span class="kw">dbinom</span>(<span class="dv">0</span><span class="op">:</span><span class="dv">3</span>,<span class="dv">24</span>,<span class="fl">0.5</span>))</span></code></pre></div>
<pre><code>## [1] 0.0001385808</code></pre>
<p>The first and fourth of those are the same as <code>smmr</code> (throwing
away the exactly-median value).</p>
<p>As we hoped, there is no <em>material</em> difference here: there is no
doubt with any of these possibilities that we will reject a median
difference of zero in favour of a median difference greater than
zero.</p>
<p><span class="math inline">\(\blacksquare\)</span></p>
</div>
<div id="throwing-baseballs-and-softballs-again-1" class="section level2" number="12.8">
<h2><span class="header-section-number">12.8</span> Throwing baseballs and softballs, again</h2>
<p>Previously, you carried out a sign test to determine
whether students could throw a baseball farther than a softball. This
time, we will calculate a confidence interval for the median
difference baseball minus softball, using the results of sign tests.</p>
<ol style="list-style-type: lower-alpha">
<li>Read the data into R from
<a href="http://ritsokiguess.site/datafiles/throw.txt">link</a>, giving
appropriate names to the columns, and add a column of
differences.</li>
</ol>
<p>Solution</p>
<p>I did it this way, combining the reading
of the data with the calculation of the differences in <em>one</em> pipe:</p>
<div class="sourceCode" id="cb583"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb583-1"><a href="matched-pairs-t-and-sign-test.html#cb583-1"></a>myurl &lt;-<span class="st"> &quot;http://ritsokiguess.site/datafiles/throw.txt&quot;</span></span>
<span id="cb583-2"><a href="matched-pairs-t-and-sign-test.html#cb583-2"></a>throws &lt;-<span class="st"> </span><span class="kw">read_delim</span>(myurl, <span class="st">&quot; &quot;</span>, <span class="dt">col_names =</span> <span class="kw">c</span>(<span class="st">&quot;student&quot;</span>, <span class="st">&quot;baseball&quot;</span>, <span class="st">&quot;softball&quot;</span>)) <span class="op">%&gt;%</span></span>
<span id="cb583-3"><a href="matched-pairs-t-and-sign-test.html#cb583-3"></a><span class="st">  </span><span class="kw">mutate</span>(<span class="dt">diff =</span> baseball <span class="op">-</span><span class="st"> </span>softball)</span></code></pre></div>
<pre><code>## 
## ── Column specification ───────────────────────────────────
## cols(
##   student = col_double(),
##   baseball = col_double(),
##   softball = col_double()
## )</code></pre>
<div class="sourceCode" id="cb585"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb585-1"><a href="matched-pairs-t-and-sign-test.html#cb585-1"></a>throws</span></code></pre></div>
<div data-pagedtable="false">
<script data-pagedtable-source type="application/json">
{"columns":[{"label":["student"],"name":[1],"type":["dbl"],"align":["right"]},{"label":["baseball"],"name":[2],"type":["dbl"],"align":["right"]},{"label":["softball"],"name":[3],"type":["dbl"],"align":["right"]},{"label":["diff"],"name":[4],"type":["dbl"],"align":["right"]}],"data":[{"1":"1","2":"65","3":"57","4":"8"},{"1":"2","2":"90","3":"58","4":"32"},{"1":"3","2":"75","3":"66","4":"9"},{"1":"4","2":"73","3":"61","4":"12"},{"1":"5","2":"79","3":"65","4":"14"},{"1":"6","2":"68","3":"56","4":"12"},{"1":"7","2":"58","3":"53","4":"5"},{"1":"8","2":"41","3":"41","4":"0"},{"1":"9","2":"56","3":"44","4":"12"},{"1":"10","2":"70","3":"65","4":"5"},{"1":"11","2":"64","3":"57","4":"7"},{"1":"12","2":"62","3":"60","4":"2"},{"1":"13","2":"73","3":"55","4":"18"},{"1":"14","2":"50","3":"53","4":"-3"},{"1":"15","2":"63","3":"54","4":"9"},{"1":"16","2":"48","3":"42","4":"6"},{"1":"17","2":"34","3":"32","4":"2"},{"1":"18","2":"49","3":"48","4":"1"},{"1":"19","2":"48","3":"45","4":"3"},{"1":"20","2":"68","3":"67","4":"1"},{"1":"21","2":"30","3":"27","4":"3"},{"1":"22","2":"26","3":"25","4":"1"},{"1":"23","2":"28","3":"25","4":"3"},{"1":"24","2":"26","3":"31","4":"-5"}],"options":{"columns":{"min":{},"max":[10]},"rows":{"min":[10],"max":[10]},"pages":{}}}
  </script>
</div>
<p><span class="math inline">\(\blacksquare\)</span></p>
<ol start="2" style="list-style-type: lower-alpha">
<li>Use <code>smmr</code> to find a 95% confidence interval for the
median difference.</li>
</ol>
<p>Solution</p>
<p><code>ci_median</code>, with 95% being the default confidence level:</p>
<div class="sourceCode" id="cb586"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb586-1"><a href="matched-pairs-t-and-sign-test.html#cb586-1"></a><span class="kw">ci_median</span>(throws, diff)</span></code></pre></div>
<pre><code>## [1] 2.002930 8.999023</code></pre>
<p>2 to 9. The ends of a CI for the median will be data values, which are
all whole numbers, so round off that 8.999.</p>
<p><span class="math inline">\(\blacksquare\)</span></p>
<ol start="3" style="list-style-type: lower-alpha">
<li>What function in <code>smmr</code> will run a two-sided sign test
and return only the P-value? Check that it works by testing whether the
median difference for your data is zero or different from zero.</li>
</ol>
<p>Solution</p>
<p>The rest of the way, we are trying to reproduce that confidence
interval by finding it ourselves.
The function is called <code>pval_sign</code>. If you haven’t run into it
before, in R Studio click on Packages, find <code>smmr</code>, and
click on its name. This will bring up package help, which
includes a list of all the functions in the package, along with
a brief description of what each one does. (Clicking
on a function name brings up the help for that function.)
Let’s check that it works properly by repeating the previous
<code>sign_test</code> and verifying that <code>pval_sign</code> gives
the same thing:</p>
<div class="sourceCode" id="cb588"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb588-1"><a href="matched-pairs-t-and-sign-test.html#cb588-1"></a><span class="kw">sign_test</span>(throws, diff, <span class="dv">0</span>)</span></code></pre></div>
<pre><code>## $above_below
## below above 
##     2    21 
## 
## $p_values
##   alternative      p_value
## 1       lower 9.999971e-01
## 2       upper 3.302097e-05
## 3   two-sided 6.604195e-05</code></pre>
<div class="sourceCode" id="cb590"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb590-1"><a href="matched-pairs-t-and-sign-test.html#cb590-1"></a><span class="kw">pval_sign</span>(<span class="dv">0</span>, throws, diff)</span></code></pre></div>
<pre><code>## [1] 6.604195e-05</code></pre>
<p>The P-values are the same (for the two-sided test) and both small, so
the median difference is not zero.</p>
<p><span class="math inline">\(\blacksquare\)</span></p>
<ol start="4" style="list-style-type: lower-alpha">
<li>Based on your P-value, do you think 0 is inside the confidence
interval or not? Explain briefly.</li>
</ol>
<p>Solution</p>
<p>Absolutely not. The median difference is definitely not
zero, so zero cannot be in the confidence interval.
Our suspicion, from the one-sided test from earlier, is that
the differences were mostly positive (people could throw a
baseball farther than a softball, in most cases). So the
confidence interval ought to contain only positive values.
I ask this because it drives what happens below.</p>
<p><span class="math inline">\(\blacksquare\)</span></p>
<ol start="5" style="list-style-type: lower-alpha">
<li>Obtain a 95% confidence interval for the population
median difference, baseball minus softball, using a
trial-and-error procedure that determines whether a number of
possible medians are inside or outside the CI.</li>
</ol>
<p>Solution</p>
<p>I’ve given you a fair bit of freedom to tackle this as you
wish. Anything that makes sense is good: whatever mixture of
mindlessness, guesswork and cleverness that you want to employ.
The most mindless way to try some values one at a time and see what
you get, eg.:</p>
<div class="sourceCode" id="cb592"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb592-1"><a href="matched-pairs-t-and-sign-test.html#cb592-1"></a><span class="kw">pval_sign</span>(<span class="dv">1</span>, throws, diff)</span></code></pre></div>
<pre><code>## [1] 0.001489639</code></pre>
<div class="sourceCode" id="cb594"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb594-1"><a href="matched-pairs-t-and-sign-test.html#cb594-1"></a><span class="kw">pval_sign</span>(<span class="dv">5</span>, throws, diff)</span></code></pre></div>
<pre><code>## [1] 1.168188</code></pre>
<p>So median 1 is outside and median 5 is inside the 95% interval. Keep
trying values until you’ve figured out where the lower and upper ends
of the interval are: where the P-values cross from below 0.05 to
above, or vice versa.</p>
<p>Something more intelligent is to make a long list of potential
medians, and get the P-value for each of them, eg.:</p>
<div class="sourceCode" id="cb596"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb596-1"><a href="matched-pairs-t-and-sign-test.html#cb596-1"></a>d &lt;-<span class="st"> </span><span class="kw">tibble</span>(<span class="dt">my.med =</span> <span class="kw">seq</span>(<span class="dv">0</span>, <span class="dv">20</span>, <span class="dv">2</span>))</span>
<span id="cb596-2"><a href="matched-pairs-t-and-sign-test.html#cb596-2"></a>d <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">rowwise</span>() <span class="op">%&gt;%</span><span class="st"> </span></span>
<span id="cb596-3"><a href="matched-pairs-t-and-sign-test.html#cb596-3"></a><span class="st">  </span><span class="kw">mutate</span>(<span class="dt">pvals =</span> <span class="kw">pval_sign</span>(my.med, throws, diff))</span></code></pre></div>
<div data-pagedtable="false">
<script data-pagedtable-source type="application/json">
{"columns":[{"label":["my.med"],"name":[1],"type":["dbl"],"align":["right"]},{"label":["pvals"],"name":[2],"type":["dbl"],"align":["right"]}],"data":[{"1":"0","2":"6.604195e-05"},{"1":"2","2":"5.247879e-02"},{"1":"4","2":"8.388197e-01"},{"1":"6","2":"6.776395e-01"},{"1":"8","2":"2.100396e-01"},{"1":"10","2":"2.265584e-02"},{"1":"12","2":"1.489639e-03"},{"1":"14","2":"6.604195e-05"},{"1":"16","2":"3.588200e-05"},{"1":"18","2":"5.722046e-06"},{"1":"20","2":"2.980232e-06"}],"options":{"columns":{"min":{},"max":[10]},"rows":{"min":[10],"max":[10]},"pages":{}}}
  </script>
</div>
<p>2 is just inside the interval, 8 is also inside, and 10 is
outside. Some closer investigation:</p>
<div class="sourceCode" id="cb597"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb597-1"><a href="matched-pairs-t-and-sign-test.html#cb597-1"></a>d &lt;-<span class="st"> </span><span class="kw">tibble</span>(<span class="dt">my.med =</span> <span class="kw">seq</span>(<span class="dv">0</span>, <span class="dv">2</span>, <span class="fl">0.5</span>))</span>
<span id="cb597-2"><a href="matched-pairs-t-and-sign-test.html#cb597-2"></a>d <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">rowwise</span>() <span class="op">%&gt;%</span><span class="st"> </span></span>
<span id="cb597-3"><a href="matched-pairs-t-and-sign-test.html#cb597-3"></a><span class="st">  </span><span class="kw">mutate</span>(<span class="dt">pvals =</span> <span class="kw">pval_sign</span>(my.med, throws, diff))</span></code></pre></div>
<div data-pagedtable="false">
<script data-pagedtable-source type="application/json">
{"columns":[{"label":["my.med"],"name":[1],"type":["dbl"],"align":["right"]},{"label":["pvals"],"name":[2],"type":["dbl"],"align":["right"]}],"data":[{"1":"0.0","2":"6.604195e-05"},{"1":"0.5","2":"2.771616e-04"},{"1":"1.0","2":"1.489639e-03"},{"1":"1.5","2":"2.265584e-02"},{"1":"2.0","2":"5.247879e-02"}],"options":{"columns":{"min":{},"max":[10]},"rows":{"min":[10],"max":[10]},"pages":{}}}
  </script>
</div>
<p>The bottom end of the interval actually is 2, since 2 is inside and
1.5 is outside.</p>
<div class="sourceCode" id="cb598"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb598-1"><a href="matched-pairs-t-and-sign-test.html#cb598-1"></a>d &lt;-<span class="st"> </span><span class="kw">tibble</span>(<span class="dt">my.med =</span> <span class="kw">seq</span>(<span class="dv">8</span>, <span class="dv">10</span>, <span class="fl">0.5</span>))</span>
<span id="cb598-2"><a href="matched-pairs-t-and-sign-test.html#cb598-2"></a>d <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">rowwise</span>() <span class="op">%&gt;%</span><span class="st"> </span></span>
<span id="cb598-3"><a href="matched-pairs-t-and-sign-test.html#cb598-3"></a><span class="st">  </span><span class="kw">mutate</span>(<span class="dt">pvals =</span> <span class="kw">pval_sign</span>(my.med, throws, diff))</span></code></pre></div>
<div data-pagedtable="false">
<script data-pagedtable-source type="application/json">
{"columns":[{"label":["my.med"],"name":[1],"type":["dbl"],"align":["right"]},{"label":["pvals"],"name":[2],"type":["dbl"],"align":["right"]}],"data":[{"1":"8.0","2":"0.21003962"},{"1":"8.5","2":"0.15158963"},{"1":"9.0","2":"0.05247879"},{"1":"9.5","2":"0.02265584"},{"1":"10.0","2":"0.02265584"}],"options":{"columns":{"min":{},"max":[10]},"rows":{"min":[10],"max":[10]},"pages":{}}}
  </script>
</div>
<p>The top end is 9, 9 being inside and 9.5 outside.</p>
<p>Since the data values are all whole numbers, I think this is accurate enough.
The most sophisticated way is the “bisection” idea we saw before. We
already have a kickoff for this, since we found, mindlessly, that 1 is
outside the interval on the low end and 5 is inside, so the lower
limit has to be between 1 and 5. Let’s try halfway between, ie. 3:</p>
<div class="sourceCode" id="cb599"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb599-1"><a href="matched-pairs-t-and-sign-test.html#cb599-1"></a><span class="kw">pval_sign</span>(<span class="dv">3</span>, throws, diff)</span></code></pre></div>
<pre><code>## [1] 0.3833103</code></pre>
<p>Inside, so lower limit is between 1 and 3. This can be automated, thus:</p>
<div class="sourceCode" id="cb601"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb601-1"><a href="matched-pairs-t-and-sign-test.html#cb601-1"></a>lo &lt;-<span class="st"> </span><span class="dv">1</span></span>
<span id="cb601-2"><a href="matched-pairs-t-and-sign-test.html#cb601-2"></a>hi &lt;-<span class="st"> </span><span class="dv">3</span></span>
<span id="cb601-3"><a href="matched-pairs-t-and-sign-test.html#cb601-3"></a><span class="cf">while</span> (<span class="kw">abs</span>(hi <span class="op">-</span><span class="st"> </span>lo) <span class="op">&gt;</span><span class="st"> </span><span class="fl">0.1</span>) {</span>
<span id="cb601-4"><a href="matched-pairs-t-and-sign-test.html#cb601-4"></a>  try &lt;-<span class="st"> </span>(lo <span class="op">+</span><span class="st"> </span>hi) <span class="op">/</span><span class="st"> </span><span class="dv">2</span></span>
<span id="cb601-5"><a href="matched-pairs-t-and-sign-test.html#cb601-5"></a>  ptry &lt;-<span class="st"> </span><span class="kw">pval_sign</span>(try, throws, diff)</span>
<span id="cb601-6"><a href="matched-pairs-t-and-sign-test.html#cb601-6"></a>  <span class="cf">if</span> (ptry <span class="op">&gt;</span><span class="st"> </span><span class="fl">0.05</span>) {</span>
<span id="cb601-7"><a href="matched-pairs-t-and-sign-test.html#cb601-7"></a>    hi &lt;-<span class="st"> </span>try</span>
<span id="cb601-8"><a href="matched-pairs-t-and-sign-test.html#cb601-8"></a>  } <span class="cf">else</span> {</span>
<span id="cb601-9"><a href="matched-pairs-t-and-sign-test.html#cb601-9"></a>    lo &lt;-<span class="st"> </span>try</span>
<span id="cb601-10"><a href="matched-pairs-t-and-sign-test.html#cb601-10"></a>  }</span>
<span id="cb601-11"><a href="matched-pairs-t-and-sign-test.html#cb601-11"></a>}</span>
<span id="cb601-12"><a href="matched-pairs-t-and-sign-test.html#cb601-12"></a><span class="kw">c</span>(lo, hi)</span></code></pre></div>
<pre><code>## [1] 1.9375 2.0000</code></pre>
<p>The difficult bit is to decide whether the value <code>try</code> becomes
the new <code>lo</code> or the new <code>hi</code>. If the P-value for the
median of <code>try</code> is greater than 0.05, <code>try</code> is inside
the interval, and it becomes the new <code>hi</code>; otherwise it’s
outside and becomes the new <code>lo</code>. Whatever the values are,
<code>lo</code> is always outside the interval and <code>hi</code> is always
inside, and they move closer and closer to each other.</p>
<p>At the other end of the interval, <code>lo</code> is inside and
<code>hi</code> is outside, so there is a little switching around within
the loop. For starting values, you can be fairly mindless: for
example, we know that 5 is inside and something big like 20 must be outside:</p>
<div class="sourceCode" id="cb603"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb603-1"><a href="matched-pairs-t-and-sign-test.html#cb603-1"></a>lo &lt;-<span class="st"> </span><span class="dv">5</span></span>
<span id="cb603-2"><a href="matched-pairs-t-and-sign-test.html#cb603-2"></a>hi &lt;-<span class="st"> </span><span class="dv">20</span></span>
<span id="cb603-3"><a href="matched-pairs-t-and-sign-test.html#cb603-3"></a><span class="cf">while</span> (<span class="kw">abs</span>(hi <span class="op">-</span><span class="st"> </span>lo) <span class="op">&gt;</span><span class="st"> </span><span class="fl">0.1</span>) {</span>
<span id="cb603-4"><a href="matched-pairs-t-and-sign-test.html#cb603-4"></a>  try &lt;-<span class="st"> </span>(lo <span class="op">+</span><span class="st"> </span>hi) <span class="op">/</span><span class="st"> </span><span class="dv">2</span></span>
<span id="cb603-5"><a href="matched-pairs-t-and-sign-test.html#cb603-5"></a>  ptry &lt;-<span class="st"> </span><span class="kw">pval_sign</span>(try, throws, diff)</span>
<span id="cb603-6"><a href="matched-pairs-t-and-sign-test.html#cb603-6"></a>  <span class="cf">if</span> (ptry <span class="op">&gt;</span><span class="st"> </span><span class="fl">0.05</span>) {</span>
<span id="cb603-7"><a href="matched-pairs-t-and-sign-test.html#cb603-7"></a>    lo &lt;-<span class="st"> </span>try</span>
<span id="cb603-8"><a href="matched-pairs-t-and-sign-test.html#cb603-8"></a>  } <span class="cf">else</span> {</span>
<span id="cb603-9"><a href="matched-pairs-t-and-sign-test.html#cb603-9"></a>    hi &lt;-<span class="st"> </span>try</span>
<span id="cb603-10"><a href="matched-pairs-t-and-sign-test.html#cb603-10"></a>  }</span>
<span id="cb603-11"><a href="matched-pairs-t-and-sign-test.html#cb603-11"></a>}</span>
<span id="cb603-12"><a href="matched-pairs-t-and-sign-test.html#cb603-12"></a><span class="kw">c</span>(lo, hi)</span></code></pre></div>
<pre><code>## [1] 8.984375 9.042969</code></pre>
<p>The interval goes from 2 to (as calculated here) about 9. (This is
apparently the same as <code>ci_median</code> in <code>smmr</code> got.)
<code>ci_median</code> uses the bisection method with a smaller “tolerance” than we
did, so its answer is more accurate. It looks as if the interval goes
from 2 to 9: that is, students can throw a baseball on average between
2 and 9 feet further than they can throw a softball.</p>
<p><span class="math inline">\(\blacksquare\)</span></p>
</div>
<div id="changes-in-salary-1" class="section level2" number="12.9">
<h2><span class="header-section-number">12.9</span> Changes in salary</h2>
<p>A company is growing and would like to attract more
employees. The company would like to advertise that salaries there are
increasing. To do this, the company randomly samples 20 employees that
have been working there since January 2016, and for each of these
employees, records their salary in January 2016 and January 2017. The
data, with salaries in thousands of dollars, are in
<a href="http://ritsokiguess.site/datafiles/salaryinc.txt">link</a>.</p>
<ol style="list-style-type: lower-alpha">
<li>Read the data into R and demonstrate that you have two
salaries for each of 20 employees.</li>
</ol>
<p>Solution</p>
<p>Looking at the file, we see that the values are separated by
exactly one space:</p>
<div class="sourceCode" id="cb605"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb605-1"><a href="matched-pairs-t-and-sign-test.html#cb605-1"></a>my_url &lt;-<span class="st"> &quot;http://ritsokiguess.site/datafiles/salaryinc.txt&quot;</span></span>
<span id="cb605-2"><a href="matched-pairs-t-and-sign-test.html#cb605-2"></a>salaries &lt;-<span class="st"> </span><span class="kw">read_delim</span>(my_url, <span class="st">&quot; &quot;</span>)</span></code></pre></div>
<pre><code>## 
## ── Column specification ───────────────────────────────────
## cols(
##   employee = col_character(),
##   jan2016 = col_double(),
##   jan2017 = col_double()
## )</code></pre>
<div class="sourceCode" id="cb607"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb607-1"><a href="matched-pairs-t-and-sign-test.html#cb607-1"></a>salaries</span></code></pre></div>
<div data-pagedtable="false">
<script data-pagedtable-source type="application/json">
{"columns":[{"label":["employee"],"name":[1],"type":["chr"],"align":["left"]},{"label":["jan2016"],"name":[2],"type":["dbl"],"align":["right"]},{"label":["jan2017"],"name":[3],"type":["dbl"],"align":["right"]}],"data":[{"1":"A","2":"36.00","3":"39.50"},{"1":"B","2":"41.25","3":"47.00"},{"1":"C","2":"40.00","3":"45.00"},{"1":"D","2":"42.80","3":"49.00"},{"1":"E","2":"51.00","3":"57.75"},{"1":"F","2":"50.50","3":"54.00"},{"1":"G","2":"56.00","3":"62.00"},{"1":"I","2":"57.80","3":"69.90"},{"1":"J","2":"62.00","3":"66.80"},{"1":"K","2":"65.50","3":"71.00"},{"1":"L","2":"66.00","3":"72.00"},{"1":"M","2":"68.90","3":"74.00"},{"1":"N","2":"71.00","3":"80.00"},{"1":"O","2":"72.30","3":"79.00"},{"1":"P","2":"74.65","3":"80.00"},{"1":"Q","2":"77.00","3":"83.10"},{"1":"R","2":"79.90","3":"82.50"},{"1":"S","2":"81.00","3":"92.00"},{"1":"T","2":"83.25","3":"85.00"},{"1":"U","2":"90.00","3":"101.00"}],"options":{"columns":{"min":{},"max":[10]},"rows":{"min":[10],"max":[10]},"pages":{}}}
  </script>
</div>
<p>There are 20 employees (rows), and two columns of salaries: for each
employee in the data set, their salary in January 2016 and in January
2017 (thus, two salaries for each employee).</p>
<p><span class="math inline">\(\blacksquare\)</span></p>
<ol start="2" style="list-style-type: lower-alpha">
<li>To compare the salaries, explain briefly why a
matched-pairs test would be better than a two-sample test.</li>
</ol>
<p>Solution</p>
<p>A matched-pairs test would be better because we have two
observations (salaries) for each subject (employee). A two-sample
test would be appropriate if we had two separate sets of
employees, one set with their salaries recorded in 2016 and the
other with their salaries recorded in 2017. That is not what we
have here.
You can go after this either way: why a matched-pairs approach is
appropriate, or why a two-sample approach is not (or a bit of both).</p>
<p><span class="math inline">\(\blacksquare\)</span></p>
<ol start="3" style="list-style-type: lower-alpha">
<li>Make a suitable graph to assess the assumptions for a
matched-pairs <span class="math inline">\(t\)</span>-test. What does your graph tell you?</li>
</ol>
<p>Solution</p>
<p>This requires thought first before you do any coding (and this is
the reason for this one being four points). What has to be at
least approximately normally distributed is the set of
<em>differences</em>, salary at one time point minus the salary at
the other, for each employee. The individual salaries don’t have
to be normally distributed at all.
We don’t have the differences here, so we have to calculate them
first. The smoothest way is to make a pipeline:</p>
<div class="sourceCode" id="cb608"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb608-1"><a href="matched-pairs-t-and-sign-test.html#cb608-1"></a>salaries <span class="op">%&gt;%</span></span>
<span id="cb608-2"><a href="matched-pairs-t-and-sign-test.html#cb608-2"></a><span class="st">  </span><span class="kw">mutate</span>(<span class="dt">diff =</span> jan2017 <span class="op">-</span><span class="st"> </span>jan2016) <span class="op">%&gt;%</span></span>
<span id="cb608-3"><a href="matched-pairs-t-and-sign-test.html#cb608-3"></a><span class="st">  </span><span class="kw">ggplot</span>(<span class="kw">aes</span>(<span class="dt">sample =</span> diff)) <span class="op">+</span><span class="st"> </span><span class="kw">stat_qq</span>() <span class="op">+</span><span class="st"> </span><span class="kw">stat_qq_line</span>()</span></code></pre></div>
<p><img src="pasias_files/figure-html/unnamed-chunk-533-1.png" width="672"  /></p>
<p>A couple of coding notes: (i) you can take the differences 2016 minus
2017 if you like (then they will tend to be negative), (ii)
<code>ggplot</code> used in a pipeline like this does <em>not</em> have a
data frame first (the data frame used is the nameless output from the
<code>mutate</code>, with the differences in it).</p>
<p>Also, there’s no problem doing the <code>mutate</code>, saving that, and
then feeding the saved data frame into <code>ggplot</code>. If you find
that clearer, go for it.</p>
<p>As for what I see: I think those points get a bit far from the
line at the high and low ends: the high values are too high and the
low values are too low, which is to say that we have outliers at both
ends, or the distribution has long tails (either way of saying it is
good).</p>
<p>The important conclusion here is whether these differences are normal
<em>enough</em> to trust a matched pairs <span class="math inline">\(t\)</span>-test here. We have a sample
of size 20, so the central limit theorem will help us some, but you
can reasonably say that these tails are too long and that we should
not trust a matched-pairs <span class="math inline">\(t\)</span>-test.</p>
<p>I actually wanted you to practice doing a matched-pairs <span class="math inline">\(t\)</span>-test
anyway, hence my comment in the next part, but the result is probably
not <em>so</em> trustworthy.</p>
<p><span class="math inline">\(\blacksquare\)</span></p>
<ol start="4" style="list-style-type: lower-alpha">
<li>Carry out a suitable matched-pairs <span class="math inline">\(t\)</span>-test on these data. (If you
thought in the previous part that this was the wrong thing to do, do
it anyway for the purposes of this assignment.) What do you conclude?</li>
</ol>
<p>Solution</p>
<p>The company is trying to prove that salaries are <em>increasing</em>
over time, so we need a one-sided alternative.
Following through the procedure, even though you may not trust it much:</p>
<div class="sourceCode" id="cb609"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb609-1"><a href="matched-pairs-t-and-sign-test.html#cb609-1"></a><span class="kw">with</span>(salaries, <span class="kw">t.test</span>(jan2016, jan2017, <span class="dt">alternative =</span> <span class="st">&quot;less&quot;</span>, <span class="dt">paired =</span> T))</span></code></pre></div>
<pre><code>## 
##  Paired t-test
## 
## data:  jan2016 and jan2017
## t = -10.092, df = 19, p-value = 2.271e-09
## alternative hypothesis: true difference in means is less than 0
## 95 percent confidence interval:
##       -Inf -5.125252
## sample estimates:
## mean of the differences 
##                  -6.185</code></pre>
<p>You could also have the years the other way around, in which case the
alternative has to be the other way around as well:</p>
<div class="sourceCode" id="cb611"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb611-1"><a href="matched-pairs-t-and-sign-test.html#cb611-1"></a><span class="kw">with</span>(salaries, <span class="kw">t.test</span>(jan2017, jan2016, <span class="dt">alternative =</span> <span class="st">&quot;greater&quot;</span>, <span class="dt">paired =</span> T))</span></code></pre></div>
<pre><code>## 
##  Paired t-test
## 
## data:  jan2017 and jan2016
## t = 10.092, df = 19, p-value = 2.271e-09
## alternative hypothesis: true difference in means is greater than 0
## 95 percent confidence interval:
##  5.125252      Inf
## sample estimates:
## mean of the differences 
##                   6.185</code></pre>
<p>Or, if you saved the data frame with the differences in it, do a
one-sample test on those, again making sure that you get the
<code>alternative</code> right. I didn’t save it, so I’m calculating the
differences again:</p>
<div class="sourceCode" id="cb613"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb613-1"><a href="matched-pairs-t-and-sign-test.html#cb613-1"></a>salaries <span class="op">%&gt;%</span></span>
<span id="cb613-2"><a href="matched-pairs-t-and-sign-test.html#cb613-2"></a><span class="st">  </span><span class="kw">mutate</span>(<span class="dt">diff =</span> jan2017 <span class="op">-</span><span class="st"> </span>jan2016) <span class="op">%&gt;%</span></span>
<span id="cb613-3"><a href="matched-pairs-t-and-sign-test.html#cb613-3"></a><span class="st">  </span><span class="kw">with</span>(., <span class="kw">t.test</span>(diff, <span class="dt">mu =</span> <span class="dv">0</span>, <span class="dt">alternative =</span> <span class="st">&quot;greater&quot;</span>))</span></code></pre></div>
<pre><code>## 
##  One Sample t-test
## 
## data:  diff
## t = 10.092, df = 19, p-value = 2.271e-09
## alternative hypothesis: true mean is greater than 0
## 95 percent confidence interval:
##  5.125252      Inf
## sample estimates:
## mean of x 
##     6.185</code></pre>
<p>Whichever way you do it, the P-value is the same <span class="math inline">\(2.271 \times 10^{-9}\)</span>, which is a whole lot less than 0.05, so there is no doubt at
all that salaries are increasing.</p>
<p>(Your intuition ought to have expected something like this, because
everyone’s 2017 salary appears to be greater than their 2016 salary.)</p>
<p>Extra: you might be feeling that we ought to be doing a matched-pairs
sign test, which you could do this way:</p>
<div class="sourceCode" id="cb615"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb615-1"><a href="matched-pairs-t-and-sign-test.html#cb615-1"></a><span class="kw">library</span>(smmr)</span>
<span id="cb615-2"><a href="matched-pairs-t-and-sign-test.html#cb615-2"></a>salaries <span class="op">%&gt;%</span></span>
<span id="cb615-3"><a href="matched-pairs-t-and-sign-test.html#cb615-3"></a><span class="st">  </span><span class="kw">mutate</span>(<span class="dt">diff =</span> jan2017 <span class="op">-</span><span class="st"> </span>jan2016) <span class="op">%&gt;%</span></span>
<span id="cb615-4"><a href="matched-pairs-t-and-sign-test.html#cb615-4"></a><span class="st">  </span><span class="kw">sign_test</span>(diff, <span class="dv">0</span>)</span></code></pre></div>
<pre><code>## $above_below
## below above 
##     0    20 
## 
## $p_values
##   alternative      p_value
## 1       lower 1.000000e+00
## 2       upper 9.536743e-07
## 3   two-sided 1.907349e-06</code></pre>
<p>and then take the “upper” P-value, which is in the same ballpark as
the one from the <span class="math inline">\(t\)</span>-test. So the salaries really are increasing,
whether you believe the <span class="math inline">\(t\)</span>-test or not. And note that <em>every single employee’s salary increased</em>.</p>
<p>(Again, the “missing” data frame in <code>sign_test</code> is the nameless
one with the differences in it.)</p>
<p><span class="math inline">\(\blacksquare\)</span></p>
<ol start="5" style="list-style-type: lower-alpha">
<li>The company would like to estimate  salaries are increasing, on average. Obtain some output that
will enable the company to assess this, and tell the CEO which piece
of the output they should look at.</li>
</ol>
<p>Solution</p>
<p>A confidence interval. 95% is fine. As before, we have to run
<code>t.test</code> again because we ran a one-sided test and a
confidence interval for us is two-sided:</p>
<div class="sourceCode" id="cb617"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb617-1"><a href="matched-pairs-t-and-sign-test.html#cb617-1"></a><span class="kw">with</span>(salaries, <span class="kw">t.test</span>(jan2017, jan2016, <span class="dt">paired =</span> T))</span></code></pre></div>
<pre><code>## 
##  Paired t-test
## 
## data:  jan2017 and jan2016
## t = 10.092, df = 19, p-value = 4.542e-09
## alternative hypothesis: true difference in means is not equal to 0
## 95 percent confidence interval:
##  4.902231 7.467769
## sample estimates:
## mean of the differences 
##                   6.185</code></pre>
<p>Between about $5,000 and about $7,500. This is what to tell the CEO.</p>
<p><span class="math inline">\(\blacksquare\)</span></p>
</div>
<div id="body-fat-revisited-1" class="section level2" number="12.10">
<h2><span class="header-section-number">12.10</span> Body fat revisited</h2>
<p>Athletes are concerned with measuring their body fat
percentage. Two different methods are available: one using ultrasound,
and the other using X-ray technology. We are interested in whether
there is a difference in the mean body fat percentage as measured by
these two methods, and if so, how big that difference is. Data on 16
athletes are at
<a href="http://ritsokiguess.site/datafiles/bodyfat.txt">link</a>.</p>
<p>We saw this data set before.</p>
<ol style="list-style-type: lower-alpha">
<li>Read in the data again.</li>
</ol>
<p>Solution</p>
<p>This kind of thing. Since you looked at the data (didn’t you?),
you’ll know that the values are separated by single spaces:</p>
<div class="sourceCode" id="cb619"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb619-1"><a href="matched-pairs-t-and-sign-test.html#cb619-1"></a>myurl &lt;-<span class="st"> &quot;http://ritsokiguess.site/datafiles/bodyfat.txt&quot;</span></span>
<span id="cb619-2"><a href="matched-pairs-t-and-sign-test.html#cb619-2"></a>bodyfat &lt;-<span class="st"> </span><span class="kw">read_delim</span>(myurl, <span class="st">&quot; &quot;</span>)</span></code></pre></div>
<pre><code>## 
## ── Column specification ───────────────────────────────────
## cols(
##   athlete = col_double(),
##   xray = col_double(),
##   ultrasound = col_double()
## )</code></pre>
<div class="sourceCode" id="cb621"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb621-1"><a href="matched-pairs-t-and-sign-test.html#cb621-1"></a>bodyfat</span></code></pre></div>
<div data-pagedtable="false">
<script data-pagedtable-source type="application/json">
{"columns":[{"label":["athlete"],"name":[1],"type":["dbl"],"align":["right"]},{"label":["xray"],"name":[2],"type":["dbl"],"align":["right"]},{"label":["ultrasound"],"name":[3],"type":["dbl"],"align":["right"]}],"data":[{"1":"1","2":"5.00","3":"4.75"},{"1":"2","2":"7.00","3":"3.75"},{"1":"3","2":"9.25","3":"9.00"},{"1":"4","2":"12.00","3":"11.75"},{"1":"5","2":"17.25","3":"17.00"},{"1":"6","2":"29.50","3":"27.50"},{"1":"7","2":"5.50","3":"6.50"},{"1":"8","2":"6.00","3":"6.75"},{"1":"9","2":"8.00","3":"8.75"},{"1":"10","2":"8.50","3":"9.50"},{"1":"11","2":"9.25","3":"9.50"},{"1":"12","2":"11.00","3":"12.00"},{"1":"13","2":"12.00","3":"12.25"},{"1":"14","2":"14.00","3":"15.50"},{"1":"15","2":"17.00","3":"18.00"},{"1":"16","2":"18.00","3":"18.25"}],"options":{"columns":{"min":{},"max":[10]},"rows":{"min":[10],"max":[10]},"pages":{}}}
  </script>
</div>
<p><span class="math inline">\(\blacksquare\)</span></p>
<ol start="2" style="list-style-type: lower-alpha">
<li>Calculate the differences, and make a normal quantile plot of
them. Is there any evidence that normality of differences fails?
Explain briefly.</li>
</ol>
<p>Solution</p>
<p>This is a good place to look ahead. We’ll need the differences in two
places, most likely: first for the normal quantile plot, and second
for the matched-pairs sign test. So we should calculate and save them first:</p>
<div class="sourceCode" id="cb622"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb622-1"><a href="matched-pairs-t-and-sign-test.html#cb622-1"></a>bodyfat <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">mutate</span>(<span class="dt">diff =</span> xray <span class="op">-</span><span class="st"> </span>ultrasound) -&gt;<span class="st"> </span>bodyfat2</span></code></pre></div>
<p>I seem to be using a 2 on the end to name my
dataframe-with-differences, but you can use whatever name you like.</p>
<p>Then, not forgetting to use the data frame that we just made:</p>
<div class="sourceCode" id="cb623"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb623-1"><a href="matched-pairs-t-and-sign-test.html#cb623-1"></a><span class="kw">ggplot</span>(bodyfat2, <span class="kw">aes</span>(<span class="dt">sample =</span> diff)) <span class="op">+</span><span class="st"> </span><span class="kw">stat_qq</span>() <span class="op">+</span><span class="st"> </span><span class="kw">stat_qq_line</span>()</span></code></pre></div>
<p><img src="pasias_files/figure-html/unnamed-chunk-541-1.png" width="672"  /></p>
<p>This is showing a little evidence of skewness or outliers (depending
on your point of view: either is good). The lowest and highest values
are both too high, and the pattern of points on the plot is kind of
curved (which would be evidence of skewness). Or you could say that
the two highest values are too high, with the other values being more
or less in line (that would be evidence of outliers at the upper
end). I like outliers better than skewness, since those bottom-end
points are not far off the line. I would also accept
“no substantial problems”,
if you can make the case that those two highest points are
not too far off the line. With only 16 observations as we have here,
even truly normal data would stray off the line a bit.</p>
<p>As ever, your explanation is more important than your conclusion. Can
you justify what you think?</p>
<p>If you took your differences the other way around, as
<code>ultrasound</code> minus <code>xray</code>, your plot will also be the
other way around, with the “outliers” at the bottom. That’s good
too.</p>
<p><span class="math inline">\(\blacksquare\)</span></p>
<ol start="3" style="list-style-type: lower-alpha">
<li>Previously, we did a matched-pairs <span class="math inline">\(t\)</span>-test for these data. In
the light of your normal quantile plot, do you think that was a good
idea? Explain briefly.</li>
</ol>
<p>Solution</p>
<p>We are looking for the differences to be approximately normal,
bearing in mind that we have a sample of size 16, which is not
that large. Say what you think here; the points, if I were giving
any here, would be for the way in which you support it.
The comment I made before when we did a matched-pairs <span class="math inline">\(t\)</span>-test
was that the P-value was so large and non-significant that it was
hard to imagine any other test giving a significant
result. Another way of saying that is that I considered these
differences to be “normal enough”, given the circumstances.
You might very well take a different view. You could say that
these differences are clearly not normal, and that the sample size
of 16 is not large enough to get any substantial help from the
Central Limit Theorem. From that point of view, running the
<span class="math inline">\(t\)</span>-test is clearly not advisable.</p>
<p><span class="math inline">\(\blacksquare\)</span></p>
<ol start="4" style="list-style-type: lower-alpha">
<li>Use the sign test appropriately to compare the two methods for
measuring body fat. (Use <code>smmr</code> if you wish.) What do you
conclude, as ever in the context of the data?</li>
</ol>
<p>Solution</p>
<p>That means using a sign test to test the null hypothesis that the
median difference is zero, against the alternative that it is not
zero. (I don’t see anything here to indicate that we are looking only
for positive or only for negative differences, so I think two-sided is
right. You need some reason to do a one-sided test, and there isn’t
one here.)</p>
<p>Remembering again to use the data frame that has the differences in it:</p>
<div class="sourceCode" id="cb624"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb624-1"><a href="matched-pairs-t-and-sign-test.html#cb624-1"></a><span class="kw">sign_test</span>(bodyfat2, diff, <span class="dv">0</span>)</span></code></pre></div>
<pre><code>## $above_below
## below above 
##    10     6 
## 
## $p_values
##   alternative   p_value
## 1       lower 0.2272491
## 2       upper 0.8949432
## 3   two-sided 0.4544983</code></pre>
<p>The two-sided P-value is 0.4545, so we are nowhere near rejecting the
null hypothesis that the median difference is zero. There is no
evidence that the two methods for measuring body fat show any
difference on average.</p>
<p>The table of aboves and belows says that there were 6 positive
differences and 10 negative ones. This is not far from an even split,
so the lack of significance is entirely what we would expect.</p>
<p>Extra: this is the same conclusion that we drew the last time we
looked at these data (with a matched-pairs <span class="math inline">\(t\)</span>-test). That supports
what I said then, which is that the <span class="math inline">\(t\)</span>-test was so far from being
significant, that it could be very wrong without changing the
conclusion. That is what seems to have happened.</p>
<p><span class="math inline">\(\blacksquare\)</span></p>

</div>
</div>
<p style="text-align: center;">
<a href="moods-median-test.html"><button class="btn btn-default">Previous</button></a>
<a href="normal-quantile-plots.html"><button class="btn btn-default">Next</button></a>
</p>
</div>
</div>



</body>
</html>
