<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>Chapter 17 Multiple regression | Problems and Solutions in Applied Statistics</title>
  <meta name="description" content="A set of problems and solutions, in R, on various parts of applied statistics" />
  <meta name="generator" content="bookdown 0.21 and GitBook 2.6.7" />

  <meta property="og:title" content="Chapter 17 Multiple regression | Problems and Solutions in Applied Statistics" />
  <meta property="og:type" content="book" />
  <meta property="og:url" content="http://ritsokiguess.site/pasias" />
  
  <meta property="og:description" content="A set of problems and solutions, in R, on various parts of applied statistics" />
  <meta name="github-repo" content="nxskok/pasias" />

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Chapter 17 Multiple regression | Problems and Solutions in Applied Statistics" />
  
  <meta name="twitter:description" content="A set of problems and solutions, in R, on various parts of applied statistics" />
  

<meta name="author" content="Ken Butler" />


<meta name="date" content="2021-05-17" />

  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="simple-regression.html"/>
<link rel="next" href="regression-with-categorical-variables.html"/>
<script src="libs/jquery-2.2.3/jquery.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />











<style type="text/css">
a.sourceLine { display: inline-block; line-height: 1.25; }
a.sourceLine { pointer-events: none; color: inherit; text-decoration: inherit; }
a.sourceLine:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode { white-space: pre; position: relative; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
code.sourceCode { white-space: pre-wrap; }
a.sourceLine { text-indent: -1em; padding-left: 1em; }
}
pre.numberSource a.sourceLine
  { position: relative; left: -4em; }
pre.numberSource a.sourceLine::before
  { content: attr(title);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; pointer-events: all; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {  }
@media screen {
a.sourceLine::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">Problems and Solutions in Applied Statistics</a></li>

<li class="divider"></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i>Introduction</a><ul>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#packages-used-somewhere-in-this-book"><i class="fa fa-check"></i>Packages used somewhere in this book</a></li>
</ul></li>
<li class="chapter" data-level="1" data-path="getting-used-to-r-and-r-studio.html"><a href="getting-used-to-r-and-r-studio.html"><i class="fa fa-check"></i><b>1</b> Getting used to R and R Studio</a></li>
<li class="chapter" data-level="2" data-path="reading-in-data.html"><a href="reading-in-data.html"><i class="fa fa-check"></i><b>2</b> Reading in data</a></li>
<li class="chapter" data-level="3" data-path="drawing-graphs.html"><a href="drawing-graphs.html"><i class="fa fa-check"></i><b>3</b> Drawing graphs</a></li>
<li class="chapter" data-level="4" data-path="data-exploration.html"><a href="data-exploration.html"><i class="fa fa-check"></i><b>4</b> Data exploration</a></li>
<li class="chapter" data-level="5" data-path="working-with-dataframes.html"><a href="working-with-dataframes.html"><i class="fa fa-check"></i><b>5</b> Working with dataframes</a></li>
<li class="chapter" data-level="6" data-path="one-sample-inference.html"><a href="one-sample-inference.html"><i class="fa fa-check"></i><b>6</b> One-sample inference</a></li>
<li class="chapter" data-level="7" data-path="two-sample-inference.html"><a href="two-sample-inference.html"><i class="fa fa-check"></i><b>7</b> Two-sample inference</a></li>
<li class="chapter" data-level="8" data-path="power-and-sample-size.html"><a href="power-and-sample-size.html"><i class="fa fa-check"></i><b>8</b> Power and sample size</a></li>
<li class="chapter" data-level="9" data-path="the-sign-test.html"><a href="the-sign-test.html"><i class="fa fa-check"></i><b>9</b> The sign test</a></li>
<li class="chapter" data-level="10" data-path="mood-median-test.html"><a href="mood-median-test.html"><i class="fa fa-check"></i><b>10</b> Mood median test</a></li>
<li class="chapter" data-level="11" data-path="matched-pairs-t-and-sign-test.html"><a href="matched-pairs-t-and-sign-test.html"><i class="fa fa-check"></i><b>11</b> Matched pairs t and sign test</a></li>
<li class="chapter" data-level="12" data-path="normal-quantile-plots.html"><a href="normal-quantile-plots.html"><i class="fa fa-check"></i><b>12</b> Normal quantile plots</a><ul>
<li class="chapter" data-level="12.1" data-path="normal-quantile-plots.html"><a href="normal-quantile-plots.html#lengths-of-heliconia-flowers"><i class="fa fa-check"></i><b>12.1</b> Lengths of heliconia flowers</a></li>
<li class="chapter" data-level="12.2" data-path="normal-quantile-plots.html"><a href="normal-quantile-plots.html#ferritin-and-normality"><i class="fa fa-check"></i><b>12.2</b> Ferritin and normality</a></li>
<li class="chapter" data-level="12.3" data-path="normal-quantile-plots.html"><a href="normal-quantile-plots.html#lengths-of-heliconia-flowers-1"><i class="fa fa-check"></i><b>12.3</b> Lengths of heliconia flowers</a></li>
<li class="chapter" data-level="12.4" data-path="normal-quantile-plots.html"><a href="normal-quantile-plots.html#ferritin-and-normality-1"><i class="fa fa-check"></i><b>12.4</b> Ferritin and normality</a></li>
</ul></li>
<li class="chapter" data-level="13" data-path="analysis-of-variance.html"><a href="analysis-of-variance.html"><i class="fa fa-check"></i><b>13</b> Analysis of variance</a></li>
<li class="chapter" data-level="14" data-path="writing-reports.html"><a href="writing-reports.html"><i class="fa fa-check"></i><b>14</b> Writing reports</a></li>
<li class="chapter" data-level="15" data-path="tidying-data.html"><a href="tidying-data.html"><i class="fa fa-check"></i><b>15</b> Tidying data</a></li>
<li class="chapter" data-level="16" data-path="simple-regression.html"><a href="simple-regression.html"><i class="fa fa-check"></i><b>16</b> Simple regression</a></li>
<li class="chapter" data-level="17" data-path="multiple-regression.html"><a href="multiple-regression.html"><i class="fa fa-check"></i><b>17</b> Multiple regression</a><ul>
<li class="chapter" data-level="17.1" data-path="multiple-regression.html"><a href="multiple-regression.html#being-satisfied-with-hospital"><i class="fa fa-check"></i><b>17.1</b> Being satisfied with hospital</a></li>
<li class="chapter" data-level="17.2" data-path="multiple-regression.html"><a href="multiple-regression.html#handling-shipments-of-chemicals"><i class="fa fa-check"></i><b>17.2</b> Handling shipments of chemicals</a></li>
<li class="chapter" data-level="17.3" data-path="multiple-regression.html"><a href="multiple-regression.html#salaries-of-mathematicians"><i class="fa fa-check"></i><b>17.3</b> Salaries of mathematicians</a></li>
<li class="chapter" data-level="17.4" data-path="multiple-regression.html"><a href="multiple-regression.html#predicting-gpa-of-computer-science-students"><i class="fa fa-check"></i><b>17.4</b> Predicting GPA of computer science students</a></li>
<li class="chapter" data-level="17.5" data-path="multiple-regression.html"><a href="multiple-regression.html#fish-and-mercury"><i class="fa fa-check"></i><b>17.5</b> Fish and mercury</a></li>
<li class="chapter" data-level="17.6" data-path="multiple-regression.html"><a href="multiple-regression.html#being-satisfied-with-hospital-1"><i class="fa fa-check"></i><b>17.6</b> Being satisfied with hospital</a></li>
<li class="chapter" data-level="17.7" data-path="multiple-regression.html"><a href="multiple-regression.html#handling-shipments-of-chemicals-1"><i class="fa fa-check"></i><b>17.7</b> Handling shipments of chemicals</a></li>
<li class="chapter" data-level="17.8" data-path="multiple-regression.html"><a href="multiple-regression.html#salaries-of-mathematicians-1"><i class="fa fa-check"></i><b>17.8</b> Salaries of mathematicians</a></li>
<li class="chapter" data-level="17.9" data-path="multiple-regression.html"><a href="multiple-regression.html#predicting-gpa-of-computer-science-students-1"><i class="fa fa-check"></i><b>17.9</b> Predicting GPA of computer science students</a></li>
<li class="chapter" data-level="17.10" data-path="multiple-regression.html"><a href="multiple-regression.html#fish-and-mercury-1"><i class="fa fa-check"></i><b>17.10</b> Fish and mercury</a></li>
</ul></li>
<li class="chapter" data-level="18" data-path="regression-with-categorical-variables.html"><a href="regression-with-categorical-variables.html"><i class="fa fa-check"></i><b>18</b> Regression with categorical variables</a><ul>
<li class="chapter" data-level="18.1" data-path="regression-with-categorical-variables.html"><a href="regression-with-categorical-variables.html#crickets-revisited"><i class="fa fa-check"></i><b>18.1</b> Crickets revisited</a></li>
<li class="chapter" data-level="18.2" data-path="regression-with-categorical-variables.html"><a href="regression-with-categorical-variables.html#pulse-rates-and-marching"><i class="fa fa-check"></i><b>18.2</b> Pulse rates and marching</a></li>
<li class="chapter" data-level="18.3" data-path="regression-with-categorical-variables.html"><a href="regression-with-categorical-variables.html#crickets-revisited-1"><i class="fa fa-check"></i><b>18.3</b> Crickets revisited</a></li>
<li class="chapter" data-level="18.4" data-path="regression-with-categorical-variables.html"><a href="regression-with-categorical-variables.html#pulse-rates-and-marching-1"><i class="fa fa-check"></i><b>18.4</b> Pulse rates and marching</a></li>
</ul></li>
<li class="chapter" data-level="19" data-path="dates-and-times.html"><a href="dates-and-times.html"><i class="fa fa-check"></i><b>19</b> Dates and times</a></li>
<li class="chapter" data-level="20" data-path="functions.html"><a href="functions.html"><i class="fa fa-check"></i><b>20</b> Functions</a></li>
<li class="chapter" data-level="21" data-path="vector-and-matrix-algebra.html"><a href="vector-and-matrix-algebra.html"><i class="fa fa-check"></i><b>21</b> Vector and matrix algebra</a><ul>
<li class="chapter" data-level="21.1" data-path="vector-and-matrix-algebra.html"><a href="vector-and-matrix-algebra.html#heights-and-foot-lengths-again"><i class="fa fa-check"></i><b>21.1</b> Heights and foot lengths again</a></li>
<li class="chapter" data-level="21.2" data-path="vector-and-matrix-algebra.html"><a href="vector-and-matrix-algebra.html#heights-and-foot-lengths-again-1"><i class="fa fa-check"></i><b>21.2</b> Heights and foot lengths again</a></li>
</ul></li>
<li class="chapter" data-level="22" data-path="the-bootstrap.html"><a href="the-bootstrap.html"><i class="fa fa-check"></i><b>22</b> The Bootstrap</a></li>
<li class="chapter" data-level="23" data-path="bayesian-statistics-with-stan.html"><a href="bayesian-statistics-with-stan.html"><i class="fa fa-check"></i><b>23</b> Bayesian Statistics with Stan</a></li>
<li class="chapter" data-level="24" data-path="logistic-regression.html"><a href="logistic-regression.html"><i class="fa fa-check"></i><b>24</b> Logistic regression</a></li>
<li class="chapter" data-level="25" data-path="logistic-regression-with-ordinal-response.html"><a href="logistic-regression-with-ordinal-response.html"><i class="fa fa-check"></i><b>25</b> Logistic regression with ordinal response</a></li>
<li class="chapter" data-level="26" data-path="logistic-regression-with-nominal-response.html"><a href="logistic-regression-with-nominal-response.html"><i class="fa fa-check"></i><b>26</b> Logistic regression with nominal response</a></li>
<li class="chapter" data-level="27" data-path="survival-analysis.html"><a href="survival-analysis.html"><i class="fa fa-check"></i><b>27</b> Survival analysis</a></li>
<li class="chapter" data-level="28" data-path="analysis-of-variance-revisited.html"><a href="analysis-of-variance-revisited.html"><i class="fa fa-check"></i><b>28</b> Analysis of variance revisited</a></li>
<li class="chapter" data-level="29" data-path="analysis-of-covariance.html"><a href="analysis-of-covariance.html"><i class="fa fa-check"></i><b>29</b> Analysis of covariance</a></li>
<li class="chapter" data-level="30" data-path="multivariate-analysis-of-variance.html"><a href="multivariate-analysis-of-variance.html"><i class="fa fa-check"></i><b>30</b> Multivariate analysis of variance</a></li>
<li class="chapter" data-level="31" data-path="repeated-measures.html"><a href="repeated-measures.html"><i class="fa fa-check"></i><b>31</b> Repeated measures</a></li>
<li class="chapter" data-level="32" data-path="discriminant-analysis.html"><a href="discriminant-analysis.html"><i class="fa fa-check"></i><b>32</b> Discriminant analysis</a></li>
<li class="chapter" data-level="33" data-path="hierarchical-cluster-analysis.html"><a href="hierarchical-cluster-analysis.html"><i class="fa fa-check"></i><b>33</b> Hierarchical cluster analysis</a></li>
<li class="chapter" data-level="34" data-path="k-means-cluster-analysis.html"><a href="k-means-cluster-analysis.html"><i class="fa fa-check"></i><b>34</b> K-means cluster analysis</a></li>
<li class="chapter" data-level="35" data-path="drawing-maps-with-leaflet.html"><a href="drawing-maps-with-leaflet.html"><i class="fa fa-check"></i><b>35</b> Drawing maps with Leaflet</a></li>
<li class="chapter" data-level="36" data-path="multidimensional-scaling.html"><a href="multidimensional-scaling.html"><i class="fa fa-check"></i><b>36</b> Multidimensional Scaling</a></li>
<li class="chapter" data-level="37" data-path="principal-components.html"><a href="principal-components.html"><i class="fa fa-check"></i><b>37</b> Principal Components</a><ul>
<li class="chapter" data-level="37.1" data-path="principal-components.html"><a href="principal-components.html#the-weather-somewhere"><i class="fa fa-check"></i><b>37.1</b> The weather, somewhere</a></li>
<li class="chapter" data-level="37.2" data-path="principal-components.html"><a href="principal-components.html#the-weather-somewhere-1"><i class="fa fa-check"></i><b>37.2</b> The weather, somewhere</a></li>
</ul></li>
<li class="chapter" data-level="38" data-path="factor-analysis.html"><a href="factor-analysis.html"><i class="fa fa-check"></i><b>38</b> Factor Analysis</a></li>
<li class="chapter" data-level="39" data-path="frequency-table-analysis.html"><a href="frequency-table-analysis.html"><i class="fa fa-check"></i><b>39</b> Frequency table analysis</a></li>
<li class="divider"></li>
<li><a href="https://github.com/rstudio/bookdown" target="blank">Published with bookdown</a></li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Problems and Solutions in Applied Statistics</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="multiple-regression" class="section level1">
<h1><span class="header-section-number">Chapter 17</span> Multiple regression</h1>
<div class="sourceCode" id="cb24"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb24-1" title="1"><span class="kw">library</span>(tidyverse)</a></code></pre></div>
<div id="being-satisfied-with-hospital" class="section level2">
<h2><span class="header-section-number">17.1</span> Being satisfied with hospital</h2>
<p>A hospital administrator collects data to study the
effect, if any, of a patient’s age, the severity of their
illness, and their anxiety level, on the patient’s satisfaction with
their hospital experience. The data, in the file
<a href="http://ritsokiguess.site/datafiles/satisfaction.txt">link</a>, are
for 46 patients in a survey. The columns are: patient’s satisfaction
score <code>satis</code>, on a scale of 0 to 100; the patient’s <code>age</code> (in
years), the <code>severity</code> of the patient’s illness (also on a
0–100 scale), and the patient’s <code>anxiety</code> score on a standard
anxiety test (scale of 0–5). Higher scores mean greater satisfaction,
increased severity of illness and more anxiety.</p>
<ol style="list-style-type: lower-alpha">
<li><p>Read in the data and check that you have four columns in
your data frame, one for each of your variables.</p></li>
<li><p><a name="part:scatmat">*</a> Obtain scatterplots of the response variable
<code>satis</code> against each of the other variables.</p></li>
<li><p>In your scatterplots of (<a href="#part:scatmat">here</a>), which
relationship appears to be the strongest one?</p></li>
<li><p><a name="part:corrmat">*</a> Create a correlation matrix for all four
variables. Does your strongest trend of the previous part have the
strongest correlation?</p></li>
<li><p>Run a regression predicting satisfaction from the other
three variables, and display the output.</p></li>
<li><p>Does the regression fit well overall? How can you tell?</p></li>
<li><p>Test the null hypothesis that none of your explanatory
variables help, against the alternative that one or more of them
do. (You’ll need an appropriate P-value. Which one is it?) What do
you conclude?</p></li>
<li><p>The correlation between <code>severity</code> and
<code>satis</code> is not small, but in my regression I found that
<code>severity</code> was nowhere near significant. Why is this? Explain briefly.
</p></li>
<li><p>Carry out a backward elimination to determine which of
<code>age</code>, <code>severity</code> and <code>anxiety</code> are needed to
predict satisfaction. What do you get?</p></li>
</ol>
</div>
<div id="handling-shipments-of-chemicals" class="section level2">
<h2><span class="header-section-number">17.2</span> Handling shipments of chemicals</h2>
<p>The data in
<a href="http://statweb.lsu.edu/EXSTWeb/StatLab/DataSets/NKNWData/CH06PR09.txt">link</a>
are on shipments of chemicals in drums that arrive at a warehouse. In
order, the variables are:</p>
<ul>
<li><p>the number of minutes required to handle the shipment</p></li>
<li><p>the number of drums in the shipment</p></li>
<li><p>the total weight of the shipment, in hundreds of pounds.</p></li>
</ul>
<ol style="list-style-type: lower-alpha">
<li><p>The data set has two features: <em>no</em> column names, and
data aligned in columns (that is, more than one space between data
values). Read the data in, giving the columns suitable names. To do
this, you may have to consult an appropriate help file, or do some
searching, perhaps of one of the other questions on this assignment.</p></li>
<li><p>Fit a regression predicting the number of minutes required
to handle a shipment from the other two variables. Display the results.</p></li>
<li><p>Explain carefully but briefly what the slope coefficients
for the two explanatory variables represent. Do their signs
(positive or negative) make practical sense in the context of
handling shipments of chemicals?</p></li>
<li><p>Obtain plots of residuals against fitted values, residuals
against explanatory variables, and a normal quantile plot of the residuals.</p></li>
<li><p>Do you have any concerns, looking at the residual plots?
Explain briefly.</p></li>
</ol>
</div>
<div id="salaries-of-mathematicians" class="section level2">
<h2><span class="header-section-number">17.3</span> Salaries of mathematicians</h2>
<p>A researcher in a scientific
foundation wanted to evaluate the relationship between annual salaries
of mathematicians and three explanatory variables:</p>
<ul>
<li><p>an index of work quality</p></li>
<li><p>number of years of experience</p></li>
<li><p>an index of publication success.</p></li>
</ul>
<p>The data can be found at
<a href="http://ritsokiguess.site/datafiles/mathsal.txt">link</a>. Data from
only a relatively small number of mathematicians were available.</p>
<ol style="list-style-type: lower-alpha">
<li><p>Read in the data and check that you have a sensible number
of rows and the right number of columns. (What does “a sensible number of rows” mean here?)</p></li>
<li><p>Make scatterplots of <code>salary</code> against each of the three explanatory variables. If you can, do this with <em>one</em> <code>ggplot</code>.</p></li>
<li><p>Comment briefly on the direction and strength of each
relationship with <code>salary</code>.</p></li>
<li><p><a name="regone">*</a> Fit a regression predicting salary from the other three
variables, and obtain a <code>summary</code> of the results.</p></li>
<li><p>How can we justify the statement
“one or more of the explanatory variables helps to predict salary”? How is this
consistent with the value of R-squared?</p></li>
<li><p>Would you consider removing any of the variables from this
regression? Why, or why not?</p></li>
<li><p>Do you think it would be a mistake to take <em>both</em> of
<code>workqual</code> and <code>pubsucc</code> out of the regression? Do a
suitable test. Was your guess right?</p></li>
<li><p>Back in part (<a href="#regone">here</a>), you fitted a regression with all
three explanatory variables. By making suitable plots, assess
whether there is any evidence that (i) that the linear model should
be a curve, (ii) that the residuals are not normally
distributed, (iii) that there is “fan-out”, where the residuals are getting
bigger <em>in size</em> as the fitted values get bigger? Explain
briefly how you came to your conclusions in each case.</p></li>
</ol>
</div>
<div id="predicting-gpa-of-computer-science-students" class="section level2">
<h2><span class="header-section-number">17.4</span> Predicting GPA of computer science students</h2>
<p>The file
<a href="http://ritsokiguess.site/datafiles/gpa.txt">link</a> contains some
measurements of academic achievement for a number of university
students studying computer science:</p>
<ul>
<li><p>High school grade point average</p></li>
<li><p>Math SAT score</p></li>
<li><p>Verbal SAT score</p></li>
<li><p>Computer Science grade point average</p></li>
<li><p>Overall university grade point average.</p></li>
</ul>
<ol style="list-style-type: lower-alpha">
<li><p>Read in the data and display it (or at least the first ten lines).</p></li>
<li><p><a name="part:hsu-scatter">*</a> Make a scatterplot of high school GPA against university
GPA. Which variable should be the response and which
explanatory? Explain briefly. Add a smooth trend to your plot.</p></li>
<li><p>Describe any relationship on your scatterplot: its direction, its
strength and its shape. Justify your description briefly.</p></li>
<li><p><a name="part:highonly">*</a> Fit a linear regression for predicting university GPA
from high-school GPA and display the results.</p></li>
<li><p>Two students have been admitted to university. One has
a high school GPA of 3.0 and the other a high school GPA of<br />
3.5. Obtain suitable intervals that summarize the GPAs that each of these
two students might obtain in university.</p></li>
<li><p><a name="part:all">*</a> Now obtain a regression predicting university GPA from
high-school GPA as well as the two SAT scores. Display your results.</p></li>
<li><p>Test whether adding the two SAT scores has improved the
prediction of university GPA. What do you conclude?</p></li>
<li><p>Carry out a backward elimination starting out from your
model in part (<a href="#part:all">here</a>). Which model do you end up with?
Is it the same model as you fit in (<a href="#part:highonly">here</a>)?</p></li>
<li><p>These students were studying computer science at
university. Do you find your backward-elimination result
sensible or surprising, given this? Explain briefly.</p></li>
</ol>
</div>
<div id="fish-and-mercury" class="section level2">
<h2><span class="header-section-number">17.5</span> Fish and mercury</h2>
<p>Eating fish is generally healthy, but sometimes the fish is contaminated with mercury. What might affect the amount of mercury in a fish? Large-mouth bass were studied in Florida lakes to examine factors that might affect the amount of mercury contamination. 38 lakes were used for the study. Water samples were taken from each lake and analyzed. Also, samples of fish were caught in each lake and the mercury concentration in their muscle tissue was measured. The resulting data are in , separated by single spaces. The variables measured were as follows:</p>
<ul>
<li>standardized mercury level (parts per million in 3-year-old fish)</li>
<li>alkalinity of water (milligrams per litre)</li>
<li>calcium level of water (milligrams per litre)</li>
<li>pH of water (standard scale; see eg. <a href="https://www.usgs.gov/special-topic/water-science-school/science/ph-and-water?qt-science_center_objects=0#qt-science_center_objects">this</a>)</li>
</ul>
<ol style="list-style-type: lower-alpha">
<li><p>Read in and display (some of) the data.</p></li>
<li><p>Plot the mercury levels against each of the explanatory variables.</p></li>
<li><p>Describe any trends (or lack thereof) that you see on your graphs.</p></li>
<li><p>Concerned by some of what you see on your plots, you consult with a fisheries scientist, who says that using the logs of <code>alkalinity</code> and <code>calcium</code> are often used in modelling this kind of data. Add columns containing the logs of these two variables to your dataframe, and run a regression predicting <code>mercury</code> from <code>ph</code> and the two new variables. Display the output from your regression.</p></li>
<li><p>What might you learn from running Box-Cox here? Explain briefly, then run it (on the same variables as your regression above) and describe what the results tell you.</p></li>
<li><p>Using the results of the Box-Cox procedure and your previous work in the question, what seems to be the most appropriate regression now? Fit it, and display the results.</p></li>
<li><p>Obtain all the standard residual plots (the ones we have seen in this course) for this model. Describe any problems you see.</p></li>
</ol>
<p>My solutions follow:</p>
</div>
<div id="being-satisfied-with-hospital-1" class="section level2">
<h2><span class="header-section-number">17.6</span> Being satisfied with hospital</h2>
<p>A hospital administrator collects data to study the
effect, if any, of a patient’s age, the severity of their
illness, and their anxiety level, on the patient’s satisfaction with
their hospital experience. The data, in the file
<a href="http://ritsokiguess.site/datafiles/satisfaction.txt">link</a>, are
for 46 patients in a survey. The columns are: patient’s satisfaction
score <code>satis</code>, on a scale of 0 to 100; the patient’s <code>age</code> (in
years), the <code>severity</code> of the patient’s illness (also on a
0–100 scale), and the patient’s <code>anxiety</code> score on a standard
anxiety test (scale of 0–5). Higher scores mean greater satisfaction,
increased severity of illness and more anxiety.</p>
<ol style="list-style-type: lower-alpha">
<li>Read in the data and check that you have four columns in
your data frame, one for each of your variables.</li>
</ol>
<p>Solution</p>
<p>This one requires a little thought
first. The data values are aligned in columns, and so are the
column headers. Thus, <code>read_table</code> is what we need:</p>
<div class="sourceCode" id="cb25"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb25-1" title="1">my_url &lt;-<span class="st"> &quot;http://ritsokiguess.site/datafiles/satisfaction.txt&quot;</span></a>
<a class="sourceLine" id="cb25-2" title="2">satisf &lt;-<span class="st"> </span><span class="kw">read_table</span>(my_url)</a></code></pre></div>
<pre><code>## 
## ── Column specification ──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
## cols(
##   satis = col_double(),
##   age = col_double(),
##   severity = col_double(),
##   anxiety = col_double()
## )</code></pre>
<div class="sourceCode" id="cb27"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb27-1" title="1">satisf</a></code></pre></div>
<pre><code>## # A tibble: 23 x 4
##    satis   age severity anxiety
##    &lt;dbl&gt; &lt;dbl&gt;    &lt;dbl&gt;   &lt;dbl&gt;
##  1    48    50       51     2.3
##  2    57    36       46     2.3
##  3    66    40       48     2.2
##  4    70    41       44     1.8
##  5    89    28       43     1.8
##  6    36    49       54     2.9
##  7    46    42       50     2.2
##  8    54    45       48     2.4
##  9    26    52       62     2.9
## 10    77    29       50     2.1
## # … with 13 more rows</code></pre>
<p>46 rows and 4 columns: satisfaction score (response), age, severity
and anxiety (explanatory).</p>
<p>There is a small question about what to call the data
frame. Basically, anything other than <code>satis</code> will do, since
there will be confusion if your data frame has the same name as one of
its columns.</p>
<p><span class="math inline">\(\blacksquare\)</span></p>
<ol start="2" style="list-style-type: lower-alpha">
<li><a name="part:scatmat">*</a> Obtain scatterplots of the response variable
<code>satis</code> against each of the other variables.</li>
</ol>
<p>Solution</p>
<p>The obvious way is to do these one after the other:</p>
<div class="sourceCode" id="cb29"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb29-1" title="1"><span class="kw">ggplot</span>(satisf, <span class="kw">aes</span>(<span class="dt">x =</span> age, <span class="dt">y =</span> satis)) <span class="op">+</span><span class="st"> </span><span class="kw">geom_point</span>()</a></code></pre></div>
<p><img src="pasias_files/figure-html/unnamed-chunk-32-1.png" width="384" /></p>
<div class="sourceCode" id="cb30"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb30-1" title="1"><span class="kw">ggplot</span>(satisf, <span class="kw">aes</span>(<span class="dt">x =</span> severity, <span class="dt">y =</span> satis)) <span class="op">+</span><span class="st"> </span><span class="kw">geom_point</span>()</a></code></pre></div>
<p><img src="pasias_files/figure-html/unnamed-chunk-32-2.png" width="384" /></p>
<div class="sourceCode" id="cb31"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb31-1" title="1"><span class="kw">ggplot</span>(satisf, <span class="kw">aes</span>(<span class="dt">x =</span> anxiety, <span class="dt">y =</span> satis)) <span class="op">+</span><span class="st"> </span><span class="kw">geom_point</span>()</a></code></pre></div>
<p><img src="pasias_files/figure-html/unnamed-chunk-32-3.png" width="384" /></p>
<p>This is fine, but there is also a way of getting all three plots with
<em>one</em> <code>ggplot</code>. This uses the <code>facet_wrap</code> trick,
but to set <em>that</em> up, we have to have all the <span class="math inline">\(x\)</span>-variables in
<em>one</em> column, with an extra column labelling which <span class="math inline">\(x\)</span>-variable
that value was. This uses <code>pivot_longer</code>. The right way to do this is
in a pipeline:</p>
<div class="sourceCode" id="cb32"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb32-1" title="1">satisf <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb32-2" title="2"><span class="st">  </span><span class="kw">pivot_longer</span>(<span class="op">-</span>satis, <span class="dt">names_to=</span><span class="st">&quot;xname&quot;</span>, <span class="dt">values_to=</span><span class="st">&quot;x&quot;</span>) <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb32-3" title="3"><span class="st">  </span><span class="kw">ggplot</span>(<span class="kw">aes</span>(<span class="dt">x =</span> x, <span class="dt">y =</span> satis)) <span class="op">+</span><span class="st"> </span><span class="kw">geom_point</span>() <span class="op">+</span></a>
<a class="sourceLine" id="cb32-4" title="4"><span class="st">  </span><span class="kw">facet_wrap</span>(<span class="op">~</span>xname, <span class="dt">scales =</span> <span class="st">&quot;free&quot;</span>, <span class="dt">ncol =</span> <span class="dv">2</span>)</a></code></pre></div>
<p><img src="pasias_files/figure-html/unnamed-chunk-33-1.png" width="672" /></p>
<p>Steps: collect together the columns age through anxiety into one column
whose values go in <code>x</code>, with names in <code>xname</code>, then plot this new
<code>x</code> against satisfaction score, with a separate facet for each
different <span class="math inline">\(x\)</span> (in <code>xname</code>).</p>
<p>What’s the difference
between <code>facet_grid</code> and <code>facet_wrap</code>? The difference is that with
<code>facet_wrap</code>, we are letting <code>ggplot</code> arrange the
facets how it wants to. In this case, we didn’t care which explanatory
variable went on which facet, just as long as we saw all of them
somewhere. Inside <code>facet_wrap</code> there are <em>no dots</em>: a
squiggle, followed by the name(s) of the variable(s) that
distinguish(es) the facets.<a href="#fn2" class="footnote-ref" id="fnref2"><sup>2</sup></a>
The only “design” decision I made here was that the facets
should be arranged somehow in two columns, but I didn’t care which
ones should be where.</p>
<p>In <code>facet_grid</code>, you have a variable that you want to be
displayed in rows or in columns (not just in “different facets”).
I’ll show you how that works here. Since I am going to draw
two plots, I should save the long data frame first and re-use it,
rather than calculating it twice (so that I ought now to go back and
do the other one using the saved data frame, really):</p>
<div class="sourceCode" id="cb33"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb33-1" title="1">satisf <span class="op">%&gt;%</span><span class="st"> </span></a>
<a class="sourceLine" id="cb33-2" title="2"><span class="st">  </span><span class="kw">pivot_longer</span>(age<span class="op">:</span>anxiety, <span class="dt">names_to=</span><span class="st">&quot;xname&quot;</span>, </a>
<a class="sourceLine" id="cb33-3" title="3">               <span class="dt">values_to=</span><span class="st">&quot;x&quot;</span>) -&gt;<span class="st"> </span>satisf.long</a>
<a class="sourceLine" id="cb33-4" title="4">satisf.long</a></code></pre></div>
<pre><code>## # A tibble: 69 x 3
##    satis xname        x
##    &lt;dbl&gt; &lt;chr&gt;    &lt;dbl&gt;
##  1    48 age       50  
##  2    48 severity  51  
##  3    48 anxiety    2.3
##  4    57 age       36  
##  5    57 severity  46  
##  6    57 anxiety    2.3
##  7    66 age       40  
##  8    66 severity  48  
##  9    66 anxiety    2.2
## 10    70 age       41  
## # … with 59 more rows</code></pre>
<p>If, at this or any stage, you get confused, the way to un-confuse
yourself is to <em>fire up R Studio and do this yourself</em>. You have
all the data and code you need. If you do it yourself, you can run
pipes one line at a time, inspect things, and so on.</p>
<p>First, making a <em>row</em> of plots, so that <code>xname</code> is the <span class="math inline">\(x\)</span>
of the facets:</p>
<div class="sourceCode" id="cb35"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb35-1" title="1"><span class="kw">ggplot</span>(satisf.long, <span class="kw">aes</span>(<span class="dt">x =</span> x, <span class="dt">y =</span> satis)) <span class="op">+</span><span class="st"> </span><span class="kw">geom_point</span>() <span class="op">+</span></a>
<a class="sourceLine" id="cb35-2" title="2"><span class="st">  </span><span class="kw">facet_grid</span>(. <span class="op">~</span><span class="st"> </span>xname, <span class="dt">scales =</span> <span class="st">&quot;free&quot;</span>)</a></code></pre></div>
<p><img src="pasias_files/figure-html/unnamed-chunk-35-1.png" width="672" /></p>
<p>I find these too tall and skinny to see the trends, as on the first
<code>facet_wrap</code> plot.</p>
<p>And now, making a <em>column</em> of plots, with <code>xname</code> as <span class="math inline">\(y\)</span>:</p>
<div class="sourceCode" id="cb36"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb36-1" title="1"><span class="kw">ggplot</span>(satisf.long, <span class="kw">aes</span>(<span class="dt">x =</span> x, <span class="dt">y =</span> satis)) <span class="op">+</span><span class="st"> </span><span class="kw">geom_point</span>() <span class="op">+</span></a>
<a class="sourceLine" id="cb36-2" title="2"><span class="st">  </span><span class="kw">facet_grid</span>(xname <span class="op">~</span><span class="st"> </span>., <span class="dt">scales =</span> <span class="st">&quot;free&quot;</span>)</a></code></pre></div>
<p><img src="pasias_files/figure-html/unnamed-chunk-36-1.png" width="672" /></p>
<p>This one looks weird because the three <span class="math inline">\(x\)</span>-variables are on different
scales. The effect of the <code>scales="free"</code> is to allow the
<code>satis</code> scale to vary, but the <code>x</code> scale cannot because
the facets are all in a line. Compare this:</p>
<div class="sourceCode" id="cb37"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb37-1" title="1"><span class="kw">ggplot</span>(satisf.long, <span class="kw">aes</span>(<span class="dt">x =</span> x, <span class="dt">y =</span> satis)) <span class="op">+</span><span class="st"> </span><span class="kw">geom_point</span>() <span class="op">+</span></a>
<a class="sourceLine" id="cb37-2" title="2"><span class="st">  </span><span class="kw">facet_wrap</span>(<span class="op">~</span>xname, <span class="dt">ncol =</span> <span class="dv">1</span>, <span class="dt">scales =</span> <span class="st">&quot;free&quot;</span>)</a></code></pre></div>
<p><img src="pasias_files/figure-html/unnamed-chunk-37-1.png" width="672" /></p>
<p>This time, the <span class="math inline">\(x\)</span> scales came out different (and suitable), but I
still like squarer plots better for judging relationships.</p>
<p><span class="math inline">\(\blacksquare\)</span></p>
<ol start="3" style="list-style-type: lower-alpha">
<li>In your scatterplots of (<a href="#part:scatmat">here</a>), which
relationship appears to be the strongest one?</li>
</ol>
<p>Solution</p>
<p>All the trends appear to be downward ones, but
I think <code>satis</code> and <code>age</code> is the strongest
trend. The other ones look more scattered to me.</p>
<p><span class="math inline">\(\blacksquare\)</span></p>
<ol start="4" style="list-style-type: lower-alpha">
<li><a name="part:corrmat">*</a> Create a correlation matrix for all four
variables. Does your strongest trend of the previous part have the
strongest correlation?</li>
</ol>
<p>Solution</p>
<p>This is a matter of running the whole data frame through <code>cor</code>:</p>
<div class="sourceCode" id="cb38"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb38-1" title="1"><span class="kw">cor</span>(satisf)</a></code></pre></div>
<pre><code>##               satis        age   severity    anxiety
## satis     1.0000000 -0.7736828 -0.5874444 -0.6023105
## age      -0.7736828  1.0000000  0.4666091  0.4976945
## severity -0.5874444  0.4666091  1.0000000  0.7945275
## anxiety  -0.6023105  0.4976945  0.7945275  1.0000000</code></pre>
<p>Ignoring the correlations of variables with themselves, the
correlation of <code>satisf</code> with <code>age</code>, the one I picked
out, is the strongest (the most negative trend). If you picked one of
the other trends as the strongest, you need to note how close it is to
the maximum correlation: for example, if you picked <code>satis</code>
and <code>severity</code>, that’s the second highest correlation (in
size).</p>
<p><span class="math inline">\(\blacksquare\)</span></p>
<ol start="5" style="list-style-type: lower-alpha">
<li>Run a regression predicting satisfaction from the other
three variables, and display the output.</li>
</ol>
<p>Solution</p>
<div class="sourceCode" id="cb40"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb40-1" title="1">satisf<span class="fl">.1</span> &lt;-<span class="st"> </span><span class="kw">lm</span>(satis <span class="op">~</span><span class="st"> </span>age <span class="op">+</span><span class="st"> </span>severity <span class="op">+</span><span class="st"> </span>anxiety, <span class="dt">data =</span> satisf)</a>
<a class="sourceLine" id="cb40-2" title="2"><span class="kw">summary</span>(satisf<span class="fl">.1</span>)</a></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = satis ~ age + severity + anxiety, data = satisf)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -16.954  -7.154   1.550   6.599  14.888 
## 
## Coefficients:
##             Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept) 162.8759    25.7757   6.319 4.59e-06 ***
## age          -1.2103     0.3015  -4.015  0.00074 ***
## severity     -0.6659     0.8210  -0.811  0.42736    
## anxiety      -8.6130    12.2413  -0.704  0.49021    
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 10.29 on 19 degrees of freedom
## Multiple R-squared:  0.6727, Adjusted R-squared:  0.621 
## F-statistic: 13.01 on 3 and 19 DF,  p-value: 7.482e-05</code></pre>
<p><span class="math inline">\(\blacksquare\)</span></p>
<ol start="6" style="list-style-type: lower-alpha">
<li>Does the regression fit well overall? How can you tell?</li>
</ol>
<p>Solution</p>
<p>For this, look at R-squared, which is 0.682 (68.2%). This is one
of those things to have an opinion about. I’d say this is good but
not great. I would not call it “poor”, since there definitely
<em>is</em> a relationship, even if it’s not a stupendously good one.</p>
<p><span class="math inline">\(\blacksquare\)</span></p>
<ol start="7" style="list-style-type: lower-alpha">
<li>Test the null hypothesis that none of your explanatory
variables help, against the alternative that one or more of them
do. (You’ll need an appropriate P-value. Which one is it?) What do
you conclude?</li>
</ol>
<p>Solution</p>
<p>This one is the (global) <span class="math inline">\(F\)</span>-test, whose P-value is at the
bottom. It translates to 0.000000000154, so this is
<em>definitely</em> small, and we reject the null. Thus, one or more
of <code>age</code>, <code>severity</code> and <code>anxiety</code> helps to
predict satisfaction. (I would like to see this last sentence,
rather than just “reject the null”.)</p>
<p><span class="math inline">\(\blacksquare\)</span></p>
<ol start="8" style="list-style-type: lower-alpha">
<li>The correlation between <code>severity</code> and
<code>satis</code> is not small, but in my regression I found that
<code>severity</code> was nowhere near significant. Why is this? Explain briefly.
</li>
</ol>
<p>Solution</p>
<p>The key thing to observe is that the <span class="math inline">\(t\)</span>-test in the regression
says how important a variable is , or, if you prefer, how much that
variable <em>adds</em> to the regression, on top of the ones that
are already there. So here, we are saying
that <code>severity</code> has nothing to add, given that the
regression already includes the others. (That is, high correlation
and strong significance don’t always go together.)
For a little more insight, look at the correlation matrix of
(<a href="#part:corrmat">here</a>) again. The strongest trend with
<code>satis</code> is with <code>age</code>, and indeed <code>age</code> is
the one obviously significant variable in the regression. The
trend of <code>severity</code> with <code>satis</code> is somewhat
downward, and you might otherwise have guessed that this is strong
enough to be significant. But see that <code>severity</code>
<em>also</em> has a clear relationship with <code>age</code>. A patient
with low severity of disease is probably also younger, and we know
that younger patients are likely to be more satisfied. Thus
severity has nothing (much) to add.
The multiple regression is actually doing something clever
here. Just looking at the correlations, it appears that all three
variables are helpful, but the regression is saying that once you
have looked at <code>age</code> (“controlled for age”),
severity of illness does not have an impact: the correlation of
<code>severity</code> with <code>satis</code> is as big as it is almost
entirely because of <code>age</code>.
This gets into the domain of “partial correlation”. If you like videos, you can
see <a href="https://www.youtube.com/watch?v=LF0WAVBIhNA">link</a> for
this. I prefer regression, myself, since I find it clearer.
<code>anxiety</code>
tells a different story: this is close to significant (or
<em>is</em> significant at the <span class="math inline">\(\alpha=0.10\)</span> level), so the
regression is saying that <code>anxiety</code> <em>does</em> appear to
have something to say about <code>satis</code> over and above
<code>age</code>. This is rather odd, to my mind, since
<code>anxiety</code> has only a slightly stronger correlation with
<code>satis</code> and about the same with <code>age</code> as
<code>severity</code> does. But the regression is telling the story to
believe, because it handles all the inter-correlations, not just
the ones between pairs of variables.
I thought it would be rather interesting to do some predictions
here. Let’s predict satisfaction for all combinations of high and
low age, severity and anxiety. I’ll use the quartiles for high and
low. There is a straightforward but ugly way:</p>
<div class="sourceCode" id="cb42"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb42-1" title="1">quartiles &lt;-<span class="st"> </span>satisf <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">summarize</span>(</a>
<a class="sourceLine" id="cb42-2" title="2">  <span class="dt">age_q1 =</span> <span class="kw">quantile</span>(age, <span class="fl">0.25</span>),</a>
<a class="sourceLine" id="cb42-3" title="3">  <span class="dt">age_q3 =</span> <span class="kw">quantile</span>(age, <span class="fl">0.75</span>),</a>
<a class="sourceLine" id="cb42-4" title="4">  <span class="dt">severity_q1 =</span> <span class="kw">quantile</span>(severity, <span class="fl">0.25</span>),</a>
<a class="sourceLine" id="cb42-5" title="5">  <span class="dt">severity_q3 =</span> <span class="kw">quantile</span>(severity, <span class="fl">0.75</span>),</a>
<a class="sourceLine" id="cb42-6" title="6">  <span class="dt">anxiety_q1 =</span> <span class="kw">quantile</span>(anxiety, <span class="fl">0.25</span>),</a>
<a class="sourceLine" id="cb42-7" title="7">  <span class="dt">anxiety_q3 =</span> <span class="kw">quantile</span>(anxiety, <span class="fl">0.75</span>)</a>
<a class="sourceLine" id="cb42-8" title="8">)</a></code></pre></div>
<p>This is ugly because of all the repetition (same quantiles of
different variables), and the programmer in you should be offended by
the ugliness. Anyway, it gives what we want:</p>
<div class="sourceCode" id="cb43"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb43-1" title="1">quartiles</a></code></pre></div>
<pre><code>## # A tibble: 1 x 6
##   age_q1 age_q3 severity_q1 severity_q3 anxiety_q1 anxiety_q3
##    &lt;dbl&gt;  &lt;dbl&gt;       &lt;dbl&gt;       &lt;dbl&gt;      &lt;dbl&gt;      &lt;dbl&gt;
## 1     33   44.5          48        53.5       2.15        2.4</code></pre>
<div class="sourceCode" id="cb45"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb45-1" title="1">quartiles <span class="op">%&gt;%</span><span class="st"> </span></a>
<a class="sourceLine" id="cb45-2" title="2"><span class="st">  </span><span class="kw">pivot_longer</span>(<span class="kw">everything</span>(), <span class="dt">names_to=</span><span class="kw">c</span>(<span class="st">&quot;.value&quot;</span>, <span class="st">&quot;which_q&quot;</span>), <span class="dt">names_sep=</span><span class="st">&quot;_&quot;</span>)</a></code></pre></div>
<pre><code>## # A tibble: 2 x 4
##   which_q   age severity anxiety
##   &lt;chr&gt;   &lt;dbl&gt;    &lt;dbl&gt;   &lt;dbl&gt;
## 1 q1       33       48      2.15
## 2 q3       44.5     53.5    2.4</code></pre>
<p>You can copy the numbers from here to below, or you can do some
cleverness to get them in the right places:</p>
<div class="sourceCode" id="cb47"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb47-1" title="1">quartiles <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb47-2" title="2"><span class="st">  </span><span class="kw">pivot_longer</span>(<span class="kw">everything</span>(), <span class="dt">names_to=</span><span class="st">&quot;var_q&quot;</span>, <span class="dt">values_to=</span><span class="st">&quot;quartile&quot;</span>) <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb47-3" title="3"><span class="st">  </span><span class="kw">separate</span>(var_q, <span class="kw">c</span>(<span class="st">&quot;var_name&quot;</span>, <span class="st">&quot;which_q&quot;</span>)) <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb47-4" title="4"><span class="st">  </span><span class="kw">pivot_wider</span>(<span class="dt">names_from=</span>var_name, <span class="dt">values_from=</span>quartile)</a></code></pre></div>
<pre><code>## # A tibble: 2 x 4
##   which_q   age severity anxiety
##   &lt;chr&gt;   &lt;dbl&gt;    &lt;dbl&gt;   &lt;dbl&gt;
## 1 q1       33       48      2.15
## 2 q3       44.5     53.5    2.4</code></pre>
<p>This combo of <code>pivot_longer</code> and <code>separate</code> can be shortened further by specifying <em>two</em> names in <code>names_to</code>, and also specifying a <code>names_sep</code> to say what they’re separated by:</p>
<div class="sourceCode" id="cb49"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb49-1" title="1">quartiles <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb49-2" title="2"><span class="st">  </span><span class="kw">pivot_longer</span>(<span class="kw">everything</span>(), <span class="dt">names_to=</span><span class="kw">c</span>(<span class="st">&quot;var_q&quot;</span>, <span class="st">&quot;which_q&quot;</span>), </a>
<a class="sourceLine" id="cb49-3" title="3">               <span class="dt">names_sep=</span><span class="st">&quot;_&quot;</span>, <span class="dt">values_to=</span><span class="st">&quot;quartile&quot;</span>) <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb49-4" title="4"><span class="st">  </span><span class="kw">pivot_wider</span>(<span class="dt">names_from=</span>var_q, <span class="dt">values_from=</span>quartile)</a></code></pre></div>
<pre><code>## # A tibble: 2 x 4
##   which_q   age severity anxiety
##   &lt;chr&gt;   &lt;dbl&gt;    &lt;dbl&gt;   &lt;dbl&gt;
## 1 q1       33       48      2.15
## 2 q3       44.5     53.5    2.4</code></pre>
<p>Believe it or not, this can be shortened even further, thus:</p>
<div class="sourceCode" id="cb51"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb51-1" title="1">quartiles <span class="op">%&gt;%</span><span class="st"> </span></a>
<a class="sourceLine" id="cb51-2" title="2"><span class="st">  </span><span class="kw">pivot_longer</span>(<span class="kw">everything</span>(), <span class="dt">names_to=</span><span class="kw">c</span>(<span class="st">&quot;.value&quot;</span>, <span class="st">&quot;which_q&quot;</span>), <span class="dt">names_sep=</span><span class="st">&quot;_&quot;</span>)</a></code></pre></div>
<pre><code>## # A tibble: 2 x 4
##   which_q   age severity anxiety
##   &lt;chr&gt;   &lt;dbl&gt;    &lt;dbl&gt;   &lt;dbl&gt;
## 1 q1       33       48      2.15
## 2 q3       44.5     53.5    2.4</code></pre>
<p>The place where this approach gains is when <code>pivot_longer</code> goes too far, making <em>everything</em> longer, when you want some of it to be wider and thus you needed a <code>pivot_wider</code> at the end. Once again, you use two things in the <code>names_to</code>, but this time instead of giving both variables names, you use the special name <code>.value</code> for the thing you want to end up in columns. The original data frame <code>quartiles</code> had columns with names like <code>severity_q1</code>, so here that is the first thing: <code>age</code> and <code>severity</code> and <code>anxiety</code> will be used as column names, and filled automatically with the values for <code>q1</code> and <code>q3</code>, so you don’t specify a <code>values_to</code>.</p>
<p>This is one of those very dense pieces of coding, where you accomplish a lot in a small space. If it is too dense for you, you can go back to one of the two previous ways of doing it, eg. the simple <code>pivot_longer</code> followed by <code>separate</code> followed by <code>pivot_wider</code>. Sometimes there is value in using a larger number of simpler tools to get where you want.</p>
<p>Those data frames above are we want for below. Let’s test the first way of coding it line by line to see exactly
what it did: (The second way does the first two lines in one, and the third way does all three.)</p>
<div class="sourceCode" id="cb53"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb53-1" title="1">quartiles <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb53-2" title="2"><span class="st">  </span><span class="kw">pivot_longer</span>(<span class="kw">everything</span>(), <span class="dt">names_to=</span><span class="st">&quot;var_q&quot;</span>, <span class="dt">values_to=</span><span class="st">&quot;quartile&quot;</span>) </a></code></pre></div>
<pre><code>## # A tibble: 6 x 2
##   var_q       quartile
##   &lt;chr&gt;          &lt;dbl&gt;
## 1 age_q1         33   
## 2 age_q3         44.5 
## 3 severity_q1    48   
## 4 severity_q3    53.5 
## 5 anxiety_q1      2.15
## 6 anxiety_q3      2.4</code></pre>
<p>Making longer. <code>everything()</code> is a select-helper saying
“pivot-longer <em>all</em> the columns”.</p>
<div class="sourceCode" id="cb55"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb55-1" title="1">quartiles <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb55-2" title="2"><span class="st">  </span><span class="kw">pivot_longer</span>(<span class="kw">everything</span>(), <span class="dt">names_to=</span><span class="st">&quot;var_q&quot;</span>, <span class="dt">values_to=</span><span class="st">&quot;quartile&quot;</span>) <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb55-3" title="3"><span class="st">  </span><span class="kw">separate</span>(var_q, <span class="kw">c</span>(<span class="st">&quot;var_name&quot;</span>, <span class="st">&quot;which_q&quot;</span>)) </a></code></pre></div>
<pre><code>## # A tibble: 6 x 3
##   var_name which_q quartile
##   &lt;chr&gt;    &lt;chr&gt;      &lt;dbl&gt;
## 1 age      q1         33   
## 2 age      q3         44.5 
## 3 severity q1         48   
## 4 severity q3         53.5 
## 5 anxiety  q1          2.15
## 6 anxiety  q3          2.4</code></pre>
<p>The column <code>var_q</code> above encodes a variable <em>and</em> a
quartile, so split them up. By default, <code>separate</code> splits at an
underscore, which is why the things in <code>quartiles</code> were named
with underscores.<a href="#fn3" class="footnote-ref" id="fnref3"><sup>3</sup></a></p>
<p>Now put the variable names back in the columns:</p>
<div class="sourceCode" id="cb57"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb57-1" title="1">quartiles <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb57-2" title="2"><span class="st">  </span><span class="kw">pivot_longer</span>(<span class="kw">everything</span>(), <span class="dt">names_to=</span><span class="st">&quot;var_q&quot;</span>, <span class="dt">values_to=</span><span class="st">&quot;quartile&quot;</span>) <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb57-3" title="3"><span class="st">  </span><span class="kw">separate</span>(var_q, <span class="kw">c</span>(<span class="st">&quot;var_name&quot;</span>, <span class="st">&quot;which_q&quot;</span>)) <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb57-4" title="4"><span class="st">  </span><span class="kw">pivot_wider</span>(<span class="dt">names_from=</span>var_name, <span class="dt">values_from=</span>quartile) -&gt;<span class="st"> </span>qq</a>
<a class="sourceLine" id="cb57-5" title="5">qq</a></code></pre></div>
<pre><code>## # A tibble: 2 x 4
##   which_q   age severity anxiety
##   &lt;chr&gt;   &lt;dbl&gt;    &lt;dbl&gt;   &lt;dbl&gt;
## 1 q1       33       48      2.15
## 2 q3       44.5     53.5    2.4</code></pre>
<p>I make <code>var_name</code> wider, carrying along the values in
<code>quartile</code> (which means that the rows will get matched up by
<code>which_q</code>).</p>
<p>Now, let’s think about why we were doing that. We want to do
predictions of all possible combinations of those values of age and
anxiety and severity.
Doing “all possible combinations” calls for <code>crossing</code>,
which looks like this. It uses the output from one of the above pipelines, which I saved in <code>qq</code>:</p>
<div class="sourceCode" id="cb59"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb59-1" title="1">satisf.new &lt;-<span class="st"> </span><span class="kw">with</span>(qq, <span class="kw">crossing</span>(age, anxiety, severity))</a>
<a class="sourceLine" id="cb59-2" title="2">satisf.new</a></code></pre></div>
<pre><code>## # A tibble: 8 x 3
##     age anxiety severity
##   &lt;dbl&gt;   &lt;dbl&gt;    &lt;dbl&gt;
## 1  33      2.15     48  
## 2  33      2.15     53.5
## 3  33      2.4      48  
## 4  33      2.4      53.5
## 5  44.5    2.15     48  
## 6  44.5    2.15     53.5
## 7  44.5    2.4      48  
## 8  44.5    2.4      53.5</code></pre>
<p>There are two possibilities for each variable, so there are <span class="math inline">\(2^3=8\)</span>
“all possible combinations”. You can check that <code>crossing</code> got
them all.</p>
<p>This is a data frame containing all the values we want to predict for,
with columns having names that are the same as the variables in the
regression, so it’s ready to go into <code>predict</code>. I’ll do
prediction intervals, just because:</p>
<div class="sourceCode" id="cb61"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb61-1" title="1">pp &lt;-<span class="st"> </span><span class="kw">predict</span>(satisf<span class="fl">.1</span>, satisf.new, <span class="dt">interval =</span> <span class="st">&quot;p&quot;</span>)</a>
<a class="sourceLine" id="cb61-2" title="2"><span class="kw">cbind</span>(satisf.new, pp)</a></code></pre></div>
<pre><code>##    age anxiety severity      fit      lwr      upr
## 1 33.0    2.15     48.0 72.45391 50.11023 94.79759
## 2 33.0    2.15     53.5 68.79143 45.11580 92.46706
## 3 33.0    2.40     48.0 70.30065 46.84885 93.75246
## 4 33.0    2.40     53.5 66.63817 43.77908 89.49727
## 5 44.5    2.15     48.0 58.53525 35.87346 81.19705
## 6 44.5    2.15     53.5 54.87277 31.28639 78.45915
## 7 44.5    2.40     48.0 56.38200 33.09400 79.66999
## 8 44.5    2.40     53.5 52.71951 30.44067 74.99836</code></pre>
<p>Looking at the predictions themselves (in <code>fit</code>), you can see
that <code>age</code> has a huge effect. If you compare the 1st and 5th
lines (or the 2nd and 6th, 3rd and 7th, ) you see that
increasing age by 13.5 years, while leaving the other variables the
same, decreases the satisfaction score by over 15 on
average. Changing <code>severity</code>, while leaving everything else the
same, has in comparison a tiny effect, just over 2 points. (Compare
eg. 1st and 2nd lines.) Anxiety has an in-between effect: increasing
anxiety from 2.1 to 2.475, leaving everything else fixed, decreases
satisfaction by about 5 points on average.</p>
<p>I chose the quartiles on purpose: to demonstrate the change in average
satisfaction by changing the explanatory variable by an appreciable
fraction of its range of values. That is, I changed <code>severity</code>
by “a fair bit”, and still the effect on satisfaction scores was small.</p>
<p>Are any of these prediction intervals longer or shorter? We can calculate how
long they are. Look at the predictions:</p>
<div class="sourceCode" id="cb63"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb63-1" title="1">pp</a></code></pre></div>
<pre><code>##        fit      lwr      upr
## 1 72.45391 50.11023 94.79759
## 2 68.79143 45.11580 92.46706
## 3 70.30065 46.84885 93.75246
## 4 66.63817 43.77908 89.49727
## 5 58.53525 35.87346 81.19705
## 6 54.87277 31.28639 78.45915
## 7 56.38200 33.09400 79.66999
## 8 52.71951 30.44067 74.99836</code></pre>
<p>This is unfortunately not a data frame:</p>
<div class="sourceCode" id="cb65"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb65-1" title="1"><span class="kw">class</span>(pp)</a></code></pre></div>
<pre><code>## [1] &quot;matrix&quot; &quot;array&quot;</code></pre>
<p>so we make it one before calculating the lengths.
We want <code>upr</code> minus <code>lwr</code>:</p>
<div class="sourceCode" id="cb67"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb67-1" title="1">pp <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb67-2" title="2"><span class="st">  </span><span class="kw">as_tibble</span>() <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb67-3" title="3"><span class="st">  </span><span class="kw">transmute</span>(<span class="dt">pi.length =</span> upr <span class="op">-</span><span class="st"> </span>lwr)</a></code></pre></div>
<pre><code>## # A tibble: 8 x 1
##   pi.length
##       &lt;dbl&gt;
## 1      44.7
## 2      47.4
## 3      46.9
## 4      45.7
## 5      45.3
## 6      47.2
## 7      46.6
## 8      44.6</code></pre>
<p>Now, I don’t want to keep the other stuff from <code>pp</code>, so I used
<code>transmute</code> instead of <code>mutate</code>; <code>transmute</code>
keeps <em>only</em> the new variable(s) that I calculate and throws away
the others.<a href="#fn4" class="footnote-ref" id="fnref4"><sup>4</sup></a></p>
<p>Then I put that side by side with the values being predicted for:</p>
<div class="sourceCode" id="cb69"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb69-1" title="1">pp <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb69-2" title="2"><span class="st">  </span><span class="kw">as_tibble</span>() <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb69-3" title="3"><span class="st">  </span><span class="kw">transmute</span>(<span class="dt">pi.length =</span> upr <span class="op">-</span><span class="st"> </span>lwr) <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb69-4" title="4"><span class="st">  </span><span class="kw">bind_cols</span>(satisf.new) <span class="op">%&gt;%</span><span class="st"> </span></a>
<a class="sourceLine" id="cb69-5" title="5"><span class="st">  </span><span class="kw">arrange</span>(pi.length)</a></code></pre></div>
<pre><code>## # A tibble: 8 x 4
##   pi.length   age anxiety severity
##       &lt;dbl&gt; &lt;dbl&gt;   &lt;dbl&gt;    &lt;dbl&gt;
## 1      44.6  44.5    2.4      53.5
## 2      44.7  33      2.15     48  
## 3      45.3  44.5    2.15     48  
## 4      45.7  33      2.4      53.5
## 5      46.6  44.5    2.4      48  
## 6      46.9  33      2.4      48  
## 7      47.2  44.5    2.15     53.5
## 8      47.4  33      2.15     53.5</code></pre>
<p>Two of these are noticeably shorter than the others. These are high-everything and low-everything. If you
look back at the scatterplot matrix of (<a href="#part:scatmat">here</a>), you’ll
see that the explanatory variables have positive correlations with
each other. This means that when one of them is low, the other ones
will tend to be low as well (and correspondingly high with high). That
is, most of the data is at or near the low-low-low end or the
high-high-high end, and so those values will be easiest to predict for.</p>
<p>I was actually expecting more of an effect, but what I expected is
actually there.</p>
<p>In the backward elimination part (coming up), I found that only
<code>age</code> and <code>anxiety</code> had a significant impact on
satisfaction, so I can plot these two explanatory variables against
each other to see where most of the values are:</p>
<div class="sourceCode" id="cb71"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb71-1" title="1"><span class="kw">ggplot</span>(satisf, <span class="kw">aes</span>(<span class="dt">x =</span> age, <span class="dt">y =</span> anxiety)) <span class="op">+</span><span class="st"> </span><span class="kw">geom_point</span>()</a></code></pre></div>
<p><img src="pasias_files/figure-html/unnamed-chunk-55-1.png" width="672" /></p>
<p>There is basically <em>no</em> data with low age and high anxiety, or
with high age and low anxiety, so these combinations will be difficult
to predict satisfaction for (and thus their prediction intervals will
be longer).</p>
<p><span class="math inline">\(\blacksquare\)</span></p>
<ol style="list-style-type: lower-roman">
<li>Carry out a backward elimination to determine which of
<code>age</code>, <code>severity</code> and <code>anxiety</code> are needed to
predict satisfaction. What do you get?</li>
</ol>
<p>Solution</p>
<p>This means starting with the regression containing all the explanatory
variables, which is the one I called <code>satisf.1</code>:</p>
<div class="sourceCode" id="cb72"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb72-1" title="1"><span class="kw">summary</span>(satisf<span class="fl">.1</span>)</a></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = satis ~ age + severity + anxiety, data = satisf)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -16.954  -7.154   1.550   6.599  14.888 
## 
## Coefficients:
##             Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept) 162.8759    25.7757   6.319 4.59e-06 ***
## age          -1.2103     0.3015  -4.015  0.00074 ***
## severity     -0.6659     0.8210  -0.811  0.42736    
## anxiety      -8.6130    12.2413  -0.704  0.49021    
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 10.29 on 19 degrees of freedom
## Multiple R-squared:  0.6727, Adjusted R-squared:  0.621 
## F-statistic: 13.01 on 3 and 19 DF,  p-value: 7.482e-05</code></pre>
<p>Pull out the least-significant (highest P-value) variable, which here
is <code>severity</code>. We already decided that this had nothing to add:</p>
<div class="sourceCode" id="cb74"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb74-1" title="1">satisf<span class="fl">.2</span> &lt;-<span class="st"> </span><span class="kw">update</span>(satisf<span class="fl">.1</span>, . <span class="op">~</span><span class="st"> </span>. <span class="op">-</span><span class="st"> </span>severity)</a>
<a class="sourceLine" id="cb74-2" title="2"><span class="kw">summary</span>(satisf<span class="fl">.2</span>)</a></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = satis ~ age + anxiety, data = satisf)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -17.868  -6.649   2.506   6.445  16.120 
## 
## Coefficients:
##             Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept) 147.0751    16.7334   8.789 2.64e-08 ***
## age          -1.2434     0.2961  -4.199 0.000442 ***
## anxiety     -15.8906     8.2556  -1.925 0.068593 .  
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 10.2 on 20 degrees of freedom
## Multiple R-squared:  0.6613, Adjusted R-squared:  0.6275 
## F-statistic: 19.53 on 2 and 20 DF,  p-value: 1.985e-05</code></pre>
<p>If you like, copy and paste the first <code>lm</code>, edit it to get rid
of <code>severity</code>, and run it again. But when I have a
“small change” to make to a model, I like to use <code>update</code>.</p>
<p>Having taken <code>severity</code> out, <code>anxiety</code> has become
strongly significant. Since all of the explanatory variables are now
significant, this is where we stop. If we’re predicting satisfaction,
we need to know both a patient’s age and their anxiety score: being
older or more anxious is associated with a <em>decrease</em> in satisfaction.</p>
<p>There is also a function <code>step</code> that will do this for you:</p>
<div class="sourceCode" id="cb76"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb76-1" title="1"><span class="kw">step</span>(satisf<span class="fl">.1</span>, <span class="dt">direction =</span> <span class="st">&quot;backward&quot;</span>, <span class="dt">test =</span> <span class="st">&quot;F&quot;</span>)</a></code></pre></div>
<pre><code>## Start:  AIC=110.84
## satis ~ age + severity + anxiety
## 
##            Df Sum of Sq    RSS    AIC F value    Pr(&gt;F)    
## - anxiety   1     52.41 2064.0 109.43  0.4951 0.4902110    
## - severity  1     69.65 2081.2 109.62  0.6579 0.4273559    
## &lt;none&gt;                  2011.6 110.84                      
## - age       1   1706.67 3718.3 122.97 16.1200 0.0007404 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Step:  AIC=109.43
## satis ~ age + severity
## 
##            Df Sum of Sq    RSS    AIC F value    Pr(&gt;F)    
## &lt;none&gt;                  2064.0 109.43                      
## - severity  1    402.78 2466.8 111.53  3.9029 0.0621629 .  
## - age       1   1960.56 4024.6 122.79 18.9977 0.0003042 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<pre><code>## 
## Call:
## lm(formula = satis ~ age + severity, data = satisf)
## 
## Coefficients:
## (Intercept)          age     severity  
##     166.591       -1.260       -1.089</code></pre>
<p>with the same result. This function doesn’t actually use P-values;
instead it uses a thing called AIC. At each step, the variable with
the lowest AIC comes out, and when <code>&lt;none&gt;</code> bubbles up to the
top, that’s when you stop. The <code>test="F"</code> means
“include an <span class="math inline">\(F\)</span>-test”, but the procedure still uses AIC (it just shows you an
<span class="math inline">\(F\)</span>-test each time as well). In this case, the other variables were
in the same order throughout, but they don’t have to be (in the same
way that removing one variable from a multiple regression can
dramatically change the P-values of the ones that remain). Here, at
the first step, <code>&lt;none&gt;</code> and <code>anxiety</code> were pretty
close, but when <code>severity</code> came out, taking out nothing was a
<em>lot</em> better than taking out <code>anxiety</code>.</p>
<p>The <code>test="F"</code> on the end gets you the P-values. Using the
<span class="math inline">\(F\)</span>-test is right for regressions; for things like logistic regression
that we see later, <code>test="Chisq"</code> is the right one to
use.<a href="#fn5" class="footnote-ref" id="fnref5"><sup>5</sup></a></p>
<p><span class="math inline">\(\blacksquare\)</span></p>
</div>
<div id="handling-shipments-of-chemicals-1" class="section level2">
<h2><span class="header-section-number">17.7</span> Handling shipments of chemicals</h2>
<p>The data in
<a href="http://statweb.lsu.edu/EXSTWeb/StatLab/DataSets/NKNWData/CH06PR09.txt">link</a>
are on shipments of chemicals in drums that arrive at a warehouse. In
order, the variables are:</p>
<ul>
<li><p>the number of minutes required to handle the shipment</p></li>
<li><p>the number of drums in the shipment</p></li>
<li><p>the total weight of the shipment, in hundreds of pounds.</p></li>
</ul>
<ol style="list-style-type: lower-alpha">
<li>The data set has two features: <em>no</em> column names, and
data aligned in columns (that is, more than one space between data
values). Read the data in, giving the columns suitable names. To do
this, you may have to consult an appropriate help file, or do some
searching, perhaps of one of the other questions on this assignment.</li>
</ol>
<p>Solution</p>
<p>The alignment of columns means that we need to use
<code>read_table</code>. Once you’ve figured <em>that</em> out, you can
search for help by typing <code>?read_table</code> in the Console
window (the help will appear bottom right), or you can put the
same thing into an R Notebook code chunk, and when you run the
chunk, the help will be displayed. (Press control-shift-1 to go
back to the notebook.)
Or you can Google it, of course.
The key observation is that you need to supply some column names
in <code>col_names</code>, like this:</p>
<div class="sourceCode" id="cb79"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb79-1" title="1">my_url &lt;-<span class="st"> &quot;http://statweb.lsu.edu/EXSTWeb/StatLab/DataSets/NKNWData/CH06PR09.txt&quot;</span></a>
<a class="sourceLine" id="cb79-2" title="2">cols &lt;-<span class="st"> </span><span class="kw">c</span>(<span class="st">&quot;minutes&quot;</span>, <span class="st">&quot;drums&quot;</span>, <span class="st">&quot;weight&quot;</span>)</a>
<a class="sourceLine" id="cb79-3" title="3">chemicals &lt;-<span class="st"> </span><span class="kw">read_table</span>(my_url, <span class="dt">col_names =</span> cols)</a></code></pre></div>
<pre><code>## 
## ── Column specification ──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
## cols(
##   minutes = col_double(),
##   drums = col_double(),
##   weight = col_double()
## )</code></pre>
<div class="sourceCode" id="cb81"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb81-1" title="1">chemicals</a></code></pre></div>
<pre><code>## # A tibble: 20 x 3
##    minutes drums weight
##      &lt;dbl&gt; &lt;dbl&gt;  &lt;dbl&gt;
##  1      58     7   5.11
##  2     152    18  16.7 
##  3      41     5   3.2 
##  4      93    14   7.03
##  5     101    11  11.0 
##  6      38     5   4.04
##  7     203    23  22.1 
##  8      78     9   7.03
##  9     117    16  10.6 
## 10      44     5   4.76
## 11     121    17  11.0 
## 12     112    12   9.51
## 13      50     6   3.79
## 14      82    12   6.45
## 15      48     8   4.6 
## 16     127    15  13.9 
## 17     140    17  13.0 
## 18     155    21  15.2 
## 19      39     6   3.64
## 20      90    11   9.57</code></pre>
<p>I like to define my URL and column names up front. You can define
either of them in the <code>read_table</code>, but it makes that line
longer. Up to you.</p>
<p>There is no <code>skip</code> here, because the data file starts right
away with the data and we want to use all the values: we are
<em>adding</em> names to what’s in the data file. If you used
<code>skip</code>, you will be one observation short all the way through,
and your output will be slightly different from mine all the way
through.</p>
<p>Use any names you like, but they should resemble what the columns
actually represent.</p>
<p><span class="math inline">\(\blacksquare\)</span></p>
<ol start="2" style="list-style-type: lower-alpha">
<li>Fit a regression predicting the number of minutes required
to handle a shipment from the other two variables. Display the results.</li>
</ol>
<p>Solution</p>
<div class="sourceCode" id="cb83"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb83-1" title="1">minutes<span class="fl">.1</span> &lt;-<span class="st"> </span><span class="kw">lm</span>(minutes <span class="op">~</span><span class="st"> </span>drums <span class="op">+</span><span class="st"> </span>weight, <span class="dt">data =</span> chemicals)</a>
<a class="sourceLine" id="cb83-2" title="2"><span class="kw">summary</span>(minutes<span class="fl">.1</span>)</a></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = minutes ~ drums + weight, data = chemicals)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -8.8353 -3.5591 -0.0533  2.4018 15.1515 
## 
## Coefficients:
##             Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)   3.3243     3.1108   1.069      0.3    
## drums         3.7681     0.6142   6.135 1.10e-05 ***
## weight        5.0796     0.6655   7.632 6.89e-07 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 5.618 on 17 degrees of freedom
## Multiple R-squared:  0.9869, Adjusted R-squared:  0.9854 
## F-statistic: 641.6 on 2 and 17 DF,  p-value: &lt; 2.2e-16</code></pre>
<p><span class="math inline">\(\blacksquare\)</span></p>
<ol start="3" style="list-style-type: lower-alpha">
<li>Explain carefully but briefly what the slope coefficients
for the two explanatory variables represent. Do their signs
(positive or negative) make practical sense in the context of
handling shipments of chemicals?</li>
</ol>
<p>Solution</p>
<p>The slope coefficient for <code>drums</code> is 3.77; this means that
a shipment with one extra drum (but the same total weight) would
take on average 3.77 minutes longer to handle. Likewise, the slope
coefficient for <code>weight</code> is 5.08, so a shipment that
weighs 1 hundred more pounds but has the same number of drums
will take 5.08 more minutes to handle.
Or “each additional drum, all else equal, will take 3.77 more minutes to handle”, or similar wording. You have to get at two
things: a one-unit increase in the explanatory variable going with
a certain increase in the response, and <em>also</em> the “all else equal” part. How you say it is up to you, but you need to say it.
That was two marks. The third one comes from noting that both
slope coefficients are positive, so making a shipment either
contain more drums or weigh more makes the handling time longer as
well. This makes perfect sense, since either kind of increase
would make the shipment more difficult to handle, and thus take
longer.
I was <em>not</em> asking about P-values. There isn’t really much to
say about those: they’re both significant, so the handling time
depends on both the total weight and the number of drums. Removing
either from the regression would be a mistake.</p>
<p><span class="math inline">\(\blacksquare\)</span></p>
<ol start="4" style="list-style-type: lower-alpha">
<li>Obtain plots of residuals against fitted values, residuals
against explanatory variables, and a normal quantile plot of the residuals.</li>
</ol>
<p>Solution</p>
<p>These are the standard plots from a multiple regression. The
second one requires care, but the first and last should be straightforward.
Residuals against fitted values:</p>
<div class="sourceCode" id="cb85"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb85-1" title="1"><span class="kw">ggplot</span>(minutes<span class="fl">.1</span>, <span class="kw">aes</span>(<span class="dt">x =</span> .fitted, <span class="dt">y =</span> .resid)) <span class="op">+</span><span class="st"> </span><span class="kw">geom_point</span>()</a></code></pre></div>
<p><img src="pasias_files/figure-html/unnamed-chunk-61-1.png" width="672" /></p>
<p>The tricky part about the second one is that the <span class="math inline">\(x\)</span>-values and the
residuals come from different data frames, which has to get expressed
in the <code>ggplot</code>. The obvious way is to do the two plots (one
for each explanatory variable) one at a time:</p>
<div class="sourceCode" id="cb86"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb86-1" title="1"><span class="kw">ggplot</span>(minutes<span class="fl">.1</span>, <span class="kw">aes</span>(<span class="dt">x =</span> chemicals<span class="op">$</span>drums, <span class="dt">y =</span> .resid)) <span class="op">+</span><span class="st"> </span><span class="kw">geom_point</span>()</a></code></pre></div>
<p><img src="pasias_files/figure-html/unnamed-chunk-62-1.png" width="672" /></p>
<p>and</p>
<div class="sourceCode" id="cb87"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb87-1" title="1"><span class="kw">ggplot</span>(minutes<span class="fl">.1</span>, <span class="kw">aes</span>(<span class="dt">x =</span> chemicals<span class="op">$</span>weight, <span class="dt">y =</span> .resid)) <span class="op">+</span><span class="st"> </span><span class="kw">geom_point</span>()</a></code></pre></div>
<p><img src="pasias_files/figure-html/unnamed-chunk-63-1.png" width="672" /></p>
<p>What would also work is to make a data frame first with the things to plot:</p>
<div class="sourceCode" id="cb88"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb88-1" title="1">dd &lt;-<span class="st"> </span><span class="kw">tibble</span>(<span class="dt">weight =</span> chemicals<span class="op">$</span>weight, <span class="dt">drums =</span> chemicals<span class="op">$</span>drums, <span class="dt">res =</span> <span class="kw">resid</span>(minutes<span class="fl">.1</span>))</a></code></pre></div>
<p>and then:</p>
<div class="sourceCode" id="cb89"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb89-1" title="1"><span class="kw">ggplot</span>(dd, <span class="kw">aes</span>(<span class="dt">x =</span> weight, <span class="dt">y =</span> res)) <span class="op">+</span><span class="st"> </span><span class="kw">geom_point</span>()</a></code></pre></div>
<p><img src="pasias_files/figure-html/unnamed-chunk-65-1.png" width="672" /></p>
<p>and similarly for <code>drums</code>. The <code>resid</code> with the model
name in brackets seems to be necessary.</p>
<p>Another way to approach this is <code>augment</code> from
<code>broom</code>. That does this:</p>
<div class="sourceCode" id="cb90"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb90-1" title="1"><span class="kw">library</span>(broom)</a>
<a class="sourceLine" id="cb90-2" title="2">d &lt;-<span class="st"> </span>minutes<span class="fl">.1</span> <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">augment</span>(chemicals)</a>
<a class="sourceLine" id="cb90-3" title="3"><span class="kw">as_tibble</span>(d)</a></code></pre></div>
<pre><code>## # A tibble: 20 x 9
##    minutes drums weight .fitted .resid   .hat .sigma  .cooksd .std.resid
##      &lt;dbl&gt; &lt;dbl&gt;  &lt;dbl&gt;   &lt;dbl&gt;  &lt;dbl&gt;  &lt;dbl&gt;  &lt;dbl&gt;    &lt;dbl&gt;      &lt;dbl&gt;
##  1      58     7   5.11    55.7  2.34  0.0913   5.76 0.00641      0.437 
##  2     152    18  16.7    156.  -4.08  0.194    5.68 0.0524      -0.809 
##  3      41     5   3.2     38.4  2.58  0.131    5.75 0.0122       0.493 
##  4      93    14   7.03    91.8  1.21  0.268    5.78 0.00779      0.252 
##  5     101    11  11.0    101.   0.453 0.149    5.79 0.000445     0.0873
##  6      38     5   4.04    42.7 -4.69  0.141    5.65 0.0441      -0.900 
##  7     203    23  22.1    202.   0.903 0.429    5.78 0.0113       0.213 
##  8      78     9   7.03    72.9  5.05  0.0665   5.64 0.0206       0.931 
##  9     117    16  10.6    118.  -0.559 0.135    5.79 0.000593    -0.107 
## 10      44     5   4.76    46.3 -2.34  0.165    5.75 0.0137      -0.456 
## 11     121    17  11.0    123.  -2.36  0.179    5.75 0.0156      -0.463 
## 12     112    12   9.51    96.8 15.2   0.0514   4.29 0.138        2.77  
## 13      50     6   3.79    45.2  4.82  0.110    5.65 0.0341       0.909 
## 14      82    12   6.45    81.3  0.695 0.156    5.79 0.00112      0.135 
## 15      48     8   4.6     56.8 -8.84  0.0954   5.30 0.0961      -1.65  
## 16     127    15  13.9    130.  -3.25  0.128    5.72 0.0188      -0.619 
## 17     140    17  13.0    134.   6.43  0.0970   5.54 0.0520       1.20  
## 18     155    21  15.2    160.  -4.72  0.230    5.63 0.0914      -0.957 
## 19      39     6   3.64    44.4 -5.42  0.112    5.61 0.0440      -1.02  
## 20      90    11   9.57    93.4 -3.39  0.0725   5.72 0.0102      -0.626</code></pre>
<p>and then you can use <code>d</code> as the “base” data frame from which
everything comes:</p>
<div class="sourceCode" id="cb92"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb92-1" title="1"><span class="kw">ggplot</span>(d, <span class="kw">aes</span>(<span class="dt">x =</span> drums, <span class="dt">y =</span> .resid)) <span class="op">+</span><span class="st"> </span><span class="kw">geom_point</span>()</a></code></pre></div>
<p><img src="pasias_files/figure-html/unnamed-chunk-67-1.png" width="672" /></p>
<p>and</p>
<div class="sourceCode" id="cb93"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb93-1" title="1"><span class="kw">ggplot</span>(d, <span class="kw">aes</span>(<span class="dt">x =</span> weight, <span class="dt">y =</span> .resid)) <span class="op">+</span><span class="st"> </span><span class="kw">geom_point</span>()</a></code></pre></div>
<p><img src="pasias_files/figure-html/unnamed-chunk-68-1.png" width="672" /></p>
<p>or you can even do that trick to put the two plots on facets:</p>
<div class="sourceCode" id="cb94"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb94-1" title="1">d <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb94-2" title="2"><span class="st">  </span><span class="kw">pivot_longer</span>(drums<span class="op">:</span>weight, <span class="dt">names_to=</span><span class="st">&quot;xname&quot;</span>, <span class="dt">values_to=</span><span class="st">&quot;x&quot;</span>) <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb94-3" title="3"><span class="st">  </span><span class="kw">ggplot</span>(<span class="kw">aes</span>(<span class="dt">x =</span> x, <span class="dt">y =</span> .resid)) <span class="op">+</span><span class="st"> </span><span class="kw">geom_point</span>() <span class="op">+</span></a>
<a class="sourceLine" id="cb94-4" title="4"><span class="st">  </span><span class="kw">facet_wrap</span>(<span class="op">~</span>xname)</a></code></pre></div>
<p><img src="pasias_files/figure-html/unnamed-chunk-69-1.png" width="672" /></p>
<p>Last, the normal quantile plot:</p>
<div class="sourceCode" id="cb95"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb95-1" title="1"><span class="kw">ggplot</span>(minutes<span class="fl">.1</span>, <span class="kw">aes</span>(<span class="dt">sample =</span> .resid)) <span class="op">+</span><span class="st"> </span><span class="kw">stat_qq</span>() <span class="op">+</span><span class="st"> </span><span class="kw">stat_qq_line</span>()</a></code></pre></div>
<p><img src="pasias_files/figure-html/unnamed-chunk-70-1.png" width="672" /></p>
<p>As a check for the grader, there should be four plots, obtained
somehow: residuals against fitted values, normal quantile plot of
residuals, residuals against <code>drums</code>, residuals against<br />
<code>weight</code>.</p>
<p><span class="math inline">\(\blacksquare\)</span></p>
<ol start="5" style="list-style-type: lower-alpha">
<li>Do you have any concerns, looking at the residual plots?
Explain briefly.</li>
</ol>
<p>Solution</p>
<p>The (only) concern I have, looking at those four plots, is the one very
positive residual, the one around 15. Take that away, and I think
all of the plots are then acceptable.
Alternatively, I will take something like “I have no concerns about the form of the relationship”, saying that the <em>kind</em>
of model being fitted here is OK (no evidence of non-linearity,
fanning out, that kind of stuff). It’s up to you to decide whether
you think “concerns” extends to outliers, high-influence points,
etc.
The normal quantile plot reveals that the most negative residual,
the one around <span class="math inline">\(-9\)</span>, is in fact almost exactly as negative as you
would expect the most negative residual to be, so it is not an
outlier at all. The residuals are almost exactly normally
distributed, <em>except</em> for the most positive one.
I don’t think you can justify fanning-in, since the evidence for
that is mostly from the single point on the right. The other
points do not really have residuals closer to zero as you move
left to right.</p>
<p>Do <em>not</em> be tempted to pick out everything you can think of wrong
with these plots. The grader can, and will, take away points if you
start naming things that are not concerns.</p>
<p>Extra: what else can I find out about that large-positive-residual
point? This is where having the “augmented” data frame is a plus:</p>
<div class="sourceCode" id="cb96"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb96-1" title="1">d <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">filter</span>(.resid <span class="op">&gt;</span><span class="st"> </span><span class="dv">10</span>)</a></code></pre></div>
<pre><code>## # A tibble: 1 x 9
##   minutes drums weight .fitted .resid   .hat .sigma .cooksd .std.resid
##     &lt;dbl&gt; &lt;dbl&gt;  &lt;dbl&gt;   &lt;dbl&gt;  &lt;dbl&gt;  &lt;dbl&gt;  &lt;dbl&gt;   &lt;dbl&gt;      &lt;dbl&gt;
## 1     112    12   9.51    96.8   15.2 0.0514   4.29   0.138       2.77</code></pre>
<p>As shown. The predicted number of minutes is 96.8, but the actual
number of minutes it took is 112. Hence the residual of 15.2.
Can we find “similar” numbers of <code>drums</code> and
<code>weight</code> and compare the <code>minutes</code>? Try this:</p>
<div class="sourceCode" id="cb98"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb98-1" title="1">chemicals <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">filter</span>(</a>
<a class="sourceLine" id="cb98-2" title="2">  <span class="kw">between</span>(weight, <span class="dv">8</span>, <span class="dv">11</span>),</a>
<a class="sourceLine" id="cb98-3" title="3">  <span class="kw">between</span>(drums, <span class="dv">10</span>, <span class="dv">14</span>)</a>
<a class="sourceLine" id="cb98-4" title="4">)</a></code></pre></div>
<pre><code>## # A tibble: 3 x 3
##   minutes drums weight
##     &lt;dbl&gt; &lt;dbl&gt;  &lt;dbl&gt;
## 1     101    11  11.0 
## 2     112    12   9.51
## 3      90    11   9.57</code></pre>
<p>You might not have seen <code>between</code> before, but it works the way
you’d expect.<a href="#fn6" class="footnote-ref" id="fnref6"><sup>6</sup></a> Two other shipments with similar numbers of drums and
total weight took around 90–100 minutes to handle, so the 112 does
look about 15 minutes too long. This was actually an average-sized shipment:</p>
<div class="sourceCode" id="cb100"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb100-1" title="1"><span class="kw">library</span>(ggrepel)</a>
<a class="sourceLine" id="cb100-2" title="2">d <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb100-3" title="3"><span class="st">  </span><span class="kw">mutate</span>(<span class="dt">my_label =</span> <span class="kw">ifelse</span>(.resid <span class="op">&gt;</span><span class="st"> </span><span class="dv">10</span>, <span class="st">&quot;residual +&quot;</span>, <span class="st">&quot;&quot;</span>)) <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb100-4" title="4"><span class="st">  </span><span class="kw">ggplot</span>(<span class="kw">aes</span>(<span class="dt">x =</span> drums, <span class="dt">y =</span> weight, <span class="dt">colour =</span> minutes, <span class="dt">label =</span> my_label)) <span class="op">+</span></a>
<a class="sourceLine" id="cb100-5" title="5"><span class="st">  </span><span class="kw">geom_point</span>() <span class="op">+</span><span class="st"> </span><span class="kw">geom_text_repel</span>()</a></code></pre></div>
<p><img src="pasias_files/figure-html/unnamed-chunk-73-1.png" width="672" /></p>
<p>so it’s a bit of a mystery why it took so long to handle.</p>
<p>I had some fun with the graph: if you set <code>colour</code> equal to a
continuous variable (as <code>minutes</code> is here), you get a
continuous colour scale, by default from dark blue (small) to light
blue (large). The number of minutes tends to get larger (lighter) as
you go up and to the right with bigger shipments. The point labelled
“residual +” is the one with the large residual; it is a
noticeably lighter blue than the points around it, meaning that it
took longer to handle than those points. I used the trick from C32 to
label “some” (here one) of the points: create a new label variable
with a <code>mutate</code> and an <code>ifelse</code>, leaving all of the
other labels blank so you don’t see them.</p>
<p>The blue colour scheme is a little hard to judge values on. Here’s
another way to do that:</p>
<div class="sourceCode" id="cb101"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb101-1" title="1">d <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb101-2" title="2"><span class="st">  </span><span class="kw">mutate</span>(<span class="dt">my_label =</span> <span class="kw">ifelse</span>(.resid <span class="op">&gt;</span><span class="st"> </span><span class="dv">10</span>, <span class="st">&quot;residual +&quot;</span>, <span class="st">&quot;&quot;</span>)) <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb101-3" title="3"><span class="st">  </span><span class="kw">ggplot</span>(<span class="kw">aes</span>(<span class="dt">x =</span> drums, <span class="dt">y =</span> weight, <span class="dt">colour =</span> minutes, <span class="dt">label =</span> my_label)) <span class="op">+</span></a>
<a class="sourceLine" id="cb101-4" title="4"><span class="st">  </span><span class="kw">geom_point</span>() <span class="op">+</span><span class="st"> </span><span class="kw">geom_text_repel</span>() <span class="op">+</span></a>
<a class="sourceLine" id="cb101-5" title="5"><span class="st">  </span><span class="kw">scale_colour_gradient</span>(<span class="dt">low =</span> <span class="st">&quot;red&quot;</span>, <span class="dt">high =</span> <span class="st">&quot;blue&quot;</span>)</a></code></pre></div>
<p><img src="pasias_files/figure-html/unnamed-chunk-74-1.png" width="672" /></p>
<p>The labelled point is a little more blue (purplish) than the more
clearly red points near it.</p>
<p>The other thing to see is that there is also a positive correlation
between the number of drums and the total weight, which is what you’d
expect. Unlike with some of our other examples, this wasn’t strong
enough to cause problems; the separate effects of <code>drums</code> and
<code>weight</code> on <code>minutes</code> were distinguishable enough to
allow both explanatory variables to have a strongly significant effect
on <code>minutes</code>.</p>
<p>Post scriptum: the “drums” here are not concert-band-type drums, but
something like this:</p>
<p><img src="Chemical-Drums-200x200.png" /></p>
<p><span class="math inline">\(\blacksquare\)</span></p>
</div>
<div id="salaries-of-mathematicians-1" class="section level2">
<h2><span class="header-section-number">17.8</span> Salaries of mathematicians</h2>
<p>A researcher in a scientific
foundation wanted to evaluate the relationship between annual salaries
of mathematicians and three explanatory variables:</p>
<ul>
<li><p>an index of work quality</p></li>
<li><p>number of years of experience</p></li>
<li><p>an index of publication success.</p></li>
</ul>
<p>The data can be found at
<a href="http://ritsokiguess.site/datafiles/mathsal.txt">link</a>. Data from
only a relatively small number of mathematicians were available.</p>
<ol style="list-style-type: lower-alpha">
<li>Read in the data and check that you have a sensible number
of rows and the right number of columns. (What does “a sensible number of rows” mean here?)</li>
</ol>
<p>Solution</p>
<p>This is a tricky one. There are aligned columns, but <em>the column headers are not aligned with them</em>.
Thus <code>read_table2</code> is what you need.</p>
<div class="sourceCode" id="cb102"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb102-1" title="1">my_url &lt;-<span class="st"> &quot;http://ritsokiguess.site/datafiles/mathsal.txt&quot;</span></a>
<a class="sourceLine" id="cb102-2" title="2">salaries &lt;-<span class="st"> </span><span class="kw">read_table2</span>(my_url)</a></code></pre></div>
<pre><code>## 
## ── Column specification ──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
## cols(
##   salary = col_double(),
##   workqual = col_double(),
##   experience = col_double(),
##   pubsucc = col_double()
## )</code></pre>
<div class="sourceCode" id="cb104"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb104-1" title="1">salaries</a></code></pre></div>
<pre><code>## # A tibble: 24 x 4
##    salary workqual experience pubsucc
##     &lt;dbl&gt;    &lt;dbl&gt;      &lt;dbl&gt;   &lt;dbl&gt;
##  1   33.2      3.5          9     6.1
##  2   40.3      5.3         20     6.4
##  3   38.7      5.1         18     7.4
##  4   46.8      5.8         33     6.7
##  5   41.4      4.2         31     7.5
##  6   37.5      6           13     5.9
##  7   39        6.8         25     6  
##  8   40.7      5.5         30     4  
##  9   30.1      3.1          5     5.8
## 10   52.9      7.2         47     8.3
## # … with 14 more rows</code></pre>
<p>24 observations (“only a relatively small number”) and 4 columns,
one for the response and one each for the explanatory variables.</p>
<p>Or, if you like,</p>
<div class="sourceCode" id="cb106"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb106-1" title="1"><span class="kw">dim</span>(salaries)</a></code></pre></div>
<pre><code>## [1] 24  4</code></pre>
<p>for the second part: 24 rows and 4 columns again.
I note, with only 24 observations, that we don’t really have enough
data to investigate the effects of three explanatory variables, but
we’ll do the best we can. If the pattern, whatever it is, is clear
enough, we should be OK.</p>
<p><span class="math inline">\(\blacksquare\)</span></p>
<ol start="2" style="list-style-type: lower-alpha">
<li>Make scatterplots of <code>salary</code> against each of the three explanatory variables. If you can, do this with <em>one</em> <code>ggplot</code>.</li>
</ol>
<p>Solution</p>
<p>The obvious way to do this is as three separate scatterplots,
and that will definitely work. But you can do it in one go if
you think about facets, and about having all the <span class="math inline">\(x\)</span>-values in
one column (and the names of the <span class="math inline">\(x\)</span>-variables in another
column):</p>
<div class="sourceCode" id="cb108"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb108-1" title="1">salaries <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb108-2" title="2"><span class="st">  </span><span class="kw">pivot_longer</span>(<span class="op">-</span>salary, <span class="dt">names_to=</span><span class="st">&quot;xname&quot;</span>, <span class="dt">values_to=</span><span class="st">&quot;x&quot;</span>) <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb108-3" title="3"><span class="st">  </span><span class="kw">ggplot</span>(<span class="kw">aes</span>(<span class="dt">x =</span> x, <span class="dt">y =</span> salary)) <span class="op">+</span><span class="st"> </span><span class="kw">geom_point</span>() <span class="op">+</span></a>
<a class="sourceLine" id="cb108-4" title="4"><span class="st">  </span><span class="kw">facet_wrap</span>(<span class="op">~</span>xname, <span class="dt">ncol =</span> <span class="dv">2</span>, <span class="dt">scales =</span> <span class="st">&quot;free&quot;</span>)</a></code></pre></div>
<p><img src="pasias_files/figure-html/ivybridge-1.png" width="672" /></p>
<p>If you don’t see how that works, run it yourself, one line at a time.</p>
<p>I was thinking ahead a bit while I was coding that: I wanted the three
plots to come out about square, and I wanted the plots to have their
own scales. The last thing in the <code>facet_wrap</code> does the latter,
and arranging the plots in two columns (thinking of the plots as a set
of four with one missing) gets them more or less square.</p>
<p>If you don’t think of those, try it without, and then fix up what you
don’t like.</p>
<p><span class="math inline">\(\blacksquare\)</span></p>
<ol start="3" style="list-style-type: lower-alpha">
<li>Comment briefly on the direction and strength of each
relationship with <code>salary</code>.</li>
</ol>
<p>Solution</p>
<p>To my mind, all of the three relationships are going uphill (that’s the “direction” part). <code>experience</code> is the
strongest, and <code>pubsucc</code> looks the weakest (that’s the
“strength” part). If you want to say there is no relationship
with <code>pubsucc</code>, that’s fine too. This is a judgement
call.
Note that all the relationships are more or less linear (no
obvious curves here). We could also investigate the relationships
among the explanatory variables:</p>
<div class="sourceCode" id="cb109"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb109-1" title="1"><span class="kw">cor</span>(salaries)</a></code></pre></div>
<pre><code>##               salary  workqual experience   pubsucc
## salary     1.0000000 0.6670958  0.8585582 0.5581960
## workqual   0.6670958 1.0000000  0.4669511 0.3227612
## experience 0.8585582 0.4669511  1.0000000 0.2537530
## pubsucc    0.5581960 0.3227612  0.2537530 1.0000000</code></pre>
<p>Mentally cut off the first row and column (<code>salary</code> is the
response). None of the remaining correlations are all that high, so we
ought not to have any multicollinearity problems.</p>
<p><span class="math inline">\(\blacksquare\)</span></p>
<ol start="4" style="list-style-type: lower-alpha">
<li><a name="regone">*</a> Fit a regression predicting salary from the other three
variables, and obtain a <code>summary</code> of the results.</li>
</ol>
<p>Solution</p>
<div class="sourceCode" id="cb111"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb111-1" title="1">salaries<span class="fl">.1</span> &lt;-<span class="st"> </span><span class="kw">lm</span>(salary <span class="op">~</span><span class="st"> </span>workqual <span class="op">+</span><span class="st"> </span>experience <span class="op">+</span><span class="st"> </span>pubsucc, <span class="dt">data =</span> salaries)</a>
<a class="sourceLine" id="cb111-2" title="2"><span class="kw">summary</span>(salaries<span class="fl">.1</span>)</a></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = salary ~ workqual + experience + pubsucc, data = salaries)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -3.2463 -0.9593  0.0377  1.1995  3.3089 
## 
## Coefficients:
##             Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept) 17.84693    2.00188   8.915 2.10e-08 ***
## workqual     1.10313    0.32957   3.347 0.003209 ** 
## experience   0.32152    0.03711   8.664 3.33e-08 ***
## pubsucc      1.28894    0.29848   4.318 0.000334 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 1.753 on 20 degrees of freedom
## Multiple R-squared:  0.9109, Adjusted R-squared:  0.8975 
## F-statistic: 68.12 on 3 and 20 DF,  p-value: 1.124e-10</code></pre>
<p><span class="math inline">\(\blacksquare\)</span></p>
<ol start="5" style="list-style-type: lower-alpha">
<li>How can we justify the statement
“one or more of the explanatory variables helps to predict salary”? How is this
consistent with the value of R-squared?</li>
</ol>
<p>Solution</p>
<p>“One or more of the explanatory variables helps” is an
invitation to consider the (global) <span class="math inline">\(F\)</span>-test for the whole
regression. This has the very small P-value of <span class="math inline">\(1.124\times 10^{-10}\)</span> (from the bottom line of the output): very small, so
one or more of the explanatory variables <em>does</em> help, and
the statement is correct.
The idea that something helps to predict salary suggests
(especially with such a small number of observations) that we
should have a high R-squared. In this case, R-squared is 0.9109,
which is indeed high.</p>
<p><span class="math inline">\(\blacksquare\)</span></p>
<ol start="6" style="list-style-type: lower-alpha">
<li>Would you consider removing any of the variables from this
regression? Why, or why not?</li>
</ol>
<p>Solution</p>
<p>Look at the P-values attached to each variable. These are all
very small: 0.003, 0.00000003 and 0.0003, way smaller than
0.05. So it would be a mistake to
take any, even one, of the variables out: doing so would make the
regression much worse.
If you need convincing of that, see what happens when we take
the variable with the highest P-value out — this is <code>workqual</code>:</p>
<div class="sourceCode" id="cb113"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb113-1" title="1">salaries<span class="fl">.2</span> &lt;-<span class="st"> </span><span class="kw">lm</span>(salary <span class="op">~</span><span class="st"> </span>experience <span class="op">+</span><span class="st"> </span>pubsucc, <span class="dt">data =</span> salaries)</a>
<a class="sourceLine" id="cb113-2" title="2"><span class="kw">summary</span>(salaries<span class="fl">.2</span>)</a></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = salary ~ experience + pubsucc, data = salaries)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -5.2723 -0.7865 -0.3983  1.7277  3.2060 
## 
## Coefficients:
##             Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept) 21.02546    2.14819   9.788 2.82e-09 ***
## experience   0.37376    0.04104   9.107 9.70e-09 ***
## pubsucc      1.52753    0.35331   4.324    3e-04 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 2.137 on 21 degrees of freedom
## Multiple R-squared:  0.8609, Adjusted R-squared:  0.8477 
## F-statistic:    65 on 2 and 21 DF,  p-value: 1.01e-09</code></pre>
<p>R-squared has gone down from 91% to 86%: maybe not so much in the
grand scheme of things, but it is noticeably less. Perhaps better,
since we are comparing models with different numbers of explanatory
variables, is to compare the <em>adjusted</em> R-squared: this has gone
down from 90% to 85%. The fact that this has gone down <em>at all</em>
is enough to say that taking out <code>workqual</code> was a
mistake.<a href="#fn7" class="footnote-ref" id="fnref7"><sup>7</sup></a></p>
<p>Another way of seeing whether a variable has anything to add in a
regression containing the others is a <strong>partial regression plot</strong>.
We take the residuals from <code>salaries.2</code> above and plot
them against the variable we removed, namely
<code>workqual</code>.<a href="#fn8" class="footnote-ref" id="fnref8"><sup>8</sup></a> If
<code>workqual</code> has nothing to add, there will be no pattern; if it
<em>does</em> have something to add, there will be a trend. Like
this. I use <code>augment</code> from <code>broom</code>:</p>
<div class="sourceCode" id="cb115"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb115-1" title="1"><span class="kw">library</span>(broom)</a>
<a class="sourceLine" id="cb115-2" title="2">salaries<span class="fl">.2</span> <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb115-3" title="3"><span class="st">  </span><span class="kw">augment</span>(salaries) <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb115-4" title="4"><span class="st">  </span><span class="kw">ggplot</span>(<span class="kw">aes</span>(<span class="dt">x =</span> workqual, <span class="dt">y =</span> .resid)) <span class="op">+</span><span class="st"> </span><span class="kw">geom_point</span>()</a></code></pre></div>
<p><img src="pasias_files/figure-html/dartington-1.png" width="672" /></p>
<p>This is a mostly straight upward trend. So we
need to add a linear term in <code>workqual</code> to the
regression.<a href="#fn9" class="footnote-ref" id="fnref9"><sup>9</sup></a></p>
<p><span class="math inline">\(\blacksquare\)</span></p>
<ol start="7" style="list-style-type: lower-alpha">
<li>Do you think it would be a mistake to take <em>both</em> of
<code>workqual</code> and <code>pubsucc</code> out of the regression? Do a
suitable test. Was your guess right?</li>
</ol>
<p>Solution</p>
<p>I think it would be a big mistake. Taking even one of these
variables out of the regression is a bad idea (from the
<span class="math inline">\(t\)</span>-tests), so taking out more than one would be a <em>really</em> bad idea.
To perform a test, fit the model without these two explanatory variables:</p>
<div class="sourceCode" id="cb116"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb116-1" title="1">salaries<span class="fl">.3</span> &lt;-<span class="st"> </span><span class="kw">lm</span>(salary <span class="op">~</span><span class="st"> </span>experience, <span class="dt">data =</span> salaries)</a></code></pre></div>
<p>and then use <code>anova</code> to compare the two regressions, smaller
model first:</p>
<div class="sourceCode" id="cb117"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb117-1" title="1"><span class="kw">anova</span>(salaries<span class="fl">.3</span>, salaries<span class="fl">.1</span>)</a></code></pre></div>
<pre><code>## Analysis of Variance Table
## 
## Model 1: salary ~ experience
## Model 2: salary ~ workqual + experience + pubsucc
##   Res.Df     RSS Df Sum of Sq      F    Pr(&gt;F)    
## 1     22 181.191                                  
## 2     20  61.443  2    119.75 19.489 2.011e-05 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<p>The P-value is extremely small, so the bigger model is definitely
better than the smaller one: we really do need all three
variables. Which is what we guessed.</p>
<p><span class="math inline">\(\blacksquare\)</span></p>
<ol start="8" style="list-style-type: lower-alpha">
<li>Back in part (<a href="#regone">here</a>), you fitted a regression with all
three explanatory variables. By making suitable plots, assess
whether there is any evidence that (i) that the linear model should
be a curve, (ii) that the residuals are not normally
distributed, (iii) that there is “fan-out”, where the residuals are getting
bigger <em>in size</em> as the fitted values get bigger? Explain
briefly how you came to your conclusions in each case.</li>
</ol>
<p>Solution</p>
<p>I intended that (i) should just be a matter of looking at residuals
vs. fitted values:</p>
<div class="sourceCode" id="cb119"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb119-1" title="1"><span class="kw">ggplot</span>(salaries<span class="fl">.1</span>, <span class="kw">aes</span>(<span class="dt">x =</span> .fitted, <span class="dt">y =</span> .resid)) <span class="op">+</span><span class="st"> </span><span class="kw">geom_point</span>()</a></code></pre></div>
<p><img src="pasias_files/figure-html/unnamed-chunk-82-1.png" width="672" /></p>
<p>There is no appreciable pattern on here, so no evidence of a curve (or
apparently of any other problems).</p>
<p>Extra: you might read this that we should check residuals against the
<span class="math inline">\(x\)</span>-variables as well, which is a similar trick to the above one for
plotting response against each of the explanatories. There is one step
first, though: use <code>augment</code> from <code>broom</code> first to get a
dataframe with the original <span class="math inline">\(x\)</span>-variables <em>and</em> the residuals in
it. The following thus looks rather complicated, and if it confuses
you, run the code a piece at a time to see what it’s doing:</p>
<div class="sourceCode" id="cb120"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb120-1" title="1">salaries<span class="fl">.1</span> <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb120-2" title="2"><span class="st">  </span><span class="kw">augment</span>(salaries) <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb120-3" title="3"><span class="st">  </span><span class="kw">pivot_longer</span>(workqual<span class="op">:</span>pubsucc, <span class="dt">names_to=</span><span class="st">&quot;xname&quot;</span>, <span class="dt">values_to=</span><span class="st">&quot;x&quot;</span>) <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb120-4" title="4"><span class="st">  </span><span class="kw">ggplot</span>(<span class="kw">aes</span>(<span class="dt">x =</span> x, <span class="dt">y =</span> .resid)) <span class="op">+</span><span class="st"> </span><span class="kw">geom_point</span>() <span class="op">+</span></a>
<a class="sourceLine" id="cb120-5" title="5"><span class="st">  </span><span class="kw">facet_wrap</span>(<span class="op">~</span>xname, <span class="dt">scales =</span> <span class="st">&quot;free&quot;</span>, <span class="dt">ncol =</span> <span class="dv">2</span>)</a></code></pre></div>
<p><img src="pasias_files/figure-html/unnamed-chunk-83-1.png" width="672" /></p>
<p>These three residual plots are also pretty much textbook random, so no problems here either.</p>
<p>For (ii), look at a normal quantile plot of the residuals, which is not as difficult as the plot I just did:</p>
<div class="sourceCode" id="cb121"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb121-1" title="1"><span class="kw">ggplot</span>(salaries<span class="fl">.1</span>, <span class="kw">aes</span>(<span class="dt">sample =</span> .resid)) <span class="op">+</span><span class="st"> </span><span class="kw">stat_qq</span>() <span class="op">+</span><span class="st"> </span><span class="kw">stat_qq_line</span>()</a></code></pre></div>
<p><img src="pasias_files/figure-html/unnamed-chunk-84-1.png" width="672" /></p>
<p>That is really pretty good. Maybe the <em>second</em> smallest point is
a bit far off the line, but otherwise there’s nothing to worry about. A
quick place to look for problems is the extreme observations, and the
largest and smallest residuals are almost exactly the size we’d expect
them to be.</p>
<p>Our graph for assessing fan-in or fan-out is to plot the <em>absolute</em> values of the residuals against the fitted values. The plot from (i) suggests that we won’t have any problems here, but to investigate:</p>
<div class="sourceCode" id="cb122"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb122-1" title="1"><span class="kw">ggplot</span>(salaries<span class="fl">.1</span>, <span class="kw">aes</span>(<span class="dt">x =</span> .fitted, <span class="dt">y =</span> <span class="kw">abs</span>(.resid))) <span class="op">+</span><span class="st"> </span><span class="kw">geom_point</span>() <span class="op">+</span><span class="st"> </span><span class="kw">geom_smooth</span>()</a></code></pre></div>
<pre><code>## `geom_smooth()` using method = &#39;loess&#39; and formula &#39;y ~ x&#39;</code></pre>
<p><img src="pasias_files/figure-html/unnamed-chunk-85-1.png" width="672" /></p>
<p>This is pretty nearly straight across. You might think it increases a
bit at the beginning, but most of the evidence for that comes from the
one observation with fitted value near 30 that happens to have a
residual near zero. Conclusions based on one observation are not to be
trusted!
In summary, I’m happy with this linear multiple regression, and I
don’t see any need to do anything more with it. I am, however, willing
to have some sympathy with opinions that differ from mine, if they are
supported by those graphs above.</p>
<p><span class="math inline">\(\blacksquare\)</span></p>
</div>
<div id="predicting-gpa-of-computer-science-students-1" class="section level2">
<h2><span class="header-section-number">17.9</span> Predicting GPA of computer science students</h2>
<p>The file
<a href="http://ritsokiguess.site/datafiles/gpa.txt">link</a> contains some
measurements of academic achievement for a number of university
students studying computer science:</p>
<ul>
<li><p>High school grade point average</p></li>
<li><p>Math SAT score</p></li>
<li><p>Verbal SAT score</p></li>
<li><p>Computer Science grade point average</p></li>
<li><p>Overall university grade point average.</p></li>
</ul>
<ol style="list-style-type: lower-alpha">
<li>Read in the data and display it (or at least the first ten lines).</li>
</ol>
<p>Solution</p>
<p>The usual:</p>
<div class="sourceCode" id="cb124"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb124-1" title="1">my_url &lt;-<span class="st"> &quot;http://ritsokiguess.site/datafiles/gpa.txt&quot;</span></a>
<a class="sourceLine" id="cb124-2" title="2">gpa &lt;-<span class="st"> </span><span class="kw">read_delim</span>(my_url, <span class="st">&quot; &quot;</span>)</a></code></pre></div>
<pre><code>## 
## ── Column specification ──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
## cols(
##   high_GPA = col_double(),
##   math_SAT = col_double(),
##   verb_SAT = col_double(),
##   comp_GPA = col_double(),
##   univ_GPA = col_double()
## )</code></pre>
<div class="sourceCode" id="cb126"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb126-1" title="1">gpa</a></code></pre></div>
<pre><code>## # A tibble: 105 x 5
##    high_GPA math_SAT verb_SAT comp_GPA univ_GPA
##       &lt;dbl&gt;    &lt;dbl&gt;    &lt;dbl&gt;    &lt;dbl&gt;    &lt;dbl&gt;
##  1     3.45      643      589     3.76     3.52
##  2     2.78      558      512     2.87     2.91
##  3     2.52      583      503     2.54     2.4 
##  4     3.67      685      602     3.83     3.47
##  5     3.24      592      538     3.29     3.47
##  6     2.1       562      486     2.64     2.37
##  7     2.82      573      548     2.86     2.4 
##  8     2.36      559      536     2.03     2.24
##  9     2.42      552      583     2.81     3.02
## 10     3.51      617      591     3.41     3.32
## # … with 95 more rows</code></pre>
<p>Two SAT scores and three GPAs, as promised.</p>
<p><span class="math inline">\(\blacksquare\)</span></p>
<ol start="2" style="list-style-type: lower-alpha">
<li><a name="part:hsu-scatter">*</a> Make a scatterplot of high school GPA against university
GPA. Which variable should be the response and which
explanatory? Explain briefly. Add a smooth trend to your plot.</li>
</ol>
<p>Solution</p>
<p>High school comes before university, so high school should be
explanatory and university should be the response. (High school
grades are used as an admission criterion to university, so we
would hope they would have some predictive value.)</p>
<div class="sourceCode" id="cb128"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb128-1" title="1"><span class="kw">ggplot</span>(gpa, <span class="kw">aes</span>(<span class="dt">x =</span> high_GPA, <span class="dt">y =</span> univ_GPA)) <span class="op">+</span><span class="st"> </span><span class="kw">geom_point</span>() <span class="op">+</span></a>
<a class="sourceLine" id="cb128-2" title="2"><span class="st">  </span><span class="kw">geom_smooth</span>()</a></code></pre></div>
<pre><code>## `geom_smooth()` using method = &#39;loess&#39; and formula &#39;y ~ x&#39;</code></pre>
<p><img src="pasias_files/figure-html/unnamed-chunk-87-1.png" width="672" /></p>
<p><span class="math inline">\(\blacksquare\)</span></p>
<ol start="3" style="list-style-type: lower-alpha">
<li>Describe any relationship on your scatterplot: its direction, its
strength and its shape. Justify your description briefly.</li>
</ol>
<p>Solution</p>
<p>Taking these points one at a time:</p>
<ul>
<li><p>direction: upward (a higher high-school GPA generally goes
with a higher university GPA as well. Or you can say that the
lowest high-school GPAs go with the lowest university GPAs,
and high with high, at least most of the time).</p></li>
<li><p>strength: something like moderately strong, since while
the trend is upward, there is quite a lot of scatter. (This is
a judgement call: something that indicates that you are basing
your description on something reasonable is fine.)</p></li>
<li><p>shape: I’d call this “approximately linear” since there
is no clear curve here. The smooth trend wiggles a bit, but
not enough to make me doubt a straight line.</p></li>
</ul>
<p>Looking ahead, I also notice that when high-school GPA is high,
university GPA is also consistently high, but when high-school
GPA is low, the university GPA is sometimes low and sometimes
high, a lot more variable. (This suggests problems with fan-in
later.) In a practical sense, what this seems to show is that
people who do well at university usually did well in high-school
as well, but sometimes their high-school grades were not
that good. This is especially true for people with university
GPAs around 3.25.</p>
<p><span class="math inline">\(\blacksquare\)</span></p>
<ol start="4" style="list-style-type: lower-alpha">
<li><a name="part:highonly">*</a> Fit a linear regression for predicting university GPA
from high-school GPA and display the results.</li>
</ol>
<p>Solution</p>
<p>Just this, therefore:</p>
<div class="sourceCode" id="cb130"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb130-1" title="1">gpa<span class="fl">.1</span> &lt;-<span class="st"> </span><span class="kw">lm</span>(univ_GPA <span class="op">~</span><span class="st"> </span>high_GPA, <span class="dt">data =</span> gpa)</a>
<a class="sourceLine" id="cb130-2" title="2"><span class="kw">summary</span>(gpa<span class="fl">.1</span>)</a></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = univ_GPA ~ high_GPA, data = gpa)
## 
## Residuals:
##      Min       1Q   Median       3Q      Max 
## -0.69040 -0.11922  0.03274  0.17397  0.91278 
## 
## Coefficients:
##             Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)  1.09682    0.16663   6.583 1.98e-09 ***
## high_GPA     0.67483    0.05342  12.632  &lt; 2e-16 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 0.2814 on 103 degrees of freedom
## Multiple R-squared:  0.6077, Adjusted R-squared:  0.6039 
## F-statistic: 159.6 on 1 and 103 DF,  p-value: &lt; 2.2e-16</code></pre>
<p>Extra: this question goes on too long, so I didn’t ask you to look at the
residuals from this model, but my comments earlier suggested that we
might have had some problems with fanning-in (the variability of
predictions getting less as the high-school GPA increases). In case
you are interested, I’ll look at this here. First, residuals against
fitted values:</p>
<div class="sourceCode" id="cb132"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb132-1" title="1"><span class="kw">ggplot</span>(gpa<span class="fl">.1</span>, <span class="kw">aes</span>(<span class="dt">x =</span> .fitted, <span class="dt">y =</span> .resid)) <span class="op">+</span><span class="st"> </span><span class="kw">geom_point</span>() <span class="op">+</span><span class="st"> </span><span class="kw">geom_smooth</span>()</a></code></pre></div>
<pre><code>## `geom_smooth()` using method = &#39;loess&#39; and formula &#39;y ~ x&#39;</code></pre>
<p><img src="pasias_files/figure-html/unnamed-chunk-89-1.png" width="672" /></p>
<p>Is that evidence of a trend in the residuals? Dunno. I’m inclined to
call this an “inconsequential wiggle” and say it’s OK. Note that the
grey envelope includes zero all the way across.</p>
<p>Normal quantile plot of residuals:</p>
<div class="sourceCode" id="cb134"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb134-1" title="1"><span class="kw">ggplot</span>(gpa<span class="fl">.1</span>, <span class="kw">aes</span>(<span class="dt">sample =</span> .resid)) <span class="op">+</span><span class="st"> </span><span class="kw">stat_qq</span>() <span class="op">+</span><span class="st"> </span><span class="kw">stat_qq_line</span>()</a></code></pre></div>
<p><img src="pasias_files/figure-html/unnamed-chunk-90-1.png" width="672" /></p>
<p>A somewhat long-tailed distribution: compared to a normal
distribution, the residuals are a bit too big in size, both on the
positive and negative end.</p>
<p>The problem I was really worried about was the potential of
fanning-in, which we can assess by looking at the absolute residuals:</p>
<div class="sourceCode" id="cb135"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb135-1" title="1"><span class="kw">ggplot</span>(gpa<span class="fl">.1</span>, <span class="kw">aes</span>(<span class="dt">x =</span> .fitted, <span class="dt">y =</span> <span class="kw">abs</span>(.resid))) <span class="op">+</span><span class="st"> </span><span class="kw">geom_point</span>() <span class="op">+</span><span class="st"> </span><span class="kw">geom_smooth</span>()</a></code></pre></div>
<pre><code>## `geom_smooth()` using method = &#39;loess&#39; and formula &#39;y ~ x&#39;</code></pre>
<p><img src="pasias_files/figure-html/unnamed-chunk-91-1.png" width="672" /></p>
<p>That is definitely a downward trend in the size of the residuals, and
I think I was right to be worried before. The residuals should be of
similar size all the way across.</p>
<p>The usual problem of this kind is fanning-<em>out</em>, where the
residuals get <em>bigger</em> in size as the fitted values increase. The
bigger values equals more spread is the kind of thing that a
transformation like taking logs will handle: the bigger values are all
brought downwards, so they will be both smaller and less variable than
they were. This one, though, goes the other way, so the only kind of
transformation that might help is one at the other end of the scale
(think of the Box-Cox lambda scale), something like maybe reciprocal,
<span class="math inline">\(\lambda=-1\)</span> maybe.</p>
<p>The other thought I had was that there is this kind of break around a
high-school GPA of 3 (go back to the scatterplot of (<a href="#part:hsu-scatter">here</a>)): when the
high-school GPA is higher than 3, the university GPA is very
consistent (and shows a clear upward trend), but when the high-school
GPA is less than 3, the university GPA is very variable and there
doesn’t seem to be any trend at all. So maybe two separate analyses
would be the way to go.</p>
<p>All right, how does Box-Cox work out here, if at all?</p>
<div class="sourceCode" id="cb137"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb137-1" title="1"><span class="kw">library</span>(MASS)</a>
<a class="sourceLine" id="cb137-2" title="2"><span class="kw">boxcox</span>(univ_GPA <span class="op">~</span><span class="st"> </span>high_GPA, <span class="dt">data =</span> gpa)</a></code></pre></div>
<p><img src="pasias_files/figure-html/unnamed-chunk-92-1.png" width="672" /></p>
<p>It doesn’t. All right, that answers <em>that</em> question.</p>
<p><span class="math inline">\(\blacksquare\)</span></p>
<ol start="5" style="list-style-type: lower-alpha">
<li>Two students have been admitted to university. One has
a high school GPA of 3.0 and the other a high school GPA of<br />
3.5. Obtain suitable intervals that summarize the GPAs that each of these
two students might obtain in university.</li>
</ol>
<p>Solution</p>
<p>Since we are talking about individual students, rather than
the mean of <em>all</em> students with these GPAs, prediction
intervals are called for. The first step is to make a data
frame to predict from. This has to contain columns for all the
explanatory variables, just <code>high_GPA</code> in this case:</p>
<div class="sourceCode" id="cb138"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb138-1" title="1">gpa.new &lt;-<span class="st"> </span><span class="kw">tibble</span>(<span class="dt">high_GPA =</span> <span class="kw">c</span>(<span class="dv">3</span>, <span class="fl">3.5</span>))</a>
<a class="sourceLine" id="cb138-2" title="2">gpa.new</a></code></pre></div>
<pre><code>## # A tibble: 2 x 1
##   high_GPA
##      &lt;dbl&gt;
## 1      3  
## 2      3.5</code></pre>
<p>and then feed that into <code>predict</code>:</p>
<div class="sourceCode" id="cb140"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb140-1" title="1">preds &lt;-<span class="st"> </span><span class="kw">predict</span>(gpa<span class="fl">.1</span>, gpa.new, <span class="dt">interval =</span> <span class="st">&quot;p&quot;</span>)</a>
<a class="sourceLine" id="cb140-2" title="2">preds</a></code></pre></div>
<pre><code>##        fit      lwr      upr
## 1 3.121313 2.560424 3.682202
## 2 3.458728 2.896105 4.021351</code></pre>
<p>and display that side by side with the values it was predicted from:</p>
<div class="sourceCode" id="cb142"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb142-1" title="1"><span class="kw">cbind</span>(gpa.new, preds)</a></code></pre></div>
<pre><code>##   high_GPA      fit      lwr      upr
## 1      3.0 3.121313 2.560424 3.682202
## 2      3.5 3.458728 2.896105 4.021351</code></pre>
<p>or this way, if you like it better:</p>
<div class="sourceCode" id="cb144"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb144-1" title="1"><span class="kw">as_tibble</span>(preds) <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">bind_cols</span>(gpa.new) <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">select</span>(high_GPA, <span class="kw">everything</span>())</a></code></pre></div>
<pre><code>## # A tibble: 2 x 4
##   high_GPA   fit   lwr   upr
##      &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt;
## 1      3    3.12  2.56  3.68
## 2      3.5  3.46  2.90  4.02</code></pre>
<p>Thus the predicted university GPA for the student with high school GPA
3.0 is between 2.6 and 3.7, and for the student with high school GPA
3.5 is between 2.9 and 4.0. (I think this is a good number of decimals
to give, but in any case, you should actually <em>say</em> what the
intervals are.)</p>
<p>I observe that these intervals are almost exactly the same
length. This surprises me a bit, since I would have said that 3.0 is
close to the average high-school GPA and 3.5 is noticeably higher. If
that’s the case, the prediction interval for 3.5 should be longer
(since there is less “nearby data”). Was I right about that?</p>
<div class="sourceCode" id="cb146"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb146-1" title="1">gpa <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">summarize</span>(</a>
<a class="sourceLine" id="cb146-2" title="2">  <span class="dt">mean =</span> <span class="kw">mean</span>(high_GPA),</a>
<a class="sourceLine" id="cb146-3" title="3">  <span class="dt">med =</span> <span class="kw">median</span>(high_GPA),</a>
<a class="sourceLine" id="cb146-4" title="4">  <span class="dt">q1 =</span> <span class="kw">quantile</span>(high_GPA, <span class="fl">0.25</span>),</a>
<a class="sourceLine" id="cb146-5" title="5">  <span class="dt">q3 =</span> <span class="kw">quantile</span>(high_GPA, <span class="fl">0.75</span>)</a>
<a class="sourceLine" id="cb146-6" title="6">)</a></code></pre></div>
<pre><code>## # A tibble: 1 x 4
##    mean   med    q1    q3
##   &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt;
## 1  3.08  3.17  2.67  3.48</code></pre>
<p>More or less: the mean is close to 3, and 3.5 is close to the third
quartile. So the thing about the length of the prediction interval is
a bit of a mystery. Maybe it works better for the confidence interval
for the mean:</p>
<div class="sourceCode" id="cb148"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb148-1" title="1">preds &lt;-<span class="st"> </span><span class="kw">predict</span>(gpa<span class="fl">.1</span>, gpa.new, <span class="dt">interval =</span> <span class="st">&quot;c&quot;</span>)</a>
<a class="sourceLine" id="cb148-2" title="2"><span class="kw">cbind</span>(gpa.new, preds)</a></code></pre></div>
<pre><code>##   high_GPA      fit      lwr      upr
## 1      3.0 3.121313 3.066243 3.176383
## 2      3.5 3.458728 3.388147 3.529309</code></pre>
<p>These intervals are a lot shorter, since we are talking about
<em>all</em> students with the high-school GPAs in question, and we
therefore no longer have to worry about variation from student to
student (which is considerable). But my supposition about length is
now correct: the interval for 3.5, which is further from the mean, is
a little longer than the interval for 3.0. Thinking about it, it seems
that the individual-to-individual variation, which is large, is
dominating things for our prediction interval above.</p>
<p><span class="math inline">\(\blacksquare\)</span></p>
<ol start="6" style="list-style-type: lower-alpha">
<li><a name="part:all">*</a> Now obtain a regression predicting university GPA from
high-school GPA as well as the two SAT scores. Display your results.</li>
</ol>
<p>Solution</p>
<p>Create a new regression with all the explanatory variables you want in it:</p>
<div class="sourceCode" id="cb150"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb150-1" title="1">gpa<span class="fl">.2</span> &lt;-<span class="st"> </span><span class="kw">lm</span>(univ_GPA <span class="op">~</span><span class="st"> </span>high_GPA <span class="op">+</span><span class="st"> </span>math_SAT <span class="op">+</span><span class="st"> </span>verb_SAT, <span class="dt">data =</span> gpa)</a>
<a class="sourceLine" id="cb150-2" title="2"><span class="kw">summary</span>(gpa<span class="fl">.2</span>)</a></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = univ_GPA ~ high_GPA + math_SAT + verb_SAT, data = gpa)
## 
## Residuals:
##      Min       1Q   Median       3Q      Max 
## -0.68186 -0.13189  0.01289  0.16186  0.93994 
## 
## Coefficients:
##              Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept) 0.5793478  0.3422627   1.693   0.0936 .  
## high_GPA    0.5454213  0.0850265   6.415  4.6e-09 ***
## math_SAT    0.0004893  0.0010215   0.479   0.6330    
## verb_SAT    0.0010202  0.0008123   1.256   0.2120    
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 0.2784 on 101 degrees of freedom
## Multiple R-squared:  0.6236, Adjusted R-squared:  0.6124 
## F-statistic: 55.77 on 3 and 101 DF,  p-value: &lt; 2.2e-16</code></pre>
<p><span class="math inline">\(\blacksquare\)</span></p>
<ol start="7" style="list-style-type: lower-alpha">
<li>Test whether adding the two SAT scores has improved the
prediction of university GPA. What do you conclude?</li>
</ol>
<p>Solution</p>
<p>Since we added <em>two</em> explanatory variables, the <span class="math inline">\(t\)</span>-tests in
<code>gpa.2</code> don’t apply (they tell us whether we can take out
<em>one</em> <span class="math inline">\(x\)</span>-variable). We might have some suspicions, but that’s
all they are. So we have to do <code>anova</code>:</p>
<div class="sourceCode" id="cb152"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb152-1" title="1"><span class="kw">anova</span>(gpa<span class="fl">.1</span>, gpa<span class="fl">.2</span>)</a></code></pre></div>
<pre><code>## Analysis of Variance Table
## 
## Model 1: univ_GPA ~ high_GPA
## Model 2: univ_GPA ~ high_GPA + math_SAT + verb_SAT
##   Res.Df    RSS Df Sum of Sq      F Pr(&gt;F)
## 1    103 8.1587                           
## 2    101 7.8288  2   0.32988 2.1279 0.1244</code></pre>
<p>If you put the models the other way around, you’ll get a negative
<span class="math inline">\(F\)</span>-statistic and degrees of freedom, which doesn’t make
much sense (although the test will still work).</p>
<p>The null hypothesis here is that the two models fit equally
well. Since the P-value is not small, we do not reject that null
hypothesis, and therefore we conclude that the two models <em>do</em>
fit equally well, and therefore we prefer the smaller one, the one
that predicts university GPA from just high-school GPA. (Or,
equivalently, we conclude that those two SAT scores don’t add anything
to the prediction of how well a student will do at university, once
you know their high-school GPA.)</p>
<p>This might surprise you, given what the SATs are supposed to be
<em>for</em>. But that’s what the data say.</p>
<p><span class="math inline">\(\blacksquare\)</span></p>
<ol start="8" style="list-style-type: lower-alpha">
<li>Carry out a backward elimination starting out from your
model in part (<a href="#part:all">here</a>). Which model do you end up with?
Is it the same model as you fit in (<a href="#part:highonly">here</a>)?</li>
</ol>
<p>Solution</p>
<p>In the model of (<a href="#part:all">here</a>), <code>math_SAT</code> was the
least significant, so that comes out first. (I use
<code>update</code> but I’m not insisting that you do:)</p>
<div class="sourceCode" id="cb154"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb154-1" title="1">gpa<span class="fl">.3</span> &lt;-<span class="st"> </span><span class="kw">update</span>(gpa<span class="fl">.2</span>, . <span class="op">~</span><span class="st"> </span>. <span class="op">-</span><span class="st"> </span>math_SAT)</a>
<a class="sourceLine" id="cb154-2" title="2"><span class="kw">summary</span>(gpa<span class="fl">.3</span>)</a></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = univ_GPA ~ high_GPA + verb_SAT, data = gpa)
## 
## Residuals:
##      Min       1Q   Median       3Q      Max 
## -0.68430 -0.11268  0.01802  0.14901  0.95239 
## 
## Coefficients:
##              Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept) 0.6838723  0.2626724   2.604   0.0106 *  
## high_GPA    0.5628331  0.0765729   7.350 5.07e-11 ***
## verb_SAT    0.0012654  0.0006283   2.014   0.0466 *  
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 0.2774 on 102 degrees of freedom
## Multiple R-squared:  0.6227, Adjusted R-squared:  0.6153 
## F-statistic: 84.18 on 2 and 102 DF,  p-value: &lt; 2.2e-16</code></pre>
<p>Here is where we have to stop, since both high-school GPA and
verbal SAT score are significant, and so taking either of them
out would be a bad idea.
This is a <em>different</em> model than the one of
(<a href="#part:highonly">here</a>). This is the case, even though the model
with high-school GPA only was not significantly worse than the
model containing everything. (This goes to show that
model-building doesn’t always have nice clear answers.)
In the model I called <code>gpa.2</code>, neither of the SAT
scores were anywhere near significant (considered singly), but
as soon as we took out one of the SAT scores (my model
<code>gpa.3</code>), the other one became significant. This goes
to show that you shouldn’t take out more than one explanatory
variable based on the results of the <span class="math inline">\(t\)</span>-tests, and even if
you test to see whether you should have taken out both of the SAT,
you won’t necessarily get consistent
results. Admittedly, it’s a close decision whether to
keep or remove <code>verb_SAT</code>, since its P-value is
close to 0.05.
The other way of tackling this one is via <code>step</code>, which
does the backward elimination for you (not that it was much
work here):</p>
<div class="sourceCode" id="cb156"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb156-1" title="1"><span class="kw">step</span>(gpa<span class="fl">.2</span>, <span class="dt">direction =</span> <span class="st">&quot;backward&quot;</span>, <span class="dt">test =</span> <span class="st">&quot;F&quot;</span>)</a></code></pre></div>
<pre><code>## Start:  AIC=-264.6
## univ_GPA ~ high_GPA + math_SAT + verb_SAT
## 
##            Df Sum of Sq     RSS     AIC F value    Pr(&gt;F)    
## - math_SAT  1    0.0178  7.8466 -266.36  0.2294     0.633    
## - verb_SAT  1    0.1223  7.9511 -264.97  1.5777     0.212    
## &lt;none&gt;                   7.8288 -264.60                      
## - high_GPA  1    3.1896 11.0184 -230.71 41.1486 4.601e-09 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Step:  AIC=-266.36
## univ_GPA ~ high_GPA + verb_SAT
## 
##            Df Sum of Sq     RSS     AIC F value    Pr(&gt;F)    
## &lt;none&gt;                   7.8466 -266.36                      
## - verb_SAT  1    0.3121  8.1587 -264.26  4.0571   0.04662 *  
## - high_GPA  1    4.1562 12.0028 -223.73 54.0268 5.067e-11 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<pre><code>## 
## Call:
## lm(formula = univ_GPA ~ high_GPA + verb_SAT, data = gpa)
## 
## Coefficients:
## (Intercept)     high_GPA     verb_SAT  
##    0.683872     0.562833     0.001265</code></pre>
<p>This gives the same result as we did from our backward
elimination. The tables with AIC in them are each step of
the elimination, and the variable at the top is the one that comes out
next. (When <code>&lt;none&gt;</code> gets to the top, that’s when you stop.)
What happened is that the two SAT scores started off highest, but once
we removed <code>math_SAT</code>, <code>verb_SAT</code> jumped below
<code>&lt;none&gt;</code> and so the verbal SAT score had to stay.</p>
<p>Both the P-value and the AIC say that the decision about keeping or
removing <code>verb_SAT</code> is very close.</p>
<p><span class="math inline">\(\blacksquare\)</span></p>
<ol style="list-style-type: lower-roman">
<li>These students were studying computer science at
university. Do you find your backward-elimination result
sensible or surprising, given this? Explain briefly.</li>
</ol>
<p>Solution</p>
<p>I would expect computer science students to be strong students
generally, good at math and possibly not so good with
words. So it is not surprising that high-school GPA figures
into the prediction, but I would expect math SAT score to have
an impact also, and it does not. It is also rather surprising
that verbal SAT score predicts success at university for these
computer science students; you wouldn’t think that having
better skills with words would be helpful. So I’m surprised.
Here, I’m looking for some kind of discussion about what’s in
the final backward-elimination model, and what you would
expect to be true of computer science students.
Let’s look at the final model from the backward elimination again:</p>
<div class="sourceCode" id="cb159"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb159-1" title="1"><span class="kw">summary</span>(gpa<span class="fl">.3</span>)</a></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = univ_GPA ~ high_GPA + verb_SAT, data = gpa)
## 
## Residuals:
##      Min       1Q   Median       3Q      Max 
## -0.68430 -0.11268  0.01802  0.14901  0.95239 
## 
## Coefficients:
##              Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept) 0.6838723  0.2626724   2.604   0.0106 *  
## high_GPA    0.5628331  0.0765729   7.350 5.07e-11 ***
## verb_SAT    0.0012654  0.0006283   2.014   0.0466 *  
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 0.2774 on 102 degrees of freedom
## Multiple R-squared:  0.6227, Adjusted R-squared:  0.6153 
## F-statistic: 84.18 on 2 and 102 DF,  p-value: &lt; 2.2e-16</code></pre>
<p>The two slope estimates are both positive, meaning that, all else
equal, a higher value for each explanatory variable goes with a higher
university GPA. This indicates that a higher verbal SAT score goes
with a higher university GPA: this is across all the university
courses that a student takes, which you would expect to be math and
computer science courses for a Comp Sci student, but might include
a few electives or writing courses. Maybe what is happening is that
the math SAT score is telling the same story as the high-school GPA
for these students, and the verbal SAT score is saying something
different. (For example, prospective computer science students are
mostly likely to have high math SAT scores, so there’s not much
information there.)</p>
<p>I think I need to look at the correlations:</p>
<div class="sourceCode" id="cb161"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb161-1" title="1"><span class="kw">cor</span>(gpa)</a></code></pre></div>
<pre><code>##           high_GPA  math_SAT  verb_SAT  comp_GPA  univ_GPA
## high_GPA 1.0000000 0.7681423 0.7261478 0.7914721 0.7795631
## math_SAT 0.7681423 1.0000000 0.8352272 0.6877209 0.6627837
## verb_SAT 0.7261478 0.8352272 1.0000000 0.6387512 0.6503012
## comp_GPA 0.7914721 0.6877209 0.6387512 1.0000000 0.9390459
## univ_GPA 0.7795631 0.6627837 0.6503012 0.9390459 1.0000000</code></pre>
<p>We’ll ignore <code>comp_GPA</code> (i) because we haven’t been thinking
about it and (ii) because it’s highly correlated with the university
GPA anyway. (There isn’t a sense that one of the two university GPAs
is explanatory and the other is a response, since students are taking
the courses that contribute to them at the same time.)</p>
<p>The highest correlation with university GPA of what remains is
high-school GPA, so it’s not at all surprising that this features in
all our regressions. The correlations between university GPA and the
two SAT scores are about equal, so there appears to be no reason to
favour one of the SAT scores over the other. But, the two SAT scores
are highly correlated with <em>each other</em> (0.835), which suggests
that if you have one, you don’t need the other, because they are
telling more or less the same story.</p>
<p>That makes me wonder how a regression with the SAT math score and
<em>not</em> the SAT verbal score would look:</p>
<div class="sourceCode" id="cb163"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb163-1" title="1">gpa<span class="fl">.4</span> &lt;-<span class="st"> </span><span class="kw">lm</span>(univ_GPA <span class="op">~</span><span class="st"> </span>high_GPA <span class="op">+</span><span class="st"> </span>math_SAT, <span class="dt">data =</span> gpa)</a>
<a class="sourceLine" id="cb163-2" title="2"><span class="kw">summary</span>(gpa<span class="fl">.4</span>)</a></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = univ_GPA ~ high_GPA + math_SAT, data = gpa)
## 
## Residuals:
##      Min       1Q   Median       3Q      Max 
## -0.68079 -0.12264  0.00741  0.16579  0.90010 
## 
## Coefficients:
##              Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept) 0.6072916  0.3425047   1.773   0.0792 .  
## high_GPA    0.5710745  0.0827705   6.899  4.5e-10 ***
## math_SAT    0.0012980  0.0007954   1.632   0.1058    
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 0.2792 on 102 degrees of freedom
## Multiple R-squared:  0.6177, Adjusted R-squared:  0.6102 
## F-statistic:  82.4 on 2 and 102 DF,  p-value: &lt; 2.2e-16</code></pre>
<p>Math SAT does not quite significantly add anything to the prediction,
which confirms that we do better to use the verbal SAT score
(surprising though it seems). Though, the two regressions with the
single SAT scores, <code>gpa.3</code> and <code>gpa.4</code>, have almost the
same R-squared values. It’s not clear-cut at all. In the end, you have
to make a call and stand by it.</p>
<p><span class="math inline">\(\blacksquare\)</span></p>
</div>
<div id="fish-and-mercury-1" class="section level2">
<h2><span class="header-section-number">17.10</span> Fish and mercury</h2>
<p>Eating fish is generally healthy, but sometimes the fish is contaminated with mercury. What might affect the amount of mercury in a fish? Large-mouth bass were studied in Florida lakes to examine factors that might affect the amount of mercury contamination. 38 lakes were used for the study. Water samples were taken from each lake and analyzed. Also, samples of fish were caught in each lake and the mercury concentration in their muscle tissue was measured. The resulting data are in , separated by single spaces. The variables measured were as follows:</p>
<ul>
<li>standardized mercury level (parts per million in 3-year-old fish)</li>
<li>alkalinity of water (milligrams per litre)</li>
<li>calcium level of water (milligrams per litre)</li>
<li>pH of water (standard scale; see eg. <a href="https://www.usgs.gov/special-topic/water-science-school/science/ph-and-water?qt-science_center_objects=0#qt-science_center_objects">this</a>)</li>
</ul>
<ol style="list-style-type: lower-alpha">
<li>Read in and display (some of) the data.</li>
</ol>
<p>Solution</p>
<p>The data values were separated by single spaces, so this one is <code>read_delim</code>:</p>
<div class="sourceCode" id="cb165"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb165-1" title="1">my_url &lt;-<span class="st"> &quot;http://ritsokiguess.site/datafiles/mercury.txt&quot;</span></a>
<a class="sourceLine" id="cb165-2" title="2">mercury &lt;-<span class="st"> </span><span class="kw">read_delim</span>(my_url, <span class="st">&quot; &quot;</span>)</a></code></pre></div>
<pre><code>## 
## ── Column specification ──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
## cols(
##   mercury = col_double(),
##   alkalinity = col_double(),
##   calcium = col_double(),
##   ph = col_double()
## )</code></pre>
<div class="sourceCode" id="cb167"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb167-1" title="1">mercury</a></code></pre></div>
<pre><code>## # A tibble: 38 x 4
##    mercury alkalinity calcium    ph
##      &lt;dbl&gt;      &lt;dbl&gt;   &lt;dbl&gt; &lt;dbl&gt;
##  1    1330        2.5     2.9   4.6
##  2     250       19.6     4.5   7.3
##  3     450        5.2     2.8   5.4
##  4     160       71.4    55.2   8.1
##  5     720       26.4     9.2   5.8
##  6     810        4.8     4.6   6.4
##  7     710        6.6     2.7   5.4
##  8     510       16.5    13.8   7.2
##  9    1000        7.1     5.2   5.8
## 10     150       83.7    66.5   8.2
## # … with 28 more rows</code></pre>
<p>Extra: I found these data in a textbook, and I couldn’t find them online anywhere, so I typed them in myself. This is how I did it.</p>
<p>First, I entered the values as a piece of text:</p>
<div class="sourceCode" id="cb169"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb169-1" title="1">mercury_txt &lt;-<span class="st"> &quot;</span></a>
<a class="sourceLine" id="cb169-2" title="2"><span class="st">mercury alkalinity calcium ph</span></a>
<a class="sourceLine" id="cb169-3" title="3"><span class="st">1330 2.5 2.9 4.6</span></a>
<a class="sourceLine" id="cb169-4" title="4"><span class="st">250 19.6 4.5 7.3</span></a>
<a class="sourceLine" id="cb169-5" title="5"><span class="st">450 5.2 2.8 5.4</span></a>
<a class="sourceLine" id="cb169-6" title="6"><span class="st">160 71.4 55.2 8.1</span></a>
<a class="sourceLine" id="cb169-7" title="7"><span class="st">720 26.4 9.2 5.8</span></a>
<a class="sourceLine" id="cb169-8" title="8"><span class="st">810 4.8 4.6 6.4</span></a>
<a class="sourceLine" id="cb169-9" title="9"><span class="st">710 6.6 2.7 5.4</span></a>
<a class="sourceLine" id="cb169-10" title="10"><span class="st">510 16.5 13.8 7.2</span></a>
<a class="sourceLine" id="cb169-11" title="11"><span class="st">1000 7.1 5.2 5.8</span></a>
<a class="sourceLine" id="cb169-12" title="12"><span class="st">150 83.7 66.5 8.2</span></a>
<a class="sourceLine" id="cb169-13" title="13"><span class="st">190 108.5 35.6 8.7</span></a>
<a class="sourceLine" id="cb169-14" title="14"><span class="st">1020 6.4 4.0 5.8</span></a>
<a class="sourceLine" id="cb169-15" title="15"><span class="st">450 7.5 2.0 4.4</span></a>
<a class="sourceLine" id="cb169-16" title="16"><span class="st">590 17.3 10.7 6.7</span></a>
<a class="sourceLine" id="cb169-17" title="17"><span class="st">810 7.0 6.3 6.9</span></a>
<a class="sourceLine" id="cb169-18" title="18"><span class="st">420 10.5 6.3 5.5</span></a>
<a class="sourceLine" id="cb169-19" title="19"><span class="st">O530 30.0 13.9 6.9</span></a>
<a class="sourceLine" id="cb169-20" title="20"><span class="st">310 55.4 15.9 7.3</span></a>
<a class="sourceLine" id="cb169-21" title="21"><span class="st">470 6.3 3.3 5.8</span></a>
<a class="sourceLine" id="cb169-22" title="22"><span class="st">250 67.0 58.6 7.8</span></a>
<a class="sourceLine" id="cb169-23" title="23"><span class="st">410 28.8 10.2 7.4</span></a>
<a class="sourceLine" id="cb169-24" title="24"><span class="st">160 119.1 38.4 7.9</span></a>
<a class="sourceLine" id="cb169-25" title="25"><span class="st">160 25.4 8.8 7.1</span></a>
<a class="sourceLine" id="cb169-26" title="26"><span class="st">230 106.5 90.7 6.8</span></a>
<a class="sourceLine" id="cb169-27" title="27"><span class="st">560 8.5 2.5 7.0</span></a>
<a class="sourceLine" id="cb169-28" title="28"><span class="st">890 87.6 85.5 7.5</span></a>
<a class="sourceLine" id="cb169-29" title="29"><span class="st">180 114.0 72.6 7.0</span></a>
<a class="sourceLine" id="cb169-30" title="30"><span class="st">190 97.5 45.5 6.8</span></a>
<a class="sourceLine" id="cb169-31" title="31"><span class="st">440 11.8 24.2 5.9</span></a>
<a class="sourceLine" id="cb169-32" title="32"><span class="st">160 66.5 26.0 8.3</span></a>
<a class="sourceLine" id="cb169-33" title="33"><span class="st">670 16.0 41.2 6.7</span></a>
<a class="sourceLine" id="cb169-34" title="34"><span class="st">550 5.0 23.6 6.2</span></a>
<a class="sourceLine" id="cb169-35" title="35"><span class="st">580 25.6 12.6 6.2</span></a>
<a class="sourceLine" id="cb169-36" title="36"><span class="st">980 1.2 2.1 4.3</span></a>
<a class="sourceLine" id="cb169-37" title="37"><span class="st">310 34.0 13.1 7.0</span></a>
<a class="sourceLine" id="cb169-38" title="38"><span class="st">430 15.5 5.2 6.9</span></a>
<a class="sourceLine" id="cb169-39" title="39"><span class="st">280 17.3 3.0 5.2</span></a>
<a class="sourceLine" id="cb169-40" title="40"><span class="st">250 71.8 20.5 7.9</span></a>
<a class="sourceLine" id="cb169-41" title="41"><span class="st">&quot;</span></a></code></pre></div>
<p>Then, I wanted to get these into a file laid out just like that, which is what <code>writeLines</code> does:</p>
<div class="sourceCode" id="cb170"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb170-1" title="1"><span class="kw">writeLines</span>(mercury_txt, <span class="st">&quot;mercury.txt&quot;</span>)</a></code></pre></div>
<p>and then I uploaded the file to the course website.</p>
<p><span class="math inline">\(\blacksquare\)</span></p>
<ol start="2" style="list-style-type: lower-alpha">
<li>Plot the mercury levels against each of the explanatory variables.</li>
</ol>
<p>Solution</p>
<p>The best way to do this is in one shot, using facets. This means organizing the dataframe so that there is one column of <span class="math inline">\(y\)</span>-values, and also one column of <span class="math inline">\(x\)</span>-values, with an additional column labelling which <span class="math inline">\(x\)</span> it is. This, as you’ll recall, is exactly what <code>pivot_longer</code> does. To show you:</p>
<div class="sourceCode" id="cb171"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb171-1" title="1">mercury <span class="op">%&gt;%</span><span class="st"> </span></a>
<a class="sourceLine" id="cb171-2" title="2"><span class="kw">pivot_longer</span>(<span class="op">-</span>mercury, <span class="dt">names_to =</span> <span class="st">&quot;xname&quot;</span>, <span class="dt">values_to =</span> <span class="st">&quot;xval&quot;</span>)</a></code></pre></div>
<pre><code>## # A tibble: 114 x 3
##    mercury xname       xval
##      &lt;dbl&gt; &lt;chr&gt;      &lt;dbl&gt;
##  1    1330 alkalinity   2.5
##  2    1330 calcium      2.9
##  3    1330 ph           4.6
##  4     250 alkalinity  19.6
##  5     250 calcium      4.5
##  6     250 ph           7.3
##  7     450 alkalinity   5.2
##  8     450 calcium      2.8
##  9     450 ph           5.4
## 10     160 alkalinity  71.4
## # … with 104 more rows</code></pre>
<p>and now we plot <code>mercury</code> against <code>xval</code> in facets according to <code>xname</code>. The other thing to remember is that the explanatory variables are on different scales, so we should use <code>scales="free"</code> to allow each facet to have its own scales:</p>
<div class="sourceCode" id="cb173"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb173-1" title="1">mercury <span class="op">%&gt;%</span><span class="st"> </span></a>
<a class="sourceLine" id="cb173-2" title="2"><span class="kw">pivot_longer</span>(<span class="op">-</span>mercury, <span class="dt">names_to =</span> <span class="st">&quot;xname&quot;</span>, <span class="dt">values_to =</span> <span class="st">&quot;xval&quot;</span>) <span class="op">%&gt;%</span><span class="st"> </span></a>
<a class="sourceLine" id="cb173-3" title="3"><span class="kw">ggplot</span>(<span class="kw">aes</span>(<span class="dt">x =</span> xval, <span class="dt">y =</span> mercury)) <span class="op">+</span><span class="st"> </span><span class="kw">geom_point</span>() <span class="op">+</span><span class="st"> </span><span class="kw">geom_smooth</span>() <span class="op">+</span><span class="st"> </span></a>
<a class="sourceLine" id="cb173-4" title="4"><span class="kw">facet_wrap</span>(<span class="op">~</span>xname, <span class="dt">scales =</span> <span class="st">&quot;free&quot;</span>, <span class="dt">ncol =</span> <span class="dv">2</span>)</a></code></pre></div>
<pre><code>## `geom_smooth()` using method = &#39;loess&#39; and formula &#39;y ~ x&#39;</code></pre>
<p><img src="pasias_files/figure-html/unnamed-chunk-110-1.png" width="672" /></p>
<p>I did one more thing, which is to note that I am going to be assessing these relationships in a moment, so I would rather have squarer plots than the tall skinny ones that come out by default (that is to say these):</p>
<div class="sourceCode" id="cb175"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb175-1" title="1">mercury <span class="op">%&gt;%</span><span class="st"> </span></a>
<a class="sourceLine" id="cb175-2" title="2"><span class="kw">pivot_longer</span>(<span class="op">-</span>mercury, <span class="dt">names_to =</span> <span class="st">&quot;xname&quot;</span>, <span class="dt">values_to =</span> <span class="st">&quot;xval&quot;</span>) <span class="op">%&gt;%</span><span class="st"> </span></a>
<a class="sourceLine" id="cb175-3" title="3"><span class="kw">ggplot</span>(<span class="kw">aes</span>(<span class="dt">x =</span> xval, <span class="dt">y =</span> mercury)) <span class="op">+</span><span class="st"> </span><span class="kw">geom_point</span>() <span class="op">+</span><span class="st"> </span><span class="kw">geom_smooth</span>() <span class="op">+</span><span class="st"> </span></a>
<a class="sourceLine" id="cb175-4" title="4"><span class="kw">facet_wrap</span>(<span class="op">~</span>xname, <span class="dt">scales =</span> <span class="st">&quot;free&quot;</span>)</a></code></pre></div>
<pre><code>## `geom_smooth()` using method = &#39;loess&#39; and formula &#39;y ~ x&#39;</code></pre>
<p><img src="pasias_files/figure-html/unnamed-chunk-111-1.png" width="672" /></p>
<p>To make this happen, I added <code>ncol=2</code>, which says to arrange the facets in <em>two</em> columns (that is, as three cells of a <span class="math inline">\(2\times 2\)</span> grid), and that makes them come out more landscape than portrait. <code>nrow=2</code> would have had the same effect.</p>
<p>If you are stuck, get three separate graphs, but note that you are making more work for yourself (that you will have to do again later).</p>
<p><span class="math inline">\(\blacksquare\)</span></p>
<ol start="3" style="list-style-type: lower-alpha">
<li>Describe any trends (or lack thereof) that you see on your graphs.</li>
</ol>
<p>Solution</p>
<p>Think about “form, direction, strength” to guide you in interpreting what you see: is it a line or a curve, does it go up or down, and are the points mostly close to the trend or not? I think it makes most sense to talk about those things for the three trends one after the other:</p>
<ul>
<li><code>alkalinity</code>: this is a curved trend, but downward (the rate of decrease is fast at the beginning and then levels off). There is one clear outlier, but otherwise most of the points are close to the trend.</li>
<li><code>calcium</code>: this is a down-and-up curved trend, though I think most of the evidence for the “up” part is the outlier on the middle right of the graph; without that, it would probably be a levelling-off decreasing trend as for <code>alkalinity</code>. There seem to be more outliers on this plot, and, on top of that, the points are not that close to the trend.</li>
<li><code>ph</code>: this is a downward trend, more or less linear, but of only moderate strength. The points can be some way from the trend, but (in contrast to the other plots) there don’t seem to be any points a <em>long</em> way away.</li>
</ul>
<p>If you are going to talk about outliers, you need to be specific about where they are: describe where they are on the plot, or give approximate coordinates (you only need to be accurate enough to make it clear which point you are talking about). For example, I described one of the outliers on the <code>calcium</code> plot as “middle right”, or you could describe the same point as having <code>calcium</code> above 80 and <code>mercury</code> near 1000, which narrows it down enough. There is a grey area between outliers and not being close to the trend overall; if it is a lot of points, I’d call it a weaker trend (as for <code>ph</code>), but if it’s a few points that are a long way off, as for <code>calcium</code>, I’d call that outliers.</p>
<p>Extra: most of the outliers are <em>above</em> the trends, which suggests that something to bring the high values down a bit would be helpful: that is, a transformation like log or square root. That’s coming up later.</p>
<p><span class="math inline">\(\blacksquare\)</span></p>
<ol start="4" style="list-style-type: lower-alpha">
<li>Concerned by some of what you see on your plots, you consult with a fisheries scientist, who says that using the logs of <code>alkalinity</code> and <code>calcium</code> are often used in modelling this kind of data. Add columns containing the logs of these two variables to your dataframe, and run a regression predicting <code>mercury</code> from <code>ph</code> and the two new variables. Display the output from your regression.</li>
</ol>
<p>Solution</p>
<p>I would create the two new variables and save them back into the original dataframe, myself:</p>
<div class="sourceCode" id="cb177"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb177-1" title="1">mercury <span class="op">%&gt;%</span><span class="st"> </span></a>
<a class="sourceLine" id="cb177-2" title="2"><span class="kw">mutate</span>(<span class="dt">log_alkalinity =</span> <span class="kw">log</span>(alkalinity), <span class="dt">log_calcium =</span> <span class="kw">log</span>(calcium)) -&gt;<span class="st"> </span>mercury</a></code></pre></div>
<p>though you could equally well create a new dataframe to hold them, as long as you remember to use the new dataframe from here on.</p>
<p>The regression has no great surprises:</p>
<div class="sourceCode" id="cb178"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb178-1" title="1">mercury<span class="fl">.1</span> &lt;-<span class="st"> </span><span class="kw">lm</span>(mercury <span class="op">~</span><span class="st"> </span>log_alkalinity <span class="op">+</span><span class="st"> </span>log_calcium <span class="op">+</span><span class="st"> </span>ph, <span class="dt">data =</span> mercury)</a>
<a class="sourceLine" id="cb178-2" title="2"><span class="kw">summary</span>(mercury<span class="fl">.1</span>)</a></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = mercury ~ log_alkalinity + log_calcium + ph, data = mercury)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -326.02 -129.92  -27.67   71.17  581.76 
## 
## Coefficients:
##                Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)     1181.20     244.21   4.837 2.79e-05 ***
## log_alkalinity  -221.18      58.87  -3.757 0.000646 ***
## log_calcium       87.90      51.43   1.709 0.096520 .  
## ph               -36.63      51.09  -0.717 0.478362    
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 204.4 on 34 degrees of freedom
## Multiple R-squared:  0.5578, Adjusted R-squared:  0.5188 
## F-statistic:  14.3 on 3 and 34 DF,  p-value: 3.424e-06</code></pre>
<p><span class="math inline">\(\blacksquare\)</span></p>
<ol start="5" style="list-style-type: lower-alpha">
<li>What might you learn from running Box-Cox here? Explain briefly, then run it (on the same variables as your regression above) and describe what the results tell you.</li>
</ol>
<p>Solution</p>
<p>Box-Cox is to find out whether you need to transform the response variable, here <code>mercury</code>. The hint is that we have already transformed two of the explanatory variables, the ones that had some unusually large values, and so those are presumably now all right now.</p>
<p><code>boxcox</code> comes from the <code>MASS</code> package, so install and load that first.</p>
<div class="sourceCode" id="cb180"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb180-1" title="1"><span class="kw">boxcox</span>(mercury <span class="op">~</span><span class="st"> </span>log_alkalinity <span class="op">+</span><span class="st"> </span>log_calcium <span class="op">+</span><span class="st"> </span>ph, <span class="dt">data =</span> mercury)</a></code></pre></div>
<p><img src="pasias_files/figure-html/unnamed-chunk-114-1.png" width="672" /></p>
<p>The confidence interval for <span class="math inline">\(\lambda\)</span> goes from about <span class="math inline">\(-0.4\)</span> to <span class="math inline">\(0.5\)</span>. The only round-number powers in there are 0 (log) and 0.5 (square root, right on the end). The <span class="math inline">\(\lambda\)</span> for the log transformation is right in the middle of the interval, so that’s what I would choose. That means that we should use log of mercury instead of mercury itself in a regression.</p>
<p>Extra: I looked at the residual plots of the regression <code>mercury.1</code>, in the hope that they would point you towards some kind of transformation of <code>mercury</code>, but they really didn’t – the biggest feature was an upper-end outlier, more extreme than the one you see below, that appeared on all of them. So I didn’t have you produce those graphs.</p>
<p><span class="math inline">\(\blacksquare\)</span></p>
<ol start="6" style="list-style-type: lower-alpha">
<li>Using the results of the Box-Cox procedure and your previous work in the question, what seems to be the most appropriate regression now? Fit it, and display the results.</li>
</ol>
<p>Solution</p>
<p>This says to predict log-mercury (Box-Cox) from log-alkalinity, log-calcium (the fisheries scientist) and pH:</p>
<div class="sourceCode" id="cb181"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb181-1" title="1">mercury<span class="fl">.2</span> &lt;-<span class="st"> </span><span class="kw">lm</span>(<span class="kw">log</span>(mercury) <span class="op">~</span><span class="st"> </span>log_alkalinity <span class="op">+</span><span class="st"> </span>log_calcium <span class="op">+</span><span class="st"> </span>ph, <span class="dt">data =</span> mercury)</a>
<a class="sourceLine" id="cb181-2" title="2"><span class="kw">summary</span>(mercury<span class="fl">.2</span>)</a></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = log(mercury) ~ log_alkalinity + log_calcium + ph, 
##     data = mercury)
## 
## Residuals:
##      Min       1Q   Median       3Q      Max 
## -0.75244 -0.30191 -0.00783  0.23852  1.22932 
## 
## Coefficients:
##                Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)     7.55983    0.48981  15.434  &lt; 2e-16 ***
## log_alkalinity -0.45880    0.11807  -3.886 0.000449 ***
## log_calcium     0.14702    0.10315   1.425 0.163185    
## ph             -0.07998    0.10248  -0.780 0.440527    
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 0.4099 on 34 degrees of freedom
## Multiple R-squared:  0.6069, Adjusted R-squared:  0.5723 
## F-statistic:  17.5 on 3 and 34 DF,  p-value: 4.808e-07</code></pre>
<p>There’s no need to define a new column containing log-mercury in the dataframe, since you can define it in the <code>lm</code>. (Note for me: do I need to define new columns anywhere?)</p>
<p><span class="math inline">\(\blacksquare\)</span></p>
<ol start="7" style="list-style-type: lower-alpha">
<li>Obtain all the standard residual plots (the ones we have seen in this course) for this model. Describe any problems you see.</li>
</ol>
<p>Solution</p>
<p>residuals against fitted</p>
<div class="sourceCode" id="cb183"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb183-1" title="1"><span class="kw">ggplot</span>(mercury<span class="fl">.2</span>, <span class="kw">aes</span>(<span class="dt">x=</span>.fitted, <span class="dt">y=</span>.resid)) <span class="op">+</span><span class="st"> </span><span class="kw">geom_point</span>()</a></code></pre></div>
<p><img src="pasias_files/figure-html/unnamed-chunk-116-1.png" width="672" /></p>
<p>normal quantile plot of residuals</p>
<div class="sourceCode" id="cb184"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb184-1" title="1"><span class="kw">ggplot</span>(mercury<span class="fl">.2</span>, <span class="kw">aes</span>(<span class="dt">sample =</span> .resid)) <span class="op">+</span><span class="st"> </span><span class="kw">stat_qq</span>() <span class="op">+</span><span class="st"> </span><span class="kw">stat_qq_line</span>()</a></code></pre></div>
<p><img src="pasias_files/figure-html/unnamed-chunk-117-1.png" width="672" /></p>
<p>against the explanatory variables. This uses the ideas of <code>augment</code> (from <code>broom</code>) and pivoting longer:</p>
<div class="sourceCode" id="cb185"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb185-1" title="1">mercury<span class="fl">.2</span> <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">augment</span>(mercury) <span class="op">%&gt;%</span><span class="st"> </span></a>
<a class="sourceLine" id="cb185-2" title="2"><span class="kw">pivot_longer</span>(ph<span class="op">:</span>log_calcium, <span class="dt">names_to =</span> <span class="st">&quot;xname&quot;</span>, <span class="dt">values_to =</span> <span class="st">&quot;xval&quot;</span>) <span class="op">%&gt;%</span><span class="st"> </span></a>
<a class="sourceLine" id="cb185-3" title="3"><span class="kw">ggplot</span>(<span class="kw">aes</span>(<span class="dt">x =</span> xval, <span class="dt">y =</span> .resid)) <span class="op">+</span><span class="st"> </span><span class="kw">geom_point</span>() <span class="op">+</span></a>
<a class="sourceLine" id="cb185-4" title="4"><span class="kw">facet_wrap</span>(<span class="op">~</span>xname, <span class="dt">scales =</span> <span class="st">&quot;free&quot;</span>, <span class="dt">ncol =</span> <span class="dv">2</span>)</a></code></pre></div>
<p><img src="pasias_files/figure-html/unnamed-chunk-118-1.png" width="672" />
I think the only troublesome feature on there is the large positive residual that appears at the top of all the plots. Other than that, I see nothing troubling.</p>
<p>You might, if you look a bit longer (but remember, apophenia!) see a tiny up and down on the plot with log-alkalinity, and maybe a small downward trend on the plots with the other two explanatory variables, but I would need a lot of convincing to say that these are more than chance. You are looking for <em>obvious trouble</em>, and I really don’t think there’s any sign of that here.</p>
<p>Extra: you sometimes see a downward trend on residual plots that have an outlier on them. This is because if you have an outlier, it can change the slope disproportionately from what it ought to be, and then most of the observations at one end will be underestimated and most of the observations at the other end will be overestimated.</p>
<p>Extra 2: which one was that outlier anyway?</p>
<div class="sourceCode" id="cb186"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb186-1" title="1">mercury<span class="fl">.2</span> <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">augment</span>(mercury) <span class="op">%&gt;%</span><span class="st"> </span></a>
<a class="sourceLine" id="cb186-2" title="2"><span class="kw">filter</span>(.resid <span class="op">&gt;</span><span class="st"> </span><span class="dv">1</span>)</a></code></pre></div>
<pre><code>## # A tibble: 1 x 12
##   mercury alkalinity calcium    ph log_alkalinity log_calcium .fitted .resid  .hat .sigma .cooksd .std.resid
##     &lt;dbl&gt;      &lt;dbl&gt;   &lt;dbl&gt; &lt;dbl&gt;          &lt;dbl&gt;       &lt;dbl&gt;   &lt;dbl&gt;  &lt;dbl&gt; &lt;dbl&gt;  &lt;dbl&gt;   &lt;dbl&gt;      &lt;dbl&gt;
## 1     890       87.6    85.5   7.5           4.47        4.45    5.56   1.23 0.111  0.349   0.315       3.18</code></pre>
<p>How do these compare to the other data values?</p>
<div class="sourceCode" id="cb188"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb188-1" title="1"><span class="kw">summary</span>(mercury)</a></code></pre></div>
<pre><code>##     mercury         alkalinity        calcium             ph        log_alkalinity    log_calcium    
##  Min.   : 150.0   Min.   :  1.20   Min.   : 2.000   Min.   :4.300   Min.   :0.1823   Min.   :0.6931  
##  1st Qu.: 250.0   1st Qu.:  7.20   1st Qu.: 4.525   1st Qu.:5.800   1st Qu.:1.9738   1st Qu.:1.5096  
##  Median : 445.0   Median : 18.45   Median :11.650   Median :6.850   Median :2.9131   Median :2.4520  
##  Mean   : 488.4   Mean   : 37.15   Mean   :22.361   Mean   :6.634   Mean   :3.0193   Mean   :2.4801  
##  3rd Qu.: 650.0   3rd Qu.: 66.88   3rd Qu.:33.200   3rd Qu.:7.300   3rd Qu.:4.2028   3rd Qu.:3.4938  
##  Max.   :1330.0   Max.   :119.10   Max.   :90.700   Max.   :8.700   Max.   :4.7800   Max.   :4.5076</code></pre>
<p>The variable values are all high (even the pH, a modest-looking 7.5, is above Q3).</p>
<p>Remember that the fitted value is of <em>log</em>-mercury, so we have to anti-log it to understand it (anti-log is “exp” since these are “natural” or base-<span class="math inline">\(e\)</span> logs):</p>
<div class="sourceCode" id="cb190"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb190-1" title="1"><span class="kw">exp</span>(<span class="fl">5.561902</span>)</a></code></pre></div>
<pre><code>## [1] 260.3175</code></pre>
<p>This was a <em>much</em> higher mercury value than expected, given the other variables.</p>
<p><span class="math inline">\(\blacksquare\)</span></p>

</div>
</div>
<div class="footnotes">
<hr />
<ol start="2">
<li id="fn2"><p>If there are more than one, they should be separated by plus signs as in <code>lm</code>. Each facet then has as many labels as variables. I haven’t actually done this myself, but from looking at examples, I think this is the way it works.<a href="multiple-regression.html#fnref2" class="footnote-back">↩</a></p></li>
<li id="fn3"><p>I’d like to claim that I was clever enough to think of this in advance, but I wasn’t; originally the variable name and the quartile name were separated by dots, which made the separate more complicated, so I went back and changed it.<a href="multiple-regression.html#fnref3" class="footnote-back">↩</a></p></li>
<li id="fn4"><p>Usually you want to keep the other variables around as well, which is why you don’t see transmute very often.<a href="multiple-regression.html#fnref4" class="footnote-back">↩</a></p></li>
<li id="fn5"><p>This is “F” in quotes, meaning <span class="math inline">\(F\)</span>-test, not “F” without quotes, which means FALSE.<a href="multiple-regression.html#fnref5" class="footnote-back">↩</a></p></li>
<li id="fn6"><p>Weight between 8 and 11, for example, returning <code>TRUE</code> or <code>FALSE</code>.<a href="multiple-regression.html#fnref6" class="footnote-back">↩</a></p></li>
<li id="fn7"><p>Adjusted R-squareds are easier to compare in this context, since you don’t have to make a judgement about whether it has changed substantially, whatever you think substantially means.<a href="multiple-regression.html#fnref7" class="footnote-back">↩</a></p></li>
<li id="fn8"><p>The residuals have to be the ones from a regression <em>not</em> including the <span class="math inline">\(x\)</span>-variable you’re testing.<a href="multiple-regression.html#fnref8" class="footnote-back">↩</a></p></li>
<li id="fn9"><p>Or not take it out in the first place.<a href="multiple-regression.html#fnref9" class="footnote-back">↩</a></p></li>
</ol>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="simple-regression.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="regression-with-categorical-variables.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/lunr.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": null,
"text": null
},
"history": {
"link": null,
"text": null
},
"view": {
"link": null,
"text": null
},
"download": ["pasias.pdf"],
"toc": {
"collapse": "subsection"
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
