<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">

<head>

<meta charset="utf-8">
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<meta name="generator" content="pandoc" />
<meta name="viewport" content="width=device-width, initial-scale=1">
<meta property="og:title" content="Problems and Solutions in Applied Statistics" />
<meta property="og:type" content="book" />
<meta property="og:url" content="<a href="http://ritsokiguess.site/pasias" class="uri">http://ritsokiguess.site/pasias</a>" />

<meta property="og:description" content="A set of problems and solutions, in R, on various parts of applied statistics" />
<meta name="github-repo" content="nxskok/pasias" />

<meta name="author" content="Ken Butler" />

<meta name="date" content="2019-01-07" />

<script type="text/x-mathjax-config">
MathJax.Hub.Config({
  TeX: { equationNumbers: { autoNumber: "AMS" } }
});
</script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.2/MathJax.js?config=TeX-AMS_CHTML-full" type="text/javascript"></script>

<meta name="description" content="A set of problems and solutions, in R, on various parts of applied statistics">

<title>Problems and Solutions in Applied Statistics</title>

<link href="libs/tufte-css-2015.12.29/tufte-fonts.css" rel="stylesheet" />
<link href="libs/tufte-css-2015.12.29/tufte-background.css" rel="stylesheet" />
<link href="libs/tufte-css-2015.12.29/tufte-italics.css" rel="stylesheet" />
<link href="libs/tufte-css-2015.12.29/tufte.css" rel="stylesheet" />


<style type="text/css">code{white-space: pre;}</style>
<style type="text/css">
a.sourceLine { display: inline-block; line-height: 1.25; }
a.sourceLine { pointer-events: none; color: inherit; text-decoration: inherit; }
a.sourceLine:empty { height: 1.2em; position: absolute; }
.sourceCode { overflow: visible; }
code.sourceCode { white-space: pre; position: relative; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
code.sourceCode { white-space: pre-wrap; }
a.sourceLine { text-indent: -1em; padding-left: 1em; }
}
pre.numberSource a.sourceLine
  { position: relative; }
pre.numberSource a.sourceLine:empty
  { position: absolute; }
pre.numberSource a.sourceLine::before
  { content: attr(data-line-number);
    position: absolute; left: -5em; text-align: right; vertical-align: baseline;
    border: none; pointer-events: all;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {  }
@media screen {
a.sourceLine::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>


<link rel="stylesheet" href="toc.css" type="text/css" />

</head>

<body>



<div class="row">
<div class="col-sm-12">
<div id="TOC">
<ul>
<li><a href="index.html#introduction"><span class="toc-section-number">1</span> Introduction</a></li>
<li class="has-sub"><a href="getting-used-to-r-and-r-studio.html#getting-used-to-r-and-r-studio"><span class="toc-section-number">2</span> Getting used to R and R Studio</a><ul>
<li><a href="getting-used-to-r-and-r-studio.html#getting-an-r-studio-cloud-account"><span class="toc-section-number">2.1</span> Getting an R Studio Cloud account</a></li>
<li><a href="getting-used-to-r-and-r-studio.html#getting-started"><span class="toc-section-number">2.2</span> Getting started</a></li>
<li><a href="getting-used-to-r-and-r-studio.html#reading-data-from-a-file"><span class="toc-section-number">2.3</span> Reading data from a file</a></li>
<li><a href="getting-used-to-r-and-r-studio.html#reading-files-different-ways"><span class="toc-section-number">2.4</span> Reading files different ways</a></li>
</ul></li>
<li class="has-sub"><a href="reading-in-data-and-drawing-some-graphs.html#reading-in-data-and-drawing-some-graphs"><span class="toc-section-number">3</span> Reading in data and drawing some graphs</a><ul>
<li><a href="reading-in-data-and-drawing-some-graphs.html#orange-juice"><span class="toc-section-number">3.1</span> Orange juice</a></li>
<li><a href="reading-in-data-and-drawing-some-graphs.html#making-soap"><span class="toc-section-number">3.2</span> Making soap</a></li>
<li><a href="reading-in-data-and-drawing-some-graphs.html#handling-shipments"><span class="toc-section-number">3.3</span> Handling shipments</a></li>
</ul></li>
<li class="has-sub"><a href="data-exploration.html#data-exploration"><span class="toc-section-number">4</span> Data exploration</a><ul>
<li><a href="data-exploration.html#north-carolina-births"><span class="toc-section-number">4.1</span> North Carolina births</a></li>
<li><a href="data-exploration.html#more-about-the-nc-births"><span class="toc-section-number">4.2</span> More about the NC births</a></li>
<li><a href="data-exploration.html#nenana-alaska"><span class="toc-section-number">4.3</span> Nenana, Alaska</a></li>
<li><a href="data-exploration.html#computerized-accounting"><span class="toc-section-number">4.4</span> Computerized accounting</a></li>
<li><a href="data-exploration.html#test-scores-in-two-classes"><span class="toc-section-number">4.5</span> Test scores in two classes</a></li>
</ul></li>
<li class="has-sub"><a href="one-sample-inference.html#one-sample-inference"><span class="toc-section-number">5</span> One-sample inference</a><ul>
<li><a href="one-sample-inference.html#hunter-gatherers-in-australia"><span class="toc-section-number">5.1</span> Hunter-gatherers in Australia</a></li>
<li><a href="one-sample-inference.html#buses-to-boulder"><span class="toc-section-number">5.2</span> Buses to Boulder</a></li>
<li><a href="one-sample-inference.html#length-of-gestation-in-north-carolina"><span class="toc-section-number">5.3</span> Length of gestation in North Carolina</a></li>
<li><a href="one-sample-inference.html#inferring-ice-break-up-in-nenana"><span class="toc-section-number">5.4</span> Inferring ice break-up in Nenana</a></li>
</ul></li>
<li class="has-sub"><a href="two-sample-inference.html#two-sample-inference"><span class="toc-section-number">6</span> Two-sample inference</a><ul>
<li><a href="two-sample-inference.html#children-and-electronic-devices"><span class="toc-section-number">6.1</span> Children and electronic devices</a></li>
<li><a href="two-sample-inference.html#parking-close-to-the-curb"><span class="toc-section-number">6.2</span> Parking close to the curb</a></li>
<li><a href="two-sample-inference.html#bell-peppers-and-too-much-water"><span class="toc-section-number">6.3</span> Bell peppers and too much water</a></li>
<li><a href="two-sample-inference.html#exercise-and-anxiety-and-bullying-mice"><span class="toc-section-number">6.4</span> Exercise and anxiety and bullying mice</a></li>
<li><a href="two-sample-inference.html#diet-and-growth-in-boys"><span class="toc-section-number">6.5</span> Diet and growth in boys</a></li>
</ul></li>
<li class="has-sub"><a href="power-and-sample-size.html#power-and-sample-size"><span class="toc-section-number">7</span> Power and sample size</a><ul>
<li><a href="power-and-sample-size.html#simulating-power"><span class="toc-section-number">7.1</span> Simulating power</a></li>
<li><a href="power-and-sample-size.html#calculating-power-and-sample-size-for-estimating-mean"><span class="toc-section-number">7.2</span> Calculating power and sample size for estimating mean</a></li>
<li><a href="power-and-sample-size.html#simulating-power-for-proportions"><span class="toc-section-number">7.3</span> Simulating power for proportions</a></li>
</ul></li>
<li class="has-sub"><a href="the-sign-test-and-moods-median-test.html#the-sign-test-and-moods-median-test"><span class="toc-section-number">8</span> The sign test and Mood’s median test</a><ul>
<li><a href="the-sign-test-and-moods-median-test.html#running-a-maze"><span class="toc-section-number">8.1</span> Running a maze</a></li>
<li><a href="the-sign-test-and-moods-median-test.html#chocolate-chips"><span class="toc-section-number">8.2</span> Chocolate chips</a></li>
<li><a href="the-sign-test-and-moods-median-test.html#the-power-of-the-sign-test"><span class="toc-section-number">8.3</span> The power of the sign test</a></li>
<li><a href="the-sign-test-and-moods-median-test.html#sugar-in-breakfast-cereals"><span class="toc-section-number">8.4</span> Sugar in breakfast cereals</a></li>
<li><a href="the-sign-test-and-moods-median-test.html#fear-of-math"><span class="toc-section-number">8.5</span> Fear of math</a></li>
<li><a href="the-sign-test-and-moods-median-test.html#medical-instructions"><span class="toc-section-number">8.6</span> Medical instructions</a></li>
</ul></li>
<li class="has-sub"><a href="matched-pairs-t-and-sign-test.html#matched-pairs-t-and-sign-test"><span class="toc-section-number">9</span> Matched pairs t and sign test</a><ul>
<li><a href="matched-pairs-t-and-sign-test.html#measuring-body-fat"><span class="toc-section-number">9.1</span> Measuring body fat</a></li>
<li><a href="matched-pairs-t-and-sign-test.html#throwing-baseballs-and-softballs"><span class="toc-section-number">9.2</span> Throwing baseballs and softballs</a></li>
<li><a href="matched-pairs-t-and-sign-test.html#throwing-baseballs-and-softballs-again"><span class="toc-section-number">9.3</span> Throwing baseballs and softballs, again</a></li>
<li><a href="matched-pairs-t-and-sign-test.html#changes-in-salary"><span class="toc-section-number">9.4</span> Changes in salary</a></li>
<li><a href="matched-pairs-t-and-sign-test.html#body-fat-revisited"><span class="toc-section-number">9.5</span> Body fat revisited</a></li>
</ul></li>
<li class="has-sub"><a href="normal-quantile-plots.html#normal-quantile-plots"><span class="toc-section-number">10</span> Normal quantile plots</a><ul>
<li><a href="normal-quantile-plots.html#lengths-of-heliconia-flowers"><span class="toc-section-number">10.1</span> Lengths of heliconia flowers</a></li>
<li><a href="normal-quantile-plots.html#ferritin-and-normality"><span class="toc-section-number">10.2</span> Ferritin and normality</a></li>
</ul></li>
<li class="has-sub"><a href="analysis-of-variance.html#analysis-of-variance"><span class="toc-section-number">11</span> Analysis of variance</a><ul>
<li><a href="analysis-of-variance.html#movie-ratings-and-lengths"><span class="toc-section-number">11.1</span> Movie ratings and lengths</a></li>
<li><a href="analysis-of-variance.html#deer-and-how-much-they-eat"><span class="toc-section-number">11.2</span> Deer and how much they eat</a></li>
<li><a href="analysis-of-variance.html#movie-ratings-again"><span class="toc-section-number">11.3</span> Movie ratings again</a></li>
<li><a href="analysis-of-variance.html#atomic-weight-of-carbon"><span class="toc-section-number">11.4</span> Atomic weight of carbon</a></li>
<li><a href="analysis-of-variance.html#can-caffeine-improve-your-performance-on-a-test"><span class="toc-section-number">11.5</span> Can caffeine improve your performance on a test?</a></li>
</ul></li>
<li class="has-sub"><a href="tidying-and-selecting-data.html#tidying-and-selecting-data"><span class="toc-section-number">12</span> Tidying and selecting data</a><ul>
<li><a href="tidying-and-selecting-data.html#tidying-the-jays-data"><span class="toc-section-number">12.1</span> Tidying the Jays data</a></li>
<li><a href="tidying-and-selecting-data.html#baseball-and-softball-spaghetti"><span class="toc-section-number">12.2</span> Baseball and softball spaghetti</a></li>
<li><a href="tidying-and-selecting-data.html#ethanol-and-sleep-time-in-rats"><span class="toc-section-number">12.3</span> Ethanol and sleep time in rats</a></li>
<li><a href="tidying-and-selecting-data.html#growth-of-tomatoes"><span class="toc-section-number">12.4</span> Growth of tomatoes</a></li>
<li><a href="tidying-and-selecting-data.html#pain-relief-in-migraine-headaches-again"><span class="toc-section-number">12.5</span> Pain relief in migraine headaches (again)</a></li>
<li><a href="tidying-and-selecting-data.html#location-species-and-disease-in-plants"><span class="toc-section-number">12.6</span> Location, species and disease in plants</a></li>
<li><a href="tidying-and-selecting-data.html#mating-songs-in-crickets"><span class="toc-section-number">12.7</span> Mating songs in crickets</a></li>
<li><a href="tidying-and-selecting-data.html#cars"><span class="toc-section-number">12.8</span> Cars</a></li>
<li><a href="tidying-and-selecting-data.html#number-1-songs"><span class="toc-section-number">12.9</span> Number 1 songs</a></li>
<li><a href="tidying-and-selecting-data.html#bikes-on-college"><span class="toc-section-number">12.10</span> Bikes on College</a></li>
<li><a href="tidying-and-selecting-data.html#feeling-the-heat"><span class="toc-section-number">12.11</span> Feeling the heat</a></li>
</ul></li>
<li class="has-sub"><a href="regression.html#regression"><span class="toc-section-number">13</span> Regression</a><ul>
<li><a href="regression.html#rainfall-in-california"><span class="toc-section-number">13.1</span> Rainfall in California</a></li>
<li><a href="regression.html#carbon-monoxide-in-cigarettes"><span class="toc-section-number">13.2</span> Carbon monoxide in cigarettes</a></li>
<li><a href="regression.html#maximal-oxygen-uptake-in-young-boys"><span class="toc-section-number">13.3</span> Maximal oxygen uptake in young boys</a></li>
<li><a href="regression.html#facebook-friends-and-grey-matter"><span class="toc-section-number">13.4</span> Facebook friends and grey matter</a></li>
<li><a href="regression.html#endogenous-nitrogen-excretion-in-carp"><span class="toc-section-number">13.5</span> Endogenous nitrogen excretion in carp</a></li>
<li><a href="regression.html#sparrowhawks"><span class="toc-section-number">13.6</span> Sparrowhawks</a></li>
<li><a href="regression.html#salaries-of-social-workers"><span class="toc-section-number">13.7</span> Salaries of social workers</a></li>
<li><a href="regression.html#predicting-volume-of-wood-in-pine-trees"><span class="toc-section-number">13.8</span> Predicting volume of wood in pine trees</a></li>
<li><a href="regression.html#tortoise-shells-and-eggs"><span class="toc-section-number">13.9</span> Tortoise shells and eggs</a></li>
<li><a href="regression.html#crickets-revisited"><span class="toc-section-number">13.10</span> Crickets revisited</a></li>
<li><a href="regression.html#roller-coasters"><span class="toc-section-number">13.11</span> Roller coasters</a></li>
<li><a href="regression.html#running-and-blood-sugar"><span class="toc-section-number">13.12</span> Running and blood sugar</a></li>
<li><a href="regression.html#calories-and-fat-in-pizza"><span class="toc-section-number">13.13</span> Calories and fat in pizza</a></li>
<li><a href="regression.html#where-should-the-fire-stations-be"><span class="toc-section-number">13.14</span> Where should the fire stations be?</a></li>
<li><a href="regression.html#being-satisfied-with-hospital"><span class="toc-section-number">13.15</span> Being satisfied with hospital</a></li>
<li><a href="regression.html#handling-shipments-of-chemicals"><span class="toc-section-number">13.16</span> Handling shipments of chemicals</a></li>
<li><a href="regression.html#salaries-of-mathematicians"><span class="toc-section-number">13.17</span> Salaries of mathematicians</a></li>
<li><a href="regression.html#predicting-gpa-of-computer-science-students"><span class="toc-section-number">13.18</span> Predicting GPA of computer science students</a></li>
</ul></li>
<li class="has-sub"><a href="dates-and-times.html#dates-and-times"><span class="toc-section-number">14</span> Dates and times</a><ul>
<li><a href="dates-and-times.html#dealing-with-dates-in-the-worcester-heart-attack-study"><span class="toc-section-number">14.1</span> Dealing with dates in the Worcester Heart Attack study</a></li>
<li><a href="dates-and-times.html#growth-of-mizuna-lettuce-seeds"><span class="toc-section-number">14.2</span> Growth of Mizuna lettuce seeds</a></li>
<li><a href="dates-and-times.html#types-of-childbirth"><span class="toc-section-number">14.3</span> Types of childbirth</a></li>
<li><a href="dates-and-times.html#wolves-and-caribou"><span class="toc-section-number">14.4</span> Wolves and caribou</a></li>
</ul></li>
<li class="has-sub"><a href="functions.html#functions"><span class="toc-section-number">15</span> Functions</a><ul>
<li><a href="functions.html#making-some-r-functions"><span class="toc-section-number">15.1</span> Making some R functions</a></li>
<li><a href="functions.html#the-collatz-sequence"><span class="toc-section-number">15.2</span> The Collatz sequence</a></li>
</ul></li>
<li class="has-sub"><a href="logistic-regression.html#logistic-regression"><span class="toc-section-number">16</span> Logistic regression</a><ul>
<li><a href="logistic-regression.html#finding-wolf-spiders-on-the-beach"><span class="toc-section-number">16.1</span> Finding wolf spiders on the beach</a></li>
<li><a href="logistic-regression.html#killing-aphids"><span class="toc-section-number">16.2</span> Killing aphids</a></li>
<li><a href="logistic-regression.html#the-effects-of-substance-a"><span class="toc-section-number">16.3</span> The effects of Substance A</a></li>
<li><a href="logistic-regression.html#what-makes-an-animal-get-infected"><span class="toc-section-number">16.4</span> What makes an animal get infected?</a></li>
<li><a href="logistic-regression.html#the-brain-of-a-cat"><span class="toc-section-number">16.5</span> The brain of a cat</a></li>
<li><a href="logistic-regression.html#how-not-to-get-heart-disease"><span class="toc-section-number">16.6</span> How not to get heart disease</a></li>
<li><a href="logistic-regression.html#successful-breastfeeding"><span class="toc-section-number">16.7</span> Successful breastfeeding</a></li>
<li><a href="logistic-regression.html#making-it-over-the-mountains"><span class="toc-section-number">16.8</span> Making it over the mountains</a></li>
<li><a href="logistic-regression.html#who-needs-the-most-intensive-care"><span class="toc-section-number">16.9</span> Who needs the most intensive care?</a></li>
<li><a href="logistic-regression.html#go-away-and-dont-come-back"><span class="toc-section-number">16.10</span> Go away and don’t come back!</a></li>
</ul></li>
<li class="has-sub"><a href="logistic-regression-with-ordinal-or-nominal-response.html#logistic-regression-with-ordinal-or-nominal-response"><span class="toc-section-number">17</span> Logistic regression with ordinal or nominal response</a><ul>
<li><a href="logistic-regression-with-ordinal-or-nominal-response.html#do-you-like-your-mobile-phone"><span class="toc-section-number">17.1</span> Do you like your mobile phone?</a></li>
<li><a href="logistic-regression-with-ordinal-or-nominal-response.html#attitudes-towards-abortion"><span class="toc-section-number">17.2</span> Attitudes towards abortion</a></li>
<li><a href="logistic-regression-with-ordinal-or-nominal-response.html#finding-non-missing-values"><span class="toc-section-number">17.3</span> Finding non-missing values</a></li>
<li><a href="logistic-regression-with-ordinal-or-nominal-response.html#european-social-survey-and-voting"><span class="toc-section-number">17.4</span> European Social Survey and voting</a></li>
<li><a href="logistic-regression-with-ordinal-or-nominal-response.html#alligator-food"><span class="toc-section-number">17.5</span> Alligator food</a></li>
<li><a href="logistic-regression-with-ordinal-or-nominal-response.html#how-do-you-like-your-steak-the-data"><span class="toc-section-number">17.6</span> How do you like your steak – the data</a></li>
<li><a href="logistic-regression-with-ordinal-or-nominal-response.html#crimes-in-san-francisco-the-data"><span class="toc-section-number">17.7</span> Crimes in San Francisco – the data</a></li>
<li><a href="logistic-regression-with-ordinal-or-nominal-response.html#how-do-you-like-your-steak"><span class="toc-section-number">17.8</span> How do you like your steak?</a></li>
<li><a href="logistic-regression-with-ordinal-or-nominal-response.html#crimes-in-san-francisco"><span class="toc-section-number">17.9</span> Crimes in San Francisco</a></li>
<li><a href="logistic-regression-with-ordinal-or-nominal-response.html#high-school-and-beyond"><span class="toc-section-number">17.10</span> High School and Beyond</a></li>
<li><a href="logistic-regression-with-ordinal-or-nominal-response.html#what-sports-do-these-athletes-play"><span class="toc-section-number">17.11</span> What sports do these athletes play?</a></li>
</ul></li>
<li class="has-sub"><a href="survival-analysis.html#survival-analysis"><span class="toc-section-number">18</span> Survival analysis</a><ul>
<li><a href="survival-analysis.html#the-worcester-survey"><span class="toc-section-number">18.1</span> The Worcester survey</a></li>
<li><a href="survival-analysis.html#drug-treatment-programs"><span class="toc-section-number">18.2</span> Drug treatment programs</a></li>
<li><a href="survival-analysis.html#multiple-myeloma"><span class="toc-section-number">18.3</span> Multiple myeloma</a></li>
<li><a href="survival-analysis.html#ovarian-cancer"><span class="toc-section-number">18.4</span> Ovarian cancer</a></li>
</ul></li>
<li class="has-sub"><a href="analysis-of-variance-revisited.html#analysis-of-variance-revisited"><span class="toc-section-number">19</span> Analysis of variance revisited</a><ul>
<li><a href="analysis-of-variance-revisited.html#acid-rain"><span class="toc-section-number">19.1</span> Acid rain</a></li>
<li><a href="analysis-of-variance-revisited.html#treating-hay-fever"><span class="toc-section-number">19.2</span> Treating hay fever</a></li>
<li><a href="analysis-of-variance-revisited.html#focused-comparisons-of-the-effect-of-caffeine"><span class="toc-section-number">19.3</span> Focused comparisons of the effect of caffeine</a></li>
<li><a href="analysis-of-variance-revisited.html#who-studies-the-most-outside-class"><span class="toc-section-number">19.4</span> Who studies the most outside class?</a></li>
<li><a href="analysis-of-variance-revisited.html#mental-context"><span class="toc-section-number">19.5</span> Mental context</a></li>
<li><a href="analysis-of-variance-revisited.html#trying-on-shirts"><span class="toc-section-number">19.6</span> Trying on shirts</a></li>
<li><a href="analysis-of-variance-revisited.html#productivity-and-research-and-development"><span class="toc-section-number">19.7</span> Productivity and research-and-development</a></li>
<li><a href="analysis-of-variance-revisited.html#treating-leprosy"><span class="toc-section-number">19.8</span> Treating leprosy</a></li>
</ul></li>
<li class="has-sub"><a href="multivariate-analysis-of-variance.html#multivariate-analysis-of-variance"><span class="toc-section-number">20</span> Multivariate analysis of variance</a><ul>
<li><a href="multivariate-analysis-of-variance.html#fabricated-data"><span class="toc-section-number">20.1</span> Fabricated data</a></li>
<li><a href="multivariate-analysis-of-variance.html#do-characteristics-of-urine-depend-on-obesity"><span class="toc-section-number">20.2</span> Do characteristics of urine depend on obesity?</a></li>
<li><a href="multivariate-analysis-of-variance.html#how-do-height-and-weight-depend-on-sport-played-by-elite-athletes"><span class="toc-section-number">20.3</span> How do height and weight depend on sport played by elite athletes?</a></li>
</ul></li>
<li class="has-sub"><a href="repeated-measures.html#repeated-measures"><span class="toc-section-number">21</span> Repeated measures</a><ul>
<li><a href="repeated-measures.html#effect-of-drug-on-rat-weight"><span class="toc-section-number">21.1</span> Effect of drug on rat weight</a></li>
<li><a href="repeated-measures.html#social-interaction-among-old-people"><span class="toc-section-number">21.2</span> Social interaction among old people</a></li>
<li><a href="repeated-measures.html#childrens-stress-levels-and-airports"><span class="toc-section-number">21.3</span> Children’s stress levels and airports</a></li>
<li><a href="repeated-measures.html#body-fat-as-repeated-measures"><span class="toc-section-number">21.4</span> Body fat as repeated measures</a></li>
<li><a href="repeated-measures.html#investigating-motor-activity-in-rats"><span class="toc-section-number">21.5</span> Investigating motor activity in rats</a></li>
<li><a href="repeated-measures.html#repeated-measures-with-no-background"><span class="toc-section-number">21.6</span> Repeated measures with no background</a></li>
</ul></li>
<li class="has-sub"><a href="discriminant-analysis.html#discriminant-analysis"><span class="toc-section-number">22</span> Discriminant analysis</a><ul>
<li><a href="discriminant-analysis.html#telling-whether-a-banknote-is-real-or-counterfeit"><span class="toc-section-number">22.1</span> Telling whether a banknote is real or counterfeit</a></li>
<li><a href="discriminant-analysis.html#urine-and-obesity-what-makes-a-difference"><span class="toc-section-number">22.2</span> Urine and obesity: what makes a difference?</a></li>
<li><a href="discriminant-analysis.html#understanding-a-manova"><span class="toc-section-number">22.3</span> Understanding a MANOVA</a></li>
<li><a href="discriminant-analysis.html#what-distinguishes-people-who-do-different-jobs"><span class="toc-section-number">22.4</span> What distinguishes people who do different jobs?</a></li>
<li><a href="discriminant-analysis.html#observing-children-with-adhd"><span class="toc-section-number">22.5</span> Observing children with ADHD</a></li>
<li><a href="discriminant-analysis.html#growing-corn"><span class="toc-section-number">22.6</span> Growing corn</a></li>
<li><a href="discriminant-analysis.html#understanding-athletes-height-weight-sport-and-gender"><span class="toc-section-number">22.7</span> Understanding athletes’ height, weight, sport and gender</a></li>
</ul></li>
<li class="has-sub"><a href="cluster-analysis.html#cluster-analysis"><span class="toc-section-number">23</span> Cluster analysis</a><ul>
<li><a href="cluster-analysis.html#dissimilarities-between-fruits"><span class="toc-section-number">23.1</span> Dissimilarities between fruits</a></li>
<li><a href="cluster-analysis.html#similarity-of-species"><span class="toc-section-number">23.2</span> Similarity of species</a></li>
<li><a href="cluster-analysis.html#rating-beer"><span class="toc-section-number">23.3</span> Rating beer</a></li>
<li><a href="cluster-analysis.html#sites-on-the-sea-bed"><span class="toc-section-number">23.4</span> Sites on the sea bed</a></li>
<li><a href="cluster-analysis.html#clustering-the-swiss-bills"><span class="toc-section-number">23.5</span> Clustering the Swiss bills</a></li>
<li><a href="cluster-analysis.html#grouping-similar-cars"><span class="toc-section-number">23.6</span> Grouping similar cars</a></li>
<li><a href="cluster-analysis.html#running-jumping-and-throwing"><span class="toc-section-number">23.7</span> Running, jumping, and throwing</a></li>
<li><a href="cluster-analysis.html#bridges-in-pittsburgh"><span class="toc-section-number">23.8</span> Bridges in Pittsburgh</a></li>
</ul></li>
<li class="has-sub"><a href="multidimensional-scaling.html#multidimensional-scaling"><span class="toc-section-number">24</span> Multidimensional Scaling</a><ul>
<li><a href="multidimensional-scaling.html#making-a-map-of-wisconsin"><span class="toc-section-number">24.1</span> Making a map of Wisconsin</a></li>
<li><a href="multidimensional-scaling.html#things-that-feel-similar-to-each-other"><span class="toc-section-number">24.2</span> Things that feel similar to each other</a></li>
<li><a href="multidimensional-scaling.html#confusing-letters"><span class="toc-section-number">24.3</span> Confusing letters</a></li>
<li><a href="multidimensional-scaling.html#more-beer-please"><span class="toc-section-number">24.4</span> More beer please</a></li>
<li><a href="multidimensional-scaling.html#feeling-similar-again"><span class="toc-section-number">24.5</span> Feeling similar, again</a></li>
</ul></li>
<li class="has-sub"><a href="principal-components-and-factor-analysis.html#principal-components-and-factor-analysis"><span class="toc-section-number">25</span> Principal Components and Factor Analysis</a><ul>
<li><a href="principal-components-and-factor-analysis.html#the-weather-somewhere"><span class="toc-section-number">25.1</span> The weather, somewhere</a></li>
<li><a href="principal-components-and-factor-analysis.html#air-pollution"><span class="toc-section-number">25.2</span> Air pollution</a></li>
<li><a href="principal-components-and-factor-analysis.html#a-correlation-matrix"><span class="toc-section-number">25.3</span> A correlation matrix</a></li>
<li><a href="principal-components-and-factor-analysis.html#the-interpersonal-circumplex"><span class="toc-section-number">25.4</span> The Interpersonal Circumplex</a></li>
</ul></li>
<li class="has-sub"><a href="frequency-table-analysis.html#frequency-table-analysis"><span class="toc-section-number">26</span> Frequency table analysis</a><ul>
<li><a href="frequency-table-analysis.html#college-plans"><span class="toc-section-number">26.1</span> College plans</a></li>
<li><a href="frequency-table-analysis.html#predicting-voting"><span class="toc-section-number">26.2</span> Predicting voting</a></li>
</ul></li>
</ul>
</div>
</div>
</div>
<div class="row">
<div class="col-sm-12">
<div id="multidimensional-scaling" class="section level1">
<h1><span class="header-section-number">Chapter 24</span> Multidimensional Scaling</h1>
<p>Packages for this chapter:</p>
<div class="sourceCode" id="cb3939"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb3939-1" data-line-number="1"><span class="kw">library</span>(ggbiplot)</a></code></pre></div>
<pre><code>## Loading required package: ggplot2</code></pre>
<pre><code>## Loading required package: plyr</code></pre>
<pre><code>## Loading required package: scales</code></pre>
<pre><code>## Loading required package: grid</code></pre>
<div class="sourceCode" id="cb3944"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb3944-1" data-line-number="1"><span class="kw">library</span>(tidyverse)</a></code></pre></div>
<pre><code>## ── Attaching packages ────────────────────────────────── tidyverse 1.2.1 ──</code></pre>
<pre><code>## ✔ tibble  2.0.1     ✔ purrr   0.3.0
## ✔ tidyr   0.8.2     ✔ dplyr   0.7.8
## ✔ readr   1.3.1     ✔ stringr 1.4.0
## ✔ tibble  2.0.1     ✔ forcats 0.3.0</code></pre>
<pre><code>## ── Conflicts ───────────────────────────────────── tidyverse_conflicts() ──
## ✖ dplyr::arrange()    masks plyr::arrange()
## ✖ readr::col_factor() masks scales::col_factor()
## ✖ purrr::compact()    masks plyr::compact()
## ✖ dplyr::count()      masks plyr::count()
## ✖ purrr::discard()    masks scales::discard()
## ✖ dplyr::failwith()   masks plyr::failwith()
## ✖ dplyr::filter()     masks stats::filter()
## ✖ dplyr::id()         masks plyr::id()
## ✖ dplyr::lag()        masks stats::lag()
## ✖ dplyr::mutate()     masks plyr::mutate()
## ✖ dplyr::rename()     masks plyr::rename()
## ✖ dplyr::summarise()  masks plyr::summarise()
## ✖ dplyr::summarize()  masks plyr::summarize()</code></pre>
<div class="sourceCode" id="cb3948"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb3948-1" data-line-number="1"><span class="kw">library</span>(ggrepel)</a></code></pre></div>
<div id="making-a-map-of-wisconsin" class="section level2">
<h2><span class="header-section-number">24.1</span> Making a map of Wisconsin</h2>
<p>The file
<a href="http://www.utsc.utoronto.ca/~butler/d29/wisconsin.txt">link</a> contains
the road distances (in miles) between 12 cities in Wisconsin and
neighbouring states. We are going to try to reproduce a map of the
area using multidimensional scaling.</p>
<ol style="list-style-type: lower-alpha">
<li>Read in the data and create a <code>dist</code> object,
bearing in mind that the data in the file are already
distances. Display your <code>dist</code> object. Probably, displaying
the data that you read in is a good idea also.</li>
</ol>
<p>Solution</p>
<div class="sourceCode" id="cb3949"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb3949-1" data-line-number="1">my_url=<span class="st">&quot;http://www.utsc.utoronto.ca/~butler/d29/wisconsin.txt&quot;</span></a>
<a class="sourceLine" id="cb3949-2" data-line-number="2">wisc=<span class="kw">read_table</span>(my_url)</a></code></pre></div>
<pre><code>## Parsed with column specification:
## cols(
##   location = col_character(),
##   Appleton = col_double(),
##   Beloit = col_double(),
##   Fort.Atkinson = col_double(),
##   Madison = col_double(),
##   Marshfield = col_double(),
##   Milwaukee = col_double(),
##   Monroe = col_double(),
##   Superior = col_double(),
##   Wausau = col_double(),
##   Dubuque = col_double(),
##   St.Paul = col_double(),
##   Chicago = col_double()
## )</code></pre>
<div class="sourceCode" id="cb3951"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb3951-1" data-line-number="1">wisc</a></code></pre></div>
<pre><code>## # A tibble: 12 x 13
##    location Appleton Beloit Fort.Atkinson Madison Marshfield Milwaukee
##    &lt;chr&gt;       &lt;dbl&gt;  &lt;dbl&gt;         &lt;dbl&gt;   &lt;dbl&gt;      &lt;dbl&gt;     &lt;dbl&gt;
##  1 Appleton        0    130            98     102        103       100
##  2 Beloit        130      0            33      50        185        73
##  3 Fort.At…       98     33             0      36        164        54
##  4 Madison       102     50            36       0        138        77
##  5 Marshfi…      103    185           164     138          0       184
##  6 Milwauk…      100     73            54      77        184         0
##  7 Monroe        149     33            58      47        170       107
##  8 Superior      315    377           359     330        219       394
##  9 Wausau         91    186           166     139         45       181
## 10 Dubuque       196     94           119      95        186       168
## 11 St.Paul       257    304           287     258        161       322
## 12 Chicago       186     97           113     146        276        93
## # … with 6 more variables: Monroe &lt;dbl&gt;, Superior &lt;dbl&gt;, Wausau &lt;dbl&gt;,
## #   Dubuque &lt;dbl&gt;, St.Paul &lt;dbl&gt;, Chicago &lt;dbl&gt;</code></pre>
<p>The first time I did this, I had a blank line on the end of the data
file, so I had a blank <code>location</code> and missing values for all
the distances for it. I tidied that up before sharing the file with
you, though.</p>
<p>So, the first column is the names of the places, which we should get
rid of before we make a <code>dist</code> object using <code>as.dist</code>
(since what we read in is already distances). The columns are also the
names of the places, so we won’t lose anything by getting rid of the
<code>location</code> column:</p>
<div class="sourceCode" id="cb3953"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb3953-1" data-line-number="1">d =<span class="st"> </span>wisc <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">select</span>(<span class="op">-</span>location) <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb3953-2" data-line-number="2"><span class="kw">as.dist</span>()</a>
<a class="sourceLine" id="cb3953-3" data-line-number="3">d</a></code></pre></div>
<pre><code>##               Appleton Beloit Fort.Atkinson Madison Marshfield Milwaukee
## Beloit             130                                                  
## Fort.Atkinson       98     33                                           
## Madison            102     50            36                             
## Marshfield         103    185           164     138                     
## Milwaukee          100     73            54      77        184          
## Monroe             149     33            58      47        170       107
## Superior           315    377           359     330        219       394
## Wausau              91    186           166     139         45       181
## Dubuque            196     94           119      95        186       168
## St.Paul            257    304           287     258        161       322
## Chicago            186     97           113     146        276        93
##               Monroe Superior Wausau Dubuque St.Paul
## Beloit                                              
## Fort.Atkinson                                       
## Madison                                             
## Marshfield                                          
## Milwaukee                                           
## Monroe                                              
## Superior         362                                
## Wausau           186      223                       
## Dubuque           61      351    215                
## St.Paul          289      162    175     274        
## Chicago          130      467    275     184     395</code></pre>
<ol start="2" style="list-style-type: lower-alpha">
<li>Obtain a vector containing the city names. (This is easy,
and not really necessary, but it was here before when I did things
a different way.)</li>
</ol>
<p>Solution</p>
<p>The <code>location</code> column of the data frame you read in
from the file:</p>
<div class="sourceCode" id="cb3955"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb3955-1" data-line-number="1">cities=wisc<span class="op">$</span>location</a>
<a class="sourceLine" id="cb3955-2" data-line-number="2">cities</a></code></pre></div>
<pre><code>##  [1] &quot;Appleton&quot;      &quot;Beloit&quot;        &quot;Fort.Atkinson&quot; &quot;Madison&quot;      
##  [5] &quot;Marshfield&quot;    &quot;Milwaukee&quot;     &quot;Monroe&quot;        &quot;Superior&quot;     
##  [9] &quot;Wausau&quot;        &quot;Dubuque&quot;       &quot;St.Paul&quot;       &quot;Chicago&quot;</code></pre>
<ol start="3" style="list-style-type: lower-alpha">
<li>Run a (metric) multidimensional scaling on the data, to
obtain a two-dimensional representation of the cities. (You
don’t need to look at the results yet.)</li>
</ol>
<p>Solution</p>
<div class="sourceCode" id="cb3957"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb3957-1" data-line-number="1">wisc<span class="fl">.1</span>=<span class="kw">cmdscale</span>(d)</a></code></pre></div>
<ol start="4" style="list-style-type: lower-alpha">
<li>Plot the results of the multidimensional scaling,
labelling the cities with their names. Use your judgement to
decide where to place the city names, and how to make sure the
whole city names are shown on the map.</li>
</ol>
<p>Solution</p>
<p>Let’s see what <code>wisc.1</code> has in it, and make a data
frame of the right thing:</p>
<div class="sourceCode" id="cb3958"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb3958-1" data-line-number="1"><span class="kw">head</span>(wisc<span class="fl">.1</span>)</a></code></pre></div>
<pre><code>##                     [,1]       [,2]
## Appleton       -13.37076  85.067148
## Beloit         -92.94157 -20.205916
## Fort.Atkinson  -74.07473   4.804039
## Madison        -44.68148 -11.252521
## Marshfield      80.61250  27.097882
## Milwaukee     -102.87582  49.849552</code></pre>
<p>Two unnamed columns (the display indicates that it’s a <code>matrix</code>
rather than a data frame). As we saw in class, if we make a data frame
out of this, the columns will get names <code>X1</code> and
<code>X2</code>. Those are perfectly good names for coordinates. The city
names on the left of <code>wisc.1</code> are actually row names rather
than an actual genuine column. It’s probably best <em>not</em> to assume
that they will make it through the transition to a data frame, so
we’ll explicitly create a column called <code>city</code> with the city
names (that we saved before):</p>
<div class="sourceCode" id="cb3960"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb3960-1" data-line-number="1">dd=<span class="kw">data.frame</span>(wisc<span class="fl">.1</span>,<span class="dt">city=</span>cities)</a>
<a class="sourceLine" id="cb3960-2" data-line-number="2">dd</a></code></pre></div>
<pre><code>##                       X1          X2          city
## Appleton       -13.37076   85.067148      Appleton
## Beloit         -92.94157  -20.205916        Beloit
## Fort.Atkinson  -74.07473    4.804039 Fort.Atkinson
## Madison        -44.68148  -11.252521       Madison
## Marshfield      80.61250   27.097882    Marshfield
## Milwaukee     -102.87582   49.849552     Milwaukee
## Monroe         -74.66603  -48.422639        Monroe
## Superior       279.27573   -8.621892      Superior
## Wausau          79.19504   60.997371        Wausau
## Dubuque        -50.92029 -108.488036       Dubuque
## St.Paul        199.16640  -39.595481       St.Paul
## Chicago       -184.71900    8.770492       Chicago</code></pre>
<p>There are only 12 rows, so it’s fine to display them all.</p>
<p>I’m calling this one <code>dd</code> since I have another <code>d</code>
elsewhere that I want to keep. I should use better names.</p>
<p>I think the best use of your judgement is to go straight to
<code>geom_text_repel</code> from package <code>ggrepel</code>:</p>
<div class="sourceCode" id="cb3962"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb3962-1" data-line-number="1"><span class="kw">ggplot</span>(dd,<span class="kw">aes</span>(<span class="dt">x=</span>X1,<span class="dt">y=</span>X2,<span class="dt">label=</span>city))<span class="op">+</span></a>
<a class="sourceLine" id="cb3962-2" data-line-number="2"><span class="kw">geom_point</span>()<span class="op">+</span></a>
<a class="sourceLine" id="cb3962-3" data-line-number="3"><span class="kw">geom_text_repel</span>()<span class="op">+</span></a>
<a class="sourceLine" id="cb3962-4" data-line-number="4"><span class="kw">coord_fixed</span>()</a></code></pre></div>
<p><img src="23-mds_files/figure-html/unnamed-chunk-8-1.png" width="672"  /></p>
<p>Your map may come out different from mine, but subject to the usual
stuff about rotation and reflection it should be equivalent to
mine. You should include the <code>coord_fixed</code> to get the scales
the same (a corresponding distance on the two scales should take the
same space). This one didn’t come out quite square because the MDS
says the points should be in a rectangle (stretching further one way
than the other).</p>
<ol start="5" style="list-style-type: lower-alpha">
<li>Are cities close together on your map also close together
in real life? Give an example or two.</li>
</ol>
<p>Solution</p>
<p>On the map, the trio of cities Madison, Beloit and Fort Atkinson
are closest together. How far apart are they actually? Well, you
can go back to the original file (or display of what I called
<code>d</code>) and find them, or you can do this:</p>
<div class="sourceCode" id="cb3963"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb3963-1" data-line-number="1">cities</a></code></pre></div>
<pre><code>##  [1] &quot;Appleton&quot;      &quot;Beloit&quot;        &quot;Fort.Atkinson&quot; &quot;Madison&quot;      
##  [5] &quot;Marshfield&quot;    &quot;Milwaukee&quot;     &quot;Monroe&quot;        &quot;Superior&quot;     
##  [9] &quot;Wausau&quot;        &quot;Dubuque&quot;       &quot;St.Paul&quot;       &quot;Chicago&quot;</code></pre>
<p>Cities 2, 3 and 4, so:</p>
<div class="sourceCode" id="cb3965"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb3965-1" data-line-number="1">wisc <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">slice</span>(<span class="dv">2</span><span class="op">:</span><span class="dv">4</span>) <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">select</span>(<span class="kw">c</span>(<span class="dv">1</span>,<span class="dv">3</span><span class="op">:</span><span class="dv">5</span>))</a></code></pre></div>
<pre><code>## # A tibble: 3 x 4
##   location      Beloit Fort.Atkinson Madison
##   &lt;chr&gt;          &lt;dbl&gt;         &lt;dbl&gt;   &lt;dbl&gt;
## 1 Beloit             0            33      50
## 2 Fort.Atkinson     33             0      36
## 3 Madison           50            36       0</code></pre>
<p>The column numbers are off by one, since the first column is the names
of the cities, which I decided to display here. It came out right, anyway.</p>
<p>These are all less than 50 miles or less apart. There are some others
this close in the original data: Monroe and Madison are 47 miles
apart, Wausau and Marshfield are 45 miles apart, but these appear
further apart on the map.
Extra: the slice-select thing doesn’t work on <code>d</code> because that is not
a data frame. It is actually stored internally as a
<em>one</em>-dimensional vector that displays nicely, but if you want to
pull things out of it you have to figure out where in the vector they are:</p>
<div class="sourceCode" id="cb3967"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb3967-1" data-line-number="1"><span class="kw">print.default</span>(d)</a></code></pre></div>
<pre><code>##  [1] 130  98 102 103 100 149 315  91 196 257 186  33  50 185  73  33 377
## [18] 186  94 304  97  36 164  54  58 359 166 119 287 113 138  77  47 330
## [35] 139  95 258 146 184 170 219  45 186 161 276 107 394 181 168 322  93
## [52] 362 186  61 289 130 223 351 162 467 215 175 275 274 184 395
## attr(,&quot;Labels&quot;)
##  [1] &quot;Appleton&quot;      &quot;Beloit&quot;        &quot;Fort.Atkinson&quot; &quot;Madison&quot;      
##  [5] &quot;Marshfield&quot;    &quot;Milwaukee&quot;     &quot;Monroe&quot;        &quot;Superior&quot;     
##  [9] &quot;Wausau&quot;        &quot;Dubuque&quot;       &quot;St.Paul&quot;       &quot;Chicago&quot;      
## attr(,&quot;Size&quot;)
## [1] 12
## attr(,&quot;call&quot;)
## as.dist.default(m = .)
## attr(,&quot;class&quot;)
## [1] &quot;dist&quot;
## attr(,&quot;Diag&quot;)
## [1] FALSE
## attr(,&quot;Upper&quot;)
## [1] FALSE</code></pre>
<p>If you compare that with the usual display of <code>d</code>, this way
goes all the way down the first column ending at 130, then all the way
down the second column (which has one fewer entry), ending at 467, and
so on. Thus the three entries we picked out are at <span class="math inline">\(11+1=12\)</span>,
<span class="math inline">\(11+2=13\)</span>, and <span class="math inline">\(11+10+1=22\)</span>:</p>
<div class="sourceCode" id="cb3969"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb3969-1" data-line-number="1">d[<span class="dv">12</span>]</a></code></pre></div>
<pre><code>## [1] 33</code></pre>
<div class="sourceCode" id="cb3971"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb3971-1" data-line-number="1">d[<span class="dv">13</span>]</a></code></pre></div>
<pre><code>## [1] 50</code></pre>
<div class="sourceCode" id="cb3973"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb3973-1" data-line-number="1">d[<span class="dv">22</span>]</a></code></pre></div>
<pre><code>## [1] 36</code></pre>
<p>It’s very easy to be off by one in this sort of calculation. There are
12 cities altogether, so <em>11</em> distances in the first column, 10
in the second, and so on. This was about my third attempt.</p>
<p>I don’t much care which cities you look at. Finding some cities that
are reasonably close on the map and doing some kind of critical
assessment of their actual distances apart is all I want.</p>
<ol start="6" style="list-style-type: lower-alpha">
<li>Obtain a Google (or other) map of the area containing these
twelve cities. (The way I expected you to do this when this was a
hand-in problem was to take a screenshot or similar and include that
in your document.)</li>
</ol>
<p>Solution</p>
<p>Since I like to show off, let me show you how you can do this in R,
using the package <code>ggmap</code>. (Of course, you can just open the
appropriate map in your browser and copy-paste it, taking a
screenshot if necessary):</p>
<div class="sourceCode" id="cb3975"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb3975-1" data-line-number="1"><span class="kw">library</span>(ggmap)</a></code></pre></div>
<pre><code>## Google&#39;s Terms of Service: https://cloud.google.com/maps-platform/terms/.</code></pre>
<pre><code>## Please cite ggmap if you use it! See citation(&quot;ggmap&quot;) for details.</code></pre>
<div class="sourceCode" id="cb3978"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb3978-1" data-line-number="1"><span class="kw">library</span>(ggmap)</a>
<a class="sourceLine" id="cb3978-2" data-line-number="2">wisc.map=<span class="kw">get_map</span>(<span class="dt">location=</span><span class="st">&quot;Milwaukee, WI&quot;</span>,<span class="dt">zoom=</span><span class="dv">6</span>)</a></code></pre></div>
<pre><code>## Source : https://maps.googleapis.com/maps/api/staticmap?center=Milwaukee,%20WI&amp;zoom=6&amp;size=640x640&amp;scale=2&amp;maptype=terrain&amp;language=en-EN&amp;key=xxx-Mj1-zNBW4GTnXNAYdGQJDNXU</code></pre>
<pre><code>## Source : https://maps.googleapis.com/maps/api/geocode/json?address=Milwaukee%2C%20WI&amp;key=xxx-Mj1-zNBW4GTnXNAYdGQJDNXU</code></pre>
<div class="sourceCode" id="cb3981"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb3981-1" data-line-number="1"><span class="kw">ggmap</span>(wisc.map)</a></code></pre></div>
<p><img src="23-mds_files/figure-html/laskhsal-1.png" width="576"  /></p>
<p>I centred this map around Milwaukee (a guess), which is not quite
where the centre should be, since Milwaukee is in southeastern
Wisconsin. The <code>zoom</code> option is how zoomed-in the map should be
(a higher number is more zoomed-in). Likewise, 6 was a guess, and it
seems that I need to zoom in a bit more.</p>
<p>The other way of specifying a location, instead of the name or
lat-long of the centre of the map, is to specify the <strong>corners</strong>
of the map in degrees of latitude or longitude. We have to give four
numbers: lower left longitude and latitude, upper right longitude and
latitude. (Degrees west are <em>negative</em>, as you see on the
<code>lon</code> scale of the above map.) This comes out as west, south,
east and north limits of the map.
Where are the 12 points we want to put on the map? We can get their
latitudes and longitudes, which is called “geocoding”, and a
function <code>geocode</code> is included in <code>ggmap</code>.</p>
<p>First add the state names to the cities, to make sure Google Maps
looks up the right ones. All of them are in Wisconsin, except for the
last three: Dubuque is in Iowa, St. Paul is in Minnesota and Chicago
is in Illinois. I am first making a vector with 12 copies of the
abbreviation for Wisconsin, and then overwriting the last three with
the states they are actually in:</p>
<div class="sourceCode" id="cb3982"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb3982-1" data-line-number="1">states=<span class="kw">rep</span>(<span class="st">&quot;WI&quot;</span>,<span class="dv">12</span>)</a>
<a class="sourceLine" id="cb3982-2" data-line-number="2">states[<span class="dv">10</span>]=<span class="st">&quot;IA&quot;</span></a>
<a class="sourceLine" id="cb3982-3" data-line-number="3">states[<span class="dv">11</span>]=<span class="st">&quot;MN&quot;</span> </a>
<a class="sourceLine" id="cb3982-4" data-line-number="4">states[<span class="dv">12</span>]=<span class="st">&quot;IL&quot;</span></a>
<a class="sourceLine" id="cb3982-5" data-line-number="5">cst=<span class="kw">str_c</span>(cities,<span class="st">&quot; &quot;</span>,states)</a>
<a class="sourceLine" id="cb3982-6" data-line-number="6">cst</a></code></pre></div>
<pre><code>##  [1] &quot;Appleton WI&quot;      &quot;Beloit WI&quot;        &quot;Fort.Atkinson WI&quot;
##  [4] &quot;Madison WI&quot;       &quot;Marshfield WI&quot;    &quot;Milwaukee WI&quot;    
##  [7] &quot;Monroe WI&quot;        &quot;Superior WI&quot;      &quot;Wausau WI&quot;       
## [10] &quot;Dubuque IA&quot;       &quot;St.Paul MN&quot;       &quot;Chicago IL&quot;</code></pre>
<p>And then I look them up. I don’t want Google to tell me that I have
done too many lookups, so I look them up first and save the results,
like this:</p>
<div class="sourceCode" id="cb3984"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb3984-1" data-line-number="1"><span class="kw">tibble</span>(cst) <span class="op">%&gt;%</span><span class="st"> </span></a>
<a class="sourceLine" id="cb3984-2" data-line-number="2">ggmap<span class="op">::</span><span class="kw">mutate_geocode</span>(cst) -&gt;<span class="st"> </span>g</a></code></pre></div>
<pre><code>## Source : https://maps.googleapis.com/maps/api/geocode/json?address=Appleton+WI&amp;key=xxx-Mj1-zNBW4GTnXNAYdGQJDNXU</code></pre>
<pre><code>## Source : https://maps.googleapis.com/maps/api/geocode/json?address=Beloit+WI&amp;key=xxx-Mj1-zNBW4GTnXNAYdGQJDNXU</code></pre>
<pre><code>## Source : https://maps.googleapis.com/maps/api/geocode/json?address=Fort.Atkinson+WI&amp;key=xxx-Mj1-zNBW4GTnXNAYdGQJDNXU</code></pre>
<pre><code>## Source : https://maps.googleapis.com/maps/api/geocode/json?address=Madison+WI&amp;key=xxx-Mj1-zNBW4GTnXNAYdGQJDNXU</code></pre>
<pre><code>## Source : https://maps.googleapis.com/maps/api/geocode/json?address=Marshfield+WI&amp;key=xxx-Mj1-zNBW4GTnXNAYdGQJDNXU</code></pre>
<pre><code>## Source : https://maps.googleapis.com/maps/api/geocode/json?address=Milwaukee+WI&amp;key=xxx-Mj1-zNBW4GTnXNAYdGQJDNXU</code></pre>
<pre><code>## Source : https://maps.googleapis.com/maps/api/geocode/json?address=Monroe+WI&amp;key=xxx-Mj1-zNBW4GTnXNAYdGQJDNXU</code></pre>
<pre><code>## Source : https://maps.googleapis.com/maps/api/geocode/json?address=Superior+WI&amp;key=xxx-Mj1-zNBW4GTnXNAYdGQJDNXU</code></pre>
<pre><code>## Source : https://maps.googleapis.com/maps/api/geocode/json?address=Wausau+WI&amp;key=xxx-Mj1-zNBW4GTnXNAYdGQJDNXU</code></pre>
<pre><code>## Source : https://maps.googleapis.com/maps/api/geocode/json?address=Dubuque+IA&amp;key=xxx-Mj1-zNBW4GTnXNAYdGQJDNXU</code></pre>
<pre><code>## Source : https://maps.googleapis.com/maps/api/geocode/json?address=St.Paul+MN&amp;key=xxx-Mj1-zNBW4GTnXNAYdGQJDNXU</code></pre>
<pre><code>## Source : https://maps.googleapis.com/maps/api/geocode/json?address=Chicago+IL&amp;key=xxx-Mj1-zNBW4GTnXNAYdGQJDNXU</code></pre>
<div class="sourceCode" id="cb3997"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb3997-1" data-line-number="1">g</a></code></pre></div>
<pre><code>## # A tibble: 12 x 3
##    cst                lon   lat
##    &lt;chr&gt;            &lt;dbl&gt; &lt;dbl&gt;
##  1 Appleton WI      -88.4  44.3
##  2 Beloit WI        -89.0  42.5
##  3 Fort.Atkinson WI -88.8  42.9
##  4 Madison WI       -89.4  43.1
##  5 Marshfield WI    -90.2  44.7
##  6 Milwaukee WI     -87.9  43.0
##  7 Monroe WI        -89.6  42.6
##  8 Superior WI      -92.1  46.7
##  9 Wausau WI        -89.6  45.0
## 10 Dubuque IA       -90.7  42.5
## 11 St.Paul MN       -93.1  45.0
## 12 Chicago IL       -87.6  41.9</code></pre>
<p>What are the extreme corners of these?</p>
<div class="sourceCode" id="cb3999"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb3999-1" data-line-number="1"><span class="kw">range</span>(g<span class="op">$</span>lon)</a></code></pre></div>
<pre><code>## [1] -93.08996 -87.62980</code></pre>
<div class="sourceCode" id="cb4001"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb4001-1" data-line-number="1"><span class="kw">range</span>(g<span class="op">$</span>lat)</a></code></pre></div>
<pre><code>## [1] 41.87811 46.72077</code></pre>
<p>or even</p>
<div class="sourceCode" id="cb4003"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb4003-1" data-line-number="1">g <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">select</span>(lat,lon) <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb4003-2" data-line-number="2"><span class="kw">map_df</span>(range)</a></code></pre></div>
<pre><code>## # A tibble: 2 x 2
##     lat   lon
##   &lt;dbl&gt; &lt;dbl&gt;
## 1  41.9 -93.1
## 2  46.7 -87.6</code></pre>
<p>(<code>range</code> in R produces the two extreme values, not the
difference between the highest and lowest, which is what you might
think of as a “range”.)</p>
<p>We don’t
get exactly the corners we ask for, since the map always comes out in the same
proportions (we could ask for a long skinny map, but we’ll always get
a rectangular one that fills the page), and also Google Maps converts
the corners into a centre and zoom. I had to tinker with the numbers
below, since on my first attempt the map zoomed in too much.
I also asked for a “roadmap” to maximize the number of places marked
on there.</p>
<p>So:</p>
<div class="sourceCode" id="cb4005"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb4005-1" data-line-number="1">wisc.map<span class="fl">.2</span>=<span class="kw">get_map</span>(<span class="dt">location=</span><span class="kw">c</span>(<span class="op">-</span><span class="dv">94</span>,<span class="fl">41.8</span>,<span class="op">-</span><span class="dv">87</span>,<span class="fl">46.8</span>),<span class="dt">maptype=</span><span class="st">&quot;roadmap&quot;</span>)</a></code></pre></div>
<pre><code>## Warning: bounding box given to google - spatial extent only approximate.</code></pre>
<div class="sourceCode" id="cb4007"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb4007-1" data-line-number="1"><span class="kw">ggmap</span>(wisc.map<span class="fl">.2</span>)</a></code></pre></div>
<p><img src="23-mds_files/figure-html/lhsdljhadkfj-1.png" width="576"  /></p>
<p>This came out about right.</p>
<p>Now we need to mark our 12 cities on the map. This is a
<code>ggplot</code> map, so the right syntax is as below.</p>
<div class="sourceCode" id="cb4008"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb4008-1" data-line-number="1"><span class="kw">ggmap</span>(wisc.map<span class="fl">.2</span>)<span class="op">+</span><span class="kw">geom_point</span>(<span class="dt">data=</span>g, <span class="kw">aes</span>(<span class="dt">x=</span>lon,<span class="dt">y=</span>lat))</a></code></pre></div>
<p><img src="23-mds_files/figure-html/sldkhdlf-1.png" width="672"  /></p>
<p>There’s a slight weirdness in that <code>ggmap</code> only takes a map,
not a data frame or an <code>aes</code>, so those go in
<code>geom_point</code> or whatever you’re using.</p>
<p>We <em>just</em> squeezed all our cities onto the map. The city
southwest of Wausau is Marshfield, the one between Madison and
Milwaukee is Fort Atkinson, and the two east of Dubuque along the
southern border of Wisconsin are Monroe and Beloit. The one <em>way</em>
up at the top is Superior.</p>
<p>After that long diversion, we come to:</p>
<ol start="7" style="list-style-type: lower-alpha">
<li>Discuss how the map that came out of the multidimensional
scaling corresponds to the actual (Google) map.</li>
</ol>
<p>Solution</p>
<p>Let’s pick a few places from the actual map, and make a table of
where they are on the actual map and the <code>cmdscale</code> map:</p>
<pre><code>
 Place        Real              Cmdscale       
----------------------------------------------
 Superior     northwest         central east   
 St. Paul     central west      southeast      
 Dubuque      central south     central south  
 Chicago      southeast         central west   
 Appleton     central east      central north  

</code></pre>
<p>This is a bit tricky. Dubuque is the only one in the right place, and
the others that were west have become east and vice versa. So I think
there is a flipping across a line going through Dubuque. That seems to
be the most important thing; if you imagine the other points being
flipped across a line going north-south through Dubuque, they all end
up in about the right place. There might be a little rotation as well,
but I’ll call that close enough.</p>
<p>(For you, any comment along the lines of “flipped around this line”
or “rotated about this much” that seems to describe what has happened, is
fine.)</p>
<ol start="8" style="list-style-type: lower-alpha">
<li>Calculate something that demonstrates that a one-dimensional
map of the cities is a much worse representation than the
two-dimensional one that we made before. (I’m planning to get to this
in class, but if we skip it, don’t worry about this part.)</li>
</ol>
<p>Solution</p>
<p>Run again with <code>eig=T</code> and take a look at <code>GOF</code> (uppercase):</p>
<div class="sourceCode" id="cb4010"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb4010-1" data-line-number="1"><span class="kw">cmdscale</span>(d,<span class="dv">2</span>,<span class="dt">eig=</span>T)<span class="op">$</span>GOF</a></code></pre></div>
<pre><code>## [1] 0.9129333 0.9315871</code></pre>
<div class="sourceCode" id="cb4012"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb4012-1" data-line-number="1"><span class="kw">cmdscale</span>(d,<span class="dv">1</span>,<span class="dt">eig=</span>T)<span class="op">$</span>GOF</a></code></pre></div>
<pre><code>## [1] 0.7916925 0.8078690</code></pre>
<p>The goodness-of-fit of the two-dimensional solution is pretty
good,
<label for="tufte-mn-247" class="margin-toggle">⊕</label><input type="checkbox" id="tufte-mn-247" class="margin-toggle"><span class="marginnote">As it ought to be, since there is a real answer here: the cities <em>do</em> exist as locations in two dimensions, you ignore the curvature of the earth. The goodness of fit isn’t 100% because the roads bend a bit.</span>
but that of the one-dimensional solution (which arranges all the
cities along a line) is pretty awful in comparison.</p>
<p>How awful? Let’s find out. I should have saved it from just above, but
now I have to do it again. For the plot, <code>ones</code> is a string of
ones, as many as there are cities.</p>
<div class="sourceCode" id="cb4014"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb4014-1" data-line-number="1">ones=<span class="kw">rep</span>(<span class="dv">1</span>,<span class="dv">12</span>)</a>
<a class="sourceLine" id="cb4014-2" data-line-number="2">v=<span class="kw">cmdscale</span>(d,<span class="dv">1</span>,<span class="dt">eig=</span>T)</a>
<a class="sourceLine" id="cb4014-3" data-line-number="3">ddd =<span class="st"> </span><span class="kw">as_tibble</span>(v<span class="op">$</span>points) <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb4014-4" data-line-number="4"><span class="kw">mutate</span>(<span class="dt">one=</span>ones, <span class="dt">city=</span>cities)</a></code></pre></div>
<pre><code>## Warning: `as_tibble.matrix()` requires a matrix with column names or a `.name_repair` argument. Using compatibility `.name_repair`.
## This warning is displayed once per session.</code></pre>
<div class="sourceCode" id="cb4016"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb4016-1" data-line-number="1">ddd</a></code></pre></div>
<pre><code>## # A tibble: 12 x 3
##        V1   one city         
##     &lt;dbl&gt; &lt;dbl&gt; &lt;chr&gt;        
##  1  -13.4     1 Appleton     
##  2  -92.9     1 Beloit       
##  3  -74.1     1 Fort.Atkinson
##  4  -44.7     1 Madison      
##  5   80.6     1 Marshfield   
##  6 -103.      1 Milwaukee    
##  7  -74.7     1 Monroe       
##  8  279.      1 Superior     
##  9   79.2     1 Wausau       
## 10  -50.9     1 Dubuque      
## 11  199.      1 St.Paul      
## 12 -185.      1 Chicago</code></pre>
<p>(the one-column matrix of points didn’t have a name, so it acquired
the name <code>V1</code>), and the plot:</p>
<div class="sourceCode" id="cb4018"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb4018-1" data-line-number="1"><span class="kw">ggplot</span>(ddd,<span class="kw">aes</span>(<span class="dt">x=</span>one,<span class="dt">y=</span>V1,<span class="dt">label=</span>city))<span class="op">+</span></a>
<a class="sourceLine" id="cb4018-2" data-line-number="2"><span class="kw">geom_point</span>()<span class="op">+</span><span class="kw">geom_text_repel</span>()</a></code></pre></div>
<p><img src="23-mds_files/figure-html/unnamed-chunk-20-1.png" width="672"  /></p>
<p>The cities get mapped onto a line that goes northwest (top) to
southeast (bottom). This is not completely terrible, since there
aren’t really any cities in the northeast of the state, but it <em>is</em>
pretty awful.</p>
</div>
<div id="things-that-feel-similar-to-each-other" class="section level2">
<h2><span class="header-section-number">24.2</span> Things that feel similar to each other</h2>
<p>Which objects feel similar to one another and which ones
feel different? Can we draw them on a “map”? 30
subjects
<label for="tufte-mn-248" class="margin-toggle">⊕</label><input type="checkbox" id="tufte-mn-248" class="margin-toggle"><span class="marginnote">Probably students in a psychology course. You know how it goes.</span> were each
given 17 different objects to feel, for example “inner surface of pine bark”,
“rubber eraser” and
“nylon scouring pad”. The
subjects had to group the objects into a maximum of 8 groups such that
the objects within a group felt similar, and the ones in different
groups felt different.
<label for="tufte-mn-249" class="margin-toggle">⊕</label><input type="checkbox" id="tufte-mn-249" class="margin-toggle"><span class="marginnote">The maximum number of groups was to ensure that each subject actually <em>did</em> group some objects together, rather than saying that they all feel different.</span> A
dissimilarity matrix was formed by counting how many subjects put each
pair of objects into <em>different</em> groups, so that the
dissimilarity ranged from 0 (the objects were always put together in
the same group) to 30 (the objects were not put together into the same
group by any of the subjects).</p>
<p>The data are in
<a href="http://www.utsc.utoronto.ca/~butler/d29/stimuli.txt">link</a>.</p>
<ol style="list-style-type: lower-alpha">
<li>Look at the data, and read in the file appropriately. Do you
have something square in shape, apart from any columns of object
names? Do your columns have the same names as the objects?</li>
</ol>
<p>Solution</p>
<p>Looking at the file first, there are <em>no column names</em>. So we
have to tell <code>read_delim</code> that:</p>
<div class="sourceCode" id="cb4019"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb4019-1" data-line-number="1">my_url=<span class="st">&quot;http://www.utsc.utoronto.ca/~butler/d29/stimuli.txt&quot;</span></a>
<a class="sourceLine" id="cb4019-2" data-line-number="2">stimuli=<span class="kw">read_delim</span>(my_url,<span class="st">&quot; &quot;</span>,<span class="dt">col_names=</span>F)</a></code></pre></div>
<pre><code>## Parsed with column specification:
## cols(
##   X1 = col_character(),
##   X2 = col_double(),
##   X3 = col_double(),
##   X4 = col_double(),
##   X5 = col_double(),
##   X6 = col_double(),
##   X7 = col_double(),
##   X8 = col_double(),
##   X9 = col_double(),
##   X10 = col_double(),
##   X11 = col_double(),
##   X12 = col_double(),
##   X13 = col_double(),
##   X14 = col_double(),
##   X15 = col_double(),
##   X16 = col_double(),
##   X17 = col_double(),
##   X18 = col_double()
## )</code></pre>
<div class="sourceCode" id="cb4021"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb4021-1" data-line-number="1">stimuli</a></code></pre></div>
<pre><code>## # A tibble: 17 x 18
##    X1        X2    X3    X4    X5    X6    X7    X8    X9   X10   X11   X12
##    &lt;chr&gt;  &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt;
##  1 inner…     0    22    23    24    26    27    26    23    24    23    23
##  2 brick     22     0    27    27    27    29    29    28    16    18    28
##  3 cardb…    23    27     0    18    19    28    23    24    24    29    27
##  4 cork      24    27    18     0    15    28    25    26    28    28    20
##  5 rubbe…    26    27    19    15     0    28    20    27    24    27    24
##  6 felt      27    29    28    28    28     0    24    28    29    26    26
##  7 leath…    26    29    23    25    20    24     0    22    28    28    27
##  8 rigid…    23    28    24    26    27    28    22     0    27    29    29
##  9 veryf…    24    16    24    28    24    29    28    27     0    21    24
## 10 nylon…    23    18    29    28    27    26    28    29    21     0    22
## 11 cellu…    23    28    27    20    24    26    27    29    24    22     0
## 12 woven…    18    25    28    27    25    29    26    27    26    16    19
## 13 block…    23    24    21    10    19    28    25    25    25    25    21
## 14 ungla…    21    10    26    26    24    29    29    25    12    24    26
## 15 velvet    28    29    28    28    29     4    24    29    29    27    27
## 16 waxpa…    24    28    24    28    24    28    21    12    29    29    29
## 17 gloss…    22    27    23    29    28    29    20    13    27    28    27
## # … with 6 more variables: X13 &lt;dbl&gt;, X14 &lt;dbl&gt;, X15 &lt;dbl&gt;, X16 &lt;dbl&gt;,
## #   X17 &lt;dbl&gt;, X18 &lt;dbl&gt;</code></pre>
<p>I have 17 rows and 18 columns, but one of the columns is the column of
object names. So I really do have the same number of rows and columns
of dissimilarities: that is, it <em>is</em> square in shape apart from
the names.</p>
<p>The columns <em>do not</em> have the same names as the
objects; R has used the <code>X1, X2, ...</code> names that it uses when
you do not have column headers.</p>
<p>I could have supplied the object names to <code>col_names</code>, but
that is a lot more work than what we do below.</p>
<ol start="2" style="list-style-type: lower-alpha">
<li>Obtain the names of the objects. Note that they are rather
long.</li>
</ol>
<p>Solution</p>
<p>The object names are in the first column, <code>X1</code>, of the data frame:</p>
<div class="sourceCode" id="cb4023"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb4023-1" data-line-number="1">objects=stimuli<span class="op">$</span>X1</a>
<a class="sourceLine" id="cb4023-2" data-line-number="2">objects</a></code></pre></div>
<pre><code>##  [1] &quot;innersurfaceofpinebark&quot; &quot;brick&quot;                 
##  [3] &quot;cardboard&quot;              &quot;cork&quot;                  
##  [5] &quot;rubbereraser&quot;           &quot;felt&quot;                  
##  [7] &quot;leatherwallet&quot;          &quot;rigidplasticsheet&quot;     
##  [9] &quot;veryfinesandpaper&quot;      &quot;nylonscouringpad&quot;      
## [11] &quot;cellulosekitchensponge&quot; &quot;wovenstraw&quot;            
## [13] &quot;blockofstyrofoam&quot;       &quot;unglazedceramictile&quot;   
## [15] &quot;velvet&quot;                 &quot;waxpaper&quot;              
## [17] &quot;glossypaintedwood&quot;</code></pre>
<p>I’m saving these for later.</p>
<ol start="3" style="list-style-type: lower-alpha">
<li>Set the column names of your data frame to be your object
names, using <code>names</code>. Before you rush to do that, figure out
how many column names you need, and supply values for any extra
ones. Check that your data frame now has the right column names.</li>
</ol>
<p>Solution</p>
<p>I have 18 columns to name (including the column of object names),
but only 17 names, so I need to supply an extra one:</p>
<div class="sourceCode" id="cb4025"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb4025-1" data-line-number="1"><span class="kw">names</span>(stimuli)=<span class="kw">c</span>(<span class="st">&quot;object&quot;</span>,objects)</a>
<a class="sourceLine" id="cb4025-2" data-line-number="2">stimuli</a></code></pre></div>
<pre><code>## # A tibble: 17 x 18
##    object innersurfaceofp… brick cardboard  cork rubbereraser  felt
##    &lt;chr&gt;             &lt;dbl&gt; &lt;dbl&gt;     &lt;dbl&gt; &lt;dbl&gt;        &lt;dbl&gt; &lt;dbl&gt;
##  1 inner…                0    22        23    24           26    27
##  2 brick                22     0        27    27           27    29
##  3 cardb…               23    27         0    18           19    28
##  4 cork                 24    27        18     0           15    28
##  5 rubbe…               26    27        19    15            0    28
##  6 felt                 27    29        28    28           28     0
##  7 leath…               26    29        23    25           20    24
##  8 rigid…               23    28        24    26           27    28
##  9 veryf…               24    16        24    28           24    29
## 10 nylon…               23    18        29    28           27    26
## 11 cellu…               23    28        27    20           24    26
## 12 woven…               18    25        28    27           25    29
## 13 block…               23    24        21    10           19    28
## 14 ungla…               21    10        26    26           24    29
## 15 velvet               28    29        28    28           29     4
## 16 waxpa…               24    28        24    28           24    28
## 17 gloss…               22    27        23    29           28    29
## # … with 11 more variables: leatherwallet &lt;dbl&gt;, rigidplasticsheet &lt;dbl&gt;,
## #   veryfinesandpaper &lt;dbl&gt;, nylonscouringpad &lt;dbl&gt;,
## #   cellulosekitchensponge &lt;dbl&gt;, wovenstraw &lt;dbl&gt;,
## #   blockofstyrofoam &lt;dbl&gt;, unglazedceramictile &lt;dbl&gt;, velvet &lt;dbl&gt;,
## #   waxpaper &lt;dbl&gt;, glossypaintedwood &lt;dbl&gt;</code></pre>
<ol start="4" style="list-style-type: lower-alpha">
<li><a name="part:distances">*</a><br />
Convert your data frame into a distance object. Take a look at the
(rather long) result.</li>
</ol>
<p>Solution</p>
<p>This is <code>as.dist</code>, since we have distances
(dissimilarities) already. Don’t forget to take off the first column!</p>
<div class="sourceCode" id="cb4027"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb4027-1" data-line-number="1">d =<span class="st"> </span>stimuli <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">select</span>(<span class="op">-</span><span class="dv">1</span>) <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">as.dist</span>()</a></code></pre></div>
<p>I can try and show it all here, tiny, but even then it’s long because
the column names are long:</p>
<div class="sourceCode" id="cb4028"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb4028-1" data-line-number="1">w=<span class="kw">getOption</span>(<span class="st">&quot;width&quot;</span>)</a>
<a class="sourceLine" id="cb4028-2" data-line-number="2"><span class="kw">options</span>(<span class="dt">width=</span><span class="dv">132</span>)</a>
<a class="sourceLine" id="cb4028-3" data-line-number="3">d</a></code></pre></div>
<pre><code>##                        innersurfaceofpinebark brick cardboard cork rubbereraser felt leatherwallet rigidplasticsheet
## brick                                      22                                                                       
## cardboard                                  23    27                                                                 
## cork                                       24    27        18                                                       
## rubbereraser                               26    27        19   15                                                  
## felt                                       27    29        28   28           28                                     
## leatherwallet                              26    29        23   25           20   24                                
## rigidplasticsheet                          23    28        24   26           27   28            22                  
## veryfinesandpaper                          24    16        24   28           24   29            28                27
## nylonscouringpad                           23    18        29   28           27   26            28                29
## cellulosekitchensponge                     23    28        27   20           24   26            27                29
## wovenstraw                                 18    25        28   27           25   29            26                27
## blockofstyrofoam                           23    24        21   10           19   28            25                25
## unglazedceramictile                        21    10        26   26           24   29            29                25
## velvet                                     28    29        28   28           29    4            24                29
## waxpaper                                   24    28        24   28           24   28            21                12
## glossypaintedwood                          22    27        23   29           28   29            20                13
##                        veryfinesandpaper nylonscouringpad cellulosekitchensponge wovenstraw blockofstyrofoam unglazedceramictile
## brick                                                                                                                           
## cardboard                                                                                                                       
## cork                                                                                                                            
## rubbereraser                                                                                                                    
## felt                                                                                                                            
## leatherwallet                                                                                                                   
## rigidplasticsheet                                                                                                               
## veryfinesandpaper                                                                                                               
## nylonscouringpad                      21                                                                                        
## cellulosekitchensponge                24               22                                                                       
## wovenstraw                            26               16                     19                                                
## blockofstyrofoam                      25               25                     21         26                                     
## unglazedceramictile                   12               24                     26         26               25                    
## velvet                                29               27                     27         28               29                  29
## waxpaper                              29               29                     29         27               26                  28
## glossypaintedwood                     27               28                     27         25               29                  26
##                        velvet waxpaper
## brick                                 
## cardboard                             
## cork                                  
## rubbereraser                          
## felt                                  
## leatherwallet                         
## rigidplasticsheet                     
## veryfinesandpaper                     
## nylonscouringpad                      
## cellulosekitchensponge                
## wovenstraw                            
## blockofstyrofoam                      
## unglazedceramictile                   
## velvet                                
## waxpaper                   27         
## glossypaintedwood          26       12</code></pre>
<div class="sourceCode" id="cb4030"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb4030-1" data-line-number="1"><span class="kw">options</span>(<span class="dt">width=</span>w)</a></code></pre></div>
<p>The stuff with <code>width</code> was to make it display lots of columns,
and then setting it back afterwards so as not to mess things up later.
If
you try and take <code>head</code> of this, you’ll lose the structure. I
don’t know of a good way to display part of one of these.</p>
<ol start="5" style="list-style-type: lower-alpha">
<li>Obtain and plot a (metric) multidimensional scaling map of
these data. Label the points with the name of the
object they represent. (Note that
<code>geom_text_repel</code> has an option <code>size</code> that controls
the size of the text.)</li>
</ol>
<p>Solution</p>
<p>This is the procedure. Talking about it is coming in a minute.</p>
<div class="sourceCode" id="cb4031"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb4031-1" data-line-number="1">d<span class="fl">.1</span>=<span class="kw">cmdscale</span>(d,<span class="dv">2</span>)</a>
<a class="sourceLine" id="cb4031-2" data-line-number="2"><span class="kw">data.frame</span>(d<span class="fl">.1</span>,<span class="dt">stim=</span>objects) <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb4031-3" data-line-number="3"><span class="kw">ggplot</span>(<span class="kw">aes</span>(<span class="dt">x=</span>X1,<span class="dt">y=</span>X2,<span class="dt">label=</span>stim))<span class="op">+</span><span class="kw">geom_point</span>()<span class="op">+</span></a>
<a class="sourceLine" id="cb4031-4" data-line-number="4"><span class="kw">geom_text_repel</span>(<span class="dt">size=</span><span class="dv">2</span>)</a></code></pre></div>
<p><img src="23-mds_files/figure-html/unnamed-chunk-26-1.png" width="672"  /></p>
<p><code>cmdscale</code> gets the coordinates to plot, then we plot them, and
then we place the object names next to the points. I’m not
quite sure what the scale is for <code>size</code>, but <code>size=2</code>
worked for me here, making the text a bit smaller (so that the labels
don’t overlap), but not so small that you can’t read it. You’ll
probably have to experiment to find a <code>size</code> that you like.</p>
<p>If you forget the <code>2</code> after the distance matrix in
<code>cmdscale</code>, you’ll get a two-dimensional solution anyway (since
two dimensions is the default). The output is an array of coordinates
in two dimensions:</p>
<div class="sourceCode" id="cb4032"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb4032-1" data-line-number="1">d<span class="fl">.1</span></a></code></pre></div>
<pre><code>##                               [,1]       [,2]
## innersurfaceofpinebark  -2.7066290   1.694420
## brick                  -12.2011332   5.147970
## cardboard                3.8630322  -9.322759
## cork                    -0.8424358 -14.884926
## rubbereraser             0.1676463 -11.733873
## felt                     5.1803473   9.328562
## leatherwallet           10.4636668  -1.016525
## rigidplasticsheet       11.0208731   1.201504
## veryfinesandpaper      -11.0869483   2.800988
## nylonscouringpad       -10.4469053   7.232787
## cellulosekitchensponge  -5.3886609  -2.770991
## wovenstraw              -5.2762142   3.836948
## blockofstyrofoam        -2.9950151 -11.927717
## unglazedceramictile    -10.5902291   2.926805
## velvet                   6.3768882  10.477972
## waxpaper                13.1702265   1.677039
## glossypaintedwood       11.2914904   5.331796</code></pre>
<p>I note that any map that is the same as this apart from rotation and
reflection is also fine (since the distances will be the same). I saw
a lot of maps that were like mine but upside down (with <code>cork</code>
at the top).
<label for="tufte-mn-250" class="margin-toggle">⊕</label><input type="checkbox" id="tufte-mn-250" class="margin-toggle"><span class="marginnote">I lie. Last year, <em>I</em> got cork at the top, and a lot of other people got cork at the bottom as you see here.</span> No problem there.</p>
<ol start="6" style="list-style-type: lower-alpha">
<li>Find a pair of objects that are close together on your
plot. Look back at your answer to part~(<a href="#part:distances">here</a>): is
the distance between those objects small? Explain briefly.</li>
</ol>
<p>Solution</p>
<p>I don’t mind (much) which objects you pick (as long as they are
reasonably close together). Find the actual distance between them
from what I called <code>d</code> in part~(<a href="#part:distances">here</a>). Some
possibilities:</p>
<ul>
<li><p>Felt and velvet, Distance 4.</p></li>
<li><p>Block of styrofoam and rubber eraser. Distance 19 (not that
small, but one of the smaller ones).</p></li>
<li><p>Rigid plastic sheet and
wax paper. Distance 12. Smallish.</p></li>
<li><p>unglazed ceramic
tile
<label for="tufte-mn-251" class="margin-toggle">⊕</label><input type="checkbox" id="tufte-mn-251" class="margin-toggle"><span class="marginnote">The first association that <em>unglazed</em> made for me was <em>donut</em>!</span> and very fine sandpaper. Distance 12. Smallish.</p></li>
</ul>
<p>There won’t be a perfect relationship between distance in the
distance matrix and on the map. In this case, there is an upper
limit on distance (30, because 30 people rated the objects for
similarity) and that upper limit is approached by many of the
distances. (This suggests that non-metric multidimensional
scaling, that just reproduces the order of the distances, might be
a better idea for these data.) If objects A and B, and also B and
C, are each close to 30 apart, then objects A and C will also be
close to 30 apart, and that constrains them to be nearly in a
triangle on the map.
There are some 10s in the distance matrix,
for example between block of styrofoam and cork, and also
between unglazed ceramic tile and brick; these are a bit
further apart on the map, but still close.</p>
<ol start="7" style="list-style-type: lower-alpha">
<li>Obtain a measure of goodness of fit for this
multidimensional scaling map.</li>
</ol>
<p>Solution</p>
<p>This means fitting again, but this time with <code>eig=T</code>, and
pulling out the thing called <code>GOF</code>. You can omit the 2,
since that’s the default 2 dimensions:</p>
<div class="sourceCode" id="cb4034"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb4034-1" data-line-number="1">d<span class="fl">.2</span>=<span class="kw">cmdscale</span>(d,<span class="dv">2</span>,<span class="dt">eig=</span>T)</a>
<a class="sourceLine" id="cb4034-2" data-line-number="2">d<span class="fl">.2</span><span class="op">$</span>GOF</a></code></pre></div>
<pre><code>## [1] 0.4019251 0.4110603</code></pre>
<p>I didn’t ask you to comment on this, but the adjective that came to my
mind was “disappointing”. I think that’s to do with the
upper-limit-30 thing again. Also, this time (unlike with Wisconsin)
there was no “right answer”, so maybe it just isn’t going to be very
good. If you looked at several pairs of points above, you might have
noticed that the correspondence between map distance and actual
distance isn’t very good; this is the same issue.</p>
<p>I was curious about whether 3 dimensions would be any better:</p>
<div class="sourceCode" id="cb4036"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb4036-1" data-line-number="1">d<span class="fl">.2</span>a=<span class="kw">cmdscale</span>(d,<span class="dv">3</span>,<span class="dt">eig=</span>T)</a>
<a class="sourceLine" id="cb4036-2" data-line-number="2">d<span class="fl">.2</span>a<span class="op">$</span>GOF</a></code></pre></div>
<pre><code>## [1] 0.5775841 0.5907117</code></pre>
<p>That is quite a bit better. The problem with this, though, is that we
need something like <code>rgl</code> to explore it with.</p>
<ol start="8" style="list-style-type: lower-alpha">
<li>Obtain a cluster analysis for the same data, using Ward’s
method. Obtain a dendrogram. What seems to be an appropriate number
of clusters? Mark them on your dendrogram too.</li>
</ol>
<p>Solution</p>
<p>This seems to be a throwback to last week, but I have my reasons,
which you’ll see in a moment:</p>
<div class="sourceCode" id="cb4038"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb4038-1" data-line-number="1">d<span class="fl">.3</span>=<span class="kw">hclust</span>(d,<span class="dt">method=</span><span class="st">&quot;ward.D&quot;</span>)</a>
<a class="sourceLine" id="cb4038-2" data-line-number="2"><span class="kw">plot</span>(d<span class="fl">.3</span>)</a></code></pre></div>
<p><img src="23-mds_files/figure-html/unnamed-chunk-30-1.png" width="672"  /></p>
<p>That looks like 5 clusters to me (chopping the tree at a height of
30). Drawing them:</p>
<div class="sourceCode" id="cb4039"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb4039-1" data-line-number="1"><span class="kw">plot</span>(d<span class="fl">.3</span>)</a>
<a class="sourceLine" id="cb4039-2" data-line-number="2"><span class="kw">rect.hclust</span>(d<span class="fl">.3</span>,<span class="dv">5</span>)</a></code></pre></div>
<p><img src="23-mds_files/figure-html/unnamed-chunk-31-1.png" width="672"  /></p>
<ol style="list-style-type: lower-roman">
<li>Discuss as briefly as seems reasonable whether your
clusters tell the same story as the map that came from
multidimensional scaling. (There were only three marks for this, so you
don’t need to go overboard.) Optionally, think about creating a plot
that will make it easier to see the correspondence between your
clusters and the MDS map.</li>
</ol>
<p>Solution</p>
<p>I would take my clusters and think about whether the objects in
them are (a) close together on the map and (b) distinct from other
objects on the map. Working from left to right of my dendrogram:</p>
<ul>
<li><p>Together at the bottom of the plot.</p></li>
<li><p>Together at the top left.</p></li>
<li><p>Together at the top left, but rather mixed up with the
previous cluster (in particular, <code>nylonscouringpad</code> looks as if it
belongs in the previous cluster).</p></li>
<li><p>Together at the top of the plot.</p></li>
<li><p>Together at the top right.</p></li>
</ul>
<p>If you had a different number of clusters, work with what you
have, and if you have done that, you’ll be good. My general
conclusion from the above is that my five clusters are mostly
distinct from each other, but the MDS map really only has
four. (If you look at the dendrogram, the two clusters that are
not really distinct from each other were the last ones to be split.)
This is a lot more detail than you need. What I want to see is
some kind of association of clusters with (hopefully) nearby
points on the map, some kind of discussion of whether the clusters
are really distinct groupings on the map, and a sense of whether
you feel the clusters are consistent with what appears on the map.
Extra: this is where I have to say I cheated. I thought this would be
hard to do by trying to match those names in the clusters
with the ones on the MDS map. So I put myself through some
short-term R coding pain for some substantial long-term gain.
I was thinking, “can I extract the clusters from this analysis, and plot them on the MDS map in different colours?” That
would go like this:</p>
<div class="sourceCode" id="cb4040"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb4040-1" data-line-number="1">clusters=<span class="kw">cutree</span>(d<span class="fl">.3</span>,<span class="dv">5</span>)</a>
<a class="sourceLine" id="cb4040-2" data-line-number="2"><span class="kw">data.frame</span>(d<span class="fl">.1</span>,<span class="dt">names=</span>stimuli[,<span class="dv">1</span>],<span class="dt">cluster=</span><span class="kw">factor</span>(clusters)) <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb4040-3" data-line-number="3"><span class="kw">ggplot</span>(<span class="kw">aes</span>(<span class="dt">x=</span>X1,<span class="dt">y=</span>X2,<span class="dt">label=</span>objects,<span class="dt">colour=</span>cluster))<span class="op">+</span></a>
<a class="sourceLine" id="cb4040-4" data-line-number="4"><span class="kw">geom_point</span>()<span class="op">+</span></a>
<a class="sourceLine" id="cb4040-5" data-line-number="5"><span class="kw">geom_text_repel</span>(<span class="dt">size=</span><span class="dv">2</span>)</a></code></pre></div>
<p><img src="23-mds_files/figure-html/unnamed-chunk-32-1.png" width="672"  /></p>
<p>The first line obtains the clusters as numbers, which I then had to
turn into a factor (to make the plot different colours).
I copied the rest from
above, and then I added to them, colouring the points according to
what cluster they belonged to. Three of my “rough” objects have
broken off into a cluster of their own; they are, kind of, in their
own little area on the map.</p>
<p>Another, non-graphical, way of doing this is to list the MDS coordinates
along with the clusters, probably sorted by cluster:</p>
<div class="sourceCode" id="cb4041"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb4041-1" data-line-number="1"><span class="kw">data.frame</span>(d<span class="fl">.1</span>,<span class="dt">object=</span>stimuli[,<span class="dv">1</span>],clusters) <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">arrange</span>(clusters)</a></code></pre></div>
<pre><code>##             X1         X2                 object clusters
## 1   -2.7066290   1.694420 innersurfaceofpinebark        1
## 2  -10.4469053   7.232787       nylonscouringpad        1
## 3   -5.3886609  -2.770991 cellulosekitchensponge        1
## 4   -5.2762142   3.836948             wovenstraw        1
## 5  -12.2011332   5.147970                  brick        2
## 6  -11.0869483   2.800988      veryfinesandpaper        2
## 7  -10.5902291   2.926805    unglazedceramictile        2
## 8    3.8630322  -9.322759              cardboard        3
## 9   -0.8424358 -14.884926                   cork        3
## 10   0.1676463 -11.733873           rubbereraser        3
## 11  -2.9950151 -11.927717       blockofstyrofoam        3
## 12   5.1803473   9.328562                   felt        4
## 13   6.3768882  10.477972                 velvet        4
## 14  10.4636668  -1.016525          leatherwallet        5
## 15  11.0208731   1.201504      rigidplasticsheet        5
## 16  13.1702265   1.677039               waxpaper        5
## 17  11.2914904   5.331796      glossypaintedwood        5</code></pre>
<p>Then you can think about what makes the clusters different in terms of
<code>X1</code> and <code>X2</code>. For me, clusters 1 and 2 are kind of
mixed up, with <code>X1</code> and (usually) <code>X2</code> negative; cluster
3 has strongly positive <code>X2</code>; cluster 4 has very
<em>negative</em> <code>X2</code>;
<label for="tufte-mn-252" class="margin-toggle">⊕</label><input type="checkbox" id="tufte-mn-252" class="margin-toggle"><span class="marginnote">Oxford semicolon, for the grammar mavens among you.</span>
and cluster 5 has strongly positive <code>X1</code>.</p>
<p>I wonder whether our three-dimensional solution distinguishes clusters
1 and 2 at all? Same approach again:</p>
<div class="sourceCode" id="cb4043"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb4043-1" data-line-number="1">save<span class="fl">.3</span>d =<span class="st"> </span><span class="kw">data.frame</span>(d<span class="fl">.2</span>a<span class="op">$</span>points,objects,clusters) <span class="op">%&gt;%</span><span class="st"> </span></a>
<a class="sourceLine" id="cb4043-2" data-line-number="2"><span class="kw">arrange</span>(clusters) </a>
<a class="sourceLine" id="cb4043-3" data-line-number="3">save<span class="fl">.3</span>d  </a></code></pre></div>
<pre><code>##             X1         X2          X3                objects clusters
## 1   -2.7066290   1.694420   4.1176385 innersurfaceofpinebark        1
## 2  -10.4469053   7.232787  -1.9720211       nylonscouringpad        1
## 3   -5.3886609  -2.770991  -6.8039573 cellulosekitchensponge        1
## 4   -5.2762142   3.836948  -0.3083513             wovenstraw        1
## 5  -12.2011332   5.147970   5.9802631                  brick        2
## 6  -11.0869483   2.800988   4.9686770      veryfinesandpaper        2
## 7  -10.5902291   2.926805   7.2124679    unglazedceramictile        2
## 8    3.8630322  -9.322759   1.2376174              cardboard        3
## 9   -0.8424358 -14.884926  -5.6157998                   cork        3
## 10   0.1676463 -11.733873  -2.3880857           rubbereraser        3
## 11  -2.9950151 -11.927717  -2.9877666       blockofstyrofoam        3
## 12   5.1803473   9.328562 -15.2730895                   felt        4
## 13   6.3768882  10.477972 -14.1837552                 velvet        4
## 14  10.4636668  -1.016525  -1.9005177          leatherwallet        5
## 15  11.0208731   1.201504  10.0016248      rigidplasticsheet        5
## 16  13.1702265   1.677039   8.2862272               waxpaper        5
## 17  11.2914904   5.331796   9.6288283      glossypaintedwood        5</code></pre>
<p>It looks as if the combo of negative <code>X1</code> and positive
<code>X3</code> distinguishes cluster 2 from cluster 1.</p>
<p>As I was writing this, I was thinking that we should throw the
coordinates and the <code>clusters</code> into a
<em>discriminant analysis</em>, to find out what distinguishes the
clusters. Which is way too weird, and therefore deserves to be
explored (with the three-dimensional solution, for example):</p>
<div class="sourceCode" id="cb4045"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb4045-1" data-line-number="1"><span class="kw">library</span>(MASS)</a></code></pre></div>
<pre><code>## 
## Attaching package: &#39;MASS&#39;</code></pre>
<pre><code>## The following object is masked from &#39;package:dplyr&#39;:
## 
##     select</code></pre>
<div class="sourceCode" id="cb4048"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb4048-1" data-line-number="1">save<span class="fl">.3</span>d.lda=<span class="kw">lda</span>(clusters<span class="op">~</span>X1<span class="op">+</span>X2<span class="op">+</span>X3,<span class="dt">data=</span>save<span class="fl">.3</span>d)</a>
<a class="sourceLine" id="cb4048-2" data-line-number="2">ppp=<span class="kw">predict</span>(save<span class="fl">.3</span>d.lda)</a></code></pre></div>
<p>I snuck a look at the output and
found that <code>LD3</code> is basically worthless, so I can plot
<code>LD1</code> against <code>LD2</code>, coloured by cluster:</p>
<div class="sourceCode" id="cb4049"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb4049-1" data-line-number="1"><span class="kw">data.frame</span>(ppp<span class="op">$</span>x,<span class="dt">cluster=</span><span class="kw">factor</span>(save<span class="fl">.3</span>d<span class="op">$</span>clusters)) <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb4049-2" data-line-number="2"><span class="kw">ggplot</span>(<span class="kw">aes</span>(<span class="dt">x=</span>LD1,<span class="dt">y=</span>LD2,<span class="dt">colour=</span>cluster))<span class="op">+</span></a>
<a class="sourceLine" id="cb4049-3" data-line-number="3"><span class="kw">geom_point</span>()</a></code></pre></div>
<p><img src="23-mds_files/figure-html/unnamed-chunk-36-1.png" width="672"  /></p>
<p>This says that the three-dimensional MDS <em>has</em> separated clusters
1 and 2, and if we were to plot <code>d.2a</code> in <code>rgl</code> and
rotate it the right way, we <em>would</em> be able to see a difference
between those two clusters as well. (They wouldn’t look mixed up as
they do on the two-dimensional map.)</p>
<p>So we can look at the three-dimensional map coordinates and the
discriminant analysis and ask “what distinguishes the clusters?”.
Map coordinates first. I need <code>points</code> since I ran
the scaling with <code>eig=T</code>:</p>
<div class="sourceCode" id="cb4050"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb4050-1" data-line-number="1">save<span class="fl">.3</span>d</a></code></pre></div>
<pre><code>##             X1         X2          X3                objects clusters
## 1   -2.7066290   1.694420   4.1176385 innersurfaceofpinebark        1
## 2  -10.4469053   7.232787  -1.9720211       nylonscouringpad        1
## 3   -5.3886609  -2.770991  -6.8039573 cellulosekitchensponge        1
## 4   -5.2762142   3.836948  -0.3083513             wovenstraw        1
## 5  -12.2011332   5.147970   5.9802631                  brick        2
## 6  -11.0869483   2.800988   4.9686770      veryfinesandpaper        2
## 7  -10.5902291   2.926805   7.2124679    unglazedceramictile        2
## 8    3.8630322  -9.322759   1.2376174              cardboard        3
## 9   -0.8424358 -14.884926  -5.6157998                   cork        3
## 10   0.1676463 -11.733873  -2.3880857           rubbereraser        3
## 11  -2.9950151 -11.927717  -2.9877666       blockofstyrofoam        3
## 12   5.1803473   9.328562 -15.2730895                   felt        4
## 13   6.3768882  10.477972 -14.1837552                 velvet        4
## 14  10.4636668  -1.016525  -1.9005177          leatherwallet        5
## 15  11.0208731   1.201504  10.0016248      rigidplasticsheet        5
## 16  13.1702265   1.677039   8.2862272               waxpaper        5
## 17  11.2914904   5.331796   9.6288283      glossypaintedwood        5</code></pre>
<p>and the business end of the LDA output:</p>
<div class="sourceCode" id="cb4052"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb4052-1" data-line-number="1">save<span class="fl">.3</span>d.lda<span class="op">$</span>svd</a></code></pre></div>
<pre><code>## [1] 12.593922  5.767636  3.007893</code></pre>
<div class="sourceCode" id="cb4054"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb4054-1" data-line-number="1">save<span class="fl">.3</span>d.lda<span class="op">$</span>scaling</a></code></pre></div>
<pre><code>##           LD1         LD2        LD3
## X1  0.5463715  0.22819994 0.03521147
## X2  0.4370065 -0.28250040 0.10269853
## X3 -0.3512713  0.09616153 0.19930252</code></pre>
<p>The plot said that cluster 2 was lowest of all on <code>LD1</code>, a bit
lower than cluster 1. What would make <code>LD1</code> small (negative)
would be if <code>X1</code> was small and <code>X2</code> and <code>X3</code> were
large. The cluster 2 observations are the smallest on <code>X1</code>
(smaller than cluster 1) and larger on <code>X3</code> than cluster 1. So
we <em>can</em> enumerate what makes clusters 1 and 2 different. The
plot of the first two <code>LD</code>s says, in fact, that under the
3-dimensional multidimensional scaling, all five groups are distinct.</p>
<p>A biplot would be another way to look at that:</p>
<div class="sourceCode" id="cb4056"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb4056-1" data-line-number="1"><span class="kw">ggbiplot</span>(save<span class="fl">.3</span>d.lda,<span class="dt">groups=</span><span class="kw">factor</span>(save<span class="fl">.3</span>d<span class="op">$</span>clusters))</a></code></pre></div>
<p><img src="23-mds_files/figure-html/unnamed-chunk-39-1.png" width="672"  /></p>
<p>Points on the right have <code>X1</code> and <code>X2</code> large, and
<code>X3</code> small (cluster 4, and to a lesser extent, cluster
5). Points on the left are the other way around. None of the arrows
point up or down really, but <code>X1</code> points up a bit and
<code>X2</code> down a bit, so points at the top of the plot are likely to
be high on <code>X1</code> and low on <code>X2</code>, like cluster 5.</p>
<p>Was that all confusing enough for you?</p>
<p>Anyway, the key to gaining some insight here is to find a way to
<em>combine</em> the
output from the cluster analysis and the multidimensional
scaling. That way you can see both in the same place, and see how they
compare.</p>
</div>
<div id="confusing-letters" class="section level2">
<h2><span class="header-section-number">24.3</span> Confusing letters</h2>
<p>Two researchers studied how often people mistook one letter
for another one. They did this by showing their subjects each
(uppercase) letter for a few milliseconds only, and asking them which
letter (out of a list) they just saw. The researchers obtain a
“confusion matrix” in which, for example, the W-Q entry is the total
of W’s taken as Q and Q’s taken as W. This confusion matrix is in
<a href="http://www.utsc.utoronto.ca/~butler/d29/letterrec.txt">link</a>. Note that
the confusions are actually <em>similarities</em> rather than
dissimilarities: a large number means that the two letters concerned
are easily confused, that is, similar. Similarities can be converted
to dissimilarities by subtracting them from a larger number than
anything in the table (that is, subtracting from 21 is good here).</p>
<ol style="list-style-type: lower-alpha">
<li>Read in the confusion matrix and convert it to
dissimilarities and then to a
<code>dist</code> object, displaying the <code>dist</code> object that you
obtain.</li>
</ol>
<p>Solution</p>
<p><code>read_table</code> to read in the data, having first noted that
we have aligned columns with spaces between:</p>
<div class="sourceCode" id="cb4057"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb4057-1" data-line-number="1">my_url=<span class="st">&quot;http://www.utsc.utoronto.ca/~butler/d29/letterrec.txt&quot;</span></a>
<a class="sourceLine" id="cb4057-2" data-line-number="2">letters=<span class="kw">read_table</span>(my_url)</a></code></pre></div>
<pre><code>## Warning: Missing column names filled in: &#39;X1&#39; [1]</code></pre>
<pre><code>## Parsed with column specification:
## cols(
##   X1 = col_character(),
##   C = col_double(),
##   D = col_double(),
##   G = col_double(),
##   H = col_double(),
##   M = col_double(),
##   N = col_double(),
##   Q = col_double(),
##   W = col_double()
## )</code></pre>
<div class="sourceCode" id="cb4060"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb4060-1" data-line-number="1">letters</a></code></pre></div>
<pre><code>## # A tibble: 8 x 9
##   X1        C     D     G     H     M     N     Q     W
##   &lt;chr&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt;
## 1 C         0     0     0     0     0     0     0     0
## 2 D         5     0     0     0     0     0     0     0
## 3 G        12     2     0     0     0     0     0     0
## 4 H         2     4     3     0     0     0     0     0
## 5 M         2     3     2    10     0     0     0     0
## 6 N         2     4     1    18    16     0     0     0
## 7 Q         9    20     9     1     2     8     0     0
## 8 W         1     5     2     5    18    13     4     0</code></pre>
<p>The first column didn’t have a heading, so <code>read_table</code> filled
in <code>X1</code> for it (there was data down below, so it needed to have
a name). This is in contrast to something like <code>read_delim</code>,
where you have to have as many headers as columns. In
<code>read_table</code>, you know where the headers have to be, so if any
are missing they can be filled in, but with <code>read_delim</code> you
don’t have that knowledge, so you have to have exactly the right
number of headers, one per data column exactly.</p>
<p>These are similarities, so convert to dissimilarities by subtracting
from 21. This is a shortcut way to do that, once you’ve gotten rid of
everything that is not numbers:</p>
<div class="sourceCode" id="cb4062"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb4062-1" data-line-number="1">letters <span class="op">%&gt;%</span><span class="st"> </span>dplyr<span class="op">::</span><span class="kw">select</span>(<span class="op">-</span>X1) -&gt;<span class="st"> </span>letters2</a>
<a class="sourceLine" id="cb4062-2" data-line-number="2">letters2=<span class="dv">21</span><span class="op">-</span>letters2</a>
<a class="sourceLine" id="cb4062-3" data-line-number="3">letters2</a></code></pre></div>
<pre><code>##    C  D  G  H  M  N  Q  W
## 1 21 21 21 21 21 21 21 21
## 2 16 21 21 21 21 21 21 21
## 3  9 19 21 21 21 21 21 21
## 4 19 17 18 21 21 21 21 21
## 5 19 18 19 11 21 21 21 21
## 6 19 17 20  3  5 21 21 21
## 7 12  1 12 20 19 13 21 21
## 8 20 16 19 16  3  8 17 21</code></pre>
<p>This looks weird, or at least the stuff above the diagonal does, but
<code>dist</code> works with the stuff <em>below</em> the diagonal (unless
you tell it otherwise), so all will be good.</p>
<p><code>as.dist</code> comes next:</p>
<div class="sourceCode" id="cb4064"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb4064-1" data-line-number="1">d=<span class="kw">as.dist</span>(letters2)</a>
<a class="sourceLine" id="cb4064-2" data-line-number="2">d</a></code></pre></div>
<pre><code>##    C  D  G  H  M  N  Q
## D 16                  
## G  9 19               
## H 19 17 18            
## M 19 18 19 11         
## N 19 17 20  3  5      
## Q 12  1 12 20 19 13   
## W 20 16 19 16  3  8 17</code></pre>
<p>This works because the letters that are confused are actually
column names of the data frame.</p>
<p>You can check (and probably should, at least for yourself) that the
distances in <code>d</code> correspond properly to the ones in
<code>letters</code>. For example, the letters C and G were confused 12
times, <span class="math inline">\(21-12=9\)</span>, and the entry for C and G in <code>d</code> is indeed
9.</p>
<p>Note that the actual confusion numbers were in the data file as the
bottom half of the matrix, with the top half being
zeroes. <code>as.dist</code> handled this with no problem. (You can check
the help for <code>as.dist</code> to find out how it deals with this kind
of thing.)</p>
<ol start="2" style="list-style-type: lower-alpha">
<li>Run a multidimensional scaling, with the default two
dimensions, on your <code>dist</code> object, and display the
results. (Making a graph is coming later.)</li>
</ol>
<p>Solution</p>
<p>This:</p>
<div class="sourceCode" id="cb4066"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb4066-1" data-line-number="1">d<span class="fl">.1</span>=<span class="kw">cmdscale</span>(d)</a>
<a class="sourceLine" id="cb4066-2" data-line-number="2">d<span class="fl">.1</span></a></code></pre></div>
<pre><code>##        [,1]       [,2]
## C  9.624942  4.7694928
## D  4.451129 -9.5740790
## G  8.863167  7.6643690
## H -6.817352  3.8283789
## M -8.917331  2.0059242
## N -7.926704 -0.8531024
## Q  7.875169 -5.9942901
## W -7.153020 -1.8466934</code></pre>
<p>Or you can do it with <code>eig=T</code>, which gets you some more information:</p>
<div class="sourceCode" id="cb4068"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb4068-1" data-line-number="1">d<span class="fl">.1</span>a=<span class="kw">cmdscale</span>(d,<span class="dt">eig=</span>T)</a>
<a class="sourceLine" id="cb4068-2" data-line-number="2">d<span class="fl">.1</span>a</a></code></pre></div>
<pre><code>## $points
##        [,1]       [,2]
## C  9.624942  4.7694928
## D  4.451129 -9.5740790
## G  8.863167  7.6643690
## H -6.817352  3.8283789
## M -8.917331  2.0059242
## N -7.926704 -0.8531024
## Q  7.875169 -5.9942901
## W -7.153020 -1.8466934
## 
## $eig
## [1]  4.930195e+02  2.319034e+02  1.399674e+02  5.318040e+01  4.054851e+01
## [6] -5.684342e-14 -1.539358e+01 -9.610062e+01
## 
## $x
## NULL
## 
## $ac
## [1] 0
## 
## $GOF
## [1] 0.6774262 0.7562157</code></pre>
<p>The most interesting thing here is the <code>GOF</code> at the bottom,
which is not that high (whichever one of the two values you take),
suggesting that the two-dimensional representation is not very
good. Further evidence for that is in <code>eig</code>, the
“eigenvalues”, which are about 493, 232, 140, 50, 40, 0 and some
negative ones, which suggests that three dimensions might be better
than two for representing the data, because the first <em>three</em>
eigenvalues seem noticeably bigger than the others. (This is the same
thinking as the <code>svd</code> or percent of trace in discriminant
analysis.) But that’s by the way: we’ll stick with two dimensions.</p>
<p>The important thing to remember is that if you go the <code>eig=T</code>
way, you have to pull out the points to plot from the thing called
<code>points</code>, so that you plot <code>d.1</code> itself but <code>d.1a$points</code>.</p>
<ol start="3" style="list-style-type: lower-alpha">
<li>Obtain a vector of the names of the letters that were
confused in this study.</li>
</ol>
<p>Solution</p>
<p>Easiest way is to pull out the first column of the data frame that
you read in from the file (if you can remember what it was called):</p>
<div class="sourceCode" id="cb4070"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb4070-1" data-line-number="1">letter_names=letters<span class="op">$</span>X1</a></code></pre></div>
<p>That silly column name <code>X1</code> that <code>read_table</code>
supplied.</p>
<p>Extra: You can even get the letter names from the thing I called <code>d</code>,
but I can’t remember how, so I have to cheat. I said that <code>d</code>
has a “print method”
<label for="tufte-mn-253" class="margin-toggle">⊕</label><input type="checkbox" id="tufte-mn-253" class="margin-toggle"><span class="marginnote">The way that a multicoloured function like <em>print</em> works is that when you ask to show something, like <em>d</em>, R first looks to see what kind of thing you want to show (by calling <em>class</em>), and determines that it is a <em>dist</em> object. Then it looks to see if there is a function called <em>print.dist</em> (there is), and if there is, it calls that (to produce that nice display). If there isn’t, it calls <em>print.default</em>, which just displays its input without doing anything special. This is why printing the output from an <em>lm</em> looks very different from printing a data frame: the first calls <em>print.lm</em> and the second calls <em>print.data.frame</em>, or <em>print.tbl-df</em> for a tibble.</span>
that controls how it looks:</p>
<div class="sourceCode" id="cb4071"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb4071-1" data-line-number="1">d</a></code></pre></div>
<pre><code>##    C  D  G  H  M  N  Q
## D 16                  
## G  9 19               
## H 19 17 18            
## M 19 18 19 11         
## N 19 17 20  3  5      
## Q 12  1 12 20 19 13   
## W 20 16 19 16  3  8 17</code></pre>
<p>but its innards are a whole lot more complicated than that:</p>
<div class="sourceCode" id="cb4073"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb4073-1" data-line-number="1"><span class="kw">print.default</span>(d)</a></code></pre></div>
<pre><code>##  [1] 16  9 19 19 19 12 20 19 17 18 17  1 16 18 19 20 12 19 11  3 20 16  5
## [24] 19  3 13  8 17
## attr(,&quot;Labels&quot;)
## [1] &quot;C&quot; &quot;D&quot; &quot;G&quot; &quot;H&quot; &quot;M&quot; &quot;N&quot; &quot;Q&quot; &quot;W&quot;
## attr(,&quot;Size&quot;)
## [1] 8
## attr(,&quot;call&quot;)
## as.dist.default(m = letters2)
## attr(,&quot;class&quot;)
## [1] &quot;dist&quot;
## attr(,&quot;Diag&quot;)
## [1] FALSE
## attr(,&quot;Upper&quot;)
## [1] FALSE</code></pre>
<p>or</p>
<div class="sourceCode" id="cb4075"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb4075-1" data-line-number="1"><span class="kw">unclass</span>(d)</a></code></pre></div>
<pre><code>##  [1] 16  9 19 19 19 12 20 19 17 18 17  1 16 18 19 20 12 19 11  3 20 16  5
## [24] 19  3 13  8 17
## attr(,&quot;Labels&quot;)
## [1] &quot;C&quot; &quot;D&quot; &quot;G&quot; &quot;H&quot; &quot;M&quot; &quot;N&quot; &quot;Q&quot; &quot;W&quot;
## attr(,&quot;Size&quot;)
## [1] 8
## attr(,&quot;call&quot;)
## as.dist.default(m = letters2)
## attr(,&quot;Diag&quot;)
## [1] FALSE
## attr(,&quot;Upper&quot;)
## [1] FALSE</code></pre>
<p>This one gets rid of any special kind of thing that <code>d</code> is, and
displays it like a thing without any special properties.</p>
<p>It’s the “attribute” called <code>Labels</code> that we need to grab:</p>
<div class="sourceCode" id="cb4077"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb4077-1" data-line-number="1"><span class="kw">attributes</span>(d)<span class="op">$</span>Labels</a></code></pre></div>
<pre><code>## [1] &quot;C&quot; &quot;D&quot; &quot;G&quot; &quot;H&quot; &quot;M&quot; &quot;N&quot; &quot;Q&quot; &quot;W&quot;</code></pre>
<ol start="4" style="list-style-type: lower-alpha">
<li>Plot your multidimensional scaling map. To do this, first
create a data frame containing the points you want to plot and their
labels, and then plot the points labelled by the right thing.</li>
</ol>
<p>Solution</p>
<p>The “labels” need to be the letter names, which is why I made
you find them in the previous part. I’m going to do this with a
pipe, or else I’ll create <em>another</em> thing called <code>d</code>
and overwrite the one I wanted to keep, again:</p>
<div class="sourceCode" id="cb4079"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb4079-1" data-line-number="1"><span class="kw">data.frame</span>(d<span class="fl">.1</span>,<span class="dt">names=</span>letter_names) </a></code></pre></div>
<pre><code>##          X1         X2 names
## C  9.624942  4.7694928     C
## D  4.451129 -9.5740790     D
## G  8.863167  7.6643690     G
## H -6.817352  3.8283789     H
## M -8.917331  2.0059242     M
## N -7.926704 -0.8531024     N
## Q  7.875169 -5.9942901     Q
## W -7.153020 -1.8466934     W</code></pre>
<p>So far so good. The coordinates have gained names <code>X1</code> and
<code>X2</code> (as they did before, but I wanted to check). This is what
happens when you turn a matrix with nameless columns into a data
frame. So I can proceed:</p>
<div class="sourceCode" id="cb4081"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb4081-1" data-line-number="1"><span class="kw">data.frame</span>(d<span class="fl">.1</span>,<span class="dt">names=</span>letter_names) <span class="op">%&gt;%</span><span class="st"> </span></a>
<a class="sourceLine" id="cb4081-2" data-line-number="2"><span class="kw">ggplot</span>(<span class="kw">aes</span>(<span class="dt">x=</span>X1,<span class="dt">y=</span>X2,<span class="dt">label=</span>names))<span class="op">+</span></a>
<a class="sourceLine" id="cb4081-3" data-line-number="3"><span class="kw">geom_point</span>()<span class="op">+</span><span class="kw">geom_text_repel</span>()<span class="op">+</span></a>
<a class="sourceLine" id="cb4081-4" data-line-number="4"><span class="kw">coord_fixed</span>()</a></code></pre></div>
<p><img src="23-mds_files/figure-html/unnamed-chunk-51-1.png" width="672"  /></p>
<p>I need the last line for the same reason as before: I want to treat
the two axes equally. If you don’t have that, you have a distorted map
where one of the coordinates appears to be more important than the other.</p>
<p>If you can’t get <code>ggrepel</code> to behave itself, an equally good
alternative is to plot the letter names instead of the labelled
dots. To do that, take out the <code>geom_point</code> and add an
ordinary <code>geom_text</code>. This will plot, <em>at</em> the location
given by the <code>x</code> and <code>y</code>, the text in <code>label</code>,
centred at the location. (If you have <code>geom_point()</code> as well,
you’ll get a black dot in the middle of each piece of text.)
<code>geom_text</code> has options to justify the text relative to the
point, so you can see both, but I’ve always found these rather
finicky, so I’d rather let <code>geom_text_repel</code> do the work of
figuring out where to put the text relative to the point.</p>
<div class="sourceCode" id="cb4082"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb4082-1" data-line-number="1"><span class="kw">data.frame</span>(d<span class="fl">.1</span>,<span class="dt">names=</span>letter_names) <span class="op">%&gt;%</span><span class="st"> </span></a>
<a class="sourceLine" id="cb4082-2" data-line-number="2"><span class="kw">ggplot</span>(<span class="kw">aes</span>(<span class="dt">x=</span>X1,<span class="dt">y=</span>X2,<span class="dt">label=</span>names))<span class="op">+</span></a>
<a class="sourceLine" id="cb4082-3" data-line-number="3"><span class="kw">geom_text</span>()<span class="op">+</span><span class="kw">coord_fixed</span>()</a></code></pre></div>
<p><img src="23-mds_files/figure-html/unnamed-chunk-52-1.png" width="672"  /></p>
<p>Then pick (in the next part) a pair of letters that is close together,
and proceed. I like the labelled dots better (as a matter of taste),
but this way is a perfectly good way to answer the question, so is
perfectly acceptable here.</p>
<ol start="5" style="list-style-type: lower-alpha">
<li>Pick a pair of letters appear close together on your
map. Does it make sense, from looking at these letters, that they
would be easy to confuse? Explain briefly.</li>
</ol>
<p>Solution</p>
<p>My map has four pairs of close-together letters: C and G, H and M,
N and W, Q and D. Pick one of those pairs. I don’t mind which pair
you pick. (If you got something different, pick from what your map
shows.)
I think it is not at all surprising that these pairs of letters
got confused, because the letters of each pair have similar shapes
(which is all you’d have to react to if you see them for “a few milliseconds” each): C and G circular with a hole on the right,
H, M, N and W vertical lines on the outside with something across
the middle, Q and D almost circular. (It’s up to you whether you
consider H, M, N and W as a group of four or as two pairs.)</p>
<ol start="6" style="list-style-type: lower-alpha">
<li>Verify that your chosen pair of letters was often confused
in the data.</li>
</ol>
<p>Solution</p>
<p>The data we read in from the file was this:</p>
<div class="sourceCode" id="cb4083"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb4083-1" data-line-number="1">letters</a></code></pre></div>
<pre><code>## # A tibble: 8 x 9
##   X1        C     D     G     H     M     N     Q     W
##   &lt;chr&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt;
## 1 C         0     0     0     0     0     0     0     0
## 2 D         5     0     0     0     0     0     0     0
## 3 G        12     2     0     0     0     0     0     0
## 4 H         2     4     3     0     0     0     0     0
## 5 M         2     3     2    10     0     0     0     0
## 6 N         2     4     1    18    16     0     0     0
## 7 Q         9    20     9     1     2     8     0     0
## 8 W         1     5     2     5    18    13     4     0</code></pre>
<p>Then look for your pair of letters:</p>

<p>These are four of the biggest numbers in the matrix, which is as it
should be. You need to find the number of confusions for your pair of
letters and assert that it is large (compared to the others).</p>
<p>These are actually not <em>all</em> the large ones: M and W, H and N, M
and N are also large (which lends some support to these letters being
a foursome
<label for="tufte-mn-254" class="margin-toggle">⊕</label><input type="checkbox" id="tufte-mn-254" class="margin-toggle"><span class="marginnote">Set of four. Match-play golf has a game called <em>foursomes</em> where the two players on each team take it in turns to hit the ball, as opposed to the game called <em>fourballs</em>, where each of the two players plays their own ball, and the team’s score on a hole is the better of the two players’ scores.</span> rather than two pairs).</p>
<p>If you prefer, you can work from your <code>dist</code> object, the thing
I called <code>d</code>:</p>
<div class="sourceCode" id="cb4085"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb4085-1" data-line-number="1">d</a></code></pre></div>
<pre><code>##    C  D  G  H  M  N  Q
## D 16                  
## G  9 19               
## H 19 17 18            
## M 19 18 19 11         
## N 19 17 20  3  5      
## Q 12  1 12 20 19 13   
## W 20 16 19 16  3  8 17</code></pre>
<p>This time, you’re looking for a <em>small</em> dissimilarity between
your pair of letters:</p>

<p>These, again, are smaller than most, though not the smallest
overall. So, if you go this way, you need to assert that the
corresponding number in your <code>dist</code> object is <em>small</em>.</p>
</div>
<div id="more-beer-please" class="section level2">
<h2><span class="header-section-number">24.4</span> More beer please</h2>
<p>Previously, you did a cluster analysis of
ten brands of beer, as rated by 32 students. This time, we will do a
non-metric multidimensional scaling of those same brands of beer. The
data are in <a href="http://www.utsc.utoronto.ca/~butler/d29/beer.txt">link</a>.</p>
<ol style="list-style-type: lower-alpha">
<li>Noting that we want to assess distances between brands of beer,
read in the data and do whatever you need to do to work out
distances between the beers. Show your result.</li>
</ol>
<p>Solution</p>
<p>First I should get rid of <code>MASS</code>, since we don’t need it here:</p>
<div class="sourceCode" id="cb4087"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb4087-1" data-line-number="1"><span class="kw">detach</span>(<span class="st">&quot;package:MASS&quot;</span>, <span class="dt">unload=</span>T)</a></code></pre></div>
<p>This is really a copy of last time. We need to transpose the data
frame to get the beers in <em>rows</em> (<code>dist</code> works on
distances between rows), then feed everything but the student IDs
into <code>dist</code>:</p>
<div class="sourceCode" id="cb4088"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb4088-1" data-line-number="1">my_url=<span class="st">&quot;http://www.utsc.utoronto.ca/~butler/d29/beer.txt&quot;</span></a>
<a class="sourceLine" id="cb4088-2" data-line-number="2">beer=<span class="kw">read_table2</span>(my_url)</a></code></pre></div>
<pre><code>## Parsed with column specification:
## cols(
##   student = col_character(),
##   AnchorS = col_double(),
##   Bass = col_double(),
##   Becks = col_double(),
##   Corona = col_double(),
##   GordonB = col_double(),
##   Guinness = col_double(),
##   Heineken = col_double(),
##   PetesW = col_double(),
##   SamAdams = col_double(),
##   SierraN = col_double()
## )</code></pre>
<div class="sourceCode" id="cb4090"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb4090-1" data-line-number="1">beer</a></code></pre></div>
<pre><code>## # A tibble: 32 x 11
##    student AnchorS  Bass Becks Corona GordonB Guinness Heineken PetesW
##    &lt;chr&gt;     &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt;  &lt;dbl&gt;   &lt;dbl&gt;    &lt;dbl&gt;    &lt;dbl&gt;  &lt;dbl&gt;
##  1 S001          5     9     7      1       7        6        6      5
##  2 S008          7     5     6      8       8        4        8      8
##  3 S015          7     7     5      6       6        1        8      4
##  4 S022          7     7     5      2       5        8        4      6
##  5 S029          9     7     3      1       6        8        2      7
##  6 S036          7     6     4      3       7        6        6      5
##  7 S043          5     5     5      6       6        4        7      5
##  8 S050          5     3     1      5       5        5        3      5
##  9 S057          9     3     2      6       4        6        1      5
## 10 S064          2     6     6      5       6        4        8      4
## # … with 22 more rows, and 2 more variables: SamAdams &lt;dbl&gt;, SierraN &lt;dbl&gt;</code></pre>
<div class="sourceCode" id="cb4092"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb4092-1" data-line-number="1">d =<span class="st"> </span>beer <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb4092-2" data-line-number="2">dplyr<span class="op">::</span><span class="kw">select</span>(<span class="op">-</span>student) <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb4092-3" data-line-number="3"><span class="kw">t</span>() <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb4092-4" data-line-number="4"><span class="kw">dist</span>()</a></code></pre></div>
<p>I did it the funny-looking way. The cluster analysis question offers
an alternative.</p>
<ol start="2" style="list-style-type: lower-alpha">
<li>Obtain a non-metric multidimensional scaling of the
beers. (Comment coming up in a moment.)</li>
</ol>
<p>Solution</p>
<div class="sourceCode" id="cb4093"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb4093-1" data-line-number="1"><span class="kw">library</span>(MASS)</a></code></pre></div>
<pre><code>## 
## Attaching package: &#39;MASS&#39;</code></pre>
<pre><code>## The following object is masked from &#39;package:dplyr&#39;:
## 
##     select</code></pre>
<div class="sourceCode" id="cb4096"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb4096-1" data-line-number="1">beer<span class="fl">.1</span>=<span class="kw">isoMDS</span>(d)</a></code></pre></div>
<pre><code>## initial  value 13.344792 
## iter   5 value 10.855662
## iter  10 value 10.391446
## final  value 10.321949 
## converged</code></pre>
<ol start="3" style="list-style-type: lower-alpha">
<li>Obtain the <code>stress</code> value of the map, and comment on it.</li>
</ol>
<p>Solution</p>
<div class="sourceCode" id="cb4098"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb4098-1" data-line-number="1">beer<span class="fl">.1</span><span class="op">$</span>stress</a></code></pre></div>
<pre><code>## [1] 10.32195</code></pre>
<p>The stress is around 10%, on the boundary between “good” and
“fair”. It seems as if the map should be more or less worth
using. (Insert your own hand-waving language here.)</p>
<ol start="4" style="list-style-type: lower-alpha">
<li>Obtain a map of the beers, labelled with the names of the
beers.</li>
</ol>
<p>Solution</p>
<p>This is slightly different from class, where I plotted the
languages actually <em>at</em> their locations. But here, the beer
names are longer, so we should plot the points and label them. I’d
make a data frame first, and probably pipe it into the plot,
thus. Don’t forget we have to get the names of the 10 beers, and
not the 32 students! The names of the columns of the data frame
include an identifier column for the students, so skip the first one:</p>
<div class="sourceCode" id="cb4100"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb4100-1" data-line-number="1">beer_names =<span class="st"> </span>beer <span class="op">%&gt;%</span><span class="st"> </span>dplyr<span class="op">::</span><span class="kw">select</span>(<span class="op">-</span>student) <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">names</span>()</a>
<a class="sourceLine" id="cb4100-2" data-line-number="2">beer_names</a></code></pre></div>
<pre><code>##  [1] &quot;AnchorS&quot;  &quot;Bass&quot;     &quot;Becks&quot;    &quot;Corona&quot;   &quot;GordonB&quot;  &quot;Guinness&quot;
##  [7] &quot;Heineken&quot; &quot;PetesW&quot;   &quot;SamAdams&quot; &quot;SierraN&quot;</code></pre>
<div class="sourceCode" id="cb4102"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb4102-1" data-line-number="1"><span class="kw">data.frame</span>(beer<span class="fl">.1</span><span class="op">$</span>points,<span class="dt">beer=</span>beer_names) <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb4102-2" data-line-number="2"><span class="kw">ggplot</span>(<span class="kw">aes</span>(<span class="dt">x=</span>X1,<span class="dt">y=</span>X2,<span class="dt">label=</span>beer))<span class="op">+</span></a>
<a class="sourceLine" id="cb4102-3" data-line-number="3"><span class="kw">geom_point</span>()<span class="op">+</span><span class="kw">geom_text_repel</span>()</a></code></pre></div>
<p><img src="23-mds_files/figure-html/unnamed-chunk-59-1.png" width="672"  /></p>
<ol start="5" style="list-style-type: lower-alpha">
<li>Find a pair of beers close together on your map. Are they
similar in terms of student ratings? Explain briefly.</li>
</ol>
<p>Solution</p>
<p>I think Sam Adams and Gordon Biersch, right in the middle of the
map. We can pull them out by name:</p>
<div class="sourceCode" id="cb4103"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb4103-1" data-line-number="1">beer <span class="op">%&gt;%</span><span class="st"> </span>dplyr<span class="op">::</span><span class="kw">select</span>(SamAdams,GordonB) <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">print</span>(<span class="dt">n=</span><span class="ot">Inf</span>)</a></code></pre></div>
<pre><code>## # A tibble: 32 x 2
##    SamAdams GordonB
##       &lt;dbl&gt;   &lt;dbl&gt;
##  1        9       7
##  2        7       8
##  3        7       6
##  4        8       5
##  5        6       6
##  6        4       7
##  7        5       6
##  8        5       5
##  9        3       4
## 10        4       6
## 11        7       7
## 12        7       9
## 13        7       6
## 14        6       6
## 15        8       5
## 16        5       6
## 17        7       6
## 18        8       2
## 19        6       7
## 20        6       5
## 21        5       5
## 22        8       7
## 23        4       5
## 24        7       7
## 25        4       7
## 26        6       3
## 27        7       6
## 28        6       6
## 29        7       5
## 30        7       7
## 31        6       9
## 32        5       6</code></pre>
<p>These are, with a few exceptions (the most glaring being the 18th
student), within a couple of points of each other. So I would say they
are similar. Another way to show this is to make a scatterplot of
them, and draw on it the line where the ratings are the same. Since
the ratings are whole numbers, they are likely to be duplicated, so I
“jitter” them as I plot them, to prevent overplotting:</p>
<div class="sourceCode" id="cb4105"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb4105-1" data-line-number="1"><span class="kw">ggplot</span>(beer,<span class="kw">aes</span>(<span class="dt">x=</span>SamAdams,<span class="dt">y=</span>GordonB))<span class="op">+</span><span class="kw">geom_jitter</span>()<span class="op">+</span></a>
<a class="sourceLine" id="cb4105-2" data-line-number="2"><span class="kw">geom_abline</span>(<span class="dt">intercept=</span><span class="dv">0</span>,<span class="dt">slope=</span><span class="dv">1</span>)</a></code></pre></div>
<p><img src="23-mds_files/figure-html/adkjalkjdsg-1.png" width="672"  /></p>
<p>Are they close to the line, or not? Dunno. Maybe I should plot the
ratings of some far-apart beers, and see whether it looks any
different, for example <code>Becks</code> and <code>SierraN</code>:</p>
<div class="sourceCode" id="cb4106"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb4106-1" data-line-number="1"><span class="kw">ggplot</span>(beer,<span class="kw">aes</span>(<span class="dt">x=</span>Becks,<span class="dt">y=</span>SierraN))<span class="op">+</span><span class="kw">geom_jitter</span>()<span class="op">+</span></a>
<a class="sourceLine" id="cb4106-2" data-line-number="2"><span class="kw">geom_abline</span>(<span class="dt">intercept=</span><span class="dv">0</span>,<span class="dt">slope=</span><span class="dv">1</span>)</a></code></pre></div>
<p><img src="23-mds_files/figure-html/adkjalkjdsh-1.png" width="672"  /></p>
<p>Not much. I was expecting something a lot more impressive. Another way
is to summarize the rating <em>differences</em> for the pairs of beers:</p>
<div class="sourceCode" id="cb4107"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb4107-1" data-line-number="1">diff=<span class="kw">with</span>(beer,SamAdams<span class="op">-</span>GordonB) </a>
<a class="sourceLine" id="cb4107-2" data-line-number="2"><span class="kw">summary</span>(diff)</a></code></pre></div>
<pre><code>##    Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
## -3.0000 -1.0000  0.0000  0.1562  1.0000  6.0000</code></pre>
<p>and</p>
<div class="sourceCode" id="cb4109"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb4109-1" data-line-number="1">diff=<span class="kw">with</span>(beer,Becks<span class="op">-</span>SierraN)</a>
<a class="sourceLine" id="cb4109-2" data-line-number="2"><span class="kw">summary</span>(diff)</a></code></pre></div>
<pre><code>##    Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
##   -8.00   -4.00   -1.50   -1.75    0.00    3.00</code></pre>
<p>Now we see something: two beers that are similar ought to have a
median rating difference close to 0 most of the time. That is the
case for the first pair; the median <em>is</em> zero, and the IQR is
only 2. But for the second pair, Becks is typically rated lower than
Sierra Nevada (negative median) and the IQR is larger (4 rather than
2).</p>
<ol start="6" style="list-style-type: lower-alpha">
<li>In our cluster analysis, we found that Anchor Steam, Pete’s
Wicked Ale, Guinness and Sierra Nevada were all in the same
cluster. Would you expect them to be close together on your map? Are
they? Explain briefly.</li>
</ol>
<p>Solution</p>
<p>If they are in the same cluster, we would expect them to
“cluster” together on the map. Except that they don’t, really.
These are the four beers over on the right of our map. They are kind
of in the same general neighbourhood, but not really what you would
call close together. (This is a judgement call, again.) In fact, none
of the beers, with the exception of Sam Adams and Gordon Biersch in
the centre, are really very close to any of the others.</p>
<p>That may be the story, in the end. With the cluster analysis, we were
forcing the clustering to happen, whether it was really there or
not. We haven’t seen a test for the “significance” of clusters, so
the clusters we found may not mean very much.</p>
</div>
<div id="feeling-similar-again" class="section level2">
<h2><span class="header-section-number">24.5</span> Feeling similar, again</h2>
<p>Previously, we looked at an experiment about which objects feel similar to one another and which ones feel different.</p>
<p>30 subjects were each
given 17 different objects to feel, for example
“inner surface of pine bark”,
“rubber eraser” and
“nylon scouring pad”. The
subjects had to group the objects into a maximum of 8 groups such that
the objects within a group felt similar, and the ones in different
groups felt different.
A
dissimilarity matrix was formed by counting how many subjects put each
pair of objects into <em>different</em> groups, so that the
dissimilarity ranged from 0 (the objects were always put together in
the same group) to 30 (the objects were not put together into the same
group by any of the subjects).</p>
<p>The data are in
<a href="http://www.utsc.utoronto.ca/~butler/d29/stimuli.txt">link</a>. These have
<em>no</em> column names.</p>
<p>This time we are going to try <em>non-metric</em> multidimensional
scaling, to see whether that produces a more reasonable map. The
reading in of the data is the same as before (so I have reduced the
marks given for it).</p>
<ol style="list-style-type: lower-alpha">
<li>Obtain and display the distance matrix that you used last
time for these data. (I don’t care whether you run all the code
again, or whether you just produce the matrix from where you had it
before on R Studio. Correct is all I care about.)</li>
</ol>
<p>Solution</p>
<p>Copied and pasted from last time:</p>
<div class="sourceCode" id="cb4111"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb4111-1" data-line-number="1">my_url=<span class="st">&quot;http://www.utsc.utoronto.ca/~butler/d29/stimuli.txt&quot;</span></a>
<a class="sourceLine" id="cb4111-2" data-line-number="2">stimuli=<span class="kw">read_delim</span>(my_url,<span class="st">&quot; &quot;</span>,<span class="dt">col_names=</span>F)</a>
<a class="sourceLine" id="cb4111-3" data-line-number="3">objects=stimuli<span class="op">$</span>X1</a>
<a class="sourceLine" id="cb4111-4" data-line-number="4"><span class="kw">names</span>(stimuli)=<span class="kw">c</span>(<span class="st">&quot;object&quot;</span>,objects)</a>
<a class="sourceLine" id="cb4111-5" data-line-number="5">stimuli</a></code></pre></div>
<pre><code>## # A tibble: 17 x 18
##    object innersurfaceofp… brick cardboard  cork rubbereraser  felt
##    &lt;chr&gt;             &lt;dbl&gt; &lt;dbl&gt;     &lt;dbl&gt; &lt;dbl&gt;        &lt;dbl&gt; &lt;dbl&gt;
##  1 inner…                0    22        23    24           26    27
##  2 brick                22     0        27    27           27    29
##  3 cardb…               23    27         0    18           19    28
##  4 cork                 24    27        18     0           15    28
##  5 rubbe…               26    27        19    15            0    28
##  6 felt                 27    29        28    28           28     0
##  7 leath…               26    29        23    25           20    24
##  8 rigid…               23    28        24    26           27    28
##  9 veryf…               24    16        24    28           24    29
## 10 nylon…               23    18        29    28           27    26
## 11 cellu…               23    28        27    20           24    26
## 12 woven…               18    25        28    27           25    29
## 13 block…               23    24        21    10           19    28
## 14 ungla…               21    10        26    26           24    29
## 15 velvet               28    29        28    28           29     4
## 16 waxpa…               24    28        24    28           24    28
## 17 gloss…               22    27        23    29           28    29
## # … with 11 more variables: leatherwallet &lt;dbl&gt;, rigidplasticsheet &lt;dbl&gt;,
## #   veryfinesandpaper &lt;dbl&gt;, nylonscouringpad &lt;dbl&gt;,
## #   cellulosekitchensponge &lt;dbl&gt;, wovenstraw &lt;dbl&gt;,
## #   blockofstyrofoam &lt;dbl&gt;, unglazedceramictile &lt;dbl&gt;, velvet &lt;dbl&gt;,
## #   waxpaper &lt;dbl&gt;, glossypaintedwood &lt;dbl&gt;</code></pre>
<p>That gets a data frame with the right column names. Then:</p>
<div class="sourceCode" id="cb4113"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb4113-1" data-line-number="1">d =<span class="st"> </span>stimuli <span class="op">%&gt;%</span><span class="st"> </span>dplyr<span class="op">::</span><span class="kw">select</span>(<span class="op">-</span><span class="dv">1</span>) <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">as.dist</span>()</a></code></pre></div>
<p>and just to check:</p>
<div class="sourceCode" id="cb4114"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb4114-1" data-line-number="1">w=<span class="kw">getOption</span>(<span class="st">&quot;width&quot;</span>)</a>
<a class="sourceLine" id="cb4114-2" data-line-number="2"><span class="kw">options</span>(<span class="dt">width=</span><span class="dv">132</span>)</a>
<a class="sourceLine" id="cb4114-3" data-line-number="3">d</a></code></pre></div>
<pre><code>##                        innersurfaceofpinebark brick cardboard cork rubbereraser felt leatherwallet rigidplasticsheet
## brick                                      22                                                                       
## cardboard                                  23    27                                                                 
## cork                                       24    27        18                                                       
## rubbereraser                               26    27        19   15                                                  
## felt                                       27    29        28   28           28                                     
## leatherwallet                              26    29        23   25           20   24                                
## rigidplasticsheet                          23    28        24   26           27   28            22                  
## veryfinesandpaper                          24    16        24   28           24   29            28                27
## nylonscouringpad                           23    18        29   28           27   26            28                29
## cellulosekitchensponge                     23    28        27   20           24   26            27                29
## wovenstraw                                 18    25        28   27           25   29            26                27
## blockofstyrofoam                           23    24        21   10           19   28            25                25
## unglazedceramictile                        21    10        26   26           24   29            29                25
## velvet                                     28    29        28   28           29    4            24                29
## waxpaper                                   24    28        24   28           24   28            21                12
## glossypaintedwood                          22    27        23   29           28   29            20                13
##                        veryfinesandpaper nylonscouringpad cellulosekitchensponge wovenstraw blockofstyrofoam unglazedceramictile
## brick                                                                                                                           
## cardboard                                                                                                                       
## cork                                                                                                                            
## rubbereraser                                                                                                                    
## felt                                                                                                                            
## leatherwallet                                                                                                                   
## rigidplasticsheet                                                                                                               
## veryfinesandpaper                                                                                                               
## nylonscouringpad                      21                                                                                        
## cellulosekitchensponge                24               22                                                                       
## wovenstraw                            26               16                     19                                                
## blockofstyrofoam                      25               25                     21         26                                     
## unglazedceramictile                   12               24                     26         26               25                    
## velvet                                29               27                     27         28               29                  29
## waxpaper                              29               29                     29         27               26                  28
## glossypaintedwood                     27               28                     27         25               29                  26
##                        velvet waxpaper
## brick                                 
## cardboard                             
## cork                                  
## rubbereraser                          
## felt                                  
## leatherwallet                         
## rigidplasticsheet                     
## veryfinesandpaper                     
## nylonscouringpad                      
## cellulosekitchensponge                
## wovenstraw                            
## blockofstyrofoam                      
## unglazedceramictile                   
## velvet                                
## waxpaper                   27         
## glossypaintedwood          26       12</code></pre>
<div class="sourceCode" id="cb4116"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb4116-1" data-line-number="1"><span class="kw">options</span>(<span class="dt">width=</span>w)</a></code></pre></div>
<ol start="2" style="list-style-type: lower-alpha">
<li>Obtain a non-metric multidimensional scaling map of the
objects. (No plotting or comments yet.)</li>
</ol>
<p>Solution</p>
<div class="sourceCode" id="cb4117"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb4117-1" data-line-number="1">stimuli<span class="fl">.1</span>=<span class="kw">isoMDS</span>(d)</a></code></pre></div>
<pre><code>## initial  value 25.537169 
## iter   5 value 20.521473
## final  value 20.216103 
## converged</code></pre>
<p>I’m going to remind myself of what this has in it:</p>
<div class="sourceCode" id="cb4119"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb4119-1" data-line-number="1"><span class="kw">names</span>(stimuli<span class="fl">.1</span>)</a></code></pre></div>
<pre><code>## [1] &quot;points&quot; &quot;stress&quot;</code></pre>
<p>This is rather like running <code>cmdscale</code> with <code>eig=T</code>: a
thing called <code>points</code> with coordinates to plot, and a measure
of fit, here called <code>stress</code>, with, as you’d guess, a smaller
<code>stress</code> being better.</p>
<ol start="3" style="list-style-type: lower-alpha">
<li><a name="part:stress">*</a> Obtain a number that says how well the map reproduces the
distances in the data, and comment on that number.</li>
</ol>
<p>Solution</p>
<p>What you need here is the “stress”:</p>
<div class="sourceCode" id="cb4121"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb4121-1" data-line-number="1">stimuli<span class="fl">.1</span><span class="op">$</span>stress</a></code></pre></div>
<pre><code>## [1] 20.2161</code></pre>
<p>This is just over 20%, which is described in the notes as
“poor”. We should thus be skeptical about the map that this produces.</p>
<ol start="4" style="list-style-type: lower-alpha">
<li>Plot the non-metric multidimensional scaling map. Label each
point with its (full) object name, sized suitably.</li>
</ol>
<p>Solution</p>
<p>Make a data frame first of things to plot, the points and the
names. I’m going to plot the names smaller). I am <em>not</em>
naming this data frame <code>d</code>, in an attempt to avoid
overwriting things I want to keep:</p>
<div class="sourceCode" id="cb4123"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb4123-1" data-line-number="1">stimuli.<span class="fl">1.</span>d=<span class="kw">data.frame</span>(stimuli<span class="fl">.1</span><span class="op">$</span>points,<span class="dt">names=</span>objects)</a>
<a class="sourceLine" id="cb4123-2" data-line-number="2">stimuli.<span class="fl">1.</span>d</a></code></pre></div>
<pre><code>##                                 X1          X2                  names
## innersurfaceofpinebark  -1.5343296   1.3163495 innersurfaceofpinebark
## brick                  -11.1198228   4.1255022                  brick
## cardboard                3.7481838  -9.4875599              cardboard
## cork                    -0.8637631 -11.6740046                   cork
## rubbereraser             0.9478406  -9.9955340           rubbereraser
## felt                     3.7030786  15.0204325                   felt
## leatherwallet            9.5323886  -3.3715939          leatherwallet
## rigidplasticsheet       11.3370118  -0.5134769      rigidplasticsheet
## veryfinesandpaper      -12.7743812   1.1092242      veryfinesandpaper
## nylonscouringpad        -9.1348586   8.0045364       nylonscouringpad
## cellulosekitchensponge  -8.2296607  -6.3368839 cellulosekitchensponge
## wovenstraw              -4.3321533   5.1303993             wovenstraw
## blockofstyrofoam        -3.3540109  -9.7135472       blockofstyrofoam
## unglazedceramictile    -10.7345424  -0.4673140    unglazedceramictile
## velvet                   7.0712701  15.3712514                 velvet
## waxpaper                14.2695604  -0.7584453               waxpaper
## glossypaintedwood       11.4681889   2.2406642      glossypaintedwood</code></pre>
<p>The repeated stimuli down the left are row names, but since they’re
row names, we won’t be able to use them in
<code>ggplot</code>.
<label for="tufte-mn-255" class="margin-toggle">⊕</label><input type="checkbox" id="tufte-mn-255" class="margin-toggle"><span class="marginnote">Next year, I’ll make everyone turn matrices into data frames first so that we won’t deal with old-fashioned data frames, row names and the like.</span></p>
<p>Remember that we are turning a matrix and a column into a data frame,
so we need either the more forgiving <code>data.frame</code>, or to turn
<code>points</code> into a data frame first, which would go like this:</p>
<div class="sourceCode" id="cb4125"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb4125-1" data-line-number="1"><span class="kw">as_tibble</span>(stimuli<span class="fl">.1</span><span class="op">$</span>points) <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb4125-2" data-line-number="2"><span class="kw">mutate</span>(<span class="dt">name=</span>objects)</a></code></pre></div>
<pre><code>## # A tibble: 17 x 3
##         V1      V2 name                  
##      &lt;dbl&gt;   &lt;dbl&gt; &lt;chr&gt;                 
##  1  -1.53    1.32  innersurfaceofpinebark
##  2 -11.1     4.13  brick                 
##  3   3.75   -9.49  cardboard             
##  4  -0.864 -11.7   cork                  
##  5   0.948 -10.00  rubbereraser          
##  6   3.70   15.0   felt                  
##  7   9.53   -3.37  leatherwallet         
##  8  11.3    -0.513 rigidplasticsheet     
##  9 -12.8     1.11  veryfinesandpaper     
## 10  -9.13    8.00  nylonscouringpad      
## 11  -8.23   -6.34  cellulosekitchensponge
## 12  -4.33    5.13  wovenstraw            
## 13  -3.35   -9.71  blockofstyrofoam      
## 14 -10.7    -0.467 unglazedceramictile   
## 15   7.07   15.4   velvet                
## 16  14.3    -0.758 waxpaper              
## 17  11.5     2.24  glossypaintedwood</code></pre>
<p>This time, the columns are called <code>V1</code> and <code>V2</code>, since
that’s what <code>as_tibble</code> does. Also note the slightly different
look: fewer decimals, since displaying a tibble rounds numerical
things to three significant digits.
Back to my data frame <code>stimuli.1.d</code>.
The points have acquired names <code>X1</code> and <code>X2</code>, as usual,
so we have all we need:</p>
<div class="sourceCode" id="cb4127"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb4127-1" data-line-number="1"><span class="kw">ggplot</span>(stimuli.<span class="fl">1.</span>d,<span class="kw">aes</span>(<span class="dt">x=</span>X1,<span class="dt">y=</span>X2,<span class="dt">label=</span>names))<span class="op">+</span></a>
<a class="sourceLine" id="cb4127-2" data-line-number="2"><span class="kw">geom_point</span>()<span class="op">+</span></a>
<a class="sourceLine" id="cb4127-3" data-line-number="3"><span class="kw">geom_text_repel</span>(<span class="dt">size=</span><span class="dv">2</span>)<span class="op">+</span></a>
<a class="sourceLine" id="cb4127-4" data-line-number="4"><span class="kw">coord_fixed</span>()</a></code></pre></div>
<p><img src="23-mds_files/figure-html/unnamed-chunk-71-1.png" width="672"  /></p>
<p>I think the full names are good with the text this small.</p>
<p>Actually, this came out a lot like the metric multidimensional scaling
that we did earlier.</p>
<p>I was expecting a greater difference. See whether you can find
out what moved, if anything.</p>
<ol start="5" style="list-style-type: lower-alpha">
<li><a name="part:incons">*</a> Find all the distances in your distance matrix that are 10
or less (there should be three of them). Find these pairs of objects
on your map. Describe where they are on your map. Do
they appear to be the three closest pairs of objects?</li>
</ol>
<p>Solution</p>
<p>These are:</p>
<ul>
<li><p><code>velvet</code> and <code>felt</code> (distance 4). On the map,
close together at the top.</p></li>
<li><p><code>block of styrofoam</code> and <code>cork</code> (distance 10). On the
map, close together at the bottom (though they appear to be
slightly farther apart than <code>rubbereraser</code> and
<code>cardboard</code>).</p></li>
<li><p><code>unglazed ceramic tile</code> and <code>brick</code> (distance
10). On the map, on the left but not especially close together
(for example, <code>very fine sandpaper</code> is in between them
and thus closer to both).</p></li>
</ul>
<p>I would say that they are not anything like the three closest
pairs of objects on the map. Consider, for example,  and <code>wax paper</code>, or  and <code>unglazed ceramic tile</code>, or  and <code>cardboard</code>, all of which are closer together
on the map than the three pairs of objects with distances 10 or
less.
Three points for saying something about the three pairs of objects
of distance 10 or less, and one point for making some relevant
comment about whether these are the three closest pairs on the
map, eg. by finding one pair (or more than one) of objects on the
map that are closer.</p>
<ol start="6" style="list-style-type: lower-alpha">
<li>Consider again your conclusions in parts (<a href="#part:stress">here</a>)
and (<a href="#part:incons">here</a>). Explain briefly how they are consistent.</li>
</ol>
<p>Solution</p>
<p>The stress is rather high, which means that the map distances and
actual distances may not correspond very well. This is also
exactly what we found in the last part, by finding one (or two)
pairs of objects that were really close in actuality, but not so
much on the map.
The point here is that a high stress <em>means</em> that distances
in real life and on the map won’t correspond very well. That’s
what I want you to say.
Extra: another way to assess this is with a Shepard
<label for="tufte-mn-256" class="margin-toggle">⊕</label><input type="checkbox" id="tufte-mn-256" class="margin-toggle"><span class="marginnote">This always makes me think of the number 190 (now 985) bus, but that’s the wrong spelling. Spelled like this, this is also the name of the illustrator of the original pre-Disney Winnie-the-Pooh stories. See <a href="https://en.wikipedia.org/wiki/E.-H.-Shepard" class="uri">https://en.wikipedia.org/wiki/E.-H.-Shepard</a>, replacing the dashes by underscores.</span>
diagram. That would go like this:</p>
<div class="sourceCode" id="cb4128"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb4128-1" data-line-number="1">stimuli.sh=<span class="kw">Shepard</span>(d,stimuli<span class="fl">.1</span><span class="op">$</span>points)</a>
<a class="sourceLine" id="cb4128-2" data-line-number="2"><span class="kw">names</span>(stimuli.sh)</a></code></pre></div>
<pre><code>## [1] &quot;x&quot;  &quot;y&quot;  &quot;yf&quot;</code></pre>
<p>In here, we plot the actual distances <code>x</code> against the map
distances <code>y</code>, making a data frame first:</p>
<div class="sourceCode" id="cb4130"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb4130-1" data-line-number="1"><span class="kw">with</span>(stimuli.sh,<span class="kw">data.frame</span>(<span class="dt">x=</span>x,<span class="dt">y=</span>y)) <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb4130-2" data-line-number="2"><span class="kw">ggplot</span>(<span class="kw">aes</span>(<span class="dt">x=</span>x,<span class="dt">y=</span>y))<span class="op">+</span><span class="kw">geom_point</span>()</a></code></pre></div>
<p><img src="23-mds_files/figure-html/unnamed-chunk-73-1.png" width="672"  /></p>
<p>The actual distances are on the <span class="math inline">\(x\)</span>-axis and the map distances are on
the <span class="math inline">\(y\)</span> axis, as far as I can tell (the help file is not clear on
this). But I think I am right, since a lot of the actual distances
were 28 or 29. Notice how the upward trend, such as it is, is very
fuzzy: when the actual distance is very large, the map distance could
be almost anything.</p>
<ol start="7" style="list-style-type: lower-alpha">
<li>Would a three-dimensional map work better than a
two-dimensional one, bearing in mind that a three-dimensional map
will need something like <code>rgl</code> to interpret? Calculate
something that will help you decide, and explain what you think.</li>
</ol>
<p>Solution</p>
<p>The calculation part is to figure out the stress value for a
three-dimensional map, and compare it with the 20% that we had
before. <code>k=3</code> gets the three dimensions:</p>
<div class="sourceCode" id="cb4131"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb4131-1" data-line-number="1"><span class="kw">isoMDS</span>(d,<span class="dt">k=</span><span class="dv">3</span>)<span class="op">$</span>stress</a></code></pre></div>
<pre><code>## initial  value 14.934110 
## iter   5 value 11.280474
## iter  10 value 10.094796
## iter  15 value 9.938456
## final  value 9.859657 
## converged</code></pre>
<pre><code>## [1] 9.859657</code></pre>
<p>What this does is to obtain the map and throw all of it away except
for the stress value.
<label for="tufte-mn-257" class="margin-toggle">⊕</label><input type="checkbox" id="tufte-mn-257" class="margin-toggle"><span class="marginnote">Which seems like a very SAS way of doing things.</span></p>
<p>I think this stress value, just under 10%, or on the “fair” end of
“good”, is a worthwhile improvement over the just-over-20% that we
had in two dimensions. So I think this is worth the trouble of having
to use a 3-dimensional plotting tool like <code>rgl</code> to interpret it
with. You might agree with me, or you might not: for example, you
might be looking for a bigger improvement. Either is good, as far as
I’m concerned, as long as your answer does something to balance the
smaller stress value
<label for="tufte-mn-258" class="margin-toggle">⊕</label><input type="checkbox" id="tufte-mn-258" class="margin-toggle"><span class="marginnote">Using more dimensions will <em>certainly</em> decrease the stress, in the same way that adding an <span class="math inline">\(x\)</span>-variable to a regression will increase R-squared; it’s the same issue, of whether the change is big enough to be worth having.</span> with the difficulty of interpreting it.</p>
<p>The kind of <code>rgl</code> code you’ll need is something like this (not tested):</p>
<div class="sourceCode" id="cb4134"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb4134-1" data-line-number="1"><span class="kw">library</span>(rgl)</a>
<a class="sourceLine" id="cb4134-2" data-line-number="2">stimuli<span class="fl">.2</span>=<span class="kw">isoMDS</span>(d,<span class="dt">k=</span><span class="dv">3</span>)<span class="op">$</span>points</a>
<a class="sourceLine" id="cb4134-3" data-line-number="3"><span class="kw">plot3d</span>(stimuli<span class="fl">.2</span>)</a>
<a class="sourceLine" id="cb4134-4" data-line-number="4"><span class="kw">text3d</span>(stimuli<span class="fl">.2</span>,<span class="dt">text=</span>object.abb)</a></code></pre></div>
<p>What you should find, looking at this (try it!) is that objects close
together in this 3-dimensional place are more nearly close together in
actuality as well, because of the in my opinion notably smaller stress
value.</p>

</div>
</div>
<p style="text-align: center;">
<a href="cluster-analysis.html"><button class="btn btn-default">Previous</button></a>
<a href="principal-components-and-factor-analysis.html"><button class="btn btn-default">Next</button></a>
</p>
</div>
</div>



</body>
</html>
