<!DOCTYPE html>
<html >

<head>

  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <title>Problems and Solutions in Applied Statistics</title>
  <meta name="description" content="A set of problems and solutions, in R, on various parts of applied statistics">
  <meta name="generator" content="bookdown 0.7 and GitBook 2.6.7">

  <meta property="og:title" content="Problems and Solutions in Applied Statistics" />
  <meta property="og:type" content="book" />
  <meta property="og:url" content="<a href="http://ritsokiguess.site/pasias" class="uri">http://ritsokiguess.site/pasias</a>" />
  
  <meta property="og:description" content="A set of problems and solutions, in R, on various parts of applied statistics" />
  <meta name="github-repo" content="nxskok/pasias" />

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Problems and Solutions in Applied Statistics" />
  
  <meta name="twitter:description" content="A set of problems and solutions, in R, on various parts of applied statistics" />
  

<meta name="author" content="Ken Butler">


<meta name="date" content="2018-10-09">

  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="apple-mobile-web-app-capable" content="yes">
  <meta name="apple-mobile-web-app-status-bar-style" content="black">
  
  
<link rel="prev" href="data-exploration.html">

<script src="libs/jquery-2.2.3/jquery.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />









<style type="text/css">
a.sourceLine { display: inline-block; line-height: 1.25; }
a.sourceLine { pointer-events: none; color: inherit; text-decoration: inherit; }
a.sourceLine:empty { height: 1.2em; position: absolute; }
.sourceCode { overflow: visible; }
code.sourceCode { white-space: pre; position: relative; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
code.sourceCode { white-space: pre-wrap; }
a.sourceLine { text-indent: -1em; padding-left: 1em; }
}
pre.numberSource a.sourceLine
  { position: relative; }
pre.numberSource a.sourceLine:empty
  { position: absolute; }
pre.numberSource a.sourceLine::before
  { content: attr(data-line-number);
    position: absolute; left: -5em; text-align: right; vertical-align: baseline;
    border: none; pointer-events: all;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {  }
@media screen {
a.sourceLine::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">Problems and Solutions in Applied Statistics</a></li>

<li class="divider"></li>
<li class="chapter" data-level="1" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i><b>1</b> Introduction</a></li>
<li class="chapter" data-level="2" data-path="getting-used-to-r-and-r-studio.html"><a href="getting-used-to-r-and-r-studio.html"><i class="fa fa-check"></i><b>2</b> Getting used to R and R Studio</a><ul>
<li class="chapter" data-level="2.1" data-path="getting-used-to-r-and-r-studio.html"><a href="getting-used-to-r-and-r-studio.html#attaching-packages-tidyverse-1.2.1"><i class="fa fa-check"></i><b>2.1</b> ── Attaching packages ─────────────────────────────────────────────────────────────────────────────────────── tidyverse 1.2.1 ──</a></li>
<li class="chapter" data-level="2.2" data-path="getting-used-to-r-and-r-studio.html"><a href="getting-used-to-r-and-r-studio.html#ggplot2-3.0.0-purrr-0.2.5"><i class="fa fa-check"></i><b>2.2</b> ✔ ggplot2 3.0.0 ✔ purrr 0.2.5</a></li>
<li class="chapter" data-level="2.3" data-path="getting-used-to-r-and-r-studio.html"><a href="getting-used-to-r-and-r-studio.html#tibble-1.4.2-dplyr-0.7.6"><i class="fa fa-check"></i><b>2.3</b> ✔ tibble 1.4.2 ✔ dplyr 0.7.6</a></li>
<li class="chapter" data-level="2.4" data-path="getting-used-to-r-and-r-studio.html"><a href="getting-used-to-r-and-r-studio.html#tidyr-0.8.1-stringr-1.3.1"><i class="fa fa-check"></i><b>2.4</b> ✔ tidyr 0.8.1 ✔ stringr 1.3.1</a></li>
<li class="chapter" data-level="2.5" data-path="getting-used-to-r-and-r-studio.html"><a href="getting-used-to-r-and-r-studio.html#readr-1.1.1-forcats-0.3.0"><i class="fa fa-check"></i><b>2.5</b> ✔ readr 1.1.1 ✔ forcats 0.3.0</a></li>
<li class="chapter" data-level="2.6" data-path="getting-used-to-r-and-r-studio.html"><a href="getting-used-to-r-and-r-studio.html#conflicts-tidyverse_conflicts"><i class="fa fa-check"></i><b>2.6</b> ── Conflicts ────────────────────────────────────────────────────────────────────────────────────────── tidyverse_conflicts() ──</a></li>
<li class="chapter" data-level="2.7" data-path="getting-used-to-r-and-r-studio.html"><a href="getting-used-to-r-and-r-studio.html#dplyrfilter-masks-statsfilter"><i class="fa fa-check"></i><b>2.7</b> ✖ dplyr::filter() masks stats::filter()</a></li>
<li class="chapter" data-level="2.8" data-path="getting-used-to-r-and-r-studio.html"><a href="getting-used-to-r-and-r-studio.html#dplyrlag-masks-statslag"><i class="fa fa-check"></i><b>2.8</b> ✖ dplyr::lag() masks stats::lag()</a></li>
<li class="chapter" data-level="2.9" data-path="getting-used-to-r-and-r-studio.html"><a href="getting-used-to-r-and-r-studio.html#getting-an-r-studio-cloud-account"><i class="fa fa-check"></i><b>2.9</b> Getting an R Studio Cloud account</a></li>
<li class="chapter" data-level="2.10" data-path="getting-used-to-r-and-r-studio.html"><a href="getting-used-to-r-and-r-studio.html#getting-started"><i class="fa fa-check"></i><b>2.10</b> Getting started</a></li>
<li class="chapter" data-level="2.11" data-path="getting-used-to-r-and-r-studio.html"><a href="getting-used-to-r-and-r-studio.html#a-tibble-32-x-11"><i class="fa fa-check"></i><b>2.11</b> # A tibble: 32 x 11</a></li>
<li class="chapter" data-level="2.12" data-path="getting-used-to-r-and-r-studio.html"><a href="getting-used-to-r-and-r-studio.html#mpg-cyl-disp-hp-drat-wt-qsec-vs-am-gear-carb"><i class="fa fa-check"></i><b>2.12</b> mpg cyl disp hp drat wt qsec vs am gear carb</a></li>
<li class="chapter" data-level="2.13" data-path="getting-used-to-r-and-r-studio.html"><a href="getting-used-to-r-and-r-studio.html#section"><i class="fa fa-check"></i><b>2.13</b> * <dbl> <dbl> <dbl> <dbl> <dbl> <dbl> <dbl> <dbl> <dbl> <dbl> <dbl></a></li>
<li class="chapter" data-level="2.14" data-path="getting-used-to-r-and-r-studio.html"><a href="getting-used-to-r-and-r-studio.html#section-1"><i class="fa fa-check"></i><b>2.14</b> 1 21 6 160 110 3.9 2.62 16.5 0 1 4 4</a></li>
<li class="chapter" data-level="2.15" data-path="getting-used-to-r-and-r-studio.html"><a href="getting-used-to-r-and-r-studio.html#section-2"><i class="fa fa-check"></i><b>2.15</b> 2 21 6 160 110 3.9 2.88 17.0 0 1 4 4</a></li>
<li class="chapter" data-level="2.16" data-path="getting-used-to-r-and-r-studio.html"><a href="getting-used-to-r-and-r-studio.html#section-3"><i class="fa fa-check"></i><b>2.16</b> 3 22.8 4 108 93 3.85 2.32 18.6 1 1 4 1</a></li>
<li class="chapter" data-level="2.17" data-path="getting-used-to-r-and-r-studio.html"><a href="getting-used-to-r-and-r-studio.html#section-4"><i class="fa fa-check"></i><b>2.17</b> 4 21.4 6 258 110 3.08 3.22 19.4 1 0 3 1</a></li>
<li class="chapter" data-level="2.18" data-path="getting-used-to-r-and-r-studio.html"><a href="getting-used-to-r-and-r-studio.html#section-5"><i class="fa fa-check"></i><b>2.18</b> 5 18.7 8 360 175 3.15 3.44 17.0 0 0 3 2</a></li>
<li class="chapter" data-level="2.19" data-path="getting-used-to-r-and-r-studio.html"><a href="getting-used-to-r-and-r-studio.html#section-6"><i class="fa fa-check"></i><b>2.19</b> 6 18.1 6 225 105 2.76 3.46 20.2 1 0 3 1</a></li>
<li class="chapter" data-level="2.20" data-path="getting-used-to-r-and-r-studio.html"><a href="getting-used-to-r-and-r-studio.html#section-7"><i class="fa fa-check"></i><b>2.20</b> 7 14.3 8 360 245 3.21 3.57 15.8 0 0 3 4</a></li>
<li class="chapter" data-level="2.21" data-path="getting-used-to-r-and-r-studio.html"><a href="getting-used-to-r-and-r-studio.html#section-8"><i class="fa fa-check"></i><b>2.21</b> 8 24.4 4 147. 62 3.69 3.19 20 1 0 4 2</a></li>
<li class="chapter" data-level="2.22" data-path="getting-used-to-r-and-r-studio.html"><a href="getting-used-to-r-and-r-studio.html#section-9"><i class="fa fa-check"></i><b>2.22</b> 9 22.8 4 141. 95 3.92 3.15 22.9 1 0 4 2</a></li>
<li class="chapter" data-level="2.23" data-path="getting-used-to-r-and-r-studio.html"><a href="getting-used-to-r-and-r-studio.html#section-10"><i class="fa fa-check"></i><b>2.23</b> 10 19.2 6 168. 123 3.92 3.44 18.3 1 0 4 4</a></li>
<li class="chapter" data-level="2.24" data-path="getting-used-to-r-and-r-studio.html"><a href="getting-used-to-r-and-r-studio.html#with-22-more-rows"><i class="fa fa-check"></i><b>2.24</b> # … with 22 more rows</a></li>
<li class="chapter" data-level="2.25" data-path="getting-used-to-r-and-r-studio.html"><a href="getting-used-to-r-and-r-studio.html#mpg-cyl-disp-hp"><i class="fa fa-check"></i><b>2.25</b> mpg cyl disp hp</a></li>
<li class="chapter" data-level="2.26" data-path="getting-used-to-r-and-r-studio.html"><a href="getting-used-to-r-and-r-studio.html#min.-10.40-min.-4.000-min.-71.1-min.-52.0"><i class="fa fa-check"></i><b>2.26</b> Min. :10.40 Min. :4.000 Min. : 71.1 Min. : 52.0</a></li>
<li class="chapter" data-level="2.27" data-path="getting-used-to-r-and-r-studio.html"><a href="getting-used-to-r-and-r-studio.html#st-qu.15.43-1st-qu.4.000-1st-qu.120.8-1st-qu.-96.5"><i class="fa fa-check"></i><b>2.27</b> 1st Qu.:15.43 1st Qu.:4.000 1st Qu.:120.8 1st Qu.: 96.5</a></li>
<li class="chapter" data-level="2.28" data-path="getting-used-to-r-and-r-studio.html"><a href="getting-used-to-r-and-r-studio.html#median-19.20-median-6.000-median-196.3-median-123.0"><i class="fa fa-check"></i><b>2.28</b> Median :19.20 Median :6.000 Median :196.3 Median :123.0</a></li>
<li class="chapter" data-level="2.29" data-path="getting-used-to-r-and-r-studio.html"><a href="getting-used-to-r-and-r-studio.html#mean-20.09-mean-6.188-mean-230.7-mean-146.7"><i class="fa fa-check"></i><b>2.29</b> Mean :20.09 Mean :6.188 Mean :230.7 Mean :146.7</a></li>
<li class="chapter" data-level="2.30" data-path="getting-used-to-r-and-r-studio.html"><a href="getting-used-to-r-and-r-studio.html#rd-qu.22.80-3rd-qu.8.000-3rd-qu.326.0-3rd-qu.180.0"><i class="fa fa-check"></i><b>2.30</b> 3rd Qu.:22.80 3rd Qu.:8.000 3rd Qu.:326.0 3rd Qu.:180.0</a></li>
<li class="chapter" data-level="2.31" data-path="getting-used-to-r-and-r-studio.html"><a href="getting-used-to-r-and-r-studio.html#max.-33.90-max.-8.000-max.-472.0-max.-335.0"><i class="fa fa-check"></i><b>2.31</b> Max. :33.90 Max. :8.000 Max. :472.0 Max. :335.0</a></li>
<li class="chapter" data-level="2.32" data-path="getting-used-to-r-and-r-studio.html"><a href="getting-used-to-r-and-r-studio.html#drat-wt-qsec-vs"><i class="fa fa-check"></i><b>2.32</b> drat wt qsec vs</a></li>
<li class="chapter" data-level="2.33" data-path="getting-used-to-r-and-r-studio.html"><a href="getting-used-to-r-and-r-studio.html#min.-2.760-min.-1.513-min.-14.50-min.-0.0000"><i class="fa fa-check"></i><b>2.33</b> Min. :2.760 Min. :1.513 Min. :14.50 Min. :0.0000</a></li>
<li class="chapter" data-level="2.34" data-path="getting-used-to-r-and-r-studio.html"><a href="getting-used-to-r-and-r-studio.html#st-qu.3.080-1st-qu.2.581-1st-qu.16.89-1st-qu.0.0000"><i class="fa fa-check"></i><b>2.34</b> 1st Qu.:3.080 1st Qu.:2.581 1st Qu.:16.89 1st Qu.:0.0000</a></li>
<li class="chapter" data-level="2.35" data-path="getting-used-to-r-and-r-studio.html"><a href="getting-used-to-r-and-r-studio.html#median-3.695-median-3.325-median-17.71-median-0.0000"><i class="fa fa-check"></i><b>2.35</b> Median :3.695 Median :3.325 Median :17.71 Median :0.0000</a></li>
<li class="chapter" data-level="2.36" data-path="getting-used-to-r-and-r-studio.html"><a href="getting-used-to-r-and-r-studio.html#mean-3.597-mean-3.217-mean-17.85-mean-0.4375"><i class="fa fa-check"></i><b>2.36</b> Mean :3.597 Mean :3.217 Mean :17.85 Mean :0.4375</a></li>
<li class="chapter" data-level="2.37" data-path="getting-used-to-r-and-r-studio.html"><a href="getting-used-to-r-and-r-studio.html#rd-qu.3.920-3rd-qu.3.610-3rd-qu.18.90-3rd-qu.1.0000"><i class="fa fa-check"></i><b>2.37</b> 3rd Qu.:3.920 3rd Qu.:3.610 3rd Qu.:18.90 3rd Qu.:1.0000</a></li>
<li class="chapter" data-level="2.38" data-path="getting-used-to-r-and-r-studio.html"><a href="getting-used-to-r-and-r-studio.html#max.-4.930-max.-5.424-max.-22.90-max.-1.0000"><i class="fa fa-check"></i><b>2.38</b> Max. :4.930 Max. :5.424 Max. :22.90 Max. :1.0000</a></li>
<li class="chapter" data-level="2.39" data-path="getting-used-to-r-and-r-studio.html"><a href="getting-used-to-r-and-r-studio.html#am-gear-carb"><i class="fa fa-check"></i><b>2.39</b> am gear carb</a></li>
<li class="chapter" data-level="2.40" data-path="getting-used-to-r-and-r-studio.html"><a href="getting-used-to-r-and-r-studio.html#min.-0.0000-min.-3.000-min.-1.000"><i class="fa fa-check"></i><b>2.40</b> Min. :0.0000 Min. :3.000 Min. :1.000</a></li>
<li class="chapter" data-level="2.41" data-path="getting-used-to-r-and-r-studio.html"><a href="getting-used-to-r-and-r-studio.html#st-qu.0.0000-1st-qu.3.000-1st-qu.2.000"><i class="fa fa-check"></i><b>2.41</b> 1st Qu.:0.0000 1st Qu.:3.000 1st Qu.:2.000</a></li>
<li class="chapter" data-level="2.42" data-path="getting-used-to-r-and-r-studio.html"><a href="getting-used-to-r-and-r-studio.html#median-0.0000-median-4.000-median-2.000"><i class="fa fa-check"></i><b>2.42</b> Median :0.0000 Median :4.000 Median :2.000</a></li>
<li class="chapter" data-level="2.43" data-path="getting-used-to-r-and-r-studio.html"><a href="getting-used-to-r-and-r-studio.html#mean-0.4062-mean-3.688-mean-2.812"><i class="fa fa-check"></i><b>2.43</b> Mean :0.4062 Mean :3.688 Mean :2.812</a></li>
<li class="chapter" data-level="2.44" data-path="getting-used-to-r-and-r-studio.html"><a href="getting-used-to-r-and-r-studio.html#rd-qu.1.0000-3rd-qu.4.000-3rd-qu.4.000"><i class="fa fa-check"></i><b>2.44</b> 3rd Qu.:1.0000 3rd Qu.:4.000 3rd Qu.:4.000</a></li>
<li class="chapter" data-level="2.45" data-path="getting-used-to-r-and-r-studio.html"><a href="getting-used-to-r-and-r-studio.html#max.-1.0000-max.-5.000-max.-8.000"><i class="fa fa-check"></i><b>2.45</b> Max. :1.0000 Max. :5.000 Max. :8.000</a></li>
<li class="chapter" data-level="2.46" data-path="getting-used-to-r-and-r-studio.html"><a href="getting-used-to-r-and-r-studio.html#reading-data-from-a-file"><i class="fa fa-check"></i><b>2.46</b> Reading data from a file</a></li>
<li class="chapter" data-level="2.47" data-path="getting-used-to-r-and-r-studio.html"><a href="getting-used-to-r-and-r-studio.html#parsed-with-column-specification"><i class="fa fa-check"></i><b>2.47</b> Parsed with column specification:</a></li>
<li class="chapter" data-level="2.48" data-path="getting-used-to-r-and-r-studio.html"><a href="getting-used-to-r-and-r-studio.html#cols"><i class="fa fa-check"></i><b>2.48</b> cols(</a></li>
<li class="chapter" data-level="2.49" data-path="getting-used-to-r-and-r-studio.html"><a href="getting-used-to-r-and-r-studio.html#group-col_character"><i class="fa fa-check"></i><b>2.49</b> group = col_character(),</a></li>
<li class="chapter" data-level="2.50" data-path="getting-used-to-r-and-r-studio.html"><a href="getting-used-to-r-and-r-studio.html#density-col_integer"><i class="fa fa-check"></i><b>2.50</b> density = col_integer()</a></li>
<li class="chapter" data-level="2.51" data-path="getting-used-to-r-and-r-studio.html"><a href="getting-used-to-r-and-r-studio.html#section-11"><i class="fa fa-check"></i><b>2.51</b> )</a></li>
<li class="chapter" data-level="2.52" data-path="getting-used-to-r-and-r-studio.html"><a href="getting-used-to-r-and-r-studio.html#a-tibble-30-x-2"><i class="fa fa-check"></i><b>2.52</b> # A tibble: 30 x 2</a></li>
<li class="chapter" data-level="2.53" data-path="getting-used-to-r-and-r-studio.html"><a href="getting-used-to-r-and-r-studio.html#group-density"><i class="fa fa-check"></i><b>2.53</b> group density</a></li>
<li class="chapter" data-level="2.54" data-path="getting-used-to-r-and-r-studio.html"><a href="getting-used-to-r-and-r-studio.html#section-12"><i class="fa fa-check"></i><b>2.54</b> <chr> <int></a></li>
<li class="chapter" data-level="2.55" data-path="getting-used-to-r-and-r-studio.html"><a href="getting-used-to-r-and-r-studio.html#control-611"><i class="fa fa-check"></i><b>2.55</b> 1 Control 611</a></li>
<li class="chapter" data-level="2.56" data-path="getting-used-to-r-and-r-studio.html"><a href="getting-used-to-r-and-r-studio.html#control-621"><i class="fa fa-check"></i><b>2.56</b> 2 Control 621</a></li>
<li class="chapter" data-level="2.57" data-path="getting-used-to-r-and-r-studio.html"><a href="getting-used-to-r-and-r-studio.html#control-614"><i class="fa fa-check"></i><b>2.57</b> 3 Control 614</a></li>
<li class="chapter" data-level="2.58" data-path="getting-used-to-r-and-r-studio.html"><a href="getting-used-to-r-and-r-studio.html#control-593"><i class="fa fa-check"></i><b>2.58</b> 4 Control 593</a></li>
<li class="chapter" data-level="2.59" data-path="getting-used-to-r-and-r-studio.html"><a href="getting-used-to-r-and-r-studio.html#control-593-1"><i class="fa fa-check"></i><b>2.59</b> 5 Control 593</a></li>
<li class="chapter" data-level="2.60" data-path="getting-used-to-r-and-r-studio.html"><a href="getting-used-to-r-and-r-studio.html#control-653"><i class="fa fa-check"></i><b>2.60</b> 6 Control 653</a></li>
<li class="chapter" data-level="2.61" data-path="getting-used-to-r-and-r-studio.html"><a href="getting-used-to-r-and-r-studio.html#control-600"><i class="fa fa-check"></i><b>2.61</b> 7 Control 600</a></li>
<li class="chapter" data-level="2.62" data-path="getting-used-to-r-and-r-studio.html"><a href="getting-used-to-r-and-r-studio.html#control-554"><i class="fa fa-check"></i><b>2.62</b> 8 Control 554</a></li>
<li class="chapter" data-level="2.63" data-path="getting-used-to-r-and-r-studio.html"><a href="getting-used-to-r-and-r-studio.html#control-603"><i class="fa fa-check"></i><b>2.63</b> 9 Control 603</a></li>
<li class="chapter" data-level="2.64" data-path="getting-used-to-r-and-r-studio.html"><a href="getting-used-to-r-and-r-studio.html#control-569"><i class="fa fa-check"></i><b>2.64</b> 10 Control 569</a></li>
<li class="chapter" data-level="2.65" data-path="getting-used-to-r-and-r-studio.html"><a href="getting-used-to-r-and-r-studio.html#with-20-more-rows"><i class="fa fa-check"></i><b>2.65</b> # … with 20 more rows</a></li>
<li class="chapter" data-level="2.66" data-path="getting-used-to-r-and-r-studio.html"><a href="getting-used-to-r-and-r-studio.html#a-tibble-3-x-2"><i class="fa fa-check"></i><b>2.66</b> # A tibble: 3 x 2</a></li>
<li class="chapter" data-level="2.67" data-path="getting-used-to-r-and-r-studio.html"><a href="getting-used-to-r-and-r-studio.html#group-m"><i class="fa fa-check"></i><b>2.67</b> group m</a></li>
<li class="chapter" data-level="2.68" data-path="getting-used-to-r-and-r-studio.html"><a href="getting-used-to-r-and-r-studio.html#section-13"><i class="fa fa-check"></i><b>2.68</b> <chr> <dbl></a></li>
<li class="chapter" data-level="2.69" data-path="getting-used-to-r-and-r-studio.html"><a href="getting-used-to-r-and-r-studio.html#control-601."><i class="fa fa-check"></i><b>2.69</b> 1 Control 601.</a></li>
<li class="chapter" data-level="2.70" data-path="getting-used-to-r-and-r-studio.html"><a href="getting-used-to-r-and-r-studio.html#highjump-639."><i class="fa fa-check"></i><b>2.70</b> 2 Highjump 639.</a></li>
<li class="chapter" data-level="2.71" data-path="getting-used-to-r-and-r-studio.html"><a href="getting-used-to-r-and-r-studio.html#lowjump-612."><i class="fa fa-check"></i><b>2.71</b> 3 Lowjump 612.</a></li>
</ul></li>
<li class="chapter" data-level="3" data-path="reading-in-data-and-drawing-some-graphs.html"><a href="reading-in-data-and-drawing-some-graphs.html"><i class="fa fa-check"></i><b>3</b> Reading in data and drawing some graphs</a><ul>
<li class="chapter" data-level="3.1" data-path="reading-in-data-and-drawing-some-graphs.html"><a href="reading-in-data-and-drawing-some-graphs.html#orange-juice"><i class="fa fa-check"></i><b>3.1</b> Orange juice</a></li>
<li class="chapter" data-level="3.2" data-path="reading-in-data-and-drawing-some-graphs.html"><a href="reading-in-data-and-drawing-some-graphs.html#attaching-packages-tidyverse-1.2.1-1"><i class="fa fa-check"></i><b>3.2</b> ── Attaching packages ─────────────────────────────────────────────────────────────────────────────────────── tidyverse 1.2.1 ──</a></li>
<li class="chapter" data-level="3.3" data-path="reading-in-data-and-drawing-some-graphs.html"><a href="reading-in-data-and-drawing-some-graphs.html#ggplot2-3.0.0-purrr-0.2.5-1"><i class="fa fa-check"></i><b>3.3</b> ✔ ggplot2 3.0.0 ✔ purrr 0.2.5</a></li>
<li class="chapter" data-level="3.4" data-path="reading-in-data-and-drawing-some-graphs.html"><a href="reading-in-data-and-drawing-some-graphs.html#tibble-1.4.2-dplyr-0.7.6-1"><i class="fa fa-check"></i><b>3.4</b> ✔ tibble 1.4.2 ✔ dplyr 0.7.6</a></li>
<li class="chapter" data-level="3.5" data-path="reading-in-data-and-drawing-some-graphs.html"><a href="reading-in-data-and-drawing-some-graphs.html#tidyr-0.8.1-stringr-1.3.1-1"><i class="fa fa-check"></i><b>3.5</b> ✔ tidyr 0.8.1 ✔ stringr 1.3.1</a></li>
<li class="chapter" data-level="3.6" data-path="reading-in-data-and-drawing-some-graphs.html"><a href="reading-in-data-and-drawing-some-graphs.html#readr-1.1.1-forcats-0.3.0-1"><i class="fa fa-check"></i><b>3.6</b> ✔ readr 1.1.1 ✔ forcats 0.3.0</a></li>
<li class="chapter" data-level="3.7" data-path="reading-in-data-and-drawing-some-graphs.html"><a href="reading-in-data-and-drawing-some-graphs.html#conflicts-tidyverse_conflicts-1"><i class="fa fa-check"></i><b>3.7</b> ── Conflicts ────────────────────────────────────────────────────────────────────────────────────────── tidyverse_conflicts() ──</a></li>
<li class="chapter" data-level="3.8" data-path="reading-in-data-and-drawing-some-graphs.html"><a href="reading-in-data-and-drawing-some-graphs.html#dplyrfilter-masks-statsfilter-1"><i class="fa fa-check"></i><b>3.8</b> ✖ dplyr::filter() masks stats::filter()</a></li>
<li class="chapter" data-level="3.9" data-path="reading-in-data-and-drawing-some-graphs.html"><a href="reading-in-data-and-drawing-some-graphs.html#dplyrlag-masks-statslag-1"><i class="fa fa-check"></i><b>3.9</b> ✖ dplyr::lag() masks stats::lag()</a></li>
<li class="chapter" data-level="3.10" data-path="reading-in-data-and-drawing-some-graphs.html"><a href="reading-in-data-and-drawing-some-graphs.html#parsed-with-column-specification-1"><i class="fa fa-check"></i><b>3.10</b> Parsed with column specification:</a></li>
<li class="chapter" data-level="3.11" data-path="reading-in-data-and-drawing-some-graphs.html"><a href="reading-in-data-and-drawing-some-graphs.html#cols-1"><i class="fa fa-check"></i><b>3.11</b> cols(</a></li>
<li class="chapter" data-level="3.12" data-path="reading-in-data-and-drawing-some-graphs.html"><a href="reading-in-data-and-drawing-some-graphs.html#run-col_integer"><i class="fa fa-check"></i><b>3.12</b> run = col_integer(),</a></li>
<li class="chapter" data-level="3.13" data-path="reading-in-data-and-drawing-some-graphs.html"><a href="reading-in-data-and-drawing-some-graphs.html#sweetness-col_double"><i class="fa fa-check"></i><b>3.13</b> sweetness = col_double(),</a></li>
<li class="chapter" data-level="3.14" data-path="reading-in-data-and-drawing-some-graphs.html"><a href="reading-in-data-and-drawing-some-graphs.html#pectin-col_integer"><i class="fa fa-check"></i><b>3.14</b> pectin = col_integer()</a></li>
<li class="chapter" data-level="3.15" data-path="reading-in-data-and-drawing-some-graphs.html"><a href="reading-in-data-and-drawing-some-graphs.html#section-14"><i class="fa fa-check"></i><b>3.15</b> )</a></li>
<li class="chapter" data-level="3.16" data-path="reading-in-data-and-drawing-some-graphs.html"><a href="reading-in-data-and-drawing-some-graphs.html#a-tibble-24-x-3"><i class="fa fa-check"></i><b>3.16</b> # A tibble: 24 x 3</a></li>
<li class="chapter" data-level="3.17" data-path="reading-in-data-and-drawing-some-graphs.html"><a href="reading-in-data-and-drawing-some-graphs.html#run-sweetness-pectin"><i class="fa fa-check"></i><b>3.17</b> run sweetness pectin</a></li>
<li class="chapter" data-level="3.18" data-path="reading-in-data-and-drawing-some-graphs.html"><a href="reading-in-data-and-drawing-some-graphs.html#section-15"><i class="fa fa-check"></i><b>3.18</b> <int> <dbl> <int></a></li>
<li class="chapter" data-level="3.19" data-path="reading-in-data-and-drawing-some-graphs.html"><a href="reading-in-data-and-drawing-some-graphs.html#section-16"><i class="fa fa-check"></i><b>3.19</b> 1 1 5.2 220</a></li>
<li class="chapter" data-level="3.20" data-path="reading-in-data-and-drawing-some-graphs.html"><a href="reading-in-data-and-drawing-some-graphs.html#section-17"><i class="fa fa-check"></i><b>3.20</b> 2 2 5.5 227</a></li>
<li class="chapter" data-level="3.21" data-path="reading-in-data-and-drawing-some-graphs.html"><a href="reading-in-data-and-drawing-some-graphs.html#section-18"><i class="fa fa-check"></i><b>3.21</b> 3 3 6 259</a></li>
<li class="chapter" data-level="3.22" data-path="reading-in-data-and-drawing-some-graphs.html"><a href="reading-in-data-and-drawing-some-graphs.html#section-19"><i class="fa fa-check"></i><b>3.22</b> 4 4 5.9 210</a></li>
<li class="chapter" data-level="3.23" data-path="reading-in-data-and-drawing-some-graphs.html"><a href="reading-in-data-and-drawing-some-graphs.html#section-20"><i class="fa fa-check"></i><b>3.23</b> 5 5 5.8 224</a></li>
<li class="chapter" data-level="3.24" data-path="reading-in-data-and-drawing-some-graphs.html"><a href="reading-in-data-and-drawing-some-graphs.html#section-21"><i class="fa fa-check"></i><b>3.24</b> 6 6 6 215</a></li>
<li class="chapter" data-level="3.25" data-path="reading-in-data-and-drawing-some-graphs.html"><a href="reading-in-data-and-drawing-some-graphs.html#section-22"><i class="fa fa-check"></i><b>3.25</b> 7 7 5.8 231</a></li>
<li class="chapter" data-level="3.26" data-path="reading-in-data-and-drawing-some-graphs.html"><a href="reading-in-data-and-drawing-some-graphs.html#section-23"><i class="fa fa-check"></i><b>3.26</b> 8 8 5.6 268</a></li>
<li class="chapter" data-level="3.27" data-path="reading-in-data-and-drawing-some-graphs.html"><a href="reading-in-data-and-drawing-some-graphs.html#section-24"><i class="fa fa-check"></i><b>3.27</b> 9 9 5.6 239</a></li>
<li class="chapter" data-level="3.28" data-path="reading-in-data-and-drawing-some-graphs.html"><a href="reading-in-data-and-drawing-some-graphs.html#section-25"><i class="fa fa-check"></i><b>3.28</b> 10 10 5.9 212</a></li>
<li class="chapter" data-level="3.29" data-path="reading-in-data-and-drawing-some-graphs.html"><a href="reading-in-data-and-drawing-some-graphs.html#with-14-more-rows"><i class="fa fa-check"></i><b>3.29</b> # … with 14 more rows</a></li>
<li class="chapter" data-level="3.30" data-path="reading-in-data-and-drawing-some-graphs.html"><a href="reading-in-data-and-drawing-some-graphs.html#parsed-with-column-specification-2"><i class="fa fa-check"></i><b>3.30</b> Parsed with column specification:</a></li>
<li class="chapter" data-level="3.31" data-path="reading-in-data-and-drawing-some-graphs.html"><a href="reading-in-data-and-drawing-some-graphs.html#cols-2"><i class="fa fa-check"></i><b>3.31</b> cols(</a></li>
<li class="chapter" data-level="3.32" data-path="reading-in-data-and-drawing-some-graphs.html"><a href="reading-in-data-and-drawing-some-graphs.html#x-col_integer"><i class="fa fa-check"></i><b>3.32</b> x = col_integer(),</a></li>
<li class="chapter" data-level="3.33" data-path="reading-in-data-and-drawing-some-graphs.html"><a href="reading-in-data-and-drawing-some-graphs.html#y-col_integer"><i class="fa fa-check"></i><b>3.33</b> y = col_integer()</a></li>
<li class="chapter" data-level="3.34" data-path="reading-in-data-and-drawing-some-graphs.html"><a href="reading-in-data-and-drawing-some-graphs.html#section-26"><i class="fa fa-check"></i><b>3.34</b> )</a></li>
<li class="chapter" data-level="3.35" data-path="reading-in-data-and-drawing-some-graphs.html"><a href="reading-in-data-and-drawing-some-graphs.html#a-tibble-3-x-2-1"><i class="fa fa-check"></i><b>3.35</b> # A tibble: 3 x 2</a></li>
<li class="chapter" data-level="3.36" data-path="reading-in-data-and-drawing-some-graphs.html"><a href="reading-in-data-and-drawing-some-graphs.html#x-y"><i class="fa fa-check"></i><b>3.36</b> x y</a></li>
<li class="chapter" data-level="3.37" data-path="reading-in-data-and-drawing-some-graphs.html"><a href="reading-in-data-and-drawing-some-graphs.html#section-27"><i class="fa fa-check"></i><b>3.37</b> <int> <int></a></li>
<li class="chapter" data-level="3.38" data-path="reading-in-data-and-drawing-some-graphs.html"><a href="reading-in-data-and-drawing-some-graphs.html#section-28"><i class="fa fa-check"></i><b>3.38</b> 1 1 2</a></li>
<li class="chapter" data-level="3.39" data-path="reading-in-data-and-drawing-some-graphs.html"><a href="reading-in-data-and-drawing-some-graphs.html#section-29"><i class="fa fa-check"></i><b>3.39</b> 2 3 4</a></li>
<li class="chapter" data-level="3.40" data-path="reading-in-data-and-drawing-some-graphs.html"><a href="reading-in-data-and-drawing-some-graphs.html#section-30"><i class="fa fa-check"></i><b>3.40</b> 3 5 6</a></li>
<li class="chapter" data-level="3.41" data-path="reading-in-data-and-drawing-some-graphs.html"><a href="reading-in-data-and-drawing-some-graphs.html#geom_smooth-using-method-loess-and-formula-y-x"><i class="fa fa-check"></i><b>3.41</b> <code>geom_smooth()</code> using method = ‘loess’ and formula ‘y ~ x’</a></li>
<li class="chapter" data-level="3.42" data-path="reading-in-data-and-drawing-some-graphs.html"><a href="reading-in-data-and-drawing-some-graphs.html#making-soap"><i class="fa fa-check"></i><b>3.42</b> Making soap</a></li>
<li class="chapter" data-level="3.43" data-path="reading-in-data-and-drawing-some-graphs.html"><a href="reading-in-data-and-drawing-some-graphs.html#parsed-with-column-specification-3"><i class="fa fa-check"></i><b>3.43</b> Parsed with column specification:</a></li>
<li class="chapter" data-level="3.44" data-path="reading-in-data-and-drawing-some-graphs.html"><a href="reading-in-data-and-drawing-some-graphs.html#cols-3"><i class="fa fa-check"></i><b>3.44</b> cols(</a></li>
<li class="chapter" data-level="3.45" data-path="reading-in-data-and-drawing-some-graphs.html"><a href="reading-in-data-and-drawing-some-graphs.html#case-col_integer"><i class="fa fa-check"></i><b>3.45</b> case = col_integer(),</a></li>
<li class="chapter" data-level="3.46" data-path="reading-in-data-and-drawing-some-graphs.html"><a href="reading-in-data-and-drawing-some-graphs.html#scrap-col_integer"><i class="fa fa-check"></i><b>3.46</b> scrap = col_integer(),</a></li>
<li class="chapter" data-level="3.47" data-path="reading-in-data-and-drawing-some-graphs.html"><a href="reading-in-data-and-drawing-some-graphs.html#speed-col_integer"><i class="fa fa-check"></i><b>3.47</b> speed = col_integer(),</a></li>
<li class="chapter" data-level="3.48" data-path="reading-in-data-and-drawing-some-graphs.html"><a href="reading-in-data-and-drawing-some-graphs.html#line-col_character"><i class="fa fa-check"></i><b>3.48</b> line = col_character()</a></li>
<li class="chapter" data-level="3.49" data-path="reading-in-data-and-drawing-some-graphs.html"><a href="reading-in-data-and-drawing-some-graphs.html#section-31"><i class="fa fa-check"></i><b>3.49</b> )</a></li>
<li class="chapter" data-level="3.50" data-path="reading-in-data-and-drawing-some-graphs.html"><a href="reading-in-data-and-drawing-some-graphs.html#a-tibble-27-x-4"><i class="fa fa-check"></i><b>3.50</b> # A tibble: 27 x 4</a></li>
<li class="chapter" data-level="3.51" data-path="reading-in-data-and-drawing-some-graphs.html"><a href="reading-in-data-and-drawing-some-graphs.html#case-scrap-speed-line"><i class="fa fa-check"></i><b>3.51</b> case scrap speed line</a></li>
<li class="chapter" data-level="3.52" data-path="reading-in-data-and-drawing-some-graphs.html"><a href="reading-in-data-and-drawing-some-graphs.html#section-32"><i class="fa fa-check"></i><b>3.52</b> <int> <int> <int> <chr></a></li>
<li class="chapter" data-level="3.53" data-path="reading-in-data-and-drawing-some-graphs.html"><a href="reading-in-data-and-drawing-some-graphs.html#a"><i class="fa fa-check"></i><b>3.53</b> 1 1 218 100 a</a></li>
<li class="chapter" data-level="3.54" data-path="reading-in-data-and-drawing-some-graphs.html"><a href="reading-in-data-and-drawing-some-graphs.html#a-1"><i class="fa fa-check"></i><b>3.54</b> 2 2 248 125 a</a></li>
<li class="chapter" data-level="3.55" data-path="reading-in-data-and-drawing-some-graphs.html"><a href="reading-in-data-and-drawing-some-graphs.html#a-2"><i class="fa fa-check"></i><b>3.55</b> 3 3 360 220 a</a></li>
<li class="chapter" data-level="3.56" data-path="reading-in-data-and-drawing-some-graphs.html"><a href="reading-in-data-and-drawing-some-graphs.html#a-3"><i class="fa fa-check"></i><b>3.56</b> 4 4 351 205 a</a></li>
<li class="chapter" data-level="3.57" data-path="reading-in-data-and-drawing-some-graphs.html"><a href="reading-in-data-and-drawing-some-graphs.html#a-4"><i class="fa fa-check"></i><b>3.57</b> 5 5 470 300 a</a></li>
<li class="chapter" data-level="3.58" data-path="reading-in-data-and-drawing-some-graphs.html"><a href="reading-in-data-and-drawing-some-graphs.html#a-5"><i class="fa fa-check"></i><b>3.58</b> 6 6 394 255 a</a></li>
<li class="chapter" data-level="3.59" data-path="reading-in-data-and-drawing-some-graphs.html"><a href="reading-in-data-and-drawing-some-graphs.html#a-6"><i class="fa fa-check"></i><b>3.59</b> 7 7 332 225 a</a></li>
<li class="chapter" data-level="3.60" data-path="reading-in-data-and-drawing-some-graphs.html"><a href="reading-in-data-and-drawing-some-graphs.html#a-7"><i class="fa fa-check"></i><b>3.60</b> 8 8 321 175 a</a></li>
<li class="chapter" data-level="3.61" data-path="reading-in-data-and-drawing-some-graphs.html"><a href="reading-in-data-and-drawing-some-graphs.html#a-8"><i class="fa fa-check"></i><b>3.61</b> 9 9 410 270 a</a></li>
<li class="chapter" data-level="3.62" data-path="reading-in-data-and-drawing-some-graphs.html"><a href="reading-in-data-and-drawing-some-graphs.html#a-9"><i class="fa fa-check"></i><b>3.62</b> 10 10 260 170 a</a></li>
<li class="chapter" data-level="3.63" data-path="reading-in-data-and-drawing-some-graphs.html"><a href="reading-in-data-and-drawing-some-graphs.html#with-17-more-rows"><i class="fa fa-check"></i><b>3.63</b> # … with 17 more rows</a></li>
<li class="chapter" data-level="3.64" data-path="reading-in-data-and-drawing-some-graphs.html"><a href="reading-in-data-and-drawing-some-graphs.html#section-33"><i class="fa fa-check"></i><b>3.64</b> </a></li>
<li class="chapter" data-level="3.65" data-path="reading-in-data-and-drawing-some-graphs.html"><a href="reading-in-data-and-drawing-some-graphs.html#welch-two-sample-t-test"><i class="fa fa-check"></i><b>3.65</b> Welch Two Sample t-test</a></li>
<li class="chapter" data-level="3.66" data-path="reading-in-data-and-drawing-some-graphs.html"><a href="reading-in-data-and-drawing-some-graphs.html#section-34"><i class="fa fa-check"></i><b>3.66</b> </a></li>
<li class="chapter" data-level="3.67" data-path="reading-in-data-and-drawing-some-graphs.html"><a href="reading-in-data-and-drawing-some-graphs.html#data-scrap-by-line"><i class="fa fa-check"></i><b>3.67</b> data: scrap by line</a></li>
<li class="chapter" data-level="3.68" data-path="reading-in-data-and-drawing-some-graphs.html"><a href="reading-in-data-and-drawing-some-graphs.html#t-1.2493-df-21.087-p-value-0.2253"><i class="fa fa-check"></i><b>3.68</b> t = 1.2493, df = 21.087, p-value = 0.2253</a></li>
<li class="chapter" data-level="3.69" data-path="reading-in-data-and-drawing-some-graphs.html"><a href="reading-in-data-and-drawing-some-graphs.html#alternative-hypothesis-true-difference-in-means-is-not-equal-to-0"><i class="fa fa-check"></i><b>3.69</b> alternative hypothesis: true difference in means is not equal to 0</a></li>
<li class="chapter" data-level="3.70" data-path="reading-in-data-and-drawing-some-graphs.html"><a href="reading-in-data-and-drawing-some-graphs.html#percent-confidence-interval"><i class="fa fa-check"></i><b>3.70</b> 95 percent confidence interval:</a></li>
<li class="chapter" data-level="3.71" data-path="reading-in-data-and-drawing-some-graphs.html"><a href="reading-in-data-and-drawing-some-graphs.html#section-35"><i class="fa fa-check"></i><b>3.71</b> -26.97888 108.21222</a></li>
<li class="chapter" data-level="3.72" data-path="reading-in-data-and-drawing-some-graphs.html"><a href="reading-in-data-and-drawing-some-graphs.html#sample-estimates"><i class="fa fa-check"></i><b>3.72</b> sample estimates:</a></li>
<li class="chapter" data-level="3.73" data-path="reading-in-data-and-drawing-some-graphs.html"><a href="reading-in-data-and-drawing-some-graphs.html#mean-in-group-a-mean-in-group-b"><i class="fa fa-check"></i><b>3.73</b> mean in group a mean in group b</a></li>
<li class="chapter" data-level="3.74" data-path="reading-in-data-and-drawing-some-graphs.html"><a href="reading-in-data-and-drawing-some-graphs.html#section-36"><i class="fa fa-check"></i><b>3.74</b> 333.5333 292.9167</a></li>
<li class="chapter" data-level="3.75" data-path="reading-in-data-and-drawing-some-graphs.html"><a href="reading-in-data-and-drawing-some-graphs.html#section-37"><i class="fa fa-check"></i><b>3.75</b> </a></li>
<li class="chapter" data-level="3.76" data-path="reading-in-data-and-drawing-some-graphs.html"><a href="reading-in-data-and-drawing-some-graphs.html#call"><i class="fa fa-check"></i><b>3.76</b> Call:</a></li>
<li class="chapter" data-level="3.77" data-path="reading-in-data-and-drawing-some-graphs.html"><a href="reading-in-data-and-drawing-some-graphs.html#lmformula-scrap-speed-line-data-soap"><i class="fa fa-check"></i><b>3.77</b> lm(formula = scrap ~ speed + line, data = soap)</a></li>
<li class="chapter" data-level="3.78" data-path="reading-in-data-and-drawing-some-graphs.html"><a href="reading-in-data-and-drawing-some-graphs.html#section-38"><i class="fa fa-check"></i><b>3.78</b> </a></li>
<li class="chapter" data-level="3.79" data-path="reading-in-data-and-drawing-some-graphs.html"><a href="reading-in-data-and-drawing-some-graphs.html#residuals"><i class="fa fa-check"></i><b>3.79</b> Residuals:</a></li>
<li class="chapter" data-level="3.80" data-path="reading-in-data-and-drawing-some-graphs.html"><a href="reading-in-data-and-drawing-some-graphs.html#min-1q-median-3q-max"><i class="fa fa-check"></i><b>3.80</b> Min 1Q Median 3Q Max</a></li>
<li class="chapter" data-level="3.81" data-path="reading-in-data-and-drawing-some-graphs.html"><a href="reading-in-data-and-drawing-some-graphs.html#section-39"><i class="fa fa-check"></i><b>3.81</b> -39.557 -14.161 -0.121 17.518 33.953</a></li>
<li class="chapter" data-level="3.82" data-path="reading-in-data-and-drawing-some-graphs.html"><a href="reading-in-data-and-drawing-some-graphs.html#section-40"><i class="fa fa-check"></i><b>3.82</b> </a></li>
<li class="chapter" data-level="3.83" data-path="reading-in-data-and-drawing-some-graphs.html"><a href="reading-in-data-and-drawing-some-graphs.html#coefficients"><i class="fa fa-check"></i><b>3.83</b> Coefficients:</a></li>
<li class="chapter" data-level="3.84" data-path="reading-in-data-and-drawing-some-graphs.html"><a href="reading-in-data-and-drawing-some-graphs.html#estimate-std.-error-t-value-prt"><i class="fa fa-check"></i><b>3.84</b> Estimate Std. Error t value Pr(&gt;|t|)</a></li>
<li><a href="reading-in-data-and-drawing-some-graphs.html#intercept-80.41099-14.54379-5.529-1.10e-05-speed-1.23074-0.06555-18.775-7.48e-16"><span class="toc-section-number">3.85</span> (Intercept) 80.41099 14.54379 5.529 1.10e-05 <strong><em>
## speed 1.23074 0.06555 18.775 7.48e-16 </em></strong></a></li>
<li><a href="reading-in-data-and-drawing-some-graphs.html#lineb--53.12920-8.21003--6.471-1.08e-06-signif.-codes-0-0.001-0.01-0.05-.-0.1-1-residual-standard-error-21.13-on-24-degrees-of-freedom-multiple-r-squared-0.9402-adjusted-r-squared-0.9352-f-statistic-188.6-on-2-and-24-df-p-value-2.104e-15-handling-shipments-parsed-with-column-specification-cols-warehouse-col_character-size-col_integer-cost-col_double-a-tibble-10-x-3-warehouse-size-cost-1-a-225-12.0-2-b-350-14.1-3-a-150-8.93-4-a-200-11.0-5-a-175-10.0-6-a-180-10.1-7-b-325-13.8-8-b-290-13.3-9-b-400-15-10-a-125-7.97"><span class="toc-section-number">3.86</span> lineb -53.12920 8.21003 -6.471 1.08e-06 ***
## —
## Signif. codes: 0 ‘<em><strong>’ 0.001 ’</strong>’ 0.01 ’</em>’ 0.05 ‘.’ 0.1 ‘’ 1
##
## Residual standard error: 21.13 on 24 degrees of freedom
## Multiple R-squared: 0.9402, Adjusted R-squared: 0.9352
## F-statistic: 188.6 on 2 and 24 DF, p-value: 2.104e-15
## Handling shipments
## Parsed with column specification:
## cols(
## warehouse = col_character(),
## size = col_integer(),
## cost = col_double()
## )
## # A tibble: 10 x 3
## warehouse size cost
## <chr> <int> <dbl>
## 1 A 225 12.0
## 2 B 350 14.1
## 3 A 150 8.93
## 4 A 200 11.0
## 5 A 175 10.0
## 6 A 180 10.1
## 7 B 325 13.8
## 8 B 290 13.3
## 9 B 400 15<br />
## 10 A 125 7.97</a></li>
</ul></li>
<li class="chapter" data-level="4" data-path="data-exploration.html"><a href="data-exploration.html"><i class="fa fa-check"></i><b>4</b> Data exploration</a><ul>
<li class="chapter" data-level="4.1" data-path="data-exploration.html"><a href="data-exploration.html#attaching-packages-tidyverse-1.2.1-2"><i class="fa fa-check"></i><b>4.1</b> ── Attaching packages ─────────────────────────────────────────────────────────────────────────────────────── tidyverse 1.2.1 ──</a></li>
<li class="chapter" data-level="4.2" data-path="data-exploration.html"><a href="data-exploration.html#ggplot2-3.0.0-purrr-0.2.5-2"><i class="fa fa-check"></i><b>4.2</b> ✔ ggplot2 3.0.0 ✔ purrr 0.2.5</a></li>
<li class="chapter" data-level="4.3" data-path="data-exploration.html"><a href="data-exploration.html#tibble-1.4.2-dplyr-0.7.6-2"><i class="fa fa-check"></i><b>4.3</b> ✔ tibble 1.4.2 ✔ dplyr 0.7.6</a></li>
<li class="chapter" data-level="4.4" data-path="data-exploration.html"><a href="data-exploration.html#tidyr-0.8.1-stringr-1.3.1-2"><i class="fa fa-check"></i><b>4.4</b> ✔ tidyr 0.8.1 ✔ stringr 1.3.1</a></li>
<li class="chapter" data-level="4.5" data-path="data-exploration.html"><a href="data-exploration.html#readr-1.1.1-forcats-0.3.0-2"><i class="fa fa-check"></i><b>4.5</b> ✔ readr 1.1.1 ✔ forcats 0.3.0</a></li>
<li class="chapter" data-level="4.6" data-path="data-exploration.html"><a href="data-exploration.html#conflicts-tidyverse_conflicts-2"><i class="fa fa-check"></i><b>4.6</b> ── Conflicts ────────────────────────────────────────────────────────────────────────────────────────── tidyverse_conflicts() ──</a></li>
<li class="chapter" data-level="4.7" data-path="data-exploration.html"><a href="data-exploration.html#dplyrfilter-masks-statsfilter-2"><i class="fa fa-check"></i><b>4.7</b> ✖ dplyr::filter() masks stats::filter()</a></li>
<li class="chapter" data-level="4.8" data-path="data-exploration.html"><a href="data-exploration.html#dplyrlag-masks-statslag-2"><i class="fa fa-check"></i><b>4.8</b> ✖ dplyr::lag() masks stats::lag()</a></li>
<li class="chapter" data-level="4.9" data-path="data-exploration.html"><a href="data-exploration.html#north-carolina-births"><i class="fa fa-check"></i><b>4.9</b> North Carolina births</a></li>
<li class="chapter" data-level="4.10" data-path="data-exploration.html"><a href="data-exploration.html#parsed-with-column-specification-4"><i class="fa fa-check"></i><b>4.10</b> Parsed with column specification:</a></li>
<li class="chapter" data-level="4.11" data-path="data-exploration.html"><a href="data-exploration.html#cols-4"><i class="fa fa-check"></i><b>4.11</b> cols(</a></li>
<li class="chapter" data-level="4.12" data-path="data-exploration.html"><a href="data-exploration.html#father-age-col_integer"><i class="fa fa-check"></i><b>4.12</b> <code>Father Age</code> = col_integer(),</a></li>
<li class="chapter" data-level="4.13" data-path="data-exploration.html"><a href="data-exploration.html#mother-age-col_integer"><i class="fa fa-check"></i><b>4.13</b> <code>Mother Age</code> = col_integer(),</a></li>
<li class="chapter" data-level="4.14" data-path="data-exploration.html"><a href="data-exploration.html#weeks-gestation-col_integer"><i class="fa fa-check"></i><b>4.14</b> <code>Weeks Gestation</code> = col_integer(),</a></li>
<li class="chapter" data-level="4.15" data-path="data-exploration.html"><a href="data-exploration.html#pre-natal-visits-col_integer"><i class="fa fa-check"></i><b>4.15</b> <code>Pre-natal Visits</code> = col_integer(),</a></li>
<li class="chapter" data-level="4.16" data-path="data-exploration.html"><a href="data-exploration.html#marital-status-col_integer"><i class="fa fa-check"></i><b>4.16</b> <code>Marital Status</code> = col_integer(),</a></li>
<li class="chapter" data-level="4.17" data-path="data-exploration.html"><a href="data-exploration.html#mother-weight-gained-col_integer"><i class="fa fa-check"></i><b>4.17</b> <code>Mother Weight Gained</code> = col_integer(),</a></li>
<li class="chapter" data-level="4.18" data-path="data-exploration.html"><a href="data-exploration.html#low-birthweight-col_integer"><i class="fa fa-check"></i><b>4.18</b> <code>Low Birthweight?</code> = col_integer(),</a></li>
<li class="chapter" data-level="4.19" data-path="data-exploration.html"><a href="data-exploration.html#weight-pounds-col_double"><i class="fa fa-check"></i><b>4.19</b> <code>Weight (pounds)</code> = col_double(),</a></li>
<li class="chapter" data-level="4.20" data-path="data-exploration.html"><a href="data-exploration.html#premie-col_integer"><i class="fa fa-check"></i><b>4.20</b> <code>Premie?</code> = col_integer(),</a></li>
<li class="chapter" data-level="4.21" data-path="data-exploration.html"><a href="data-exploration.html#few-visits-col_integer"><i class="fa fa-check"></i><b>4.21</b> <code>Few Visits?</code> = col_integer()</a></li>
<li class="chapter" data-level="4.22" data-path="data-exploration.html"><a href="data-exploration.html#section-41"><i class="fa fa-check"></i><b>4.22</b> )</a></li>
<li class="chapter" data-level="4.23" data-path="data-exploration.html"><a href="data-exploration.html#a-tibble-500-x-10"><i class="fa fa-check"></i><b>4.23</b> # A tibble: 500 x 10</a></li>
<li class="chapter" data-level="4.24" data-path="data-exploration.html"><a href="data-exploration.html#father-age-mother-age-weeks-gestatiopre-natal-visi"><i class="fa fa-check"></i><b>4.24</b> <code>Father Age</code> <code>Mother Age</code> <code>Weeks Gestatio…</code>Pre-natal Visi…</a></li>
<li class="chapter" data-level="4.25" data-path="data-exploration.html"><a href="data-exploration.html#section-42"><i class="fa fa-check"></i><b>4.25</b> <int> <int> <int> <int></a></li>
<li class="chapter" data-level="4.26" data-path="data-exploration.html"><a href="data-exploration.html#section-43"><i class="fa fa-check"></i><b>4.26</b> 1 27 26 38 14</a></li>
<li class="chapter" data-level="4.27" data-path="data-exploration.html"><a href="data-exploration.html#section-44"><i class="fa fa-check"></i><b>4.27</b> 2 35 33 40 11</a></li>
<li class="chapter" data-level="4.28" data-path="data-exploration.html"><a href="data-exploration.html#section-45"><i class="fa fa-check"></i><b>4.28</b> 3 34 22 37 10</a></li>
<li class="chapter" data-level="4.29" data-path="data-exploration.html"><a href="data-exploration.html#na-16-38-9"><i class="fa fa-check"></i><b>4.29</b> 4 NA 16 38 9</a></li>
<li class="chapter" data-level="4.30" data-path="data-exploration.html"><a href="data-exploration.html#section-46"><i class="fa fa-check"></i><b>4.30</b> 5 35 33 39 12</a></li>
<li class="chapter" data-level="4.31" data-path="data-exploration.html"><a href="data-exploration.html#section-47"><i class="fa fa-check"></i><b>4.31</b> 6 32 24 36 12</a></li>
<li class="chapter" data-level="4.32" data-path="data-exploration.html"><a href="data-exploration.html#section-48"><i class="fa fa-check"></i><b>4.32</b> 7 33 33 38 15</a></li>
<li class="chapter" data-level="4.33" data-path="data-exploration.html"><a href="data-exploration.html#section-49"><i class="fa fa-check"></i><b>4.33</b> 8 38 35 38 16</a></li>
<li class="chapter" data-level="4.34" data-path="data-exploration.html"><a href="data-exploration.html#section-50"><i class="fa fa-check"></i><b>4.34</b> 9 28 29 40 5</a></li>
<li class="chapter" data-level="4.35" data-path="data-exploration.html"><a href="data-exploration.html#na-19-34-10"><i class="fa fa-check"></i><b>4.35</b> 10 NA 19 34 10</a></li>
<li class="chapter" data-level="4.36" data-path="data-exploration.html"><a href="data-exploration.html#with-490-more-rows-and-6-more-variables-marital-status"><i class="fa fa-check"></i><b>4.36</b> # … with 490 more rows, and 6 more variables: <code>Marital Status</code> <int>,</a></li>
<li class="chapter" data-level="4.37" data-path="data-exploration.html"><a href="data-exploration.html#mother-weight-gained-low-birthweight-weight-pounds-premie-few-visits"><i class="fa fa-check"></i><b>4.37</b> # <code>Mother Weight Gained</code> <int>, <code>Low Birthweight?</code> <int>, <code>Weight ## #   (pounds)</code> <dbl>, <code>Premie?</code> <int>, <code>Few Visits?</code> <int></a></li>
<li class="chapter" data-level="4.38" data-path="data-exploration.html"><a href="data-exploration.html#observations-500"><i class="fa fa-check"></i><b>4.38</b> Observations: 500</a></li>
<li class="chapter" data-level="4.39" data-path="data-exploration.html"><a href="data-exploration.html#variables-10"><i class="fa fa-check"></i><b>4.39</b> Variables: 10</a></li>
<li class="chapter" data-level="4.40" data-path="data-exploration.html"><a href="data-exploration.html#father-age-27-35-34-na-35-32-33-38-28-na"><i class="fa fa-check"></i><b>4.40</b> $ <code>Father Age</code> <int> 27, 35, 34, NA, 35, 32, 33, 38, 28, NA,…</a></li>
<li class="chapter" data-level="4.41" data-path="data-exploration.html"><a href="data-exploration.html#mother-age-26-33-22-16-33-24-33-35-29-19"><i class="fa fa-check"></i><b>4.41</b> $ <code>Mother Age</code> <int> 26, 33, 22, 16, 33, 24, 33, 35, 29, 19,…</a></li>
<li class="chapter" data-level="4.42" data-path="data-exploration.html"><a href="data-exploration.html#weeks-gestation-38-40-37-38-39-36-38-38-40-34"><i class="fa fa-check"></i><b>4.42</b> $ <code>Weeks Gestation</code> <int> 38, 40, 37, 38, 39, 36, 38, 38, 40, 34,…</a></li>
<li class="chapter" data-level="4.43" data-path="data-exploration.html"><a href="data-exploration.html#pre-natal-visits-14-11-10-9-12-12-15-16-5-10-1"><i class="fa fa-check"></i><b>4.43</b> $ <code>Pre-natal Visits</code> <int> 14, 11, 10, 9, 12, 12, 15, 16, 5, 10, 1…</a></li>
<li class="chapter" data-level="4.44" data-path="data-exploration.html"><a href="data-exploration.html#marital-status-1-1-2-2-1-1-2-1-1-2-1-1-2"><i class="fa fa-check"></i><b>4.44</b> $ <code>Marital Status</code> <int> 1, 1, 2, 2, 1, 1, 2, 1, 1, 2, 1, 1, 2, …</a></li>
<li class="chapter" data-level="4.45" data-path="data-exploration.html"><a href="data-exploration.html#mother-weight-gained-32-23-50-na-15-12-60-2-20-na"><i class="fa fa-check"></i><b>4.45</b> $ <code>Mother Weight Gained</code> <int> 32, 23, 50, NA, 15, 12, 60, 2, 20, NA, …</a></li>
<li class="chapter" data-level="4.46" data-path="data-exploration.html"><a href="data-exploration.html#low-birthweight-0-0-0-0-0-0-0-0-0-1-0-0-0"><i class="fa fa-check"></i><b>4.46</b> $ <code>Low Birthweight?</code> <int> 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, …</a></li>
<li class="chapter" data-level="4.47" data-path="data-exploration.html"><a href="data-exploration.html#weight-pounds-6.8750-6.8125-7.2500-8.8125-8.8125"><i class="fa fa-check"></i><b>4.47</b> $ <code>Weight (pounds)</code> <dbl> 6.8750, 6.8125, 7.2500, 8.8125, 8.8125,…</a></li>
<li class="chapter" data-level="4.48" data-path="data-exploration.html"><a href="data-exploration.html#premie-0-0-0-0-0-1-0-0-0-1-0-0-1"><i class="fa fa-check"></i><b>4.48</b> $ <code>Premie?</code> <int> 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, …</a></li>
<li class="chapter" data-level="4.49" data-path="data-exploration.html"><a href="data-exploration.html#few-visits-0-0-0-0-0-0-0-0-1-0-0-0-1"><i class="fa fa-check"></i><b>4.49</b> $ <code>Few Visits?</code> <int> 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, …</a></li>
<li class="chapter" data-level="4.50" data-path="data-exploration.html"><a href="data-exploration.html#section-51"><i class="fa fa-check"></i><b>4.50</b> [1] 10</a></li>
<li class="chapter" data-level="4.51" data-path="data-exploration.html"><a href="data-exploration.html#section-52"><i class="fa fa-check"></i><b>4.51</b> [1] 0.4094743</a></li>
<li class="chapter" data-level="4.52" data-path="data-exploration.html"><a href="data-exploration.html#section-53"><i class="fa fa-check"></i><b>4.52</b> [1] 26</a></li>
<li class="chapter" data-level="4.53" data-path="data-exploration.html"><a href="data-exploration.html#more-about-the-nc-births"><i class="fa fa-check"></i><b>4.53</b> More about the NC births</a></li>
<li class="chapter" data-level="4.54" data-path="data-exploration.html"><a href="data-exploration.html#warning-removed-1-rows-containing-non-finite-values-stat_boxplot."><i class="fa fa-check"></i><b>4.54</b> Warning: Removed 1 rows containing non-finite values (stat_boxplot).</a></li>
<li class="chapter" data-level="4.55" data-path="data-exploration.html"><a href="data-exploration.html#warning-removed-1-rows-containing-missing-values-geom_point."><i class="fa fa-check"></i><b>4.55</b> Warning: Removed 1 rows containing missing values (geom_point).</a></li>
<li class="chapter" data-level="4.56" data-path="data-exploration.html"><a href="data-exploration.html#a-tibble-1-x-3"><i class="fa fa-check"></i><b>4.56</b> # A tibble: 1 x 3</a></li>
<li class="chapter" data-level="4.57" data-path="data-exploration.html"><a href="data-exploration.html#n-min-max"><i class="fa fa-check"></i><b>4.57</b> n min max</a></li>
<li class="chapter" data-level="4.58" data-path="data-exploration.html"><a href="data-exploration.html#section-54"><i class="fa fa-check"></i><b>4.58</b> <int> <dbl> <dbl></a></li>
<li class="chapter" data-level="4.59" data-path="data-exploration.html"><a href="data-exploration.html#na-na"><i class="fa fa-check"></i><b>4.59</b> 1 500 NA NA</a></li>
<li class="chapter" data-level="4.60" data-path="data-exploration.html"><a href="data-exploration.html#a-tibble-3-x-4"><i class="fa fa-check"></i><b>4.60</b> # A tibble: 3 x 4</a></li>
<li class="chapter" data-level="4.61" data-path="data-exploration.html"><a href="data-exploration.html#premie-n-min-max"><i class="fa fa-check"></i><b>4.61</b> <code>Premie?</code> n min max</a></li>
<li class="chapter" data-level="4.62" data-path="data-exploration.html"><a href="data-exploration.html#section-55"><i class="fa fa-check"></i><b>4.62</b> <int> <int> <dbl> <dbl></a></li>
<li class="chapter" data-level="4.63" data-path="data-exploration.html"><a href="data-exploration.html#section-56"><i class="fa fa-check"></i><b>4.63</b> 1 0 424 37 45</a></li>
<li class="chapter" data-level="4.64" data-path="data-exploration.html"><a href="data-exploration.html#section-57"><i class="fa fa-check"></i><b>4.64</b> 2 1 75 20 36</a></li>
<li class="chapter" data-level="4.65" data-path="data-exploration.html"><a href="data-exploration.html#na-1-na-na"><i class="fa fa-check"></i><b>4.65</b> 3 NA 1 NA NA</a></li>
<li class="chapter" data-level="4.66" data-path="data-exploration.html"><a href="data-exploration.html#a-tibble-10-x-2"><i class="fa fa-check"></i><b>4.66</b> # A tibble: 10 x 2</a></li>
<li class="chapter" data-level="4.67" data-path="data-exploration.html"><a href="data-exploration.html#name-value"><i class="fa fa-check"></i><b>4.67</b> name value</a></li>
<li class="chapter" data-level="4.68" data-path="data-exploration.html"><a href="data-exploration.html#section-58"><i class="fa fa-check"></i><b>4.68</b> <chr> <dbl></a></li>
<li class="chapter" data-level="4.69" data-path="data-exploration.html"><a href="data-exploration.html#father-age-33"><i class="fa fa-check"></i><b>4.69</b> 1 Father Age 33</a></li>
<li class="chapter" data-level="4.70" data-path="data-exploration.html"><a href="data-exploration.html#mother-age-32"><i class="fa fa-check"></i><b>4.70</b> 2 Mother Age 32</a></li>
<li class="chapter" data-level="4.71" data-path="data-exploration.html"><a href="data-exploration.html#weeks-gestation-na"><i class="fa fa-check"></i><b>4.71</b> 3 Weeks Gestation NA</a></li>
<li class="chapter" data-level="4.72" data-path="data-exploration.html"><a href="data-exploration.html#pre-natal-visits-9"><i class="fa fa-check"></i><b>4.72</b> 4 Pre-natal Visits 9</a></li>
<li class="chapter" data-level="4.73" data-path="data-exploration.html"><a href="data-exploration.html#marital-status-1"><i class="fa fa-check"></i><b>4.73</b> 5 Marital Status 1</a></li>
<li class="chapter" data-level="4.74" data-path="data-exploration.html"><a href="data-exploration.html#mother-weight-gained-25"><i class="fa fa-check"></i><b>4.74</b> 6 Mother Weight Gained 25</a></li>
<li class="chapter" data-level="4.75" data-path="data-exploration.html"><a href="data-exploration.html#low-birthweight-0"><i class="fa fa-check"></i><b>4.75</b> 7 Low Birthweight? 0</a></li>
<li class="chapter" data-level="4.76" data-path="data-exploration.html"><a href="data-exploration.html#weight-pounds-7.19"><i class="fa fa-check"></i><b>4.76</b> 8 Weight (pounds) 7.19</a></li>
<li class="chapter" data-level="4.77" data-path="data-exploration.html"><a href="data-exploration.html#premie-na"><i class="fa fa-check"></i><b>4.77</b> 9 Premie? NA</a></li>
<li class="chapter" data-level="4.78" data-path="data-exploration.html"><a href="data-exploration.html#few-visits-0"><i class="fa fa-check"></i><b>4.78</b> 10 Few Visits? 0</a></li>
<li class="chapter" data-level="4.79" data-path="data-exploration.html"><a href="data-exploration.html#warning-removed-1-rows-containing-missing-values-geom_point.-1"><i class="fa fa-check"></i><b>4.79</b> Warning: Removed 1 rows containing missing values (geom_point).</a></li>
<li class="chapter" data-level="4.80" data-path="data-exploration.html"><a href="data-exploration.html#warning-removed-1-rows-containing-missing-values-geom_point.-2"><i class="fa fa-check"></i><b>4.80</b> Warning: Removed 1 rows containing missing values (geom_point).</a></li>
<li class="chapter" data-level="4.81" data-path="data-exploration.html"><a href="data-exploration.html#warning-removed-1-rows-containing-missing-values-geom_point.-3"><i class="fa fa-check"></i><b>4.81</b> Warning: Removed 1 rows containing missing values (geom_point).</a></li>
<li class="chapter" data-level="4.82" data-path="data-exploration.html"><a href="data-exploration.html#nenana-alaska"><i class="fa fa-check"></i><b>4.82</b> Nenana, Alaska</a></li>
<li class="chapter" data-level="4.83" data-path="data-exploration.html"><a href="data-exploration.html#parsed-with-column-specification-5"><i class="fa fa-check"></i><b>4.83</b> Parsed with column specification:</a></li>
<li class="chapter" data-level="4.84" data-path="data-exploration.html"><a href="data-exploration.html#cols-5"><i class="fa fa-check"></i><b>4.84</b> cols(</a></li>
<li class="chapter" data-level="4.85" data-path="data-exploration.html"><a href="data-exploration.html#year-col_integer"><i class="fa fa-check"></i><b>4.85</b> Year = col_integer(),</a></li>
<li class="chapter" data-level="4.86" data-path="data-exploration.html"><a href="data-exploration.html#juliandate-col_double"><i class="fa fa-check"></i><b>4.86</b> JulianDate = col_double(),</a></li>
<li class="chapter" data-level="4.87" data-path="data-exploration.html"><a href="data-exploration.html#datetime-col_character"><i class="fa fa-check"></i><b>4.87</b> <code>Date&amp;Time</code> = col_character()</a></li>
<li class="chapter" data-level="4.88" data-path="data-exploration.html"><a href="data-exploration.html#section-59"><i class="fa fa-check"></i><b>4.88</b> )</a></li>
<li class="chapter" data-level="4.89" data-path="data-exploration.html"><a href="data-exploration.html#parsed-with-column-specification-6"><i class="fa fa-check"></i><b>4.89</b> Parsed with column specification:</a></li>
<li class="chapter" data-level="4.90" data-path="data-exploration.html"><a href="data-exploration.html#cols-6"><i class="fa fa-check"></i><b>4.90</b> cols(</a></li>
<li class="chapter" data-level="4.91" data-path="data-exploration.html"><a href="data-exploration.html#year-juliandate-datetime-col_character"><i class="fa fa-check"></i><b>4.91</b> <code>Year  JulianDate  Date&amp;Time</code> = col_character()</a></li>
<li class="chapter" data-level="4.92" data-path="data-exploration.html"><a href="data-exploration.html#section-60"><i class="fa fa-check"></i><b>4.92</b> )</a></li>
<li class="chapter" data-level="4.93" data-path="data-exploration.html"><a href="data-exploration.html#warning-in-rbindnamesprobs-probs_f-number-of-columns-of-result-is-not"><i class="fa fa-check"></i><b>4.93</b> Warning in rbind(names(probs), probs_f): number of columns of result is not</a></li>
<li class="chapter" data-level="4.94" data-path="data-exploration.html"><a href="data-exploration.html#a-multiple-of-vector-length-arg-1"><i class="fa fa-check"></i><b>4.94</b> a multiple of vector length (arg 1)</a></li>
<li class="chapter" data-level="4.95" data-path="data-exploration.html"><a href="data-exploration.html#warning-87-parsing-failures."><i class="fa fa-check"></i><b>4.95</b> Warning: 87 parsing failures.</a></li>
<li class="chapter" data-level="4.96" data-path="data-exploration.html"><a href="data-exploration.html#row-a-tibble-5-x-5-col-row-col-expected-actual-file-expected-actual-1-1-1-columns-5-columns-httpwww.utsc.utoronto.cabutlerc3-file-2-2-1-columns-5-columns-httpwww.utsc.utoronto.cabutlerc3-row-3-3-1-columns-5-columns-httpwww.utsc.utoronto.cabutlerc3-col-4-4-1-columns-5-columns-httpwww.utsc.utoronto.cabutlerc3-expected-5-5-1-columns-5-columns-httpwww.utsc.utoronto.cabutlerc3"><i class="fa fa-check"></i><b>4.96</b> row # A tibble: 5 x 5 col row col expected actual file expected <int> <chr> <chr> <chr> <chr> actual 1 1 <NA> 1 columns 5 columns ’<a href="http://www.utsc.utoronto.ca/~butler/c3" class="uri">http://www.utsc.utoronto.ca/~butler/c3</a>… file 2 2 <NA> 1 columns 5 columns ’<a href="http://www.utsc.utoronto.ca/~butler/c3" class="uri">http://www.utsc.utoronto.ca/~butler/c3</a>… row 3 3 <NA> 1 columns 5 columns ’<a href="http://www.utsc.utoronto.ca/~butler/c3" class="uri">http://www.utsc.utoronto.ca/~butler/c3</a>… col 4 4 <NA> 1 columns 5 columns ’<a href="http://www.utsc.utoronto.ca/~butler/c3" class="uri">http://www.utsc.utoronto.ca/~butler/c3</a>… expected 5 5 <NA> 1 columns 5 columns ’<a href="http://www.utsc.utoronto.ca/~butler/c3" class="uri">http://www.utsc.utoronto.ca/~butler/c3</a>…</a></li>
<li class="chapter" data-level="4.97" data-path="data-exploration.html"><a href="data-exploration.html#section-61"><i class="fa fa-check"></i><b>4.97</b> … …………….. … ……………………………………………………………….. …….. ……………………………………………………………….. …… ……………………………………………………………….. …. ……………………………………………………………….. … ……………………………………………………………….. … ……………………………………………………………….. …….. ………………………………………………………………..</a></li>
<li class="chapter" data-level="4.98" data-path="data-exploration.html"><a href="data-exploration.html#see-problems-for-more-details."><i class="fa fa-check"></i><b>4.98</b> See problems(…) for more details.</a></li>
<li class="chapter" data-level="4.99" data-path="data-exploration.html"><a href="data-exploration.html#a-tibble-87-x-1"><i class="fa fa-check"></i><b>4.99</b> # A tibble: 87 x 1</a></li>
<li class="chapter" data-level="4.100" data-path="data-exploration.html"><a href="data-exploration.html#yeartjuliandatetdatetime"><i class="fa fa-check"></i><b>4.100</b> <code>Year\tJulianDate\tDate&amp;Time</code></a></li>
<li class="chapter" data-level="4.101" data-path="data-exploration.html"><a href="data-exploration.html#section-62"><i class="fa fa-check"></i><b>4.101</b> <chr></a></li>
<li class="chapter" data-level="4.102" data-path="data-exploration.html"><a href="data-exploration.html#section-63"><i class="fa fa-check"></i><b>4.102</b> 1 “1917120.4795”</a></li>
<li class="chapter" data-level="4.103" data-path="data-exploration.html"><a href="data-exploration.html#section-64"><i class="fa fa-check"></i><b>4.103</b> 2 “1918131.3983”</a></li>
<li class="chapter" data-level="4.104" data-path="data-exploration.html"><a href="data-exploration.html#section-65"><i class="fa fa-check"></i><b>4.104</b> 3 “1919123.6066”</a></li>
<li class="chapter" data-level="4.105" data-path="data-exploration.html"><a href="data-exploration.html#section-66"><i class="fa fa-check"></i><b>4.105</b> 4 “1920132.4490”</a></li>
<li class="chapter" data-level="4.106" data-path="data-exploration.html"><a href="data-exploration.html#section-67"><i class="fa fa-check"></i><b>4.106</b> 5 “1921131.2795”</a></li>
<li class="chapter" data-level="4.107" data-path="data-exploration.html"><a href="data-exploration.html#section-68"><i class="fa fa-check"></i><b>4.107</b> 6 “1922132.5559”</a></li>
<li class="chapter" data-level="4.108" data-path="data-exploration.html"><a href="data-exploration.html#section-69"><i class="fa fa-check"></i><b>4.108</b> 7 “1923129.0837”</a></li>
<li class="chapter" data-level="4.109" data-path="data-exploration.html"><a href="data-exploration.html#section-70"><i class="fa fa-check"></i><b>4.109</b> 8 “1924132.6323”</a></li>
<li class="chapter" data-level="4.110" data-path="data-exploration.html"><a href="data-exploration.html#section-71"><i class="fa fa-check"></i><b>4.110</b> 9 “1925127.7726”</a></li>
<li class="chapter" data-level="4.111" data-path="data-exploration.html"><a href="data-exploration.html#section-72"><i class="fa fa-check"></i><b>4.111</b> 10 “1926116.6691”</a></li>
<li class="chapter" data-level="4.112" data-path="data-exploration.html"><a href="data-exploration.html#with-77-more-rows"><i class="fa fa-check"></i><b>4.112</b> # … with 77 more rows</a></li>
<li class="chapter" data-level="4.113" data-path="data-exploration.html"><a href="data-exploration.html#a-tibble-87-x-5"><i class="fa fa-check"></i><b>4.113</b> # A tibble: 87 x 5</a></li>
<li class="chapter" data-level="4.114" data-path="data-exploration.html"><a href="data-exploration.html#row-col-expected-actual-file"><i class="fa fa-check"></i><b>4.114</b> row col expected actual file</a></li>
<li class="chapter" data-level="4.115" data-path="data-exploration.html"><a href="data-exploration.html#section-73"><i class="fa fa-check"></i><b>4.115</b> <int> <chr> <chr> <chr> <chr></a></li>
<li class="chapter" data-level="4.116" data-path="data-exploration.html"><a href="data-exploration.html#columns-5-colum-httpwww.utsc.utoronto.cabutlerc3"><i class="fa fa-check"></i><b>4.116</b> 1 1 <NA> 1 columns 5 colum… ’<a href="http://www.utsc.utoronto.ca/~butler/c3" class="uri">http://www.utsc.utoronto.ca/~butler/c3</a>…</a></li>
<li class="chapter" data-level="4.117" data-path="data-exploration.html"><a href="data-exploration.html#columns-5-colum-httpwww.utsc.utoronto.cabutlerc3-1"><i class="fa fa-check"></i><b>4.117</b> 2 2 <NA> 1 columns 5 colum… ’<a href="http://www.utsc.utoronto.ca/~butler/c3" class="uri">http://www.utsc.utoronto.ca/~butler/c3</a>…</a></li>
<li class="chapter" data-level="4.118" data-path="data-exploration.html"><a href="data-exploration.html#columns-5-colum-httpwww.utsc.utoronto.cabutlerc3-2"><i class="fa fa-check"></i><b>4.118</b> 3 3 <NA> 1 columns 5 colum… ’<a href="http://www.utsc.utoronto.ca/~butler/c3" class="uri">http://www.utsc.utoronto.ca/~butler/c3</a>…</a></li>
<li class="chapter" data-level="4.119" data-path="data-exploration.html"><a href="data-exploration.html#columns-5-colum-httpwww.utsc.utoronto.cabutlerc3-3"><i class="fa fa-check"></i><b>4.119</b> 4 4 <NA> 1 columns 5 colum… ’<a href="http://www.utsc.utoronto.ca/~butler/c3" class="uri">http://www.utsc.utoronto.ca/~butler/c3</a>…</a></li>
<li class="chapter" data-level="4.120" data-path="data-exploration.html"><a href="data-exploration.html#columns-5-colum-httpwww.utsc.utoronto.cabutlerc3-4"><i class="fa fa-check"></i><b>4.120</b> 5 5 <NA> 1 columns 5 colum… ’<a href="http://www.utsc.utoronto.ca/~butler/c3" class="uri">http://www.utsc.utoronto.ca/~butler/c3</a>…</a></li>
<li class="chapter" data-level="4.121" data-path="data-exploration.html"><a href="data-exploration.html#columns-5-colum-httpwww.utsc.utoronto.cabutlerc3-5"><i class="fa fa-check"></i><b>4.121</b> 6 6 <NA> 1 columns 5 colum… ’<a href="http://www.utsc.utoronto.ca/~butler/c3" class="uri">http://www.utsc.utoronto.ca/~butler/c3</a>…</a></li>
<li class="chapter" data-level="4.122" data-path="data-exploration.html"><a href="data-exploration.html#columns-5-colum-httpwww.utsc.utoronto.cabutlerc3-6"><i class="fa fa-check"></i><b>4.122</b> 7 7 <NA> 1 columns 5 colum… ’<a href="http://www.utsc.utoronto.ca/~butler/c3" class="uri">http://www.utsc.utoronto.ca/~butler/c3</a>…</a></li>
<li class="chapter" data-level="4.123" data-path="data-exploration.html"><a href="data-exploration.html#columns-5-colum-httpwww.utsc.utoronto.cabutlerc3-7"><i class="fa fa-check"></i><b>4.123</b> 8 8 <NA> 1 columns 5 colum… ’<a href="http://www.utsc.utoronto.ca/~butler/c3" class="uri">http://www.utsc.utoronto.ca/~butler/c3</a>…</a></li>
<li class="chapter" data-level="4.124" data-path="data-exploration.html"><a href="data-exploration.html#columns-5-colum-httpwww.utsc.utoronto.cabutlerc3-8"><i class="fa fa-check"></i><b>4.124</b> 9 9 <NA> 1 columns 5 colum… ’<a href="http://www.utsc.utoronto.ca/~butler/c3" class="uri">http://www.utsc.utoronto.ca/~butler/c3</a>…</a></li>
<li class="chapter" data-level="4.125" data-path="data-exploration.html"><a href="data-exploration.html#columns-5-colum-httpwww.utsc.utoronto.cabutlerc3-9"><i class="fa fa-check"></i><b>4.125</b> 10 10 <NA> 1 columns 5 colum… ’<a href="http://www.utsc.utoronto.ca/~butler/c3" class="uri">http://www.utsc.utoronto.ca/~butler/c3</a>…</a></li>
<li class="chapter" data-level="4.126" data-path="data-exploration.html"><a href="data-exploration.html#with-77-more-rows-1"><i class="fa fa-check"></i><b>4.126</b> # … with 77 more rows</a></li>
<li class="chapter" data-level="4.127" data-path="data-exploration.html"><a href="data-exploration.html#a-tibble-87-x-3"><i class="fa fa-check"></i><b>4.127</b> # A tibble: 87 x 3</a></li>
<li class="chapter" data-level="4.128" data-path="data-exploration.html"><a href="data-exploration.html#year-juliandate-datetime"><i class="fa fa-check"></i><b>4.128</b> Year JulianDate <code>Date&amp;Time</code></a></li>
<li class="chapter" data-level="4.129" data-path="data-exploration.html"><a href="data-exploration.html#section-74"><i class="fa fa-check"></i><b>4.129</b> <int> <dbl> <chr></a></li>
<li class="chapter" data-level="4.130" data-path="data-exploration.html"><a href="data-exploration.html#april-30-at-1130-am"><i class="fa fa-check"></i><b>4.130</b> 1 1917 120. April 30 at 11:30 AM</a></li>
<li class="chapter" data-level="4.131" data-path="data-exploration.html"><a href="data-exploration.html#may-11-at-933-am"><i class="fa fa-check"></i><b>4.131</b> 2 1918 131. May 11 at 9:33 AM</a></li>
<li class="chapter" data-level="4.132" data-path="data-exploration.html"><a href="data-exploration.html#may-3-at-233-pm"><i class="fa fa-check"></i><b>4.132</b> 3 1919 124. May 3 at 2:33 PM</a></li>
<li class="chapter" data-level="4.133" data-path="data-exploration.html"><a href="data-exploration.html#may-11-at-1046-am"><i class="fa fa-check"></i><b>4.133</b> 4 1920 132. May 11 at 10:46 AM</a></li>
<li class="chapter" data-level="4.134" data-path="data-exploration.html"><a href="data-exploration.html#may-11-at-642-am"><i class="fa fa-check"></i><b>4.134</b> 5 1921 131. May 11 at 6:42 AM</a></li>
<li class="chapter" data-level="4.135" data-path="data-exploration.html"><a href="data-exploration.html#may-12-at-120-pm"><i class="fa fa-check"></i><b>4.135</b> 6 1922 133. May 12 at 1:20 PM</a></li>
<li class="chapter" data-level="4.136" data-path="data-exploration.html"><a href="data-exploration.html#may-9-at-200-am"><i class="fa fa-check"></i><b>4.136</b> 7 1923 129. May 9 at 2:00 AM</a></li>
<li class="chapter" data-level="4.137" data-path="data-exploration.html"><a href="data-exploration.html#may-11-at-310-pm"><i class="fa fa-check"></i><b>4.137</b> 8 1924 133. May 11 at 3:10 PM</a></li>
<li class="chapter" data-level="4.138" data-path="data-exploration.html"><a href="data-exploration.html#may-7-at-632-pm"><i class="fa fa-check"></i><b>4.138</b> 9 1925 128. May 7 at 6:32 PM</a></li>
<li class="chapter" data-level="4.139" data-path="data-exploration.html"><a href="data-exploration.html#april-26-at-403-pm"><i class="fa fa-check"></i><b>4.139</b> 10 1926 117. April 26 at 4:03 PM</a></li>
<li class="chapter" data-level="4.140" data-path="data-exploration.html"><a href="data-exploration.html#with-77-more-rows-2"><i class="fa fa-check"></i><b>4.140</b> # … with 77 more rows</a></li>
<li class="chapter" data-level="4.141" data-path="data-exploration.html"><a href="data-exploration.html#observations-87"><i class="fa fa-check"></i><b>4.141</b> Observations: 87</a></li>
<li class="chapter" data-level="4.142" data-path="data-exploration.html"><a href="data-exploration.html#variables-3"><i class="fa fa-check"></i><b>4.142</b> Variables: 3</a></li>
<li class="chapter" data-level="4.143" data-path="data-exploration.html"><a href="data-exploration.html#year-1917-1918-1919-1920-1921-1922-1923-1924-19"><i class="fa fa-check"></i><b>4.143</b> $ Year <int> 1917, 1918, 1919, 1920, 1921, 1922, 1923, 1924, 19…</a></li>
<li class="chapter" data-level="4.144" data-path="data-exploration.html"><a href="data-exploration.html#juliandate-120.4795-131.3983-123.6066-132.4490-131.2795"><i class="fa fa-check"></i><b>4.144</b> $ JulianDate <dbl> 120.4795, 131.3983, 123.6066, 132.4490, 131.2795, …</a></li>
<li><a href="data-exploration.html#datetime-april-30-at-1130-am-may-11-at-933-am-may-attaching-package-lubridate-the-following-object-is-masked-from-packagebase-date-a-tibble-87-x-5-year-juliandate-datetime-longdt-datetime-1-1917-120.-april-30-at-113-1917-april-30-a-1917-04-30-113000-2-1918-131.-may-11-at-933-am-1918-may-11-at-1918-05-11-093300-3-1919-124.-may-3-at-233-pm-1919-may-3-at-2-1919-05-03-143300-4-1920-132.-may-11-at-1046-1920-may-11-at-1920-05-11-104600-5-1921-131.-may-11-at-642-am-1921-may-11-at-1921-05-11-064200-6-1922-133.-may-12-at-120-pm-1922-may-12-at-1922-05-12-132000-7-1923-129.-may-9-at-200-am-1923-may-9-at-2-1923-05-09-020000-8-1924-133.-may-11-at-310-pm-1924-may-11-at-1924-05-11-151000-9-1925-128.-may-7-at-632-pm-1925-may-7-at-6-1925-05-07-183200-10-1926-117.-april-26-at-403-1926-april-26-a-1926-04-26-160300-with-77-more-rows-a-tibble-87-x-3-juliandate-jd-datetime-1-120.-120-1917-04-30-113000-2-131.-131-1918-05-11-093300-3-124.-123-1919-05-03-143300-4-132.-132-1920-05-11-104600-5-131.-131-1921-05-11-064200-6-133.-132-1922-05-12-132000-7-129.-129-1923-05-09-020000-8-133.-132-1924-05-11-151000-9-128.-127-1925-05-07-183200-10-117.-116-1926-04-26-160300-with-77-more-rows-a-tibble-61-x-3-juliandate-jd-datetime-1-124.-123-1919-05-03-143300-2-133.-132-1922-05-12-132000-3-133.-132-1924-05-11-151000-4-128.-127-1925-05-07-183200-5-117.-116-1926-04-26-160300-6-128.-127-1928-05-06-162500-7-126.-125-1929-05-05-154100-8-129.-128-1930-05-08-190300-9-129.-128-1933-05-08-193000-10-121.-120-1934-04-30-140700-with-51-more-rows-a-tibble-61-x-3-juliandate-jd-datetime-1-123.607-123-1919-05-03-143300-2-132.556-132-1922-05-12-132000-3-132.632-132-1924-05-11-151000-4-127.773-127-1925-05-07-183200-5-116.669-116-1926-04-26-160300-6-127.684-127-1928-05-06-162500-7-125.654-125-1929-05-05-154100-8-128.794-128-1930-05-08-190300-9-128.813-128-1933-05-08-193000-10-120.588-120-1934-04-30-140700-with-51-more-rows-geom_smooth-using-method-loess-and-formula-y-x-computerized-accounting-parsed-with-column-specification-cols-gender-col_character-cas-col_double-cars-col_double-a-tibble-35-x-3-gender-cas-cars-1-female-2.85-2.9-2-male-2.6-2.32-3-female-2.2-1-4-male-2.65-2.58-5-male-2.6-2.58-6-male-3.2-3.05-7-male-3.65-3.74-8-female-2.55-1.9-9-male-3.15-3.32-10-male-2.8-2.74-with-25-more-rows-a-tibble-2-x-2-gender-n-1-female-15-2-male-20-a-tibble-2-x-2-gender-count-1-female-15-2-male-20-a-tibble-2-x-2-gender-med-1-female-2.55-2-male-2.85-a-tibble-1-x-4-cas_mean-cars_mean-cas_sd-cars_sd-1-2.82-2.77-0.484-0.671-a-tibble-1-x-4-cas_mean-cars_mean-cas_sd-cars_sd-1-2.82-2.77-0.484-0.671-a-tibble-1-x-4-cas_mean-cars_mean-cas_sd-cars_sd-1-2.82-2.77-0.484-0.671-a-tibble-1-x-4-cas_mean-cars_mean-cas_sd-cars_sd-1-2.82-2.77-0.484-0.671-gender-cas-cars-length35-min.-1.800-min.-1.000-class-character-1st-qu.2.575-1st-qu.2.445-mode-character-median-2.800-median-2.790-mean-2.816-mean-2.771-3rd-qu.3.150-3rd-qu.3.290-max.-3.750-max.-4.000-a-tibble-2-x-5-gender-cas_mean-cars_mean-cas_sd-cars_sd-1-female-2.64-2.51-0.554-0.773-2-male-2.94-2.96-0.390-0.525-a-tibble-2-x-5-gender-cas_mean-cars_mean-cas_sd-cars_sd-1-female-2.64-2.51-0.554-0.773-2-male-2.94-2.96-0.390-0.525-hunter-gatherers-in-australia-parsed-with-column-specification-cols-name-col_character-density-col_double-a-tibble-13-x-2-name-density-1-jeidji-17-2-kuku-50-3-mamu-45-4-ngatjan-59.8-5-undanbi-21.7-6-jinibarra-16-7-ualaria-9-8-barkindji-15.4-9-wongaibon-5.12-10-jaralde-40-11-tjapwurong-35-12-tasmanians-13.4-13-badjalang-13.4-one-sample-t-test-data-societiesdensity-t-3.8627-df-12-p-value-0.002257-alternative-hypothesis-true-mean-is-not-equal-to-7.38-95-percent-confidence-interval-15.59244-36.84449-sample-estimates-mean-of-x-26.21846-1-3"><span class="toc-section-number">4.145</span> $ <code>Date&amp;Time</code> <chr> “April 30 at 11:30 AM”, “May 11 at 9:33 AM”, “May …
##
## Attaching package: ‘lubridate’
## The following object is masked from ‘package:base’:
##
## date
## # A tibble: 87 x 5
## Year JulianDate <code>Date&amp;Time</code> longdt datetime<br />
## <int> <dbl> <chr> <chr> <dttm><br />
## 1 1917 120. April 30 at 11:3… 1917 April 30 a… 1917-04-30 11:30:00
## 2 1918 131. May 11 at 9:33 AM 1918 May 11 at … 1918-05-11 09:33:00
## 3 1919 124. May 3 at 2:33 PM 1919 May 3 at 2… 1919-05-03 14:33:00
## 4 1920 132. May 11 at 10:46 … 1920 May 11 at … 1920-05-11 10:46:00
## 5 1921 131. May 11 at 6:42 AM 1921 May 11 at … 1921-05-11 06:42:00
## 6 1922 133. May 12 at 1:20 PM 1922 May 12 at … 1922-05-12 13:20:00
## 7 1923 129. May 9 at 2:00 AM 1923 May 9 at 2… 1923-05-09 02:00:00
## 8 1924 133. May 11 at 3:10 PM 1924 May 11 at … 1924-05-11 15:10:00
## 9 1925 128. May 7 at 6:32 PM 1925 May 7 at 6… 1925-05-07 18:32:00
## 10 1926 117. April 26 at 4:03… 1926 April 26 a… 1926-04-26 16:03:00
## # … with 77 more rows
## # A tibble: 87 x 3
## JulianDate jd datetime<br />
## <dbl> <dbl> <dttm><br />
## 1 120. 120 1917-04-30 11:30:00
## 2 131. 131 1918-05-11 09:33:00
## 3 124. 123 1919-05-03 14:33:00
## 4 132. 132 1920-05-11 10:46:00
## 5 131. 131 1921-05-11 06:42:00
## 6 133. 132 1922-05-12 13:20:00
## 7 129. 129 1923-05-09 02:00:00
## 8 133. 132 1924-05-11 15:10:00
## 9 128. 127 1925-05-07 18:32:00
## 10 117. 116 1926-04-26 16:03:00
## # … with 77 more rows
## # A tibble: 61 x 3
## JulianDate jd datetime<br />
## <dbl> <dbl> <dttm><br />
## 1 124. 123 1919-05-03 14:33:00
## 2 133. 132 1922-05-12 13:20:00
## 3 133. 132 1924-05-11 15:10:00
## 4 128. 127 1925-05-07 18:32:00
## 5 117. 116 1926-04-26 16:03:00
## 6 128. 127 1928-05-06 16:25:00
## 7 126. 125 1929-05-05 15:41:00
## 8 129. 128 1930-05-08 19:03:00
## 9 129. 128 1933-05-08 19:30:00
## 10 121. 120 1934-04-30 14:07:00
## # … with 51 more rows
## # A tibble: 61 x 3
## JulianDate jd datetime<br />
## <dbl> <dbl> <dttm><br />
## 1 123.607 123 1919-05-03 14:33:00
## 2 132.556 132 1922-05-12 13:20:00
## 3 132.632 132 1924-05-11 15:10:00
## 4 127.773 127 1925-05-07 18:32:00
## 5 116.669 116 1926-04-26 16:03:00
## 6 127.684 127 1928-05-06 16:25:00
## 7 125.654 125 1929-05-05 15:41:00
## 8 128.794 128 1930-05-08 19:03:00
## 9 128.813 128 1933-05-08 19:30:00
## 10 120.588 120 1934-04-30 14:07:00
## # … with 51 more rows
## <code>geom_smooth()</code> using method = ‘loess’ and formula ‘y ~ x’
## Computerized accounting
## Parsed with column specification:
## cols(
## gender = col_character(),
## CAS = col_double(),
## CARS = col_double()
## )
## # A tibble: 35 x 3
## gender CAS CARS
## <chr> <dbl> <dbl>
## 1 female 2.85 2.9
## 2 male 2.6 2.32
## 3 female 2.2 1<br />
## 4 male 2.65 2.58
## 5 male 2.6 2.58
## 6 male 3.2 3.05
## 7 male 3.65 3.74
## 8 female 2.55 1.9
## 9 male 3.15 3.32
## 10 male 2.8 2.74
## # … with 25 more rows
## # A tibble: 2 x 2
## gender n
## <chr> <int>
## 1 female 15
## 2 male 20
## # A tibble: 2 x 2
## gender count
## <chr> <int>
## 1 female 15
## 2 male 20
## # A tibble: 2 x 2
## gender med
## <chr> <dbl>
## 1 female 2.55
## 2 male 2.85
## # A tibble: 1 x 4
## CAS_mean CARS_mean CAS_sd CARS_sd
## <dbl> <dbl> <dbl> <dbl>
## 1 2.82 2.77 0.484 0.671
## # A tibble: 1 x 4
## CAS_mean CARS_mean CAS_sd CARS_sd
## <dbl> <dbl> <dbl> <dbl>
## 1 2.82 2.77 0.484 0.671
## # A tibble: 1 x 4
## CAS_mean CARS_mean CAS_sd CARS_sd
## <dbl> <dbl> <dbl> <dbl>
## 1 2.82 2.77 0.484 0.671
## # A tibble: 1 x 4
## CAS_mean CARS_mean CAS_sd CARS_sd
## <dbl> <dbl> <dbl> <dbl>
## 1 2.82 2.77 0.484 0.671
## gender CAS CARS<br />
## Length:35 Min. :1.800 Min. :1.000<br />
## Class :character 1st Qu.:2.575 1st Qu.:2.445<br />
## Mode :character Median :2.800 Median :2.790<br />
## Mean :2.816 Mean :2.771<br />
## 3rd Qu.:3.150 3rd Qu.:3.290<br />
## Max. :3.750 Max. :4.000
## # A tibble: 2 x 5
## gender CAS_mean CARS_mean CAS_sd CARS_sd
## <chr> <dbl> <dbl> <dbl> <dbl>
## 1 female 2.64 2.51 0.554 0.773
## 2 male 2.94 2.96 0.390 0.525
## # A tibble: 2 x 5
## gender CAS_mean CARS_mean CAS_sd CARS_sd
## <chr> <dbl> <dbl> <dbl> <dbl>
## 1 female 2.64 2.51 0.554 0.773
## 2 male 2.94 2.96 0.390 0.525
## Hunter-gatherers in Australia
## Parsed with column specification:
## cols(
## name = col_character(),
## density = col_double()
## )
## # A tibble: 13 x 2
## name density
## <chr> <dbl>
## 1 jeidji 17<br />
## 2 kuku 50<br />
## 3 mamu 45<br />
## 4 ngatjan 59.8
## 5 undanbi 21.7
## 6 jinibarra 16<br />
## 7 ualaria 9<br />
## 8 barkindji 15.4
## 9 wongaibon 5.12
## 10 jaralde 40<br />
## 11 tjapwurong 35<br />
## 12 tasmanians 13.4
## 13 badjalang 13.4
##
## One Sample t-test
##
## data: societies$density
## t = 3.8627, df = 12, p-value = 0.002257
## alternative hypothesis: true mean is not equal to 7.38
## 95 percent confidence interval:
## 15.59244 36.84449
## sample estimates:
## mean of x
## 26.21846
## [1] 3</a></li>
</ul></li>
<li class="chapter" data-level="5" data-path="one-sample-inference.html"><a href="one-sample-inference.html"><i class="fa fa-check"></i><b>5</b> One-sample inference</a><ul>
<li class="chapter" data-level="5.1" data-path="one-sample-inference.html"><a href="one-sample-inference.html#length-of-gestation-in-north-carolina"><i class="fa fa-check"></i><b>5.1</b> Length of gestation in North Carolina</a></li>
<li class="chapter" data-level="5.2" data-path="one-sample-inference.html"><a href="one-sample-inference.html#inferring-ice-break-up-in-nenana"><i class="fa fa-check"></i><b>5.2</b> Inferring ice break-up in Nenana</a></li>
</ul></li>
<li class="divider"></li>
<li><a href="https://github.com/rstudio/bookdown" target="blank">Published with bookdown</a></li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Problems and Solutions in Applied Statistics</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="one-sample-inference" class="section level1">
<h1><span class="header-section-number">Chapter 5</span> One-sample inference</h1>
<div class="sourceCode" id="cb1"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb1-1" data-line-number="1"><span class="kw">library</span>(tidyverse)</a></code></pre></div>
<pre><code>## ── Attaching packages ─────────────────────────────────────────────────────────────────────────────────────── tidyverse 1.2.1 ──</code></pre>
<pre><code>## ✔ ggplot2 3.0.0     ✔ purrr   0.2.5
## ✔ tibble  1.4.2     ✔ dplyr   0.7.6
## ✔ tidyr   0.8.1     ✔ stringr 1.3.1
## ✔ readr   1.1.1     ✔ forcats 0.3.0</code></pre>
<pre><code>## ── Conflicts ────────────────────────────────────────────────────────────────────────────────────────── tidyverse_conflicts() ──
## ✖ dplyr::filter() masks stats::filter()
## ✖ dplyr::lag()    masks stats::lag()</code></pre>
<div id="length-of-gestation-in-north-carolina" class="section level2">
<h2><span class="header-section-number">5.1</span> Length of gestation in North Carolina</h2>
<p>The data in file
<a href="http://www.utsc.utoronto.ca/~butler/c32/ncbirths.csv" class="uri">http://www.utsc.utoronto.ca/~butler/c32/ncbirths.csv</a> are about
500 randomly chosen births of babies in North Carolina. There is a lot
of information: not just the weight at birth of the baby, but whether
the baby was born prematurely, the ages of the parents, whether the
parents are married, how long (in weeks) the pregnancy lasted (this is
called the “gestation”) and so on. We have seen these data before.</p>
<ol style="list-style-type: lower-alpha">
<li>Read in the data from the file into R, bearing in mind what
type of file it is.</li>
</ol>
<p>Solution</p>
<p>This is a <code>.csv</code> file (it came from a spreadsheet), so it
needs reading in accordingly. Work directly from the URL (rather
than downloading the file, unless you are working offline):</p>
<div class="sourceCode" id="cb5"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb5-1" data-line-number="1">myurl=<span class="st">&quot;http://www.utsc.utoronto.ca/~butler/c32/ncbirths.csv&quot;</span></a>
<a class="sourceLine" id="cb5-2" data-line-number="2">bw=<span class="kw">read_csv</span>(myurl)</a></code></pre></div>
<pre><code>## Parsed with column specification:
## cols(
##   `Father Age` = col_integer(),
##   `Mother Age` = col_integer(),
##   `Weeks Gestation` = col_integer(),
##   `Pre-natal Visits` = col_integer(),
##   `Marital Status` = col_integer(),
##   `Mother Weight Gained` = col_integer(),
##   `Low Birthweight?` = col_integer(),
##   `Weight (pounds)` = col_double(),
##   `Premie?` = col_integer(),
##   `Few Visits?` = col_integer()
## )</code></pre>
<ol start="2" style="list-style-type: lower-alpha">
<li>Find a 95% confidence interval for the mean birth weight of
all babies born in North Carolina (of which these babies are a
sample). At the end, you should state what the confidence interval is.
Giving some output is necessary, but <em>not</em> enough by itself.</li>
</ol>
<p>If your variable name has a space or other special character (like a
question mark) in it, remember that you have to surround its name with
backticks, as discussed the first time we looked at these data.</p>
<p>Solution</p>
<p>This:</p>
<div class="sourceCode" id="cb7"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb7-1" data-line-number="1"><span class="kw">t.test</span>(bw<span class="op">$</span><span class="st">`</span><span class="dt">Weight (pounds)</span><span class="st">`</span>)  </a></code></pre></div>
<pre><code>## 
##  One Sample t-test
## 
## data:  bw$`Weight (pounds)`
## t = 104.94, df = 499, p-value &lt; 2.2e-16
## alternative hypothesis: true mean is not equal to 0
## 95 percent confidence interval:
##  6.936407 7.201093
## sample estimates:
## mean of x 
##   7.06875</code></pre>
<p>or (the same, but remember to match your brackets):</p>
<div class="sourceCode" id="cb9"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb9-1" data-line-number="1"><span class="kw">with</span>(bw,<span class="kw">t.test</span>(<span class="st">`</span><span class="dt">Weight (pounds)</span><span class="st">`</span>))</a></code></pre></div>
<pre><code>## 
##  One Sample t-test
## 
## data:  Weight (pounds)
## t = 104.94, df = 499, p-value &lt; 2.2e-16
## alternative hypothesis: true mean is not equal to 0
## 95 percent confidence interval:
##  6.936407 7.201093
## sample estimates:
## mean of x 
##   7.06875</code></pre>
<p>The confidence interval goes from 6.94 to 7.20 pounds.</p>
<p>There is an annoyance about <code>t.test</code>. Sometimes you can use
<code>data=</code> with it, and sometimes not. When we do a two-sample
<span class="math inline">\(t\)</span>-test later, there is a “model formula” with a squiggle in it,
and there we can use <code>data=</code>, but here not, so you have to use
the dollar sign or the <code>with</code> to say which data frame to get
things from. The distinction seems to be that , you can use <code>data=</code>, and if not, not.</p>
<p>This is one of those things that is a consequence of R’s history. The
original <code>t.test</code> was without the model formula and thus
without the <code>data=</code>, but the model formula got “retro-fitted”
to it later. Since the model formula comes from things like
regression, where <code>data=</code> is legit, that had to be retro-fitted
as well. Or, at least, that’s my understanding.</p>
<ol start="3" style="list-style-type: lower-alpha">
<li>Birth weights of babies born in the United States have a mean
of 7.3 pounds. Is there any evidence that babies born in North
Carolina are less heavy on average? State appropriate hypotheses, do your
test, obtain a P-value and state your conclusion, in terms of the
original data.</li>
</ol>
<p>Solution</p>
<p>Null is that the population mean (the mean weight of all babies born
in North Carolina) is <span class="math inline">\(H_0: \mu=7.3\)</span> pounds, and the alternative is
that the mean is less: <span class="math inline">\(H_a: \mu&lt;7.3\)</span> pounds. This is a one-sided
alternative, which we need to feed into <code>t.test</code>:</p>
<div class="sourceCode" id="cb11"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb11-1" data-line-number="1"><span class="kw">t.test</span>(bw<span class="op">$</span><span class="st">`</span><span class="dt">Weight (pounds)</span><span class="st">`</span>,<span class="dt">mu=</span><span class="fl">7.3</span>,<span class="dt">alternative=</span><span class="st">&quot;less&quot;</span>)</a></code></pre></div>
<pre><code>## 
##  One Sample t-test
## 
## data:  bw$`Weight (pounds)`
## t = -3.4331, df = 499, p-value = 0.0003232
## alternative hypothesis: true mean is less than 7.3
## 95 percent confidence interval:
##      -Inf 7.179752
## sample estimates:
## mean of x 
##   7.06875</code></pre>
<p>$ %$</p>
<p>Or with <code>with</code>. If you see what I mean.</p>
<p>The P-value is 0.0003, which is <em>less</em> than any <span class="math inline">\(\alpha\)</span> we might
have chosen: we <em>reject</em> the null hypothesis in favour of the
alternative, and thus we conclude that the mean birth weight of babies
in North Carolina
is indeed less than 7.3 pounds.</p>
<p>“Reject the null hypothesis” is <em>not</em> a complete answer. You
need to say something about what rejecting the null hypothesis means
<em>in this case</em>: that is, you must make a statement about birth
weights of babies.</p>
<ol start="4" style="list-style-type: lower-alpha">
<li>The theory behind the <span class="math inline">\(t\)</span>-test says that the distribution of
birth weights should be (approximately) normally distributed. Obtain a
histogram of the birth weights. Does it look approximately normal?
Comment briefly. (You’ll have to pick a number of bins for your
histogram first. I don’t mind very much what you pick, as long as it’s
not obviously too many or too few bins.)</li>
</ol>
<p>Solution</p>
<p>We did this before (and discussed the number of bins before), so
I’ll just reproduce my 10-bin histogram (which is what I preferred,
but this is a matter of taste):</p>
<div class="sourceCode" id="cb13"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb13-1" data-line-number="1"><span class="kw">ggplot</span>(bw,<span class="kw">aes</span>(<span class="dt">x=</span><span class="st">`</span><span class="dt">Weight (pounds)</span><span class="st">`</span>))<span class="op">+</span><span class="kw">geom_histogram</span>(<span class="dt">bins=</span><span class="dv">10</span>)</a></code></pre></div>
<p><img src="04-one-sample-inference_files/figure-html/unnamed-chunk-8-1.png" width="672" /></p>
<p>So, we were assessing normality. What about that?</p>
<p>It is mostly normal-looking, but I am suspicious about those
<em>very</em> low birth weights, the ones below about 4 pounds. There
are too many of those, as I see it.</p>
<p>If you think this is approximately normal, you need to make some
comment along the lines of ``the shape is approximately symmetric with
no outliers’’. I think my first answer is better, but this answer is
worth something, since it is a not completely unreasonable
interpretation of the histogram.</p>
<p>A normal quantile plot is better for assessing normality
than a histogram is, but I won’t make you do one until we have seen
the idea in class. Here’s the normal quantile plot for these data:</p>
<div class="sourceCode" id="cb14"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb14-1" data-line-number="1"><span class="kw">ggplot</span>(bw,<span class="kw">aes</span>(<span class="dt">sample=</span><span class="st">`</span><span class="dt">Weight (pounds)</span><span class="st">`</span>))<span class="op">+</span><span class="kw">stat_qq</span>()<span class="op">+</span><span class="kw">stat_qq_line</span>()</a></code></pre></div>
<p><img src="04-one-sample-inference_files/figure-html/unnamed-chunk-9-1.png" width="672" /></p>
<p>This is rather striking: the lowest birthweights (the ones below 5
pounds or so) are <em>way</em> too low for a normal distribution to
apply. The top end is fine (except perhaps for that one very heavy
baby), but there are too many low birthweights for a normal
distribution to be believable. Note how much clearer this story is
than on the histogram.</p>
<p>Having said that, the <span class="math inline">\(t\)</span>-test, especially with a sample size as big
as this (500), behaves <em>very</em> well when the data are somewhat
non-normal (because it takes advantage of the Central Limit Theorem:
that is, it’s the <em>sampling distribution of the sample mean</em>
whose shape matters). So, even though the data are definitely not
normal, I wouldn’t be too worried about our test.</p>
<p>This perhaps gives some insight as to why Freedman-Diaconis said we
should use so many bins for our histogram. We have a lot of low-end
outliers, so that the IQR is actually <em>small</em> compared to the
overall spread of the data (as measured, say, by the SD or the range)
and so FD thinks we need a lot of bins to describe the shape. Sturges
is based on data being approximately normal, so it will tend to
produce a small number of bins for data that have outliers.</p>
</div>
<div id="inferring-ice-break-up-in-nenana" class="section level2">
<h2><span class="header-section-number">5.2</span> Inferring ice break-up in Nenana</h2>
<p>Nenana, Alaska, is about 50 miles west of Fairbanks.
Every spring, there is a contest in Nenana. A wooden tripod is
placed on the frozen river, and people try to guess the exact minute
when the ice melts enough for the tripod to fall through the ice. The
contest started in 1917 as an amusement for railway workers, and has
taken place every year since. Now, hundreds of thousands of people
enter their guesses on the Internet and the prize for the winner can
be as much as $300,000.</p>
<p>Because so much money is at stake, and because the exact same tripod
is placed at the exact same spot on the ice every year, the data are
consistent and accurate. The data are in
<a href="http://www.utsc.utoronto.ca/~butler/c32/nenana.txt" class="uri">http://www.utsc.utoronto.ca/~butler/c32/nenana.txt</a>.</p>
<p>Yes, we saw these data before.</p>
<ol style="list-style-type: lower-alpha">
<li>Read the data into R, as before, or use the data frame that
you read in before. Note that the values are separated by
<em>tabs</em> rather than spaces, so you’ll need an appropriate
<code>read_</code> to read it in.</li>
</ol>
<p>Solution</p>
<p>These are “tab-separated values”, so <code>read_tsv</code> is the
thing, as for the Australian athletes:</p>
<div class="sourceCode" id="cb15"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb15-1" data-line-number="1">myurl=<span class="st">&quot;http://www.utsc.utoronto.ca/~butler/c32/nenana.txt&quot;</span></a>
<a class="sourceLine" id="cb15-2" data-line-number="2">nenana=<span class="kw">read_tsv</span>(myurl)</a></code></pre></div>
<pre><code>## Parsed with column specification:
## cols(
##   Year = col_integer(),
##   JulianDate = col_double(),
##   `Date&amp;Time` = col_character()
## )</code></pre>
<p>Use whatever name you like for the data frame. One that is different
from any of the column headers is smart; then it is clear whether you
mean the whole data frame or one of its columns. <code>ice</code> or
<code>melt</code> or anything like that would also be good.</p>
<ol start="2" style="list-style-type: lower-alpha">
<li>Obtain a 90% confidence interval for the mean
<code>JulianDate</code>. What interval do you get? Looking back at your
histogram, do you have any doubts about the validity of what you
have just done?</li>
</ol>
<p>Solution</p>
<p>This is a matter of using <code>t.test</code> and pulling out the
interval. Since we are looking for a non-standard interval, we
have to remember <code>conf.level</code> as the way to get the
confidence level that we want. I’m going with <code>with</code> this
time, though the dollar-sign thing is equally as good:</p>
<div class="sourceCode" id="cb17"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb17-1" data-line-number="1"><span class="kw">with</span>(nenana,<span class="kw">t.test</span>(JulianDate,<span class="dt">conf.level=</span><span class="fl">0.90</span>))</a></code></pre></div>
<pre><code>## 
##  One Sample t-test
## 
## data:  JulianDate
## t = 197.41, df = 86, p-value &lt; 2.2e-16
## alternative hypothesis: true mean is not equal to 0
## 90 percent confidence interval:
##  124.4869 126.6018
## sample estimates:
## mean of x 
##  125.5443</code></pre>
<p>Between 124.5 and 126.6 days into the year. Converting that into
something we can understand (because I want to), there are
<span class="math inline">\(31+28+31+30=120\)</span> days in
January through April (in a non-leap year), so this says that the mean
breakup date is between about May 4 and May 6.</p>
<p>The <span class="math inline">\(t\)</span>-test is based on an assumption of data coming from a normal
distribution. The histogram we made earlier looks pretty much normal,
so there are no doubts about normality and thus no doubts about the
validity of what we have done, on the evidence we have seen so far. (I
have some doubts on different grounds, based on another of the plots
we did earlier, which I’ll explain later, but all I’m expecting you to
do is to look at the histogram and say ``Yep, that’s normal
enough’’. Bear in mind that the sample size is 87, which is large
enough for the Central Limit Theorem to be pretty helpful, so that we don’t need the data to be more than “approximately normal” for the sampling distribution of the sample mean to be very close to <span class="math inline">\(t\)</span> with the right df.)</p>
<ol start="3" style="list-style-type: lower-alpha">
<li>An old-timer in Nenana strokes his grey beard and says
“When I were young, I remember the tripod used to fall into the water around May 10”.
In a non-leap year, May 10 is Julian day 130. Test the null hypothesis that the
mean <code>JulianDay</code> is 130, against the alternative that it is less. What do you conclude?
What practical implication does that have
(assuming that the old-timer has a good memory)?</li>
</ol>
<p>Solution</p>
<p>The test is <code>t.test</code> again, but this time we have to
specify a null mean and a direction of alternative:</p>
<div class="sourceCode" id="cb19"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb19-1" data-line-number="1"><span class="kw">with</span>(nenana,<span class="kw">t.test</span>(JulianDate,<span class="dt">mu=</span><span class="dv">130</span>,<span class="dt">alternative=</span><span class="st">&quot;less&quot;</span>))</a></code></pre></div>
<pre><code>## 
##  One Sample t-test
## 
## data:  JulianDate
## t = -7.0063, df = 86, p-value = 2.575e-10
## alternative hypothesis: true mean is less than 130
## 95 percent confidence interval:
##      -Inf 126.6018
## sample estimates:
## mean of x 
##  125.5443</code></pre>
<p>For a test, look first at the P-value, which is 0.0000000002575: that
is to say, the P-value is very small, definitely smaller than 0.05 (or
any other <span class="math inline">\(\alpha\)</span> you might have chosen). So we <em>reject</em> the
null hypothesis, and conclude that the mean <code>JulianDate</code> is actually
<em>less</em> than 130.</p>
<p>Now, this is the date on which the ice breaks up on average, and we
have concluded that it is <em>earlier</em> than it used to be, since we
are assuming the old-timer’s memory is correct.</p>
<p>This is evidence in
favour of global warming; a small piece of evidence, to be sure, but
the ice is melting earlier than it used to all over the Arctic, so
it’s not just in Nenana that it is happening. You don’t need to get to
the “global warming” part, but I <em>do</em> want you to observe that
the ice is breaking up earlier than it used to.</p>
<ol start="4" style="list-style-type: lower-alpha">
<li>Plot <code>JulianDate</code> against <code>Year</code> on a
scatterplot. What recent trends, if any, do you see? Comment
briefly. (You did this before, but I have some extra comments on
the graph this time, so feel free to just read this part.)</li>
</ol>
<p>Solution</p>
<p>I liked the <code>ggplot</code> with a smooth trend on it:</p>
<div class="sourceCode" id="cb21"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb21-1" data-line-number="1"><span class="kw">ggplot</span>(nenana,<span class="kw">aes</span>(<span class="dt">x=</span>Year,<span class="dt">y=</span>JulianDate))<span class="op">+</span><span class="kw">geom_point</span>()<span class="op">+</span><span class="kw">geom_smooth</span>()</a></code></pre></div>
<pre><code>## `geom_smooth()` using method = &#39;loess&#39; and formula &#39;y ~ x&#39;</code></pre>
<p><img src="04-one-sample-inference_files/figure-html/unnamed-chunk-13-1.png" width="672" /></p>
<p>There was something obvious to see: after about 1960, there is a clear
downward trend: the ice is breaking up earlier on average every
year. Even though there is a lot of variability, the overall trend,
viewed this way, is clear (and consistent with the test we did
earlier). Note that the old-timer’s value of 130 is the kind of
<code>JulianDate</code> we would typically observe around 1920, which
would make the old-timer over 90 years old.</p>
<p>All right, why did I say I had some doubts earlier? Well, because of
this downward trend, the mean is not actually the same all the way
through, so it doesn’t make all that much sense to estimate it, which
is what we were doing earlier by doing a confidence interval or a
hypothesis test. What would actually make more sense is to estimate
the mean <code>JulianDate</code> <em>for a particular year</em>. This could
be done by a regression: predict <code>JulianDate</code> from
<code>Year</code>, and then get a
“confidence interval for the mean response”
(as you would have seen in B27 or will see in C67). The
trend isn’t really linear, but is not that far off. I can modify the
previous picture to give you an idea. Putting in <code>method=&quot;lm&quot;</code>
fits a line; as we see later, <code>lm</code> does regressions in R:</p>
<div class="sourceCode" id="cb23"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb23-1" data-line-number="1"><span class="kw">ggplot</span>(nenana,<span class="kw">aes</span>(<span class="dt">x=</span>Year,<span class="dt">y=</span>JulianDate))<span class="op">+</span><span class="kw">geom_point</span>()<span class="op">+</span></a>
<a class="sourceLine" id="cb23-2" data-line-number="2"><span class="kw">geom_smooth</span>(<span class="dt">method=</span><span class="st">&quot;lm&quot;</span>)</a></code></pre></div>
<p><img src="04-one-sample-inference_files/figure-html/unnamed-chunk-14-1.png" width="672" /></p>
<p>Compare the confidence interval for the mean <code>JulianDate</code> in
1920: 126 to 131 (the shaded area on the graph), with 2000: 121 to
125. A change of about 5 days over 80 years. And with the recent trend
that we saw above, it’s probably changing faster than that
now. Sobering indeed.</p>

</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="data-exploration.html" class="navigation navigation-prev navigation-unique" aria-label="Previous page"><i class="fa fa-angle-left"></i></a>

    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/lunr.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"google": false,
"linkedin": false,
"weibo": false,
"instapper": false,
"vk": false,
"all": ["facebook", "google", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": null,
"text": null
},
"download": null,
"toc": {
"collapse": "subsection"
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://cdn.bootcss.com/mathjax/2.7.1/MathJax.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:" && /^https?:/.test(src))
      src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
