<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>Chapter 8 Power and sample size | Problems and Solutions in Applied Statistics</title>
  <meta name="description" content="A set of problems and solutions, in R, on various parts of applied statistics" />
  <meta name="generator" content="bookdown 0.21 and GitBook 2.6.7" />

  <meta property="og:title" content="Chapter 8 Power and sample size | Problems and Solutions in Applied Statistics" />
  <meta property="og:type" content="book" />
  <meta property="og:url" content="http://ritsokiguess.site/pasias" />
  
  <meta property="og:description" content="A set of problems and solutions, in R, on various parts of applied statistics" />
  <meta name="github-repo" content="nxskok/pasias" />

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Chapter 8 Power and sample size | Problems and Solutions in Applied Statistics" />
  
  <meta name="twitter:description" content="A set of problems and solutions, in R, on various parts of applied statistics" />
  

<meta name="author" content="Ken Butler" />


<meta name="date" content="2021-05-17" />

  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="two-sample-inference.html"/>
<link rel="next" href="the-sign-test.html"/>
<script src="libs/header-attrs-2.7/header-attrs.js"></script>
<script src="libs/jquery-2.2.3/jquery.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />









<script src="libs/accessible-code-block-0.0.1/empty-anchor.js"></script>


<style type="text/css">
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">Problems and Solutions in Applied Statistics</a></li>

<li class="divider"></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i>Introduction</a>
<ul>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#packages-used-somewhere-in-this-book"><i class="fa fa-check"></i>Packages used somewhere in this book</a></li>
</ul></li>
<li class="chapter" data-level="1" data-path="getting-used-to-r-and-r-studio.html"><a href="getting-used-to-r-and-r-studio.html"><i class="fa fa-check"></i><b>1</b> Getting used to R and R Studio</a></li>
<li class="chapter" data-level="2" data-path="reading-in-data.html"><a href="reading-in-data.html"><i class="fa fa-check"></i><b>2</b> Reading in data</a></li>
<li class="chapter" data-level="3" data-path="drawing-graphs.html"><a href="drawing-graphs.html"><i class="fa fa-check"></i><b>3</b> Drawing graphs</a></li>
<li class="chapter" data-level="4" data-path="data-exploration.html"><a href="data-exploration.html"><i class="fa fa-check"></i><b>4</b> Data exploration</a></li>
<li class="chapter" data-level="5" data-path="working-with-dataframes.html"><a href="working-with-dataframes.html"><i class="fa fa-check"></i><b>5</b> Working with dataframes</a></li>
<li class="chapter" data-level="6" data-path="one-sample-inference.html"><a href="one-sample-inference.html"><i class="fa fa-check"></i><b>6</b> One-sample inference</a></li>
<li class="chapter" data-level="7" data-path="two-sample-inference.html"><a href="two-sample-inference.html"><i class="fa fa-check"></i><b>7</b> Two-sample inference</a></li>
<li class="chapter" data-level="8" data-path="power-and-sample-size.html"><a href="power-and-sample-size.html"><i class="fa fa-check"></i><b>8</b> Power and sample size</a>
<ul>
<li class="chapter" data-level="8.1" data-path="power-and-sample-size.html"><a href="power-and-sample-size.html#simulating-power"><i class="fa fa-check"></i><b>8.1</b> Simulating power</a></li>
<li class="chapter" data-level="8.2" data-path="power-and-sample-size.html"><a href="power-and-sample-size.html#calculating-power-and-sample-size-for-estimating-mean"><i class="fa fa-check"></i><b>8.2</b> Calculating power and sample size for estimating mean</a></li>
<li class="chapter" data-level="8.3" data-path="power-and-sample-size.html"><a href="power-and-sample-size.html#simulating-power-for-proportions"><i class="fa fa-check"></i><b>8.3</b> Simulating power for proportions</a></li>
<li class="chapter" data-level="8.4" data-path="power-and-sample-size.html"><a href="power-and-sample-size.html#designing-a-study-to-have-enough-power"><i class="fa fa-check"></i><b>8.4</b> Designing a study to have enough power</a></li>
<li class="chapter" data-level="8.5" data-path="power-and-sample-size.html"><a href="power-and-sample-size.html#power-and-alpha-in-a-skewed-population"><i class="fa fa-check"></i><b>8.5</b> Power and <span class="math inline">\(\alpha\)</span> in a skewed population</a></li>
<li class="chapter" data-level="8.6" data-path="power-and-sample-size.html"><a href="power-and-sample-size.html#simulating-power-1"><i class="fa fa-check"></i><b>8.6</b> Simulating power</a></li>
<li class="chapter" data-level="8.7" data-path="power-and-sample-size.html"><a href="power-and-sample-size.html#calculating-power-and-sample-size-for-estimating-mean-1"><i class="fa fa-check"></i><b>8.7</b> Calculating power and sample size for estimating mean</a></li>
<li class="chapter" data-level="8.8" data-path="power-and-sample-size.html"><a href="power-and-sample-size.html#simulating-power-for-proportions-1"><i class="fa fa-check"></i><b>8.8</b> Simulating power for proportions</a></li>
<li class="chapter" data-level="8.9" data-path="power-and-sample-size.html"><a href="power-and-sample-size.html#designing-a-study-to-have-enough-power-1"><i class="fa fa-check"></i><b>8.9</b> Designing a study to have enough power</a></li>
<li class="chapter" data-level="8.10" data-path="power-and-sample-size.html"><a href="power-and-sample-size.html#power-and-alpha-in-a-skewed-population-1"><i class="fa fa-check"></i><b>8.10</b> Power and <span class="math inline">\(\alpha\)</span> in a skewed population</a></li>
</ul></li>
<li class="chapter" data-level="9" data-path="the-sign-test.html"><a href="the-sign-test.html"><i class="fa fa-check"></i><b>9</b> The sign test</a></li>
<li class="chapter" data-level="10" data-path="mood-median-test.html"><a href="mood-median-test.html"><i class="fa fa-check"></i><b>10</b> Mood median test</a></li>
<li class="chapter" data-level="11" data-path="matched-pairs-t-and-sign-test.html"><a href="matched-pairs-t-and-sign-test.html"><i class="fa fa-check"></i><b>11</b> Matched pairs t and sign test</a></li>
<li class="chapter" data-level="12" data-path="normal-quantile-plots.html"><a href="normal-quantile-plots.html"><i class="fa fa-check"></i><b>12</b> Normal quantile plots</a>
<ul>
<li class="chapter" data-level="12.1" data-path="normal-quantile-plots.html"><a href="normal-quantile-plots.html#lengths-of-heliconia-flowers"><i class="fa fa-check"></i><b>12.1</b> Lengths of heliconia flowers</a></li>
<li class="chapter" data-level="12.2" data-path="normal-quantile-plots.html"><a href="normal-quantile-plots.html#ferritin-and-normality"><i class="fa fa-check"></i><b>12.2</b> Ferritin and normality</a></li>
<li class="chapter" data-level="12.3" data-path="normal-quantile-plots.html"><a href="normal-quantile-plots.html#lengths-of-heliconia-flowers-1"><i class="fa fa-check"></i><b>12.3</b> Lengths of heliconia flowers</a></li>
<li class="chapter" data-level="12.4" data-path="normal-quantile-plots.html"><a href="normal-quantile-plots.html#ferritin-and-normality-1"><i class="fa fa-check"></i><b>12.4</b> Ferritin and normality</a></li>
</ul></li>
<li class="chapter" data-level="13" data-path="analysis-of-variance.html"><a href="analysis-of-variance.html"><i class="fa fa-check"></i><b>13</b> Analysis of variance</a></li>
<li class="chapter" data-level="14" data-path="writing-reports.html"><a href="writing-reports.html"><i class="fa fa-check"></i><b>14</b> Writing reports</a></li>
<li class="chapter" data-level="15" data-path="learning-to-code.html"><a href="learning-to-code.html"><i class="fa fa-check"></i><b>15</b> Learning to code</a>
<ul>
<li class="chapter" data-level="15.1" data-path="learning-to-code.html"><a href="learning-to-code.html#introduction-1"><i class="fa fa-check"></i><b>15.1</b> Introduction</a></li>
<li class="chapter" data-level="15.2" data-path="learning-to-code.html"><a href="learning-to-code.html#data-and-pre-processing"><i class="fa fa-check"></i><b>15.2</b> Data and pre-processing</a></li>
<li class="chapter" data-level="15.3" data-path="learning-to-code.html"><a href="learning-to-code.html#analysis"><i class="fa fa-check"></i><b>15.3</b> Analysis</a></li>
<li class="chapter" data-level="15.4" data-path="learning-to-code.html"><a href="learning-to-code.html#conclusions-see-note-9"><i class="fa fa-check"></i><b>15.4</b> Conclusions (see note 9)</a></li>
</ul></li>
<li class="chapter" data-level="16" data-path="a-comparison-of-four-shampoos-in-treating-dandruff.html"><a href="a-comparison-of-four-shampoos-in-treating-dandruff.html"><i class="fa fa-check"></i><b>16</b> A comparison of four shampoos in treating dandruff</a>
<ul>
<li class="chapter" data-level="16.1" data-path="a-comparison-of-four-shampoos-in-treating-dandruff.html"><a href="a-comparison-of-four-shampoos-in-treating-dandruff.html#introduction-2"><i class="fa fa-check"></i><b>16.1</b> Introduction</a></li>
<li class="chapter" data-level="16.2" data-path="a-comparison-of-four-shampoos-in-treating-dandruff.html"><a href="a-comparison-of-four-shampoos-in-treating-dandruff.html#exploratory-analysis"><i class="fa fa-check"></i><b>16.2</b> Exploratory analysis</a></li>
<li class="chapter" data-level="16.3" data-path="a-comparison-of-four-shampoos-in-treating-dandruff.html"><a href="a-comparison-of-four-shampoos-in-treating-dandruff.html#analysis-of-variance-1"><i class="fa fa-check"></i><b>16.3</b> Analysis of Variance</a></li>
<li class="chapter" data-level="16.4" data-path="a-comparison-of-four-shampoos-in-treating-dandruff.html"><a href="a-comparison-of-four-shampoos-in-treating-dandruff.html#assessment-of-assumptions"><i class="fa fa-check"></i><b>16.4</b> Assessment of Assumptions</a></li>
<li class="chapter" data-level="16.5" data-path="a-comparison-of-four-shampoos-in-treating-dandruff.html"><a href="a-comparison-of-four-shampoos-in-treating-dandruff.html#conclusions"><i class="fa fa-check"></i><b>16.5</b> Conclusions</a></li>
<li class="chapter" data-level="16.6" data-path="a-comparison-of-four-shampoos-in-treating-dandruff.html"><a href="a-comparison-of-four-shampoos-in-treating-dandruff.html#end"><i class="fa fa-check"></i><b>16.6</b> End</a></li>
</ul></li>
<li class="chapter" data-level="17" data-path="tidying-data.html"><a href="tidying-data.html"><i class="fa fa-check"></i><b>17</b> Tidying data</a></li>
<li class="chapter" data-level="18" data-path="simple-regression.html"><a href="simple-regression.html"><i class="fa fa-check"></i><b>18</b> Simple regression</a></li>
<li class="chapter" data-level="19" data-path="multiple-regression.html"><a href="multiple-regression.html"><i class="fa fa-check"></i><b>19</b> Multiple regression</a></li>
<li class="chapter" data-level="20" data-path="regression-with-categorical-variables.html"><a href="regression-with-categorical-variables.html"><i class="fa fa-check"></i><b>20</b> Regression with categorical variables</a>
<ul>
<li class="chapter" data-level="20.1" data-path="regression-with-categorical-variables.html"><a href="regression-with-categorical-variables.html#crickets-revisited"><i class="fa fa-check"></i><b>20.1</b> Crickets revisited</a></li>
<li class="chapter" data-level="20.2" data-path="regression-with-categorical-variables.html"><a href="regression-with-categorical-variables.html#pulse-rates-and-marching"><i class="fa fa-check"></i><b>20.2</b> Pulse rates and marching</a></li>
<li class="chapter" data-level="20.3" data-path="regression-with-categorical-variables.html"><a href="regression-with-categorical-variables.html#crickets-revisited-1"><i class="fa fa-check"></i><b>20.3</b> Crickets revisited</a></li>
<li class="chapter" data-level="20.4" data-path="regression-with-categorical-variables.html"><a href="regression-with-categorical-variables.html#pulse-rates-and-marching-1"><i class="fa fa-check"></i><b>20.4</b> Pulse rates and marching</a></li>
</ul></li>
<li class="chapter" data-level="21" data-path="dates-and-times.html"><a href="dates-and-times.html"><i class="fa fa-check"></i><b>21</b> Dates and times</a></li>
<li class="chapter" data-level="22" data-path="functions.html"><a href="functions.html"><i class="fa fa-check"></i><b>22</b> Functions</a></li>
<li class="chapter" data-level="23" data-path="vector-and-matrix-algebra.html"><a href="vector-and-matrix-algebra.html"><i class="fa fa-check"></i><b>23</b> Vector and matrix algebra</a>
<ul>
<li class="chapter" data-level="23.1" data-path="vector-and-matrix-algebra.html"><a href="vector-and-matrix-algebra.html#heights-and-foot-lengths-again"><i class="fa fa-check"></i><b>23.1</b> Heights and foot lengths again</a></li>
<li class="chapter" data-level="23.2" data-path="vector-and-matrix-algebra.html"><a href="vector-and-matrix-algebra.html#heights-and-foot-lengths-again-1"><i class="fa fa-check"></i><b>23.2</b> Heights and foot lengths again</a></li>
</ul></li>
<li class="chapter" data-level="24" data-path="the-bootstrap.html"><a href="the-bootstrap.html"><i class="fa fa-check"></i><b>24</b> The Bootstrap</a></li>
<li class="chapter" data-level="25" data-path="bayesian-statistics-with-stan.html"><a href="bayesian-statistics-with-stan.html"><i class="fa fa-check"></i><b>25</b> Bayesian Statistics with Stan</a></li>
<li class="chapter" data-level="26" data-path="logistic-regression.html"><a href="logistic-regression.html"><i class="fa fa-check"></i><b>26</b> Logistic regression</a></li>
<li class="chapter" data-level="27" data-path="logistic-regression-with-ordinal-response.html"><a href="logistic-regression-with-ordinal-response.html"><i class="fa fa-check"></i><b>27</b> Logistic regression with ordinal response</a></li>
<li class="chapter" data-level="28" data-path="logistic-regression-with-nominal-response.html"><a href="logistic-regression-with-nominal-response.html"><i class="fa fa-check"></i><b>28</b> Logistic regression with nominal response</a></li>
<li class="chapter" data-level="29" data-path="survival-analysis.html"><a href="survival-analysis.html"><i class="fa fa-check"></i><b>29</b> Survival analysis</a></li>
<li class="chapter" data-level="30" data-path="analysis-of-variance-revisited.html"><a href="analysis-of-variance-revisited.html"><i class="fa fa-check"></i><b>30</b> Analysis of variance revisited</a></li>
<li class="chapter" data-level="31" data-path="analysis-of-covariance.html"><a href="analysis-of-covariance.html"><i class="fa fa-check"></i><b>31</b> Analysis of covariance</a></li>
<li class="chapter" data-level="32" data-path="multivariate-analysis-of-variance.html"><a href="multivariate-analysis-of-variance.html"><i class="fa fa-check"></i><b>32</b> Multivariate analysis of variance</a></li>
<li class="chapter" data-level="33" data-path="repeated-measures.html"><a href="repeated-measures.html"><i class="fa fa-check"></i><b>33</b> Repeated measures</a></li>
<li class="chapter" data-level="34" data-path="discriminant-analysis.html"><a href="discriminant-analysis.html"><i class="fa fa-check"></i><b>34</b> Discriminant analysis</a></li>
<li class="chapter" data-level="35" data-path="hierarchical-cluster-analysis.html"><a href="hierarchical-cluster-analysis.html"><i class="fa fa-check"></i><b>35</b> Hierarchical cluster analysis</a></li>
<li class="chapter" data-level="36" data-path="k-means-cluster-analysis.html"><a href="k-means-cluster-analysis.html"><i class="fa fa-check"></i><b>36</b> K-means cluster analysis</a></li>
<li class="chapter" data-level="37" data-path="drawing-maps-with-leaflet.html"><a href="drawing-maps-with-leaflet.html"><i class="fa fa-check"></i><b>37</b> Drawing maps with Leaflet</a></li>
<li class="chapter" data-level="38" data-path="multidimensional-scaling.html"><a href="multidimensional-scaling.html"><i class="fa fa-check"></i><b>38</b> Multidimensional Scaling</a></li>
<li class="chapter" data-level="39" data-path="principal-components.html"><a href="principal-components.html"><i class="fa fa-check"></i><b>39</b> Principal Components</a>
<ul>
<li class="chapter" data-level="39.1" data-path="principal-components.html"><a href="principal-components.html#the-weather-somewhere"><i class="fa fa-check"></i><b>39.1</b> The weather, somewhere</a></li>
<li class="chapter" data-level="39.2" data-path="principal-components.html"><a href="principal-components.html#the-weather-somewhere-1"><i class="fa fa-check"></i><b>39.2</b> The weather, somewhere</a></li>
</ul></li>
<li class="chapter" data-level="40" data-path="factor-analysis.html"><a href="factor-analysis.html"><i class="fa fa-check"></i><b>40</b> Factor Analysis</a></li>
<li class="chapter" data-level="41" data-path="frequency-table-analysis.html"><a href="frequency-table-analysis.html"><i class="fa fa-check"></i><b>41</b> Frequency table analysis</a></li>
<li class="divider"></li>
<li><a href="https://github.com/rstudio/bookdown" target="blank">Published with bookdown</a></li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Problems and Solutions in Applied Statistics</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="power-and-sample-size" class="section level1" number="8">
<h1><span class="header-section-number">Chapter 8</span> Power and sample size</h1>
<div class="sourceCode" id="cb1"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1-1"><a href="power-and-sample-size.html#cb1-1"></a><span class="kw">library</span>(tidyverse)</span></code></pre></div>
<div id="simulating-power" class="section level2" number="8.1">
<h2><span class="header-section-number">8.1</span> Simulating power</h2>
<p>This question investigates power by
simulation.</p>
<ol style="list-style-type: lower-alpha">
<li><p>Use <code>rnorm</code> to generate 10 random values from a
normal distribution with mean 20 and SD 2. Do your values look
reasonable? Explain briefly. (You don’t need to draw a graph.)</p></li>
<li><p>Estimate by simulation the power of a <span class="math inline">\(t\)</span>-test to reject a
null hypothesis of 20 when the true mean is also 20, the
population SD is 2, and the sample size is 10, against a (default)
two-sided alternative. Remember the
steps: (i) generate a lot of random samples from the true
distribution, (ii) run the <span class="math inline">\(t\)</span>-test with the required null mean, (iii) pull out the P-values, (iv) count how many of them are 0.05
or less.</p></li>
<li><p>In the simulation you just did, was the null hypothesis true
or false? Do you want to reject the null hypothesis or not?
Explain briefly why the simulation results you got were (or were
not) about what you would expect.</p></li>
<li><p>By copying, pasting and editing your code from the previous
part, estimate the power of the test of <span class="math inline">\(H_0: \mu=20\)</span> (against a
two-sided alternative) when the true population mean is 22 (rather
than 20).</p></li>
<li><p>Use R to calculate this power exactly (without
simulation). Compare the exact result with your simulation.</p></li>
</ol>
</div>
<div id="calculating-power-and-sample-size-for-estimating-mean" class="section level2" number="8.2">
<h2><span class="header-section-number">8.2</span> Calculating power and sample size for estimating mean</h2>
<p>We are planning a study to estimate a population mean. The
population standard deviation is believed to be 20, and the population
distribution is believed to be approximately normal. We will be
testing the null hypothesis that the population mean is 100. Suppose
the population mean is actually 110, and we want to determine how
likely we are to (correctly) reject the null hypothesis in this case,
using a two-sided (but one-sample) test with <span class="math inline">\(\alpha=0.05\)</span>.</p>
<ol style="list-style-type: lower-alpha">
<li><p>We will take a sample of size <span class="math inline">\(n=30\)</span>. Calculate the power of
this test.</p></li>
<li><p>Find the sample size necessary to obtain a power
of at least 0.80 under these conditions. What sample size do you
need? Explain briefly how your answer is
consistent with (a).</p></li>
</ol>
</div>
<div id="simulating-power-for-proportions" class="section level2" number="8.3">
<h2><span class="header-section-number">8.3</span> Simulating power for proportions</h2>
<p>In opinion surveys (and other places), we are testing for a
proportion <span class="math inline">\(p\)</span> (for example, the proportion of people agreeing with
some statement). Often, we want to know whether the proportion is
“really” greater than 0.5.<a href="#fn1" class="footnote-ref" id="fnref1"><sup>1</sup></a><br />
That would entail testing a null
<span class="math inline">\(H_0: p=0.5\)</span> against an alternative <span class="math inline">\(H_a: p&gt;0.5\)</span>. This is usually done
by calculating the test statistic
<span class="math display">\[ z = { \hat{p} - 0.5 \over \sqrt{0.25/n}},\]</span>
where <span class="math inline">\(\hat{p}\)</span> is the observed proportion in the sample,
and getting a P-value from the upper tail of a standard normal
distribution. (The 0.25 is <span class="math inline">\(p(1-p)\)</span> where <span class="math inline">\(p=0.5\)</span>.) This is what
<code>prop.test</code> does, as we investigate shortly.</p>
<ol style="list-style-type: lower-alpha">
<li><p>Use <code>rbinom</code> to generate a random value from a
binomial distribution with <span class="math inline">\(n=100\)</span> and <span class="math inline">\(p=0.6\)</span>. There are three
inputs to <code>rbinom</code>: the first one should be the number 1, and
the second and third are the <span class="math inline">\(n\)</span> and <span class="math inline">\(p\)</span> of the binomial distribution.</p></li>
<li><p>Using the random binomial that you generated just above, use
<code>prop.test</code> to test whether it could reasonably have come
from a binomial population with <span class="math inline">\(n=100\)</span> and <span class="math inline">\(p=0.5\)</span>, or whether <span class="math inline">\(p\)</span>
is actually bigger than 0.5. (Of course,
you know it actually did not come from a population with <span class="math inline">\(p=0.5\)</span>.)
<code>prop.test</code> has, for us, four inputs, thus:</p></li>
</ol>
<ul>
<li><p>the observed number of successes</p></li>
<li><p>the <code>n</code> of the binomial distribution</p></li>
<li><p>the null-hypothesis <code>p</code> of the binomial distribution</p></li>
<li><p>the alternative hypothesis, here “greater”</p></li>
</ul>
<ol start="3" style="list-style-type: lower-alpha">
<li><p>Run <code>prop.test</code> again, just as you did before, but this
time save the result, and extract the piece of it called
<code>p.value</code>. Is that the P-value from your test?</p></li>
<li><p>Estimate the power of a test of
<span class="math inline">\(H_0: p=0.5\)</span> against <span class="math inline">\(H_a: p&gt;0.5\)</span> when <span class="math inline">\(n=500\)</span> and <span class="math inline">\(p=0.56\)</span>, using
<span class="math inline">\(\alpha=0.05\)</span>. There are three steps:</p></li>
</ol>
<ul>
<li><p>generate random samples from binomial
distributions with <span class="math inline">\(n=500\)</span> and <span class="math inline">\(p=0.56\)</span>, repeated “many” times
(something like 1000 or 10,000 is good)</p></li>
<li><p>run <code>prop.test</code> on each of those
random samples</p></li>
<li><p>extract the P-value for each test and
save the results (in a column called, perhaps, <code>pvals</code>).</p></li>
</ul>
<p>So I lied: the fourth and final step is to count how many of
those P-values are 0.05 or less.</p>
</div>
<div id="designing-a-study-to-have-enough-power" class="section level2" number="8.4">
<h2><span class="header-section-number">8.4</span> Designing a study to have enough power</h2>
<p>You are designing a study to test the null hypothesis that a population mean is 0 against the alternative hypothesis that it is greater than 0. Assume that the population SD is <span class="math inline">\(\sigma=15\)</span>. It is important to detect the alternative <span class="math inline">\(\mu=2\)</span>; that is, we want to design the study so that most of the time the null hypothesis would be (correctly) rejected if in fact <span class="math inline">\(\mu=2\)</span>. A one-sample <span class="math inline">\(t\)</span>-test will be used, and the data values are assumed to have a normal distribution.</p>
<ol style="list-style-type: lower-alpha">
<li><p>Use simulation to estimate the power of this test when the sample size is 100. Use <span class="math inline">\(\alpha=0.05\)</span>.</p></li>
<li><p>Again by using simulation, estimate how large a sample size would be needed to obtain a power of 0.80. Show and briefly explain your process.</p></li>
</ol>
</div>
<div id="power-and-alpha-in-a-skewed-population" class="section level2" number="8.5">
<h2><span class="header-section-number">8.5</span> Power and <span class="math inline">\(\alpha\)</span> in a skewed population</h2>
<p>A population of a large number of values <code>v</code> is at , in a CSV file.</p>
<ol style="list-style-type: lower-alpha">
<li><p>Read in the population and display some of the values.</p></li>
<li><p>Obtain a suitable plot of your population. What do you notice?</p></li>
<li><p>If you take a sample of 10 observations from this population and run a <span class="math inline">\(t\)</span>-test, how likely are you to (correctly) reject the null hypothesis <span class="math inline">\(H_0: \mu = 4\)</span>, against the alternative <span class="math inline">\(H_a: \mu &gt; 4\)</span>? Investigate by simulation.</p></li>
<li><p>Try again with a sample size of 50 (leaving everything else the same). Explain briefly why the results so far are as you’d expect.</p></li>
<li><p>Again by simulation, estimate the probability that the null hypothesis <span class="math inline">\(H_0: \mu=5\)</span> will be rejected when a sample of size 10 is taken from this population, in favour of the alternative <span class="math inline">\(H_a: \mu &gt; 5\)</span>. Explain briefly why the answer is not what you would have expected, and why that happened here. (Hint: what is the population mean?)</p></li>
</ol>
<p>My solutions follow:</p>
</div>
<div id="simulating-power-1" class="section level2" number="8.6">
<h2><span class="header-section-number">8.6</span> Simulating power</h2>
<p>This question investigates power by
simulation.</p>
<ol style="list-style-type: lower-alpha">
<li>Use <code>rnorm</code> to generate 10 random values from a
normal distribution with mean 20 and SD 2. Do your values look
reasonable? Explain briefly. (You don’t need to draw a graph.)</li>
</ol>
<p>Solution</p>
<p><code>rnorm</code> with the number of values first, then the mean,
then the SD:</p>
<div class="sourceCode" id="cb2"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb2-1"><a href="power-and-sample-size.html#cb2-1"></a>x=<span class="kw">rnorm</span>(<span class="dv">10</span>,<span class="dv">20</span>,<span class="dv">2</span>)</span>
<span id="cb2-2"><a href="power-and-sample-size.html#cb2-2"></a>x</span></code></pre></div>
<pre><code>##  [1] 21.59476 18.64044 21.83231 18.76556 18.64861 21.81889 21.62614 20.18249 16.91266 20.63490</code></pre>
<p>95% of the sampled values should be within 2 SDs of the mean, that
is, between 16 and 24 (or 99.7% should be within 3 SDs of the mean,
between 14 and 26). None of my values are even outside the interval 16
to 24, though yours may be different.</p>
<p>I saved mine in a variable and then displayed them, which you don’t
need to do. I did because there’s another way of assessing them for
reasonableness: turn the sample into <span class="math inline">\(z\)</span>-scores and see whether the
values you get look like <span class="math inline">\(z\)</span>-scores (that is, most of them are between
<span class="math inline">\(-2\)</span> and 2, for example):</p>
<div class="sourceCode" id="cb4"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb4-1"><a href="power-and-sample-size.html#cb4-1"></a>(x<span class="dv">-20</span>)<span class="op">/</span><span class="dv">2</span></span></code></pre></div>
<pre><code>##  [1]  0.79738130 -0.67977910  0.91615386 -0.61722168 -0.67569291  0.90944266  0.81307163  0.09124563 -1.54367207  0.31744905</code></pre>
<p>These ones look very much like <span class="math inline">\(z\)</span>-scores. This, if you think about
it, is really the flip-side of 68–95–99.7, so it’s another way of
implementing the same idea.</p>
<p>You might also think of finding the <em>sample</em> mean and SD, and
demonstrating that they are close to the right answers. Mine are:</p>
<div class="sourceCode" id="cb6"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb6-1"><a href="power-and-sample-size.html#cb6-1"></a><span class="kw">mean</span>(x)</span></code></pre></div>
<pre><code>## [1] 20.06568</code></pre>
<div class="sourceCode" id="cb8"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb8-1"><a href="power-and-sample-size.html#cb8-1"></a><span class="kw">sd</span>(x)</span></code></pre></div>
<pre><code>## [1] 1.731305</code></pre>
<p>The sample SD is more variable than the sample mean, so it can get
further away from the population SD than the sample mean does from the
population mean.</p>
<p>The downside to this idea is that it doesn’t get at
assessing the normality, which looking at <span class="math inline">\(z\)</span>-scores or equivalent
does. Maybe coupling the above with a boxplot would have helped, had I
not said “no graphs”, since then you’d (hopefully) see no outliers
and a roughly symmetric shape.</p>
<p>This is old-fashioned “base R” technology; you could do it with a
data frame like this:</p>
<div class="sourceCode" id="cb10"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb10-1"><a href="power-and-sample-size.html#cb10-1"></a>d=<span class="kw">tibble</span>(<span class="dt">x=</span><span class="kw">rnorm</span>(<span class="dv">10</span>,<span class="dv">20</span>,<span class="dv">2</span>))</span>
<span id="cb10-2"><a href="power-and-sample-size.html#cb10-2"></a>d</span>
<span id="cb10-3"><a href="power-and-sample-size.html#cb10-3"></a>d <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">summarize</span>(<span class="dt">m=</span><span class="kw">mean</span>(x), <span class="dt">s=</span><span class="kw">sd</span>(x))</span></code></pre></div>
<p>These are different random numbers, but are about equally what you’d
expect. (These ones are a bit less variable than you’d expect, but
with only ten values, don’t expect perfection.)</p>
<p>Some discussion about the kind of values you should get, and whether
or not you get them, is what is called for here. I want you to say
something convincing about how the values you get come from a normal
distribution with mean 20 <em>and</em> SD 2. “Close to 20” is not the
whole answer here, because that doesn’t get at “how close to 20?”:
that is, it talks about the mean but not about the SD.</p>
<p><span class="math inline">\(\blacksquare\)</span></p>
<ol start="2" style="list-style-type: lower-alpha">
<li>Estimate by simulation the power of a <span class="math inline">\(t\)</span>-test to reject a
null hypothesis of 20 when the true mean is also 20, the
population SD is 2, and the sample size is 10, against a (default)
two-sided alternative. Remember the
steps: (i) generate a lot of random samples from the true
distribution, (ii) run the <span class="math inline">\(t\)</span>-test with the required null mean, (iii) pull out the P-values, (iv) count how many of them are 0.05
or less.</li>
</ol>
<p>Solution</p>
<p>Once you get the hang of these, they all look almost the
same. This one is easier than some because we don’t have to do
anything special to get a two-sided alternative hypothesis. The initial setup is to make a dataframe with a column called something like <code>sim</code> to label the simulations, and then a <code>rowwise</code> to generate one random sample, <span class="math inline">\(t\)</span>-test and P-value for each simulation:</p>
<div class="sourceCode" id="cb11"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb11-1"><a href="power-and-sample-size.html#cb11-1"></a><span class="kw">tibble</span>(<span class="dt">sim =</span> <span class="dv">1</span><span class="op">:</span><span class="dv">1000</span>) <span class="op">%&gt;%</span><span class="st"> </span></span>
<span id="cb11-2"><a href="power-and-sample-size.html#cb11-2"></a><span class="st">  </span><span class="kw">rowwise</span>() <span class="op">%&gt;%</span><span class="st"> </span></span>
<span id="cb11-3"><a href="power-and-sample-size.html#cb11-3"></a><span class="st">  </span><span class="kw">mutate</span>(<span class="dt">norm_sample =</span> <span class="kw">list</span>(<span class="kw">rnorm</span>(<span class="dv">10</span>, <span class="dv">20</span>, <span class="dv">2</span>))) <span class="op">%&gt;%</span><span class="st"> </span></span>
<span id="cb11-4"><a href="power-and-sample-size.html#cb11-4"></a><span class="st">  </span><span class="kw">mutate</span>(<span class="dt">t_test =</span> <span class="kw">list</span>(<span class="kw">t.test</span>(norm_sample, <span class="dt">mu =</span> <span class="dv">20</span>))) <span class="op">%&gt;%</span><span class="st"> </span></span>
<span id="cb11-5"><a href="power-and-sample-size.html#cb11-5"></a><span class="st">  </span><span class="kw">mutate</span>(<span class="dt">pval =</span> t_test<span class="op">$</span>p.value) <span class="op">%&gt;%</span><span class="st"> </span></span>
<span id="cb11-6"><a href="power-and-sample-size.html#cb11-6"></a><span class="st">  </span><span class="kw">count</span>(pval <span class="op">&lt;=</span><span class="st"> </span><span class="fl">0.05</span>)</span></code></pre></div>
<p>The power is about 4.2%. This seems depressingly small, but see the
next part. (Are you confused about something in this one? You have a right to be.)</p>
<p><span class="math inline">\(\blacksquare\)</span></p>
<ol start="3" style="list-style-type: lower-alpha">
<li>In the simulation you just did, was the null hypothesis true
or false? Do you want to reject the null hypothesis or not?
Explain briefly why the simulation results you got were (or were
not) about what you would expect.</li>
</ol>
<p>Solution</p>
<p>The null mean and the true mean were both 20: that is, the
null hypothesis was correct, and rejecting it would be a
mistake, to be precise a type I error. We were doing the test
at <span class="math inline">\(\alpha=0.05\)</span> (by comparing our collection of simulated
P-values with 0.05), so we should be making a type I error 5%
of the time. This is entirely in line with the 4.2% of
(wrong) rejections that I had.
Your estimation is likely to be different from mine, but you
should be rejecting about 5% of the time. If your result is
very different from 5%, that’s an invitation to go back and
check your code. On the other hand, if it <em>is</em> about 5%,
that ought to give you confidence to go on and use the same
ideas for the next part.</p>
<p><span class="math inline">\(\blacksquare\)</span></p>
<ol start="4" style="list-style-type: lower-alpha">
<li>By copying, pasting and editing your code from the previous
part, estimate the power of the test of <span class="math inline">\(H_0: \mu=20\)</span> (against a
two-sided alternative) when the true population mean is 22 (rather
than 20).</li>
</ol>
<p>Solution</p>
<p>Here’s the code we just used:</p>
<div class="sourceCode" id="cb12"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb12-1"><a href="power-and-sample-size.html#cb12-1"></a><span class="kw">tibble</span>(<span class="dt">sim =</span> <span class="dv">1</span><span class="op">:</span><span class="dv">1000</span>) <span class="op">%&gt;%</span><span class="st"> </span></span>
<span id="cb12-2"><a href="power-and-sample-size.html#cb12-2"></a><span class="st">  </span><span class="kw">rowwise</span>() <span class="op">%&gt;%</span><span class="st"> </span></span>
<span id="cb12-3"><a href="power-and-sample-size.html#cb12-3"></a><span class="st">  </span><span class="kw">mutate</span>(<span class="dt">norm_sample =</span> <span class="kw">list</span>(<span class="kw">rnorm</span>(<span class="dv">10</span>, <span class="dv">20</span>, <span class="dv">2</span>))) <span class="op">%&gt;%</span><span class="st"> </span></span>
<span id="cb12-4"><a href="power-and-sample-size.html#cb12-4"></a><span class="st">  </span><span class="kw">mutate</span>(<span class="dt">t_test =</span> <span class="kw">list</span>(<span class="kw">t.test</span>(norm_sample, <span class="dt">mu =</span> <span class="dv">20</span>))) <span class="op">%&gt;%</span><span class="st"> </span></span>
<span id="cb12-5"><a href="power-and-sample-size.html#cb12-5"></a><span class="st">  </span><span class="kw">mutate</span>(<span class="dt">pval =</span> t_test<span class="op">$</span>p.value) <span class="op">%&gt;%</span><span class="st"> </span></span>
<span id="cb12-6"><a href="power-and-sample-size.html#cb12-6"></a><span class="st">  </span><span class="kw">count</span>(pval <span class="op">&lt;=</span><span class="st"> </span><span class="fl">0.05</span>)</span></code></pre></div>
<p>One of those 20s needs to become 22. Not the one in the
<code>t.test</code>, since the hypotheses have not changed. So we need to
change the 20 in the <code>rnorm</code> line to 22, since that’s where
we’re generating data from the true distribution. The rest of it stays
the same:</p>
<div class="sourceCode" id="cb13"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb13-1"><a href="power-and-sample-size.html#cb13-1"></a><span class="kw">tibble</span>(<span class="dt">sim =</span> <span class="dv">1</span><span class="op">:</span><span class="dv">1000</span>) <span class="op">%&gt;%</span><span class="st"> </span></span>
<span id="cb13-2"><a href="power-and-sample-size.html#cb13-2"></a><span class="st">  </span><span class="kw">rowwise</span>() <span class="op">%&gt;%</span><span class="st"> </span></span>
<span id="cb13-3"><a href="power-and-sample-size.html#cb13-3"></a><span class="st">  </span><span class="kw">mutate</span>(<span class="dt">norm_sample =</span> <span class="kw">list</span>(<span class="kw">rnorm</span>(<span class="dv">10</span>, <span class="dv">20</span>, <span class="dv">2</span>))) <span class="op">%&gt;%</span><span class="st"> </span></span>
<span id="cb13-4"><a href="power-and-sample-size.html#cb13-4"></a><span class="st">  </span><span class="kw">mutate</span>(<span class="dt">t_test =</span> <span class="kw">list</span>(<span class="kw">t.test</span>(norm_sample, <span class="dt">mu =</span> <span class="dv">22</span>))) <span class="op">%&gt;%</span><span class="st"> </span></span>
<span id="cb13-5"><a href="power-and-sample-size.html#cb13-5"></a><span class="st">  </span><span class="kw">mutate</span>(<span class="dt">pval =</span> t_test<span class="op">$</span>p.value) <span class="op">%&gt;%</span><span class="st"> </span></span>
<span id="cb13-6"><a href="power-and-sample-size.html#cb13-6"></a><span class="st">  </span><span class="kw">count</span>(pval <span class="op">&lt;=</span><span class="st"> </span><span class="fl">0.05</span>)</span></code></pre></div>
<p>This time, we <em>want</em> to reject, since the null hypothesis is
false. So look at the <code>TRUE</code> count: the power is about
<span class="math inline">\(80\%\)</span>. We are very likely to correctly reject a null
of 20 when the mean is actually 22.</p>
<p>Extra: another way to reason that the power should be fairly large is to
think about what kind of sample you are likely to get from the true
distribution: one with a mean around 22 and an SD around 2. Thus the
<span class="math inline">\(t\)</span>-statistic should be somewhere around this (we have a sample size
of 10):</p>
<div class="sourceCode" id="cb14"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb14-1"><a href="power-and-sample-size.html#cb14-1"></a>t_stat=(<span class="dv">22-20</span>)<span class="op">/</span>(<span class="dv">2</span><span class="op">/</span><span class="kw">sqrt</span>(<span class="dv">10</span>))</span>
<span id="cb14-2"><a href="power-and-sample-size.html#cb14-2"></a>t_stat</span></code></pre></div>
<pre><code>## [1] 3.162278</code></pre>
<p>and the two-sided P-value should be about</p>
<div class="sourceCode" id="cb16"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb16-1"><a href="power-and-sample-size.html#cb16-1"></a><span class="dv">2</span><span class="op">*</span>(<span class="dv">1</span><span class="op">-</span><span class="kw">pt</span>(t_stat,<span class="dv">10-1</span>))</span></code></pre></div>
<pre><code>## [1] 0.01150799</code></pre>
<p>Of course, with your actual data, you will sometimes be less lucky
than this (a sample mean nearer 20 or a larger sample SD), but
sometimes you will be luckier. But the suggestion is that most of the
time, the P-value will be pretty small and you will end up correctly
rejecting.</p>
<p>The quantity <code>t_stat</code> above, 3.16, is known to some
people as an “effect size”, and summarizes how far apart the null
and true means are, relative to the amount of variability present (in
the sampling distribution of the sample mean). As effect sizes go,
this one is pretty large.</p>
<p><span class="math inline">\(\blacksquare\)</span></p>
<ol start="5" style="list-style-type: lower-alpha">
<li>Use R to calculate this power exactly (without
simulation). Compare the exact result with your simulation.</li>
</ol>
<p>Solution</p>
<p>This is <code>power.t.test</code>. The quantity <code>delta</code> is
the difference between true and null means:</p>
<div class="sourceCode" id="cb18"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb18-1"><a href="power-and-sample-size.html#cb18-1"></a><span class="kw">power.t.test</span>(<span class="dt">n=</span><span class="dv">10</span>,<span class="dt">delta=</span><span class="dv">22-20</span>,<span class="dt">sd=</span><span class="dv">2</span>,<span class="dt">type=</span><span class="st">&quot;one.sample&quot;</span>,<span class="dt">alternative=</span><span class="st">&quot;two.sided&quot;</span>)</span></code></pre></div>
<pre><code>## 
##      One-sample t test power calculation 
## 
##               n = 10
##           delta = 2
##              sd = 2
##       sig.level = 0.05
##           power = 0.8030962
##     alternative = two.sided</code></pre>
<p>This, 0.803, is very close to the value I got from my
simulation. Which makes me think I did them both right. This is not a watertight proof, though: for example, I might have made a mistake and gotten lucky somewhere. But it does at least give me confidence.</p>
<p>Extra: when you estimate power by simulation, what you are doing is
rejecting or not with a certain probability (which is the same for all
simulations). So the number of times you actually <em>do</em> reject has
a binomial distribution with <span class="math inline">\(n\)</span> equal to the number of simulated
P-values you got (1000 in my case; you could do more) and a <span class="math inline">\(p\)</span> that
the simulation is trying to estimate. This is inference for a
proportion, exactly what <code>prop.test</code> does.</p>
<p>Recall that <code>prop.test</code> has as input:</p>
<ul>
<li><p>a number of “successes” (rejections of the null in our case)</p></li>
<li><p>the number of trials (simulated tests)</p></li>
<li><p>the null-hypothesis value of <code>p</code> (optional if you only
want a CI)</p></li>
<li><p>(optional) a confidence level <code>conf.level</code>.</p></li>
</ul>
<p>In part (b), we knew that the probability of
(incorrectly) rejecting should have been 0.05 and we rejected 42 times
out of 1000:</p>
<div class="sourceCode" id="cb20"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb20-1"><a href="power-and-sample-size.html#cb20-1"></a><span class="kw">prop.test</span>(<span class="dv">42</span>,<span class="dv">1000</span>,<span class="fl">0.05</span>)</span></code></pre></div>
<pre><code>## 
##  1-sample proportions test with continuity correction
## 
## data:  42 out of 1000, null probability 0.05
## X-squared = 1.1842, df = 1, p-value = 0.2765
## alternative hypothesis: true p is not equal to 0.05
## 95 percent confidence interval:
##  0.03079269 0.05685194
## sample estimates:
##     p 
## 0.042</code></pre>
<p>** check that the values are correct below **</p>
<p>Looking at the P-value, we definitely fail to reject that the
probability of (incorrectly) rejecting is the 0.05 that it should
be. Ouch. That’s true, but unnecessarily confusing. Look at the
confidence interval instead, 0.031 to 0.057. The right answer is 0.05,
which is inside that interval, so good.</p>
<p>In part (c), we didn’t know what the power was going
to be (not until we calculated it with <code>power.t.test</code>, anyway),
so we go straight for a confidence interval; the default 95% confidence
level is fine. We (correctly) rejected 798 times out of 1000:</p>
<div class="sourceCode" id="cb22"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb22-1"><a href="power-and-sample-size.html#cb22-1"></a><span class="kw">prop.test</span>(<span class="dv">798</span>,<span class="dv">1000</span>)</span></code></pre></div>
<pre><code>## 
##  1-sample proportions test with continuity correction
## 
## data:  798 out of 1000, null probability 0.5
## X-squared = 354.02, df = 1, p-value &lt; 2.2e-16
## alternative hypothesis: true p is not equal to 0.5
## 95 percent confidence interval:
##  0.7714759 0.8221976
## sample estimates:
##     p 
## 0.798</code></pre>
<p>I left out the 3rd input since we’re not doing a test, and ignore the
P-value that comes out. (The default null proportion is 0.5, which
often makes sense, but not here.)</p>
<p>According to the confidence interval, the estimated power is between
0.771 and 0.822. This interval definitely includes what we now know is
the right answer of 0.803.</p>
<p>This might be an accurate enough assessment of the power for you, but
if not, you can do more simulations, say 10,000:</p>
<div class="sourceCode" id="cb24"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb24-1"><a href="power-and-sample-size.html#cb24-1"></a><span class="kw">tibble</span>(<span class="dt">sim =</span> <span class="dv">1</span><span class="op">:</span><span class="dv">10000</span>) <span class="op">%&gt;%</span><span class="st"> </span></span>
<span id="cb24-2"><a href="power-and-sample-size.html#cb24-2"></a><span class="st">  </span><span class="kw">rowwise</span>() <span class="op">%&gt;%</span><span class="st"> </span></span>
<span id="cb24-3"><a href="power-and-sample-size.html#cb24-3"></a><span class="st">  </span><span class="kw">mutate</span>(<span class="dt">norm_sample =</span> <span class="kw">list</span>(<span class="kw">rnorm</span>(<span class="dv">10</span>, <span class="dv">20</span>, <span class="dv">2</span>))) <span class="op">%&gt;%</span><span class="st"> </span></span>
<span id="cb24-4"><a href="power-and-sample-size.html#cb24-4"></a><span class="st">  </span><span class="kw">mutate</span>(<span class="dt">t_test =</span> <span class="kw">list</span>(<span class="kw">t.test</span>(norm_sample, <span class="dt">mu =</span> <span class="dv">22</span>))) <span class="op">%&gt;%</span><span class="st"> </span></span>
<span id="cb24-5"><a href="power-and-sample-size.html#cb24-5"></a><span class="st">  </span><span class="kw">mutate</span>(<span class="dt">pval =</span> t_test<span class="op">$</span>p.value) <span class="op">%&gt;%</span><span class="st"> </span></span>
<span id="cb24-6"><a href="power-and-sample-size.html#cb24-6"></a><span class="st">  </span><span class="kw">count</span>(pval <span class="op">&lt;=</span><span class="st"> </span><span class="fl">0.05</span>)</span></code></pre></div>
<p>I copied and pasted my code again, which means that I’m dangerously
close to turning it into a function, but anyway.</p>
<p>The confidence interval for the power is then</p>
<div class="sourceCode" id="cb25"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb25-1"><a href="power-and-sample-size.html#cb25-1"></a><span class="kw">prop.test</span>(<span class="dv">7996</span>,<span class="dv">10000</span>)</span></code></pre></div>
<pre><code>## 
##  1-sample proportions test with continuity correction
## 
## data:  7996 out of 10000, null probability 0.5
## X-squared = 3589.2, df = 1, p-value &lt; 2.2e-16
## alternative hypothesis: true p is not equal to 0.5
## 95 percent confidence interval:
##  0.7915892 0.8073793
## sample estimates:
##      p 
## 0.7996</code></pre>
<p>that is, from 0.792 to 0.807, which once again includes the right
answer of 0.803. The first interval, based on 1,000 simulations, has
length 0.051, while this interval has length 0.015. The first
interval is more than three times as long as the second, which is
about what you’d expect since the first one is based on 10 times fewer
simulations, and thus ought to be a factor of <span class="math inline">\(\sqrt{10}\simeq 3.16\)</span>
times longer.</p>
<p>This means that you can estimate power as accurately as you like by
doing a large enough (possibly very large) number of simulations. Provided, that is, that
you are prepared to wait a possibly long time for it to finish working!</p>
<p><span class="math inline">\(\blacksquare\)</span></p>
</div>
<div id="calculating-power-and-sample-size-for-estimating-mean-1" class="section level2" number="8.7">
<h2><span class="header-section-number">8.7</span> Calculating power and sample size for estimating mean</h2>
<p>We are planning a study to estimate a population mean. The
population standard deviation is believed to be 20, and the population
distribution is believed to be approximately normal. We will be
testing the null hypothesis that the population mean is 100. Suppose
the population mean is actually 110, and we want to determine how
likely we are to (correctly) reject the null hypothesis in this case,
using a two-sided (but one-sample) test with <span class="math inline">\(\alpha=0.05\)</span>.</p>
<ol style="list-style-type: lower-alpha">
<li>We will take a sample of size <span class="math inline">\(n=30\)</span>. Calculate the power of
this test.</li>
</ol>
<p>Solution</p>
<p><code>power.t.test</code>. Fill in: sample size <code>n</code>, difference
in means <code>delta</code> (<span class="math inline">\(10=110-100\)</span>), population SD <code>sd</code>,
type of test <code>type</code> (<code>one.sample</code>) and kind of
alternative hypothesis <code>alternative</code>
(<code>two.sided</code>). Leave out <code>power</code> since that’s what
we want:</p>
<div class="sourceCode" id="cb27"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb27-1"><a href="power-and-sample-size.html#cb27-1"></a><span class="kw">power.t.test</span>(<span class="dt">n=</span><span class="dv">30</span>,<span class="dt">delta=</span><span class="dv">10</span>,<span class="dt">sd=</span><span class="dv">20</span>,<span class="dt">type=</span><span class="st">&quot;one.sample&quot;</span>,<span class="dt">alternative=</span><span class="st">&quot;two.sided&quot;</span>)</span></code></pre></div>
<pre><code>## 
##      One-sample t test power calculation 
## 
##               n = 30
##           delta = 10
##              sd = 20
##       sig.level = 0.05
##           power = 0.7539627
##     alternative = two.sided</code></pre>
<p>I meant “calculate” exactly rather than “estimate” (by
simulation). Though if you want to, you can do that as well, thus:</p>
<div class="sourceCode" id="cb29"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb29-1"><a href="power-and-sample-size.html#cb29-1"></a><span class="kw">tibble</span>(<span class="dt">sim =</span> <span class="dv">1</span><span class="op">:</span><span class="dv">1000</span>) <span class="op">%&gt;%</span><span class="st"> </span></span>
<span id="cb29-2"><a href="power-and-sample-size.html#cb29-2"></a><span class="st">  </span><span class="kw">rowwise</span>() <span class="op">%&gt;%</span><span class="st"> </span></span>
<span id="cb29-3"><a href="power-and-sample-size.html#cb29-3"></a><span class="st">  </span><span class="kw">mutate</span>(<span class="dt">samples =</span> <span class="kw">list</span>(<span class="kw">rnorm</span>(<span class="dv">30</span>, <span class="dv">110</span>, <span class="dv">20</span>))) <span class="op">%&gt;%</span><span class="st"> </span></span>
<span id="cb29-4"><a href="power-and-sample-size.html#cb29-4"></a><span class="st">  </span><span class="kw">mutate</span>(<span class="dt">ttest =</span> <span class="kw">list</span>(<span class="kw">t.test</span>(samples, <span class="dt">mu=</span> <span class="dv">100</span>))) <span class="op">%&gt;%</span><span class="st"> </span></span>
<span id="cb29-5"><a href="power-and-sample-size.html#cb29-5"></a><span class="st">  </span><span class="kw">mutate</span>(<span class="dt">pvals =</span> ttest<span class="op">$</span>p.value) <span class="op">%&gt;%</span><span class="st"> </span></span>
<span id="cb29-6"><a href="power-and-sample-size.html#cb29-6"></a><span class="st">  </span><span class="kw">count</span>(pvals<span class="op">&lt;=</span><span class="fl">0.05</span>)</span></code></pre></div>
<p>That came out alarmingly close to the exact answer.</p>
<p><span class="math inline">\(\blacksquare\)</span></p>
<ol start="2" style="list-style-type: lower-alpha">
<li>Find the sample size necessary to obtain a power
of at least 0.80 under these conditions. What sample size do you
need? Explain briefly how your answer is
consistent with (a).</li>
</ol>
<p>Solution</p>
<p>Again, the implication is “by calculation”.
This time, in <code>power.t.test</code>, put in 0.80 for
<code>power</code> and leave out <code>n</code>. The order of things
doesn’t matter (since I have named everything that’s going into
<code>power.t.test</code>):</p>
<div class="sourceCode" id="cb30"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb30-1"><a href="power-and-sample-size.html#cb30-1"></a><span class="kw">power.t.test</span>(<span class="dt">delta=</span><span class="dv">10</span>,<span class="dt">power=</span><span class="fl">0.80</span>,<span class="dt">sd=</span><span class="dv">20</span>,<span class="dt">type=</span><span class="st">&quot;one.sample&quot;</span>,<span class="dt">alternative=</span><span class="st">&quot;two.sided&quot;</span>)  </span></code></pre></div>
<pre><code>## 
##      One-sample t test power calculation 
## 
##               n = 33.3672
##           delta = 10
##              sd = 20
##       sig.level = 0.05
##           power = 0.8
##     alternative = two.sided</code></pre>
<p>To get sample size for power at least 0.80, we have to round 33.36
<em>up</em> to the next whole number, ie. <span class="math inline">\(n=34\)</span> is needed. (A sample
of size 33 wouldn’t quite have enough power.)</p>
<p>This answer is consistent with (a) because a sample size of 30 gave a
power a bit less than 0.80, and so to increase the power by a little
(0.75 to 0.80),
we had to increase the sample size by a little (30 to 34).</p>
<p>Extra: estimating sample sizes by simulation is tricky, because the sample size
has to be input to the simulation. That means your only strategy is to
try different sample sizes until you find one that gives the right power.</p>
<p>In this case, we know that a sample of size 30 doesn’t give quite
enough power, so we have to up the sample size a bit. How about we try
40? I copied and pasted my code from above and changed 30 to 40:</p>
<div class="sourceCode" id="cb32"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb32-1"><a href="power-and-sample-size.html#cb32-1"></a><span class="kw">tibble</span>(<span class="dt">sim =</span> <span class="dv">1</span><span class="op">:</span><span class="dv">1000</span>) <span class="op">%&gt;%</span><span class="st"> </span></span>
<span id="cb32-2"><a href="power-and-sample-size.html#cb32-2"></a><span class="st">  </span><span class="kw">rowwise</span>() <span class="op">%&gt;%</span><span class="st"> </span></span>
<span id="cb32-3"><a href="power-and-sample-size.html#cb32-3"></a><span class="st">  </span><span class="kw">mutate</span>(<span class="dt">samples =</span> <span class="kw">list</span>(<span class="kw">rnorm</span>(<span class="dv">40</span>, <span class="dv">110</span>, <span class="dv">20</span>))) <span class="op">%&gt;%</span><span class="st"> </span></span>
<span id="cb32-4"><a href="power-and-sample-size.html#cb32-4"></a><span class="st">  </span><span class="kw">mutate</span>(<span class="dt">ttest =</span> <span class="kw">list</span>(<span class="kw">t.test</span>(samples, <span class="dt">mu=</span> <span class="dv">100</span>))) <span class="op">%&gt;%</span><span class="st"> </span></span>
<span id="cb32-5"><a href="power-and-sample-size.html#cb32-5"></a><span class="st">  </span><span class="kw">mutate</span>(<span class="dt">pvals =</span> ttest<span class="op">$</span>p.value) <span class="op">%&gt;%</span><span class="st"> </span></span>
<span id="cb32-6"><a href="power-and-sample-size.html#cb32-6"></a><span class="st">  </span><span class="kw">count</span>(pvals<span class="op">&lt;=</span><span class="fl">0.05</span>)</span></code></pre></div>
<p>Now the power is a bit too big, so we don’t need a sample size quite
as big as 40. So probably our next guess would be 35. But before we
copy and paste again, we should be thinking about making a function of
it first, with the sample size as input. Copy-paste once more and edit:</p>
<div class="sourceCode" id="cb33"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb33-1"><a href="power-and-sample-size.html#cb33-1"></a>sim_power=<span class="cf">function</span>(n) {</span>
<span id="cb33-2"><a href="power-and-sample-size.html#cb33-2"></a>  <span class="kw">tibble</span>(<span class="dt">sim =</span> <span class="dv">1</span><span class="op">:</span><span class="dv">1000</span>) <span class="op">%&gt;%</span><span class="st"> </span></span>
<span id="cb33-3"><a href="power-and-sample-size.html#cb33-3"></a><span class="st">    </span><span class="kw">rowwise</span>() <span class="op">%&gt;%</span><span class="st"> </span></span>
<span id="cb33-4"><a href="power-and-sample-size.html#cb33-4"></a><span class="st">    </span><span class="kw">mutate</span>(<span class="dt">samples =</span> <span class="kw">list</span>(<span class="kw">rnorm</span>(n, <span class="dv">110</span>, <span class="dv">20</span>))) <span class="op">%&gt;%</span><span class="st"> </span></span>
<span id="cb33-5"><a href="power-and-sample-size.html#cb33-5"></a><span class="st">    </span><span class="kw">mutate</span>(<span class="dt">ttest =</span> <span class="kw">list</span>(<span class="kw">t.test</span>(samples, <span class="dt">mu=</span> <span class="dv">100</span>))) <span class="op">%&gt;%</span><span class="st"> </span></span>
<span id="cb33-6"><a href="power-and-sample-size.html#cb33-6"></a><span class="st">    </span><span class="kw">mutate</span>(<span class="dt">pvals =</span> ttest<span class="op">$</span>p.value) <span class="op">%&gt;%</span><span class="st"> </span></span>
<span id="cb33-7"><a href="power-and-sample-size.html#cb33-7"></a><span class="st">    </span><span class="kw">ungroup</span>() <span class="op">%&gt;%</span><span class="st"> </span></span>
<span id="cb33-8"><a href="power-and-sample-size.html#cb33-8"></a><span class="st">    </span><span class="kw">count</span>(pvals<span class="op">&lt;=</span><span class="fl">0.05</span>)</span>
<span id="cb33-9"><a href="power-and-sample-size.html#cb33-9"></a>}</span></code></pre></div>
<p>In the grand scheme of things, we might want to have the null and true
means, population SD and <span class="math inline">\(\alpha\)</span> be inputs to the function as well,
so that we have a more general tool, but this will do for now.</p>
<p>Let’s run it with a sample size of 35:</p>
<div class="sourceCode" id="cb34"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb34-1"><a href="power-and-sample-size.html#cb34-1"></a><span class="kw">sim_power</span>(<span class="dv">35</span>)</span></code></pre></div>
<p>and I’m going to call that good. (Because there is randomness in the
estimation of the power, don’t expect to get <em>too</em> close to the
right answer. This one came out a fair bit less than the right answer;
the power for <span class="math inline">\(n=35\)</span> should be a bit <em>more</em> than 0.80.)</p>
<p>Now that you have the software to do it, you can see that figuring out
a sample size like this, at least roughly, won’t take very long: each
one of these simulations takes maybe seconds to run, and all you have
to do is copy and paste the previous one, and edit it to contain the
new sample size before running it again. You’re making the computer
work hard while you lazily sip your coffee, but there’s no harm in
that: programmer’s brain cells are more valuable than computer CPU
cycles, and you might as well save your brain cells for when you
really need them.</p>
<p>You might even think about automating this further. The easiest way, now that we have the function, is something like this:</p>
<div class="sourceCode" id="cb35"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb35-1"><a href="power-and-sample-size.html#cb35-1"></a><span class="kw">tibble</span>(<span class="dt">ns =</span> <span class="kw">seq</span>(<span class="dv">20</span>, <span class="dv">50</span>, <span class="dv">5</span>)) <span class="op">%&gt;%</span><span class="st"> </span></span>
<span id="cb35-2"><a href="power-and-sample-size.html#cb35-2"></a><span class="st">  </span><span class="kw">rowwise</span>() <span class="op">%&gt;%</span><span class="st"> </span></span>
<span id="cb35-3"><a href="power-and-sample-size.html#cb35-3"></a><span class="st">  </span><span class="kw">mutate</span>(<span class="dt">power_tab =</span> <span class="kw">list</span>(<span class="kw">sim_power</span>(ns))) <span class="op">%&gt;%</span><span class="st"> </span></span>
<span id="cb35-4"><a href="power-and-sample-size.html#cb35-4"></a><span class="st">  </span><span class="kw">unnest</span>(power_tab) <span class="op">%&gt;%</span><span class="st"> </span></span>
<span id="cb35-5"><a href="power-and-sample-size.html#cb35-5"></a><span class="st">  </span><span class="kw">pivot_wider</span>(<span class="dt">names_from =</span> <span class="st">`</span><span class="dt">pvals &lt;= 0.05</span><span class="st">`</span>, <span class="dt">values_from =</span> n)</span></code></pre></div>
<p>The business end of this is happening in the first three lines. I wasn’t thinking of this when I originally wrote <code>sim_power</code> to return a dataframe, so there is a bit more fiddling after the simulations are done: I have to <code>unnest</code> to see what the list-column <code>power_tab</code> actually contains, and because of the layout of the output from unnesting <code>sim_power</code> (long format), it looks better if I pivot it wider, so that I can just cast my eye down the TRUE column and see the power increasing as the sample size increases.</p>
<p>You might also think of something like bisection to find the sample size that has power 0.8, but it starts getting tricky because of the randomness; just by chance, it may be that sometimes the simulated power goes <em>down</em> as the sample size goes up. With 1000 simulations each time, it seems that the power ought to hit 80% with a sample size between 30 and 35.</p>
</div>
<div id="simulating-power-for-proportions-1" class="section level2" number="8.8">
<h2><span class="header-section-number">8.8</span> Simulating power for proportions</h2>
<p>In opinion surveys (and other places), we are testing for a
proportion <span class="math inline">\(p\)</span> (for example, the proportion of people agreeing with
some statement). Often, we want to know whether the proportion is
“really” greater than 0.5.<a href="#fn2" class="footnote-ref" id="fnref2"><sup>2</sup></a><br />
That would entail testing a null
<span class="math inline">\(H_0: p=0.5\)</span> against an alternative <span class="math inline">\(H_a: p&gt;0.5\)</span>. This is usually done
by calculating the test statistic
<span class="math display">\[ z = { \hat{p} - 0.5 \over \sqrt{0.25/n}},\]</span>
where <span class="math inline">\(\hat{p}\)</span> is the observed proportion in the sample,
and getting a P-value from the upper tail of a standard normal
distribution. (The 0.25 is <span class="math inline">\(p(1-p)\)</span> where <span class="math inline">\(p=0.5\)</span>.) This is what
<code>prop.test</code> does, as we investigate shortly.</p>
<ol style="list-style-type: lower-alpha">
<li>Use <code>rbinom</code> to generate a random value from a
binomial distribution with <span class="math inline">\(n=100\)</span> and <span class="math inline">\(p=0.6\)</span>. There are three
inputs to <code>rbinom</code>: the first one should be the number 1, and
the second and third are the <span class="math inline">\(n\)</span> and <span class="math inline">\(p\)</span> of the binomial distribution.</li>
</ol>
<p>Solution</p>
<p>I am doing some preparatory work that you don’t need to do:</p>
<div class="sourceCode" id="cb36"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb36-1"><a href="power-and-sample-size.html#cb36-1"></a><span class="kw">set.seed</span>(<span class="dv">457299</span>)</span></code></pre></div>
<p>By setting the “seed” for the random number generator, I guarantee
that I will get the same answers every time I run my code below (and
therefore I can talk about my answers without worrying that they will
change). Up to you whether you do this. You can “seed” the random
number generator with any number you like. A lot of people use
<code>1</code>. Mahinda seems to like <code>123</code>. Mine is an old phone
number.</p>
<p>And so to work:</p>
<div class="sourceCode" id="cb37"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb37-1"><a href="power-and-sample-size.html#cb37-1"></a><span class="kw">rbinom</span>(<span class="dv">1</span>, <span class="dv">100</span>, <span class="fl">0.6</span>)</span></code></pre></div>
<pre><code>## [1] 60</code></pre>
<p>I got exactly 60% successes this time. You probably won’t get exactly
60, but you should get somewhere close. (If you use my random number
seed and use the random number generator exactly the same way I did,
you should get the same values I did.)</p>
<p>For fun, you can see what happens if you change the 1:</p>
<div class="sourceCode" id="cb39"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb39-1"><a href="power-and-sample-size.html#cb39-1"></a><span class="kw">rbinom</span>(<span class="dv">3</span>, <span class="dv">100</span>, <span class="fl">0.6</span>)</span></code></pre></div>
<pre><code>## [1] 58 57 55</code></pre>
<p>Three random binomials, that happened to come out just below 60. We’re
going to leave the first input as 1, though, and let <code>rowwise</code>
handle “lots of sampled values” later.</p>
<p><span class="math inline">\(\blacksquare\)</span></p>
<ol start="2" style="list-style-type: lower-alpha">
<li>Using the random binomial that you generated just above, use
<code>prop.test</code> to test whether it could reasonably have come
from a binomial population with <span class="math inline">\(n=100\)</span> and <span class="math inline">\(p=0.5\)</span>, or whether <span class="math inline">\(p\)</span>
is actually bigger than 0.5. (Of course,
you know it actually did not come from a population with <span class="math inline">\(p=0.5\)</span>.)
<code>prop.test</code> has, for us, four inputs, thus:</li>
</ol>
<ul>
<li><p>the observed number of successes</p></li>
<li><p>the <code>n</code> of the binomial distribution</p></li>
<li><p>the null-hypothesis <code>p</code> of the binomial distribution</p></li>
<li><p>the alternative hypothesis, here “greater”</p></li>
</ul>
<p>Solution</p>
<p>I got exactly 60 successes, so I do this:</p>
<div class="sourceCode" id="cb41"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb41-1"><a href="power-and-sample-size.html#cb41-1"></a><span class="kw">prop.test</span>(<span class="dv">60</span>, <span class="dv">100</span>, <span class="fl">0.5</span>, <span class="dt">alternative =</span> <span class="st">&quot;greater&quot;</span>)</span></code></pre></div>
<pre><code>## 
##  1-sample proportions test with continuity correction
## 
## data:  60 out of 100, null probability 0.5
## X-squared = 3.61, df = 1, p-value = 0.02872
## alternative hypothesis: true p is greater than 0.5
## 95 percent confidence interval:
##  0.5127842 1.0000000
## sample estimates:
##   p 
## 0.6</code></pre>
<p>The P-value should at least be fairly small, since 60 is a bit bigger
than 50. (Think about tossing a coin 100 times; would 60 heads make
you doubt the coin’s fairness? The above says it should.)</p>
<p><span class="math inline">\(\blacksquare\)</span></p>
<ol start="3" style="list-style-type: lower-alpha">
<li>Run <code>prop.test</code> again, just as you did before, but this
time save the result, and extract the piece of it called
<code>p.value</code>. Is that the P-value from your test?</li>
</ol>
<p>Solution</p>
<p>Copying and pasting:</p>
<div class="sourceCode" id="cb43"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb43-1"><a href="power-and-sample-size.html#cb43-1"></a>p_test &lt;-<span class="st"> </span><span class="kw">prop.test</span>(<span class="dv">60</span>, <span class="dv">100</span>, <span class="fl">0.5</span>, <span class="dt">alternative =</span> <span class="st">&quot;greater&quot;</span>)</span>
<span id="cb43-2"><a href="power-and-sample-size.html#cb43-2"></a>p_test<span class="op">$</span>p.value</span></code></pre></div>
<pre><code>## [1] 0.02871656</code></pre>
<p>Yep, the same.</p>
<p><span class="math inline">\(\blacksquare\)</span></p>
<ol start="4" style="list-style-type: lower-alpha">
<li>Estimate the power of a test of
<span class="math inline">\(H_0: p=0.5\)</span> against <span class="math inline">\(H_a: p&gt;0.5\)</span> when <span class="math inline">\(n=500\)</span> and <span class="math inline">\(p=0.56\)</span>, using
<span class="math inline">\(\alpha=0.05\)</span>. There are three steps:</li>
</ol>
<ul>
<li><p>generate random samples from binomial
distributions with <span class="math inline">\(n=500\)</span> and <span class="math inline">\(p=0.56\)</span>, repeated “many” times
(something like 1000 or 10,000 is good)</p></li>
<li><p>run <code>prop.test</code> on each of those
random samples</p></li>
<li><p>extract the P-value for each test and
save the results (in a column called, perhaps, <code>pvals</code>).</p></li>
</ul>
<p>So I lied: the fourth and final step is to count how many of
those P-values are 0.05 or less.</p>
<p>Solution</p>
<p>The first part of the first step is to create a column called something like <code>sim</code> that labels each simulated sample, and to make sure that everything happens rowwise. After that, you follow the procedure:</p>
<div class="sourceCode" id="cb45"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb45-1"><a href="power-and-sample-size.html#cb45-1"></a><span class="kw">tibble</span>(<span class="dt">sim =</span> <span class="dv">1</span><span class="op">:</span><span class="dv">1000</span>) <span class="op">%&gt;%</span><span class="st"> </span></span>
<span id="cb45-2"><a href="power-and-sample-size.html#cb45-2"></a><span class="st">  </span><span class="kw">rowwise</span>() <span class="op">%&gt;%</span><span class="st"> </span></span>
<span id="cb45-3"><a href="power-and-sample-size.html#cb45-3"></a><span class="st">  </span><span class="kw">mutate</span>(<span class="dt">sample =</span> <span class="kw">rbinom</span>(<span class="dv">1</span>, <span class="dv">500</span>, <span class="fl">0.56</span>)) <span class="op">%&gt;%</span><span class="st"> </span></span>
<span id="cb45-4"><a href="power-and-sample-size.html#cb45-4"></a><span class="st">  </span><span class="kw">mutate</span>(<span class="dt">test =</span> <span class="kw">list</span>(<span class="kw">prop.test</span>(sample, <span class="dv">500</span>, <span class="fl">0.5</span>, <span class="dt">alternative =</span> <span class="st">&quot;greater&quot;</span>))) <span class="op">%&gt;%</span><span class="st"> </span></span>
<span id="cb45-5"><a href="power-and-sample-size.html#cb45-5"></a><span class="st">  </span><span class="kw">mutate</span>(<span class="dt">pvals =</span> test<span class="op">$</span>p.value) <span class="op">%&gt;%</span><span class="st"> </span></span>
<span id="cb45-6"><a href="power-and-sample-size.html#cb45-6"></a><span class="st">  </span><span class="kw">count</span>(pvals <span class="op">&lt;=</span><span class="st"> </span><span class="fl">0.05</span>)</span></code></pre></div>
<p>The previous parts, using <code>rbinom</code> and <code>prop.test</code>,
were meant to provide you with the ingredients for this part.
The first step is to use <code>rbinom</code>. The first input is 1 since
we only want one random binomial each time (the <code>rowwise</code> will
handle the fact that you actually want lots of them; you only want one <em>per row</em> since you are working rowwise). The second step
runs <code>prop.test</code>; the first input to that is each one of the
numbers of successes from the first step. The last part is to pull out all the P-values and
make a table of them, just like the example in lecture.</p>
<p>The estimated power is about 85%. That is, if <span class="math inline">\(p\)</span> is actually 0.56
and we have a sample of size 500, we have a good chance of (correctly)
rejecting that <span class="math inline">\(p=0.5\)</span>.</p>
<p>Extra: It turns out that SAS can work out this power by calculation
(using <code>proc power</code>).
SAS says our power is also about 85%, as our simulation
said. I was actually pleased that my simulation came
out so close to the right answer.</p>
<p>In contrast to <code>power.t.test</code>, SAS’s <code>proc power</code>
handles power analyses for a lot of things, including analysis of
variance, correlation and (multiple) regression. What these have in
common is some normal-based theory that allows you (under assumptions
of sufficiently normal-shaped populations) to calculate the exact
answer (that is, the distribution of the test statistic when the
<em>alternative</em> hypothesis is true). The case we looked at is one
of those because of the normal approximation to the binomial: once <span class="math inline">\(n\)</span>
gets big, particularly if <span class="math inline">\(p\)</span> is somewhere near 0.5, the binomial is
very well approximated by a normal with the right mean and SD.</p>
<p>The moral of this story is that when you have a decently large sample,
<span class="math inline">\(n=500\)</span> in this case, <span class="math inline">\(p\)</span> doesn’t have to get very far away from 0.5
before you can correctly reject 0.5. Bear in mind that sample sizes
for estimating proportions need to be larger than those for estimating
means, so <span class="math inline">\(n=500\)</span> is large without being huge. The practical upshot
is that if you design a survey and give it to 500 (or more) randomly
chosen people, the proportion of people in favour doesn’t have to be
much above 50% for you to correctly infer that it <em>is</em> above
50%, most of the time.</p>
<p><span class="math inline">\(\blacksquare\)</span></p>
</div>
<div id="designing-a-study-to-have-enough-power-1" class="section level2" number="8.9">
<h2><span class="header-section-number">8.9</span> Designing a study to have enough power</h2>
<p>You are designing a study to test the null hypothesis that a population mean is 0 against the alternative hypothesis that it is greater than 0. Assume that the population SD is <span class="math inline">\(\sigma=15\)</span>. It is important to detect the alternative <span class="math inline">\(\mu=2\)</span>; that is, we want to design the study so that most of the time the null hypothesis would be (correctly) rejected if in fact <span class="math inline">\(\mu=2\)</span>. A one-sample <span class="math inline">\(t\)</span>-test will be used, and the data values are assumed to have a normal distribution.</p>
<ol style="list-style-type: lower-alpha">
<li>Use simulation to estimate the power of this test when the sample size is 100. Use <span class="math inline">\(\alpha=0.05\)</span>.</li>
</ol>
<p>Solution</p>
<p>Use at least 1000 simulations (more, if you’re willing to wait for it). In <code>rnorm</code>, the sample size is first, then the (true) population mean, then the (assumed) population SD:</p>
<div class="sourceCode" id="cb46"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb46-1"><a href="power-and-sample-size.html#cb46-1"></a><span class="kw">tibble</span>(<span class="dt">sim =</span> <span class="dv">1</span><span class="op">:</span><span class="dv">1000</span>) <span class="op">%&gt;%</span><span class="st"> </span></span>
<span id="cb46-2"><a href="power-and-sample-size.html#cb46-2"></a><span class="st">  </span><span class="kw">rowwise</span>() <span class="op">%&gt;%</span><span class="st"> </span></span>
<span id="cb46-3"><a href="power-and-sample-size.html#cb46-3"></a><span class="st">  </span><span class="kw">mutate</span>(<span class="dt">my_sample =</span> <span class="kw">list</span>(<span class="kw">rnorm</span>(<span class="dv">100</span>, <span class="dv">2</span>, <span class="dv">15</span>))) <span class="op">%&gt;%</span><span class="st"> </span></span>
<span id="cb46-4"><a href="power-and-sample-size.html#cb46-4"></a><span class="st">  </span><span class="kw">mutate</span>(<span class="dt">t_test =</span> <span class="kw">list</span>(<span class="kw">t.test</span>(my_sample, <span class="dt">mu =</span> <span class="dv">0</span>, <span class="dt">alternative =</span> <span class="st">&quot;greater&quot;</span>))) <span class="op">%&gt;%</span><span class="st"> </span></span>
<span id="cb46-5"><a href="power-and-sample-size.html#cb46-5"></a><span class="st">  </span><span class="kw">mutate</span>(<span class="dt">p_value =</span> t_test<span class="op">$</span>p.value) <span class="op">%&gt;%</span><span class="st"> </span></span>
<span id="cb46-6"><a href="power-and-sample-size.html#cb46-6"></a><span class="st">  </span><span class="kw">count</span>(p_value <span class="op">&lt;=</span><span class="st"> </span><span class="fl">0.05</span>)</span></code></pre></div>
<p>The power is (estimated as) a disappointing 0.361. Your answer won’t (most likely) be the same as this, but it should be somewhere close. I would like to see you demonstrate that you know what power is, for example “if the population mean is actually 2, the null hypothesis <span class="math inline">\(H_0: \mu = 0\)</span>, which is wrong, will only be rejected about 36% of the time.”<a href="#fn3" class="footnote-ref" id="fnref3"><sup>3</sup></a></p>
<p>The test we are doing is one-sided, so you need the <code>alternative</code> in there. If you omit it, you’ll have the answer to a different problem:</p>
<div class="sourceCode" id="cb47"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb47-1"><a href="power-and-sample-size.html#cb47-1"></a><span class="kw">tibble</span>(<span class="dt">sim =</span> <span class="dv">1</span><span class="op">:</span><span class="dv">1000</span>) <span class="op">%&gt;%</span><span class="st"> </span></span>
<span id="cb47-2"><a href="power-and-sample-size.html#cb47-2"></a><span class="st">  </span><span class="kw">rowwise</span>() <span class="op">%&gt;%</span><span class="st"> </span></span>
<span id="cb47-3"><a href="power-and-sample-size.html#cb47-3"></a><span class="st">  </span><span class="kw">mutate</span>(<span class="dt">my_sample =</span> <span class="kw">list</span>(<span class="kw">rnorm</span>(<span class="dv">100</span>, <span class="dv">2</span>, <span class="dv">15</span>))) <span class="op">%&gt;%</span><span class="st"> </span></span>
<span id="cb47-4"><a href="power-and-sample-size.html#cb47-4"></a><span class="st">  </span><span class="kw">mutate</span>(<span class="dt">t_test =</span> <span class="kw">list</span>(<span class="kw">t.test</span>(my_sample, <span class="dt">mu =</span> <span class="dv">0</span>))) <span class="op">%&gt;%</span><span class="st"> </span></span>
<span id="cb47-5"><a href="power-and-sample-size.html#cb47-5"></a><span class="st">  </span><span class="kw">mutate</span>(<span class="dt">p_value =</span> t_test<span class="op">$</span>p.value) <span class="op">%&gt;%</span><span class="st"> </span></span>
<span id="cb47-6"><a href="power-and-sample-size.html#cb47-6"></a><span class="st">  </span><span class="kw">count</span>(p_value <span class="op">&lt;=</span><span class="st"> </span><span class="fl">0.05</span>)</span></code></pre></div>
<p>This is the probability that you reject <span class="math inline">\(H_0: \mu=0\)</span> in favour of <span class="math inline">\(H_a: \mu \ne 0\)</span>. This is smaller, because the test is “wasting effort” allowing the possibility of rejecting when the sample mean is far enough <em>less</em> than zero, when most of the time the samples drawn from the true distribution have mean greater than zero. (If you get a sample mean of 2.5, say, the P-value for a one-sided test will be smaller than for a two-sided one.)</p>
<p>Extra 1:</p>
<p>This low power of 0.361 is because the population SD is large relative to the kind of difference from the null that we are hoping to find. To get a sense of how big the power might be, imagine you draw a “typical” sample from the true population: it will have a sample mean of 2 and a sample SD of 15, so that <span class="math inline">\(t\)</span> will be about</p>
<div class="sourceCode" id="cb48"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb48-1"><a href="power-and-sample-size.html#cb48-1"></a>(<span class="dv">2-0</span>)<span class="op">/</span>(<span class="dv">15</span><span class="op">/</span><span class="kw">sqrt</span>(<span class="dv">100</span>))</span></code></pre></div>
<pre><code>## [1] 1.333333</code></pre>
<p>You won’t reject with this (<span class="math inline">\(t\)</span> would have to be bigger than 2), so in the cases where you <em>do</em> reject, you’ll have to be more lucky: you’ll need a sample mean bigger than 2, or a sample SD smaller than 15. So the power won’t be very big, less than 0.5, because about half the time you’ll get a test statistic less than 1.33 and about half the time more, and not all of <em>those</em> will lead to rejection.</p>
<p>Extra 2:</p>
<p>This is exactly the situation where <code>power.t.test</code> works, so we can get the exact answer (you need all the pieces):</p>
<div class="sourceCode" id="cb50"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb50-1"><a href="power-and-sample-size.html#cb50-1"></a><span class="kw">power.t.test</span>(<span class="dt">n=</span><span class="dv">100</span>, <span class="dt">delta=</span><span class="dv">2-0</span>, <span class="dt">sd=</span><span class="dv">15</span>, <span class="dt">type=</span><span class="st">&quot;one.sample&quot;</span>, </span>
<span id="cb50-2"><a href="power-and-sample-size.html#cb50-2"></a><span class="dt">alternative =</span> <span class="st">&quot;one.sided&quot;</span>)</span></code></pre></div>
<pre><code>## 
##      One-sample t test power calculation 
## 
##               n = 100
##           delta = 2
##              sd = 15
##       sig.level = 0.05
##           power = 0.3742438
##     alternative = one.sided</code></pre>
<p>Your answer, from 1000 simulations, should be within about 3 percentage points of that. (Mine was only about 1 percentage point off.)</p>
<p><span class="math inline">\(\blacksquare\)</span></p>
<ol start="2" style="list-style-type: lower-alpha">
<li>Again by using simulation, estimate how large a sample size would be needed to obtain a power of 0.80. Show and briefly explain your process.</li>
</ol>
<p>Solution</p>
<p>The point of this one is the process as well as the final answer, so you need to show and justify what you are doing. Showing only a final answer <em>does not</em> show that you know how to do it. The <em>whole point</em> of this one is to make mistakes and fix them!</p>
<p>The simulation approach does not immediately give you a sample size for fixed power, so what you have to do is to try different sample sizes until you get one that gives a power close enough to 0.80. You have to decide what “close enough” means for you, given that the simulations have randomness in them. I’m going to use 10,000 simulations for each of my attempts, in the hope of getting a more accurate answer.</p>
<p>First off, for a sample size of 100, the power was too small, so the answer had better be bigger than 100. I’ll try 200. For these, copy and paste the code, changing the sample size each time:</p>
<div class="sourceCode" id="cb52"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb52-1"><a href="power-and-sample-size.html#cb52-1"></a><span class="kw">tibble</span>(<span class="dt">sim =</span> <span class="dv">1</span><span class="op">:</span><span class="dv">10000</span>) <span class="op">%&gt;%</span><span class="st"> </span></span>
<span id="cb52-2"><a href="power-and-sample-size.html#cb52-2"></a><span class="st">  </span><span class="kw">rowwise</span>() <span class="op">%&gt;%</span><span class="st"> </span></span>
<span id="cb52-3"><a href="power-and-sample-size.html#cb52-3"></a><span class="st">  </span><span class="kw">mutate</span>(<span class="dt">my_sample =</span> <span class="kw">list</span>(<span class="kw">rnorm</span>(<span class="dv">200</span>, <span class="dv">2</span>, <span class="dv">15</span>))) <span class="op">%&gt;%</span><span class="st"> </span></span>
<span id="cb52-4"><a href="power-and-sample-size.html#cb52-4"></a><span class="st">  </span><span class="kw">mutate</span>(<span class="dt">t_test =</span> <span class="kw">list</span>(<span class="kw">t.test</span>(my_sample, <span class="dt">mu =</span> <span class="dv">0</span>, <span class="dt">alternative =</span> <span class="st">&quot;greater&quot;</span>))) <span class="op">%&gt;%</span><span class="st"> </span></span>
<span id="cb52-5"><a href="power-and-sample-size.html#cb52-5"></a><span class="st">  </span><span class="kw">mutate</span>(<span class="dt">p_value =</span> t_test<span class="op">$</span>p.value) <span class="op">%&gt;%</span><span class="st"> </span></span>
<span id="cb52-6"><a href="power-and-sample-size.html#cb52-6"></a><span class="st">  </span><span class="kw">count</span>(p_value <span class="op">&lt;=</span><span class="st"> </span><span class="fl">0.05</span>)</span></code></pre></div>
<p>A sample size of 200 isn’t big enough yet. I’ll double again to 400:</p>
<div class="sourceCode" id="cb53"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb53-1"><a href="power-and-sample-size.html#cb53-1"></a><span class="kw">tibble</span>(<span class="dt">sim =</span> <span class="dv">1</span><span class="op">:</span><span class="dv">10000</span>) <span class="op">%&gt;%</span><span class="st"> </span></span>
<span id="cb53-2"><a href="power-and-sample-size.html#cb53-2"></a><span class="st">  </span><span class="kw">rowwise</span>() <span class="op">%&gt;%</span><span class="st"> </span></span>
<span id="cb53-3"><a href="power-and-sample-size.html#cb53-3"></a><span class="st">  </span><span class="kw">mutate</span>(<span class="dt">my_sample =</span> <span class="kw">list</span>(<span class="kw">rnorm</span>(<span class="dv">400</span>, <span class="dv">2</span>, <span class="dv">15</span>))) <span class="op">%&gt;%</span><span class="st"> </span></span>
<span id="cb53-4"><a href="power-and-sample-size.html#cb53-4"></a><span class="st">  </span><span class="kw">mutate</span>(<span class="dt">t_test =</span> <span class="kw">list</span>(<span class="kw">t.test</span>(my_sample, <span class="dt">mu =</span> <span class="dv">0</span>, <span class="dt">alternative =</span> <span class="st">&quot;greater&quot;</span>))) <span class="op">%&gt;%</span><span class="st"> </span></span>
<span id="cb53-5"><a href="power-and-sample-size.html#cb53-5"></a><span class="st">  </span><span class="kw">mutate</span>(<span class="dt">p_value =</span> t_test<span class="op">$</span>p.value) <span class="op">%&gt;%</span><span class="st"> </span></span>
<span id="cb53-6"><a href="power-and-sample-size.html#cb53-6"></a><span class="st">  </span><span class="kw">count</span>(p_value <span class="op">&lt;=</span><span class="st"> </span><span class="fl">0.05</span>)</span></code></pre></div>
<p>Getting closer. 400 is too big, but closer than 200. 350?</p>
<div class="sourceCode" id="cb54"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb54-1"><a href="power-and-sample-size.html#cb54-1"></a><span class="kw">tibble</span>(<span class="dt">sim =</span> <span class="dv">1</span><span class="op">:</span><span class="dv">10000</span>) <span class="op">%&gt;%</span><span class="st"> </span></span>
<span id="cb54-2"><a href="power-and-sample-size.html#cb54-2"></a><span class="st">  </span><span class="kw">rowwise</span>() <span class="op">%&gt;%</span><span class="st"> </span></span>
<span id="cb54-3"><a href="power-and-sample-size.html#cb54-3"></a><span class="st">  </span><span class="kw">mutate</span>(<span class="dt">my_sample =</span> <span class="kw">list</span>(<span class="kw">rnorm</span>(<span class="dv">350</span>, <span class="dv">2</span>, <span class="dv">15</span>))) <span class="op">%&gt;%</span><span class="st"> </span></span>
<span id="cb54-4"><a href="power-and-sample-size.html#cb54-4"></a><span class="st">  </span><span class="kw">mutate</span>(<span class="dt">t_test =</span> <span class="kw">list</span>(<span class="kw">t.test</span>(my_sample, <span class="dt">mu =</span> <span class="dv">0</span>, <span class="dt">alternative =</span> <span class="st">&quot;greater&quot;</span>))) <span class="op">%&gt;%</span><span class="st"> </span></span>
<span id="cb54-5"><a href="power-and-sample-size.html#cb54-5"></a><span class="st">  </span><span class="kw">mutate</span>(<span class="dt">p_value =</span> t_test<span class="op">$</span>p.value) <span class="op">%&gt;%</span><span class="st"> </span></span>
<span id="cb54-6"><a href="power-and-sample-size.html#cb54-6"></a><span class="st">  </span><span class="kw">count</span>(p_value <span class="op">&lt;=</span><span class="st"> </span><span class="fl">0.05</span>)</span></code></pre></div>
<p>Close! I reckon you could call that good (see below), or try again with a sample size a bit less than 350:</p>
<div class="sourceCode" id="cb55"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb55-1"><a href="power-and-sample-size.html#cb55-1"></a><span class="kw">tibble</span>(<span class="dt">sim =</span> <span class="dv">1</span><span class="op">:</span><span class="dv">10000</span>) <span class="op">%&gt;%</span><span class="st"> </span></span>
<span id="cb55-2"><a href="power-and-sample-size.html#cb55-2"></a><span class="st">  </span><span class="kw">rowwise</span>() <span class="op">%&gt;%</span><span class="st"> </span></span>
<span id="cb55-3"><a href="power-and-sample-size.html#cb55-3"></a><span class="st">  </span><span class="kw">mutate</span>(<span class="dt">my_sample =</span> <span class="kw">list</span>(<span class="kw">rnorm</span>(<span class="dv">345</span>, <span class="dv">2</span>, <span class="dv">15</span>))) <span class="op">%&gt;%</span><span class="st"> </span></span>
<span id="cb55-4"><a href="power-and-sample-size.html#cb55-4"></a><span class="st">  </span><span class="kw">mutate</span>(<span class="dt">t_test =</span> <span class="kw">list</span>(<span class="kw">t.test</span>(my_sample, <span class="dt">mu =</span> <span class="dv">0</span>, <span class="dt">alternative =</span> <span class="st">&quot;greater&quot;</span>))) <span class="op">%&gt;%</span><span class="st"> </span></span>
<span id="cb55-5"><a href="power-and-sample-size.html#cb55-5"></a><span class="st">  </span><span class="kw">mutate</span>(<span class="dt">p_value =</span> t_test<span class="op">$</span>p.value) <span class="op">%&gt;%</span><span class="st"> </span></span>
<span id="cb55-6"><a href="power-and-sample-size.html#cb55-6"></a><span class="st">  </span><span class="kw">count</span>(p_value <span class="op">&lt;=</span><span class="st"> </span><span class="fl">0.05</span>)</span></code></pre></div>
<p>340 is definitely too small:</p>
<div class="sourceCode" id="cb56"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb56-1"><a href="power-and-sample-size.html#cb56-1"></a><span class="kw">tibble</span>(<span class="dt">sim =</span> <span class="dv">1</span><span class="op">:</span><span class="dv">10000</span>) <span class="op">%&gt;%</span><span class="st"> </span></span>
<span id="cb56-2"><a href="power-and-sample-size.html#cb56-2"></a><span class="st">  </span><span class="kw">rowwise</span>() <span class="op">%&gt;%</span><span class="st"> </span></span>
<span id="cb56-3"><a href="power-and-sample-size.html#cb56-3"></a><span class="st">  </span><span class="kw">mutate</span>(<span class="dt">my_sample =</span> <span class="kw">list</span>(<span class="kw">rnorm</span>(<span class="dv">340</span>, <span class="dv">2</span>, <span class="dv">15</span>))) <span class="op">%&gt;%</span><span class="st"> </span></span>
<span id="cb56-4"><a href="power-and-sample-size.html#cb56-4"></a><span class="st">  </span><span class="kw">mutate</span>(<span class="dt">t_test =</span> <span class="kw">list</span>(<span class="kw">t.test</span>(my_sample, <span class="dt">mu =</span> <span class="dv">0</span>, <span class="dt">alternative =</span> <span class="st">&quot;greater&quot;</span>))) <span class="op">%&gt;%</span><span class="st"> </span></span>
<span id="cb56-5"><a href="power-and-sample-size.html#cb56-5"></a><span class="st">  </span><span class="kw">mutate</span>(<span class="dt">p_value =</span> t_test<span class="op">$</span>p.value) <span class="op">%&gt;%</span><span class="st"> </span></span>
<span id="cb56-6"><a href="power-and-sample-size.html#cb56-6"></a><span class="st">  </span><span class="kw">count</span>(p_value <span class="op">&lt;=</span><span class="st"> </span><span class="fl">0.05</span>)</span></code></pre></div>
<p>This is actually not as close as I was expecting. I think we are getting close to simulation accuracy for this number of simulations. If we do 10,000 simulations of an event with probability 0.8 (correctly rejecting this null), below are the kind of results we might get.<a href="#fn4" class="footnote-ref" id="fnref4"><sup>4</sup></a> This is the middle 95% of that distribution.</p>
<div class="sourceCode" id="cb57"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb57-1"><a href="power-and-sample-size.html#cb57-1"></a><span class="kw">qbinom</span>(<span class="kw">c</span>(<span class="fl">0.025</span>,<span class="fl">0.975</span>), <span class="dv">10000</span>, <span class="fl">0.8</span>)</span></code></pre></div>
<pre><code>## [1] 7921 8078</code></pre>
<p>Anything between those limits is the kind of thing we might get by chance, so simulation doesn’t let us distinguish between 347 and 350 as the correct sample size. Unless we do more than 10,000 simulations, of course!</p>
<p>If you stuck with 1000 simulations each time, these are the corresponding limits:</p>
<div class="sourceCode" id="cb59"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb59-1"><a href="power-and-sample-size.html#cb59-1"></a><span class="kw">qbinom</span>(<span class="kw">c</span>(<span class="fl">0.025</span>,<span class="fl">0.975</span>), <span class="dv">1000</span>, <span class="fl">0.8</span>)</span></code></pre></div>
<pre><code>## [1] 775 824</code></pre>
<p>and any sample sizes that produce an estimated power between these are as accurate as you’ll get. (Here you see the advantage of doing more simulations.)</p>
<p>If you’ve been using 10,000 simulations each time like me, you’ll have noticed that these actually take a noticeable time to run. This is why coders always have a coffee or something else to sip on while their code runs; coders, like us, need to see the output to decide what to do next. Or you could install the <a href="https://www.r-project.org/nosvn/pandoc/beepr.html">beepr package</a>, and get some kind of sound when your simulation finishes, so that you’ll know to get off Twitter<a href="#fn5" class="footnote-ref" id="fnref5"><sup>5</sup></a> and see what happened. There are also packages that will send you a text message or will send a notification to all your devices.</p>
<p>What I want to see from you here is some kind of trial and error that proceeds logically, sensibly increasing or decreasing the sample size at each trial, until you have gotten reasonably close to power 0.8.</p>
<p>Extra: once again we can figure out the correct answer:</p>
<div class="sourceCode" id="cb61"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb61-1"><a href="power-and-sample-size.html#cb61-1"></a><span class="kw">power.t.test</span>(<span class="dt">power =</span> <span class="fl">0.80</span>, <span class="dt">delta=</span><span class="dv">2-0</span>, <span class="dt">sd=</span><span class="dv">15</span>, <span class="dt">type=</span><span class="st">&quot;one.sample&quot;</span>, </span>
<span id="cb61-2"><a href="power-and-sample-size.html#cb61-2"></a><span class="dt">alternative =</span> <span class="st">&quot;one.sided&quot;</span>)</span></code></pre></div>
<pre><code>## 
##      One-sample t test power calculation 
## 
##               n = 349.1256
##           delta = 2
##              sd = 15
##       sig.level = 0.05
##           power = 0.8
##     alternative = one.sided</code></pre>
<p>This does not answer the question, though, since you need to do it by simulation with trial and error. If you want to do it this way, do it at the <em>end</em> as a check on your work; if the answer you get this way is very different from the simulation results, that’s an invitation to check what you did.</p>
<p>350 actually <em>is</em> the correct answer. But you will need to try different sample sizes until you get close enough to a power of 0.8; simply doing it for <span class="math inline">\(n=350\)</span> is not enough, because how did you know to try 350 and not some other sample size?</p>
<p><span class="math inline">\(\blacksquare\)</span></p>
</div>
<div id="power-and-alpha-in-a-skewed-population-1" class="section level2" number="8.10">
<h2><span class="header-section-number">8.10</span> Power and <span class="math inline">\(\alpha\)</span> in a skewed population</h2>
<p>A population of a large number of values <code>v</code> is at , in a CSV file.</p>
<ol style="list-style-type: lower-alpha">
<li>Read in the population and display some of the values.</li>
</ol>
<p>Solution</p>
<div class="sourceCode" id="cb63"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb63-1"><a href="power-and-sample-size.html#cb63-1"></a>my_url &lt;-<span class="st"> &quot;http://ritsokiguess.site/datafiles/pop.csv&quot;</span></span>
<span id="cb63-2"><a href="power-and-sample-size.html#cb63-2"></a>pop &lt;-<span class="st"> </span><span class="kw">read_csv</span>(my_url)</span></code></pre></div>
<pre><code>## 
## ── Column specification ────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
## cols(
##   v = col_double()
## )</code></pre>
<div class="sourceCode" id="cb65"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb65-1"><a href="power-and-sample-size.html#cb65-1"></a>pop</span></code></pre></div>
<p>10,000 values. A large population. (From these few values, <code>v</code> seems to be positive but rather variable.)</p>
<p><span class="math inline">\(\blacksquare\)</span></p>
<ol start="2" style="list-style-type: lower-alpha">
<li>Obtain a suitable plot of your population. What do you notice?</li>
</ol>
<p>Solution</p>
<p>One quantitative variable, so a histogram. The population is large, so you can use more bins than usual. Sturges’ rule says 14 bins (the logarithm below is base 2, or, the next power of 2 above 10,000 is 16,384 which is <span class="math inline">\(2^{14}\)</span>):</p>
<div class="sourceCode" id="cb66"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb66-1"><a href="power-and-sample-size.html#cb66-1"></a><span class="kw">log</span>(<span class="dv">10000</span>, <span class="dv">2</span>)</span></code></pre></div>
<pre><code>## [1] 13.28771</code></pre>
<div class="sourceCode" id="cb68"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb68-1"><a href="power-and-sample-size.html#cb68-1"></a><span class="dv">2</span><span class="op">^</span><span class="dv">14</span></span></code></pre></div>
<pre><code>## [1] 16384</code></pre>
<div class="sourceCode" id="cb70"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb70-1"><a href="power-and-sample-size.html#cb70-1"></a><span class="kw">ggplot</span>(pop, <span class="kw">aes</span>(<span class="dt">x=</span>v)) <span class="op">+</span><span class="st"> </span><span class="kw">geom_histogram</span>(<span class="dt">bins=</span><span class="dv">14</span>)</span></code></pre></div>
<p><img src="pasias_files/figure-html/unnamed-chunk-70-1.png" width="672" /></p>
<p>Pick a number of bins: the default 30 bins is pretty much always too many. Any number of bins that shows this shape is good as an answer, but you also need to display some thinking about how many bins to use, either starting with a rule as I did, or experimenting with different numbers of bins. Rules are not hard and fast; it so happened that I liked the picture that 14 bins gave, so I stopped there. Thirty bins, the default, is actually not bad here:</p>
<div class="sourceCode" id="cb71"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb71-1"><a href="power-and-sample-size.html#cb71-1"></a><span class="kw">ggplot</span>(pop, <span class="kw">aes</span>(<span class="dt">x=</span>v)) <span class="op">+</span><span class="st"> </span><span class="kw">geom_histogram</span>()</span></code></pre></div>
<pre><code>## `stat_bin()` using `bins = 30`. Pick better value with `binwidth`.</code></pre>
<p><img src="pasias_files/figure-html/unnamed-chunk-71-1.png" width="672" /></p>
<p>but if you do this, you need to say something that indicates some conscious thought, such as saying “this number of bins gives a good picture of the shape of the distribution”, which I am OK with. <em>Have a reason for doing what you do</em>.</p>
<p>This is skewed to the right, or has a long right tail. This is a better description than “outliers”: there are indeed some very large values (almost invisible on the histogram), but to say that is to imply that the rest of the distribution apart from the outliers has a regular shape, not something you can say here.<a href="#fn6" class="footnote-ref" id="fnref6"><sup>6</sup></a></p>
<p>Extra: The issue that’s coming up is whether this is normally-distributed, which of course it is not. This is a normal quantile plot. (Idea: if the points follow the line, at least approximately, the variable is normally distributed; if not, not.):</p>
<div class="sourceCode" id="cb73"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb73-1"><a href="power-and-sample-size.html#cb73-1"></a><span class="kw">ggplot</span>(pop, <span class="kw">aes</span>(<span class="dt">sample=</span>v)) <span class="op">+</span><span class="st"> </span><span class="kw">stat_qq</span>() <span class="op">+</span><span class="st"> </span><span class="kw">stat_qq_line</span>()</span></code></pre></div>
<p><img src="pasias_files/figure-html/unnamed-chunk-72-1.png" width="672" /></p>
<p>That is your archetypal skewed-to-right. The two highest values are not a lot higher than the rest, again supporting a curved shape overall (skewness) on this plot, rather than the problem being outliers. (The highest values are consistent with the shape of the curve, rather than being unusually high compared to the curve.)</p>
<p><span class="math inline">\(\blacksquare\)</span></p>
<ol start="3" style="list-style-type: lower-alpha">
<li>If you take a sample of 10 observations from this population and run a <span class="math inline">\(t\)</span>-test, how likely are you to (correctly) reject the null hypothesis <span class="math inline">\(H_0: \mu = 4\)</span>, against the alternative <span class="math inline">\(H_a: \mu &gt; 4\)</span>? Investigate by simulation.</li>
</ol>
<p>Solution</p>
<p>As you noted, this is a one-sided alternative, so make sure your code does the right thing. Take a lot of random samples, run the <span class="math inline">\(t\)</span>-test on each one, grab the P-value each time, count the number of P-values less or equal to your <span class="math inline">\(\alpha\)</span>. This is <em>not</em> a bootstrap, so the sampling needs to be <em>without</em> replacement, and you need to say how big the sample is:</p>
<div class="sourceCode" id="cb74"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb74-1"><a href="power-and-sample-size.html#cb74-1"></a><span class="kw">tibble</span>(<span class="dt">sim =</span> <span class="dv">1</span><span class="op">:</span><span class="dv">1000</span>) <span class="op">%&gt;%</span><span class="st"> </span></span>
<span id="cb74-2"><a href="power-and-sample-size.html#cb74-2"></a><span class="st">  </span><span class="kw">rowwise</span>() <span class="op">%&gt;%</span><span class="st"> </span></span>
<span id="cb74-3"><a href="power-and-sample-size.html#cb74-3"></a><span class="st">  </span><span class="kw">mutate</span>(<span class="dt">my_sample =</span> <span class="kw">list</span>(<span class="kw">sample</span>(pop<span class="op">$</span>v, <span class="dv">10</span>))) <span class="op">%&gt;%</span><span class="st"> </span></span>
<span id="cb74-4"><a href="power-and-sample-size.html#cb74-4"></a><span class="st">  </span><span class="kw">mutate</span>(<span class="dt">t_test =</span> <span class="kw">list</span>(<span class="kw">t.test</span>(my_sample, <span class="dt">mu =</span> <span class="dv">4</span>, <span class="dt">alternative =</span> <span class="st">&quot;greater&quot;</span>))) <span class="op">%&gt;%</span><span class="st"> </span></span>
<span id="cb74-5"><a href="power-and-sample-size.html#cb74-5"></a><span class="st">  </span><span class="kw">mutate</span>(<span class="dt">p_value =</span> t_test<span class="op">$</span>p.value) <span class="op">%&gt;%</span><span class="st"> </span></span>
<span id="cb74-6"><a href="power-and-sample-size.html#cb74-6"></a><span class="st">  </span><span class="kw">count</span>(p_value <span class="op">&lt;=</span><span class="st"> </span><span class="fl">0.05</span>)</span></code></pre></div>
<p>The estimated power is only about 0.19.</p>
<p>As to the code, well, the samples and the <span class="math inline">\(t\)</span>-test both consist of more than one thing, so in the <code>mutate</code>s that create them, don’t forget the <code>list</code> around the outside, which will create a list-column.</p>
<p>Here, and elsewhere in this question, use at least 1000 simulations. More will give you more accurate results, but you’ll have to wait longer for it to run. Your choice.</p>
<p>As a final remark, you <em>can not</em> do this one by algebra, as you might have done in other courses, because you do not know the functional form of the population distribution. The power calculations you may have done before as calculations typically assume a normal population, because if you don’t, the algebra gets too messy too fast. (You’d need to know the distribution of the test statistic under the <em>alternative</em> hypothesis, which in cases beyond the normal is not usually known.)</p>
<p><span class="math inline">\(\blacksquare\)</span></p>
<ol start="4" style="list-style-type: lower-alpha">
<li>Try again with a sample size of 50 (leaving everything else the same). Explain briefly why the results so far are as you’d expect.</li>
</ol>
<p>Solution</p>
<p>For the code, this is copy-paste-edit. Just change the sample size:</p>
<div class="sourceCode" id="cb75"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb75-1"><a href="power-and-sample-size.html#cb75-1"></a><span class="kw">tibble</span>(<span class="dt">sim =</span> <span class="dv">1</span><span class="op">:</span><span class="dv">1000</span>) <span class="op">%&gt;%</span><span class="st"> </span></span>
<span id="cb75-2"><a href="power-and-sample-size.html#cb75-2"></a><span class="st">  </span><span class="kw">rowwise</span>() <span class="op">%&gt;%</span><span class="st"> </span></span>
<span id="cb75-3"><a href="power-and-sample-size.html#cb75-3"></a><span class="st">  </span><span class="kw">mutate</span>(<span class="dt">my_sample =</span> <span class="kw">list</span>(<span class="kw">sample</span>(pop<span class="op">$</span>v, <span class="dv">50</span>))) <span class="op">%&gt;%</span><span class="st"> </span></span>
<span id="cb75-4"><a href="power-and-sample-size.html#cb75-4"></a><span class="st">  </span><span class="kw">mutate</span>(<span class="dt">t_test =</span> <span class="kw">list</span>(<span class="kw">t.test</span>(my_sample, <span class="dt">mu =</span> <span class="dv">4</span>, <span class="dt">alternative =</span> <span class="st">&quot;greater&quot;</span>))) <span class="op">%&gt;%</span><span class="st"> </span></span>
<span id="cb75-5"><a href="power-and-sample-size.html#cb75-5"></a><span class="st">  </span><span class="kw">mutate</span>(<span class="dt">p_value =</span> t_test<span class="op">$</span>p.value) <span class="op">%&gt;%</span><span class="st"> </span></span>
<span id="cb75-6"><a href="power-and-sample-size.html#cb75-6"></a><span class="st">  </span><span class="kw">count</span>(p_value <span class="op">&lt;=</span><span class="st"> </span><span class="fl">0.05</span>)</span></code></pre></div>
<p>The power is now much bigger, around 73%. This is as expected because with a larger sample size we should be more likely to reject a false null hypothesis.</p>
<p>The reason for this is that the mean of a bigger sample should be closer to the population mean, because of the Law of Large Numbers, and thus further away from the incorrect null hypothesis and more likely far enough away to reject it. In this case, as you will see shortly, the population mean is 5, and so, with a bigger sample, the sample mean will almost certainly be closer to 5 and further away from 4.</p>
<p>I have a feeling you could formalize this kind of argument with Chebyshev’s inequality, which would apply to any kind of population.<a href="#fn7" class="footnote-ref" id="fnref7"><sup>7</sup></a> I think I’d have to write it down to get it right, though.</p>
<p><span class="math inline">\(\blacksquare\)</span></p>
<ol start="5" style="list-style-type: lower-alpha">
<li>Again by simulation, estimate the probability that the null hypothesis <span class="math inline">\(H_0: \mu=5\)</span> will be rejected when a sample of size 10 is taken from this population, in favour of the alternative <span class="math inline">\(H_a: \mu &gt; 5\)</span>. Explain briefly why the answer is not what you would have expected, and why that happened here. (Hint: what is the population mean?)</li>
</ol>
<p>Solution</p>
<p>Taking the hint first:</p>
<div class="sourceCode" id="cb76"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb76-1"><a href="power-and-sample-size.html#cb76-1"></a>pop <span class="op">%&gt;%</span><span class="st"> </span></span>
<span id="cb76-2"><a href="power-and-sample-size.html#cb76-2"></a><span class="kw">summarize</span>(<span class="dt">m =</span> <span class="kw">mean</span>(v))</span></code></pre></div>
<p>(I’m hoping that some light dawns at this point), and copy-paste-edit your simulation code again, this time changing the null mean to 5:</p>
<div class="sourceCode" id="cb77"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb77-1"><a href="power-and-sample-size.html#cb77-1"></a><span class="kw">tibble</span>(<span class="dt">sim =</span> <span class="dv">1</span><span class="op">:</span><span class="dv">1000</span>) <span class="op">%&gt;%</span><span class="st"> </span></span>
<span id="cb77-2"><a href="power-and-sample-size.html#cb77-2"></a><span class="st">  </span><span class="kw">rowwise</span>() <span class="op">%&gt;%</span><span class="st"> </span></span>
<span id="cb77-3"><a href="power-and-sample-size.html#cb77-3"></a><span class="st">  </span><span class="kw">mutate</span>(<span class="dt">my_sample =</span> <span class="kw">list</span>(<span class="kw">sample</span>(pop<span class="op">$</span>v, <span class="dv">10</span>))) <span class="op">%&gt;%</span><span class="st"> </span></span>
<span id="cb77-4"><a href="power-and-sample-size.html#cb77-4"></a><span class="st">  </span><span class="kw">mutate</span>(<span class="dt">t_test =</span> <span class="kw">list</span>(<span class="kw">t.test</span>(my_sample, <span class="dt">mu =</span> <span class="dv">5</span>, <span class="dt">alternative =</span> <span class="st">&quot;greater&quot;</span>))) <span class="op">%&gt;%</span><span class="st"> </span></span>
<span id="cb77-5"><a href="power-and-sample-size.html#cb77-5"></a><span class="st">  </span><span class="kw">mutate</span>(<span class="dt">p_value =</span> t_test<span class="op">$</span>p.value) <span class="op">%&gt;%</span><span class="st"> </span></span>
<span id="cb77-6"><a href="power-and-sample-size.html#cb77-6"></a><span class="st">  </span><span class="kw">count</span>(p_value <span class="op">&lt;=</span><span class="st"> </span><span class="fl">0.05</span>)</span></code></pre></div>
<p>The “power” is estimated to be 0.020. (Again, your value won’t be exactly this, most likely, but it should be somewhere close.)</p>
<p>So what were we expecting? This time, the null hypothesis, that the population mean is 5, is actually <em>true</em>. So rejecting it is now a <em>type I error</em>, and the probability of that should be <span class="math inline">\(\alpha\)</span>, which was 0.05 here. In our simulation, though, the estimated probability is quite a bit <em>less</em> than 0.05. (Your result will probably differ from mine, but it is not likely to be bigger than 0.05).</p>
<p>To think about why that happened, remember that this is a very skewed population, and the sample size of 10 is not big, so this is not really the situation in which we should be using a <span class="math inline">\(t\)</span>-test. The consequence of doing so anyway, which is what we investigated, is that the actual <span class="math inline">\(\alpha\)</span> of our test is not 0.05, but something smaller: the test is not properly calibrated.</p>
<p>If you do this again for a sample of size 50, you’ll find that the simulation tells you that <span class="math inline">\(\alpha\)</span> is closer to 0.05, but still less. The population is skewed enough that the Central Limit Theorem still hasn’t kicked in yet, and so we still cannot trust the <span class="math inline">\(t\)</span>-test to give us a sensible P-value.</p>
<p>Extra: a lot more discussion on what is happening here:</p>
<p>This test is what is known in the jargon as “conservative”. To a statistician, this means that the probability of making a type I error is smaller than it should be. That is in some sense safe, in that if you reject, you can be pretty sure that this rejection is correct, but it makes it a lot harder than it should to reject in the first place, and thus you can fail to declare a discovery when you have really made one (but the test didn’t say so).</p>
<p>I did some investigation to see what was going on. First, I ran the simulation again, but this time keeping the mean and SD of each sample, as well as the <span class="math inline">\(t\)</span>-statistic, but not actually doing the <span class="math inline">\(t\)</span>-test:</p>
<div class="sourceCode" id="cb78"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb78-1"><a href="power-and-sample-size.html#cb78-1"></a><span class="kw">tibble</span>(<span class="dt">sim =</span> <span class="dv">1</span><span class="op">:</span><span class="dv">1000</span>) <span class="op">%&gt;%</span><span class="st"> </span></span>
<span id="cb78-2"><a href="power-and-sample-size.html#cb78-2"></a><span class="st">  </span><span class="kw">rowwise</span>() <span class="op">%&gt;%</span><span class="st"> </span></span>
<span id="cb78-3"><a href="power-and-sample-size.html#cb78-3"></a><span class="st">  </span><span class="kw">mutate</span>(<span class="dt">my_sample =</span> <span class="kw">list</span>(<span class="kw">sample</span>(pop<span class="op">$</span>v, <span class="dv">10</span>))) <span class="op">%&gt;%</span><span class="st"> </span></span>
<span id="cb78-4"><a href="power-and-sample-size.html#cb78-4"></a><span class="st">  </span><span class="kw">mutate</span>(<span class="dt">xbar =</span> <span class="kw">mean</span>(my_sample),</span>
<span id="cb78-5"><a href="power-and-sample-size.html#cb78-5"></a>         <span class="dt">s =</span> <span class="kw">sd</span>(my_sample),</span>
<span id="cb78-6"><a href="power-and-sample-size.html#cb78-6"></a>         <span class="dt">t_stat =</span> (xbar <span class="op">-</span><span class="st"> </span><span class="dv">5</span>) <span class="op">/</span><span class="st"> </span>(s <span class="op">/</span><span class="st"> </span><span class="kw">sqrt</span>(<span class="dv">10</span>))) -&gt;<span class="st"> </span>mean_sd</span>
<span id="cb78-7"><a href="power-and-sample-size.html#cb78-7"></a>mean_sd</span></code></pre></div>
<p>As for coding, I made a dataframe with a column <code>sim</code> that numbers the individual samples, made sure I said that I wanted to work rowwise, generated a random sample from the population in each row of size 10, and found its mean, SD and the calculated-by-me <span class="math inline">\(t\)</span>-statistic.<a href="#fn8" class="footnote-ref" id="fnref8"><sup>8</sup></a></p>
<p>After that, I played around with several things, but I found something interesting when I plotted the sample mean and SD <em>against each other</em>:</p>
<div class="sourceCode" id="cb79"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb79-1"><a href="power-and-sample-size.html#cb79-1"></a><span class="kw">ggplot</span>(mean_sd, <span class="kw">aes</span>(<span class="dt">x=</span>xbar, <span class="dt">y=</span>s)) <span class="op">+</span><span class="st"> </span><span class="kw">geom_point</span>() <span class="op">+</span><span class="st"> </span><span class="kw">geom_smooth</span>(<span class="dt">se=</span>F)</span></code></pre></div>
<pre><code>## `geom_smooth()` using method = &#39;gam&#39; and formula &#39;y ~ s(x, bs = &quot;cs&quot;)&#39;</code></pre>
<p><img src="pasias_files/figure-html/unnamed-chunk-78-1.png" width="672" /></p>
<p><em>When the sample mean is bigger, so is the sample standard deviation!</em></p>
<p>This actually does make sense, if you stop to think about it. A sample with a large mean will have some of those values from the long right tail in it, and having those values will also make the sample more spread out. The same does not happen at the low end: if the mean is small, all the sample values must be close together and the SD will be small also.<a href="#fn9" class="footnote-ref" id="fnref9"><sup>9</sup></a></p>
<p>It wasn’t clear to me what that would do to the <span class="math inline">\(t\)</span>-statistic. A larger sample mean would make the top of the test statistic bigger, but a larger sample mean would also go with a larger sample SD, and so the bottom of the test statistic would be bigger as well. That’s why I included this in the simulation too:</p>
<div class="sourceCode" id="cb81"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb81-1"><a href="power-and-sample-size.html#cb81-1"></a><span class="kw">ggplot</span>(mean_sd, <span class="kw">aes</span>(<span class="dt">x=</span>t_stat)) <span class="op">+</span><span class="st"> </span><span class="kw">geom_histogram</span>(<span class="dt">bins=</span><span class="dv">12</span>)</span></code></pre></div>
<p><img src="pasias_files/figure-html/unnamed-chunk-79-1.png" width="672" /></p>
<p>Well, well. Skewed to the <em>left</em>.</p>
<p>This too makes sense with a bit of thought. A small sample mean will also have a small sample SD, so the test statistic could be more negative. But a large sample mean will have a <em>large</em> sample SD, so the test statistic won’t get so positive. Hence, in our simulation, the test statistic won’t get large enough to reject with as often as it should. Thus, the type I error probability that is too small.</p>
<p><span class="math inline">\(\blacksquare\)</span></p>

</div>
</div>
<div class="footnotes">
<hr />
<ol start="1">
<li id="fn1"><p>That would mean assessing whether an observed proportion could be greater than 0.5 just by chance, or whether it is bigger enough than 0.5 to reject chance as a plausible explanation.<a href="power-and-sample-size.html#fnref1" class="footnote-back">↩︎</a></p></li>
<li id="fn2"><p>That would mean assessing whether an observed proportion could be greater than 0.5 just by chance, or whether it is bigger enough than 0.5 to reject chance as a plausible explanation.<a href="power-and-sample-size.html#fnref2" class="footnote-back">↩︎</a></p></li>
<li id="fn3"><p>This is why I called my result disappointing. I would like to reject a lot more of the time than this, but, given that the truth was not very far away from the null given the (large) population SD, I can’t. See Extra 1.<a href="power-and-sample-size.html#fnref3" class="footnote-back">↩︎</a></p></li>
<li id="fn4"><p>If the power is really 0.8, the number of simulated tests that end up rejecting has a binomial distribution with n of 10000 and p of 0.80.<a href="power-and-sample-size.html#fnref4" class="footnote-back">↩︎</a></p></li>
<li id="fn5"><p>Or Reddit or Quora or whatever your favourite time-killer is.<a href="power-and-sample-size.html#fnref5" class="footnote-back">↩︎</a></p></li>
<li id="fn6"><p>The question to ask yourself is whether the shape comes from the entire distribution, as it does here (skewness), or whether it comes from a few unusual observations (outliers).<a href="power-and-sample-size.html#fnref6" class="footnote-back">↩︎</a></p></li>
<li id="fn7"><p>It has to have a standard deviation, though, but our population seems well-enough behaved to have a standard deviation.<a href="power-and-sample-size.html#fnref7" class="footnote-back">↩︎</a></p></li>
<li id="fn8"><p>This is not bootstrapping, but generating ordinary random samples from a presumed-known population, so there is no <code>replace = TRUE</code> here.<a href="power-and-sample-size.html#fnref8" class="footnote-back">↩︎</a></p></li>
<li id="fn9"><p>You might have something lurking in your mind about the sample mean and sample SD/variance being <em>independent</em>, which they clearly are not here. That is true if the samples come from a normal distribution, and from that comes independence of the top and bottom of the <span class="math inline">\(t\)</span>-statistic. But here is an example of how everything fails once you go away from normality, and how you have to rely on the central limit theorem, or large sample sizes more generally, for most of your theory to be any good.<a href="power-and-sample-size.html#fnref9" class="footnote-back">↩︎</a></p></li>
</ol>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="two-sample-inference.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="the-sign-test.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/lunr.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": null,
"text": null
},
"history": {
"link": null,
"text": null
},
"view": {
"link": null,
"text": null
},
"download": ["pasias.pdf"],
"toc": {
"collapse": "subsection"
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
