<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

<meta charset="utf-8" />
<meta name="generator" content="pandoc" />
<meta name="viewport" content="width=device-width, initial-scale=1" />
<meta property="og:title" content="Chapter 29 Principal Components and Factor Analysis | Problems and Solutions in Applied Statistics" />
<meta property="og:type" content="book" />
<meta property="og:url" content="http://ritsokiguess.site/pasias" />

<meta property="og:description" content="A set of problems and solutions, in R, on various parts of applied statistics" />
<meta name="github-repo" content="nxskok/pasias" />

<meta name="author" content="Ken Butler" />

<meta name="date" content="2019-01-07" />

<script type="text/x-mathjax-config">
MathJax.Hub.Config({
  TeX: { equationNumbers: { autoNumber: "AMS" } }
});
</script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js" type="text/javascript"></script>

<meta name="description" content="A set of problems and solutions, in R, on various parts of applied statistics">

<title>Chapter 29 Principal Components and Factor Analysis | Problems and Solutions in Applied Statistics</title>

<script src="libs/header-attrs-2.7/header-attrs.js"></script>
<link href="libs/tufte-css-2015.12.29/tufte-fonts.css" rel="stylesheet" />
<link href="libs/tufte-css-2015.12.29/tufte-background.css" rel="stylesheet" />
<link href="libs/tufte-css-2015.12.29/tufte-italics.css" rel="stylesheet" />
<link href="libs/tufte-css-2015.12.29/tufte.css" rel="stylesheet" />
<script src="libs/accessible-code-block-0.0.1/empty-anchor.js"></script>
<script src="libs/htmlwidgets-1.5.3/htmlwidgets.js"></script>
<script src="libs/jquery-1.12.4/jquery.min.js"></script>
<link href="libs/leaflet-1.3.1/leaflet.css" rel="stylesheet" />
<script src="libs/leaflet-1.3.1/leaflet.js"></script>
<link href="libs/leafletfix-1.0.0/leafletfix.css" rel="stylesheet" />
<script src="libs/proj4-2.6.2/proj4.min.js"></script>
<script src="libs/Proj4Leaflet-1.0.1/proj4leaflet.js"></script>
<link href="libs/rstudio_leaflet-1.3.1/rstudio_leaflet.css" rel="stylesheet" />
<script src="libs/leaflet-binding-2.0.4.1/leaflet.js"></script>


<style type="text/css">code{white-space: pre;}</style>
<style type="text/css">
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>


<link rel="stylesheet" href="toc.css" type="text/css" />

</head>

<body>



<div class="row">
<div class="col-sm-12">
<div id="TOC">
<ul>
<li><a href="index.html#introduction"><span class="toc-section-number">1</span> Introduction</a>
<ul>
<li><a href="index.html#packages-used-somewhere-in-this-book"><span class="toc-section-number">1.1</span> Packages used somewhere in this book</a></li>
</ul></li>
<li><a href="getting-used-to-r-and-r-studio.html#getting-used-to-r-and-r-studio"><span class="toc-section-number">2</span> Getting used to R and R Studio</a>
<ul>
<li><a href="getting-used-to-r-and-r-studio.html#getting-an-r-studio-cloud-account"><span class="toc-section-number">2.1</span> Getting an R Studio Cloud account</a></li>
<li><a href="getting-used-to-r-and-r-studio.html#getting-started"><span class="toc-section-number">2.2</span> Getting started</a></li>
<li><a href="getting-used-to-r-and-r-studio.html#reading-data-from-a-file"><span class="toc-section-number">2.3</span> Reading data from a file</a></li>
<li><a href="getting-used-to-r-and-r-studio.html#reading-files-different-ways"><span class="toc-section-number">2.4</span> Reading files different ways</a></li>
</ul></li>
<li><a href="reading-in-data.html#reading-in-data"><span class="toc-section-number">3</span> Reading in data</a>
<ul>
<li><a href="reading-in-data.html#orange-juice"><span class="toc-section-number">3.1</span> Orange juice</a></li>
<li><a href="reading-in-data.html#making-soap"><span class="toc-section-number">3.2</span> Making soap</a></li>
<li><a href="reading-in-data.html#handling-shipments"><span class="toc-section-number">3.3</span> Handling shipments</a></li>
</ul></li>
<li><a href="drawing-graphs.html#drawing-graphs"><span class="toc-section-number">4</span> Drawing graphs</a>
<ul>
<li><a href="drawing-graphs.html#orange-juice-1"><span class="toc-section-number">4.1</span> Orange juice</a></li>
<li><a href="drawing-graphs.html#making-soap-1"><span class="toc-section-number">4.2</span> Making soap</a></li>
<li><a href="drawing-graphs.html#handling-shipments-1"><span class="toc-section-number">4.3</span> Handling shipments</a></li>
</ul></li>
<li><a href="data-exploration.html#data-exploration"><span class="toc-section-number">5</span> Data exploration</a>
<ul>
<li><a href="data-exploration.html#north-carolina-births"><span class="toc-section-number">5.1</span> North Carolina births</a></li>
<li><a href="data-exploration.html#more-about-the-nc-births"><span class="toc-section-number">5.2</span> More about the NC births</a></li>
<li><a href="data-exploration.html#nenana-alaska"><span class="toc-section-number">5.3</span> Nenana, Alaska</a></li>
<li><a href="data-exploration.html#computerized-accounting"><span class="toc-section-number">5.4</span> Computerized accounting</a></li>
<li><a href="data-exploration.html#test-scores-in-two-classes"><span class="toc-section-number">5.5</span> Test scores in two classes</a></li>
<li><a href="data-exploration.html#working-with-dataframes"><span class="toc-section-number">5.6</span> Working with dataframes</a></li>
<li><a href="data-exploration.html#tidying-the-jays-data"><span class="toc-section-number">5.7</span> Tidying the Jays data</a></li>
<li><a href="data-exploration.html#cars"><span class="toc-section-number">5.8</span> Cars</a></li>
</ul></li>
<li><a href="one-sample-inference.html#one-sample-inference"><span class="toc-section-number">6</span> One-sample inference</a>
<ul>
<li><a href="one-sample-inference.html#hunter-gatherers-in-australia"><span class="toc-section-number">6.1</span> Hunter-gatherers in Australia</a></li>
<li><a href="one-sample-inference.html#buses-to-boulder"><span class="toc-section-number">6.2</span> Buses to Boulder</a></li>
<li><a href="one-sample-inference.html#length-of-gestation-in-north-carolina"><span class="toc-section-number">6.3</span> Length of gestation in North Carolina</a></li>
<li><a href="one-sample-inference.html#inferring-ice-break-up-in-nenana"><span class="toc-section-number">6.4</span> Inferring ice break-up in Nenana</a></li>
</ul></li>
<li><a href="two-sample-inference.html#two-sample-inference"><span class="toc-section-number">7</span> Two-sample inference</a>
<ul>
<li><a href="two-sample-inference.html#children-and-electronic-devices"><span class="toc-section-number">7.1</span> Children and electronic devices</a></li>
<li><a href="two-sample-inference.html#parking-close-to-the-curb"><span class="toc-section-number">7.2</span> Parking close to the curb</a></li>
<li><a href="two-sample-inference.html#bell-peppers-and-too-much-water"><span class="toc-section-number">7.3</span> Bell peppers and too much water</a></li>
<li><a href="two-sample-inference.html#exercise-and-anxiety-and-bullying-mice"><span class="toc-section-number">7.4</span> Exercise and anxiety and bullying mice</a></li>
<li><a href="two-sample-inference.html#diet-and-growth-in-boys"><span class="toc-section-number">7.5</span> Diet and growth in boys</a></li>
</ul></li>
<li><a href="power-and-sample-size.html#power-and-sample-size"><span class="toc-section-number">8</span> Power and sample size</a>
<ul>
<li><a href="power-and-sample-size.html#simulating-power"><span class="toc-section-number">8.1</span> Simulating power</a></li>
<li><a href="power-and-sample-size.html#calculating-power-and-sample-size-for-estimating-mean"><span class="toc-section-number">8.2</span> Calculating power and sample size for estimating mean</a></li>
<li><a href="power-and-sample-size.html#simulating-power-for-proportions"><span class="toc-section-number">8.3</span> Simulating power for proportions</a></li>
</ul></li>
<li><a href="the-sign-test-and-moods-median-test.html#the-sign-test-and-moods-median-test"><span class="toc-section-number">9</span> The sign test and Mood’s median test</a>
<ul>
<li><a href="the-sign-test-and-moods-median-test.html#running-a-maze"><span class="toc-section-number">9.1</span> Running a maze</a></li>
<li><a href="the-sign-test-and-moods-median-test.html#chocolate-chips"><span class="toc-section-number">9.2</span> Chocolate chips</a></li>
<li><a href="the-sign-test-and-moods-median-test.html#the-power-of-the-sign-test"><span class="toc-section-number">9.3</span> The power of the sign test</a></li>
<li><a href="the-sign-test-and-moods-median-test.html#sugar-in-breakfast-cereals"><span class="toc-section-number">9.4</span> Sugar in breakfast cereals</a></li>
<li><a href="the-sign-test-and-moods-median-test.html#fear-of-math"><span class="toc-section-number">9.5</span> Fear of math</a></li>
<li><a href="the-sign-test-and-moods-median-test.html#medical-instructions"><span class="toc-section-number">9.6</span> Medical instructions</a></li>
</ul></li>
<li><a href="matched-pairs-t-and-sign-test.html#matched-pairs-t-and-sign-test"><span class="toc-section-number">10</span> Matched pairs t and sign test</a>
<ul>
<li><a href="matched-pairs-t-and-sign-test.html#measuring-body-fat"><span class="toc-section-number">10.1</span> Measuring body fat</a></li>
<li><a href="matched-pairs-t-and-sign-test.html#throwing-baseballs-and-softballs"><span class="toc-section-number">10.2</span> Throwing baseballs and softballs</a></li>
<li><a href="matched-pairs-t-and-sign-test.html#throwing-baseballs-and-softballs-again"><span class="toc-section-number">10.3</span> Throwing baseballs and softballs, again</a></li>
<li><a href="matched-pairs-t-and-sign-test.html#changes-in-salary"><span class="toc-section-number">10.4</span> Changes in salary</a></li>
<li><a href="matched-pairs-t-and-sign-test.html#body-fat-revisited"><span class="toc-section-number">10.5</span> Body fat revisited</a></li>
</ul></li>
<li><a href="normal-quantile-plots.html#normal-quantile-plots"><span class="toc-section-number">11</span> Normal quantile plots</a>
<ul>
<li><a href="normal-quantile-plots.html#lengths-of-heliconia-flowers"><span class="toc-section-number">11.1</span> Lengths of heliconia flowers</a></li>
<li><a href="normal-quantile-plots.html#ferritin-and-normality"><span class="toc-section-number">11.2</span> Ferritin and normality</a></li>
</ul></li>
<li><a href="analysis-of-variance.html#analysis-of-variance"><span class="toc-section-number">12</span> Analysis of variance</a>
<ul>
<li><a href="analysis-of-variance.html#movie-ratings-and-lengths"><span class="toc-section-number">12.1</span> Movie ratings and lengths</a></li>
<li><a href="analysis-of-variance.html#deer-and-how-much-they-eat"><span class="toc-section-number">12.2</span> Deer and how much they eat</a></li>
<li><a href="analysis-of-variance.html#movie-ratings-again"><span class="toc-section-number">12.3</span> Movie ratings again</a></li>
<li><a href="analysis-of-variance.html#atomic-weight-of-carbon"><span class="toc-section-number">12.4</span> Atomic weight of carbon</a></li>
<li><a href="analysis-of-variance.html#can-caffeine-improve-your-performance-on-a-test"><span class="toc-section-number">12.5</span> Can caffeine improve your performance on a test?</a></li>
</ul></li>
<li><a href="tidying-data.html#tidying-data"><span class="toc-section-number">13</span> Tidying data</a>
<ul>
<li><a href="tidying-data.html#baseball-and-softball-spaghetti"><span class="toc-section-number">13.1</span> Baseball and softball spaghetti</a></li>
<li><a href="tidying-data.html#ethanol-and-sleep-time-in-rats"><span class="toc-section-number">13.2</span> Ethanol and sleep time in rats</a></li>
<li><a href="tidying-data.html#growth-of-tomatoes"><span class="toc-section-number">13.3</span> Growth of tomatoes</a></li>
<li><a href="tidying-data.html#pain-relief-in-migraine-headaches-again"><span class="toc-section-number">13.4</span> Pain relief in migraine headaches (again)</a></li>
<li><a href="tidying-data.html#location-species-and-disease-in-plants"><span class="toc-section-number">13.5</span> Location, species and disease in plants</a></li>
<li><a href="tidying-data.html#mating-songs-in-crickets"><span class="toc-section-number">13.6</span> Mating songs in crickets</a></li>
<li><a href="tidying-data.html#number-1-songs"><span class="toc-section-number">13.7</span> Number 1 songs</a></li>
<li><a href="tidying-data.html#bikes-on-college"><span class="toc-section-number">13.8</span> Bikes on College</a></li>
<li><a href="tidying-data.html#feeling-the-heat"><span class="toc-section-number">13.9</span> Feeling the heat</a></li>
</ul></li>
<li><a href="regression.html#regression"><span class="toc-section-number">14</span> Regression</a>
<ul>
<li><a href="regression.html#rainfall-in-california"><span class="toc-section-number">14.1</span> Rainfall in California</a></li>
<li><a href="regression.html#carbon-monoxide-in-cigarettes"><span class="toc-section-number">14.2</span> Carbon monoxide in cigarettes</a></li>
<li><a href="regression.html#maximal-oxygen-uptake-in-young-boys"><span class="toc-section-number">14.3</span> Maximal oxygen uptake in young boys</a></li>
<li><a href="regression.html#facebook-friends-and-grey-matter"><span class="toc-section-number">14.4</span> Facebook friends and grey matter</a></li>
<li><a href="regression.html#endogenous-nitrogen-excretion-in-carp"><span class="toc-section-number">14.5</span> Endogenous nitrogen excretion in carp</a></li>
<li><a href="regression.html#sparrowhawks"><span class="toc-section-number">14.6</span> Sparrowhawks</a></li>
<li><a href="regression.html#salaries-of-social-workers"><span class="toc-section-number">14.7</span> Salaries of social workers</a></li>
<li><a href="regression.html#predicting-volume-of-wood-in-pine-trees"><span class="toc-section-number">14.8</span> Predicting volume of wood in pine trees</a></li>
<li><a href="regression.html#tortoise-shells-and-eggs"><span class="toc-section-number">14.9</span> Tortoise shells and eggs</a></li>
<li><a href="regression.html#crickets-revisited"><span class="toc-section-number">14.10</span> Crickets revisited</a></li>
<li><a href="regression.html#roller-coasters"><span class="toc-section-number">14.11</span> Roller coasters</a></li>
<li><a href="regression.html#running-and-blood-sugar"><span class="toc-section-number">14.12</span> Running and blood sugar</a></li>
<li><a href="regression.html#calories-and-fat-in-pizza"><span class="toc-section-number">14.13</span> Calories and fat in pizza</a></li>
<li><a href="regression.html#where-should-the-fire-stations-be"><span class="toc-section-number">14.14</span> Where should the fire stations be?</a></li>
<li><a href="regression.html#being-satisfied-with-hospital"><span class="toc-section-number">14.15</span> Being satisfied with hospital</a></li>
<li><a href="regression.html#handling-shipments-of-chemicals"><span class="toc-section-number">14.16</span> Handling shipments of chemicals</a></li>
<li><a href="regression.html#salaries-of-mathematicians"><span class="toc-section-number">14.17</span> Salaries of mathematicians</a></li>
<li><a href="regression.html#predicting-gpa-of-computer-science-students"><span class="toc-section-number">14.18</span> Predicting GPA of computer science students</a></li>
</ul></li>
<li><a href="dates-and-times.html#dates-and-times"><span class="toc-section-number">15</span> Dates and times</a>
<ul>
<li><a href="dates-and-times.html#dealing-with-dates-in-the-worcester-heart-attack-study"><span class="toc-section-number">15.1</span> Dealing with dates in the Worcester Heart Attack study</a></li>
<li><a href="dates-and-times.html#growth-of-mizuna-lettuce-seeds"><span class="toc-section-number">15.2</span> Growth of Mizuna lettuce seeds</a></li>
<li><a href="dates-and-times.html#types-of-childbirth"><span class="toc-section-number">15.3</span> Types of childbirth</a></li>
<li><a href="dates-and-times.html#wolves-and-caribou"><span class="toc-section-number">15.4</span> Wolves and caribou</a></li>
</ul></li>
<li><a href="functions.html#functions"><span class="toc-section-number">16</span> Functions</a>
<ul>
<li><a href="functions.html#making-some-r-functions"><span class="toc-section-number">16.1</span> Making some R functions</a></li>
<li><a href="functions.html#the-collatz-sequence"><span class="toc-section-number">16.2</span> The Collatz sequence</a></li>
</ul></li>
<li><a href="the-bootstrap.html#the-bootstrap"><span class="toc-section-number">17</span> The Bootstrap</a>
<ul>
<li><a href="the-bootstrap.html#air-conditioning-failures"><span class="toc-section-number">17.1</span> Air conditioning failures</a></li>
<li><a href="the-bootstrap.html#air-conditioning-failures-bootstrapping-the-median"><span class="toc-section-number">17.2</span> Air conditioning failures: bootstrapping the median</a></li>
</ul></li>
<li><a href="bayesian-statistics-with-stan.html#bayesian-statistics-with-stan"><span class="toc-section-number">18</span> Bayesian Statistics with Stan</a>
<ul>
<li><a href="bayesian-statistics-with-stan.html#estimating-proportion-in-favour-from-a-survey"><span class="toc-section-number">18.1</span> Estimating proportion in favour from a survey</a></li>
<li><a href="bayesian-statistics-with-stan.html#bayesian-regression"><span class="toc-section-number">18.2</span> Bayesian regression</a></li>
</ul></li>
<li><a href="logistic-regression.html#logistic-regression"><span class="toc-section-number">19</span> Logistic regression</a>
<ul>
<li><a href="logistic-regression.html#finding-wolf-spiders-on-the-beach"><span class="toc-section-number">19.1</span> Finding wolf spiders on the beach</a></li>
<li><a href="logistic-regression.html#killing-aphids"><span class="toc-section-number">19.2</span> Killing aphids</a></li>
<li><a href="logistic-regression.html#the-effects-of-substance-a"><span class="toc-section-number">19.3</span> The effects of Substance A</a></li>
<li><a href="logistic-regression.html#what-makes-an-animal-get-infected"><span class="toc-section-number">19.4</span> What makes an animal get infected?</a></li>
<li><a href="logistic-regression.html#the-brain-of-a-cat"><span class="toc-section-number">19.5</span> The brain of a cat</a></li>
<li><a href="logistic-regression.html#how-not-to-get-heart-disease"><span class="toc-section-number">19.6</span> How not to get heart disease</a></li>
<li><a href="logistic-regression.html#successful-breastfeeding"><span class="toc-section-number">19.7</span> Successful breastfeeding</a></li>
<li><a href="logistic-regression.html#making-it-over-the-mountains"><span class="toc-section-number">19.8</span> Making it over the mountains</a></li>
<li><a href="logistic-regression.html#who-needs-the-most-intensive-care"><span class="toc-section-number">19.9</span> Who needs the most intensive care?</a></li>
<li><a href="logistic-regression.html#go-away-and-dont-come-back"><span class="toc-section-number">19.10</span> Go away and don’t come back!</a></li>
</ul></li>
<li><a href="logistic-regression-with-ordinal-or-nominal-response.html#logistic-regression-with-ordinal-or-nominal-response"><span class="toc-section-number">20</span> Logistic regression with ordinal or nominal response</a>
<ul>
<li><a href="logistic-regression-with-ordinal-or-nominal-response.html#do-you-like-your-mobile-phone"><span class="toc-section-number">20.1</span> Do you like your mobile phone?</a></li>
<li><a href="logistic-regression-with-ordinal-or-nominal-response.html#attitudes-towards-abortion"><span class="toc-section-number">20.2</span> Attitudes towards abortion</a></li>
<li><a href="logistic-regression-with-ordinal-or-nominal-response.html#finding-non-missing-values"><span class="toc-section-number">20.3</span> Finding non-missing values</a></li>
<li><a href="logistic-regression-with-ordinal-or-nominal-response.html#european-social-survey-and-voting"><span class="toc-section-number">20.4</span> European Social Survey and voting</a></li>
<li><a href="logistic-regression-with-ordinal-or-nominal-response.html#alligator-food"><span class="toc-section-number">20.5</span> Alligator food</a></li>
<li><a href="logistic-regression-with-ordinal-or-nominal-response.html#how-do-you-like-your-steak-the-data"><span class="toc-section-number">20.6</span> How do you like your steak – the data</a></li>
<li><a href="logistic-regression-with-ordinal-or-nominal-response.html#crimes-in-san-francisco-the-data"><span class="toc-section-number">20.7</span> Crimes in San Francisco – the data</a></li>
<li><a href="logistic-regression-with-ordinal-or-nominal-response.html#how-do-you-like-your-steak"><span class="toc-section-number">20.8</span> How do you like your steak?</a></li>
<li><a href="logistic-regression-with-ordinal-or-nominal-response.html#crimes-in-san-francisco"><span class="toc-section-number">20.9</span> Crimes in San Francisco</a></li>
<li><a href="logistic-regression-with-ordinal-or-nominal-response.html#high-school-and-beyond"><span class="toc-section-number">20.10</span> High School and Beyond</a></li>
<li><a href="logistic-regression-with-ordinal-or-nominal-response.html#what-sports-do-these-athletes-play"><span class="toc-section-number">20.11</span> What sports do these athletes play?</a></li>
</ul></li>
<li><a href="survival-analysis.html#survival-analysis"><span class="toc-section-number">21</span> Survival analysis</a>
<ul>
<li><a href="survival-analysis.html#the-worcester-survey"><span class="toc-section-number">21.1</span> The Worcester survey</a></li>
<li><a href="survival-analysis.html#drug-treatment-programs"><span class="toc-section-number">21.2</span> Drug treatment programs</a></li>
<li><a href="survival-analysis.html#multiple-myeloma"><span class="toc-section-number">21.3</span> Multiple myeloma</a></li>
<li><a href="survival-analysis.html#ovarian-cancer"><span class="toc-section-number">21.4</span> Ovarian cancer</a></li>
</ul></li>
<li><a href="analysis-of-variance-revisited.html#analysis-of-variance-revisited"><span class="toc-section-number">22</span> Analysis of variance revisited</a>
<ul>
<li><a href="analysis-of-variance-revisited.html#acid-rain"><span class="toc-section-number">22.1</span> Acid rain</a></li>
<li><a href="analysis-of-variance-revisited.html#treating-hay-fever"><span class="toc-section-number">22.2</span> Treating hay fever</a></li>
<li><a href="analysis-of-variance-revisited.html#focused-comparisons-of-the-effect-of-caffeine"><span class="toc-section-number">22.3</span> Focused comparisons of the effect of caffeine</a></li>
<li><a href="analysis-of-variance-revisited.html#who-studies-the-most-outside-class"><span class="toc-section-number">22.4</span> Who studies the most outside class?</a></li>
<li><a href="analysis-of-variance-revisited.html#mental-context"><span class="toc-section-number">22.5</span> Mental context</a></li>
<li><a href="analysis-of-variance-revisited.html#trying-on-shirts"><span class="toc-section-number">22.6</span> Trying on shirts</a></li>
<li><a href="analysis-of-variance-revisited.html#productivity-and-research-and-development"><span class="toc-section-number">22.7</span> Productivity and research-and-development</a></li>
<li><a href="analysis-of-variance-revisited.html#treating-leprosy"><span class="toc-section-number">22.8</span> Treating leprosy</a></li>
</ul></li>
<li><a href="multivariate-analysis-of-variance.html#multivariate-analysis-of-variance"><span class="toc-section-number">23</span> Multivariate analysis of variance</a>
<ul>
<li><a href="multivariate-analysis-of-variance.html#fabricated-data"><span class="toc-section-number">23.1</span> Fabricated data</a></li>
<li><a href="multivariate-analysis-of-variance.html#do-characteristics-of-urine-depend-on-obesity"><span class="toc-section-number">23.2</span> Do characteristics of urine depend on obesity?</a></li>
<li><a href="multivariate-analysis-of-variance.html#how-do-height-and-weight-depend-on-sport-played-by-elite-athletes"><span class="toc-section-number">23.3</span> How do height and weight depend on sport played by elite athletes?</a></li>
</ul></li>
<li><a href="repeated-measures.html#repeated-measures"><span class="toc-section-number">24</span> Repeated measures</a>
<ul>
<li><a href="repeated-measures.html#effect-of-drug-on-rat-weight"><span class="toc-section-number">24.1</span> Effect of drug on rat weight</a></li>
<li><a href="repeated-measures.html#social-interaction-among-old-people"><span class="toc-section-number">24.2</span> Social interaction among old people</a></li>
<li><a href="repeated-measures.html#childrens-stress-levels-and-airports"><span class="toc-section-number">24.3</span> Children’s stress levels and airports</a></li>
<li><a href="repeated-measures.html#body-fat-as-repeated-measures"><span class="toc-section-number">24.4</span> Body fat as repeated measures</a></li>
<li><a href="repeated-measures.html#investigating-motor-activity-in-rats"><span class="toc-section-number">24.5</span> Investigating motor activity in rats</a></li>
<li><a href="repeated-measures.html#repeated-measures-with-no-background"><span class="toc-section-number">24.6</span> Repeated measures with no background</a></li>
</ul></li>
<li><a href="discriminant-analysis.html#discriminant-analysis"><span class="toc-section-number">25</span> Discriminant analysis</a>
<ul>
<li><a href="discriminant-analysis.html#telling-whether-a-banknote-is-real-or-counterfeit"><span class="toc-section-number">25.1</span> Telling whether a banknote is real or counterfeit</a></li>
<li><a href="discriminant-analysis.html#urine-and-obesity-what-makes-a-difference"><span class="toc-section-number">25.2</span> Urine and obesity: what makes a difference?</a></li>
<li><a href="discriminant-analysis.html#understanding-a-manova"><span class="toc-section-number">25.3</span> Understanding a MANOVA</a></li>
<li><a href="discriminant-analysis.html#what-distinguishes-people-who-do-different-jobs"><span class="toc-section-number">25.4</span> What distinguishes people who do different jobs?</a></li>
<li><a href="discriminant-analysis.html#observing-children-with-adhd"><span class="toc-section-number">25.5</span> Observing children with ADHD</a></li>
<li><a href="discriminant-analysis.html#growing-corn"><span class="toc-section-number">25.6</span> Growing corn</a></li>
<li><a href="discriminant-analysis.html#understanding-athletes-height-weight-sport-and-gender"><span class="toc-section-number">25.7</span> Understanding athletes’ height, weight, sport and gender</a></li>
</ul></li>
<li><a href="cluster-analysis.html#cluster-analysis"><span class="toc-section-number">26</span> Cluster analysis</a>
<ul>
<li><a href="cluster-analysis.html#sites-on-the-sea-bed"><span class="toc-section-number">26.1</span> Sites on the sea bed</a></li>
<li><a href="cluster-analysis.html#dissimilarities-between-fruits"><span class="toc-section-number">26.2</span> Dissimilarities between fruits</a></li>
<li><a href="cluster-analysis.html#similarity-of-species"><span class="toc-section-number">26.3</span> Similarity of species</a></li>
<li><a href="cluster-analysis.html#rating-beer"><span class="toc-section-number">26.4</span> Rating beer</a></li>
<li><a href="cluster-analysis.html#clustering-the-swiss-bills"><span class="toc-section-number">26.5</span> Clustering the Swiss bills</a></li>
<li><a href="cluster-analysis.html#grouping-similar-cars"><span class="toc-section-number">26.6</span> Grouping similar cars</a></li>
<li><a href="cluster-analysis.html#running-jumping-and-throwing"><span class="toc-section-number">26.7</span> Running, jumping, and throwing</a></li>
<li><a href="cluster-analysis.html#bridges-in-pittsburgh"><span class="toc-section-number">26.8</span> Bridges in Pittsburgh</a></li>
<li><a href="cluster-analysis.html#clustering-the-australian-athletes"><span class="toc-section-number">26.9</span> Clustering the Australian athletes</a></li>
</ul></li>
<li><a href="drawing-maps-with-leaflet.html#drawing-maps-with-leaflet"><span class="toc-section-number">27</span> Drawing maps with Leaflet</a>
<ul>
<li><a href="drawing-maps-with-leaflet.html#the-brain-of-a-cat-revisited"><span class="toc-section-number">27.1</span> The brain of a cat, revisited</a></li>
<li><a href="drawing-maps-with-leaflet.html#making-a-map-of-wisconsin"><span class="toc-section-number">27.2</span> Making a map of Wisconsin</a></li>
</ul></li>
<li><a href="multidimensional-scaling.html#multidimensional-scaling"><span class="toc-section-number">28</span> Multidimensional Scaling</a>
<ul>
<li><a href="multidimensional-scaling.html#making-a-map-of-wisconsin-1"><span class="toc-section-number">28.1</span> Making a map of Wisconsin</a></li>
<li><a href="multidimensional-scaling.html#things-that-feel-similar-to-each-other"><span class="toc-section-number">28.2</span> Things that feel similar to each other</a></li>
<li><a href="multidimensional-scaling.html#confusing-letters"><span class="toc-section-number">28.3</span> Confusing letters</a></li>
<li><a href="multidimensional-scaling.html#more-beer-please"><span class="toc-section-number">28.4</span> More beer please</a></li>
<li><a href="multidimensional-scaling.html#feeling-similar-again"><span class="toc-section-number">28.5</span> Feeling similar, again</a></li>
</ul></li>
<li><a href="principal-components-and-factor-analysis.html#principal-components-and-factor-analysis"><span class="toc-section-number">29</span> Principal Components and Factor Analysis</a>
<ul>
<li><a href="principal-components-and-factor-analysis.html#the-weather-somewhere"><span class="toc-section-number">29.1</span> The weather, somewhere</a></li>
<li><a href="principal-components-and-factor-analysis.html#air-pollution"><span class="toc-section-number">29.2</span> Air pollution</a></li>
<li><a href="principal-components-and-factor-analysis.html#a-correlation-matrix"><span class="toc-section-number">29.3</span> A correlation matrix</a></li>
<li><a href="principal-components-and-factor-analysis.html#the-interpersonal-circumplex"><span class="toc-section-number">29.4</span> The Interpersonal Circumplex</a></li>
</ul></li>
<li><a href="frequency-table-analysis.html#frequency-table-analysis"><span class="toc-section-number">30</span> Frequency table analysis</a>
<ul>
<li><a href="frequency-table-analysis.html#college-plans"><span class="toc-section-number">30.1</span> College plans</a></li>
<li><a href="frequency-table-analysis.html#predicting-voting"><span class="toc-section-number">30.2</span> Predicting voting</a></li>
</ul></li>
</ul>
</div>
</div>
</div>
<div class="row">
<div class="col-sm-12">
<div id="principal-components-and-factor-analysis" class="section level1" number="29">
<h1><span class="header-section-number">Chapter 29</span> Principal Components and Factor Analysis</h1>
<p>Packages for this chapter:</p>
<div class="sourceCode" id="cb3388"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb3388-1"><a href="principal-components-and-factor-analysis.html#cb3388-1"></a><span class="kw">library</span>(ggbiplot)</span>
<span id="cb3388-2"><a href="principal-components-and-factor-analysis.html#cb3388-2"></a><span class="kw">library</span>(tidyverse)</span></code></pre></div>
<div id="the-weather-somewhere" class="section level2" number="29.1">
<h2><span class="header-section-number">29.1</span> The weather, somewhere</h2>
<p>The data in
<a href="http://www.utsc.utoronto.ca/~butler/d29/weather_2014.csv">link</a> is of the
weather in a certain location: daily weather records for 2014. The
variables are:</p>
<ul>
<li><p>day of the year (1 through 365)</p></li>
<li><p>day of the month</p></li>
<li><p>number of the month</p></li>
<li><p>season</p></li>
<li><p>low temperature (for the day)</p></li>
<li><p>high temperature</p></li>
<li><p>average temperature</p></li>
<li><p>time of the low temperature</p></li>
<li><p>time of the high temperature</p></li>
<li><p>rainfall (mm)</p></li>
<li><p>average wind speed</p></li>
<li><p>wind gust (highest wind speed)</p></li>
<li><p>time of the wind gust</p></li>
<li><p>wind direction</p></li>
</ul>
<ol style="list-style-type: lower-alpha">
<li>Read in the data, and create a data frame containing only
the temperature variables, the rainfall and the wind speed variables
(the ones that are actual numbers, not times or text). Display the
first few lines of your data frame.</li>
</ol>
<p>Solution</p>
<p>Read into a temporary data frame, and then process:</p>
<div class="sourceCode" id="cb3389"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb3389-1"><a href="principal-components-and-factor-analysis.html#cb3389-1"></a>my_url &lt;-<span class="st"> &quot;http://www.utsc.utoronto.ca/~butler/d29/weather_2014.csv&quot;</span></span>
<span id="cb3389-2"><a href="principal-components-and-factor-analysis.html#cb3389-2"></a>weather<span class="fl">.0</span> &lt;-<span class="st"> </span><span class="kw">read_csv</span>(my_url)</span>
<span id="cb3389-3"><a href="principal-components-and-factor-analysis.html#cb3389-3"></a>weather<span class="fl">.0</span></span></code></pre></div>
<p>There are lots of columns, of which we only want a few:</p>
<div class="sourceCode" id="cb3390"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb3390-1"><a href="principal-components-and-factor-analysis.html#cb3390-1"></a>(weather<span class="fl">.0</span> <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">select</span>(l.temp<span class="op">:</span>ave.temp, rain<span class="op">:</span>gust.wind) -&gt;<span class="st"> </span>weather)</span></code></pre></div>
<ol start="2" style="list-style-type: lower-alpha">
<li>Find five-number summaries for each column by running
<code>quantile</code> on all the columns of the data frame (at once, if
you can).</li>
</ol>
<p>Solution</p>
<p>I think this is the easiest way:</p>
<div class="sourceCode" id="cb3391"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb3391-1"><a href="principal-components-and-factor-analysis.html#cb3391-1"></a>weather <span class="op">%&gt;%</span><span class="st"> </span></span>
<span id="cb3391-2"><a href="principal-components-and-factor-analysis.html#cb3391-2"></a><span class="st">  </span><span class="kw">summarize</span>(<span class="kw">across</span>(<span class="kw">everything</span>(), <span class="op">~</span><span class="kw">quantile</span>(.)))</span></code></pre></div>
<p>This loses the actual percents of the percentiles of the five-number summary (because they are “names” of the numerical result, and the tidyverse doesn’t like names.) I think you can see which percentile is which, though.</p>
<p>Another way to do it is to make a column of column names, using
<code>pivot_longer</code>, and then use <code>nest</code> and list-columns to find
the quantiles for each variable:</p>
<div class="sourceCode" id="cb3392"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb3392-1"><a href="principal-components-and-factor-analysis.html#cb3392-1"></a>weather <span class="op">%&gt;%</span></span>
<span id="cb3392-2"><a href="principal-components-and-factor-analysis.html#cb3392-2"></a><span class="st">  </span><span class="kw">pivot_longer</span>(<span class="kw">everything</span>(), <span class="dt">names_to=</span><span class="st">&quot;xname&quot;</span>, <span class="dt">values_to=</span><span class="st">&quot;x&quot;</span>) <span class="op">%&gt;%</span></span>
<span id="cb3392-3"><a href="principal-components-and-factor-analysis.html#cb3392-3"></a><span class="st">  </span><span class="kw">nest_by</span>(xname) <span class="op">%&gt;%</span></span>
<span id="cb3392-4"><a href="principal-components-and-factor-analysis.html#cb3392-4"></a><span class="st">  </span><span class="kw">mutate</span>(<span class="dt">q =</span> <span class="kw">list</span>(<span class="kw">enframe</span>(<span class="kw">quantile</span>(data<span class="op">$</span>x)))) <span class="op">%&gt;%</span></span>
<span id="cb3392-5"><a href="principal-components-and-factor-analysis.html#cb3392-5"></a><span class="st">  </span><span class="kw">unnest</span>(q) <span class="op">%&gt;%</span></span>
<span id="cb3392-6"><a href="principal-components-and-factor-analysis.html#cb3392-6"></a><span class="st">  </span><span class="kw">pivot_wider</span>(<span class="dt">names_from=</span>name, <span class="dt">values_from=</span>value) <span class="op">%&gt;%</span></span>
<span id="cb3392-7"><a href="principal-components-and-factor-analysis.html#cb3392-7"></a><span class="st">  </span><span class="kw">select</span>(<span class="op">-</span>data)</span></code></pre></div>
<p>That was a lot of work, but it depends on how you see it when you’re coding it. You should investigate this one line at a time, but the steps are:</p>
<ul>
<li><p>create a “long” data frame with one column of variable names and a second with the values for that variable</p></li>
<li><p>make mini-data-frames <code>data</code> containing everything but <code>xname</code>: that is, one column <code>x</code> with the values for that variable.</p></li>
<li><p>for each mini-data-frame, work out the quantiles of its <code>x</code>. The <code>enframe</code> saves the labels for what percentiles they are.</p></li>
<li><p>Unnest this to make a long data frame with one row for each quantile for each variable.</p></li>
<li><p>put the variable names in rows and the percentiles in columns.</p></li>
</ul>
<ol start="3" style="list-style-type: lower-alpha">
<li>Run a principal components analysis (on the correlation matrix).</li>
</ol>
<p>Solution</p>
<div class="sourceCode" id="cb3393"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb3393-1"><a href="principal-components-and-factor-analysis.html#cb3393-1"></a>weather<span class="fl">.1</span> &lt;-<span class="st"> </span><span class="kw">princomp</span>(weather, <span class="dt">cor =</span> T)</span></code></pre></div>
<ol start="4" style="list-style-type: lower-alpha">
<li>Obtain a <code>summary</code> of your principal components
analysis. How many components do you think are worth investigating?</li>
</ol>
<p>Solution</p>
<div class="sourceCode" id="cb3394"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb3394-1"><a href="principal-components-and-factor-analysis.html#cb3394-1"></a><span class="kw">summary</span>(weather<span class="fl">.1</span>)</span></code></pre></div>
<pre><code>## Importance of components:
##                           Comp.1    Comp.2     Comp.3     Comp.4     Comp.5      Comp.6
## Standard deviation     1.7830875 1.4138296 0.74407069 0.38584917 0.33552998 0.081140732
## Proportion of Variance 0.5299001 0.3331524 0.09227353 0.02481326 0.01876339 0.001097303
## Cumulative Proportion  0.5299001 0.8630525 0.95532604 0.98013930 0.99890270 1.000000000</code></pre>
<p>The issue is to see where the standard deviations are getting small
(after the second component, or perhaps the third one) and to see
where the cumulative proportion of variance explained is acceptably
high (again, after the second one, 86%, or the third, 95%).</p>
<ol start="5" style="list-style-type: lower-alpha">
<li>Make a scree plot. Does this
support your conclusion from the previous part?</li>
</ol>
<p>Solution</p>
<p><code>ggscreeplot</code> from <code>ggbiplot</code>:</p>
<div class="sourceCode" id="cb3396"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb3396-1"><a href="principal-components-and-factor-analysis.html#cb3396-1"></a><span class="kw">ggscreeplot</span>(weather<span class="fl">.1</span>)</span></code></pre></div>
<p><img src="pasias_files/figure-html/adskjheuya-1.png" width="672"  /></p>
<p>I see elbows at 3 and at 4. Remember you want to be on the mountain
for these, not on the scree, so this suggests 2 or 3 components, which
is exactly what we got from looking at the standard deviations and
cumulative variance explained.</p>
<p>The eigenvalue-greater-than-1 thing
(that is, the “standard deviation” in the <code>summary</code> being greater than 1)
says 2 components, rather than 3.</p>
<ol start="6" style="list-style-type: lower-alpha">
<li>Obtain the component loadings. How do the first three
components depend on the original variables? (That is, what kind of
values for the original variables would make the component scores
large or small?)</li>
</ol>
<p>Solution</p>
<div class="sourceCode" id="cb3397"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb3397-1"><a href="principal-components-and-factor-analysis.html#cb3397-1"></a>weather<span class="fl">.1</span><span class="op">$</span>loadings</span></code></pre></div>
<pre><code>## 
## Loadings:
##           Comp.1 Comp.2 Comp.3 Comp.4 Comp.5 Comp.6
## l.temp     0.465  0.348         0.542  0.470  0.379
## h.temp     0.510  0.231        -0.576 -0.381  0.458
## ave.temp   0.502  0.311                      -0.804
## rain      -0.296  0.397  0.853        -0.163       
## ave.wind  -0.253  0.560 -0.463  0.357 -0.529       
## gust.wind -0.347  0.507 -0.230 -0.492  0.572       
## 
##                Comp.1 Comp.2 Comp.3 Comp.4 Comp.5 Comp.6
## SS loadings     1.000  1.000  1.000  1.000  1.000  1.000
## Proportion Var  0.167  0.167  0.167  0.167  0.167  0.167
## Cumulative Var  0.167  0.333  0.500  0.667  0.833  1.000</code></pre>
<ul>
<li><p>1: This component loads mainly (and positively) on the temperature
variables, so when temperature is high, component 1 is high.
You could also say that it loads negatively on the other
variables, in which case component 1 is high if the temperature
variables are low and the rain and wind variables are high.</p></li>
<li><p>2: This one loads most heavily, positively, on wind: when wind is high,
component 2 is high. Again, you can make the judgement call that the
other variables also feature in component 2, so that when
<em>everything</em> is large, component 2 is large and small with small.</p></li>
<li><p>3: This one is a bit clearer. The blank loadings are close to 0,
and can be ignored. The main thing in component 3 is rain: when
rainfall is large, component 3 is large. Or, if you like, it is
large (positive) when rainfall is large <em>and wind is small</em>.</p></li>
</ul>
<p>The interpretation here is kind of muffled, because each component has
bits of everything. One of the advantages of factor analysis that we
see in class later is that
you can do a “rotation” so that each variable (to a greater extent)
is either <em>in</em> a factor or <em>out</em> of it. Such a varimax rotation
is the default for <code>factanal</code>, which I presume I now have to
show you (so this is looking ahead):</p>
<div class="sourceCode" id="cb3399"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb3399-1"><a href="principal-components-and-factor-analysis.html#cb3399-1"></a>weather<span class="fl">.2</span> &lt;-<span class="st"> </span><span class="kw">factanal</span>(weather, <span class="dv">3</span>, <span class="dt">scores =</span> <span class="st">&quot;r&quot;</span>)</span>
<span id="cb3399-2"><a href="principal-components-and-factor-analysis.html#cb3399-2"></a>weather<span class="fl">.2</span><span class="op">$</span>loadings</span></code></pre></div>
<pre><code>## 
## Loadings:
##           Factor1 Factor2 Factor3
## l.temp     0.964          -0.230 
## h.temp     0.939  -0.203   0.267 
## ave.temp   0.992  -0.101         
## rain      -0.147   0.604         
## ave.wind           0.864         
## gust.wind -0.144   0.984         
## 
##                Factor1 Factor2 Factor3
## SS loadings      2.839   2.131   0.140
## Proportion Var   0.473   0.355   0.023
## Cumulative Var   0.473   0.828   0.852</code></pre>
<p>These are a lot less ambiguous: factor 1 is temperature, factor 2 is
rain and wind, and factor 3 is large (positive) if the high
temperature is high or the low temperature is low: that is, if the
high temperature was especially high relative to the low temperature
(or, said differently, if the temperature <em>range</em> was high).</p>
<p>These factors are rather pleasantly interpretable.</p>
<p><code>ggbiplot</code> mysteriously doesn’t handle factor analyses, so we
have to go back to the base-graphics version, which goes a bit like this:</p>
<div class="sourceCode" id="cb3401"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb3401-1"><a href="principal-components-and-factor-analysis.html#cb3401-1"></a><span class="kw">biplot</span>(weather<span class="fl">.2</span><span class="op">$</span>scores, weather<span class="fl">.2</span><span class="op">$</span>loadings)</span></code></pre></div>
<p><img src="pasias_files/figure-html/unnamed-chunk-2088-1.png" width="672"  /></p>
<p>Now you see that the factors are aligned with the axes, and it’s very
clear what the factors “represent”. (You don’t see much else, in all
honesty, but you see at least this much.)</p>
<ol start="7" style="list-style-type: lower-alpha">
<li>Obtain the principal component scores, for as many components
as you think are reasonable, and display the first
20 of them for each component alongside the other variables in your
data frame.</li>
</ol>
<p>Solution</p>
<p>Something like this. I begin by turning the component scores
(which are a matrix) into a data frame, and selecting the ones I
want (the first three):</p>
<div class="sourceCode" id="cb3402"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb3402-1"><a href="principal-components-and-factor-analysis.html#cb3402-1"></a><span class="kw">as_tibble</span>(weather<span class="fl">.1</span><span class="op">$</span>scores) <span class="op">%&gt;%</span></span>
<span id="cb3402-2"><a href="principal-components-and-factor-analysis.html#cb3402-2"></a><span class="st">  </span><span class="kw">select</span>(<span class="dv">1</span><span class="op">:</span><span class="dv">3</span>) <span class="op">%&gt;%</span></span>
<span id="cb3402-3"><a href="principal-components-and-factor-analysis.html#cb3402-3"></a><span class="st">  </span><span class="kw">bind_cols</span>(weather) <span class="op">%&gt;%</span></span>
<span id="cb3402-4"><a href="principal-components-and-factor-analysis.html#cb3402-4"></a><span class="st">  </span><span class="kw">mutate</span>(<span class="dt">day =</span> <span class="kw">row_number</span>()) -&gt;<span class="st"> </span>d</span>
<span id="cb3402-5"><a href="principal-components-and-factor-analysis.html#cb3402-5"></a>d <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">print</span>(<span class="dt">n =</span> <span class="dv">20</span>)</span></code></pre></div>
<p>I just did the first three scores. I made a column <code>day</code> so that I can see which day of the year I am looking at (later).</p>
<ol start="8" style="list-style-type: lower-alpha">
<li>Find a day that scores low on component 1, and explain briefly why
it came out that way (by looking at the measured variables).</li>
</ol>
<p>Solution</p>
<p>We can do this one and the ones following by running
<code>arrange</code> appropriately:</p>
<div class="sourceCode" id="cb3403"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb3403-1"><a href="principal-components-and-factor-analysis.html#cb3403-1"></a>d <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">arrange</span>(Comp<span class="fl">.1</span>)</span></code></pre></div>
<p>Day 40 has the lowest component 1 score. This is one of the
cooler days. Also, there is a
largish amount of rain <em>and</em> wind. So low temperature, high
rain and wind.
Some of the other days on my list were cooler than day 4, but they
had less rain and less wind.</p>
<ol style="list-style-type: lower-roman">
<li>Find a day that scores high on component 2, and explain
briefly why it came out that way.</li>
</ol>
<p>Solution</p>
<div class="sourceCode" id="cb3404"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb3404-1"><a href="principal-components-and-factor-analysis.html#cb3404-1"></a>d <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">arrange</span>(<span class="kw">desc</span>(Comp<span class="fl">.2</span>))</span></code></pre></div>
<p>Day 37. These are days when the wind speed (average or
gust) is on the high side.</p>
<ol start="10" style="list-style-type: lower-alpha">
<li>Find a day that scores high on component 3, and explain
briefly why it came out high.</li>
</ol>
<p>Solution</p>
<div class="sourceCode" id="cb3405"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb3405-1"><a href="principal-components-and-factor-analysis.html#cb3405-1"></a>d <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">arrange</span>(<span class="kw">desc</span>(Comp<span class="fl">.3</span>))</span></code></pre></div>
<p>Day 307. Component 3 was mainly rain, so it is not surprising that
the rainfall is the highest on this day.</p>
<ol start="11" style="list-style-type: lower-alpha">
<li>Make a biplot of these data, labelling the days by the day
count (from 1 to 365). You may have to get the day count from the
original data frame that you read in from the file. You can shrink
the day numbers to make them overwrite each other (a bit) less.</li>
</ol>
<p>Solution</p>
<p><code>ggbiplot</code>. I did some digging in the help file to figure
out how to label the points by a variable and how to control the
size of the labels, and I also went digging in the data frame
that I read in from the file to get the count of the day in the
year, which was called <code>day.count</code>:</p>
<div class="sourceCode" id="cb3406"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb3406-1"><a href="principal-components-and-factor-analysis.html#cb3406-1"></a><span class="kw">ggbiplot</span>(weather<span class="fl">.1</span>, <span class="dt">labels =</span> weather<span class="fl">.0</span><span class="op">$</span>day.count, <span class="dt">labels.size =</span> <span class="dv">2</span>)</span></code></pre></div>
<p><img src="pasias_files/figure-html/unnamed-chunk-2094-1.png" width="672"  /></p>
<p>I think the label text is small enough, though you could make it
smaller. I’ll be asking you to look at some extreme points in a
moment, so those are the only ones you’ll need to be able to
disentangle.</p>
<p>The variables divide into two groups: the temperature ones, that point
to about 2 o’clock, and the wind and rain ones, that point to about 11
o’clock. These are not straight up or down or across, so they all
feature in both components: component 1 is mostly temperature, but has
a bit of wind/rain in it, while component 2 is mostly wind/rain with a
bit of temperature in it. You might be wondering whether things
couldn’t be rotated so that, say, the temperature variables go across
and the rain/wind ones go down, which means you’d have a temperature
component and a rain/wind component. This is what factor analysis
does, and I think I did that earlier (and this is what we found).</p>
<ol start="12" style="list-style-type: lower-alpha">
<li>Looking at your biplot, what do you think was remarkable
about the weather on day 37? Day 211? Confirm your guesses by
looking at the appropriate rows of your data frame (and comparing
with your <code>summary</code> from earlier).</li>
</ol>
<p>Solution</p>
<p>Day 37 is at the top left of the plot, at the pointy end of
the arrows for rain, wind gust and average wind. This suggests a
rainy, windy day:</p>
<div class="sourceCode" id="cb3407"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb3407-1"><a href="principal-components-and-factor-analysis.html#cb3407-1"></a>weather <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">slice</span>(<span class="dv">37</span>)</span></code></pre></div>
<p>Those are high numbers for both rain and wind (the highest for average
wind and above the third quartile otherwise), but the temperatures
are unremarkable.</p>
<p>Day 211 is towards the pointy end of the arrows for temperature, so
this is a hot day:</p>
<div class="sourceCode" id="cb3408"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb3408-1"><a href="principal-components-and-factor-analysis.html#cb3408-1"></a>weather <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">slice</span>(<span class="dv">211</span>)</span></code></pre></div>
<p>This is actually the hottest day of the entire year: day 211 is
highest on all three temperatures, while the
wind speeds are right around average (and no rain is not completely
surprising).</p>
<p>I can do a couple more. Points away from the pointy end of the arrows
are <em>low</em> on the variables in question, for example day 265:</p>
<div class="sourceCode" id="cb3409"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb3409-1"><a href="principal-components-and-factor-analysis.html#cb3409-1"></a>weather <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">slice</span>(<span class="dv">265</span>)</span></code></pre></div>
<p>This is not really low rain, but it is definitely low
<em>wind</em>. What about day 47?</p>
<div class="sourceCode" id="cb3410"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb3410-1"><a href="principal-components-and-factor-analysis.html#cb3410-1"></a>weather <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">slice</span>(<span class="dv">47</span>)</span></code></pre></div>
<p>This is predominantly low on temperature. In fact, it is kind of low
on wind and rain too.
<label for="tufte-mn-269" class="margin-toggle">⊕</label><input type="checkbox" id="tufte-mn-269" class="margin-toggle"><span class="marginnote">If you ignore the wind gust, anyway.</span>
This makes sense, because not only is it at the “wrong” end of the
temperature arrows, it is kind of at the wrong end of the wind/rain
arrows as well.</p>
<p>Having done these by percentile ranks in one of the other questions,
let’s see if we can do that here as well:</p>
<div class="sourceCode" id="cb3411"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb3411-1"><a href="principal-components-and-factor-analysis.html#cb3411-1"></a>weather <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">mutate</span>(<span class="kw">across</span>(<span class="kw">everything</span>(), <span class="op">~</span><span class="kw">percent_rank</span>(.))) <span class="op">%&gt;%</span><span class="st"> </span></span>
<span id="cb3411-2"><a href="principal-components-and-factor-analysis.html#cb3411-2"></a><span class="st">    </span><span class="kw">slice</span>(<span class="kw">c</span>(<span class="dv">37</span>, <span class="dv">211</span>, <span class="dv">265</span>, <span class="dv">47</span>))</span></code></pre></div>
<p>The idea here is that we want to <em>replace</em> all the data values by the percent-rank version of themselves, rather than <em>summarizing</em> them as we have done before. That’s what using an <code>across</code> inside a <code>mutate</code> will do.
<label for="tufte-mn-270" class="margin-toggle">⊕</label><input type="checkbox" id="tufte-mn-270" class="margin-toggle"><span class="marginnote">There are also options to keep the original variables, and give the new ones new names.</span></p>
<p>These are:</p>
<ul>
<li><p>Day 37: highly rainy and windy (and below average,
but not remarkably so, on temperature).</p></li>
<li><p>Day 211: the highest or near-highest temperature, no rain but
unremarkable for wind.</p></li>
<li><p>Day 265: Lowest for wind (and above Q3 for low temperature and
rain).</p></li>
<li><p>Day 47: Lowest or near-lowest temperature.</p></li>
</ul>
<p>The advantage to doing it this way is that you don’t need a separate
five-number summary for each variable; the percentile ranks
<em>give</em> you a comparison with quartiles (or any other percentile
of interest to you).
In case you are wondering where this is: I was doing a presentation
using these data to some Environmental Science grad students, and I
had them guess where it was. The temperatures for the whole year are
warm-temperate, with a smallish range, and sometimes a lot of
rain. This suggests a maritime climate. I gave the additional clues of
“western Europe” and
“this place’s soccer team plays in blue and white striped shirts”.
The temperatures have about the right range
low-to-high for Britain, but are too warm. Which suggests going south:
perhaps Brittany in France, but actually the west
coast of the Iberian peninsula: Porto, in northern Portugal, with the
weather blowing in off the Atlantic.</p>
</div>
<div id="air-pollution" class="section level2" number="29.2">
<h2><span class="header-section-number">29.2</span> Air pollution</h2>
<p>The data in
<a href="http://www.utsc.utoronto.ca/~butler/d29/airpollution.csv">link</a> are
measurements of air-pollution variables recorded at 12 noon on 42
different days at a location in Los Angeles. The file is in
<code>.csv</code> format, since it came from a spreadsheet. Specifically,
the variables (in suitable units), in the same order as in the data
file, are:</p>
<ul>
<li><p>wind speed</p></li>
<li><p>solar radiation</p></li>
<li><p>carbon monoxide</p></li>
<li><p>Nitric oxide (also known as nitrogen monoxide)</p></li>
<li><p>Nitrogen dioxide</p></li>
<li><p>Ozone</p></li>
<li><p>Hydrocarbons</p></li>
</ul>
<p>The aim is to describe pollution using fewer than these seven variables.</p>
<ol style="list-style-type: lower-alpha">
<li>Read in the data and demonstrate that you have the right
number of rows and columns in your data frame.</li>
</ol>
<p>Solution</p>
<p>This is a <code>.csv</code> file, so:</p>
<div class="sourceCode" id="cb3412"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb3412-1"><a href="principal-components-and-factor-analysis.html#cb3412-1"></a>my_url &lt;-<span class="st"> &quot;http://www.utsc.utoronto.ca/~butler/d29/airpollution.csv&quot;</span></span>
<span id="cb3412-2"><a href="principal-components-and-factor-analysis.html#cb3412-2"></a>air &lt;-<span class="st"> </span><span class="kw">read_csv</span>(my_url)</span></code></pre></div>
<pre><code>## 
## ── Column specification ──────────────────────────────────────────────────────────────────────────────────────
## cols(
##   wind = col_double(),
##   solar.radiation = col_double(),
##   CO = col_double(),
##   NO = col_double(),
##   NO2 = col_double(),
##   O3 = col_double(),
##   HC = col_double()
## )</code></pre>
<div class="sourceCode" id="cb3414"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb3414-1"><a href="principal-components-and-factor-analysis.html#cb3414-1"></a>air</span></code></pre></div>
<p>There should be 42 rows (for the 42 days), and 7 columns (for the 7
variables), and there are.</p>
<ol start="2" style="list-style-type: lower-alpha">
<li><a name="part:fivenum">*</a>
Obtain a five-number summary for each variable. You can do this in
one go for all seven variables.</li>
</ol>
<p>Solution</p>
<p>Like this (the cleanest):</p>
<div class="sourceCode" id="cb3415"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb3415-1"><a href="principal-components-and-factor-analysis.html#cb3415-1"></a>air <span class="op">%&gt;%</span><span class="st"> </span></span>
<span id="cb3415-2"><a href="principal-components-and-factor-analysis.html#cb3415-2"></a><span class="st">  </span><span class="kw">summarize</span>(<span class="kw">across</span>(<span class="kw">everything</span>(), <span class="op">~</span><span class="kw">quantile</span>(.)))</span></code></pre></div>
<p>I have to figure out how to
identify which number from the five number summary each of these is,
but in this case you can easily figure it out since the min is the
smallest and the max has to be the biggest in each column.</p>
<p>Or, with some more work, this:</p>
<div class="sourceCode" id="cb3416"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb3416-1"><a href="principal-components-and-factor-analysis.html#cb3416-1"></a>air <span class="op">%&gt;%</span></span>
<span id="cb3416-2"><a href="principal-components-and-factor-analysis.html#cb3416-2"></a><span class="st">  </span><span class="kw">pivot_longer</span>(<span class="kw">everything</span>(), <span class="dt">names_to=</span><span class="st">&quot;xname&quot;</span>, <span class="dt">values_to=</span><span class="st">&quot;x&quot;</span>) <span class="op">%&gt;%</span><span class="st"> </span></span>
<span id="cb3416-3"><a href="principal-components-and-factor-analysis.html#cb3416-3"></a><span class="st">  </span><span class="kw">nest_by</span>(xname) <span class="op">%&gt;%</span></span>
<span id="cb3416-4"><a href="principal-components-and-factor-analysis.html#cb3416-4"></a><span class="st">  </span><span class="kw">rowwise</span>() <span class="op">%&gt;%</span><span class="st"> </span></span>
<span id="cb3416-5"><a href="principal-components-and-factor-analysis.html#cb3416-5"></a><span class="st">  </span><span class="kw">mutate</span>(<span class="dt">q =</span> <span class="kw">list</span>(<span class="kw">enframe</span>(<span class="kw">quantile</span>(data<span class="op">$</span>x)))) <span class="op">%&gt;%</span></span>
<span id="cb3416-6"><a href="principal-components-and-factor-analysis.html#cb3416-6"></a><span class="st">  </span><span class="kw">unnest</span>(q) <span class="op">%&gt;%</span></span>
<span id="cb3416-7"><a href="principal-components-and-factor-analysis.html#cb3416-7"></a><span class="st">  </span><span class="kw">pivot_wider</span>(<span class="dt">names_from=</span>name, <span class="dt">values_from=</span>value) <span class="op">%&gt;%</span><span class="st"> </span></span>
<span id="cb3416-8"><a href="principal-components-and-factor-analysis.html#cb3416-8"></a><span class="st">  </span><span class="kw">select</span>(<span class="op">-</span>data)</span></code></pre></div>
<p>There’s a lot here. Run it one line at a time to see what it does:</p>
<ul>
<li><p>put the names of the variables in one column and the values in a second. This is the same trick as when we want to make plots of all the variables facetted.</p></li>
<li><p>the <code>nest_by</code> says: for each variable (whose names are now in <code>xname</code>), make a dataframe called <code>data</code> of the observations (in <code>x</code>) for that variable</p></li>
<li><p>the rest of the way, work one row at a time</p></li>
<li><p>work out the five-number summary for each variable, using the values <code>x</code> in the data frame <code>data</code> of each row of the list-column, one at a time. This is the base R <code>quantile</code>, working on a vector (the column <code>x</code> of the data frame <code>data</code>), so it gives you back a named vector. If you are not familiar with that, try running <code>quantile(1:10)</code> and see how the output has both the percentiles and, above them, the percents that they go with. The tidyverse doesn’t like names, so my favourite way of keeping them with a named vector is to run it through <code>enframe</code>. This makes a two-column dataframe, with a column called <code>name</code> that is in this case the percents, and a column called <code>value</code> that is the percentiles. This is a dataframe rather than a single number, so it needs a <code>list</code> on the front as well (to make another list-column).
There are rather a lot of brackets to close here; if you are not sure you have enough, type another close bracket, pause, and see what it matches (R Studio will show you). If it matches nothing, you have too many close brackets.</p></li>
<li><p>show the values of the five-number summary for each variable (in long format, but with the percentages attached)</p></li>
<li><p>for human consumption, put the percentiles in columns, one row for each variable</p></li>
<li><p>finally, get rid of the dataframes of original values (that we don’t need any more now that we have summarized them).</p></li>
</ul>
<p>Extra: say you wanted to make facetted histograms of each variable. You would begin the same way, with the <code>pivot_longer</code>, and at the end, <code>facet_wrap</code> with <code>scales = "free"</code> (since the variables are measured on different scales):</p>
<div class="sourceCode" id="cb3417"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb3417-1"><a href="principal-components-and-factor-analysis.html#cb3417-1"></a>air <span class="op">%&gt;%</span></span>
<span id="cb3417-2"><a href="principal-components-and-factor-analysis.html#cb3417-2"></a><span class="st">  </span><span class="kw">pivot_longer</span>(<span class="kw">everything</span>(), <span class="dt">names_to=</span><span class="st">&quot;xname&quot;</span>, <span class="dt">values_to=</span><span class="st">&quot;x&quot;</span>) <span class="op">%&gt;%</span><span class="st"> </span></span>
<span id="cb3417-3"><a href="principal-components-and-factor-analysis.html#cb3417-3"></a><span class="st">  </span><span class="kw">ggplot</span>(<span class="kw">aes</span>(<span class="dt">x=</span>x)) <span class="op">+</span><span class="st"> </span><span class="kw">geom_histogram</span>(<span class="dt">bins =</span> <span class="dv">6</span>) <span class="op">+</span></span>
<span id="cb3417-4"><a href="principal-components-and-factor-analysis.html#cb3417-4"></a><span class="st">  </span><span class="kw">facet_wrap</span>(<span class="op">~</span>xname, <span class="dt">scales =</span> <span class="st">&quot;free&quot;</span>)</span></code></pre></div>
<p><img src="pasias_files/figure-html/unnamed-chunk-2103-1.png" width="672"  /></p>
<p>Extra extra: I originally put a pipe symbol on the end of the line with the <code>geom_histogram</code> on it, and got an impenetrable error. However, googling the error message (often a good plan) gave me a first hit that told me exactly what I had done.</p>
<ol start="3" style="list-style-type: lower-alpha">
<li>Obtain a principal components analysis. Do it on the
correlation matrix, since the variables are measured on different
scales. You don’t need to look at the results yet.</li>
</ol>
<p>Solution</p>
<p>This too is all rather like the previous question:</p>
<div class="sourceCode" id="cb3418"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb3418-1"><a href="principal-components-and-factor-analysis.html#cb3418-1"></a>air<span class="fl">.1</span> &lt;-<span class="st"> </span><span class="kw">princomp</span>(air, <span class="dt">cor =</span> T)</span></code></pre></div>
<ol start="4" style="list-style-type: lower-alpha">
<li>Obtain a scree plot. How many principal components might be
worth looking at? Explain briefly. (There might be more than one
possibility. If so, discuss them all.)</li>
</ol>
<p>Solution</p>
<p><code>ggscreeplot</code> the thing you just obtained, having loaded
package <code>ggbiplot</code>:</p>
<div class="sourceCode" id="cb3419"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb3419-1"><a href="principal-components-and-factor-analysis.html#cb3419-1"></a><span class="kw">ggscreeplot</span>(air<span class="fl">.1</span>)</span></code></pre></div>
<p><img src="pasias_files/figure-html/unnamed-chunk-2105-1.png" width="672"  /></p>
<p>There is a technicality here, which is
that <code>ggbiplot</code>, the package, loads <code>plyr</code>, which
contains a lot of the same things as <code>dplyr</code> (the latter is a
cut-down version of the former). If you load <code>dplyr</code> and
<em>then</em> <code>plyr</code> (that is to say, if you load the
<code>tidyverse</code> first and then <code>ggbiplot</code>), you will end up
with trouble, and probably the wrong version of a lot of functions. To
avoid this, load <code>ggbiplot</code> <em>first</em>, and then you’ll be
OK.</p>
<p>Now, finally, we might diverge from the previous question. There are
actually <em>two</em> elbows on this plot, at 2 and at 4, which means
that we should entertain the idea of either 1 or 3 components. I would
be inclined to say that the elbow at 2 is still “too high up” the
mountain — there is still some more mountain below it.</p>
<p>The points at 3 and 6 components look like elbows too, but they are
<em>pointing the wrong way</em>. What you are looking for when you
search for elbows are points that are the end of the mountain and the
start of the scree. The elbows at 2 (maybe) and 4 (definitely) are
this kind of thing, but the elbows at 3 and at 6 are not.</p>
<ol start="5" style="list-style-type: lower-alpha">
<li>Look at the <code>summary</code> of the principal components
object. What light does this shed on the choice of number of
components? Explain briefly.</li>
</ol>
<p>Solution</p>
<div class="sourceCode" id="cb3420"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb3420-1"><a href="principal-components-and-factor-analysis.html#cb3420-1"></a><span class="kw">summary</span>(air<span class="fl">.1</span>)</span></code></pre></div>
<pre><code>## Importance of components:
##                           Comp.1    Comp.2    Comp.3    Comp.4     Comp.5     Comp.6     Comp.7
## Standard deviation     1.5286539 1.1772853 1.0972994 0.8526937 0.80837896 0.73259047 0.39484041
## Proportion of Variance 0.3338261 0.1980001 0.1720094 0.1038695 0.09335379 0.07666983 0.02227128
## Cumulative Proportion  0.3338261 0.5318262 0.7038356 0.8077051 0.90105889 0.97772872 1.00000000</code></pre>
<p>The first component only explains 33% of the variability, not very
much, but the first <em>three</em> components together explain 70%,
which is much more satisfactory. So I would go with 3 components.</p>
<p>There are two things here: finding an elbow, <em>and</em> explaining a
sensible fraction of the variability. You could explain more of the
variability by taking more components, but if you are not careful you
end up explaining seven variables with, um, seven variables.</p>
<p>If you go back and look at the scree plot, you’ll see that the first
elbow is really rather high up the mountain, and it’s really the
<em>second</em> elbow that is the start of the scree.</p>
<p>If this part doesn’t persuade you that three components is better than
one, you need to pick a number of components to use for the rest of
the question, and stick to it all the way through.</p>
<ol start="6" style="list-style-type: lower-alpha">
<li><a name="part:preferred">*</a> How do each of your preferred number of components depend
on the variables that were measured? Explain briefly.</li>
</ol>
<p>Solution</p>
<p>When this was a hand-in question, there were three marks for it,
which was a bit of a giveaway!
Off we go:</p>
<div class="sourceCode" id="cb3422"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb3422-1"><a href="principal-components-and-factor-analysis.html#cb3422-1"></a>air<span class="fl">.1</span><span class="op">$</span>loadings</span></code></pre></div>
<pre><code>## 
## Loadings:
##                 Comp.1 Comp.2 Comp.3 Comp.4 Comp.5 Comp.6 Comp.7
## wind             0.237  0.278  0.643  0.173  0.561  0.224  0.241
## solar.radiation -0.206 -0.527  0.224  0.778 -0.156              
## CO              -0.551        -0.114         0.573  0.110 -0.585
## NO              -0.378  0.435 -0.407  0.291         0.450  0.461
## NO2             -0.498  0.200  0.197               -0.745  0.338
## O3              -0.325 -0.567  0.160 -0.508         0.331  0.417
## HC              -0.319  0.308  0.541 -0.143 -0.566  0.266 -0.314
## 
##                Comp.1 Comp.2 Comp.3 Comp.4 Comp.5 Comp.6 Comp.7
## SS loadings     1.000  1.000  1.000  1.000  1.000  1.000  1.000
## Proportion Var  0.143  0.143  0.143  0.143  0.143  0.143  0.143
## Cumulative Var  0.143  0.286  0.429  0.571  0.714  0.857  1.000</code></pre>
<p>You’ll have to decide where to draw the line between “zero” and
“nonzero”. It doesn’t matter so much where you put the line, so your
answers can differ from mine and still be correct.</p>
<p>We need to pick the loadings that are “nonzero”, however we define
that, for example:</p>
<ul>
<li><p>component 1 depends (negatively) on carbon monoxide and nitrogen dioxide.</p></li>
<li><p>component 2 depends (negatively) on solar radiation and ozone
and possibly positively on nitric oxide.</p></li>
<li><p>component 3 depends (positively) on wind and hydrocarbons.</p></li>
</ul>
<p>It is a good idea to translate the variable names (which are
abbreviated) back into the long forms.</p>
<ol start="7" style="list-style-type: lower-alpha">
<li>Make a data frame that contains (i) the original data, (ii) a column of row numbers, (iii) the principal component scores. Display some of it.</li>
</ol>
<p>Solution</p>
<p>All the columns contain numbers, so <code>cbind</code> will do
it. (The component scores are seven columns, so
<code>bind_cols</code> won’t do it unless you are careful.):</p>
<div class="sourceCode" id="cb3424"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb3424-1"><a href="principal-components-and-factor-analysis.html#cb3424-1"></a><span class="kw">cbind</span>(air, air<span class="fl">.1</span><span class="op">$</span>scores) <span class="op">%&gt;%</span><span class="st">  </span></span>
<span id="cb3424-2"><a href="principal-components-and-factor-analysis.html#cb3424-2"></a><span class="st">  </span><span class="kw">mutate</span>(<span class="dt">row =</span> <span class="kw">row_number</span>()) -&gt;<span class="st"> </span>d</span>
<span id="cb3424-3"><a href="principal-components-and-factor-analysis.html#cb3424-3"></a><span class="kw">head</span>(d)</span></code></pre></div>
<p>This is probably the easiest way, but you see that there is a mixture
of base R and Tidyverse. The result is actually a base R <code>data.frame</code>, so displaying it will display <em>all</em> of it, hence my use of <code>head</code>.
If you want to do it the all-Tidyverse
way
<label for="tufte-mn-271" class="margin-toggle">⊕</label><input type="checkbox" id="tufte-mn-271" class="margin-toggle"><span class="marginnote">There really ought to be a radio station <em>CTDY: All Tidyverse, All The Time</em>.</span>
then you need to bear in mind that <code>bind_cols</code> <em>only</em>
accepts vectors or data frames, not matrices, so a bit of care is needed first:</p>
<div class="sourceCode" id="cb3425"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb3425-1"><a href="principal-components-and-factor-analysis.html#cb3425-1"></a>air<span class="fl">.1</span><span class="op">$</span>scores <span class="op">%&gt;%</span></span>
<span id="cb3425-2"><a href="principal-components-and-factor-analysis.html#cb3425-2"></a><span class="st">  </span><span class="kw">as_tibble</span>() <span class="op">%&gt;%</span></span>
<span id="cb3425-3"><a href="principal-components-and-factor-analysis.html#cb3425-3"></a><span class="st">  </span><span class="kw">bind_cols</span>(air) <span class="op">%&gt;%</span></span>
<span id="cb3425-4"><a href="principal-components-and-factor-analysis.html#cb3425-4"></a><span class="st">  </span><span class="kw">mutate</span>(<span class="dt">row =</span> <span class="kw">row_number</span>()) -&gt;<span class="st"> </span>dd</span>
<span id="cb3425-5"><a href="principal-components-and-factor-analysis.html#cb3425-5"></a>dd</span></code></pre></div>
<p>I think the best way to think about this is to start with what is
farthest from being a data frame or a vector (the matrix of principal
component scores, here), bash that into shape first, and then glue the
rest of the things to it.</p>
<p>Note that we used all Tidyverse stuff here, so the result is a
<code>tibble</code>, and displaying it for me displays the first ten rows as
you’d expect. (This may be different in an R Notebook, since I think
there you get the first ten rows anyway.)</p>
<ol start="8" style="list-style-type: lower-alpha">
<li>Display the row of your new data frame for the observation
with the smallest (most negative) score on component 1. Which row is
this? What makes this observation have the most negative score on
component 1?</li>
</ol>
<p>Solution</p>
<p>I think the best strategy is to sort by component 1 score (in the default ascending order), and then display the first row:</p>
<div class="sourceCode" id="cb3426"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb3426-1"><a href="principal-components-and-factor-analysis.html#cb3426-1"></a>d <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">arrange</span>(Comp<span class="fl">.1</span>) <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">slice</span>(<span class="dv">1</span>)</span></code></pre></div>
<p>It’s row 8.</p>
<p>We said earlier that component 1 depends negatively on carbon monoxide
and nitrogen dioxide, so that an observation that is <em>low</em> on
component 1 should be <em>high</em> on these things.
<label for="tufte-mn-272" class="margin-toggle">⊕</label><input type="checkbox" id="tufte-mn-272" class="margin-toggle"><span class="marginnote">You might have said that component 1 depended on other things as well, in which case you ought to consider whether observation 8 is, as appropriate, high or low on these as well.</span></p>
<p>So are these values high or low? That was the reason for having you
make the five-number summary <a href="#part:fivenum">here</a>. For
observation 8, <code>CO</code> is 6 and <code>NO2</code> is 21; looking back
at the five-number summary, the value of <code>CO</code> is above Q3, and
the value of <code>NO2</code> is the highest of all. So this is entirely
what we’d expect.</p>
<ol style="list-style-type: lower-roman">
<li>Which observation has the lowest (most negative) value on
component 2? Which variables ought to be high or low for this
observation? Are they? Explain briefly.</li>
</ol>
<p>Solution</p>
<p>This is a repeat of the ideas we just saw:</p>
<div class="sourceCode" id="cb3427"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb3427-1"><a href="principal-components-and-factor-analysis.html#cb3427-1"></a>d <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">arrange</span>(Comp<span class="fl">.2</span>) <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">slice</span>(<span class="dv">1</span>)</span></code></pre></div>
<p>and for convenience, we’ll grab the quantiles again:</p>
<div class="sourceCode" id="cb3428"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb3428-1"><a href="principal-components-and-factor-analysis.html#cb3428-1"></a>air <span class="op">%&gt;%</span><span class="st"> </span></span>
<span id="cb3428-2"><a href="principal-components-and-factor-analysis.html#cb3428-2"></a><span class="st">  </span><span class="kw">summarize</span>(<span class="kw">across</span>(<span class="kw">everything</span>(), <span class="op">~</span><span class="kw">quantile</span>(.)))</span></code></pre></div>
<p>Day 34 (at the end of the line). We said that component 2 depends (negatively) on solar
radiation and ozone and possibly positively on nitric oxide. This
means that day 34 ought to be <em>high</em> on the first two and low on
the last one (since it’s at the low end of component 2). Solar
radiation is, surprisingly, close to the median (75), but ozone, 24,
is very near the highest, and nitric oxide, 1, is one of a large
number of values equal to the lowest. So day 34 is pointing the right
way, even if its variable values are not quite what you’d expect.
This business about figuring out whether values on variables are high
or low is kind of fiddly, since you have to refer back to the
five-number summary to see where the values for a particular
observation come. Another way to approach this is to calculate
<em>percentile ranks</em> for everything. Let’s go back to our original data frame and replace everything with its percent rank:</p>
<div class="sourceCode" id="cb3429"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb3429-1"><a href="principal-components-and-factor-analysis.html#cb3429-1"></a>air <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">mutate</span>(<span class="kw">across</span>(<span class="kw">everything</span>(), <span class="op">~</span><span class="st"> </span><span class="kw">percent_rank</span>(.))) -&gt;<span class="st"> </span>pct_rank</span>
<span id="cb3429-2"><a href="principal-components-and-factor-analysis.html#cb3429-2"></a>pct_rank</span></code></pre></div>
<p>Observation 34 is row 34 of this:</p>
<div class="sourceCode" id="cb3430"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb3430-1"><a href="principal-components-and-factor-analysis.html#cb3430-1"></a>pct_rank <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">slice</span>(<span class="dv">34</span>)</span></code></pre></div>
<p>Very high on ozone, (joint) lowest on nitric oxide, but middling on
solar radiation.
The one we looked at before, observation 8, is this:</p>
<div class="sourceCode" id="cb3431"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb3431-1"><a href="principal-components-and-factor-analysis.html#cb3431-1"></a>pct_rank <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">slice</span>(<span class="dv">8</span>)</span></code></pre></div>
<p>High on carbon monoxide, the highest on nitrogen dioxide.</p>
<ol start="10" style="list-style-type: lower-alpha">
<li>Obtain a biplot, with the row numbers labelled, and explain briefly how your conclusions from the previous two parts are consistent with it.</li>
</ol>
<p>Solution</p>
<div class="sourceCode" id="cb3432"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb3432-1"><a href="principal-components-and-factor-analysis.html#cb3432-1"></a><span class="kw">ggbiplot</span>(air<span class="fl">.1</span>, <span class="dt">labels =</span> d<span class="op">$</span>row)</span></code></pre></div>
<p><img src="pasias_files/figure-html/unnamed-chunk-2116-1.png" width="672"  /></p>
<p>Day 8 is way over on the left. The things that point in the direction
of observation 8 (<code>NO2, CO</code> and to a lesser extent <code>NO</code>
and <code>HC</code>) are the things that observation 8 is high on. On the
other hand, observation 8 is around the middle of the arrows for
<code>wind</code>, <code>solar.radiation</code> and <code>O3</code>, so that day
is not especially remarkable for those.</p>
<p>Observation 34 is
nearest the bottom, so we’d expect it to be high on ozone (yes), high
on solar radiation (no), low on nitric oxide (since that points the
most upward, yes) and also maybe low on wind, since observation 34 is
at the “back end” of that arrow. Wind is 6, which is at the first
quartile, low indeed.</p>
<p>The other thing that you see from the biplot is that there are four
variables pointing more or less up and to the left, and at right
angles to them, three other variables pointing up-and-right or
down-and-left. You could imagine rotating those arrows so that the
group of 4 point upwards, and the other three point left and
right. This is what factor analysis does, so you might imagine that
this technique might give a clearer picture of which variables belong
in which factor than principal components does. Hence what follows.</p>
<ol start="11" style="list-style-type: lower-alpha">
<li>Run a factor analysis on the same data, obtaining two factors. Look at the factor loadings. Is it clearer which variables belong to which factor, compared to the principal components analysis? Explain briefly.</li>
</ol>
<p>Solution</p>
<div class="sourceCode" id="cb3433"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb3433-1"><a href="principal-components-and-factor-analysis.html#cb3433-1"></a>air<span class="fl">.2</span> &lt;-<span class="st"> </span><span class="kw">factanal</span>(air, <span class="dv">2</span>, <span class="dt">scores =</span> <span class="st">&quot;r&quot;</span>)</span>
<span id="cb3433-2"><a href="principal-components-and-factor-analysis.html#cb3433-2"></a>air<span class="fl">.2</span><span class="op">$</span>loadings</span></code></pre></div>
<pre><code>## 
## Loadings:
##                 Factor1 Factor2
## wind            -0.176  -0.249 
## solar.radiation          0.319 
## CO               0.797   0.391 
## NO               0.692  -0.152 
## NO2              0.602   0.152 
## O3                       0.997 
## HC               0.251   0.147 
## 
##                Factor1 Factor2
## SS loadings      1.573   1.379
## Proportion Var   0.225   0.197
## Cumulative Var   0.225   0.422</code></pre>
<p>I got the factor scores since I’m going to look at a biplot
shortly. If you aren’t, you don’t need them.</p>
<p>Factor 1 is rather more clearly carbon monoxide, nitric oxide and
nitrogen dioxide. Factor 2 is mostly ozone, with a bit of solar
radiation and carbon monoxide. I’d say this is clearer than before.</p>
<p>A biplot would tell us whether the variables are better aligned with
the axes now:</p>
<div class="sourceCode" id="cb3435"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb3435-1"><a href="principal-components-and-factor-analysis.html#cb3435-1"></a><span class="kw">biplot</span>(air<span class="fl">.2</span><span class="op">$</span>scores, air<span class="fl">.2</span><span class="op">$</span>loadings)</span></code></pre></div>
<p><img src="pasias_files/figure-html/unnamed-chunk-2118-1.png" width="672"  /></p>
<p>At least somewhat. Ozone points straight up, since it is the dominant part of factor 2 and not part of factor 1 at all. Carbon monoxide and the two oxides of nitrogen point to the right.</p>
<p>Extra:
<code>wind</code>, <code>solar.radiation</code> and <code>HC</code> don’t appear
in either of our factors, which also shows up here:</p>
<div class="sourceCode" id="cb3436"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb3436-1"><a href="principal-components-and-factor-analysis.html#cb3436-1"></a>air<span class="fl">.2</span><span class="op">$</span>uniquenesses</span></code></pre></div>
<pre><code>##            wind solar.radiation              CO              NO             NO2              O3 
##       0.9070224       0.8953343       0.2126417       0.4983564       0.6144170       0.0050000 
##              HC 
##       0.9152467</code></pre>
<p>Those variables all have <em>high</em> uniquenesses.</p>
<p>What with the high uniquenesses, and the fact that two factors explain
only 42% of the variability, we
really ought to look at 3 factors, the same way that we said we should look at
3 components:</p>
<div class="sourceCode" id="cb3438"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb3438-1"><a href="principal-components-and-factor-analysis.html#cb3438-1"></a>air<span class="fl">.3</span> &lt;-<span class="st"> </span><span class="kw">factanal</span>(air, <span class="dv">3</span>)</span>
<span id="cb3438-2"><a href="principal-components-and-factor-analysis.html#cb3438-2"></a>air<span class="fl">.3</span><span class="op">$</span>loadings</span></code></pre></div>
<pre><code>## 
## Loadings:
##                 Factor1 Factor2 Factor3
## wind                    -0.210  -0.334 
## solar.radiation          0.318         
## CO               0.487   0.318   0.507 
## NO               0.238  -0.269   0.931 
## NO2              0.989                 
## O3                       0.987   0.124 
## HC               0.427   0.103   0.172 
## 
##                Factor1 Factor2 Factor3
## SS loadings      1.472   1.312   1.288
## Proportion Var   0.210   0.187   0.184
## Cumulative Var   0.210   0.398   0.582</code></pre>
<p>In case you are wondering, <code>factanal</code> automatically uses the
correlation matrix, and so takes care of variables measured on
different scales without our having to worry about that.</p>
<p>The rotation has only helped somewhat here. Factor 1 is mainly
<code>NO2</code> with some influence of <code>CO</code> and <code>HC</code>;
factor 2 is mainly ozone (with a bit of solar radiation and carbon monoxide),
and factor 3 is mainly <code>NO</code> with a bit of <code>CO</code>.</p>
<p>I think I mentioned most of the variables in there, so the uniquenesses
should not be too bad:</p>
<div class="sourceCode" id="cb3440"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb3440-1"><a href="principal-components-and-factor-analysis.html#cb3440-1"></a>air<span class="fl">.3</span><span class="op">$</span>uniquenesses</span></code></pre></div>
<pre><code>##            wind solar.radiation              CO              NO             NO2              O3 
##       0.8404417       0.8905074       0.4046425       0.0050000       0.0050000       0.0050000 
##              HC 
##       0.7776557</code></pre>
<p>Well, not great: <code>wind</code> and <code>solar.radiation</code> still have
high uniquenesses because they are not <em>strongly</em> part of any
factors.</p>
<p>If you wanted to, you could obtain the factor scores for the 3-factor
solution, and plot them on a three-dimensional plot using
<code>rgl</code>, rotating them to see the structure. A three dimensional
“biplot”
<label for="tufte-mn-273" class="margin-toggle">⊕</label><input type="checkbox" id="tufte-mn-273" class="margin-toggle"><span class="marginnote">A three-dimensional biplot ought to be called a <em>triplot</em>.</span>
would also be a cool thing to look at.</p>
</div>
<div id="a-correlation-matrix" class="section level2" number="29.3">
<h2><span class="header-section-number">29.3</span> A correlation matrix</h2>
<p>Here is a correlation matrix between five variables. This
correlation matrix was based on <span class="math inline">\(n=50\)</span> observations. Save the data
into a file.</p>
<pre><code>
1.00 0.90 -0.40 0.28 -0.05
0.90 1.00 -0.60 0.43 -0.20
-0.40 -0.60 1.00 -0.80 0.40
0.28 0.43 -0.80 1.00 -0.70
-0.05 -0.20 0.40 -0.70 1.00
</code></pre>
<ol style="list-style-type: lower-alpha">
<li>Read in the data, using <code>col_names=F</code> (why?). Check that you
have five variables with names invented by R.</li>
</ol>
<p>Solution</p>
<p>I saved my data into <code>cov5.txt</code>,
<label for="tufte-mn-274" class="margin-toggle">⊕</label><input type="checkbox" id="tufte-mn-274" class="margin-toggle"><span class="marginnote">Not to be confused with <em>covfefe</em>.</span> delimited by single spaces, so:</p>
<div class="sourceCode" id="cb3443"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb3443-1"><a href="principal-components-and-factor-analysis.html#cb3443-1"></a>corr &lt;-<span class="st"> </span><span class="kw">read_delim</span>(<span class="st">&quot;cov5.txt&quot;</span>, <span class="st">&quot; &quot;</span>, <span class="dt">col_names =</span> F)</span></code></pre></div>
<pre><code>## 
## ── Column specification ──────────────────────────────────────────────────────────────────────────────────────
## cols(
##   X1 = col_double(),
##   X2 = col_double(),
##   X3 = col_double(),
##   X4 = col_double(),
##   X5 = col_double()
## )</code></pre>
<div class="sourceCode" id="cb3445"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb3445-1"><a href="principal-components-and-factor-analysis.html#cb3445-1"></a>corr</span></code></pre></div>
<p>I needed to say that I have no variable names and I want R
to provide some. As you see, it did: <code>X1</code> through
<code>X5</code>. You can also supply your own names in this fashion:</p>
<div class="sourceCode" id="cb3446"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb3446-1"><a href="principal-components-and-factor-analysis.html#cb3446-1"></a>my_names &lt;-<span class="st"> </span><span class="kw">c</span>(<span class="st">&quot;first&quot;</span>, <span class="st">&quot;second&quot;</span>, <span class="st">&quot;third&quot;</span>, <span class="st">&quot;fourth&quot;</span>, <span class="st">&quot;fifth&quot;</span>)</span>
<span id="cb3446-2"><a href="principal-components-and-factor-analysis.html#cb3446-2"></a>corr2 &lt;-<span class="st"> </span><span class="kw">read_delim</span>(<span class="st">&quot;cov5.txt&quot;</span>, <span class="st">&quot; &quot;</span>, <span class="dt">col_names =</span> my_names)</span></code></pre></div>
<pre><code>## 
## ── Column specification ──────────────────────────────────────────────────────────────────────────────────────
## cols(
##   first = col_double(),
##   second = col_double(),
##   third = col_double(),
##   fourth = col_double(),
##   fifth = col_double()
## )</code></pre>
<div class="sourceCode" id="cb3448"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb3448-1"><a href="principal-components-and-factor-analysis.html#cb3448-1"></a>corr2</span></code></pre></div>
<ol start="2" style="list-style-type: lower-alpha">
<li>Run a principal components analysis from this correlation matrix.</li>
</ol>
<p>Solution</p>
<p>Two lines, these:</p>
<div class="sourceCode" id="cb3449"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb3449-1"><a href="principal-components-and-factor-analysis.html#cb3449-1"></a>corr.mat &lt;-<span class="st"> </span><span class="kw">as.matrix</span>(corr)</span>
<span id="cb3449-2"><a href="principal-components-and-factor-analysis.html#cb3449-2"></a>corr<span class="fl">.1</span> &lt;-<span class="st"> </span><span class="kw">princomp</span>(<span class="dt">covmat =</span> corr.mat)</span></code></pre></div>
<p>Or do it in one step as</p>
<div class="sourceCode" id="cb3450"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb3450-1"><a href="principal-components-and-factor-analysis.html#cb3450-1"></a>corr<span class="fl">.1</span>a &lt;-<span class="st"> </span><span class="kw">princomp</span>(<span class="kw">as.matrix</span>(corr))</span></code></pre></div>
<p>if you like, but I think it’s less clear what’s going on.</p>
<ol start="3" style="list-style-type: lower-alpha">
<li><a name="part:howmany">*</a> Obtain a scree plot. Can you justify
the use of two components (later, factors), bearing in mind that we
have only five variables?</li>
</ol>
<p>Solution</p>
<div class="sourceCode" id="cb3451"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb3451-1"><a href="principal-components-and-factor-analysis.html#cb3451-1"></a><span class="kw">ggscreeplot</span>(corr<span class="fl">.1</span>)</span></code></pre></div>
<p><img src="pasias_files/figure-html/sdljhljsahja-1.png" width="672"  /></p>
<p>There is kind of an elbow at 3, which would suggest two components/factors.
<label for="tufte-mn-275" class="margin-toggle">⊕</label><input type="checkbox" id="tufte-mn-275" class="margin-toggle"><span class="marginnote">There is also kind of an elbow at 4, which would suggest three factors, but that’s really too many with only 5 variables. That wouldn’t be much of a <em>reduction</em> in the number of variables, which is what principal components is trying to achieve.</span></p>
<p>You can also use the eigenvalue-bigger-than-1 thing:</p>
<div class="sourceCode" id="cb3452"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb3452-1"><a href="principal-components-and-factor-analysis.html#cb3452-1"></a><span class="kw">summary</span>(corr<span class="fl">.1</span>)</span></code></pre></div>
<pre><code>## Importance of components:
##                           Comp.1    Comp.2     Comp.3     Comp.4    Comp.5
## Standard deviation     1.7185460 1.1686447 0.70207741 0.36584870 0.2326177
## Proportion of Variance 0.5906801 0.2731461 0.09858254 0.02676905 0.0108222
## Cumulative Proportion  0.5906801 0.8638262 0.96240875 0.98917780 1.0000000</code></pre>
<p>Only the first
<em>two</em> eigenvalues are bigger than 1, and the third is quite a bit
smaller. So this would suggest two factors also. The third eigenvalue
is in that kind of nebulous zone between between being big and being
small, and the percent of variance explained is also ambiguous: is
86% good enough or should I go for 96%? These questions rarely have
good answers. But an issue is that you want to summarize your
variables with a (much) smaller number of factors; with 5 variables,
having two factors rather than more than two seems to be a way of
gaining some insight.</p>
<ol start="4" style="list-style-type: lower-alpha">
<li>Take a look at the first two component loadings. Which variables appear
to feature in which component? Do they have a positive or negative effect?</li>
</ol>
<p>Solution</p>
<div class="sourceCode" id="cb3454"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb3454-1"><a href="principal-components-and-factor-analysis.html#cb3454-1"></a>corr<span class="fl">.1</span><span class="op">$</span>loadings</span></code></pre></div>
<pre><code>## 
## Loadings:
##    Comp.1 Comp.2 Comp.3 Comp.4 Comp.5
## X1  0.404  0.571  0.287  0.363  0.545
## X2  0.482  0.439  0.144 -0.363 -0.650
## X3 -0.501  0.122  0.652  0.412 -0.375
## X4  0.490 -0.390 -0.171  0.689 -0.323
## X5 -0.338  0.561 -0.665  0.304 -0.189
## 
##                Comp.1 Comp.2 Comp.3 Comp.4 Comp.5
## SS loadings       1.0    1.0    1.0    1.0    1.0
## Proportion Var    0.2    0.2    0.2    0.2    0.2
## Cumulative Var    0.2    0.4    0.6    0.8    1.0</code></pre>
<p>This is messy.</p>
<p>In the first component, the loadings are all about the
same in size, but the ones for <code>X3</code> and <code>X5</code> are
negative and the rest are positive. Thus, component 1 is contrasting
<code>X3</code> and <code>X5</code> with the others.</p>
<p>In the second component, the emphasis is on <code>X1</code>, <code>X2</code>
and <code>X5</code>, all with negative loadings, and possibly <code>X4</code>,
with a positive loading.</p>
<p>Note that the first component is basically “size”, since the
component loadings are all almost equal in absolute value. This often
happens in principal components; for example, it also happened with
the running records in class.</p>
<p>I hope the factor analysis, with its rotation, will straighten things
out some.</p>
<ol start="5" style="list-style-type: lower-alpha">
<li>Create a “covariance list” (for the purposes of
performing a factor analysis on the correlation matrix).</li>
</ol>
<p>Solution</p>
<p>This is about the most direct way:</p>
<div class="sourceCode" id="cb3456"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb3456-1"><a href="principal-components-and-factor-analysis.html#cb3456-1"></a>corr.list &lt;-<span class="st"> </span><span class="kw">list</span>(<span class="dt">cov =</span> corr.mat, <span class="dt">n.obs =</span> <span class="dv">50</span>)</span></code></pre></div>
<p>recalling that there were 50 observations. The idea is that we feed
this into <code>factanal</code> instead of the correlation matrix, so that
the factor analysis knows how many individuals there were (for testing
and such).</p>
<p>Note that you need the correlation matrix <em>as a <code>matrix</code></em>,
not as a data frame. If you ran the <code>princomp</code> all in one step,
you’ll have to create the correlation matrix again, for example like this:</p>
<div class="sourceCode" id="cb3457"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb3457-1"><a href="principal-components-and-factor-analysis.html#cb3457-1"></a>corr.list2 &lt;-<span class="st"> </span><span class="kw">list</span>(<span class="dt">cov =</span> <span class="kw">as.matrix</span>(corr), <span class="dt">n.obs =</span> <span class="dv">50</span>)</span></code></pre></div>
<p>The actual list looks like this:</p>
<div class="sourceCode" id="cb3458"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb3458-1"><a href="principal-components-and-factor-analysis.html#cb3458-1"></a>corr.list</span></code></pre></div>
<pre><code>## $cov
##         X1    X2   X3    X4    X5
## [1,]  1.00  0.90 -0.4  0.28 -0.05
## [2,]  0.90  1.00 -0.6  0.43 -0.20
## [3,] -0.40 -0.60  1.0 -0.80  0.40
## [4,]  0.28  0.43 -0.8  1.00 -0.70
## [5,] -0.05 -0.20  0.4 -0.70  1.00
## 
## $n.obs
## [1] 50</code></pre>
<p>An R list is a collection of things <em>not all of the same type</em>,
here a matrix and a number, and is a handy way of keeping a bunch of
connected things together. You use the same dollar-sign notation as
for a data frame to
access the things in a list:</p>
<div class="sourceCode" id="cb3460"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb3460-1"><a href="principal-components-and-factor-analysis.html#cb3460-1"></a>corr.list<span class="op">$</span>n.obs</span></code></pre></div>
<pre><code>## [1] 50</code></pre>
<p>and logically this is because, to R, a data frame <em>is</em> a special
kind of a list, so anything that works for a list also works for a
data frame, plus some extra things besides.
<label for="tufte-mn-276" class="margin-toggle">⊕</label><input type="checkbox" id="tufte-mn-276" class="margin-toggle"><span class="marginnote">In computer science terms, a data frame is said to <strong>inherit</strong> from a list: it is a list plus extra stuff.</span></p>
<p>The same idea applies to extracting things from the output of a
regression (with <code>lm</code>) or something like a <code>t.test</code>: the
output from those is also a list. But for those, I like <code>tidy</code>
from <code>broom</code> better.</p>
<ol start="6" style="list-style-type: lower-alpha">
<li>Carry out a factor analysis with two factors. We’ll
investigate the bits of it in a
moment.</li>
</ol>
<p>Solution</p>
<div class="sourceCode" id="cb3462"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb3462-1"><a href="principal-components-and-factor-analysis.html#cb3462-1"></a>corr<span class="fl">.2</span> &lt;-<span class="st"> </span><span class="kw">factanal</span>(<span class="dt">factors =</span> <span class="dv">2</span>, <span class="dt">covmat =</span> corr.list)</span></code></pre></div>
<ol start="7" style="list-style-type: lower-alpha">
<li><a name="part:load">*</a> Look at the factor loadings. Describe how the factors are
related to the original variables. Is the interpretation clearer
than for the principal components analysis?</li>
</ol>
<p>Solution</p>
<div class="sourceCode" id="cb3463"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb3463-1"><a href="principal-components-and-factor-analysis.html#cb3463-1"></a>corr<span class="fl">.2</span><span class="op">$</span>loadings</span></code></pre></div>
<pre><code>## 
## Loadings:
##      Factor1 Factor2
## [1,]          0.905 
## [2,] -0.241   0.968 
## [3,]  0.728  -0.437 
## [4,] -0.977   0.201 
## [5,]  0.709         
## 
##                Factor1 Factor2
## SS loadings      2.056   1.987
## Proportion Var   0.411   0.397
## Cumulative Var   0.411   0.809</code></pre>
<p>Oh yes, this is a lot clearer. Factor 1 is variables 3 and 5
contrasted with variable 4; factor 2 is variables 1 and 2. No
hand-waving required.</p>
<p>Perhaps now is a good time to look back at the correlation matrix and
see why the factor analysis came out this way:</p>
<div class="sourceCode" id="cb3465"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb3465-1"><a href="principal-components-and-factor-analysis.html#cb3465-1"></a>corr</span></code></pre></div>
<p>Variable <code>X1</code> is highly correlated with <code>X2</code> but not
really any of the others. Likewise variables <code>X3, X4, X5</code> are
more or less highly correlated among themselves but not with the
others (<code>X2</code> and <code>X3</code> being an exception, but the big
picture is as I described). So variables that appear in the same
factor should be highly correlated with each other and not with
variables that are in different factors. But it took the factor
analysis to really show this up.</p>
<ol start="8" style="list-style-type: lower-alpha">
<li>Look at the uniquenesses. Are there any that are unusually
high? Does that surprise you, given your answer to
(<a href="#part:load">here</a>)? (You will probably have to make a judgement call here.)</li>
</ol>
<p>Solution</p>
<div class="sourceCode" id="cb3466"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb3466-1"><a href="principal-components-and-factor-analysis.html#cb3466-1"></a>corr<span class="fl">.2</span><span class="op">$</span>uniquenesses</span></code></pre></div>
<pre><code>##        X1        X2        X3        X4        X5 
## 0.1715682 0.0050000 0.2789445 0.0050000 0.4961028</code></pre>
<p>The ones for <code>X3</code> and <code>X5</code> are higher than the rest;
this is because their loadings on factor 1 are lower than the
rest. Since those loadings are still high, I wouldn’t be worried about
the uniquenesses.</p>
<p>The point here is that an (excessively) high uniqueness indicates a
variable that doesn’t appear in <em>any</em> factor. The easy link to
make is “all the variables appear in a factor, so there shouldn’t be any very high uniquenesses”. If, say, <code>X3</code> doesn’t have a high
loading on any factor, <code>X3</code> would have a high uniqueness (like
0.9, and none of these values approach that).</p>
</div>
<div id="the-interpersonal-circumplex" class="section level2" number="29.4">
<h2><span class="header-section-number">29.4</span> The Interpersonal Circumplex</h2>
<p>The “IPIP Interpersonal Circumplex” (see
<a href="http://ipip.ori.org/newIPIP-IPCSurvey.htm">link</a>) is a personal
behaviour survey, where respondents have to rate how accurately a
number of statements about behaviour apply to them, on a scale from
1 (“very inaccurate”) to 5 (“very accurate”). A survey was done
on 459 people, using a 44-item variant of the above questionnaire,
where the statements were as follows. Put an “I” or an “I am” in
front of each one:</p>
<ul>
<li><p>talkative</p></li>
<li><p>find fault</p></li>
<li><p>do a thorough job</p></li>
<li><p>depressed</p></li>
<li><p>original</p></li>
<li><p>reserved</p></li>
<li><p>helpful</p></li>
<li><p>careless</p></li>
<li><p>relaxed</p></li>
<li><p>curious</p></li>
<li><p>full of energy</p></li>
<li><p>start quarrels</p></li>
<li><p>reliable</p></li>
<li><p>tense</p></li>
<li><p>ingenious</p></li>
<li><p>generate enthusiasm in others</p></li>
<li><p>forgiving</p></li>
<li><p>disorganized</p></li>
<li><p>worry</p></li>
<li><p>imaginative</p></li>
<li><p>quiet</p></li>
<li><p>trusting</p></li>
<li><p>lazy</p></li>
<li><p>emotionally stable</p></li>
<li><p>inventive</p></li>
<li><p>assertive</p></li>
<li><p>cold and aloof</p></li>
<li><p>persevere</p></li>
<li><p>moody</p></li>
<li><p>value artistic experiences</p></li>
<li><p>shy</p></li>
<li><p>considerate</p></li>
<li><p>efficient</p></li>
<li><p>calm in tense situations</p></li>
<li><p>prefer routine work</p></li>
<li><p>outgoing</p></li>
<li><p>sometimes rude</p></li>
<li><p>stick to plans</p></li>
<li><p>nervous</p></li>
<li><p>reflective</p></li>
<li><p>have few artistic interests</p></li>
<li><p>co-operative</p></li>
<li><p>distractible</p></li>
<li><p>sophisticated in art and music</p></li>
</ul>
<p>I don’t know what a “circumplex” is, but I know it’s not one of those “hat” accents that they have in French.
The data are in
<a href="http://www.utsc.utoronto.ca/~butler/d29/personality.txt">link</a>. The
columns <code>PERS01</code> through <code>PERS44</code> represent the above traits.</p>
<ol style="list-style-type: lower-alpha">
<li>Read in the data and check that you have the right number
of rows and columns.</li>
</ol>
<p>Solution</p>
<p>Separated by single spaces.</p>
<div class="sourceCode" id="cb3468"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb3468-1"><a href="principal-components-and-factor-analysis.html#cb3468-1"></a>my_url &lt;-<span class="st"> &quot;http://www.utsc.utoronto.ca/~butler/d29/personality.txt&quot;</span></span>
<span id="cb3468-2"><a href="principal-components-and-factor-analysis.html#cb3468-2"></a>pers &lt;-<span class="st"> </span><span class="kw">read_delim</span>(my_url, <span class="st">&quot; &quot;</span>)</span></code></pre></div>
<pre><code>## 
## ── Column specification ──────────────────────────────────────────────────────────────────────────────────────
## cols(
##   .default = col_double()
## )
## ℹ Use `spec()` for the full column specifications.</code></pre>
<div class="sourceCode" id="cb3470"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb3470-1"><a href="principal-components-and-factor-analysis.html#cb3470-1"></a>pers</span></code></pre></div>
<p>Yep, 459 people (in rows), and 44 items (in columns), plus one column
of <code>id</code>s for the people who took the survey.</p>
<p>In case you were wondering about the “I” vs. “I am” thing, the
story seems to be that each behaviour needs to have a verb. If the
behaviour has a verb, “I” is all you need, but if it doesn’t, you
have to add one, ie. “I am”.</p>
<p>Another thing you might be concerned about is whether these data are
“tidy” or not. To some extent, it depends on what you are going to
do with it. You could say that the <code>PERS</code> columns are all
survey-responses, just to different questions, and you might think of
doing something like this:</p>
<div class="sourceCode" id="cb3471"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb3471-1"><a href="principal-components-and-factor-analysis.html#cb3471-1"></a>pers <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">pivot_longer</span>(<span class="op">-</span>id, <span class="dt">names_to=</span><span class="st">&quot;item&quot;</span>, <span class="dt">values_to=</span><span class="st">&quot;response&quot;</span>)</span></code></pre></div>
<p>to get a <em>really</em> long and skinny data frame. It all depends on
what you are doing with it. Long-and-skinny is ideal if you are going
to summarize the responses by survey item, or draw something like bar
charts of responses facetted by item:</p>
<div class="sourceCode" id="cb3472"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb3472-1"><a href="principal-components-and-factor-analysis.html#cb3472-1"></a>pers <span class="op">%&gt;%</span></span>
<span id="cb3472-2"><a href="principal-components-and-factor-analysis.html#cb3472-2"></a><span class="st">  </span><span class="kw">pivot_longer</span>(<span class="op">-</span>id, <span class="dt">names_to=</span><span class="st">&quot;item&quot;</span>, <span class="dt">values_to=</span><span class="st">&quot;response&quot;</span>) <span class="op">%&gt;%</span></span>
<span id="cb3472-3"><a href="principal-components-and-factor-analysis.html#cb3472-3"></a><span class="st">  </span><span class="kw">ggplot</span>(<span class="kw">aes</span>(<span class="dt">x =</span> response)) <span class="op">+</span><span class="st"> </span><span class="kw">geom_bar</span>() <span class="op">+</span><span class="st"> </span><span class="kw">facet_wrap</span>(<span class="op">~</span>item)</span></code></pre></div>
<pre><code>## Warning: Removed 371 rows containing non-finite values (stat_count).</code></pre>
<p><img src="pasias_files/figure-html/unnamed-chunk-2137-1.png" width="672"  /></p>
<p>The first time I did this, item <code>PERS36</code> appeared out of order
at the end, and I was wondering what happened, until I realized it was
actually misspelled as <code>PES36</code>! I corrected it in the data
file, and it should be good now (though I wonder how many years that
error persisted for).</p>
<p>For us, in this problem, though, we need the wide format.</p>
<ol start="2" style="list-style-type: lower-alpha">
<li>There are some missing values among these
responses. Eliminate all the individuals with any missing values
(since <code>princomp</code> can’t handle them).</li>
</ol>
<p>Solution</p>
<p>This is actually much easier than it was in the past.
A way of asking “are there any missing values anywhere?” is:</p>
<div class="sourceCode" id="cb3474"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb3474-1"><a href="principal-components-and-factor-analysis.html#cb3474-1"></a><span class="kw">any</span>(<span class="kw">is.na</span>(pers))</span></code></pre></div>
<pre><code>## [1] TRUE</code></pre>
<p>There are.
To remove them, just this:</p>
<div class="sourceCode" id="cb3476"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb3476-1"><a href="principal-components-and-factor-analysis.html#cb3476-1"></a>pers <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">drop_na</span>() -&gt;<span class="st"> </span>pers.ok</span></code></pre></div>
<p>Are there any missings left?</p>
<div class="sourceCode" id="cb3477"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb3477-1"><a href="principal-components-and-factor-analysis.html#cb3477-1"></a><span class="kw">any</span>(<span class="kw">is.na</span>(pers.ok))</span></code></pre></div>
<pre><code>## [1] FALSE</code></pre>
<p>Nope.
Extra: you might also have thought of the “tidy, remove, untidy”
strategy here. The trouble with that here is that you want to remove
<em>all</em> the observations for a subject who has <em>any</em> missing
ones. This is unlike the multidimensional scaling one where
we wanted to remove all the distances for two cities .</p>
<p>That gives me an idea, though.</p>
<div class="sourceCode" id="cb3479"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb3479-1"><a href="principal-components-and-factor-analysis.html#cb3479-1"></a>pers <span class="op">%&gt;%</span></span>
<span id="cb3479-2"><a href="principal-components-and-factor-analysis.html#cb3479-2"></a><span class="st">  </span><span class="kw">pivot_longer</span>(<span class="op">-</span>id, <span class="dt">names_to=</span><span class="st">&quot;item&quot;</span>, <span class="dt">values_to=</span><span class="st">&quot;rating&quot;</span>)</span></code></pre></div>
<p>To find out which <em>subjects</em> have any missing values, we can do a
<code>group_by</code> and <code>summarize</code> on <em>subjects</em> (that
means, the <code>id</code> column; the <code>PERS</code> in the column I
called <code>item</code> means “personality”, not “person”!). What do
we summarize? Any one of the standard things like <code>mean</code> will
return <code>NA</code> if the thing whose mean you are finding has any NA
values in it anywhere, and a number if it’s “complete”, so this kind
of thing, adding to my pipeline:</p>
<div class="sourceCode" id="cb3480"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb3480-1"><a href="principal-components-and-factor-analysis.html#cb3480-1"></a>pers <span class="op">%&gt;%</span></span>
<span id="cb3480-2"><a href="principal-components-and-factor-analysis.html#cb3480-2"></a><span class="st">  </span><span class="kw">pivot_longer</span>(<span class="op">-</span>id, <span class="dt">names_to=</span><span class="st">&quot;item&quot;</span>, <span class="dt">values_to=</span><span class="st">&quot;rating&quot;</span>) <span class="op">%&gt;%</span><span class="st"> </span></span>
<span id="cb3480-3"><a href="principal-components-and-factor-analysis.html#cb3480-3"></a><span class="st">  </span><span class="kw">group_by</span>(id) <span class="op">%&gt;%</span></span>
<span id="cb3480-4"><a href="principal-components-and-factor-analysis.html#cb3480-4"></a><span class="st">  </span><span class="kw">summarize</span>(<span class="dt">m =</span> <span class="kw">mean</span>(rating)) <span class="op">%&gt;%</span></span>
<span id="cb3480-5"><a href="principal-components-and-factor-analysis.html#cb3480-5"></a><span class="st">  </span><span class="kw">filter</span>(<span class="kw">is.na</span>(m))</span></code></pre></div>
<p>This is different from <code>drop_na</code>, which would remove any rows (of the long data frame) that have a missing response. This, though, is exactly what we <em>don’t</em> want, since we are trying to keep track of the subjects that have missing values.</p>
<p>Most of the subjects had an actual numerical mean here, whose value
we don’t care about; all we care about here is whether the mean is
missing, which implies that one (or more) of the responses was
missing.</p>
<p>So now we define a column <code>has_missing</code> that is true if the
subject has any missing values and false otherwise:</p>
<div class="sourceCode" id="cb3481"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb3481-1"><a href="principal-components-and-factor-analysis.html#cb3481-1"></a>pers <span class="op">%&gt;%</span></span>
<span id="cb3481-2"><a href="principal-components-and-factor-analysis.html#cb3481-2"></a><span class="st">  </span><span class="kw">pivot_longer</span>(<span class="op">-</span>id, <span class="dt">names_to=</span><span class="st">&quot;item&quot;</span>, <span class="dt">values_to=</span><span class="st">&quot;rating&quot;</span>) <span class="op">%&gt;%</span><span class="st"> </span></span>
<span id="cb3481-3"><a href="principal-components-and-factor-analysis.html#cb3481-3"></a><span class="st">  </span><span class="kw">group_by</span>(id) <span class="op">%&gt;%</span></span>
<span id="cb3481-4"><a href="principal-components-and-factor-analysis.html#cb3481-4"></a><span class="st">  </span><span class="kw">summarize</span>(<span class="dt">m =</span> <span class="kw">mean</span>(rating)) <span class="op">%&gt;%</span></span>
<span id="cb3481-5"><a href="principal-components-and-factor-analysis.html#cb3481-5"></a><span class="st">  </span><span class="kw">mutate</span>(<span class="dt">has_missing =</span> <span class="kw">is.na</span>(m)) -&gt;<span class="st"> </span>pers.hm</span>
<span id="cb3481-6"><a href="principal-components-and-factor-analysis.html#cb3481-6"></a>pers.hm </span></code></pre></div>
<p>This data frame <code>pers.hm</code> has the same number of rows as the
original data frame <code>pers</code>, one per subject, so we can just
glue it onto the end of that:</p>
<div class="sourceCode" id="cb3482"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb3482-1"><a href="principal-components-and-factor-analysis.html#cb3482-1"></a>pers <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">bind_cols</span>(pers.hm)</span></code></pre></div>
<pre><code>## New names:
## * id -&gt; id...1
## * id -&gt; id...46</code></pre>
<p>and then filter out the rows for which <code>has_missing</code> is true.
What we did here is really a way of mimicking <code>complete.cases</code>,
which is the way we used to have to do it, before <code>drop_na</code>
came on the scene.</p>
<ol start="3" style="list-style-type: lower-alpha">
<li>Carry out a principal components analysis and obtain a
scree plot.</li>
</ol>
<p>Solution</p>
<p>This ought to be straightforward, but we’ve got to remember to
use only the columns with actual data in them: that is,
<code>PERS01</code> through <code>PERS44</code>:</p>
<div class="sourceCode" id="cb3484"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb3484-1"><a href="principal-components-and-factor-analysis.html#cb3484-1"></a>pers<span class="fl">.1</span> &lt;-<span class="st"> </span>pers.ok <span class="op">%&gt;%</span></span>
<span id="cb3484-2"><a href="principal-components-and-factor-analysis.html#cb3484-2"></a><span class="st">  </span><span class="kw">select</span>(<span class="kw">starts_with</span>(<span class="st">&quot;PERS&quot;</span>)) <span class="op">%&gt;%</span></span>
<span id="cb3484-3"><a href="principal-components-and-factor-analysis.html#cb3484-3"></a><span class="st">  </span><span class="kw">princomp</span>(<span class="dt">cor =</span> T)</span>
<span id="cb3484-4"><a href="principal-components-and-factor-analysis.html#cb3484-4"></a><span class="kw">ggscreeplot</span>(pers<span class="fl">.1</span>)</span></code></pre></div>
<p><img src="pasias_files/figure-html/saljhsajd-1.png" width="672"  /></p>
<ol start="4" style="list-style-type: lower-alpha">
<li>How many components/factors should you use? Explain briefly.</li>
</ol>
<p>Solution</p>
<p>I think the clearest elbow is at 7, so we should use 6
components/factors. You could make a case that the elbow at 6 is
also part of the scree, and therefore you should use 5
components/factors. Another one of those judgement calls.
Ignore the “backwards elbow” at 5: this is
definitely part of the mountain rather than the scree. Backwards
elbows, as you’ll recall, don’t count as elbows anyway.
When I drew this in R Studio, the elbow at 6 was clearer than
the one at 7, so I went with 5 components/factors below.
The other way to go is to take the number of eigenvalues bigger
than 1:</p>
<div class="sourceCode" id="cb3485"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb3485-1"><a href="principal-components-and-factor-analysis.html#cb3485-1"></a><span class="kw">summary</span>(pers<span class="fl">.1</span>)</span></code></pre></div>
<pre><code>## Importance of components:
##                           Comp.1     Comp.2     Comp.3     Comp.4     Comp.5    Comp.6     Comp.7     Comp.8
## Standard deviation     2.6981084 2.04738207 1.74372011 1.59610543 1.50114586 1.2627066 1.14816136 1.10615404
## Proportion of Variance 0.1654497 0.09526758 0.06910363 0.05789892 0.05121452 0.0362370 0.02996078 0.02780856
## Cumulative Proportion  0.1654497 0.26071732 0.32982096 0.38771988 0.43893440 0.4751714 0.50513218 0.53294074
##                            Comp.9    Comp.10    Comp.11    Comp.12    Comp.13    Comp.14    Comp.15
## Standard deviation     1.07405521 1.02180353 0.98309198 0.97514006 0.94861102 0.90832065 0.90680594
## Proportion of Variance 0.02621806 0.02372915 0.02196522 0.02161132 0.02045143 0.01875105 0.01868857
## Cumulative Proportion  0.55915880 0.58288795 0.60485317 0.62646449 0.64691592 0.66566698 0.68435554
##                           Comp.16    Comp.17    Comp.18    Comp.19   Comp.20    Comp.21    Comp.22    Comp.23
## Standard deviation     0.86798188 0.85762608 0.84515849 0.82819534 0.8123579 0.80910333 0.80435744 0.76594963
## Proportion of Variance 0.01712256 0.01671642 0.01623393 0.01558881 0.0149983 0.01487837 0.01470434 0.01333361
## Cumulative Proportion  0.70147810 0.71819452 0.73442845 0.75001726 0.7650156 0.77989393 0.79459827 0.80793188
##                           Comp.24    Comp.25    Comp.26    Comp.27   Comp.28    Comp.29    Comp.30    Comp.31
## Standard deviation     0.75946741 0.75434835 0.74494825 0.73105470 0.6956473 0.68327155 0.67765233 0.66847179
## Proportion of Variance 0.01310888 0.01293276 0.01261245 0.01214639 0.0109983 0.01061045 0.01043665 0.01015578
## Cumulative Proportion  0.82104076 0.83397352 0.84658597 0.85873236 0.8697307 0.88034111 0.89077776 0.90093355
##                            Comp.32     Comp.33     Comp.34     Comp.35     Comp.36     Comp.37     Comp.38
## Standard deviation     0.660473737 0.651473777 0.629487724 0.618765271 0.605892700 0.594231727 0.581419871
## Proportion of Variance 0.009914217 0.009645865 0.009005791 0.008701601 0.008343317 0.008025258 0.007682933
## Cumulative Proportion  0.910847763 0.920493629 0.929499420 0.938201021 0.946544338 0.954569596 0.962252530
##                            Comp.39     Comp.40     Comp.41     Comp.42     Comp.43     Comp.44
## Standard deviation     0.568951666 0.560084703 0.547059522 0.524949694 0.490608152 0.456010047
## Proportion of Variance 0.007356955 0.007129429 0.006801685 0.006263004 0.005470372 0.004726026
## Cumulative Proportion  0.969609484 0.976738913 0.983540598 0.989803602 0.995273974 1.000000000</code></pre>
<p>There are actually 10 of these. But if you look at the scree plot,
there really seems to be no reason to take 10 factors rather than,
say, 11 or 12. There are a lot of eigenvalues (standard deviations)
close to (but just below) 1, and no obvious “bargains” in terms of
variance explained: the “cumulative proportion” just keeps going
gradually up.</p>
<ol start="5" style="list-style-type: lower-alpha">
<li><a name="part:score">*</a> Using your preferred number of factors, run a factor
analysis. Obtain “r”-type factor scores, as in class. You don’t need to look at any output yet.</li>
</ol>
<p>Solution</p>
<p>I’m going to do the 5 factors that I preferred the first time I
looked at this. Don’t forget to grab only the appropriate
columns from <code>pers.ok</code>:</p>
<div class="sourceCode" id="cb3487"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb3487-1"><a href="principal-components-and-factor-analysis.html#cb3487-1"></a>pers.ok<span class="fl">.1</span> &lt;-<span class="st"> </span>pers.ok <span class="op">%&gt;%</span></span>
<span id="cb3487-2"><a href="principal-components-and-factor-analysis.html#cb3487-2"></a><span class="st">  </span><span class="kw">select</span>(<span class="kw">starts_with</span>(<span class="st">&quot;PERS&quot;</span>)) <span class="op">%&gt;%</span></span>
<span id="cb3487-3"><a href="principal-components-and-factor-analysis.html#cb3487-3"></a><span class="st">  </span><span class="kw">factanal</span>(<span class="dv">5</span>, <span class="dt">scores =</span> <span class="st">&quot;r&quot;</span>)</span></code></pre></div>
<p>If you think 6 is better, you should feel free to use that here.</p>
<ol start="6" style="list-style-type: lower-alpha">
<li>Obtain the factor loadings. How much of the variability
does your chosen number of factors explain?</li>
</ol>
<p>Solution</p>
<div class="sourceCode" id="cb3488"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb3488-1"><a href="principal-components-and-factor-analysis.html#cb3488-1"></a>pers.ok<span class="fl">.1</span><span class="op">$</span>loadings</span></code></pre></div>
<pre><code>## 
## Loadings:
##        Factor1 Factor2 Factor3 Factor4 Factor5
## PERS01  0.130   0.752           0.279         
## PERS02          0.199   0.202  -0.545         
## PERS03  0.677                   0.160   0.126 
## PERS04 -0.143  -0.239   0.528  -0.195         
## PERS05  0.191   0.258  -0.180   0.159   0.520 
## PERS06  0.104  -0.658   0.185  -0.143         
## PERS07  0.313   0.113           0.533   0.130 
## PERS08 -0.558           0.168  -0.173         
## PERS09                 -0.641           0.136 
## PERS10  0.149   0.169                   0.445 
## PERS11  0.106   0.282  -0.224  -0.107   0.271 
## PERS12 -0.157                  -0.404         
## PERS13  0.577                   0.331   0.126 
## PERS14                  0.685  -0.135         
## PERS15  0.133                           0.480 
## PERS16  0.106   0.481                   0.335 
## PERS17                          0.277   0.102 
## PERS18 -0.641                                 
## PERS19         -0.159   0.596   0.109         
## PERS20          0.215   0.103           0.498 
## PERS21         -0.805   0.121                 
## PERS22  0.153   0.175           0.533         
## PERS23 -0.622           0.121  -0.259         
## PERS24          0.135  -0.582           0.153 
## PERS25          0.176  -0.124           0.517 
## PERS26  0.144   0.515  -0.215  -0.260   0.244 
## PERS27         -0.205   0.136  -0.438         
## PERS28  0.623                   0.245   0.132 
## PERS29                  0.477  -0.231         
## PERS30                                  0.500 
## PERS31         -0.619   0.191                 
## PERS32  0.322                   0.553   0.134 
## PERS33  0.622                                 
## PERS34  0.105          -0.566                 
## PERS35         -0.180                  -0.161 
## PERS36          0.675  -0.146   0.118   0.107 
## PERS37 -0.300   0.134          -0.495         
## PERS38  0.521                           0.169 
## PERS39         -0.333   0.530                 
## PERS40                          0.162   0.585 
## PERS41                         -0.171  -0.326 
## PERS42  0.271   0.179           0.552   0.139 
## PERS43 -0.465           0.236  -0.174         
## PERS44                                  0.449 
## 
##                Factor1 Factor2 Factor3 Factor4 Factor5
## SS loadings      3.810   3.740   3.174   2.939   2.627
## Proportion Var   0.087   0.085   0.072   0.067   0.060
## Cumulative Var   0.087   0.172   0.244   0.311   0.370</code></pre>
<p>The Cumulative Var line at the bottom says that our five factors
together have
explained 37% of the variability. This is not great, but is the kind
of thing we have to live with in this kind of analysis (like the
personality one in class).</p>
<ol start="7" style="list-style-type: lower-alpha">
<li>Interpret each of your chosen number of factors. That is,
for each factor, identify the items that load heavily on it (you
can be fairly crude about this, eg. use a cutoff like 0.4 in
absolute value), and translate these items into the statements
given in each item. Then, if you can, name what the items loading
heavily on each factor have in common. Interpret a negative
loading as “not” whatever the item says.</li>
</ol>
<p>Solution</p>
<p>This is a lot of work, but I figure you should go through it at
least once! If you have some number of factors other than 5,
your results will be different from mine. Keep going as long as
you reasonably can.
Factor 1: 3, 8 (negatively), 13, 18
(negative), 23 (negative), 28, 33, 38 and maybe 43
(negatively). These are: do a thorough job, not-careless,
reliable, not-disorganized, not-lazy, persevere, efficient,
stick to plans, not-distractible. These have the common theme of
paying attention to detail and getting the job done properly.</p>
<p>Factor 2: 1, not-6, 16, not-21, 26, not-31, 36. Talkative,
not-reserved, generates enthusiasm, not-quiet, assertive,
not-shy, outgoing. “Extravert” seems to capture all of those.
Factor 3: 4, not-9, 14, 19, not-24, 29, not-34, 39. Depressed,
not-relaxed, tense, worried, not emotionally stable, moody,
not-calm-when-tense, nervous. “Not happy” or something like that.</p>
<p>Notice how these seem to be jumping in steps of 5? The
psychology scoring of assessments like this is that a person’s
score on some dimension is found by adding up their scores on
certain of the questions and subtracting their scores on others
(“reverse-coded questions”). I’m guessing that these guys have
5 dimensions they are testing for, corresponding presumably to
my five factors. The questionnaire at
<a href="http://ipip.ori.org/newIPIP-IPCScoringKey.htm">link</a> is
different, but you see the same idea there. (The jumps there seem to
be in steps of 8, since they have 8 dimensions.)</p>
<p>Factor 4: not-2, 7, not-12 (just), 22, not-27, 32, not-37,
42. Doesn’t find fault, helpful, doesn’t start quarrels,
trusting, not-cold-and-aloof, considerate, not-sometimes-rude,
co-operative. “Helps without judgement” or similar.</p>
<p>Factor 5: 5, 10, 15, 20, 25, 30, 40, 44. Original, curious,
ingenious, imaginative, inventive, values artistic experiences,
reflective, sophisticated in art and music. Creative.</p>
<p>I remembered that psychologists like to talk about the “big 5”
personality traits. These are extraversion (factor 2 here),
agreeableness (factor 4), openness (factor 5?),
conscientiousness (factor 1), and neuroticism (factor 3). The
correspondence appears to be pretty good. (I wrote my answers
above last year without thinking about “big 5” at all.)</p>
<p>I wonder whether 6 factors is different?</p>
<div class="sourceCode" id="cb3490"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb3490-1"><a href="principal-components-and-factor-analysis.html#cb3490-1"></a>pers.ok<span class="fl">.2</span> &lt;-<span class="st"> </span>pers.ok <span class="op">%&gt;%</span></span>
<span id="cb3490-2"><a href="principal-components-and-factor-analysis.html#cb3490-2"></a><span class="st">  </span><span class="kw">select</span>(<span class="kw">starts_with</span>(<span class="st">&quot;PERS&quot;</span>)) <span class="op">%&gt;%</span></span>
<span id="cb3490-3"><a href="principal-components-and-factor-analysis.html#cb3490-3"></a><span class="st">  </span><span class="kw">factanal</span>(<span class="dv">6</span>, <span class="dt">scores =</span> <span class="st">&quot;r&quot;</span>)</span>
<span id="cb3490-4"><a href="principal-components-and-factor-analysis.html#cb3490-4"></a>pers.ok<span class="fl">.2</span><span class="op">$</span>loadings</span></code></pre></div>
<pre><code>## 
## Loadings:
##        Factor1 Factor2 Factor3 Factor4 Factor5 Factor6
## PERS01  0.114  -0.668           0.343           0.290 
## PERS02                  0.204  -0.451           0.354 
## PERS03  0.658                   0.200           0.131 
## PERS04 -0.141   0.215   0.538  -0.196                 
## PERS05  0.212  -0.271  -0.168   0.115   0.571         
## PERS06          0.694   0.171  -0.102                 
## PERS07  0.315  -0.114           0.530   0.138         
## PERS08 -0.602           0.145                   0.180 
## PERS09                 -0.669   0.118           0.106 
## PERS10  0.125                           0.398   0.264 
## PERS11         -0.131  -0.257           0.173   0.445 
## PERS12 -0.178                  -0.348           0.188 
## PERS13  0.572                   0.332   0.129         
## PERS14          0.142   0.675                   0.121 
## PERS15  0.141                           0.495         
## PERS16         -0.322  -0.130   0.114   0.248   0.491 
## PERS17                 -0.111   0.346           0.139 
## PERS18 -0.655                                         
## PERS19          0.139   0.598   0.101   0.104         
## PERS20         -0.165                   0.489   0.166 
## PERS21          0.843                          -0.110 
## PERS22  0.123  -0.105           0.613           0.110 
## PERS23 -0.631           0.115  -0.232                 
## PERS24                 -0.603           0.113   0.143 
## PERS25         -0.135  -0.119           0.513   0.166 
## PERS26  0.113  -0.385  -0.225  -0.163   0.176   0.454 
## PERS27          0.275   0.128  -0.365           0.177 
## PERS28  0.617                   0.253   0.129         
## PERS29                  0.466  -0.161           0.164 
## PERS30                                  0.497         
## PERS31          0.659   0.166                         
## PERS32  0.297                   0.630           0.102 
## PERS33  0.597                                   0.239 
## PERS34                 -0.584                   0.153 
## PERS35          0.221                  -0.210         
## PERS36         -0.562  -0.171   0.214           0.385 
## PERS37 -0.320                  -0.439           0.220 
## PERS38  0.501                   0.123   0.130   0.182 
## PERS39 -0.123   0.410   0.512                   0.118 
## PERS40                          0.146   0.598         
## PERS41                         -0.106  -0.378   0.117 
## PERS42  0.259  -0.139           0.587   0.118         
## PERS43 -0.515           0.210                   0.253 
## PERS44                                  0.454         
## 
##                Factor1 Factor2 Factor3 Factor4 Factor5 Factor6
## SS loadings      3.830   3.284   3.213   2.865   2.527   1.659
## Proportion Var   0.087   0.075   0.073   0.065   0.057   0.038
## Cumulative Var   0.087   0.162   0.235   0.300   0.357   0.395</code></pre>
<p>Much of the same kind of thing seems to be happening, though it’s a
bit fuzzier. I suspect the devisers of this survey were adherents to
the “big 5” theory. The factor 6 here is items 11, 16 and 26, which
would be expected to belong to factor 2 here, given what we found
before. I think these particular items are about generating enthusiasm
in others, rather than (necessarily) about being extraverted oneself.</p>
<ol start="8" style="list-style-type: lower-alpha">
<li>Find a person who is extreme on each of your first three
factors (one at a time). For each of these people, what kind of
data should they have for the relevant ones of variables
<code>PERS01</code> through <code>PERS44</code>? Do they? Explain
reasonably briefly.</li>
</ol>
<p>Solution</p>
<p>For this, we need the factor scores obtained in part
(<a href="#part:score">here</a>).
<label for="tufte-mn-277" class="margin-toggle">⊕</label><input type="checkbox" id="tufte-mn-277" class="margin-toggle"><span class="marginnote">There are two types of scores here: a person’s scores on the psychological test, 1 through 5, and their factor scores, which are decimal numbers centred at zero. Try not to get these confused.</span>
I’m thinking that I will create a data frame
with the original data (with the missing values removed) and the
factor scores together, and then look in there. This will have a
lot of columns, but we’ll only need to display some each time.
This is based on my 5-factor solution. I’m adding a column
<code>id</code> so that I know which of the individuals (with no
missing data) we are looking at:</p>
<div class="sourceCode" id="cb3492"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb3492-1"><a href="principal-components-and-factor-analysis.html#cb3492-1"></a>scores<span class="fl">.1</span> &lt;-<span class="st"> </span><span class="kw">as_tibble</span>(pers.ok<span class="fl">.1</span><span class="op">$</span>scores) <span class="op">%&gt;%</span></span>
<span id="cb3492-2"><a href="principal-components-and-factor-analysis.html#cb3492-2"></a><span class="st">  </span><span class="kw">bind_cols</span>(pers.ok) <span class="op">%&gt;%</span></span>
<span id="cb3492-3"><a href="principal-components-and-factor-analysis.html#cb3492-3"></a><span class="st">  </span><span class="kw">mutate</span>(<span class="dt">id =</span> <span class="kw">row_number</span>())</span>
<span id="cb3492-4"><a href="principal-components-and-factor-analysis.html#cb3492-4"></a>scores<span class="fl">.1</span></span></code></pre></div>
<p>I did it this way, rather than using <code>data.frame</code>, so that I
would end up with a <code>tibble</code> that would display nicely rather
than running off the page. This meant turning the matrix of factor
scores into a <code>tibble</code> first and then gluing everything onto
it. (There’s no problem in using <code>data.frame</code> here if you
prefer. You could even begin with <code>data.frame</code> and pipe the
final result into <code>as_tibble</code> to end up with a
<code>tibble</code>.)
Let’s start with factor 1. There are several ways to find the person
who scores highest and/or lowest on that factor:</p>
<div class="sourceCode" id="cb3493"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb3493-1"><a href="principal-components-and-factor-analysis.html#cb3493-1"></a>scores<span class="fl">.1</span> <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">filter</span>(Factor1 <span class="op">==</span><span class="st"> </span><span class="kw">max</span>(Factor1))</span></code></pre></div>
<p>to display the maximum, or</p>
<div class="sourceCode" id="cb3494"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb3494-1"><a href="principal-components-and-factor-analysis.html#cb3494-1"></a>scores<span class="fl">.1</span> <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">arrange</span>(Factor1) <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">print</span>(<span class="dt">n =</span> <span class="dv">5</span>)</span></code></pre></div>
<p>to display the minimum (and in this case the five smallest ones), or</p>
<div class="sourceCode" id="cb3495"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb3495-1"><a href="principal-components-and-factor-analysis.html#cb3495-1"></a>scores<span class="fl">.1</span> <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">filter</span>(<span class="kw">abs</span>(Factor1) <span class="op">==</span><span class="st"> </span><span class="kw">max</span>(<span class="kw">abs</span>(Factor1)))</span></code></pre></div>
<p>to display the largest one in size, whether positive or negative. The
code is a bit obfuscated because I have to take absolute values
twice. Maybe it would be clearer to create a column with the absolute
values in it and look at that:</p>
<div class="sourceCode" id="cb3496"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb3496-1"><a href="principal-components-and-factor-analysis.html#cb3496-1"></a>scores<span class="fl">.1</span> <span class="op">%&gt;%</span></span>
<span id="cb3496-2"><a href="principal-components-and-factor-analysis.html#cb3496-2"></a><span class="st">  </span><span class="kw">mutate</span>(<span class="dt">abso =</span> <span class="kw">abs</span>(Factor1)) <span class="op">%&gt;%</span></span>
<span id="cb3496-3"><a href="principal-components-and-factor-analysis.html#cb3496-3"></a><span class="st">  </span><span class="kw">filter</span>(abso <span class="op">==</span><span class="st"> </span><span class="kw">max</span>(abso))</span></code></pre></div>
<p>Does
this work too?</p>
<div class="sourceCode" id="cb3497"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb3497-1"><a href="principal-components-and-factor-analysis.html#cb3497-1"></a>scores<span class="fl">.1</span> <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">arrange</span>(<span class="kw">desc</span>(<span class="kw">abs</span>(Factor1))) <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">print</span>(<span class="dt">n =</span> <span class="dv">5</span>)</span></code></pre></div>
<p>It looks as if it does: “sort the Factor 1 scores in descending order by absolute value, and display the first few”. The most extreme
scores on Factor 1 are all negative: the most positive one (found
above) was only about 1.70.</p>
<p>For you, you don’t have to be this sophisticated. It’s enough to
eyeball the factor scores on factor 1 and find one that’s reasonably
far away from zero. Then you note its row and <code>slice</code> that row,
later.</p>
<p>I think I like the idea of creating a new column with the absolute
values in it and finding the largest of that. Before we pursue that,
though, remember that we don’t need to look at <em>all</em> the
<code>PERS</code> columns, because only some of them load highly on each
factor. These are the ones I defined into <code>f1</code> first; the first
ones have positive loadings and the last three have negative loadings:</p>
<div class="sourceCode" id="cb3498"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb3498-1"><a href="principal-components-and-factor-analysis.html#cb3498-1"></a>f1 &lt;-<span class="st"> </span><span class="kw">c</span>(<span class="dv">3</span>, <span class="dv">13</span>, <span class="dv">28</span>, <span class="dv">33</span>, <span class="dv">38</span>, <span class="dv">8</span>, <span class="dv">18</span>, <span class="dv">23</span>, <span class="dv">43</span>)</span>
<span id="cb3498-2"><a href="principal-components-and-factor-analysis.html#cb3498-2"></a>scores<span class="fl">.1</span> <span class="op">%&gt;%</span></span>
<span id="cb3498-3"><a href="principal-components-and-factor-analysis.html#cb3498-3"></a><span class="st">  </span><span class="kw">mutate</span>(<span class="dt">abso =</span> <span class="kw">abs</span>(Factor1)) <span class="op">%&gt;%</span></span>
<span id="cb3498-4"><a href="principal-components-and-factor-analysis.html#cb3498-4"></a><span class="st">  </span><span class="kw">filter</span>(abso <span class="op">==</span><span class="st"> </span><span class="kw">max</span>(abso)) <span class="op">%&gt;%</span></span>
<span id="cb3498-5"><a href="principal-components-and-factor-analysis.html#cb3498-5"></a><span class="st">  </span><span class="kw">select</span>(id, Factor1, <span class="kw">num_range</span>(<span class="st">&quot;PERS&quot;</span>, f1, <span class="dt">width =</span> <span class="dv">2</span>)) <span class="op">%&gt;%</span></span>
<span id="cb3498-6"><a href="principal-components-and-factor-analysis.html#cb3498-6"></a><span class="st">  </span><span class="kw">print</span>(<span class="dt">width =</span> <span class="ot">Inf</span>)</span></code></pre></div>
<p>I don’t think I’ve used <code>num_range</code> before, like, ever. It is
one of the select-helpers like <code>starts_with</code>. It is used when
you have column names that are some constant text followed by variable
numbers, which is exactly what we have here: we want to select the
<code>PERS</code> columns with numbers that we
specify. <code>num_range</code> requires (at least) two things: the text prefix,
followed by a vector of numbers that are to be glued onto the
prefix. I defined that first so as not to clutter up the
<code>select</code> line. The third thing here is <code>width</code>: all the
<code>PERS</code> columns have a name that ends with two digits, so
<code>PERS03</code> rather than <code>PERS3</code>, and using <code>width</code>
makes sure that the zero gets inserted.</p>
<p>Individual 340 is a low scorer on factor 1, so they should have low
scores on the first five items (the ones with positive loading on
factor 1) and high scores on the last four. This is indeed what
happened: 1s, 2s and 3s on the first five items and 4s and 5s on the
last four.
Having struggled through that, factors 2 and 3 are repeats of
this. The high loaders on factor 2 are the ones shown in <code>f2</code>
below, with the first five loading positively and the last three
negatively.
<label for="tufte-mn-278" class="margin-toggle">⊕</label><input type="checkbox" id="tufte-mn-278" class="margin-toggle"><span class="marginnote">I think the last four items in the entire survey are different; otherwise the total number of items would be a multiple of 5.</span></p>
<div class="sourceCode" id="cb3499"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb3499-1"><a href="principal-components-and-factor-analysis.html#cb3499-1"></a>f2 &lt;-<span class="st"> </span><span class="kw">c</span>(<span class="dv">1</span>, <span class="dv">11</span>, <span class="dv">16</span>, <span class="dv">26</span>, <span class="dv">36</span>, <span class="dv">6</span>, <span class="dv">21</span>, <span class="dv">31</span>)</span>
<span id="cb3499-2"><a href="principal-components-and-factor-analysis.html#cb3499-2"></a>scores<span class="fl">.1</span> <span class="op">%&gt;%</span></span>
<span id="cb3499-3"><a href="principal-components-and-factor-analysis.html#cb3499-3"></a><span class="st">  </span><span class="kw">mutate</span>(<span class="dt">abso =</span> <span class="kw">abs</span>(Factor2)) <span class="op">%&gt;%</span></span>
<span id="cb3499-4"><a href="principal-components-and-factor-analysis.html#cb3499-4"></a><span class="st">  </span><span class="kw">filter</span>(abso <span class="op">==</span><span class="st"> </span><span class="kw">max</span>(abso)) <span class="op">%&gt;%</span></span>
<span id="cb3499-5"><a href="principal-components-and-factor-analysis.html#cb3499-5"></a><span class="st">  </span><span class="kw">select</span>(id, Factor2, <span class="kw">num_range</span>(<span class="st">&quot;PERS&quot;</span>, f2, <span class="dt">width =</span> <span class="dv">2</span>)) <span class="op">%&gt;%</span></span>
<span id="cb3499-6"><a href="principal-components-and-factor-analysis.html#cb3499-6"></a><span class="st">  </span><span class="kw">print</span>(<span class="dt">width =</span> <span class="ot">Inf</span>)</span></code></pre></div>
<p>What kind of idiot, I was thinking, named the data frame of scores
<code>scores.1</code> when there are going to be three factors to assess?</p>
<p>The first five scores are lowish, but the last three are definitely
high (three 5s). This idea of a low score on the positive-loading
items and a high score on the negatively-loading ones is entirely
consistent with a negative factor score.</p>
<p>Finally, factor 3, which loads highly on items 4, 9 (neg), 14, 19, 24
(neg), 29, 34 (neg), 39. (Item 44, which you’d expect to be part of
this factor, is actually in factor 5.) First we see which individual
this is:</p>
<div class="sourceCode" id="cb3500"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb3500-1"><a href="principal-components-and-factor-analysis.html#cb3500-1"></a>f3 &lt;-<span class="st"> </span><span class="kw">c</span>(<span class="dv">4</span>, <span class="dv">14</span>, <span class="dv">19</span>, <span class="dv">29</span>, <span class="dv">39</span>, <span class="dv">9</span>, <span class="dv">24</span>, <span class="dv">34</span>)</span>
<span id="cb3500-2"><a href="principal-components-and-factor-analysis.html#cb3500-2"></a>scores<span class="fl">.1</span> <span class="op">%&gt;%</span></span>
<span id="cb3500-3"><a href="principal-components-and-factor-analysis.html#cb3500-3"></a><span class="st">  </span><span class="kw">mutate</span>(<span class="dt">abso =</span> <span class="kw">abs</span>(Factor3)) <span class="op">%&gt;%</span></span>
<span id="cb3500-4"><a href="principal-components-and-factor-analysis.html#cb3500-4"></a><span class="st">  </span><span class="kw">filter</span>(abso <span class="op">==</span><span class="st"> </span><span class="kw">max</span>(abso)) <span class="op">%&gt;%</span></span>
<span id="cb3500-5"><a href="principal-components-and-factor-analysis.html#cb3500-5"></a><span class="st">  </span><span class="kw">select</span>(id, Factor3, <span class="kw">num_range</span>(<span class="st">&quot;PERS&quot;</span>, f3, <span class="dt">width =</span> <span class="dv">2</span>)) <span class="op">%&gt;%</span></span>
<span id="cb3500-6"><a href="principal-components-and-factor-analysis.html#cb3500-6"></a><span class="st">  </span><span class="kw">print</span>(<span class="dt">width =</span> <span class="ot">Inf</span>)</span></code></pre></div>
<p>The only mysterious one there is item 19, which ought to be low,
because it has a positive loading and the factor score is unusually
negative. But it is 4 on a 5-point scale. The others that are supposed
to be low are 1 and the ones that are supposed to be high are 4 or 5, so
those all match up.</p>
<ol style="list-style-type: lower-roman">
<li>Check the uniquenesses. Which one(s) seem unusually
high? Check these against the factor loadings. Are these what you
would expect?</li>
</ol>
<p>Solution</p>
<p>Mine are</p>
<div class="sourceCode" id="cb3501"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb3501-1"><a href="principal-components-and-factor-analysis.html#cb3501-1"></a>pers.ok<span class="fl">.1</span><span class="op">$</span>uniquenesses</span></code></pre></div>
<pre><code>##    PERS01    PERS02    PERS03    PERS04    PERS05    PERS06    PERS07    PERS08    PERS09    PERS10    PERS11 
## 0.3276244 0.6155884 0.4955364 0.6035655 0.5689691 0.4980334 0.5884146 0.6299781 0.5546981 0.7460655 0.7740590 
##    PERS12    PERS13    PERS14    PERS15    PERS16    PERS17    PERS18    PERS19    PERS20    PERS21    PERS22 
## 0.8016644 0.5336047 0.5035412 0.7381636 0.6352166 0.8978624 0.5881834 0.5949740 0.6900378 0.3274366 0.6564542 
##    PERS23    PERS24    PERS25    PERS26    PERS27    PERS28    PERS29    PERS30    PERS31    PERS32    PERS33 
## 0.5279346 0.6107080 0.6795545 0.5412962 0.7438329 0.5289192 0.7114735 0.7386601 0.5762901 0.5592906 0.6029914 
##    PERS34    PERS35    PERS36    PERS37    PERS38    PERS39    PERS40    PERS41    PERS42    PERS43    PERS44 
## 0.6573411 0.9306766 0.4966071 0.6396371 0.6804821 0.5933423 0.6204610 0.8560531 0.5684220 0.6898732 0.7872295</code></pre>
<p>Yours will be different if you used a different number of factors. But
the procedure you follow will be the same as mine.</p>
<p>I think the highest of these is 0.9307, for item 35. Also high is item
17, 0.8979. If you look back at the table of loadings, item 35 has low
loadings on <em>all</em> the factors: the largest in size is only
0.180. The largest loading for item 17 is 0.277, on factor 4. This is
not high either.</p>
<p>Looking down the loadings table, also item 41 has only a loading of
<span class="math inline">\(-0.326\)</span> on factor 5, so its uniqueness ought to be pretty high as
well. At 0.8561, it is.</p>

</div>
</div>
<p style="text-align: center;">
<a href="multidimensional-scaling.html"><button class="btn btn-default">Previous</button></a>
<a href="frequency-table-analysis.html"><button class="btn btn-default">Next</button></a>
</p>
</div>
</div>



</body>
</html>
