<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>Chapter 39 Principal Components | Problems and Solutions in Applied Statistics</title>
  <meta name="description" content="A set of problems and solutions, in R, on various parts of applied statistics" />
  <meta name="generator" content="bookdown 0.21 and GitBook 2.6.7" />

  <meta property="og:title" content="Chapter 39 Principal Components | Problems and Solutions in Applied Statistics" />
  <meta property="og:type" content="book" />
  <meta property="og:url" content="http://ritsokiguess.site/pasias" />
  
  <meta property="og:description" content="A set of problems and solutions, in R, on various parts of applied statistics" />
  <meta name="github-repo" content="nxskok/pasias" />

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Chapter 39 Principal Components | Problems and Solutions in Applied Statistics" />
  
  <meta name="twitter:description" content="A set of problems and solutions, in R, on various parts of applied statistics" />
  

<meta name="author" content="Ken Butler" />


<meta name="date" content="2021-06-04" />

  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="multidimensional-scaling.html"/>
<link rel="next" href="factor-analysis.html"/>
<script src="libs/jquery-2.2.3/jquery.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />











<style type="text/css">
a.sourceLine { display: inline-block; line-height: 1.25; }
a.sourceLine { pointer-events: none; color: inherit; text-decoration: inherit; }
a.sourceLine:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode { white-space: pre; position: relative; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
code.sourceCode { white-space: pre-wrap; }
a.sourceLine { text-indent: -1em; padding-left: 1em; }
}
pre.numberSource a.sourceLine
  { position: relative; left: -4em; }
pre.numberSource a.sourceLine::before
  { content: attr(title);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; pointer-events: all; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {  }
@media screen {
a.sourceLine::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">Problems and Solutions in Applied Statistics</a></li>

<li class="divider"></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i>Introduction</a><ul>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#packages-used-somewhere-in-this-book"><i class="fa fa-check"></i>Packages used somewhere in this book</a></li>
</ul></li>
<li class="chapter" data-level="1" data-path="getting-used-to-r-and-r-studio.html"><a href="getting-used-to-r-and-r-studio.html"><i class="fa fa-check"></i><b>1</b> Getting used to R and R Studio</a><ul>
<li class="chapter" data-level="1.1" data-path="getting-used-to-r-and-r-studio.html"><a href="getting-used-to-r-and-r-studio.html#running-r-studio-on-jupyterhub"><i class="fa fa-check"></i><b>1.1</b> Running R Studio on Jupyterhub</a></li>
<li class="chapter" data-level="1.2" data-path="getting-used-to-r-and-r-studio.html"><a href="getting-used-to-r-and-r-studio.html#getting-an-r-studio-cloud-account"><i class="fa fa-check"></i><b>1.2</b> Getting an R Studio Cloud account</a></li>
<li class="chapter" data-level="1.3" data-path="getting-used-to-r-and-r-studio.html"><a href="getting-used-to-r-and-r-studio.html#getting-started"><i class="fa fa-check"></i><b>1.3</b> Getting started</a></li>
<li class="chapter" data-level="1.4" data-path="getting-used-to-r-and-r-studio.html"><a href="getting-used-to-r-and-r-studio.html#reading-data-from-a-file"><i class="fa fa-check"></i><b>1.4</b> Reading data from a file</a></li>
<li class="chapter" data-level="1.5" data-path="getting-used-to-r-and-r-studio.html"><a href="getting-used-to-r-and-r-studio.html#reading-files-different-ways"><i class="fa fa-check"></i><b>1.5</b> Reading files different ways</a></li>
</ul></li>
<li class="chapter" data-level="2" data-path="reading-in-data.html"><a href="reading-in-data.html"><i class="fa fa-check"></i><b>2</b> Reading in data</a></li>
<li class="chapter" data-level="3" data-path="drawing-graphs.html"><a href="drawing-graphs.html"><i class="fa fa-check"></i><b>3</b> Drawing graphs</a></li>
<li class="chapter" data-level="4" data-path="data-exploration.html"><a href="data-exploration.html"><i class="fa fa-check"></i><b>4</b> Data exploration</a></li>
<li class="chapter" data-level="5" data-path="working-with-dataframes.html"><a href="working-with-dataframes.html"><i class="fa fa-check"></i><b>5</b> Working with dataframes</a></li>
<li class="chapter" data-level="6" data-path="one-sample-inference.html"><a href="one-sample-inference.html"><i class="fa fa-check"></i><b>6</b> One-sample inference</a></li>
<li class="chapter" data-level="7" data-path="two-sample-inference.html"><a href="two-sample-inference.html"><i class="fa fa-check"></i><b>7</b> Two-sample inference</a></li>
<li class="chapter" data-level="8" data-path="power-and-sample-size.html"><a href="power-and-sample-size.html"><i class="fa fa-check"></i><b>8</b> Power and sample size</a></li>
<li class="chapter" data-level="9" data-path="the-sign-test.html"><a href="the-sign-test.html"><i class="fa fa-check"></i><b>9</b> The sign test</a></li>
<li class="chapter" data-level="10" data-path="mood-median-test.html"><a href="mood-median-test.html"><i class="fa fa-check"></i><b>10</b> Mood median test</a></li>
<li class="chapter" data-level="11" data-path="matched-pairs-t-and-sign-test.html"><a href="matched-pairs-t-and-sign-test.html"><i class="fa fa-check"></i><b>11</b> Matched pairs t and sign test</a></li>
<li class="chapter" data-level="12" data-path="normal-quantile-plots.html"><a href="normal-quantile-plots.html"><i class="fa fa-check"></i><b>12</b> Normal quantile plots</a><ul>
<li class="chapter" data-level="12.1" data-path="normal-quantile-plots.html"><a href="normal-quantile-plots.html#lengths-of-heliconia-flowers"><i class="fa fa-check"></i><b>12.1</b> Lengths of heliconia flowers</a></li>
<li class="chapter" data-level="12.2" data-path="normal-quantile-plots.html"><a href="normal-quantile-plots.html#ferritin-and-normality"><i class="fa fa-check"></i><b>12.2</b> Ferritin and normality</a></li>
<li class="chapter" data-level="12.3" data-path="normal-quantile-plots.html"><a href="normal-quantile-plots.html#lengths-of-heliconia-flowers-1"><i class="fa fa-check"></i><b>12.3</b> Lengths of heliconia flowers</a></li>
<li class="chapter" data-level="12.4" data-path="normal-quantile-plots.html"><a href="normal-quantile-plots.html#ferritin-and-normality-1"><i class="fa fa-check"></i><b>12.4</b> Ferritin and normality</a></li>
</ul></li>
<li class="chapter" data-level="13" data-path="analysis-of-variance.html"><a href="analysis-of-variance.html"><i class="fa fa-check"></i><b>13</b> Analysis of variance</a></li>
<li class="chapter" data-level="14" data-path="writing-reports.html"><a href="writing-reports.html"><i class="fa fa-check"></i><b>14</b> Writing reports</a></li>
<li class="chapter" data-level="15" data-path="learning-to-code.html"><a href="learning-to-code.html"><i class="fa fa-check"></i><b>15</b> Learning to code</a><ul>
<li class="chapter" data-level="15.1" data-path="learning-to-code.html"><a href="learning-to-code.html#introduction-1"><i class="fa fa-check"></i><b>15.1</b> Introduction</a></li>
<li class="chapter" data-level="15.2" data-path="learning-to-code.html"><a href="learning-to-code.html#data-and-pre-processing"><i class="fa fa-check"></i><b>15.2</b> Data and pre-processing</a></li>
<li class="chapter" data-level="15.3" data-path="learning-to-code.html"><a href="learning-to-code.html#analysis"><i class="fa fa-check"></i><b>15.3</b> Analysis</a></li>
<li class="chapter" data-level="15.4" data-path="learning-to-code.html"><a href="learning-to-code.html#conclusions-see-note-9"><i class="fa fa-check"></i><b>15.4</b> Conclusions (see note 9)</a></li>
</ul></li>
<li class="chapter" data-level="16" data-path="treating-dandruff.html"><a href="treating-dandruff.html"><i class="fa fa-check"></i><b>16</b> Treating dandruff</a><ul>
<li class="chapter" data-level="16.1" data-path="treating-dandruff.html"><a href="treating-dandruff.html#introduction-2"><i class="fa fa-check"></i><b>16.1</b> Introduction</a></li>
<li class="chapter" data-level="16.2" data-path="treating-dandruff.html"><a href="treating-dandruff.html#exploratory-analysis"><i class="fa fa-check"></i><b>16.2</b> Exploratory analysis</a></li>
<li class="chapter" data-level="16.3" data-path="treating-dandruff.html"><a href="treating-dandruff.html#analysis-of-variance-1"><i class="fa fa-check"></i><b>16.3</b> Analysis of Variance</a></li>
<li class="chapter" data-level="16.4" data-path="treating-dandruff.html"><a href="treating-dandruff.html#assessment-of-assumptions"><i class="fa fa-check"></i><b>16.4</b> Assessment of Assumptions</a></li>
<li class="chapter" data-level="16.5" data-path="treating-dandruff.html"><a href="treating-dandruff.html#conclusions"><i class="fa fa-check"></i><b>16.5</b> Conclusions</a></li>
<li class="chapter" data-level="16.6" data-path="treating-dandruff.html"><a href="treating-dandruff.html#end"><i class="fa fa-check"></i><b>16.6</b> End</a></li>
</ul></li>
<li class="chapter" data-level="17" data-path="tidying-data.html"><a href="tidying-data.html"><i class="fa fa-check"></i><b>17</b> Tidying data</a></li>
<li class="chapter" data-level="18" data-path="simple-regression.html"><a href="simple-regression.html"><i class="fa fa-check"></i><b>18</b> Simple regression</a></li>
<li class="chapter" data-level="19" data-path="multiple-regression.html"><a href="multiple-regression.html"><i class="fa fa-check"></i><b>19</b> Multiple regression</a></li>
<li class="chapter" data-level="20" data-path="regression-with-categorical-variables.html"><a href="regression-with-categorical-variables.html"><i class="fa fa-check"></i><b>20</b> Regression with categorical variables</a><ul>
<li class="chapter" data-level="20.1" data-path="regression-with-categorical-variables.html"><a href="regression-with-categorical-variables.html#crickets-revisited"><i class="fa fa-check"></i><b>20.1</b> Crickets revisited</a></li>
<li class="chapter" data-level="20.2" data-path="regression-with-categorical-variables.html"><a href="regression-with-categorical-variables.html#pulse-rates-and-marching"><i class="fa fa-check"></i><b>20.2</b> Pulse rates and marching</a></li>
<li class="chapter" data-level="20.3" data-path="regression-with-categorical-variables.html"><a href="regression-with-categorical-variables.html#crickets-revisited-1"><i class="fa fa-check"></i><b>20.3</b> Crickets revisited</a></li>
<li class="chapter" data-level="20.4" data-path="regression-with-categorical-variables.html"><a href="regression-with-categorical-variables.html#pulse-rates-and-marching-1"><i class="fa fa-check"></i><b>20.4</b> Pulse rates and marching</a></li>
</ul></li>
<li class="chapter" data-level="21" data-path="dates-and-times.html"><a href="dates-and-times.html"><i class="fa fa-check"></i><b>21</b> Dates and times</a></li>
<li class="chapter" data-level="22" data-path="functions.html"><a href="functions.html"><i class="fa fa-check"></i><b>22</b> Functions</a></li>
<li class="chapter" data-level="23" data-path="vector-and-matrix-algebra.html"><a href="vector-and-matrix-algebra.html"><i class="fa fa-check"></i><b>23</b> Vector and matrix algebra</a><ul>
<li class="chapter" data-level="23.1" data-path="vector-and-matrix-algebra.html"><a href="vector-and-matrix-algebra.html#heights-and-foot-lengths-again"><i class="fa fa-check"></i><b>23.1</b> Heights and foot lengths again</a></li>
<li class="chapter" data-level="23.2" data-path="vector-and-matrix-algebra.html"><a href="vector-and-matrix-algebra.html#heights-and-foot-lengths-again-1"><i class="fa fa-check"></i><b>23.2</b> Heights and foot lengths again</a></li>
</ul></li>
<li class="chapter" data-level="24" data-path="the-bootstrap.html"><a href="the-bootstrap.html"><i class="fa fa-check"></i><b>24</b> The Bootstrap</a></li>
<li class="chapter" data-level="25" data-path="bayesian-statistics-with-stan.html"><a href="bayesian-statistics-with-stan.html"><i class="fa fa-check"></i><b>25</b> Bayesian Statistics with Stan</a></li>
<li class="chapter" data-level="26" data-path="logistic-regression.html"><a href="logistic-regression.html"><i class="fa fa-check"></i><b>26</b> Logistic regression</a></li>
<li class="chapter" data-level="27" data-path="logistic-regression-with-ordinal-response.html"><a href="logistic-regression-with-ordinal-response.html"><i class="fa fa-check"></i><b>27</b> Logistic regression with ordinal response</a></li>
<li class="chapter" data-level="28" data-path="logistic-regression-with-nominal-response.html"><a href="logistic-regression-with-nominal-response.html"><i class="fa fa-check"></i><b>28</b> Logistic regression with nominal response</a></li>
<li class="chapter" data-level="29" data-path="survival-analysis.html"><a href="survival-analysis.html"><i class="fa fa-check"></i><b>29</b> Survival analysis</a></li>
<li class="chapter" data-level="30" data-path="analysis-of-variance-revisited.html"><a href="analysis-of-variance-revisited.html"><i class="fa fa-check"></i><b>30</b> Analysis of variance revisited</a></li>
<li class="chapter" data-level="31" data-path="analysis-of-covariance.html"><a href="analysis-of-covariance.html"><i class="fa fa-check"></i><b>31</b> Analysis of covariance</a></li>
<li class="chapter" data-level="32" data-path="multivariate-analysis-of-variance.html"><a href="multivariate-analysis-of-variance.html"><i class="fa fa-check"></i><b>32</b> Multivariate analysis of variance</a></li>
<li class="chapter" data-level="33" data-path="repeated-measures.html"><a href="repeated-measures.html"><i class="fa fa-check"></i><b>33</b> Repeated measures</a></li>
<li class="chapter" data-level="34" data-path="discriminant-analysis.html"><a href="discriminant-analysis.html"><i class="fa fa-check"></i><b>34</b> Discriminant analysis</a></li>
<li class="chapter" data-level="35" data-path="hierarchical-cluster-analysis.html"><a href="hierarchical-cluster-analysis.html"><i class="fa fa-check"></i><b>35</b> Hierarchical cluster analysis</a></li>
<li class="chapter" data-level="36" data-path="k-means-cluster-analysis.html"><a href="k-means-cluster-analysis.html"><i class="fa fa-check"></i><b>36</b> K-means cluster analysis</a></li>
<li class="chapter" data-level="37" data-path="drawing-maps-with-leaflet.html"><a href="drawing-maps-with-leaflet.html"><i class="fa fa-check"></i><b>37</b> Drawing maps with Leaflet</a></li>
<li class="chapter" data-level="38" data-path="multidimensional-scaling.html"><a href="multidimensional-scaling.html"><i class="fa fa-check"></i><b>38</b> Multidimensional Scaling</a></li>
<li class="chapter" data-level="39" data-path="principal-components.html"><a href="principal-components.html"><i class="fa fa-check"></i><b>39</b> Principal Components</a><ul>
<li class="chapter" data-level="39.1" data-path="principal-components.html"><a href="principal-components.html#the-weather-somewhere"><i class="fa fa-check"></i><b>39.1</b> The weather, somewhere</a></li>
<li class="chapter" data-level="39.2" data-path="principal-components.html"><a href="principal-components.html#the-weather-somewhere-1"><i class="fa fa-check"></i><b>39.2</b> The weather, somewhere</a></li>
</ul></li>
<li class="chapter" data-level="40" data-path="factor-analysis.html"><a href="factor-analysis.html"><i class="fa fa-check"></i><b>40</b> Factor Analysis</a></li>
<li class="chapter" data-level="41" data-path="frequency-table-analysis.html"><a href="frequency-table-analysis.html"><i class="fa fa-check"></i><b>41</b> Frequency table analysis</a></li>
<li class="divider"></li>
<li><a href="https://github.com/rstudio/bookdown" target="blank">Published with bookdown</a></li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Problems and Solutions in Applied Statistics</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="principal-components" class="section level1">
<h1><span class="header-section-number">Chapter 39</span> Principal Components</h1>
<p>Packages for this chapter:</p>
<div class="sourceCode" id="cb250"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb250-1" title="1"><span class="kw">library</span>(ggbiplot)</a>
<a class="sourceLine" id="cb250-2" title="2"><span class="kw">library</span>(tidyverse)</a></code></pre></div>
<div id="the-weather-somewhere" class="section level2">
<h2><span class="header-section-number">39.1</span> The weather, somewhere</h2>
<p>The data in
<a href="http://ritsokiguess.site/datafiles/weather_2014.csv">link</a> is of the
weather in a certain location: daily weather records for 2014. The
variables are:</p>
<ul>
<li><p>day of the year (1 through 365)</p></li>
<li><p>day of the month</p></li>
<li><p>number of the month</p></li>
<li><p>season</p></li>
<li><p>low temperature (for the day)</p></li>
<li><p>high temperature</p></li>
<li><p>average temperature</p></li>
<li><p>time of the low temperature</p></li>
<li><p>time of the high temperature</p></li>
<li><p>rainfall (mm)</p></li>
<li><p>average wind speed</p></li>
<li><p>wind gust (highest wind speed)</p></li>
<li><p>time of the wind gust</p></li>
<li><p>wind direction</p></li>
</ul>
<ol style="list-style-type: lower-alpha">
<li><p>Read in the data, and create a data frame containing only
the temperature variables, the rainfall and the wind speed variables
(the ones that are actual numbers, not times or text). Display the
first few lines of your data frame.</p></li>
<li><p>Find five-number summaries for each column by running
<code>quantile</code> on all the columns of the data frame (at once, if
you can).</p></li>
<li><p>Run a principal components analysis (on the correlation matrix).</p></li>
<li><p>Obtain a <code>summary</code> of your principal components
analysis. How many components do you think are worth investigating?</p></li>
<li><p>Make a scree plot. Does this
support your conclusion from the previous part?</p></li>
<li><p>Obtain the component loadings. How do the first three
components depend on the original variables? (That is, what kind of
values for the original variables would make the component scores
large or small?)</p></li>
<li><p>Obtain the principal component scores, for as many components
as you think are reasonable, and display the first
20 of them for each component alongside the other variables in your
data frame.</p></li>
<li><p>Find a day that scores low on component 1, and explain briefly why
it came out that way (by looking at the measured variables).</p></li>
<li><p>Find a day that scores high on component 2, and explain
briefly why it came out that way.</p></li>
<li><p>Find a day that scores high on component 3, and explain
briefly why it came out high.</p></li>
<li><p>Make a biplot of these data, labelling the days by the day
count (from 1 to 365). You may have to get the day count from the
original data frame that you read in from the file. You can shrink
the day numbers to make them overwrite each other (a bit) less.</p></li>
<li><p>Looking at your biplot, what do you think was remarkable
about the weather on day 37? Day 211? Confirm your guesses by
looking at the appropriate rows of your data frame (and comparing
with your <code>summary</code> from earlier).</p></li>
</ol>
<p>My solutions follow:</p>
</div>
<div id="the-weather-somewhere-1" class="section level2">
<h2><span class="header-section-number">39.2</span> The weather, somewhere</h2>
<p>The data in
<a href="http://ritsokiguess.site/datafiles/weather_2014.csv">link</a> is of the
weather in a certain location: daily weather records for 2014. The
variables are:</p>
<ul>
<li><p>day of the year (1 through 365)</p></li>
<li><p>day of the month</p></li>
<li><p>number of the month</p></li>
<li><p>season</p></li>
<li><p>low temperature (for the day)</p></li>
<li><p>high temperature</p></li>
<li><p>average temperature</p></li>
<li><p>time of the low temperature</p></li>
<li><p>time of the high temperature</p></li>
<li><p>rainfall (mm)</p></li>
<li><p>average wind speed</p></li>
<li><p>wind gust (highest wind speed)</p></li>
<li><p>time of the wind gust</p></li>
<li><p>wind direction</p></li>
</ul>
<ol style="list-style-type: lower-alpha">
<li>Read in the data, and create a data frame containing only
the temperature variables, the rainfall and the wind speed variables
(the ones that are actual numbers, not times or text). Display the
first few lines of your data frame.</li>
</ol>
<p>Solution</p>
<p>Read into a temporary data frame, and then process:</p>
<div class="sourceCode" id="cb251"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb251-1" title="1">my_url &lt;-<span class="st"> &quot;http://ritsokiguess.site/datafiles/weather_2014.csv&quot;</span></a>
<a class="sourceLine" id="cb251-2" title="2">weather<span class="fl">.0</span> &lt;-<span class="st"> </span><span class="kw">read_csv</span>(my_url)</a>
<a class="sourceLine" id="cb251-3" title="3">weather<span class="fl">.0</span></a></code></pre></div>
<pre><code>## # A tibble: 365 x 14
##    day.count   day month season l.temp h.temp ave.temp l.temp.time h.temp.time  rain ave.wind gust.wind gust.wind.time dir.wind
##        &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;chr&gt;   &lt;dbl&gt;  &lt;dbl&gt;    &lt;dbl&gt; &lt;time&gt;      &lt;time&gt;      &lt;dbl&gt;    &lt;dbl&gt;     &lt;dbl&gt; &lt;time&gt;         &lt;chr&gt;   
##  1         1     1     1 Winter   12.7   14       13.4 01:25       23:50        32       11.4      53.1 15:45          S       
##  2         2     2     1 Winter   11.3   14.7     13.5 07:30       11:15        64.8      5.6      41.8 22:25          S       
##  3         3     3     1 Winter   12.6   14.7     13.6 21:00       14:00        12.7      4.3      38.6 00:00          SSW     
##  4         4     4     1 Winter    7.7   13.9     11.3 10:35       01:50        20.1     10.3      66   09:05          SW      
##  5         5     5     1 Winter    8.8   14.6     13   01:40       12:55         9.4     11.6      51.5 13:50          SSE     
##  6         6     6     1 Winter   11.8   14.4     13.1 19:35       00:05        38.9      9.9      57.9 08:10          SSE     
##  7         7     7     1 Winter   11.4   14.8     13.5 07:25       14:30         2        6.6      38.6 11:45          SE      
##  8         8     8     1 Winter   12.4   15.6     14.1 23:50       13:25         1.5      5.9      33.8 14:00          SE      
##  9         9     9     1 Winter    9.2   18.4     12.9 07:10       14:05         0        0.2      16.1 14:25          N       
## 10        10    10     1 Winter    8.3   14.8     11   07:55       12:20         0        1.4      24.1 14:20          NNW     
## # … with 355 more rows</code></pre>
<p>There are lots of columns, of which we only want a few:</p>
<div class="sourceCode" id="cb253"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb253-1" title="1">(weather<span class="fl">.0</span> <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">select</span>(l.temp<span class="op">:</span>ave.temp, rain<span class="op">:</span>gust.wind) -&gt;<span class="st"> </span>weather)</a></code></pre></div>
<pre><code>## # A tibble: 365 x 6
##    l.temp h.temp ave.temp  rain ave.wind gust.wind
##     &lt;dbl&gt;  &lt;dbl&gt;    &lt;dbl&gt; &lt;dbl&gt;    &lt;dbl&gt;     &lt;dbl&gt;
##  1   12.7   14       13.4  32       11.4      53.1
##  2   11.3   14.7     13.5  64.8      5.6      41.8
##  3   12.6   14.7     13.6  12.7      4.3      38.6
##  4    7.7   13.9     11.3  20.1     10.3      66  
##  5    8.8   14.6     13     9.4     11.6      51.5
##  6   11.8   14.4     13.1  38.9      9.9      57.9
##  7   11.4   14.8     13.5   2        6.6      38.6
##  8   12.4   15.6     14.1   1.5      5.9      33.8
##  9    9.2   18.4     12.9   0        0.2      16.1
## 10    8.3   14.8     11     0        1.4      24.1
## # … with 355 more rows</code></pre>
<p><span class="math inline">\(\blacksquare\)</span></p>
<ol start="2" style="list-style-type: lower-alpha">
<li>Find five-number summaries for each column by running
<code>quantile</code> on all the columns of the data frame (at once, if
you can).</li>
</ol>
<p>Solution</p>
<p>I think this is the easiest way:</p>
<div class="sourceCode" id="cb255"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb255-1" title="1">weather <span class="op">%&gt;%</span><span class="st"> </span></a>
<a class="sourceLine" id="cb255-2" title="2"><span class="st">  </span><span class="kw">summarize</span>(<span class="kw">across</span>(<span class="kw">everything</span>(), <span class="op">~</span><span class="kw">quantile</span>(.)))</a></code></pre></div>
<pre><code>## # A tibble: 5 x 6
##   l.temp h.temp ave.temp  rain ave.wind gust.wind
##    &lt;dbl&gt;  &lt;dbl&gt;    &lt;dbl&gt; &lt;dbl&gt;    &lt;dbl&gt;     &lt;dbl&gt;
## 1    3.1    9.8      7.3   0        0         3.2
## 2    9.1   14.4     12     0        2.3      22.5
## 3   12.9   19.1     15.8   0.3      3.5      29  
## 4   16.3   23.3     19.3   5.3      5.2      38.6
## 5   22.6   31.5     26.6  74.9     16.6      86.9</code></pre>
<p>This loses the actual percents of the percentiles of the five-number summary (because they are “names” of the numerical result, and the tidyverse doesn’t like names.) I think you can see which percentile is which, though.</p>
<p>Another way to do it is to make a column of column names, using
<code>pivot_longer</code>, and then use <code>nest</code> and list-columns to find
the quantiles for each variable:</p>
<div class="sourceCode" id="cb257"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb257-1" title="1">weather <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb257-2" title="2"><span class="st">  </span><span class="kw">pivot_longer</span>(<span class="kw">everything</span>(), <span class="dt">names_to=</span><span class="st">&quot;xname&quot;</span>, <span class="dt">values_to=</span><span class="st">&quot;x&quot;</span>) <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb257-3" title="3"><span class="st">  </span><span class="kw">nest_by</span>(xname) <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb257-4" title="4"><span class="st">  </span><span class="kw">mutate</span>(<span class="dt">q =</span> <span class="kw">list</span>(<span class="kw">enframe</span>(<span class="kw">quantile</span>(data<span class="op">$</span>x)))) <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb257-5" title="5"><span class="st">  </span><span class="kw">unnest</span>(q) <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb257-6" title="6"><span class="st">  </span><span class="kw">pivot_wider</span>(<span class="dt">names_from=</span>name, <span class="dt">values_from=</span>value) <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb257-7" title="7"><span class="st">  </span><span class="kw">select</span>(<span class="op">-</span>data)</a></code></pre></div>
<pre><code>## # A tibble: 6 x 6
## # Groups:   xname [6]
##   xname      `0%` `25%` `50%` `75%` `100%`
##   &lt;chr&gt;     &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt;  &lt;dbl&gt;
## 1 ave.temp    7.3  12    15.8  19.3   26.6
## 2 ave.wind    0     2.3   3.5   5.2   16.6
## 3 gust.wind   3.2  22.5  29    38.6   86.9
## 4 h.temp      9.8  14.4  19.1  23.3   31.5
## 5 l.temp      3.1   9.1  12.9  16.3   22.6
## 6 rain        0     0     0.3   5.3   74.9</code></pre>
<p>That was a lot of work, but it depends on how you see it when you’re coding it. You should investigate this one line at a time, but the steps are:</p>
<ul>
<li><p>create a “long” data frame with one column of variable names and a second with the values for that variable</p></li>
<li><p>make mini-data-frames <code>data</code> containing everything but <code>xname</code>: that is, one column <code>x</code> with the values for that variable.</p></li>
<li><p>for each mini-data-frame, work out the quantiles of its <code>x</code>. The <code>enframe</code> saves the labels for what percentiles they are.</p></li>
<li><p>Unnest this to make a long data frame with one row for each quantile for each variable.</p></li>
<li><p>put the variable names in rows and the percentiles in columns.</p></li>
</ul>
<p><span class="math inline">\(\blacksquare\)</span></p>
<ol start="3" style="list-style-type: lower-alpha">
<li>Run a principal components analysis (on the correlation matrix).</li>
</ol>
<p>Solution</p>
<div class="sourceCode" id="cb259"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb259-1" title="1">weather<span class="fl">.1</span> &lt;-<span class="st"> </span><span class="kw">princomp</span>(weather, <span class="dt">cor =</span> T)</a></code></pre></div>
<p><span class="math inline">\(\blacksquare\)</span></p>
<ol start="4" style="list-style-type: lower-alpha">
<li>Obtain a <code>summary</code> of your principal components
analysis. How many components do you think are worth investigating?</li>
</ol>
<p>Solution</p>
<div class="sourceCode" id="cb260"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb260-1" title="1"><span class="kw">summary</span>(weather<span class="fl">.1</span>)</a></code></pre></div>
<pre><code>## Importance of components:
##                           Comp.1    Comp.2     Comp.3     Comp.4     Comp.5      Comp.6
## Standard deviation     1.7830875 1.4138296 0.74407069 0.38584917 0.33552998 0.081140732
## Proportion of Variance 0.5299001 0.3331524 0.09227353 0.02481326 0.01876339 0.001097303
## Cumulative Proportion  0.5299001 0.8630525 0.95532604 0.98013930 0.99890270 1.000000000</code></pre>
<p>The issue is to see where the standard deviations are getting small
(after the second component, or perhaps the third one) and to see
where the cumulative proportion of variance explained is acceptably
high (again, after the second one, 86%, or the third, 95%).</p>
<p><span class="math inline">\(\blacksquare\)</span></p>
<ol start="5" style="list-style-type: lower-alpha">
<li>Make a scree plot. Does this
support your conclusion from the previous part?</li>
</ol>
<p>Solution</p>
<p><code>ggscreeplot</code> from <code>ggbiplot</code>:</p>
<div class="sourceCode" id="cb262"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb262-1" title="1"><span class="kw">ggscreeplot</span>(weather<span class="fl">.1</span>)</a></code></pre></div>
<p><img src="pasias_files/figure-html/adskjheuya-1.png" width="672" /></p>
<p>I see elbows at 3 and at 4. Remember you want to be on the mountain
for these, not on the scree, so this suggests 2 or 3 components, which
is exactly what we got from looking at the standard deviations and
cumulative variance explained.</p>
<p>The eigenvalue-greater-than-1 thing
(that is, the “standard deviation” in the <code>summary</code> being greater than 1)
says 2 components, rather than 3.</p>
<p><span class="math inline">\(\blacksquare\)</span></p>
<ol start="6" style="list-style-type: lower-alpha">
<li>Obtain the component loadings. How do the first three
components depend on the original variables? (That is, what kind of
values for the original variables would make the component scores
large or small?)</li>
</ol>
<p>Solution</p>
<div class="sourceCode" id="cb263"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb263-1" title="1">weather<span class="fl">.1</span><span class="op">$</span>loadings</a></code></pre></div>
<pre><code>## 
## Loadings:
##           Comp.1 Comp.2 Comp.3 Comp.4 Comp.5 Comp.6
## l.temp     0.465  0.348         0.542  0.470  0.379
## h.temp     0.510  0.231        -0.576 -0.381  0.458
## ave.temp   0.502  0.311                      -0.804
## rain      -0.296  0.397  0.853        -0.163       
## ave.wind  -0.253  0.560 -0.463  0.357 -0.529       
## gust.wind -0.347  0.507 -0.230 -0.492  0.572       
## 
##                Comp.1 Comp.2 Comp.3 Comp.4 Comp.5 Comp.6
## SS loadings     1.000  1.000  1.000  1.000  1.000  1.000
## Proportion Var  0.167  0.167  0.167  0.167  0.167  0.167
## Cumulative Var  0.167  0.333  0.500  0.667  0.833  1.000</code></pre>
<ul>
<li><p>1: This component loads mainly (and positively) on the temperature
variables, so when temperature is high, component 1 is high.
You could also say that it loads negatively on the other
variables, in which case component 1 is high if the temperature
variables are low and the rain and wind variables are high.</p></li>
<li><p>2: This one loads most heavily, positively, on wind: when wind is high,
component 2 is high. Again, you can make the judgement call that the
other variables also feature in component 2, so that when
<em>everything</em> is large, component 2 is large and small with small.</p></li>
<li><p>3: This one is a bit clearer. The blank loadings are close to 0,
and can be ignored. The main thing in component 3 is rain: when
rainfall is large, component 3 is large. Or, if you like, it is
large (positive) when rainfall is large <em>and wind is small</em>.</p></li>
</ul>
<p>The interpretation here is kind of muffled, because each component has
bits of everything. One of the advantages of factor analysis that we
see in class later is that
you can do a “rotation” so that each variable (to a greater extent)
is either <em>in</em> a factor or <em>out</em> of it. Such a varimax rotation
is the default for <code>factanal</code>, which I presume I now have to
show you (so this is looking ahead):</p>
<div class="sourceCode" id="cb265"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb265-1" title="1">weather<span class="fl">.2</span> &lt;-<span class="st"> </span><span class="kw">factanal</span>(weather, <span class="dv">3</span>, <span class="dt">scores =</span> <span class="st">&quot;r&quot;</span>)</a>
<a class="sourceLine" id="cb265-2" title="2">weather<span class="fl">.2</span><span class="op">$</span>loadings</a></code></pre></div>
<pre><code>## 
## Loadings:
##           Factor1 Factor2 Factor3
## l.temp     0.964          -0.230 
## h.temp     0.939  -0.203   0.267 
## ave.temp   0.992  -0.101         
## rain      -0.147   0.604         
## ave.wind           0.864         
## gust.wind -0.144   0.984         
## 
##                Factor1 Factor2 Factor3
## SS loadings      2.839   2.131   0.140
## Proportion Var   0.473   0.355   0.023
## Cumulative Var   0.473   0.828   0.852</code></pre>
<p>These are a lot less ambiguous: factor 1 is temperature, factor 2 is
rain and wind, and factor 3 is large (positive) if the high
temperature is high or the low temperature is low: that is, if the
high temperature was especially high relative to the low temperature
(or, said differently, if the temperature <em>range</em> was high).</p>
<p>These factors are rather pleasantly interpretable.</p>
<p><code>ggbiplot</code> mysteriously doesn’t handle factor analyses, so we
have to go back to the base-graphics version, which goes a bit like this:</p>
<div class="sourceCode" id="cb267"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb267-1" title="1"><span class="kw">biplot</span>(weather<span class="fl">.2</span><span class="op">$</span>scores, weather<span class="fl">.2</span><span class="op">$</span>loadings)</a></code></pre></div>
<p><img src="pasias_files/figure-html/weather-2014-9-1.png" width="672" /></p>
<p>Now you see that the factors are aligned with the axes, and it’s very
clear what the factors “represent”. (You don’t see much else, in all
honesty, but you see at least this much.)</p>
<p><span class="math inline">\(\blacksquare\)</span></p>
<ol start="7" style="list-style-type: lower-alpha">
<li>Obtain the principal component scores, for as many components
as you think are reasonable, and display the first
20 of them for each component alongside the other variables in your
data frame.</li>
</ol>
<p>Solution</p>
<p>Something like this. I begin by turning the component scores
(which are a matrix) into a data frame, and selecting the ones I
want (the first three):</p>
<div class="sourceCode" id="cb268"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb268-1" title="1"><span class="kw">as_tibble</span>(weather<span class="fl">.1</span><span class="op">$</span>scores) <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb268-2" title="2"><span class="st">  </span><span class="kw">select</span>(<span class="dv">1</span><span class="op">:</span><span class="dv">3</span>) <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb268-3" title="3"><span class="st">  </span><span class="kw">bind_cols</span>(weather) <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb268-4" title="4"><span class="st">  </span><span class="kw">mutate</span>(<span class="dt">day =</span> <span class="kw">row_number</span>()) -&gt;<span class="st"> </span>d</a>
<a class="sourceLine" id="cb268-5" title="5">d </a></code></pre></div>
<pre><code>## # A tibble: 365 x 10
##    Comp.1 Comp.2   Comp.3 l.temp h.temp ave.temp  rain ave.wind gust.wind   day
##     &lt;dbl&gt;  &lt;dbl&gt;    &lt;dbl&gt;  &lt;dbl&gt;  &lt;dbl&gt;    &lt;dbl&gt; &lt;dbl&gt;    &lt;dbl&gt;     &lt;dbl&gt; &lt;int&gt;
##  1 -2.84   3.13  -0.00402   12.7   14       13.4  32       11.4      53.1     1
##  2 -2.79   2.31   3.64      11.3   14.7     13.5  64.8      5.6      41.8     2
##  3 -1.11   0.255  0.263     12.6   14.7     13.6  12.7      4.3      38.6     3
##  4 -3.62   2.47  -0.992      7.7   13.9     11.3  20.1     10.3      66       4
##  5 -2.67   2.03  -1.68       8.8   14.6     13     9.4     11.6      51.5     5
##  6 -3.09   3.14   0.664     11.8   14.4     13.1  38.9      9.9      57.9     6
##  7 -1.22   0.328 -0.958     11.4   14.8     13.5   2        6.6      38.6     7
##  8 -0.734  0.102 -0.743     12.4   15.6     14.1   1.5      5.9      33.8     8
##  9  0.210 -2.26   0.534      9.2   18.4     12.9   0        0.2      16.1     9
## 10 -0.825 -2.00   0.109      8.3   14.8     11     0        1.4      24.1    10
## # … with 355 more rows</code></pre>
<p>I just did the first three scores. I made a column <code>day</code> so that I can see which day of the year I am looking at (later).</p>
<p><span class="math inline">\(\blacksquare\)</span></p>
<ol start="8" style="list-style-type: lower-alpha">
<li>Find a day that scores low on component 1, and explain briefly why
it came out that way (by looking at the measured variables).</li>
</ol>
<p>Solution</p>
<p>We can do this one and the ones following by running
<code>arrange</code> appropriately:</p>
<div class="sourceCode" id="cb270"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb270-1" title="1">d <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">arrange</span>(Comp<span class="fl">.1</span>)</a></code></pre></div>
<pre><code>## # A tibble: 365 x 10
##    Comp.1 Comp.2 Comp.3 l.temp h.temp ave.temp  rain ave.wind gust.wind   day
##     &lt;dbl&gt;  &lt;dbl&gt;  &lt;dbl&gt;  &lt;dbl&gt;  &lt;dbl&gt;    &lt;dbl&gt; &lt;dbl&gt;    &lt;dbl&gt;     &lt;dbl&gt; &lt;int&gt;
##  1  -5.29  4.64  -0.294    7     14.4      9.9  43.2     13        86.9    40
##  2  -4.89  3.50   1.64     6.5   12.9     10.3  57.4     10.3      66      35
##  3  -4.64  5.33  -0.653    9.3   15.3     12.5  43.4     16.6      74      37
##  4  -4.57  2.19  -1.49     5.5   10.7      8.8  17       11.1      69.2    41
##  5  -4.48  2.11   1.90     6.8   11.5      8.9  50.5      6.8      61.2    34
##  6  -4.36  4.45   1.06     9.1   15.2     12.2  55.1     12.8      66      45
##  7  -3.82  2.24   0.532    7.8   12.9     10.7  34.8      8.1      62.8    39
##  8  -3.62  2.47  -0.992    7.7   13.9     11.3  20.1     10.3      66       4
##  9  -3.44  0.576 -2.10     5.7   11.4      8.4   0        9.8      51.5   363
## 10  -3.36  2.19  -0.705    9.1   13       11.3  20.3      9.3      62.8    38
## # … with 355 more rows</code></pre>
<p>Day 40 has the lowest component 1 score. This is one of the
cooler days. Also, there is a
largish amount of rain <em>and</em> wind. So low temperature, high
rain and wind.
Some of the other days on my list were cooler than day 4, but they
had less rain and less wind.</p>
<p><span class="math inline">\(\blacksquare\)</span></p>
<ol style="list-style-type: lower-roman">
<li>Find a day that scores high on component 2, and explain
briefly why it came out that way.</li>
</ol>
<p>Solution</p>
<div class="sourceCode" id="cb272"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb272-1" title="1">d <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">arrange</span>(<span class="kw">desc</span>(Comp<span class="fl">.2</span>))</a></code></pre></div>
<pre><code>## # A tibble: 365 x 10
##     Comp.1 Comp.2  Comp.3 l.temp h.temp ave.temp  rain ave.wind gust.wind   day
##      &lt;dbl&gt;  &lt;dbl&gt;   &lt;dbl&gt;  &lt;dbl&gt;  &lt;dbl&gt;    &lt;dbl&gt; &lt;dbl&gt;    &lt;dbl&gt;     &lt;dbl&gt; &lt;int&gt;
##  1 -4.64     5.33 -0.653     9.3   15.3     12.5  43.4     16.6      74      37
##  2 -5.29     4.64 -0.294     7     14.4      9.9  43.2     13        86.9    40
##  3 -4.36     4.45  1.06      9.1   15.2     12.2  55.1     12.8      66      45
##  4 -1.61     4.33  3.43     17.7   19.1     18.3  68.3      8.3      46.7   261
##  5 -1.02     3.63  1.36     16.8   20.4     19    39.1      6.9      59.5   289
##  6  2.42     3.51 -1.39     20.9   31.2     25.7   0        8.8      46.7   166
##  7 -4.89     3.50  1.64      6.5   12.9     10.3  57.4     10.3      66      35
##  8  0.0301   3.49 -0.0846   18.5   22.3     20.3  22.9     10.3      43.5   260
##  9 -0.745    3.45  1.99     15.9   21.4     19.9  46.2      7.7      45.1   281
## 10 -0.105    3.20 -0.493    17.9   21.8     19.5  16.5      9.3      49.9   290
## # … with 355 more rows</code></pre>
<p>Day 37. These are days when the wind speed (average or
gust) is on the high side.</p>
<p><span class="math inline">\(\blacksquare\)</span></p>
<ol start="10" style="list-style-type: lower-alpha">
<li>Find a day that scores high on component 3, and explain
briefly why it came out high.</li>
</ol>
<p>Solution</p>
<div class="sourceCode" id="cb274"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb274-1" title="1">d <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">arrange</span>(<span class="kw">desc</span>(Comp<span class="fl">.3</span>))</a></code></pre></div>
<pre><code>## # A tibble: 365 x 10
##     Comp.1 Comp.2 Comp.3 l.temp h.temp ave.temp  rain ave.wind gust.wind   day
##      &lt;dbl&gt;  &lt;dbl&gt;  &lt;dbl&gt;  &lt;dbl&gt;  &lt;dbl&gt;    &lt;dbl&gt; &lt;dbl&gt;    &lt;dbl&gt;     &lt;dbl&gt; &lt;int&gt;
##  1 -2.32    2.23    4.92   11.8   17.2     14.6  74.9      2.8      41.8   307
##  2 -2.79    2.31    3.64   11.3   14.7     13.5  64.8      5.6      41.8     2
##  3  0.0819  2.90    3.59   16.1   26.6     20.3  54.4      2        49.9   264
##  4 -1.61    4.33    3.43   17.7   19.1     18.3  68.3      8.3      46.7   261
##  5 -0.759   2.48    3.42   15.7   19.5     18.6  55.6      4.5      37     288
##  6 -2.21    3.12    2.15   12.8   17.7     15.8  50.5      7.2      53.1   317
##  7 -0.745   3.45    1.99   15.9   21.4     19.9  46.2      7.7      45.1   281
##  8 -4.48    2.11    1.90    6.8   11.5      8.9  50.5      6.8      61.2    34
##  9 -1.77    0.693   1.72   10.7   15.6     13    32.8      4        38.6   312
## 10 -4.89    3.50    1.64    6.5   12.9     10.3  57.4     10.3      66      35
## # … with 355 more rows</code></pre>
<p>Day 307. Component 3 was mainly rain, so it is not surprising that
the rainfall is the highest on this day.</p>
<p><span class="math inline">\(\blacksquare\)</span></p>
<ol start="11" style="list-style-type: lower-alpha">
<li>Make a biplot of these data, labelling the days by the day
count (from 1 to 365). You may have to get the day count from the
original data frame that you read in from the file. You can shrink
the day numbers to make them overwrite each other (a bit) less.</li>
</ol>
<p>Solution</p>
<p><code>ggbiplot</code>. I did some digging in the help file to figure
out how to label the points by a variable and how to control the
size of the labels, and I also went digging in the data frame
that I read in from the file to get the count of the day in the
year, which was called <code>day.count</code>:</p>
<div class="sourceCode" id="cb276"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb276-1" title="1"><span class="kw">ggbiplot</span>(weather<span class="fl">.1</span>, <span class="dt">labels =</span> weather<span class="fl">.0</span><span class="op">$</span>day.count, <span class="dt">labels.size =</span> <span class="dv">2</span>)</a></code></pre></div>
<p><img src="pasias_files/figure-html/weather-2014-15-1.png" width="672" /></p>
<p>I think the label text is small enough, though you could make it
smaller. I’ll be asking you to look at some extreme points in a
moment, so those are the only ones you’ll need to be able to
disentangle.</p>
<p>The variables divide into two groups: the temperature ones, that point
to about 2 o’clock, and the wind and rain ones, that point to about 11
o’clock. These are not straight up or down or across, so they all
feature in both components: component 1 is mostly temperature, but has
a bit of wind/rain in it, while component 2 is mostly wind/rain with a
bit of temperature in it. You might be wondering whether things
couldn’t be rotated so that, say, the temperature variables go across
and the rain/wind ones go down, which means you’d have a temperature
component and a rain/wind component. This is what factor analysis
does, and I think I did that earlier (and this is what we found).</p>
<p><span class="math inline">\(\blacksquare\)</span></p>
<ol start="12" style="list-style-type: lower-alpha">
<li>Looking at your biplot, what do you think was remarkable
about the weather on day 37? Day 211? Confirm your guesses by
looking at the appropriate rows of your data frame (and comparing
with your <code>summary</code> from earlier).</li>
</ol>
<p>Solution</p>
<p>Day 37 is at the top left of the plot, at the pointy end of
the arrows for rain, wind gust and average wind. This suggests a
rainy, windy day:</p>
<div class="sourceCode" id="cb277"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb277-1" title="1">weather <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">slice</span>(<span class="dv">37</span>)</a></code></pre></div>
<pre><code>## # A tibble: 1 x 6
##   l.temp h.temp ave.temp  rain ave.wind gust.wind
##    &lt;dbl&gt;  &lt;dbl&gt;    &lt;dbl&gt; &lt;dbl&gt;    &lt;dbl&gt;     &lt;dbl&gt;
## 1    9.3   15.3     12.5  43.4     16.6        74</code></pre>
<p>Those are high numbers for both rain and wind (the highest for average
wind and above the third quartile otherwise), but the temperatures
are unremarkable.</p>
<p>Day 211 is towards the pointy end of the arrows for temperature, so
this is a hot day:</p>
<div class="sourceCode" id="cb279"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb279-1" title="1">weather <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">slice</span>(<span class="dv">211</span>)</a></code></pre></div>
<pre><code>## # A tibble: 1 x 6
##   l.temp h.temp ave.temp  rain ave.wind gust.wind
##    &lt;dbl&gt;  &lt;dbl&gt;    &lt;dbl&gt; &lt;dbl&gt;    &lt;dbl&gt;     &lt;dbl&gt;
## 1   22.6   31.5     26.6     0      4.5      33.8</code></pre>
<p>This is actually the hottest day of the entire year: day 211 is
highest on all three temperatures, while the
wind speeds are right around average (and no rain is not completely
surprising).</p>
<p>I can do a couple more. Points away from the pointy end of the arrows
are <em>low</em> on the variables in question, for example day 265:</p>
<div class="sourceCode" id="cb281"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb281-1" title="1">weather <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">slice</span>(<span class="dv">265</span>)</a></code></pre></div>
<pre><code>## # A tibble: 1 x 6
##   l.temp h.temp ave.temp  rain ave.wind gust.wind
##    &lt;dbl&gt;  &lt;dbl&gt;    &lt;dbl&gt; &lt;dbl&gt;    &lt;dbl&gt;     &lt;dbl&gt;
## 1   16.6   20.3     18.1   6.3        0       3.2</code></pre>
<p>This is not really low rain, but it is definitely low
<em>wind</em>. What about day 47?</p>
<div class="sourceCode" id="cb283"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb283-1" title="1">weather <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">slice</span>(<span class="dv">47</span>)</a></code></pre></div>
<pre><code>## # A tibble: 1 x 6
##   l.temp h.temp ave.temp  rain ave.wind gust.wind
##    &lt;dbl&gt;  &lt;dbl&gt;    &lt;dbl&gt; &lt;dbl&gt;    &lt;dbl&gt;     &lt;dbl&gt;
## 1    3.1   11.8      7.3   0.8        2      24.1</code></pre>
<p>This is predominantly low on temperature. In fact, it is kind of low
on wind and rain too.<a href="#fn36" class="footnote-ref" id="fnref36"><sup>36</sup></a>
This makes sense, because not only is it at the “wrong” end of the
temperature arrows, it is kind of at the wrong end of the wind/rain
arrows as well.</p>
<p>Having done these by percentile ranks in one of the other questions,
let’s see if we can do that here as well:</p>
<div class="sourceCode" id="cb285"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb285-1" title="1">weather <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">mutate</span>(<span class="kw">across</span>(<span class="kw">everything</span>(), <span class="op">~</span><span class="kw">percent_rank</span>(.))) <span class="op">%&gt;%</span><span class="st"> </span></a>
<a class="sourceLine" id="cb285-2" title="2"><span class="st">    </span><span class="kw">slice</span>(<span class="kw">c</span>(<span class="dv">37</span>, <span class="dv">211</span>, <span class="dv">265</span>, <span class="dv">47</span>))</a></code></pre></div>
<pre><code>## # A tibble: 4 x 6
##   l.temp h.temp ave.temp  rain ave.wind gust.wind
##    &lt;dbl&gt;  &lt;dbl&gt;    &lt;dbl&gt; &lt;dbl&gt;    &lt;dbl&gt;     &lt;dbl&gt;
## 1  0.264 0.316     0.299 0.973    1         0.997
## 2  1     0.997     1     0        0.654     0.626
## 3  0.783 0.560     0.635 0.761    0         0    
## 4  0     0.0275    0     0.582    0.162     0.275</code></pre>
<p>The idea here is that we want to <em>replace</em> all the data values by the percent-rank version of themselves, rather than <em>summarizing</em> them as we have done before. That’s what using an <code>across</code> inside a <code>mutate</code> will do.<a href="#fn37" class="footnote-ref" id="fnref37"><sup>37</sup></a></p>
<p>These are:</p>
<ul>
<li><p>Day 37: highly rainy and windy (and below average,
but not remarkably so, on temperature).</p></li>
<li><p>Day 211: the highest or near-highest temperature, no rain but
unremarkable for wind.</p></li>
<li><p>Day 265: Lowest for wind (and above Q3 for low temperature and
rain).</p></li>
<li><p>Day 47: Lowest or near-lowest temperature.</p></li>
</ul>
<p>The advantage to doing it this way is that you don’t need a separate
five-number summary for each variable; the percentile ranks
<em>give</em> you a comparison with quartiles (or any other percentile
of interest to you).
In case you are wondering where this is: I was doing a presentation
using these data to some Environmental Science grad students, and I
had them guess where it was. The temperatures for the whole year are
warm-temperate, with a smallish range, and sometimes a lot of
rain. This suggests a maritime climate. I gave the additional clues of
“western Europe” and
“this place’s soccer team plays in blue and white striped shirts”.
The temperatures have about the right range
low-to-high for Britain, but are too warm. Which suggests going south:
perhaps Brittany in France, but actually the west
coast of the Iberian peninsula: Porto, in northern Portugal, with the
weather blowing in off the Atlantic.</p>
<p><span class="math inline">\(\blacksquare\)</span></p>

</div>
</div>
<div class="footnotes">
<hr />
<ol start="36">
<li id="fn36"><p>If you ignore the wind gust, anyway.<a href="principal-components.html#fnref36" class="footnote-back">↩</a></p></li>
<li id="fn37"><p>There are also options to keep the original variables, and to give the new ones new names.<a href="principal-components.html#fnref37" class="footnote-back">↩</a></p></li>
</ol>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="multidimensional-scaling.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="factor-analysis.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/lunr.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": null,
"text": null
},
"history": {
"link": null,
"text": null
},
"view": {
"link": null,
"text": null
},
"download": ["pasias.pdf"],
"toc": {
"collapse": "subsection"
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
