<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">

<head>

<meta charset="utf-8">
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<meta name="generator" content="pandoc" />
<meta name="viewport" content="width=device-width, initial-scale=1">
<meta property="og:title" content="Problems and Solutions in Applied Statistics" />
<meta property="og:type" content="book" />
<meta property="og:url" content="<a href="http://ritsokiguess.site/pasias" class="uri">http://ritsokiguess.site/pasias</a>" />

<meta property="og:description" content="A set of problems and solutions, in R, on various parts of applied statistics" />
<meta name="github-repo" content="nxskok/pasias" />

<meta name="author" content="Ken Butler" />

<meta name="date" content="2018-10-09" />

<script type="text/x-mathjax-config">
MathJax.Hub.Config({
  TeX: { equationNumbers: { autoNumber: "AMS" } }
});
</script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.2/MathJax.js?config=TeX-AMS_CHTML-full" type="text/javascript"></script>

<meta name="description" content="A set of problems and solutions, in R, on various parts of applied statistics">

<title>Problems and Solutions in Applied Statistics</title>

<link href="libs/tufte-css-2015.12.29/tufte-fonts.css" rel="stylesheet" />
<link href="libs/tufte-css-2015.12.29/tufte-background.css" rel="stylesheet" />
<link href="libs/tufte-css-2015.12.29/tufte-italics.css" rel="stylesheet" />
<link href="libs/tufte-css-2015.12.29/tufte.css" rel="stylesheet" />


<style type="text/css">code{white-space: pre;}</style>
<style type="text/css">
a.sourceLine { display: inline-block; line-height: 1.25; }
a.sourceLine { pointer-events: none; color: inherit; text-decoration: inherit; }
a.sourceLine:empty { height: 1.2em; position: absolute; }
.sourceCode { overflow: visible; }
code.sourceCode { white-space: pre; position: relative; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
code.sourceCode { white-space: pre-wrap; }
a.sourceLine { text-indent: -1em; padding-left: 1em; }
}
pre.numberSource a.sourceLine
  { position: relative; }
pre.numberSource a.sourceLine:empty
  { position: absolute; }
pre.numberSource a.sourceLine::before
  { content: attr(data-line-number);
    position: absolute; left: -5em; text-align: right; vertical-align: baseline;
    border: none; pointer-events: all;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {  }
@media screen {
a.sourceLine::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>


<link rel="stylesheet" href="toc.css" type="text/css" />

</head>

<body>



<div class="row">
<div class="col-sm-12">
<div id="TOC">
<ul>
<li><a href="index.html#introduction"><span class="toc-section-number">1</span> Introduction</a></li>
<li class="has-sub"><a href="getting-used-to-r-and-r-studio.html#getting-used-to-r-and-r-studio"><span class="toc-section-number">2</span> Getting used to R and R Studio</a><ul>
<li><a href="getting-used-to-r-and-r-studio.html#getting-an-r-studio-cloud-account"><span class="toc-section-number">2.1</span> Getting an R Studio Cloud account</a></li>
<li><a href="getting-used-to-r-and-r-studio.html#getting-started"><span class="toc-section-number">2.2</span> Getting started</a></li>
<li><a href="getting-used-to-r-and-r-studio.html#reading-data-from-a-file"><span class="toc-section-number">2.3</span> Reading data from a file</a></li>
</ul></li>
<li class="has-sub"><a href="reading-in-data-and-drawing-some-graphs.html#reading-in-data-and-drawing-some-graphs"><span class="toc-section-number">3</span> Reading in data and drawing some graphs</a><ul>
<li><a href="reading-in-data-and-drawing-some-graphs.html#orange-juice"><span class="toc-section-number">3.1</span> Orange juice</a></li>
<li><a href="reading-in-data-and-drawing-some-graphs.html#making-soap"><span class="toc-section-number">3.2</span> Making soap</a></li>
<li><a href="reading-in-data-and-drawing-some-graphs.html#handling-shipments"><span class="toc-section-number">3.3</span> Handling shipments</a></li>
</ul></li>
<li class="has-sub"><a href="data-exploration.html#data-exploration"><span class="toc-section-number">4</span> Data exploration</a><ul>
<li><a href="data-exploration.html#north-carolina-births"><span class="toc-section-number">4.1</span> North Carolina births</a></li>
<li><a href="data-exploration.html#more-about-the-nc-births"><span class="toc-section-number">4.2</span> More about the NC births</a></li>
<li><a href="data-exploration.html#nenana-alaska"><span class="toc-section-number">4.3</span> Nenana, Alaska</a></li>
<li><a href="data-exploration.html#computerized-accounting"><span class="toc-section-number">4.4</span> Computerized accounting</a></li>
</ul></li>
<li class="has-sub"><a href="one-sample-inference.html#one-sample-inference"><span class="toc-section-number">5</span> One-sample inference</a><ul>
<li><a href="one-sample-inference.html#hunter-gatherers-in-australia"><span class="toc-section-number">5.1</span> Hunter-gatherers in Australia</a></li>
<li><a href="one-sample-inference.html#length-of-gestation-in-north-carolina"><span class="toc-section-number">5.2</span> Length of gestation in North Carolina</a></li>
<li><a href="one-sample-inference.html#inferring-ice-break-up-in-nenana"><span class="toc-section-number">5.3</span> Inferring ice break-up in Nenana</a></li>
</ul></li>
<li class="has-sub"><a href="two-sample-inference.html#two-sample-inference"><span class="toc-section-number">6</span> Two-sample inference</a><ul>
<li><a href="two-sample-inference.html#children-and-electronic-devices"><span class="toc-section-number">6.1</span> Children and electronic devices</a></li>
<li><a href="two-sample-inference.html#parking-close-to-the-curb"><span class="toc-section-number">6.2</span> Parking close to the curb</a></li>
</ul></li>
<li class="has-sub"><a href="power-and-sample-size.html#power-and-sample-size"><span class="toc-section-number">7</span> Power and sample size</a><ul>
<li><a href="power-and-sample-size.html#simulating-power"><span class="toc-section-number">7.1</span> Simulating power</a></li>
<li><a href="power-and-sample-size.html#calculating-power-and-sample-size-for-estimating-mean"><span class="toc-section-number">7.2</span> Calculating power and sample size for estimating mean</a></li>
<li><a href="power-and-sample-size.html#simulating-power-for-proportions"><span class="toc-section-number">7.3</span> Simulating power for proportions</a></li>
</ul></li>
<li class="has-sub"><a href="the-sign-test-and-moods-median-test.html#the-sign-test-and-moods-median-test"><span class="toc-section-number">8</span> The sign test and Mood’s median test</a><ul>
<li><a href="the-sign-test-and-moods-median-test.html#running-a-maze"><span class="toc-section-number">8.1</span> Running a maze</a></li>
<li><a href="the-sign-test-and-moods-median-test.html#chocolate-chips"><span class="toc-section-number">8.2</span> Chocolate chips</a></li>
<li><a href="the-sign-test-and-moods-median-test.html#the-power-of-the-sign-test"><span class="toc-section-number">8.3</span> The power of the sign test</a></li>
<li><a href="the-sign-test-and-moods-median-test.html#sugar-in-breakfast-cereals"><span class="toc-section-number">8.4</span> Sugar in breakfast cereals</a></li>
<li><a href="the-sign-test-and-moods-median-test.html#fear-of-math"><span class="toc-section-number">8.5</span> Fear of math</a></li>
<li><a href="the-sign-test-and-moods-median-test.html#medical-instructions"><span class="toc-section-number">8.6</span> Medical instructions</a></li>
</ul></li>
<li class="has-sub"><a href="matched-pairs-t-and-sign-test.html#matched-pairs-t-and-sign-test"><span class="toc-section-number">9</span> Matched pairs t and sign test</a><ul>
<li><a href="matched-pairs-t-and-sign-test.html#measuring-body-fat"><span class="toc-section-number">9.1</span> Measuring body fat</a></li>
<li><a href="matched-pairs-t-and-sign-test.html#throwing-baseballs-and-softballs"><span class="toc-section-number">9.2</span> Throwing baseballs and softballs</a></li>
<li><a href="matched-pairs-t-and-sign-test.html#changes-in-salary"><span class="toc-section-number">9.3</span> Changes in salary</a></li>
</ul></li>
<li class="has-sub"><a href="normal-quantile-plots.html#normal-quantile-plots"><span class="toc-section-number">10</span> Normal quantile plots</a><ul>
<li><a href="normal-quantile-plots.html#lengths-of-heliconia-flowers"><span class="toc-section-number">10.1</span> Lengths of heliconia flowers</a></li>
<li><a href="normal-quantile-plots.html#ferritin-and-normality"><span class="toc-section-number">10.2</span> Ferritin and normality</a></li>
</ul></li>
<li class="has-sub"><a href="analysis-of-variance.html#analysis-of-variance"><span class="toc-section-number">11</span> Analysis of variance</a><ul>
<li><a href="analysis-of-variance.html#movie-ratings-and-lengths"><span class="toc-section-number">11.1</span> Movie ratings and lengths</a></li>
<li><a href="analysis-of-variance.html#deer-and-how-much-they-eat"><span class="toc-section-number">11.2</span> Deer and how much they eat</a></li>
<li><a href="analysis-of-variance.html#movie-ratings-again"><span class="toc-section-number">11.3</span> Movie ratings again</a></li>
<li><a href="analysis-of-variance.html#atomic-weight-of-carbon"><span class="toc-section-number">11.4</span> Atomic weight of carbon</a></li>
</ul></li>
<li class="has-sub"><a href="tidying-and-selecting-data.html#tidying-and-selecting-data"><span class="toc-section-number">12</span> Tidying and selecting data</a><ul>
<li><a href="tidying-and-selecting-data.html#tidying-the-jays-data"><span class="toc-section-number">12.1</span> Tidying the Jays data</a></li>
<li><a href="tidying-and-selecting-data.html#ethanol-and-sleep-time-in-rats"><span class="toc-section-number">12.2</span> Ethanol and sleep time in rats</a></li>
<li><a href="tidying-and-selecting-data.html#growth-of-tomatoes"><span class="toc-section-number">12.3</span> Growth of tomatoes</a></li>
<li><a href="tidying-and-selecting-data.html#pain-relief-in-migraine-headaches-again"><span class="toc-section-number">12.4</span> Pain relief in migraine headaches (again)</a></li>
<li><a href="tidying-and-selecting-data.html#location-species-and-disease-in-plants"><span class="toc-section-number">12.5</span> Location, species and disease in plants</a></li>
<li><a href="tidying-and-selecting-data.html#kens-cars"><span class="toc-section-number">12.6</span> Ken’s cars</a></li>
<li><a href="tidying-and-selecting-data.html#number-1-songs"><span class="toc-section-number">12.7</span> Number 1 songs</a></li>
</ul></li>
<li class="has-sub"><a href="regression.html#regression"><span class="toc-section-number">13</span> Regression</a><ul>
<li><a href="regression.html#facebook-friends-and-grey-matter"><span class="toc-section-number">13.1</span> Facebook friends and grey matter</a></li>
<li><a href="regression.html#endogenous-nitrogen-excretion-in-carp"><span class="toc-section-number">13.2</span> Endogenous nitrogen excretion in carp</a></li>
<li><a href="regression.html#sparrowhawks"><span class="toc-section-number">13.3</span> Sparrowhawks</a></li>
</ul></li>
<li class="has-sub"><a href="the-data.html#the-data"><span class="toc-section-number">14</span> The data</a><ul>
<li><a href="the-data.html#exploratory-analysis"><span class="toc-section-number">14.0.1</span> Exploratory analysis</a></li>
<li><a href="the-data.html#regression-analysis"><span class="toc-section-number">14.0.2</span> Regression analysis</a></li>
<li><a href="the-data.html#conclusions"><span class="toc-section-number">14.0.3</span> Conclusions</a></li>
<li><a href="the-data.html#salaries-of-social-workers"><span class="toc-section-number">14.1</span> Salaries of social workers</a></li>
<li><a href="the-data.html#predicting-volume-of-wood-in-pine-trees"><span class="toc-section-number">14.2</span> Predicting volume of wood in pine trees</a></li>
</ul></li>
</ul>
</div>
</div>
</div>
<div class="row">
<div class="col-sm-12">
<div id="regression" class="section level1">
<h1><span class="header-section-number">Chapter 13</span> Regression</h1>
<div class="sourceCode" id="cb897"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb897-1" data-line-number="1"><span class="kw">library</span>(tidyverse)</a></code></pre></div>
<pre><code>## ── Attaching packages ────────────────────────────────── tidyverse 1.2.1 ──</code></pre>
<pre><code>## ✔ ggplot2 3.0.0     ✔ purrr   0.2.5
## ✔ tibble  1.4.2     ✔ dplyr   0.7.6
## ✔ tidyr   0.8.1     ✔ stringr 1.3.1
## ✔ readr   1.1.1     ✔ forcats 0.3.0</code></pre>
<pre><code>## ── Conflicts ───────────────────────────────────── tidyverse_conflicts() ──
## ✖ dplyr::filter() masks stats::filter()
## ✖ dplyr::lag()    masks stats::lag()</code></pre>
<div id="facebook-friends-and-grey-matter" class="section level2">
<h2><span class="header-section-number">13.1</span> Facebook friends and grey matter</h2>
<p>Is there a relationship between the number
of Facebook friends a person has, and the density of grey matter in
the areas of the brain associated with social perception and
associative memory? To find out, a 2012 study measured both of these
variables for a sample of 40 students at City University in London
(England). The data are at
<a href="http://www.utsc.utoronto.ca/~butler/c32/facebook.txt" class="uri">http://www.utsc.utoronto.ca/~butler/c32/facebook.txt</a>. The grey
matter density is on a <span class="math inline">\(z\)</span>-score standardized scale. The values are
separated by <em>tabs</em>.</p>
<p>The aim of this question is to produce an R Markdown report that
contains your answers to the questions below.</p>
<p>You should aim to make your report flow smoothly, so that it would be
pleasant for a grader to read, and can stand on its own as an analysis
(rather than just being the answer to a question that I set you).
Some suggestions: give your report a title and arrange it into
sections with an Introduction; add a small amount of additional text
here and there explaining what you are doing and why. I don’t expect
you to spend a large amount of time on this, but I <em>do</em> hope
you will make some effort. (My report came out to 4 Word pages.)</p>
<ol style="list-style-type: lower-alpha">
<li>Read in the data and make a scatterplot for predicting the
number of Facebook friends from the grey matter density. On your
scatterplot, add a smooth trend.</li>
</ol>
<p>Solution</p>
<p>Begin your document with a code chunk containing
<code>library(tidyverse)</code>. The data values are
separated by tabs, which you will need to take into account:</p>
<div class="sourceCode" id="cb901"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb901-1" data-line-number="1">my_url=<span class="st">&quot;http://www.utsc.utoronto.ca/~butler/c32/facebook.txt&quot;</span></a>
<a class="sourceLine" id="cb901-2" data-line-number="2">fb=<span class="kw">read_tsv</span>(my_url)</a></code></pre></div>
<pre><code>## Parsed with column specification:
## cols(
##   GMdensity = col_double(),
##   FBfriends = col_integer()
## )</code></pre>
<div class="sourceCode" id="cb903"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb903-1" data-line-number="1">fb</a></code></pre></div>
<pre><code>## # A tibble: 40 x 2
##    GMdensity FBfriends
##        &lt;dbl&gt;     &lt;int&gt;
##  1      -1.8        23
##  2       0.1        35
##  3      -1.2        80
##  4      -0.4       110
##  5      -0.9       120
##  6      -2.1       140
##  7      -1.5       168
##  8       0.5       132
##  9       0.6       154
## 10      -0.5       241
## # ... with 30 more rows</code></pre>
<div class="sourceCode" id="cb905"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb905-1" data-line-number="1"><span class="kw">ggplot</span>(fb,<span class="kw">aes</span>(<span class="dt">x=</span>GMdensity,<span class="dt">y=</span>FBfriends))<span class="op">+</span><span class="kw">geom_point</span>()<span class="op">+</span><span class="kw">geom_smooth</span>()</a></code></pre></div>
<pre><code>## `geom_smooth()` using method = &#39;loess&#39; and formula &#39;y ~ x&#39;</code></pre>
<p><img src="12-regression_files/figure-html/unnamed-chunk-2-1.png" width="672"  /></p>
<ol start="2" style="list-style-type: lower-alpha">
<li>Describe what you see on your scatterplot: is there a
trend, and if so, what kind of trend is it? (Don’t get too taken in
by the exact shape of your smooth trend.) Think ``form, direction,
strength’’.</li>
</ol>
<p>Solution</p>
<p>I’d say there seems to be a weak, upward, apparently linear
trend. The points are not especially close to the trend, so I
don’t think there’s any justification for calling this other
than “weak”. (If you think the trend is, let’s say,
“moderate”, you ought to say what makes you think that: for
example, that the people with a lot of Facebook friends also
tend to have a higher grey matter density. I can live with a
reasonably-justified “moderate”.)
The reason I said not to get taken in by the shape of the smooth
trend is that this has a “wiggle” in it: it goes down again
briefly in the middle. But this is likely a quirk of the data,
and the trend, if there is any, seems to be an upward one.</p>
<ol start="3" style="list-style-type: lower-alpha">
<li>Fit a regression predicting the number of Facebook friends
from the grey matter density, and display the output.</li>
</ol>
<p>Solution</p>
<p>That looks like this. You can call the “fitted model object”
whatever you like, but you’ll need to get the capitalization of
the variable names correct:</p>
<div class="sourceCode" id="cb907"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb907-1" data-line-number="1">fb<span class="fl">.1</span>=<span class="kw">lm</span>(FBfriends<span class="op">~</span>GMdensity,<span class="dt">data=</span>fb)</a>
<a class="sourceLine" id="cb907-2" data-line-number="2"><span class="kw">summary</span>(fb<span class="fl">.1</span>)</a></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = FBfriends ~ GMdensity, data = fb)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -339.89 -110.01   -5.12   99.80  303.64 
## 
## Coefficients:
##             Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)   366.64      26.35  13.916  &lt; 2e-16 ***
## GMdensity      82.45      27.58   2.989  0.00488 ** 
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 165.7 on 38 degrees of freedom
## Multiple R-squared:  0.1904, Adjusted R-squared:  0.1691 
## F-statistic: 8.936 on 1 and 38 DF,  p-value: 0.004882</code></pre>
<p>I observe, though I didn’t ask you to, that the R-squared is pretty
awful, going with a correlation of</p>
<div class="sourceCode" id="cb909"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb909-1" data-line-number="1"><span class="kw">sqrt</span>(<span class="fl">0.1904</span>)</a></code></pre></div>
<pre><code>## [1] 0.4363485</code></pre>
<p>which <em>would</em> look
like as weak of a trend as we saw.
<label for="tufte-mn-36" class="margin-toggle">⊕</label><input type="checkbox" id="tufte-mn-36" class="margin-toggle"><span class="marginnote">Correlations have to go up beyond 0.50 before they start looking at all interesting.</span></p>
<ol start="4" style="list-style-type: lower-alpha">
<li>Is the slope of your regression line significantly
different from zero? What does that mean, in the context of the
data?</li>
</ol>
<p>Solution</p>
<p>The P-value of the slope is 0.005, which is less than
0.05. Therefore the slope <em>is</em> significantly different from
zero. That means that the number of Facebook friends really does
depend on the grey matter density, for the whole population of
interest and not just the 40 students observed here (that were a
sample from that population). I don’t mind so much what you
think the population is, but it needs to be clear that the
relationship applies to a population.
Another way to approach this is to say that you would expect
this relationship to show up again in another similar
experiment. That also works, because it gets at the idea of
reproducibility.</p>
<ol start="5" style="list-style-type: lower-alpha">
<li>Are you surprised by the results of
parts (b) and (d)? Explain briefly.</li>
</ol>
<p>Solution</p>
<p>I <em>am</em> surprised, because I thought the trend on the
scatterplot was so weak that there would not be a significant
slope. I guess there was enough of an upward trend to be
significant, and with <span class="math inline">\(n=40\)</span> observations we were able to get a
significant slope out of that scatterplot. With this many
observations, even a weak correlation can be significantly
nonzero.
You can be surprised or not, but you need to have some kind of
consideration of the strength of the trend on the scatterplot as
against the significance of the slope. For example, if you
decided that the trend was “moderate” in strength, you would
be justified in being less surprised than I was.
Here, there is the usual issue that we have proved that the
slope is not zero (that the relationship is not flat), but we
may not have a very clear idea of what the slope actually
<em>is</em>. There are a couple of ways to get a confidence
interval. The obvious one is to use R as a calculator and go up
and down twice its standard error (to get a rough idea):</p>
<div class="sourceCode" id="cb911"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb911-1" data-line-number="1"><span class="fl">82.45</span><span class="op">+</span><span class="dv">2</span><span class="op">*</span><span class="fl">27.58</span><span class="op">*</span><span class="kw">c</span>(<span class="op">-</span><span class="dv">1</span>,<span class="dv">1</span>)</a></code></pre></div>
<pre><code>## [1]  27.29 137.61</code></pre>
<p>The <code>c()</code> thing is to get both confidence limits at once. The
smoother way is this:</p>
<div class="sourceCode" id="cb913"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb913-1" data-line-number="1"><span class="kw">confint</span>(fb<span class="fl">.1</span>)</a></code></pre></div>
<pre><code>##                 2.5 %   97.5 %
## (Intercept) 313.30872 419.9810
## GMdensity    26.61391 138.2836</code></pre>
<p>Feed <code>confint</code> a “fitted model object” and it’ll give you
confidence intervals (by default 95%) for all the parameters in it.</p>
<p>The confidence interval for the slope goes from about 27 to about
138. That is to say, a one-unit increase in grey matter density goes
with an increase in Facebook friends of this much. This is not
especially insightful: it’s bigger than zero (the test was
significant), but other than that, it could be almost
anything. <em>This</em> is where the weakness of the trend comes back to
bite us. With this much scatter in our data, we need a <em>much</em>
larger sample size to estimate accurately how big an effect grey
matter density has.</p>
<ol start="6" style="list-style-type: lower-alpha">
<li>Obtain a scatterplot with the regression line on it.</li>
</ol>
<p>Solution</p>
<p>Just a modification
of (a):</p>
<div class="sourceCode" id="cb915"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb915-1" data-line-number="1"><span class="kw">ggplot</span>(fb,<span class="kw">aes</span>(<span class="dt">x=</span>GMdensity,<span class="dt">y=</span>FBfriends))<span class="op">+</span><span class="kw">geom_point</span>()<span class="op">+</span></a>
<a class="sourceLine" id="cb915-2" data-line-number="2"><span class="kw">geom_smooth</span>(<span class="dt">method=</span><span class="st">&quot;lm&quot;</span>)</a></code></pre></div>
<p><img src="12-regression_files/figure-html/unnamed-chunk-7-1.png" width="672"  /></p>
<ol start="7" style="list-style-type: lower-alpha">
<li>Obtain a plot of the residuals from the regression against
the fitted values, and comment briefly on it.</li>
</ol>
<p>Solution</p>
<p>This is, to my mind, the easiest way:</p>
<div class="sourceCode" id="cb916"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb916-1" data-line-number="1"><span class="kw">ggplot</span>(fb<span class="fl">.1</span>,<span class="kw">aes</span>(<span class="dt">x=</span>.fitted,<span class="dt">y=</span>.resid))<span class="op">+</span><span class="kw">geom_point</span>()</a></code></pre></div>
<p><img src="12-regression_files/figure-html/unnamed-chunk-8-1.png" width="672"  /></p>
<p>There is some “magic” here, since the fitted model object is not
actually a data frame, but it works this way.
That looks to me like a completely random scatter of
points. Thus, I am completely happy with the straight-line regression
that we fitted, and I see no need to improve it.</p>
<p>(You should make two points here: one, describe what you see, and two,
what it implies about whether or not your regression is satisfactory.)</p>
<p>Compare that residual plot with this one:</p>
<div class="sourceCode" id="cb917"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb917-1" data-line-number="1"><span class="kw">ggplot</span>(fb<span class="fl">.1</span>,<span class="kw">aes</span>(<span class="dt">x=</span>.fitted,<span class="dt">y=</span>.resid))<span class="op">+</span></a>
<a class="sourceLine" id="cb917-2" data-line-number="2"><span class="kw">geom_point</span>()<span class="op">+</span><span class="kw">geom_smooth</span>()</a></code></pre></div>
<pre><code>## `geom_smooth()` using method = &#39;loess&#39; and formula &#39;y ~ x&#39;</code></pre>
<p><img src="12-regression_files/figure-html/unnamed-chunk-9-1.png" width="672"  />
Now, why did I try adding a smooth trend, and why is it not
necessarily a good idea? The idea of a residual plot is that there
should be no trend, and so the smooth trend curve ought to go straight
across. The problem is that it will tend to wiggle, just by chance, as
here: it looks as if it goes up and down before flattening out. But if
you look at the points, <em>they</em> are all over the place, not close
to the smooth trend at all. So the smooth trend is rather
deceiving. Or, to put it another way, to indicate a real problem, the
smooth trend would have to be a <em>lot</em> farther from flat than this
one is. I’d call this one basically flat.</p>
</div>
<div id="endogenous-nitrogen-excretion-in-carp" class="section level2">
<h2><span class="header-section-number">13.2</span> Endogenous nitrogen excretion in carp</h2>
<p>A paper in Fisheries Science reported on variables that
affect “endogenous nitrogen excretion” or ENE in carp raised in
Japan. A number of carp were divided into groups based on body weight,
and each group was placed in a different tank. The mean body weight of
the carp placed in each tank was recorded. The carp were then fed a
protein-free diet three times daily for a period of 20 days. At the
end of the experiment, the amount of ENE in each tank was measured, in
milligrams of total fish body weight per day. (Thus it should not
matter that some of the tanks had more fish than others, because the
scaling is done properly.)</p>
<p>For this question, write a report in R Markdown that answers the
questions below and contains some narrative that describes your
analysis. Create an HTML document from your R Markdown.</p>
<ol style="list-style-type: lower-alpha">
<li>Read the data in from
<a href="http://www.utsc.utoronto.ca/~butler/c32/carp.txt" class="uri">http://www.utsc.utoronto.ca/~butler/c32/carp.txt</a>. There are 10
tanks.</li>
</ol>
<p>Solution</p>
<p>Just this. Listing the data is up to you, but doing so and
commenting that the values appear to be correct will improve your report.</p>
<div class="sourceCode" id="cb919"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb919-1" data-line-number="1">my_url=<span class="st">&quot;http://www.utsc.utoronto.ca/~butler/c32/carp.txt&quot;</span></a>
<a class="sourceLine" id="cb919-2" data-line-number="2">carp=<span class="kw">read_delim</span>(my_url,<span class="st">&quot; &quot;</span>)  </a></code></pre></div>
<pre><code>## Parsed with column specification:
## cols(
##   tank = col_integer(),
##   bodyweight = col_double(),
##   ENE = col_double()
## )</code></pre>
<div class="sourceCode" id="cb921"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb921-1" data-line-number="1">carp</a></code></pre></div>
<pre><code>## # A tibble: 10 x 3
##     tank bodyweight   ENE
##    &lt;int&gt;      &lt;dbl&gt; &lt;dbl&gt;
##  1     1       11.7  15.3
##  2     2       25.3   9.3
##  3     3       90.2   6.5
##  4     4      213     6  
##  5     5       10.2  15.7
##  6     6       17.6  10  
##  7     7       32.6   8.6
##  8     8       81.3   6.4
##  9     9      142.    5.6
## 10    10      286.    6</code></pre>
<ol start="2" style="list-style-type: lower-alpha">
<li>Create a scatterplot of ENE (response) against bodyweight
(explanatory). Add a smooth trend to your plot.</li>
</ol>
<p>Solution</p>
<div class="sourceCode" id="cb923"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb923-1" data-line-number="1"><span class="kw">ggplot</span>(carp,<span class="kw">aes</span>(<span class="dt">x=</span>bodyweight,<span class="dt">y=</span>ENE))<span class="op">+</span><span class="kw">geom_point</span>()<span class="op">+</span></a>
<a class="sourceLine" id="cb923-2" data-line-number="2"><span class="kw">geom_smooth</span>()</a></code></pre></div>
<pre><code>## `geom_smooth()` using method = &#39;loess&#39; and formula &#39;y ~ x&#39;</code></pre>
<p><img src="12-regression_files/figure-html/unnamed-chunk-11-1.png" width="672"  /></p>
<p>This part is just about getting the plot. Comments are coming in a
minute. Note that <code>ENE</code> is capital letters, so that
<code>ene</code> will not work.</p>
<ol start="3" style="list-style-type: lower-alpha">
<li>Is there an upward or downward trend (or neither)? Is the
relationship a line or a curve? Explain briefly.</li>
</ol>
<p>Solution</p>
<p>The trend is downward: as bodyweight increases, ENE
decreases. However, the decrease is rapid at first and then levels
off, so the relationship is nonlinear. I want some kind of
support for an assertion of non-linearity: anything that says that
the slope or rate of decrease is not constant is good.</p>
<ol start="4" style="list-style-type: lower-alpha">
<li>Fit a straight line to the data, and obtain the R-squared
for the regression.</li>
</ol>
<p>Solution</p>
<p><code>lm</code>. The first stage is to fit the straight line, saving
the result in a variable, and the second stage is to look at the
“fitted model object”, here via <code>summary</code>:</p>
<div class="sourceCode" id="cb925"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb925-1" data-line-number="1">carp<span class="fl">.1</span>=<span class="kw">lm</span>(ENE<span class="op">~</span>bodyweight,<span class="dt">data=</span>carp)</a>
<a class="sourceLine" id="cb925-2" data-line-number="2"><span class="kw">summary</span>(carp<span class="fl">.1</span>)</a></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = ENE ~ bodyweight, data = carp)
## 
## Residuals:
##    Min     1Q Median     3Q    Max 
## -2.800 -1.957 -1.173  1.847  4.572 
## 
## Coefficients:
##             Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept) 11.40393    1.31464   8.675 2.43e-05 ***
## bodyweight  -0.02710    0.01027  -2.640   0.0297 *  
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 2.928 on 8 degrees of freedom
## Multiple R-squared:  0.4656, Adjusted R-squared:  0.3988 
## F-statistic: 6.971 on 1 and 8 DF,  p-value: 0.0297</code></pre>
<p>Finally, you need to give me a (suitably rounded) value for
R-squared: 46.6% or 47% or the equivalents as a decimal. I just
need the value at this point.
This kind of R-squared is actually pretty good for natural data, but
the issue is whether we can improve it by fitting a non-linear
model.</p>
<ol start="5" style="list-style-type: lower-alpha">
<li>Obtain a residual plot (residuals against fitted values)
for this regression. Do you see any problems? If so, what does that
tell you about the relationship in the data?</li>
</ol>
<p>Solution</p>
<p>This is the easiest way: feed the output of the regression
straight into <code>ggplot</code>:</p>
<div class="sourceCode" id="cb927"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb927-1" data-line-number="1"><span class="kw">ggplot</span>(carp<span class="fl">.1</span>,<span class="kw">aes</span>(<span class="dt">x=</span>.fitted,<span class="dt">y=</span>.resid))<span class="op">+</span><span class="kw">geom_point</span>()</a></code></pre></div>
<p><img src="12-regression_files/figure-html/unnamed-chunk-13-1.png" width="672"  /></p>
<ol start="6" style="list-style-type: lower-alpha">
<li>Fit a parabola to the data (that is, including an
<span class="math inline">\(x\)</span>-squared term). Compare the R-squared values for the models in
this part and part (????). Does that suggest that the parabola
model is an improvement here over the linear model?</li>
</ol>
<p>Solution</p>
<p>Add bodyweight-squared to
the regression. Don’t forget the <code>I()</code>:</p>
<div class="sourceCode" id="cb928"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb928-1" data-line-number="1">carp<span class="fl">.2</span>=<span class="kw">lm</span>(ENE<span class="op">~</span>bodyweight<span class="op">+</span><span class="kw">I</span>(bodyweight<span class="op">^</span><span class="dv">2</span>),<span class="dt">data=</span>carp)</a>
<a class="sourceLine" id="cb928-2" data-line-number="2"><span class="kw">summary</span>(carp<span class="fl">.2</span>)</a></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = ENE ~ bodyweight + I(bodyweight^2), data = carp)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -2.0834 -1.7388 -0.5464  1.3841  2.9976 
## 
## Coefficients:
##                   Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)     13.7127373  1.3062494  10.498 1.55e-05 ***
## bodyweight      -0.1018390  0.0288109  -3.535  0.00954 ** 
## I(bodyweight^2)  0.0002735  0.0001016   2.692  0.03101 *  
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 2.194 on 7 degrees of freedom
## Multiple R-squared:  0.7374, Adjusted R-squared:  0.6624 
## F-statistic: 9.829 on 2 and 7 DF,  p-value: 0.009277</code></pre>
<p>R-squared has gone up from 47% to 74%, a substantial
improvement. This suggests to me that the parabola model is a
substantial improvement.</p>
<p>I try to avoid using the word “significant” in this context, since
we haven’t actually done a test of significance.</p>
<p>The reason for the <code>I()</code> is that the up-arrow has a special
meaning in <code>lm</code>, relating to interactions between factors (as
in ANOVA), that we don’t want here. Putting <code>I()</code> around it
means “use as is”, that is, raise bodyweight to power 2, rather than
using the special meaning of the up-arrow in <code>lm</code>.</p>
<p>Because it’s the up-arrow that is the problem, this applies whenever
you’re raising an explanatory variable to a power (or taking a
reciprocal or a square root, say).</p>
<ol start="7" style="list-style-type: lower-alpha">
<li>Is the test for the slope coefficient for the squared term
significant? What does this mean?</li>
</ol>
<p>Solution</p>
<p>Look along the <code>bodyweight</code>-squared line to get a P-value
of 0.031. This is less than the default 0.05, so it <em>is</em>
significant.
This means, in short, that the quadratic model is a significant
<em>improvement</em> over the linear one.
Said longer: the null hypothesis being tested is that the slope
coefficient of the squared term is zero (that is, that the squared
term has nothing to add over the linear model). This is rejected,
so the squared term has <em>something</em> to add in terms of
quality of prediction.</p>
<ol start="8" style="list-style-type: lower-alpha">
<li>Make the scatterplot of part (????), but add
the fitted curve. Describe any way in which the curve fails to fit well.</li>
</ol>
<p>Solution</p>
<p>This is a bit slippery, because the points to plot and the
fitted curve are from different data frames. What you do in this
case is to put a <code>data=</code> in one of the <code>geom</code>s,
which says `<code>don't use the data frame that was in the</code>ggplot<code>, but use this one instead''. I would think about starting with the regression object</code>carp.2` as my base
data frame, since we want (or I want) to do two things with
that: plot the fitted values and join them with lines. Then I
want to add the original data, just the points:</p>
<div class="sourceCode" id="cb930"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb930-1" data-line-number="1"><span class="kw">ggplot</span>(carp<span class="fl">.2</span>,<span class="kw">aes</span>(<span class="dt">x=</span>carp<span class="op">$</span>bodyweight,<span class="dt">y=</span>.fitted),<span class="dt">colour=</span><span class="st">&quot;blue&quot;</span>)<span class="op">+</span></a>
<a class="sourceLine" id="cb930-2" data-line-number="2"><span class="kw">geom_line</span>(<span class="dt">colour=</span><span class="st">&quot;blue&quot;</span>)<span class="op">+</span></a>
<a class="sourceLine" id="cb930-3" data-line-number="3"><span class="kw">geom_point</span>(<span class="dt">data=</span>carp,<span class="kw">aes</span>(<span class="dt">x=</span>bodyweight,<span class="dt">y=</span>ENE))</a></code></pre></div>
<p><img src="12-regression_files/figure-html/unnamed-chunk-15-1.png" width="672"  />
$ %$ %$</p>
<p>This works, but is not very aesthetic, because the bodyweight that is
plotted against the fitted values is in the wrong data frame, and so
we have to use the dollar-sign thing to get it from the right one.</p>
<p>A better way around this is “fortify” the regression object. What
that means, in the context of <code>ggplot</code>, is to add the original
data back onto the regression object, so that we can plot any
combination of original data and values derived from the
regression. That goes like this:</p>
<div class="sourceCode" id="cb931"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb931-1" data-line-number="1">carp.<span class="fl">2.</span>fort=<span class="kw">fortify</span>(carp<span class="fl">.2</span>)</a>
<a class="sourceLine" id="cb931-2" data-line-number="2">carp.<span class="fl">2.</span>fort</a></code></pre></div>
<pre><code>##     ENE bodyweight I(bodyweight^2)      .hat   .sigma    .cooksd   .fitted
## 1  15.3       11.7          136.89 0.2392022 1.992810 0.21499558 12.558657
## 2   9.3       25.3          640.09 0.1629840 2.193651 0.06514640 11.311261
## 3   6.5       90.2         8136.04 0.2396677 2.367208 0.00182089  6.751885
## 4   6.0      213.0           45369 0.3246419 2.237874 0.12169479  4.428445
## 5  15.7       10.2          104.04 0.2511559 1.902036 0.27859605 12.702432
## 6  10.0       17.6          309.76 0.1993691 2.186473 0.08656338 12.005083
## 7   8.6       32.6         1062.76 0.1425478 2.184918 0.05826041 10.683427
## 8   6.4       81.3         6609.69 0.2112076 2.338418 0.01661407  7.240829
## 9   5.6      141.5        20022.25 0.3546865 2.333053 0.03982493  4.778159
## 10  6.0      285.7        81624.49 0.8745372 2.108136 3.39715895  6.939822
##        .resid  .stdresid
## 1   2.7413428  1.4322784
## 2  -2.0112607 -1.0018443
## 3  -0.2518851 -0.1316435
## 4   1.5715555  0.8714880
## 5   2.9975680  1.5785999
## 6  -2.0050832 -1.0212098
## 7  -2.0834268 -1.0253497
## 8  -0.8408294 -0.4314448
## 9   0.8218410  0.4662310
## 10 -0.9398221 -1.2091687</code></pre>
<p>so now you see what <code>carp.2.fort</code> has in it, and then:</p>
<div class="sourceCode" id="cb933"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb933-1" data-line-number="1">g=<span class="kw">ggplot</span>(carp.<span class="fl">2.</span>fort,<span class="kw">aes</span>(<span class="dt">x=</span>bodyweight,<span class="dt">y=</span>.fitted))<span class="op">+</span></a>
<a class="sourceLine" id="cb933-2" data-line-number="2"><span class="kw">geom_line</span>(<span class="dt">colour=</span><span class="st">&quot;blue&quot;</span>)<span class="op">+</span></a>
<a class="sourceLine" id="cb933-3" data-line-number="3"><span class="kw">geom_point</span>(<span class="kw">aes</span>(<span class="dt">y=</span>ENE))</a></code></pre></div>
<p>This is easier coding: there are only two non-standard things. The
first is that the fitted-value lines should be a distinct colour like
blue so that you can tell them from the data points. The second thing
is that for the second <code>geom_point</code>, the one that plots the data,
the <span class="math inline">\(x\)</span> coordinate <code>bodyweight</code> is correct so that we don’t
have to change that; we only have to change the <span class="math inline">\(y\)</span>-coordinate, which
is <code>ENE</code>. The plot is this:</p>
<div class="sourceCode" id="cb934"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb934-1" data-line-number="1">g</a></code></pre></div>
<p><img src="12-regression_files/figure-html/unnamed-chunk-18-1.png" width="672"  /></p>
<p>Concerning interpretation, you have a number of possibilities
here. The simplest is that the points in the middle are above the
curve, and the points at the ends are below. (That is, negative
residuals at the ends, and positive ones in the middle, which gives
you a hint for the next part.) Another is that the parabola curve
fails to capture the <em>shape</em> of the relationship; for example, I
see nothing much in the data suggesting that the relationship should go
back up, and even given that, the fitted curve doesn’t go especially
near any of the points.</p>
<p>I was thinking that the data should be fit better by something like
the left half of an upward-opening parabola, but I guess the curvature
on the left half of the plot suggests that it needs most of the left
half of the parabola just to cover the left half of the plot.</p>
<p>The moral of the story, as we see in the next part, is that the
parabola is the wrong curve for the job.</p>
<ol style="list-style-type: lower-roman">
<li>Obtain a residual plot for the parabola model. Do you see
any problems with it? (If you do, I’m not asking you to do anything
about them in this question, but I will.)</li>
</ol>
<p>Solution</p>
<p>The same idea as before for the other residual plot. Use the
fitted model object <code>carp.2</code> as your data frame for the
<code>ggplot</code>:</p>
<div class="sourceCode" id="cb935"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb935-1" data-line-number="1"><span class="kw">ggplot</span>(carp<span class="fl">.2</span>,<span class="kw">aes</span>(<span class="dt">x=</span>.fitted,<span class="dt">y=</span>.resid))<span class="op">+</span><span class="kw">geom_point</span>()</a></code></pre></div>
<p><img src="12-regression_files/figure-html/unnamed-chunk-19-1.png" width="672"  /></p>
<p>I think this is <em>still</em> a curve (or, it goes down and then
sharply up at the end). Either way, there is still a pattern.</p>
<p>That was all I needed, but as to what this means: our parabola was a
curve all right, but it appears not to be the right <em>kind</em> of
curve. I think the original data looks more like a hyperbola (a curve
like <span class="math inline">\(y=1/x\)</span>) than a parabola, in that it seems to decrease fast and
then gradually to a limit, and <em>that</em> suggests, as in the class
example, that we should try an asymptote model. Note how I specify it,
with the <code>I()</code> thing again, since a reciprocal is power <span class="math inline">\(-1\)</span>:</p>
<div class="sourceCode" id="cb936"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb936-1" data-line-number="1">carp<span class="fl">.3</span>=<span class="kw">lm</span>(ENE<span class="op">~</span><span class="kw">I</span>(bodyweight<span class="op">^</span>(<span class="op">-</span><span class="dv">1</span>)),<span class="dt">data=</span>carp)</a>
<a class="sourceLine" id="cb936-2" data-line-number="2"><span class="kw">summary</span>(carp<span class="fl">.3</span>)</a></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = ENE ~ I(bodyweight^(-1)), data = carp)
## 
## Residuals:
##      Min       1Q   Median       3Q      Max 
## -1.29801 -0.12830  0.04029  0.26702  0.91707 
## 
## Coefficients:
##                    Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)          5.1804     0.2823   18.35 8.01e-08 ***
## I(bodyweight^(-1)) 107.6690     5.8860   18.29 8.21e-08 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 0.6121 on 8 degrees of freedom
## Multiple R-squared:  0.9766, Adjusted R-squared:  0.9737 
## F-statistic: 334.6 on 1 and 8 DF,  p-value: 8.205e-08</code></pre>
<p>That fits <em>extraordinarily</em> well, with an R-squared up near
98%. The intercept is the asymptote, which suggests a (lower) limit
of about 5.2 for <code>ENE</code> (in the limit for large bodyweight). We
would have to ask the fisheries scientist whether this kind of thing
is a reasonable biological mechanism. It says that a carp always has
some ENE, no matter how big it gets, but a smaller carp will have a
lot more.</p>
<p>Does the fitted value plot look reasonable now? The “fortify” thing
doesn’t quite work here, since <code>bodyweight</code> doesn’t itself get
added to the fortified data set (it is not part of the model), so it
looks as if we are working with two data frames. I cheated and pulled
the things I wanted out of <code>carp</code> without doing a
<code>data=</code>:</p>
<div class="sourceCode" id="cb938"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb938-1" data-line-number="1"><span class="kw">ggplot</span>(carp<span class="fl">.3</span>,<span class="kw">aes</span>(<span class="dt">x=</span>carp<span class="op">$</span>bodyweight,<span class="dt">y=</span>.fitted))<span class="op">+</span></a>
<a class="sourceLine" id="cb938-2" data-line-number="2"><span class="kw">geom_line</span>(<span class="dt">colour=</span><span class="st">&quot;blue&quot;</span>)<span class="op">+</span></a>
<a class="sourceLine" id="cb938-3" data-line-number="3"><span class="kw">geom_point</span>(<span class="kw">aes</span>(<span class="dt">y=</span>carp<span class="op">$</span>ENE))</a></code></pre></div>
<p><img src="12-regression_files/figure-html/unnamed-chunk-21-1.png" width="672"  /></p>
<p>I’d say that does a really nice job of fitting the data. But it would
be nice to have a few more tanks with large-bodyweight fish, to
convince us that we have the shape of the trend right.</p>
<p>And, as ever, the residual plot. That’s a lot easier than the plot we
just did:</p>
<div class="sourceCode" id="cb939"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb939-1" data-line-number="1"><span class="kw">ggplot</span>(carp<span class="fl">.3</span>,<span class="kw">aes</span>(<span class="dt">x=</span>.fitted,<span class="dt">y=</span>.resid))<span class="op">+</span><span class="kw">geom_point</span>()</a></code></pre></div>
<p><img src="12-regression_files/figure-html/unnamed-chunk-22-1.png" width="672"  /></p>
<p>All in all, that looks pretty good (and certainly a vast improvement
over the ones you got before).</p>
<p>When you write up your report, you can make it flow better by writing
it in a way that suggests that each thing was the obvious thing to do
next: that is, that <em>you</em> would have thought to do it next,
rather than me telling you what to do.</p>
<p>My report (as an R Markdown file) is at
<a href="http://www.utsc.utoronto.ca/~butler/c32/carp.Rmd" class="uri">http://www.utsc.utoronto.ca/~butler/c32/carp.Rmd</a>. Download it,
knit it, play with it.</p>
</div>
<div id="sparrowhawks" class="section level2">
<h2><span class="header-section-number">13.3</span> Sparrowhawks</h2>
<p>One of nature’s patterns is the relationship
between the percentage of adult birds in a colony that return from the
previous year, and the number of new adults that join the colony. Data
for 13 colonies of sparrowhawks can be found at
<a href="http://www.utsc.utoronto.ca/~butler/c32/sparrowhawk.txt" class="uri">http://www.utsc.utoronto.ca/~butler/c32/sparrowhawk.txt</a>. The
columns are the percentage of adults returning from the previous year,
and the number of new adults that join the colony.</p>
<ol style="list-style-type: lower-alpha">
<li>Create a new R Markdown report, give it a suitable title, and
ask for HTML output. Answer the questions that follow in your
report. At any stage, you can Knit HTML
to see how the report looks so far.</li>
</ol>
<p>Solution</p>
<p>In R Studio, select File, New File, R Markdown. Fill in the Title,
Author and leave the Default Output Format at HTML. You’ll see a
template report with the document info at the top. This is mine:</p>
<pre><code>
---
title: &quot;Sparrowhawks&quot;
author: &quot;Ken Butler&quot;
date: &quot;October 13, 2015&quot;
output: html_document
---
</code></pre>
<p>This is known in the jargon as a “YAML block”.
Below that is the template R Markdown document. You can copy and cut it,
or leave it lying around for reminders and delete it later. Up to you.</p>
<ol start="2" style="list-style-type: lower-alpha">
<li>Read in the data and display all the values (there are only 13
rows, so this is OK). Add some text saying how many rows of data
there are.</li>
</ol>
<p>Solution</p>
<p>Copy the data as usual to a file that R Studio can find. In your
report, add some text like “we read in the data”, perhaps
after a section heading like “The data”. Then add a  by selecting Chunks and Insert Chunk, or by pressing
control-alt-I. So far you have something like this. (I’m using level-3 headings, for annoying technical reasons, but you should probably use second-level headings.)</p>
<pre><code>
### The data

We begin by reading in the data.


</code></pre>
<p>Inside the code chunk, that is, in the bit between the
backtick characters, put R code, just as you would type it at
the Console or put in an R script. In this case, that would be
the following code, minus the message that comes out of
<code>read_delim</code>:</p>
<div class="sourceCode" id="cb942"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb942-1" data-line-number="1"><span class="kw">library</span>(tidyverse)</a>
<a class="sourceLine" id="cb942-2" data-line-number="2">my_url=<span class="st">&quot;http://www.utsc.utoronto.ca/~butler/c32/sparrowhawk.txt&quot;</span></a>
<a class="sourceLine" id="cb942-3" data-line-number="3">sparrowhawks=<span class="kw">read_delim</span>(my_url,<span class="st">&quot; &quot;</span>)</a></code></pre></div>
<pre><code>## Parsed with column specification:
## cols(
##   returning = col_integer(),
##   newadults = col_integer()
## )</code></pre>
<div class="sourceCode" id="cb944"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb944-1" data-line-number="1">sparrowhawks</a></code></pre></div>
<p>For you, it looks like this:</p>
<p>```</p>
</div>
</div>
<p style="text-align: center;">
<a href="tidying-and-selecting-data.html"><button class="btn btn-default">Previous</button></a>
<a href="the-data.html"><button class="btn btn-default">Next</button></a>
</p>
</div>
</div>



</body>
</html>
