<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>Chapter 29 Survival analysis | Problems and Solutions in Applied Statistics</title>
  <meta name="description" content="A set of problems and solutions, in R, on various parts of applied statistics" />
  <meta name="generator" content="bookdown 0.21 and GitBook 2.6.7" />

  <meta property="og:title" content="Chapter 29 Survival analysis | Problems and Solutions in Applied Statistics" />
  <meta property="og:type" content="book" />
  <meta property="og:url" content="http://ritsokiguess.site/pasias" />
  
  <meta property="og:description" content="A set of problems and solutions, in R, on various parts of applied statistics" />
  <meta name="github-repo" content="nxskok/pasias" />

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Chapter 29 Survival analysis | Problems and Solutions in Applied Statistics" />
  
  <meta name="twitter:description" content="A set of problems and solutions, in R, on various parts of applied statistics" />
  

<meta name="author" content="Ken Butler" />


<meta name="date" content="2021-06-04" />

  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="logistic-regression-with-nominal-response.html"/>
<link rel="next" href="analysis-of-variance-revisited.html"/>
<script src="libs/header-attrs-2.8/header-attrs.js"></script>
<script src="libs/jquery-2.2.3/jquery.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />









<script src="libs/accessible-code-block-0.0.1/empty-anchor.js"></script>


<style type="text/css">
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">Problems and Solutions in Applied Statistics</a></li>

<li class="divider"></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i>Introduction</a>
<ul>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#packages-used-somewhere-in-this-book"><i class="fa fa-check"></i>Packages used somewhere in this book</a></li>
</ul></li>
<li class="chapter" data-level="1" data-path="getting-used-to-r-and-r-studio.html"><a href="getting-used-to-r-and-r-studio.html"><i class="fa fa-check"></i><b>1</b> Getting used to R and R Studio</a>
<ul>
<li class="chapter" data-level="1.1" data-path="getting-used-to-r-and-r-studio.html"><a href="getting-used-to-r-and-r-studio.html#running-r-studio-on-jupyterhub"><i class="fa fa-check"></i><b>1.1</b> Running R Studio on Jupyterhub</a></li>
<li class="chapter" data-level="1.2" data-path="getting-used-to-r-and-r-studio.html"><a href="getting-used-to-r-and-r-studio.html#getting-an-r-studio-cloud-account"><i class="fa fa-check"></i><b>1.2</b> Getting an R Studio Cloud account</a></li>
<li class="chapter" data-level="1.3" data-path="getting-used-to-r-and-r-studio.html"><a href="getting-used-to-r-and-r-studio.html#getting-started"><i class="fa fa-check"></i><b>1.3</b> Getting started</a></li>
<li class="chapter" data-level="1.4" data-path="getting-used-to-r-and-r-studio.html"><a href="getting-used-to-r-and-r-studio.html#reading-data-from-a-file"><i class="fa fa-check"></i><b>1.4</b> Reading data from a file</a></li>
<li class="chapter" data-level="1.5" data-path="getting-used-to-r-and-r-studio.html"><a href="getting-used-to-r-and-r-studio.html#reading-files-different-ways"><i class="fa fa-check"></i><b>1.5</b> Reading files different ways</a></li>
</ul></li>
<li class="chapter" data-level="2" data-path="reading-in-data.html"><a href="reading-in-data.html"><i class="fa fa-check"></i><b>2</b> Reading in data</a></li>
<li class="chapter" data-level="3" data-path="drawing-graphs.html"><a href="drawing-graphs.html"><i class="fa fa-check"></i><b>3</b> Drawing graphs</a></li>
<li class="chapter" data-level="4" data-path="data-exploration.html"><a href="data-exploration.html"><i class="fa fa-check"></i><b>4</b> Data exploration</a></li>
<li class="chapter" data-level="5" data-path="working-with-dataframes.html"><a href="working-with-dataframes.html"><i class="fa fa-check"></i><b>5</b> Working with dataframes</a></li>
<li class="chapter" data-level="6" data-path="one-sample-inference.html"><a href="one-sample-inference.html"><i class="fa fa-check"></i><b>6</b> One-sample inference</a></li>
<li class="chapter" data-level="7" data-path="two-sample-inference.html"><a href="two-sample-inference.html"><i class="fa fa-check"></i><b>7</b> Two-sample inference</a></li>
<li class="chapter" data-level="8" data-path="power-and-sample-size.html"><a href="power-and-sample-size.html"><i class="fa fa-check"></i><b>8</b> Power and sample size</a></li>
<li class="chapter" data-level="9" data-path="the-sign-test.html"><a href="the-sign-test.html"><i class="fa fa-check"></i><b>9</b> The sign test</a></li>
<li class="chapter" data-level="10" data-path="mood-median-test.html"><a href="mood-median-test.html"><i class="fa fa-check"></i><b>10</b> Mood median test</a></li>
<li class="chapter" data-level="11" data-path="matched-pairs-t-and-sign-test.html"><a href="matched-pairs-t-and-sign-test.html"><i class="fa fa-check"></i><b>11</b> Matched pairs t and sign test</a></li>
<li class="chapter" data-level="12" data-path="normal-quantile-plots.html"><a href="normal-quantile-plots.html"><i class="fa fa-check"></i><b>12</b> Normal quantile plots</a>
<ul>
<li class="chapter" data-level="12.1" data-path="normal-quantile-plots.html"><a href="normal-quantile-plots.html#lengths-of-heliconia-flowers"><i class="fa fa-check"></i><b>12.1</b> Lengths of heliconia flowers</a></li>
<li class="chapter" data-level="12.2" data-path="normal-quantile-plots.html"><a href="normal-quantile-plots.html#ferritin-and-normality"><i class="fa fa-check"></i><b>12.2</b> Ferritin and normality</a></li>
<li class="chapter" data-level="12.3" data-path="normal-quantile-plots.html"><a href="normal-quantile-plots.html#lengths-of-heliconia-flowers-1"><i class="fa fa-check"></i><b>12.3</b> Lengths of heliconia flowers</a></li>
<li class="chapter" data-level="12.4" data-path="normal-quantile-plots.html"><a href="normal-quantile-plots.html#ferritin-and-normality-1"><i class="fa fa-check"></i><b>12.4</b> Ferritin and normality</a></li>
</ul></li>
<li class="chapter" data-level="13" data-path="analysis-of-variance.html"><a href="analysis-of-variance.html"><i class="fa fa-check"></i><b>13</b> Analysis of variance</a></li>
<li class="chapter" data-level="14" data-path="writing-reports.html"><a href="writing-reports.html"><i class="fa fa-check"></i><b>14</b> Writing reports</a></li>
<li class="chapter" data-level="15" data-path="learning-to-code.html"><a href="learning-to-code.html"><i class="fa fa-check"></i><b>15</b> Learning to code</a>
<ul>
<li class="chapter" data-level="15.1" data-path="learning-to-code.html"><a href="learning-to-code.html#introduction-1"><i class="fa fa-check"></i><b>15.1</b> Introduction</a></li>
<li class="chapter" data-level="15.2" data-path="learning-to-code.html"><a href="learning-to-code.html#data-and-pre-processing"><i class="fa fa-check"></i><b>15.2</b> Data and pre-processing</a></li>
<li class="chapter" data-level="15.3" data-path="learning-to-code.html"><a href="learning-to-code.html#analysis"><i class="fa fa-check"></i><b>15.3</b> Analysis</a></li>
<li class="chapter" data-level="15.4" data-path="learning-to-code.html"><a href="learning-to-code.html#conclusions-see-note-9"><i class="fa fa-check"></i><b>15.4</b> Conclusions (see note 9)</a></li>
</ul></li>
<li class="chapter" data-level="16" data-path="treating-dandruff.html"><a href="treating-dandruff.html"><i class="fa fa-check"></i><b>16</b> Treating dandruff</a>
<ul>
<li class="chapter" data-level="16.1" data-path="treating-dandruff.html"><a href="treating-dandruff.html#introduction-2"><i class="fa fa-check"></i><b>16.1</b> Introduction</a></li>
<li class="chapter" data-level="16.2" data-path="treating-dandruff.html"><a href="treating-dandruff.html#exploratory-analysis"><i class="fa fa-check"></i><b>16.2</b> Exploratory analysis</a></li>
<li class="chapter" data-level="16.3" data-path="treating-dandruff.html"><a href="treating-dandruff.html#analysis-of-variance-1"><i class="fa fa-check"></i><b>16.3</b> Analysis of Variance</a></li>
<li class="chapter" data-level="16.4" data-path="treating-dandruff.html"><a href="treating-dandruff.html#assessment-of-assumptions"><i class="fa fa-check"></i><b>16.4</b> Assessment of Assumptions</a></li>
<li class="chapter" data-level="16.5" data-path="treating-dandruff.html"><a href="treating-dandruff.html#conclusions"><i class="fa fa-check"></i><b>16.5</b> Conclusions</a></li>
<li class="chapter" data-level="16.6" data-path="treating-dandruff.html"><a href="treating-dandruff.html#end"><i class="fa fa-check"></i><b>16.6</b> End</a></li>
</ul></li>
<li class="chapter" data-level="17" data-path="tidying-data.html"><a href="tidying-data.html"><i class="fa fa-check"></i><b>17</b> Tidying data</a></li>
<li class="chapter" data-level="18" data-path="simple-regression.html"><a href="simple-regression.html"><i class="fa fa-check"></i><b>18</b> Simple regression</a></li>
<li class="chapter" data-level="19" data-path="multiple-regression.html"><a href="multiple-regression.html"><i class="fa fa-check"></i><b>19</b> Multiple regression</a></li>
<li class="chapter" data-level="20" data-path="regression-with-categorical-variables.html"><a href="regression-with-categorical-variables.html"><i class="fa fa-check"></i><b>20</b> Regression with categorical variables</a>
<ul>
<li class="chapter" data-level="20.1" data-path="regression-with-categorical-variables.html"><a href="regression-with-categorical-variables.html#crickets-revisited"><i class="fa fa-check"></i><b>20.1</b> Crickets revisited</a></li>
<li class="chapter" data-level="20.2" data-path="regression-with-categorical-variables.html"><a href="regression-with-categorical-variables.html#pulse-rates-and-marching"><i class="fa fa-check"></i><b>20.2</b> Pulse rates and marching</a></li>
<li class="chapter" data-level="20.3" data-path="regression-with-categorical-variables.html"><a href="regression-with-categorical-variables.html#crickets-revisited-1"><i class="fa fa-check"></i><b>20.3</b> Crickets revisited</a></li>
<li class="chapter" data-level="20.4" data-path="regression-with-categorical-variables.html"><a href="regression-with-categorical-variables.html#pulse-rates-and-marching-1"><i class="fa fa-check"></i><b>20.4</b> Pulse rates and marching</a></li>
</ul></li>
<li class="chapter" data-level="21" data-path="dates-and-times.html"><a href="dates-and-times.html"><i class="fa fa-check"></i><b>21</b> Dates and times</a></li>
<li class="chapter" data-level="22" data-path="functions.html"><a href="functions.html"><i class="fa fa-check"></i><b>22</b> Functions</a></li>
<li class="chapter" data-level="23" data-path="vector-and-matrix-algebra.html"><a href="vector-and-matrix-algebra.html"><i class="fa fa-check"></i><b>23</b> Vector and matrix algebra</a>
<ul>
<li class="chapter" data-level="23.1" data-path="vector-and-matrix-algebra.html"><a href="vector-and-matrix-algebra.html#heights-and-foot-lengths-again"><i class="fa fa-check"></i><b>23.1</b> Heights and foot lengths again</a></li>
<li class="chapter" data-level="23.2" data-path="vector-and-matrix-algebra.html"><a href="vector-and-matrix-algebra.html#heights-and-foot-lengths-again-1"><i class="fa fa-check"></i><b>23.2</b> Heights and foot lengths again</a></li>
</ul></li>
<li class="chapter" data-level="24" data-path="the-bootstrap.html"><a href="the-bootstrap.html"><i class="fa fa-check"></i><b>24</b> The Bootstrap</a></li>
<li class="chapter" data-level="25" data-path="bayesian-statistics-with-stan.html"><a href="bayesian-statistics-with-stan.html"><i class="fa fa-check"></i><b>25</b> Bayesian Statistics with Stan</a></li>
<li class="chapter" data-level="26" data-path="logistic-regression.html"><a href="logistic-regression.html"><i class="fa fa-check"></i><b>26</b> Logistic regression</a></li>
<li class="chapter" data-level="27" data-path="logistic-regression-with-ordinal-response.html"><a href="logistic-regression-with-ordinal-response.html"><i class="fa fa-check"></i><b>27</b> Logistic regression with ordinal response</a></li>
<li class="chapter" data-level="28" data-path="logistic-regression-with-nominal-response.html"><a href="logistic-regression-with-nominal-response.html"><i class="fa fa-check"></i><b>28</b> Logistic regression with nominal response</a></li>
<li class="chapter" data-level="29" data-path="survival-analysis.html"><a href="survival-analysis.html"><i class="fa fa-check"></i><b>29</b> Survival analysis</a>
<ul>
<li class="chapter" data-level="29.1" data-path="survival-analysis.html"><a href="survival-analysis.html#the-worcester-survey"><i class="fa fa-check"></i><b>29.1</b> The Worcester survey</a></li>
<li class="chapter" data-level="29.2" data-path="survival-analysis.html"><a href="survival-analysis.html#drug-treatment-programs"><i class="fa fa-check"></i><b>29.2</b> Drug treatment programs</a></li>
<li class="chapter" data-level="29.3" data-path="survival-analysis.html"><a href="survival-analysis.html#multiple-myeloma"><i class="fa fa-check"></i><b>29.3</b> Multiple myeloma</a></li>
<li class="chapter" data-level="29.4" data-path="survival-analysis.html"><a href="survival-analysis.html#ovarian-cancer"><i class="fa fa-check"></i><b>29.4</b> Ovarian cancer</a></li>
<li class="chapter" data-level="29.5" data-path="survival-analysis.html"><a href="survival-analysis.html#the-worcester-survey-1"><i class="fa fa-check"></i><b>29.5</b> The Worcester survey</a></li>
<li class="chapter" data-level="29.6" data-path="survival-analysis.html"><a href="survival-analysis.html#drug-treatment-programs-1"><i class="fa fa-check"></i><b>29.6</b> Drug treatment programs</a></li>
<li class="chapter" data-level="29.7" data-path="survival-analysis.html"><a href="survival-analysis.html#multiple-myeloma-1"><i class="fa fa-check"></i><b>29.7</b> Multiple myeloma</a></li>
<li class="chapter" data-level="29.8" data-path="survival-analysis.html"><a href="survival-analysis.html#ovarian-cancer-1"><i class="fa fa-check"></i><b>29.8</b> Ovarian cancer</a></li>
</ul></li>
<li class="chapter" data-level="30" data-path="analysis-of-variance-revisited.html"><a href="analysis-of-variance-revisited.html"><i class="fa fa-check"></i><b>30</b> Analysis of variance revisited</a></li>
<li class="chapter" data-level="31" data-path="analysis-of-covariance.html"><a href="analysis-of-covariance.html"><i class="fa fa-check"></i><b>31</b> Analysis of covariance</a></li>
<li class="chapter" data-level="32" data-path="multivariate-analysis-of-variance.html"><a href="multivariate-analysis-of-variance.html"><i class="fa fa-check"></i><b>32</b> Multivariate analysis of variance</a></li>
<li class="chapter" data-level="33" data-path="repeated-measures.html"><a href="repeated-measures.html"><i class="fa fa-check"></i><b>33</b> Repeated measures</a></li>
<li class="chapter" data-level="34" data-path="discriminant-analysis.html"><a href="discriminant-analysis.html"><i class="fa fa-check"></i><b>34</b> Discriminant analysis</a></li>
<li class="chapter" data-level="35" data-path="hierarchical-cluster-analysis.html"><a href="hierarchical-cluster-analysis.html"><i class="fa fa-check"></i><b>35</b> Hierarchical cluster analysis</a></li>
<li class="chapter" data-level="36" data-path="k-means-cluster-analysis.html"><a href="k-means-cluster-analysis.html"><i class="fa fa-check"></i><b>36</b> K-means cluster analysis</a></li>
<li class="chapter" data-level="37" data-path="drawing-maps-with-leaflet.html"><a href="drawing-maps-with-leaflet.html"><i class="fa fa-check"></i><b>37</b> Drawing maps with Leaflet</a></li>
<li class="chapter" data-level="38" data-path="multidimensional-scaling.html"><a href="multidimensional-scaling.html"><i class="fa fa-check"></i><b>38</b> Multidimensional Scaling</a></li>
<li class="chapter" data-level="39" data-path="principal-components.html"><a href="principal-components.html"><i class="fa fa-check"></i><b>39</b> Principal Components</a>
<ul>
<li class="chapter" data-level="39.1" data-path="principal-components.html"><a href="principal-components.html#the-weather-somewhere"><i class="fa fa-check"></i><b>39.1</b> The weather, somewhere</a></li>
<li class="chapter" data-level="39.2" data-path="principal-components.html"><a href="principal-components.html#the-weather-somewhere-1"><i class="fa fa-check"></i><b>39.2</b> The weather, somewhere</a></li>
</ul></li>
<li class="chapter" data-level="40" data-path="factor-analysis.html"><a href="factor-analysis.html"><i class="fa fa-check"></i><b>40</b> Factor Analysis</a></li>
<li class="chapter" data-level="41" data-path="frequency-table-analysis.html"><a href="frequency-table-analysis.html"><i class="fa fa-check"></i><b>41</b> Frequency table analysis</a></li>
<li class="divider"></li>
<li><a href="https://github.com/rstudio/bookdown" target="blank">Published with bookdown</a></li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Problems and Solutions in Applied Statistics</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="survival-analysis" class="section level1" number="29">
<h1><span class="header-section-number">Chapter 29</span> Survival analysis</h1>
<div class="sourceCode" id="cb254"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb254-1"><a href="survival-analysis.html#cb254-1"></a><span class="kw">library</span>(survival)</span>
<span id="cb254-2"><a href="survival-analysis.html#cb254-2"></a><span class="kw">library</span>(tidyverse)</span>
<span id="cb254-3"><a href="survival-analysis.html#cb254-3"></a><span class="kw">library</span>(survminer)</span></code></pre></div>
<div id="the-worcester-survey" class="section level2" number="29.1">
<h2><span class="header-section-number">29.1</span> The Worcester survey</h2>
<p>The Worcester survey was a long-term study of
all myocardial-infarction<a href="#fn36" class="footnote-ref" id="fnref36"><sup>36</sup></a> victims admitted to hospitals in the
Worcester, Massachusetts area.<a href="#fn37" class="footnote-ref" id="fnref37"><sup>37</sup></a>
The data have been well studied, and can be found in
the file <a href="http://ritsokiguess.site/datafiles/whas100.csv">link</a>.</p>
<ol style="list-style-type: lower-alpha">
<li>Read the data and
display the first few rows of the data frame. You might get an extra
column, which you can ignore.
For your information, the variables are:</li>
</ol>
<ul>
<li><p>patient ID code</p></li>
<li><p>admission date</p></li>
<li><p>date of last followup (this is the date of death if the
patient died)</p></li>
<li><p>length of hospital stay (days)</p></li>
<li><p>followup time (days) (time between admission and last followup)</p></li>
<li><p>followup status: 1=dead, 0=alive</p></li>
<li><p>Age in years (at admission)</p></li>
<li><p>gender (0=male, 1=female)</p></li>
<li><p>body mass index (kg/m<span class="math inline">\(^2\)</span>)</p></li>
</ul>
<ol start="2" style="list-style-type: lower-alpha">
<li><p>Create a suitable response variable for a Cox proportional
hazards model for time of survival, using the followup time and
followup status.</p></li>
<li><p>Fit a Cox proportional hazards model predicting survival time
from age, gender and BMI. Obtain the <code>summary</code> (but you don’t
need to comment on it yet).</p></li>
<li><p>Test the overall fit of the model. What does the result mean?</p></li>
<li><p>Can any of your explanatory variables be removed from the
model? Explain briefly.</p></li>
<li><p>Remove your most non-significant explanatory variable from
the model and fit again. Take a look at the results. Are all your
remaining explanatory variables significant? (If all your
explanatory variables were previously significant, you can skip this part.)</p></li>
<li><p>Calculate the 1st quartile, median, and 3rd quartiles of
age and BMI. (<code>quantile</code>.) Round these off to the
nearest whole number. (Do the rounding off yourself, though R has a
function <code>round</code> that does this, which you can investigate if
you want.) As an alternative, you can get these by passing the whole
data frame, or the columns of it you want, into <code>summary</code>.</p></li>
<li><p>Make a data frame out of all the combinations of
age and BMI values (that you obtained in the previous part) suitable for predicting
with.</p></li>
<li><p>Obtain predicted survival probabilities for each of the values
in your new data frame. Use your best model. (You don’t need to look
at the results, though you can if you want to.)</p></li>
<li><p>Make a graph depicting the survival curves from
<code>survfit</code> with different colours distinguishing the different
survival curves.</p></li>
<li><p>What is the effect of age on survival? What is the effect
of BMI on survival? Explain briefly. (You will have to disentangle
the meaning of the different coloured lines on the plot to do this.)</p></li>
</ol>
</div>
<div id="drug-treatment-programs" class="section level2" number="29.2">
<h2><span class="header-section-number">29.2</span> Drug treatment programs</h2>
<p>One of the goals of drug treatment programs is to lengthen
the time until the patient returns to using drugs. (It is not
generally possible to prevent patients from <em>ever</em> using drugs
again.) In one study, over 600 former drug users took part. Two
different programs, a short program and a long program, were offered
at two different sites, labelled A and B. The data can be found in
<a href="http://ritsokiguess.site/datafiles/drugusers.txt">link</a>. The
variables are these:</p>
<ul>
<li><p><code>ID</code>: patient ID number</p></li>
<li><p><code>age</code>: patient age at enrollment into the study</p></li>
<li><p><code>ndrugtx</code>: number of previous drug treatments</p></li>
<li><p><code>treat</code>: 0 for short treatment program, 1 for long program</p></li>
<li><p><code>site</code>: 0 for site A, 1 for site B</p></li>
<li><p><code>time</code>: time until return to drug use</p></li>
<li><p><code>censor</code>: whether the subject returned to drug use (1) or
not (0) during the follow-up period</p></li>
<li><p><code>herco</code>: whether subject used heroine or cocaine in the
last 3 months: 1 is both, 2 is one (either heroine or cocaine), 3 is neither.</p></li>
</ul>
<ol style="list-style-type: lower-alpha">
<li><p>Read in the data and check in one way or another that you
have what was promised above.</p></li>
<li><p>There are some missing values in the dataframe. Demonstrate
this using <code>summary</code>. Pipe the dataframe into
<code>drop_na</code> and show that they have gone. (<code>drop_na</code>
removes all rows that have missing values in them.)</p></li>
<li><p>Some of these variables are recorded as numbers but are
actually categorical. Which ones? Re-define these variables in your
data frame so that they have sensible (text) values.</p></li>
<li><p>Create a suitable reponse variable for a Cox proportional
hazards regression that predicts time until return to drug use from
the other variables.
This requires some care, because you need to be sure about what the
censoring variable actually represents and what you need it to represent.</p></li>
<li><p>Look at the first few values of your response variable. Why
is the fifth one marked with a <code>+</code>? Explain briefly.</p></li>
<li><p>Fit a Cox proportional hazards model, predicting from all
the other variables (except for <code>row</code> and <code>ID</code>) that you haven’t used
yet. Display the results.</p></li>
<li><p>Find which explanatory variables can be removed at <span class="math inline">\(\alpha=0.05\)</span>
(there should be two of them). Bear in mind that we have categorical variables, so that looking at the output from <code>summary</code> is not enough.</p></li>
<li><p>Remove <em>all</em> the non-significant explanatory variables
and re-fit your model. By carrying out a suitable test demonstrate
that your smaller model is the better one.</p></li>
<li><p><a name="part:posneg">*</a> Display your better model. Are all of the
explanatory variables significant? Do their slope coefficients have
sensible signs (plus or minus), based on what you know or can guess
about drug treatments? Explain briefly.</p></li>
<li><p>We have three variables left in our model, <code>age</code>,
<code>ndrugtx</code> and <code>treat</code>. The quartiles of age are 27 and
37, the quartiles of <code>ndrugtx</code> are 1 and 6, and the two
possible values of <code>treat</code> are <code>short</code> and <code>long</code>. Create a data frame
with variables of these names and all possible combinations of their
values (so there should be 8 rows in the resulting data
frame). Display the resulting data frame.</p></li>
<li><p>Obtain predicted survival probabilities for each of the
values of <code>age</code>, <code>ndrugtx</code> and <code>treat</code> used in
the previous part. You don’t need to display it (we are going to
plot it shortly).</p></li>
<li><p>Plot your predicted survival curves.</p></li>
<li><p>Which of your combinations of values is predicted to take
the longest to return to drug use? Which is predicted to take the
shortest time? Explain briefly.</p></li>
<li><p>Are your survival curve plot and your conclusions from part
(<a href="#part:posneg">here</a>) consistent, or not? Explain briefly.</p></li>
</ol>
</div>
<div id="multiple-myeloma" class="section level2" number="29.3">
<h2><span class="header-section-number">29.3</span> Multiple myeloma</h2>
<p>Multiple myeloma is a kind of cancer. It
forms in a plasma cell (which is a type of white blood cell). It
causes cancer cells to accumulate in the bone marrow, where they crowd
out healthy blood cells. Plasma cells make antibodies (to help fight
infections), while the cancer cells don’t: they produce abnormal
proteins that can cause kidney problems. (This adapted from
<a href="http://www.mayoclinic.org/diseases-conditions/multiple-myeloma/basics/definition/con-20026607">link</a>.)
The variables are:</p>
<ul>
<li><p><code>time</code>: survival time from diagnosis (months)</p></li>
<li><p><code>vstatus</code>: 0=alive, 1=dead at end of study</p></li>
<li><p><code>logbun</code>: log of BUN test score (BUN test is a test of
kidney function, not to be confused with cha siu
bao<a href="#fn38" class="footnote-ref" id="fnref38"><sup>38</sup></a>).</p></li>
<li><p><code>hgb</code>: hemoglobin (at diagnosis).</p></li>
<li><p><code>platelet</code>: platelets: 1=normal, 0=abnormal (at
diagnosis).</p></li>
<li><p><code>age</code> at diagnosis, in years</p></li>
<li><p><code>logwbc</code>: log of WBC (white blood cell count, at
diagnosis)</p></li>
<li><p><code>frac</code>: fractures at diagnosis (0=absent, 1=present)</p></li>
<li><p><code>logpbm</code>: log of percent of plasma cells in bone marrow</p></li>
<li><p><code>protein</code>: proteinuria (protein in urine) at
diagnosis. Most people have very little, so a larger than normal
amount indicates illness of some kind.</p></li>
<li><p><code>scalc</code>: serum calcium at diagnosis.</p></li>
</ul>
<p>The data, on 65 patients with multiple myeloma, are in
<a href="http://ritsokiguess.site/datafiles/myeloma.csv">link</a>. Some of the
variables are logs because they could take very large values.</p>
<p>There are a lot of parts here, but each part is supposed to be short.</p>
<ol style="list-style-type: lower-alpha">
<li><p>Read in the data and display (some of) the values. Confirm that
you have the right number of observations and the right variables.</p></li>
<li><p>Create a suitable response variable for a Cox
proportional-hazards survival model, bearing in mind that the
“event” here is death. Display your response variable, and explain
briefly what the <code>+</code> signs attached to some of the values
mean, without using a technical term.</p></li>
<li><p>What is the technical term for those patients that have a
<code>+</code> by their values for the response variable?</p></li>
<li><p>Fit a Cox proportional-hazards survival model predicting
your response variable from all the other variables (except for the
ones that you used to make the response variable). Display the
<code>summary</code> of your model.</p></li>
<li><p>In your model, which explanatory variables have a P-value less than
0.10? Fit a model containing only those and display the results.</p></li>
<li><p>Do a test to compare the two models that you fit. Why do
you prefer the second model? Explain briefly.</p></li>
<li><p>There should be two explanatory variables left in your
model. These are both numerical variables. Find their first and
third quartiles, any way you like.</p></li>
<li><p>Create a data frame containing all possible combinations
of the two quartiles for each of the two variables, and display the result.</p></li>
<li><p>Obtain predicted survival probabilities for each of the
combinations of variables you created above. You don’t need to look
at the results (they are rather long).</p></li>
<li><p>Obtain a graph of the predicted survival curves for each
combination of your variables.</p></li>
<li><p>Is it better to have high or low values for each of the
variables in your prediction? Explain briefly.</p></li>
</ol>
</div>
<div id="ovarian-cancer" class="section level2" number="29.4">
<h2><span class="header-section-number">29.4</span> Ovarian cancer</h2>
<p>R’s <code>survival</code> package contains several data
sets. One of these is called <code>ovarian</code>; it comes from a study
of 26 ovarian cancer patients. The major purpose of this study was to
compare the effects of two treatments on survival time.</p>
<ol style="list-style-type: lower-alpha">
<li><p>Obtain and display (all of) the data set. This is as simple as
loading the package and typing the data set’s name.</p></li>
<li><p>The columns of interest to us are:</p></li>
</ol>
<ul>
<li><p><code>futime</code>: the time for which a patient was followed-up:
the number of days until either they died or the study ended (or
they withdrew from the study for some other reason).</p></li>
<li><p><code>fustat</code>: follow-up status: 1 if the patient died of
ovarian cancer, 0 if they were still alive when the study ended.</p></li>
<li><p><code>age</code>: of patient, at diagnosis, in years</p></li>
<li><p><code>rx</code>: treatment, numbered 1 or 2, but really labels for
the two treatments.</p></li>
</ul>
<p>Create and display a suitable response variable <code>y</code> for a Cox
proportional-hazards model.</p>
<ol start="3" style="list-style-type: lower-alpha">
<li><p>In the display of your response variable, some values are
marked with a <code>+</code>. Why is that? Explain briefly. (If you use
a technical term, you should explain what it means.)</p></li>
<li><p>Fit a Cox proportional-hazards model for predicting
survival time from age and treatment. Note that the numeric values
for treatment make sense only as labels for the two treatments, so
in your model formula make treatment into a factor. Display the
results.</p></li>
<li><p>Is there a significant difference between the treatments in
terms of their effects on survival (from ovarian cancer)?</p></li>
<li><p>Is there a significant effect of age? If there is, describe
the effect that age has on survival.</p></li>
<li><p>Make a martingale residual plot for this model. Do you see
any problems? Explain briefly.</p></li>
<li><p>Find the quartiles of <code>age</code>, and make a data frame
containing all combinations of those two ages and the two
treatments. Display what you have. (Feel free to copy the values by
hand, rather than trying to save them and use them.)</p></li>
<li><p>Obtain predicted survival probabilities for each of your
age-treatment combinations, for each of a variety of survival
times. (This is only one thing, despite it sounding like a lot.)</p></li>
<li><p>Draw a plot that compares the survival probabilities at the
different times.</p></li>
<li><p>According to your plot, how would you describe the effects of
treatment and of age?</p></li>
</ol>
<p>My solutions follow:</p>
</div>
<div id="the-worcester-survey-1" class="section level2" number="29.5">
<h2><span class="header-section-number">29.5</span> The Worcester survey</h2>
<p>The Worcester survey was a long-term study of
all myocardial-infarction<a href="#fn39" class="footnote-ref" id="fnref39"><sup>39</sup></a> victims admitted to hospitals in the
Worcester, Massachusetts area.<a href="#fn40" class="footnote-ref" id="fnref40"><sup>40</sup></a>
The data have been well studied, and can be found in
the file <a href="http://ritsokiguess.site/datafiles/whas100.csv">link</a>.</p>
<ol style="list-style-type: lower-alpha">
<li>Read the data and
display the first few rows of the data frame. You might get an extra
column, which you can ignore.
For your information, the variables are:</li>
</ol>
<ul>
<li><p>patient ID code</p></li>
<li><p>admission date</p></li>
<li><p>date of last followup (this is the date of death if the
patient died)</p></li>
<li><p>length of hospital stay (days)</p></li>
<li><p>followup time (days) (time between admission and last followup)</p></li>
<li><p>followup status: 1=dead, 0=alive</p></li>
<li><p>Age in years (at admission)</p></li>
<li><p>gender (0=male, 1=female)</p></li>
<li><p>body mass index (kg/m<span class="math inline">\(^2\)</span>)</p></li>
</ul>
<p>Solution</p>
<div class="sourceCode" id="cb255"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb255-1"><a href="survival-analysis.html#cb255-1"></a>my_url &lt;-<span class="st"> &quot;http://ritsokiguess.site/datafiles/whas100.csv&quot;</span></span>
<span id="cb255-2"><a href="survival-analysis.html#cb255-2"></a>whas100 &lt;-<span class="st"> </span><span class="kw">read_csv</span>(my_url)</span></code></pre></div>
<pre><code>## Warning: Missing column names filled in: &#39;X1&#39; [1]</code></pre>
<pre><code>## 
## ── Column specification ────────────────────────────────────────────────────────
## cols(
##   X1 = col_double(),
##   id = col_double(),
##   admitdate = col_character(),
##   foldate = col_character(),
##   los = col_double(),
##   lenfol = col_double(),
##   fstat = col_double(),
##   age = col_double(),
##   gender = col_double(),
##   bmi = col_double()
## )</code></pre>
<div class="sourceCode" id="cb258"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb258-1"><a href="survival-analysis.html#cb258-1"></a>whas100</span></code></pre></div>
<pre><code>## # A tibble: 100 x 10
##       X1    id admitdate  foldate      los lenfol fstat   age gender   bmi
##    &lt;dbl&gt; &lt;dbl&gt; &lt;chr&gt;      &lt;chr&gt;      &lt;dbl&gt;  &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt;  &lt;dbl&gt; &lt;dbl&gt;
##  1     1     1 3/13/1995  3/19/1995      4      6     1    65      0  31.4
##  2     2     2 1/14/1995  1/23/1996      5    374     1    88      1  22.7
##  3     3     3 2/17/1995  10/4/2001      5   2421     1    77      0  27.9
##  4     4     4 4/7/1995   7/14/1995      9     98     1    81      1  21.5
##  5     5     5 2/9/1995   5/29/1998      4   1205     1    78      0  30.7
##  6     6     6 1/16/1995  9/11/2000      7   2065     1    82      1  26.5
##  7     7     7 1/17/1995  10/15/1997     3   1002     1    66      1  35.7
##  8     8     8 11/15/1994 11/24/2000    56   2201     1    81      1  28.3
##  9     9     9 8/18/1995  2/23/1996      5    189     1    76      0  27.1
## 10    10    10 7/22/1995  12/31/2002     9   2719     0    40      0  21.8
## # … with 90 more rows</code></pre>
<p>I seem to have an extra column called <code>X1</code>. This is because I
saved my version of the data using the old <code>write.csv</code>, which
comes with row names, and I forgot to
get rid of them. These came back as an extra unnamed variable to which
<code>read_delim</code> gave the name <code>X1</code>.</p>
<p><span class="math inline">\(\blacksquare\)</span></p>
<ol start="2" style="list-style-type: lower-alpha">
<li>Create a suitable response variable for a Cox proportional
hazards model for time of survival, using the followup time and
followup status.</li>
</ol>
<p>Solution</p>
<p><code>Surv</code>. The event here is death, so the two parts of the
response variable are followup time <code>lenfol</code> and followup
status, 1 being “dead”, <code>fstat</code>:</p>
<div class="sourceCode" id="cb260"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb260-1"><a href="survival-analysis.html#cb260-1"></a>y &lt;-<span class="st"> </span><span class="kw">with</span>(whas100, <span class="kw">Surv</span>(lenfol, fstat <span class="op">==</span><span class="st"> </span><span class="dv">1</span>))</span>
<span id="cb260-2"><a href="survival-analysis.html#cb260-2"></a>y</span></code></pre></div>
<pre><code>##   [1]    6   374  2421    98  1205  2065  1002  2201   189  2719+ 2638+  492 
##  [13]  302  2574+ 2610+ 2641+ 1669  2624  2578+ 2595+  123  2613+  774  2012 
##  [25] 2573+ 1874  2631+ 1907   538   104     6  1401  2710   841   148  2137+
##  [37] 2190+ 2173+  461  2114+ 2157+ 2054+ 2124+ 2137+ 2031  2003+ 2074+  274 
##  [49] 1984+ 1993+ 1939+ 1172    89   128  1939+   14  1011  1497  1929+ 2084+
##  [61]  107   451  2183+ 1876+  936   363  1048  1889+ 2072+ 1879+ 1870+ 1859+
##  [73] 2052+ 1846+ 2061+ 1912+ 1836+  114  1557  1278  1836+ 1916+ 1934+ 1923+
##  [85]   44  1922+  274  1860+ 1806  2145+  182  2013+ 2174+ 1624   187  1883+
##  [97] 1577    62  1969+ 1054</code></pre>
<p>Just using <code>fstat</code> alone as the second thing in <code>Surv</code>
also works, because anything that gives <code>TRUE</code> or 1 when the
event (death) occurs is equally good. (In R, <code>TRUE</code> as a number
is 1 and <code>FALSE</code> as a number is 0.)</p>
<p>I listed the values by way of checking. The ones with a <code>+</code> are
censored: that is, the patient was still alive the last time the
doctor saw them. Most of the censored values are longer times. Usually
this happens because the patient was still alive at the end of the study.</p>
<p><span class="math inline">\(\blacksquare\)</span></p>
<ol start="3" style="list-style-type: lower-alpha">
<li>Fit a Cox proportional hazards model predicting survival time
from age, gender and BMI. Obtain the <code>summary</code> (but you don’t
need to comment on it yet).</li>
</ol>
<p>Solution</p>
<p>This, using the response variable that we just created:</p>
<div class="sourceCode" id="cb262"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb262-1"><a href="survival-analysis.html#cb262-1"></a>whas100<span class="fl">.1</span> &lt;-<span class="st"> </span><span class="kw">coxph</span>(y <span class="op">~</span><span class="st"> </span>age <span class="op">+</span><span class="st"> </span>gender <span class="op">+</span><span class="st"> </span>bmi, <span class="dt">data =</span> whas100)</span>
<span id="cb262-2"><a href="survival-analysis.html#cb262-2"></a><span class="kw">summary</span>(whas100<span class="fl">.1</span>)</span></code></pre></div>
<pre><code>## Call:
## coxph(formula = y ~ age + gender + bmi, data = whas100)
## 
##   n= 100, number of events= 51 
## 
##            coef exp(coef) se(coef)      z Pr(&gt;|z|)   
## age     0.03713   1.03783  0.01272  2.918  0.00352 **
## gender  0.14325   1.15402  0.30604  0.468  0.63973   
## bmi    -0.07083   0.93162  0.03607 -1.964  0.04956 * 
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
##        exp(coef) exp(-coef) lower .95 upper .95
## age       1.0378     0.9636    1.0123    1.0640
## gender    1.1540     0.8665    0.6334    2.1024
## bmi       0.9316     1.0734    0.8680    0.9999
## 
## Concordance= 0.683  (se = 0.037 )
## Likelihood ratio test= 21.54  on 3 df,   p=8e-05
## Wald test            = 19.46  on 3 df,   p=2e-04
## Score (logrank) test = 20.82  on 3 df,   p=1e-04</code></pre>
<p><span class="math inline">\(\blacksquare\)</span></p>
<ol start="4" style="list-style-type: lower-alpha">
<li>Test the overall fit of the model. What does the result mean?</li>
</ol>
<p>Solution</p>
<p>Look at those three P-values at the bottom. They are all small,
so something in the model is helping to predict survival. As to
what? Well, that’s the next part.</p>
<p><span class="math inline">\(\blacksquare\)</span></p>
<ol start="5" style="list-style-type: lower-alpha">
<li>Can any of your explanatory variables be removed from the
model? Explain briefly.</li>
</ol>
<p>Solution</p>
<p><code>gender</code> has a (very) large P-value, so that can be taken
out of the model. The other two variables have small P-values
(<code>bmi</code> only just under 0.05), so they need to stay.
The other way to think about this is <code>step</code>, or <code>drop1</code>:</p>
<div class="sourceCode" id="cb264"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb264-1"><a href="survival-analysis.html#cb264-1"></a><span class="kw">drop1</span>(whas100<span class="fl">.1</span>, <span class="dt">test =</span> <span class="st">&quot;Chisq&quot;</span>)</span></code></pre></div>
<pre><code>## Single term deletions
## 
## Model:
## y ~ age + gender + bmi
##        Df    AIC    LRT Pr(&gt;Chi)   
## &lt;none&gt;    402.66                   
## age     1 410.25 9.5972 0.001949 **
## gender  1 400.87 0.2185 0.640218   
## bmi     1 404.60 3.9389 0.047182 * 
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<p>This is here equivalent to<a href="#fn41" class="footnote-ref" id="fnref41"><sup>41</sup></a> the output
from <code>summary</code>, but where it
scores is if you have a categorical explanatory variable like
“treatment” with more than two levels: <code>drop1</code> will tell you
about keeping or dropping it as a whole.<a href="#fn42" class="footnote-ref" id="fnref42"><sup>42</sup></a></p>
<p>If you prefer:</p>
<div class="sourceCode" id="cb266"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb266-1"><a href="survival-analysis.html#cb266-1"></a><span class="kw">step</span>(whas100<span class="fl">.1</span>, <span class="dt">trace =</span> <span class="dv">0</span>, <span class="dt">test =</span> <span class="st">&quot;Chisq&quot;</span>)</span></code></pre></div>
<pre><code>## Call:
## coxph(formula = y ~ age + bmi, data = whas100)
## 
##         coef exp(coef) se(coef)      z        p
## age  0.03927   1.04005  0.01187  3.309 0.000938
## bmi -0.07116   0.93131  0.03614 -1.969 0.048952
## 
## Likelihood ratio test=21.32  on 2 df, p=2.346e-05
## n= 100, number of events= 51</code></pre>
<p><code>gender</code> comes out, but the others stay. As usual, put
<code>trace=1</code> or <code>trace=2</code> to get more output, which will
look like a sequence of <code>drop1</code>’s one after the other.</p>
<p><span class="math inline">\(\blacksquare\)</span></p>
<ol start="6" style="list-style-type: lower-alpha">
<li>Remove your most non-significant explanatory variable from
the model and fit again. Take a look at the results. Are all your
remaining explanatory variables significant? (If all your
explanatory variables were previously significant, you can skip this part.)</li>
</ol>
<p>Solution</p>
<p>So, take out <code>gender</code>:</p>
<div class="sourceCode" id="cb268"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb268-1"><a href="survival-analysis.html#cb268-1"></a>whas100<span class="fl">.2</span> &lt;-<span class="st"> </span><span class="kw">update</span>(whas100<span class="fl">.1</span>, . <span class="op">~</span><span class="st"> </span>. <span class="op">-</span><span class="st"> </span>gender)</span>
<span id="cb268-2"><a href="survival-analysis.html#cb268-2"></a><span class="kw">summary</span>(whas100<span class="fl">.2</span>)</span></code></pre></div>
<pre><code>## Call:
## coxph(formula = y ~ age + bmi, data = whas100)
## 
##   n= 100, number of events= 51 
## 
##         coef exp(coef) se(coef)      z Pr(&gt;|z|)    
## age  0.03927   1.04005  0.01187  3.309 0.000938 ***
## bmi -0.07116   0.93131  0.03614 -1.969 0.048952 *  
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
##     exp(coef) exp(-coef) lower .95 upper .95
## age    1.0401     0.9615    1.0161    1.0645
## bmi    0.9313     1.0738    0.8676    0.9997
## 
## Concordance= 0.681  (se = 0.037 )
## Likelihood ratio test= 21.32  on 2 df,   p=2e-05
## Wald test            = 19  on 2 df,   p=7e-05
## Score (logrank) test = 19.99  on 2 df,   p=5e-05</code></pre>
<p>Both explanatory variables are significant: <code>age</code> definitely,
<code>bmi</code> only just. This is the same model as <code>step</code> gave me.</p>
<p><span class="math inline">\(\blacksquare\)</span></p>
<ol start="7" style="list-style-type: lower-alpha">
<li>Calculate the 1st quartile, median, and 3rd quartiles of
age and BMI. (<code>quantile</code>.) Round these off to the
nearest whole number. (Do the rounding off yourself, though R has a
function <code>round</code> that does this, which you can investigate if
you want.) As an alternative, you can get these by passing the whole
data frame, or the columns of it you want, into <code>summary</code>.</li>
</ol>
<p>Solution</p>
<div class="sourceCode" id="cb270"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb270-1"><a href="survival-analysis.html#cb270-1"></a><span class="kw">quantile</span>(whas100<span class="op">$</span>age)</span></code></pre></div>
<pre><code>##    0%   25%   50%   75%  100% 
## 32.00 59.75 71.00 80.25 92.00</code></pre>
<div class="sourceCode" id="cb272"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb272-1"><a href="survival-analysis.html#cb272-1"></a><span class="kw">quantile</span>(whas100<span class="op">$</span>bmi)</span></code></pre></div>
<pre><code>##       0%      25%      50%      75%     100% 
## 14.91878 23.53717 27.19158 30.34770 39.93835</code></pre>
<p>or</p>
<div class="sourceCode" id="cb274"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb274-1"><a href="survival-analysis.html#cb274-1"></a>whas100 <span class="op">%&gt;%</span></span>
<span id="cb274-2"><a href="survival-analysis.html#cb274-2"></a><span class="st">  </span><span class="kw">select</span>(age, bmi) <span class="op">%&gt;%</span></span>
<span id="cb274-3"><a href="survival-analysis.html#cb274-3"></a><span class="st">  </span><span class="kw">summary</span>()</span></code></pre></div>
<pre><code>##       age             bmi       
##  Min.   :32.00   Min.   :14.92  
##  1st Qu.:59.75   1st Qu.:23.54  
##  Median :71.00   Median :27.19  
##  Mean   :68.25   Mean   :27.04  
##  3rd Qu.:80.25   3rd Qu.:30.35  
##  Max.   :92.00   Max.   :39.94</code></pre>
<p>Or, pure tidyverse: summarize all the columns (after you’ve done the <code>select</code>).</p>
<div class="sourceCode" id="cb276"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb276-1"><a href="survival-analysis.html#cb276-1"></a>whas100 <span class="op">%&gt;%</span></span>
<span id="cb276-2"><a href="survival-analysis.html#cb276-2"></a><span class="st">  </span><span class="kw">select</span>(age, bmi) <span class="op">%&gt;%</span></span>
<span id="cb276-3"><a href="survival-analysis.html#cb276-3"></a><span class="st">  </span><span class="kw">summarize</span>(<span class="kw">across</span>(<span class="kw">everything</span>(), <span class="op">~</span><span class="kw">list</span>(<span class="kw">quantile</span>(.)))) <span class="op">%&gt;%</span></span>
<span id="cb276-4"><a href="survival-analysis.html#cb276-4"></a><span class="st">  </span><span class="kw">unnest</span>()</span></code></pre></div>
<pre><code>## Warning: `cols` is now required when using unnest().
## Please use `cols = c(age, bmi)`</code></pre>
<pre><code>## # A tibble: 5 x 2
##     age   bmi
##   &lt;dbl&gt; &lt;dbl&gt;
## 1  32    14.9
## 2  59.8  23.5
## 3  71    27.2
## 4  80.2  30.3
## 5  92    39.9</code></pre>
<p>The reason for the <code>list()</code> and the <code>unnest()</code> is that
<code>quantile</code> returns five numbers rather than just one, so it has
to go into the output data frame as a list-column, which then gets
broken apart with <code>unnest</code> so that you can see it. Try it
without the <code>unnest()</code> line to see what happens if you don’t do
that.
Using whichever of this multitude of ways appeals to you:</p>
<p>60, 71 and 80 for age, 24, 27 and 30 for BMI.</p>
<p><span class="math inline">\(\blacksquare\)</span></p>
<ol start="8" style="list-style-type: lower-alpha">
<li>Make a data frame out of all the combinations of
age and BMI values (that you obtained in the previous part) suitable for predicting
with.</li>
</ol>
<p>Solution</p>
<p>The inevitable <code>crossing</code>. This is probably quickest:</p>
<div class="sourceCode" id="cb279"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb279-1"><a href="survival-analysis.html#cb279-1"></a>whas100.new &lt;-<span class="st"> </span><span class="kw">crossing</span>(<span class="dt">age =</span> <span class="kw">c</span>(<span class="dv">60</span>, <span class="dv">71</span>, <span class="dv">80</span>), <span class="dt">bmi =</span> <span class="kw">c</span>(<span class="dv">24</span>, <span class="dv">27</span>, <span class="dv">30</span>))</span>
<span id="cb279-2"><a href="survival-analysis.html#cb279-2"></a>whas100.new</span></code></pre></div>
<pre><code>## # A tibble: 9 x 2
##     age   bmi
##   &lt;dbl&gt; &lt;dbl&gt;
## 1    60    24
## 2    60    27
## 3    60    30
## 4    71    24
## 5    71    27
## 6    71    30
## 7    80    24
## 8    80    27
## 9    80    30</code></pre>
<p>Or, with some setup beforehand to make the <code>crossing</code>
clearer. This is my no-think approach, which is what I recommend;
vectors with plural names containing the values, and inside the
<code>crossing</code>, a singular name equals a plural one:</p>
<div class="sourceCode" id="cb281"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb281-1"><a href="survival-analysis.html#cb281-1"></a>ages &lt;-<span class="st"> </span><span class="kw">c</span>(<span class="dv">60</span>, <span class="dv">71</span>, <span class="dv">80</span>)</span>
<span id="cb281-2"><a href="survival-analysis.html#cb281-2"></a>bmis &lt;-<span class="st"> </span><span class="kw">c</span>(<span class="dv">24</span>, <span class="dv">27</span>, <span class="dv">30</span>)</span>
<span id="cb281-3"><a href="survival-analysis.html#cb281-3"></a>whas100.new &lt;-<span class="st"> </span><span class="kw">crossing</span>(<span class="dt">age =</span> ages, <span class="dt">bmi =</span> bmis)</span>
<span id="cb281-4"><a href="survival-analysis.html#cb281-4"></a>whas100.new</span></code></pre></div>
<pre><code>## # A tibble: 9 x 2
##     age   bmi
##   &lt;dbl&gt; &lt;dbl&gt;
## 1    60    24
## 2    60    27
## 3    60    30
## 4    71    24
## 5    71    27
## 6    71    30
## 7    80    24
## 8    80    27
## 9    80    30</code></pre>
<p><span class="math inline">\(\blacksquare\)</span></p>
<ol style="list-style-type: lower-roman">
<li>Obtain predicted survival probabilities for each of the values
in your new data frame. Use your best model. (You don’t need to look
at the results, though you can if you want to.)</li>
</ol>
<p>Solution</p>
<p>The magic word is <code>survfit</code> (which plays the role of
<code>predict</code> here). The best model is <code>whas100.2</code>,
with the non-significant <code>gender</code> removed:</p>
<div class="sourceCode" id="cb283"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb283-1"><a href="survival-analysis.html#cb283-1"></a>pp2 &lt;-<span class="st"> </span><span class="kw">survfit</span>(whas100<span class="fl">.2</span>, whas100.new, <span class="dt">data =</span> whas100)</span></code></pre></div>
<p>This doesn’t need the <code>data=</code> at the end (it works perfectly
well without), but the plot (later) seems to need it to be there. I
think the plot needs the information from the original data to be in
the predictions somewhere.</p>
<p>This is kind of long to look at (<code>summary(pp2)</code> would be the
thing), so we will need to make a graph of it. I gave it a name, since
I want to use it again later.</p>
<p><span class="math inline">\(\blacksquare\)</span></p>
<ol start="10" style="list-style-type: lower-alpha">
<li>Make a graph depicting the survival curves from
<code>survfit</code> with different colours distinguishing the different
survival curves.</li>
</ol>
<p>Solution</p>
<p>This is actually easy once you work out what to do:</p>
<div class="sourceCode" id="cb284"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb284-1"><a href="survival-analysis.html#cb284-1"></a><span class="kw">ggsurvplot</span>(pp2, <span class="dt">conf.int =</span> <span class="ot">FALSE</span>)</span></code></pre></div>
<p><img src="pasias_files/figure-html/worcester-13-1.png" width="672" /></p>
<p>Without the <code>conf.int</code> thing, you get confidence intervals for
each survival curve, which overlap each other and generally make the
plot look messy.</p>
<p>The “strata” are the different age-BMI combinations that you
predicted for, so it’s usually a good idea to list the “new”
prediction data frame, either here or when you assess the effects of
the variables (next part) so that you can see which is which:</p>
<div class="sourceCode" id="cb285"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb285-1"><a href="survival-analysis.html#cb285-1"></a>whas100.new</span></code></pre></div>
<pre><code>## # A tibble: 9 x 2
##     age   bmi
##   &lt;dbl&gt; &lt;dbl&gt;
## 1    60    24
## 2    60    27
## 3    60    30
## 4    71    24
## 5    71    27
## 6    71    30
## 7    80    24
## 8    80    27
## 9    80    30</code></pre>
<p><span class="math inline">\(\blacksquare\)</span></p>
<ol start="11" style="list-style-type: lower-alpha">
<li>What is the effect of age on survival? What is the effect
of BMI on survival? Explain briefly. (You will have to disentangle
the meaning of the different coloured lines on the plot to do this.)</li>
</ol>
<p>Solution</p>
<p>Bear in mind that up-and-to-the-right is best for a survival
curve, since that means that people in the upper-right group have
a higher chance of surviving for longer.</p>
<p>The best survival curve is therefore the olive-green one. According
to the legend, this goes with stratum 3, which is (according to
the listing of <code>whas100.new</code>) age 60 (the youngest) and BMI
30 (the highest). So it looks as if the best survival goes with a
lower age (not surprising) and a higher BMI (surprising; see
discussion about BMI below).</p>
<p>You can also leave one variable constant and see the effects of
changing the other one. Let’s pick the oldest age 80: the BMI
values are 24 (stratum 7, blue), 27 (stratum 8, purple), 30
(stratum 9, pink). These survival curves are the bottom one, the
second bottom one, and the fourth bottom one. At this age,
survival chances are not great, but having a higher BMI goes with
a greater chance of surviving longer.</p>
<p>Or pick a BMI, say 30. These are strata 3 (olive green), 6 (light blue)
and 9 (pink) respectively for ages 60, 71 and 80. These are the
best, 3rd best and 5th best survival curves; that is, as age
increases, the chance of surviving a long time decreases.</p>
<p>The effect of BMI, though, seems backwards: a higher BMI is
associated with a <em>higher</em> chance of survival.</p>
<p>That’s the end of what I wanted you to do, but:</p>
<p>A higher BMI is usually associated with being obese (and therefore
unhealthy), so you’d expect the effect of BMI to be the other way
around. According to Wikipedia
(<a href="http://en.wikipedia.org/wiki/Body_mass_index">link</a>), the BMI values
here are “overweight” or close to it. Maybe being heavier helps
the body recover from a heart attack.</p>
<p>Let’s start with the martingale residual plot:</p>
<div class="sourceCode" id="cb287"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb287-1"><a href="survival-analysis.html#cb287-1"></a><span class="kw">ggcoxdiagnostics</span>(whas100<span class="fl">.2</span>) <span class="op">+</span><span class="st"> </span><span class="kw">geom_smooth</span>()</span></code></pre></div>
<pre><code>## `geom_smooth()` using formula &#39;y ~ x&#39;</code></pre>
<pre><code>## `geom_smooth()` using method = &#39;loess&#39; and formula &#39;y ~ x&#39;</code></pre>
<p><img src="pasias_files/figure-html/worcester-15-1.png" width="672" /></p>
<p>There is a suspicion of bendiness here, though the left side of the
curve is entirely because of that one positive residual on the
left. In any case, this suggests that nonlinearity (evidently in terms
of BMI, since that’s the relationship that currently makes no sense)
would be worth exploring.</p>
<p>Thus:</p>
<div class="sourceCode" id="cb290"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb290-1"><a href="survival-analysis.html#cb290-1"></a>whas100<span class="fl">.3</span> &lt;-<span class="st"> </span><span class="kw">update</span>(whas100<span class="fl">.2</span>, . <span class="op">~</span><span class="st"> </span>. <span class="op">+</span><span class="st"> </span><span class="kw">I</span>(bmi<span class="op">^</span><span class="dv">2</span>))</span>
<span id="cb290-2"><a href="survival-analysis.html#cb290-2"></a><span class="kw">summary</span>(whas100<span class="fl">.3</span>)</span></code></pre></div>
<pre><code>## Call:
## coxph(formula = y ~ age + bmi + I(bmi^2), data = whas100)
## 
##   n= 100, number of events= 51 
## 
##               coef exp(coef)  se(coef)      z Pr(&gt;|z|)    
## age       0.040542  1.041375  0.012035  3.369 0.000755 ***
## bmi      -0.848949  0.427864  0.231562 -3.666 0.000246 ***
## I(bmi^2)  0.014500  1.014606  0.004227  3.430 0.000603 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
##          exp(coef) exp(-coef) lower .95 upper .95
## age         1.0414     0.9603    1.0171    1.0662
## bmi         0.4279     2.3372    0.2718    0.6736
## I(bmi^2)    1.0146     0.9856    1.0062    1.0230
## 
## Concordance= 0.693  (se = 0.04 )
## Likelihood ratio test= 30.71  on 3 df,   p=1e-06
## Wald test            = 32.56  on 3 df,   p=4e-07
## Score (logrank) test = 36.57  on 3 df,   p=6e-08</code></pre>
<p>Ah, that seems to be it. The significant positive coefficient on
<code>bmi</code>-squared
means that the “hazard of dying” increases faster with increasing
<code>bmi</code>, so there ought to be an optimal BMI beyond which
survival chances decrease again.
Have we improved the residuals by adding the squared term?</p>
<div class="sourceCode" id="cb292"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb292-1"><a href="survival-analysis.html#cb292-1"></a><span class="kw">ggcoxdiagnostics</span>(whas100<span class="fl">.3</span>) <span class="op">+</span><span class="st"> </span><span class="kw">geom_smooth</span>()</span></code></pre></div>
<pre><code>## `geom_smooth()` using formula &#39;y ~ x&#39;</code></pre>
<pre><code>## `geom_smooth()` using method = &#39;loess&#39; and formula &#39;y ~ x&#39;</code></pre>
<p><img src="pasias_files/figure-html/worcester-17-1.png" width="672" /></p>
<p>I call those “inconsequential wiggles” now, so I think we are good.
Let’s explore the quadratic relationship on a graph.</p>
<p>I’m going to focus on a close-to-median age of 70, since, in this
model, the effect of BMI is the same for all ages (to make it
different, we would need an interaction term, ANOVA-style).</p>
<p>First we create a data frame with a bunch of different BMIs in, and
one age 70:</p>
<div class="sourceCode" id="cb295"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb295-1"><a href="survival-analysis.html#cb295-1"></a>bmis &lt;-<span class="st"> </span><span class="kw">seq</span>(<span class="dv">20</span>, <span class="dv">36</span>, <span class="dv">4</span>)</span>
<span id="cb295-2"><a href="survival-analysis.html#cb295-2"></a>ages &lt;-<span class="st"> </span><span class="dv">70</span></span>
<span id="cb295-3"><a href="survival-analysis.html#cb295-3"></a>whas100.new<span class="fl">.2</span> &lt;-<span class="st"> </span><span class="kw">crossing</span>(<span class="dt">bmi =</span> bmis, <span class="dt">age =</span> ages)</span>
<span id="cb295-4"><a href="survival-analysis.html#cb295-4"></a>whas100.new<span class="fl">.2</span></span></code></pre></div>
<pre><code>## # A tibble: 5 x 2
##     bmi   age
##   &lt;dbl&gt; &lt;dbl&gt;
## 1    20    70
## 2    24    70
## 3    28    70
## 4    32    70
## 5    36    70</code></pre>
<p>It is rather absurd to have a plural <code>ages</code> with only one age
in it, but that’s the way it goes, if you’re me and trying to avoid thinking.</p>
<p>Predictions, using the model with the squared term in it:</p>
<div class="sourceCode" id="cb297"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb297-1"><a href="survival-analysis.html#cb297-1"></a>pp3 &lt;-<span class="st"> </span><span class="kw">survfit</span>(whas100<span class="fl">.3</span>, whas100.new<span class="fl">.2</span>, <span class="dt">data =</span> whas100)</span></code></pre></div>
<p>And then the plot:</p>
<div class="sourceCode" id="cb298"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb298-1"><a href="survival-analysis.html#cb298-1"></a><span class="kw">ggsurvplot</span>(pp3, <span class="dt">conf.int =</span> F)</span></code></pre></div>
<p><img src="pasias_files/figure-html/worcester-20-1.png" width="672" /></p>
<p>and the customary reminder of which stratum is which, with its rather
ungainly name:</p>
<div class="sourceCode" id="cb299"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb299-1"><a href="survival-analysis.html#cb299-1"></a>whas100.new<span class="fl">.2</span></span></code></pre></div>
<pre><code>## # A tibble: 5 x 2
##     bmi   age
##   &lt;dbl&gt; &lt;dbl&gt;
## 1    20    70
## 2    24    70
## 3    28    70
## 4    32    70
## 5    36    70</code></pre>
<p>This time, the green survival curve is best, stratum 3, which means that
survival is best at BMI 28, and worse for both higher BMIs and lower
BMIs. You can follow the sequence of colours: red, olive-green, green,
blue, pink, that goes up and then down again. But it’s still true
that having a very <em>low</em> BMI is worst, which is why our (linear)
model said that having a higher BMI was better.</p>
<p>It would have been better to have you put a squared term in the model,
but the question was already long and complicated enough, and I
didn’t want to make your lives more of a nightmare than they are
already becoming!</p>
<p><span class="math inline">\(\blacksquare\)</span></p>
</div>
<div id="drug-treatment-programs-1" class="section level2" number="29.6">
<h2><span class="header-section-number">29.6</span> Drug treatment programs</h2>
<p>One of the goals of drug treatment programs is to lengthen
the time until the patient returns to using drugs. (It is not
generally possible to prevent patients from <em>ever</em> using drugs
again.) In one study, over 600 former drug users took part. Two
different programs, a short program and a long program, were offered
at two different sites, labelled A and B. The data can be found in
<a href="http://ritsokiguess.site/datafiles/drugusers.txt">link</a>. The
variables are these:</p>
<ul>
<li><p><code>ID</code>: patient ID number</p></li>
<li><p><code>age</code>: patient age at enrollment into the study</p></li>
<li><p><code>ndrugtx</code>: number of previous drug treatments</p></li>
<li><p><code>treat</code>: 0 for short treatment program, 1 for long program</p></li>
<li><p><code>site</code>: 0 for site A, 1 for site B</p></li>
<li><p><code>time</code>: time until return to drug use</p></li>
<li><p><code>censor</code>: whether the subject returned to drug use (1) or
not (0) during the follow-up period</p></li>
<li><p><code>herco</code>: whether subject used heroine or cocaine in the
last 3 months: 1 is both, 2 is one (either heroine or cocaine), 3 is neither.</p></li>
</ul>
<ol style="list-style-type: lower-alpha">
<li>Read in the data and check in one way or another that you
have what was promised above.</li>
</ol>
<p>Solution</p>
<p>This:</p>
<div class="sourceCode" id="cb301"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb301-1"><a href="survival-analysis.html#cb301-1"></a>my_url &lt;-<span class="st"> &quot;http://ritsokiguess.site/datafiles/drugusers.txt&quot;</span></span>
<span id="cb301-2"><a href="survival-analysis.html#cb301-2"></a>drugusers &lt;-<span class="st"> </span><span class="kw">read_delim</span>(my_url, <span class="st">&quot; &quot;</span>)</span></code></pre></div>
<pre><code>## 
## ── Column specification ────────────────────────────────────────────────────────
## cols(
##   row = col_double(),
##   ID = col_double(),
##   age = col_double(),
##   ndrugtx = col_double(),
##   treat = col_double(),
##   site = col_double(),
##   time = col_double(),
##   censor = col_double(),
##   herco = col_double()
## )</code></pre>
<div class="sourceCode" id="cb303"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb303-1"><a href="survival-analysis.html#cb303-1"></a>drugusers</span></code></pre></div>
<pre><code>## # A tibble: 628 x 9
##      row    ID   age ndrugtx treat  site  time censor herco
##    &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt;   &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt;  &lt;dbl&gt; &lt;dbl&gt;
##  1     1     1    39       1     1     0   188      1     3
##  2     2     2    33       8     1     0    26      1     3
##  3     3     3    33       3     1     0   207      1     2
##  4     4     4    32       1     0     0   144      1     3
##  5     5     5    24       5     1     0   551      0     2
##  6     6     6    30       1     1     0    32      1     1
##  7     7     7    39      34     1     0   459      1     3
##  8     8     8    27       2     1     0    22      1     3
##  9     9     9    40       3     1     0   210      1     2
## 10    10    10    36       7     1     0   184      1     2
## # … with 618 more rows</code></pre>
<p>This shows that you have over 600 rows and the variables described.</p>
<p><span class="math inline">\(\blacksquare\)</span></p>
<ol start="2" style="list-style-type: lower-alpha">
<li>There are some missing values in the dataframe. Demonstrate
this using <code>summary</code>. Pipe the dataframe into
<code>drop_na</code> and show that they have gone. (<code>drop_na</code>
removes all rows that have missing values in them.)</li>
</ol>
<p>Solution</p>
<p>First off, <code>summary</code> is a quick way to show how many missing
values there are:<a href="#fn43" class="footnote-ref" id="fnref43"><sup>43</sup></a></p>
<div class="sourceCode" id="cb305"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb305-1"><a href="survival-analysis.html#cb305-1"></a><span class="kw">summary</span>(drugusers)</span></code></pre></div>
<pre><code>##       row              ID             age           ndrugtx      
##  Min.   :  1.0   Min.   :  1.0   Min.   :20.00   Min.   : 0.000  
##  1st Qu.:157.8   1st Qu.:157.8   1st Qu.:27.00   1st Qu.: 1.000  
##  Median :314.5   Median :314.5   Median :32.00   Median : 3.000  
##  Mean   :314.5   Mean   :314.5   Mean   :32.37   Mean   : 4.574  
##  3rd Qu.:471.2   3rd Qu.:471.2   3rd Qu.:37.00   3rd Qu.: 6.000  
##  Max.   :628.0   Max.   :628.0   Max.   :56.00   Max.   :40.000  
##                                  NA&#39;s   :5       NA&#39;s   :17      
##      treat             site            time            censor      
##  Min.   :0.0000   Min.   :0.000   Min.   :   2.0   Min.   :0.0000  
##  1st Qu.:0.0000   1st Qu.:0.000   1st Qu.:  79.0   1st Qu.:1.0000  
##  Median :0.0000   Median :0.000   Median : 166.0   Median :1.0000  
##  Mean   :0.4904   Mean   :0.293   Mean   : 234.7   Mean   :0.8089  
##  3rd Qu.:1.0000   3rd Qu.:1.000   3rd Qu.: 365.2   3rd Qu.:1.0000  
##  Max.   :1.0000   Max.   :1.000   Max.   :1172.0   Max.   :1.0000  
##                                                                    
##      herco      
##  Min.   :1.000  
##  1st Qu.:1.000  
##  Median :2.000  
##  Mean   :1.898  
##  3rd Qu.:3.000  
##  Max.   :3.000  
## </code></pre>
<p>Age has five missing values and “number of previous drug treatments”
has seventeen.</p>
<p>Following the instructions, and saving back into the original dataframe:</p>
<div class="sourceCode" id="cb307"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb307-1"><a href="survival-analysis.html#cb307-1"></a>drugusers <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">drop_na</span>() -&gt;<span class="st"> </span>drugusers</span></code></pre></div>
<p>and then</p>
<div class="sourceCode" id="cb308"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb308-1"><a href="survival-analysis.html#cb308-1"></a><span class="kw">summary</span>(drugusers)</span></code></pre></div>
<pre><code>##       row              ID             age           ndrugtx      
##  Min.   :  1.0   Min.   :  1.0   Min.   :20.00   Min.   : 0.000  
##  1st Qu.:155.2   1st Qu.:155.2   1st Qu.:27.00   1st Qu.: 1.000  
##  Median :312.5   Median :312.5   Median :32.00   Median : 3.000  
##  Mean   :313.8   Mean   :313.8   Mean   :32.39   Mean   : 4.579  
##  3rd Qu.:473.8   3rd Qu.:473.8   3rd Qu.:37.00   3rd Qu.: 6.000  
##  Max.   :628.0   Max.   :628.0   Max.   :56.00   Max.   :40.000  
##      treat             site             time            censor      
##  Min.   :0.0000   Min.   :0.0000   Min.   :   2.0   Min.   :0.0000  
##  1st Qu.:0.0000   1st Qu.:0.0000   1st Qu.:  79.0   1st Qu.:1.0000  
##  Median :0.0000   Median :0.0000   Median : 166.0   Median :1.0000  
##  Mean   :0.4918   Mean   :0.2984   Mean   : 234.4   Mean   :0.8115  
##  3rd Qu.:1.0000   3rd Qu.:1.0000   3rd Qu.: 361.8   3rd Qu.:1.0000  
##  Max.   :1.0000   Max.   :1.0000   Max.   :1172.0   Max.   :1.0000  
##      herco     
##  Min.   :1.00  
##  1st Qu.:1.00  
##  Median :2.00  
##  Mean   :1.89  
##  3rd Qu.:3.00  
##  Max.   :3.00</code></pre>
<p>No NA left. Gosh, as they say, that was easy.
Extra: how many rows did we lose?</p>
<div class="sourceCode" id="cb310"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb310-1"><a href="survival-analysis.html#cb310-1"></a><span class="kw">nrow</span>(drugusers)</span></code></pre></div>
<pre><code>## [1] 610</code></pre>
<p>There were 628 rows before, so we lost 18. (There were 22 missing
values, but some of them were two on one row, so we only lost 18
rows.)</p>
<p>This is a very unsophisticated way of dealing with missing
values. Another way is to “impute” them, that is, to guess what they
would have been, and then fill in the guessed values and use them as
if they were the truth, for example by regressing the columns with missing values on all the others, and using the regression predictions in place of the missing values.</p>
<p><span class="math inline">\(\blacksquare\)</span></p>
<ol start="3" style="list-style-type: lower-alpha">
<li>Some of these variables are recorded as numbers but are
actually categorical. Which ones? Re-define these variables in your
data frame so that they have sensible (text) values.</li>
</ol>
<p>Solution</p>
<p>These variables are actually categorical rather than quantitative:</p>
<ul>
<li><p><code>treat</code></p></li>
<li><p><code>site</code></p></li>
<li><p><code>censor</code></p></li>
<li><p><code>herco</code></p></li>
</ul>
<p>Most of them have only two levels, so it doesn’t matter whether
we make them categorical or leave them as numbers, but for
<code>herco</code> it matters. Let’s give them all sensible values,
mostly with <code>ifelse</code>,<a href="#fn44" class="footnote-ref" id="fnref44"><sup>44</sup></a> thus:</p>
<div class="sourceCode" id="cb312"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb312-1"><a href="survival-analysis.html#cb312-1"></a>drugusers <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">mutate</span>(</span>
<span id="cb312-2"><a href="survival-analysis.html#cb312-2"></a>  <span class="dt">treat =</span> <span class="kw">ifelse</span>(treat <span class="op">==</span><span class="st"> </span><span class="dv">0</span>, <span class="st">&quot;short&quot;</span>, <span class="st">&quot;long&quot;</span>),</span>
<span id="cb312-3"><a href="survival-analysis.html#cb312-3"></a>  <span class="dt">site =</span> <span class="kw">ifelse</span>(site <span class="op">==</span><span class="st"> </span><span class="dv">0</span>, <span class="st">&quot;A&quot;</span>, <span class="st">&quot;B&quot;</span>),</span>
<span id="cb312-4"><a href="survival-analysis.html#cb312-4"></a>  <span class="dt">censor =</span> <span class="kw">ifelse</span>(censor <span class="op">==</span><span class="st"> </span><span class="dv">1</span>, <span class="st">&quot;returned&quot;</span>, <span class="st">&quot;no-return&quot;</span>),</span>
<span id="cb312-5"><a href="survival-analysis.html#cb312-5"></a>  <span class="dt">herco =</span> <span class="kw">case_when</span>(</span>
<span id="cb312-6"><a href="survival-analysis.html#cb312-6"></a>    herco <span class="op">==</span><span class="st"> </span><span class="dv">1</span> <span class="op">~</span><span class="st"> &quot;both&quot;</span>,</span>
<span id="cb312-7"><a href="survival-analysis.html#cb312-7"></a>    herco <span class="op">==</span><span class="st"> </span><span class="dv">2</span> <span class="op">~</span><span class="st"> &quot;one&quot;</span>,</span>
<span id="cb312-8"><a href="survival-analysis.html#cb312-8"></a>    herco <span class="op">==</span><span class="st"> </span><span class="dv">3</span> <span class="op">~</span><span class="st"> &quot;neither&quot;</span></span>
<span id="cb312-9"><a href="survival-analysis.html#cb312-9"></a>  )</span>
<span id="cb312-10"><a href="survival-analysis.html#cb312-10"></a>) -&gt;<span class="st"> </span>drugusers</span></code></pre></div>
<p>I’m living on the edge and overwriting everything:</p>
<div class="sourceCode" id="cb313"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb313-1"><a href="survival-analysis.html#cb313-1"></a>drugusers</span></code></pre></div>
<pre><code>## # A tibble: 610 x 9
##      row    ID   age ndrugtx treat site   time censor    herco  
##    &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt;   &lt;dbl&gt; &lt;chr&gt; &lt;chr&gt; &lt;dbl&gt; &lt;chr&gt;     &lt;chr&gt;  
##  1     1     1    39       1 long  A       188 returned  neither
##  2     2     2    33       8 long  A        26 returned  neither
##  3     3     3    33       3 long  A       207 returned  one    
##  4     4     4    32       1 short A       144 returned  neither
##  5     5     5    24       5 long  A       551 no-return one    
##  6     6     6    30       1 long  A        32 returned  both   
##  7     7     7    39      34 long  A       459 returned  neither
##  8     8     8    27       2 long  A        22 returned  neither
##  9     9     9    40       3 long  A       210 returned  one    
## 10    10    10    36       7 long  A       184 returned  one    
## # … with 600 more rows</code></pre>
<p><span class="math inline">\(\blacksquare\)</span></p>
<ol start="4" style="list-style-type: lower-alpha">
<li>Create a suitable reponse variable for a Cox proportional
hazards regression that predicts time until return to drug use from
the other variables.
This requires some care, because you need to be sure about what the
censoring variable actually represents and what you need it to represent.</li>
</ol>
<p>Solution</p>
<p>This is <code>Surv</code> in package <code>survival</code>. The response
variable needs to encode two things: the time until the event of
interest (return to drug use) and whether or not that event
happened for each patient.<a href="#fn45" class="footnote-ref" id="fnref45"><sup>45</sup></a>
In this case, that is
<code>censor="returned"</code>.</p>
<div class="sourceCode" id="cb315"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb315-1"><a href="survival-analysis.html#cb315-1"></a>y &lt;-<span class="st"> </span><span class="kw">with</span>(drugusers, <span class="kw">Surv</span>(time, censor <span class="op">==</span><span class="st"> &quot;returned&quot;</span>))</span></code></pre></div>
<p>Use whatever name you gave to the level of <code>censor</code> that means “returned to drug use”.</p>
<p><span class="math inline">\(\blacksquare\)</span></p>
<ol start="5" style="list-style-type: lower-alpha">
<li>Look at the first few values of your response variable. Why
is the fifth one marked with a <code>+</code>? Explain briefly.</li>
</ol>
<p>Solution</p>
<p><code>head</code> works as well with a vector (displaying the first
six values) as it does with a data frame:</p>
<div class="sourceCode" id="cb316"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb316-1"><a href="survival-analysis.html#cb316-1"></a><span class="kw">head</span>(y)</span></code></pre></div>
<pre><code>## [1] 188   26  207  144  551+  32</code></pre>
<p>The fifth value is marked with a <code>+</code> because it is a censored
value: this is a patient who was never observed to go back to drug
use. You can tell this by looking at the <code>head</code> of the entire
data frame:</p>
<div class="sourceCode" id="cb318"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb318-1"><a href="survival-analysis.html#cb318-1"></a><span class="kw">head</span>(drugusers)</span></code></pre></div>
<pre><code>## # A tibble: 6 x 9
##     row    ID   age ndrugtx treat site   time censor    herco  
##   &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt;   &lt;dbl&gt; &lt;chr&gt; &lt;chr&gt; &lt;dbl&gt; &lt;chr&gt;     &lt;chr&gt;  
## 1     1     1    39       1 long  A       188 returned  neither
## 2     2     2    33       8 long  A        26 returned  neither
## 3     3     3    33       3 long  A       207 returned  one    
## 4     4     4    32       1 short A       144 returned  neither
## 5     5     5    24       5 long  A       551 no-return one    
## 6     6     6    30       1 long  A        32 returned  both</code></pre>
<p>since this patient has <code>censor="no-return"</code>. The other ones have
<code>censor="returned"</code>; these are all “uncensored” in the jargon.</p>
<p>Typically, censored values will be bigger than uncensored ones,
because (in general) the individual will be observed until the study
ends, and studies of this kind carry on for years:</p>
<div class="sourceCode" id="cb320"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb320-1"><a href="survival-analysis.html#cb320-1"></a><span class="kw">ggplot</span>(drugusers, <span class="kw">aes</span>(<span class="dt">x =</span> censor, <span class="dt">y =</span> time)) <span class="op">+</span><span class="st"> </span><span class="kw">geom_boxplot</span>()</span></code></pre></div>
<p><img src="pasias_files/figure-html/drug-treatment-11-1.png" width="672" /></p>
<p>Yep. The smallest time for a censored observation would be an upper outlier
if it were observed for an uncensored observation.</p>
<p>One nice side-effect of turning <code>censor</code> into a categorical variable is that it can now
distinguish groups as a boxplot requires.</p>
<p>I discovered something rather amusing when I originally wrote this (a
year ago). Suppose you want to compare times for the two treatment
groups, and you <em>also</em> want to distinguish censored from
non-censored observations. Then, this works:</p>
<div class="sourceCode" id="cb321"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb321-1"><a href="survival-analysis.html#cb321-1"></a><span class="kw">ggplot</span>(drugusers, <span class="kw">aes</span>(<span class="dt">x =</span> treat, <span class="dt">y =</span> time, <span class="dt">colour =</span> censor)) <span class="op">+</span></span>
<span id="cb321-2"><a href="survival-analysis.html#cb321-2"></a><span class="st">  </span><span class="kw">geom_boxplot</span>()</span></code></pre></div>
<p><img src="pasias_files/figure-html/drug-treatment-12-1.png" width="672" /></p>
<p>For each treatment, you get side-by-side boxplots of the times for
censored (red) and uncensored (blue) observations, and so you see for
both treatments (short and long) the censored times are typically
longer than the uncensored ones.</p>
<p>(This you may recognize as a “grouped boxplot”, for when we have two
categorical variables and one quantitative one.)</p>
<p>I borrow this idea for two-way ANOVA (coming up later).</p>
<p><span class="math inline">\(\blacksquare\)</span></p>
<ol start="6" style="list-style-type: lower-alpha">
<li>Fit a Cox proportional hazards model, predicting from all
the other variables (except for <code>row</code> and <code>ID</code>) that you haven’t used
yet. Display the results.</li>
</ol>
<p>Solution</p>
<div class="sourceCode" id="cb322"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb322-1"><a href="survival-analysis.html#cb322-1"></a>drugusers<span class="fl">.1</span> &lt;-<span class="st"> </span><span class="kw">coxph</span>(y <span class="op">~</span><span class="st"> </span>age <span class="op">+</span><span class="st"> </span>ndrugtx <span class="op">+</span><span class="st"> </span>treat <span class="op">+</span><span class="st"> </span>site <span class="op">+</span><span class="st"> </span>herco, <span class="dt">data =</span> drugusers)</span>
<span id="cb322-2"><a href="survival-analysis.html#cb322-2"></a><span class="kw">summary</span>(drugusers<span class="fl">.1</span>)</span></code></pre></div>
<pre><code>## Call:
## coxph(formula = y ~ age + ndrugtx + treat + site + herco, data = drugusers)
## 
##   n= 610, number of events= 495 
## 
##                   coef exp(coef)  se(coef)      z Pr(&gt;|z|)    
## age          -0.023798  0.976483  0.007561 -3.148  0.00165 ** 
## ndrugtx       0.034815  1.035429  0.007755  4.490 7.14e-06 ***
## treatshort    0.254606  1.289953  0.091006  2.798  0.00515 ** 
## siteB        -0.173021  0.841120  0.102105 -1.695  0.09016 .  
## herconeither  0.125779  1.134032  0.103075  1.220  0.22236    
## hercoone      0.247318  1.280586  0.122759  2.015  0.04394 *  
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
##              exp(coef) exp(-coef) lower .95 upper .95
## age             0.9765     1.0241    0.9621    0.9911
## ndrugtx         1.0354     0.9658    1.0198    1.0513
## treatshort      1.2900     0.7752    1.0792    1.5418
## siteB           0.8411     1.1889    0.6886    1.0275
## herconeither    1.1340     0.8818    0.9266    1.3879
## hercoone        1.2806     0.7809    1.0067    1.6289
## 
## Concordance= 0.581  (se = 0.014 )
## Likelihood ratio test= 35.08  on 6 df,   p=4e-06
## Wald test            = 36.96  on 6 df,   p=2e-06
## Score (logrank) test = 37.36  on 6 df,   p=1e-06</code></pre>
<p>Another way to handle
“all the other <span class="math inline">\(x\)</span>’s except <code>row</code>, <code>ID</code>, <code>time</code> and <code>censor</code>” is this:</p>
<div class="sourceCode" id="cb324"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb324-1"><a href="survival-analysis.html#cb324-1"></a>drugusers<span class="fl">.1</span>a &lt;-<span class="st"> </span><span class="kw">coxph</span>(y <span class="op">~</span><span class="st"> </span>. <span class="op">-</span><span class="st"> </span>row <span class="op">-</span><span class="st"> </span>ID <span class="op">-</span><span class="st"> </span>time <span class="op">-</span><span class="st"> </span>censor, <span class="dt">data =</span> drugusers)</span>
<span id="cb324-2"><a href="survival-analysis.html#cb324-2"></a>broom<span class="op">::</span><span class="kw">tidy</span>(drugusers<span class="fl">.1</span>a)</span></code></pre></div>
<pre><code>## # A tibble: 6 x 5
##   term         estimate std.error statistic    p.value
##   &lt;chr&gt;           &lt;dbl&gt;     &lt;dbl&gt;     &lt;dbl&gt;      &lt;dbl&gt;
## 1 age           -0.0238   0.00756     -3.15 0.00165   
## 2 ndrugtx        0.0348   0.00775      4.49 0.00000714
## 3 treatshort     0.255    0.0910       2.80 0.00515   
## 4 siteB         -0.173    0.102       -1.69 0.0902    
## 5 herconeither   0.126    0.103        1.22 0.222     
## 6 hercoone       0.247    0.123        2.01 0.0439</code></pre>
<p>Same. I used <code>tidy</code> from <code>broom</code> to shorten the output a bit.</p>
<p><span class="math inline">\(\blacksquare\)</span></p>
<ol start="7" style="list-style-type: lower-alpha">
<li>Find which explanatory variables can be removed at <span class="math inline">\(\alpha=0.05\)</span>
(there should be two of them). Bear in mind that we have categorical variables, so that looking at the output from <code>summary</code> is not enough.</li>
</ol>
<p>Solution</p>
<p>The hint is meant to suggest to you that looking at <code>drop1</code> is the right way to go:</p>
<div class="sourceCode" id="cb326"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb326-1"><a href="survival-analysis.html#cb326-1"></a><span class="kw">drop1</span>(drugusers<span class="fl">.1</span>, <span class="dt">test =</span> <span class="st">&quot;Chisq&quot;</span>)</span></code></pre></div>
<pre><code>## Single term deletions
## 
## Model:
## y ~ age + ndrugtx + treat + site + herco
##         Df    AIC     LRT  Pr(&gt;Chi)    
## &lt;none&gt;     5712.2                      
## age      1 5720.3 10.0972  0.001485 ** 
## ndrugtx  1 5727.3 17.1446 3.464e-05 ***
## treat    1 5718.0  7.8352  0.005124 ** 
## site     1 5713.1  2.9335  0.086760 .  
## herco    2 5712.5  4.3182  0.115427    
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<p>Note that <code>herco</code>, a categorical variable with three levels,
has 2 degrees of freedom here, since a test of
“no effect of <code>herco</code>” is testing that survival is the same at
<em>all three</em> levels of <code>herco</code>.</p>
<p><span class="math inline">\(\blacksquare\)</span></p>
<ol start="8" style="list-style-type: lower-alpha">
<li>Remove <em>all</em> the non-significant explanatory variables
and re-fit your model. By carrying out a suitable test demonstrate
that your smaller model is the better one.</li>
</ol>
<p>Solution</p>
<p><code>site</code> and <code>herco</code> are the two variables to come
out.<a href="#fn46" class="footnote-ref" id="fnref46"><sup>46</sup></a> I like
<code>update</code>, but there is no
problem about copying-pasting your <code>coxph</code> and taking out
what you no longer need.</p>
<div class="sourceCode" id="cb328"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb328-1"><a href="survival-analysis.html#cb328-1"></a>drugusers<span class="fl">.2</span> &lt;-<span class="st"> </span><span class="kw">update</span>(drugusers<span class="fl">.1</span>, . <span class="op">~</span><span class="st"> </span>. <span class="op">-</span><span class="st"> </span>site <span class="op">-</span><span class="st"> </span>herco)</span></code></pre></div>
<p>Having fit two models, we can use <code>anova</code> to compare them. The
right test gets done, so no need for <code>test=</code>:</p>
<div class="sourceCode" id="cb329"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb329-1"><a href="survival-analysis.html#cb329-1"></a><span class="kw">anova</span>(drugusers<span class="fl">.2</span>, drugusers<span class="fl">.1</span>)</span></code></pre></div>
<pre><code>## Analysis of Deviance Table
##  Cox model: response is  y
##  Model 1: ~ age + ndrugtx + treat
##  Model 2: ~ age + ndrugtx + treat + site + herco
##    loglik  Chisq Df P(&gt;|Chi|)  
## 1 -2853.7                      
## 2 -2850.1 7.2117  3   0.06545 .
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<p>There is no significant difference between these two
models,<a href="#fn47" class="footnote-ref" id="fnref47"><sup>47</sup></a> so we can go with the
smaller, simpler one
(with just <code>age</code>, <code>ndrugtx</code> and <code>treat</code>).</p>
<p><span class="math inline">\(\blacksquare\)</span></p>
<ol style="list-style-type: lower-roman">
<li><a name="part:posneg">*</a> Display your better model. Are all of the
explanatory variables significant? Do their slope coefficients have
sensible signs (plus or minus), based on what you know or can guess
about drug treatments? Explain briefly.</li>
</ol>
<p>Solution</p>
<div class="sourceCode" id="cb331"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb331-1"><a href="survival-analysis.html#cb331-1"></a><span class="kw">summary</span>(drugusers<span class="fl">.2</span>)</span></code></pre></div>
<pre><code>## Call:
## coxph(formula = y ~ age + ndrugtx + treat, data = drugusers)
## 
##   n= 610, number of events= 495 
## 
##                 coef exp(coef)  se(coef)      z Pr(&gt;|z|)    
## age        -0.020801  0.979414  0.007419 -2.804  0.00505 ** 
## ndrugtx     0.035567  1.036207  0.007621  4.667 3.05e-06 ***
## treatshort  0.231055  1.259929  0.090175  2.562  0.01040 *  
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
##            exp(coef) exp(-coef) lower .95 upper .95
## age           0.9794     1.0210    0.9653    0.9938
## ndrugtx       1.0362     0.9651    1.0208    1.0518
## treatshort    1.2599     0.7937    1.0558    1.5035
## 
## Concordance= 0.572  (se = 0.014 )
## Likelihood ratio test= 27.87  on 3 df,   p=4e-06
## Wald test            = 30.5  on 3 df,   p=1e-06
## Score (logrank) test = 30.62  on 3 df,   p=1e-06</code></pre>
<p>The three remaining explanatory variables are all clearly significant:
the patient’s age, the number of previous drug treatments, and whether
the treatment was short or long. This is legit (we don’t need to run
<code>drop1</code> again) because the remaining explanatory variables are
all quantitative or have only two levels, so that the single-df tests
in <code>summary</code> are what we need.</p>
<p>Do their slope coefficients have sensible signs? Well, this requires
careful thought. A positive coefficient means that increasing that
variable <em>increases the hazard of the event</em>: ie., it makes the
event likelier to happen sooner. Here, the “event” is
“return to drug use”:</p>
<ul>
<li><p>Age has a negative coefficient, so an older person is likely to take
<em>longer</em> to return to drug use, other things being equal. This
makes some kind of sense, if you imagine drug use as being related to
maturity, or an older drug user as being more strongly committed to
“turning their life around”, so that a drug treatment of any kind is
going to be more effective on an older patient.</p></li>
<li><p>The number of previous treatments has a positive coefficient, so that a
patient who has had a lot of previous treatments is likely to go back
to drugs sooner. Such a person might be an “addict” for whom
treatments really do not work, or might not be committed to giving up drugs.</p></li>
<li><p><code>treatshort</code> has a positive coefficient. This says that
if you give a patient a short treatment, they are more likely (other
things being equal) to go back to drugs sooner, as compared to the
baseline long treatment. That is, a longer treatment is more
effective than a shorter one. Given a significant effect of
treatment length, this is the way around you would expect it to be.</p></li>
</ul>
<p><span class="math inline">\(\blacksquare\)</span></p>
<ol start="10" style="list-style-type: lower-alpha">
<li>We have three variables left in our model, <code>age</code>,
<code>ndrugtx</code> and <code>treat</code>. The quartiles of age are 27 and
37, the quartiles of <code>ndrugtx</code> are 1 and 6, and the two
possible values of <code>treat</code> are <code>short</code> and <code>long</code>. Create a data frame
with variables of these names and all possible combinations of their
values (so there should be 8 rows in the resulting data
frame). Display the resulting data frame.</li>
</ol>
<p>Solution</p>
<p>This data frame is going to be used for prediction, so I will
call it <code>new</code> and construct it in pieces as I did before
(thus meaning that I don’t have to think too hard about what I’m doing):</p>
<div class="sourceCode" id="cb333"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb333-1"><a href="survival-analysis.html#cb333-1"></a>ages &lt;-<span class="st"> </span><span class="kw">c</span>(<span class="dv">27</span>, <span class="dv">37</span>)</span>
<span id="cb333-2"><a href="survival-analysis.html#cb333-2"></a>ndrugtxs &lt;-<span class="st"> </span><span class="kw">c</span>(<span class="dv">1</span>, <span class="dv">6</span>)</span>
<span id="cb333-3"><a href="survival-analysis.html#cb333-3"></a>treats &lt;-<span class="st"> </span><span class="kw">c</span>(<span class="st">&quot;short&quot;</span>, <span class="st">&quot;long&quot;</span>)</span>
<span id="cb333-4"><a href="survival-analysis.html#cb333-4"></a>new &lt;-<span class="st"> </span><span class="kw">crossing</span>(<span class="dt">age =</span> ages, <span class="dt">ndrugtx =</span> ndrugtxs, <span class="dt">treat =</span> treats)</span>
<span id="cb333-5"><a href="survival-analysis.html#cb333-5"></a>new</span></code></pre></div>
<pre><code>## # A tibble: 8 x 3
##     age ndrugtx treat
##   &lt;dbl&gt;   &lt;dbl&gt; &lt;chr&gt;
## 1    27       1 long 
## 2    27       1 short
## 3    27       6 long 
## 4    27       6 short
## 5    37       1 long 
## 6    37       1 short
## 7    37       6 long 
## 8    37       6 short</code></pre>
<p>8 rows as promised.</p>
<p><span class="math inline">\(\blacksquare\)</span></p>
<ol start="11" style="list-style-type: lower-alpha">
<li>Obtain predicted survival probabilities for each of the
values of <code>age</code>, <code>ndrugtx</code> and <code>treat</code> used in
the previous part. You don’t need to display it (we are going to
plot it shortly).</li>
</ol>
<p>Solution</p>
<p><code>survfit</code> is the survival analysis version of
<code>predict</code> and works the same way, so this is all you need:</p>
<div class="sourceCode" id="cb335"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb335-1"><a href="survival-analysis.html#cb335-1"></a>pp &lt;-<span class="st"> </span><span class="kw">survfit</span>(drugusers<span class="fl">.2</span>, new, <span class="dt">data =</span> drugusers)</span></code></pre></div>
<p>Make sure that you use your best model, ie. the second one. The
<code>data=</code> is needed for the plot below, not in itself for the
prediction.</p>
<p><span class="math inline">\(\blacksquare\)</span></p>
<ol start="12" style="list-style-type: lower-alpha">
<li>Plot your predicted survival curves.</li>
</ol>
<p>Solution</p>
<p>This:</p>
<div class="sourceCode" id="cb336"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb336-1"><a href="survival-analysis.html#cb336-1"></a><span class="kw">ggsurvplot</span>(pp, <span class="dt">conf.int =</span> F)</span></code></pre></div>
<p><img src="pasias_files/figure-html/drug-treatment-21-1.png" width="672" /></p>
<p>The only thing to remember is that you plot your <em>predictions</em>,
not the model from which they came.</p>
<p>If your plot didn’t come out, you may have to go back and re-do the
<code>survfit</code> with the <code>data=</code> at the end.</p>
<p>For reference in a minute:</p>
<div class="sourceCode" id="cb337"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb337-1"><a href="survival-analysis.html#cb337-1"></a>new</span></code></pre></div>
<pre><code>## # A tibble: 8 x 3
##     age ndrugtx treat
##   &lt;dbl&gt;   &lt;dbl&gt; &lt;chr&gt;
## 1    27       1 long 
## 2    27       1 short
## 3    27       6 long 
## 4    27       6 short
## 5    37       1 long 
## 6    37       1 short
## 7    37       6 long 
## 8    37       6 short</code></pre>
<p><span class="math inline">\(\blacksquare\)</span></p>
<ol start="13" style="list-style-type: lower-alpha">
<li>Which of your combinations of values is predicted to take
the longest to return to drug use? Which is predicted to take the
shortest time? Explain briefly.</li>
</ol>
<p>Solution</p>
<p>Remember that “up and to the right” is the best survival
curve: that is, the people on this survival curve are predicted
to take the longest to return to drug use. On my plot, this is
the pale blue survival curve, stratum 5. Going back to my
combinations data frame, this is 37-year-olds with only one
previous drug treatment and the longer drug treatment this time.</p>
<p>The worst is my green survival curve, stratum 4, which is
the exact opposite of this: 27-year-olds, 6 previous drug
treatments, shorter treatment this time.</p>
<p>“Returning to drug use” is like “death” in that you want it
to be a long time before it happens, so “best” is top right on
the plot of survival curves. In other curcumstances, you might
want the event to happen <em>sooner</em>, in which case the
lower-left survival curve would be the “best” one.</p>
<p><span class="math inline">\(\blacksquare\)</span></p>
<ol start="14" style="list-style-type: lower-alpha">
<li>Are your survival curve plot and your conclusions from part
(<a href="#part:posneg">here</a>) consistent, or not? Explain briefly.</li>
</ol>
<p>Solution</p>
<p>The survival curves say that being older, having fewer previous
treatments and being on the long treatment are better in terms
of taking longer to return to drug use. Our analysis of whether
the slope coefficients in <code>drugusers.2</code> were positive or
negative came to exactly the same conclusion. So the survival
curves and part (<a href="#part:posneg">here</a>) are entirely consistent.</p>
<p>On my plot with the legend, you can assess the effects of the
individual variables: for example, to assess the effect of age,
find two combos that differ only in age, say strata 1 and 5, the
red and light blue ones. Of these, the light blue survival curve is
higher, so age 37 is better in terms of survival than age
27. This will work whichever such pair you pick: for example,
strata 3 and 7, the olive green and purple curves, compare
the same way.</p>
<p>Extra: more comparisons for you to do: to assess the effect of number of
previous treatments, compare eg. strata 1 and 3, red and olive
green, and to assess the effect of treatment length, compare
eg. strata 5 and 6, light blue and darker blue.</p>
<p>All this struggling to identify colours makes me think of
<a href="https://blog.xkcd.com/2010/05/03/color-survey-results/">link</a>, in
which the guy behind the webcomic XKCD did a survey where he
showed people a whole bunch of different colours and asked the
people to name the colours.</p>
<p><span class="math inline">\(\blacksquare\)</span></p>
</div>
<div id="multiple-myeloma-1" class="section level2" number="29.7">
<h2><span class="header-section-number">29.7</span> Multiple myeloma</h2>
<p>Multiple myeloma is a kind of cancer. It
forms in a plasma cell (which is a type of white blood cell). It
causes cancer cells to accumulate in the bone marrow, where they crowd
out healthy blood cells. Plasma cells make antibodies (to help fight
infections), while the cancer cells don’t: they produce abnormal
proteins that can cause kidney problems. (This adapted from
<a href="http://www.mayoclinic.org/diseases-conditions/multiple-myeloma/basics/definition/con-20026607">link</a>.)
The variables are:</p>
<ul>
<li><p><code>time</code>: survival time from diagnosis (months)</p></li>
<li><p><code>vstatus</code>: 0=alive, 1=dead at end of study</p></li>
<li><p><code>logbun</code>: log of BUN test score (BUN test is a test of
kidney function, not to be confused with cha siu
bao<a href="#fn48" class="footnote-ref" id="fnref48"><sup>48</sup></a>).</p></li>
<li><p><code>hgb</code>: hemoglobin (at diagnosis).</p></li>
<li><p><code>platelet</code>: platelets: 1=normal, 0=abnormal (at
diagnosis).</p></li>
<li><p><code>age</code> at diagnosis, in years</p></li>
<li><p><code>logwbc</code>: log of WBC (white blood cell count, at
diagnosis)</p></li>
<li><p><code>frac</code>: fractures at diagnosis (0=absent, 1=present)</p></li>
<li><p><code>logpbm</code>: log of percent of plasma cells in bone marrow</p></li>
<li><p><code>protein</code>: proteinuria (protein in urine) at
diagnosis. Most people have very little, so a larger than normal
amount indicates illness of some kind.</p></li>
<li><p><code>scalc</code>: serum calcium at diagnosis.</p></li>
</ul>
<p>The data, on 65 patients with multiple myeloma, are in
<a href="http://ritsokiguess.site/datafiles/myeloma.csv">link</a>. Some of the
variables are logs because they could take very large values.</p>
<p>There are a lot of parts here, but each part is supposed to be short.</p>
<ol style="list-style-type: lower-alpha">
<li>Read in the data and display (some of) the values. Confirm that
you have the right number of observations and the right variables.</li>
</ol>
<p>Solution</p>
<p>The usual:</p>
<div class="sourceCode" id="cb339"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb339-1"><a href="survival-analysis.html#cb339-1"></a>my_url &lt;-<span class="st"> &quot;http://ritsokiguess.site/datafiles/myeloma.csv&quot;</span></span>
<span id="cb339-2"><a href="survival-analysis.html#cb339-2"></a>myeloma &lt;-<span class="st"> </span><span class="kw">read_csv</span>(my_url)</span></code></pre></div>
<pre><code>## 
## ── Column specification ────────────────────────────────────────────────────────
## cols(
##   time = col_double(),
##   vstatus = col_double(),
##   logbun = col_double(),
##   hgb = col_double(),
##   platelet = col_double(),
##   age = col_double(),
##   logwbc = col_double(),
##   frac = col_double(),
##   logpbm = col_double(),
##   protein = col_double(),
##   scalc = col_double()
## )</code></pre>
<div class="sourceCode" id="cb341"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb341-1"><a href="survival-analysis.html#cb341-1"></a>myeloma</span></code></pre></div>
<pre><code>## # A tibble: 65 x 11
##     time vstatus logbun   hgb platelet   age logwbc  frac logpbm protein scalc
##    &lt;dbl&gt;   &lt;dbl&gt;  &lt;dbl&gt; &lt;dbl&gt;    &lt;dbl&gt; &lt;dbl&gt;  &lt;dbl&gt; &lt;dbl&gt;  &lt;dbl&gt;   &lt;dbl&gt; &lt;dbl&gt;
##  1  1.25       1   2.22   9.4        1    67   3.66     1   1.95      12    10
##  2  1.25       1   1.94  12          1    38   3.99     1   1.95      20    18
##  3  2          1   1.52   9.8        1    81   3.88     1   2          2    15
##  4  2          1   1.75  11.3        0    75   3.81     1   1.26       0    12
##  5  2          1   1.30   5.1        0    57   3.72     1   2          3     9
##  6  3          1   1.54   6.7        1    46   4.48     0   1.93      12    10
##  7  5          1   2.24  10.1        1    50   4.95     1   1.66       4     9
##  8  5          1   1.68   6.5        1    74   3.73     0   1.73       5     9
##  9  6          1   1.36   9          1    77   3.54     0   1.46       1     8
## 10  6          1   2.11  10.2        0    70   3.54     1   1.36       1     8
## # … with 55 more rows</code></pre>
<p>65 observations, and all the variables listed. If you want to go
further (not necessary here), you can check that the variables
<code>vstatus</code>, <code>platelet</code> and <code>frac</code> that should be
zero and one actually <em>are</em> zero and one, at least for the values
shown (they are), and the ages look like ages (they do).</p>
<p>The tidyverse also offers:</p>
<div class="sourceCode" id="cb343"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb343-1"><a href="survival-analysis.html#cb343-1"></a><span class="kw">glimpse</span>(myeloma)</span></code></pre></div>
<pre><code>## Rows: 65
## Columns: 11
## $ time     &lt;dbl&gt; 1.25, 1.25, 2.00, 2.00, 2.00, 3.00, 5.00, 5.00, 6.00, 6.00, 6…
## $ vstatus  &lt;dbl&gt; 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1…
## $ logbun   &lt;dbl&gt; 2.2175, 1.9395, 1.5185, 1.7482, 1.3010, 1.5441, 2.2355, 1.681…
## $ hgb      &lt;dbl&gt; 9.4, 12.0, 9.8, 11.3, 5.1, 6.7, 10.1, 6.5, 9.0, 10.2, 9.7, 10…
## $ platelet &lt;dbl&gt; 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1…
## $ age      &lt;dbl&gt; 67, 38, 81, 75, 57, 46, 50, 74, 77, 70, 60, 67, 48, 61, 53, 5…
## $ logwbc   &lt;dbl&gt; 3.6628, 3.9868, 3.8751, 3.8062, 3.7243, 4.4757, 4.9542, 3.732…
## $ frac     &lt;dbl&gt; 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1…
## $ logpbm   &lt;dbl&gt; 1.9542, 1.9542, 2.0000, 1.2553, 2.0000, 1.9345, 1.6628, 1.732…
## $ protein  &lt;dbl&gt; 12, 20, 2, 0, 3, 12, 4, 5, 1, 1, 0, 0, 5, 1, 1, 0, 0, 1, 1, 0…
## $ scalc    &lt;dbl&gt; 10, 18, 15, 12, 9, 10, 9, 9, 8, 8, 10, 8, 10, 10, 13, 12, 10,…</code></pre>
<p>which gives a bit more of a picture of the values.<a href="#fn49" class="footnote-ref" id="fnref49"><sup>49</sup></a>
Or if you were
serious about checking, you could do</p>
<div class="sourceCode" id="cb345"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb345-1"><a href="survival-analysis.html#cb345-1"></a><span class="kw">summary</span>(myeloma)</span></code></pre></div>
<pre><code>##       time          vstatus           logbun            hgb      
##  Min.   : 1.25   Min.   :0.0000   Min.   :0.7782   Min.   : 4.9  
##  1st Qu.: 7.00   1st Qu.:0.0000   1st Qu.:1.1461   1st Qu.: 8.8  
##  Median :15.00   Median :1.0000   Median :1.3222   Median :10.2  
##  Mean   :24.01   Mean   :0.7385   Mean   :1.3929   Mean   :10.2  
##  3rd Qu.:35.00   3rd Qu.:1.0000   3rd Qu.:1.5682   3rd Qu.:12.0  
##  Max.   :92.00   Max.   :1.0000   Max.   :2.2355   Max.   :14.6  
##     platelet           age            logwbc           frac       
##  Min.   :0.0000   Min.   :38.00   Min.   :3.362   Min.   :0.0000  
##  1st Qu.:1.0000   1st Qu.:51.00   1st Qu.:3.643   1st Qu.:1.0000  
##  Median :1.0000   Median :60.00   Median :3.732   Median :1.0000  
##  Mean   :0.8615   Mean   :60.15   Mean   :3.769   Mean   :0.7538  
##  3rd Qu.:1.0000   3rd Qu.:67.00   3rd Qu.:3.875   3rd Qu.:1.0000  
##  Max.   :1.0000   Max.   :82.00   Max.   :4.954   Max.   :1.0000  
##      logpbm          protein           scalc      
##  Min.   :0.4771   Min.   : 0.000   Min.   : 7.00  
##  1st Qu.:1.3617   1st Qu.: 0.000   1st Qu.: 9.00  
##  Median :1.6232   Median : 1.000   Median :10.00  
##  Mean   :1.5497   Mean   : 3.615   Mean   :10.12  
##  3rd Qu.:1.8451   3rd Qu.: 4.000   3rd Qu.:10.00  
##  Max.   :2.0000   Max.   :27.000   Max.   :18.00</code></pre>
<p>which gives means and five-number summaries for each of the variables
(the numeric ones, but they all are here, even the ones coded as 0 or
1 that are really categorical).</p>
<p><span class="math inline">\(\blacksquare\)</span></p>
<ol start="2" style="list-style-type: lower-alpha">
<li>Create a suitable response variable for a Cox
proportional-hazards survival model, bearing in mind that the
“event” here is death. Display your response variable, and explain
briefly what the <code>+</code> signs attached to some of the values
mean, without using a technical term.</li>
</ol>
<p>Solution</p>
<p>I seem to call my response variables <code>y</code>, but you can call
yours whatever you like. Two things: the survival times, here
<code>time</code>, and the indicator of the event, here
<code>vstatus</code> being 1:</p>
<div class="sourceCode" id="cb347"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb347-1"><a href="survival-analysis.html#cb347-1"></a>y &lt;-<span class="st"> </span><span class="kw">with</span>(myeloma, <span class="kw">Surv</span>(time, vstatus <span class="op">==</span><span class="st"> </span><span class="dv">1</span>))</span>
<span id="cb347-2"><a href="survival-analysis.html#cb347-2"></a>y</span></code></pre></div>
<pre><code>##  [1]  1.25   1.25   2.00   2.00   2.00   3.00   5.00   5.00   6.00   6.00 
## [11]  6.00   6.00   7.00   7.00   7.00   9.00  11.00  11.00  11.00  11.00 
## [21] 11.00  13.00  14.00  15.00  16.00  16.00  17.00  17.00  18.00  19.00 
## [31] 19.00  24.00  25.00  26.00  32.00  35.00  37.00  41.00  41.00  51.00 
## [41] 52.00  54.00  58.00  66.00  67.00  88.00  89.00  92.00   4.00+  4.00+
## [51]  7.00+  7.00+  8.00+ 12.00+ 11.00+ 12.00+ 13.00+ 16.00+ 19.00+ 19.00+
## [61] 28.00+ 41.00+ 53.00+ 57.00+ 77.00+</code></pre>
<p>Or use
<code>myeloma$</code> (twice) before the variable names.</p>
<p>The values of <code>y</code> that have a <code>+</code> by them go with
patients who were never observed to die (or were still alive at the
end of the study). There were 17 of these, listed at the end of the
data frame. Usually, these values of the response will be higher than
the others, but they weren’t here. (Maybe some of these patients were
withdrawn from the study, or they joined it late.)</p>
<p><span class="math inline">\(\blacksquare\)</span></p>
<ol start="3" style="list-style-type: lower-alpha">
<li>What is the technical term for those patients that have a
<code>+</code> by their values for the response variable?</li>
</ol>
<p>Solution</p>
<p>Censored. A quick one.
I was trying to dissuade you from using the word “censored” in
the previous part, since I wanted you to demonstrate that you
understood what it <em>meant</em>. But you should know the technical
term as well, which is why I asked you for it here.
Grading note: if this part and the previous one contain,
somewhere, the word “censored” <em>and</em> a clear explanation of
what “censored” means, then I don’t mind what is where.</p>
<p><span class="math inline">\(\blacksquare\)</span></p>
<ol start="4" style="list-style-type: lower-alpha">
<li>Fit a Cox proportional-hazards survival model predicting
your response variable from all the other variables (except for the
ones that you used to make the response variable). Display the
<code>summary</code> of your model.</li>
</ol>
<p>Solution</p>
<p>The obvious way to do this is to list all the other variables on
the right side of the squiggle, but a faster way is this:</p>
<div class="sourceCode" id="cb349"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb349-1"><a href="survival-analysis.html#cb349-1"></a>y<span class="fl">.1</span> &lt;-<span class="st"> </span><span class="kw">coxph</span>(y <span class="op">~</span><span class="st"> </span>. <span class="op">-</span><span class="st"> </span>time <span class="op">-</span><span class="st"> </span>vstatus, <span class="dt">data =</span> myeloma)</span>
<span id="cb349-2"><a href="survival-analysis.html#cb349-2"></a><span class="kw">summary</span>(y<span class="fl">.1</span>)</span></code></pre></div>
<pre><code>## Call:
## coxph(formula = y ~ . - time - vstatus, data = myeloma)
## 
##   n= 65, number of events= 48 
## 
##              coef exp(coef) se(coef)      z Pr(&gt;|z|)   
## logbun    1.85557   6.39536  0.65628  2.827  0.00469 **
## hgb      -0.12629   0.88136  0.07212 -1.751  0.07994 . 
## platelet -0.25488   0.77501  0.51194 -0.498  0.61858   
## age      -0.01306   0.98702  0.01957 -0.668  0.50439   
## logwbc    0.35389   1.42460  0.71576  0.494  0.62101   
## frac      0.34232   1.40821  0.40725  0.841  0.40059   
## logpbm    0.38165   1.46470  0.48743  0.783  0.43364   
## protein   0.01302   1.01311  0.02612  0.498  0.61817   
## scalc     0.12976   1.13856  0.10502  1.236  0.21659   
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
##          exp(coef) exp(-coef) lower .95 upper .95
## logbun      6.3954     0.1564    1.7670    23.147
## hgb         0.8814     1.1346    0.7652     1.015
## platelet    0.7750     1.2903    0.2841     2.114
## age         0.9870     1.0131    0.9499     1.026
## logwbc      1.4246     0.7020    0.3503     5.794
## frac        1.4082     0.7101    0.6339     3.128
## logpbm      1.4647     0.6827    0.5634     3.808
## protein     1.0131     0.9871    0.9625     1.066
## scalc       1.1386     0.8783    0.9268     1.399
## 
## Concordance= 0.675  (se = 0.051 )
## Likelihood ratio test= 17.62  on 9 df,   p=0.04
## Wald test            = 17.93  on 9 df,   p=0.04
## Score (logrank) test = 18.97  on 9 df,   p=0.03</code></pre>
<p>The <code>.</code> in this model formula means
“all the columns in the data frame”
(except for the response variable if it was in the data
frame, which here it was not). I used <code>time</code> and
<code>vstatus</code> to make <code>y</code>, so I had to exclude them explicitly.</p>
<p>If you forget to exclude <code>time</code> and <code>vstatus</code>, you are
in danger of having a model that fits perfectly:</p>
<div class="sourceCode" id="cb351"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb351-1"><a href="survival-analysis.html#cb351-1"></a>y<span class="fl">.00</span> &lt;-<span class="st"> </span><span class="kw">coxph</span>(y <span class="op">~</span><span class="st"> </span>., <span class="dt">data =</span> myeloma)</span></code></pre></div>
<pre><code>## Warning in coxph.fit(X, Y, istrat, offset, init, control, weights = weights, :
## Ran out of iterations and did not converge</code></pre>
<div class="sourceCode" id="cb353"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb353-1"><a href="survival-analysis.html#cb353-1"></a><span class="kw">summary</span>(y<span class="fl">.00</span>)</span></code></pre></div>
<pre><code>## Call:
## coxph(formula = y ~ ., data = myeloma)
## 
##   n= 65, number of events= 48 
## 
##                coef  exp(coef)   se(coef)       z Pr(&gt;|z|)    
## time     -1.109e+01  1.526e-05  9.799e-01 -11.318   &lt;2e-16 ***
## vstatus   1.543e+01  5.031e+06  6.233e+02   0.025     0.98    
## logbun    1.759e-04  1.000e+00  7.904e-01   0.000     1.00    
## hgb       6.861e-06  1.000e+00  9.143e-02   0.000     1.00    
## platelet  9.226e-05  1.000e+00  6.221e-01   0.000     1.00    
## age      -4.311e-06  1.000e+00  2.245e-02   0.000     1.00    
## logwbc   -1.220e-06  1.000e+00  8.940e-01   0.000     1.00    
## frac     -6.694e-05  9.999e-01  6.262e-01   0.000     1.00    
## logpbm    2.400e-04  1.000e+00  7.307e-01   0.000     1.00    
## protein   3.472e-05  1.000e+00  6.776e-02   0.001     1.00    
## scalc    -1.447e-05  1.000e+00  1.091e-01   0.000     1.00    
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
##          exp(coef) exp(-coef) lower .95 upper .95
## time     1.526e-05  6.554e+04 2.236e-06 0.0001041
## vstatus  5.031e+06  1.988e-07 0.000e+00       Inf
## logbun   1.000e+00  9.998e-01 2.124e-01 4.7087742
## hgb      1.000e+00  1.000e+00 8.359e-01 1.1962633
## platelet 1.000e+00  9.999e-01 2.955e-01 3.3849492
## age      1.000e+00  1.000e+00 9.569e-01 1.0449881
## logwbc   1.000e+00  1.000e+00 1.734e-01 5.7673011
## frac     9.999e-01  1.000e+00 2.930e-01 3.4119518
## logpbm   1.000e+00  9.998e-01 2.389e-01 4.1885763
## protein  1.000e+00  1.000e+00 8.757e-01 1.1420792
## scalc    1.000e+00  1.000e+00 8.075e-01 1.2384242
## 
## Concordance= 1  (se = 0 )
## Likelihood ratio test= 277  on 11 df,   p=&lt;2e-16
## Wald test            = 128.1  on 11 df,   p=&lt;2e-16
## Score (logrank) test = 87.4  on 11 df,   p=5e-14</code></pre>
<p>The warning at the top is your clue that something has gone
wrong. This kind of warning <em>can</em> happen with real data, but not
often: it is usually an indication that something is wrong with the
way you specified the model. If you look at the output, you’ll realize
that predicting survival time from survival time makes no sense at all.</p>
<p>There is of course nothing wrong with typing out all the variable
names, except that the first time you type them out, you will likely
make a typo (unless you are more careful than I usually am).</p>
<p><span class="math inline">\(\blacksquare\)</span></p>
<ol start="5" style="list-style-type: lower-alpha">
<li>In your model, which explanatory variables have a P-value less than
0.10? Fit a model containing only those and display the results.</li>
</ol>
<p>Solution</p>
<p>Only <code>logbun</code> and <code>hgb</code>; the other P-values are
larger, usually much larger.
Because there are so many variables to remove, I am frightened
away from <code>update</code> here (which I would normally try to use
in this situation). I’m going to copy-and-paste my code for
<code>y.1</code> and edit it:</p>
<div class="sourceCode" id="cb355"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb355-1"><a href="survival-analysis.html#cb355-1"></a>y<span class="fl">.2</span> &lt;-<span class="st"> </span><span class="kw">coxph</span>(y <span class="op">~</span><span class="st"> </span>logbun <span class="op">+</span><span class="st"> </span>hgb, <span class="dt">data =</span> myeloma)</span>
<span id="cb355-2"><a href="survival-analysis.html#cb355-2"></a><span class="kw">summary</span>(y<span class="fl">.2</span>)</span></code></pre></div>
<pre><code>## Call:
## coxph(formula = y ~ logbun + hgb, data = myeloma)
## 
##   n= 65, number of events= 48 
## 
##            coef exp(coef) se(coef)      z Pr(&gt;|z|)   
## logbun  1.71597   5.56209  0.61855  2.774  0.00553 **
## hgb    -0.11966   0.88722  0.05742 -2.084  0.03717 * 
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
##        exp(coef) exp(-coef) lower .95 upper .95
## logbun    5.5621     0.1798    1.6547   18.6961
## hgb       0.8872     1.1271    0.7928    0.9929
## 
## Concordance= 0.675  (se = 0.043 )
## Likelihood ratio test= 12.27  on 2 df,   p=0.002
## Wald test            = 12.51  on 2 df,   p=0.002
## Score (logrank) test = 13.07  on 2 df,   p=0.001</code></pre>
<p>That’s all I wanted, but you can note that <code>hgb</code> has become
significant at <span class="math inline">\(\alpha=0.05\)</span>. I suspect it was somewhat correlated
with a variable that we removed, so that its value to the regression
has become clearer.</p>
<p><span class="math inline">\(\blacksquare\)</span></p>
<ol start="6" style="list-style-type: lower-alpha">
<li>Do a test to compare the two models that you fit. Why do
you prefer the second model? Explain briefly.</li>
</ol>
<p>Solution</p>
<p>Comparing two models is <code>anova</code>, which also works here. The
right <code>test</code> is <code>Chisq</code>:</p>
<div class="sourceCode" id="cb357"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb357-1"><a href="survival-analysis.html#cb357-1"></a><span class="kw">anova</span>(y<span class="fl">.2</span>, y<span class="fl">.1</span>, <span class="dt">test =</span> <span class="st">&quot;Chisq&quot;</span>)</span></code></pre></div>
<pre><code>## Analysis of Deviance Table
##  Cox model: response is  y
##  Model 1: ~ logbun + hgb
##  Model 2: ~ (time + vstatus + logbun + hgb + platelet + age + logwbc + frac + logpbm + protein + scalc) - time - vstatus
##    loglik Chisq Df P(&gt;|Chi|)
## 1 -148.06                   
## 2 -145.39 5.347  7    0.6177</code></pre>
<p>The usual logic here: this is far from significant, so the null
hypothesis (that the two models are equally good) is not rejected, so
we prefer the smaller model <code>y.2</code> because it is simpler.</p>
<p>I wasn’t sure about the <code>Model 2</code> line of my <code>anova</code>
output (what are <code>time</code> and <code>vstatus</code> doing there?), but
the test has 7 degrees of freedom, which is correct since we started with 9
explanatory variables and finished with 2, so that we took out 7 of
them. I checked what went off the right side of the page: there is a
<code>-time-vstatus</code> on the end, so that it is correct. What
happened is that the <code>.</code> got expanded out into all the
variables separated by <code>+</code>, and then whatever else (the
“minus” variables) were on the end.</p>
<p>In case you are curious, <code>step</code> also works on models like these:</p>
<div class="sourceCode" id="cb359"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb359-1"><a href="survival-analysis.html#cb359-1"></a>y<span class="fl">.3</span> &lt;-<span class="st"> </span><span class="kw">step</span>(y<span class="fl">.1</span>, <span class="dt">direction =</span> <span class="st">&quot;backward&quot;</span>, <span class="dt">trace =</span> <span class="dv">0</span>)</span>
<span id="cb359-2"><a href="survival-analysis.html#cb359-2"></a><span class="kw">summary</span>(y<span class="fl">.3</span>)</span></code></pre></div>
<pre><code>## Call:
## coxph(formula = y ~ logbun + hgb, data = myeloma)
## 
##   n= 65, number of events= 48 
## 
##            coef exp(coef) se(coef)      z Pr(&gt;|z|)   
## logbun  1.71597   5.56209  0.61855  2.774  0.00553 **
## hgb    -0.11966   0.88722  0.05742 -2.084  0.03717 * 
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
##        exp(coef) exp(-coef) lower .95 upper .95
## logbun    5.5621     0.1798    1.6547   18.6961
## hgb       0.8872     1.1271    0.7928    0.9929
## 
## Concordance= 0.675  (se = 0.043 )
## Likelihood ratio test= 12.27  on 2 df,   p=0.002
## Wald test            = 12.51  on 2 df,   p=0.002
## Score (logrank) test = 13.07  on 2 df,   p=0.001</code></pre>
<p>The same model as the one we found by brute force. You can change the
value of <code>trace</code> to see the progress, but in this case it’s not
very illuminating, since <code>&lt;none&gt;</code> and the variables we end up
keeping are always at the bottom of the list to remove.</p>
<p><code>step</code> is built on <code>add1</code> and <code>drop1</code>. In this
case, <code>drop1</code> is run repeatedly and the variable with lowest
AIC is removed. We had all numeric variables in this one, but if our
model had something categorical like <code>treatment</code> with, let’s
say, 4 levels, <code>drop1</code> would contemplate dropping all four of
these in one shot, the same way it works with a categorical variable
in a regression of any other kind.</p>
<p><span class="math inline">\(\blacksquare\)</span></p>
<ol start="7" style="list-style-type: lower-alpha">
<li>There should be two explanatory variables left in your
model. These are both numerical variables. Find their first and
third quartiles, any way you like.</li>
</ol>
<p>Solution</p>
<p>The obvious way is probably this:</p>
<div class="sourceCode" id="cb361"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb361-1"><a href="survival-analysis.html#cb361-1"></a><span class="kw">quantile</span>(myeloma<span class="op">$</span>logbun)</span></code></pre></div>
<pre><code>##     0%    25%    50%    75%   100% 
## 0.7782 1.1461 1.3222 1.5682 2.2355</code></pre>
<div class="sourceCode" id="cb363"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb363-1"><a href="survival-analysis.html#cb363-1"></a><span class="kw">quantile</span>(myeloma<span class="op">$</span>hgb)</span></code></pre></div>
<pre><code>##   0%  25%  50%  75% 100% 
##  4.9  8.8 10.2 12.0 14.6</code></pre>
<p>So the quartiles are 1.15 and 1.57 for <code>logbun</code>, and 8.8 and
12.0 for <code>hgb</code>.</p>
<p>There are (at least) three other ways to do it. This is the easiest:</p>
<div class="sourceCode" id="cb365"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb365-1"><a href="survival-analysis.html#cb365-1"></a><span class="kw">summary</span>(myeloma)</span></code></pre></div>
<pre><code>##       time          vstatus           logbun            hgb      
##  Min.   : 1.25   Min.   :0.0000   Min.   :0.7782   Min.   : 4.9  
##  1st Qu.: 7.00   1st Qu.:0.0000   1st Qu.:1.1461   1st Qu.: 8.8  
##  Median :15.00   Median :1.0000   Median :1.3222   Median :10.2  
##  Mean   :24.01   Mean   :0.7385   Mean   :1.3929   Mean   :10.2  
##  3rd Qu.:35.00   3rd Qu.:1.0000   3rd Qu.:1.5682   3rd Qu.:12.0  
##  Max.   :92.00   Max.   :1.0000   Max.   :2.2355   Max.   :14.6  
##     platelet           age            logwbc           frac       
##  Min.   :0.0000   Min.   :38.00   Min.   :3.362   Min.   :0.0000  
##  1st Qu.:1.0000   1st Qu.:51.00   1st Qu.:3.643   1st Qu.:1.0000  
##  Median :1.0000   Median :60.00   Median :3.732   Median :1.0000  
##  Mean   :0.8615   Mean   :60.15   Mean   :3.769   Mean   :0.7538  
##  3rd Qu.:1.0000   3rd Qu.:67.00   3rd Qu.:3.875   3rd Qu.:1.0000  
##  Max.   :1.0000   Max.   :82.00   Max.   :4.954   Max.   :1.0000  
##      logpbm          protein           scalc      
##  Min.   :0.4771   Min.   : 0.000   Min.   : 7.00  
##  1st Qu.:1.3617   1st Qu.: 0.000   1st Qu.: 9.00  
##  Median :1.6232   Median : 1.000   Median :10.00  
##  Mean   :1.5497   Mean   : 3.615   Mean   :10.12  
##  3rd Qu.:1.8451   3rd Qu.: 4.000   3rd Qu.:10.00  
##  Max.   :2.0000   Max.   :27.000   Max.   :18.00</code></pre>
<p>from which you pick out the ones you need. Or, you <code>select</code> the
ones you need first:</p>
<div class="sourceCode" id="cb367"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb367-1"><a href="survival-analysis.html#cb367-1"></a>myeloma <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">select</span>(logbun, hgb) <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">summary</span>()</span></code></pre></div>
<pre><code>##      logbun            hgb      
##  Min.   :0.7782   Min.   : 4.9  
##  1st Qu.:1.1461   1st Qu.: 8.8  
##  Median :1.3222   Median :10.2  
##  Mean   :1.3929   Mean   :10.2  
##  3rd Qu.:1.5682   3rd Qu.:12.0  
##  Max.   :2.2355   Max.   :14.6</code></pre>
<p>The obvious <code>tidyverse</code> way is actually a bit
inelegant, because you have to calculate two things for two variables:<a href="#fn50" class="footnote-ref" id="fnref50"><sup>50</sup></a></p>
<div class="sourceCode" id="cb369"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb369-1"><a href="survival-analysis.html#cb369-1"></a>myeloma <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">summarize</span>(</span>
<span id="cb369-2"><a href="survival-analysis.html#cb369-2"></a>  <span class="dt">logbun.q1 =</span> <span class="kw">quantile</span>(logbun, <span class="fl">0.25</span>),</span>
<span id="cb369-3"><a href="survival-analysis.html#cb369-3"></a>  <span class="dt">logbun.q3 =</span> <span class="kw">quantile</span>(logbun, <span class="fl">0.75</span>),</span>
<span id="cb369-4"><a href="survival-analysis.html#cb369-4"></a>  <span class="dt">hgb.q1 =</span> <span class="kw">quantile</span>(hgb, <span class="fl">0.25</span>),</span>
<span id="cb369-5"><a href="survival-analysis.html#cb369-5"></a>  <span class="dt">hgb.q3 =</span> <span class="kw">quantile</span>(hgb, <span class="fl">0.75</span>)</span>
<span id="cb369-6"><a href="survival-analysis.html#cb369-6"></a>)</span></code></pre></div>
<pre><code>## # A tibble: 1 x 4
##   logbun.q1 logbun.q3 hgb.q1 hgb.q3
##       &lt;dbl&gt;     &lt;dbl&gt;  &lt;dbl&gt;  &lt;dbl&gt;
## 1      1.15      1.57    8.8     12</code></pre>
<p>Next is the tidyverse-approved way to get both quartiles for both variables at once. Use <code>across</code> to select the variables to use, and then something with a squiggle and a dot to say “do this on each of the columns selected in the <code>across</code>”. If you have a cleverer way to select those two columns without naming them, go for it. Read this in English as “for each of the columns <code>logbun</code> and <code>hgb</code>, work out the first and third quantiles of it”, where the dot is read as “it”:</p>
<div class="sourceCode" id="cb371"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb371-1"><a href="survival-analysis.html#cb371-1"></a>myeloma <span class="op">%&gt;%</span><span class="st"> </span></span>
<span id="cb371-2"><a href="survival-analysis.html#cb371-2"></a><span class="st">  </span><span class="kw">summarize</span>(<span class="kw">across</span>(<span class="kw">c</span>(logbun, hgb), </span>
<span id="cb371-3"><a href="survival-analysis.html#cb371-3"></a>                   <span class="op">~</span><span class="kw">quantile</span>(., <span class="kw">c</span>(<span class="fl">0.25</span>, <span class="fl">0.75</span>))))</span></code></pre></div>
<pre><code>## # A tibble: 2 x 2
##   logbun   hgb
##    &lt;dbl&gt; &lt;dbl&gt;
## 1   1.15   8.8
## 2   1.57  12</code></pre>
<p>We have lost which quartile is which, but of course the lower one must be Q1 and the higher one Q3 for each variable.<a href="#fn51" class="footnote-ref" id="fnref51"><sup>51</sup></a></p>
<p><span class="math inline">\(\blacksquare\)</span></p>
<ol start="8" style="list-style-type: lower-alpha">
<li>Create a data frame containing all possible combinations
of the two quartiles for each of the two variables, and display the result.</li>
</ol>
<p>Solution</p>
<p>The usual <code>crossing</code>:</p>
<div class="sourceCode" id="cb373"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb373-1"><a href="survival-analysis.html#cb373-1"></a>logbuns &lt;-<span class="st"> </span><span class="kw">c</span>(<span class="fl">1.1461</span>, <span class="fl">1.5682</span>)</span>
<span id="cb373-2"><a href="survival-analysis.html#cb373-2"></a>hgbs &lt;-<span class="st"> </span><span class="kw">c</span>(<span class="fl">8.8</span>, <span class="dv">12</span>)</span>
<span id="cb373-3"><a href="survival-analysis.html#cb373-3"></a>new &lt;-<span class="st"> </span><span class="kw">crossing</span>(<span class="dt">logbun =</span> logbuns, <span class="dt">hgb =</span> hgbs)</span>
<span id="cb373-4"><a href="survival-analysis.html#cb373-4"></a>new</span></code></pre></div>
<pre><code>## # A tibble: 4 x 2
##   logbun   hgb
##    &lt;dbl&gt; &lt;dbl&gt;
## 1   1.15   8.8
## 2   1.15  12  
## 3   1.57   8.8
## 4   1.57  12</code></pre>
<p>Or anything equivalent to that. This is my procedure, but you are free
to shorten it if it will still work. The place you have to get to in
the end is a data frame with columns called <code>logbun</code> and
<code>hgb</code>, and the right four combinations of values. If you want
to round the <code>logbun</code> values off more, for example to two
decimals, that’s fine; it won’t affect the graph that’s coming up.</p>
<p><span class="math inline">\(\blacksquare\)</span></p>
<ol style="list-style-type: lower-roman">
<li>Obtain predicted survival probabilities for each of the
combinations of variables you created above. You don’t need to look
at the results (they are rather long).</li>
</ol>
<p>Solution</p>
<p>This seems as if it ought to be <code>predict</code>, but the
<code>survival</code> version of it is called <code>survfit</code>:</p>
<div class="sourceCode" id="cb375"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb375-1"><a href="survival-analysis.html#cb375-1"></a>s &lt;-<span class="st"> </span><span class="kw">survfit</span>(y<span class="fl">.2</span>, new, <span class="dt">data =</span> myeloma)</span></code></pre></div>
<p>It works the same as <code>predict</code>: a fitted model object (your
smaller survival model), and a data frame of values to predict
for. The <code>data=</code> is not strictly needed here, but if you want
<code>ggsurvplot</code> to work right, you <em>do</em> need it to be here.</p>
<p><span class="math inline">\(\blacksquare\)</span></p>
<ol start="10" style="list-style-type: lower-alpha">
<li>Obtain a graph of the predicted survival curves for each
combination of your variables.</li>
</ol>
<p>Solution</p>
<p>This is easier than you think: it’s just <code>ggsurvplot</code> from <code>survminer</code>:</p>
<div class="sourceCode" id="cb376"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb376-1"><a href="survival-analysis.html#cb376-1"></a><span class="kw">ggsurvplot</span>(s, <span class="dt">conf.int =</span> F)</span></code></pre></div>
<p><img src="pasias_files/figure-html/myeloma-17-1.png" width="672" /></p>
<p><span class="math inline">\(\blacksquare\)</span></p>
<ol start="11" style="list-style-type: lower-alpha">
<li>Is it better to have high or low values for each of the
variables in your prediction? Explain briefly.</li>
</ol>
<p>Solution</p>
<p>Those four “strata” are the four rows in your prediction data
frame (the four combinations). They are in the same order that
they were in <code>new</code> (or whatever name you used):</p>
<div class="sourceCode" id="cb377"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb377-1"><a href="survival-analysis.html#cb377-1"></a>new</span></code></pre></div>
<pre><code>## # A tibble: 4 x 2
##   logbun   hgb
##    &lt;dbl&gt; &lt;dbl&gt;
## 1   1.15   8.8
## 2   1.15  12  
## 3   1.57   8.8
## 4   1.57  12</code></pre>
<p>The best survival curve is the top-right green one. This is
stratum<a href="#fn52" class="footnote-ref" id="fnref52"><sup>52</sup></a>
2, from the legend at the top. In <code>new</code>,
this goes with a low value of <code>logbun</code> and a <em>high</em> value
of <code>hgb</code>.</p>
<p>You can check this by looking at the <em>worst</em> survival curve,
which should be diametrically opposed. This is the blue one, stratum
3, which is <em>high</em> <code>logbun</code> and <em>low</em> <code>hgb</code>,
indeed exactly the opposite of the best one.</p>
<p>Things that are tests, like <code>logbun</code>, are often set up so that
a high value is the abnormal one (so that an abnormal one will be easy
to spot). Things that are measurements, like <code>hgb</code>, might have
an ideal range, but the better value could be high or low, depending
on what is being measured.</p>
<p><span class="math inline">\(\blacksquare\)</span></p>
</div>
<div id="ovarian-cancer-1" class="section level2" number="29.8">
<h2><span class="header-section-number">29.8</span> Ovarian cancer</h2>
<p>R’s <code>survival</code> package contains several data
sets. One of these is called <code>ovarian</code>; it comes from a study
of 26 ovarian cancer patients. The major purpose of this study was to
compare the effects of two treatments on survival time.</p>
<ol style="list-style-type: lower-alpha">
<li>Obtain and display (all of) the data set. This is as simple as
loading the package and typing the data set’s name.</li>
</ol>
<p>Solution</p>
<p>Thus. You may need to start with <code>library(survival)</code>:</p>
<div class="sourceCode" id="cb379"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb379-1"><a href="survival-analysis.html#cb379-1"></a>ovarian</span></code></pre></div>
<pre><code>##    futime fustat     age resid.ds rx ecog.ps
## 1      59      1 72.3315        2  1       1
## 2     115      1 74.4932        2  1       1
## 3     156      1 66.4658        2  1       2
## 4     421      0 53.3644        2  2       1
## 5     431      1 50.3397        2  1       1
## 6     448      0 56.4301        1  1       2
## 7     464      1 56.9370        2  2       2
## 8     475      1 59.8548        2  2       2
## 9     477      0 64.1753        2  1       1
## 10    563      1 55.1781        1  2       2
## 11    638      1 56.7562        1  1       2
## 12    744      0 50.1096        1  2       1
## 13    769      0 59.6301        2  2       2
## 14    770      0 57.0521        2  2       1
## 15    803      0 39.2712        1  1       1
## 16    855      0 43.1233        1  1       2
## 17   1040      0 38.8932        2  1       2
## 18   1106      0 44.6000        1  1       1
## 19   1129      0 53.9068        1  2       1
## 20   1206      0 44.2055        2  2       1
## 21   1227      0 59.5890        1  2       2
## 22    268      1 74.5041        2  1       2
## 23    329      1 43.1370        2  1       1
## 24    353      1 63.2192        1  2       2
## 25    365      1 64.4247        2  2       1
## 26    377      0 58.3096        1  2       1</code></pre>
<p>There are indeed 26 rows. This is a <code>data.frame</code> rather than a
<code>tibble</code>, so you see the whole thing, in case you were
expecting something like this:</p>
<div class="sourceCode" id="cb381"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb381-1"><a href="survival-analysis.html#cb381-1"></a>ovarian <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">as.tibble</span>()</span></code></pre></div>
<pre><code>## Warning: `as.tibble()` was deprecated in tibble 2.0.0.
## Please use `as_tibble()` instead.
## The signature and semantics have changed, see `?as_tibble`.</code></pre>
<pre><code>## # A tibble: 26 x 6
##    futime fustat   age resid.ds    rx ecog.ps
##     &lt;dbl&gt;  &lt;dbl&gt; &lt;dbl&gt;    &lt;dbl&gt; &lt;dbl&gt;   &lt;dbl&gt;
##  1     59      1  72.3        2     1       1
##  2    115      1  74.5        2     1       1
##  3    156      1  66.5        2     1       2
##  4    421      0  53.4        2     2       1
##  5    431      1  50.3        2     1       1
##  6    448      0  56.4        1     1       2
##  7    464      1  56.9        2     2       2
##  8    475      1  59.9        2     2       2
##  9    477      0  64.2        2     1       1
## 10    563      1  55.2        1     2       2
## # … with 16 more rows</code></pre>
<p>which doesn’t change anything in <code>ovarian</code>, but changes what
kind of thing it is (and thus how it displays). Usually when you read
something in from a file, you use something like <code>read_delim</code>
that makes a <code>tibble</code>, but this one wasn’t read in from a
file. It was stored in the package as an old-fashioned
<code>data.frame</code>, and so that’s how it stays.</p>
<p><span class="math inline">\(\blacksquare\)</span></p>
<ol start="2" style="list-style-type: lower-alpha">
<li>The columns of interest to us are:</li>
</ol>
<ul>
<li><p><code>futime</code>: the time for which a patient was followed-up:
the number of days until either they died or the study ended (or
they withdrew from the study for some other reason).</p></li>
<li><p><code>fustat</code>: follow-up status: 1 if the patient died of
ovarian cancer, 0 if they were still alive when the study ended.</p></li>
<li><p><code>age</code>: of patient, at diagnosis, in years</p></li>
<li><p><code>rx</code>: treatment, numbered 1 or 2, but really labels for
the two treatments.</p></li>
</ul>
<p>Create and display a suitable response variable <code>y</code> for a Cox
proportional-hazards model.</p>
<p>Solution</p>
<p>The idea is to use the appropriate one(s) of these columns in
<code>Surv</code>. Remember that the response variable in a survival
model encodes two things: the survival time, and whether or not
the event (here death) actually happened to that patient or not.
I always forget whether the second thing in <code>Surv</code> has to
be 1 or 0 if the event happened. The help says that it needs to be
1 or <code>TRUE</code> if the event (death) happened, which is what
<code>fustat</code> is, so we can use it as it is:</p>
<div class="sourceCode" id="cb384"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb384-1"><a href="survival-analysis.html#cb384-1"></a>y &lt;-<span class="st"> </span><span class="kw">with</span>(ovarian, <span class="kw">Surv</span>(futime, fustat))</span>
<span id="cb384-2"><a href="survival-analysis.html#cb384-2"></a>y</span></code></pre></div>
<pre><code>##  [1]   59   115   156   421+  431   448+  464   475   477+  563   638   744+
## [13]  769+  770+  803+  855+ 1040+ 1106+ 1129+ 1206+ 1227+  268   329   353 
## [25]  365   377+</code></pre>
<p>This creates a separate variable <code>y</code> outside of any data
frame. This is how it has to be done, because although <code>y</code>
looks as if it is 26 long (one per patient), it’s actually more
complicated than that:</p>
<div class="sourceCode" id="cb386"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb386-1"><a href="survival-analysis.html#cb386-1"></a>ov2 &lt;-<span class="st"> </span>ovarian <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">mutate</span>(<span class="dt">y =</span> <span class="kw">Surv</span>(futime, fustat))</span></code></pre></div>
<p>This doesn’t work, because internally <code>y</code> is a <code>matrix</code> with two columns:</p>
<div class="sourceCode" id="cb387"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb387-1"><a href="survival-analysis.html#cb387-1"></a><span class="kw">print.default</span>(y)</span></code></pre></div>
<pre><code>##       time status
##  [1,]   59      1
##  [2,]  115      1
##  [3,]  156      1
##  [4,]  421      0
##  [5,]  431      1
##  [6,]  448      0
##  [7,]  464      1
##  [8,]  475      1
##  [9,]  477      0
## [10,]  563      1
## [11,]  638      1
## [12,]  744      0
## [13,]  769      0
## [14,]  770      0
## [15,]  803      0
## [16,]  855      0
## [17,] 1040      0
## [18,] 1106      0
## [19,] 1129      0
## [20,] 1206      0
## [21,] 1227      0
## [22,]  268      1
## [23,]  329      1
## [24,]  353      1
## [25,]  365      1
## [26,]  377      0
## attr(,&quot;type&quot;)
## [1] &quot;right&quot;
## attr(,&quot;class&quot;)
## [1] &quot;Surv&quot;</code></pre>
<p>The <code>attr(,"class")</code> thing at the bottom of this says that <code>y</code> is actually a <code>Surv</code> object, which is how it knows to display as it does, as 26 values some of which have plusses.<a href="#fn53" class="footnote-ref" id="fnref53"><sup>53</sup></a></p>
<p>The way R works out the length of something is its total number of
entries, which for this matrix is <span class="math inline">\(26 \times 2=52\)</span>. The only things
you can add via <code>mutate</code> to a data frame with 26 rows have
length 26 (since everything in a data frame has to be the same length)
or length 1 (in which case it is repeated 26 times).</p>
<p>With some cajoling, you can get this into a data frame, but with more
cajoling than seems necessary. It’s much easier to leave it as a
separate thing outside a data frame.<a href="#fn54" class="footnote-ref" id="fnref54"><sup>54</sup></a></p>
<p>I gave <code>ov2</code> a “temporary” name because I am not going to use
it again.</p>
<p><span class="math inline">\(\blacksquare\)</span></p>
<ol start="3" style="list-style-type: lower-alpha">
<li>In the display of your response variable, some values are
marked with a <code>+</code>. Why is that? Explain briefly. (If you use
a technical term, you should explain what it means.)</li>
</ol>
<p>Solution</p>
<p>These are the censored observations. You can say this, but you
also need to say what that means (this is the “technical term”
referred to in the question). The observations with a <code>+</code>
are individuals who were never observed to die, or who were still
alive at the end of the study.</p>
<p>I want you to demonstrate that you know what censored
<em>means</em>, not just that you know when you have a censored
observation.</p>
<p>Extra: in a study like this, patients are typically “recruited”
into the study at various different times. Patients who happened
to be in the study near the beginning and who survived can have a
large (censored) value of <code>y</code> (like those values over 1000
days). But a patient might join the study later on; if they
survive, they might produce a censored observation with a small
survival time, like the last value 377. I’m sure the doctor would
have liked to follow them for longer, but the funding ran out, and
the doctor had a paper to write. (There is <em>some</em> information
in these small censored values, but not much, because most of the
patients, even the ones who eventually died, survived for longer
than 377 days.)</p>
<p>The other thing that might have happened is that a patient with
the 377-censored value died <em>from something else</em> unrelated
to ovarian cancer. The study is only concerned with deaths from
ovarian cancer, so such a patient is treated as censored at their
death time. After this point we cannot assess how long
this patient survived <em>ovarian cancer</em>.</p>
<p><span class="math inline">\(\blacksquare\)</span></p>
<ol start="4" style="list-style-type: lower-alpha">
<li>Fit a Cox proportional-hazards model for predicting
survival time from age and treatment. Note that the numeric values
for treatment make sense only as labels for the two treatments, so
in your model formula make treatment into a factor. Display the
results.</li>
</ol>
<p>Solution</p>
<p>The hint suggests something like this:</p>
<div class="sourceCode" id="cb389"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb389-1"><a href="survival-analysis.html#cb389-1"></a>time<span class="fl">.1</span> &lt;-<span class="st"> </span><span class="kw">coxph</span>(y <span class="op">~</span><span class="st"> </span>age <span class="op">+</span><span class="st"> </span><span class="kw">factor</span>(rx), <span class="dt">data =</span> ovarian)</span>
<span id="cb389-2"><a href="survival-analysis.html#cb389-2"></a><span class="kw">summary</span>(time<span class="fl">.1</span>)</span></code></pre></div>
<pre><code>## Call:
## coxph(formula = y ~ age + factor(rx), data = ovarian)
## 
##   n= 26, number of events= 12 
## 
##                 coef exp(coef) se(coef)      z Pr(&gt;|z|)   
## age          0.14733   1.15873  0.04615  3.193  0.00141 **
## factor(rx)2 -0.80397   0.44755  0.63205 -1.272  0.20337   
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
##             exp(coef) exp(-coef) lower .95 upper .95
## age            1.1587      0.863    1.0585     1.268
## factor(rx)2    0.4475      2.234    0.1297     1.545
## 
## Concordance= 0.798  (se = 0.076 )
## Likelihood ratio test= 15.89  on 2 df,   p=4e-04
## Wald test            = 13.47  on 2 df,   p=0.001
## Score (logrank) test = 18.56  on 2 df,   p=9e-05</code></pre>
<p>Alternatively, define the factor version of <code>rx</code> in the data
frame first. This is the slick way to do that:</p>
<div class="sourceCode" id="cb391"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb391-1"><a href="survival-analysis.html#cb391-1"></a>time<span class="fl">.1</span>a &lt;-<span class="st"> </span>ovarian <span class="op">%&gt;%</span></span>
<span id="cb391-2"><a href="survival-analysis.html#cb391-2"></a><span class="st">  </span><span class="kw">mutate</span>(<span class="dt">rxf =</span> <span class="kw">factor</span>(rx)) <span class="op">%&gt;%</span></span>
<span id="cb391-3"><a href="survival-analysis.html#cb391-3"></a><span class="st">  </span><span class="kw">coxph</span>(y <span class="op">~</span><span class="st"> </span>age <span class="op">+</span><span class="st"> </span>rxf, <span class="dt">data =</span> .)</span>
<span id="cb391-4"><a href="survival-analysis.html#cb391-4"></a><span class="kw">summary</span>(time<span class="fl">.1</span>a)</span></code></pre></div>
<pre><code>## Call:
## coxph(formula = y ~ age + rxf, data = .)
## 
##   n= 26, number of events= 12 
## 
##          coef exp(coef) se(coef)      z Pr(&gt;|z|)   
## age   0.14733   1.15873  0.04615  3.193  0.00141 **
## rxf2 -0.80397   0.44755  0.63205 -1.272  0.20337   
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
##      exp(coef) exp(-coef) lower .95 upper .95
## age     1.1587      0.863    1.0585     1.268
## rxf2    0.4475      2.234    0.1297     1.545
## 
## Concordance= 0.798  (se = 0.076 )
## Likelihood ratio test= 15.89  on 2 df,   p=4e-04
## Wald test            = 13.47  on 2 df,   p=0.001
## Score (logrank) test = 18.56  on 2 df,   p=9e-05</code></pre>
<p>The answer is the same either way.
The <code>data=.</code> means “use the data frame that came out of the previous step, the one with <code>rxf</code> in it.”</p>
<p><span class="math inline">\(\blacksquare\)</span></p>
<ol start="5" style="list-style-type: lower-alpha">
<li>Is there a significant difference between the treatments in
terms of their effects on survival (from ovarian cancer)?</li>
</ol>
<p>Solution</p>
<p>Look at the P-value for my <code>factor(rx)2</code>, 0.203. This is
not small, so there is no evidence of a difference between
treatments.</p>
<p>Extra: the reason for the odd label is that we have turned
treatment into a categorical variable; treatment 1 is used as the
baseline, and the negative slope says that the “hazard of death”
is lower for treatment 2 than for treatment 1: that is, people
survive longer on treatment 2, but the difference is not big
enough to be significant (we also have a smallish sample size).</p>
<p>Since there are only two treatments, it would in fact have been OK
to leave them as numbers (with two numbers one unit apart, the
slope would have been the same size as here), but I think it’s a
good idea to treat categorical variables as categorical. My own habit
is to use letters or something non-numerical to distinguish
categories. I might have used <code>t1</code> and <code>t2</code> in this
case, or the names of the different treatments.</p>
<p><span class="math inline">\(\blacksquare\)</span></p>
<ol start="6" style="list-style-type: lower-alpha">
<li>Is there a significant effect of age? If there is, describe
the effect that age has on survival.</li>
</ol>
<p>Solution</p>
<p>The P-value for age is 0.0014, small, so age definitely has a
significant effect on survival. As to what kind of effect, look at
the slope coefficient, 0.15, positive, which means that increased
age-at-diagnosis goes with an <em>increased</em> hazard of death, or
that older patients do not survive as long.</p>
<p>I would like you to get to the plain-English words at the
end. Part of your job as a statistician is explaining what you got
to people who are doctors, managers, etc., who won’t
understand the terminology.</p>
<p>Thus, one mark for assessing significance
via P-value, one for looking at the slope coefficient and noting
that it is positive, and one for getting to “older patients do not survive as long”, or
“older patients have a larger chance of dying sooner”.
(Strictly, this is also “all else equal” as usual,
since survival time might also have depended on treatment, but the
point of this question is for you to get to “older patients do not survive as long”.)</p>
<p>(The interpretation of the slope may seem backwards: a positive
slope means a <em>shorter</em> survival time for a larger age. This
is why I talk about “hazard of death”, since that guides us to
the correct interpretation.)</p>
<p>Extra: I was curious about what would happen if I just included
<code>rx</code> in the model:</p>
<div class="sourceCode" id="cb393"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb393-1"><a href="survival-analysis.html#cb393-1"></a>time<span class="fl">.2</span> &lt;-<span class="st"> </span><span class="kw">update</span>(time<span class="fl">.1</span>, . <span class="op">~</span><span class="st"> </span>. <span class="op">-</span><span class="st"> </span>age)</span>
<span id="cb393-2"><a href="survival-analysis.html#cb393-2"></a><span class="kw">summary</span>(time<span class="fl">.2</span>)</span></code></pre></div>
<pre><code>## Call:
## coxph(formula = y ~ factor(rx), data = ovarian)
## 
##   n= 26, number of events= 12 
## 
##                coef exp(coef) se(coef)      z Pr(&gt;|z|)
## factor(rx)2 -0.5964    0.5508   0.5870 -1.016     0.31
## 
##             exp(coef) exp(-coef) lower .95 upper .95
## factor(rx)2    0.5508      1.816    0.1743      1.74
## 
## Concordance= 0.608  (se = 0.07 )
## Likelihood ratio test= 1.05  on 1 df,   p=0.3
## Wald test            = 1.03  on 1 df,   p=0.3
## Score (logrank) test = 1.06  on 1 df,   p=0.3</code></pre>
<p>Still not significant, but this model is a <em>lot worse</em> because I
took out the significant <code>age</code>. What this is doing is mixing up
all the people of different ages (and we know that age has an effect
on survival) and trying (and failing) to discern an effect of
treatment.</p>
<p>We could have been badly misled by this model if one of the treatments
had predominantly older patients. We know that older patients have
worse survival, so the treatment with older patients would have looked
worse, even if it actually wasn’t. The model <code>time.1</code> which
contained <code>age</code> properly adjusted for the effect of age, so
that was the best way to see whether there was a difference between
treatments.</p>
<p>What you often see early on in a paper on this kind of stuff is a
graph showing that the treatment groups are similar in terms of
important things like <code>age</code>. Here, that could be a boxplot:</p>
<div class="sourceCode" id="cb395"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb395-1"><a href="survival-analysis.html#cb395-1"></a><span class="kw">ggplot</span>(ovarian, <span class="kw">aes</span>(<span class="dt">x =</span> <span class="kw">factor</span>(rx), <span class="dt">y =</span> age)) <span class="op">+</span><span class="st"> </span><span class="kw">geom_boxplot</span>()</span></code></pre></div>
<p><img src="pasias_files/figure-html/ovarian-9-1.png" width="672" /></p>
<p>I needed to do <code>factor(rx)</code> because <code>geom_boxplot</code>
needs a genuine categorical variable, not just a numerical variable
masquerading as one. If you just leave it as <code>rx</code>, as I
discovered, you get <em>one</em> boxplot of all the ages together
regardless of treatment. The key, for you as user of software, is not
(necessarily) to get it right the first time, but to know what to do
to fix up the errors you will inevitably get. If you have worked
through the boxplot examples in C32 and D29, you will have enough
experience to remember that a boxplot has to have a categorical <code>x</code>
(text will do, but definitely not numbers). This is why I give you so
many things to work through: so that you gain the experience to know
how to fix up problems.</p>
<p>Treatment 1 has a larger spread of ages and treatment 2 has a low
outlier age, but the median ages are very similar.</p>
<p><span class="math inline">\(\blacksquare\)</span></p>
<ol start="7" style="list-style-type: lower-alpha">
<li>Make a martingale residual plot for this model. Do you see
any problems? Explain briefly.</li>
</ol>
<p>Solution</p>
<p>The plot is just the same idea as the one in the notes. Make sure
you have <code>survminer</code> installed and loaded:</p>
<div class="sourceCode" id="cb396"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb396-1"><a href="survival-analysis.html#cb396-1"></a><span class="kw">ggcoxdiagnostics</span>(time<span class="fl">.1</span>) <span class="op">+</span><span class="st"> </span><span class="kw">geom_smooth</span>()</span></code></pre></div>
<pre><code>## `geom_smooth()` using formula &#39;y ~ x&#39;</code></pre>
<pre><code>## `geom_smooth()` using method = &#39;loess&#39; and formula &#39;y ~ x&#39;</code></pre>
<p><img src="pasias_files/figure-html/ovarian-10-1.png" width="672" /></p>
<p>Make a call about whether you think the smooth trend deviates too much
from the red dotted line going across at zero. Martingale residuals
can get very negative (and that is OK), so that residual of <span class="math inline">\(-2\)</span> is
not a problem, and this is pulling the smooth trend down a bit (it’s
the reason for the dip on the right side of the smooth trend). So I’d
call this OK, but you can make whatever call you like as long as it’s
supported by what you see here.</p>
<p>I observe that the obvious fixable thing is where you have a curve
here, one that looks like a parabola (at which point you add squared
terms to your explanatory variables and see if that helps, as for
<code>bmi</code> in one of the other problems). This one
is too wiggly to be a parabola (it bends <em>twice</em>), and so is more
like a cubic than anything.</p>
<p>The other thing you can note is that the grey envelope is
“not significantly different from zero”, since 0 is clearly within the grey
envelope all the way across.</p>
<p><span class="math inline">\(\blacksquare\)</span></p>
<ol start="8" style="list-style-type: lower-alpha">
<li>Find the quartiles of <code>age</code>, and make a data frame
containing all combinations of those two ages and the two
treatments. Display what you have. (Feel free to copy the values by
hand, rather than trying to save them and use them.)</li>
</ol>
<p>Solution</p>
<p>I imagine you can guess what we are going to be doing with these:
predictions, so we’ll call the data frame <code>new</code> when we get
there.
Quartiles first:</p>
<div class="sourceCode" id="cb399"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb399-1"><a href="survival-analysis.html#cb399-1"></a><span class="kw">quantile</span>(ovarian<span class="op">$</span>age)</span></code></pre></div>
<pre><code>##       0%      25%      50%      75%     100% 
## 38.89320 50.16712 56.84660 62.37810 74.50410</code></pre>
<p>or, if you prefer,</p>
<div class="sourceCode" id="cb401"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb401-1"><a href="survival-analysis.html#cb401-1"></a>ovarian <span class="op">%&gt;%</span></span>
<span id="cb401-2"><a href="survival-analysis.html#cb401-2"></a><span class="st">  </span><span class="kw">summarize</span>(</span>
<span id="cb401-3"><a href="survival-analysis.html#cb401-3"></a>    <span class="dt">q1 =</span> <span class="kw">quantile</span>(age, <span class="fl">0.25</span>),</span>
<span id="cb401-4"><a href="survival-analysis.html#cb401-4"></a>    <span class="dt">q3 =</span> <span class="kw">quantile</span>(age, <span class="fl">0.75</span>)</span>
<span id="cb401-5"><a href="survival-analysis.html#cb401-5"></a>  )</span></code></pre></div>
<pre><code>##         q1      q3
## 1 50.16712 62.3781</code></pre>
<p>The quartiles are 50.17 and 62.38 (rounding slightly).</p>
<p>Either way is good.</p>
<p>Then follow my standard procedure (or one of your own devising),
remembering that “treatment” is called <code>rx</code> here:</p>
<div class="sourceCode" id="cb403"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb403-1"><a href="survival-analysis.html#cb403-1"></a>ages &lt;-<span class="st"> </span><span class="kw">c</span>(<span class="fl">50.17</span>, <span class="fl">62.38</span>)</span>
<span id="cb403-2"><a href="survival-analysis.html#cb403-2"></a>rxs &lt;-<span class="st"> </span><span class="kw">c</span>(<span class="dv">1</span>, <span class="dv">2</span>)</span>
<span id="cb403-3"><a href="survival-analysis.html#cb403-3"></a>new &lt;-<span class="st"> </span><span class="kw">crossing</span>(<span class="dt">age =</span> ages, <span class="dt">rx =</span> rxs)</span>
<span id="cb403-4"><a href="survival-analysis.html#cb403-4"></a>new</span></code></pre></div>
<pre><code>## # A tibble: 4 x 2
##     age    rx
##   &lt;dbl&gt; &lt;dbl&gt;
## 1  50.2     1
## 2  50.2     2
## 3  62.4     1
## 4  62.4     2</code></pre>
<p><span class="math inline">\(\blacksquare\)</span></p>
<ol style="list-style-type: lower-roman">
<li>Obtain predicted survival probabilities for each of your
age-treatment combinations, for each of a variety of survival
times. (This is only one thing, despite it sounding like a lot.)</li>
</ol>
<p>Solution</p>
<p>The magic word here is <code>survfit</code>. The structure is the same
as for <code>predict</code>:</p>
<div class="sourceCode" id="cb405"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb405-1"><a href="survival-analysis.html#cb405-1"></a>s &lt;-<span class="st"> </span><span class="kw">survfit</span>(time<span class="fl">.1</span>, new, <span class="dt">data =</span> ovarian)</span>
<span id="cb405-2"><a href="survival-analysis.html#cb405-2"></a><span class="kw">summary</span>(s)</span></code></pre></div>
<pre><code>## Call: survfit(formula = time.1, newdata = new, data = ovarian)
## 
##  time n.risk n.event survival1 survival2 survival3 survival4
##    59     26       1     0.993     0.997     0.959     0.981
##   115     25       1     0.985     0.993     0.911     0.959
##   156     24       1     0.973     0.988     0.846     0.928
##   268     23       1     0.959     0.981     0.777     0.893
##   329     22       1     0.932     0.969     0.653     0.826
##   353     21       1     0.905     0.956     0.548     0.764
##   365     20       1     0.877     0.943     0.452     0.701
##   431     17       1     0.843     0.926     0.356     0.630
##   464     15       1     0.805     0.908     0.271     0.557
##   475     14       1     0.768     0.888     0.202     0.489
##   563     12       1     0.701     0.853     0.117     0.382
##   638     11       1     0.634     0.816     0.064     0.292</code></pre>
<p>I didn’t ask you to display it, so doing so is optional. Also, you
don’t need (here) that <code>data=ovarian</code> (the predictions will
work just fine without it), but the plot coming up <em>will not</em>. So
my recommendation is to put it in.</p>
<p>Extra: The four columns <code>survival1</code> through <code>survival4</code> are the
survival probabilities for the times shown in the left-hand column
(these are numbers of days), for the four <em>rows</em> of my
<code>new</code>, in the same order.</p>
<p>There are only a few different times, because these are the numbers of
days at which somebody in the data set died, and the estimated
survival probability does not change at the times in between
these. (You’ll see this on a plot in a minute.)</p>
<p>These survival probabilities are pretty easy to eyeball: the best
survival is in stratum 2, which is the younger patients in treatment
2. This we’ll come back to.</p>
<p><span class="math inline">\(\blacksquare\)</span></p>
<ol start="10" style="list-style-type: lower-alpha">
<li>Draw a plot that compares the survival probabilities at the
different times.</li>
</ol>
<p>Solution</p>
<p>Thus. The <code>conf.int=F</code> means to skip the confidence interval
“envelopes” that I find make the plot rather messy:</p>
<div class="sourceCode" id="cb407"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb407-1"><a href="survival-analysis.html#cb407-1"></a><span class="kw">ggsurvplot</span>(s, <span class="dt">conf.int =</span> F)</span></code></pre></div>
<p><img src="pasias_files/figure-html/ovarian-15-1.png" width="672" /></p>
<p><span class="math inline">\(\blacksquare\)</span></p>
<ol start="11" style="list-style-type: lower-alpha">
<li>According to your plot, how would you describe the effects of
treatment and of age?</li>
</ol>
<p>Solution</p>
<p>The best survival curve, in terms of surviving longest, is up and to
the right, so the green one is best and the blue one is
worst.<a href="#fn55" class="footnote-ref" id="fnref55"><sup>55</sup></a> To figure out which those
are, we have to go back to the data frame we created:</p>
<div class="sourceCode" id="cb408"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb408-1"><a href="survival-analysis.html#cb408-1"></a>new</span></code></pre></div>
<pre><code>## # A tibble: 4 x 2
##     age    rx
##   &lt;dbl&gt; &lt;dbl&gt;
## 1  50.2     1
## 2  50.2     2
## 3  62.4     1
## 4  62.4     2</code></pre>
<p>To see the effect of age, compare strata 1 and 3 (or 2 and 4). This
means comparing the red and blue curves; the red one is clearly better
(in the sense of longer survival time), which means that age has a big
effect on survival, with younger people living longer, other things
being equal (that we saw earlier was significant). You could
equally well compare the green and purple survival curves and come to
the same conclusion.</p>
<p>To assess the effect of treatment, compare strata 1 and 2 (red and
green), or strata 3 and 4 (blue and purple). In both cases, the
stratum corresponding to treatment 2 has slightly better survival (has
a higher chance of living for longer), but there is not as big an
effect as for age. (You’ll recall that the treatment difference was
not significant).</p>
<p>State or imply that you know which stratum is
which, say something about the effects of age and
of treatment, including which one is better.</p>
<p>Extra: recall the output from the Cox model:</p>
<div class="sourceCode" id="cb410"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb410-1"><a href="survival-analysis.html#cb410-1"></a><span class="kw">summary</span>(time<span class="fl">.1</span>)</span></code></pre></div>
<pre><code>## Call:
## coxph(formula = y ~ age + factor(rx), data = ovarian)
## 
##   n= 26, number of events= 12 
## 
##                 coef exp(coef) se(coef)      z Pr(&gt;|z|)   
## age          0.14733   1.15873  0.04615  3.193  0.00141 **
## factor(rx)2 -0.80397   0.44755  0.63205 -1.272  0.20337   
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
##             exp(coef) exp(-coef) lower .95 upper .95
## age            1.1587      0.863    1.0585     1.268
## factor(rx)2    0.4475      2.234    0.1297     1.545
## 
## Concordance= 0.798  (se = 0.076 )
## Likelihood ratio test= 15.89  on 2 df,   p=4e-04
## Wald test            = 13.47  on 2 df,   p=0.001
## Score (logrank) test = 18.56  on 2 df,   p=9e-05</code></pre>
<p>The slope coefficient for treatment 2 (as compared to the baseline
treatment 1) was <span class="math inline">\(-0.83097\)</span>, <em>negative</em>, which meant that patients on
treatment 2 had a <em>lower</em> hazard of death than patients on
treatment 1: that is, that treatment 2 was better for survival than
treatment 1. That is what the plot said also (and the relatively small
difference is consistent with that difference not being significant).</p>
<p><span class="math inline">\(\blacksquare\)</span></p>

</div>
</div>
<div class="footnotes">
<hr />
<ol start="36">
<li id="fn36"><p>Heart attack.<a href="survival-analysis.html#fnref36" class="footnote-back">↩︎</a></p></li>
<li id="fn37"><p>Worcester is pronounced, by locals, <em>Woo-stuh</em>.<a href="survival-analysis.html#fnref37" class="footnote-back">↩︎</a></p></li>
<li id="fn38"><p>Barbecued pork in a bun. A staple of Chinese dim sum and Chinese bakeries, such as Ding Dong bakery on Spadina.<a href="survival-analysis.html#fnref38" class="footnote-back">↩︎</a></p></li>
<li id="fn39"><p>Heart attack.<a href="survival-analysis.html#fnref39" class="footnote-back">↩︎</a></p></li>
<li id="fn40"><p>Worcester is pronounced, by locals, <em>Woo-stuh</em>.<a href="survival-analysis.html#fnref40" class="footnote-back">↩︎</a></p></li>
<li id="fn41"><p>Not exactly the same as that output, because it is doing a test that would be the same if you had an infinitely large sample, but is slightly different with an ordinary finite number of observations.<a href="survival-analysis.html#fnref41" class="footnote-back">↩︎</a></p></li>
<li id="fn42"><p>Our categorical variable <em>gender</em> has only two levels.<a href="survival-analysis.html#fnref42" class="footnote-back">↩︎</a></p></li>
<li id="fn43"><p>It doesn’t work with text columns, but it <em>does</em> work if you temporarily turn the text columns into factors, eg. by using <code>mutate</code> with <code>where</code>. However, we don’t have any text columns here, so what we do here is good for this data set.<a href="survival-analysis.html#fnref43" class="footnote-back">↩︎</a></p></li>
<li id="fn44"><p><code>case_when</code> is much clearer than using nested <code>if-else</code>s when you have three or more categories, as for <code>herco</code>.<a href="survival-analysis.html#fnref44" class="footnote-back">↩︎</a></p></li>
<li id="fn45"><p>Some people define the response variable right inside the <code>coxph</code>, in the same way as putting something like <code>log(y)</code> as a response in an <code>lm</code>, but I think, especially while you’re getting used to the process, it’s better to create the response variable first and look at it to make sure it’s the right thing.<a href="survival-analysis.html#fnref45" class="footnote-back">↩︎</a></p></li>
<li id="fn46"><p>The researchers were probably relieved that there was not quite a significant effect of <code>site</code>.<a href="survival-analysis.html#fnref46" class="footnote-back">↩︎</a></p></li>
<li id="fn47"><p>Not at the 0.05 level, anyway.<a href="survival-analysis.html#fnref47" class="footnote-back">↩︎</a></p></li>
<li id="fn48"><p>Barbecued pork in a bun. A staple of Chinese dim sum and Chinese bakeries, such as Ding Dong bakery on Spadina.<a href="survival-analysis.html#fnref48" class="footnote-back">↩︎</a></p></li>
<li id="fn49"><p>Don’t confuse this with <code>glance</code> from <code>broom</code>, which gives a one-line summary of a <em>model</em>, containing things like R-squared and a test for the overall model significance.<a href="survival-analysis.html#fnref49" class="footnote-back">↩︎</a></p></li>
<li id="fn50"><p>Because <em>summarize</em> will only allow you to have a single-number answer.<a href="survival-analysis.html#fnref50" class="footnote-back">↩︎</a></p></li>
<li id="fn51"><p>The way, as we have seen elsewhere, is to use {} or {}, which produce a two-column data frame with the percentiles shown.<a href="survival-analysis.html#fnref51" class="footnote-back">↩︎</a></p></li>
<li id="fn52"><p>Strata is plural; the singular is <em>stratum</em>. Like data and datum.<a href="survival-analysis.html#fnref52" class="footnote-back">↩︎</a></p></li>
<li id="fn53"><p>Internally, printing a <code>Surv</code> thing calls the method <code>print.Surv</code>, which is defined in the <code>survival</code> package.<a href="survival-analysis.html#fnref53" class="footnote-back">↩︎</a></p></li>
<li id="fn54"><p>In some respects, it’s like that two-column response in logistic regression, where each row of the data frame represents several observations pooled together.<a href="survival-analysis.html#fnref54" class="footnote-back">↩︎</a></p></li>
<li id="fn55"><p>In other cases, having the event happen sooner is better. For example, you might be poisoning rats, in which case you want them to die quicker. Or the event might be something desirable like becoming qualified to fly an airplane. In those cases, down and to the left is better.<a href="survival-analysis.html#fnref55" class="footnote-back">↩︎</a></p></li>
</ol>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="logistic-regression-with-nominal-response.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="analysis-of-variance-revisited.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/lunr.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": null,
"text": null
},
"history": {
"link": null,
"text": null
},
"view": {
"link": null,
"text": null
},
"download": ["pasias.pdf"],
"toc": {
"collapse": "subsection"
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
