<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>Chapter 22 The Bootstrap | Problems and Solutions in Applied Statistics</title>
  <meta name="description" content="A set of problems and solutions, in R, on various parts of applied statistics" />
  <meta name="generator" content="bookdown 0.21 and GitBook 2.6.7" />

  <meta property="og:title" content="Chapter 22 The Bootstrap | Problems and Solutions in Applied Statistics" />
  <meta property="og:type" content="book" />
  <meta property="og:url" content="http://ritsokiguess.site/pasias" />
  
  <meta property="og:description" content="A set of problems and solutions, in R, on various parts of applied statistics" />
  <meta name="github-repo" content="nxskok/pasias" />

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Chapter 22 The Bootstrap | Problems and Solutions in Applied Statistics" />
  
  <meta name="twitter:description" content="A set of problems and solutions, in R, on various parts of applied statistics" />
  

<meta name="author" content="Ken Butler" />


<meta name="date" content="2021-05-17" />

  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="vector-and-matrix-algebra.html"/>
<link rel="next" href="bayesian-statistics-with-stan.html"/>
<script src="libs/jquery-2.2.3/jquery.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />











<style type="text/css">
a.sourceLine { display: inline-block; line-height: 1.25; }
a.sourceLine { pointer-events: none; color: inherit; text-decoration: inherit; }
a.sourceLine:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode { white-space: pre; position: relative; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
code.sourceCode { white-space: pre-wrap; }
a.sourceLine { text-indent: -1em; padding-left: 1em; }
}
pre.numberSource a.sourceLine
  { position: relative; left: -4em; }
pre.numberSource a.sourceLine::before
  { content: attr(title);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; pointer-events: all; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {  }
@media screen {
a.sourceLine::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">Problems and Solutions in Applied Statistics</a></li>

<li class="divider"></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i>Introduction</a><ul>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#packages-used-somewhere-in-this-book"><i class="fa fa-check"></i>Packages used somewhere in this book</a></li>
</ul></li>
<li class="chapter" data-level="1" data-path="getting-used-to-r-and-r-studio.html"><a href="getting-used-to-r-and-r-studio.html"><i class="fa fa-check"></i><b>1</b> Getting used to R and R Studio</a></li>
<li class="chapter" data-level="2" data-path="reading-in-data.html"><a href="reading-in-data.html"><i class="fa fa-check"></i><b>2</b> Reading in data</a></li>
<li class="chapter" data-level="3" data-path="drawing-graphs.html"><a href="drawing-graphs.html"><i class="fa fa-check"></i><b>3</b> Drawing graphs</a></li>
<li class="chapter" data-level="4" data-path="data-exploration.html"><a href="data-exploration.html"><i class="fa fa-check"></i><b>4</b> Data exploration</a></li>
<li class="chapter" data-level="5" data-path="working-with-dataframes.html"><a href="working-with-dataframes.html"><i class="fa fa-check"></i><b>5</b> Working with dataframes</a></li>
<li class="chapter" data-level="6" data-path="one-sample-inference.html"><a href="one-sample-inference.html"><i class="fa fa-check"></i><b>6</b> One-sample inference</a></li>
<li class="chapter" data-level="7" data-path="two-sample-inference.html"><a href="two-sample-inference.html"><i class="fa fa-check"></i><b>7</b> Two-sample inference</a></li>
<li class="chapter" data-level="8" data-path="power-and-sample-size.html"><a href="power-and-sample-size.html"><i class="fa fa-check"></i><b>8</b> Power and sample size</a></li>
<li class="chapter" data-level="9" data-path="the-sign-test.html"><a href="the-sign-test.html"><i class="fa fa-check"></i><b>9</b> The sign test</a></li>
<li class="chapter" data-level="10" data-path="mood-median-test.html"><a href="mood-median-test.html"><i class="fa fa-check"></i><b>10</b> Mood median test</a></li>
<li class="chapter" data-level="11" data-path="matched-pairs-t-and-sign-test.html"><a href="matched-pairs-t-and-sign-test.html"><i class="fa fa-check"></i><b>11</b> Matched pairs t and sign test</a></li>
<li class="chapter" data-level="12" data-path="normal-quantile-plots.html"><a href="normal-quantile-plots.html"><i class="fa fa-check"></i><b>12</b> Normal quantile plots</a><ul>
<li class="chapter" data-level="12.1" data-path="normal-quantile-plots.html"><a href="normal-quantile-plots.html#lengths-of-heliconia-flowers"><i class="fa fa-check"></i><b>12.1</b> Lengths of heliconia flowers</a></li>
<li class="chapter" data-level="12.2" data-path="normal-quantile-plots.html"><a href="normal-quantile-plots.html#ferritin-and-normality"><i class="fa fa-check"></i><b>12.2</b> Ferritin and normality</a></li>
<li class="chapter" data-level="12.3" data-path="normal-quantile-plots.html"><a href="normal-quantile-plots.html#lengths-of-heliconia-flowers-1"><i class="fa fa-check"></i><b>12.3</b> Lengths of heliconia flowers</a></li>
<li class="chapter" data-level="12.4" data-path="normal-quantile-plots.html"><a href="normal-quantile-plots.html#ferritin-and-normality-1"><i class="fa fa-check"></i><b>12.4</b> Ferritin and normality</a></li>
</ul></li>
<li class="chapter" data-level="13" data-path="analysis-of-variance.html"><a href="analysis-of-variance.html"><i class="fa fa-check"></i><b>13</b> Analysis of variance</a></li>
<li class="chapter" data-level="14" data-path="writing-reports.html"><a href="writing-reports.html"><i class="fa fa-check"></i><b>14</b> Writing reports</a></li>
<li class="chapter" data-level="15" data-path="tidying-data.html"><a href="tidying-data.html"><i class="fa fa-check"></i><b>15</b> Tidying data</a></li>
<li class="chapter" data-level="16" data-path="simple-regression.html"><a href="simple-regression.html"><i class="fa fa-check"></i><b>16</b> Simple regression</a></li>
<li class="chapter" data-level="17" data-path="multiple-regression.html"><a href="multiple-regression.html"><i class="fa fa-check"></i><b>17</b> Multiple regression</a></li>
<li class="chapter" data-level="18" data-path="regression-with-categorical-variables.html"><a href="regression-with-categorical-variables.html"><i class="fa fa-check"></i><b>18</b> Regression with categorical variables</a><ul>
<li class="chapter" data-level="18.1" data-path="regression-with-categorical-variables.html"><a href="regression-with-categorical-variables.html#crickets-revisited"><i class="fa fa-check"></i><b>18.1</b> Crickets revisited</a></li>
<li class="chapter" data-level="18.2" data-path="regression-with-categorical-variables.html"><a href="regression-with-categorical-variables.html#pulse-rates-and-marching"><i class="fa fa-check"></i><b>18.2</b> Pulse rates and marching</a></li>
<li class="chapter" data-level="18.3" data-path="regression-with-categorical-variables.html"><a href="regression-with-categorical-variables.html#crickets-revisited-1"><i class="fa fa-check"></i><b>18.3</b> Crickets revisited</a></li>
<li class="chapter" data-level="18.4" data-path="regression-with-categorical-variables.html"><a href="regression-with-categorical-variables.html#pulse-rates-and-marching-1"><i class="fa fa-check"></i><b>18.4</b> Pulse rates and marching</a></li>
</ul></li>
<li class="chapter" data-level="19" data-path="dates-and-times.html"><a href="dates-and-times.html"><i class="fa fa-check"></i><b>19</b> Dates and times</a></li>
<li class="chapter" data-level="20" data-path="functions.html"><a href="functions.html"><i class="fa fa-check"></i><b>20</b> Functions</a></li>
<li class="chapter" data-level="21" data-path="vector-and-matrix-algebra.html"><a href="vector-and-matrix-algebra.html"><i class="fa fa-check"></i><b>21</b> Vector and matrix algebra</a><ul>
<li class="chapter" data-level="21.1" data-path="vector-and-matrix-algebra.html"><a href="vector-and-matrix-algebra.html#heights-and-foot-lengths-again"><i class="fa fa-check"></i><b>21.1</b> Heights and foot lengths again</a></li>
<li class="chapter" data-level="21.2" data-path="vector-and-matrix-algebra.html"><a href="vector-and-matrix-algebra.html#heights-and-foot-lengths-again-1"><i class="fa fa-check"></i><b>21.2</b> Heights and foot lengths again</a></li>
</ul></li>
<li class="chapter" data-level="22" data-path="the-bootstrap.html"><a href="the-bootstrap.html"><i class="fa fa-check"></i><b>22</b> The Bootstrap</a><ul>
<li class="chapter" data-level="22.1" data-path="the-bootstrap.html"><a href="the-bootstrap.html#air-conditioning-failures"><i class="fa fa-check"></i><b>22.1</b> Air conditioning failures</a></li>
<li class="chapter" data-level="22.2" data-path="the-bootstrap.html"><a href="the-bootstrap.html#air-conditioning-failures-bootstrapping-the-median"><i class="fa fa-check"></i><b>22.2</b> Air conditioning failures: bootstrapping the median</a></li>
<li class="chapter" data-level="22.3" data-path="the-bootstrap.html"><a href="the-bootstrap.html#comparing-eyesight"><i class="fa fa-check"></i><b>22.3</b> Comparing eyesight</a></li>
<li class="chapter" data-level="22.4" data-path="the-bootstrap.html"><a href="the-bootstrap.html#bootstrapping-the-irs-data"><i class="fa fa-check"></i><b>22.4</b> Bootstrapping the IRS data</a></li>
<li class="chapter" data-level="22.5" data-path="the-bootstrap.html"><a href="the-bootstrap.html#air-conditioning-failures-1"><i class="fa fa-check"></i><b>22.5</b> Air conditioning failures</a></li>
<li class="chapter" data-level="22.6" data-path="the-bootstrap.html"><a href="the-bootstrap.html#air-conditioning-failures-bootstrapping-the-median-1"><i class="fa fa-check"></i><b>22.6</b> Air conditioning failures: bootstrapping the median</a></li>
<li class="chapter" data-level="22.7" data-path="the-bootstrap.html"><a href="the-bootstrap.html#comparing-eyesight-1"><i class="fa fa-check"></i><b>22.7</b> Comparing eyesight</a></li>
<li class="chapter" data-level="22.8" data-path="the-bootstrap.html"><a href="the-bootstrap.html#bootstrapping-the-irs-data-1"><i class="fa fa-check"></i><b>22.8</b> Bootstrapping the IRS data</a></li>
</ul></li>
<li class="chapter" data-level="23" data-path="bayesian-statistics-with-stan.html"><a href="bayesian-statistics-with-stan.html"><i class="fa fa-check"></i><b>23</b> Bayesian Statistics with Stan</a></li>
<li class="chapter" data-level="24" data-path="logistic-regression.html"><a href="logistic-regression.html"><i class="fa fa-check"></i><b>24</b> Logistic regression</a></li>
<li class="chapter" data-level="25" data-path="logistic-regression-with-ordinal-response.html"><a href="logistic-regression-with-ordinal-response.html"><i class="fa fa-check"></i><b>25</b> Logistic regression with ordinal response</a></li>
<li class="chapter" data-level="26" data-path="logistic-regression-with-nominal-response.html"><a href="logistic-regression-with-nominal-response.html"><i class="fa fa-check"></i><b>26</b> Logistic regression with nominal response</a></li>
<li class="chapter" data-level="27" data-path="survival-analysis.html"><a href="survival-analysis.html"><i class="fa fa-check"></i><b>27</b> Survival analysis</a></li>
<li class="chapter" data-level="28" data-path="analysis-of-variance-revisited.html"><a href="analysis-of-variance-revisited.html"><i class="fa fa-check"></i><b>28</b> Analysis of variance revisited</a></li>
<li class="chapter" data-level="29" data-path="analysis-of-covariance.html"><a href="analysis-of-covariance.html"><i class="fa fa-check"></i><b>29</b> Analysis of covariance</a></li>
<li class="chapter" data-level="30" data-path="multivariate-analysis-of-variance.html"><a href="multivariate-analysis-of-variance.html"><i class="fa fa-check"></i><b>30</b> Multivariate analysis of variance</a></li>
<li class="chapter" data-level="31" data-path="repeated-measures.html"><a href="repeated-measures.html"><i class="fa fa-check"></i><b>31</b> Repeated measures</a></li>
<li class="chapter" data-level="32" data-path="discriminant-analysis.html"><a href="discriminant-analysis.html"><i class="fa fa-check"></i><b>32</b> Discriminant analysis</a></li>
<li class="chapter" data-level="33" data-path="hierarchical-cluster-analysis.html"><a href="hierarchical-cluster-analysis.html"><i class="fa fa-check"></i><b>33</b> Hierarchical cluster analysis</a></li>
<li class="chapter" data-level="34" data-path="k-means-cluster-analysis.html"><a href="k-means-cluster-analysis.html"><i class="fa fa-check"></i><b>34</b> K-means cluster analysis</a></li>
<li class="chapter" data-level="35" data-path="drawing-maps-with-leaflet.html"><a href="drawing-maps-with-leaflet.html"><i class="fa fa-check"></i><b>35</b> Drawing maps with Leaflet</a></li>
<li class="chapter" data-level="36" data-path="multidimensional-scaling.html"><a href="multidimensional-scaling.html"><i class="fa fa-check"></i><b>36</b> Multidimensional Scaling</a></li>
<li class="chapter" data-level="37" data-path="principal-components.html"><a href="principal-components.html"><i class="fa fa-check"></i><b>37</b> Principal Components</a><ul>
<li class="chapter" data-level="37.1" data-path="principal-components.html"><a href="principal-components.html#the-weather-somewhere"><i class="fa fa-check"></i><b>37.1</b> The weather, somewhere</a></li>
<li class="chapter" data-level="37.2" data-path="principal-components.html"><a href="principal-components.html#the-weather-somewhere-1"><i class="fa fa-check"></i><b>37.2</b> The weather, somewhere</a></li>
</ul></li>
<li class="chapter" data-level="38" data-path="factor-analysis.html"><a href="factor-analysis.html"><i class="fa fa-check"></i><b>38</b> Factor Analysis</a></li>
<li class="chapter" data-level="39" data-path="frequency-table-analysis.html"><a href="frequency-table-analysis.html"><i class="fa fa-check"></i><b>39</b> Frequency table analysis</a></li>
<li class="divider"></li>
<li><a href="https://github.com/rstudio/bookdown" target="blank">Published with bookdown</a></li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Problems and Solutions in Applied Statistics</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="the-bootstrap" class="section level1">
<h1><span class="header-section-number">Chapter 22</span> The Bootstrap</h1>
<p>Packages for this chapter:</p>
<div class="sourceCode" id="cb117"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb117-1" title="1"><span class="kw">library</span>(tidyverse)</a>
<a class="sourceLine" id="cb117-2" title="2"><span class="kw">library</span>(bootstrap)</a></code></pre></div>
<div id="air-conditioning-failures" class="section level2">
<h2><span class="header-section-number">22.1</span> Air conditioning failures</h2>
<p>Back in 1963, there was a report on failures in
air-conditioning equipment in

aircraft. For one aircraft, the air-conditioning equipment failed 12
times, and the number of hours it ran before failing each time was
recorded. The data are in
<a href="https://raw.githubusercontent.com/nxskok/pasias/master/air_conditioning.csv">link</a>. Boeing
was interested in the mean failure time, because the company wanted to
plan for engineers to fix the failures (and thus needed to estimate a
failure <em>rate</em>).</p>
<p>There is randomization here. Your answers will differ slightly from
mine, unless you throw in this before you start (or at least before
you generate your first random numbers).</p>
<div class="sourceCode" id="cb118"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb118-1" title="1"><span class="kw">set.seed</span>(<span class="dv">457299</span>)</a></code></pre></div>
<ol style="list-style-type: lower-alpha">
<li><p>Read in the data, and observe that you have the correct number
of rows. (Note that the failure times are in ascending order).</p></li>
<li><p>What do you notice about the <em>shape</em> of the distribution of failure times? Explain briefly.</p></li>
<li><p>Obtain the means of 1000 bootstrap samples (that is, samples from the data with replacement). Save them.</p></li>
<li><p>Make a normal quantile plot of your bootstrap distribution. What do you see? Explain briefly.</p></li>
<li><p>Obtain the 95% bootstrap percentile confidence interval for the mean.</p></li>
<li><p>Obtain the 95% bootstrap-<span class="math inline">\(t\)</span> confidence interval for
the mean, and compare your two intervals.</p></li>
<li><p>Obtain the BCa 95% confidence interval for the mean.</p></li>
<li><p>Compare the BCa confidence interval with the other ones. Which one would you recommend? Explain briefly.</p></li>
</ol>
</div>
<div id="air-conditioning-failures-bootstrapping-the-median" class="section level2">
<h2><span class="header-section-number">22.2</span> Air conditioning failures: bootstrapping the median</h2>
<p>With a skewed data distribution such as the air-conditioning
failure times, we might be interested in inference for the median. One
way to get a confidence interval for the median is to invert the sign
test, as in <code>smmr</code>, but another way is to obtain a bootstrap
sampling distribution for the median. How do these approaches compare
for the air-conditioning data? We explore this here.</p>
<ol style="list-style-type: lower-alpha">
<li><p>Read in the air-conditioning data again (if you don’t already
have it lying around). The link is in the previous question.</p></li>
<li><p>Use <code>smmr</code> to get a confidence interval for the median (based on the sign test).</p></li>
<li><p>Obtain the bootstrap distribution of the sample median. Make a normal quantile plot of it. What do you notice? Explain briefly.</p></li>
<li><p>Obtain a 95% bootstrap percentile confidence interval for the median. How does it compare with the one you obtained earlier?</p></li>
<li><p>Obtain a 95% BCa interval. Compare it with the two other intervals you found.</p></li>
</ol>
</div>
<div id="comparing-eyesight" class="section level2">
<h2><span class="header-section-number">22.3</span> Comparing eyesight</h2>
<p>Do people see on average better with their left eye or their right eye, or is there no difference? To find out, 15 subjects were shown a sequence of images, some to their left eye and some to their right (with a blindfold on the other eye). The subjects were asked to identify some objects in each image, and were given an overall score for each eye, based on their ability to identify objects with each eye. (A higher score is better.) Data in .</p>
<ol style="list-style-type: lower-alpha">
<li><p>Read in and display (some of) the data.</p></li>
<li><p>Explain briefly why looking at differences (say right minus left) makes sense for these data, and calculate and save a dataframe with the differences added to it.</p></li>
<li><p>Make a suitable normal quantile plot, and describe what it tells you.</p></li>
<li><p>Obtain a bootstrap distribution of the sample <em>median</em>.</p></li>
<li><p>Make a histogram of your bootstrap distribution of the median. Use a lot of bins, such as the default 30, for this. What do you notice about the distribution? Why did it come out this way?</p></li>
<li><p>Find a 95% percentile interval for the population median.<a href="#fn16" class="footnote-ref" id="fnref16"><sup>16</sup></a></p></li>
<li><p>Find the BCA 95% confidence interval for the population median difference.</p></li>
<li><p>What do your intervals tell us about any possible difference between left eye and right eye in terms of ability to identify objects in images? Do the intervals agree or disagree about this?</p></li>
</ol>
</div>
<div id="bootstrapping-the-irs-data" class="section level2">
<h2><span class="header-section-number">22.4</span> Bootstrapping the IRS data</h2>
<p>You might recall the IRS data from when we were learning about the sign test. The idea was that we wanted to see how long “on average” it took people to fill out a tax form. The data are in <a href="http://ritsokiguess.site/datafiles/irs.txt">http://ritsokiguess.site/datafiles/irs.txt</a>.</p>
<ol style="list-style-type: lower-alpha">
<li><p>Read in and display (some of) the data. There is only one column of data, so you can pretend the values are separated by anything.</p></li>
<li><p>Obtain a bootstrap distribution of the sample <em>median</em>.</p></li>
<li><p>Make a suitable graph of the bootstrap distribution of the median. What seems odd about it? Why did that happen? (Hint: use more bins on your plot than usual, like 50.)</p></li>
<li><p>Find 95% percentile and bootstrap-<span class="math inline">\(t\)</span> intervals for the population median. (Hint: your dataframe of bootstrapped medians may still be <code>rowwise</code>, so you might need to run <code>ungroup</code> first.)</p></li>
</ol>
<p>My solutions follow:</p>
</div>
<div id="air-conditioning-failures-1" class="section level2">
<h2><span class="header-section-number">22.5</span> Air conditioning failures</h2>
<p>Back in 1963, there was a report on failures in
air-conditioning equipment in

aircraft. For one aircraft, the air-conditioning equipment failed 12
times, and the number of hours it ran before failing each time was
recorded. The data are in
<a href="https://raw.githubusercontent.com/nxskok/pasias/master/air_conditioning.csv">link</a>. Boeing
was interested in the mean failure time, because the company wanted to
plan for engineers to fix the failures (and thus needed to estimate a
failure <em>rate</em>).</p>
<p>There is randomization here. Your answers will differ slightly from
mine, unless you throw in this before you start (or at least before
you generate your first random numbers).</p>
<div class="sourceCode" id="cb119"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb119-1" title="1"><span class="kw">set.seed</span>(<span class="dv">457299</span>)</a></code></pre></div>
<ol style="list-style-type: lower-alpha">
<li>Read in the data, and observe that you have the correct number
of rows. (Note that the failure times are in ascending order).</li>
</ol>
<p>Solution</p>
<p>This is a <code>.csv</code> so <code>read_csv</code> is the thing:</p>
<div class="sourceCode" id="cb120"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb120-1" title="1">my_url &lt;-<span class="st"> &quot;https://raw.githubusercontent.com/nxskok/pasias/master/air_conditioning.csv&quot;</span></a>
<a class="sourceLine" id="cb120-2" title="2">aircon &lt;-<span class="st"> </span><span class="kw">read_csv</span>(my_url)</a></code></pre></div>
<pre><code>## 
## ── Column specification ──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
## cols(
##   failure = col_double(),
##   hours = col_double()
## )</code></pre>
<div class="sourceCode" id="cb122"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb122-1" title="1">aircon</a></code></pre></div>
<pre><code>## # A tibble: 12 x 2
##    failure hours
##      &lt;dbl&gt; &lt;dbl&gt;
##  1       1     3
##  2       2     5
##  3       3     7
##  4       4    18
##  5       5    43
##  6       6    85
##  7       7    91
##  8       8    98
##  9       9   100
## 10      10   130
## 11      11   230
## 12      12   487</code></pre>
<p>Twelve rows (12 failure times).</p>
<p><span class="math inline">\(\blacksquare\)</span></p>
<ol start="2" style="list-style-type: lower-alpha">
<li>What do you notice about the <em>shape</em> of the distribution of failure times? Explain briefly.</li>
</ol>
<p>Solution</p>
<p>Make a suitable graph. The obvious one is a histogram:</p>
<div class="sourceCode" id="cb124"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb124-1" title="1"><span class="kw">ggplot</span>(aircon, <span class="kw">aes</span>(<span class="dt">x =</span> hours)) <span class="op">+</span><span class="st"> </span><span class="kw">geom_histogram</span>(<span class="dt">bins =</span> <span class="dv">7</span>)</a></code></pre></div>
<p><img src="pasias_files/figure-html/unnamed-chunk-81-1.png" width="672" /></p>
<p>You’ll have to play with the number of bins (there are only 12 observations). I got 7 from the Freedman-Diaconis rule:</p>
<div class="sourceCode" id="cb125"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb125-1" title="1"><span class="kw">nclass.FD</span>(aircon<span class="op">$</span>hours)</a></code></pre></div>
<pre><code>## [1] 7</code></pre>
<p>I was a little suspicious that the data would not be much like normal (I have run into failure times before), so I kept away from the Sturges rule.</p>
<p>Another possibility is a one-group boxplot:</p>
<div class="sourceCode" id="cb127"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb127-1" title="1"><span class="kw">ggplot</span>(aircon, <span class="kw">aes</span>(<span class="dt">y =</span> hours, <span class="dt">x =</span> <span class="dv">1</span>)) <span class="op">+</span><span class="st"> </span><span class="kw">geom_boxplot</span>()</a></code></pre></div>
<p><img src="pasias_files/figure-html/unnamed-chunk-83-1.png" width="672" /></p>
<p>If you like, you can do a normal quantile plot. I rank that third here, because there is nothing immediately implying a comparison with the <em>normal</em> distribution, but I would accept it:</p>
<div class="sourceCode" id="cb128"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb128-1" title="1"><span class="kw">ggplot</span>(aircon, <span class="kw">aes</span>(<span class="dt">sample =</span> hours)) <span class="op">+</span><span class="st"> </span><span class="kw">stat_qq</span>() <span class="op">+</span><span class="st"> </span><span class="kw">stat_qq_line</span>()</a></code></pre></div>
<p><img src="pasias_files/figure-html/unnamed-chunk-84-1.png" width="672" /></p>
<p>Pick a visual and defend it.</p>
<p>All three of these graphs are showing a strong skewness to the right.</p>
<p>Extra: this is probably not a surprise, because a time until failure
cannot be less than zero, and distributions with a limit tend to be
skewed away from that limit. (If you look back at the data, there are
some very small failure times, but there are also some very big
ones. The very small ones are saying that the lower limit matters.) If
you were modelling these times until failure, you might use a
distribution like the exponential or gamma or Weibull.</p>
<p><span class="math inline">\(\blacksquare\)</span></p>
<ol start="3" style="list-style-type: lower-alpha">
<li>Obtain the means of 1000 bootstrap samples (that is, samples from the data with replacement). Save them.</li>
</ol>
<p>Solution</p>
<p>Something like this, therefore:</p>
<div class="sourceCode" id="cb129"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb129-1" title="1"><span class="kw">tibble</span>(<span class="dt">sim =</span> <span class="dv">1</span><span class="op">:</span><span class="dv">1000</span>) <span class="op">%&gt;%</span><span class="st"> </span></a>
<a class="sourceLine" id="cb129-2" title="2"><span class="st">  </span><span class="kw">rowwise</span>() <span class="op">%&gt;%</span><span class="st"> </span></a>
<a class="sourceLine" id="cb129-3" title="3"><span class="st">  </span><span class="kw">mutate</span>(<span class="dt">sample =</span> <span class="kw">list</span>(<span class="kw">sample</span>(aircon<span class="op">$</span>hours, <span class="dt">replace =</span> <span class="ot">TRUE</span>))) <span class="op">%&gt;%</span><span class="st"> </span></a>
<a class="sourceLine" id="cb129-4" title="4"><span class="st">  </span><span class="kw">mutate</span>(<span class="dt">sample_mean =</span> <span class="kw">mean</span>(sample)) -&gt;<span class="st"> </span>means</a>
<a class="sourceLine" id="cb129-5" title="5">means</a></code></pre></div>
<pre><code>## # A tibble: 1,000 x 3
## # Rowwise: 
##      sim sample     sample_mean
##    &lt;int&gt; &lt;list&gt;           &lt;dbl&gt;
##  1     1 &lt;dbl [12]&gt;        83.2
##  2     2 &lt;dbl [12]&gt;        52.3
##  3     3 &lt;dbl [12]&gt;       122. 
##  4     4 &lt;dbl [12]&gt;        82.3
##  5     5 &lt;dbl [12]&gt;       115. 
##  6     6 &lt;dbl [12]&gt;       150. 
##  7     7 &lt;dbl [12]&gt;       141. 
##  8     8 &lt;dbl [12]&gt;        69.2
##  9     9 &lt;dbl [12]&gt;        90  
## 10    10 &lt;dbl [12]&gt;        69.4
## # … with 990 more rows</code></pre>
<p>Forgetting the <code>rowwise</code> will cause all sorts of trouble.</p>
<p><span class="math inline">\(\blacksquare\)</span></p>
<ol start="4" style="list-style-type: lower-alpha">
<li>Make a normal quantile plot of your bootstrap distribution. What do you see? Explain briefly.</li>
</ol>
<p>Solution</p>
<p>This:</p>
<div class="sourceCode" id="cb131"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb131-1" title="1"><span class="kw">ggplot</span>(means, <span class="kw">aes</span>(<span class="dt">sample =</span> sample_mean)) <span class="op">+</span><span class="st"> </span><span class="kw">stat_qq</span>() <span class="op">+</span><span class="st"> </span><span class="kw">stat_qq_line</span>()</a></code></pre></div>
<p><img src="pasias_files/figure-html/unnamed-chunk-86-1.png" width="672" /></p>
<p>This is still skewed to the right (it has a curved shape, or, the low values and the high values are both too high compared to the normal).</p>
<p>Extra: this is less skewed than the original data was, because, with a
sample size of 12, we have a <em>little</em> help from the Central Limit
Theorem, but not much. This picture is the one that has to be normal
enough for <span class="math inline">\(t\)</span> procedures to work, and it is not. This comes back into
the picture when we compare our confidence intervals later.</p>
<p>Also, it makes sense to see how <em>normal</em> a sampling distribution of a
mean is, so a normal quantile plot would be my first choice for this.</p>
<p><span class="math inline">\(\blacksquare\)</span></p>
<ol start="5" style="list-style-type: lower-alpha">
<li>Obtain the 95% bootstrap percentile confidence interval for the mean.</li>
</ol>
<p>Solution</p>
<p>This is the 2.5 and 97.5 percentiles of the bootstrapped sampling distribution of the mean:</p>
<div class="sourceCode" id="cb132"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb132-1" title="1"><span class="kw">quantile</span>(means<span class="op">$</span>sample_mean, <span class="kw">c</span>(<span class="fl">0.025</span>, <span class="fl">0.975</span>))</a></code></pre></div>
<pre><code>##      2.5%     97.5% 
##  46.74583 180.92917</code></pre>
<p><span class="math inline">\(\blacksquare\)</span></p>
<ol start="6" style="list-style-type: lower-alpha">
<li>Obtain the 95% bootstrap-<span class="math inline">\(t\)</span> confidence interval for
the mean, and compare your two intervals.</li>
</ol>
<p>Solution</p>
<p>The key is to remember that the original sample (and thus each bootstrap sample) had <span class="math inline">\(n=12\)</span>, so there are <span class="math inline">\(12-1=11\)</span> df. (The fact that there were 1000 bootstrap samples is neither here nor there). This is how I like to do it:</p>
<div class="sourceCode" id="cb134"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb134-1" title="1">t_star &lt;-<span class="st"> </span><span class="kw">qt</span>(<span class="fl">0.975</span>, <span class="dv">11</span>)</a>
<a class="sourceLine" id="cb134-2" title="2">t_star</a></code></pre></div>
<pre><code>## [1] 2.200985</code></pre>
<div class="sourceCode" id="cb136"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb136-1" title="1"><span class="kw">mean</span>(means<span class="op">$</span>sample_mean) <span class="op">+</span><span class="st"> </span><span class="kw">c</span>(<span class="op">-</span><span class="dv">1</span>, <span class="dv">1</span>) <span class="op">*</span><span class="st"> </span>t_star <span class="op">*</span><span class="st"> </span><span class="kw">sd</span>(means<span class="op">$</span>sample_mean)</a></code></pre></div>
<pre><code>## [1]  26.18964 185.96786</code></pre>
<p>The <code>c(-1, 1)</code> thing is the calculation version of the <span class="math inline">\(\pm\)</span>,
and gets both limits at once. Pull the above apart to see how it works. If
you don’t like that, you might prefer something like this:</p>
<div class="sourceCode" id="cb138"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb138-1" title="1">the_mean &lt;-<span class="st"> </span><span class="kw">mean</span>(means<span class="op">$</span>sample_mean)</a>
<a class="sourceLine" id="cb138-2" title="2">the_sd &lt;-<span class="st"> </span><span class="kw">sd</span>(means<span class="op">$</span>sample_mean)</a>
<a class="sourceLine" id="cb138-3" title="3">margin &lt;-<span class="st"> </span>t_star <span class="op">*</span><span class="st"> </span>the_sd</a>
<a class="sourceLine" id="cb138-4" title="4">the_mean <span class="op">-</span><span class="st"> </span>margin</a></code></pre></div>
<pre><code>## [1] 26.18964</code></pre>
<div class="sourceCode" id="cb140"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb140-1" title="1">the_mean <span class="op">+</span><span class="st"> </span>margin</a></code></pre></div>
<pre><code>## [1] 185.9679</code></pre>
<p>I apologize for the crazy first line of that!
As for comparison: the bootstrap-<span class="math inline">\(t\)</span> interval goes down a lot further,
though the upper limits are quite similar (on this scale). Both
intervals are very long and don’t tell us much about the population
mean time to failure, which is not very surprising given the small
sample size (<span class="math inline">\(n=12\)</span>) and the large variability in the data.</p>
<p>Extra: the non-normality of the bootstrap (sampling) distribution says that we should definitely not trust the bootstrap-<span class="math inline">\(t\)</span>, and probably not the bootstrap percentile interval either. Which brings us to the next part.</p>
<p><span class="math inline">\(\blacksquare\)</span></p>
<ol start="7" style="list-style-type: lower-alpha">
<li>Obtain the BCa 95% confidence interval for the mean.</li>
</ol>
<p>Solution</p>
<p>This means (possibly) installing and (certainly) loading the <code>bootstrap</code> package, and then:</p>
<div class="sourceCode" id="cb142"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb142-1" title="1">theta &lt;-<span class="st"> </span><span class="cf">function</span>(x) {</a>
<a class="sourceLine" id="cb142-2" title="2">  <span class="kw">mean</span>(x)</a>
<a class="sourceLine" id="cb142-3" title="3">}</a>
<a class="sourceLine" id="cb142-4" title="4">bca_all &lt;-<span class="st"> </span><span class="kw">with</span>(aircon, <span class="kw">bcanon</span>(hours, <span class="dv">1000</span>, theta))</a>
<a class="sourceLine" id="cb142-5" title="5">bca &lt;-<span class="st"> </span>bca_all<span class="op">$</span>confpoints</a>
<a class="sourceLine" id="cb142-6" title="6">bca</a></code></pre></div>
<pre><code>##      alpha bca point
## [1,] 0.025     55.25
## [2,] 0.050     61.25
## [3,] 0.100     70.50
## [4,] 0.160     78.50
## [5,] 0.840    160.50
## [6,] 0.900    178.00
## [7,] 0.950    204.25
## [8,] 0.975    228.75</code></pre>
<p>Pull out the ones from this that you need: the top one and the bottom one, to get an interval of 55.2
to 228.8.</p>
<p>I seem to need to define the function <code>theta</code> first and pass it into <code>bcanon</code> as the third input. You may have more luck with <code>bcanon(hours, 1000, mean)</code> than I did. Try it.</p>
<p>Or, if you feel like some extra coding: turn this matrix into a data frame, grab the rows you want, and then the column you want:</p>
<div class="sourceCode" id="cb144"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb144-1" title="1">bca <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb144-2" title="2"><span class="st">  </span><span class="kw">as_tibble</span>() <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb144-3" title="3"><span class="st">  </span><span class="kw">filter</span>(alpha <span class="op">%in%</span><span class="st"> </span><span class="kw">c</span>(<span class="fl">0.025</span>, <span class="fl">0.975</span>)) <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb144-4" title="4"><span class="st">  </span><span class="kw">pull</span>(<span class="st">`</span><span class="dt">bca point</span><span class="st">`</span>)</a></code></pre></div>
<pre><code>## [1]  55.25 228.75</code></pre>
<p><span class="math inline">\(\blacksquare\)</span></p>
<ol start="8" style="list-style-type: lower-alpha">
<li>Compare the BCa confidence interval with the other ones. Which one would you recommend? Explain briefly.</li>
</ol>
<p>Solution</p>
<p>In this example, the bootstrap-<span class="math inline">\(t\)</span> and percentile intervals are very different, so we should use neither of them, and prefer the BCa interval.</p>
<p>Extra: as usual in this kind of case, the BCa contains values for the mean pulled out into the long tail, but that’s a proper adjustment for the sampling distribution being skewed.</p>
<p><span class="math inline">\(\blacksquare\)</span></p>
</div>
<div id="air-conditioning-failures-bootstrapping-the-median-1" class="section level2">
<h2><span class="header-section-number">22.6</span> Air conditioning failures: bootstrapping the median</h2>
<p>With a skewed data distribution such as the air-conditioning
failure times, we might be interested in inference for the median. One
way to get a confidence interval for the median is to invert the sign
test, as in <code>smmr</code>, but another way is to obtain a bootstrap
sampling distribution for the median. How do these approaches compare
for the air-conditioning data? We explore this here.</p>
<ol style="list-style-type: lower-alpha">
<li>Read in the air-conditioning data again (if you don’t already
have it lying around). The link is in the previous question.</li>
</ol>
<p>Solution</p>
<div class="sourceCode" id="cb146"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb146-1" title="1">my_url &lt;-<span class="st"> &quot;https://raw.githubusercontent.com/nxskok/pasias/master/air_conditioning.csv&quot;</span></a>
<a class="sourceLine" id="cb146-2" title="2">aircon &lt;-<span class="st"> </span><span class="kw">read_csv</span>(my_url)</a></code></pre></div>
<pre><code>## 
## ── Column specification ──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
## cols(
##   failure = col_double(),
##   hours = col_double()
## )</code></pre>
<div class="sourceCode" id="cb148"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb148-1" title="1">aircon</a></code></pre></div>
<pre><code>## # A tibble: 12 x 2
##    failure hours
##      &lt;dbl&gt; &lt;dbl&gt;
##  1       1     3
##  2       2     5
##  3       3     7
##  4       4    18
##  5       5    43
##  6       6    85
##  7       7    91
##  8       8    98
##  9       9   100
## 10      10   130
## 11      11   230
## 12      12   487</code></pre>
<p><span class="math inline">\(\blacksquare\)</span></p>
<ol start="2" style="list-style-type: lower-alpha">
<li>Use <code>smmr</code> to get a confidence interval for the median (based on the sign test).</li>
</ol>
<p>Solution</p>
<p>Input to <code>ci_median</code> is data frame and column:</p>
<div class="sourceCode" id="cb150"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb150-1" title="1"><span class="kw">ci_median</span>(aircon, hours)</a></code></pre></div>
<pre><code>## [1]   7.002319 129.998291</code></pre>
<p><span class="math inline">\(\blacksquare\)</span></p>
<ol start="3" style="list-style-type: lower-alpha">
<li>Obtain the bootstrap distribution of the sample median. Make a normal quantile plot of it. What do you notice? Explain briefly.</li>
</ol>
<p>Solution</p>
<p>The usual do-it-yourself bootstrap:</p>
<div class="sourceCode" id="cb152"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb152-1" title="1"><span class="kw">tibble</span>(<span class="dt">sim =</span> <span class="dv">1</span><span class="op">:</span><span class="dv">1000</span>) <span class="op">%&gt;%</span><span class="st"> </span></a>
<a class="sourceLine" id="cb152-2" title="2"><span class="st">  </span><span class="kw">rowwise</span>() <span class="op">%&gt;%</span><span class="st"> </span></a>
<a class="sourceLine" id="cb152-3" title="3"><span class="st">  </span><span class="kw">mutate</span>(<span class="dt">samples =</span> <span class="kw">list</span>(<span class="kw">sample</span>(aircon<span class="op">$</span>hours, <span class="dt">replace =</span> <span class="ot">TRUE</span>))) <span class="op">%&gt;%</span><span class="st"> </span></a>
<a class="sourceLine" id="cb152-4" title="4"><span class="st">  </span><span class="kw">mutate</span>(<span class="dt">medians =</span> <span class="kw">median</span>(samples)) -&gt;<span class="st"> </span>meds</a></code></pre></div>
<p>I actually copied and pasted my code from the previous problem, changing <code>mean</code> to <code>median</code>.</p>
<p>As for a plot, well, this:</p>
<div class="sourceCode" id="cb153"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb153-1" title="1"><span class="kw">ggplot</span>(meds, <span class="kw">aes</span>(<span class="dt">sample =</span> medians)) <span class="op">+</span><span class="st"> </span><span class="kw">stat_qq</span>() <span class="op">+</span><span class="st"> </span><span class="kw">stat_qq_line</span>()</a></code></pre></div>
<p><img src="pasias_files/figure-html/unnamed-chunk-95-1.png" width="672" /></p>
<p>Not only does this not look very normal, but also there are those
curious horizontal patches of points (that, you might recall, are
characteristic of a discrete distribution). This has happened because
there are only a few possible medians: the median has to be either a
data value or halfway between two data values, so there are only
something like <span class="math inline">\(2(12)-1=23\)</span> different possible medians, with the ones
in the middle being more likely.</p>
<p>This also shows up on a histogram, but only if you have enough
bins. (If you don’t have enough bins, some of the neighbouring
possible values end up in the same bin; here, the aim is to have
enough bins to show the discreteness, rather than the usual thing of
having few enough bins to show the shape.)</p>
<div class="sourceCode" id="cb154"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb154-1" title="1"><span class="kw">ggplot</span>(meds, <span class="kw">aes</span>(<span class="dt">x =</span> medians)) <span class="op">+</span><span class="st"> </span><span class="kw">geom_histogram</span>(<span class="dt">bins =</span> <span class="dv">30</span>)</a></code></pre></div>
<p><img src="pasias_files/figure-html/unnamed-chunk-96-1.png" width="672" /></p>
<p><span class="math inline">\(\blacksquare\)</span></p>
<ol start="4" style="list-style-type: lower-alpha">
<li>Obtain a 95% bootstrap percentile confidence interval for the median. How does it compare with the one you obtained earlier?</li>
</ol>
<p>Solution</p>
<p>Also, the usual:</p>
<div class="sourceCode" id="cb155"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb155-1" title="1"><span class="kw">quantile</span>(meds<span class="op">$</span>medians, <span class="kw">c</span>(<span class="fl">0.025</span>, <span class="fl">0.975</span>))</a></code></pre></div>
<pre><code>##  2.5% 97.5% 
##  12.5 115.0</code></pre>
<p>This goes down and up not quite so far as the interval from <code>smmr</code>. That might be because the <code>smmr</code> interval is too wide (based on a not-very-powerful test), or because the bootstrap quantile interval is too narrow (as it usually is). It’s hard to tell which it is.</p>
<p><span class="math inline">\(\blacksquare\)</span></p>
<ol start="5" style="list-style-type: lower-alpha">
<li>Obtain a 95% BCa interval. Compare it with the two other intervals you found.</li>
</ol>
<p>Solution</p>
<p>Yet more copying and pasting (from the previous question):</p>
<div class="sourceCode" id="cb157"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb157-1" title="1">theta &lt;-<span class="st"> </span><span class="cf">function</span>(x) {</a>
<a class="sourceLine" id="cb157-2" title="2">  <span class="kw">median</span>(x)</a>
<a class="sourceLine" id="cb157-3" title="3">}</a>
<a class="sourceLine" id="cb157-4" title="4">bca_all &lt;-<span class="st"> </span><span class="kw">with</span>(aircon, <span class="kw">bcanon</span>(hours, <span class="dv">1000</span>, theta))</a>
<a class="sourceLine" id="cb157-5" title="5">bca &lt;-<span class="st"> </span>bca_all<span class="op">$</span>confpoints</a>
<a class="sourceLine" id="cb157-6" title="6">bca</a></code></pre></div>
<pre><code>##      alpha bca point
## [1,] 0.025      12.5
## [2,] 0.050      12.5
## [3,] 0.100      18.0
## [4,] 0.160      30.5
## [5,] 0.840      94.5
## [6,] 0.900      98.0
## [7,] 0.950     100.0
## [8,] 0.975     115.0</code></pre>
<p>Again, I seem to need to define the tiny function, while you can probably call <code>bcanon(hours, 1000, median)</code>. Try it and see.</p>
<p>My BCa interval is a little longer than the bootstrap percentile
interval and a little shorter than the one that came from the sign
test. I would guess that the BCa interval is the most trustworthy of
the three, though there is here not that much difference between
them. All the intervals are again very long, a reflection of the small
sample size and large variability.</p>
<p><span class="math inline">\(\blacksquare\)</span></p>
</div>
<div id="comparing-eyesight-1" class="section level2">
<h2><span class="header-section-number">22.7</span> Comparing eyesight</h2>
<p>Do people see on average better with their left eye or their right eye, or is there no difference? To find out, 15 subjects were shown a sequence of images, some to their left eye and some to their right (with a blindfold on the other eye). The subjects were asked to identify some objects in each image, and were given an overall score for each eye, based on their ability to identify objects with each eye. (A higher score is better.) Data in .</p>
<ol style="list-style-type: lower-alpha">
<li>Read in and display (some of) the data.</li>
</ol>
<p>Solution</p>
<p>This is a <code>csv</code>, so no surprises:</p>
<div class="sourceCode" id="cb159"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb159-1" title="1">my_url &lt;-<span class="st"> &quot;http://ritsokiguess.site/datafiles/eyesight.csv&quot;</span></a>
<a class="sourceLine" id="cb159-2" title="2">sight &lt;-<span class="st"> </span><span class="kw">read_csv</span>(my_url)</a></code></pre></div>
<pre><code>## 
## ── Column specification ──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
## cols(
##   person = col_double(),
##   right = col_double(),
##   left = col_double()
## )</code></pre>
<div class="sourceCode" id="cb161"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb161-1" title="1">sight</a></code></pre></div>
<pre><code>## # A tibble: 15 x 3
##    person right  left
##     &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt;
##  1      1    50    47
##  2      2    45    45
##  3      3    33    31
##  4      4    22    24
##  5      5    99    78
##  6      6    79    76
##  7      7     4    13
##  8      8    36    46
##  9      9    62    45
## 10     10    51    44
## 11     11    27    23
## 12     12    15    14
## 13     13    26    34
## 14     14    83    79
## 15     15    86    81</code></pre>
<p>15 observations, with the subjects labelled by number, and a score for each subject and each eye.</p>
<p><span class="math inline">\(\blacksquare\)</span></p>
<ol start="2" style="list-style-type: lower-alpha">
<li>Explain briefly why looking at differences (say right minus left) makes sense for these data, and calculate and save a dataframe with the differences added to it.</li>
</ol>
<p>Solution</p>
<p>This is matched pairs data, with two observations for each subject. A matched pairs analysis, whether by a sign test or a matched-pairs <span class="math inline">\(t\)</span>-test, would be based on one difference for each subject, and so those would make sense to calculate. (You’ll recall that a matched pairs analysis uses the differences and <em>not</em> the original data.)</p>
<p>Thus, saving back into our original dataframe:</p>
<div class="sourceCode" id="cb163"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb163-1" title="1">sight <span class="op">%&gt;%</span><span class="st"> </span></a>
<a class="sourceLine" id="cb163-2" title="2"><span class="kw">mutate</span>(<span class="dt">difference =</span> right <span class="op">-</span><span class="st"> </span>left) -&gt;<span class="st"> </span>sight</a>
<a class="sourceLine" id="cb163-3" title="3">sight</a></code></pre></div>
<pre><code>## # A tibble: 15 x 4
##    person right  left difference
##     &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt;      &lt;dbl&gt;
##  1      1    50    47          3
##  2      2    45    45          0
##  3      3    33    31          2
##  4      4    22    24         -2
##  5      5    99    78         21
##  6      6    79    76          3
##  7      7     4    13         -9
##  8      8    36    46        -10
##  9      9    62    45         17
## 10     10    51    44          7
## 11     11    27    23          4
## 12     12    15    14          1
## 13     13    26    34         -8
## 14     14    83    79          4
## 15     15    86    81          5</code></pre>
<p>Extra: this is one of those cases where having long data would make it very much more difficult to work out the differences for each person. Try it and see. How will you match up the two measurements for each person?</p>
<p><span class="math inline">\(\blacksquare\)</span></p>
<ol start="3" style="list-style-type: lower-alpha">
<li>Make a suitable normal quantile plot, and describe what it tells you.</li>
</ol>
<p>Solution</p>
<p>A normal quantile plot <em>of the differences</em>, therefore, since normality of the two individual scores is immaterial:</p>
<div class="sourceCode" id="cb165"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb165-1" title="1"><span class="kw">ggplot</span>(sight, <span class="kw">aes</span>(<span class="dt">sample =</span> difference)) <span class="op">+</span><span class="st"> </span><span class="kw">stat_qq</span>() <span class="op">+</span></a>
<a class="sourceLine" id="cb165-2" title="2"><span class="kw">stat_qq_line</span>()</a></code></pre></div>
<p><img src="pasias_files/figure-html/unnamed-chunk-101-1.png" width="672" /></p>
<p>We have what I think is best described as “long tails”, with the high values being too high and the low ones being a bit too low for a normal distribution. I think this is a better description than “outliers” because outliers are isolated unusual values, not five observations out of fifteen!</p>
<p>The plot is telling us that a matched-pairs <span class="math inline">\(t\)</span>-test is questionable, and that we might do a sign test instead. Or, as we explore in this question, find a bootstrap distribution (in this case, for the median).</p>
<p>Extra: the one kind of sensible plot that uses the original data in this situation would be a scatterplot, since the right and left scores are matched up:</p>
<div class="sourceCode" id="cb166"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb166-1" title="1"><span class="kw">ggplot</span>(sight, <span class="kw">aes</span>(<span class="dt">x =</span> right, <span class="dt">y =</span> left)) <span class="op">+</span><span class="st"> </span></a>
<a class="sourceLine" id="cb166-2" title="2"><span class="kw">geom_point</span>() <span class="op">+</span><span class="st"> </span><span class="kw">geom_abline</span>(<span class="dt">slope =</span> <span class="dv">1</span>, <span class="dt">intercept =</span> <span class="dv">0</span>)</a></code></pre></div>
<p><img src="pasias_files/figure-html/unnamed-chunk-102-1.png" width="672" /></p>
<p>I added the line <span class="math inline">\(y = x\)</span> to the plot. The value of doing that is that a point to the right and below the line has the right-eye score bigger than the left-eye one, and vice versa for a point to the left and above. This plot tells us that a small majority of the subjects had a higher score with the right eye, and for the ones that had a higher score with the left eye, the difference wasn’t usually very big.</p>
<p>This plot tells us nothing about normality of differences, though (not without some careful looking), which is one of the things we usually care about.</p>
<p><span class="math inline">\(\blacksquare\)</span></p>
<ol start="4" style="list-style-type: lower-alpha">
<li>Obtain a bootstrap distribution of the sample <em>median</em>.</li>
</ol>
<p>Solution</p>
<p>Borrow the idea from lecture, replacing mean with median:</p>
<div class="sourceCode" id="cb167"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb167-1" title="1"><span class="kw">tibble</span>(<span class="dt">sim =</span> <span class="dv">1</span><span class="op">:</span><span class="dv">1000</span>) <span class="op">%&gt;%</span><span class="st"> </span></a>
<a class="sourceLine" id="cb167-2" title="2"><span class="kw">rowwise</span>() <span class="op">%&gt;%</span><span class="st"> </span></a>
<a class="sourceLine" id="cb167-3" title="3"><span class="kw">mutate</span>(<span class="dt">sample =</span> <span class="kw">list</span>(<span class="kw">sample</span>(sight<span class="op">$</span>difference, <span class="dt">replace =</span> <span class="ot">TRUE</span>))) <span class="op">%&gt;%</span><span class="st"> </span></a>
<a class="sourceLine" id="cb167-4" title="4"><span class="kw">mutate</span>(<span class="dt">my_median =</span> <span class="kw">median</span>(sample)) -&gt;<span class="st"> </span>meds</a>
<a class="sourceLine" id="cb167-5" title="5">meds</a></code></pre></div>
<pre><code>## # A tibble: 1,000 x 3
## # Rowwise: 
##      sim sample     my_median
##    &lt;int&gt; &lt;list&gt;         &lt;dbl&gt;
##  1     1 &lt;dbl [15]&gt;         3
##  2     2 &lt;dbl [15]&gt;         3
##  3     3 &lt;dbl [15]&gt;         2
##  4     4 &lt;dbl [15]&gt;         2
##  5     5 &lt;dbl [15]&gt;         3
##  6     6 &lt;dbl [15]&gt;         4
##  7     7 &lt;dbl [15]&gt;         3
##  8     8 &lt;dbl [15]&gt;         3
##  9     9 &lt;dbl [15]&gt;         3
## 10    10 &lt;dbl [15]&gt;         3
## # … with 990 more rows</code></pre>
<p>The steps are:</p>
<ul>
<li>create a dataframe with a column called <code>sim</code> to label the simulations</li>
<li>from here on out, work “rowwise”, that is, with one row at a time</li>
<li>generate a bootstrap sample for each row. A bootstrap sample is fifteen observations rather than just one, so we are making a list-column and thus the <code>list</code> has to go on the front</li>
<li>work out the median of each bootstrap sample. Remember, the <code>rowwise</code> applies until you cancel it,<a href="#fn17" class="footnote-ref" id="fnref17"><sup>17</sup></a> and so this will be the median of the bootstrap sample on each row, one at a time.</li>
</ul>
<p>As ever, if you want to see what’s going on, run this one line at a time.</p>
<p><span class="math inline">\(\blacksquare\)</span></p>
<ol start="5" style="list-style-type: lower-alpha">
<li>Make a histogram of your bootstrap distribution of the median. Use a lot of bins, such as the default 30, for this. What do you notice about the distribution? Why did it come out this way?</li>
</ol>
<p>Solution</p>
<p>For this histogram, there is no need to specify a number of bins (unless you want to):</p>
<div class="sourceCode" id="cb169"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb169-1" title="1"><span class="kw">ggplot</span>(meds, <span class="kw">aes</span>(<span class="dt">x =</span> my_median)) <span class="op">+</span><span class="st"> </span><span class="kw">geom_histogram</span>()</a></code></pre></div>
<pre><code>## `stat_bin()` using `bins = 30`. Pick better value with `binwidth`.</code></pre>
<p><img src="pasias_files/figure-html/unnamed-chunk-105-1.png" width="672" /></p>
<p>The distribution is very discrete (this shows up more clearly with more bins).</p>
<p>The data values are all integers (and therefore so are the differences). The median of an odd number of data values must be one of the data values, and the bootstrap samples only contain (varying numbers of copies of) the differences in the original dataset, so
each bootstrap sample must have a median that is an integer too.</p>
<p>Extra:
in case you are thinking that this happened because the data values were integers, no, it would happen even if the data were decimal numbers. Let’s make some fake data of 15 random normals and then do the same thing again:</p>
<div class="sourceCode" id="cb171"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb171-1" title="1">fake_data &lt;-<span class="st"> </span><span class="kw">tibble</span>(<span class="dt">x =</span> <span class="kw">rnorm</span>(<span class="dv">15</span>))</a>
<a class="sourceLine" id="cb171-2" title="2">fake_data</a></code></pre></div>
<pre><code>## # A tibble: 15 x 1
##           x
##       &lt;dbl&gt;
##  1 -2.02   
##  2  0.867  
##  3 -0.00982
##  4 -0.123  
##  5 -0.431  
##  6  0.702  
##  7  1.22   
##  8 -0.0818 
##  9  1.06   
## 10  0.318  
## 11 -0.0179 
## 12 -0.370  
## 13  0.0115 
## 14 -1.57   
## 15  0.0529</code></pre>
<p>and once again bootstrap the median:</p>
<div class="sourceCode" id="cb173"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb173-1" title="1"><span class="kw">tibble</span>(<span class="dt">sim =</span> <span class="dv">1</span><span class="op">:</span><span class="dv">1000</span>) <span class="op">%&gt;%</span><span class="st"> </span></a>
<a class="sourceLine" id="cb173-2" title="2"><span class="kw">rowwise</span>() <span class="op">%&gt;%</span><span class="st"> </span></a>
<a class="sourceLine" id="cb173-3" title="3"><span class="kw">mutate</span>(<span class="dt">sample =</span> <span class="kw">list</span>(<span class="kw">sample</span>(fake_data<span class="op">$</span>x, <span class="dt">replace =</span> <span class="ot">TRUE</span>))) <span class="op">%&gt;%</span><span class="st"> </span></a>
<a class="sourceLine" id="cb173-4" title="4"><span class="kw">mutate</span>(<span class="dt">my_median =</span> <span class="kw">median</span>(sample)) -&gt;<span class="st"> </span>meds2</a>
<a class="sourceLine" id="cb173-5" title="5">meds2</a></code></pre></div>
<pre><code>## # A tibble: 1,000 x 3
## # Rowwise: 
##      sim sample     my_median
##    &lt;int&gt; &lt;list&gt;         &lt;dbl&gt;
##  1     1 &lt;dbl [15]&gt;   0.0115 
##  2     2 &lt;dbl [15]&gt;   0.0115 
##  3     3 &lt;dbl [15]&gt;  -0.123  
##  4     4 &lt;dbl [15]&gt;  -0.0179 
##  5     5 &lt;dbl [15]&gt;   0.0115 
##  6     6 &lt;dbl [15]&gt;   0.318  
##  7     7 &lt;dbl [15]&gt;   0.0115 
##  8     8 &lt;dbl [15]&gt;  -0.00982
##  9     9 &lt;dbl [15]&gt;   0.0529 
## 10    10 &lt;dbl [15]&gt;   0.0115 
## # … with 990 more rows</code></pre>
<p>You can see even from these few that the bootstrap distribution of the median has repeats, so there should also be some discreteness here:</p>
<div class="sourceCode" id="cb175"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb175-1" title="1"><span class="kw">ggplot</span>(meds2, <span class="kw">aes</span>(<span class="dt">x =</span> my_median)) <span class="op">+</span><span class="st"> </span><span class="kw">geom_histogram</span>()</a></code></pre></div>
<pre><code>## `stat_bin()` using `bins = 30`. Pick better value with `binwidth`.</code></pre>
<p><img src="pasias_files/figure-html/unnamed-chunk-108-1.png" width="672" /></p>
<p>The discreteness is a property of the fact that we were bootstrapping the <em>median</em>, and the median has to be one of the data values.</p>
<p>To confirm that, recall that our original data were integers:</p>
<div class="sourceCode" id="cb177"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb177-1" title="1">sight</a></code></pre></div>
<pre><code>## # A tibble: 15 x 4
##    person right  left difference
##     &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt;      &lt;dbl&gt;
##  1      1    50    47          3
##  2      2    45    45          0
##  3      3    33    31          2
##  4      4    22    24         -2
##  5      5    99    78         21
##  6      6    79    76          3
##  7      7     4    13         -9
##  8      8    36    46        -10
##  9      9    62    45         17
## 10     10    51    44          7
## 11     11    27    23          4
## 12     12    15    14          1
## 13     13    26    34         -8
## 14     14    83    79          4
## 15     15    86    81          5</code></pre>
<p>but even for these, if you bootstrap the mean, you don’t get the same discreteness:</p>
<div class="sourceCode" id="cb179"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb179-1" title="1"><span class="kw">tibble</span>(<span class="dt">sim =</span> <span class="dv">1</span><span class="op">:</span><span class="dv">1000</span>) <span class="op">%&gt;%</span><span class="st"> </span></a>
<a class="sourceLine" id="cb179-2" title="2"><span class="kw">rowwise</span>() <span class="op">%&gt;%</span><span class="st"> </span></a>
<a class="sourceLine" id="cb179-3" title="3"><span class="kw">mutate</span>(<span class="dt">sample =</span> <span class="kw">list</span>(<span class="kw">sample</span>(sight<span class="op">$</span>difference, <span class="dt">replace =</span> <span class="ot">TRUE</span>))) <span class="op">%&gt;%</span><span class="st"> </span></a>
<a class="sourceLine" id="cb179-4" title="4"><span class="kw">mutate</span>(<span class="dt">my_mean =</span> <span class="kw">mean</span>(sample)) -&gt;<span class="st"> </span>means</a>
<a class="sourceLine" id="cb179-5" title="5">means <span class="op">%&gt;%</span><span class="st"> </span></a>
<a class="sourceLine" id="cb179-6" title="6"><span class="kw">ggplot</span>(<span class="kw">aes</span>(<span class="dt">x =</span> my_mean)) <span class="op">+</span><span class="st"> </span><span class="kw">geom_histogram</span>()</a></code></pre></div>
<pre><code>## `stat_bin()` using `bins = 30`. Pick better value with `binwidth`.</code></pre>
<p><img src="pasias_files/figure-html/unnamed-chunk-110-1.png" width="672" /></p>
<p>This is too many bins for 1000 bootstrap samples, so the shape is kind of irregular, but there are not the big gaps that the bootstrap distribution of the sample median has. Indeed, this ought to be somewhere near normal and is:</p>
<div class="sourceCode" id="cb181"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb181-1" title="1"><span class="kw">ggplot</span>(means, <span class="kw">aes</span>(<span class="dt">sample =</span> my_mean)) <span class="op">+</span><span class="st"> </span><span class="kw">stat_qq</span>() <span class="op">+</span></a>
<a class="sourceLine" id="cb181-2" title="2"><span class="kw">stat_qq_line</span>()</a></code></pre></div>
<p><img src="pasias_files/figure-html/unnamed-chunk-111-1.png" width="672" /></p>
<p>(This is saying that the Central Limit Theorem is really helping, even for a sample size of only 15 from clearly non-normal data, so the paired <span class="math inline">\(t\)</span> may not be as bad as we would have thought.)</p>
<p><span class="math inline">\(\blacksquare\)</span></p>
<ol start="6" style="list-style-type: lower-alpha">
<li>Find a 95% percentile interval for the population median.<a href="#fn18" class="footnote-ref" id="fnref18"><sup>18</sup></a></li>
</ol>
<p>Solution</p>
<p>The percentile interval comes from the middle 95% of the bootstrap distribution of medians:</p>
<div class="sourceCode" id="cb182"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb182-1" title="1"><span class="kw">quantile</span>(meds<span class="op">$</span>my_median, <span class="kw">c</span>(<span class="fl">0.025</span>, <span class="fl">0.975</span>))</a></code></pre></div>
<pre><code>##  2.5% 97.5% 
##    -2     4</code></pre>
<p>The bootstrap percentile interval goes from <span class="math inline">\(-2\)</span> to 4. Like the CI for the median based on the sign test, the ends of this interval must be data values.</p>
<p>Extra: for comparison, the interval from the sign test is this:</p>
<div class="sourceCode" id="cb184"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb184-1" title="1"><span class="kw">ci_median</span>(sight, difference)</a></code></pre></div>
<pre><code>## [1] -1.997070  4.994629</code></pre>
<p>which is, when rounded off, from <span class="math inline">\(-2\)</span> to 5, very like the percentile interval.</p>
<p><span class="math inline">\(\blacksquare\)</span></p>
<ol start="7" style="list-style-type: lower-alpha">
<li>Find the BCA 95% confidence interval for the population median difference.</li>
</ol>
<p>Solution</p>
<p>Load (and if necessary install) the <code>bootstrap</code> package, and then:</p>
<div class="sourceCode" id="cb186"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb186-1" title="1">bca &lt;-<span class="st"> </span><span class="kw">bcanon</span>(sight<span class="op">$</span>difference, <span class="dv">1000</span>, median)</a>
<a class="sourceLine" id="cb186-2" title="2">bca<span class="op">$</span>confpoints</a></code></pre></div>
<pre><code>##      alpha bca point
## [1,] 0.025        -2
## [2,] 0.050        -2
## [3,] 0.100         0
## [4,] 0.160         0
## [5,] 0.840         3
## [6,] 0.900         3
## [7,] 0.950         4
## [8,] 0.975         4</code></pre>
<p><span class="math inline">\(-2\)</span> to 4, in this case like the percentile interval.<a href="#fn19" class="footnote-ref" id="fnref19"><sup>19</sup></a> Note how this one is data values also.</p>
<p><span class="math inline">\(\blacksquare\)</span></p>
<ol start="8" style="list-style-type: lower-alpha">
<li>What do your intervals tell us about any possible difference between left eye and right eye in terms of ability to identify objects in images? Do the intervals agree or disagree about this?</li>
</ol>
<p>Solution</p>
<p>The intervals are not quite all the same, but one thing they have in common is that they all have a negative lower limit and a positive upper one (more positive than the negative one is negative). This says that 0 is a plausible difference in each case, and thus it is reasonable to conclude that there is no evidence of any difference between the two eyes, based on this sample of 15 subjects.</p>
<p>The intervals do all go more positive than negative, which says that if anything the scores are better with the right eye than the left on average (from the way around that we took the differences). However, there is no evidence here that this is any more than chance.</p>
<p><span class="math inline">\(\blacksquare\)</span></p>
</div>
<div id="bootstrapping-the-irs-data-1" class="section level2">
<h2><span class="header-section-number">22.8</span> Bootstrapping the IRS data</h2>
<p>You might recall the IRS data from when we were learning about the sign test. The idea was that we wanted to see how long “on average” it took people to fill out a tax form. The data are in <a href="http://ritsokiguess.site/datafiles/irs.txt">http://ritsokiguess.site/datafiles/irs.txt</a>.</p>
<ol style="list-style-type: lower-alpha">
<li>Read in and display (some of) the data. There is only one column of data, so you can pretend the values are separated by anything.</li>
</ol>
<p>Solution</p>
<p>Pretty much any of the <code>read_</code> functions will work, even this one:</p>
<div class="sourceCode" id="cb188"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb188-1" title="1">my_url &lt;-<span class="st"> &quot;http://ritsokiguess.site/datafiles/irs.txt&quot;</span></a>
<a class="sourceLine" id="cb188-2" title="2">irs &lt;-<span class="st"> </span><span class="kw">read_table</span>(my_url)</a></code></pre></div>
<pre><code>## 
## ── Column specification ──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
## cols(
##   Time = col_double()
## )</code></pre>
<div class="sourceCode" id="cb190"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb190-1" title="1">irs</a></code></pre></div>
<pre><code>## # A tibble: 30 x 1
##     Time
##    &lt;dbl&gt;
##  1    91
##  2    64
##  3   243
##  4   167
##  5   123
##  6    65
##  7    71
##  8   204
##  9   110
## 10   178
## # … with 20 more rows</code></pre>
<p>One column called <code>Time</code>.</p>
<p><span class="math inline">\(\blacksquare\)</span></p>
<ol start="2" style="list-style-type: lower-alpha">
<li>Obtain a bootstrap distribution of the sample <em>median</em>.</li>
</ol>
<p>Solution</p>
<p>The lecture notes use the exact same dataset, so you can borrow ideas from there:</p>
<p>Set up a dataframe with one row for each bootstrap sample you’re going to draw, 1000 in this case:</p>
<div class="sourceCode" id="cb192"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb192-1" title="1"><span class="kw">tibble</span>(<span class="dt">sim =</span> <span class="dv">1</span><span class="op">:</span><span class="dv">1000</span>)</a></code></pre></div>
<pre><code>## # A tibble: 1,000 x 1
##      sim
##    &lt;int&gt;
##  1     1
##  2     2
##  3     3
##  4     4
##  5     5
##  6     6
##  7     7
##  8     8
##  9     9
## 10    10
## # … with 990 more rows</code></pre>
<p>Create a column with a new bootstrap sample for each <code>sim</code>. This means doing <code>rowwise</code> <em>first</em> and then wrapping the sampling in <code>list</code> because you are creating a list-column of samples:</p>
<div class="sourceCode" id="cb194"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb194-1" title="1"><span class="kw">tibble</span>(<span class="dt">sim =</span> <span class="dv">1</span><span class="op">:</span><span class="dv">1000</span>) <span class="op">%&gt;%</span><span class="st"> </span></a>
<a class="sourceLine" id="cb194-2" title="2"><span class="kw">rowwise</span>() <span class="op">%&gt;%</span><span class="st"> </span></a>
<a class="sourceLine" id="cb194-3" title="3"><span class="kw">mutate</span>(<span class="dt">sample =</span> <span class="kw">list</span>(<span class="kw">sample</span>(irs<span class="op">$</span>Time, <span class="dt">replace =</span> <span class="ot">TRUE</span>)))</a></code></pre></div>
<pre><code>## # A tibble: 1,000 x 2
## # Rowwise: 
##      sim sample    
##    &lt;int&gt; &lt;list&gt;    
##  1     1 &lt;dbl [30]&gt;
##  2     2 &lt;dbl [30]&gt;
##  3     3 &lt;dbl [30]&gt;
##  4     4 &lt;dbl [30]&gt;
##  5     5 &lt;dbl [30]&gt;
##  6     6 &lt;dbl [30]&gt;
##  7     7 &lt;dbl [30]&gt;
##  8     8 &lt;dbl [30]&gt;
##  9     9 &lt;dbl [30]&gt;
## 10    10 &lt;dbl [30]&gt;
## # … with 990 more rows</code></pre>
<p>Each thing in <code>sample</code> has 30 observations in it (one bootstrap sample). If you want, you can <code>unnest</code> to take a look at the values; they should be the ones in the dataset, possibly with extra repeats.</p>
<p>Next, work out the median of each bootstrapped sample, which is simple because we are still working rowwise:</p>
<div class="sourceCode" id="cb196"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb196-1" title="1"><span class="kw">tibble</span>(<span class="dt">sim =</span> <span class="dv">1</span><span class="op">:</span><span class="dv">1000</span>) <span class="op">%&gt;%</span><span class="st"> </span></a>
<a class="sourceLine" id="cb196-2" title="2"><span class="kw">rowwise</span>() <span class="op">%&gt;%</span><span class="st"> </span></a>
<a class="sourceLine" id="cb196-3" title="3"><span class="kw">mutate</span>(<span class="dt">sample =</span> <span class="kw">list</span>(<span class="kw">sample</span>(irs<span class="op">$</span>Time, <span class="dt">replace =</span> <span class="ot">TRUE</span>))) <span class="op">%&gt;%</span><span class="st"> </span></a>
<a class="sourceLine" id="cb196-4" title="4"><span class="kw">mutate</span>(<span class="dt">my_median =</span> <span class="kw">median</span>(sample)) -&gt;<span class="st"> </span>bs</a>
<a class="sourceLine" id="cb196-5" title="5">bs</a></code></pre></div>
<pre><code>## # A tibble: 1,000 x 3
## # Rowwise: 
##      sim sample     my_median
##    &lt;int&gt; &lt;list&gt;         &lt;dbl&gt;
##  1     1 &lt;dbl [30]&gt;      209 
##  2     2 &lt;dbl [30]&gt;      162 
##  3     3 &lt;dbl [30]&gt;      172.
##  4     4 &lt;dbl [30]&gt;      186 
##  5     5 &lt;dbl [30]&gt;      206.
##  6     6 &lt;dbl [30]&gt;      196 
##  7     7 &lt;dbl [30]&gt;      136.
##  8     8 &lt;dbl [30]&gt;      154.
##  9     9 &lt;dbl [30]&gt;      194 
## 10    10 &lt;dbl [30]&gt;      194 
## # … with 990 more rows</code></pre>
<p>As you realize, <code>bs</code> stands for “bootstrap”. Of course.</p>
<p><span class="math inline">\(\blacksquare\)</span></p>
<ol start="3" style="list-style-type: lower-alpha">
<li>Make a suitable graph of the bootstrap distribution of the median. What seems odd about it? Why did that happen? (Hint: use more bins on your plot than usual, like 50.)</li>
</ol>
<p>Solution</p>
<p>The medians are already in a dataframe, so go straight ahead:</p>
<div class="sourceCode" id="cb198"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb198-1" title="1"><span class="kw">ggplot</span>(bs, <span class="kw">aes</span>(<span class="dt">x =</span> my_median)) <span class="op">+</span><span class="st"> </span><span class="kw">geom_histogram</span>(<span class="dt">bins =</span> <span class="dv">50</span>)</a></code></pre></div>
<p><img src="pasias_files/figure-html/unnamed-chunk-119-1.png" width="672" /></p>
<p>What we are seeing at this resolution is that the distribution is <em>very</em> irregular, with funny holes in it, more than you would expect even with this many bins. By way of comparison, the bootstrap distribution of the <em>mean</em> looks a lot smoother:</p>
<div class="sourceCode" id="cb199"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb199-1" title="1"><span class="kw">tibble</span>(<span class="dt">sim =</span> <span class="dv">1</span><span class="op">:</span><span class="dv">1000</span>) <span class="op">%&gt;%</span><span class="st"> </span></a>
<a class="sourceLine" id="cb199-2" title="2"><span class="st">  </span><span class="kw">rowwise</span>() <span class="op">%&gt;%</span><span class="st"> </span></a>
<a class="sourceLine" id="cb199-3" title="3"><span class="st">  </span><span class="kw">mutate</span>(<span class="dt">my_sample =</span> <span class="kw">list</span>(<span class="kw">sample</span>(irs<span class="op">$</span>Time, <span class="dt">replace =</span> <span class="ot">TRUE</span>))) <span class="op">%&gt;%</span><span class="st"> </span></a>
<a class="sourceLine" id="cb199-4" title="4"><span class="st">  </span><span class="kw">mutate</span>(<span class="dt">my_mean =</span> <span class="kw">mean</span>(my_sample)) <span class="op">%&gt;%</span><span class="st"> </span></a>
<a class="sourceLine" id="cb199-5" title="5"><span class="st">  </span><span class="kw">ggplot</span>(<span class="kw">aes</span>(<span class="dt">x =</span> my_mean)) <span class="op">+</span><span class="st"> </span><span class="kw">geom_histogram</span>(<span class="dt">bins =</span> <span class="dv">50</span>)</a></code></pre></div>
<p><img src="pasias_files/figure-html/unnamed-chunk-120-1.png" width="672" />
This is somewhat irregular, because we really have too many bins, but there are not nearly so many holes and irregular heights as on the plot for the median. I had you use a lot of bins in this special case because I wanted you to see just how irregular the bootstrapped distribution for the median really was.</p>
<p>So why did that happen? Think about what the sample median is for 30 observations: it is the mean of the 15th and 16th smallest values when you arrange them in order. A bootstrap sample must contain the same values as the original dataset (just probably not the same frequencies of them). So the median of a bootstrap sample must be the average of two of the values in the original dataset, and probably two that were close together. What that means is that there are <em>not very many possible medians</em> of the bootstrap samples, and they form a clearly discrete rather than a continuous distribution. (The sample mean, on the other hand, uses all the values in the bootstrap sample, and so there are a lot more possible bootstrap means than bootstrap medians; the distribution of those is as good as continuous.)</p>
<p>What this means is that bootstrapping for medians is odd (it always looks like this), but that’s what the bootstrap distribution looks like.</p>
<p><span class="math inline">\(\blacksquare\)</span></p>
<ol start="4" style="list-style-type: lower-alpha">
<li>Find 95% percentile and bootstrap-<span class="math inline">\(t\)</span> intervals for the population median. (Hint: your dataframe of bootstrapped medians may still be <code>rowwise</code>, so you might need to run <code>ungroup</code> first.)</li>
</ol>
<p>Solution</p>
<p>The percentile interval comes from the middle 95% of the bootstrap distribution of medians. The dataframe <code>bs</code> is still rowwise, so we have to undo that first to do it the obvious way:</p>
<div class="sourceCode" id="cb200"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb200-1" title="1">bs <span class="op">%&gt;%</span><span class="st"> </span></a>
<a class="sourceLine" id="cb200-2" title="2"><span class="st">  </span><span class="kw">ungroup</span>() <span class="op">%&gt;%</span><span class="st"> </span></a>
<a class="sourceLine" id="cb200-3" title="3"><span class="st">  </span><span class="kw">summarize</span>(<span class="dt">ci1 =</span> <span class="kw">quantile</span>(my_median, <span class="fl">0.025</span>),</a>
<a class="sourceLine" id="cb200-4" title="4">            <span class="dt">ci2 =</span> <span class="kw">quantile</span>(my_median, <span class="fl">0.975</span>))</a></code></pre></div>
<pre><code>## # A tibble: 1 x 2
##     ci1   ci2
##   &lt;dbl&gt; &lt;dbl&gt;
## 1  123.   215</code></pre>
<p>Or, pull out just that column and find the two quantiles of that, for which there are two ways, the base R way:</p>
<div class="sourceCode" id="cb202"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb202-1" title="1"><span class="kw">quantile</span>(bs<span class="op">$</span>my_median, <span class="kw">c</span>(<span class="fl">0.025</span>, <span class="fl">0.975</span>))</a></code></pre></div>
<pre><code>##   2.5%  97.5% 
## 122.95 215.00</code></pre>
<p>and the slightly odd-looking:</p>
<div class="sourceCode" id="cb204"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb204-1" title="1">bs <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">pull</span>(my_median) <span class="op">%&gt;%</span><span class="st"> </span></a>
<a class="sourceLine" id="cb204-2" title="2"><span class="st">  </span><span class="kw">quantile</span>(<span class="kw">c</span>(<span class="fl">0.025</span>, <span class="fl">0.975</span>))</a></code></pre></div>
<pre><code>##   2.5%  97.5% 
## 122.95 215.00</code></pre>
<p>All of these get you to the same place. There is even one more:</p>
<div class="sourceCode" id="cb206"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb206-1" title="1">bs <span class="op">%&gt;%</span><span class="st"> </span></a>
<a class="sourceLine" id="cb206-2" title="2"><span class="st">  </span><span class="kw">ungroup</span>() <span class="op">%&gt;%</span><span class="st"> </span></a>
<a class="sourceLine" id="cb206-3" title="3"><span class="st">  </span><span class="kw">summarize</span>(<span class="dt">ci =</span> <span class="kw">quantile</span>(my_median, <span class="kw">c</span>(<span class="fl">0.025</span>, <span class="fl">0.975</span>)))</a></code></pre></div>
<pre><code>## # A tibble: 2 x 1
##      ci
##   &lt;dbl&gt;
## 1  123.
## 2  215</code></pre>
<p>This takes advantage of a (newish) behaviour of <code>summarize</code>: if your summary is more than one thing, it puts one of the summaries on each row, as if you had done something like this:</p>
<div class="sourceCode" id="cb208"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb208-1" title="1">bs <span class="op">%&gt;%</span><span class="st"> </span></a>
<a class="sourceLine" id="cb208-2" title="2"><span class="st">  </span><span class="kw">ungroup</span>() <span class="op">%&gt;%</span><span class="st"> </span></a>
<a class="sourceLine" id="cb208-3" title="3"><span class="st">  </span><span class="kw">summarize</span>(<span class="dt">ci =</span> <span class="kw">list</span>(<span class="kw">quantile</span>(my_median, <span class="kw">c</span>(<span class="fl">0.025</span>, <span class="fl">0.975</span>)))) <span class="op">%&gt;%</span><span class="st"> </span></a>
<a class="sourceLine" id="cb208-4" title="4"><span class="st">  </span><span class="kw">unnest</span>(ci)  </a></code></pre></div>
<pre><code>## # A tibble: 2 x 1
##      ci
##   &lt;dbl&gt;
## 1  123.
## 2  215</code></pre>
<p>If you had <code>rowwise</code> in the back of your mind, you might have tried this. Try it up to but <em>not</em> including the <code>unnest</code> to see how it works.</p>
<p>For the bootstrap <span class="math inline">\(t\)</span>, estimate the population median as the sample median:</p>
<div class="sourceCode" id="cb210"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb210-1" title="1">med &lt;-<span class="st"> </span><span class="kw">median</span>(irs<span class="op">$</span>Time)</a>
<a class="sourceLine" id="cb210-2" title="2">med</a></code></pre></div>
<pre><code>## [1] 172.5</code></pre>
<p>get its standard error from the SD of the bootstrap distribution of medians:</p>
<div class="sourceCode" id="cb212"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb212-1" title="1">se &lt;-<span class="st"> </span><span class="kw">sd</span>(bs<span class="op">$</span>my_median)</a>
<a class="sourceLine" id="cb212-2" title="2">se</a></code></pre></div>
<pre><code>## [1] 24.04391</code></pre>
<p>then go up and down twice this (or 1.96 if you believe in <span class="math inline">\(z\)</span>):</p>
<div class="sourceCode" id="cb214"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb214-1" title="1">med <span class="op">+</span><span class="st"> </span><span class="kw">c</span>(<span class="op">-</span><span class="dv">2</span>, <span class="dv">2</span>)<span class="op">*</span>se</a></code></pre></div>
<pre><code>## [1] 124.4122 220.5878</code></pre>
<p>Extra: in this case, we also have the CI for the median that came out of the sign test:</p>
<div class="sourceCode" id="cb216"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb216-1" title="1"><span class="kw">library</span>(smmr)</a>
<a class="sourceLine" id="cb216-2" title="2"><span class="kw">ci_median</span>(irs, Time)</a></code></pre></div>
<pre><code>## [1] 119.0065 214.9955</code></pre>
<p>This one is actually very close to the bootstrap percentile interval, while the bootstrap <span class="math inline">\(t\)</span> interval is higher at both ends.</p>
<p><span class="math inline">\(\blacksquare\)</span></p>

</div>
</div>
<div class="footnotes">
<hr />
<ol start="16">
<li id="fn16"><p>I was also going to have you do a bootstrap-t interval, but I’m not completely convinced I got that right when I was explaining it to you before.<a href="the-bootstrap.html#fnref16" class="footnote-back">↩</a></p></li>
<li id="fn17"><p>That is done using ungroup, should you ever need to stop working rowwise. This seems like an odd choice of function, since the usual use of ungroup is to undo a group-by, but what ungroup actually does is to remove any special properties a dataframe has, including both groups and any rowwise behaviour.<a href="the-bootstrap.html#fnref17" class="footnote-back">↩</a></p></li>
<li id="fn18"><p>I was also going to have you do a bootstrap-t interval, but I’m not completely convinced I got that right when I was explaining it to you before.<a href="the-bootstrap.html#fnref18" class="footnote-back">↩</a></p></li>
<li id="fn19"><p>They don’t often agree this well, but all of these intervals in this situation but have data values at their endpoints, and all of our data values are integers.<a href="the-bootstrap.html#fnref19" class="footnote-back">↩</a></p></li>
</ol>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="vector-and-matrix-algebra.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="bayesian-statistics-with-stan.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/lunr.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": null,
"text": null
},
"history": {
"link": null,
"text": null
},
"view": {
"link": null,
"text": null
},
"download": ["pasias.pdf"],
"toc": {
"collapse": "subsection"
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
