<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>Chapter 9 The sign test | Problems and Solutions in Applied Statistics</title>
  <meta name="description" content="A set of problems and solutions, in R, on various parts of applied statistics" />
  <meta name="generator" content="bookdown 0.21 and GitBook 2.6.7" />

  <meta property="og:title" content="Chapter 9 The sign test | Problems and Solutions in Applied Statistics" />
  <meta property="og:type" content="book" />
  <meta property="og:url" content="http://ritsokiguess.site/pasias" />
  
  <meta property="og:description" content="A set of problems and solutions, in R, on various parts of applied statistics" />
  <meta name="github-repo" content="nxskok/pasias" />

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Chapter 9 The sign test | Problems and Solutions in Applied Statistics" />
  
  <meta name="twitter:description" content="A set of problems and solutions, in R, on various parts of applied statistics" />
  

<meta name="author" content="Ken Butler" />


<meta name="date" content="2021-06-04" />

  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="power-and-sample-size.html"/>
<link rel="next" href="mood-median-test.html"/>
<script src="libs/jquery-2.2.3/jquery.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />











<style type="text/css">
a.sourceLine { display: inline-block; line-height: 1.25; }
a.sourceLine { pointer-events: none; color: inherit; text-decoration: inherit; }
a.sourceLine:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode { white-space: pre; position: relative; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
code.sourceCode { white-space: pre-wrap; }
a.sourceLine { text-indent: -1em; padding-left: 1em; }
}
pre.numberSource a.sourceLine
  { position: relative; left: -4em; }
pre.numberSource a.sourceLine::before
  { content: attr(title);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; pointer-events: all; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {  }
@media screen {
a.sourceLine::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">Problems and Solutions in Applied Statistics</a></li>

<li class="divider"></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i>Introduction</a><ul>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#packages-used-somewhere-in-this-book"><i class="fa fa-check"></i>Packages used somewhere in this book</a></li>
</ul></li>
<li class="chapter" data-level="1" data-path="getting-used-to-r-and-r-studio.html"><a href="getting-used-to-r-and-r-studio.html"><i class="fa fa-check"></i><b>1</b> Getting used to R and R Studio</a><ul>
<li class="chapter" data-level="1.1" data-path="getting-used-to-r-and-r-studio.html"><a href="getting-used-to-r-and-r-studio.html#running-r-studio-on-jupyterhub"><i class="fa fa-check"></i><b>1.1</b> Running R Studio on Jupyterhub</a></li>
<li class="chapter" data-level="1.2" data-path="getting-used-to-r-and-r-studio.html"><a href="getting-used-to-r-and-r-studio.html#getting-an-r-studio-cloud-account"><i class="fa fa-check"></i><b>1.2</b> Getting an R Studio Cloud account</a></li>
<li class="chapter" data-level="1.3" data-path="getting-used-to-r-and-r-studio.html"><a href="getting-used-to-r-and-r-studio.html#getting-started"><i class="fa fa-check"></i><b>1.3</b> Getting started</a></li>
<li class="chapter" data-level="1.4" data-path="getting-used-to-r-and-r-studio.html"><a href="getting-used-to-r-and-r-studio.html#reading-data-from-a-file"><i class="fa fa-check"></i><b>1.4</b> Reading data from a file</a></li>
<li class="chapter" data-level="1.5" data-path="getting-used-to-r-and-r-studio.html"><a href="getting-used-to-r-and-r-studio.html#reading-files-different-ways"><i class="fa fa-check"></i><b>1.5</b> Reading files different ways</a></li>
</ul></li>
<li class="chapter" data-level="2" data-path="reading-in-data.html"><a href="reading-in-data.html"><i class="fa fa-check"></i><b>2</b> Reading in data</a></li>
<li class="chapter" data-level="3" data-path="drawing-graphs.html"><a href="drawing-graphs.html"><i class="fa fa-check"></i><b>3</b> Drawing graphs</a></li>
<li class="chapter" data-level="4" data-path="data-exploration.html"><a href="data-exploration.html"><i class="fa fa-check"></i><b>4</b> Data exploration</a></li>
<li class="chapter" data-level="5" data-path="working-with-dataframes.html"><a href="working-with-dataframes.html"><i class="fa fa-check"></i><b>5</b> Working with dataframes</a></li>
<li class="chapter" data-level="6" data-path="one-sample-inference.html"><a href="one-sample-inference.html"><i class="fa fa-check"></i><b>6</b> One-sample inference</a></li>
<li class="chapter" data-level="7" data-path="two-sample-inference.html"><a href="two-sample-inference.html"><i class="fa fa-check"></i><b>7</b> Two-sample inference</a></li>
<li class="chapter" data-level="8" data-path="power-and-sample-size.html"><a href="power-and-sample-size.html"><i class="fa fa-check"></i><b>8</b> Power and sample size</a></li>
<li class="chapter" data-level="9" data-path="the-sign-test.html"><a href="the-sign-test.html"><i class="fa fa-check"></i><b>9</b> The sign test</a><ul>
<li class="chapter" data-level="9.1" data-path="the-sign-test.html"><a href="the-sign-test.html#running-a-maze"><i class="fa fa-check"></i><b>9.1</b> Running a maze</a></li>
<li class="chapter" data-level="9.2" data-path="the-sign-test.html"><a href="the-sign-test.html#chocolate-chips"><i class="fa fa-check"></i><b>9.2</b> Chocolate chips</a></li>
<li class="chapter" data-level="9.3" data-path="the-sign-test.html"><a href="the-sign-test.html#the-power-of-the-sign-test"><i class="fa fa-check"></i><b>9.3</b> The power of the sign test</a></li>
<li class="chapter" data-level="9.4" data-path="the-sign-test.html"><a href="the-sign-test.html#ben-roethlisberger"><i class="fa fa-check"></i><b>9.4</b> Ben Roethlisberger</a></li>
<li class="chapter" data-level="9.5" data-path="the-sign-test.html"><a href="the-sign-test.html#six-ounces-of-protein"><i class="fa fa-check"></i><b>9.5</b> Six ounces of protein</a></li>
<li class="chapter" data-level="9.6" data-path="the-sign-test.html"><a href="the-sign-test.html#running-a-maze-1"><i class="fa fa-check"></i><b>9.6</b> Running a maze</a></li>
<li class="chapter" data-level="9.7" data-path="the-sign-test.html"><a href="the-sign-test.html#chocolate-chips-1"><i class="fa fa-check"></i><b>9.7</b> Chocolate chips</a></li>
<li class="chapter" data-level="9.8" data-path="the-sign-test.html"><a href="the-sign-test.html#the-power-of-the-sign-test-1"><i class="fa fa-check"></i><b>9.8</b> The power of the sign test</a></li>
<li class="chapter" data-level="9.9" data-path="the-sign-test.html"><a href="the-sign-test.html#ben-roethlisberger-1"><i class="fa fa-check"></i><b>9.9</b> Ben Roethlisberger</a></li>
<li class="chapter" data-level="9.10" data-path="the-sign-test.html"><a href="the-sign-test.html#six-ounces-of-protein-1"><i class="fa fa-check"></i><b>9.10</b> Six ounces of protein</a></li>
</ul></li>
<li class="chapter" data-level="10" data-path="mood-median-test.html"><a href="mood-median-test.html"><i class="fa fa-check"></i><b>10</b> Mood median test</a></li>
<li class="chapter" data-level="11" data-path="matched-pairs-t-and-sign-test.html"><a href="matched-pairs-t-and-sign-test.html"><i class="fa fa-check"></i><b>11</b> Matched pairs t and sign test</a></li>
<li class="chapter" data-level="12" data-path="normal-quantile-plots.html"><a href="normal-quantile-plots.html"><i class="fa fa-check"></i><b>12</b> Normal quantile plots</a><ul>
<li class="chapter" data-level="12.1" data-path="normal-quantile-plots.html"><a href="normal-quantile-plots.html#lengths-of-heliconia-flowers"><i class="fa fa-check"></i><b>12.1</b> Lengths of heliconia flowers</a></li>
<li class="chapter" data-level="12.2" data-path="normal-quantile-plots.html"><a href="normal-quantile-plots.html#ferritin-and-normality"><i class="fa fa-check"></i><b>12.2</b> Ferritin and normality</a></li>
<li class="chapter" data-level="12.3" data-path="normal-quantile-plots.html"><a href="normal-quantile-plots.html#lengths-of-heliconia-flowers-1"><i class="fa fa-check"></i><b>12.3</b> Lengths of heliconia flowers</a></li>
<li class="chapter" data-level="12.4" data-path="normal-quantile-plots.html"><a href="normal-quantile-plots.html#ferritin-and-normality-1"><i class="fa fa-check"></i><b>12.4</b> Ferritin and normality</a></li>
</ul></li>
<li class="chapter" data-level="13" data-path="analysis-of-variance.html"><a href="analysis-of-variance.html"><i class="fa fa-check"></i><b>13</b> Analysis of variance</a></li>
<li class="chapter" data-level="14" data-path="writing-reports.html"><a href="writing-reports.html"><i class="fa fa-check"></i><b>14</b> Writing reports</a></li>
<li class="chapter" data-level="15" data-path="learning-to-code.html"><a href="learning-to-code.html"><i class="fa fa-check"></i><b>15</b> Learning to code</a><ul>
<li class="chapter" data-level="15.1" data-path="learning-to-code.html"><a href="learning-to-code.html#introduction-1"><i class="fa fa-check"></i><b>15.1</b> Introduction</a></li>
<li class="chapter" data-level="15.2" data-path="learning-to-code.html"><a href="learning-to-code.html#data-and-pre-processing"><i class="fa fa-check"></i><b>15.2</b> Data and pre-processing</a></li>
<li class="chapter" data-level="15.3" data-path="learning-to-code.html"><a href="learning-to-code.html#analysis"><i class="fa fa-check"></i><b>15.3</b> Analysis</a></li>
<li class="chapter" data-level="15.4" data-path="learning-to-code.html"><a href="learning-to-code.html#conclusions-see-note-9"><i class="fa fa-check"></i><b>15.4</b> Conclusions (see note 9)</a></li>
</ul></li>
<li class="chapter" data-level="16" data-path="treating-dandruff.html"><a href="treating-dandruff.html"><i class="fa fa-check"></i><b>16</b> Treating dandruff</a><ul>
<li class="chapter" data-level="16.1" data-path="treating-dandruff.html"><a href="treating-dandruff.html#introduction-2"><i class="fa fa-check"></i><b>16.1</b> Introduction</a></li>
<li class="chapter" data-level="16.2" data-path="treating-dandruff.html"><a href="treating-dandruff.html#exploratory-analysis"><i class="fa fa-check"></i><b>16.2</b> Exploratory analysis</a></li>
<li class="chapter" data-level="16.3" data-path="treating-dandruff.html"><a href="treating-dandruff.html#analysis-of-variance-1"><i class="fa fa-check"></i><b>16.3</b> Analysis of Variance</a></li>
<li class="chapter" data-level="16.4" data-path="treating-dandruff.html"><a href="treating-dandruff.html#assessment-of-assumptions"><i class="fa fa-check"></i><b>16.4</b> Assessment of Assumptions</a></li>
<li class="chapter" data-level="16.5" data-path="treating-dandruff.html"><a href="treating-dandruff.html#conclusions"><i class="fa fa-check"></i><b>16.5</b> Conclusions</a></li>
<li class="chapter" data-level="16.6" data-path="treating-dandruff.html"><a href="treating-dandruff.html#end"><i class="fa fa-check"></i><b>16.6</b> End</a></li>
</ul></li>
<li class="chapter" data-level="17" data-path="tidying-data.html"><a href="tidying-data.html"><i class="fa fa-check"></i><b>17</b> Tidying data</a></li>
<li class="chapter" data-level="18" data-path="simple-regression.html"><a href="simple-regression.html"><i class="fa fa-check"></i><b>18</b> Simple regression</a></li>
<li class="chapter" data-level="19" data-path="multiple-regression.html"><a href="multiple-regression.html"><i class="fa fa-check"></i><b>19</b> Multiple regression</a></li>
<li class="chapter" data-level="20" data-path="regression-with-categorical-variables.html"><a href="regression-with-categorical-variables.html"><i class="fa fa-check"></i><b>20</b> Regression with categorical variables</a><ul>
<li class="chapter" data-level="20.1" data-path="regression-with-categorical-variables.html"><a href="regression-with-categorical-variables.html#crickets-revisited"><i class="fa fa-check"></i><b>20.1</b> Crickets revisited</a></li>
<li class="chapter" data-level="20.2" data-path="regression-with-categorical-variables.html"><a href="regression-with-categorical-variables.html#pulse-rates-and-marching"><i class="fa fa-check"></i><b>20.2</b> Pulse rates and marching</a></li>
<li class="chapter" data-level="20.3" data-path="regression-with-categorical-variables.html"><a href="regression-with-categorical-variables.html#crickets-revisited-1"><i class="fa fa-check"></i><b>20.3</b> Crickets revisited</a></li>
<li class="chapter" data-level="20.4" data-path="regression-with-categorical-variables.html"><a href="regression-with-categorical-variables.html#pulse-rates-and-marching-1"><i class="fa fa-check"></i><b>20.4</b> Pulse rates and marching</a></li>
</ul></li>
<li class="chapter" data-level="21" data-path="dates-and-times.html"><a href="dates-and-times.html"><i class="fa fa-check"></i><b>21</b> Dates and times</a></li>
<li class="chapter" data-level="22" data-path="functions.html"><a href="functions.html"><i class="fa fa-check"></i><b>22</b> Functions</a></li>
<li class="chapter" data-level="23" data-path="vector-and-matrix-algebra.html"><a href="vector-and-matrix-algebra.html"><i class="fa fa-check"></i><b>23</b> Vector and matrix algebra</a><ul>
<li class="chapter" data-level="23.1" data-path="vector-and-matrix-algebra.html"><a href="vector-and-matrix-algebra.html#heights-and-foot-lengths-again"><i class="fa fa-check"></i><b>23.1</b> Heights and foot lengths again</a></li>
<li class="chapter" data-level="23.2" data-path="vector-and-matrix-algebra.html"><a href="vector-and-matrix-algebra.html#heights-and-foot-lengths-again-1"><i class="fa fa-check"></i><b>23.2</b> Heights and foot lengths again</a></li>
</ul></li>
<li class="chapter" data-level="24" data-path="the-bootstrap.html"><a href="the-bootstrap.html"><i class="fa fa-check"></i><b>24</b> The Bootstrap</a></li>
<li class="chapter" data-level="25" data-path="bayesian-statistics-with-stan.html"><a href="bayesian-statistics-with-stan.html"><i class="fa fa-check"></i><b>25</b> Bayesian Statistics with Stan</a></li>
<li class="chapter" data-level="26" data-path="logistic-regression.html"><a href="logistic-regression.html"><i class="fa fa-check"></i><b>26</b> Logistic regression</a></li>
<li class="chapter" data-level="27" data-path="logistic-regression-with-ordinal-response.html"><a href="logistic-regression-with-ordinal-response.html"><i class="fa fa-check"></i><b>27</b> Logistic regression with ordinal response</a></li>
<li class="chapter" data-level="28" data-path="logistic-regression-with-nominal-response.html"><a href="logistic-regression-with-nominal-response.html"><i class="fa fa-check"></i><b>28</b> Logistic regression with nominal response</a></li>
<li class="chapter" data-level="29" data-path="survival-analysis.html"><a href="survival-analysis.html"><i class="fa fa-check"></i><b>29</b> Survival analysis</a></li>
<li class="chapter" data-level="30" data-path="analysis-of-variance-revisited.html"><a href="analysis-of-variance-revisited.html"><i class="fa fa-check"></i><b>30</b> Analysis of variance revisited</a></li>
<li class="chapter" data-level="31" data-path="analysis-of-covariance.html"><a href="analysis-of-covariance.html"><i class="fa fa-check"></i><b>31</b> Analysis of covariance</a></li>
<li class="chapter" data-level="32" data-path="multivariate-analysis-of-variance.html"><a href="multivariate-analysis-of-variance.html"><i class="fa fa-check"></i><b>32</b> Multivariate analysis of variance</a></li>
<li class="chapter" data-level="33" data-path="repeated-measures.html"><a href="repeated-measures.html"><i class="fa fa-check"></i><b>33</b> Repeated measures</a></li>
<li class="chapter" data-level="34" data-path="discriminant-analysis.html"><a href="discriminant-analysis.html"><i class="fa fa-check"></i><b>34</b> Discriminant analysis</a></li>
<li class="chapter" data-level="35" data-path="hierarchical-cluster-analysis.html"><a href="hierarchical-cluster-analysis.html"><i class="fa fa-check"></i><b>35</b> Hierarchical cluster analysis</a></li>
<li class="chapter" data-level="36" data-path="k-means-cluster-analysis.html"><a href="k-means-cluster-analysis.html"><i class="fa fa-check"></i><b>36</b> K-means cluster analysis</a></li>
<li class="chapter" data-level="37" data-path="drawing-maps-with-leaflet.html"><a href="drawing-maps-with-leaflet.html"><i class="fa fa-check"></i><b>37</b> Drawing maps with Leaflet</a></li>
<li class="chapter" data-level="38" data-path="multidimensional-scaling.html"><a href="multidimensional-scaling.html"><i class="fa fa-check"></i><b>38</b> Multidimensional Scaling</a></li>
<li class="chapter" data-level="39" data-path="principal-components.html"><a href="principal-components.html"><i class="fa fa-check"></i><b>39</b> Principal Components</a><ul>
<li class="chapter" data-level="39.1" data-path="principal-components.html"><a href="principal-components.html#the-weather-somewhere"><i class="fa fa-check"></i><b>39.1</b> The weather, somewhere</a></li>
<li class="chapter" data-level="39.2" data-path="principal-components.html"><a href="principal-components.html#the-weather-somewhere-1"><i class="fa fa-check"></i><b>39.2</b> The weather, somewhere</a></li>
</ul></li>
<li class="chapter" data-level="40" data-path="factor-analysis.html"><a href="factor-analysis.html"><i class="fa fa-check"></i><b>40</b> Factor Analysis</a></li>
<li class="chapter" data-level="41" data-path="frequency-table-analysis.html"><a href="frequency-table-analysis.html"><i class="fa fa-check"></i><b>41</b> Frequency table analysis</a></li>
<li class="divider"></li>
<li><a href="https://github.com/rstudio/bookdown" target="blank">Published with bookdown</a></li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Problems and Solutions in Applied Statistics</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="the-sign-test" class="section level1">
<h1><span class="header-section-number">Chapter 9</span> The sign test</h1>
<div class="sourceCode" id="cb43"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb43-1" title="1"><span class="kw">library</span>(tidyverse)</a>
<a class="sourceLine" id="cb43-2" title="2"><span class="kw">library</span>(smmr)</a></code></pre></div>
<div id="running-a-maze" class="section level2">
<h2><span class="header-section-number">9.1</span> Running a maze</h2>
<p>A researcher is trying to design a maze that can be run by
rats in about 60 seconds. One particular maze was run by a sample of
21 rats, with the times shown in
<a href="http://ritsokiguess.site/datafiles/maze.txt">link</a>.</p>
<ol style="list-style-type: lower-alpha">
<li><p>Read the data into R. What (if anything) are the data values
delimited by?</p></li>
<li><p>Run a sign test, doing it yourself as we did in class:
count the number of values above and below 60, take the <em>smaller</em>
of those, and find the probability of a value of that or smaller still
on a binomial distribution with <span class="math inline">\(n=21\)</span> and <span class="math inline">\(p=0.5\)</span> (we have 21 data
points), doubling the answer because the test is two-sided.</p></li>
<li><p>Install my package <code>smmr</code>, if you haven’t already. To do
this, you first need to install the package <code>devtools</code> (if you
haven’t already),
by going to the console and typing</p></li>
</ol>
<div class="sourceCode" id="cb44"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb44-1" title="1"><span class="kw">install.packages</span>(<span class="st">&quot;devtools&quot;</span>)</a></code></pre></div>
<p>When that’s all done, install <code>smmr</code> thus:</p>
<div class="sourceCode" id="cb45"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb45-1" title="1"><span class="kw">library</span>(devtools)</a>
<a class="sourceLine" id="cb45-2" title="2"><span class="kw">install_github</span>(<span class="st">&quot;nxskok/smmr&quot;</span>)</a></code></pre></div>
<p>That all needs to be done only once. Then, each R Studio session where
you want to use <code>smmr</code> needs this:</p>
<div class="sourceCode" id="cb46"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb46-1" title="1"><span class="kw">library</span>(smmr)</a></code></pre></div>
<p>As usual, only the <code>library</code> thing only needs to be done every
time.</p>
<p>When you have <code>smmr</code> installed, use <code>sign_test</code> from
that package to re-run your sign test. Do you get the same P-value?</p>
<ol start="4" style="list-style-type: lower-alpha">
<li><p>Package <code>smmr</code> also has a function
<code>pval_sign</code>, which has the same input as
<code>sign_test</code>, but with the null median <em>first</em>.
Run it on your data and see what it gives.</p></li>
<li><p>Obtain a 95% confidence interval for the median based on these
data. Do this two ways. First, use the trial and error way from class
(either the try-lots-of-values way or the bisection way; either is good).
Second, use <code>ci_median</code> from <code>smmr</code>. The latter takes
as input a data frame, a column name (unquoted) and optionally a
<code>conf.level</code> that defaults to 0.95.</p></li>
</ol>
</div>
<div id="chocolate-chips" class="section level2">
<h2><span class="header-section-number">9.2</span> Chocolate chips</h2>
<p>A famous cookie manufacturer claims that
their bags of chocolate chip cookies contain “more than 1100 chocolate chips on average”. A diligent group of students buys 16
bags of these cookies and counts the number of chocolate chips in each
bag. The results are in <a href="http://ritsokiguess.site/datafiles/chips.txt">http://ritsokiguess.site/datafiles/chips.txt</a>.</p>
<ol style="list-style-type: lower-alpha">
<li><p>Read in and display (some of) the data.</p></li>
<li><p>Build your own sign test in R for testing that the median is
1100 chocolate chips, against the alternative that it is greater.
(Do this as in class: count the appropriate thing,
compare it with an appropriate binomial distribution, and obtain a
P-value.</p></li>
<li><p>Use my R package <code>smmr</code> to reproduce your sign test
above, and verify that you get consistent results. (See the
maze-design question for instructions on installing this, if you
haven’t yet.)</p></li>
<li><p>Use <code>smmr</code> to obtain a 95% confidence interval for the
median number of chocolate chips per bag of cookies.</p></li>
</ol>
</div>
<div id="the-power-of-the-sign-test" class="section level2">
<h2><span class="header-section-number">9.3</span> The power of the sign test</h2>
<p>I’ve mentioned several times that the sign test has less
power than the <span class="math inline">\(t\)</span>-test. Let’s investigate this with a specific example.</p>
<p>Let’s suppose we are testing <span class="math inline">\(H_0: \mu=40\)</span> against <span class="math inline">\(H_a: \mu \ne 40\)</span>,
where <span class="math inline">\(\mu\)</span> is the population mean (and median, as we shall see). Our
population actually has a normal distribution with mean 50 and SD 15,
so that the null hypothesis is <em>wrong</em> and we want to reject it
most of the time. On the other hand, the population actually <em>is</em>
normally-distributed and so the <span class="math inline">\(t\)</span>-test is the right one to use.</p>
<p>(This is an old question, so I tackle the simulated power differently
than I did it in class this time. But see if you can follow what I do
here.)</p>
<ol style="list-style-type: lower-alpha">
<li><p>Use <code>power.t.test</code> to find the probability that a
<span class="math inline">\(t\)</span>-test correctly rejects the null hypothesis using a sample size
of <span class="math inline">\(n=10\)</span>.</p></li>
<li><p>What code in R would draw a random sample of size 10 from the
<em>true</em> population distribution and save the sample in a variable?</p></li>
<li><p>What code would count how many of the sampled values are less
than 40 and how many are greater (or equal)?</p></li>
<li><p>It turns out the sign test would reject <span class="math inline">\(H_0: M=40\)</span> against
<span class="math inline">\(H_a: M \ne 40\)</span> at <span class="math inline">\(\alpha=0.05\)</span> if the smaller of the numbers in the
last part is 1 or less. (<span class="math inline">\(M\)</span> is the population median.)
Add to your pipeline to obtain <code>TRUE</code>
if you should reject the null for your
data and <code>FALSE</code> otherwise.</p></li>
<li><p>Simulate the above process 1000 times:
draw a random sample from a normal distribution of size 10 with mean 50 and SD
15, count the number of values below 40, reject if the
minimum of those is 0, 1, 9, or 10, then count the number of rejections
out of 1000.</p></li>
<li><p>Which is more powerful in this case, the sign test or the
<span class="math inline">\(t\)</span>-test? How do you know?</p></li>
</ol>
</div>
<div id="ben-roethlisberger" class="section level2">
<h2><span class="header-section-number">9.4</span> Ben Roethlisberger</h2>
<p>Ben Roethlisberger plays (American) football for the Pittsburgh Steelers. He plays as a quarterback, which means that his job is to throw (pass) the ball so that one of his teammates can catch it. Each time he makes a pass that is caught, this is called a “completion”, and the team coaches are interested in his average number of completions per game (this average could be the mean or the median).</p>
<p>In 2010, Roethlisberger was suspended for the first four games of the season, and there was concern that this might affect his performance (in terms of the number of passes completed in the games after he returned). The Pittsburgh Steelers did not play in week 5 of the 2010 season; the season is 17 weeks long (one game per week) and each team has one week in which they do not play.</p>
<p>The data are <a href="http://ritsokiguess.site/datafiles/roethlisberger.csv">here</a>. There are four columns: the year (always 2010), the week number of the season that the game was played in, the name of the opposing team, and the number of completed passes by Roethlisberger in the game.</p>
<ol style="list-style-type: lower-alpha">
<li><p>Read in and display (some of) the data. Do you have what you were expecting?</p></li>
<li><p>Make a suitable graph of the number of completed passes, and explain briefly why you would have some doubts about using <span class="math inline">\(t\)</span>-procedures in this situation.</p></li>
<li><p>Run a sign test to compare Roethlisberger’s performance in 2010 with his previous average of 22.5 completions per game. What do you conclude?</p></li>
<li><p>Why might you have expected your sign test to come out significant, even without looking at the P-value? Explain briefly.</p></li>
<li><p>Obtain a 90% confidence interval for the median number of completed passes (over “all possible games played by 2010 Ben Roethlisberger”).</p></li>
<li><p>Find a 90% confidence interval for the <em>mean</em> number of passes completed, and explain briefly why it differs from the one for the median in the way that it does.</p></li>
</ol>
</div>
<div id="six-ounces-of-protein" class="section level2">
<h2><span class="header-section-number">9.5</span> Six ounces of protein</h2>
<p>A company produces prepackaged diet meals. These meals are advertised as containing “6 ounces of protein per package”. A consumer organization is concerned that this is not accurate. The organization takes a random sample of 20 of these meals, and measures the protein content of each one. The data are in <a href="http://ritsokiguess.site/datafiles/protein.txt">http://ritsokiguess.site/datafiles/protein.txt</a>
as one column.</p>
<ol style="list-style-type: lower-alpha">
<li><p>Read in and display (some of) the data.</p></li>
<li><p>Make a suitable graph of your data.</p></li>
<li><p>Why might a sign test be better than a <span class="math inline">\(t\)</span>-test for assessing the average amount of protein per package? Explain briefly. (“Average” here means any measure of centre.)</p></li>
<li><p>Run a suitable sign test for these data. What do you conclude?</p></li>
<li><p>In your sign test, how could you have deduced that the P-value was going to be small even without looking at any of the P-values themselves? Explain briefly.</p></li>
<li><p>Obtain a 90% confidence interval for the population median protein content. What does this tell you about the reason for the rejection or non-rejection of the null hypothesis above?</p></li>
</ol>
<p>My solutions follow:</p>
</div>
<div id="running-a-maze-1" class="section level2">
<h2><span class="header-section-number">9.6</span> Running a maze</h2>
<p>A researcher is trying to design a maze that can be run by
rats in about 60 seconds. One particular maze was run by a sample of
21 rats, with the times shown in
<a href="http://ritsokiguess.site/datafiles/maze.txt">link</a>.</p>
<ol style="list-style-type: lower-alpha">
<li>Read the data into R. What (if anything) are the data values
delimited by?</li>
</ol>
<p>Solution</p>
<p>Take a look at the data file first. There is only one column of
data, so you can treat it as being delimited by anything you like:
a space, or a comma (the file can also be treated as a
<code>.csv</code>), etc.:</p>
<div class="sourceCode" id="cb47"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb47-1" title="1">myurl &lt;-<span class="st"> &quot;http://ritsokiguess.site/datafiles/maze.txt&quot;</span></a>
<a class="sourceLine" id="cb47-2" title="2">times &lt;-<span class="st"> </span><span class="kw">read_delim</span>(myurl, <span class="st">&quot; &quot;</span>)</a></code></pre></div>
<pre><code>## 
## ── Column specification ──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
## cols(
##   time = col_double()
## )</code></pre>
<div class="sourceCode" id="cb49"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb49-1" title="1">times</a></code></pre></div>
<pre><code>## # A tibble: 21 x 1
##     time
##    &lt;dbl&gt;
##  1  38.4
##  2  46.2
##  3  62.5
##  4  38  
##  5  62.8
##  6  33.9
##  7  50.4
##  8  35  
##  9  52.8
## 10  60.1
## # … with 11 more rows</code></pre>
<p><span class="math inline">\(\blacksquare\)</span></p>
<ol start="2" style="list-style-type: lower-alpha">
<li>Run a sign test, doing it yourself as we did in class:
count the number of values above and below 60, take the <em>smaller</em>
of those, and find the probability of a value of that or smaller still
on a binomial distribution with <span class="math inline">\(n=21\)</span> and <span class="math inline">\(p=0.5\)</span> (we have 21 data
points), doubling the answer because the test is two-sided.</li>
</ol>
<p>Solution</p>
<p>Count how many values are above and below 60:</p>
<div class="sourceCode" id="cb51"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb51-1" title="1">times <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">count</span>(time <span class="op">&gt;</span><span class="st"> </span><span class="dv">60</span>)</a></code></pre></div>
<pre><code>## # A tibble: 2 x 2
##   `time &gt; 60`     n
##   &lt;lgl&gt;       &lt;int&gt;
## 1 FALSE          16
## 2 TRUE            5</code></pre>
<p>5 above and 16 below. Then find out how likely it is that a binomial
with <span class="math inline">\(n=21, p=0.5\)</span> would produce 5 or fewer successes:</p>
<div class="sourceCode" id="cb53"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb53-1" title="1">p &lt;-<span class="st"> </span><span class="kw">sum</span>(<span class="kw">dbinom</span>(<span class="dv">0</span><span class="op">:</span><span class="dv">5</span>, <span class="dv">21</span>, <span class="fl">0.5</span>))</a>
<a class="sourceLine" id="cb53-2" title="2">p</a></code></pre></div>
<pre><code>## [1] 0.01330185</code></pre>
<p>or if you prefer count upwards from 16:</p>
<div class="sourceCode" id="cb55"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb55-1" title="1"><span class="kw">sum</span>(<span class="kw">dbinom</span>(<span class="dv">16</span><span class="op">:</span><span class="dv">21</span>, <span class="dv">21</span>, <span class="fl">0.5</span>))</a></code></pre></div>
<pre><code>## [1] 0.01330185</code></pre>
<p>and double it to get a two-sided P-value:</p>
<div class="sourceCode" id="cb57"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb57-1" title="1"><span class="dv">2</span> <span class="op">*</span><span class="st"> </span>p</a></code></pre></div>
<pre><code>## [1] 0.0266037</code></pre>
<p>We’ll compare this with <code>smmr</code> in a moment.</p>
<p><span class="math inline">\(\blacksquare\)</span></p>
<ol start="3" style="list-style-type: lower-alpha">
<li>Install my package <code>smmr</code>, if you haven’t already. To do
this, you first need to install the package <code>devtools</code> (if you
haven’t already),
by going to the console and typing</li>
</ol>
<div class="sourceCode" id="cb59"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb59-1" title="1"><span class="kw">install.packages</span>(<span class="st">&quot;devtools&quot;</span>)</a></code></pre></div>
<p>When that’s all done, install <code>smmr</code> thus:</p>
<div class="sourceCode" id="cb60"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb60-1" title="1"><span class="kw">library</span>(devtools)</a>
<a class="sourceLine" id="cb60-2" title="2"><span class="kw">install_github</span>(<span class="st">&quot;nxskok/smmr&quot;</span>)</a></code></pre></div>
<p>That all needs to be done only once. Then, each R Studio session where
you want to use <code>smmr</code> needs this:</p>
<div class="sourceCode" id="cb61"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb61-1" title="1"><span class="kw">library</span>(smmr)</a></code></pre></div>
<p>As usual, only the <code>library</code> thing only needs to be done every
time.</p>
<p>When you have <code>smmr</code> installed, use <code>sign_test</code> from
that package to re-run your sign test. Do you get the same P-value?</p>
<p>Solution</p>
<p>The sign test function takes a data frame, an (unquoted) column
name from that data frame of data to test the median of, and a
null median (which defaults to 0 if you omit it):</p>
<div class="sourceCode" id="cb62"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb62-1" title="1"><span class="kw">library</span>(smmr)</a>
<a class="sourceLine" id="cb62-2" title="2"><span class="kw">sign_test</span>(times, time, <span class="dv">60</span>)</a></code></pre></div>
<pre><code>## $above_below
## below above 
##    16     5 
## 
## $p_values
##   alternative    p_value
## 1       lower 0.01330185
## 2       upper 0.99640131
## 3   two-sided 0.02660370</code></pre>
<p>This shows you two things: a count of the values below and above the
null median, and then the P-values according to the various
alternative hypotheses you might have.</p>
<p>In our case, we see again the 16 maze-running times below 60 seconds
and 5 above (one of which was a long way above, but we don’t care
about that here). We were testing whether the median was different
from 60, so we look at the two-sided P-value of 0.0266, which is
exactly what we had before.</p>
<p>If <code>sign_test</code> doesn’t work for you (perhaps because it needs
a function <code>enquo</code> that you don’t have), there is an
alternative function <code>sign_test0</code> that doesn’t use it. It
requires as input a <em>column</em> of values (extracted from the data
frame) and a null median, thus:</p>
<div class="sourceCode" id="cb64"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb64-1" title="1"><span class="kw">with</span>(times, <span class="kw">sign_test0</span>(time, <span class="dv">60</span>))</a></code></pre></div>
<pre><code>## $above_below
## below above 
##    16     5 
## 
## $p_values
##   alternative    p_value
## 1       lower 0.01330185
## 2       upper 0.99640131
## 3   two-sided 0.02660370</code></pre>
<p>The output should be, and here is, identical.</p>
<p><span class="math inline">\(\blacksquare\)</span></p>
<ol start="4" style="list-style-type: lower-alpha">
<li>Package <code>smmr</code> also has a function
<code>pval_sign</code>, which has the same input as
<code>sign_test</code>, but with the null median <em>first</em>.
Run it on your data and see what it gives.</li>
</ol>
<p>Solution</p>
<p>Try it and see:</p>
<div class="sourceCode" id="cb66"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb66-1" title="1"><span class="kw">pval_sign</span>(<span class="dv">60</span>, times, time)</a></code></pre></div>
<pre><code>## [1] 0.0266037</code></pre>
<p>The two-sided P-value, and that is all. We’ll be using this in a minute.</p>
<p>Alternatively, there is also this, which needs a null median and a
<em>column</em> as input:</p>
<div class="sourceCode" id="cb68"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb68-1" title="1"><span class="kw">with</span>(times, <span class="kw">pval_sign0</span>(<span class="dv">60</span>, time))</a></code></pre></div>
<pre><code>## [1] 0.0266037</code></pre>
<p><span class="math inline">\(\blacksquare\)</span></p>
<ol start="5" style="list-style-type: lower-alpha">
<li>Obtain a 95% confidence interval for the median based on these
data. Do this two ways. First, use the trial and error way from class
(either the try-lots-of-values way or the bisection way; either is good).
Second, use <code>ci_median</code> from <code>smmr</code>. The latter takes
as input a data frame, a column name (unquoted) and optionally a
<code>conf.level</code> that defaults to 0.95.</li>
</ol>
<p>Solution</p>
<p>The reason for showing you <code>pval_sign</code> in the previous
part is that this is a building block for the confidence interval.
What we do is to try various null medians
and find out which ones give P-values less than 0.05 (outside the
interval) and which ones bigger (inside).
We know that the value 60 is
outside the 95% CI, and the sample median is close to 50 (which we
expect to be inside), so sensible values to try for the upper end of
the interval would be between 50 and 60:</p>
<div class="sourceCode" id="cb70"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb70-1" title="1"><span class="kw">pval_sign</span>(<span class="dv">58</span>, times, time)</a></code></pre></div>
<pre><code>## [1] 0.0266037</code></pre>
<div class="sourceCode" id="cb72"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb72-1" title="1"><span class="kw">pval_sign</span>(<span class="dv">55</span>, times, time)</a></code></pre></div>
<pre><code>## [1] 0.6636238</code></pre>
<p>So, 55 is inside the interval and 58 is outside. I could investigate
further in similar fashion, but I thought I would try a whole bunch of null
medians all at once. That goes like this, <code>rowwise</code> because <code>pval_sign</code> expects <em>one</em> null-hypothesis median, not several all at once:</p>
<div class="sourceCode" id="cb74"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb74-1" title="1"><span class="kw">tibble</span>(<span class="dt">meds =</span> <span class="kw">seq</span>(<span class="dv">55</span>, <span class="dv">58</span>, <span class="fl">0.25</span>)) <span class="op">%&gt;%</span><span class="st"> </span></a>
<a class="sourceLine" id="cb74-2" title="2"><span class="st">  </span><span class="kw">rowwise</span>() <span class="op">%&gt;%</span><span class="st"> </span></a>
<a class="sourceLine" id="cb74-3" title="3"><span class="st">  </span><span class="kw">mutate</span>(<span class="dt">pvals =</span> <span class="kw">pval_sign</span>(meds, times, time))</a></code></pre></div>
<pre><code>## # A tibble: 13 x 2
## # Rowwise: 
##     meds  pvals
##    &lt;dbl&gt;  &lt;dbl&gt;
##  1  55   0.664 
##  2  55.2 0.383 
##  3  55.5 0.263 
##  4  55.8 0.189 
##  5  56   0.189 
##  6  56.2 0.189 
##  7  56.5 0.0784
##  8  56.8 0.0784
##  9  57   0.0784
## 10  57.2 0.0784
## 11  57.5 0.0784
## 12  57.8 0.0266
## 13  58   0.0266</code></pre>
<p>So values for the median all the way up to and including 57.5 are in
the confidence interval.</p>
<p>Now for the other end of the interval. I’m going to do this a
different way: more efficient, but less transparent. The first thing I
need is a pair of values for the median: one inside the interval and
one outside. Let’s try 40 and 50:</p>
<div class="sourceCode" id="cb76"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb76-1" title="1"><span class="kw">pval_sign</span>(<span class="dv">40</span>, times, time)</a></code></pre></div>
<pre><code>## [1] 0.00719738</code></pre>
<div class="sourceCode" id="cb78"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb78-1" title="1"><span class="kw">pval_sign</span>(<span class="dv">50</span>, times, time)</a></code></pre></div>
<pre><code>## [1] 1</code></pre>
<p>OK, so 40 is outside and 50 is inside. So what do I guess for the next
value to try? I could do something clever like assuming that the
relationship between hypothesized median and P-value is <em>linear</em>,
and then guessing where that line crosses 0.05. But I’m going to
assume <em>nothing</em> about the relationship except that it goes
uphill, and therefore crosses 0.05 somewhere. So my next guess is
halfway between the two values I tried before:</p>
<div class="sourceCode" id="cb80"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb80-1" title="1"><span class="kw">pval_sign</span>(<span class="dv">45</span>, times, time)</a></code></pre></div>
<pre><code>## [1] 0.07835388</code></pre>
<p>So, 45 is inside the interval, and my (slightly) improved guess at the
bottom end of the interval is that it’s between 40 and 45. So next, I
try halfway between <em>those</em>:</p>
<div class="sourceCode" id="cb82"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb82-1" title="1"><span class="kw">pval_sign</span>(<span class="fl">42.5</span>, times, time)</a></code></pre></div>
<pre><code>## [1] 0.0266037</code></pre>
<p>42.5 is outside, so the bottom end of the interval is between 42.5 and 45.</p>
<p>What we are doing is narrowing down where the interval’s bottom end
is. We started by knowing it to within 10, and now we know it to
within 2.5. So if we keep going, we’ll know it as accurately as we wish.</p>
<p>This is called a “bisection” method, because at each step, we’re
dividing our interval by 2.</p>
<p>There is one piece of decision-making at each step: if the P-value for
the median you try is greater than 0.05, that becomes the top end of
your interval (as when we tried 45); if it is less, it becomes the
bottom end (when we tried 42.5).</p>
<p>This all begs to be automated into a loop. It’s not a
<code>for</code>-type loop, because we don’t know how many times we’ll be
going around. It’s a <code>while</code> loop: keep going while something
is true. Here’s how it goes:</p>
<div class="sourceCode" id="cb84"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb84-1" title="1">lo &lt;-<span class="st"> </span><span class="dv">40</span></a>
<a class="sourceLine" id="cb84-2" title="2">hi &lt;-<span class="st"> </span><span class="dv">50</span></a>
<a class="sourceLine" id="cb84-3" title="3"><span class="cf">while</span> (<span class="kw">abs</span>(hi <span class="op">-</span><span class="st"> </span>lo) <span class="op">&gt;</span><span class="st"> </span><span class="fl">0.1</span>) {</a>
<a class="sourceLine" id="cb84-4" title="4">  try &lt;-<span class="st"> </span>(hi <span class="op">+</span><span class="st"> </span>lo) <span class="op">/</span><span class="st"> </span><span class="dv">2</span></a>
<a class="sourceLine" id="cb84-5" title="5">  ptry &lt;-<span class="st"> </span><span class="kw">pval_sign</span>(try, times, time)</a>
<a class="sourceLine" id="cb84-6" title="6">  <span class="kw">print</span>(<span class="kw">c</span>(try, ptry))</a>
<a class="sourceLine" id="cb84-7" title="7">  <span class="cf">if</span> (ptry <span class="op">&lt;</span><span class="st"> </span><span class="fl">0.05</span>) {</a>
<a class="sourceLine" id="cb84-8" title="8">    lo &lt;-<span class="st"> </span>try</a>
<a class="sourceLine" id="cb84-9" title="9">  } <span class="cf">else</span> {</a>
<a class="sourceLine" id="cb84-10" title="10">    hi &lt;-<span class="st"> </span>try</a>
<a class="sourceLine" id="cb84-11" title="11">  }</a>
<a class="sourceLine" id="cb84-12" title="12">}</a></code></pre></div>
<pre><code>## [1] 45.00000000  0.07835388
## [1] 42.5000000  0.0266037
## [1] 43.7500000  0.0266037
## [1] 44.37500000  0.07835388
## [1] 44.0625000  0.0266037
## [1] 44.2187500  0.0266037
## [1] 44.2968750  0.0266037</code></pre>
<div class="sourceCode" id="cb86"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb86-1" title="1">lo</a></code></pre></div>
<pre><code>## [1] 44.29688</code></pre>
<div class="sourceCode" id="cb88"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb88-1" title="1"><span class="kw">pval_sign</span>(lo, times, time)</a></code></pre></div>
<pre><code>## [1] 0.0266037</code></pre>
<div class="sourceCode" id="cb90"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb90-1" title="1">hi</a></code></pre></div>
<pre><code>## [1] 44.375</code></pre>
<div class="sourceCode" id="cb92"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb92-1" title="1"><span class="kw">pval_sign</span>(hi, times, time)</a></code></pre></div>
<pre><code>## [1] 0.07835388</code></pre>
<p>The loop stopped because 44.297 and 44.375 are less than 0.1
apart. The first of those is outside the interval and the second is
inside. So the bottom end of our interval is 44.375, to this
accuracy. If you want it more accurately, change 0.1 in the
<code>while</code> line to something smaller (but then you’ll be waiting
longer for the answer).</p>
<p>I put the <code>print</code> statement in the loop so that you could see
what values were being tried, and what P-values they were
producing. What happens with these is that the P-value jumps at each
data value, so you won’t get a P-value exactly 0.05; you’ll get one
above and one below.</p>
<p>Likewise, you can use the function with a zero on its name and feed it
a column rather than a data frame and a column name:</p>
<div class="sourceCode" id="cb94"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb94-1" title="1"><span class="kw">tibble</span>(<span class="dt">meds =</span>  <span class="kw">seq</span>(<span class="dv">55</span>, <span class="dv">58</span>, <span class="fl">0.25</span>)) <span class="op">%&gt;%</span><span class="st"> </span></a>
<a class="sourceLine" id="cb94-2" title="2"><span class="st">  </span><span class="kw">rowwise</span>() <span class="op">%&gt;%</span><span class="st"> </span></a>
<a class="sourceLine" id="cb94-3" title="3"><span class="st">  </span><span class="kw">mutate</span>(<span class="dt">pvals =</span>  <span class="kw">with</span>(times, <span class="kw">pval_sign0</span>(meds, time)))</a></code></pre></div>
<pre><code>## # A tibble: 13 x 2
## # Rowwise: 
##     meds  pvals
##    &lt;dbl&gt;  &lt;dbl&gt;
##  1  55   0.664 
##  2  55.2 0.383 
##  3  55.5 0.263 
##  4  55.8 0.189 
##  5  56   0.189 
##  6  56.2 0.189 
##  7  56.5 0.0784
##  8  56.8 0.0784
##  9  57   0.0784
## 10  57.2 0.0784
## 11  57.5 0.0784
## 12  57.8 0.0266
## 13  58   0.0266</code></pre>
<p>Or adapt the idea I had above for bisection.
All that was a lot of work, but I wanted you to see it all once, so that you
know where the confidence interval is coming from. <code>smmr</code> also
has a function <code>ci_median</code> that does all of the above without
you having to do it. As I first wrote it, it was using the trial and
error thing with <code>rowwise</code>, but I chose to rewrite it with the
bisection idea, because I thought that would be more accurate.</p>
<div class="sourceCode" id="cb96"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb96-1" title="1"><span class="kw">ci_median</span>(times, time)</a></code></pre></div>
<pre><code>## [1] 44.30747 57.59766</code></pre>
<p>This is a more accurate interval than we got above. (The
<code>while</code> loop for the bisection keeps going until the two
guesses at the appropriate end of the interval are less than 0.01
apart, by default.)<a href="#fn1" class="footnote-ref" id="fnref1"><sup>1</sup></a></p>
<p>If you want some other confidence level, you add <code>conf.level</code>
on the end, as you would for <code>t.test</code>:</p>
<div class="sourceCode" id="cb98"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb98-1" title="1"><span class="kw">ci_median</span>(times, time, <span class="dt">conf.level =</span> <span class="fl">0.75</span>)</a></code></pre></div>
<pre><code>## [1] 46.20444 55.49473</code></pre>
<p>A 75% CI, just for fun. This is a shorter interval than the 95% one,
as it should be.</p>
<p>Likewise there is a <code>ci_median0</code> that takes a column and an
optional confidence level:</p>
<div class="sourceCode" id="cb100"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb100-1" title="1"><span class="kw">with</span>(times, <span class="kw">ci_median0</span>(time))</a></code></pre></div>
<pre><code>## [1] 44.30747 57.59766</code></pre>
<div class="sourceCode" id="cb102"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb102-1" title="1"><span class="kw">with</span>(times, <span class="kw">ci_median0</span>(time, <span class="dt">conf.level =</span> <span class="fl">0.75</span>))</a></code></pre></div>
<pre><code>## [1] 46.20444 55.49473</code></pre>
<p>with the same results. Try <code>ci_median</code> first, and if it
doesn’t work, try <code>ci_median0</code>.</p>
<p><span class="math inline">\(\blacksquare\)</span></p>
</div>
<div id="chocolate-chips-1" class="section level2">
<h2><span class="header-section-number">9.7</span> Chocolate chips</h2>
<p>A famous cookie manufacturer claims that
their bags of chocolate chip cookies contain “more than 1100 chocolate chips on average”. A diligent group of students buys 16
bags of these cookies and counts the number of chocolate chips in each
bag. The results are in <a href="http://ritsokiguess.site/datafiles/chips.txt">http://ritsokiguess.site/datafiles/chips.txt</a>.</p>
<ol style="list-style-type: lower-alpha">
<li>Read in and display (some of) the data.</li>
</ol>
<p>Solution</p>
<p>I’ll pretend it’s a
<code>.csv</code> this time, just for fun. Give the data frame a
name different from <code>chips</code>, so that you don’t get
confused:</p>
<div class="sourceCode" id="cb104"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb104-1" title="1">bags=<span class="kw">read_csv</span>(<span class="st">&quot;chips.txt&quot;</span>)</a></code></pre></div>
<pre><code>## 
## ── Column specification ──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
## cols(
##   chips = col_double()
## )</code></pre>
<div class="sourceCode" id="cb106"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb106-1" title="1">bags</a></code></pre></div>
<pre><code>## # A tibble: 16 x 1
##    chips
##    &lt;dbl&gt;
##  1  1219
##  2  1214
##  3  1087
##  4  1200
##  5  1419
##  6  1121
##  7  1325
##  8  1345
##  9  1244
## 10  1258
## 11  1356
## 12  1132
## 13  1191
## 14  1270
## 15  1295
## 16  1135</code></pre>
<p>That looks sensible.</p>
<p><span class="math inline">\(\blacksquare\)</span></p>
<ol start="2" style="list-style-type: lower-alpha">
<li>Build your own sign test in R for testing that the median is
1100 chocolate chips, against the alternative that it is greater.
(Do this as in class: count the appropriate thing,
compare it with an appropriate binomial distribution, and obtain a
P-value.</li>
</ol>
<p>Solution</p>
<p>The null median is 1100, so we count the number
of values above and below:</p>
<div class="sourceCode" id="cb108"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb108-1" title="1">bags <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">count</span>(chips<span class="op">&lt;</span><span class="dv">1100</span>)</a></code></pre></div>
<pre><code>## # A tibble: 2 x 2
##   `chips &lt; 1100`     n
##   &lt;lgl&gt;          &lt;int&gt;
## 1 FALSE             15
## 2 TRUE               1</code></pre>
<p>The un-standard thing there is that we can put a logical condition
directly into the <code>count</code>. If you don’t think of that, you can
also do this, which creates a new variable <code>less</code> that is
<code>TRUE</code> or <code>FALSE</code> for each bag appropriately:</p>
<div class="sourceCode" id="cb110"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb110-1" title="1">bags <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">mutate</span>(<span class="dt">less=</span>(chips<span class="op">&lt;</span><span class="dv">1100</span>)) <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">count</span>(less)</a></code></pre></div>
<pre><code>## # A tibble: 2 x 2
##   less      n
##   &lt;lgl&gt; &lt;int&gt;
## 1 FALSE    15
## 2 TRUE      1</code></pre>
<p>or the more verbose</p>
<div class="sourceCode" id="cb112"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb112-1" title="1">bags <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">mutate</span>(<span class="dt">less=</span>(chips<span class="op">&lt;</span><span class="dv">1100</span>)) <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb112-2" title="2"><span class="kw">group_by</span>(less) <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">summarize</span>(<span class="dt">howmany=</span><span class="kw">n</span>())</a></code></pre></div>
<pre><code>## # A tibble: 2 x 2
##   less  howmany
##   &lt;lgl&gt;   &lt;int&gt;
## 1 FALSE      15
## 2 TRUE        1</code></pre>
<p>Just one value below, with all the rest above.
Getting the right P-value, properly, requires some careful thought
(but you will probably get the right answer anyway). If the
alternative hypothesis is true, and the median is actually bigger than
1100 (say, 1200), you would expect half the data values to be bigger
than 1200 and half smaller. So <em>more</em> than half the data values
would be bigger than <em>1100</em>, and fewer than half of them would be
less than 1100. So, if we are going to reject the null (as it looks as
if we will), that small number of values below 1100 is what we want.</p>
<p>The P-value is the probability of a value 1 or less in a binomial
distribution with <span class="math inline">\(n=16, p=0.5\)</span>:</p>
<div class="sourceCode" id="cb114"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb114-1" title="1"><span class="kw">sum</span>(<span class="kw">dbinom</span>(<span class="dv">0</span><span class="op">:</span><span class="dv">1</span>,<span class="dv">16</span>,<span class="fl">0.5</span>))</a></code></pre></div>
<pre><code>## [1] 0.0002593994</code></pre>
<p>Or, equivalently, count <em>up</em> from 15:</p>
<div class="sourceCode" id="cb116"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb116-1" title="1"><span class="kw">sum</span>(<span class="kw">dbinom</span>(<span class="dv">15</span><span class="op">:</span><span class="dv">16</span>,<span class="dv">16</span>,<span class="fl">0.5</span>))</a></code></pre></div>
<pre><code>## [1] 0.0002593994</code></pre>
<p>This is correctly one-sided, so we don’t have to do anything with
it.</p>
<p><span class="math inline">\(\blacksquare\)</span></p>
<ol start="3" style="list-style-type: lower-alpha">
<li>Use my R package <code>smmr</code> to reproduce your sign test
above, and verify that you get consistent results. (See the
maze-design question for instructions on installing this, if you
haven’t yet.)</li>
</ol>
<p>Solution</p>
<p>This will mean reading the output carefully:</p>
<div class="sourceCode" id="cb118"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb118-1" title="1"><span class="kw">library</span>(smmr)</a>
<a class="sourceLine" id="cb118-2" title="2"><span class="kw">sign_test</span>(bags,chips,<span class="dv">1100</span>)</a></code></pre></div>
<pre><code>## $above_below
## below above 
##     1    15 
## 
## $p_values
##   alternative      p_value
## 1       lower 0.9999847412
## 2       upper 0.0002593994
## 3   two-sided 0.0005187988</code></pre>
<p>This time, we’re doing a one-sided test, specifically an
<em>upper-tail</em> test, since we are looking for evidence that the
median is <em>greater than</em> 1100. The results are exactly what we
got “by hand”: 15 values above and one below, and a P-value (look
along the <code>upper</code> line) of 0.00026.
The two-sided P-value of 0.00052 rounds to the same 0.0005 as SAS got.</p>
<p>Alternatively, you can do this:</p>
<div class="sourceCode" id="cb120"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb120-1" title="1"><span class="kw">sign_test0</span>(bags<span class="op">$</span>chips,<span class="dv">1100</span>)</a></code></pre></div>
<pre><code>## $above_below
## below above 
##     1    15 
## 
## $p_values
##   alternative      p_value
## 1       lower 0.9999847412
## 2       upper 0.0002593994
## 3   two-sided 0.0005187988</code></pre>
<p>with the same result (but only go this way if you need to).</p>
<p><span class="math inline">\(\blacksquare\)</span></p>
<ol start="4" style="list-style-type: lower-alpha">
<li>Use <code>smmr</code> to obtain a 95% confidence interval for the
median number of chocolate chips per bag of cookies.</li>
</ol>
<p>Solution</p>
<p>Once everything is in place, this is simplicity itself:</p>
<div class="sourceCode" id="cb122"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb122-1" title="1"><span class="kw">ci_median</span>(bags,chips)</a></code></pre></div>
<pre><code>## [1] 1135.003 1324.996</code></pre>
<p>1135 to 1325. I would round these off to whole numbers, since the data
values are all whole numbers. These values are all above 1100, which
supports the conclusion we got above that the median is above
1100. This is as it should be, because the CI is “all those medians that would <em>not</em> be rejected by the sign test”.</p>
<p>Or,</p>
<div class="sourceCode" id="cb124"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb124-1" title="1"><span class="kw">ci_median0</span>(bags<span class="op">$</span>chips)</a></code></pre></div>
<pre><code>## [1] 1135.003 1324.996</code></pre>
<p><span class="math inline">\(\blacksquare\)</span></p>
</div>
<div id="the-power-of-the-sign-test-1" class="section level2">
<h2><span class="header-section-number">9.8</span> The power of the sign test</h2>
<p>I’ve mentioned several times that the sign test has less
power than the <span class="math inline">\(t\)</span>-test. Let’s investigate this with a specific example.</p>
<p>Let’s suppose we are testing <span class="math inline">\(H_0: \mu=40\)</span> against <span class="math inline">\(H_a: \mu \ne 40\)</span>,
where <span class="math inline">\(\mu\)</span> is the population mean (and median, as we shall see). Our
population actually has a normal distribution with mean 50 and SD 15,
so that the null hypothesis is <em>wrong</em> and we want to reject it
most of the time. On the other hand, the population actually <em>is</em>
normally-distributed and so the <span class="math inline">\(t\)</span>-test is the right one to use.</p>
<p>(This is an old question, so I tackle the simulated power differently
than I did it in class this time. But see if you can follow what I do
here.)</p>
<ol style="list-style-type: lower-alpha">
<li>Use <code>power.t.test</code> to find the probability that a
<span class="math inline">\(t\)</span>-test correctly rejects the null hypothesis using a sample size
of <span class="math inline">\(n=10\)</span>.</li>
</ol>
<p>Solution</p>
<div class="sourceCode" id="cb126"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb126-1" title="1"><span class="kw">power.t.test</span>(<span class="dt">delta=</span><span class="dv">50-40</span>,<span class="dt">n=</span><span class="dv">10</span>,<span class="dt">sd=</span><span class="dv">15</span>,<span class="dt">type=</span><span class="st">&quot;one.sample&quot;</span>,<span class="dt">alternative=</span><span class="st">&quot;two.sided&quot;</span>)</a></code></pre></div>
<pre><code>## 
##      One-sample t test power calculation 
## 
##               n = 10
##           delta = 10
##              sd = 15
##       sig.level = 0.05
##           power = 0.4691805
##     alternative = two.sided</code></pre>
<p>The power is 0.469. Not great, but we’ll see how this stacks up
against the sign test.</p>
<p><span class="math inline">\(\blacksquare\)</span></p>
<ol start="2" style="list-style-type: lower-alpha">
<li>What code in R would draw a random sample of size 10 from the
<em>true</em> population distribution and save the sample in a variable?</li>
</ol>
<p>Solution</p>
<p>The data actually have a normal distribution with mean 50 and
SD 15, so we use <code>rnorm</code> with this mean and SD, obtaining
10 values:</p>
<div class="sourceCode" id="cb128"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb128-1" title="1">x=<span class="kw">rnorm</span>(<span class="dv">10</span>,<span class="dv">50</span>,<span class="dv">15</span>)  </a>
<a class="sourceLine" id="cb128-2" title="2">x</a></code></pre></div>
<pre><code>##  [1] 69.56086 33.95769 53.17117 49.29129 55.50699 64.61828 77.67814 50.42967 71.11399 50.78041</code></pre>
<p><span class="math inline">\(\blacksquare\)</span></p>
<ol start="3" style="list-style-type: lower-alpha">
<li>What code would count how many of the sampled values are less
than 40 and how many are greater (or equal)?</li>
</ol>
<p>Solution</p>
<p>The way we know this is to put <code>x</code> into a data frame first:</p>
<div class="sourceCode" id="cb130"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb130-1" title="1"><span class="kw">tibble</span>(x) <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">count</span>(x<span class="op">&lt;</span><span class="dv">40</span>)</a></code></pre></div>
<pre><code>## # A tibble: 2 x 2
##   `x &lt; 40`     n
##   &lt;lgl&gt;    &lt;int&gt;
## 1 FALSE        9
## 2 TRUE         1</code></pre>
<p>2 values less (and 8 greater-or-equal).</p>
<p><span class="math inline">\(\blacksquare\)</span></p>
<ol start="4" style="list-style-type: lower-alpha">
<li>It turns out the sign test would reject <span class="math inline">\(H_0: M=40\)</span> against
<span class="math inline">\(H_a: M \ne 40\)</span> at <span class="math inline">\(\alpha=0.05\)</span> if the smaller of the numbers in the
last part is 1 or less. (<span class="math inline">\(M\)</span> is the population median.)
Add to your pipeline to obtain <code>TRUE</code>
if you should reject the null for your
data and <code>FALSE</code> otherwise.</li>
</ol>
<p>Solution</p>
<p>This is actually easier than you might think. The output from
<code>count</code> is a data frame with a column called <code>n</code>,
whose minimum value you want. I add to my pipeline:</p>
<div class="sourceCode" id="cb132"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb132-1" title="1"><span class="kw">tibble</span>(x) <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">count</span>(x<span class="op">&lt;</span><span class="dv">40</span>) <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb132-2" title="2"><span class="kw">summarize</span>(<span class="dt">the_min=</span><span class="kw">min</span>(n)) <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb132-3" title="3"><span class="kw">mutate</span>(<span class="dt">is_rejected=</span>(the_min<span class="op">&lt;=</span><span class="dv">1</span>))</a></code></pre></div>
<pre><code>## # A tibble: 1 x 2
##   the_min is_rejected
##     &lt;int&gt; &lt;lgl&gt;      
## 1       1 TRUE</code></pre>
<p>This will fail sometimes. If all 10 of your sample values are greater
than 40, which they might turn out to be, you’ll get a table with only
one line, <code>FALSE</code> and 10; the minimum of the <code>n</code> values
is 10 (since there is only one), and it will falsely say that you
should not reject. The fix is</p>
<div class="sourceCode" id="cb134"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb134-1" title="1"><span class="kw">tibble</span>(x) <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">count</span>(x<span class="op">&lt;</span><span class="dv">40</span>) <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb134-2" title="2"><span class="kw">summarize</span>(<span class="dt">the_min=</span><span class="kw">min</span>(n)) <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb134-3" title="3"><span class="kw">mutate</span>(<span class="dt">is_rejected=</span>(the_min<span class="op">&lt;=</span><span class="dv">1</span> <span class="op">|</span><span class="st"> </span>the_min<span class="op">==</span><span class="dv">10</span>))</a></code></pre></div>
<pre><code>## # A tibble: 1 x 2
##   the_min is_rejected
##     &lt;int&gt; &lt;lgl&gt;      
## 1       1 TRUE</code></pre>
<p>The above is almost the right thing, but not quite: we only want that value
that I called <code>is_rejected</code>, rather than the whole data frame,
so a <code>pull</code> will grab it:</p>
<div class="sourceCode" id="cb136"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb136-1" title="1"><span class="kw">tibble</span>(x) <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">count</span>(x<span class="op">&lt;</span><span class="dv">40</span>) <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb136-2" title="2"><span class="kw">summarize</span>(<span class="dt">the_min=</span><span class="kw">min</span>(n)) <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb136-3" title="3"><span class="kw">mutate</span>(<span class="dt">is_rejected=</span>(the_min<span class="op">&lt;=</span><span class="dv">1</span> <span class="op">|</span><span class="st"> </span>the_min<span class="op">==</span><span class="dv">10</span>)) <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb136-4" title="4"><span class="kw">pull</span>(is_rejected)</a></code></pre></div>
<pre><code>## [1] TRUE</code></pre>
<p>You might be wondering where the “1 or less” came from. Getting a
P-value for the sign test involves the binomial distribution: if the
null is correct, each data value is independently either above or
below 40, with probability 0.5 of each, so the number of values below
40 (say) is binomial with <span class="math inline">\(n=10\)</span> and <span class="math inline">\(p=0.5\)</span>. The P-value for 1
observed value below 40 and the rest above is</p>
<div class="sourceCode" id="cb138"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb138-1" title="1"><span class="dv">2</span><span class="op">*</span><span class="kw">pbinom</span>(<span class="dv">1</span>,<span class="dv">10</span>,<span class="fl">0.5</span>)  </a></code></pre></div>
<pre><code>## [1] 0.02148438</code></pre>
<p>which is less than 0.05; the P-value for 2 values below 40 and the
rest above is</p>
<div class="sourceCode" id="cb140"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb140-1" title="1"><span class="dv">2</span><span class="op">*</span><span class="kw">pbinom</span>(<span class="dv">2</span>,<span class="dv">10</span>,<span class="fl">0.5</span>)    </a></code></pre></div>
<pre><code>## [1] 0.109375</code></pre>
<p>which is bigger than 0.05.</p>
<p>You might have encountered the term “critical region” for a
test. This is the values of your test statistic that you would reject
the null hypothesis for. In this case, the critical region is 1 and 0
observations below 40, along with 1 and 0 observations above 40.</p>
<p>When you’re thinking about power, I think it’s easiest to think in
terms of the critical region (rather than directly in terms of
P-values) since you have a certain <span class="math inline">\(\alpha\)</span> in mind all the way
through, 0.05 in the power examples that I’ve done. The steps are then:</p>
<ul>
<li><p>Work out the critical region for your test, the values of the
test statistic (or sample mean or sample count) that would lead to
rejecting the null hypothesis.</p></li>
<li><p>Under your particular alternative hypothesis, find the
probability of falling into your critical region.</p></li>
</ul>
<p>When I say “work out”, I mean either calculating (along the lines of
STAB57), or simulating, as we have done here.</p>
<p><span class="math inline">\(\blacksquare\)</span></p>
<ol start="5" style="list-style-type: lower-alpha">
<li>Simulate the above process 1000 times:
draw a random sample from a normal distribution of size 10 with mean 50 and SD
15, count the number of values below 40, reject if the
minimum of those is 0, 1, 9, or 10, then count the number of rejections
out of 1000.</li>
</ol>
<p>Solution</p>
<p>Set up a dataframe with a column (called, maybe, <code>sim</code>) that counts the number of simulations you are doing, and then use <code>rowwise</code> to take a random sample in each row and extract what you need from it.</p>
<p>I start with setting the random number seed, so it comes out the
same each time. That way, if I rerun the code, my answers are the same (and I don’t have to change my discussion of them.)</p>
<div class="sourceCode" id="cb142"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb142-1" title="1"><span class="kw">set.seed</span>(<span class="dv">457299</span>)</a>
<a class="sourceLine" id="cb142-2" title="2"><span class="kw">tibble</span>(<span class="dt">sim =</span> <span class="dv">1</span><span class="op">:</span><span class="dv">1000</span>) <span class="op">%&gt;%</span><span class="st"> </span></a>
<a class="sourceLine" id="cb142-3" title="3"><span class="st">  </span><span class="kw">rowwise</span>() <span class="op">%&gt;%</span><span class="st"> </span></a>
<a class="sourceLine" id="cb142-4" title="4"><span class="st">  </span><span class="kw">mutate</span>(<span class="dt">sample =</span> <span class="kw">list</span>(<span class="kw">rnorm</span>(<span class="dv">10</span>, <span class="dv">50</span>, <span class="dv">15</span>)))</a></code></pre></div>
<pre><code>## # A tibble: 1,000 x 2
## # Rowwise: 
##      sim sample    
##    &lt;int&gt; &lt;list&gt;    
##  1     1 &lt;dbl [10]&gt;
##  2     2 &lt;dbl [10]&gt;
##  3     3 &lt;dbl [10]&gt;
##  4     4 &lt;dbl [10]&gt;
##  5     5 &lt;dbl [10]&gt;
##  6     6 &lt;dbl [10]&gt;
##  7     7 &lt;dbl [10]&gt;
##  8     8 &lt;dbl [10]&gt;
##  9     9 &lt;dbl [10]&gt;
## 10    10 &lt;dbl [10]&gt;
## # … with 990 more rows</code></pre>
<p>Each sample has 10 values in it, not just one, so you need the <code>list</code> around the <code>rnorm</code>. Note that <code>sample</code> is labelled as a list-column.</p>
<p>Now we have to count how many of the sample values are less than 40:</p>
<div class="sourceCode" id="cb144"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb144-1" title="1"><span class="kw">set.seed</span>(<span class="dv">457299</span>)</a>
<a class="sourceLine" id="cb144-2" title="2"><span class="kw">tibble</span>(<span class="dt">sim =</span> <span class="dv">1</span><span class="op">:</span><span class="dv">1000</span>) <span class="op">%&gt;%</span><span class="st"> </span></a>
<a class="sourceLine" id="cb144-3" title="3"><span class="st">  </span><span class="kw">rowwise</span>() <span class="op">%&gt;%</span><span class="st"> </span></a>
<a class="sourceLine" id="cb144-4" title="4"><span class="st">  </span><span class="kw">mutate</span>(<span class="dt">sample =</span> <span class="kw">list</span>(<span class="kw">rnorm</span>(<span class="dv">10</span>, <span class="dv">50</span>, <span class="dv">15</span>))) <span class="op">%&gt;%</span><span class="st"> </span></a>
<a class="sourceLine" id="cb144-5" title="5"><span class="st">  </span><span class="kw">mutate</span>(<span class="dt">less =</span> <span class="kw">list</span>(sample<span class="op">&lt;</span><span class="dv">40</span>)) <span class="op">%&gt;%</span><span class="st"> </span></a>
<a class="sourceLine" id="cb144-6" title="6"><span class="st">  </span><span class="kw">mutate</span>(<span class="dt">counted =</span> <span class="kw">sum</span>(less)) </a></code></pre></div>
<pre><code>## # A tibble: 1,000 x 4
## # Rowwise: 
##      sim sample     less       counted
##    &lt;int&gt; &lt;list&gt;     &lt;list&gt;       &lt;int&gt;
##  1     1 &lt;dbl [10]&gt; &lt;lgl [10]&gt;       3
##  2     2 &lt;dbl [10]&gt; &lt;lgl [10]&gt;       4
##  3     3 &lt;dbl [10]&gt; &lt;lgl [10]&gt;       2
##  4     4 &lt;dbl [10]&gt; &lt;lgl [10]&gt;       1
##  5     5 &lt;dbl [10]&gt; &lt;lgl [10]&gt;       4
##  6     6 &lt;dbl [10]&gt; &lt;lgl [10]&gt;       2
##  7     7 &lt;dbl [10]&gt; &lt;lgl [10]&gt;       1
##  8     8 &lt;dbl [10]&gt; &lt;lgl [10]&gt;       1
##  9     9 &lt;dbl [10]&gt; &lt;lgl [10]&gt;       2
## 10    10 &lt;dbl [10]&gt; &lt;lgl [10]&gt;       5
## # … with 990 more rows</code></pre>
<p>This is a bit of a programmer’s trick. In R, <code>less</code> contains a vector of 10 TRUE or FALSE values, according to whether the corresponding value in <code>sample</code> is less than 40 or not. In R (and many other programming languages), the numeric value of TRUE is 1 and of FALSE is 0, so you count how many TRUE values there are by adding them up. To verify that this worked, we should <code>unnest</code> <code>sample</code> and <code>less</code>:</p>
<div class="sourceCode" id="cb146"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb146-1" title="1"><span class="kw">set.seed</span>(<span class="dv">457299</span>)</a>
<a class="sourceLine" id="cb146-2" title="2"><span class="kw">tibble</span>(<span class="dt">sim =</span> <span class="dv">1</span><span class="op">:</span><span class="dv">1000</span>) <span class="op">%&gt;%</span><span class="st"> </span></a>
<a class="sourceLine" id="cb146-3" title="3"><span class="st">  </span><span class="kw">rowwise</span>() <span class="op">%&gt;%</span><span class="st"> </span></a>
<a class="sourceLine" id="cb146-4" title="4"><span class="st">  </span><span class="kw">mutate</span>(<span class="dt">sample =</span> <span class="kw">list</span>(<span class="kw">rnorm</span>(<span class="dv">10</span>, <span class="dv">50</span>, <span class="dv">15</span>))) <span class="op">%&gt;%</span><span class="st"> </span></a>
<a class="sourceLine" id="cb146-5" title="5"><span class="st">  </span><span class="kw">mutate</span>(<span class="dt">less =</span> <span class="kw">list</span>(sample<span class="op">&lt;</span><span class="dv">40</span>)) <span class="op">%&gt;%</span><span class="st"> </span></a>
<a class="sourceLine" id="cb146-6" title="6"><span class="st">  </span><span class="kw">mutate</span>(<span class="dt">counted =</span> <span class="kw">sum</span>(less)) <span class="op">%&gt;%</span><span class="st"> </span></a>
<a class="sourceLine" id="cb146-7" title="7"><span class="st">  </span><span class="kw">unnest</span>(<span class="kw">c</span>(sample, less))</a></code></pre></div>
<pre><code>## # A tibble: 10,000 x 4
##      sim sample less  counted
##    &lt;int&gt;  &lt;dbl&gt; &lt;lgl&gt;   &lt;int&gt;
##  1     1   74.3 FALSE       3
##  2     1   38.8 TRUE        3
##  3     1   46.0 FALSE       3
##  4     1   39.5 TRUE        3
##  5     1   53.2 FALSE       3
##  6     1   60.6 FALSE       3
##  7     1   33.8 TRUE        3
##  8     1   61.9 FALSE       3
##  9     1   50.1 FALSE       3
## 10     1   66.4 FALSE       3
## # … with 9,990 more rows</code></pre>
<p>In the first sample, 38.8, 39.5, and 33.8 are less than 40, correctly identified so in <code>less</code>, and the <code>counted</code> column shows that the first sample did indeed have 3 values less than 40. You can check a few of the others as well, enough to convince yourself that this is working.</p>
<p>Next, the sign test will reject if there are 0, 1, 9 or 10 values less than 40 (you might be guessing that the last two will be pretty unlikely), so make a column called <code>reject</code> that encapsulates that, and then count how many times you rejected in your simulations. I don’t need my <code>unnest</code> any more; that was just to check that everything was working so far:</p>
<div class="sourceCode" id="cb148"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb148-1" title="1"><span class="kw">set.seed</span>(<span class="dv">457299</span>)</a>
<a class="sourceLine" id="cb148-2" title="2"><span class="kw">tibble</span>(<span class="dt">sim =</span> <span class="dv">1</span><span class="op">:</span><span class="dv">1000</span>) <span class="op">%&gt;%</span><span class="st"> </span></a>
<a class="sourceLine" id="cb148-3" title="3"><span class="st">  </span><span class="kw">rowwise</span>() <span class="op">%&gt;%</span><span class="st"> </span></a>
<a class="sourceLine" id="cb148-4" title="4"><span class="st">  </span><span class="kw">mutate</span>(<span class="dt">sample =</span> <span class="kw">list</span>(<span class="kw">rnorm</span>(<span class="dv">10</span>, <span class="dv">50</span>, <span class="dv">15</span>))) <span class="op">%&gt;%</span><span class="st"> </span></a>
<a class="sourceLine" id="cb148-5" title="5"><span class="st">  </span><span class="kw">mutate</span>(<span class="dt">less =</span> <span class="kw">list</span>(sample<span class="op">&lt;</span><span class="dv">40</span>)) <span class="op">%&gt;%</span><span class="st"> </span></a>
<a class="sourceLine" id="cb148-6" title="6"><span class="st">  </span><span class="kw">mutate</span>(<span class="dt">counted =</span> <span class="kw">sum</span>(less)) <span class="op">%&gt;%</span><span class="st"> </span></a>
<a class="sourceLine" id="cb148-7" title="7"><span class="st">  </span><span class="kw">mutate</span>(<span class="dt">reject =</span> (counted<span class="op">&lt;=</span><span class="dv">1</span> <span class="op">|</span><span class="st"> </span>counted <span class="op">&gt;=</span><span class="st"> </span><span class="dv">9</span>)) <span class="op">%&gt;%</span><span class="st"> </span></a>
<a class="sourceLine" id="cb148-8" title="8"><span class="st">  </span><span class="kw">count</span>(reject)</a></code></pre></div>
<pre><code>## # A tibble: 2 x 2
## # Rowwise: 
##   reject     n
##   &lt;lgl&gt;  &lt;int&gt;
## 1 FALSE    757
## 2 TRUE     243</code></pre>
<p>My simulated power is 0.243</p>
<p>This is all liable to go wrong the first few times, so make sure that
each line works before you go on to the next, as I did.
While you’re debugging, try it with a
small number of random samples like 5. (It is smart to have a variable called <code>nsim</code> which you set to a small number like 5 when you are testing, and than to 1000 when you run the real thing, so that the first line of the pipeline is then <code>tibble(sim = 1:nsim)</code>.)</p>
<p>If you were handing something like this in, I would only want to see your code for the final pipeline that does everything, though you could and should have some words that describe what you did.</p>
<p>I’m now thinking a better way to do this is to write a function that
takes a sample (in a vector) and returns a TRUE or FALSE according to
whether or not a median of 40 would be rejected for that sample:</p>
<div class="sourceCode" id="cb150"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb150-1" title="1">is_reject=<span class="cf">function</span>(x) {</a>
<a class="sourceLine" id="cb150-2" title="2">  <span class="kw">tibble</span>(<span class="dt">x=</span>x) <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb150-3" title="3"><span class="st">    </span><span class="kw">mutate</span>(<span class="dt">counted =</span> (x <span class="op">&lt;</span><span class="st"> </span><span class="dv">40</span>)) <span class="op">%&gt;%</span><span class="st"> </span></a>
<a class="sourceLine" id="cb150-4" title="4"><span class="st">    </span><span class="kw">summarize</span>(<span class="dt">below =</span> <span class="kw">sum</span>(counted)) <span class="op">%&gt;%</span><span class="st"> </span></a>
<a class="sourceLine" id="cb150-5" title="5"><span class="st">    </span><span class="kw">summarize</span>(<span class="dt">is_rejected =</span> (below<span class="op">&lt;=</span><span class="dv">1</span> <span class="op">|</span><span class="st"> </span>below<span class="op">&gt;=</span><span class="dv">9</span>)) <span class="op">%&gt;%</span><span class="st"> </span></a>
<a class="sourceLine" id="cb150-6" title="6"><span class="st">    </span><span class="kw">pull</span>(is_rejected)</a>
<a class="sourceLine" id="cb150-7" title="7">}</a>
<a class="sourceLine" id="cb150-8" title="8"><span class="kw">is_reject</span>(<span class="kw">c</span>(<span class="dv">35</span>, <span class="dv">45</span>, <span class="dv">55</span>))</a></code></pre></div>
<pre><code>## [1] TRUE</code></pre>
<div class="sourceCode" id="cb152"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb152-1" title="1"><span class="kw">is_reject</span>(<span class="kw">c</span>(<span class="dv">35</span>, <span class="dv">38</span>, <span class="dv">45</span>, <span class="dv">55</span>))</a></code></pre></div>
<pre><code>## [1] FALSE</code></pre>
<p>Now, we have to use that:</p>
<div class="sourceCode" id="cb154"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb154-1" title="1"><span class="kw">set.seed</span>(<span class="dv">457299</span>)</a>
<a class="sourceLine" id="cb154-2" title="2"><span class="kw">tibble</span>(<span class="dt">sim =</span> <span class="dv">1</span><span class="op">:</span><span class="dv">1000</span>) <span class="op">%&gt;%</span><span class="st"> </span></a>
<a class="sourceLine" id="cb154-3" title="3"><span class="st">  </span><span class="kw">rowwise</span>() <span class="op">%&gt;%</span><span class="st"> </span></a>
<a class="sourceLine" id="cb154-4" title="4"><span class="st">  </span><span class="kw">mutate</span>(<span class="dt">sample =</span> <span class="kw">list</span>(<span class="kw">rnorm</span>(<span class="dv">10</span>, <span class="dv">50</span>, <span class="dv">15</span>))) <span class="op">%&gt;%</span><span class="st"> </span></a>
<a class="sourceLine" id="cb154-5" title="5"><span class="st">  </span><span class="kw">mutate</span>(<span class="dt">reject =</span> <span class="kw">is_reject</span>(sample)) <span class="op">%&gt;%</span><span class="st"> </span></a>
<a class="sourceLine" id="cb154-6" title="6"><span class="st">  </span><span class="kw">count</span>(reject)</a></code></pre></div>
<pre><code>## # A tibble: 2 x 2
## # Rowwise: 
##   reject     n
##   &lt;lgl&gt;  &lt;int&gt;
## 1 FALSE    757
## 2 TRUE     243</code></pre>
<p>This is a bit cleaner because the process of deciding whether each sample leads to a rejection of the median being 40 has been “outsourced” to the function, and the pipeline with the <code>rowwise</code> is a lot cleaner: take a sample, decide whether that sample leads to rejection, and count up the rejections.</p>
<p><span class="math inline">\(\blacksquare\)</span></p>
<ol start="6" style="list-style-type: lower-alpha">
<li>Which is more powerful in this case, the sign test or the
<span class="math inline">\(t\)</span>-test? How do you know?</li>
</ol>
<p>Solution</p>
<p>The power of the sign test is estimated as 0.243, which is quite a bit less
than the power of the <span class="math inline">\(t\)</span>-test, which we found back in (a) to be
0.469. So the <span class="math inline">\(t\)</span>-test, in this situation where it is valid, is
the right test to use: it is (i) valid and (ii) more powerful.
So the <span class="math inline">\(t\)</span>-test is more powerful. One way to think about how
<em>much</em> more powerful is to ask “how much smaller of a sample size would be needed for the <span class="math inline">\(t\)</span>-test to have the same power as this sign test?”
The power of my sign test was 0.243, so in
<code>power.t.test</code> we set
<code>power</code> equal to that and
omit the sample size <code>n</code>:</p>
<div class="sourceCode" id="cb156"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb156-1" title="1"><span class="kw">power.t.test</span>(<span class="dt">delta=</span><span class="dv">50-40</span>,<span class="dt">power=</span><span class="fl">0.243</span>,<span class="dt">sd=</span><span class="dv">15</span>,<span class="dt">type=</span><span class="st">&quot;one.sample&quot;</span>,<span class="dt">alternative=</span><span class="st">&quot;two.sided&quot;</span>)</a></code></pre></div>
<pre><code>## 
##      One-sample t test power calculation 
## 
##               n = 5.599293
##           delta = 10
##              sd = 15
##       sig.level = 0.05
##           power = 0.243
##     alternative = two.sided</code></pre>
<p>A sample of size 6 gives the same power for the <span class="math inline">\(t\)</span>-test that a
sample of size 10 does for the sign test. The ratio of these two
sample sizes is called the <em>relative efficiency</em> of the two
tests: in this case, the <span class="math inline">\(t\)</span>-test is <span class="math inline">\(10/6=1.67\)</span> times more
efficient. The data that you have are being used “more efficiently”
by the <span class="math inline">\(t\)</span>-test.
It is possible to derive<a href="#fn2" class="footnote-ref" id="fnref2"><sup>2</sup></a><br />
the limiting relative efficiency of
the <span class="math inline">\(t\)</span> test relative to the sign test when the data are actually
normal, as the sample size gets larger. This turns out not to
depend on how far wrong the null is (as long as it is the same for
both the <span class="math inline">\(t\)</span>-test and the sign test). This “asymptotic relative efficiency” is <span class="math inline">\(\pi/2=1.57\)</span>.
Our relative efficiency for power
0.243, namely 1.67, was pretty close to this, even though our
sample sizes 10 and 6 are not especially close to infinity.
This says that, if your data are actually from a normal
distribution, you do a lot better to use the <span class="math inline">\(t\)</span>-test than the
sign test, because the sign test is wasteful of data (it only uses
above/below rather than the actual values).</p>
<p>Extra: if your data are <em>not</em> from a normal distribution, then the
story can be very different.
Of course you knew I would investigate this. There is a
distribution called the “Laplace” or “double exponential”
distribution, that has very long tails.<a href="#fn3" class="footnote-ref" id="fnref3"><sup>3</sup></a>
The distribution is not in
base R, but there is a package called <code>smoothmest</code> that
contains a function <code>rdoublex</code> to generate random values from
this distribution. So we’re going to do a simulation investigation
of the power of the sign test for Laplace data, by the same
simulation technique that we did above. Like the normal, the Laplace
distribution is symmetric, so its mean and median are the same
(which makes our life easier).<a href="#fn4" class="footnote-ref" id="fnref4"><sup>4</sup></a></p>
<p>Let’s test the hypothesis that the median is zero. We’ll suppose that
the true median is 0.5 (this is called <code>mu</code> in
<code>rdoublex</code>). The first problem we run into is that we can’t use
<code>power.t.test</code> because they assume normal data, which we are
far from having. So we have to do two simulations: one to simulate the
power of the <span class="math inline">\(t\)</span> test, and one to simulate the power of the sign test.</p>
<p>To simulate the <span class="math inline">\(t\)</span> test, we first have to generate some Laplace data
with the true mean of 0.5. We’ll use a sample size of 50 throughout
these simulations.</p>
<div class="sourceCode" id="cb158"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb158-1" title="1"><span class="kw">library</span>(smoothmest)</a>
<a class="sourceLine" id="cb158-2" title="2">rl &lt;-<span class="st"> </span><span class="kw">rdoublex</span>(<span class="dv">50</span>,<span class="dt">mu=</span><span class="fl">0.5</span>)</a>
<a class="sourceLine" id="cb158-3" title="3">rl</a></code></pre></div>
<pre><code>##  [1] -0.33323285  0.70569291 -1.22513053  0.68517708  0.87221482  0.49250051  0.26700527  1.90236874  0.53288312  1.37374732  0.72743434  0.46634071  0.43581431 -0.01545866  0.18594908 -0.40403202 -0.13540289  0.83862694 -0.23360644
## [20] -0.74050354  2.92089551 -2.72173880  0.51571185  1.23636045  0.82921382  1.72456334  0.07903058  0.74789589  0.90487190  2.52310082  3.13629814  0.81851434  0.74615575 -0.26068744  2.70683355  1.46981530  1.45646489  1.20232517
## [39]  6.65249860 -0.51575026 -0.07606399  2.11338640 -1.20427995  1.70986104 -1.66466321  0.55346854  0.33908531  0.72100677  0.92025176  0.98922656</code></pre>
<p>This seems to have some unusual values, far away from zero:</p>
<div class="sourceCode" id="cb160"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb160-1" title="1"><span class="kw">tibble</span>(rl) <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb160-2" title="2"><span class="kw">ggplot</span>(<span class="kw">aes</span>(<span class="dt">sample=</span>rl))<span class="op">+</span></a>
<a class="sourceLine" id="cb160-3" title="3"><span class="kw">stat_qq</span>()<span class="op">+</span><span class="kw">stat_qq_line</span>()</a></code></pre></div>
<p><img src="pasias_files/figure-html/unnamed-chunk-105-1.png" width="672" /></p>
<p>You see the long tails compared to the normal.</p>
<p>Now, we feed these values into <code>t.test</code> and see whether we
reject a null median of zero (at <span class="math inline">\(\alpha=0.05\)</span>):</p>
<div class="sourceCode" id="cb161"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb161-1" title="1">tt &lt;-<span class="st"> </span><span class="kw">t.test</span>(rl)  </a>
<a class="sourceLine" id="cb161-2" title="2">tt</a></code></pre></div>
<pre><code>## 
##  One Sample t-test
## 
## data:  rl
## t = 3.72, df = 49, p-value = 0.0005131
## alternative hypothesis: true mean is not equal to 0
## 95 percent confidence interval:
##  0.3399906 1.1388911
## sample estimates:
## mean of x 
## 0.7394408</code></pre>
<p>Or we can just pull out the P-value and even compare it to 0.05:</p>
<div class="sourceCode" id="cb163"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb163-1" title="1">pval &lt;-<span class="st"> </span>tt<span class="op">$</span>p.value  </a>
<a class="sourceLine" id="cb163-2" title="2">pval</a></code></pre></div>
<pre><code>## [1] 0.0005130841</code></pre>
<div class="sourceCode" id="cb165"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb165-1" title="1">is.reject &lt;-<span class="st"> </span>(pval<span class="op">&lt;=</span><span class="fl">0.05</span>)</a>
<a class="sourceLine" id="cb165-2" title="2">is.reject</a></code></pre></div>
<pre><code>## [1] TRUE</code></pre>
<p>This one has a small P-value and so the null median of 0 should be
(correctly) rejected.</p>
<p>We’ll use these ideas to simulate the power of the <span class="math inline">\(t\)</span>-test for these
data, testing a mean of 0. This uses the same ideas as for any power
simulation; the difference here is the true distribution:</p>
<div class="sourceCode" id="cb167"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb167-1" title="1"><span class="kw">tibble</span>(<span class="dt">sim =</span> <span class="dv">1</span><span class="op">:</span><span class="dv">1000</span>) <span class="op">%&gt;%</span><span class="st"> </span></a>
<a class="sourceLine" id="cb167-2" title="2"><span class="st">  </span><span class="kw">rowwise</span>() <span class="op">%&gt;%</span><span class="st"> </span></a>
<a class="sourceLine" id="cb167-3" title="3"><span class="st">  </span><span class="kw">mutate</span>(<span class="dt">sample =</span> <span class="kw">list</span>(<span class="kw">rdoublex</span>(<span class="dv">50</span>, <span class="dt">mu =</span> <span class="fl">0.5</span>))) <span class="op">%&gt;%</span><span class="st"> </span></a>
<a class="sourceLine" id="cb167-4" title="4"><span class="st">  </span><span class="kw">mutate</span>(<span class="dt">t_test =</span> <span class="kw">list</span>(<span class="kw">t.test</span>(sample, <span class="dt">mu =</span> <span class="dv">0</span>))) <span class="op">%&gt;%</span><span class="st"> </span></a>
<a class="sourceLine" id="cb167-5" title="5"><span class="st">  </span><span class="kw">mutate</span>(<span class="dt">t_pval =</span> t_test<span class="op">$</span>p.value) <span class="op">%&gt;%</span><span class="st"> </span></a>
<a class="sourceLine" id="cb167-6" title="6"><span class="st">  </span><span class="kw">count</span>(t_pval <span class="op">&lt;=</span><span class="st"> </span><span class="fl">0.05</span>)</a></code></pre></div>
<pre><code>## # A tibble: 2 x 2
## # Rowwise: 
##   `t_pval &lt;= 0.05`     n
##   &lt;lgl&gt;            &lt;int&gt;
## 1 FALSE              298
## 2 TRUE               702</code></pre>
<p>And now we simulate the sign test. Since what we want is a P-value
from a vector, the easiest way to do this is to use
<code>pval_sign0</code> from <code>smmr</code>, which returns exactly the
two-sided P-value that we want, so that the procedure is a step simpler:</p>
<div class="sourceCode" id="cb169"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb169-1" title="1"><span class="kw">tibble</span>(<span class="dt">sim =</span> <span class="dv">1</span><span class="op">:</span><span class="dv">1000</span>) <span class="op">%&gt;%</span><span class="st"> </span></a>
<a class="sourceLine" id="cb169-2" title="2"><span class="st">  </span><span class="kw">rowwise</span>() <span class="op">%&gt;%</span><span class="st"> </span></a>
<a class="sourceLine" id="cb169-3" title="3"><span class="st">  </span><span class="kw">mutate</span>(<span class="dt">sample =</span> <span class="kw">list</span>(<span class="kw">rdoublex</span>(<span class="dv">50</span>, <span class="dt">mu =</span> <span class="fl">0.5</span>))) <span class="op">%&gt;%</span><span class="st"> </span></a>
<a class="sourceLine" id="cb169-4" title="4"><span class="st">  </span><span class="kw">mutate</span>(<span class="dt">sign_pval =</span> <span class="kw">pval_sign0</span>(<span class="dv">0</span>, sample)) <span class="op">%&gt;%</span><span class="st"> </span></a>
<a class="sourceLine" id="cb169-5" title="5"><span class="st">  </span><span class="kw">count</span>(sign_pval <span class="op">&lt;=</span><span class="st"> </span><span class="fl">0.05</span>)</a></code></pre></div>
<pre><code>## # A tibble: 2 x 2
## # Rowwise: 
##   `sign_pval &lt;= 0.05`     n
##   &lt;lgl&gt;               &lt;int&gt;
## 1 FALSE                 228
## 2 TRUE                  772</code></pre>
<p>For data from this Laplace
distribution, the power of this <span class="math inline">\(t\)</span>-test is 0.696, but the power of
the sign test on the same data is 0.761, <em>bigger</em>. For
Laplace-distributed data, the sign test is <em>more</em> powerful than
the <span class="math inline">\(t\)</span>-test.</p>
<p>This is not to say that you will ever run into data that comes from
the Laplace distribution. But the moral of the story is that the sign
test <em>can</em> be more powerful than the <span class="math inline">\(t\)</span>-test, under the right
circumstances (and the above simulation is the “proof” of that
statement). So a blanket statement like “the sign test is not very powerful”
needs to be qualified a bit: when your data come from a
sufficiently long-tailed distribution, the sign test can be more
powerful relative to the <span class="math inline">\(t\)</span>-test than you would think.</p>
<p><span class="math inline">\(\blacksquare\)</span></p>
</div>
<div id="ben-roethlisberger-1" class="section level2">
<h2><span class="header-section-number">9.9</span> Ben Roethlisberger</h2>
<p>Ben Roethlisberger plays (American) football for the Pittsburgh Steelers. He plays as a quarterback, which means that his job is to throw (pass) the ball so that one of his teammates can catch it. Each time he makes a pass that is caught, this is called a “completion”, and the team coaches are interested in his average number of completions per game (this average could be the mean or the median).</p>
<p>In 2010, Roethlisberger was suspended for the first four games of the season, and there was concern that this might affect his performance (in terms of the number of passes completed in the games after he returned). The Pittsburgh Steelers did not play in week 5 of the 2010 season; the season is 17 weeks long (one game per week) and each team has one week in which they do not play.</p>
<p>The data are <a href="http://ritsokiguess.site/datafiles/roethlisberger.csv">here</a>. There are four columns: the year (always 2010), the week number of the season that the game was played in, the name of the opposing team, and the number of completed passes by Roethlisberger in the game.</p>
<ol style="list-style-type: lower-alpha">
<li>Read in and display (some of) the data. Do you have what you were expecting?</li>
</ol>
<p>Solution</p>
<p>Reading in is the usual, noting that this is a <code>.csv</code>:</p>
<div class="sourceCode" id="cb171"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb171-1" title="1">my_url &lt;-<span class="st"> &quot;http://ritsokiguess.site/datafiles/roethlisberger.csv&quot;</span></a>
<a class="sourceLine" id="cb171-2" title="2">ben &lt;-<span class="st"> </span><span class="kw">read_csv</span>(my_url)</a></code></pre></div>
<pre><code>## 
## ── Column specification ──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
## cols(
##   season = col_double(),
##   week = col_double(),
##   opponent = col_character(),
##   completed = col_double()
## )</code></pre>
<div class="sourceCode" id="cb173"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb173-1" title="1">ben</a></code></pre></div>
<pre><code>## # A tibble: 12 x 4
##    season  week opponent      completed
##     &lt;dbl&gt; &lt;dbl&gt; &lt;chr&gt;             &lt;dbl&gt;
##  1   2010     6 Cleveland            16
##  2   2010     7 Miami                19
##  3   2010     8 New Orleans          17
##  4   2010     9 Cincinnati           17
##  5   2010    10 New England          30
##  6   2010    11 Oakland              18
##  7   2010    12 Buffalo              20
##  8   2010    13 Baltimore            22
##  9   2010    14 Cincinnati           21
## 10   2010    15 New York Jets        23
## 11   2010    16 Carolina             22
## 12   2010    17 Cleveland            15</code></pre>
<p>Since “Roethlisberger” is a lot to type every time, I called the dataframe by his first name.</p>
<p>I am showing all 12 rows here; you are probably seeing only 10, and will have to scroll down to see the last two.</p>
<p>I have the four variables promised, and I also have a sensible number of rows. In particular, there is no data for weeks 1–4 (the suspension) and for week 5 (in which the team did not play), but there is a number of passes completed for all the other weeks of the season up to week 17. (If Roethlisberger had not played in any other games, you can expect that I would have told you about it.)</p>
<p>Extra: I did some processing to get the data to this point. I wanted to ask you about the 2010 season, and that meant having the 2009 data to compare it with. So I went <a href="https://www.pro-football-reference.com/teams/pit/2009.htm">here</a>, scrolled down to Schedule and Game Results, and clicked on each of the Boxscores to get the player stats by game. Then I made a note of the opponent and the number of passes completed, and did the same for 2010. I put them in a file I called <code>r1.txt</code>, in aligned columns, and read that in. (An alternative would have been to make a spreadsheet and save that as a <code>.csv</code>, but I already had R Studio open.) Thus:</p>
<div class="sourceCode" id="cb175"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb175-1" title="1">r0 &lt;-<span class="st"> </span><span class="kw">read_table</span>(<span class="st">&quot;r1.txt&quot;</span>)</a></code></pre></div>
<pre><code>## 
## ── Column specification ──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
## cols(
##   season = col_double(),
##   week = col_double(),
##   opponent = col_character(),
##   completed = col_double()
## )</code></pre>
<div class="sourceCode" id="cb177"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb177-1" title="1">r0</a></code></pre></div>
<pre><code>## # A tibble: 27 x 4
##    season  week opponent    completed
##     &lt;dbl&gt; &lt;dbl&gt; &lt;chr&gt;           &lt;dbl&gt;
##  1   2009     1 Tennessee          33
##  2   2009     2 Chicago            23
##  3   2009     3 Cincinnati         22
##  4   2009     4 San Diego          26
##  5   2009     5 Detroit            23
##  6   2009     6 Cleveland          23
##  7   2009     7 Minnesota          14
##  8   2009     9 Denver             21
##  9   2009    10 Cincinnati         20
## 10   2009    11 Kansas City        32
## # … with 17 more rows</code></pre>
<p>I was curious about the season medians (for reasons you see later), thus:</p>
<div class="sourceCode" id="cb179"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb179-1" title="1">r0 <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">group_by</span>(season) <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">summarise</span>(<span class="dt">med =</span> <span class="kw">median</span>(completed))</a></code></pre></div>
<pre><code>## # A tibble: 2 x 2
##   season   med
##    &lt;dbl&gt; &lt;dbl&gt;
## 1   2009  22  
## 2   2010  19.5</code></pre>
<p>You will realize that my asserted average for “previous seasons” is close to the median for 2009. Here is where I have to admit that I cheated. It actually <em>is</em> the median for 2009, except that there are some games in 2010 where Roethlisberger had 22 completed passes and I didn’t want to mess the sign test up (I talk more about this later). So I made it 22.5, which is a possible value for the median of an even number of whole-number values.</p>
<p>Anyway, the last thing to do is to grab only the rows for 2010 and save them for you. This uses <code>filter</code> to select only the rows for which something is true:</p>
<div class="sourceCode" id="cb181"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb181-1" title="1"><span class="kw">library</span>(smmr)</a>
<a class="sourceLine" id="cb181-2" title="2">r0 <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">filter</span>(season<span class="op">==</span><span class="dv">2010</span>) -&gt;<span class="st"> </span>r1</a>
<a class="sourceLine" id="cb181-3" title="3"><span class="kw">write_csv</span>(r1, <span class="st">&quot;roethlisberger.csv&quot;</span>)</a></code></pre></div>
<p><span class="math inline">\(\blacksquare\)</span></p>
<ol start="2" style="list-style-type: lower-alpha">
<li>Make a suitable graph of the number of completed passes, and explain briefly why you would have some doubts about using <span class="math inline">\(t\)</span>-procedures in this situation.</li>
</ol>
<p>Solution</p>
<p>Don’t be tempted to think <em>too</em> hard about the choice of graph (though I talk more about this below). One quantitative variable, so a histogram again. There are only 12 observations, so 5 bins is about as high as you should go:</p>
<div class="sourceCode" id="cb182"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb182-1" title="1"><span class="kw">ggplot</span>(ben, <span class="kw">aes</span>(<span class="dt">x=</span>completed)) <span class="op">+</span><span class="st"> </span><span class="kw">geom_histogram</span>(<span class="dt">bins=</span><span class="dv">5</span>)</a></code></pre></div>
<p><img src="pasias_files/figure-html/unnamed-chunk-114-1.png" width="672" /></p>
<p>This one shows an outlier: there is one number of completed passes that is noticeably higher than the rest. A normal distribution doesn’t have outliers, and so this, coupled with a small sample in which normality is important, means that we should not be using a <span class="math inline">\(t\)</span>-test or confidence interval.</p>
<p>If you chose a different number of bins, you might get a different look. Here’s 4 bins:</p>
<div class="sourceCode" id="cb183"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb183-1" title="1"><span class="kw">ggplot</span>(ben, <span class="kw">aes</span>(<span class="dt">x=</span>completed)) <span class="op">+</span><span class="st"> </span><span class="kw">geom_histogram</span>(<span class="dt">bins=</span><span class="dv">4</span>)</a></code></pre></div>
<p><img src="pasias_files/figure-html/unnamed-chunk-115-1.png" width="672" /></p>
<p>That looks more like right-skewness, but the conclusion is the same.</p>
<p>Extra: if you have read, for example, <a href="http://ritsokiguess.site/datafiles/pasias/one-sample-inference.html#hunter-gatherers-in-australia">Problem 6.1 in PASIAS</a>, you’ll have seen that another possibility is a one-group boxplot. This might have been the context in which you first saw the boxplot, maybe at about the time you first saw the five-number summary, but I don’t talk about that so much in this course because <code>ggplot</code> boxplots have both an <code>x</code> and a <code>y</code>, and it makes more sense to think about using boxplots to <em>compare</em> groups. But, you can certainly get R to make you a one-sample boxplot. What you do is to set the grouping variable to a “dummy” thing like the number 1:</p>
<div class="sourceCode" id="cb184"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb184-1" title="1"><span class="kw">ggplot</span>(ben, <span class="kw">aes</span>(<span class="dt">x=</span><span class="dv">1</span>, <span class="dt">y=</span>completed)) <span class="op">+</span><span class="st"> </span><span class="kw">geom_boxplot</span>()</a></code></pre></div>
<p><img src="pasias_files/figure-html/unnamed-chunk-116-1.png" width="672" />
and then you ignore the <span class="math inline">\(x\)</span>-axis.</p>
<p>This really shows off the outlier; it is actually <em>much</em> bigger than the other observations. It didn’t show up so much on the histograms because of where the bin boundaries happened to come. On the four-bin histogram, the highest value 30 was in the 27.5–32.5 bin, and the second-highest value 23 was at the bottom of the 22.5–27.5 bin. So the highest and second-highest values looked closer together than they actually were.</p>
<p>If you have been reading ahead, you might also be thinking about a normal quantile plot. That is for specifically assessing normality, and here this is something that interests us, because a <span class="math inline">\(t\)</span>-test will be doubtful if the normality fails:</p>
<div class="sourceCode" id="cb185"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb185-1" title="1"><span class="kw">ggplot</span>(ben, <span class="kw">aes</span>(<span class="dt">sample=</span>completed)) <span class="op">+</span><span class="st"> </span><span class="kw">stat_qq</span>() <span class="op">+</span><span class="st"> </span><span class="kw">stat_qq_line</span>()</a></code></pre></div>
<p><img src="pasias_files/figure-html/unnamed-chunk-117-1.png" width="672" />
This again shows off the outlier at the high end. It is a reasonable choice of plot <em>here</em> because normality is of specific interest to us.</p>
<p>A note: you are absolutely not required to read ahead to future lectures. Each assignment can be done using the material in the indicated lectures only. If you want to use something from future lectures, go ahead, but make sure you are using it appropriately.</p>
<p>Don’t be tempted to plot the number of completed passes against something like week number:</p>
<div class="sourceCode" id="cb186"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb186-1" title="1"><span class="kw">ggplot</span>(ben, <span class="kw">aes</span>(<span class="dt">x=</span>week, <span class="dt">y=</span>completed)) <span class="op">+</span><span class="st"> </span><span class="kw">geom_point</span>()</a></code></pre></div>
<p><img src="pasias_files/figure-html/unnamed-chunk-118-1.png" width="672" />
That is quite interesting (a mostly increasing trend over weeks, with the outlier performance in week 10), but it doesn’t tell us what we want to know <em>here</em>: namely, is a <span class="math inline">\(t\)</span>-test any good?</p>
<p><span class="math inline">\(\blacksquare\)</span></p>
<ol start="3" style="list-style-type: lower-alpha">
<li>Run a sign test to compare Roethlisberger’s performance in 2010 with his previous average of 22.5 completions per game. What do you conclude?</li>
</ol>
<p>Solution</p>
<p>Use <code>smmr</code>, dataframe, column, null median:</p>
<div class="sourceCode" id="cb187"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb187-1" title="1"><span class="kw">sign_test</span>(ben, completed, <span class="fl">22.5</span>)</a></code></pre></div>
<pre><code>## $above_below
## below above 
##    10     2 
## 
## $p_values
##   alternative    p_value
## 1       lower 0.01928711
## 2       upper 0.99682617
## 3   two-sided 0.03857422</code></pre>
<p>I am looking for <em>any</em> change, so for me, a two-sided test is appropriate. If you think this is one-sided, make a case for your side, and then go ahead.</p>
<p>My P-value is 0.039, so I can reject the null hypothesis (that the median number of passes completed is 22.5) and conclude that it has changed in 2010.</p>
<p>(You might hypothesize that this is the result of a decrease in confidence, that he is either throwing fewer passes, or the ones that he is throwing are harder to catch. If you know about football, you might suspect that Roethlisberger was actually passing <em>too much</em>, including in situations where he should have handing off to the running back, instead of reading the game appropriately.)</p>
<p>Extra: I said above that I cheated and made the null median 22.5 instead of 22. What happens if we make the null median 22?</p>
<div class="sourceCode" id="cb189"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb189-1" title="1"><span class="kw">sign_test</span>(ben, completed, <span class="dv">22</span>)</a></code></pre></div>
<pre><code>## $above_below
## below above 
##     8     2 
## 
## $p_values
##   alternative   p_value
## 1       lower 0.0546875
## 2       upper 0.9892578
## 3   two-sided 0.1093750</code></pre>
<p>For one thing, the result is no longer significant. But looking at the table of values above and below reveals something odd: there are only ten values. What happened to the other two? What happened is that two of the data values were exactly equal to 22, so they are neither above nor below. In the sign test, they are thrown away, so that we are left with 8 values below 22 and 2 above.</p>
<p>I didn’t want to make you wonder what happened, so I made the null median 22.5.</p>
<p><span class="math inline">\(\blacksquare\)</span></p>
<ol start="4" style="list-style-type: lower-alpha">
<li>Why might you have expected your sign test to come out significant, even without looking at the P-value? Explain briefly.</li>
</ol>
<p>Solution</p>
<p>The other ingredient to the sign test is how many data values are above and below the null median. You can look at the output from <code>sign_test</code> (the first part), or count them yourself:</p>
<div class="sourceCode" id="cb191"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb191-1" title="1">ben <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">count</span>(completed<span class="op">&lt;</span><span class="fl">22.5</span>)</a></code></pre></div>
<pre><code>## # A tibble: 2 x 2
##   `completed &lt; 22.5`     n
##   &lt;lgl&gt;              &lt;int&gt;
## 1 FALSE                  2
## 2 TRUE                  10</code></pre>
<p>You can put a logical condition (something that can be true or false) into <code>count</code>, or you can create a new column using <code>ifelse</code> (which I think I showed you somewhere):</p>
<div class="sourceCode" id="cb193"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb193-1" title="1">ben <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">mutate</span>(<span class="dt">side =</span> <span class="kw">ifelse</span>(completed<span class="op">&lt;</span><span class="fl">22.5</span>, <span class="st">&quot;below&quot;</span>, <span class="st">&quot;above&quot;</span>)) <span class="op">%&gt;%</span><span class="st"> </span></a>
<a class="sourceLine" id="cb193-2" title="2"><span class="kw">count</span>(side)</a></code></pre></div>
<pre><code>## # A tibble: 2 x 2
##   side      n
##   &lt;chr&gt; &lt;int&gt;
## 1 above     2
## 2 below    10</code></pre>
<p>Whichever way you do it, there seem to be a lot more values below than above, very different from a 50–50 split. Even with only 12 observations, this turns out to be enough to be significant. (If you tossed a fair coin 12 times, would you be surprised to get only 2 heads or 2 tails?)</p>
<p><span class="math inline">\(\blacksquare\)</span></p>
<ol start="5" style="list-style-type: lower-alpha">
<li>Obtain a 90% confidence interval for the median number of completed passes (over “all possible games played by 2010 Ben Roethlisberger”).</li>
</ol>
<p>Solution</p>
<p>This is <code>ci_median</code>, but with <code>conf.level</code> since you are not using the default level of 95%:</p>
<div class="sourceCode" id="cb195"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb195-1" title="1"><span class="kw">ci_median</span>(ben, completed, <span class="dt">conf.level =</span> <span class="fl">0.90</span>)</a></code></pre></div>
<pre><code>## [1] 17.00244 21.99878</code></pre>
<p>17 to 22 completed passes.</p>
<p>Extra: the P-value of the sign test only changes (as the null median changes) when you get to a data point; otherwise, the number of values above and below will stay the same, and the P-value will stay the same. The data values here were all whole numbers, so the limits of the confidence interval are also whole numbers (to the accuracy of the bisection), so the interval really should be rounded off.</p>
<p><span class="math inline">\(\blacksquare\)</span></p>
<ol start="6" style="list-style-type: lower-alpha">
<li>Find a 90% confidence interval for the <em>mean</em> number of passes completed, and explain briefly why it differs from the one for the median in the way that it does.</li>
</ol>
<p>Solution</p>
<p>All right, get the interval for the mean first:</p>
<div class="sourceCode" id="cb197"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb197-1" title="1"><span class="kw">with</span>(ben, <span class="kw">t.test</span>(completed, <span class="dt">conf.level =</span> <span class="fl">0.90</span>))</a></code></pre></div>
<pre><code>## 
##  One Sample t-test
## 
## data:  completed
## t = 17.033, df = 11, p-value = 2.971e-09
## alternative hypothesis: true mean is not equal to 0
## 90 percent confidence interval:
##  17.89124 22.10876
## sample estimates:
## mean of x 
##        20</code></pre>
<p>The 95% confidence interval for the mean goes from 17.9 to 22.1 (completions per game).</p>
<p>This is higher at both ends than the interval for the median, though possibly not as much as I expected. This is because the mean is made higher by the outlier (compared to the median), and so the CI procedure comes to the conclusion that the mean is higher.</p>
<p>Extra: this is one of those cases where the bootstrap might shed some light on the sampling distribution of the sample mean:</p>
<div class="sourceCode" id="cb199"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb199-1" title="1"><span class="kw">tibble</span>(<span class="dt">sim =</span> <span class="dv">1</span><span class="op">:</span><span class="dv">1000</span>) <span class="op">%&gt;%</span><span class="st"> </span></a>
<a class="sourceLine" id="cb199-2" title="2"><span class="st">  </span><span class="kw">rowwise</span>() <span class="op">%&gt;%</span><span class="st"> </span></a>
<a class="sourceLine" id="cb199-3" title="3"><span class="st">  </span><span class="kw">mutate</span>(<span class="dt">my_sample =</span> <span class="kw">list</span>(<span class="kw">sample</span>(ben<span class="op">$</span>completed, <span class="dt">replace =</span> <span class="ot">TRUE</span>))) <span class="op">%&gt;%</span><span class="st"> </span></a>
<a class="sourceLine" id="cb199-4" title="4"><span class="st">  </span><span class="kw">mutate</span>(<span class="dt">my_mean =</span> <span class="kw">mean</span>(my_sample)) <span class="op">%&gt;%</span><span class="st"> </span></a>
<a class="sourceLine" id="cb199-5" title="5"><span class="st">  </span><span class="kw">ggplot</span>(<span class="kw">aes</span>(<span class="dt">x =</span> my_mean)) <span class="op">+</span><span class="st"> </span><span class="kw">geom_histogram</span>(<span class="dt">bins =</span> <span class="dv">10</span>)</a></code></pre></div>
<p><img src="pasias_files/figure-html/unnamed-chunk-125-1.png" width="672" /></p>
<p>This is noticeably skewed to the right (it goes further up from the peak than down), which is why the CI for the mean went up a bit higher than the one for the median.</p>
<p>Finally, bootstrapping the median is not something you’d want to do, since the sign test doesn’t depend on anything being normally-distributed. This is a good thing, since bootstrapping the sample median is weird:</p>
<div class="sourceCode" id="cb200"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb200-1" title="1"><span class="kw">tibble</span>(<span class="dt">sim =</span> <span class="dv">1</span><span class="op">:</span><span class="dv">1000</span>) <span class="op">%&gt;%</span><span class="st"> </span></a>
<a class="sourceLine" id="cb200-2" title="2"><span class="st">  </span><span class="kw">rowwise</span>() <span class="op">%&gt;%</span><span class="st"> </span></a>
<a class="sourceLine" id="cb200-3" title="3"><span class="st">  </span><span class="kw">mutate</span>(<span class="dt">my_sample =</span> <span class="kw">list</span>(<span class="kw">sample</span>(ben<span class="op">$</span>completed, <span class="dt">replace =</span> <span class="ot">TRUE</span>))) <span class="op">%&gt;%</span><span class="st"> </span></a>
<a class="sourceLine" id="cb200-4" title="4"><span class="st">  </span><span class="kw">mutate</span>(<span class="dt">my_median =</span> <span class="kw">median</span>(my_sample)) <span class="op">%&gt;%</span><span class="st"> </span></a>
<a class="sourceLine" id="cb200-5" title="5"><span class="st">  </span><span class="kw">ggplot</span>(<span class="kw">aes</span>(<span class="dt">x =</span> my_median)) <span class="op">+</span><span class="st"> </span><span class="kw">geom_histogram</span>(<span class="dt">bins =</span> <span class="dv">30</span>)</a></code></pre></div>
<p><img src="pasias_files/figure-html/unnamed-chunk-126-1.png" width="672" /></p>
<p>The “holes” in the distribution comes about because there are not all that many different possible sample medians when you sample with replacement. For one thing, the values are all whole numbers, so the median can only be something or something and a half. Even then, the bar heights look kind of irregular.</p>
<p>I used a large number of bins to emphasize this, but even a more reasonable number looks strange:</p>
<div class="sourceCode" id="cb201"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb201-1" title="1"><span class="kw">tibble</span>(<span class="dt">sim =</span> <span class="dv">1</span><span class="op">:</span><span class="dv">1000</span>) <span class="op">%&gt;%</span><span class="st"> </span></a>
<a class="sourceLine" id="cb201-2" title="2"><span class="st">  </span><span class="kw">rowwise</span>() <span class="op">%&gt;%</span><span class="st"> </span></a>
<a class="sourceLine" id="cb201-3" title="3"><span class="st">  </span><span class="kw">mutate</span>(<span class="dt">my_sample =</span> <span class="kw">list</span>(<span class="kw">sample</span>(ben<span class="op">$</span>completed, <span class="dt">replace =</span> <span class="ot">TRUE</span>))) <span class="op">%&gt;%</span><span class="st"> </span></a>
<a class="sourceLine" id="cb201-4" title="4"><span class="st">  </span><span class="kw">mutate</span>(<span class="dt">my_median =</span> <span class="kw">median</span>(my_sample)) <span class="op">%&gt;%</span><span class="st"> </span></a>
<a class="sourceLine" id="cb201-5" title="5"><span class="st">  </span><span class="kw">ggplot</span>(<span class="kw">aes</span>(<span class="dt">x =</span> my_median)) <span class="op">+</span><span class="st"> </span><span class="kw">geom_histogram</span>(<span class="dt">bins =</span> <span class="dv">10</span>)</a></code></pre></div>
<p><img src="pasias_files/figure-html/unnamed-chunk-127-1.png" width="672" /></p>
<p>A sample median of 19 or 20 is more likely than one of 19.5.</p>
<p><span class="math inline">\(\blacksquare\)</span></p>
</div>
<div id="six-ounces-of-protein-1" class="section level2">
<h2><span class="header-section-number">9.10</span> Six ounces of protein</h2>
<p>A company produces prepackaged diet meals. These meals are advertised as containing “6 ounces of protein per package”. A consumer organization is concerned that this is not accurate. The organization takes a random sample of 20 of these meals, and measures the protein content of each one. The data are in <a href="http://ritsokiguess.site/datafiles/protein.txt">http://ritsokiguess.site/datafiles/protein.txt</a>
as one column.</p>
<ol style="list-style-type: lower-alpha">
<li>Read in and display (some of) the data.</li>
</ol>
<p>Solution</p>
<p>The usual. This is one column only, so you can pretend the columns are separated by anything at all and it will still work:</p>
<div class="sourceCode" id="cb202"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb202-1" title="1">my_url &lt;-<span class="st"> &quot;http://ritsokiguess.site/datafiles/protein.txt&quot;</span></a>
<a class="sourceLine" id="cb202-2" title="2">meals &lt;-<span class="st"> </span><span class="kw">read_table</span>(my_url)</a></code></pre></div>
<pre><code>## 
## ── Column specification ──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
## cols(
##   protein = col_double()
## )</code></pre>
<div class="sourceCode" id="cb204"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb204-1" title="1">meals <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">arrange</span>(protein)</a></code></pre></div>
<pre><code>## # A tibble: 20 x 1
##    protein
##      &lt;dbl&gt;
##  1     3.6
##  2     4.2
##  3     4.3
##  4     4.4
##  5     4.7
##  6     4.9
##  7     5.1
##  8     5.1
##  9     5.2
## 10     5.5
## 11     5.5
## 12     5.6
## 13     5.7
## 14     5.8
## 15     5.8
## 16     6.1
## 17     6.1
## 18     6.1
## 19     6.1
## 20     6.1</code></pre>
<p>Get it to work via one of the methods you’ve seen in this class (ie., <em>not</em> <code>read.table</code>); I don’t mind how you manage it.</p>
<p><span class="math inline">\(\blacksquare\)</span></p>
<ol start="2" style="list-style-type: lower-alpha">
<li>Make a suitable graph of your data.</li>
</ol>
<p>Solution</p>
<p>One quantitative variable, so a histogram with a sufficiently small number of bins:</p>
<div class="sourceCode" id="cb206"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb206-1" title="1"><span class="kw">ggplot</span>(meals, <span class="kw">aes</span>(<span class="dt">x=</span>protein)) <span class="op">+</span><span class="st"> </span><span class="kw">geom_histogram</span>(<span class="dt">bins =</span> <span class="dv">5</span>)</a></code></pre></div>
<p><img src="pasias_files/figure-html/unnamed-chunk-129-1.png" width="672" /></p>
<p><span class="math inline">\(\blacksquare\)</span></p>
<ol start="3" style="list-style-type: lower-alpha">
<li>Why might a sign test be better than a <span class="math inline">\(t\)</span>-test for assessing the average amount of protein per package? Explain briefly. (“Average” here means any measure of centre.)</li>
</ol>
<p>Solution</p>
<p>The shape of the above distribution is skewed to the left, and not symmetric like a normal distribution. (If you say “the histogram is not normal”, make sure you also say how you know.) This means that the median would be a better measure of “average” (that is, centre) than the mean is, because the mean would be pulled downwards by the long tail, and the median would not. To complete the story, the sign test is a test of the median, so the sign test would be better than the <span class="math inline">\(t\)</span>-test, which is a test of the mean.</p>
<p>The other thing you might consider is the sample size, 20, which <em>might</em> be large enough to overcome this amount of skewness, but then again it might not be. So you could say that we should be cautious and run the sign test here instead.</p>
<p><span class="math inline">\(\blacksquare\)</span></p>
<ol start="4" style="list-style-type: lower-alpha">
<li>Run a suitable sign test for these data. What do you conclude?</li>
</ol>
<p>Solution</p>
<p>First, if you have not already done so, install <code>smmr</code> <em>following the instructions in the lecture notes</em>. (This one is not just <code>install.packages</code>.) Then, make sure you have a <code>library(smmr)</code> somewhere above where you are going to use something from it. Once that is in place, remember what we were interested in: was the median protein content 6 ounces, or is there evidence that it is something different? (The “not accurate” in the question says that the median could be higher or lower, either of which would be a problem, and so we need a two-sided alternative.) Thus, the null median is 6 and we need a two-sided test, which goes this way:</p>
<div class="sourceCode" id="cb207"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb207-1" title="1"><span class="kw">sign_test</span>(meals, protein, <span class="dv">6</span>)</a></code></pre></div>
<pre><code>## $above_below
## below above 
##    15     5 
## 
## $p_values
##   alternative    p_value
## 1       lower 0.02069473
## 2       upper 0.99409103
## 3   two-sided 0.04138947</code></pre>
<p>The P-value, 0.0414, is less than 0.05, so we reject the null hypothesis and conclude that the median is different from 6 ounces. The advertisement by the company is not accurate.</p>
<p>Make sure you give the actual P-value you are comparing with 0.05, since otherwise your answer is incomplete. That is, you need to say more than just “the P-value is less than 0.05”; there are three P-values here, and only one of them is the right one.</p>
<p>Extra: we already decided that a <span class="math inline">\(t\)</span>-test is not the best here, but I am curious as to how different its P-value is:</p>
<div class="sourceCode" id="cb209"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb209-1" title="1"><span class="kw">with</span>(meals, <span class="kw">t.test</span>(protein, <span class="dt">mu=</span><span class="dv">6</span>))</a></code></pre></div>
<pre><code>## 
##  One Sample t-test
## 
## data:  protein
## t = -4.2312, df = 19, p-value = 0.000452
## alternative hypothesis: true mean is not equal to 6
## 95 percent confidence interval:
##  4.946263 5.643737
## sample estimates:
## mean of x 
##     5.295</code></pre>
<p>The conclusion is the same, but the P-value is a lot smaller. I don’t think it should really be this small; this is probably because the mean is pulled down by the left skew and so really ought not to look so far below 6. I am inclined to think that if the <span class="math inline">\(t\)</span>-test were correct, its P-value ought to be between this and the one from the sign test, because the <span class="math inline">\(t\)</span>-test uses the actual data values, and the sign test uses the data less efficiently (only considering whether each one is above or below the null median).</p>
<p><span class="math inline">\(\blacksquare\)</span></p>
<ol start="5" style="list-style-type: lower-alpha">
<li>In your sign test, how could you have deduced that the P-value was going to be small even without looking at any of the P-values themselves? Explain briefly.</li>
</ol>
<p>Solution</p>
<p>Look at the other part of the output, the count of values above and below the null median. (You might have to click on “R Console” to see it.) If the null hypothesis was correct and the median was really 6, you’d expect to see about half the data values above 6 and about half below. But that is not what happened: there were 15 values below and only 5 above. Such an uneven split is rather unlikely if the null hypothesis was correct. So we would guess that our P-value would be small, as indeed it is.</p>
<p><span class="math inline">\(\blacksquare\)</span></p>
<ol start="6" style="list-style-type: lower-alpha">
<li>Obtain a 90% confidence interval for the population median protein content. What does this tell you about the reason for the rejection or non-rejection of the null hypothesis above?</li>
</ol>
<p>Solution</p>
<p>This is <code>ci_median</code>, but you need to be paying attention: it’s not the default 95% confidence level, so you have to specify that as well:</p>
<div class="sourceCode" id="cb211"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb211-1" title="1"><span class="kw">ci_median</span>(meals, protein, <span class="dt">conf.level =</span> <span class="fl">0.90</span>)</a></code></pre></div>
<pre><code>## [1] 4.905273 5.793750</code></pre>
<p>The interval goes from 4.91 to 5.79. (The data values have one decimal place, so you could justify two decimals in the CI for the median, but anything beyond that is noise and you shouldn’t give it in your answer.<a href="#fn5" class="footnote-ref" id="fnref5"><sup>5</sup></a>)</p>
<p>This interval is entirely below 6 (the null median), so evidently the reason that we rejected 6 as the population median is that the actual population median is <em>less than</em> 6.</p>
<p>Extra: the CI for the median is not that different from the one for the mean, which suggests that maybe the <span class="math inline">\(t\)</span>-test was not so bad after all. If you want to investigate further, you can try finding a bootstrapped sampling distribution of the sample mean, and see how non-normal it looks:</p>
<div class="sourceCode" id="cb213"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb213-1" title="1"><span class="kw">tibble</span>(<span class="dt">sim =</span> <span class="dv">1</span><span class="op">:</span><span class="dv">1000</span>) <span class="op">%&gt;%</span><span class="st"> </span></a>
<a class="sourceLine" id="cb213-2" title="2"><span class="st">  </span><span class="kw">rowwise</span>() <span class="op">%&gt;%</span><span class="st"> </span></a>
<a class="sourceLine" id="cb213-3" title="3"><span class="st">  </span><span class="kw">mutate</span>(<span class="dt">my_sample =</span> <span class="kw">list</span>(<span class="kw">sample</span>(meals<span class="op">$</span>protein, <span class="dt">replace =</span> <span class="ot">TRUE</span>))) <span class="op">%&gt;%</span><span class="st"> </span></a>
<a class="sourceLine" id="cb213-4" title="4"><span class="st">  </span><span class="kw">mutate</span>(<span class="dt">my_mean =</span> <span class="kw">mean</span>(my_sample)) -&gt;<span class="st"> </span>d</a>
<a class="sourceLine" id="cb213-5" title="5"><span class="kw">ggplot</span>(d, <span class="kw">aes</span>(<span class="dt">x =</span> my_mean)) <span class="op">+</span><span class="st"> </span><span class="kw">geom_histogram</span>(<span class="dt">bins =</span> <span class="dv">10</span>)</a></code></pre></div>
<p><img src="pasias_files/figure-html/unnamed-chunk-133-1.png" width="672" /></p>
<p>That is pretty close to normal. So the <span class="math inline">\(t\)</span>-test would in actual fact have been fine. To confirm, a normal quantile plot of the bootstrapped sampling distribution:</p>
<div class="sourceCode" id="cb214"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb214-1" title="1"><span class="kw">ggplot</span>(d, <span class="kw">aes</span>(<span class="dt">sample =</span> my_mean)) <span class="op">+</span><span class="st"> </span><span class="kw">stat_qq</span>() <span class="op">+</span><span class="st"> </span><span class="kw">stat_qq_line</span>()</a></code></pre></div>
<p><img src="pasias_files/figure-html/unnamed-chunk-134-1.png" width="672" />
A <em>tiny bit</em> skewed to the left.</p>
<p>But I didn’t ask you to do this, because I wanted to give you a chance to do a sign test for what seemed like a good reason.</p>
<p>Extra 2: I mentioned in an note that the endpoints of the CI for the median are actually data points, only we didn’t see it because of the accuracy to which <code>ci_median</code> was working. You can control this accuracy by an extra input <code>tol</code>. Let’s do something silly here:</p>
<div class="sourceCode" id="cb215"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb215-1" title="1"><span class="kw">ci_median</span>(meals, protein, <span class="dt">conf.level =</span> <span class="fl">0.90</span>, <span class="dt">tol =</span> <span class="fl">0.00000001</span>)</a></code></pre></div>
<pre><code>## [1] 4.900001 5.799999</code></pre>
<p>This takes a bit longer to run, since it has to get the answer more accurately, but now you can see how the interval goes from “just over 4.9” to “just under 5.8”, and it actually makes the most sense to give the interval as “4.9 to 5.8” without giving any more decimals.</p>
<p>Extra 3: the reason for the confidence interval endpoints to be data values is that the interval comes from inverting the test: that is, finding the values of the population median that would not be rejected by a sign test run on our data. Recall how the sign test works: it is based on a count of how many data values are above and below the hypothesized population median. These counts are only going to change as the hypothesized median changes if you hit a data point, since that’s the only way you can change how many values are above and below.<a href="#fn6" class="footnote-ref" id="fnref6"><sup>6</sup></a> Thus, the only places where changing the null median changes whether or not a value for it is inside or outside the confidence interval are at data values, and thus the ends of the interval must be at (or, perhaps more strictly, just above or below) data values.</p>
<p>This is a peculiarity of using the sign test to get a CI for the median. If, say, you were to invert the <span class="math inline">\(t\)</span>-test to get a confidence interval for the mean, you wouldn’t see that. (This is in fact exactly what you do to get a confidence interval for the mean, but this is not the way it is usually introduced.) The reason that the CI for the mean (based on the <span class="math inline">\(t\)</span>-test) is different from the one for the median (based on the sign test) is that if you change the null hypothesis in the <span class="math inline">\(t\)</span>-test, however slightly, you change the P-value (maybe only slightly, but you change it). So the CI for the mean, based on the <span class="math inline">\(t\)</span>-test, is not required to have data points at its ends, and indeed usually does not. The difference is in the kind of distribution the test statistic has; the <span class="math inline">\(t\)</span>-distribution is continuous, while the sign test statistic (a count of the number of values above or below something) is discrete. It’s the discreteness that causes the problems.</p>
<p><span class="math inline">\(\blacksquare\)</span></p>

</div>
</div>
<div class="footnotes">
<hr />
<ol start="1">
<li id="fn1"><p>You can change this by adding something like <em>tol=1e-4</em> to the end of your <em>ci-median</em>.<a href="the-sign-test.html#fnref1" class="footnote-back">↩</a></p></li>
<li id="fn2"><p>Meaning, I forget how to do it. But it has something to do with looking at alternatives that are very close to the null.<a href="the-sign-test.html#fnref2" class="footnote-back">↩</a></p></li>
<li id="fn3"><p>If you’ve ever run into the exponential distribution, you’ll recall that this is right skewed with a very long tail. The Laplace distribution looks like two of these glued back to back.<a href="the-sign-test.html#fnref3" class="footnote-back">↩</a></p></li>
<li id="fn4"><p>This is about the <em>only</em> way in which the normal and Laplace distributions are alike.<a href="the-sign-test.html#fnref4" class="footnote-back">↩</a></p></li>
<li id="fn5"><p>There is actually slightly more to it here: the ends of this confidence interval for the median are always data values, because of the way it is constructed, so the actual end points really ought to be given to the <em>same</em> number of decimals as the data, here 4.9 to 5.8. The output given is not exactly 4.9 and 5.8 because of inaccuracy in the bisection.<a href="the-sign-test.html#fnref5" class="footnote-back">↩</a></p></li>
<li id="fn6"><p>There is a technicality about what happens when the null median is exactly equal to a data value; see PASIAS for more discussion on this.<a href="the-sign-test.html#fnref6" class="footnote-back">↩</a></p></li>
</ol>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="power-and-sample-size.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="mood-median-test.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/lunr.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": null,
"text": null
},
"history": {
"link": null,
"text": null
},
"view": {
"link": null,
"text": null
},
"download": ["pasias.pdf"],
"toc": {
"collapse": "subsection"
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
