<!DOCTYPE html>
<html >

<head>

  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <title>Problems and Solutions in Applied Statistics</title>
  <meta name="description" content="A set of problems and solutions, in R, on various parts of applied statistics">
  <meta name="generator" content="bookdown 0.7 and GitBook 2.6.7">

  <meta property="og:title" content="Problems and Solutions in Applied Statistics" />
  <meta property="og:type" content="book" />
  <meta property="og:url" content="<a href="http://ritsokiguess.site/pasias" class="uri">http://ritsokiguess.site/pasias</a>" />
  
  <meta property="og:description" content="A set of problems and solutions, in R, on various parts of applied statistics" />
  <meta name="github-repo" content="nxskok/pasias" />

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Problems and Solutions in Applied Statistics" />
  
  <meta name="twitter:description" content="A set of problems and solutions, in R, on various parts of applied statistics" />
  

<meta name="author" content="Ken Butler">


<meta name="date" content="2018-10-09">

  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="apple-mobile-web-app-capable" content="yes">
  <meta name="apple-mobile-web-app-status-bar-style" content="black">
  
  
<link rel="prev" href="power-and-sample-size.html">
<link rel="next" href="matched-pairs-t-and-sign-test.html">
<script src="libs/jquery-2.2.3/jquery.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />









<style type="text/css">
a.sourceLine { display: inline-block; line-height: 1.25; }
a.sourceLine { pointer-events: none; color: inherit; text-decoration: inherit; }
a.sourceLine:empty { height: 1.2em; position: absolute; }
.sourceCode { overflow: visible; }
code.sourceCode { white-space: pre; position: relative; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
code.sourceCode { white-space: pre-wrap; }
a.sourceLine { text-indent: -1em; padding-left: 1em; }
}
pre.numberSource a.sourceLine
  { position: relative; }
pre.numberSource a.sourceLine:empty
  { position: absolute; }
pre.numberSource a.sourceLine::before
  { content: attr(data-line-number);
    position: absolute; left: -5em; text-align: right; vertical-align: baseline;
    border: none; pointer-events: all;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {  }
@media screen {
a.sourceLine::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">Problems and Solutions in Applied Statistics</a></li>

<li class="divider"></li>
<li class="chapter" data-level="1" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i><b>1</b> Introduction</a></li>
<li class="chapter" data-level="2" data-path="getting-used-to-r-and-r-studio.html"><a href="getting-used-to-r-and-r-studio.html"><i class="fa fa-check"></i><b>2</b> Getting used to R and R Studio</a><ul>
<li class="chapter" data-level="2.1" data-path="getting-used-to-r-and-r-studio.html"><a href="getting-used-to-r-and-r-studio.html#getting-an-r-studio-cloud-account"><i class="fa fa-check"></i><b>2.1</b> Getting an R Studio Cloud account</a></li>
<li class="chapter" data-level="2.2" data-path="getting-used-to-r-and-r-studio.html"><a href="getting-used-to-r-and-r-studio.html#getting-started"><i class="fa fa-check"></i><b>2.2</b> Getting started</a></li>
<li class="chapter" data-level="2.3" data-path="getting-used-to-r-and-r-studio.html"><a href="getting-used-to-r-and-r-studio.html#reading-data-from-a-file"><i class="fa fa-check"></i><b>2.3</b> Reading data from a file</a></li>
</ul></li>
<li class="chapter" data-level="3" data-path="reading-in-data-and-drawing-some-graphs.html"><a href="reading-in-data-and-drawing-some-graphs.html"><i class="fa fa-check"></i><b>3</b> Reading in data and drawing some graphs</a><ul>
<li class="chapter" data-level="3.1" data-path="reading-in-data-and-drawing-some-graphs.html"><a href="reading-in-data-and-drawing-some-graphs.html#orange-juice"><i class="fa fa-check"></i><b>3.1</b> Orange juice</a></li>
<li class="chapter" data-level="3.2" data-path="reading-in-data-and-drawing-some-graphs.html"><a href="reading-in-data-and-drawing-some-graphs.html#making-soap"><i class="fa fa-check"></i><b>3.2</b> Making soap</a></li>
<li class="chapter" data-level="3.3" data-path="reading-in-data-and-drawing-some-graphs.html"><a href="reading-in-data-and-drawing-some-graphs.html#handling-shipments"><i class="fa fa-check"></i><b>3.3</b> Handling shipments</a></li>
</ul></li>
<li class="chapter" data-level="4" data-path="data-exploration.html"><a href="data-exploration.html"><i class="fa fa-check"></i><b>4</b> Data exploration</a><ul>
<li class="chapter" data-level="4.1" data-path="data-exploration.html"><a href="data-exploration.html#north-carolina-births"><i class="fa fa-check"></i><b>4.1</b> North Carolina births</a></li>
<li class="chapter" data-level="4.2" data-path="data-exploration.html"><a href="data-exploration.html#more-about-the-nc-births"><i class="fa fa-check"></i><b>4.2</b> More about the NC births</a></li>
<li class="chapter" data-level="4.3" data-path="data-exploration.html"><a href="data-exploration.html#nenana-alaska"><i class="fa fa-check"></i><b>4.3</b> Nenana, Alaska</a></li>
<li class="chapter" data-level="4.4" data-path="data-exploration.html"><a href="data-exploration.html#computerized-accounting"><i class="fa fa-check"></i><b>4.4</b> Computerized accounting</a></li>
</ul></li>
<li class="chapter" data-level="5" data-path="one-sample-inference.html"><a href="one-sample-inference.html"><i class="fa fa-check"></i><b>5</b> One-sample inference</a><ul>
<li class="chapter" data-level="5.1" data-path="one-sample-inference.html"><a href="one-sample-inference.html#hunter-gatherers-in-australia"><i class="fa fa-check"></i><b>5.1</b> Hunter-gatherers in Australia</a></li>
<li class="chapter" data-level="5.2" data-path="one-sample-inference.html"><a href="one-sample-inference.html#length-of-gestation-in-north-carolina"><i class="fa fa-check"></i><b>5.2</b> Length of gestation in North Carolina</a></li>
<li class="chapter" data-level="5.3" data-path="one-sample-inference.html"><a href="one-sample-inference.html#inferring-ice-break-up-in-nenana"><i class="fa fa-check"></i><b>5.3</b> Inferring ice break-up in Nenana</a></li>
</ul></li>
<li class="chapter" data-level="6" data-path="two-sample-inference.html"><a href="two-sample-inference.html"><i class="fa fa-check"></i><b>6</b> Two-sample inference</a><ul>
<li class="chapter" data-level="6.1" data-path="two-sample-inference.html"><a href="two-sample-inference.html#children-and-electronic-devices"><i class="fa fa-check"></i><b>6.1</b> Children and electronic devices</a></li>
<li class="chapter" data-level="6.2" data-path="two-sample-inference.html"><a href="two-sample-inference.html#parking-close-to-the-curb"><i class="fa fa-check"></i><b>6.2</b> Parking close to the curb</a></li>
</ul></li>
<li class="chapter" data-level="7" data-path="power-and-sample-size.html"><a href="power-and-sample-size.html"><i class="fa fa-check"></i><b>7</b> Power and sample size</a><ul>
<li class="chapter" data-level="7.1" data-path="power-and-sample-size.html"><a href="power-and-sample-size.html#simulating-power"><i class="fa fa-check"></i><b>7.1</b> Simulating power</a></li>
<li class="chapter" data-level="7.2" data-path="power-and-sample-size.html"><a href="power-and-sample-size.html#calculating-power-and-sample-size-for-estimating-mean"><i class="fa fa-check"></i><b>7.2</b> Calculating power and sample size for estimating mean</a></li>
<li class="chapter" data-level="7.3" data-path="power-and-sample-size.html"><a href="power-and-sample-size.html#simulating-power-for-proportions"><i class="fa fa-check"></i><b>7.3</b> Simulating power for proportions</a></li>
</ul></li>
<li class="chapter" data-level="8" data-path="the-sign-test-and-moods-median-test.html"><a href="the-sign-test-and-moods-median-test.html"><i class="fa fa-check"></i><b>8</b> The sign test and Mood’s median test</a></li>
<li class="chapter" data-level="9" data-path="matched-pairs-t-and-sign-test.html"><a href="matched-pairs-t-and-sign-test.html"><i class="fa fa-check"></i><b>9</b> Matched pairs t and sign test</a></li>
<li class="chapter" data-level="10" data-path="normal-quantile-plots.html"><a href="normal-quantile-plots.html"><i class="fa fa-check"></i><b>10</b> Normal quantile plots</a></li>
<li class="divider"></li>
<li><a href="https://github.com/rstudio/bookdown" target="blank">Published with bookdown</a></li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Problems and Solutions in Applied Statistics</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="the-sign-test-and-moods-median-test" class="section level1">
<h1><span class="header-section-number">Chapter 8</span> The sign test and Mood’s median test</h1>
<div class="sourceCode" id="cb309"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb309-1" data-line-number="1"><span class="kw">library</span>(tidyverse)</a></code></pre></div>
<pre><code>## ── Attaching packages ─────────────────────────────────────────────────────────────────────────────────────── tidyverse 1.2.1 ──</code></pre>
<pre><code>## ✔ ggplot2 3.0.0     ✔ purrr   0.2.5
## ✔ tibble  1.4.2     ✔ dplyr   0.7.6
## ✔ tidyr   0.8.1     ✔ stringr 1.3.1
## ✔ readr   1.1.1     ✔ forcats 0.3.0</code></pre>
<pre><code>## ── Conflicts ────────────────────────────────────────────────────────────────────────────────────────── tidyverse_conflicts() ──
## ✖ dplyr::filter() masks stats::filter()
## ✖ dplyr::lag()    masks stats::lag()</code></pre>
<div class="sourceCode" id="cb313"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb313-1" data-line-number="1"><span class="kw">library</span>(smmr)</a></code></pre></div>
<p>A researcher is trying to design a maze that can be run by
rats in about 60 seconds. One particular maze was run by a sample of
21 rats, with the times shown in
<a href="http://www.utsc.utoronto.ca/~butler/c32/maze.txt" class="uri">http://www.utsc.utoronto.ca/~butler/c32/maze.txt</a>.</p>
<ol style="list-style-type: lower-alpha">
<li>Read the data into R. What (if anything) are the data values
delimited by?</li>
</ol>
<p>Solution</p>
<p>Take a look at the data file first. There is only one column of
data, so you can treat it as being delimited by anything you like:
a space, or a comma (the file can also be treated as a
<code>.csv</code>), etc.:</p>
<div class="sourceCode" id="cb314"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb314-1" data-line-number="1">myurl=<span class="st">&quot;http://www.utsc.utoronto.ca/~butler/c32/maze.txt&quot;</span></a>
<a class="sourceLine" id="cb314-2" data-line-number="2">times=<span class="kw">read_delim</span>(myurl,<span class="st">&quot; &quot;</span>)</a></code></pre></div>
<pre><code>## Parsed with column specification:
## cols(
##   time = col_double()
## )</code></pre>
<div class="sourceCode" id="cb316"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb316-1" data-line-number="1">times</a></code></pre></div>
<pre><code>## # A tibble: 21 x 1
##     time
##    &lt;dbl&gt;
##  1  38.4
##  2  46.2
##  3  62.5
##  4  38  
##  5  62.8
##  6  33.9
##  7  50.4
##  8  35  
##  9  52.8
## 10  60.1
## # ... with 11 more rows</code></pre>
<ol start="2" style="list-style-type: lower-alpha">
<li>Run a sign test, doing it yourself as we did in class:
count the number of values above and below 60, take the <em>smaller</em>
of those, and find the probability of a value of that or smaller still
on a binomial distribution with <span class="math inline">\(n=21\)</span> and <span class="math inline">\(p=0.5\)</span> (we have 21 data
points), doubling the answer because the test is two-sided.</li>
</ol>
<p>Solution</p>
<p>Count how many values are above and below 60:</p>
<div class="sourceCode" id="cb318"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb318-1" data-line-number="1">times <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">count</span>(time<span class="op">&gt;</span><span class="dv">60</span>)</a></code></pre></div>
<pre><code>## # A tibble: 2 x 2
##   `time &gt; 60`     n
##   &lt;lgl&gt;       &lt;int&gt;
## 1 FALSE          16
## 2 TRUE            5</code></pre>
<p>5 above and 16 below. Then find out how likely it is that a binomial
with <span class="math inline">\(n=21, p=0.5\)</span> would produce 5 or fewer successes:</p>
<div class="sourceCode" id="cb320"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb320-1" data-line-number="1">p=<span class="kw">sum</span>(<span class="kw">dbinom</span>(<span class="dv">0</span><span class="op">:</span><span class="dv">5</span>,<span class="dv">21</span>,<span class="fl">0.5</span>))</a>
<a class="sourceLine" id="cb320-2" data-line-number="2">p</a></code></pre></div>
<pre><code>## [1] 0.01330185</code></pre>
<p>or if you prefer count upwards from 16:</p>
<div class="sourceCode" id="cb322"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb322-1" data-line-number="1"><span class="kw">sum</span>(<span class="kw">dbinom</span>(<span class="dv">16</span><span class="op">:</span><span class="dv">21</span>,<span class="dv">21</span>,<span class="fl">0.5</span>))</a></code></pre></div>
<pre><code>## [1] 0.01330185</code></pre>
<p>and double it to get a two-sided P-value:</p>
<div class="sourceCode" id="cb324"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb324-1" data-line-number="1"><span class="dv">2</span><span class="op">*</span>p  </a></code></pre></div>
<pre><code>## [1] 0.0266037</code></pre>
<p>We’ll compare this with <code>smmr</code> in a moment.</p>
<ol start="3" style="list-style-type: lower-alpha">
<li>Install my package <code>smmr</code>, if you haven’t already. To do
this, you first need to install the package <code>devtools</code> (if you
haven’t already),
by going to the console and typing</li>
</ol>
<div class="sourceCode" id="cb326"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb326-1" data-line-number="1"><span class="kw">install.packages</span>(<span class="st">&quot;devtools&quot;</span>)</a></code></pre></div>
<p>When that’s all done, install <code>smmr</code> thus:</p>
<div class="sourceCode" id="cb327"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb327-1" data-line-number="1"><span class="kw">library</span>(devtools)</a>
<a class="sourceLine" id="cb327-2" data-line-number="2"><span class="kw">install_github</span>(<span class="st">&quot;nxskok/smmr&quot;</span>)</a></code></pre></div>
<p>That all needs to be done only once. Then, each R Studio session where
you want to use <code>smmr</code> needs this:</p>
<div class="sourceCode" id="cb328"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb328-1" data-line-number="1"><span class="kw">library</span>(smmr)</a></code></pre></div>
<p>As usual, only the <code>library</code> thing only needs to be done every
time.</p>
<p>When you have <code>smmr</code> installed, use <code>sign_test</code> from
that package to re-run your sign test. Do you get the same P-value?</p>
<p>Solution</p>
<p>The sign test function takes a data frame, an (unquoted) column
name from that data frame of data to test the median of, and a
null median (which defaults to 0 if you omit it):</p>
<div class="sourceCode" id="cb329"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb329-1" data-line-number="1"><span class="kw">library</span>(smmr)</a>
<a class="sourceLine" id="cb329-2" data-line-number="2"><span class="kw">sign_test</span>(times,time,<span class="dv">60</span>)</a></code></pre></div>
<pre><code>## $above_below
## below above 
##    16     5 
## 
## $p_values
##   alternative    p_value
## 1       lower 0.01330185
## 2       upper 0.99640131
## 3   two-sided 0.02660370</code></pre>
<p>This shows you two things: a count of the values below and above the
null median, and then the P-values according to the various
alternative hypotheses you might have.</p>
<p>In our case, we see again the 16 maze-running times below 60 seconds
and 5 above (one of which was a long way above, but we don’t care
about that here). We were testing whether the median was different
from 60, so we look at the two-sided P-value of 0.0266, which is
exactly what we had before.</p>
<p>If <code>sign_test</code> doesn’t work for you (perhaps because it needs
a function <code>enquo</code> that you don’t have), there is an
alternative function <code>sign_test0</code> that doesn’t use it. It
requires as input a <em>column</em> of values (extracted from the data
frame) and a null median, thus:</p>
<div class="sourceCode" id="cb331"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb331-1" data-line-number="1"><span class="kw">sign_test0</span>(times<span class="op">$</span>time,<span class="dv">60</span>)</a></code></pre></div>
<pre><code>## $above_below
## below above 
##    16     5 
## 
## $p_values
##   alternative    p_value
## 1       lower 0.01330185
## 2       upper 0.99640131
## 3   two-sided 0.02660370</code></pre>
<p>The output should be, and here is, identical.</p>
<ol start="4" style="list-style-type: lower-alpha">
<li>Package <code>smmr</code> also has a function
<code>pval_sign</code>, which has the same input as
<code>sign_test</code>, but with the null median <em>first</em>.
Run it on your data and see what it gives.</li>
</ol>
<p>Solution</p>
<p>Try it and see:</p>
<div class="sourceCode" id="cb333"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb333-1" data-line-number="1"><span class="kw">pval_sign</span>(<span class="dv">60</span>,times,time)</a></code></pre></div>
<pre><code>## [1] 0.0266037</code></pre>
<p>The two-sided P-value, and that is all. We’ll be using this in a minute.</p>
<p>Alternatively, there is also this, which needs a null median and a
<em>column</em> as input:</p>
<div class="sourceCode" id="cb335"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb335-1" data-line-number="1"><span class="kw">pval_sign0</span>(<span class="dv">60</span>,times<span class="op">$</span>time)</a></code></pre></div>
<pre><code>## [1] 0.0266037</code></pre>
<ol start="5" style="list-style-type: lower-alpha">
<li>Obtain a 95% confidence interval for the median based on these
data. Do this two ways. First, use the trial and error way from class
(either the try-lots-of-values way or the bisection way; either is good).
Second, use <code>ci_median</code> from <code>smmr</code>. The latter takes
as input a data frame, a column name (unquoted) and optionally a
<code>conf.level</code> that defaults to 0.95.</li>
</ol>
<p>Solution</p>
<p>The reason for showing you <code>pval_sign</code> in the previous
part is that this is a building block for the confidence interval.
What we do is to try various null medians
and find out which ones give P-values less than 0.05 (outside the
interval) and which ones bigger (inside).
We know that the value 60 is
outside the 95% CI, and the sample median is close to 50 (which we
expect to be inside), so sensible values to try for the upper end of
the interval would be between 50 and 60:</p>
<div class="sourceCode" id="cb337"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb337-1" data-line-number="1"><span class="kw">pval_sign</span>(<span class="dv">58</span>,times,time)</a></code></pre></div>
<pre><code>## [1] 0.0266037</code></pre>
<div class="sourceCode" id="cb339"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb339-1" data-line-number="1"><span class="kw">pval_sign</span>(<span class="dv">55</span>,times,time)</a></code></pre></div>
<pre><code>## [1] 0.6636238</code></pre>
<p>So, 55 is inside the interval and 58 is outside. I could investigate
further in similar fashion, but I thought I would try a whole bunch of null
medians all at once. That goes like this:</p>
<div class="sourceCode" id="cb341"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb341-1" data-line-number="1">meds=<span class="kw">seq</span>(<span class="dv">55</span>,<span class="dv">58</span>,<span class="fl">0.25</span>)</a>
<a class="sourceLine" id="cb341-2" data-line-number="2">meds</a></code></pre></div>
<pre><code>##  [1] 55.00 55.25 55.50 55.75 56.00 56.25 56.50 56.75 57.00 57.25 57.50
## [12] 57.75 58.00</code></pre>
<div class="sourceCode" id="cb343"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb343-1" data-line-number="1">pvals=<span class="kw">map_dbl</span>(meds,pval_sign,times,time)</a>
<a class="sourceLine" id="cb343-2" data-line-number="2"><span class="kw">data.frame</span>(meds,pvals)</a></code></pre></div>
<pre><code>##     meds      pvals
## 1  55.00 0.66362381
## 2  55.25 0.38331032
## 3  55.50 0.26317596
## 4  55.75 0.18924713
## 5  56.00 0.18924713
## 6  56.25 0.18924713
## 7  56.50 0.07835388
## 8  56.75 0.07835388
## 9  57.00 0.07835388
## 10 57.25 0.07835388
## 11 57.50 0.07835388
## 12 57.75 0.02660370
## 13 58.00 0.02660370</code></pre>
<p>So values for the median all the way up to and including 57.5 are in
the confidence interval.</p>
<p>What <code>map_dbl</code> does is to take a vector of values, here the
ones in <code>meds</code> (55 through 58 in steps of 0.25), feed them into
a function, here <code>pval_sign</code>, one by one and gather together
the results. <code>pval_sign</code> has two other inputs, <code>times</code> and
<code>time</code>, which are added to <code>map_dbl</code> at the end. (They
are the same no matter what median we are testing.) So, putting the
calculated P-values side by side with the null medians they belong to
shows you which medians are inside the confidence interval and which
are outside.</p>
<p>The function is called <code>map_dbl</code> because <em>my</em> function
called <code>pval_sign</code> that is called repeatedly returns a single
decimal number (a <code>dbl</code>). There is also, for example,
<code>map_chr</code> for repeatedly calling a function that returns a
single piece of text, and plain <code>map</code> that is used when the
repeatedly-called function returns a data frame.</p>
<p>Since you don’t know about <code>map_dbl</code>, I didn’t want to confuse
things more than necessary, but now that you <em>do</em> know what it
does, you might be in a better position to understand this more
Tidyverse-flavoured code, with the <code>map_dbl</code> inside a
<code>mutate</code> and the data frame created as we go:</p>
<div class="sourceCode" id="cb345"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb345-1" data-line-number="1"><span class="kw">tibble</span>(<span class="dt">meds=</span><span class="kw">seq</span>(<span class="dv">55</span>,<span class="dv">58</span>,<span class="fl">0.25</span>)) <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb345-2" data-line-number="2"><span class="kw">mutate</span>(<span class="dt">pvals=</span><span class="kw">map_dbl</span>(meds,pval_sign,times,time)) </a></code></pre></div>
<pre><code>## # A tibble: 13 x 2
##     meds  pvals
##    &lt;dbl&gt;  &lt;dbl&gt;
##  1  55   0.664 
##  2  55.2 0.383 
##  3  55.5 0.263 
##  4  55.8 0.189 
##  5  56   0.189 
##  6  56.2 0.189 
##  7  56.5 0.0784
##  8  56.8 0.0784
##  9  57   0.0784
## 10  57.2 0.0784
## 11  57.5 0.0784
## 12  57.8 0.0266
## 13  58   0.0266</code></pre>
<p>Now for the other end of the interval. I’m going to do this a
different way: more efficient, but less transparent. The first thing I
need is a pair of values for the median: one inside the interval and
one outside. Let’s try 40 and 50:</p>
<div class="sourceCode" id="cb347"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb347-1" data-line-number="1"><span class="kw">pval_sign</span>(<span class="dv">40</span>,times,time)</a></code></pre></div>
<pre><code>## [1] 0.00719738</code></pre>
<div class="sourceCode" id="cb349"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb349-1" data-line-number="1"><span class="kw">pval_sign</span>(<span class="dv">50</span>,times,time)</a></code></pre></div>
<pre><code>## [1] 1</code></pre>
<p>OK, so 40 is outside and 50 is inside. So what do I guess for the next
value to try? I could do something clever like assuming that the
relationship between hypothesized median and P-value is <em>linear</em>,
and then guessing where that line crosses 0.05. But I’m going to
assume <em>nothing</em> about the relationship except that it goes
uphill, and therefore crosses 0.05 somewhere. So my next guess is
halfway between the two values I tried before:</p>
<div class="sourceCode" id="cb351"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb351-1" data-line-number="1"><span class="kw">pval_sign</span>(<span class="dv">45</span>,times,time)</a></code></pre></div>
<pre><code>## [1] 0.07835388</code></pre>
<p>So, 45 is inside the interval, and my (slightly) improved guess at the
bottom end of the interval is that it’s between 40 and 45. So next, I
try halfway between <em>those</em>:</p>
<div class="sourceCode" id="cb353"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb353-1" data-line-number="1"><span class="kw">pval_sign</span>(<span class="fl">42.5</span>,times,time)</a></code></pre></div>
<pre><code>## [1] 0.0266037</code></pre>
<p>42.5 is outside, so the bottom end of the interval is between 42.5 and 45.</p>
<p>What we are doing is narrowing down where the interval’s bottom end
is. We started by knowing it to within 10, and now we know it to
within 2.5. So if we keep going, we’ll know it as accurately as we wish.</p>
<p>This is called a “bisection” method, because at each step, we’re
dividing our interval by 2.</p>
<p>There is one piece of decision-making at each step: if the P-value for
the median you try is greater than 0.05, that becomes the top end of
your interval (as when we tried 45); if it is less, it becomes the
bottom end (when we tried 42.5).</p>
<p>This all begs to be automated into a loop. It’s not a
<code>for</code>-type loop, because we don’t know how many times we’ll be
going around. It’s a <code>while</code> loop: keep going while something
is true. Here’s how it goes:</p>
<div class="sourceCode" id="cb355"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb355-1" data-line-number="1">lo=<span class="dv">40</span></a>
<a class="sourceLine" id="cb355-2" data-line-number="2">hi=<span class="dv">50</span></a>
<a class="sourceLine" id="cb355-3" data-line-number="3"><span class="cf">while</span>(<span class="kw">abs</span>(hi<span class="op">-</span>lo)<span class="op">&gt;</span><span class="fl">0.1</span>) {</a>
<a class="sourceLine" id="cb355-4" data-line-number="4">try=(hi<span class="op">+</span>lo)<span class="op">/</span><span class="dv">2</span></a>
<a class="sourceLine" id="cb355-5" data-line-number="5">ptry=<span class="kw">pval_sign</span>(try,times,time)</a>
<a class="sourceLine" id="cb355-6" data-line-number="6"><span class="kw">print</span>(<span class="kw">c</span>(try,ptry))</a>
<a class="sourceLine" id="cb355-7" data-line-number="7"><span class="cf">if</span> (ptry<span class="op">&lt;</span><span class="fl">0.05</span>) {</a>
<a class="sourceLine" id="cb355-8" data-line-number="8">lo=try</a>
<a class="sourceLine" id="cb355-9" data-line-number="9">} <span class="cf">else</span> {</a>
<a class="sourceLine" id="cb355-10" data-line-number="10">hi=try</a>
<a class="sourceLine" id="cb355-11" data-line-number="11">}</a>
<a class="sourceLine" id="cb355-12" data-line-number="12">}</a></code></pre></div>
<pre><code>## [1] 45.00000000  0.07835388
## [1] 42.5000000  0.0266037
## [1] 43.7500000  0.0266037
## [1] 44.37500000  0.07835388
## [1] 44.0625000  0.0266037
## [1] 44.2187500  0.0266037
## [1] 44.2968750  0.0266037</code></pre>
<div class="sourceCode" id="cb357"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb357-1" data-line-number="1">lo</a></code></pre></div>
<pre><code>## [1] 44.29688</code></pre>
<div class="sourceCode" id="cb359"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb359-1" data-line-number="1"><span class="kw">pval_sign</span>(lo,times,time)</a></code></pre></div>
<pre><code>## [1] 0.0266037</code></pre>
<div class="sourceCode" id="cb361"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb361-1" data-line-number="1">hi</a></code></pre></div>
<pre><code>## [1] 44.375</code></pre>
<div class="sourceCode" id="cb363"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb363-1" data-line-number="1"><span class="kw">pval_sign</span>(hi,times,time)</a></code></pre></div>
<pre><code>## [1] 0.07835388</code></pre>
<p>The loop stopped because 44.297 and 44.375 are less than 0.1
apart. The first of those is outside the interval and the second is
inside. So the bottom end of our interval is 44.375, to this
accuracy. If you want it more accurately, change 0.1 in the
<code>while</code> line to something smaller (but then you’ll be waiting
longer for the answer).</p>
<p>I put the <code>print</code> statement in the loop so that you could see
what values were being tried, and what P-values they were
producing. What happens with these is that the P-value jumps at each
data value, so you won’t get a P-value exactly 0.05; you’ll get one
above and one below.</p>
<p>Likewise, you can use the function with a zero on its name and feed it
a column rather than a data frame and a column name:</p>
<div class="sourceCode" id="cb365"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb365-1" data-line-number="1">meds=<span class="kw">seq</span>(<span class="dv">55</span>,<span class="dv">58</span>,<span class="fl">0.25</span>)</a>
<a class="sourceLine" id="cb365-2" data-line-number="2">meds</a></code></pre></div>
<pre><code>##  [1] 55.00 55.25 55.50 55.75 56.00 56.25 56.50 56.75 57.00 57.25 57.50
## [12] 57.75 58.00</code></pre>
<div class="sourceCode" id="cb367"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb367-1" data-line-number="1">pvals=<span class="kw">map_dbl</span>(meds,pval_sign0,times<span class="op">$</span>time)</a>
<a class="sourceLine" id="cb367-2" data-line-number="2"><span class="kw">data.frame</span>(meds,pvals)</a></code></pre></div>
<pre><code>##     meds      pvals
## 1  55.00 0.66362381
## 2  55.25 0.38331032
## 3  55.50 0.26317596
## 4  55.75 0.18924713
## 5  56.00 0.18924713
## 6  56.25 0.18924713
## 7  56.50 0.07835388
## 8  56.75 0.07835388
## 9  57.00 0.07835388
## 10 57.25 0.07835388
## 11 57.50 0.07835388
## 12 57.75 0.02660370
## 13 58.00 0.02660370</code></pre>
<p>Or adapt the idea I had above for bisection.
All that was a lot of work, but I wanted you to see it all once, so that you
know where the confidence interval is coming from. <code>smmr</code> also
has a function <code>ci_median</code> that does all of the above without
you having to do it. As I first wrote it, it was using the trial and
error thing with <code>map_dbl</code>, but I chose to rewrite it with the
bisection idea, because I thought that would be more accurate.</p>
<div class="sourceCode" id="cb369"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb369-1" data-line-number="1"><span class="kw">ci_median</span>(times,time)</a></code></pre></div>
<pre><code>## [1] 44.30747 57.59766</code></pre>
<p>This is a more accurate interval than we got above. (The
<code>while</code> loop for the bisection keeps going until the two
guesses at the appropriate end of the interval are less than 0.01
apart, by default.)</p>
<p>If you want some other confidence level, you add <code>conf.level</code>
on the end, as you would for <code>t.test</code>:</p>
<div class="sourceCode" id="cb371"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb371-1" data-line-number="1"><span class="kw">ci_median</span>(times,time,<span class="dt">conf.level=</span><span class="fl">0.75</span>)</a></code></pre></div>
<pre><code>## [1] 46.20444 55.49473</code></pre>
<p>A 75% CI, just for fun. This is a shorter interval than the 95% one,
as it should be.</p>
<p>Likewise there is a <code>ci_median0</code> that takes a column and an
optional confidence level:</p>
<div class="sourceCode" id="cb373"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb373-1" data-line-number="1"><span class="kw">ci_median0</span>(times<span class="op">$</span>time)</a></code></pre></div>
<pre><code>## [1] 44.30747 57.59766</code></pre>
<div class="sourceCode" id="cb375"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb375-1" data-line-number="1"><span class="kw">ci_median0</span>(times<span class="op">$</span>time,<span class="dt">conf.level=</span><span class="fl">0.75</span>)</a></code></pre></div>
<pre><code>## [1] 46.20444 55.49473</code></pre>
<p>with the same results. Try <code>ci_median</code> first, and if it
doesn’t work, try <code>ci_median0</code>.</p>
<p>A famous cookie manufacturer claims that
their bags of chocolate chip cookies contain ``more than 1100
chocolate chips on average’’. A diligent group of students buys 16
bags of these cookies and counts the number of chocolate chips in each
bag. The results are in <a href="http://www.utsc.utoronto.ca/~butler/c32/chips.txt" class="uri">http://www.utsc.utoronto.ca/~butler/c32/chips.txt</a>.</p>
<ol style="list-style-type: lower-alpha">
<li>Read in and display (some of) the data.</li>
</ol>
<p>Solution</p>
<p>I’ll pretend it’s a
<code>.csv</code> this time, just for fun. Give the data frame a
name different from <code>chips</code>, so that you don’t get
confused:</p>
<div class="sourceCode" id="cb377"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb377-1" data-line-number="1">bags=<span class="kw">read_csv</span>(<span class="st">&quot;chips.txt&quot;</span>)</a></code></pre></div>
<pre><code>## Parsed with column specification:
## cols(
##   chips = col_integer()
## )</code></pre>
<div class="sourceCode" id="cb379"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb379-1" data-line-number="1">bags</a></code></pre></div>
<pre><code>## # A tibble: 16 x 1
##    chips
##    &lt;int&gt;
##  1  1219
##  2  1214
##  3  1087
##  4  1200
##  5  1419
##  6  1121
##  7  1325
##  8  1345
##  9  1244
## 10  1258
## 11  1356
## 12  1132
## 13  1191
## 14  1270
## 15  1295
## 16  1135</code></pre>
<p>That looks sensible.</p>
<ol start="2" style="list-style-type: lower-alpha">
<li>Build your own sign test in R for testing that the median is
1100 chocolate chips, against the alternative that it is greater.
(Do this as in class: count the appropriate thing,
compare it with an appropriate binomial distribution, and obtain a
P-value.</li>
</ol>
<p>Solution</p>
<p>The null median is 1100, so we count the number
of values above and below:</p>
<div class="sourceCode" id="cb381"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb381-1" data-line-number="1">bags <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">count</span>(chips<span class="op">&lt;</span><span class="dv">1100</span>)</a></code></pre></div>
<pre><code>## # A tibble: 2 x 2
##   `chips &lt; 1100`     n
##   &lt;lgl&gt;          &lt;int&gt;
## 1 FALSE             15
## 2 TRUE               1</code></pre>
<p>The un-standard thing there is that we can put a logical condition
directly into the <code>count</code>. If you don’t think of that, you can
also do this, which creates a new variable <code>less</code> that is
<code>TRUE</code> or <code>FALSE</code> for each bag appropriately:</p>
<div class="sourceCode" id="cb383"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb383-1" data-line-number="1">bags <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">mutate</span>(<span class="dt">less=</span>(chips<span class="op">&lt;</span><span class="dv">1100</span>)) <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">count</span>(less)</a></code></pre></div>
<pre><code>## # A tibble: 2 x 2
##   less      n
##   &lt;lgl&gt; &lt;int&gt;
## 1 FALSE    15
## 2 TRUE      1</code></pre>
<p>or the more verbose</p>
<div class="sourceCode" id="cb385"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb385-1" data-line-number="1">bags <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">mutate</span>(<span class="dt">less=</span>(chips<span class="op">&lt;</span><span class="dv">1100</span>)) <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb385-2" data-line-number="2"><span class="kw">group_by</span>(less) <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">summarize</span>(<span class="dt">howmany=</span><span class="kw">n</span>())</a></code></pre></div>
<pre><code>## # A tibble: 2 x 2
##   less  howmany
##   &lt;lgl&gt;   &lt;int&gt;
## 1 FALSE      15
## 2 TRUE        1</code></pre>
<p>Just one value below, with all the rest above.
Getting the right P-value, properly, requires some careful thought
(but you will probably get the right answer anyway). If the
alternative hypothesis is true, and the median is actually bigger than
1100 (say, 1200), you would expect half the data values to be bigger
than 1200 and half smaller. So <em>more</em> than half the data values
would be bigger than <em>1100</em>, and fewer than half of them would be
less than 1100. So, if we are going to reject the null (as it looks as
if we will), that small number of values below 1100 is what we want.</p>
<p>The P-value is the probability of a value 1 or less in a binomial
distribution with <span class="math inline">\(n=16, p=0.5\)</span>:</p>
<div class="sourceCode" id="cb387"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb387-1" data-line-number="1"><span class="kw">sum</span>(<span class="kw">dbinom</span>(<span class="dv">0</span><span class="op">:</span><span class="dv">1</span>,<span class="dv">16</span>,<span class="fl">0.5</span>))</a></code></pre></div>
<pre><code>## [1] 0.0002593994</code></pre>
<p>Or, equivalently, count <em>up</em> from 15:</p>
<div class="sourceCode" id="cb389"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb389-1" data-line-number="1"><span class="kw">sum</span>(<span class="kw">dbinom</span>(<span class="dv">15</span><span class="op">:</span><span class="dv">16</span>,<span class="dv">16</span>,<span class="fl">0.5</span>))</a></code></pre></div>
<pre><code>## [1] 0.0002593994</code></pre>
<p>This is correctly one-sided, so we don’t have to do anything with
it.</p>
<ol start="3" style="list-style-type: lower-alpha">
<li>Use my R package <code>smmr</code> to reproduce your sign test
above, and verify that you get consistent results. (See the
maze-design question for instructions on installing this, if you
haven’t yet.)</li>
</ol>
<p>Solution</p>
<p>This will mean reading the output carefully:</p>
<div class="sourceCode" id="cb391"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb391-1" data-line-number="1"><span class="kw">library</span>(smmr)</a>
<a class="sourceLine" id="cb391-2" data-line-number="2"><span class="kw">sign_test</span>(bags,chips,<span class="dv">1100</span>)</a></code></pre></div>
<pre><code>## $above_below
## below above 
##     1    15 
## 
## $p_values
##   alternative      p_value
## 1       lower 0.9999847412
## 2       upper 0.0002593994
## 3   two-sided 0.0005187988</code></pre>
<p>This time, we’re doing a one-sided test, specifically an
<em>upper-tail</em> test, since we are looking for evidence that the
median is <em>greater than</em> 1100. The results are exactly what we
got “by hand”: 15 values above and one below, and a P-value (look
along the <code>upper</code> line) of 0.00026.
The two-sided P-value of 0.00052 rounds to the same 0.0005 as SAS got.</p>
<p>Alternatively, you can do this:</p>
<div class="sourceCode" id="cb393"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb393-1" data-line-number="1"><span class="kw">sign_test0</span>(bags<span class="op">$</span>chips,<span class="dv">1100</span>)</a></code></pre></div>
<pre><code>## $above_below
## below above 
##     1    15 
## 
## $p_values
##   alternative      p_value
## 1       lower 0.9999847412
## 2       upper 0.0002593994
## 3   two-sided 0.0005187988</code></pre>
<p>with the same result (but only go this way if you need to).</p>
<ol start="4" style="list-style-type: lower-alpha">
<li>Use <code>smmr</code> to obtain a 95% confidence interval for the
median number of chocolate chips per bag of cookies.</li>
</ol>
<p>Solution</p>
<p>Once everything is in place, this is simplicity itself:</p>
<div class="sourceCode" id="cb395"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb395-1" data-line-number="1"><span class="kw">ci_median</span>(bags,chips)</a></code></pre></div>
<pre><code>## [1] 1135.003 1324.996</code></pre>
<p>1135 to 1325. I would round these off to whole numbers, since the data
values are all whole numbers. These values are all above 1100, which
supports the conclusion we got above that the median is above
1100. This is as it should be, because the CI is ``all those medians
that would <em>not</em> be rejected by the sign test’’.</p>
<p>Or,</p>
<div class="sourceCode" id="cb397"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb397-1" data-line-number="1"><span class="kw">ci_median0</span>(bags<span class="op">$</span>chips)</a></code></pre></div>
<pre><code>## [1] 1135.003 1324.996</code></pre>
<p>I’ve mentioned several times that the sign test has less
power than the <span class="math inline">\(t\)</span>-test. Let’s investigate this with a specific example.</p>
<p>Let’s suppose we are testing <span class="math inline">\(H_0: \mu=40\)</span> against <span class="math inline">\(H_a: \mu \ne 40\)</span>,
where <span class="math inline">\(\mu\)</span> is the population mean (and median, as we shall see). Our
population actually has a normal distribution with mean 50 and SD 15,
so that the null hypothesis is <em>wrong</em> and we want to reject it
most of the time. On the other hand, the population actually <em>is</em>
normally-distributed and so the <span class="math inline">\(t\)</span>-test is the right one to use.</p>
<p>(This is an old question, so I tackle the simulated power differently
than I did it in class this time. But see if you can follow what I do
here.)</p>
<ol style="list-style-type: lower-alpha">
<li>Use <code>power.t.test</code> to find the probability that a
<span class="math inline">\(t\)</span>-test correctly rejects the null hypothesis using a sample size
of <span class="math inline">\(n=10\)</span>.</li>
</ol>
<p>Solution</p>
<div class="sourceCode" id="cb399"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb399-1" data-line-number="1"><span class="kw">power.t.test</span>(<span class="dt">delta=</span><span class="dv">50-40</span>,<span class="dt">n=</span><span class="dv">10</span>,<span class="dt">sd=</span><span class="dv">15</span>,<span class="dt">type=</span><span class="st">&quot;one.sample&quot;</span>,<span class="dt">alternative=</span><span class="st">&quot;two.sided&quot;</span>)</a></code></pre></div>
<pre><code>## 
##      One-sample t test power calculation 
## 
##               n = 10
##           delta = 10
##              sd = 15
##       sig.level = 0.05
##           power = 0.4691805
##     alternative = two.sided</code></pre>
<p>The power is 0.469. Not great, but we’ll see how this stacks up
against the sign test.</p>
<ol start="2" style="list-style-type: lower-alpha">
<li>What code in R would draw a random sample of size 10 from the
<em>true</em> population distribution and save the sample in a variable?</li>
</ol>
<p>Solution</p>
<p>The data actually have a normal distribution with mean 50 and
SD 15, so we use <code>rnorm</code> with this mean and SD, obtaining
10 values:</p>
<div class="sourceCode" id="cb401"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb401-1" data-line-number="1">x=<span class="kw">rnorm</span>(<span class="dv">10</span>,<span class="dv">50</span>,<span class="dv">15</span>)  </a>
<a class="sourceLine" id="cb401-2" data-line-number="2">x</a></code></pre></div>
<pre><code>##  [1] 31.62951 36.11209 45.54645 47.17731 48.19507 81.02678 64.07474
##  [8] 57.41174 43.79292 33.56827</code></pre>
<ol start="3" style="list-style-type: lower-alpha">
<li>What code would count how many of the sampled values are less
than 40 and how many are greater (or equal)?</li>
</ol>
<p>Solution</p>
<p>The way we know this is to put <code>x</code> into a data frame first:</p>
<div class="sourceCode" id="cb403"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb403-1" data-line-number="1"><span class="kw">tibble</span>(x) <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">count</span>(x<span class="op">&lt;</span><span class="dv">40</span>)</a></code></pre></div>
<pre><code>## # A tibble: 2 x 2
##   `x &lt; 40`     n
##   &lt;lgl&gt;    &lt;int&gt;
## 1 FALSE        7
## 2 TRUE         3</code></pre>
<p>2 values less (and 8 greater-or-equal).</p>
<ol start="4" style="list-style-type: lower-alpha">
<li>It turns out the sign test would reject <span class="math inline">\(H_0: M=40\)</span> against
<span class="math inline">\(H_a: M \ne 40\)</span> at <span class="math inline">\(\alpha=0.05\)</span> if the smaller of the numbers in the
last part is 1 or less. (<span class="math inline">\(M\)</span> is the population median.)
Add to your pipeline to obtain <code>TRUE</code>
if you should reject the null for your
data and <code>FALSE</code> otherwise.</li>
</ol>
<p>Solution</p>
<p>This is actually easier than you might think. The output from
<code>count</code> is a data frame with a column called <code>n</code>,
whose minimum value you want. I add to my pipeline:</p>
<div class="sourceCode" id="cb405"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb405-1" data-line-number="1"><span class="kw">tibble</span>(x) <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">count</span>(x<span class="op">&lt;</span><span class="dv">40</span>) <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb405-2" data-line-number="2"><span class="kw">summarize</span>(<span class="dt">the_min=</span><span class="kw">min</span>(n)) <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb405-3" data-line-number="3"><span class="kw">mutate</span>(<span class="dt">is_rejected=</span>(the_min<span class="op">&lt;=</span><span class="dv">1</span>))</a></code></pre></div>
<pre><code>## # A tibble: 1 x 2
##   the_min is_rejected
##     &lt;dbl&gt; &lt;lgl&gt;      
## 1       3 FALSE</code></pre>
<p>This will fail sometimes. If all 10 of your sample values are greater
than 40, which they might turn out to be, you’ll get a table with only
one line, <code>FALSE</code> and 10; the minimum of the <code>n</code> values
is 10 (since there is only one), and it will falsely say that you
should not reject. The fix is</p>
<div class="sourceCode" id="cb407"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb407-1" data-line-number="1"><span class="kw">tibble</span>(x) <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">count</span>(x<span class="op">&lt;</span><span class="dv">40</span>) <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb407-2" data-line-number="2"><span class="kw">summarize</span>(<span class="dt">the_min=</span><span class="kw">min</span>(n)) <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb407-3" data-line-number="3"><span class="kw">mutate</span>(<span class="dt">is_rejected=</span>(the_min<span class="op">&lt;=</span><span class="dv">1</span> <span class="op">|</span><span class="st"> </span>the_min<span class="op">==</span><span class="dv">10</span>))</a></code></pre></div>
<pre><code>## # A tibble: 1 x 2
##   the_min is_rejected
##     &lt;dbl&gt; &lt;lgl&gt;      
## 1       3 FALSE</code></pre>
<p>The above is almost the right thing, but not quite: we only want that value
that I called <code>is_rejected</code>, rather than the whole data frame,
so a <code>pull</code> will grab it:</p>
<div class="sourceCode" id="cb409"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb409-1" data-line-number="1"><span class="kw">tibble</span>(x) <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">count</span>(x<span class="op">&lt;</span><span class="dv">40</span>) <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb409-2" data-line-number="2"><span class="kw">summarize</span>(<span class="dt">the_min=</span><span class="kw">min</span>(n)) <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb409-3" data-line-number="3"><span class="kw">mutate</span>(<span class="dt">is_rejected=</span>(the_min<span class="op">&lt;=</span><span class="dv">1</span> <span class="op">|</span><span class="st"> </span>the_min<span class="op">==</span><span class="dv">10</span>)) <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb409-4" data-line-number="4"><span class="kw">pull</span>(is_rejected)</a></code></pre></div>
<pre><code>## [1] FALSE</code></pre>
<p>You might be wondering where the “1 or less” came from. Getting a
P-value for the sign test involves the binomial distribution: if the
null is correct, each data value is independently either above or
below 40, with probability 0.5 of each, so the number of values below
40 (say) is binomial with <span class="math inline">\(n=10\)</span> and <span class="math inline">\(p=0.5\)</span>. The P-value for 1
observed value below 40 and the rest above is</p>
<div class="sourceCode" id="cb411"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb411-1" data-line-number="1"><span class="dv">2</span><span class="op">*</span><span class="kw">pbinom</span>(<span class="dv">1</span>,<span class="dv">10</span>,<span class="fl">0.5</span>)  </a></code></pre></div>
<pre><code>## [1] 0.02148438</code></pre>
<p>which is less than 0.05; the P-value for 2 values below 40 and the
rest above is</p>
<div class="sourceCode" id="cb413"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb413-1" data-line-number="1"><span class="dv">2</span><span class="op">*</span><span class="kw">pbinom</span>(<span class="dv">2</span>,<span class="dv">10</span>,<span class="fl">0.5</span>)    </a></code></pre></div>
<pre><code>## [1] 0.109375</code></pre>
<p>which is bigger than 0.05.</p>
<p>You might have encountered the term “critical region” for a
test. This is the values of your test statistic that you would reject
the null hypothesis for. In this case, the critical region is 1 and 0
observations below 40, along with 1 and 0 observations above 40.</p>
<p>When you’re thinking about power, I think it’s easiest to think in
terms of the critical region (rather than directly in terms of
P-values) since you have a certain <span class="math inline">\(\alpha\)</span> in mind all the way
through, 0.05 in the power examples that I’ve done. The steps are then:</p>
<ul>
<li><p>Work out the critical region for your test, the values of the
test statistic (or sample mean or sample count) that would lead to
rejecting the null hypothesis.</p></li>
<li><p>Under your particular alternative hypothesis, find the
probability of falling into your critical region.</p></li>
</ul>
<p>When I say “work out”, I mean either calculating (along the lines of
STAB57), or simulating, as we have done here.</p>
<ol start="5" style="list-style-type: lower-alpha">
<li>Use <code>rerun</code> to simulate the above process 1000 times:
drawing a random sample from a normal distribution with mean 50 and SD
15, counting the number of values below and above 40, rejecting if the
minimum of those is 1 or less, then counting the number of rejections
out of 1000.</li>
</ol>
<p>Solution</p>
<p>The way we’ve used <code>rerun</code> is to use it to select the
random samples, and then we use <code>map</code> ideas to do what we
want to do with each random sample, along the lines of what we did
with the one random sample above.
This is liable to go wrong the first few times, so make sure that
each line works before you go on to the next. (<code>rerun</code> will
produce you a <code>list</code> of random samples, with each of which
you want to do something.) While you’re debugging, try it with a
small number of random samples like 5.
I start with setting the random number seed, so it comes out the
same each time. I discuss the results below and the code below that.</p>
<div class="sourceCode" id="cb415"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb415-1" data-line-number="1"><span class="kw">set.seed</span>(<span class="dv">457299</span>)</a>
<a class="sourceLine" id="cb415-2" data-line-number="2"><span class="kw">rerun</span>(<span class="dv">1000</span>,<span class="kw">rnorm</span>(<span class="dv">10</span>,<span class="dv">50</span>,<span class="dv">15</span>)) <span class="op">%&gt;%</span><span class="st"> </span></a>
<a class="sourceLine" id="cb415-3" data-line-number="3"><span class="kw">map</span>(<span class="op">~</span><span class="kw">tibble</span>(<span class="dt">x=</span>.)) <span class="op">%&gt;%</span><span class="st"> </span></a>
<a class="sourceLine" id="cb415-4" data-line-number="4"><span class="kw">map</span>(<span class="op">~</span><span class="kw">count</span>(.,x<span class="op">&lt;</span><span class="dv">40</span>)) <span class="op">%&gt;%</span><span class="st"> </span></a>
<a class="sourceLine" id="cb415-5" data-line-number="5"><span class="kw">map</span>(<span class="op">~</span><span class="kw">summarize</span>(.,<span class="dt">the_min=</span><span class="kw">min</span>(n))) <span class="op">%&gt;%</span><span class="st"> </span></a>
<a class="sourceLine" id="cb415-6" data-line-number="6"><span class="kw">map</span>(<span class="op">~</span><span class="kw">mutate</span>(.,<span class="dt">is_rejected=</span>(the_min<span class="op">&lt;=</span><span class="dv">1</span> <span class="op">|</span><span class="st"> </span>the_min<span class="op">==</span><span class="dv">10</span>))) <span class="op">%&gt;%</span><span class="st"> </span></a>
<a class="sourceLine" id="cb415-7" data-line-number="7"><span class="kw">map_lgl</span>(<span class="op">~</span><span class="kw">pull</span>(.,is_rejected)) <span class="op">%&gt;%</span><span class="st"> </span></a>
<a class="sourceLine" id="cb415-8" data-line-number="8"><span class="kw">tibble</span>(<span class="dt">was_true=</span>.) <span class="op">%&gt;%</span><span class="st"> </span></a>
<a class="sourceLine" id="cb415-9" data-line-number="9"><span class="kw">count</span>(was_true)</a></code></pre></div>
<pre><code>## # A tibble: 2 x 2
##   was_true     n
##   &lt;lgl&gt;    &lt;int&gt;
## 1 FALSE      757
## 2 TRUE       243</code></pre>
<p>The estimated power of the sign test is 0.243, since that was the
number of times a simulated sample gave us 0 or 1 values above or
below 40 (and the rest on the other side).</p>
<p>All right, that code is seriously scary. Let me try to take you
through it.</p>
<ul>
<li><p>The <code>rerun</code> line is the same kind of thing we had before:
generate 1000 different random samples of size 10 from a normal
distribution with mean 50 and SD 15.</p></li>
<li><p>The output from the previous step is a <code>list</code> of
vectors. But we like data frames to count things in, so for each
vector we turn it into a data frame, filling a column called
<code>x</code> with whatever was in each vector (that random sample). So
now we have 1000 data frames each containing a column called
<code>x</code>.</p></li>
<li><p>Next, in each of those data frames, count up how many of the
<code>x</code> values are less than 40. This will produce a data frame
each time containing a column <code>n</code> that is the
frequencies. Here and below, the <code>.</code> is used to denote
“it”: that is, each of the elements of the list created originally
by <code>rerun</code> that we are doing something with. Also, at the
moment, the output for each element of the list is a data frame, so
we stick with <code>map</code> for the time being.</p></li>
<li><p>Next, for each of those tables of frequencies, find the smallest
one and call it <code>the_min</code>. (As discussed above, all the
values might be bigger than 40, in which case <code>the_min</code> will
be 10 rather than 0, which we handle next.)</p></li>
<li><p>Next, we create a new column called <code>is_rejected</code> which
says that we should reject a median of 40 if the minimum value we
just calculated is 1 or less, or if it happens to be 10, in which
case that would have been the only entry in the frequency table, so
that the missing one would have been zero.</p></li>
<li><p>Next, we pull out only the true-or-false value in
<code>is_rejected</code>. At last, the answer here is not a data frame
but a simple logical value; <code>map_lgl</code> is like
<code>map_dbl</code> except that the thing we are doing returns a
<code>TRUE</code> or a <code>FALSE</code> rather than a number.</p></li>
<li><p>At this point we have a vector of 1000 true-or-false. We want to
count them, so we put them into a data frame (with a column called
<code>was_true</code>), and in the last line, count them up. There are
243 (correct) rejections and 757 (incorrect) non-rejections.</p></li>
</ul>
<p>You may now breathe again.</p>
<p>I’m now thinking a better way to do this is to write a function that
takes a sample (in a vector) and returns a TRUE or FALSE according to
whether or not a median of 40 would be rejected for that sample:</p>
<div class="sourceCode" id="cb417"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb417-1" data-line-number="1">is_reject=<span class="cf">function</span>(x) {</a>
<a class="sourceLine" id="cb417-2" data-line-number="2"><span class="kw">tibble</span>(<span class="dt">x=</span>x) <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb417-3" data-line-number="3"><span class="kw">count</span>(x<span class="op">&lt;</span><span class="dv">40</span>) <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb417-4" data-line-number="4"><span class="kw">summarize</span>(<span class="dt">the_min=</span><span class="kw">min</span>(n)) <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb417-5" data-line-number="5"><span class="kw">mutate</span>(<span class="dt">is_rejected=</span>the_min<span class="op">&lt;=</span><span class="dv">1</span> <span class="op">|</span><span class="st"> </span>the_min<span class="op">==</span><span class="dv">10</span>) <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb417-6" data-line-number="6"><span class="kw">pull</span>(is_rejected)</a>
<a class="sourceLine" id="cb417-7" data-line-number="7">}</a></code></pre></div>
<p>Now, we have to use that. This function will be “mapped” over for
each of the random samples that come out of <code>rerun</code>, but now
there will be only one <code>map</code> because the complication of the
multiple <code>maps</code> has been subsumed into this one function. I’ll
set my random number seed so that I get the same results as before:</p>
<div class="sourceCode" id="cb418"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb418-1" data-line-number="1"><span class="kw">set.seed</span>(<span class="dv">457299</span>)</a>
<a class="sourceLine" id="cb418-2" data-line-number="2"><span class="kw">rerun</span>(<span class="dv">1000</span>,<span class="kw">rnorm</span>(<span class="dv">10</span>,<span class="dv">50</span>,<span class="dv">15</span>)) <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb418-3" data-line-number="3"><span class="kw">map_lgl</span>(<span class="op">~</span><span class="kw">is_reject</span>(.)) <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb418-4" data-line-number="4"><span class="kw">tibble</span>(<span class="dt">rejected=</span>.) <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb418-5" data-line-number="5"><span class="kw">count</span>(rejected)</a></code></pre></div>
<pre><code>## # A tibble: 2 x 2
##   rejected     n
##   &lt;lgl&gt;    &lt;int&gt;
## 1 FALSE      757
## 2 TRUE       243</code></pre>
<p>Same results, and yeah, I like that a lot better.</p>
<ol start="6" style="list-style-type: lower-alpha">
<li>Which is more powerful in this case, the sign test or the
<span class="math inline">\(t\)</span>-test? How do you know?</li>
</ol>
<p>Solution</p>
<p>The power of the sign test is estimated as 0.243, which is quite a bit less
than the power of the <span class="math inline">\(t\)</span>-test, which we found back in (a) to be
0.469. So the <span class="math inline">\(t\)</span>-test, in this situation where it is valid, is
the right test to use: it is (a) valid and (b) more powerful.
So the <span class="math inline">\(t\)</span>-test is more powerful. One way to think about how
<em>much</em> more powerful is to ask `<code>how much smaller of a sample size would be needed for the $t$-test to have the same power as this sign test?'' The power of my sign test was 0.243, so in</code>power.t.test<code>we set</code>power<code>equal to that and omit the sample size</code>n`:</p>
<div class="sourceCode" id="cb420"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb420-1" data-line-number="1"><span class="kw">power.t.test</span>(<span class="dt">delta=</span><span class="dv">50-40</span>,<span class="dt">power=</span><span class="fl">0.243</span>,<span class="dt">sd=</span><span class="dv">15</span>,<span class="dt">type=</span><span class="st">&quot;one.sample&quot;</span>,<span class="dt">alternative=</span><span class="st">&quot;two.sided&quot;</span>)</a></code></pre></div>
<pre><code>## 
##      One-sample t test power calculation 
## 
##               n = 5.599293
##           delta = 10
##              sd = 15
##       sig.level = 0.05
##           power = 0.243
##     alternative = two.sided</code></pre>
<p>A sample of size 6 gives the same power for the <span class="math inline">\(t\)</span>-test that a
sample of size 10 does for the sign test. The ratio of these two
sample sizes is called the <em>relative efficiency</em> of the two
tests: in this case, the <span class="math inline">\(t\)</span>-test is <span class="math inline">\(10/6=1.67\)</span> times more
efficient. The data that you have are being used <code>more efficiently'' by the $t$-test. It is possible to derive\endnote{Meaning, I forget how to do it. But it has something to do with looking at alternatives that are very close to the null.}  the limiting relative efficiency of the $t$ test relative to the sign test when the data are actually normal, as the sample size gets larger. This turns out not to depend on how far wrong the null is (as long as it is the same for both the $t$-test and the sign test). This</code>asymptotic relative
efficiency’’ is <span class="math inline">\(\pi/2=1.57\)</span>. Our relative efficiency for power
0.243, namely 1.67, was pretty close to this, even though our
sample sizes 10 and 6 are not especially close to infinity.
This says that, if your data are actually from a normal
distribution, you do a lot better to use the <span class="math inline">\(t\)</span>-test than the
sign test, because the sign test is wasteful of data (it only uses
above/below rather than the actual values).
If your data are <em>not</em> from a normal distribution, then the
story can be very different.
Of course you knew I would investigate this. There is a
distribution called the “Laplace” or “double exponential”
distribution, that has very long tails. The distribution is not in
base R, but there is a package called <code>smoothmest</code> that
contains a function <code>rdoublex</code> to generate random values from
this distribution. So we’re going to do a simulation investigation
of the power of the sign test for Laplace data, by the same
simulation technique that we did above. Like the normal, the Laplace
distribution is symmetric, so its mean and median are the same
(which makes our life easier).</p>
<p>Let’s test the hypothesis that the median is zero. We’ll suppose that
the true median is 0.5 (this is called <code>mu</code> in
<code>rdoublex</code>). The first problem we run into is that we can’t use
<code>power.t.test</code> because they assume normal data, which we are
far from having. So we have to do two simulations: one to simulate the
power of the <span class="math inline">\(t\)</span> test, and one to simulate the power of the sign test.</p>
<p>To simulate the <span class="math inline">\(t\)</span> test, we first have to generate some Laplace data
with the true mean of 0.5. We’ll use a sample size of 50 throughout
these simulations.</p>
<div class="sourceCode" id="cb422"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb422-1" data-line-number="1"><span class="kw">library</span>(smoothmest)</a></code></pre></div>
<pre><code>## Loading required package: MASS</code></pre>
<pre><code>## 
## Attaching package: &#39;MASS&#39;</code></pre>
<pre><code>## The following object is masked from &#39;package:dplyr&#39;:
## 
##     select</code></pre>
<div class="sourceCode" id="cb426"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb426-1" data-line-number="1">rl=<span class="kw">rdoublex</span>(<span class="dv">50</span>,<span class="dt">mu=</span><span class="fl">0.5</span>)</a>
<a class="sourceLine" id="cb426-2" data-line-number="2">rl</a></code></pre></div>
<pre><code>##  [1] -0.33323285  0.70569291 -1.22513053  0.68517708  0.12778518
##  [6]  0.50749949  0.26700527  1.90236874  0.53288312 -0.37374732
## [11]  0.27256566  0.53365929  0.43581431 -0.01545866  0.18594908
## [16] -0.40403202  1.13540289  0.16137306 -0.23360644 -0.74050354
## [21]  2.92089551 -2.72173880  0.48428815  1.23636045  0.17078618
## [26]  1.72456334  0.07903058  0.25210411  0.09512810  2.52310082
## [31] -2.13629814  0.81851434  0.74615575 -0.26068744  2.70683355
## [36]  1.46981530  1.45646489 -0.20232517  6.65249860  1.51575026
## [41] -0.07606399 -1.11338640 -1.20427995 -0.70986104 -1.66466321
## [46]  0.55346854  0.66091469  0.72100677  0.92025176  0.98922656</code></pre>
<p>This seems to have some unusual values, far away from zero:</p>
<div class="sourceCode" id="cb428"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb428-1" data-line-number="1"><span class="kw">tibble</span>(rl) <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb428-2" data-line-number="2"><span class="kw">ggplot</span>(<span class="kw">aes</span>(<span class="dt">sample=</span>rl))<span class="op">+</span></a>
<a class="sourceLine" id="cb428-3" data-line-number="3"><span class="kw">stat_qq</span>()<span class="op">+</span><span class="kw">stat_qq_line</span>()</a></code></pre></div>
<p><img src="07-sign-mood-median_files/figure-html/unnamed-chunk-48-1.png" width="672" /></p>
<p>You see the long tails compared to the normal.</p>
<p>Now, we feed these values into <code>t.test</code> and see whether we
reject a null median of zero (at <span class="math inline">\(\alpha=0.05\)</span>):</p>
<div class="sourceCode" id="cb429"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb429-1" data-line-number="1">tt=<span class="kw">t.test</span>(rl)  </a>
<a class="sourceLine" id="cb429-2" data-line-number="2">tt</a></code></pre></div>
<pre><code>## 
##  One Sample t-test
## 
## data:  rl
## t = 2.2556, df = 49, p-value = 0.0286
## alternative hypothesis: true mean is not equal to 0
## 95 percent confidence interval:
##  0.04959344 0.85981931
## sample estimates:
## mean of x 
## 0.4547064</code></pre>
<p>Or we can just pull out the P-value and even compare it to 0.05:</p>
<div class="sourceCode" id="cb431"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb431-1" data-line-number="1">pval=tt<span class="op">$</span>p.value  </a>
<a class="sourceLine" id="cb431-2" data-line-number="2">pval</a></code></pre></div>
<pre><code>## [1] 0.02859596</code></pre>
<div class="sourceCode" id="cb433"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb433-1" data-line-number="1">is.reject=(pval<span class="op">&lt;=</span><span class="fl">0.05</span>)</a>
<a class="sourceLine" id="cb433-2" data-line-number="2">is.reject</a></code></pre></div>
<pre><code>## [1] TRUE</code></pre>
<p>$</p>
<p>This one has a small P-value and so the null median of 0 should be
(correctly) rejected.</p>
<p>We’ll use these ideas to simulate the power of the <span class="math inline">\(t\)</span>-test for these
data, testing a mean of 0. This uses the same ideas as for any power
simulation; the difference here is the true distribution:</p>
<div class="sourceCode" id="cb435"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb435-1" data-line-number="1"><span class="kw">rerun</span>(<span class="dv">1000</span>,<span class="kw">rdoublex</span>(<span class="dv">50</span>,<span class="dt">mu=</span><span class="fl">0.5</span>)) <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb435-2" data-line-number="2"><span class="kw">map</span>(<span class="op">~</span><span class="kw">t.test</span>(.,<span class="dt">mu=</span><span class="dv">0</span>)) <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb435-3" data-line-number="3"><span class="kw">map_dbl</span>(<span class="st">&quot;p.value&quot;</span>) -&gt;</a>
<a class="sourceLine" id="cb435-4" data-line-number="4">pvals</a></code></pre></div>
<p>and then count them:</p>
<div class="sourceCode" id="cb436"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb436-1" data-line-number="1"><span class="kw">tibble</span>(pvals) <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">count</span>(pvals<span class="op">&lt;=</span><span class="fl">0.05</span>)</a></code></pre></div>
<pre><code>## # A tibble: 2 x 2
##   `pvals &lt;= 0.05`     n
##   &lt;lgl&gt;           &lt;int&gt;
## 1 FALSE             304
## 2 TRUE              696</code></pre>
<p>And now we simulate the sign test. Since what we want is a P-value
from a vector, the easiest way to do this is to use
<code>pval_sign0</code> from <code>smmr</code>, which returns exactly the
two-sided P-value that we want, so that the procedure is a step simpler:</p>
<div class="sourceCode" id="cb438"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb438-1" data-line-number="1"><span class="kw">rerun</span>(<span class="dv">1000</span>,<span class="kw">rdoublex</span>(<span class="dv">50</span>,<span class="dt">mu=</span><span class="fl">0.5</span>)) <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb438-2" data-line-number="2"><span class="kw">map_dbl</span>(<span class="op">~</span><span class="kw">pval_sign0</span>(<span class="dv">0</span>,.)) -&gt;</a>
<a class="sourceLine" id="cb438-3" data-line-number="3">pvals_sign</a></code></pre></div>
<p>and then</p>
<div class="sourceCode" id="cb439"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb439-1" data-line-number="1"><span class="kw">tibble</span>(pvals_sign) <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">count</span>(pvals_sign<span class="op">&lt;=</span><span class="fl">0.05</span>)</a></code></pre></div>
<pre><code>## # A tibble: 2 x 2
##   `pvals_sign &lt;= 0.05`     n
##   &lt;lgl&gt;                &lt;int&gt;
## 1 FALSE                  239
## 2 TRUE                   761</code></pre>
<p>For data from this Laplace
distribution, the power of this <span class="math inline">\(t\)</span>-test is 0.696, but the power of
the sign test on the same data is 0.761, <em>bigger</em>. For
Laplace-distributed data, the sign test is <em>more</em> powerful than
the <span class="math inline">\(t\)</span>-test.</p>
<p>This is not to say that you will ever run into data that comes from
the Laplace distribution. But the moral of the story is that the sign
test <em>can</em> be more powerful than the <span class="math inline">\(t\)</span>-test, under the right
circumstances (and the above simulation is the “proof” of that
statement). So a blanket statement like ``the sign test is not very
powerful’’ needs to be qualified a bit: when your data come from a
sufficiently long-tailed distribution, the sign test can be more
powerful relative to the <span class="math inline">\(t\)</span>-test than you would think.</p>
<p>I finish by “unloading” the two packages that got loaded:</p>
<div class="sourceCode" id="cb441"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb441-1" data-line-number="1"><span class="kw">detach</span>(package<span class="op">:</span>smoothmest, <span class="dt">unload=</span>T)</a>
<a class="sourceLine" id="cb441-2" data-line-number="2"><span class="kw">detach</span>(package<span class="op">:</span>MASS, <span class="dt">unload=</span>T)</a></code></pre></div>

</div>
            </section>

          </div>
        </div>
      </div>
<a href="power-and-sample-size.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="matched-pairs-t-and-sign-test.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/lunr.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"google": false,
"linkedin": false,
"weibo": false,
"instapper": false,
"vk": false,
"all": ["facebook", "google", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": null,
"text": null
},
"download": null,
"toc": {
"collapse": "subsection"
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://cdn.bootcss.com/mathjax/2.7.1/MathJax.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:" && /^https?:/.test(src))
      src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
