<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">

<head>

<meta charset="utf-8">
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<meta name="generator" content="pandoc" />
<meta name="viewport" content="width=device-width, initial-scale=1">
<meta property="og:title" content="Problems and Solutions in Applied Statistics" />
<meta property="og:type" content="book" />
<meta property="og:url" content="<a href="http://ritsokiguess.site/pasias" class="uri">http://ritsokiguess.site/pasias</a>" />

<meta property="og:description" content="A set of problems and solutions, in R, on various parts of applied statistics" />
<meta name="github-repo" content="nxskok/pasias" />

<meta name="author" content="Ken Butler" />

<meta name="date" content="2018-10-09" />

<script type="text/x-mathjax-config">
MathJax.Hub.Config({
  TeX: { equationNumbers: { autoNumber: "AMS" } }
});
</script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.2/MathJax.js?config=TeX-AMS_CHTML-full" type="text/javascript"></script>

<meta name="description" content="A set of problems and solutions, in R, on various parts of applied statistics">

<title>Problems and Solutions in Applied Statistics</title>

<link href="libs/tufte-css-2015.12.29/tufte-fonts.css" rel="stylesheet" />
<link href="libs/tufte-css-2015.12.29/tufte-background.css" rel="stylesheet" />
<link href="libs/tufte-css-2015.12.29/tufte-italics.css" rel="stylesheet" />
<link href="libs/tufte-css-2015.12.29/tufte.css" rel="stylesheet" />


<style type="text/css">code{white-space: pre;}</style>
<style type="text/css">
a.sourceLine { display: inline-block; line-height: 1.25; }
a.sourceLine { pointer-events: none; color: inherit; text-decoration: inherit; }
a.sourceLine:empty { height: 1.2em; position: absolute; }
.sourceCode { overflow: visible; }
code.sourceCode { white-space: pre; position: relative; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
code.sourceCode { white-space: pre-wrap; }
a.sourceLine { text-indent: -1em; padding-left: 1em; }
}
pre.numberSource a.sourceLine
  { position: relative; }
pre.numberSource a.sourceLine:empty
  { position: absolute; }
pre.numberSource a.sourceLine::before
  { content: attr(data-line-number);
    position: absolute; left: -5em; text-align: right; vertical-align: baseline;
    border: none; pointer-events: all;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {  }
@media screen {
a.sourceLine::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>


<link rel="stylesheet" href="toc.css" type="text/css" />

</head>

<body>



<div class="row">
<div class="col-sm-12">
<div id="TOC">
<ul>
<li><a href="index.html#introduction"><span class="toc-section-number">1</span> Introduction</a></li>
<li class="has-sub"><a href="getting-used-to-r-and-r-studio.html#getting-used-to-r-and-r-studio"><span class="toc-section-number">2</span> Getting used to R and R Studio</a><ul>
<li><a href="getting-used-to-r-and-r-studio.html#getting-an-r-studio-cloud-account"><span class="toc-section-number">2.1</span> Getting an R Studio Cloud account</a></li>
<li><a href="getting-used-to-r-and-r-studio.html#getting-started"><span class="toc-section-number">2.2</span> Getting started</a></li>
<li><a href="getting-used-to-r-and-r-studio.html#reading-data-from-a-file"><span class="toc-section-number">2.3</span> Reading data from a file</a></li>
</ul></li>
<li class="has-sub"><a href="reading-in-data-and-drawing-some-graphs.html#reading-in-data-and-drawing-some-graphs"><span class="toc-section-number">3</span> Reading in data and drawing some graphs</a><ul>
<li><a href="reading-in-data-and-drawing-some-graphs.html#orange-juice"><span class="toc-section-number">3.1</span> Orange juice</a></li>
<li><a href="reading-in-data-and-drawing-some-graphs.html#making-soap"><span class="toc-section-number">3.2</span> Making soap</a></li>
<li><a href="reading-in-data-and-drawing-some-graphs.html#handling-shipments"><span class="toc-section-number">3.3</span> Handling shipments</a></li>
</ul></li>
<li class="has-sub"><a href="data-exploration.html#data-exploration"><span class="toc-section-number">4</span> Data exploration</a><ul>
<li><a href="data-exploration.html#north-carolina-births"><span class="toc-section-number">4.1</span> North Carolina births</a></li>
<li><a href="data-exploration.html#more-about-the-nc-births"><span class="toc-section-number">4.2</span> More about the NC births</a></li>
<li><a href="data-exploration.html#nenana-alaska"><span class="toc-section-number">4.3</span> Nenana, Alaska</a></li>
<li><a href="data-exploration.html#computerized-accounting"><span class="toc-section-number">4.4</span> Computerized accounting</a></li>
</ul></li>
<li class="has-sub"><a href="one-sample-inference.html#one-sample-inference"><span class="toc-section-number">5</span> One-sample inference</a><ul>
<li><a href="one-sample-inference.html#hunter-gatherers-in-australia"><span class="toc-section-number">5.1</span> Hunter-gatherers in Australia</a></li>
<li><a href="one-sample-inference.html#length-of-gestation-in-north-carolina"><span class="toc-section-number">5.2</span> Length of gestation in North Carolina</a></li>
<li><a href="one-sample-inference.html#inferring-ice-break-up-in-nenana"><span class="toc-section-number">5.3</span> Inferring ice break-up in Nenana</a></li>
</ul></li>
<li class="has-sub"><a href="two-sample-inference.html#two-sample-inference"><span class="toc-section-number">6</span> Two-sample inference</a><ul>
<li><a href="two-sample-inference.html#children-and-electronic-devices"><span class="toc-section-number">6.1</span> Children and electronic devices</a></li>
<li><a href="two-sample-inference.html#parking-close-to-the-curb"><span class="toc-section-number">6.2</span> Parking close to the curb</a></li>
</ul></li>
<li class="has-sub"><a href="power-and-sample-size.html#power-and-sample-size"><span class="toc-section-number">7</span> Power and sample size</a><ul>
<li><a href="power-and-sample-size.html#simulating-power"><span class="toc-section-number">7.1</span> Simulating power</a></li>
<li><a href="power-and-sample-size.html#calculating-power-and-sample-size-for-estimating-mean"><span class="toc-section-number">7.2</span> Calculating power and sample size for estimating mean</a></li>
<li><a href="power-and-sample-size.html#simulating-power-for-proportions"><span class="toc-section-number">7.3</span> Simulating power for proportions</a></li>
</ul></li>
<li class="has-sub"><a href="the-sign-test-and-moods-median-test.html#the-sign-test-and-moods-median-test"><span class="toc-section-number">8</span> The sign test and Mood’s median test</a><ul>
<li><a href="the-sign-test-and-moods-median-test.html#running-a-maze"><span class="toc-section-number">8.1</span> Running a maze</a></li>
<li><a href="the-sign-test-and-moods-median-test.html#chocolate-chips"><span class="toc-section-number">8.2</span> Chocolate chips</a></li>
<li><a href="the-sign-test-and-moods-median-test.html#the-power-of-the-sign-test"><span class="toc-section-number">8.3</span> The power of the sign test</a></li>
<li><a href="the-sign-test-and-moods-median-test.html#sugar-in-breakfast-cereals"><span class="toc-section-number">8.4</span> Sugar in breakfast cereals</a></li>
<li><a href="the-sign-test-and-moods-median-test.html#fear-of-math"><span class="toc-section-number">8.5</span> Fear of math</a></li>
<li><a href="the-sign-test-and-moods-median-test.html#medical-instructions"><span class="toc-section-number">8.6</span> Medical instructions</a></li>
</ul></li>
<li class="has-sub"><a href="matched-pairs-t-and-sign-test.html#matched-pairs-t-and-sign-test"><span class="toc-section-number">9</span> Matched pairs t and sign test</a><ul>
<li><a href="matched-pairs-t-and-sign-test.html#measuring-body-fat"><span class="toc-section-number">9.1</span> Measuring body fat</a></li>
<li><a href="matched-pairs-t-and-sign-test.html#throwing-baseballs-and-softballs"><span class="toc-section-number">9.2</span> Throwing baseballs and softballs</a></li>
<li><a href="matched-pairs-t-and-sign-test.html#changes-in-salary"><span class="toc-section-number">9.3</span> Changes in salary</a></li>
</ul></li>
<li class="has-sub"><a href="normal-quantile-plots.html#normal-quantile-plots"><span class="toc-section-number">10</span> Normal quantile plots</a><ul>
<li><a href="normal-quantile-plots.html#lengths-of-heliconia-flowers"><span class="toc-section-number">10.1</span> Lengths of heliconia flowers</a></li>
<li><a href="normal-quantile-plots.html#ferritin-and-normality"><span class="toc-section-number">10.2</span> Ferritin and normality</a></li>
</ul></li>
<li class="has-sub"><a href="analysis-of-variance.html#analysis-of-variance"><span class="toc-section-number">11</span> Analysis of variance</a><ul>
<li><a href="analysis-of-variance.html#movie-ratings-and-lengths"><span class="toc-section-number">11.1</span> Movie ratings and lengths</a></li>
<li><a href="analysis-of-variance.html#deer-and-how-much-they-eat"><span class="toc-section-number">11.2</span> Deer and how much they eat</a></li>
<li><a href="analysis-of-variance.html#movie-ratings-again"><span class="toc-section-number">11.3</span> Movie ratings again</a></li>
<li><a href="analysis-of-variance.html#atomic-weight-of-carbon"><span class="toc-section-number">11.4</span> Atomic weight of carbon</a></li>
</ul></li>
<li class="has-sub"><a href="tidying-and-selecting-data.html#tidying-and-selecting-data"><span class="toc-section-number">12</span> Tidying and selecting data</a><ul>
<li><a href="tidying-and-selecting-data.html#tidying-the-jays-data"><span class="toc-section-number">12.1</span> Tidying the Jays data</a></li>
<li><a href="tidying-and-selecting-data.html#ethanol-and-sleep-time-in-rats"><span class="toc-section-number">12.2</span> Ethanol and sleep time in rats</a></li>
<li><a href="tidying-and-selecting-data.html#growth-of-tomatoes"><span class="toc-section-number">12.3</span> Growth of tomatoes</a></li>
<li><a href="tidying-and-selecting-data.html#pain-relief-in-migraine-headaches-again"><span class="toc-section-number">12.4</span> Pain relief in migraine headaches (again)</a></li>
<li><a href="tidying-and-selecting-data.html#location-species-and-disease-in-plants"><span class="toc-section-number">12.5</span> Location, species and disease in plants</a></li>
<li><a href="tidying-and-selecting-data.html#cars"><span class="toc-section-number">12.6</span> Cars</a></li>
<li><a href="tidying-and-selecting-data.html#number-1-songs"><span class="toc-section-number">12.7</span> Number 1 songs</a></li>
<li><a href="tidying-and-selecting-data.html#bikes-on-college"><span class="toc-section-number">12.8</span> Bikes on College</a></li>
</ul></li>
<li class="has-sub"><a href="regression.html#regression"><span class="toc-section-number">13</span> Regression</a><ul>
<li><a href="regression.html#rainfall-in-california"><span class="toc-section-number">13.1</span> Rainfall in California</a></li>
<li><a href="regression.html#carbon-monoxide-in-cigarettes"><span class="toc-section-number">13.2</span> Carbon monoxide in cigarettes</a></li>
<li><a href="regression.html#maximal-oxygen-uptake-in-young-boys"><span class="toc-section-number">13.3</span> Maximal oxygen uptake in young boys</a></li>
<li><a href="regression.html#mating-songs-in-crickets"><span class="toc-section-number">13.4</span> Mating songs in crickets</a></li>
<li><a href="regression.html#facebook-friends-and-grey-matter"><span class="toc-section-number">13.5</span> Facebook friends and grey matter</a></li>
<li><a href="regression.html#endogenous-nitrogen-excretion-in-carp"><span class="toc-section-number">13.6</span> Endogenous nitrogen excretion in carp</a></li>
<li><a href="regression.html#sparrowhawks"><span class="toc-section-number">13.7</span> Sparrowhawks</a></li>
<li><a href="regression.html#salaries-of-social-workers"><span class="toc-section-number">13.8</span> Salaries of social workers</a></li>
<li><a href="regression.html#predicting-volume-of-wood-in-pine-trees"><span class="toc-section-number">13.9</span> Predicting volume of wood in pine trees</a></li>
<li><a href="regression.html#mating-songs-in-crickets-1"><span class="toc-section-number">13.10</span> Mating songs in crickets</a></li>
</ul></li>
<li class="has-sub"><a href="dates-and-times.html#dates-and-times"><span class="toc-section-number">14</span> Dates and times</a><ul>
<li><a href="dates-and-times.html#dealing-with-dates-in-the-worcester-heart-attack-study"><span class="toc-section-number">14.1</span> Dealing with dates in the Worcester Heart Attack study</a></li>
<li><a href="dates-and-times.html#growth-of-mizuna-lettuce-seeds"><span class="toc-section-number">14.2</span> Growth of Mizuna lettuce seeds</a></li>
<li><a href="dates-and-times.html#types-of-childbirth"><span class="toc-section-number">14.3</span> Types of childbirth</a></li>
<li><a href="dates-and-times.html#wolves-and-caribou"><span class="toc-section-number">14.4</span> Wolves and caribou</a></li>
</ul></li>
<li class="has-sub"><a href="functions.html#functions"><span class="toc-section-number">15</span> Functions</a><ul>
<li><a href="functions.html#making-some-r-functions"><span class="toc-section-number">15.1</span> Making some R functions</a></li>
<li><a href="functions.html#the-collatz-sequence"><span class="toc-section-number">15.2</span> The Collatz sequence</a></li>
</ul></li>
</ul>
</div>
</div>
</div>
<div class="row">
<div class="col-sm-12">
<div id="two-sample-inference" class="section level1">
<h1><span class="header-section-number">Chapter 6</span> Two-sample inference</h1>
<div class="sourceCode" id="cb189"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb189-1" data-line-number="1"><span class="kw">library</span>(tidyverse)</a></code></pre></div>
<pre><code>## ── Attaching packages ────────────────────────────────── tidyverse 1.2.1 ──</code></pre>
<pre><code>## ✔ ggplot2 3.0.0     ✔ purrr   0.2.5
## ✔ tibble  1.4.2     ✔ dplyr   0.7.6
## ✔ tidyr   0.8.1     ✔ stringr 1.3.1
## ✔ readr   1.1.1     ✔ forcats 0.3.0</code></pre>
<pre><code>## ── Conflicts ───────────────────────────────────── tidyverse_conflicts() ──
## ✖ dplyr::filter() masks stats::filter()
## ✖ dplyr::lag()    masks stats::lag()</code></pre>
<div id="children-and-electronic-devices" class="section level2">
<h2><span class="header-section-number">6.1</span> Children and electronic devices</h2>
<p>Do children (aged 8–17) spend more time on electronic
devices now than they did 10 years ago? Samples of 15 children aged
8–17 were taken in each of two years, 1999 and 2009, and the children (with
their parents’ help) were
asked to keep a diary of the number of hours they spent using
electronic devices on a certain day. The data are in the file
<a href="http://www.utsc.utoronto.ca/~butler/c32/pluggedin.txt" class="uri">http://www.utsc.utoronto.ca/~butler/c32/pluggedin.txt</a>.</p>
<ol style="list-style-type: lower-alpha">
<li>Read in the data and verify that you have 30 rows of data from two
different years.</li>
</ol>
<p>Solution</p>
<p>I see this:</p>
<div class="sourceCode" id="cb193"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb193-1" data-line-number="1">myurl=<span class="st">&quot;http://www.utsc.utoronto.ca/~butler/c32/pluggedin.txt&quot;</span></a>
<a class="sourceLine" id="cb193-2" data-line-number="2">plugged=<span class="kw">read_delim</span>(myurl,<span class="st">&quot; &quot;</span>)</a></code></pre></div>
<pre><code>## Parsed with column specification:
## cols(
##   year = col_integer(),
##   hours = col_integer()
## )</code></pre>
<div class="sourceCode" id="cb195"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb195-1" data-line-number="1">plugged</a></code></pre></div>
<pre><code>## # A tibble: 30 x 2
##     year hours
##    &lt;int&gt; &lt;int&gt;
##  1  1999     4
##  2  1999     5
##  3  1999     7
##  4  1999     7
##  5  1999     5
##  6  1999     7
##  7  1999     5
##  8  1999     6
##  9  1999     5
## 10  1999     6
## # ... with 20 more rows</code></pre>
<p>I see only the first ten rows (with an indication that there are 20 more, so 30 altogether). In your notebook, it’ll look a bit different: again, you’ll see the first 10 rows, but you’ll see exactly how many rows and columns there are, and there will be buttons “Next” and “Previous” to see earlier and later rows, and a little right-arrow to see more columns to the right (to which is added a little left-arrow if there are previous columns to scroll back to). If you want to check for yourself that there are 30 rows, you can click Next a couple of times to get down to row 30, and then see that the Next button cannot be clicked again, and therefore that 30 rows is how many there are.</p>
<p>Or, you can summarize the years by counting how many there are
of each:</p>
<div class="sourceCode" id="cb197"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb197-1" data-line-number="1">plugged <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">count</span>(year)</a></code></pre></div>
<pre><code>## # A tibble: 2 x 2
##    year     n
##   &lt;int&gt; &lt;int&gt;
## 1  1999    15
## 2  2009    15</code></pre>
<p>or the more verbose form of the same thing:</p>
<div class="sourceCode" id="cb199"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb199-1" data-line-number="1">plugged <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">group_by</span>(year) <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">summarize</span>(<span class="dt">rows=</span><span class="kw">n</span>())</a></code></pre></div>
<pre><code>## # A tibble: 2 x 2
##    year  rows
##   &lt;int&gt; &lt;int&gt;
## 1  1999    15
## 2  2009    15</code></pre>
<p>Any of those says that it looks good. 30 rows, 1999 and 2009, 15
measurements for each.</p>
<ol start="2" style="list-style-type: lower-alpha">
<li>Draw side-by-side boxplots of the number of hours for each
year. <code>year</code> is a numeric variable that we want to treat as a
factor, so we need to <em>make</em> it into a factor.</li>
</ol>
<p>Solution</p>
<div class="sourceCode" id="cb201"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb201-1" data-line-number="1"><span class="kw">ggplot</span>(plugged,<span class="kw">aes</span>(<span class="dt">x=</span><span class="kw">factor</span>(year),<span class="dt">y=</span>hours))<span class="op">+</span><span class="kw">geom_boxplot</span>()</a></code></pre></div>
<p><img src="05-two-sample-inference_files/figure-html/unnamed-chunk-5-1.png" width="672"  /></p>
<p>The <code>fct_inorder</code> trick from assignment 1 will also work, since
the years are in the data in the order we want them to be displayed.</p>
<p>The median for 2009 is noticeably higher, and there is no skewness or
outliers worth worrying about.</p>
<p>The measurements for the two years have a very similar spread, so
there would be no problem running the pooled test here.</p>
<p>You might be bothered by the <code>factor(year)</code> on the <span class="math inline">\(x\)</span>-axis. To
get around that, you can define year-as-factor <em>first</em>, using
<code>mutate</code>, then feed your new column into the boxplot. That goes
like this. There is a wrinkle that I explain afterwards:</p>
<div class="sourceCode" id="cb202"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb202-1" data-line-number="1">plugged <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">mutate</span>(<span class="dt">the_year=</span><span class="kw">factor</span>(year)) <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb202-2" data-line-number="2"><span class="kw">ggplot</span>(<span class="kw">aes</span>(<span class="dt">x=</span>the_year, <span class="dt">y=</span>hours))<span class="op">+</span><span class="kw">geom_boxplot</span>()</a></code></pre></div>
<p><img src="05-two-sample-inference_files/figure-html/unnamed-chunk-6-1.png" width="672"  /></p>
<p>You could even redefine <code>year</code> to be the factor version of
itself (if you don’t need the year-as-number anywhere else). The
wrinkle I mentioned above is that in the <code>ggplot</code> you  name the data frame first; the data frame used is the
(nameless) data frame that came out of the previous step, not
<code>plugged</code> but <code>plugged</code> with a new column
<code>the_year</code>.</p>
<p>Note how the <span class="math inline">\(x\)</span>-axis now has the name of the new variable.</p>
<p>If you forget to make <code>year</code> into a factor, this happens:</p>
<div class="sourceCode" id="cb203"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb203-1" data-line-number="1"><span class="kw">ggplot</span>(plugged,<span class="kw">aes</span>(<span class="dt">x=</span>year,<span class="dt">y=</span>hours))<span class="op">+</span><span class="kw">geom_boxplot</span>()</a></code></pre></div>
<pre><code>## Warning: Continuous x aesthetic -- did you forget aes(group=...)?</code></pre>
<p><img src="05-two-sample-inference_files/figure-html/unnamed-chunk-7-1.png" width="672"  /></p>
<p>You get <em>one</em> boxplot, for all the hours, without distinguishing
by year, and a warning message that tries (and fails) to read our
mind: yes, we have a continuous, quantitative <code>x</code>, but
<code>geom_boxplot</code> doesn’t take a <code>group</code>.</p>
<ol start="3" style="list-style-type: lower-alpha">
<li>Test whether the mean number of hours has <em>increased</em> since</li>
</ol>
<ol start="1999" style="list-style-type: decimal">
<li>Which test did R do?</li>
</ol>
<p>Solution</p>
<p>The hard part to remember is how you specify a one-sided test in
R; it’s <code>alternative=&quot;less&quot;</code> (rather
than “greater”) because 1999 is “before” 2009:</p>
<div class="sourceCode" id="cb205"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb205-1" data-line-number="1"><span class="kw">t.test</span>(hours<span class="op">~</span>year,<span class="dt">data=</span>plugged,<span class="dt">alternative=</span><span class="st">&quot;less&quot;</span>)  </a></code></pre></div>
<pre><code>## 
##  Welch Two Sample t-test
## 
## data:  hours by year
## t = -3.3323, df = 24.861, p-value = 0.001348
## alternative hypothesis: true difference in means is less than 0
## 95 percent confidence interval:
##        -Inf -0.8121415
## sample estimates:
## mean in group 1999 mean in group 2009 
##           5.933333           7.600000</code></pre>
<p>The P-value is 0.0013. R does the Welch-Satterthwaite test by default
(the unequal-variances one). Since we didn’t change that, that’s what
we got. (The pooled test is below.)</p>
<p>This is the cleanest way to do it, because this version of
<code>t.test</code>, with a “model formula” (the thing with the
squiggle) allows a <code>data=</code> to say which data frame to get
things from. The other ways, using (for example) <code>with</code>, also work:</p>
<div class="sourceCode" id="cb207"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb207-1" data-line-number="1"><span class="kw">with</span>(plugged,<span class="kw">t.test</span>(hours<span class="op">~</span>year,<span class="dt">alternative=</span><span class="st">&quot;less&quot;</span>))</a></code></pre></div>
<pre><code>## 
##  Welch Two Sample t-test
## 
## data:  hours by year
## t = -3.3323, df = 24.861, p-value = 0.001348
## alternative hypothesis: true difference in means is less than 0
## 95 percent confidence interval:
##        -Inf -0.8121415
## sample estimates:
## mean in group 1999 mean in group 2009 
##           5.933333           7.600000</code></pre>
<p>This also works, but is <em>ugly</em>:</p>
<div class="sourceCode" id="cb209"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb209-1" data-line-number="1"><span class="kw">t.test</span>(plugged<span class="op">$</span>hours<span class="op">~</span>plugged<span class="op">$</span>year,<span class="dt">alternative=</span><span class="st">&quot;less&quot;</span>)</a></code></pre></div>
<pre><code>## 
##  Welch Two Sample t-test
## 
## data:  plugged$hours by plugged$year
## t = -3.3323, df = 24.861, p-value = 0.001348
## alternative hypothesis: true difference in means is less than 0
## 95 percent confidence interval:
##        -Inf -0.8121415
## sample estimates:
## mean in group 1999 mean in group 2009 
##           5.933333           7.600000</code></pre>
<p>Ugly because you’ve just typed the name of the data frame and the
dollar sign <em>twice</em> for no reason. As a general principle, if you
as a programmer are repeating yourself, you should stop and ask
yourself how you can avoid the repeat.</p>
<p>If you want the pooled test in R, you have to ask for it:</p>
<div class="sourceCode" id="cb211"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb211-1" data-line-number="1"><span class="kw">t.test</span>(hours<span class="op">~</span>year,<span class="dt">alternative=</span><span class="st">&quot;less&quot;</span>,<span class="dt">data=</span>plugged,<span class="dt">var.equal=</span>T)    </a></code></pre></div>
<pre><code>## 
##  Two Sample t-test
## 
## data:  hours by year
## t = -3.3323, df = 28, p-value = 0.001216
## alternative hypothesis: true difference in means is less than 0
## 95 percent confidence interval:
##        -Inf -0.8158312
## sample estimates:
## mean in group 1999 mean in group 2009 
##           5.933333           7.600000</code></pre>
<p>As is often the case, the P-values for the pooled and
Welch-Satterthwaite tests are very similar, so from that point of view
it doesn’t matter much which one you use. If you remember back to the
boxplots, the number of hours had about the same spread for the two
years, so if you used the pooled test instead of the
Welch-Satterthwaite test, that would have been just fine.</p>
<p>There is a school of thought that says we should learn the
Welch-Satterthwaite test and use that always. This is because W-S (i)
works when the populations from which the groups are sampled have
different SDs and (ii) is pretty good even when those SDs are the same.</p>
<p>The pooled test can go badly wrong if the groups have very different
SDs. The story is this: if the larger sample is from the population
with the larger SD, the probability of a type I error will be smaller
than <span class="math inline">\(\alpha\)</span>, and if the larger sample is from the population with
the <em>smaller</em> SD, the probability of a type I error will be
larger than <span class="math inline">\(\alpha\)</span>. This is why you see S-W in STAB22. You see the
pooled test in STAB57 because the logic of its derivation is so much
clearer,
<label for="tufte-mn-13" class="margin-toggle">⊕</label><input type="checkbox" id="tufte-mn-13" class="margin-toggle"><span class="marginnote">I return to this issue when we look at the same data in SAS later.</span>
not because it’s really the better test in
practice. The theory says that if your data are normal in both groups
with the same variance, then the pooled test is best, but it says
<em>nothing</em> about the quality of the pooled test if any of that
goes wrong.
The usual approach to assessing things like this is via simulation,
as we do for estimating power (later): generate some random data
eg. from normal distributions with the same means, SDs 10 and 20
and sample sizes 15 and 30, run the pooled <span class="math inline">\(t\)</span>-test, see if you
reject, then repeat lots of times and see whether you reject about
5% of the time. Then do the same thing again with the sample sizes
switched around. Or, do the same thing with Welch-Satterthwaite.</p>
<ol start="4" style="list-style-type: lower-alpha">
<li>Obtain a 99% confidence interval for the difference in means.</li>
</ol>
<p>Solution</p>
<p>Take off the thing that made it one-sided, and
put in a thing that gets the right CI:</p>
<div class="sourceCode" id="cb213"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb213-1" data-line-number="1"><span class="kw">t.test</span>(hours<span class="op">~</span>year,<span class="dt">data=</span>plugged,<span class="dt">conf.level=</span><span class="fl">0.99</span>)  </a></code></pre></div>
<pre><code>## 
##  Welch Two Sample t-test
## 
## data:  hours by year
## t = -3.3323, df = 24.861, p-value = 0.002696
## alternative hypothesis: true difference in means is not equal to 0
## 99 percent confidence interval:
##  -3.0614628 -0.2718705
## sample estimates:
## mean in group 1999 mean in group 2009 
##           5.933333           7.600000</code></pre>
<p><span class="math inline">\(-3.06\)</span> to <span class="math inline">\(-0.27\)</span>. The interval contains only negative values, which
is consistent with our having rejected a null hypothesis of no
difference in means.</p>
</div>
<div id="parking-close-to-the-curb" class="section level2">
<h2><span class="header-section-number">6.2</span> Parking close to the curb</h2>
<p>In 2009, the Toronto Star commissioned a survey to address
the issue of who is better at parking a car: men or women. The
researchers recorded 93 drivers who were parallel-parking their car in
downtown Toronto, and for each driver, recorded the distance between
the car and the curb, in inches, when the driver was finished parking
their car. The data are in an Excel spreadsheet,
<a href="http://www.utsc.utoronto.ca/~butler/c32/parking.xlsx" class="uri">http://www.utsc.utoronto.ca/~butler/c32/parking.xlsx</a>. (Let me
know if you cannot handle this format.) Click on the link. The data
will probably download automatically. Check the folder on your
computer where things get downloaded.
<label for="tufte-mn-14" class="margin-toggle">⊕</label><input type="checkbox" id="tufte-mn-14" class="margin-toggle"><span class="marginnote">Mine is rather prosaically called <em>Downloads</em>.</span>
If the spreadsheet is just
displayed and not downloaded, save it somewhere on your computer.</p>
<ol style="list-style-type: lower-alpha">
<li>There are two sheets in this spreadsheet workbook. They are
of the same data in two different formats. Take a look at Sheet 1
and Sheet 2. Describe the format of the data in each case. Which will be the most suitable data layout, bearing in
mind that one of the first things we do is to make side-by-side
boxplots of parking distances for males and females? Explain briefly.</li>
</ol>
<p>Solution</p>
<p>The data in Sheet 1 has one column of parking distances for
males, and another for females. This is often how you see data
of this sort laid out. Sheet 2 has <em>one</em> column of parking
distances, all combined together, and a second column indicating
the gender of the driver whose distance is in the first column.
If you look back at the kind of data we’ve used to make
side-by-side boxplots, it’s always been in the format of Sheet
2: one column containing all the values of the variable we’re
interested in, with a second column indicating which group each
observation belongs to (“group” here being
“gender of driver”).
So we need to use the data in Sheet 2, because the
data in Sheet 1 are not easy to handle with R.
The layout of Sheet 2 is the way R likes to do most things:
so-called “long format” with a lot of rows and not many
columns. This is true for descriptive stuff: side-by-side
boxplots or histograms or means by group, as well as modelling
such as (here) a two-sample <span class="math inline">\(t\)</span>-test, or (in other
circumstances, as with several groups) a one-way analysis of
variance.
Hadley Wickham, the guy behind the <code>tidyverse</code>, likes to
talk about “tidy data” (like Sheet 2), with each column
containing a variable, and “untidy data” (like Sheet 1), where
the two columns are the same thing (distances), but under
different circumstances (genders). As we’ll see later, it is
possible to convert from one format to the other. Usually you
want to make untidy data tidy (the function for this is called
<code>gather</code>).</p>
<ol start="2" style="list-style-type: lower-alpha">
<li>Read your preferred sheet directly into R, <em>without</em>
using a <code>.csv</code> file. (There is a clue in the lecture notes,
in the section about reading in files.) If you get stuck, make a
<code>.csv</code> file and read that in.</li>
</ol>
<p>Solution</p>
<p>The direct way is to use the package <code>readxl</code>. This has a
<code>read_excel</code> that works the same way as any of the other
<code>read_</code> functions. You’ll have to make sure that you
read in sheet 2, since that’s the one you want.
There is some setup first. There are a couple of ways you can do that:</p>
<ul>
<li><p>Download the spreadsheet to your computer, and upload it
to your project on R Studio Cloud (or, if you are running R
Studio on your computer, use something like
<code>file.choose</code> to get the file from wherever it got
downloaded to).</p></li>
<li><p>Use the function <code>download.file</code> to get the file
from the URL and store it in your project folder
directly. This also works in R Studio Cloud, and completely
by-passes the download-upload steps that you would have to do
otherwise. (I am grateful to Rose Gao for this idea.)
Here is how you can use <code>download.file</code> here:</p></li>
</ul>
<div class="sourceCode" id="cb215"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb215-1" data-line-number="1">my_url=<span class="st">&#39;http://www.utsc.utoronto.ca/~butler/c32/parking.xlsx&#39;</span></a>
<a class="sourceLine" id="cb215-2" data-line-number="2">local=<span class="st">&quot;parking.xlsx&quot;</span></a>
<a class="sourceLine" id="cb215-3" data-line-number="3"><span class="kw">download.file</span>(my_url, local, <span class="dt">mode=</span><span class="st">&quot;wb&quot;</span>)</a></code></pre></div>
<p>When you’ve gotten the spreadsheet into your project folder via one of
those two ways, you go ahead and do this:</p>
<div class="sourceCode" id="cb216"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb216-1" data-line-number="1"><span class="kw">library</span>(readxl)</a>
<a class="sourceLine" id="cb216-2" data-line-number="2">parking=<span class="kw">read_excel</span>(<span class="st">&quot;parking.xlsx&quot;</span>,<span class="dt">sheet=</span><span class="dv">2</span>)</a>
<a class="sourceLine" id="cb216-3" data-line-number="3">parking</a></code></pre></div>
<pre><code>## # A tibble: 93 x 2
##    distance gender
##       &lt;dbl&gt; &lt;chr&gt; 
##  1      0.5 male  
##  2      1   male  
##  3      1.5 male  
##  4      1.5 male  
##  5      1.5 male  
##  6      3   male  
##  7      3.5 male  
##  8      5   male  
##  9      6   male  
## 10      6   male  
## # ... with 83 more rows</code></pre>
<p>You have to do it this way, using the version of the spreadsheet on
your computer, since <code>read_excel</code> won’t take a
URL, or if it does, I can’t make it work.
<label for="tufte-mn-15" class="margin-toggle">⊕</label><input type="checkbox" id="tufte-mn-15" class="margin-toggle"><span class="marginnote">Let me know if you have more success than I did.</span>
I put the spreadsheet in R Studio’s
current folder, so I could read it in by name, or you can do the
<code>f=file.choose()</code> thing, find it, then read it in.
The <code>sheet=</code> thing can take either a number (as here: the
second sheet in the workbook), or a name (whatever name the sheet has
on its tab in the workbook).</p>
<p>Extra: Rose actually came up with a better idea, which I will show
you and explain:</p>
<div class="sourceCode" id="cb218"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb218-1" data-line-number="1">tf=<span class="kw">tempfile</span>()</a>
<a class="sourceLine" id="cb218-2" data-line-number="2"><span class="kw">download.file</span>(my_url, tf, <span class="dt">mode=</span><span class="st">&quot;wb&quot;</span>)</a>
<a class="sourceLine" id="cb218-3" data-line-number="3">p=<span class="kw">read_excel</span>(tf, <span class="dt">sheet =</span> <span class="dv">2</span>)</a></code></pre></div>
<p>What <code>tempfile()</code> does is to create a temporary file to hold the
spreadsheet that you are about to download. After downloading the
spreadsheet to the temporary file, you then use <code>read_excel</code> to
read <em>from the temporary file</em> into the data frame.</p>
<p>The advantage of this approach is that the temporary file disappears
as soon as you close R, and so you don’t have a copy of the
spreadsheet lying around that you don’t need (once you have created
the data frame that I called <code>parking</code>, anyway).</p>
<p>If you are wondering about that <code>mode</code> thing on
<code>download.file</code>: files are of two different types, “text”
(like the text of an email, that you can open and look at in something
like Notepad), and “binary” that you can’t look at directly, but for
which you need special software like Word or Excel to decode it for
you.
<label for="tufte-mn-16" class="margin-toggle">⊕</label><input type="checkbox" id="tufte-mn-16" class="margin-toggle"><span class="marginnote">A Word or Excel document has all kinds of formatting information hidden in the file as well as the text that you see on the screen.</span><br />
The first character in  is either
<code>w</code> for “write a new file”, which is what we want here, or
<code>a</code> for “append”, which would mean adding to the end of a
file that already exists. Thus <code>mode=&quot;wb&quot;</code> means
“create a new binary file”.
End of Extra.
If you can’t make any of this work, then do it in two steps:
save the appropriate sheet as a <code>.csv</code>
file, and then read the <code>.csv</code> file using
<code>read_csv</code>. If you experiment, you’ll find that saving a
spreadsheet workbook as <code>.csv</code> only saves the sheet
you’re looking at, so make sure you are looking at sheet 2
before you Save As <code>.csv</code>. I did that, and called my
saved <code>.csv</code> <code>parking2.csv</code> (because it was from
sheet 2, but you can use any name you like).
Then I read this into R thus:</p>
<div class="sourceCode" id="cb219"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb219-1" data-line-number="1">parking2=<span class="kw">read_csv</span>(<span class="st">&quot;parking2.csv&quot;</span>)</a></code></pre></div>
<pre><code>## Parsed with column specification:
## cols(
##   distance = col_double(),
##   gender = col_character()
## )</code></pre>
<div class="sourceCode" id="cb221"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb221-1" data-line-number="1">parking2</a></code></pre></div>
<pre><code>## # A tibble: 93 x 2
##    distance gender
##       &lt;dbl&gt; &lt;chr&gt; 
##  1      0.5 male  
##  2      1   male  
##  3      1.5 male  
##  4      1.5 male  
##  5      1.5 male  
##  6      3   male  
##  7      3.5 male  
##  8      5   male  
##  9      6   male  
## 10      6   male  
## # ... with 83 more rows</code></pre>
<p>The read-in data frame <code>parking</code>
has 93 rows (<span class="math inline">\(47+46=93\)</span> drivers) and two columns: the distance from
the curb that the driver ended up at, and the gender of the
driver. This is as the spreadsheet Sheet 2 was, and the first few
distances match the ones in the spreadsheet.</p>
<p>If I were grading this, you’d get some credit for the <code>.csv</code>
route, but I really wanted you to figure out how to read the Excel
spreadsheet directly, so that’s what would be worth full marks.</p>
<p>You might want to check that you have some males and some females, and
how many of each, which you could do this way:</p>
<div class="sourceCode" id="cb223"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb223-1" data-line-number="1">parking <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">count</span>(gender)</a></code></pre></div>
<pre><code>## # A tibble: 2 x 2
##   gender     n
##   &lt;chr&gt;  &lt;int&gt;
## 1 female    47
## 2 male      46</code></pre>
<ol start="3" style="list-style-type: lower-alpha">
<li>Obtain side-by-side boxplots of parking distances for
males and females. Does one
gender seem to be better at parking than the other? Explain briefly.</li>
</ol>
<p>Solution</p>
<p>With the right data set, this is a piece of cake:</p>
<div class="sourceCode" id="cb225"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb225-1" data-line-number="1"><span class="kw">ggplot</span>(parking,<span class="kw">aes</span>(<span class="dt">x=</span>gender,<span class="dt">y=</span>distance))<span class="op">+</span><span class="kw">geom_boxplot</span>()</a></code></pre></div>
<p><img src="05-two-sample-inference_files/figure-html/unnamed-chunk-18-1.png" width="672"  /></p>
<p>The outcome variable is distance from the curb, so smaller should be
better (more accurate parking). With that in mind, the median for
females is a little smaller than for males (about 8.5 vs. about 10),
so it seems that on average females are more accurate parkers than
males are. The difference is small, however (and so you might be
wondering at this point whether it’s a statistically significant
difference — don’t worry, that’s coming up).</p>
<p>Before I leave this one, I want to show you something else:
above-and-below histograms, as another way of comparing males and
females (two or more groups, in general). First, we make a histogram of all
the distances, without distinguishing by gender:</p>
<div class="sourceCode" id="cb226"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb226-1" data-line-number="1"><span class="kw">ggplot</span>(parking,<span class="kw">aes</span>(<span class="dt">x=</span>distance))<span class="op">+</span><span class="kw">geom_histogram</span>(<span class="dt">bins=</span><span class="dv">8</span>)</a></code></pre></div>
<p><img src="05-two-sample-inference_files/figure-html/unnamed-chunk-19-1.png" width="672"  /></p>
<p>That big outlier is the very inaccurate male driver.</p>
<p>Now, how do we get a <em>separate</em> histogram for each
<code>gender</code>? In <code>ggplot</code>, separate plots for each
“something” are called <strong>facets</strong>, and the way to get facets
arranged as you want them is called <code>facet_grid</code>. Let me show you
the code first, and then explain how it works:</p>
<div class="sourceCode" id="cb227"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb227-1" data-line-number="1"><span class="kw">ggplot</span>(parking,<span class="kw">aes</span>(<span class="dt">x=</span>distance))<span class="op">+</span></a>
<a class="sourceLine" id="cb227-2" data-line-number="2"><span class="kw">geom_histogram</span>(<span class="dt">bins=</span><span class="dv">7</span>)<span class="op">+</span></a>
<a class="sourceLine" id="cb227-3" data-line-number="3"><span class="kw">facet_grid</span>(gender<span class="op">~</span>.)</a></code></pre></div>
<p><img src="05-two-sample-inference_files/figure-html/unnamed-chunk-20-1.png" width="672"  /></p>
<p><code>facet_grid</code> takes a “model formula” with a squiggle, with <span class="math inline">\(y\)</span>
on the left and <span class="math inline">\(x\)</span> on the right. We want to compare our two
histograms, one for males and one for females, and I think the best
way to compare histograms is to have one on top of the other. Note
that the same <code>distance</code> scale is used for both histograms, so
that it is a fair comparison. The above-and-below is accomplished by
having <code>gender</code> as the <span class="math inline">\(y\)</span> in the arrangement of the facets, so
it goes before the squiggle. We don’t have any <span class="math inline">\(x\)</span> in the arrangement
of the facets, and we tell <code>ggplot</code> this by putting a dot where
the <span class="math inline">\(x\)</span> would be.
<label for="tufte-mn-17" class="margin-toggle">⊕</label><input type="checkbox" id="tufte-mn-17" class="margin-toggle"><span class="marginnote">You might have a second categorical variable by which you want to arrange the facets left and right, and that would go where the dot is.</span></p>
<p>You can also use <code>facet_wrap</code> for this, but you have to be
more careful since you don’t have any control over how the histograms
come out (you probably get them side by side, which is not so helpful
for comparing distributions). You can make it work by using
<code>ncol=1</code> to arrange “all” the histograms in one column:</p>
<div class="sourceCode" id="cb228"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb228-1" data-line-number="1"><span class="kw">ggplot</span>(parking,<span class="kw">aes</span>(<span class="dt">x=</span>distance))<span class="op">+</span></a>
<a class="sourceLine" id="cb228-2" data-line-number="2"><span class="kw">geom_histogram</span>(<span class="dt">bins=</span><span class="dv">7</span>)<span class="op">+</span></a>
<a class="sourceLine" id="cb228-3" data-line-number="3"><span class="kw">facet_wrap</span>(<span class="op">~</span>gender,<span class="dt">ncol=</span><span class="dv">1</span>)</a></code></pre></div>
<p><img src="05-two-sample-inference_files/figure-html/unnamed-chunk-21-1.png" width="672"  /></p>
<p>The centres of both histograms are somewhere around 10, so it’s hard
to see any real difference between males and females here. Maybe this
is further evidence that the small difference we saw between the
boxplots is really not worth getting excited about.</p>
<p>You might be concerned about how you know what to put with the
squiggle-thing in <code>facet_grid</code> and <code>facet_wrap</code>. The
answer is that <code>facet_wrap</code> <em>only</em> has something to the
right of the squiggle (which <code>ggplot</code> then decides how to
arrange), but <code>facet_grid</code> <em>must</em> have something on
<em>both</em> sides of the squiggle (how to arrange in the <span class="math inline">\(y\)</span> direction
on the left, how to arrange in the <span class="math inline">\(x\)</span> direction on the right), and if
you don’t have anything else to put there, you put a dot. Here’s my
<code>facet_grid</code> code from above, again:</p>
<div class="sourceCode" id="cb229"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb229-1" data-line-number="1"><span class="kw">ggplot</span>(parking,<span class="kw">aes</span>(<span class="dt">x=</span>distance))<span class="op">+</span></a>
<a class="sourceLine" id="cb229-2" data-line-number="2"><span class="kw">geom_histogram</span>(<span class="dt">bins=</span><span class="dv">7</span>)<span class="op">+</span></a>
<a class="sourceLine" id="cb229-3" data-line-number="3"><span class="kw">facet_grid</span>(gender<span class="op">~</span>.)</a></code></pre></div>
<p>We wanted gender to go up and down, and we had nothing to go left and
right, hence the dot. Contrast that with my <code>facet_wrap</code>
code:
<label for="tufte-mn-18" class="margin-toggle">⊕</label><input type="checkbox" id="tufte-mn-18" class="margin-toggle"><span class="marginnote">I took out the <em>ncol</em> since that confuses the explanation here.</span></p>
<div class="sourceCode" id="cb230"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb230-1" data-line-number="1"><span class="kw">ggplot</span>(parking,<span class="kw">aes</span>(<span class="dt">x=</span>distance))<span class="op">+</span></a>
<a class="sourceLine" id="cb230-2" data-line-number="2"><span class="kw">geom_histogram</span>(<span class="dt">bins=</span><span class="dv">7</span>)<span class="op">+</span></a>
<a class="sourceLine" id="cb230-3" data-line-number="3"><span class="kw">facet_wrap</span>(<span class="op">~</span>gender)</a></code></pre></div>
<p>This says “make a separate facet for each gender”, but it doesn’t
say anything about how to arrange them.
The choice of bins for my histogram(s) came from Sturges’ rule: with
<span class="math inline">\(n\)</span> being the number of observations, you use <span class="math inline">\(k\)</span> bins where
<span class="math inline">\(k=\log_2(n)+1\)</span>, rounded up. If we were to make a histogram of all the
parking distances combined together, we would have <span class="math inline">\(n=47+48=95\)</span>
observations, so we should use this many bins:</p>
<div class="sourceCode" id="cb231"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb231-1" data-line-number="1">sturges=<span class="kw">log</span>(<span class="dv">95</span>,<span class="dv">2</span>)<span class="op">+</span><span class="dv">1</span></a>
<a class="sourceLine" id="cb231-2" data-line-number="2">sturges</a></code></pre></div>
<pre><code>## [1] 7.569856</code></pre>
<p>Round this up to 8. (The second thing in <code>log</code> is the base of
the logs, if you specify it, otherwise it defaults to <span class="math inline">\(e\)</span> and gives
you “natural” logs.) I seem to have the powers of 2 in my head, so I
can do it mentally by saying “the next power of 2 is 128, which is <span class="math inline">\(2^7\)</span>, so I need <span class="math inline">\(7+1=8\)</span> bins.”</p>
<p>Or:</p>
<div class="sourceCode" id="cb233"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb233-1" data-line-number="1"><span class="kw">with</span>(parking,<span class="kw">nclass.Sturges</span>(distance))</a></code></pre></div>
<pre><code>## [1] 8</code></pre>
<p>Sturges’ rule tends to produce not enough bins if <span class="math inline">\(n\)</span> is small, so be
prepared to increase it a bit if you don’t have much data.
I think that gives a fairly bare-bones picture of the shape: skewed to
the right with outlier.</p>
<p>The other rule we saw was Freedman-Diaconis:</p>
<div class="sourceCode" id="cb235"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb235-1" data-line-number="1"><span class="kw">with</span>(parking, <span class="kw">nclass.FD</span>(distance))</a></code></pre></div>
<pre><code>## [1] 14</code></pre>
<p>and that leads to this histogram:</p>
<div class="sourceCode" id="cb237"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb237-1" data-line-number="1"><span class="kw">ggplot</span>(parking,<span class="kw">aes</span>(<span class="dt">x=</span>distance))<span class="op">+</span><span class="kw">geom_histogram</span>(<span class="dt">bins=</span><span class="dv">14</span>)</a></code></pre></div>
<p><img src="05-two-sample-inference_files/figure-html/unnamed-chunk-27-1.png" width="672"  /></p>
<p>That gives rather more detail (a lot more bars: the binwidth in the
Sturges-rule histogram is about 7, or twice what you see here), but in
this case the overall story is about the same.</p>
<p>In the case of faceted histograms, you would want to apply a rule that
uses the number of observations in <em>each</em> histogram. The facets
might have quite different numbers of observations, but you can only
use one <code>binwidth</code> (or <code>bins</code>), so you may have to
compromise. For example, using Sturges’ rule based on 47 observations
(the number of males; the number of females is one more):</p>
<div class="sourceCode" id="cb238"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb238-1" data-line-number="1"><span class="kw">log</span>(<span class="dv">47</span>,<span class="dv">2</span>)<span class="op">+</span><span class="dv">1</span></a></code></pre></div>
<pre><code>## [1] 6.554589</code></pre>
<p>and so each facet should have that many bins, rounded up. That’s where
I got my 7 for the facetted histogram from. This one doesn’t work
immediately with <code>nclass.Sturges</code>, because we do not have
<em>one</em> column whose length is the number of observations we want:
we have one column of distances that are males and females mixed
up. To do <em>that</em>, <code>filter</code> one of the genders first:</p>
<div class="sourceCode" id="cb240"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb240-1" data-line-number="1">parking <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb240-2" data-line-number="2"><span class="kw">filter</span>(gender<span class="op">==</span><span class="st">&quot;female&quot;</span>) <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb240-3" data-line-number="3"><span class="kw">with</span>(.,<span class="kw">nclass.Sturges</span>(distance))</a></code></pre></div>
<pre><code>## [1] 7</code></pre>
<p>I used the “dot” trick again, which you can read as “it”: “from <code>parking</code>, take only the rows for the females, and with it, give me the number of bins for a histogram by Sturges’ rule.”</p>
<ol start="4" style="list-style-type: lower-alpha">
<li>Explain briefly why this is two independent samples
rather than matched pairs.</li>
</ol>
<p>Solution</p>
<p>There is no way to pair any male with a corresponding female,
because they are unrelated people. You might also notice that
there are not even the <em>same number</em> of males and females,
so there can be no way of pairing them up without leaving one
over. (In general, if the two samples are paired, there must be
the same number of observations in each; if there are different
numbers in each, as here, they cannot be paired.)
If you want that more mathematically, let <span class="math inline">\(n_1\)</span> and <span class="math inline">\(n_2\)</span> be the
two sample sizes; then:
<span class="math display">\[
\mbox{Paired} \Longrightarrow n_1=n_2
\]</span></p>
<p>from which it follows logically (the “contrapositive”) that</p>
<p><span class="math display">\[
n_1 \ne n_2 \Longrightarrow \mbox{not paired}
\]</span>
You’ll note from the logic that if the two sample sizes are the same,
that tells you <em>nothing</em> about whether it’s paired or independent
samples: it could be either, and in that case you have to look at the
description of the data to decide between them.</p>
<p>Here, anything that gets at why the males and females cannot be paired
up is good.</p>
<ol start="5" style="list-style-type: lower-alpha">
<li>Run a suitable <span class="math inline">\(t\)</span>-test for comparing parking distances
for males and females. What do you conclude, in the context of the data?</li>
</ol>
<p>Solution</p>
<p>A two-sample <span class="math inline">\(t\)</span>-test. I think either the Welch or the pooled one can
be justified (and I would expect them to give similar answers). You
can do the Welch one either without comment or by asserting that the
boxplots show different spreads; if you are going to do the pooled
one, you need to say that the spreads are “about equal”, by
comparing the heights of the boxes on the boxplots:</p>
<div class="sourceCode" id="cb242"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb242-1" data-line-number="1"><span class="kw">t.test</span>(distance<span class="op">~</span>gender,<span class="dt">data=</span>parking)</a></code></pre></div>
<pre><code>## 
##  Welch Two Sample t-test
## 
## data:  distance by gender
## t = -1.3238, df = 79.446, p-value = 0.1894
## alternative hypothesis: true difference in means is not equal to 0
## 95 percent confidence interval:
##  -4.5884103  0.9228228
## sample estimates:
## mean in group female   mean in group male 
##             9.308511            11.141304</code></pre>
<p>This is the Welch-Satterthwaite version of the test, the one that does
not assume equal SDs in the two groups. The P-value of 0.1894 is not
small, so there is no evidence of any difference in parking accuracy
between males and females.</p>
<p>Or, this being the pooled one:</p>
<div class="sourceCode" id="cb244"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb244-1" data-line-number="1"><span class="kw">t.test</span>(distance<span class="op">~</span>gender,<span class="dt">data=</span>parking,<span class="dt">var.equal=</span>T)</a></code></pre></div>
<pre><code>## 
##  Two Sample t-test
## 
## data:  distance by gender
## t = -1.329, df = 91, p-value = 0.1872
## alternative hypothesis: true difference in means is not equal to 0
## 95 percent confidence interval:
##  -4.5722381  0.9066506
## sample estimates:
## mean in group female   mean in group male 
##             9.308511            11.141304</code></pre>
<p>You might have thought, looking at the boxplots, that the groups had
about the same SD (based, for example, on noting that the two boxes
were about the same height, so the IQRs were about the same). In that
case, you might run a pooled <span class="math inline">\(t\)</span>-test, which here gives an almost
identical P-value of 0.1872, and the exact same conclusion.</p>
<ol start="6" style="list-style-type: lower-alpha">
<li>Why might you have some doubts about the <span class="math inline">\(t\)</span>-test that
you just did? Explain briefly.</li>
</ol>
<p>Solution</p>
<p>The two-sample <span class="math inline">\(t\)</span>-test is based on an assumption of
normally-distributed data within each group. If you go back
and look at the boxplots, you’ll see either (depending on
your point of view) that both groups are right-skewed, or
that both groups have outliers, neither of which fits a
normal distribution. The outlier in the male group is
particularly egregious.
<label for="tufte-mn-19" class="margin-toggle">⊕</label><input type="checkbox" id="tufte-mn-19" class="margin-toggle"><span class="marginnote">Google defines this as meaning <em>outstandingly bad, shocking</em>.</span> So I think we
are entitled to question whether a two-sample <span class="math inline">\(t\)</span>-test is
the right thing to do.
Having said that, we should go back and remember that the
<span class="math inline">\(t\)</span>-tests are “robust to departures from normality” (since
we are working with the Central Limit Theorem here), and
therefore that this test might be quite good even though the
data are not normal, because the sample sizes of 40-plus are
large (by the standards of what typically makes the Central
Limit Theorem work for us). So it may not be as bad as it seems.
A common competitor for the two-sample <span class="math inline">\(t\)</span>-test is the
Mann-Whitney test. This doesn’t assume normality, but it
<em>does</em> assume symmetric distributions, which it’s not
clear that we have here. I like a test called Mood’s Median
Test, which is kind of the two-sample equivalent of the sign
test (which we will also see later). It goes like this:
Work out the overall median of all the distances, regardless
of gender:</p>
<div class="sourceCode" id="cb246"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb246-1" data-line-number="1">parking <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">summarize</span>(<span class="dt">med=</span><span class="kw">median</span>(distance))</a></code></pre></div>
<pre><code>## # A tibble: 1 x 1
##     med
##   &lt;dbl&gt;
## 1     9</code></pre>
<p>The overall median is 9.</p>
<p>Count up how many distances of each gender were above or below the
overall median. (Strictly, I’m supposed to throw away any values that
are exactly equal to the overall median, but I won’t here for clarity
of exposition.)</p>
<div class="sourceCode" id="cb248"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb248-1" data-line-number="1">tab=<span class="kw">with</span>(parking,<span class="kw">table</span>(gender,distance<span class="op">&lt;</span><span class="dv">9</span>))</a>
<a class="sourceLine" id="cb248-2" data-line-number="2">tab</a></code></pre></div>
<pre><code>##         
## gender   FALSE TRUE
##   female    23   24
##   male      27   19</code></pre>
<p>For example, 19 of the male drivers had a distance (strictly) less than 9.
Both genders are pretty close to 50–50 above and below the overall
median, which suggests that the males and females have about the same
median. This can be tested (it’s a chi-squared test for independence,
if you know that):</p>
<div class="sourceCode" id="cb250"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb250-1" data-line-number="1"><span class="kw">chisq.test</span>(tab,<span class="dt">correct=</span>F)</a></code></pre></div>
<pre><code>## 
##  Pearson&#39;s Chi-squared test
## 
## data:  tab
## X-squared = 0.89075, df = 1, p-value = 0.3453</code></pre>
<p>This is even less significant (P-value 0.3453) than the two-sample
<span class="math inline">\(t\)</span>-test, and so is consistent with our conclusion from before that
there is actually no difference between males and females in terms of
average parking distance. The Mood’s median test is believable because
it is not affected by outliers or distribution shape.</p>
<ol start="7" style="list-style-type: lower-alpha">
<li>The Toronto Star in its report said that females are
more accurate at parking their cars. Why do you think they
concluded that, and do you think they were right to do so?
Explain briefly.</li>
</ol>
<p>Solution</p>
<p>The conclusion from the boxplots was that the female
median distance was less than the males, slightly, in this
sample. That is probably what the Star seized on.
Were they right? Well, that was why we did the test of
significance. We were trying to see whether this observed
difference between males and females was “real” (would
hold up if you looked at “all” male and female drivers)
or “reproducible” (you would expect to see it again if
you did another study like this one). The large,
non-significant P-values in all our tests tell us that the
difference observed here was nothing more than chance. So
it was not reasonable to conclude that females generally
are more accurate at parallel-parking than males are.</p>

</div>
</div>
<p style="text-align: center;">
<a href="one-sample-inference.html"><button class="btn btn-default">Previous</button></a>
<a href="power-and-sample-size.html"><button class="btn btn-default">Next</button></a>
</p>
</div>
</div>



</body>
</html>
